### ISSUE TITLE
Lawnfeed update notice causing crash

### ISSUE THREAD

**Issue by heArt-coder** [Deletescape-Media/Lawnchair#1000]
Right after lawnchair update installed i got update notification about lawnfeed. Clicking on it made lawnfeed crash and notification popped back up and same goes again like 4-5 times until lawnchair crashes.

Uninstalled lawnfeed and no more notifications about lawnfeed. 

## Environment

* Device: Htc e8 single sim europe
* Android version: 6.0.1
* Launcher version: 1.1.0.1742
* Rom: Stock Rom

**Comment by divadsn** [comment]
Logcat or it never happened
