### ISSUE TITLE
Bad German text

### ISSUE THREAD

**Issue by honsberg** [Deletescape-Media/Lawnchair#1001]
![screenshot_20171210-170212](https://user-images.githubusercontent.com/12712721/33806890-bf37b2de-ddce-11e7-89ab-ee488f6f07fa.png)

The Text "icon Beschriftungen auf dem Startbildschirm.." means the wrong. Because if it is on You diaable the "Icon Beschriftungen"

Better Text: "keine Icon Beschriftungen auf dem Startbildschirm"

**Comment by divadsn** [comment]
Translation issues are to be reported on [Crowdin](http://translate.lawnchair.info).

**Comment by honsberg** [comment]
Done
