### ISSUE TITLE
Inconsistent Navbars 

### ISSUE THREAD

**Issue by sawankumar** [Deletescape-Media/Lawnchair#1002]
![screenshot_20171211-091923](https://user-images.githubusercontent.com/33548019/33815205-b195cf76-de55-11e7-9add-df57b86b352c.png)
![screenshot_20171211-091930](https://user-images.githubusercontent.com/33548019/33815221-c1d16436-de55-11e7-9744-d359ccd63690.png)

**Comment by LinuxLlama** [comment]
This seems like a ROM problem...

**Comment by sawankumar** [comment]
Well this looks like a theme issue or ROM side issue ....
