### ISSUE TITLE
Weird issue: White glare (like light bleed) on black wallpapers

### ISSUE THREAD

**Issue by baruchin** [Deletescape-Media/Lawnchair#101]
This one is weird. When using Lawnchair there's a subtle white glare on the top of the screen (similar to light bleed on defective LCD panels), noticeable on black wallpapers. It's not my phone, because this doesn't happen using the same wallpaper on the stock Google Now launcher. I'm using Moto Z force (OLED display).

**Comment by fonix232** [comment]
The same happens with all Launcher3 derivatives in my experience. Will see if it is intentional or an actual bug.

**Comment by jlnstrk** [comment]
It is intentional. It's probably meant to improve contrast to the status bar icons, as it's dark on light wallpapers. The fact that it's existent & light on dark wallpapers is probably just not thought through.
It's especially annoying on amoled displays, so I'm hoping for a quick fix

**Comment by jlnstrk** [comment]
@deletescape any updates on this? I know this is an AOSP launcher/Pixel launcher issue in general, still it's annoying & keeping me from using Lawnchair (GNow launcher doesn't have it). It needs to be fixed as it makes for a seriously bad UX when using black wallpapers on amoled devices (and there are quite a lot of amoled devices nowadays).
-> https://photos.app.goo.gl/7g3qFA7LfjDGNWLC3
