### ISSUE TITLE
Wallpaper does not center 

### ISSUE THREAD

**Issue by ahoneybun** [Deletescape-Media/Lawnchair#102]
I believe launchers call this "scrolling wallpaper" or something like that.

Lawnchair:
![img_20170630_011536_322](https://user-images.githubusercontent.com/4884946/27721892-bccdafe4-5d31-11e7-849a-f49369637119.jpg)

Action Launcher:
![screenshot_20170630-011741](https://user-images.githubusercontent.com/4884946/27721935-061363ce-5d32-11e7-807e-ce93409e3a3c.png)

**Comment by ahoneybun** [comment]
@fonix232 it seems to be an issue with Google Now Launcher/Launcher3 in general. It's fixed if you set the wallpaper with the Long press on the homescreen and select it from there. The issue came from using Backdrops and just pressing Set rather then long pressing Set and letting the launcher handle it.

**Comment by intelligentcasanova** [comment]
I believe this has been fixed in: https://github.com/Deletescape-Media/Lawnchair/commit/511f1fc06f8110d8e72123082cc057402f74b9ed.
