### ISSUE TITLE
Sorry for the spam / Why interactions with this repository are locked.

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Lawnchair#1024]
Hi everyone,

mostly all the watchers which have probably just gotten a huge amount of spam emails. Unfortunately a user (@SpamMaster, a burner account) decided that it would be a great idea to show that he dislikes lawnchair by spamming our issues and pull requests with untrue accusations. The user was blocked from any interactions in the @Deletescape-media org, but to prevent him from creating new accounts to spam here we have disabled interactions for everyone for the next 24 hours.

For any questions or bug reports, @divadsn will be happy to answer those via e-mail at projects@codebucket.de

We're terribly sorry for this and will try to prevent anything like this in the future.

Kind Regards
The Lawnchair Developer Team

(If you have any comments on this or want to submit some informations about the identity of @SpamMaster, feel free to drop me an E-Mail at deletescape@gmail.com)

**Comment by nyancrimew** [comment]
EDIT 1: Added E-Mail as contact option

**Comment by divadsn** [comment]
Also, feel free to report him to GitHub using the link below:
https://github.com/contact/report-abuse

**Comment by divadsn** [comment]
For any questions or bug reports, you can send them to me via E-mail at projects@codebucket.de, thanks :)

**Comment by divadsn** [comment]
Alright, we've now locked interactions for new user accounts, anyone else should be able to create issues and write comments :)
