### ISSUE TITLE
app shortcuts disappearing after reboot (restart?)

### ISSUE THREAD

**Issue by kr428** [Deletescape-Media/Lawnchair#1027]
## Description

When installing Lawnchair Launcher off Google Play or github apk, I use to have app-specific shortcuts in the long-press menu (such as "my apps" while long-pressing Google Play). After rebooting or at times just restarting the launcher, they seem all gone; by then long-pressing an app icon just displays "edit" / "widgets" / "info" as with applications that don't support app shortcuts.

## Expected Behavior

Application specific shortcuts should always be available using long-press on the corresponding icon.

## Actual Behavior

Application specific shortcuts are gone after random events (reproducibly after rebooting the device).

## Steps to Reproduce

1. Install Lawnchair Launcher.
2. Long-press "Play" icon on the start screen, see "my apps" there.
3. Reboot device.
4. Long-press "Play" icon on the start screen again, "my apps" is gone.

## Environment

* Device: Moto G 2015 (osprey)
* Android version: 7.1.2 
* Launcher version: 1.1.0.1742
* Rom: AOSP Extended

**Comment by divadsn** [comment]
Could you please make a video so we can reproduce it 1:1? And a Logcat would be nice too, thanks.

**Comment by kr428** [comment]
Have to rewrite this: It doesn't seem related to restarting anything - it just appeared all along the way. I can *reproducibly* trigger this behaviour by configuring dock or app drawer setting ("blur" or "transparent"), see screens. I'll try to get hold of a Logcat output too as soon as possible.

![screenshot_20171213-065216](https://user-images.githubusercontent.com/685879/33927604-3208538e-dfe3-11e7-81df-3bd44d689d96.png)
![screenshot_20171213-084948](https://user-images.githubusercontent.com/685879/33927605-3226b018-dfe3-11e7-8b42-573575547b2b.png)
