### ISSUE TITLE
Add the ability to scroll the wallpaper or add an empty page.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1028]
As title says, I think it would be nice, since wallpapers look gorgeous on phones these days.

Thanks!

**Comment by guest4711** [comment]
Use Transparent Widget (Create transparent widgets) for it - https://f-droid.org/app/com.easwareapps.transparentwidget

**Comment by ghost** [comment]
@guest4711, that's a workaround, a native solution would be better.

**Comment by guest4711** [comment]
Following the KISS approach it is better to have a set of well tested simple tools which we could put together than one big app which is not easy to understand and hard to maintain. Whole UNIX is based on simple and small programms like grep, cat, sort, tail, cut, sed, sh, echo, test.

**Comment by ghost** [comment]
Nova Launcher can do it without hiccups, why would it be so hard to implement it to Lawnchar?

**Comment by divadsn** [comment]
@Ufeldraku everyone is busy maybe?

**Comment by divadsn** [comment]
@Ufeldraku also, we are not paid for our work unlike Nova.

**Comment by ghost** [comment]
I'd pay tho

**Comment by anirudhgupta109** [comment]
@Ufeldraku Why not donate for what already exists, that'll help run the project:
https://play.google.com/store/apps/details?id=ch.deletescape.donut

(Not saying that donating means you'll get the feature)

**Comment by ghost** [comment]
I didn't see it. I will donate.
