### ISSUE TITLE
(bug?) Missing translations

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#1030]
After you remade the strings, some translations are still missing though they are already been translated.
![](https://i.imgur.com/N8MXXJT.png)
![](https://i.imgur.com/l3hCDeQ.png)
![](https://i.imgur.com/5Y8Hcpc.png)
![](https://i.imgur.com/UEMggwV.png)

**Comment by divadsn** [comment]
Fix them or upvote those translations on translate.lawnchair.info, thanks.
