### ISSUE TITLE
The strings for the easter egg/hidden menu in debugging options aren't translatable

### ISSUE THREAD

**Issue by FacuM** [Deletescape-Media/Lawnchair#1035]
## Description
The strings for the easter egg found when you press in the "Debug" menu aren't translated nor translatable.

## Expected Behavior
These should be translatable through Crowdin.

## Actual Behavior
These strings are always shown in English.

## Steps to Reproduce

1. Tap and hold in any empty space of the screen.
2. Tap Settings.
3. Tap and hold "Debug".

## Environment

* Device: Lenovo Moto G Play (4th. gen.), LATAM/XT1601.
* Android version: 7.1.2
* Launcher version: 1.1.0.1791
* Rom: ColtOS Breeze.

## Logcat

```
No need to provide any.
```

**Comment by nyancrimew** [comment]
These Strings are not translatable on purpose, to not blow up the Apk size with easter eggs too much

**Comment by FacuM** [comment]
It's your want but I don't believe it's gonna grow the size much.

BTW, thanks for checking it :+1:.

**Comment by divadsn** [comment]
@FacuM A question: Would you translate jokes in real-life?

**Comment by FacuM** [comment]
@divadsn Real life good jokes have been translated like these: https://www.reddit.com/r/AskReddit/comments/1mxbyt/what_jokes_get_completely_lost_in_translation/ out of the fact that these translations are pure bullshit, I guess you get the point.
