### ISSUE TITLE
Disabling the Google pill disables the weather indicator

### ISSUE THREAD

**Issue by Axelzero1** [Deletescape-Media/Lawnchair#1036]
## Description

When the Google search pill is disabled but weather is enabled, weather disappears.
The pill shouldn't dictate the status of the weather indicator

**Comment by divadsn** [comment]
The weather is part of the Google search pill widget, therefore it will get removed when you disable it.

**Comment by robglez** [comment]
You can achieve it by uninstalling Google as you see on this screenshot I only have the weather without the Google pill 

https://imgur.com/QCTNTgU

**Comment by divadsn** [comment]
To be added in #959
