### ISSUE TITLE
More on ram less on features

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1068]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
https://play.google.com/store/apps/details?id=com.gau.go.launcherex&hl=pl
GO launcher EX (polski) – Aplikacje na Androida w Google Play
