### ISSUE TITLE
Screen Takes about 2 seconds to turn on

### ISSUE THREAD

**Issue by RealAlcibiades** [Deletescape-Media/Lawnchair#107]

**Comment by fonix232** [comment]
Would be nice if you provided some further details. It does not happen to neither me, nor to @deletescape AFAIK. Phone model, OS version, etc. would be nice to know (also, Lawnchair version).

**Comment by RealAlcibiades** [comment]
Pixel XL, 8.0.0 DP3... The delay has stopped, I normally install more than one app at a time and then uninstall the ones I don't like, so I'm assuming it was a different app causing the delay.

**Comment by intelligentcasanova** [comment]
This issue can be closed @deletescape.
