### ISSUE TITLE
Why hey bye

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1073]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
What's your point of doing this?

**Comment by ghost** [comment]
i will not tell

**Comment by ghost** [comment]
But there is a good reson

**Comment by divadsn** [comment]
Tell it or I will take morr actions against you

**Comment by divadsn** [comment]
We don't wanna ban you, but we will do it and even more if you don't want to work with us the community.

**Comment by deletescape** [comment]
@divadsn I already blocked him on org level 😝
