### ISSUE TITLE
There are no limits to spam

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1075]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
There are limits, lemme show you them later, reply to my previous messages you shady guy with no balls.

**Comment by ghost** [comment]
I know tgat why i an spamming aglfter half ot 1 hour

**Comment by ghost** [comment]
I think it is 20/hour
