### ISSUE TITLE
Android 8.1 notifications don't work without notification channels

### ISSUE THREAD

**Issue by Xyolyp** [Deletescape-Media/Lawnchair#1087]
## Description
On my Nexus 6P the notifications for a new version of lawnfeed result in a toast that says that the notification channel mustn't be null. 

## Expected Behavior
A notification to download the neue Version of lawnfeed should appear. 

## Actual Behavior
I get a toast message that says that the notification channel mustn't be null.

## Steps to Reproduce

1. Restart lawnchair that the notification gets triggered

## Environment
* Device: Nexus 6P
* Android version: 8.1
* Launcher version: Most recent Google Play Download
* Rom: stock

**Comment by LinuxLlama** [comment]
I've never experienced this.

**Comment by Xyolyp** [comment]
What additional data can I provide? 
Side note: I activated the option to get a toast whenever there is a notification that fails because of missing the notification channel. Otherwise there wouldnt be anything.

**Comment by divadsn** [comment]
Me neither on 8.0, do you have notification access granted? Keep in mind that after an upgrade some permissions needs to be reapplied, that's not our fault.

**Comment by Xyolyp** [comment]
I checked the permissions and yes, the permissions are all granted.
