### ISSUE TITLE
unfinished easter egg or what ?

### ISSUE THREAD

**Issue by agoogleuser** [Deletescape-Media/Lawnchair#1091]
![screenshot_20171222-171725](https://user-images.githubusercontent.com/33462243/34303098-96ff5106-e73c-11e7-9e00-1db69d1302eb.png)
![screenshot_20171222-171733](https://user-images.githubusercontent.com/33462243/34303100-99370112-e73c-11e7-8c51-e2d3f3f11d34.png)
![screenshot_20171222-155752](https://user-images.githubusercontent.com/33462243/34303101-9a1fedbe-e73c-11e7-87d5-342c1d207d56.png)
--snip--
Edit: don't spoil the fun ;)

**Comment by guest4711** [comment]
You are using a very outdated version of LawnChair, aren't you? (I use 1.1.0.1809)

**Comment by agoogleuser** [comment]
i use the one in the play store. last version , but the version is 1.1.0.1742

**Comment by guest4711** [comment]
See also #1035

**Comment by divadsn** [comment]
That's just something that we don't really care tbh, it's an easteregg in the end though.
