### ISSUE TITLE
Folders in app drawer.

### ISSUE THREAD

**Issue by arkydon** [Deletescape-Media/Lawnchair#1092]
It would be very useful for us folks who have a lot of apps installed to be able to group apps in the app drawer into folders.

**Comment by fonix232** [comment]
There's already an issue ticket open for this, #666 

Please do not open duplicate issues! It just makes life harder :)

**Comment by divadsn** [comment]
@fonix232 Tbh, Folders in app drawer isn't really the Pixel style to go

**Comment by guest4711** [comment]
But being better than the original would be great ...

**Comment by skittles9823** [comment]
@guest4711 Please stop replying in this issue. There is another one already open.
