### ISSUE TITLE
[Feature request] Quick Toggle to show hidden apps

### ISSUE THREAD

**Issue by bungabunga** [Deletescape-Media/Lawnchair#1093]
I use Lawnchair launcher in a way that I hide any app that I don't use frequently (settings, widget apps, apps that you only configure once ant then leave doing their job...) so that the other apps are easier to search for in the launcher area. but now and then I have to go to those hidden apps just to adjust some settings. and it takes me a while to go to settings/launcher/hidden aps to find the right one, unhide it, change settings and then do all those steps once again to hide it again...

it would be great if there would be a toggle somewhere within the Lawnchair UI to just quickly unhide all hidden apps and then hide them again after doing the job that needs to be done.

**Comment by divadsn** [comment]
@bungabunga As far as I can remember there is a switch in the behavior settings

**Comment by bungabunga** [comment]
you're right, I'm closing this. thank you!
