### ISSUE TITLE
Launchair settings not accessible if dekstop area fully populated

### ISSUE THREAD

**Issue by bungabunga** [Deletescape-Media/Lawnchair#1094]
## Description
Currently it seems there's no simple way to access Lawnchair settings when the desktop area is fully populated with app icons and widgets. And there is no way to lock desktop area when it's fully populated.

## Expected Behavior
A simple way to access Lawnchair settings even when the desktop area is populated in full.

## Actual Behavior
I have to change the shape of some widget or remove some desktop icon to make an empty desktop area, long press it to access Launchair settings.

## Possible Solution
A dedicated launcher icon - Launchair settings (Launchair icon currently hidden from launcher area by default)

**Comment by JonnyTech** [comment]
Try pinching the screen, as `Behaviour >> pinch to overview` should be on by default.

**Comment by bungabunga** [comment]
thanks! i'm a bit ashamed that i didn't find this out myself. do anyone thinks that it would still be a good idea to have a separate icon for this (for people that have pinch to overview disabled)? if not i'm going to close this issue.

**Comment by JonnyTech** [comment]
Well, there is also the option of going to `Android settings >> Apps >> Lawnchair` then clicking on the cog in the top right hand corner.

![screenshot_20171225-134531](https://user-images.githubusercontent.com/3584732/34340330-121454f6-e97a-11e7-9cc9-d98a0e6a3c88.png)

**Comment by bungabunga** [comment]
seems you have a Google device? on my device (Sony) this feature is also there but hidden so i would've never thought it's there. you have to tap on an empty space (where an icon should be but it's not).

![2017-12-25 14 56 57](https://user-images.githubusercontent.com/2994878/34340470-6a1c716a-e984-11e7-90a3-27a49a8a09c1.png)

**Comment by JonnyTech** [comment]
No, I have a completely Google-free AOSP 7.1 ROM. Maybe your ROM is modified or old.

**Comment by msfjarvis** [comment]
I will never know how can someone typo Lawnchair in a GitHub repository whose URL has the word twice...

**Comment by akhilnarang** [comment]
Luncherrr

**Comment by divadsn** [comment]
@akhilnarang Lauwnchar

**Comment by JonnyTech** [comment]
>  you have to tap on an empty space (where an icon should be but it's not).

@bungabunga I would create a separate issue for that as it looks like a bug to me.

@akhilnarang don't you mean Christmas luncherrr...?
