### ISSUE TITLE
Weather widget icon issue

### ISSUE THREAD

**Issue by ArseniiMitianin** [Deletescape-Media/Lawnchair#1095]
Did anyone else encounter something like this when using Google Awareness API? I'm not sure if it could be related, but it might have started after updating Magisk to v15.0 and Magisk Manager to v5.5.1. Could be a coincidence. On the other hand, OpenWeatherMap works fine.

I know that Google's API updates the weather widget only after 3 degree changes, but this issue persisted even after several re-installs and reboots.
![image](https://user-images.githubusercontent.com/22371160/34349250-e91970d6-e9dd-11e7-9840-f24e11f26f1e.png)

## Environment
* Device: OnePlus 5T (rooted)
* Android version: 7.1.1
* Launcher version: 1.1.0.1742
* Rom: Oxygen OS 4.7.4 (Stock)

**Comment by AxiK101** [comment]
Is it closed?

**Comment by ArseniiMitianin** [comment]
Yes, I started worrying too soon, the icon updates fine.
Looks like the Awareness API behavior was the reason for this.
