### ISSUE TITLE
Drag app 1*1 widget（such as 1*1 direct dial） bug

### ISSUE THREAD

**Issue by LeongAndroid** [Deletescape-Media/Lawnchair#1096]
![bug](https://user-images.githubusercontent.com/27144110/34368077-2059b876-eaec-11e7-8e07-829fe9dba777.png)

## Description

I want to add some app widget 1*1（In fact it's shortcut type) to screen, but sometimes can not move,
it's bad experience. Icon will can not move between in hotseat and workspace.

Can you help me?Thanks.

## Expected Behavior

should can drag normal.

## Actual Behavior

Can not move, it will stay there, unless i drag it again.

## Steps to Reproduce

1.long click Contacts,can show pop window.
2.choose widgets icon and Click it, so show contacts widgets list in below on screen.
3.choose widgets icon and Click it, so show contacts widgets list in below on screen.
4.When icon position in between hotseat and workspace, icon sometimes can not move, can stay here.

## Environment

* Device: any devices
* Android version: android 8.0+
* Launcher version: all version
* Rom: all rom

## Logcat

```
your log here
```
nothings,

**Comment by Frontear** [comment]
I can't reproduce. Running S8
