### ISSUE TITLE
Google search button does not work

### ISSUE THREAD

**Issue by psyycker** [Deletescape-Media/Lawnchair#1097]
When I press on the google search button, nothing happen

**Comment by divadsn** [comment]
@Psyycker http://bit.ly/lawnfeed

**Comment by Psyycker** [comment]
So if I understand well, the app available on the playstore is not able to use search button ? I need to use this one ?

**Comment by nyancrimew** [comment]
@Psyycker The search functionality on the PlayStore version is currently broken without the Google Now addon (Lawnfeed). This will be fixed in a future release

**Comment by Psyycker** [comment]
Ok but after installing launchfeed, it's still not working, do I need to do something after installing ?

**Comment by divadsn** [comment]
@Psyycker Restart Lawnchair in Debug
