### ISSUE TITLE
Google calendar icon unchangeable in app drawer

### ISSUE THREAD

**Issue by ellienieuwdorp** [Deletescape-Media/Lawnchair#1099]
I found some other issues describing this but they seem to have gotten closed a few months ago after a certain PR got merged. The issue still remains for me though so here goes.

## Description
Attempting to change the icon of Google calendar in the app drawer doesn't do anything, the icon stays default. Changing it on the home screen however works fine.

## Expected Behavior
The icon should get changed to the chosen icon like how all other apps behave.

## Actual Behavior
When clicking the custom icon, the activity closes and the old unchanged app icon shows instead of the chosen one.

## Steps to Reproduce
1. Open app drawer
2. Long press Google calendar
3. Press the edit button
4. Press the icon
5. Select different icon
6. See that the icon remains unchanged.

## Environment
* Device: Pixel 2 XL & OnePlus 5
* Android version: 8.1 & 8.0
* Launcher version: 1.1.0.1742
* Rom: Stock pixel rom & OOS.

**Comment by divadsn** [comment]
Not reproducable, tried with multiple iconpacks, try rebuilding your icon database.

**Comment by ellienieuwdorp** [comment]
Still doesn't work, I tried with multiple icon packs too. Should I take a log of the issue? If so, how should I?

**Comment by divadsn** [comment]
@luuknieuwdorp Rebuild icon database

**Comment by ellienieuwdorp** [comment]
@davidsn once again, already tried that. It still doesn't work.

**Comment by Davidsn** [comment]
@luuknieuwdorp
I believe you mentioned the wrong user :-)
I hope you could fix your issue nonetheless.
Best,
David

**Comment by ellienieuwdorp** [comment]
Whoops, your names are very similar.  @divadsn this time then ;-)
