### ISSUE TITLE
Seperately change Homescreen and App Tray icon sizes

### ISSUE THREAD

**Issue by ZerNico** [Deletescape-Media/Lawnchair#11]
Allows the user to select a different size for their icons on the homescreen than in the tray and vice-versa

**Comment by intelligentcasanova** [comment]
@deletescape, this feature has already been fully implemented, right?

**Comment by AxiK101** [comment]
Yed

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
