### ISSUE TITLE
[Feat. Req] Simple RSS reader widget? 

### ISSUE THREAD

**Issue by momoe** [Deletescape-Media/Lawnchair#1101]
While I understand this might be beyond the perview of LawnChair's features, I would like to see if there's a simple RSS feed widget that can be implemented to allow Lawnchair's customization features in it. Features such as: 

*Blurry background feature
*Custom Font Scale (title/short summery)
*Theme color sampling
*(Optional) RSS image thumbnails

Again I know this is a little outside the scope of features, but would be great to include one for news subscriptions. Thank you. 

-momoe

**Comment by nyancrimew** [comment]
@momoe I think you should be able to do this with KWGT quite easily, as it is out of scope for Lawnchair imo
