### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by lingtjien** [Deletescape-Media/Lawnchair#1102]
I would personally like to see these features as these are the ones that still keep me on Nova launcher...

In no particular order:
- ability to hide the search bar in the app drawer
- ability to hide the (right) scrollbar in the app drawer
- add a "double tap to lock" gesture to the behavior options (or in a new separate gestures options)
- ability to adjust the accented color in the settings menu, right now I could only adjust it with the option that extracts a color from the wallpaper but I would like to be able to choose this color myself instead of using the wallpaper to get it
- ability to choose an icon for folders
- make the arrow key that opens the app drawer automatically change to a page indicator when switching between "desktops" and it should return to an arrow once you haven't switched "desktops" for a (few) seconds (multiple dots, one dot per "desktop", with the current "desktop" dot slightly larger in size)

Thank you for reading, have a great day.

**Comment by divadsn** [comment]
Thanks for the list, but:
Most of them are not Pixel style, we will look into the color option and the D2TS is already on the list.
