### ISSUE TITLE
New downloaded apps icons aren't automatically added to launcher

### ISSUE THREAD

**Issue by MicBlang** [Deletescape-Media/Lawnchair#1103]
## Description

When downloading a new app from the Play Store, the app isn't being added to the launcher pages. We have to add it manually.
## Expected Behavior

Icons should be added automatically to the launcher when they finished downloading. This issue wasn't happening before I updated my device ROM to OxygenOS Android 8.0.0 beta. The issue isn't happening on OnePlus Launcher.

## Actual Behavior

The app isn't being automatically added.

## Steps to Reproduce

1. https://photos.app.goo.gl/5GQFCpKXkhHXIOiJ2

## Environment

* Device: OnePlus 5T
* Android version: 8.0.0
* Launcher version: 1.1.0.1742
* Rom: OxygenOS OP5T_O2_Open_1

**Comment by guest4711** [comment]
New apps are added to the appdrawer. If I like to have an apps on my homescreen too I have to decide where to put it. I'd really hate a launcher if it would alter my homescreens without asking me...

**Comment by MicBlang** [comment]
Lawnchair was automatically adding apps to the homescreen before.

**Comment by guest4711** [comment]
An option, to sort the drawer by installation time (desc.) would be helpful to find the newly installed apps. See also #1111

**Comment by MicBlang** [comment]
Yes, I agree.

**Comment by guest4711** [comment]
I'm using it since june 2017 on some devices. It never added apps to the homescreen by itself... I know other launchers will or can optionally do that. As an option (off by default) it would be okay (for me).

**Comment by MicBlang** [comment]
That's weird... It did on my Nexus 6P and OnePlus 5T.

**Comment by Navd15** [comment]
thats right guys it sometimes do not add icon automatically ..........even restart of launcher doesnt solve this

**Comment by widewing** [comment]
Also, Chrome's "Add to home screen" not work in the latest version of Lawnchair. This really annoys me. I think it's an issue between Lawnchair and OnePlus OOS 5.0 since I have no issue on OOS 4.x

**Comment by MicBlang** [comment]
@widewing Yes you're right!!!

**Comment by guest4711** [comment]
Ok, it depends on setting in Google Play Store, where you can enable automatic addition of new apps to the homescreen. Cause I don't use g-apps or play services (I don't install them) I never noticed that behavior...

**Comment by MicBlang** [comment]
@guest4711 [You won't find the setting in the Play Store anymore](https://android.stackexchange.com/questions/182782/how-do-you-disable-add-icon-to-home-screen-on-android-oreo). I'm on Android Oreo, and the setting isn't there anymore. @deletescape needs to add an option in Lawnchair settings to turn the option on or off...

**Comment by GAZ082** [comment]
Same issue. Also when i want to add webpages shortcuts to the desktop it wont add it.

**Comment by null1099** [comment]
Same issue: I installed a new app via Play Store. It does not show up in the app drawer. The same applies to apps installed via ADB. They do show up in the device's app list (Settings -> Apps), but do not show up in Lawnchair's app drawer.

Huawei Mate 10 Pro / Android 8
