### ISSUE TITLE
HAPPY BIRTHDAY!

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Lawnchair#1106]
Since it's the coming to age of one of our Greatest Developers, I suggest we celebrate here on this occasion!

So guys, send all the whores, cocaine, and other unspeakable stuff in the way of @divadsn - he deserves it!

🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂

(Issue-text blantly copied from @fonix232)

Personal message from me here:

Thank you so much David! For all the work you have done for Lawnchair and also as a friend and gaming partner ;) welcome to the adult world 😂

**Comment by fonix232** [comment]
This needs to be fixed ASAP, @divadsn do something!

**Comment by divadsn** [comment]
Lmao not today @fonix232 😂
