### ISSUE TITLE
Doc arrow in the wrong place

### ISSUE THREAD

**Issue by ffeingol** [Deletescape-Media/Lawnchair#1108]
After a recent update ( 1.1.0.1820) the dock arrow is showing up in the wrong place.  The change for this release says 'Don't move arrow below transparent dock', but I have no dock.

My config is 8 rows by 4 columns with no dock.  I'm on a Nexus 5X with Android 8.0.0, November security patch.  The doc arrows shows up between the 1st and second row of icons instead of under the first row of icons.

Screen shot:

![rsz_screenshot_20180103-132452](https://user-images.githubusercontent.com/18329578/34539264-6e8747b2-f095-11e7-885f-66d4d6465aad.png)

Please let me know if you need any further details.

**Comment by divadsn** [comment]
It is normal now since the last builds.
