### ISSUE TITLE
KWGT widget blocking swipe for opening app drawer

### ISSUE THREAD

**Issue by theothertored** [Deletescape-Media/Lawnchair#1109]
Title is explanatory enough, I think.
The widget doesn't block horizontal swipes.
The issue doesn't occur if the widget is in the dock.

**Comment by sawankumar** [comment]
Swipe from the dock part... It will work...

You must be swiping on widget because mostly it coveres the desktop . Then it won't work at all...

I don't think it is a lawnchair issue

**Comment by theothertored** [comment]
Dev confirmed it is an issue on G+, so I posted it here. What you presented is a workaround :D
