### ISSUE TITLE
Wallpaper has a serious case of jpeg

### ISSUE THREAD

**Issue by theothertored** [Deletescape-Media/Lawnchair#1110]
See the attached image.
I did a little searching and found that this is a common issue probably inherited from Launcher3.
Worth looking at though.
![1515142878502](https://user-images.githubusercontent.com/17922244/34602309-87aba290-f1ff-11e7-93bb-274197cae55a.png)

**Comment by nyancrimew** [comment]
Wallpapers are actually not rendered by the Launcher, they are rendered by Android, the background of the Launcher is just set to fully transparent which makes the Wallpaper appear. So a Launcher technically has no way to affect the quality of a Wallpaper (unless of course you're only talking about wallpapers applied through the built in wallpaper picker)

**Comment by theothertored** [comment]
I hope I understood correctly.
I used both the Lawnchair wallpaper picker and the built-in Android one, both producing the same result, which is to be expected considering the information you provided.
I suspect that might have to do with copying the file to a temporary location, changing the compression. If that's true, maybe Lawnchair could copy the PNG file instead of converting it to JPEG. (It's probably not that simple, I know)
Otherwise, if this is a rendering issue, I think rewriting the implementation would be to much work, so the issue should be closed.

**Comment by nyancrimew** [comment]
Like I have stated in my previous reply, wallpapers are not rendered by Launchers, but by Android, there is nothing we can do about this in Lawnchair
