### ISSUE TITLE
[FR] Start search from app drawer by pull down gesture 

### ISSUE THREAD

**Issue by Zizou3000** [Deletescape-Media/Lawnchair#1112]
It's a very useful option in Nova launcher.

You open the drawer, and pull down to search. 

That way you don't have to reach the top with your finger to search. 

Lawnchair has an option to start search immediately by holding that arrow, but this is different. You can use it anytime with drawer already opened.

**Comment by theothertored** [comment]
Actually it would be great to have the search bar in the drawer at the bottom :D

**Comment by bohrabhijeet** [comment]
@TheTored You can do that by enabling 2 row dock and placing the widget in the second row

**Comment by theothertored** [comment]
*In the drawer*

**Comment by fonix232** [comment]
This won't be implemented, since pulling down in the app drawer will either scroll towards the beginning, or if on top, close the app drawer.

As for moving the search bar to the bottom, it wouldn't be helping since to follow Material guidelines, the search box would need to be on the same level as the app shortcuts, dropping the search bar to the very end of the app drawer.

**Comment by ghost** [comment]
> This won't be implemented, since pulling down in the app drawer will either scroll towards the beginning, or if on top, close the app drawer.

I realize this is quite old now but it is an important feature for me so I'm offering some input on how it could be done:

Pulling from the bottom 20-30% of the drawer opens the search.
Pulling from the top 20-30% closes the drawer.
Pulling from the middle/remainder functions as scroll. 

I do not value scroll function but this is how it could be done without sacrificing other functions. An option for this in the setting - doesn't have to be default - would be immensely appreciated as it is the one feature I still miss coming from Nova.
