### ISSUE TITLE
Integrated Google search bar doesn't work

### ISSUE THREAD

**Issue by AlexanderBarta** [Deletescape-Media/Lawnchair#1113]
## Description

Tapping the integrated Google search field doesn't do anything except showing the onclick animation. It doesn't matter if the search field is set to be the small pill or to be full width.

The integrated search field used to work in the past, but this was quite a while ago and I can't recall how long it has been. Reinstalling didn't help.

Device: Samsung Galaxy S7; Android 7.0 (Stock Rom)

**Comment by divadsn** [comment]
http://bit.ly/lawnfeed if you are using Play Store version.
