### ISSUE TITLE
Add a search string like in the original launcher

### ISSUE THREAD

**Issue by gargullia** [Deletescape-Media/Lawnchair#1114]
![photo_2018-01-11_21-07-44](https://user-images.githubusercontent.com/19420334/34839848-23a26ce2-f714-11e7-9acb-5abd29e2a58b.jpg)
![photo_2018-01-11_21-07-48](https://user-images.githubusercontent.com/19420334/34839849-23d3cc92-f714-11e7-825b-1220e877a1df.jpg)

**Comment by nyancrimew** [comment]
There are multiple existing issues open for this.
