### ISSUE TITLE
Launcher Crashes Once in a while

### ISSUE THREAD

**Issue by shreyasbapat** [Deletescape-Media/Lawnchair#1115]
## Description

The launcher crashes when used parallely with Google Now

## Expected Behavior

The Launcher must open when the home button is pressed.

## Actual Behavior

It Crashes. The launcher opens but does not display anything, hangs.

## Steps to Reproduce

1.  Pressing the Home Button
2.
3.
4.

## Environment

* Device: Lenovo Z2 Plus
* Android version: Nougat 7.0
* Launcher version:  One on the Play Store
* Rom: Stock Rom

**Comment by nyancrimew** [comment]
How are supposed to fix this if you do not provide any valuable information. Please use the issue template and provide us with usable logs, with that one sentence you provided we can NOT do anything.

**Comment by divadsn** [comment]
@deletescape Somebody once told me...

**Comment by shreyasbapat** [comment]
I don't know like. It crashed multiple times in my device. I am using Lenovo Zuk Z2. Will try to provie you with the log files.

**Comment by bohrabhijeet** [comment]
@shreyasbapat Give storage permissions to the launcher from Settings > Apps
