### ISSUE TITLE
Different badges

### ISSUE THREAD

**Issue by tofylion** [Deletescape-Media/Lawnchair#1116]
## Description

We can't change the way the notification badges look like. I would prefer if it had a number or anything to show what you missed.

## Expected Behavior

Show numbers next to the icon as a badge

## Actual Behavior

Just shows a colored circle

## Steps to Reproduce

1.Get a notification
2.Look at app icon

## Environment

* Device: 
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by yurtemre7** [comment]
Please rename the title with a "[FR]" in front to declare it's a Feature Request. Thanks!
-Émre

**Comment by ghost** [comment]
I would also like this feature. At this point, the Talkback screen reader doesn't recognize the notification dot, and I miss the new notification count from stock launchers I've had on other phones I've had in the past.

**Comment by marrie** [comment]
I have to agree. This is an accessibility over-site on the part of the developers. As indicated talkback, the screen reader for android which can be gotten fro the play store does not read the dots. Please have your staff take a look at this as it's very important we know if we missed something in a message etc.

**Comment by chaltain** [comment]
I agree with Kyle and Mary above. I'd like to be able to access notification dots with the Talk Back screen reader from Google.

**Comment by rodrigoswz** [comment]
I miss a lot the numeric badges in Lawnchair, I hope it will be added. Any word from one of the LC staff representatives about this?

**Comment by divadsn** [comment]
Support is planned, as basically every well made app puts an unread counter to the notification, which we can make use of.

**Comment by rodrigoswz** [comment]
Nice, thanks David.

**Comment by Davy49** [comment]
I agree with what other user's have stated about having actual numbers showing in the notifications instead of just simple dots like most of other popular launchers that I've used in the past already have.
