### ISSUE TITLE
Icons animate to the wrong place when app is closed

### ISSUE THREAD

**Issue by marcinciarka** [Deletescape-Media/Lawnchair#1121]
## Description
I've recorded a video:
https://www.youtube.com/watch?v=74ShdXkPrpY

## Steps to Reproduce

1. Open app
2. Hit home button
3. App icon is being animated to the wrong place and it has wrong shape

## Environment

* Device: Xiaomi Mi 6 MCE16
* Android version: 8.0.0
* Launcher version: 1.1.0.1742
* Rom: MIUI 9.3 by xiaomi.eu 8.1.18

**Comment by divadsn** [comment]
Known issue with MIUI, we don't have any Xiaomi device with MIUI to test it out unfortunately.

**Comment by marcinciarka** [comment]
@divadsn okay, can I help you somehow?

**Comment by divadsn** [comment]
Sadly after running MIUI 9 on my Redmi Note 3 I noticed that it's a MIUI bug, as the animation is going to the icon position of the stock launcher, instead of Lawnchair's.

**Comment by fghsgh** [comment]
Workaround: you can change the place of the icon in the stock launcher, or get a custom ROM.
