### ISSUE TITLE
Ability to change both dock and desktop spacing 

### ISSUE THREAD

**Issue by calebdonut** [Deletescape-Media/Lawnchair#1123]
Hey there,

It would be nice if you could incorporate this into lawnchair. Idk if it's possible, but the option to change both the spacing (height and width) for the dock and desktop would be nice!

**Comment by calebdonut** [comment]
Screenshots

https://imgur.com/a/AC5CQ

https://imgur.com/a/OlGem

**Comment by divadsn** [comment]
That's already possible, you can adjust dock height scale in the dock settings.

**Comment by calebdonut** [comment]
You're right, didn't realize we could. But not the width!

**Comment by divadsn** [comment]
That's something currently not expecting to be, as we rather were thinking about padding adjustments.

**Comment by calebdonut** [comment]
Oh, alright then
