### ISSUE TITLE
Logo for Lawnchair made on Utopian platform

### ISSUE THREAD

**Issue by linadesteem** [Deletescape-Media/Lawnchair#1125]
## Description
Hello,
this my design of logo for your project. Its free. Created on Utopian platform where users are rewarded for contributions to open-source projects.

https://utopian.io/utopian-io/@linade/logo-design-for-lawnchair-launcher

or you can view it here without registration to utopian

https://busy.org/utopian-io/@linade/logo-design-for-lawnchair-launcher

You dont have to accept it or anything. But if you like it, spread the good work about the platform :)

Munir,

**Comment by LuanEduardo47** [comment]
Nice! 👍

**Comment by Frontear** [comment]
It looks very nice. Would love to see it on the official app.

**Comment by TheShark27** [comment]
Looks cool actually!

**Comment by dhruvkb** [comment]
It's a major improvement over the current logo!

**Comment by unrooted** [comment]
That's really nice concept art!

**Comment by nyancrimew** [comment]
It is a really nice concept art / design, but I don't think we want to go through yet another rebranding already. Thanks a lot for your effort though, it is always highly appreciated :+1:
