### ISSUE TITLE
Integrated Google search bar doesn't work if Google Now page is disabled. 

### ISSUE THREAD

**Issue by ankitydv193** [Deletescape-Media/Lawnchair#1127]
## Description

The Google search bar stops working when I disable the Google Now page. The search bar is still there and I can here 'click' sound when I touch the bar but there is no response. It starts working again when I enable the Google Now page. 
This issue is present with the Google button as well as the wide search bar. 
This issue was present in previous versions too. 
I have downloaded and installed the latest version of Lawnfeed so that's not the issue. 

## Expected Behavior

It should work even when the Google Now page is disabled. 

## Actual Behavior

The search bar/button stops working even though they give feedback(sound on touch) that they are being pressed

## Steps to Reproduce

1. Open settings
2. Go to Behavior. 
3. Turn off Google Now page
4. Go to home screen and press the Google search bar/button

## Environment

* Device: One Plus 5 running OxygenOs 5.0.1
* Android version: 8.0.0
* Launcher version: 1.1.0.1742
* Rom: Stock Rom

**Comment by divadsn** [comment]
Closed, see #959

**Comment by ankitydv193** [comment]
@divadsn Why did you close this issue?
Google search bar should work without having to enable google now/

**Comment by divadsn** [comment]
@Bluethf Read above.
