### ISSUE TITLE
Subgrid positioning

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#1129]
Pretty self-explanatory. Allows icons to be placed in between the grid, like Nova Launcher.

**Comment by divadsn** [comment]
@Treemindr Ewww, are we Nova Launcher?

**Comment by skittles9823** [comment]
@Treemindr Colin pls ;-;

**Comment by ghost** [comment]
Gib clay

**Comment by LinuxLlama** [comment]
@skittles9823 @divadsn I'm just giving a suggestion from Google Plus... Jeez

**Comment by skittles9823** [comment]
@Treemindr Just teasing fam 😘

**Comment by divadsn** [comment]
Interesting feature, but as I said in the end, that should be a Nova exclusive tho and it should be respected.

**Comment by Atulin** [comment]
With Nova being acquired by an ad tech company, it might be worth reconsidering. In the first place, I see no reason why it should be exclusive to Nova. Not like they patented or copyrighted the idea.
