### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1130]
Device: BQ Aquaris X
Android version: 7.1.1
Rom: Stock Rom 1.5.1 rooted
Weather in launcher does not update temperature, pressing opens the weather application of google with a different temperature than the one shown by the launcher in version 1.1.0.1742

**Comment by divadsn** [comment]
See FAQ for the answer please, it's been already posted here several times.

2018-01-30 20:10 GMT+01:00 Elnarci <notifications@github.com>:

**Comment by divadsn** [comment]
> This depends on which weather provider you have selected. If you use OpenWeatherMap, the difference is normal because Google Now uses weather data from Weather.com. But if you use Google Awareness, then things get tricky, as it updates only if the weather is more than 3 degrees from the previous value.

**Comment by ghost** [comment]
Attached screenshots where you see the weather provider (Google), and the difference in degrees between the desktop and weather information as you can see is 6 degrees (10 to 4)



⁣Enviado desde BlueMail ​

**Comment by divadsn** [comment]
@Elnarci Report it to Google, not us, we are only using their data provided by the Awareness API which as I said updates only on huge temperature differences.

**Comment by ghost** [comment]
Sorry? with other launchers (Nova, Go, etc.) the problem does not happen.
In fact, in the screenshots that I sent to them, the error is in the screen of the launcher that marked 10 degrees when the actual temperature was 4 degrees, which indicated the google apk. Therefore I do not think Google is responsible for the launcher's weather information not being updated properly.
regards
Enviado desde Correo para Windows 10

De: David Sn
Enviado: jueves, 1 de febrero de 2018 8:12
Para: LawnchairLauncher/Lawnchair
CC: Elnarci; Mention
Asunto: Re: [LawnchairLauncher/Lawnchair] Weather (#1130)

@Elnarci Report it to Google, not us, we are only using their data provided by the Awareness API which as I said updates only on huge temperature differences.

**Comment by divadsn** [comment]
@Elnarci Nova has the same issue if you use Google Awareness API, and you can't compare the OpenWeatherMap weather data with the one displayed in the Google app.

**Comment by ghost** [comment]
Regardless of any comparison, I understand that if Lawnchair I have selected as Google Awareness API weather provider (which is what I've always had), the information that the launcher must show must be the same as Google Awareness shows on the weather screen or, well a maximum difference of 3 degrees as they indicated to me in their first mail, but observe that the difference of the case that this morning I have documented them is of 6 degrees (from 10 to 4)
regards

Enviado desde Correo para Windows 10

De: David Sn
Enviado: jueves, 1 de febrero de 2018 17:34
Para: LawnchairLauncher/Lawnchair
CC: Elnarci; Mention
Asunto: Re: [LawnchairLauncher/Lawnchair] Weather (#1130)

@Elnarci Nova has the same issue if you use Google Awareness API, and you can't compare the OpenWeatherMap weather data with the one displayed in the Google app.

**Comment by nyancrimew** [comment]
Google Now doesn't even use Google Awareness for their weather information (weird, I know, but it is google after all). So the weather information there will be different in some cases.

**Comment by ghost** [comment]
Surprising as it says, but it's Google after all, but even so, I can assure you that the temperature in Madrid this morning at the time of my report was closer to the 4 degrees of Google Now than to 10 of the launcher.

Enviado desde Correo para Windows 10

De: Till Kottmann
Enviado: jueves, 1 de febrero de 2018 18:04
Para: LawnchairLauncher/Lawnchair
CC: Elnarci; Mention
Asunto: Re: [LawnchairLauncher/Lawnchair] Weather (#1130)

Google Now doesn't even use Google Awareness for their weather information (weird, I know, but it is google after all). So the weather information there will be different in some cases.

**Comment by skittles9823** [comment]
@Elnarci Blame google for having an inaccurate weather API then. If you wish for better accuracy, use OWM as the API for Google Feed isn't open for use.

**Comment by ghost** [comment]
Ok, I will use OpenWeatherMap although in your email dated 30/1/18 (22.40) they wrote expressly: "If you use OpenWeatherMap, the difference is normal ..." so I do not understand that now the recommendation to avoid differences is use OWM Anyway, I will try and communicate the result.

Enviado desde Correo para Windows 10

De: skittles9823
Enviado: jueves, 1 de febrero de 2018 18:17
Para: LawnchairLauncher/Lawnchair
CC: Elnarci; Mention
Asunto: Re: [LawnchairLauncher/Lawnchair] Weather (#1130)

@Elnarci Blame google for having an inaccurate weather API then. If you wish for better accuracy, use OWM as the API for Google Feed isn't open for use.

**Comment by skittles9823** [comment]
@Elnarci Look the bottom line is just use the one which is more accurate to you. Neither are going to give the same result as google feed as neither are google feed.

**Comment by ghost** [comment]
Okay. Thank you

Enviado desde Correo para Windows 10

De: skittles9823
Enviado: jueves, 1 de febrero de 2018 18:30
Para: LawnchairLauncher/Lawnchair
CC: Elnarci; Mention
Asunto: Re: [LawnchairLauncher/Lawnchair] Weather (#1130)

@Elnarci Look the bottom line is just use the one which is more accurate to you. Neither are going to give the same result as google feed as neither are google feed.
