### ISSUE TITLE
Do not show the prompt to upgrade Lawnfeed if  Lawnfeed is not installed

### ISSUE THREAD

**Issue by michallepicki** [Deletescape-Media/Lawnchair#1131]
## Description

On a phone with Lawnchair installed but without Lawnfeed installed, after turning on the phone and sometimes when using the Home key, Lawnchair shows a dialog saying to upgrade the Lawnfeed version. This behaviour is undesired because I don't want use Lawnfeed at all. I don't even know if I can since I don't use Google Play Services. 

## Expected Behavior

There is no prompt to upgrade Lawnfeed if Lawnfeed is not installed.

## Actual Behavior

Lawnchair prompts to upgrade Lawnfeed despite the fact that it is not installed at all.

## Steps to Reproduce

1. Uninstall Lawnfeed
2. Reboot phone
3. See the prompt

## Environment

* Device: Xiaomi Redmi 4 Prime
* Android version: 7.1.2
* Launcher version: Lawnchair 1.1.0.1742
* Rom: LineageOS 14.1-20180125-UNOFFICIAL-markw

**Comment by divadsn** [comment]
Already fixed, see #1124.

**Comment by ildar** [comment]
Not fixed.
F-Droid version. Never had this LawnFeed thing. Annoying 😉

**Comment by ildar** [comment]
Ahh! Sorry. The fix came later then F-Droid sources. Sorry for the noise.

**Comment by michallepicki** [comment]
yes, I'm waiting for a release too ;)

**Comment by divadsn** [comment]
@ildar F-Droid version uses some hackery, we can't support it until we know exactly what hackery is being used.

**Comment by ildar** [comment]
FYI, the "hackery" is transparent:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/ch.deletescape.lawnchair.plah.txt
, just to get rid of non-FOSS jars.
I don't expect you support it yet, until the "flavor" PR be ready (https://github.com/LawnchairLauncher/Lawnchair/pull/806). Hence I wrote it was my mistake.
Thanks anyway!

**Comment by divadsn** [comment]
Tagging PR #1157 to keep track of necessary things to do.
