### ISSUE TITLE
Can't set custom Google Calendar icon in app drawer

### ISSUE THREAD

**Issue by ellienieuwdorp** [Deletescape-Media/Lawnchair#1133]
## Description
I opened an issue about this before but it was closed, it is however still an issue. Rebuilding icon database doesn't help.

Changing the Google Calendar icon works fine on the home screen but not in the app drawer.

## Expected Behavior
The icon should get changed to the icon that is selected.

## Actual Behavior
The icon stays the same.

## Steps to reproduce
https://youtu.be/tz5Po5NP5hY

## Environment
* Device: Google Pixel 2 XL
* Android version: 8.1 Jan 05 update.
* Launcher version: 1.1.0.1742
* Rom: stock + rooted

**Comment by divadsn** [comment]
Confirmed, thanks
