### ISSUE TITLE
Alphabetical App Drawer

### ISSUE THREAD

**Issue by deviant77** [Deletescape-Media/Lawnchair#1136]
I think Microsoft Launcher has a really well designed app drawer. I find it really easy to find the app I need quickly with this layout - something I find difficult with the traditional all-icons-lumped-together app drawer layout.

So my feature request, if I may, is to implement an alphabetic app drawer. The recently used apps and new apps sections would be a nice bonus too!

Screenshot of Microsoft Launcher's app drawer:
![Screenshot from Microsoft Launcher's app drawer](https://user-images.githubusercontent.com/16081842/35767995-8303c772-08ed-11e8-879f-d7bc603551bf.png)

**Comment by divadsn** [comment]
We already have something like that, turn on the horizontal list in drawer settings.

**Comment by deviant77** [comment]
Hi,
I did investigate all the options including the horizontal list option in the drawer settings before submitting this issue, but it just results in a long long long list of installed apps - which isn't something similar, and for usability has the opposite problem to the traditional all-icons-lumped-together app drawer layout.

**Comment by divadsn** [comment]
@JustinTrouble Then that's not our thing, as we already have an alphabetical app drawer, we'll look back into that layout in v2, thanks!

**Comment by deviant77** [comment]
Thank you for your time :-)
