### ISSUE TITLE
On-screen buttons are hidden

### ISSUE THREAD

**Issue by tofylion** [Deletescape-Media/Lawnchair#1138]
## Description

In the home screen, the on-screen software buttons are supposed to be up. However, in devices which can hide them, they don't appear in the launcher. We should have the option in the settings to enable it

## Expected Behavior

Show on-screen buttons

## Actual Behavior

On-screen buttons are hidden

## Steps to Reproduce

1.View home screen
2.
3.
4.

## Environment

* Device: Galaxy S8 International version
* Android version:7.0.0
* Launcher version: 1.1.0.1742
* Rom: Stock

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by divadsn** [comment]
We can't access system settings to enable those if they are disabled by system.

**Comment by tofylion** [comment]
@divadsn There are other launchers and apps that force it to be shown. I'll be attaching 2 screenshots, one from nova launcher and one from lawnchair. Both were taken without modifying any system settings. You can clearly see that the software buttons were shown in nova and not in lawnchair. If it's done in nova, that means that it's possible, and that it's not necessarily disabled by the system.
![screenshot_20180206-161036](https://user-images.githubusercontent.com/20754943/35863833-94a91aa0-0b58-11e8-90da-7e121e0cb149.png)
^Lawnchair^
![screenshot_20180206-161021](https://user-images.githubusercontent.com/20754943/35863835-94decb5a-0b58-11e8-9183-0b30de29f467.png)
^Nova^

**Comment by divadsn** [comment]
@tofylion forwarding to @fonix232, I don't own a Samsung device to test that out. It works on AOSP 8.1 on my Redmi Note 3 fine with navbar enabled.

**Comment by tofylion** [comment]
@divadsn Ok, thanks for looking into the issue with me. If you find a way to make it permanently up, please inform me so I can update the launcher asap.

**Comment by Frontear** [comment]
Interestingly, I cannot reproduce this is any way. I am also running an S8, and even though I keep my on screen buttons showing and hidden, I could not replicate this. Is their any additional information about this and it's reproduction?

**Comment by tofylion** [comment]
@Frontear I have the on-screen buttons hidden from the settings. If I keep them shown, they'll be shown in all apps. There are apps that hsve exceptions and force the buttons to be shown, and I can't toggle them to be hidden. If you go to the Settings > Display > Navigation Bar > Show and hide button, you should see a small dot at the left side of the navigation bar. I double tap it and hide it, but it stays hidden even in the launcher.

**Comment by Frontear** [comment]
@tofylion Still no luck reproducing. I have the small dot to the left, and have toggled it numerous times now, outside the launcher, within the launcher, in other apps, nothing bugs out. I will keep trying, and hopefully can get a more concise reproduction method.

**Comment by tofylion** [comment]
@Frontear I'm not saying that anything bugs out inside the launcher, I'm saying that the nav bar is hidden. In the stock and other launchers, the nav bar is supposed to be shown, and forced to be shown with a transparent background instead of the white. I was thinking that maybe there should be a way to toggle the nav bar to be hidden or not from the settings, like in Nova Launcher or Microsoft Launcher

**Comment by bohrabhijeet** [comment]
@tofylion If your ROM has expanded desktop then force enable navbar on the launcher.

**Comment by divadsn** [comment]
@tofylion We already have a fix, it's just a manifest value which hasn't been documented very well by Samsung, so blame them for doing such changes to Android.

**Comment by tofylion** [comment]
@divadsn So there should be an update soon to show the nav bar? That sounds like good news

**Comment by divadsn** [comment]
@tofylion Yes, the final update is aimed for end of February

**Comment by Frontear** [comment]
@divadsn Cannot wait for this new update!

**Comment by bohrabhijeet** [comment]
@Frontear Many users can't! Stay tuned for the updates at t.me/lccommunity 😁

**Comment by fonix232** [comment]
That latest commit should fix this issue on future builds.
