### ISSUE TITLE
Weather widget not showing on lawnchair.

### ISSUE THREAD

**Issue by Frontear** [Deletescape-Media/Lawnchair#1141]
## Screenshots
https://imgur.com/a/LDlfS

## Description
The weather widget is completely inaccessible on lawnchair, while others launchers are able to access it, such as Nova or TouchWiz.

## Expected Behavior
Weather widgets should be seen and accessible

## Actual Behavior
Weather widgets are not accessible

## Steps to Reproduce
1. Hold down / pinch desktop screen to open context menu
2. Select widgets
3. Scroll down to alphabet 'W' section

## Environment
* Device: Samsung Galaxy S8 SM-G950W
* Android version: 7.0
* Launcher version: 1.1.0.1742
* Rom: Stock Rom

**Comment by Frontear** [comment]
Wasn't that fast @divadsn

**Comment by divadsn** [comment]
What weather widget is it?

**Comment by Frontear** [comment]
The stock Samsung weather widget.

**Comment by Frontear** [comment]
Did this get resolved @deletescape?

**Comment by divadsn** [comment]
@Frontear See pinned issue for more information.
