### ISSUE TITLE
When installing Lawnfeed Google Now is checked but not activated

### ISSUE THREAD

**Issue by capstan1** [Deletescape-Media/Lawnchair#1142]
## Description

When installing Lawnchair from the PlayStore and Lawnfeed afterwards, the Google Now Feed on the Most Left Page isn't working automatically. However, looking in the settings it's activated. I had to disable it, back out of settings and reenable it to actually work.

## Expected Behavior

The Google Feed should be available from the beginning (alternatively the setting should show "off" to not confuse users)

## Actual Behavior
- setting shows "on"
- feature not working, has to be re-enabled again

## Steps to Reproduce

1. install LawnChair from PlayStore
2. Install Lawnfeed
3. swipe left on home page to see if it works
4. go to settings and toggle the setting
5. try to get to the page again

## Environment

* Device: Motorola Moto Z
* Android version: 7.1.1
* Launcher version: Lawnchair: 1.1.0.1742, Lawnfeed: 1.1.0.1742.apk
* Rom: Stock

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
@capstan1 Restart Lawnchair in Settings under Debug.

**Comment by capstan1** [comment]
It's working for me now, just toggling the switch helped.

I just meant it should be changed somehow in first place, so new users don't get confused.

**Comment by divadsn** [comment]
@capstan1 On the Play Store version the option is disabled by default, on the GitHub release version it should usually work out-of-the box

**Comment by capstan1** [comment]
For me it was disabled (or maybe not even displayed?) in the Play Store Version. Then I installed LawnFeed and the switch got toggled on, but not actually working.

**Comment by divadsn** [comment]
@capstan1 We have to hide the switch in the Play Store version if Lawnfeed isn't installed, but we are also aware that the integration is buggy (cc @deletescape)

**Comment by divadsn** [comment]
Tested on latest Play Store version, is working as expected for me.

**Comment by itsmejay80** [comment]
For me this issue solved by uninstalling update on my google app

**Comment by 0xSDX** [comment]
> For me this issue solved by uninstalling update on my google app

Thanks a lot for this quick fix. 
 Tested on :-
- `A12 lawnchair v12.0.0 (dev #683)`
- `Google app v13.2.19.23 arm64`

**Comment by Shesh1994** [comment]
Hey guys,
I'm landing here with the fix which I almost figured out after one year..
After searching a lot to try the fix..
You can download The Rootless Pixel Bridge, it works 💋
https://www.apkmirror.com/apk/amirzaidi/rootless-pixel-bridge/rootless-pixel-bridge-v3-release/rootless-pixel-bridge-v3-android-apk-download/
