### ISSUE TITLE
Adaptive icons dont work on some apps

### ISSUE THREAD

**Issue by mueller-ma** [Deletescape-Media/Lawnchair#1143]
Hi, 
first of all: awesome launcher!
I have some few apps which include an adaptive icon, but have target api lower set to lower than 26. For those apps only the legacy icon is shown.
Examples: MALP, openHAB

**Comment by divadsn** [comment]
@mueller-ma Already known, thanks.

**Comment by mueller-ma** [comment]
Has this been fixed? I couldn't find a commit.

**Comment by divadsn** [comment]
@mueller-ma It's not an issue that we can solve, it's on the heads-up for further investigation.
