### ISSUE TITLE
Suggestions: Categories for App List, Drawer Folders and Duck Duck Go

### ISSUE THREAD

**Issue by Teyro** [Deletescape-Media/Lawnchair#1144]
Hi there,

First i want to thank you all for your work! In my opinion it is the best FOSS Launcher :D But there a some features i badly miss from my "old Launcher" (Nova Launcher) ....

**App Categories / Horizontal Scroll in App List**
I use Nova Launcher and have many app installed on my phone... So is sorted it into some Categories (e.g Network, Social, Tools) so that i can find than faster and better.... Is there a chance to implement this?

https://cloud.teyro.tech/index.php/s/eHx6z9nopz7LTYJ

**Drawer Folders**

Same there... For better Orga... 

https://cloud.teyro.tech/index.php/s/3WgiJpDP7KkCkfB

**Duck Duck Go**

I saw that Lawnchair is on fdroid... Very very good idea! But i use DuckDuckGo instead Google is there a chance to implement DDG?

**Comment by divadsn** [comment]
Categories won't be a thing for now, maybe in v2, but Duck Duck Go will definetely be a thing for the f-droid build flavor!
