### ISSUE TITLE
Folder transparency only appearsnin home page

### ISSUE THREAD

**Issue by AlyamanMas** [Deletescape-Media/Lawnchair#1146]
When I make a folder outside the homepage it is black and folder transparency doesn't apply on it, although a folder on the homepage is transparent, and once I move that untransparent folder to the hompeage it does become transparent, reloading the icon database and restarting the launcher doesn't help at all.
Android 6.0.1, Samsung Galaxy J7, Exynos Variant.
Hope this gets fixed fastly.

**Comment by divadsn** [comment]
@AlyamanMas10 Marshmallow, we don't have any testing device available, any screenshots maybe please?

**Comment by AlyamanMas** [comment]
![On homepage](https://drive.google.com/file/d/1OMj7c__uOV1wENRtHyt1BKNZgRCEFyBG/view?usp=drivesdk)

![Outside homepage](https://drive.google.com/file/d/1T8LGPJ9cvIxeqYCV3-4s9n_CyYPnxrHg/view?usp=drivesdk)

**Comment by divadsn** [comment]
"Non-image content type returned"

**Comment by Frontear** [comment]
Cannot reproduce on Galaxy S8. Please update your your Screenshots, they are broken. [Imgur](https://imgur.com/) is a good place to start.
