### ISSUE TITLE
Samsung gadgets can't be placed on launcher

### ISSUE THREAD

**Issue by AlyamanMas** [Deletescape-Media/Lawnchair#1147]
So, yes, Samsung gadgets can't be placed, well, most of them, when I try placing them, it says no more available room, no matter how much I increase the number of squares on my page, I'm assuming it's a problem in the launcher not the gadgets because they work fine on every other launcher except this.
Running Android 6.0.1, Samsung Galaxy J7. Exynos Variant.

**Comment by Frontear** [comment]
I feel a good amount of blame can be placed on the way Samsung programs their android versions. Always breaking something.

**Comment by divadsn** [comment]
@Frontear and their widgets, it's usual with widgets from OEM weather apps, like on Huawei's EMUI for example.

**Comment by Frontear** [comment]
Btw @divadsn, can confirm that this occurs on android 7, galaxy S8. The most common trend I found was that 5x2 widgets from Samsung would not even drop onto the desktop, no matter what. I will upload a video of my testing should you wish to find any other 'trends'. *Where does Samsung go wrong?*

**Comment by bohrabhijeet** [comment]
@Frontear Where Samsung doesn't go wrong? Lmao!

**Comment by Frontear** [comment]
@divadsn [Streamable link](https://streamable.com/xcnkt), should you wish to find a relative trend

**Comment by fonix232** [comment]
Samsung widgets work fine on my Note8 using Oreo - however Samsung did change some things with Oreo (e.g. now we can place the Weather widget from 3rd party launchers, previously it wasn't possible).

Since I can't reproduce it, I'd like to ask those of you who still experience this (@AlyamanMas10  and @Frontear) to try and grab some ADB output while trying to place such a widget.

**Comment by Frontear** [comment]
@fonix232 This issue still exists on Android 8. Can't currently get ADB output (at school), however, I did record a simple video. The video is [here](https://drive.google.com/file/d/19hmuB9YCrDRSnNCV5YxZQIZqllnuhSyR/view?usp=drivesdk). (Google trashed the video quality, woops).

**Comment by fonix232** [comment]
Made a small recording of my own. Freshly installed Lawnchair from Play Store, completely stock Note8 on Oreo (Exynos dual SIM variant). [See here](https://drive.google.com/file/d/1Wx6eiQw1jsq6l9DRYvGIMHT7z5_r7nk_/view?usp=sharing). Widgets can be easily added even after resizing the grid or enabling full screen widgets.

**Comment by Frontear** [comment]
Could this be dependant on desktop > rows? Maybe this only affects S8?

**Comment by fonix232** [comment]
That's why I changed rows mid-video. First is default, then Samsung's values.
