### ISSUE TITLE
No notification dot for missed calls in Android M

### ISSUE THREAD

**Issue by JimmyX32** [Deletescape-Media/Lawnchair#1149]
There is no notification dot (badge) for the Phone app (i.e., missed phone call(s)) in Lawnchair, neither in the app drawer nor the dock. There is a notification icon in the status bar only.

## Description
Notifications for other apps work flawlessly (Messages, Chrome, Google Play, WhatsApp, ...), both in the app drawer and the dock.
I granted all available permission to the Phone app (didn't help). I'm using Google Phone (com.google.android.dialer - the latest version).

## Expected Behavior
A notificaation dot should appear on the phone icon if there is a missed call.

## Actual Behavior
There is no notification on the icon.

## Steps to Reproduce
1. Miss a call.
2. Check the icon.

## Environment
* Device: Sony Xperia M4 Aqua (E2303)
* Android version: 6.0.1
* Launcher version: 1.1.0.1371
* Rom: Concept-ify (debloated stock)

**Comment by divadsn** [comment]
Can't confirm, working fine for me with Google Dialer, have you tried turning notification access on and off?

**Comment by JimmyX32** [comment]
Thanks for your reply, divadsn, I tried so far:
- turn the notifications off/on
- I have the Google Dialer set as a default phone app
- turn on the priority notifications for the Dialer

Unfortunately, still no luck.

**Comment by divadsn** [comment]
Tried with emulator, works fine with Google Dialer on 6.0, therefore I will close it.
