### ISSUE TITLE
[Feature request] Named sections, frequently launched apps to find apps faster

### ISSUE THREAD

**Issue by rmenessec** [Deletescape-Media/Lawnchair#1152]
## Description
I have just under 300 apps installed on my primary Android device. It would be lovely if I could create a few sections to break up the visual monotony of the Very Long List and find apps faster by skipping right to the section I've created for them.

I'm envisioning a very simple layout: each section separated by one half or one full icon row of blank space and a left-aligned section header with large, user-defined section label text using a full icon row, with horizontal bar under the header text. That would keep the metrics simple. (Support for a user-defined icon in front of the header text would be great.)

In addition, having a configurable "frequently launched apps" and/or pinned apps row at the top—maybe fixed relative to the scrolling apps list?—would make finding apps lightning-fast.

I think that Lawnchair's great, but I'm using another launcher in the meantime while I wait for a feature like this. It just takes too long to locate the app I need to launch.

**Comment by Frontear** [comment]
Great idea! It would take a lot of time to implement though. Maybe v2?

**Comment by rmenessec** [comment]
@Frontear , I'm just hoping for "soon." 😉

**Comment by bohrabhijeet** [comment]
@rmenessec "Soon" is actually soon ;)

**Comment by rmenessec** [comment]
@abhijeetbohra , hurray!

**Comment by asherpen** [comment]
I want to sort the apps by usage frequency, thank you!

**Comment by fonix232** [comment]
@asherpen commenting the same shit on every ticket will just gonna get you blocked from the repos. This is your first and final warning.
