### ISSUE TITLE
Let the screens cycle on desktop or let user select any of the screen as home screen

### ISSUE THREAD

**Issue by sultanahamer** [Deletescape-Media/Lawnchair#1153]
Summary:
Let the screens cycle on desktop or let user select any of the screen as home screen

## Description
I want to have my home screen with icons that I use a lot on my home screen and swipe left giving me calendar widget screen and swipe right to be another screen with more icons that I rarely use.

To achieve this, right now, I have to move all my icons one by one from home(1st screen) to next screen. Then create calendar widget on left and few more icons on right.

## Expected Behavior
I should be able to cycle through all home screens that way I can swipe left and get last screen from the right. 

## Actual Behavior
I am not able to swipe left from 1st screen.

## Steps to Reproduce
1. Create a new screen on desktop
2. Try to swipe left

## Environment
Device: Infocus bingo 21
Android version: 6.0.1
Launcher version: 1.1.0.1742 (1742) - Added on 2018-02-16 - from f-droid
Rom: Stock Rom from Infocus

**Comment by divadsn** [comment]
@sultanahamer Sorry, that's not the Pixel style, we can't do it.

**Comment by sultanahamer** [comment]
Oh, is it coz left swipe takes you to google now??

**Comment by divadsn** [comment]
@sultanahamer Not only that, the first left screen has the Google Pill widget, with the intended left side of the pill being the first page.

**Comment by sultanahamer** [comment]
Cool, will close this issue then.

**Comment by fghsgh** [comment]
It could still be an option in the settings, couldn't it?

**Comment by andrewteg** [comment]
Know this is old, but any chance the dev thoughts have changed and would consider this an option like @fghsgh mentioned?  For my purpose, it'd be nice to scroll left or right to infinite scroll, and I have always thought that and making a different the primary home screen are things missing from the Pixel launcher.  Thanks for considering.
