### ISSUE TITLE
Fire HD - Your device isn't comaptible with this version.

### ISSUE THREAD

**Issue by hackel** [Deletescape-Media/Lawnchair#1156]
When I try to install Lawnchair on a Fire HD 8 tablet (Fire OS 5.9.0.1 based on Android 5.1) through the Play Store (sideloaded), I get the message "Your device isn't compatible with this version."  I manually installed 1.1.0.1742 from the releases page and it seems to be working fine.  It would be great to be able to get updates directly from the Play Store.

**Comment by divadsn** [comment]
Tablets aren't supported during alpha stage, that's a Play Store restriction.
