### ISSUE TITLE
'Trimming' icons

### ISSUE THREAD

**Issue by unrooted** [Deletescape-Media/Lawnchair#1161]
I'm trying to fix it in some ways, but icons on my home screen are little 'trimmed', can you look for it? Maybe that's problem with my DPI, but if it matters, my settings for Lawnchair are 9 icons in dock and I don't know what happened with date and clock. Greetings, Root

**Comment by divadsn** [comment]
Hey, thanks for the report. Can we have a screenshot for reference please? And also, do you use a custom DPI value or what phone?

**Comment by unrooted** [comment]
![screenshot_2018-03-02-07-35-31](https://user-images.githubusercontent.com/30440603/36886724-072e79a6-1dee-11e8-9dda-dcce637df8e9.png)
My phone is Nexus 6P on an AOSP based ROM

**Comment by nyancrimew** [comment]
This isn't really a DPI issue, depending on the icon size and count this can happen on all devices, I have already spent over 5 hours investigating this issue a while ago, but I have so far been unable to find the cause.

It happened with the original icon scaling algorithm, as well as with our custom, for adjustments improved completely rewritten algorithm.

**Comment by unrooted** [comment]
You can see that 'trim' on settings icon and date (there's trimmed 'Friday 2018')

**Comment by nyancrimew** [comment]
By that I do not mean it can't be fixed, but just that maybe someone else than me might have more luck in solving it (wink, wink @divadsn, @paphonb)

**Comment by nyancrimew** [comment]
The trimming of the Date is probably related to something else actually, but it still is an issue nevertheless

**Comment by unrooted** [comment]
Icon scale is 60%, height is 90% (that's for my dock) and settings for home screen are normal

**Comment by paphonb** [comment]
@RootKlawiter
