### ISSUE TITLE
[Feature Request] Automatic Settings/Layout Backup

### ISSUE THREAD

**Issue by Mushoz** [Deletescape-Media/Lawnchair#1163]
I often play around with different ROMs and flash _a lot_. It would be amazing if settings and the layout of the launcher would be backupped once a day and stored on Google Drive, so that each time I restore a device from the cloud that when all my previous apps are automatically pulled from the app store, lawnchair will be able to automatically restore its settings and layout as well.

**Comment by divadsn** [comment]
It's already a feature for v2, stay tuned! :)

**Comment by Mushoz** [comment]
Wow, that must have been the fastest response I've ever received on Github :) Amazing work and thank you very much for making this all a possibility :)
