### ISSUE TITLE
[Feature Request] Export settings to internal storage / sync across clients 

### ISSUE THREAD

**Issue by Nevexo** [Deletescape-Media/Lawnchair#1164]
As the backup for settings is currently stored in the app's hidden directories they can't be shared with others or taken between devices, I'd like to be able to export it into the public storage of the device.

For copying settings to other devices, maybe a simple service using Google oauth for login could be used to sync the settings across devices. 

Thanks, 
Nevexo

**Comment by divadsn** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/LawnchairLauncher/Lawnchair/issues/664 (Feature request :)), https://github.com/LawnchairLauncher/Lawnchair/issues/1102 (Feature Requests), https://github.com/LawnchairLauncher/Lawnchair/issues/583 (Features request), https://github.com/LawnchairLauncher/Lawnchair/issues/590 (Feature Request), and https://github.com/LawnchairLauncher/Lawnchair/issues/598 (Feature request).

**Comment by Nevexo** [comment]
@divadsn that's weird. It has nothing to do with any of those feature requests.

**Comment by divadsn** [comment]
@Nevexo Uhm, it has, all of that is already mentioned in those

**Comment by Nevexo** [comment]
@divadsn oh, bit weird evrrytime I open them they are different, fasthub must be messing up Sorry

**Comment by divadsn** [comment]
Actually GitMate messed up, but this was already proposed in #1163 and has been added for v2.
