### ISSUE TITLE
[bug] Blur effect strange on lower value.

### ISSUE THREAD

**Issue by FelixAgairu** [Deletescape-Media/Lawnchair#1169]
## Description
While blur radius goes lower about 25, the wallpaper appear many stairs steps.
Larger values work fine.

## Expected Behavior
Smooth blur effect in both color edges and lines even in lower given blur radius.

## Actual Behavior
Stairs shows up and turn line to stairs. Such as a picture use black stroke.

## Steps to Reproduce
Screenshot:
https://1drv.ms/u/s!AkL-7NgRmjYBhthRPkg4e34DqFFyEg

1. Select a picture which has many strokes and set it as wallpaper.
2. Open LawnchairLauncher setting.
3. Into "Theme" : Enable "Enable Blur", Set "Apply Blur to" at least choose the "Dock & Drawer", set "Blur Radius" to 10.
4. Into "App drawer" : Slide "Drawer Opacity" lower ( to make drawer transparent. Such as "0%").
5. Back to home screen then open drawer.
6. Should looks odd like screenshot say.

## Environment
* Device: Xiaomi 5 (3 GB RAM) "Gemini"
* Android version: 8.1.0
* Launcher version: 1.1.0.1472
* Rom: Custom ROM RR base on Lineage OS

**Comment by divadsn** [comment]
Well, it's kinda expected I would say, waiting for @deletescape to comment onto that.

**Comment by fonix232** [comment]
It is indeed expected, afaik the blur provider uses integers for steps instead of decimals to provide faster drawing.

Instead of the current setup I'd like to recommend using the screen height/total movement distance for blur steps (e.g. drawer pulling up on a 1920px height, with the drawer being, say, 320px, would mean 1600 distinct steps).

**Comment by FelixAgairu** [comment]
More. On drawer pulling up and down, it looks it doesn't has any issue, the blur effect works perfectly and smoothly (in drawer open and close, no stairs).
