### ISSUE TITLE
Pull-up Handle Not Transparent

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#117]
Look at the dock on these two pictures. I would like the Pull-up handle to also be in transparency, as shown in the first picture
![screenshot_2017-07-03-13-39-38](https://user-images.githubusercontent.com/29732079/27803179-326a7b76-5ff6-11e7-971f-e3d422bf1919.png)
![screenshot_2017-07-03-13-39-40](https://user-images.githubusercontent.com/29732079/27803191-3e8fd7ac-5ff6-11e7-9ddb-4492713d0478.png)

**Comment by deletescape** [comment]
It's not supposed to be transparent

**Comment by deletescape** [comment]
But I might add a seperate option to hide it
