### ISSUE TITLE
Long press on icons with dark theme no text visible

### ISSUE THREAD

**Issue by MaiBpenRai** [Deletescape-Media/Lawnchair#1178]
##Description
When the dark or grey theme is activated and you long press any icon on the home screen and in the app drawer, you get a black box without text for selection. Everything is fine in the light theme.

## Expected Behavior
There should be white text on black background

## Actual Behavior
There is a black box without text (i am guessing the text is there but in black too)

## Steps to Reproduce
Long Select any icon on home screen or app drawer , till the selection window opens

## Environment
Newest lawnchair 1.1.0.1868
On M-Horse pure 2 with stock firmware
Previous version of lawnchair was fine

**Comment by marrco** [comment]
Confirmed. And the text is indeed present, black on very dark background. 

Using 1.1.0.1868 on a Honor 9 lite w/ Oreo. The previous version was fine

**Comment by divadsn** [comment]
@marrco Added to HIGHVERYIMPORTANTLIST for @deletescape 😂

**Comment by divadsn** [comment]
@divadsn /😂

**Comment by shubhchan** [comment]
@divadsn Lul
