### ISSUE TITLE
Incorrect position of app bubble on desktop when using RTL locale.

### ISSUE THREAD

**Issue by forabi** [Deletescape-Media/Lawnchair#1180]
## Description
Incorrect position of app bubble on desktop when using RTL locale. In the following screenshots, the bubble for WhatsApp is away from the icon:

![img-20180324-wa0002](https://user-images.githubusercontent.com/1012761/37863053-551ae572-2f60-11e8-9221-01216ea58de9.jpg)

## Expected Behavior
The bubble should be close to the app icon

## Actual Behavior
The bubble is not close to the app icon

## Environment

* Device:
* Android version: 7.0
* Launcher version: 1.1.0.1868
* Rom: Samsung Experience 8.0 (stock Samsung ROM)

**Comment by divadsn** [comment]
@forabi thanks, RTL support is already on the list for final release.

**Comment by yosimor** [comment]
Duplicate of #977
