### ISSUE TITLE
lawnfeed keeps giving 'update available' notification but when I click on it, I get a pop up saying lawnfeed stopped working.

### ISSUE THREAD

**Issue by chessnut1** [Deletescape-Media/Lawnchair#1181]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
@chessnut1 please read the goddamn changelog notice...
