### ISSUE TITLE
Incorrect position of drawer arrow with no dock

### ISSUE THREAD

**Issue by ffeingol** [Deletescape-Media/Lawnchair#1182]
Hello Guys,

This was fixed before, but the issue is back with the latest Play Store version (1.1.0.1868).  If you have the Doc turned off the drawer arrow shows between the 1st and 2nd row of icons instead of under the 1st row.

Screen shot:

![rsz_screenshot_20180324-102853](https://user-images.githubusercontent.com/18329578/37865725-c20dd354-2f4e-11e8-84c7-b78136b95925.png)

**Comment by divadsn** [comment]
@ffeingol this is a supposed behavior, @deletescape has intentionally moved it back to the top.

**Comment by nyancrimew** [comment]
@divadsn I only moved it for the transparent dock, this however is a screenshot of the dock turned off completely
