### ISSUE TITLE
One layer mode

### ISSUE THREAD

**Issue by aniel300** [Deletescape-Media/Lawnchair#1183]
Would it be possible to add one layer mode to this fantastic launcher?

**Comment by divadsn** [comment]
What do you mean by "One layer" mode?

**Comment by aniel300** [comment]
No app drawer, all apps in home screen

**Comment by bohrabhijeet** [comment]
@aniel300 Vary nais.

**Comment by shubhchan** [comment]
@abhijeetbohra Well thats really easy ,just pull all apps in Drawer and forget that u have a swipe up gesture 🤷‍♂

**Comment by divadsn** [comment]
@shubhchan is this the Pixel style tho?

**Comment by abhijeetbohra** [comment]
@shubhchan Mujhe kyu reply kiya 😂

**Comment by shubhchan** [comment]
@divadsn Well its Chinese style 😂

**Comment by fonix232** [comment]
It does not match the Pixel/AOSP/Material style Lawnchair is going for. I doubt this will be implemented ever.
