### ISSUE TITLE
Long press icon text not showing.

### ISSUE THREAD

**Issue by GAZ082** [Deletescape-Media/Lawnchair#1191]
1. Long press a desktop icon.
2. Wait until the quick access menu is displayed.
3. Text is not shown or its same as the backgroud.

Version: 1.1.0.1868

Android 8.0, Sony XZ1 Compact.

Thanks!

![](https://dl2.pushbulletusercontent.com/T4Ze9ECkdkXbDUZVDPwxDMMpNiwg3CoT/Screenshot_20180327-171800.png)

**Comment by divadsn** [comment]
@GAZ082 Fixed in recent PRs, to be rolled out today.

**Comment by GAZ082** [comment]
That was fast, thanks!
