### ISSUE TITLE
Custom dock opacity setting takes no effect with blur on

### ISSUE THREAD

**Issue by hosimati** [Deletescape-Media/Lawnchair#1197]
## Steps to Reproduce

1.Settings -- Theme -- Enable blur
2.Settings -- Theme -- Apply blur on dock&drawer
3.Settings -- Dock -- Enable custom drawer opacity
4.Move the slider and compare the effects

**Comment by divadsn** [comment]
There is no point in having an opacity setting with blur enabled.
