### ISSUE TITLE
Backup (or restored backup) is incomplete

### ISSUE THREAD

**Issue by tp0** [Deletescape-Media/Lawnchair#1198]
## Description

Some settings are not either backed up or restored from the backup. For example but likely not limited to `Number of columns`, `Number of rows`, `Icon scale` under Settings > Desktop.

## Repro:

1. Change for example `Number of columns`, `Number of rows`, `Icon scale` settings under Desktop.
2. Take backup
3. Exit Lawnchair and reset app data
4. Launch Lawnchair and restore backup
5. Result: above settings are not restored.

## Environment
* Device: Motorola Moto G 3rd Gen
* Android version: 7.1.2
* Launcher version: 1.1.0.1872
* Rom: LineageOS 14.1

I installed 1.1.0.1742 (1742) from F-Droid, with has apparently the older backup/restore menu/screen and I could not reproduce this.

**Comment by yurtemre7** [comment]
Did you allowed Lawnchair storage-permission?

**Comment by tp0** [comment]
> Did you allowed Lawnchair storage-permission?

Yes. Double-checked now. And by all accounts the backup saving shouldn't work at all without storage permission.

**Comment by EliasSchriefer** [comment]
I also came over this issue, even without clearing the app data. (Tested with Homescreen rows and columns)
- Device: Huawei P8 Lite
- Android version: 6.0 (EMUI 4.0.3)
- Launcher version: 1.1.0.1872
- ROM: Stock

**Comment by kolAflash** [comment]
I observed, that sometimes also icons are not being backed up. This seems to be the case, if an icon has just been added before making the backup.

To me this looks like the Lawnchair app may not immediately store changes in the database file!? And the backup feature may not read the settings from the inside of the app, but instead backups and restores the settings database file!?
So when doing a backup, there may needs to be a trigger storing all recent changes to the database file before it's being backed up.

**Comment by msfjarvis** [comment]
> I observed, that sometimes also icons are not being backed up. This seems to be the case, if an icon has just been added before making the backup.
> 
> To me this looks like the Lawnchair app may not immediately store changes in the database file!? And the backup feature may not read the settings from the inside of the app, but instead backups and restores the settings database file!?
> So when doing a backup, there may needs to be a trigger storing all recent changes to the database file before it's being backed up.

Your in-depth diagnosis is very appreciated, care to send a PR to correct this? :smile:
