### ISSUE TITLE
Preference changes aren't properly applied

### ISSUE THREAD

**Issue by deletescape** [Deletescape-Media/Lawnchair#12]
For now, force closing the launcher is the only way to apply all the settings, we need to fix this asap

**Comment by deletescape** [comment]
I closed the wrong issue, lol

**Comment by deletescape** [comment]
Seems to be working for everything except row and column icon counts

**Comment by NachiketNamjoshi** [comment]
Restarting the app after setting it up seems to be the only way.. AFAIK 
So we implement the logic in the app?

**Comment by deletescape** [comment]
I think the best way to make sure settings are applied is actually adding some kind of reload logic to pretty much everything :joy:

Most of the things are already reloaded right now. There was some logic to kill the process and start it again in the past, but the app ended up in a weird state and wasn't usable at all, also it isn't really great in terms of ux
