### ISSUE TITLE
Version 1872 , swipe right Google now is empty

### ISSUE THREAD

**Issue by papampi** [Deletescape-Media/Lawnchair#1201]
Upgraded my galaxy tab s3 and Moto z to v 1872 and on both devices Google now page on swipe right is blank, but if open Google now app it shows all the stuff it should.

**Comment by nyancrimew** [comment]
@papampi This is a bug introduced by google, we have no control over how the google now tab appears

**Comment by papampi** [comment]
Thanks for info
Just tried this pixel 2 launcher 
https://forum.xda-developers.com/android/apps-games/app-rootless-pixel-2-launcher-google-t3688393
and its google now swipe right works.

**Comment by divadsn** [comment]
You have to enable your Now feed in the Google app, otherwise it won't work obviously.
