### ISSUE TITLE
How to center the icon in HotSeat

### ISSUE THREAD

**Issue by PureAway** [Deletescape-Media/Lawnchair#1202]
As title, if icons should be centered to the display in Hotseat.(different than stock android, similar to some samsung devices) Can it work?

**Comment by divadsn** [comment]
How?

**Comment by nyancrimew** [comment]
Please rephrase your issue and add some screenshots and then open it again

**Comment by PureAway** [comment]
<img width="370" alt="1" src="https://user-images.githubusercontent.com/10737801/38399121-f5ca60e6-397a-11e8-8378-c794c8c4e8a1.png">
<img width="365" alt="2" src="https://user-images.githubusercontent.com/10737801/38399128-ff796204-397a-11e8-8d7b-bcb7cfa18a21.png">
<img width="365" alt="3" src="https://user-images.githubusercontent.com/10737801/38399133-08223796-397b-11e8-8d44-3f1175e84e22.png">
<img width="370" alt="4" src="https://user-images.githubusercontent.com/10737801/38399140-1018a340-397b-11e8-8d38-5d3f1eba3bf0.png">
<img width="370" alt="5" src="https://user-images.githubusercontent.com/10737801/38399149-1821ef6a-397b-11e8-974d-887a81bd9a23.png">
Such as this: all of the icons displayed centered on hotseat, similar to macosx's dock.

**Comment by divadsn** [comment]
Just change rhe amount of icons in the dock settings.

**Comment by fonix232** [comment]
IMO the amount should denote the maximum number of items, and otherwise center it like the image posted. It's the default on pretty much all the major launchers, including stock ones, and users expect this behaviour - the number setting might be misleading since it means the maximum number in other cases.
