### ISSUE TITLE
Multiple dock pages.

### ISSUE THREAD

**Issue by joshuamjiji** [Deletescape-Media/Lawnchair#1203]
Suggestion
Hello.
Can you please add multiple dock pages features in Lawnchair just like in Nova launcher Il liked it very much but since I am fully into open source apps I can't use this feature. Its my humble request plzzz add this feature plzzz.

Thank you

**Comment by divadsn** [comment]
@thematrjx sorry but no, we are respecting other Launchers and won't include that, as it is not the Pixel style.

**Comment by divadsn** [comment]
We already added two row dock for people to have more space to customize, whether to add a searchbar widget or just play around with KWGT.

**Comment by joshuamjiji** [comment]
Thanks for your reply it means a lot. And your point is true, sorry if my suggestion wasted your valuable time. And keep doing this awesome work for the people like us and I will try my best to contribute in your great project.

Thank You
