### ISSUE TITLE
App drawer > Hidden Apps > Lawnchair Not Checked But Hidden?

### ISSUE THREAD

**Issue by 0pLuS0** [Deletescape-Media/Lawnchair#1205]
## Description
Lawnchair app doesn't appear in the App drawer

## Expected Behavior
I assumed that Lawnchair should appear in the App drawer?

## Steps to Reproduce
1. I install Lawnchair
2. After installing Lawnchair I look in the App drawer and it doesn't appear.
3. In the Lawnchair settings > App drawer > Hidden Apps > I check and uncheck it, but no luck...

## Environment
Device: Mi A1
Android version: Oreo 8.0.0 - Patch level March 2018
Launcher version: 1.1.0.1872
Rom: Stock Android One

By the way Lawnchair is awesome, I really love it, and how it just keeps Android One pretty much stock, keep up the great work! :)

**Comment by suphon-t** [comment]
It is hidden in Lawnchair because clicking is not going to do anything useful.

**Comment by 0pLuS0** [comment]
@paphonb well it seems to make sense it should be removed then from the settings > App drawer > Hidden Apps, which just confuses people into thinking you can hide it, because it's suppose to appear in the App drawer... :)

That's why I reported it... 

Thanks

**Comment by fonix232** [comment]
@paphonb I agree, I think we should make Lawnchair un-uncheckable in the hidden apps list.
