### ISSUE TITLE
Android Gradle plugin: closed-source ALPHA version used

### ISSUE THREAD

**Issue by ildar** [Deletescape-Media/Lawnchair#1206]
what was the particular reason to switch to ALPHA version of Android Gradle plugin?

According to [relan](https://gitlab.com/fdroid/fdroiddata/issues/1167#note_65174445):
> Unfortunately, 1.1.0.1868 uses com.android.tools.build:gradle:3.2.0-alpha06.
> Google does not publish source code of pre-release versions of Android Gradle plugin, so it's proprietary software.

So this commit effectively makes Lawnchair closed-source.
Ref: https://github.com/LawnchairLauncher/Lawnchair/commit/210394f23848c25d5246ae7040f040b72f722762
Blocks: https://github.com/LawnchairLauncher/Lawnchair/pull/1157

**Comment by msfjarvis** [comment]
I have seen all kinds of shit in the issues section of this repository but this is by far the most retarded issue ever.

**Comment by divadsn** [comment]
@ildar And now what?

**Comment by ildar** [comment]
1st, guys, I didn't mean to offend anyone. The issue only contains a
**question**, no "demands/requests/whatever". I don't think a simple
technical question should raise a reaction like this.
Next, the reason behind this question is quite clear: it blocks your,
David, own work in the PR. I though it could be meaningful.
Sorry if technical questions aren't welcome here.

**Comment by divadsn** [comment]
@ildar no it's like no one cares if the software we use to compile is closed source or not, it doesn't matter for the end product as the source of Lawnchair is open anyways. By using alpha we are just preparing for newer Android versions and bleeding edge technologies, like dockerizing our builds.

**Comment by ildar** [comment]
Ah! clear answer! ok!
THANKS.
Then what do you think if the FOSS flavor will fix it to the release
version? Will it break anything?

**Comment by divadsn** [comment]
@ildar It will break support in Android Studio, which surprise, is also closed source. The foss flavor is expected to be rolled out as the final features are added.

**Comment by ildar** [comment]
What about Gradle build. Will it work?

**Comment by divadsn** [comment]
I left my opinion over at F-Droid, it's ridiculous IMO but I reverted that as Android Studio 3.1 stable has been released a week ago, so it should work fine now I hope.

See commit 5d3292f and [this](https://gitlab.com/fdroid/fdroiddata/issues/1167#note_67836381) for more details.

**Comment by ildar** [comment]
David, that's great, thanks a lot.
Sidenote: regarding overconcerning the FOSS versus non-FOSS components for
build: that's the core idea for F-Droid so it can't be just passed over.
Thanks for your attention to my requests.
