### ISSUE TITLE
Lawnchair crashes and prompts to upgrade Lawnfeed

### ISSUE THREAD

**Issue by Nonononoki** [Deletescape-Media/Lawnchair#1208]
## Expected Behavior
No crashing
There is no prompt to upgrade Lawnfeed if Lawnfeed is not installed.

## Actual Behavior
Crashing message
Lawnchair prompts to upgrade Lawnfeed despite the fact that it is not installed at all.

## Steps to Reproduce
Install Lawnchair from F-Droid
Go to Lawnchair settings
Change Icon shape

## Environment
* Device: ZUK Z2
* Android version: 8.1.0
* Launcher version: 1.1.0.1742
* Rom: AEX AOSP Extended
* Gapps: MicroG

**Comment by divadsn** [comment]
@Nonononoki Closing, please update Lawnchair, thanks.

**Comment by Nonononoki** [comment]
@divadsn But it IS the latest version: https://f-droid.org/en/packages/ch.deletescape.lawnchair.plah/

**Comment by divadsn** [comment]
@Nonononoki We do not handle issues for F-Droid, please have a look at the releases in the repo or on the anti-privacy Google Play Store.
