### ISSUE TITLE
Lawnfeed update required

### ISSUE THREAD

**Issue by foosinn** [Deletescape-Media/Lawnchair#1209]
## Description

Using a phone with lineageos, microg and lawnchair (from microg) results in a error message that it needs to download lawnfeed.

As far as i understood: there is no need for lawnfeed if i do not have google now installed.

## Expected Behavior

Make lawnfeed optional, or even detect if there is no google now.

## Actual Behavior

After every restart i get kindly asked to download lawnfeed.

## Steps to Reproduce

1. install microg rom from https://lineage.microg.org/
2. install lawnfeed
3. use lawnfeed

## Environment
* Device: Nexus 5x
* Android version: Lineageos 15.1
* Launcher version: 1.1.0.1742

Thanks!

**Comment by divadsn** [comment]
@foosinn Update Lawnchair, kthxbye.
