### ISSUE TITLE
Crash when changing icons for 'Work' apps.

### ISSUE THREAD

**Issue by ceiphr** [Deletescape-Media/Lawnchair#1211]
## Description

I have a work container on my device that is managed by an app called Island (made by the greenify developer). Apps within this work container have a little suitcase next to the app icon. When attempting to edit the app icon, Lawnchair crashes and must restart. 

## Expected Behavior

The icon changing menu should appear to select a new icon from a pack.

## Actual Behavior

Lawnchair Crashes.

## Steps to Reproduce

1. Have a work container with app installed in it.
2. Open edit menu
3. Attempt to change icon
4. Lawnchair crashes

## Environment

* Device: Samsung Galaxy S7 Edge
* Android version: 7.0
* Launcher version: 1.1.0
* Rom: Stock Rom

**Comment by divadsn** [comment]
@ceiphr @paphonb has work apps, can you confirm that too?
