### ISSUE TITLE
A RTL Bug in the Hebrew Version

### ISSUE THREAD

**Issue by eyal-sasson** [Deletescape-Media/Lawnchair#1213]
## Description

In the Hebrew version, there is a RTL bug, when I do a long press on an app, the shortcut window is showing in the right, and not above the app icon.

## Steps to Reproduce

![screenshot_20180417-073534](https://user-images.githubusercontent.com/37512471/38848879-207514fe-4212-11e8-9752-879ac4167530.png)

## Environment

* Device: Nexus 5X
* Android version: 8.1
* Launcher version: lastest (1.1.0.1872)

**Comment by divadsn** [comment]
@eyal100 RTL Support is currently on our list, please be patient :)

**Comment by bsagal** [comment]
I think this is a duplicate of #1180

**Comment by yosimor** [comment]
Duplicate of #977 as well.
