### ISSUE TITLE
[Suggestion] Static Wallpaper

### ISSUE THREAD

**Issue by toompitow** [Deletescape-Media/Lawnchair#1215]
Wallpapers are scrolling. It is the default behaviour of many launchers.

That causes two problems though: 
1- the scrolling can be slow on some Phone, the performances are lowered because of the scrolling wallpaper.

2- the wallpaper definition has to be huge so it doesn't look pixelated.

I think it would be great to be able to prevent wallpaper from scrolling. It would also prevent user from having to crop every picture to manually get them to "static" .

**Comment by divadsn** [comment]
@toompitow Already in list

**Comment by fghsgh** [comment]
I also had to crop my wallpaper to exactly fit the screen, but it would be nice if this option were added.

**Comment by gardiol** [comment]
I also second this. I have an animated wallpaper which fits one screen and its very annoying to see it "change" when switching page. More.so, please add an option NOT to change the wallpaper when switching page
