### ISSUE TITLE
Option to NOT show hidden apps in search

### ISSUE THREAD

**Issue by source124** [Deletescape-Media/Lawnchair#1216]
## Description
Many people want hidden apps to be visible in search results. The _original behavior_ (hidden even in search results) should be present as an option.

## Environment
* Android version: 8.0
* Launcher version: 1.1.0.1872

Thank you :)

**Comment by Frontear** [comment]
I personally am against this. I prefer to hide apps that I don't use (Samsung bloatware, etc), but still have a use for. I don't want to go into settings and show them just to use one app.

**Comment by source124** [comment]
Perhaps I wasn't clear. I don't call for the current behavior to be removed; just to be optional.

Example of a setting:
Show hidden apps in search (On/Off).

It can even be on by default. I just want the **option**.

**Comment by divadsn** [comment]
@source124 Ahhh k, that should be easy then ^^

**Comment by source124** [comment]
Thanks :)
