### ISSUE TITLE
Double tap on/of screen  not working.

### ISSUE THREAD

**Issue by dangrigore7** [Deletescape-Media/Lawnchair#1220]
## Description
<!-Double tap on/of screen not working-- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:Blackberry Motion 
* Android version:Android version: 7.1.2 
* Launcher version:auncher version: 1.1.9.9136
* Rom:Rom: Stock

## Logcat

```
your log here
```

**Comment by fonix232** [comment]
Please use the template provided to describe your issue. It's there for a reason...
