### ISSUE TITLE
Option to hide the search bar in the app drawer

### ISSUE THREAD

**Issue by aartoni** [Deletescape-Media/Lawnchair#1221]
I know this was asked before in #1102, and the answer was "this is not Pixel style", but as you can see in my screenshot the search bar isn't of any use at all if your apps are all visible in a single screen, also if you have a few more it will prevent you from viewing them in a single screen.

![screenshot 1](https://user-images.githubusercontent.com/34690870/39410299-cdecacb2-4bf6-11e8-9f75-442b436b7415.png)

**Comment by electricflock** [comment]
I likewise have a small-screen device with only a few apps, and would just like a checkmark to disable the search bar. 
This is the only issue/request I have for an otherwise perfect launcher!

**Comment by SapneshNaik** [comment]
I also second my support for this feature. For my minimalistic single screen app drawer, the search bar is the only distraction. Can you please add the ability to hide it?
