### ISSUE TITLE
Wrong app drawer color

### ISSUE THREAD

**Issue by aartoni** [Deletescape-Media/Lawnchair#1222]
I'm not a graphic design expert but i think app drawer's background should be as dark as possible when set to black, in the screenshot you can clearly see that it is lighter than the black wallpaper.

[Edit] Seems to be fixed.

![screenshot](https://user-images.githubusercontent.com/34690870/39410479-1385f4fc-4bf9-11e8-8946-3711d60ecac6.png)

**Comment by divadsn** [comment]
I'm neither a graphic design expert too, therefore closed. Please describe it at least so we can reproduce it on our own way.
