### ISSUE TITLE
Google "At a Glance" widget is always too large to place

### ISSUE THREAD

**Issue by CometDog** [Deletescape-Media/Lawnchair#1224]
Device: Pixel 2 XL
OS: Android P (API 27)

Placing the "At a glance" widget on LawnChair always causes the "no room" toast to appear. Increasing row/column size does not help. Stepping through the code, as I increase the row/column size, the widget size "increases" so it's always out of range of the home screen size. 

This is similar to issues https://github.com/LawnchairLauncher/Lawnchair/issues/1195 and [INSERT] but very specifically targets this widget, as all others work on my device. It's possible this is an artifact of it being in beta but it may be worth looking at since it may not be device specific (unless P is causing this somehow).

**Comment by divadsn** [comment]
@PiwwowPants Beta software, closed.
