### ISSUE TITLE
Shortcuts appear on Desktop even if it's locked

### ISSUE THREAD

**Issue by tibyandy** [Deletescape-Media/Lawnchair#1225]
## Description

When installing a new app from Google Play Store, even with the Lock Desktop option turned on, a new shortcut icon for it appears (and eventually new Desktop Panels too, if they don't fit the existing Panels).
Since the Desktop is locked, I'm unable to remove the automatically created shortcut, unless I disable this option.

## Expected Behavior

When the Desktop is locked, no changes should happen at all on the Desktop. 

## Actual Behavior

Apps installed from Google Play Store automatically create shortcut icons on the Desktop. 

## Steps to Reproduce

1. Open Lawnchair Settings 
2. Choose "Behavior"
3. Switch on "Lock desktop" 
4. Install an app using Google Play Store
5. A new unremovable shortcut for that app will be created on the Desktop 

## Environment

* Device: Sony Xperia Z5

* Android version: 7.1.2

* Launcher version: 1.1.0.1872

* Rom: Stock Rom

**Comment by LinuxLlama** [comment]
A simple workaround would be to open the Play Store, slide out the side menu, tap settings, then uncheck "Add icon to Home screen."
