### ISSUE TITLE
Long press doesn't work after screen rotation. 

### ISSUE THREAD

**Issue by changty6** [Deletescape-Media/Lawnchair#1226]
## Description

The long press is failed after I rotate the screen (Auto-rotate is on). I cannot use long press neither in desktop nor on icons. And I can not call the menu so I have to go to system settings to force stop the launcher to restart. 

## Expected Behavior

The long press both on desktop and icons should work all the time.

## Actual Behavior

The long press fails after rotating the screen. 

## Steps to Reproduce

1. Go to the launcher Settings -> Behavior -> Enable screen rotation.
2. Pull down the system notification menu -> turn on Auto-rotate.
3. Rotate phone. 
4. The long press is failed. 

## Environment

* Device: Pixel XL
* Android version: 8.1.0
* Launcher version: 1.1.0.1872
* Rom: Stock Rom

## Logcat

```
your log here
```

**Comment by minhdangoz** [comment]
I think that we can fix this issue by editing Launcher.java like this:
return mWorkspace.isInOverviewMode() instead of false
@Override
    public boolean onLongClick(View view) {
        CellLayout.CellInfo cellInfo = null;
        if (!isDraggingEnabled() || isWorkspaceLocked() || this.mState != State.WORKSPACE) {
            // return false;
            mWorkspace.isInOverviewMode();
        }

**Comment by TomJansen** [comment]
Long press does not work for me, but I after reinstalling the app I can't seem to reproduce this bug with your instructions.

**Comment by TomJansen** [comment]
Ah I found it.
## Steps to reproduce
1. Go to the launcher Settings -> Behavior -> Enable screen rotation.
2. Pull down the system notification menu -> turn on Auto-rotate.
3. Rotate phone **in app drawer**
4. The long press is failed.

The issue is fixed when I build the app from the master branch
