### ISSUE TITLE
App drawer in desktop option like iOS

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1230]
create an option to set the desk as a drawer

**Comment by shubhchan** [comment]
@Tuxi Why tho? Its not iOS

**Comment by ghost** [comment]
I think that an extra option is not a bad idea. I said iOS? ok! So MIUI Launcher? do you digest it more? :stuck_out_tongue_winking_eye:

**Comment by fonix232** [comment]
No. Lawnchair is going for a Pixel Launcher look. Having the desktop as the drawer is against that on pretty much every level.

**Comment by ghost** [comment]
Ok

**Comment by minhdangoz** [comment]
I have done this option for my own

**Comment by divadsn** [comment]
We are a Pixel style launcher :wink:

**Comment by yuxingfafu** [comment]
@minhdangoz can you share you idea or code ?you done style like ios launcher or like MIUI Launcher? please thank you，i want to found a solution,but can not found,I am very  worried
