### ISSUE TITLE
Google Wallpapers app doesn't appear in app drawer

### ISSUE THREAD

**Issue by Keith94** [Deletescape-Media/Lawnchair#1231]
For some reason, the Wallpapers app doesn't appear at all, and I made sure it was NOT hidden via the settings. Sorry for the quick summary - on mobile atm.

**Comment by suphon-t** [comment]
The wallpapers app is hidden from the app drawers like on Pixel Launcher. You can still access it by long pressing a blank space and click wallpaper.

**Comment by Keith94** [comment]
You're right; thanks for the tip!
