### ISSUE TITLE
Move searchbar to bottom of desktop

### ISSUE THREAD

**Issue by Keith94** [Deletescape-Media/Lawnchair#1233]
I didn't see an option for enabling this; if there's a way, let me know.

**Comment by LinuxLlama** [comment]
You can't move it to the bottom. Alternatively, you can place a custom widget instead.

**Comment by Keith94** [comment]
I guess that works, but an option to move to bottom would be nice too.

**Comment by Keith94** [comment]
In v2, the search bar is at the bottom by default.
