### ISSUE TITLE
Unable to send intents for 5 seconds after pressing home button. Link in description

### ISSUE THREAD

**Issue by kshksdrt** [Deletescape-Media/Lawnchair#1235]
## Description
When you press "home" Android will introduce a 5 secs delay to any app and service trying to execute an intent unless the app sending that intent is the current launcher. Here's a workaround - https://help.kustom.rocks/i194-launchers-touch-features-support-aka-remove-5-secs-delay

## Expected Behavior
To be able to send intents as soon as the home button is pressed

## Actual Behavior
Unable to send intents for 5 seconds after the home button is pressed

**Comment by divadsn** [comment]
On the list for later

**Comment by divadsn** [comment]
Actually we already have that added:
https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/app/src/main/AndroidManifest.xml#L121-L131

**Comment by zero41120** [comment]
The release on June 2020 from APK mirror has the 5 second delay. This issue was back in 2018, I assume something changed. Maybe we should reopen this issue
