### ISSUE TITLE
Lawnchair is stopping when changing icon texture

### ISSUE THREAD

**Issue by what-rf** [Deletescape-Media/Lawnchair#1238]
## Description
Lets say that the icon pack i use have 2 or more texture for the same app.i dont like how the aparence is by "default",so i change manually the texture of the app,and boom,lawnchair stops. PS:i have the candycons and the pixbit icon packs.

## Expected Behavior
Change the texture succefuly.

## Actual Behavior
Lawnchair stops.

## Environment

* Device:BLU energy diamond mini
* Android version: 5.1 lollipop
* Launcher version: 1.1.0.1872
* Rom: stock rom
* Rooted: no (already was rooted)
* Lawnchair downloaded from: apkmirror

**Comment by divadsn** [comment]
Hmm, that's strange, can you please provide a logcat for us?

**Comment by what-rf** [comment]
How can i give you a logcat?
(Im new here)

**Comment by shubhchan** [comment]
@Rayanfhoula15 -open ur Mac /PC 
-Open command prompt /terminal
-connect ur phone via USB after re creating bug
- type `adb devices'
- it will show some random number 2933djdi3 or such (ur device)
-then type 'adb logcat ' and boom copy and send




Also u can do that via any logcat app in play store if u use root

**Comment by what-rf** [comment]
There you go. https://github.com/LawnchairLauncher/Lawnchair/issues/1243

**Comment by divadsn** [comment]
If you could provide us a full logcat with the entire exception, it would be great. Otherwise we will try to see that on the Play Console and fix it.

**Comment by divadsn** [comment]
Oh, didn't meant to close that one, lul
