### ISSUE TITLE
[Feature Request] add sort options and menu to App Drawer

### ISSUE THREAD

**Issue by zilexa** [Deletescape-Media/Lawnchair#1241]
Note this is a FR not a bug. 
The FAQ section of the homepage directed me here to create feature requests.

## Description
The famous and much appreciated launchers from HTC used to have a few useful options at the top of the app drawer: 
[example ](https://i2.wp.com/ausdroid.net/wp-content/uploads/2015/04/HTC-Sense-7-App-Drawer-1.png)
FR 1. a menu button to sort the apps 1) Alphabetical 2) by date 3) custom. 
FR 2. a settings button to open the Launcher settings.
FR 3. The same seetings button could give direct access to App drawer settings such as grid (columns x rows). 
~~FR 4. a Play Store button to open the Play Store directly.~~

## Expected Behavior
Have a look at this [example](https://i2.wp.com/ausdroid.net/wp-content/uploads/2015/04/HTC-Sense-7-App-Drawer-1.png).
The search bar takes up the full width of the App Drawer. Add 2 buttons to support the features as described above.

## Actual Behavior
Currently the top of the App Drawer consists entirely of a search bar.

## Steps to Reproduce
Since this is not a bug, there is nothing to reproduce.

**Comment by divadsn** [comment]
@zilexa Why the hell do you need a Play button, that's useless.

**Comment by zilexa** [comment]
I guess that one is not the most important one. I personally always found it weird to search for the Play store somewhere in my list of apps (switching from an HTC). I will change the FR.

**Comment by divadsn** [comment]
@zilexa Just a small tipp, you can search directly for apps in the drawer and it will suggest you taking to the Play Store 😉

**Comment by zilexa** [comment]
Thanks! I actually never knew that one. I have removed the Play button from the request :)

**Comment by zilexa** [comment]
I was actually going to add another FR (feel free to say you will never implement it) but I believe that one could be a lot of work, so it deserves its own ticket: allow folders (just like on the Desktop) in the App Drawer.

**Comment by bohrabhijeet** [comment]
@zilexa We have that in our to-do list. Will let the developers know about that.

**Comment by zilexa** [comment]
@abhijeetbohra do you mean folder support for app drawer?

**Comment by asherpen** [comment]
I want sort the apps by usage frequency, thank you!
