### ISSUE TITLE
(Function Request) Inbuilt Applock 

### ISSUE THREAD

**Issue by weirdeep** [Deletescape-Media/Lawnchair#1242]
There should be in-built Applock function in this launcher

I have tried bunch of 3rd party Applock apps but all of them suffered lag issue on my RN3. One could easily see the contents of an app before the lockscreen appears. I mean what's the point then? This page I have experienced on custom rom Nitrogen OS. Before that MIUI was a saviour as it offers Inbuilt Applock.

Further, it can be resolved by Launcher itself as Flick launcher offers the same function. But the functionality was not practical on this launcher, as app gets locked everytime I minimized the app i had to unlock. I wish there was an option to keep it unlocked untill screen goes off, despite the app being minimized.

**Comment by divadsn** [comment]
@iamdeep08 no

**Comment by nyancrimew** [comment]
@iamdeep08 Applocks built into launchers are bullshit and not secure at all, they can be bypassed way too easily. More detailed explainations can be found in earlier issues on this topic.

**Comment by iamdeep08** [comment]
Why?

**Comment by shubhchan** [comment]
@iamdeep08 Cos when u clear data of launcher all ur apps r unlocked

**Comment by bohrabhijeet** [comment]
@iamdeep08 "More detailed explanations can be found in earlier issues on this topic" he said. 😐

**Comment by weirdeep** [comment]
okay.. I was not aware of this fact. When is the next update coming?

**Comment by shubhchan** [comment]
@iamdeep08 When we feel like "its about time"
