### ISSUE TITLE
[Feature Request] Change the location of home screen relative to other screens 

### ISSUE THREAD

**Issue by Faboulous** [Deletescape-Media/Lawnchair#1245]
## Description

1-The home screen is set to be the left screen
2- Screens cannot be moved around

## Expected Behavior

1- Have an option to set the desired home screen after a long press in a blank space 
2- Being able to move the screens relative to one another.

## Actual Behavior

1- Presently the home screen is set to be the left screen, lawnchair does not allow for another screen to be the home screen.
2- Screens cannot be move relative to each other, the content/icons have to be moved 1-by-1 to another screen in order to rearrange.

* Device: Samsung S7
* Android version:  7.0
* Launcher version: 1.1.0.1872
* Rom: unknown

**Comment by divadsn** [comment]
That won't change, we are a Pixel style launcher and it's designed to be like that for Google Now pane.

**Comment by Faboulous** [comment]
Best of luck then
