### ISSUE TITLE
New icon design for Lawnchair Launcher

### ISSUE THREAD

**Issue by adem3455** [Deletescape-Media/Lawnchair#1248]
The editable files of the new icon are below. 
I hope you will like it. 

Lawnchair Launcher Editable Files: https://drive.google.com/open?id=1wEabfAO9eKDx2IcLxwVOlEbVRndgiIl0

**Comment by LinuxLlama** [comment]
We already have a design for our next icon. While this icon is nice, it's not going to be used since we've picked our next design.

**Comment by divadsn** [comment]
Thanks, but we have already made a choice for our new icon :)
