### ISSUE TITLE
Feature request: Allow date/weather on the right side when Pixel searchbar is not shown

### ISSUE THREAD

**Issue by misha-franz** [Deletescape-Media/Lawnchair#1250]
Hello,

I am using Lineage OS 14.1 without Google services, which makes use of Pixel searchbar impossible (and I am OK with that). However I still want to see the date/weather on the right side (mostly weather as I see the date on the Calendar widget) - and it works except the left side (where the search would be) is empty and cannot be used for anything.

Please add an option to show date/weather without the searchbar and make it smaller (do not allocate the whole width of the screen).

Thanks,
Michael.

**Comment by divadsn** [comment]
Isn't it already a thing in the latest release? :thinking:

**Comment by addiittya2006** [comment]
no, actually it does take up the whole width ![calender_span](https://user-images.githubusercontent.com/7330961/41310971-a73535b8-6ea0-11e8-90f2-c2fc85bfc0d9.jpg)
