### ISSUE TITLE
LOOK & FEEL please provide android p like features

### ISSUE THREAD

**Issue by prabhash77484** [Deletescape-Media/Lawnchair#1251]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by LinuxLlama** [comment]
That's what Lawnchair v2 is all about!

**Comment by fonix232** [comment]
Use the damn template, it's not there so you can write your requests in the title...
