### ISSUE TITLE
Ability to swipe away Google Now cards

### ISSUE THREAD

**Issue by ncost** [Deletescape-Media/Lawnchair#1252]
Couldn't find anything about this in previous issues. I have Google Now enabled from my home page, and everything works great except for the fact that I can't swipe away my Google Now cards to the left like the real Google Now app. Something in my settings? 

Device: Samsung Galaxy S9 Verizon
Android version: 8.0.0
Launcher version: 1.1.0.1872

**Comment by LinuxLlama** [comment]
We can't control how you interact with the Google Feed. This is a Google issue. If you would like, you can submit a bug report to Google.
