### ISSUE TITLE
Feature request: add an option to make the navigation bar opaque / solid

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#1254]
Feature request: add an option to make the navigation bar opaque / solid

## Description

Current the navigation bar is opaque on the home screen and transparent light in the app drawer, which is disturbing in my opinion. Users should be able to set same behaviour for the navigation bar in all launcher windows if necessary.

Using Samsung S9 (G960F), Android 8, app version 1.1.0. 1872 from Google Play.

See also issue #790 and  #998

**Comment by divadsn** [comment]
That's an issue we can't fix without accessing third party SDKs which is disallowed in Android P, but we have a toggle to force white status bar icons.

**Comment by eggsgent** [comment]
Thanks David, I don't quite understand why third party SDK is needed to show opaque navigation bar in the app drawer, isn't the drawer part of the launcher itself? Google apps like Gmail and Chrome both use opaque navigation bars on my Samsung S9.

**Comment by suphon-t** [comment]
@eggsgent The Google Now page is a part of the Google app.

**Comment by eggsgent** [comment]
@paphonb I modified my feature request to be specifically about "all Lawnchair launcher windows only".

Currently the navigation bar is opaque on the home screen, but transparent in the app drawer.
