### ISSUE TITLE
Deep Shortcuts Drag Handles are misleading

### ISSUE THREAD

**Issue by schokotets** [Deletescape-Media/Lawnchair#1257]
## Description
The Drag Handles (double lines), as seen on the image, don't seem to serve any purpose and are rather misleading, because one would assume that you can drag the entries around vertically (it's even called _drag_ handles), but they don't have any special function. I'm unsure whether they should symbolize that you can pin these shortcuts on the home screen. _I don't know their purpose on the pixel launcher, admittedly._

## Fix
Please remove these drag handles as long as they don't serve any purpose.

## Steps to Reproduce
_long-tapping on an app which supports deep shortcuts_

![lawnchair-shortcuts](https://user-images.githubusercontent.com/13350549/41200501-dfb372b2-6ca5-11e8-99d5-ef7d0c5134b5.jpg)

**Comment by suphon-t** [comment]
I think they serve as an indicator so that the user knows the shortcuts can be dragged. Normal clicks are also ignored inside the "drag handler"

**Comment by divadsn** [comment]
@paphonb yet I can also confirm they're misleading, I was thinking first that I could re-arrange the order of the shortcuts, but instead I just could only place them on the homescreen.
