### ISSUE TITLE
[alpha] Lawnchair won't open

### ISSUE THREAD

**Issue by marcinciarka** [Deletescape-Media/Lawnchair#1262]
## Description

When I run the app it crashes and EMUI reports a serious crash.

## Expected Behavior
Lawnchair opens.

## Actual Behavior
Lawnchair crashes.

## Steps to Reproduce

1. Install app (from xda-dev)
2. Run app
3. App crashes

## Environment
Device: Huawei P20 Pro
ROM: default P20 Pro (CLT-L29 8.1.0128 C432)
Launcher version: v2-alpha_137

**Comment by divadsn** [comment]
Grant storage permissions manually in system settings.
