### ISSUE TITLE
[Feature Request] Allow Google search pill to use different Search engines

### ISSUE THREAD

**Issue by ImortisInglorian** [Deletescape-Media/Lawnchair#1268]
## Description

Allow the Google Search Pill to connect to alternate search engines such as https://duckduckgo.com/

I really like the way the search pill looks, but would love to connect it to different search engines. It would also be nice if changing the search engine would also change the icon to that of the engine to which it has been changed, but that is not strictly required.

**Comment by spyjoshx** [comment]
I too would like this feature very much

**Comment by coderex96** [comment]
Please add this feature ♥

**Comment by TheMatten** [comment]
>It would also be nice if changing the search engine would also change the icon to that of the engine to which it has been changed...

Or use generic search icon.

**Comment by LinuxLlama** [comment]
This is something we have on our to-do list and have made some process on it.

**Comment by baarkerlounger** [comment]
Is there a branch anywhere to look at? Also is the to-do list visible anywhere?

**Comment by nyancrimew** [comment]
@baarkerlounger This has been implemented in V2 now

**Comment by baarkerlounger** [comment]
@deletescape great thanks, is V2 the alpha branch? Or is it hosted somewhere else?

**Comment by theel0ja** [comment]
I use V2, but it allows only "global search" and "Google". I'd like to have similar approach than KISS Launcher, that you have pre-defined options like Google, Bing, DDG and on top of that, Custom URL.

**Comment by bohrabhijeet** [comment]
@theel0ja Lawnchair v2 supports other search engines like DDG, etc. For that you have to have the said engine's app installed and then navigate to Settings > Search and change the search provider.

**Comment by theel0ja** [comment]
I think that the DuckDuckGo app sucks, I don't think it allows opening in custom browser. That's why I like KISS Launcher's approach for having URLs that open in browser.

For example for DDG I can enter `https://duckduckgo.com/?q=%s` (`%s` = query) for KISS Launcher and it opens it in my preferred browser.
