### ISSUE TITLE
[Feature Request] Adaptive Colored App Shortcuts

### ISSUE THREAD

**Issue by tychoregter** [Deletescape-Media/Lawnchair#1270]
I'd like to request adaptive colored app shortcuts (the color taken from the app icon/wallpaper) it would look really cool, some other Launcher have it too like Action Launcher and some modded Pixel Launchers

**Comment by bohrabhijeet** [comment]
@tychoregter Hmm, that sounds good. 🤔

**Comment by LinuxLlama** [comment]
I support this idea. Sounds interesting.

**Comment by divadsn** [comment]
Could be easily added as we already have the option to extract the accent color based on the wallpaper.

**Comment by ghost** [comment]
I also support think it would look interesting :)
