### ISSUE TITLE
Setting wallpaper by 3rd party app crashes Lawnchair

### ISSUE THREAD

**Issue by imoseyon** [Deletescape-Media/Lawnchair#1272]
## Description

I use an App called Wonderwall to auto set wallpaper periodically.  When Wonderwall sets wallpaper Lawchair crashes.

## Expected Behavior

It shouldn't crash. Other launchers don't exhibit this problem.

## Actual Behavior

App crashes (FC)

## Steps to Reproduce

1. Download/install Wonderwall
2. Have Wonderwall autoset wallpaper
3. Use the phone while wallpaper is being auto set
4. Experience Lawnchair crash

## Environment

* Device: Galaxy S9+
* Android version: 8.0
* Launcher version: 1.2.0.1878
* Rom: stock

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
@imoseyon What Lawnchair version are you running?
