### ISSUE TITLE
Add option for in-app payment to support development

### ISSUE THREAD

**Issue by quassy** [Deletescape-Media/Lawnchair#1276]
## Description
> Nothing, I am promising that Lawnchair, including all it's features, will always be free! But if you really like it, you can still buy me a beer or something via PayPal.

I'm sure you are gonna keep this promise, but nonetheless to keep your spirits up it'd be nice to have some links in the settings to send small donations your way, e.g. "buy coffee ($3); buy pizza ($9)" :wink:

## Expected Behavior
Donations should be possible through multiple channels, so more people have the chance to show appreciation for the development. No adverts, no annoying notifications, all the features should remain the same whether you pay or not.

## Actual Behavior
The developer can only be supported via PayPal.

## Steps to Reproduce
1. Open Lawnchair setting
2. Go to About menu
3. No indication on how to support the developer (PayPal is missing as well)

## Environment
Any.

**Comment by fonix232** [comment]
Not exactly the same, but [there's already a way to support the launcher via Google Play](https://play.google.com/store/apps/details?id=ch.deletescape.donut).

**Comment by divadsn** [comment]
@quassy Adding in-app purchases would classify our app as non-free and would make look like we have a Pro version on the store listing.

**Comment by fonix232** [comment]
@divadsn an option could be to make the Donut app free, and add IAPs in that. That way if someone wants to donate multiple times, the option is given (not sure if it already exists in the app or not, haven't checked it TBH).

**Comment by divadsn** [comment]
@fonix232 hmm, what about asking @deletescape, as he has the source for that.

**Comment by suphon-t** [comment]
@fonix232 Nah, just keep it paid and then add in-app purchases for people that want to donate multiple times.

**Comment by fonix232** [comment]
@paphonb That works too, my reason for making it free would be to entice people to download it, and then they can select donation amount (1$, 2$, 3$, 5$, 10$, 20$, 25$)

**Comment by quassy** [comment]
> @quassy Adding in-app purchases would classify our app as non-free and would make look like we have a Pro version on the store listing.

@divadsn That's a very good point. So instead of integrating IAP, linking to Donut could be an option. I guess for the Play Store listing it would not be a problem to link to the Donut app, _but_ in F-Droid this would already count as advertising non-free stuff 😐 

> @fonix232 Nah, just keep it paid and then add in-app purchases for people that want to donate multiple times.

@paphonb Agreed. 1.59 € is a reasonable amount for a minimal donation. Maybe display an extra Donut for each 1 € that is donated as a gimmick.

**Comment by ghost** [comment]
Could always just add

```
         <link
             name="Donate"
             icon="@drawable/ic_donate"
             url="https://paypal.me/name-of-account" />
```

to the attriboutor.xml in the the appinfo section. also any contributor could add their own link under their info.

Then add the attached ic_donate.png to the drawer folder.
Wouldn't really be an In-App-Purchase just another link, like the twitter or github links but, to PayPal.me with an empty amount so people can choose how much to donate.

ic_donate:
![ic_donate](https://user-images.githubusercontent.com/327196/42190203-d76cef62-7e29-11e8-98ee-f555bc70c3c7.png)

Example:
![example](https://user-images.githubusercontent.com/327196/42190877-ac575552-7e2d-11e8-8222-3df7f4141078.png)

**Comment by suphon-t** [comment]
That would go against Google Play rules. No payment methods other than IAP are allowed in apps.

**Comment by ghost** [comment]
google picks and chooses. lol i understand not wanting to take the risk, though, a link to paypal.me shouldn't be viewed as an IAP. Technically the donation is made in the users web browser application. 
Ebay and Amazon are on the PlayStore and they have thousands of items up for purchase, in-app.

**Comment by nyancrimew** [comment]
@HighRidas Quoting the official payment policy by GOOGLE (https://play.google.com/about/monetization-ads/payments/):

* Developers offering products within a game downloaded on Google Play or providing access to game content must use Google Play In-app Billing as the method of payment.
* Developers offering products within another category of app downloaded on Google Play must use Google Play In-app Billing as the method of payment, except for the following cases:
  * Payment is solely for physical products
  * Payment is for digital content that may be consumed outside of the app itself (e.g. songs that can be played on other music players).

**Comment by fonix232** [comment]
@deletescape however the clause does define "offering products" - here, you're not offering a product, hence this point of the policy does not apply.

**Comment by nyancrimew** [comment]
@fonix232 If we don't offer a product at all we are definitely not offering a physical product or digital product which can be consumed outside of the app which means that it is not allowed. Stop arguing about it, apps have been taken down from the playstore or updates havent been approved for linking to paypal.

**Comment by ghost** [comment]
not arguing. discussing. if you named the button SHIT and it happened to open up paypal.me you're not asking or offering anything. its a SHIT button thats opens a website. googles become too power hungry. it was intentionally worded the way it is. the paypal app is in the playstore i can send money right now through the app and its not an in-app purchase.

**Comment by ghost** [comment]
goFund me is literally an app that has a million donation links in it and it doesn't offer in-app purchases. or purchases through google pay specifically. Its just googles way of keeping small apps from making anything without paying google. big companies get away with it because they're invested in them. lol my 'issue' isn't with you guys not wanting to risk a ban. that's understandable. my issue now is with google changing their policies every 3-6 months and having no choice but follow. that's all from me for now lol. have good day, or night, wherever you are..

**Comment by quassy** [comment]
> google picks and chooses. lol i understand not wanting to take the risk, though, a link to paypal.me shouldn't be viewed as an IAP. Technically the donation is made in the users web browser application.

Öffi (a popular app for public transport info) was kicked for having a PayPal link in the source code, which was hidden when the app was installed via Play Store. There is no point in arguing the powers that be.

It's either official Google IAP or no payment info in the app at all.

Does Donut have a bug tracker somewhere?

**Comment by nyancrimew** [comment]
> Does Donut have a bug tracker somewhere?

Yep, in my E-Mail inbox (deletescape@gmail.com) 😉 

Closing this issue now
