### ISSUE TITLE
Norwegian nb-NO translation is a mess in the app, please use latest translations from crowdin

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#1277]
![lawnchair](https://user-images.githubusercontent.com/7951056/41819961-29afd08e-77ca-11e8-85a4-2565dc1fa3bb.jpg)
## Description
Norwegian nb-NO translation is a mess in the app, please use latest translations from crowdin.
Many menu strings which are translated to Norwegian are shown in English in the app.

## Steps to Reproduce

1. Set device language to Norsk bokmål (nb-NO)
2. Install 160 alpha
3. Inspect that all app strings are in Norwegian

Actual result: 
1. Lots of English strings shown instead of the latest available Norwegian translations.
2. Some translated items in the app cannot be found on crowdin(!)

Examples in the screenshot:
1. This translation is not found on Crowdin: http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=Endre+formen+p%C3%A5+ikonet
2. This string is translated to Norwegian on Crowdin, but not in app: http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=apply+blur+effect
3. This string is translated to Norwegian on Crowdin, but not in app: http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=Local+backups

## Environment

* Device: Samsung Galaxy S9
* Android version: 8.0
* Launcher version: 160 alpha, 1.2.0.1878 does not load any Norwegian translations

**Comment by bohrabhijeet** [comment]
@eggsgent Haven't you already created an issue for the same earlier?

**Comment by eggsgent** [comment]
No, i've commented on missing translations in https://github.com/LawnchairLauncher/Lawnchair/issues/175

**Comment by eggsgent** [comment]
A few other comments:

Translations are added to Norwegian by non-natives, this should be avoided to keep the translations at the highest possible quality (example of a translation which doesn't make sense):

http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=Set+default+launcher

English strings are added to Norwegian translations, why?

http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=read+home+settings+and+shortcuts

Norwegian translations are updated by non-natives, which may result in less uniformity and introduce errors, like in this example: http://translate.lawnchair.info/translate/lawnchairandroid/11/en-no#q=hjem-knapp

**Comment by LinuxLlama** [comment]
There are no translations because we haven't added other languages to V2 yet. It's just an alpha.

**Comment by suphon-t** [comment]
As @reC0D3D stated above, translations aren’t imported into v2 yet.

**Comment by eggsgent** [comment]
Thanks, will the translations also be applied to version 1 through a maintenance release or is all focus moved to version 2 and no further updates to version 1?

There are some translations in V2 alpha, but those are not coming from Crowdin.
Where can the other issues I have mentioned in the comment above be discussed and addressed?

**Comment by divadsn** [comment]
@eggsgent Those translations are from Launcher3, but not from us.

**Comment by eggsgent** [comment]
Hi, when are you planning to sync the translations? Please add them in good time before the final so they can be reviewed on a device. Thanks. Not synced as of 2.0.370 alpha.

**Comment by nyancrimew** [comment]
@eggsgent We are not going to sync translations for V2 before we release a beta and the source. We have an open source plan with crowdin and don't wanna risk loosing that by uploading already

**Comment by eggsgent** [comment]
Thanks for the reply. Just following up as I'm keen on seeing the translation live in a product for verification. Version 1.2.0.1884 from playstore is still missing / not loading the Norwegian translation.

**Comment by nyancrimew** [comment]
@eggsgent I think the language code we've been using for norwegian might be wrong as there are three different ones and they all fall back to something else from what I have seen. I will check it again before importing to V2 to make sure we're doing this properly :)

**Comment by eggsgent** [comment]
Not fixed in build 2027

**Comment by eggsgent** [comment]
Issue still present in 2.0.2500 ci-alpha, please fix it so the proper translations can be applied, thanks!

**Comment by eggsgent** [comment]
I have found following discrepancies which should be easy to fix:

"nb" (norsk bokmål) is not a target language for this project:
https://crowdin.com/translate/lawnchairandroid/14/en-nb

Import file: https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/crowdin.yml
  languages_mapping:
     android_code:  "no: no"

But translation files are in "nb" directory: https://github.com/LawnchairLauncher/Lawnchair/tree/alpha/res/values-nb (this file is old an contains wrong translations fixed on crowdin long time ago)

While the update file uses the "no" directory: https://github.com/LawnchairLauncher/Lawnchair/tree/alpha/lawnchair/res/values-no

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by eggsgent** [comment]
> 
> 
> Closing because effort has been moved to v11

Is the "v11" being translated somewhere and can the previous translations be imported into the new project?

**Comment by RikKoedoot** [comment]
https://lawnchair.crowdin.com/lawnchair I'm not aware of a way except manually copying strings
