### ISSUE TITLE
Weather widget disapearing after  period of time

### ISSUE THREAD

**Issue by nate97** [Deletescape-Media/Lawnchair#1279]
## Description
While using the Lawnchair launcher, I usually have the weather widget enabled through the Theme tab, however at random, the weather will inevitably after a few hours disappear and only show the date and day. ( Note, My location is turned on even when this issue occurs )

## Expected Behavior
The weather information should continue to be displayed and occasionally be refreshed.

## Actual Behavior
The weather information displays and refreshes for a little while, but eventually disappears entirely leaving only the date and day.

## Steps to Reproduce
I'm unsure about how to reproduce the behavior, but my work around is to:
1. Go into Lawnchair launcher's settings
2. Disable the weather widget in themes
3. Re-enable the weather widget
4. Go back to the launcher, and the weather information will be back

## Environment
* Device: Device: OnePlus 5T 
* Android version:  8.1.0
* Launcher version: 2.1.0.1878
* Rom: Stock Rom, Oxygen OS  5.1.3

**Comment by ivanbeldad** [comment]
Exact same behavior from my first install three months ago or so.

I don't know if it's related to #898, I'll try to disable WiFi and data intentionally to find if that's the origin of the problem.
