### ISSUE TITLE
Icon shape

### ISSUE THREAD

**Issue by NathanFrederick** [Deletescape-Media/Lawnchair#1280]
Add change icon shape in Lawnchair V2

**Comment by LinuxLlama** [comment]
You can already change the icon shape in V2, unless you mean porting it?

**Comment by NathanFrederick** [comment]
Oh okay I don't see it in the settings but I will keep looking

**Comment by ghost** [comment]
I can't find the option either. Maybe it's because I'm not on oreo?

**Comment by divadsn** [comment]
@khaledson Nougat or higher, kthxbye

**Comment by ghost** [comment]
@divadsn I'm on nougat.

**Comment by divadsn** [comment]
They're not backported in v2.
