### ISSUE TITLE
Remove back button from navigation bar in Android P DP3+

### ISSUE THREAD

**Issue by ihighonlyfe** [Deletescape-Media/Lawnchair#1281]
Please provide an option to remove the back button in the navigation bar on home screen, following the DP3 suit, and just see the pill. 

* Device: Google Pixel 2 XL
* Android version: Android P DP3
* Launcher version: alpha 163
* Rom: default

**Comment by suphon-t** [comment]
Unfortunately, Google didn't add an API for apps to control the back button visibility. Sorry about that.

**Comment by DennisBednarz** [comment]
Is there still no API available?

**Comment by nyancrimew** [comment]
@DennisBednarz Only the current recents provider/launcher can hide the back button. If you install Lawnstep (our magisk addon for pie recents) we are able to hide the button and provide our own recent apps screen
