### ISSUE TITLE
Home Long Press - Wallpapers Replicate At Bottom

### ISSUE THREAD

**Issue by 0pLuS0** [Deletescape-Media/Lawnchair#1284]
## Description
When applying a wallpaper, and the choices appear, and I have applied the same wallpapers over, they will replicate and appear several times.

## Expected Behavior
See the wallpaper choices correctly, if only three wallpapers to choose from, then see only three wallpapers.

## Actual Behavior
When I go back and forth between a few wallpapers, applying them over several times, then these wallpapers will replicate at the bottom for the choices to pick from. So with only two wallpapers on the phone, I will see these same images appear several times.

```There appears to be some cache, because if I delete the images off the phone I can reapply them, so maybe this has nothing to do with Lawnchair, but someone can tell me what this is, and where to correct this?```

``` I also noticed after making this post, that if I press on the images, I get a popup appearing at the top of the screen with a trash can to delete these. So now I'm assuming this is a RECENT images option, so is there a way to disable this in Lawnchair, if this is not a bug?```

## Steps to Reproduce
1. Press Home screen until options appear
2. Press Wallpapers and apply a wallpaper
3. Repeat steps 1 & 2 with the same wallpaper
4. Press Home screen until options appear
5.  Press Wallpapers and apply a different wallpaper
6.  Repeat steps 4 & 5 with the same wallpaper

Now after running these steps, applying the same two wallpapers twice, you will now see both wallpapers appear twice in the choices... Please see the attached screen shot showing these images replicated at the bottom of the screen.

## Environment
Xiaomi Mi A1
Rom: Android Open Source illusion Project - (AOSiP-8.1-Official-tissot-20180617)
Android version: Oreo 8.1.0
Launcher version: 1.2.0.1878

![wallpaper](https://user-images.githubusercontent.com/36190223/41951780-0fde18ac-79bc-11e8-81da-a80f2717ee81.jpg)

## Logcat
[logcat.txt](https://github.com/LawnchairLauncher/Lawnchair/files/2139705/logcat.txt)

**Comment by divadsn** [comment]
That's actually an expected behavior, as these are your previous wallpapers, you can simply select them by longpressing and delete them.

**Comment by 0pLuS0** [comment]
@divadsn 

I can understand having a wallpaper appearing only once that you selected before, but this is not the case.

It is replicating the wallpaper many times over. I've seen the same wallpaper appear 5 times, this is crazy. 

I was playing back and forth with an issue and setting a few wallpapers over, and I had at one time, only two wallpaper, each appear 5 times, with a total of like 10 images of the same wallpaper, that's just to much...

Please reopen this report and please fix this, so a wallpaper only appears once that was used, not multiple times over.

Thanks
