### ISSUE TITLE
Feature: Google Assistant

### ISSUE THREAD

**Issue by SohailRaheman** [Deletescape-Media/Lawnchair#1289]
Instead of having Google voice search, it is very handy to launch Google assistant.

**Comment by soaringowl2145** [comment]
Or an option to choose which option?

**Comment by rk134** [comment]
Maybe we can have ai preinstalled and then edit the code slightly, to check if the user has Google Assistant. If they have it, then it opens when you long press home button. If not then it uses the default google voice search. I think you need to edit the handler side.
