### ISSUE TITLE
Phone app has wrong icon

### ISSUE THREAD

**Issue by failsafe42** [Deletescape-Media/Lawnchair#1291]
## Description

The phone app has the contacts icon instead of the phone icon.

## Expected Behavior

Phone app should have phone icon

## Actual Behavior

Phone app has contacts icon

## Steps to Reproduce

https://imgur.com/a/W6ZMpbA

## Environment

* Device: Samsung Galaxy S8 SM-G950U
* Android version: 8.0.0
* Launcher version: 1.2.0.1878
* Rom: Default Samsung Rom

**Comment by LinuxLlama** [comment]
You can change it by long pressing the icon, tapping edit, tap system icons (or which icon pack your using), and select the correct icon.

**Comment by failsafe42** [comment]
I have tried to do that, but it doesn't change.

**Comment by Fyde7** [comment]
I'm having the same problem but on multiple apps, if I try to change the icon I can see the right one but if I select it it doesn't change.
[Screenshots](https://imgur.com/a/BgNBNbj)
