### ISSUE TITLE
[Feature Request] More Gestures for custom actions

### ISSUE THREAD

**Issue by soaringowl2145** [Deletescape-Media/Lawnchair#1292]
Nova Launcher has a feature that you can double tap on the home screen, or two finger swipe to make a custom action.

The only actions I would like to request at this time is to be able to: 

Double tap the home screen to launch Google Assistant
Two finger swipe up or down to be able to launch an app of my choosing.

Thank you!

By the way, your launcher is awesome!

**Comment by maturabg** [comment]
Yeah, customizeable gestures would be nice to have. I'd like to be able to double tap to sleep and pinch in to launch app.

**Comment by divadsn** [comment]
@kptawesome All in v2

**Comment by divadsn** [comment]
You can get v2 alpha APK in our Telegram community group.

**Comment by guest4711** [comment]
You'll find most v2 versions at 
https://www.apkmirror.com/apk/deletescape/lawnchair/
