### ISSUE TITLE
Go back to the Material Design icons (v2) 

### ISSUE THREAD

**Issue by DragoCubed** [Deletescape-Media/Lawnchair#1293]
## Description
Overall the normal, filled in Material Design icons are better than the Frankenstein icons that are the new icons from Google. This is very subjective. I might not be alone though. I wouldn't consider this to be a bug but I don't know if there is a place for things like this. 

Also, so many options are missing from v2. Is it a rewrite? I haven't really been following Lawnchair. 

## Expected Behavior

The icons should be filled in

## Actual Behavior

Some icons are filled in. Some are not. Some are partially filled in. 

## Environment
* Device: Samsung Galaxy J5 Pro
* Android version: 7.0
* Launcher version: 2.0.237
* Rom: Stock Samsung rom

**Comment by divadsn** [comment]
@DragoCubed It is an alpha, and we are heading toward the new Material Design which is present in current DP of P.

**Comment by DragoCubed** [comment]
Honestly I really hate the design of Android P.

**Comment by divadsn** [comment]
@DragoCubed we will see forward to have both options available, but I can't guarantee.

**Comment by LinuxLlama** [comment]
We're following Google's approach to Material Design. In the recent Android P DP4, Google used outlined icons everywhere which first started with the Pixel Launcher, which is what Lawnchair is mimicking. As a designer myself, I like the outlined icons more than filled in ones.

**Comment by bohrabhijeet** [comment]
@DragoCubed Following the Material Design guidelines set by Google, is what we're doing.

**Comment by suphon-t** [comment]
I also have no idea why you dislike the outlines icons. Each person has their own opinion.
