### ISSUE TITLE
Kanged launcher "Phantom Launcher"

### ISSUE THREAD

**Issue by KieronQuinn** [Deletescape-Media/Lawnchair#1295]
Came across this launcher, it's a blatant copy of Lawnchair with just (some of) the strings changed [They didn't change every language lol]: https://play.google.com/store/apps/details?id=highridas.phantom.launcher

The source is here, but there are no commits except the initial upload: https://github.com/HighRidas/PhantomLauncher
The licence is also different which I believe is not allowed

Your choice of what to do, I just spotted it on Google+

**Comment by shubhchan** [comment]
@KieronQuinn @deletescape pls get it removed its kensur

**Comment by nyancrimew** [comment]
@KieronQuinn Thanks a lot for the report, I'm taking care of it

**Comment by amirzaidi** [comment]
Reported.

**Comment by KieronQuinn** [comment]
This was taken down but appears to now be back, good spot @amirzaidi 

Reported again.

**Comment by divadsn** [comment]
@KieronQuinn What the hell...

**Comment by nyancrimew** [comment]
Updated my DMCA request again as it is up again
