### ISSUE TITLE
Change icon shape

### ISSUE THREAD

**Issue by NathanFrederick** [Deletescape-Media/Lawnchair#1297]
In V2 I don't see change icon shape option Android version 7.1.2 I had the option before now it's gone

**Comment by nyancrimew** [comment]
@NathanFrederick Icon shape change is currently not backported yet in v2

**Comment by shubhchan** [comment]
@NathanFrederick It was take from amir's approach and as he removed it, we also did maybe will get added in future

**Comment by NathanFrederick** [comment]
Okay thanks
