### ISSUE TITLE
[Feature Request] Icon search option. 

### ISSUE THREAD

**Issue by atul0000** [Deletescape-Media/Lawnchair#1299]
Kindly add an option of searching Icons while changing any specific App's icon. It'll be easier & convenient for us to choose the icons or change the icons.
As well as add and option of lock desktop. So, it'll locked as like earlier v1 lawnchair.

**Comment by weirdeep** [comment]
Very genuine demand.

**Comment by AxiK101** [comment]
This should be a standard

**Comment by ghost** [comment]
Duplicate of https://github.com/LawnchairLauncher/Lawnchair/issues/665?

**Comment by paphonb** [comment]
Duplicate of #665.
