### ISSUE TITLE
"Cannot launch app." when trying to launch one of the 5 suggested apps through the google search bar.

### ISSUE THREAD

**Issue by Dahliamma** [Deletescape-Media/Lawnchair#1301]
## Description

When you tap the google search bar, either at the bottom of the desktop or top of the app drawer (if that option is enabled), it shows 5 suggested apps on the bottom, below your recent searches. Tapping on those icons doesn't launch the app however, it just shows a toast that says "Cannot launch app." The apps still launch fine from the app drawer, desktop, and the suggested apps at the top of the app drawer OUTSIDE of the google search screen (the ones that are always there, not the ones that show up below your recent search results).

I had the [ported pixel launcher from XDA](https://forum.xda-developers.com/android/apps-games/app-rootless-pixel-2-launcher-google-t3688393) installed prior to this, and noticed that, before uninstalling the ported pixel launcher, launching an app from the google search screen asked which launcher I wanted to use to complete the action, with the two choices being the ported launcher linked above and lawnchair v2. Choosing either one worked for launching an app, but as soon as I uninstalled the ported launcher, this issue started occurring. If I had to guess, it for whatever reason isn't attempting to grab default right properly once the other launcher is removed, and thus cannot launch the app. Reinstalling the ported launcher brings back the expected behavior, although it doesn't ask which launcher I want to use as default. 

## Expected Behavior

Tapping on a suggested app from within the google search screen opens the app. 

## Actual Behavior

Instead of opening the app, it shows the "Cannot launch app." toast message.

## Steps to Reproduce

1. Tap google search bar to start a search (can either be the one on the desktop, or the one in the app drawer if Google Search is enabled under the app drawer settings).
2. Tap on an app icon from one of the 5 suggested apps shown below recent search results.
3. "Cannot launch app." toast pops up at the bottom of the screen, or above the keyboard if the keyboard is shown.

## Environment

- Device: Galaxy S8+, US T-Mobile version (SM-G955U)
- Android Version: 8.0.0, June Security Patch (CRE9)
- Launcher Version: 2.0-269-ci-alpha
- ROM: Stock (Samsung Experience 9.0)
- Google App Version: 8.8.15.21.arm64

**Comment by computerchad** [comment]
Thank I've got the exact same issue in an Android One Moto X4

**Comment by LinuxLlama** [comment]
This is a Google issue, not a Lawnchair issue. The Google search menu is part of the Google app and only expects to be opened by the _Pixel Launcher_ so it doesn't have support for other launchers. If you want this menu to work correctly, you can install the Pixel Launcher but still keep Lawnchair as the main launcher, it'll work since the Pixel Launcher is present.

**Comment by computerchad** [comment]
Awesome, thanks
