### ISSUE TITLE
The icons are too close to the edge of the screen (v2)

### ISSUE THREAD

**Issue by Tminus1** [Deletescape-Media/Lawnchair#1302]
## Description
I've noticed that you changed the icons to be closer to the edges. This is how it was on the "older" Pixel launcher. I had only installed the first version and the latest one so I can't pinpoint when the change was made, but I think it's for the worse and should be reverted. Or at least add an option to change it ourselves if we want.

**Comment by divadsn** [comment]
@Tminus1 What build? 🤔

**Comment by Tminus1** [comment]
@divadsn 2.0-274-ci-alpha.

I've also put this comparison image together:

![2018-07-13_0-47-29](https://user-images.githubusercontent.com/40320559/42661523-1c80a232-8637-11e8-96bd-0a4d730a5c1b.png)

**Comment by amirzaidi** [comment]
res/values/dimens.xml -> dynamic_grid_cell_layout_padding

**Comment by nyancrimew** [comment]
This should be fixed in the next alpha build

**Comment by Tminus1** [comment]
Just downloaded it. Thank you so much!
