### ISSUE TITLE
ISO 8601 Date/Time format for backups

### ISSUE THREAD

**Issue by source124** [Deletescape-Media/Lawnchair#1307]
## Expected Behavior
Date/ Time format for backups should be: YYYY-MM-DD hh.mm.ss or something else similar to ISO 8601

This helps sorting (as when deleting old backups using a file manager).
## Actual Behavior
Currently it is DD-MM-YYYY

---
* Android version: 8.0
* Launcher version: 1.2.0.1878

**Comment by nyancrimew** [comment]
@source124 @paphonb we should probably base the date/time format either on an international standard or on the format provided by Locale.

**Comment by source124** [comment]
Well, ISO is the standardest :)

**Comment by source124** [comment]
This is still not the case in v14
