### ISSUE TITLE
Wallpaper gets added to backup file regardless of setting

### ISSUE THREAD

**Issue by source124** [Deletescape-Media/Lawnchair#1308]
## Expected Behavior
Unselecting wallpaper on backup should not add it to backup files

## Actual Behavior
Wallpaper is added regardless

---
* Android version: 8.0
* Launcher version: 1.2.0.1878

**Comment by LinuxLlama** [comment]
That's because it's going to be used as a preview for backups. It's currently work in progress.

**Comment by source124** [comment]
OK, thanks,
maybe a small thumbnail instead of the full image to keep the size small?
