### ISSUE TITLE
Shortcut Widget Issue

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#131]
![screenshot_2017-07-05-12-00-58](https://user-images.githubusercontent.com/29732079/27873366-dbcdaa42-6179-11e7-8974-84f88cb9624f.png)
![screenshot_2017-07-05-12-00-51](https://user-images.githubusercontent.com/29732079/27873367-dbd293a4-6179-11e7-9c54-73ea049451ab.png)
![screenshot_2017-07-05-12-00-16](https://user-images.githubusercontent.com/29732079/27873368-dbd712da-6179-11e7-88f1-c4e249412419.png)
![screenshot_2017-07-05-12-00-12](https://user-images.githubusercontent.com/29732079/27873369-dbd822f6-6179-11e7-973f-014dcec76841.png)

**Comment by Dondrejohnson5** [comment]
Also, I would like to know if the Lawnchair team is making successful progress with Nougat app shortcuts?

**Comment by suphon-t** [comment]
Fixed with 9c39106
