### ISSUE TITLE
[resource request] the google search bar in the dock could colorize dark.

### ISSUE THREAD

**Issue by ojuara1987** [Deletescape-Media/Lawnchair#1313]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

``

**Comment by fonix232** [comment]
Please use the issue template, it's there for a reason.

**Comment by ojuara1987** [comment]
OK sorry
