### ISSUE TITLE
Add "latest installed apps" list in the application menu list

### ISSUE THREAD

**Issue by seth100** [Deletescape-Media/Lawnchair#1315]
Hi,

is it possible to add an option to see a small list of latest installed apps before the full apps menu list.
Nova Launcher does it when using the search icon.

Thank you for the great work!

**Comment by bohrabhijeet** [comment]
You can enable "Add icons to home screen" for newly installed apps. 

_However, the devs will see if they will/will not add the following feature._

**Comment by seth100** [comment]
Thank you for the tip, but that's not an option I want to use. I need something different. Thanks
