### ISSUE TITLE
Problem with Icons

### ISSUE THREAD

**Issue by StormDuet** [Deletescape-Media/Lawnchair#1316]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```
Square Icons doesn't fit well on MI Note 5 Pro. The icon of chrome get cropped out. plz add round icons or fix this issue

**Comment by TheComputerGuy96** [comment]
@StormDuet You haven't filled the issue template

Please fill it

**Comment by nyancrimew** [comment]
@StormDuet You can change the icon shape in the Lawnchair settings and the chrome icon "getting cropped out" is simply the official chrome adaptive icon I assume. Also by the looks of it you simply personally don't like square icons which isn't really a bug anyways.
