### ISSUE TITLE
Badge Icons Don't Appear to Recognize Permissions

### ISSUE THREAD

**Issue by Reubend** [Deletescape-Media/Lawnchair#1317]
Although permission is granted to Lawnchair to access notifications, it does't change the text that says to enable permissions.

## Description
Even when the notification permission is granted to Lawnchair, it acts like it's not. Please see [the video I made of it](https://imgur.com/za40H8f). In the video, I demonstrate that the app says permission must be granted, even though permission are already enabled for it.

## Expected Behavior
It should detect the notification permission as being granted, and then change the text displayed.

## Actual Behavior
[Here is a video of the bug.](https://imgur.com/za40H8f)

## Environment
* Device: Samsung Galaxy S9 (SM-G960U1)
* Android version: 8.0.0
* Launcher version: 1.2.0.1878
* Rom: Stock (Samsung Experience 9.0)

## Fixes I Already Tried

- Restarting my phone
- Clearing the app cache and restarting Lawnchair
- Disabling and re-enabling the permission

**Comment by Smaffster** [comment]
I am having this issue on a Galaxy S9 (SM-G960U)
Android Version: 9
Launcher Version: 1.2.1.2001
