### ISSUE TITLE
Feature request: dock height option.

### ISSUE THREAD

**Issue by Muscarv2** [Deletescape-Media/Lawnchair#1319]
Sorry if this has been requested, on mobile and the github app doesn't have search for issues from what I can see.

**Comment by RikKoedoot** [comment]
What version of lawnchair are you using? V1 already has it. V2 may get it in the future.

**Comment by Muscarv2** [comment]
V2, latest build. Hoping to see it in a future one!

**Comment by brokenpylons** [comment]
Any updates? The dock looks bad once you remove the search bar.
