### ISSUE TITLE
Periodic lag / freezing

### ISSUE THREAD

**Issue by Arkanas1** [Deletescape-Media/Lawnchair#132]
The launcher freezes when i hold on an app icon for the app shortcuts, then pressing the back button. It freezes for a few seconds before coming back to normal.

**Comment by tstackhouse** [comment]
Possible duplicate of #76?

**Comment by vivekappas** [comment]
Double tap to locking and unlocking screen in needed

**Comment by paphonbth** [comment]
Duplicate of #76
