### ISSUE TITLE
Unable to see weather information when openweathermap is used in the at a glance settings. (Lawnchair v2 beta-328)

### ISSUE THREAD

**Issue by Muscarv2** [Deletescape-Media/Lawnchair#1320]
I've gone to the openweathermap website and made sure my location is exactly the same as it's named there (Gothenburg, Sweden. Named "Goeteborg, SE" on the website) I've tried a few different ways but the weather never shows. I have the Google app disabled and really don't want to enable it just for this. Anyone else having this issue?

**Comment by divadsn** [comment]
@Muscarv2 Already known issue
