### ISSUE TITLE
[v2] Dock brighter than supposed to until dragging up any amount

### ISSUE THREAD

**Issue by jmalexan** [Deletescape-Media/Lawnchair#1321]
## Description

For some reason when going to the home screen, the dock background is brighter than it should be, until I drag up and start opening the app drawer any amount, when it immediately goes back to normal.

## Expected Behavior

Dock is correct color (opacity?)

## Actual Behavior

Dock is brighter (more opaque?) than set to until dragging up any amount.

## Steps to Reproduce

What it looks like right after I go home: ![screenshot_20180721-212453](https://user-images.githubusercontent.com/1496947/43042247-9a1995c6-8d2d-11e8-9de5-03fa9203ac2b.jpg)

What it looks like after dragging up on the screen: ![screenshot_20180721-213133](https://user-images.githubusercontent.com/1496947/43042254-ac29f698-8d2d-11e8-8333-64e03586d3c9.jpg)

## Environment

* Device: OnePlus 6
* Android version: Android 8.1 and P
* Launcher version:2.0-316-ci-alpha
* Rom: OxygenOS 5.1.9 and OnePlus Android P Beta 3

**Comment by suphon-t** [comment]
Already have a temporary workaround (1262c06) but will need some more debugging to actually fix this.
