### ISSUE TITLE
Can't uninstall any app from the launcher

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1323]
![screenshot_20180723-144036](https://user-images.githubusercontent.com/29479752/43077341-ea4d2158-8e8f-11e8-8abe-7ba96d66f4ef.jpeg)

## Description
When I tap and hold on an app, the option to uninstall doesn't show up in the launcher. The screenshot above shows the app drawer, but it doesn't work on the home screen either. I'm not sure if this is an actual bug from the launcher or from my phone, but it used to work. It still does in Nova.

## Environment
* Device: Lenovo P2 (P2a42)
* Android version: 7.0
* Launcher version: 2 2.0-328-ci-beta
* Rom: Stock Lenovo rom

**Comment by JonnyTech** [comment]
Click on `App info` to bring up the details which include uninstall.

**Comment by ghost** [comment]
@JonnyTech yeah, I know that, but that's a workaround, not a solution.

**Comment by fonix232** [comment]
It's not a bug. Both Nova and your phone's default launcher have it as a fixed shortcut, and display them accordingly. Lawnchair does not have this.

**Comment by ghost** [comment]
Then.. feature request, I guess?

**Comment by suphon-t** [comment]
It clutters up the list while you can just drag to the top to uninstall.
