### ISSUE TITLE
Caaaaaan't uuuuuuniiiiiinstaaaaaall aaaaaany aaaaaapp froooooom theeeeee laaaaaauuuuuuncheeeeeer

### ISSUE THREAD

**Issue by Thecrazyskull** [Deletescape-Media/Lawnchair#1324]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

IIIIIT IIIIIS NOOOOT WOOOOORKIIIIINNNGGGG!!!!

**Comment by ghost** [comment]
Uhm.. ok

**Comment by skittles9823** [comment]
@khaledson 10/10 bug report...

**Comment by Thecrazyskull** [comment]
OOOPPPSSS FFIIIIXXXEEEEEEDDDDD

**Comment by fonix232** [comment]
What will be fixed is your name on the list of users blocked from accessing this repository if you continue this. Consider it your final warning.

**Comment by divadsn** [comment]
Lmao, that's an admeme member...
