### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1325]
c3b9ece189f2829d293d27a7863a8806c708db01 accidentally merged two different versions of the same code.
[Here](https://github.com/LawnchairLauncher/Lawnchair/blob/5740b4cf24ac1f178160a4c762362253b1387fab/app/src/main/java/ch/deletescape/lawnchair/DeviceProfile.java#L302-L319) only the last version should be kept (so remove lines 302-310).

**Comment by divadsn** [comment]
That's a year old and fixed

**Comment by ghost** [comment]
It's still there in the alpha branch?

**Comment by divadsn** [comment]
@Twilrom It's how it is, fixed.

**Comment by ghost** [comment]
It's wrong though? It has two versions of the same code.
Lines 302-310 and 311-319.
