### ISSUE TITLE
[Request for appeal] Dock

### ISSUE THREAD

**Issue by ojuara1987** [Deletescape-Media/Lawnchair#1326]
Would it be possible to add a dock style to the Google search bar at the top of the apps? print Screen
![screenshot_20180725-125543](https://user-images.githubusercontent.com/41386794/43214360-6037d040-900f-11e8-8bca-1f33e5038162.png)

**Comment by bohrabhijeet** [comment]
@ojuara1987 For v1 and v2, you can just enable two-row dock and place a search bar widget there. It's exactly the same.

**Comment by ojuara1987** [comment]
@abhijeetbohra OK, but it was not cool, I'd like you to review that possibility.
![screenshot_20180725-134758](https://user-images.githubusercontent.com/41386794/43215492-af66dfaa-9012-11e8-88ee-2a6016495230.png)
![screenshot_20180725-134845](https://user-images.githubusercontent.com/41386794/43215499-b3fc6986-9012-11e8-96ab-bbf21a34ce97.png)

**Comment by bohrabhijeet** [comment]
You can use KWGT widgets to replicate the rounded search bar.

**Comment by ojuara1987** [comment]
como faço isso?

**Comment by bohrabhijeet** [comment]
@ojuara1987 Download KWGT Pro, the widget of your choice, and then place it on the homescreen. It's pretty easy, you just have to read.

**Comment by ojuara1987** [comment]
I do not like having many applications installed, the KWGT application only works in the pro version. Thanks for listening :)
