### ISSUE TITLE
Programmatically change icon pack

### ISSUE THREAD

**Issue by biloaramin** [Deletescape-Media/Lawnchair#1327]
how can i change the icon pack programmatically ?
As we can change it from setting but i want to do it programatically. 
will any one please guide me.

**Comment by nyancrimew** [comment]
There is currently no intent to change the icon pack yet, this will be added soon however so we can support quick add from IconPack dashboards

**Comment by biloaramin** [comment]
basically i want to add a dashboard activity to it, so that when a person(Developer) want to apply an icon pack in this launcher he just call that activity with an intent extra and we receive that extra string from intent in our launcher app and apply that icon pack over it (launcher).
now one thing that i did not find till now is how to change icon pack to preferences.

**Comment by nyancrimew** [comment]
That's what I mean in my earlier reply, I will implement this in our V2 source which is currently still closed source. Depending on how much work it would be I will also backport it to v1, but as that is mostly deprecated now and we want to get v2 out as soon as possible I don't think this will be worth doing

**Comment by biloaramin** [comment]
ok and thanks for quick replay.
