### ISSUE TITLE
No icon packs to select

### ISSUE THREAD

**Issue by mish0501** [Deletescape-Media/Lawnchair#1328]
## Description
When i head over to Theme to change the icon packs that I have, the only option there is None, but I have two icon packs that come with the phone. Some versions back, that didn't happen.

## Environment
* Device: Oneplus 3T
* Android version: 8.0.0
* Launcher version:  1.2.0.1884
* Rom: Stock rom (OxygenOS  5.0.4)

**Comment by nyancrimew** [comment]
@mish0501 The format of the OxygenOS icon packs recently changed I believe, which is why they are not supported anymore right now. Support for them might be reintroduced later if I feel like looking into it.

**Comment by mish0501** [comment]
@deletescape  Ohh, I see. I somehow managed to get the icons back, because of a backup I have created in the past. I hope you look into this problem. Thanks for answering.
