### ISSUE TITLE
Studder when going to home screen from Google feed

### ISSUE THREAD

**Issue by Horak14** [Deletescape-Media/Lawnchair#1329]
When using the latest Lawnchair and Lawnfeed, I get studdering and janking when I go home from the Google feed on the left. Never used to happen.

I'm one the 1+ 6 with Android 8.1

**Comment by estatz** [comment]
Confirmed on my 1+ 6.  OOS 5.1.9, Lawnchair v1.2.0.1884, Lawnfeed v1.2.0.1883

Happens only when I have Lawnfeed open and then I press the home button.  Swiping back to the home screen (main Lawnchair screen) from Lawnfeed is smooth.

**Comment by tocococa** [comment]
I have the exact same issue described in estatz' comment, I'm on a stock Moto G4 Plus running Android 7.0

**Comment by valeksensky** [comment]
+1, exact same problem!
Device - OP3t with OOS 5.0.5. I'm using latest stable versions of Lawnchair and Lawnfeed

**Comment by rl2macdo** [comment]
Same issue. Has been happening ever since upgrade to 8.1.  It looks to be continuously loading on a loop. Screen flashing, google loading circle. 
 All permissions granted. Can't find any solution online. 

1883 lawnfeed on 1884 lawnchair. KeyOne device.

**Comment by divadsn** [comment]
@rl2macdo We might wanna push the hotfix which is in our repo since ages to the Play Store

**Comment by rl2macdo** [comment]
Any way to get an apk for that?
