### ISSUE TITLE
home screen emptied every time LC preferences are edited

### ISSUE THREAD

**Issue by mccoys** [Deletescape-Media/Lawnchair#1330]
## Description
When I edit any of the preferences for lawnchair, then go back to its home screen, icons and widgets are gone. They cannot be restored using the save/restore tool.

## Expected Behavior
The home screen setup should be remembered.

## Actual Behavior
All icons are gone.

## Steps to Reproduce
See description

## Environment

* Device: Nexus 5
* Android version: 6.0.1
* Launcher version: 1.2.0.1878

**Comment by bohrabhijeet** [comment]
@mccoys Do you have the "Allow Lawnchair to create widgets on homescreen" permission allowed?

**Comment by mccoys** [comment]
@abhijeetbohra I remember I allowed lawnchair to "access widgets data" when I was adding a widget to the home screen, but I don't think that's what you are referring to.

I have searched all permissions requested by lawnchair, and it only says Position, Storage, and Phone. Nothing about widgets. Where do I find this permission ?

**Comment by mccoys** [comment]
Why was this closed?  I still have the issue

**Comment by nyancrimew** [comment]
See #1462
