### ISSUE TITLE
[add resource] Google Now

### ISSUE THREAD

**Issue by ojuara1987** [Deletescape-Media/Lawnchair#1332]
I use lawnchair as the main launcher, and I would like to add an option to change the look on google now. as shown in the screenshot. thank you
![screenshot_20180801-121555](https://user-images.githubusercontent.com/41386794/43532309-24608ffc-9588-11e8-86f1-f7b95f7749f9.png)
![screenshot_20180801-122233](https://user-images.githubusercontent.com/41386794/43532318-2a26e652-9588-11e8-87eb-36770f2ac05a.png)

**Comment by divadsn** [comment]
It's not in our power to control that.

**Comment by ojuara1987** [comment]
ok, obrigado
