### ISSUE TITLE
[review]

### ISSUE THREAD

**Issue by ojuara1987** [Deletescape-Media/Lawnchair#1333]
The Google search bar in the dock  not apply the dark color, as applied to the search bar in thes application drawer, this is correct or bug. thank you
![screenshot_20180801-122056](https://user-images.githubusercontent.com/41386794/43533199-a8d0310a-958a-11e8-8986-1eef3533c242.png)
![screenshot_20180801-121957](https://user-images.githubusercontent.com/41386794/43533226-b05f1670-958a-11e8-93dc-15d54e4009f7.png)
![screenshot_20180801-121911](https://user-images.githubusercontent.com/41386794/43533234-b4b34f0c-958a-11e8-86c4-d05646e2b89b.png)

**Comment by LinuxLlama** [comment]
This is intended behavior for this option.
