### ISSUE TITLE
Can't use face unlock or fingerprint to unlock after using Lawnchair double tap to lock screen and double tap to unlock (Oneplus6)

### ISSUE THREAD

**Issue by lulbob** [Deletescape-Media/Lawnchair#1334]
## Description

Can't use face unlock or fingerprint to unlock after using Lawnchair's double tap to lock screen and double tap to unlock feature from Oneplus6.

See this comment on an XDA thread. https://forum.xda-developers.com/oneplus-6/help/launcher-using-t3814747/post77053437#post77053437 

User has the same issue as I am.

## Expected Behavior

What should happen is that face unlock and finger print unlock should work after using double tap to unlock screen, but it does not work if the screen was locked via Lawnchair's double tap to lock.

## Actual Behavior

Only allows pattern unlock. Says "device locked by administrator".

## Steps to Reproduce

1. Have double tap to UNLOCK turned on within Oneplus 6 settings.
2. Have double tap to LOCK turned on within Lawnchair settings
3. Double tap to lock screen
4. Double tap to unlock screen

## Environment

* Device: Oneplus 6
* Android version: 8.1.0
* Launcher version: 1.2.0.1884
* Rom: OxygenOS version 5.1.9

**Comment by divadsn** [comment]
@lulbob Read exactly what's written when activating device admin, it's a secure lock, which means you have to enter your PIN/Password each time you want to unlock again, sorry 🤷‍♂️

**Comment by lulbob** [comment]
thanks for the quick reply. is there a way to double tap to lock reliably without device admin?

**Comment by divadsn** [comment]
@lulbob Yes, you can do safely by using the screen timeout method, should work fine when you have granted access to change system settings

**Comment by lulbob** [comment]
Screen timeout method works to lock it, but the default double tap to unlock feature opens up to a black screen where I can only see the bottom nav bar. Should I submit another issue for this?
