### ISSUE TITLE
[Feature Request] Hide app drawer icons when on home screen

### ISSUE THREAD

**Issue by dyskos** [Deletescape-Media/Lawnchair#1336]
Hi, this is a great launcher. However, I like launchers that don't have any app drawers, so I can keep everything organized in folders on the desktop. The problem is, there aren't any good launchers that do this.

I'd like either a feature to disable the app drawer, and Lawnchair will put all apps on the desktop, or a feature so that whenever I move an app from the app drawer to the desktop, that app is actually "moved" and not duplicated, as almost all launchers usually do (and the current behavior of Lawnchair).

For example: If I move Google Maps from the app drawer to the desktop, then Google maps will no longer be in the app drawer, until it's removed from the home screen. That way, the app is only ever in one place -- either the app drawer, or the desktop.

Feel free to ask for clarification if this is confusing, I've never seen this feature in an app before, so it'd be unique if Lawnchair implemented it.

Thanks and Cheers!

**Comment by bohrabhijeet** [comment]
That'll be an unnecessary feature to add, in my opinion. However, you can manually hide the apps that you have on homescreen :)

**Comment by dyskos** [comment]
All features are unnecessary, really. But it would be nice if there were an option for Lawnchair to automatically hide apps when there's an Icon on the homescreen, then having to manually hide and unhide it each time, which feels a big hacky. :) If something like this were added, I'd never use another launcher again. The only reason I use this over, say, Evie, is because this is Open Source. With Evie, I have no idea if they're using my data without me knowing.

**Comment by Kuphi** [comment]
How is this an unnecessary feature. It's quite a hazzle to hide all those apps manually. I would love this feature!
