### ISSUE TITLE
Implement Fuzzy search

### ISSUE THREAD

**Issue by faroit** [Deletescape-Media/Lawnchair#1339]
when using the text search in the app drawer to find an app, [fuzzy search](https://en.wikipedia.org/wiki/Approximate_string_matching) would help to allow typos and still find the right app.

## Description
fuzzy search is widely used across many launchers and apps. Many users know how to deal with fuzzy search and would probably like this feature as it helps to speed up the text search. There are many existing Java implementations, I would propose to pick [FuzzyWuzzy](https://github.com/xdrop/fuzzywuzzy).

## Actual Behavior
typing "frfx" in the app drawer text input, outputs no match

## Expected Behavior
_firefox_ should be found.

**Comment by divadsn** [comment]
@faroit It is already present in Lawnchair.

**Comment by nyancrimew** [comment]
@divadsn No, Lawnchair uses a Collator, currently not set up for fuzzy matching.

**Comment by faroit** [comment]
@divadsn can you point me to the code? I would like to investigate why it is not working as I would expect

**Comment by divadsn** [comment]
https://github.com/LawnchairLauncher/Lawnchair/pull/930

**Comment by faroit** [comment]
@divadsn I guess its [this part](https://github.com/LawnchairLauncher/Lawnchair/blob/7759136b41c7ddd85033f17ad93dc60ba44ac4e8/app/src/main/java/ch/deletescape/lawnchair/model/AppNameComparator.java#L85)?

I will check why it doesn't work as expected

**Comment by divadsn** [comment]
@faroit If you are relating to v2: it's still not done and everything from v1 will be implemented in v2 too, therefore mention please if you are relating to v2, as the code repo is v1

**Comment by faroit** [comment]
Alright, I will wait until the source code of v2 is released. I will reopen when that has happend.

also, I thought the alpha branch is v2. I would recommend to add a note on the main readme of this project.

**Comment by divadsn** [comment]
@faroit Technically v2 isn't yet public, therefore it's something "hidden" ;)

**Comment by faroit** [comment]
@divadsn @deletescape It looks a bit weird for an open source project to develop a new major release in private. What is the benefit of this procedure? 
I would propose to not release the v2 alphas in the public telegram channel till the source code is released. This is confusing for new contributors.

**Comment by divadsn** [comment]
@faroit It's a common practice for many open-source projects, we had bad experiences in the past with people stealing our code and impersonating us on the Play Store, we don't want to deal with that again.

**Comment by faroit** [comment]
I understand, thats sad :-/

**Comment by faroit** [comment]
v2 source is released. Fuzzy search is still not implemented in alpha-1940, so I reopen this.

**Comment by shubhchan** [comment]
@faroit Wew

**Comment by LuminarySage** [comment]
I think fuzzy search is implemented in 2380, correct?

**Comment by faroit** [comment]
yes, indeed. I just tried it. It works as expected. Thanks!
