### ISSUE TITLE
[Feature Request] Double-tap to sleep using Android P accessibility

### ISSUE THREAD

**Issue by markus-lendermann** [Deletescape-Media/Lawnchair#1340]
In the current Nova Launcher V6.0.3 beta, there is the option to lock the screen using Android P accessibility permissions, which _instantly_ locks the screen _while still retaining biometric unlocks_ (e.g. fingerprint). Lawnchair only supports screen lock using root, timeout and device admin (which disables biometric unlock). Would be nice to see this added, thanks!

https://www.xda-developers.com/android-p-action-lock-screen/

**Comment by VRUnleashed** [comment]
Yup this would be useful af

**Comment by msawatzky75** [comment]
no work on this?

**Comment by skittles9823** [comment]
@msawatzky75 It's already a thing in V2.
