### ISSUE TITLE
[Feature request] Animate calendar icon

### ISSUE THREAD

**Issue by JonnyTech** [Deletescape-Media/Lawnchair#1342]
Is it possible to add a feature which updates the calendar icon to show the current date, similar to how the clock icon shows the current time?

**Comment by divadsn** [comment]
@JonnyTech It's already been a feature

**Comment by JonnyTech** [comment]
Thanks @divadsn. Can you explain how to activate it please? My clock icon animates correctly. Saw some issues here about calendar icon but found nothing in settings.

**Comment by Lisguincio** [comment]
You need a custom icon pack. I use "stardust" for example.

**Comment by JonnyTech** [comment]
Understood. Thanks for clarifying. I do not use icon packs. Can this be documented to avoid any further confusion?

**Comment by suphon-t** [comment]
It doesn’t require icon packs if your calendar app supports this feature.
