### ISSUE TITLE
Assistant button V2

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1344]
## Description

In v2 when you enable the assistant button for the search bar then it will show up on the homescreen but not in the app drawer

## Expected Behavior

Show up on both homescreen and app drawer

## Actual Behavior

Doesn't show up on app drawer

## Steps to Reproduce

go to settings enable assistant button

Way to temp fix this (Will reset after you restart lawnchair or you phone:

1: enable voice button
2: go to your homescreen
3: go back to settings and enable assistant without touching anything else
4: go back to your home screen and now it will appear in both the homescreen and app drawer

**Comment by ghost** [comment]
?

**Comment by suphon-t** [comment]
Any screenshots?
