### ISSUE TITLE
second hand missing

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1345]
## Description
second hand is missing on clock icon... Just minute and hour

## Expected Behavior
red second hand for the clock icon

## Actual Behavior
second hand missing

**Comment by ghost** [comment]
v2

**Comment by LinuxLlama** [comment]
The Pixel Launcher doesn't use the seconds hand which Lawnchair reflects in v2. The seconds hand would also increase RAM usage.

**Comment by ghost** [comment]
But in v1 it was worth it

**Comment by ghost** [comment]
And @reC0D3D lawnchair already does take alot of ram so does it make sense then?

**Comment by bohrabhijeet** [comment]
@PixelNotFound Lawnchair consumes RAM because of:
1. Blur
2. Google Feed
and
3. Notification Listener (Notification dots) 

You can disable any of the above to reduce the RAM usage

**Comment by liquidev** [comment]
Actually the second hand would probably impact battery life, not RAM usage.
