### ISSUE TITLE
New repository 'Lawnchair2' here.

### ISSUE THREAD

**Issue by DI555** [Deletescape-Media/Lawnchair#1347]
Would like to suggest create here, in the  main account, 'Lawnchair2' repository.
And issues, betas, and releases, etc. place there in 'Lawnchair2' repository.

**Comment by nyancrimew** [comment]
@DI555 Lawnchair v2 sources will be released on this same repository once we release a beta or stable build

**Comment by DI555** [comment]
Ok, but the repo may be used fornow for v2 test builds, and may be bug reports, why not ;) ?

And apkmirror's not bad, but downloading test builds from here is so comfortable!!!
P.s. telegram is blocked from me, it's no problem btw, but would like to see the v2 test builds here on github ;)!

**Comment by DI555** [comment]
And another plus to it wouldn't be a little messy here in issues, where v1 and v2 are reported together (in a mix;)).

**Comment by divadsn** [comment]
@DI555 Technically feedback for v2 is supposed to be given on Telegram 😂

**Comment by TheMatten** [comment]
> Lawnchair v2 sources will be released on this same repository once we release a beta or stable build

That's pity - I'm interested in implementing #1268 ... Can we get at least some (vague) release date?

**Comment by suphon-t** [comment]
@TheMatten As @ReC0D3D stated in #1268, we've already made some progress on it.

**Comment by TheMatten** [comment]
@paphonb ok then, thanks for reply :)
