### ISSUE TITLE
Google search bar opens twice

### ISSUE THREAD

**Issue by Arkanas1** [Deletescape-Media/Lawnchair#135]
When pressing on the google search pill/bar, then i press back i have another google search bar opened behind it, and i have to press back again to close the second search bar.
https://media.giphy.com/media/K8NxpX2LwoNsk/giphy.gif

**Comment by Arkanas1** [comment]
I deleted and reinstalled the launcher, and it is now fixed. I don't really know what caused it.

**Comment by intelligentcasanova** [comment]
If this issue has been solved, please close it.
