### ISSUE TITLE
custom icons from gallery (feature request)

### ISSUE THREAD

**Issue by fghsgh** [Deletescape-Media/Lawnchair#1353]
## Description

This is not a bug, but a feature request. You should be able to choose an image from the gallery to set as an app's icon (not only through icon packs). The displayed name is already editable, but that's not enough for me (sorry for being this kind of annoying customer, don't get me wrong, Lawnchair is still the best, but this would be really nice).

## Expected Behavior

In the app icon pick menu, there should be a PICK button to let you open the gallery and choose an icon from your filesystem.

## Actual Behavior

You can only choose from the list of installed icon packs in said menu.

## Steps to Reproduce

[screen recording (gzipped because GitHub doesn't support mp4 files directly)](https://github.com/LawnchairLauncher/Lawnchair/files/2323549/20180827_124434.mp4.gz)

1. long-press any icon
2. if it has shortcut support, tap the pencil, otherwise, tap the pencil next to "Edit"
3. tap the app icon next to the editable app name
4. at the top (next to RESET), there should be a PICK button as described above.

## Workaround
You can create your own icon pack, but that is very complicated if you don't have the tools yet. There are icon pack-generating apps that can do this, but they only support setting one "background" for all icons, or it's a paid feature.

## Environment

* Device: Xiaomi Redmi Note 4 "mido"
* Android version: 8.1.0
* Launcher version: 1.2.0.1884
* Rom: LineageOS (15.1-20180821-NIGHTLY-mido)

**Comment by alekksander** [comment]
why closed? it's not gonna happen?

**Comment by suphon-t** [comment]
It’s already implemented in the alpha branch.

**Comment by yavko** [comment]
> It’s already implemented in the alpha branch.

I don't see it working?
![Screenshot_20220901-193745_Lawnchair](https://user-images.githubusercontent.com/15178513/188047050-791e3f14-8577-4adc-b2fd-f60918293d9b.png)
![Screenshot_20220901-193823_Lawnchair](https://user-images.githubusercontent.com/15178513/188047186-1e202344-11e2-4606-b2d5-421fdbfc59b8.png)

**Comment by SuperDragonXD** [comment]
This issue was related in Lawnchair 2. Not for Lawnchair 12.1+

**Comment by yavko** [comment]
Is there a chance this feature can be reimplemented fro lawnchair 12?

**Comment by SuperDragonXD** [comment]
There will be a chance for this feature to be re-implemented, but we don't know when.
