### ISSUE TITLE
[v2] Dissappearing of installed apps view

### ISSUE THREAD

**Issue by DI555** [Deletescape-Media/Lawnchair#1357]
View of installed apps(wich appearing by touch swipe from bottom border) is dissappeared.
It's visible befor it gets up to 100% visibility, but when lt's reached full size it's not visible(. I see only clear view(.
But it's touchable!!! I can touch somewhere on screen and launch some app!!!!!
Android5.

This bug is existed and on some others launchers, based on latest Launcher3 code.
Ps. Devs, are you using the Launcher3 latest code for v2 ???

**Comment by suphon-t** [comment]
Please use the issue template and try to provide screen recordings if you're not good at English. That will help us understand the issue.

**Comment by DI555** [comment]
Yes, sorry, will be trying to record screen video. I thought it's a known bug..., I mean someone's seen.

**Comment by chongbo2013** [comment]
yes，Dissappearing of installed apps view   on reboot phone

**Comment by DI555** [comment]
Still don't see installed apps view(((
(2.0-839 alfa, Android 5.1, Spreadtrum SC7731)
