### ISSUE TITLE
After the phone reboot, the drawer icon does not load, v2

### ISSUE THREAD

**Issue by chongbo2013** [Deletescape-Media/Lawnchair#1358]
## Description
After the phone reboot, the drawer icon does not load, v2
## Steps to Reproduce
1.Set the default desktopSet the default desktop
2.reboot phone
## Environment

vivo xplay6  android 7.1.1

![_20180901_092557](https://user-images.githubusercontent.com/3191545/44941188-38571e80-adcb-11e8-8e20-16ca688b0825.jpg)

**Comment by chongbo2013** [comment]
oh .no .hei bro . no body  care?????????????????????????

**Comment by divadsn** [comment]
@chongbo2013 any logs maybe??????????

**Comment by chongbo2013** [comment]
@divadsn The phone restarts, the operation is mandatory, the log I don't know which to grab.

**Comment by chongbo2013** [comment]
@divadsn You just know how to take a mobile phone test, reboot the phone, set the default desktop

**Comment by chongbo2013** [comment]
Because this software appears after the phone restarts, the icon does not load a bug, but can only change one.
