### ISSUE TITLE
Feature Request : Right swipe to show Twitter /Instagram/ Any of our Favorite application locked in memory

### ISSUE THREAD

**Issue by dheerain** [Deletescape-Media/Lawnchair#1360]
## Description

Similar to LawnFeed. can we set the Right swipe on the home screen to show my Twitter /Facebook/Instagram Feed/ Any of our Favorite application . (The Application will be locked in memory) on Swipe it will show the Applcation. In this way We can use the Swipe left and simple go through our favourite app.

**Comment by zurdala** [comment]
I know it's closed but this would be pretty cool!

**Comment by divadsn** [comment]
Pretty much impossible lol

**Comment by zurdala** [comment]
> Pretty much impossible lol

😥
