### ISSUE TITLE
Horizontal Scroll on App drawer

### ISSUE THREAD

**Issue by donjajo** [Deletescape-Media/Lawnchair#1364]
Nice work with this launcher, perfect replacement :)
One thing I'm looking for is scrolling the app drawer by pages, side by side not up and down. Any feature like this?

**Comment by chongbo2013** [comment]
playstore search  apsu 3d launcher

**Comment by bohrabhijeet** [comment]
@chongbo2013 Guess you're in the wrong repo mate.

**Comment by donjajo** [comment]
@chongbo2013 seriously? :rofl:

**Comment by chongbo2013** [comment]
@donjajo  @abhijeetbohra  Because this software appears after the phone restarts, the icon does not load a bug, but can only change one.
