### ISSUE TITLE
[Icon Packs] Have to change home screen and app drawer icons separately

### ISSUE THREAD

**Issue by n-o-o-b** [Deletescape-Media/Lawnchair#1365]
## Description
When I want to change an icon to an alternative design from an installed icon pack, I have to change it separately for the home screen and the app drawer. If I long press and press edit from the home screen, it will only change on the home screen and vice versa.

## Expected Behavior
The icon should change both on the home screen and in the app drawer.

## Actual Behavior
Icon only changes in the place where I long-pressed it.

## Steps to Reproduce
1. Long press on an icon from either the home screen or the app drawer.
2. Press the edit button.
3. Select an alternative icon.
4. Open the app drawer (if you changed it from the home screen, or the home screen if you changed it from the app drawer). The icon will not have changed there.

## Environment
* Device: LG G6 H870
* Android version: 8.0.0
* Launcher version: 1.2.0.1884
* Rom: Stock Rom

**Comment by divadsn** [comment]
@n-o-o-b Expected behavior, you should edit icons in the app drawer, not on the desktop

**Comment by n-o-o-b** [comment]
But why is there an edit function on the home screen if I'm not supposed to do it from there?

**Comment by divadsn** [comment]
@n-o-o-b To change icons individually

**Comment by divadsn** [comment]
@n-o-o-b Changing an icon on a homescreen is only affecting change to the shortcut, not the app itself in the drawer.

**Comment by n-o-o-b** [comment]
I see. And this is baked into the OS, there's no way to make it affect the app in the app drawer too? Seems kind of a pointless feature to me.

**Comment by divadsn** [comment]
@n-o-o-b Edit the icon from the app drawer, not from the homescreen as said before.

**Comment by n-o-o-b** [comment]
I understand what you said, I was asking a separate question.

**Comment by studio315b** [comment]
An example of this feature in action:

I have a monochrome home screen with the time, my calendar and shortcuts to my common apps (browser, phone, text, email) The icons for these apps use a monochrome minimalist icon theme to blend in. My app drawer uses the default icons. When I change the icon on my homescreen, I don't want it to override my drawer icon and vice versa.
