### ISSUE TITLE
Lockscreen media controls & artwork

### ISSUE THREAD

**Issue by z-vap** [Deletescape-Media/Lawnchair#1367]
This may be more of a question that an issue or a feature request.  Lockscreen media controls artwork does not display for 3rd party apps 
## Description

When I updated from my old Moto X 2014 to a Huawei Mate SE with Android Oreo, only the builtin Music app will show custom media controls with artwork displayed on screen.   These apps used to show the album artwork or podcast artwork, now they do not.   Is this controlled by the Launcher?   And if so can this be implemented?

## Expected Behavior

Custom media controls and artwork on the lock screen

## Actual Behavior

the running app is shown with minimal controls

## Environment

* Device:    Huawei Mate SE 
* Android version: Android 8.0 (Oreo)
* Launcher version: 1.2.0.1884
* Rom: N/A

**Comment by divadsn** [comment]
@z-vap That's an EMUI bug, therefore we can't do anything about that issue

**Comment by fonix232** [comment]
No, it is in no way controlled by the launcher.
