### ISSUE TITLE
Suggestion: gesture up go to app search.,

### ISSUE THREAD

**Issue by GAZ082** [Deletescape-Media/Lawnchair#1370]
Aye. I want to keep the option to swype down to check the notifications while using the gesture up to go straight to the app search, not just the drawer.

**Comment by nyancrimew** [comment]
@GAZ082 This option has been implemented in Lawnchair V2 already

**Comment by GAZ082** [comment]
@deletescape oh goodie. Has been released? I do not see it in the Play Store.
