### ISSUE TITLE
Suggest installing Lawnstep magisk module if not present

### ISSUE THREAD

**Issue by OctoNezd** [Deletescape-Media/Lawnchair#1372]
## Description

Suggest installation of lawnstep module if it's not installed and Magisk is present

## Expected Behavior

Lawnchair suggests installing module if there is Magisk and module is not already installed or outdated

## Actual Behavior

Nothing

## Steps to Reproduce

1. Open Lawnchair without Lawnstep installed

## Environment

* Android version: 9
* Launcher version: 2.0-556

**Comment by divadsn** [comment]
@OctoNezd We cannot do that due to Google Play Store policy afaik, that's also the reason why we don't menton lawnfeed download in Lawnchair v1.

**Comment by OctoNezd** [comment]
I am not sure it will affect in that case, cause Lawnfeed was an app and Lawnstep is a Magisk module. I am trying to look up sideload policies in GPlay developer policies

**Comment by fonix232** [comment]
The rules are strict and quite obscure - possibly even the restoring of a recommended ZIP file could get us in trouble.

This is a nice idea for the non-PlayStore versions, but otherwise I'd advise against it.

**Comment by PixleProgrambetaxl** [comment]
+1
