### ISSUE TITLE
Ugly empty space between dock searchbar and icons

### ISSUE THREAD

**Issue by KasraIDK2** [Deletescape-Media/Lawnchair#1374]
## Description
* UPDATE: Even after the update the option for minimal padding does not work.
* ORIGINAL: Not really sure if it's a bug or it's supposed to be there, maybe it's to do with the pie gesture navigation but to summarize there is a very ugly empty space between the searchbar and the icons in the dock. If it's something that's supposed to be there then it would be great if there was an option to remove it.

## Expected Behavior
There should be minimal space between the searchbar and icons in the dock.

## Actual Behavior
There is a big, empty space between the icons and the searchbar in the dock.

## Steps to Reproduce
No steps, but i can provide a picture showing it:
http://imgur.com/O90jZAx

## Environment
* Device: Huawei P Smart FIG-LA1
* Android version: Android 8.0.0 With EMUI skin on top
* Launcher version: v2 556 alpha build (also on latest 564 update)

**Comment by nyancrimew** [comment]
@KasraIDK2 We have an option to minimize padding on our internal branch already, will be released with a few other fixes in a few hours
