### ISSUE TITLE
Icon shape issue

### ISSUE THREAD

**Issue by eiarhabi** [Deletescape-Media/Lawnchair#1375]
It's an issue for Lawnchair V2.
I'm not sure if it's a bug, but on my xiaomi device, the adaptive icon shape option doesn't work. After I choose 'round', it still shows a square icon.

**Comment by divadsn** [comment]
@eiarhabi What Android version?

**Comment by nyancrimew** [comment]
@eiarhabi This is a problem with miui, we will try to resolve this in the future if possible

**Comment by divadsn** [comment]
@divadsn Ok, why is that comment not there anymore?

**Comment by Stanzilla** [comment]
What helped me is just switching back and forth on my Nexus 7 (2013). Select square, wait a bit, hit the home button, watch it redraw all the icons, go back to settings again, select round, wait a bit, hit the home button and watch it redraw again.
