### ISSUE TITLE
[REQUEST] Blank page support

### ISSUE THREAD

**Issue by tytydraco** [Deletescape-Media/Lawnchair#1378]
## Description
This request specifies that the user should be able to add a new page. The most preferable way to accomplish this task would be to add an additional action to the long-press menu. This action allows this launcher to be far more compatible with theming apps such as KLWP.

## Expected Behavior
The launcher should create a new blank page after the selected one.
For example, if the original homescreen has the following layout:
[1] [2] [3]
Where page 2 is the currently selected page, the homescreen should shift the following pages one place to the right:
[1] [2] [N] [3]
Where page N is the newly created blank page.

## Disclaimer
I realize this particular topic has been recreated multiple times, but I feel it is worth mentioning once again that this is a feature that makes Lawnchair the primary option for almost all users. This is the main reason that I'd rather use Nova Launcher for KLWP. Please understand, and thank you for your consideration.

**Comment by n-o-o-b** [comment]
@deletescape Please could you allow blank pages to be added; I like to have a blank page as my homepage with just my wallpaper and dock, for mental health reasons.

Edit: it seems I can accomplish this by having a blank home widget on my homepage. Never mind.

**Comment by bohrabhijeet** [comment]
@n-o-o-b Adding a blank widget on the page and resizing it to the smallest size is one of the workarounds for a blank screen.

**Comment by n-o-o-b** [comment]
@bohrabhijeet How would I add a blank widget?

**Comment by bohrabhijeet** [comment]
@n-o-o-b You can search for it on Play Store and there are a few apps that provide a blank widget.

**Comment by n-o-o-b** [comment]
Seems a bit excessive. I'll stick to the home widget method.

**Comment by ELY3M** [comment]
I agree that this launcher need the ability to add blank screens like in Nova Launcher.
