### ISSUE TITLE
(Request new feature) Google Feed with dark theme

### ISSUE THREAD

**Issue by weirdeep** [Deletescape-Media/Lawnchair#1379]
## Description

Dark theme in Google Feed

## Expected Behavior

Google Feed doesn't turn on dark theme when the lawnchair theme as well as Oxygen OS theme is dark.

## Actual Behavior

Google Feed(discover) should be dark as well.

## Steps to Reproduce

1. 
2.
3.
4.

## Environment

* Device: OnePlus 6
* Android version: 9.0
* Launcher version: 2.0.571
* Rom: Oxygen OS

## Logcat

```
your log here
```

**Comment by weirdeep** [comment]
Sry I messed up in expected and actually behaviour. But you got the issue i hope.

**Comment by suphon-t** [comment]
That's actually the current behavior.

**Comment by weirdeep** [comment]
It's not that's why I reported this. Or you are not aware of complete dark mode yet.

**Comment by bohrabhijeet** [comment]
@iamdeep08 Lawnfeed is just an add-on to enable Google Feed on non-debug versions. The feed's theme is handled by Google, and not us. The feed's background goes dark or white depending upon what theme of the launcher is, or how dark/white is your wallpaper.

**Comment by weirdeep** [comment]
I see your point. May be Google is pushing this feature in batches. What I thought was the update which includes full dark mode, in which cards are shown in grey colour instead of white on black background, is bundled with Google discover update itself. I've got the Google discover but dark theme isn't working as of now. Thanks.

**Comment by bohrabhijeet** [comment]
@iamdeep08 I'm not aware of the dark cards in Google Discover, but let's see how Google tries to go with their overhaul.
