### ISSUE TITLE
Log the apps opened into a CSV file

### ISSUE THREAD

**Issue by subash774** [Deletescape-Media/Lawnchair#1380]
Hi,
I'm trying to do a data science project, using fitbit and phone data, find out more on how phone usage is affecting general schedule. I thought it'd be a good idea to just use lawnchair as it's my default launcher to add app open times to a csv file on the phone. As it's only used by me, it won't be a privacy violation, anyone know how I can log what applications from the launcher are clicked/opened?

Thanks

**Comment by divadsn** [comment]
@subash774 There is Digital Wellbeing on Android Pie and apps which have access to your usage data, no need to have that into a launcher.

**Comment by subash774** [comment]
@divadsn thanks for the quick reply, but project is due soon and I just wanted to try it out as Android P is probably months/weeks away.

**Comment by divadsn** [comment]
@subash774 App usage is available on most Android versions right now, just find an app on Play Store, there are plenty of them.

**Comment by ghost** [comment]
there's this app called antisocial that does what you want
