### ISSUE TITLE
Add new app on the msin screen doesn't work for workspsce

### ISSUE THREAD

**Issue by linsui** [Deletescape-Media/Lawnchair#1383]
## Description

I use shelter to freeze some apps. Every time I freeze and unfreeze an app the icon will be deleted from and added to the mainscreen. The option to change the behavior doesn't work.

## Expected Behavior

Just as the PixelLauncher, the new workspace app won't be added to the mainscreen.

## Environment

* Device:Xiaomi Mi 6
* Android version:9
* Launcher version:1.2.0.1884
* Rom:PixelExperience

**Comment by ghost** [comment]
Same for me.

**Comment by linsui** [comment]
Discontinued? @deletescape 
I got. Great! :+1:

**Comment by nyancrimew** [comment]
@linsui see #1462
