### ISSUE TITLE
Wrong numbe of columns in the app drawer after restart

### ISSUE THREAD

**Issue by flocke** [Deletescape-Media/Lawnchair#1386]
## Description
I set the number of columns for the app drawer to 5 (6 is default). Right after I set it everything works as expected (5 columns shown), but after I reboot my phone it shows 6 again. In the settings it still shows my custom 5 columns. If I set it to something else and then back to 5 it works again, so I assume it just isn't honoring the custom settings on first start for some reason.

## Expected Behavior
Show only 5 columns right after reboot.

## Actual Behavior
Shows 6 columns (default) even though 5 are set.

## Steps to Reproduce
1. Set the columns for the app drawer to something other than the default value
2. Reboot your phone
3. Open the app drawer

## Environment
* Device: Moto G5 Plus
* Android version: 9.0
* Launcher version: 2.0-601-ci-alpha
* Rom: ArrowOS

[Screenshots of the Settings and the drawer right after a reboot](https://cloud.shadowice.org/s/LJ3SpTgxNywb2DY)

## Logcat
Will get a logcat as soon as I am home (on the road right now).

**Comment by flocke** [comment]
Closing because I posted this issue twice (it didn't show up in the issue list an hour after I first submitted it, so I thought something went wrong). See #1387 for the newer one.

**Comment by divadsn** [comment]
@flocke GitHub was broken at the time, so yeah, we are aware of that :)
