### ISSUE TITLE
Bug: "add icon to home screen" doesn't always work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Deletescape-Media/Lawnchair#1390]
## Description
The launcher doesn't always put an app icon for newly installed apps.

## Expected Behavior
The app icon should appear for the new app, because the settings for it is enabled

## Actual Behavior
Nothing .

## Steps to Reproduce
1. Install Lawnchair. Make it default one. :)
2. Make sure "add icon to home screen for new apps" is enabled. Install any app from Play Store to see that it works.
3. Download and install any APK file from APK-mirror website, of an app that isn't installed yet.

## Environment
with stock)
* Device: Pixel 2 
* Android version: Android P PPR2.181005.003 
* Launcher version: 1.2.0.1884 , version number: 1884
* Rom: stock

**Comment by AndroidDeveloperLB** [comment]
@deletescape Why close? Is it now fixed?

**Comment by nyancrimew** [comment]
@AndroidDeveloperLB feel free to reopen any issues regarding v2, we're closing all issues because it became impossible to handle this and will have a proper workflow in place in the future

**Comment by AndroidDeveloperLB** [comment]
@deletescape By "reopen", you mean to create a new one?
I can't reopen this. I don't have the button to do it...
