### ISSUE TITLE
Bug: incompatibility with some live wallpaper apps

### ISSUE THREAD

**Issue by alphajoza** [Deletescape-Media/Lawnchair#1391]
Using live wallpaper apps such as Muzei, when these apps try to automatically change wallpaper (slideshow mode), Lawnchair freezes for more than one minute and finally I have to force close Lawnchair and launch it again.

**Comment by CodenameSam** [comment]
I was using alpha 137 version, in that when I open my wallpaper app by Google from tapping n holding home screen>wallpaper , the app didn't used to show on recents screen. After updating to 601 directly, I've issues with it. When i open it from long press home home screen>wallpaper, the app started showing in the recent screen and when I close it, my daily wallpaper doesn't change coz wallpaper app gets closed. 
I'm using redmi note 4 running on android 7.0(miui 10 global beta.).
Please fix this issue. I don't want that wallpaper app to be shown in recent menu and don't want to close it by mistakenly. (even by swiping and closing from recent)
