### ISSUE TITLE
[REQUEST] Search for icons when in change icon menu

### ISSUE THREAD

**Issue by poperigby** [Deletescape-Media/Lawnchair#1392]
This would make it a lot easier to find a particular icon you wanted. What I mean by icon searching is have it open the icon pack like on Nova launcher.

**Comment by bohrabhijeet** [comment]
@PopeRigby We already have this in v2, have you tried it out?

**Comment by poperigby** [comment]
I thought v2 was still in beta and I couldn't find a way to opt into the beta program

**Comment by bohrabhijeet** [comment]
@PopeRigby You can download v2 either from APKMirror or t.me/lawnchairci

**Comment by poperigby** [comment]
Alright thanks
