### ISSUE TITLE
Trying To Add Lawnchair to in both Nuget&Pie my Custom rom as is without install gradle and using make

### ISSUE THREAD

**Issue by BAProductions** [Deletescape-Media/Lawnchair#1394]
## Description
 How would to this so its build Lawnchair Lawnchair_feed with make and not gradle to save space on my HDD 

## Expected Behavior
Build with rom

## Actual Behavior
Not building with my rom

## Steps to Reproduce
None

* Device:None Want to add it to my rom with make not gradle(SM-T530NU&SM-T560NU)
* Android version: 7.1.2:r36
* Launcher version: 3
* Rom: LineageOS 14.1

## Logcat
 I don't have one

**Comment by nyancrimew** [comment]
@BAProductions The best and easiest way to add Lawnchair to your ROM is by adding it as a prebuilt

**Comment by BAProductions** [comment]
Thank but if I add it as a prebuilt then how to I use the overlay folder than.
If not can I get a prebuilt sign for the play store so it auto update then

**Comment by nyancrimew** [comment]
@BAProductions You can find build of all our variants on apkmirror.com you can use as prebuilts
