### ISSUE TITLE
Broken shadow in app drawer

### ISSUE THREAD

**Issue by Friend-LGA** [Deletescape-Media/Lawnchair#1397]
If I use not rounded search bar in app drawer, it suppose to drop shadow while scrolling. But in my case it is not a shadow, but opaque gray stripe.

https://drive.google.com/file/d/1fwXYdIHy1ytkKOL83WUjIGn9PH3hkUa9/view?usp=drivesdk

Device: OnePlus 6T
Launcher v1.2.0.1884

**Comment by fonix232** [comment]
@Friend-LGA Please upload the image to an open host, or remove the requirement to request access. Thanks!

**Comment by Friend-LGA** [comment]
Should be available now
