### ISSUE TITLE
Abbreviation in Weekday

### ISSUE THREAD

**Issue by rodrigojcmello** [Deletescape-Media/Lawnchair#1398]
## Description

In Portuguese Thursday (Quinta-feira) can be abbreviated by Qui. Quinta-feira is too long to be displayed in a small screens like smartphones.

By the provision of how the information is displayed it is impracticable to show the names of the days of the week completely, in the Pixel Launcher the full name is displayed but there the layout is different, the day of the week is over the complete date, here the day of the week dispute space with the date (same row).

Weekdays in Portuguese
Sunday (Domingo) - abbreviation Dom
Monday (Segunda-feira) - abbreviation Seg
Tuesday (Terça-feira) - abbreviation Ter
Wednesday (Quarta-feira) - abbreviation Qua
Thursday (Quinta-feira) - abbreviation Qui
Friday (Sexta-feira) - abbreviation Sex
Saturday (Sábado) - abbreviation Sáb

## Expected Behavior

Add weekdays abbreviations in clock widget in pt-br

## Actual Behavior

Month name is completed hidden because of the long Portuguese weekdays names

## Steps to Reproduce

1. choose Portuguese as the default Android language 
2. press "home button"
3. Look at clock widget

## Environment

* Device: Xiamo MI5S / Capricorn
* Android version: 9
* Launcher version: 2.0-601-ci-alpha
* Rom: LineageOS 16.0

![whatsapp image 2018-11-15 at 10 29 14](https://user-images.githubusercontent.com/5174526/48555945-ad65ca80-e8c9-11e8-9d59-b64a696b65a2.jpeg)

**Comment by nyancrimew** [comment]
Can you check what this same data would look like in the Pixel Launcher / Google's at a glance widget?

**Comment by rodrigojcmello** [comment]
Google fixed it with smaller font size and using month name abbreviation.

![whatsapp image 2018-11-19 at 10 13 34](https://user-images.githubusercontent.com/5174526/48706600-e19bfc80-ebe3-11e8-90c8-5e3d88b91aac.jpeg)

**Comment by nyancrimew** [comment]
@rodrigojcmello Alright, we'll try to get our implementation to align more with that of google
