### ISSUE TITLE
Ability to access launcher settings and use app shortcuts disappears 

### ISSUE THREAD

**Issue by reysetti** [Deletescape-Media/Lawnchair#1400]
## Description
After some time I lose the ability to access the launcher's setting and use long-press shortcuts. I consistently lose this function multiple times per day.

## Expected Behavior
Long pressing on the home screen should pop up with the options to select Wallpapers, Widgets, Settings and add a home page. Holding and releasing an app icon opens the shortcuts for that specific app. 

## Actual Behavior
Nothing happens when the home screen is long-pressed. Holding and app icon highlights it but nothing further occurs. 

## Steps to Reproduce

1. Have Lawnchair installed
2. Wake from sleep/lock 
3. Try and open the settings or use app shortcuts
4. Reboot device or Force Stop app to restore functionality
5. Repeat till functionality is lost again

## Environment

* Device: Moto Z2 Play US version "Albus"
* Android version: 8.0.0 & 8.1.0
* Launcher version: 1.2.0.1884
* Rom: Stock & LineageOS

**Comment by reysetti** [comment]
This might be an isolated issue. I've flashed LineageOS and the issue is gone.

**Comment by breversa** [comment]
Same happens on an older Samsung Galaxy Core Prime running Android 5.1 (Touchwiz) with the same Lawnchair version.
