### ISSUE TITLE
Do you guys track us or any other use of tracking tools?

### ISSUE THREAD

**Issue by zero-arc** [Deletescape-Media/Lawnchair#1401]
Hi,
This is just a simple question but do you guys track us using google analytics, metrica and other else?

It's just that it's hard to find good launcher apps today that does not track.

Also sorry if this is the wrong place to ask...

**Comment by divadsn** [comment]
@arcenas090 No

**Comment by zero-arc** [comment]
Hi,
Thanks for the reply but could you give me a peice of proof that could convince me?
Thanks!

**Comment by divadsn** [comment]
@arcenas090 Well, take a look into the source code, we don't include any libraries that are used for tracking, all data sent to 3rd parties is only used to get weather information from OpenWeatherMap or Google Awareness API. But again, we are not responsible for their privacy policy at that point.

**Comment by LuminarySage** [comment]
@arcenas090 Lawnchair is open source. You have access to the whole source code. Go ahead and check
