### ISSUE TITLE
Suggested apps no longer work in alpha 689 build

### ISSUE THREAD

**Issue by goanga** [Deletescape-Media/Lawnchair#1406]
## Description

On OnePlus 6, OxygenOS 9.0.2. After installing alpha 689 (specifically for the new app suggestions engine!), the app suggestions space is blank.

## Expected Behavior

There should be some suggested apps at the top of the drawer.

## Actual Behavior

No apps are suggested.

## Steps to Reproduce

https://i.imgur.com/Il7rUuX.jpg

2.
3.
4.

## Environment

* Device: OnePlus 6
* Android version: OxygenOS 9.0.2
* Launcher version: alpha 689 build
* Rom: stock

## Logcat

```
your log here
```

**Comment by bohrabhijeet** [comment]
@goanga We know about this issue. Developers are investigating and will fix it soon.

**Comment by goanga** [comment]
The issue is still present for me even after the Dec 29 update

**Comment by goanga** [comment]
Using alpha 746, the issue persists. The first row does show suggestions, but they are the default ones and never change

**Comment by bohrabhijeet** [comment]
@goanga That's a known issue. It'll be fixed in the upcoming builds. Stay tuned.
