### ISSUE TITLE
Dock Fill When Collapsed UI Error

### ISSUE THREAD

**Issue by hssahdev** [Deletescape-Media/Lawnchair#1407]
## Description
See attached image!
Dock fill overlaps with Icon labels

## Steps to Reproduce
1.  https://drive.google.com/file/d/1MgvGXr0Xp0Mx-rmK76-lsoO6LzYbJdU-/view?usp=sharing

## Environment

* Device: Oneplus 3
* Android version: 9.0
* Launcher version: 2.0-698-ci-alpha
* Rom: SkyDragon

**Comment by nyancrimew** [comment]
@hssahdev This is a known issue and will be investigated
