### ISSUE TITLE
Icon shape not working on Samsung Galaxy S7, Android 7.0

### ISSUE THREAD

**Issue by lukefisklennon** [Deletescape-Media/Lawnchair#1408]
**EDIT**: sorry about not using the issue template. I was writing it on the FastHub Android app which doesn’t load in the template.

Hi there,

I’ve just started using Lawnchair and I’m loving it. Just… _wow_!

There’s one small problem though. The icon shape feature doesn’t seem to be working. A few apps change their shape, such as Substratum and Google Calender, but the vast majority just stay the same.

My phone is a Samsung Galaxy S7 running Android 7.0. The version of Lawnchair is 1.2.0.1884.

Any idea what could be going on?

Thanks so much!

**Comment by ghost** [comment]
@lukefisklennon Got any logs?

**Comment by lukefisklennon** [comment]
@preprux How would I go about getting logs?

**Comment by lukefisklennon** [comment]
Response to support ticket:

> This is because apps need so support adaptive icons to have adaptive icons. If they don't have it we can't use it. In our lawnchair alpha we have implemented adaptive icons generation for non adaptive icons, but currently adaptive icons only work on Android 8 and above. In the Future we will backport this feature to Android 7 and lower
