### ISSUE TITLE
Widgets in pill area

### ISSUE THREAD

**Issue by uudruid74** [Deletescape-Media/Lawnchair#141]
Lawnchair seems to treat the 'pill area' as special even if it's turned off.  A widget in the pill area can not be resized and a widget below the pill area can not be moved up to the top of the screen nor resized into that area.  Additionally, the widget acts like it's scaled via some bitmap routine rather than letting the widget do the work.  It's noticeably blurry compared to other launchers.  I'm using a custom KWGT widget, so it takes up most of my homescreen and provides all the features I want.  If it won't work, then lawnchair can't come in the house and it stays outside.

**Comment by Dondrejohnson5** [comment]
Image, maybe?

**Comment by uudruid74** [comment]
For comparison, here is my usual desktop using Nova Launcher.  The widget looks the same on all Launchers but this one.

![screenshot_20170706-072708](https://user-images.githubusercontent.com/7726301/27911404-92c26054-621e-11e7-9e4d-0dd369f45d29.png)

## Lawnchair 
In the upper area, I can not resize the widget in any way ...

![screenshot_20170706-072807](https://user-images.githubusercontent.com/7726301/27911500-de5fc5ba-621e-11e7-9ec6-d223338cbdce.png)

When moved out of this area, it can be dragged back up to the top, nor resized to include the upper area.  Also, notice the blurred edges from the odd scaling compared to the original.

![screenshot_20170706-072820](https://user-images.githubusercontent.com/7726301/27911488-d1460f92-621e-11e7-9eb8-36aaf4b0a908.png)

**Comment by fishears** [comment]
I've had this issue and solved it by opening the app drawer after disabling the pixel top bar. It seems to refresh the home screen. Then I add my widget at the top of the screen.

**Comment by uudruid74** [comment]
This does not fix the issue for me.  I even tried with the default clock widget and the clock / weather widget.  Opening app drawer doesn't help.

The launcher just isn't usable for me since I don't like "pills" on my desktop and I have no need to clone the pixel's UI.  Everyone else is asking for weather and blur effects and I'm talking basic usability here!

**Comment by Mr-Perezident** [comment]
Try using in the debug section of setting the restart lawnchair button.

**Comment by uudruid74** [comment]
I use Nova as my daily driver.  So the test I just did started Lawnchair for the first time since starting my phone.   You want me to restart it again?  How many times?   What next?  Cat in a paper bag and spin it around my head?   How about someone looks at the code and finds the bug and fixes it rather than wasting my time looking for a work around?

I might be willing to look at it when I have time, but its gonna be a long while.

**Comment by Mr-Perezident** [comment]
Sorry I was trying to help.

**Comment by fonix232** [comment]
@uudruid74 Please take back on your tone.

Lawnchair is primarily a Pixel launcher, bringing the looks and feels of the Pixel to other phones, with some extra features missing from the original. Your use case is pretty unique, and the few others who also use it that way tried to help.

We're actively looking into bugs and crashes, hence why we switched crash logging recently, but our main attention is on streamlining the whole structure of the code, getting rid of legacy overcomplicated Launcher/Launcher2 bits (and even some Launcher3 stuff), and fixing it up so it doesn't crash. After that we can consider looking at the lesser bugs (since this one is certainly a bug, but not something that makes use of the launcher impossible). I'm marking it as an enhancement for now, so that it won't end up in our pretty tight 0.1 milestone accidentally. But don't worry, all valid open issues will be considered. Just don't forget that we're a small team working in our free time on this project, expecting nothing in return but politeness.

**Comment by uudruid74** [comment]
My apologies, but if it the issue could be rectified without looking at the source, I would have done it. 

Yes, crashes come first, usability next, but dark themes, weather, O styling, and all the prettiness should take a back seat to basic things like widget placement IMHO.   It's not an "enhancement".

**Comment by fishears** [comment]
@uudruid74  "I don't like "pills" on my desktop and I have no need to clone the pixel's UI" - maybe this isn't the right launcher for your requirements as it aims mainly to replicate the Pixel launcher for non-Pixel devices. I'm not being rude, honestly, its just that there's a lot of launchers out there that don't have the pill and don't look like the pixel UI...

**Comment by uudruid74** [comment]
My interest is purely because it's open source.

On Jul 15, 2017, John Philpott <notifications@github.com> wrote:
>@uudruid74  "I don't like "pills" on my desktop and I have no need to
>clone the pixel's UI" - maybe this isn't the right launcher for your
>requirements as it aims mainly to replicate the Pixel launcher for
>non-Pixel devices. I'm not being rude, honestly, its just that there's
>a lot of launchers out there that don't have the pill and don't look
>like the pixel UI...

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by fishears** [comment]
OK, but it is possible to use the space in the meantime - you just have to play a little, try a few things;)
![screenshot_20170715-111017 resized](https://user-images.githubusercontent.com/909571/28238565-a7a2905c-694e-11e7-9464-d1667341be16.png)

**Comment by uudruid74** [comment]
That clearly shows the pill in the space.  If I can turn off the pill, I should be able to put my own widget in the space.   IMHO, the "pill" is the "enhancement" and basic functionality is broken

On Jul 15, 2017, John Philpott <notifications@github.com> wrote:
>OK, but it is possible to use the space in the meantime - you just have
>to play a little, try a few things;)
>![screenshot_20170715-111017
>resized](https://user-images.githubusercontent.com/909571/28238565-a7a2905c-694e-11e7-9464-d1667341be16.png)

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by fishears** [comment]
No, that's NOT the Lawnchair pill, it's the one in Pixel Widget Pro which is the widget I use in place of the Lawnchair top bar. You can clearly see that the widget resize box uses the whole of the top of the screen space - that means Lawnchair isn't using that space. Look - I've moved it to show you:
![screenshot_20170715-121635 resized](https://user-images.githubusercontent.com/909571/28238961-bef7b238-6957-11e7-80f9-14805ebd3424.png)

**Comment by paphonbth** [comment]
That pill in the screenshot is from a widget, not from the launcher.

**Comment by uudruid74** [comment]
I can get a widget up there, but once up there I can't resize it.  Put it up top and taller than 1 icon

On Jul 15, 2017, paphonbth <notifications@github.com> wrote:
>That pill in the screenshot is from a widget, not from the launcher.

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by fishears** [comment]
I'm finished here. I've given you two screenshots of me having done what your original issue says can not be done I.E. resizing a widget in the pill area and moving a widget into that area from below it. I'm using the full height of my screen. It's a 5x5 grid, the Fit widget is 2x2, Pill widget is 1x5 and then 2 rows of icons.   You simply refuse to accept what you see. Enjoy the rest of your day.

**Comment by uudruid74** [comment]
No you most certainly have not.  Look at the very first picture I posted.  I want a damn widget to extend from the top of the screen down more than 1 freaking row.   It's bug.  It doesn't work.  Shove your attitude up your ass with your damn pill.   If I wanted a pill at the top I'd use the built in one.   I want a damn clock at the top of my screen and I want it BIG, not 1 line high. 

I was very plain that if it was possible without source, I would have done it.  Now quit being an ass.

On Jul 15, 2017, John Philpott <notifications@github.com> wrote:
>I'm finished here. I've given you two screenshots of me having done
>what your original issue says can not be done I.E. resizing a widget in
>the pill area and moving a widget into that area from below it. You
>simply refuse to accept what you see. Enjoy the rest of your day.

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by uudruid74** [comment]
@paphonbth Thanks!   Will try the new commits soon
