### ISSUE TITLE
Hacking tools detected when trying to change icon pack

### ISSUE THREAD

**Issue by XenocodeRCE** [Deletescape-Media/Lawnchair#1410]
Hello :-) 

## Description

When I try to change the used icon pack i got a message telling me to remove hacking tools detected on the phone before continue.

## Expected Behavior

Not having this message preventing me from using the icon pack i want.

## Actual Behavior

An error message is preventing me from installing any icon packs

## Steps to Reproduce

1. Install LuckyPatcher / GameGuardian
2. Not enjoy Lawnchair 

screenshot (french) : https://www.sendspace.com/file/rl927y

## Environment

* Device:
* Android version: 8.0
* Launcher version: latest up to this date
* Rom: custom kernel mod

Have a nice day :-)

**Comment by divadsn** [comment]
@XenocodeRCE Lucky Patcher, there you have it 🤷

**Comment by fonix232** [comment]
## Description
User is a dumbass pirate

## Expected Behavior
User buys icon packs and other software to support the developer

## Actual Behavior
User decides to use Lucky Patcher to get things for free

## Steps to reproduce
1. Be an asshole big enough to think you're entitled to free stuff
2. Download Lucky Patcher
3. Try to use Lawnchair with custom icons
4. ???
5. Profit. Oh wait, you can't, cuz YOU'RE A PIRATE

## Environment
* Device: Any
* Android version; Any
* User IQ: Below 70


Have a nice day :-)

**Comment by abhayruparel** [comment]
😂😂😂😂

**Comment by XenocodeRCE** [comment]
I did not use LuckyPatcher to get IconPacks for free ? I bought this icon pack and can prove it ? So please stay gentle and polite.

**Comment by divadsn** [comment]
@XenocodeRCE So why even the use of Lucky Patcher?

**Comment by XenocodeRCE** [comment]
So this launcher simply prevent icon pack loading just because LuckPatcher is installed on the device ?

**Comment by divadsn** [comment]
@XenocodeRCE Lucky Patcher is a privacy tool, get rid of it

**Comment by ghost** [comment]
@XenocodeRCE https://tinyurl.com/luckluckypatch

**Comment by fwapy** [comment]
In general lawnchair doesn't like pirates, and you are considered to be a pirate by having it installed

**Comment by ghost** [comment]
@XenocodeRCE In general lawnchair doesn't like pirates, and you are considered to be a pirate by having it installed

**Comment by XenocodeRCE** [comment]
So I bought the icon pack and I can't even use it on Lawnchair because the dev is blind on the fact that somebody could install LP without being a pirate ? 

I use it to handle permissions on some app that asks too much in my humble opinion.

**Comment by divadsn** [comment]
@XenocodeRCE There is no valid reason to use Lucky Patcher, period.

**Comment by ghost** [comment]
@XenocodeRCE Just uninstall the app and get over with it, there's nothing you can get out of this debate

**Comment by XenocodeRCE** [comment]
I'll just download source and get rid of that LP check and build the apk ? Cool

**Comment by nyancrimew** [comment]
@XenocodeRCE Yes, you are free to do with our source what you want and we can't restrict you from doing that. V2 also does not contain any checks for piracy apps anymore and we try to keep it as unopinionated as we can
