### ISSUE TITLE
swipe up from dock not opening the recents but instead going to app drawer. not the same behavior as stock pie launcher

### ISSUE THREAD

**Issue by OliverRhyme** [Deletescape-Media/Lawnchair#1413]
## Description
swiping up from the dock does not open the recent apps as opposed to the stock android pie launcher behavior (quickstep installed)

## Expected Behavior
when you swipe up the dock once it should bring you to recent screen with predictive apps

## Actual Behavior
goes into app drawer instead.

## Steps to Reproduce
1. swipe up from dock
2. it will open to app drawer instead of recent apps

## Environment

* Device: Xiaomi Mi A2 Lite
* Android version: 9
* Launcher version: alpha build 740
* Rom: Stock pie

**Comment by bohrabhijeet** [comment]
@Bberx Have you flashed Quickswitch zip?

**Comment by OliverRhyme** [comment]
Yup via twrp. The recent apps works well but the problem is that swiping the once it goes to app drawer as opposed to the stock pie behavior where it goes to recents then another swipe for app drawer

**Comment by bohrabhijeet** [comment]
@Bberx That's not a bug, instead it's an intended behaviour. Go to Gestures > Swipe up from dock to configure it.

**Comment by OliverRhyme** [comment]
ow my bad thanks.
