### ISSUE TITLE
Dock Blur on changing background

### ISSUE THREAD

**Issue by Lyr3x** [Deletescape-Media/Lawnchair#1415]
When using the blurred dock and changing the background the blurred part shows still the old background. To update the dock you need to toggle the blurring off and on.
When using daily changing backgrounds the toggle does not help at all. 

Tested on:
- Android 9.0
- OnePlus 6T
- Lawnchair 2 2.0-746-ci-alpha

**Comment by bohrabhijeet** [comment]
@Lyr3x Usually a restart fixes it.

**Comment by Lyr3x** [comment]
That's not the point because it should always refresh the dock blur image instantly

**Comment by skittles9823** [comment]
@Lyr3x He didn't give you a fix, he gave you a temporary workaround until it's fixed. Even then, it doesn't take much to simply force stop the launcher.

**Comment by Lyr3x** [comment]
Sure :+1:

**Comment by steviator** [comment]
Toggling blur off and on again in Lawnchair settings does the trick quicker than force stopping.
