### ISSUE TITLE
[v2] Follow night mode theme doesn't persist for long

### ISSUE THREAD

**Issue by viggy96** [Deletescape-Media/Lawnchair#1416]
## Description
Using 'follow night mode' theme appears to crash after an hour after taking effect, and the launcher reverts back to light, when the system is still on night mode. 

## Expected Behavior
Launcher should stay on night mode when the system is. 

## Actual Behavior
After a short time, a half hour or hour, the launcher no longer follows the system night mode, and reverts to 
light theme, when the system is still on night mode. 

## Environment
* Device: Motorola Moto X4
* Android version: 8.1.0
* Launcher version: v2 alpha 721
* Rom: LineageOS 15.1

**Comment by suphon-t** [comment]
Please attach the crash log.

**Comment by viggy96** [comment]
I'll try to capture a logcat, but the nature of this bug makes it very hard to predict when exactly it will occur.

**Comment by viggy96** [comment]
I've found that it could be the Google Messenger app's dark mode that is messing with Lawnchair's automatic night mode. When I disable Messenger's dark mode, the launcher reverts to light, when it should still be on dark. I've attached a logcat, but I couldn't see anything in it useful. Maybe you guys can see something in it. 
[lawnchair_output.txt](https://github.com/LawnchairLauncher/Lawnchair/files/2719803/lawnchair_output.txt)

**Comment by suphon-t** [comment]
Then that’s the correct behavior. Lawnchair follows the system night mode and Google Messenger app toggles that.

**Comment by noahajac** [comment]
While confirmed to not be an issue with Lawnchair, have you figured out how to stop Google's Message app from messing with night mode?

**Comment by divadsn** [comment]
@noahajac Google Messages changes your system's night mode and therefore Lawnchair is following that option too.

**Comment by viggy96** [comment]
@noahajac The real solution to this is Google updating the Message app to follow the system night mode.

**Comment by noahajac** [comment]
@viggy96 Fully agreed. In the meantime I have the option in the Message app being changed automatically using Tasker (rooted). Just wondering if you have a less bodge solution.
