### ISSUE TITLE
Gestures: double tap to lock as admin option missing in newest build.

### ISSUE THREAD

**Issue by dhufford81** [Deletescape-Media/Lawnchair#1417]
## Description

The double tap to lock as admin is not a selection in the gesture menu anymore, this is really handy to actually lock the device down if needed. I appreciate the ability to lock out the fingerprint sensor on short notice.

## Expected Behavior

Make the proper selection for my need/want.

## Actual Behavior

Option not available to choose.

## Steps to Reproduce

1.open settings
2.navigate to gestures
3.choose double tap
4.see missing sleep as admin option

## Environment

* Device:Pixel 3XL
* Android version:9.0
* Launcher version: Lawnchair 2 2.0-746-ci-alpha 
* Rom:stock/rooted

## Logcat

```
your log here
```

**Comment by dhufford81** [comment]
hope this isn't annoying, just wanted to speak up on something i liked and missed when it disappeared.

**Comment by skittles9823** [comment]
@dhufford81 It's still there. Just moved into the collective "sleep" gesture. Basically it will automatically choose which is the best way to lock the device. 

Idk how to force the admin one specifically but if you deny lawnchair root and don't grant it accessibility it'll probably revert to device admin.

**Comment by dhufford81** [comment]
the first version i installed had the actual sleep as admin option in gestures, i updated today and that is now gone.

**Comment by dhufford81** [comment]
it is never choosing to lock as admin at the moment, if i double tap, i can immediate re-unlock with with the fingerprint sensor. i have it set as full control thinking that would help.

**Comment by dhufford81** [comment]
i believe i previously had Lawnchair 2 2.0-601-ci-alpha, but i don't remember and i deleted it after i updated today. i pulled it off an xda link so i know it was a little older.

**Comment by dhufford81** [comment]
thanks for the quick response btw, it's not a deal breaker by any means just food for thought. great job on this project it is really impressive!

**Comment by bohrabhijeet** [comment]
@dhufford81 Locking as admin is sometimes annoying. You have to unlock the device with the PIN/pattern everytime. It's better begone lol

**Comment by dhufford81** [comment]
i understand that it's not for everyone, why not just throw it in for an option for people who want though? it's a wonderful security feature. i work itsec field and loved it. now my only recourse is going back to googles lockout feature by hitting the power button and choosing lockout.

**Comment by dhufford81** [comment]
hell even if there's just a line of code i can modify to make mine do what i want, i would be open to modifying mine every release. i like it that much.

**Comment by skittles9823** [comment]
@dhufford81 That's fair if there was any sleep provider to separate, it would be device admin.
