### ISSUE TITLE
Lag in swiping from app to recent apps panel

### ISSUE THREAD

**Issue by aviwad** [Deletescape-Media/Lawnchair#1424]
If an app is open, and you swipe up with navigation gestures, or click the multitasking button, the animation for the app zooming out into the recents app panel is very laggy.

## Description

All other animations are smooth, but this one is super glitchy, and I think because it keeps updating the app screen while doing the animation, so maybe just freeze the screen and then do it to make it faster?

## Expected Behavior

The animation should be buttery smooth

## Actual Behavior

glitchy, jaggy animation

## Steps to Reproduce

1. set Lawnchair to give recents panel through QuickSwitch (this issue also occurs in Pixel Launcher)
2. open phone app
3. click multitasking button or swipe up
4. notice the slow animation to recents apps

## Environment

* Device: Xiaomi Redmi Note 4 Snapdragon
* Android version: 9
* Launcher version: alpha 760
* Rom: Syberia Project (issue also occurs in Pixel Experience rom)

**Comment by LaeliocattleyaLustre** [comment]
Were you able to find a fix for this?
