### ISSUE TITLE
[FR] Lock when phone snatched out of hand

### ISSUE THREAD

**Issue by CrimsonFork** [Deletescape-Media/Lawnchair#1427]
It would be nice if there was an automatic lock on detection of a strong non-gravitational force. I found that there is [PluckLockEx](https://github.com/0xFireball/PluckLockEX), but it doesn't work on my devices.

**Comment by fonix232** [comment]
Dammit Jim, I'm a launcher, not a security officer!

**Comment by CrimsonFork** [comment]
I just thought it would fit, since when I first saw that, I immediately thought of Lawnchair's double-tap feature.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
