### ISSUE TITLE
Incorrect recent apps position with hidden dock and quickstep

### ISSUE THREAD

**Issue by gavinfernandes2012** [Deletescape-Media/Lawnchair#1429]
## Description

Lawnchair's app suggestions overlap with the recent apps when the dock mode is hidden and quickstep is being used.

## Expected Behavior
The apps are (vertically) positioned correctly ie. centered in the free space.

## Actual Behavior
The app suggestions cover up part of the recent apps
https://photos.app.goo.gl/U3NmjzVFNyFdYght6

## Steps to Reproduce
1. Use quickstep to get pie recents integration working
2. Change the dock style to hidden
3. Open the recents screen

## Environment

* Device: Essential Ph-1
* Android version: Pie (January update)
* Launcher version: 2.0-808-ci-alpha
* Rom: Stock, but with magisk and pix3lify

**Comment by choboko** [comment]
I'm seeing this exact same issue. I should add that when the search bar is enabled in dock, the recents screen shows the space where the search bar is supposed to be but the search bar is missing, here's a screenshot:

https://photos.app.goo.gl/V57hL37hPLk8o72PA

This is what I'm using:

Device: Nextbit Robin
Android version: Pie
Launcher version: 2.0-839-ci-alpha
Rom: XenonHD ROM, with Magisk
