### ISSUE TITLE
Find a bug in app drawer for mi8se

### ISSUE THREAD

**Issue by lyl12321** [Deletescape-Media/Lawnchair#1430]
As I slide up and down, repeated draws appear above the navigation bar.
OS:PE PR2 GSI
Vendor:Xiaomi
Model:8se
app Version: 2.0-808-ci-alpha

**Comment by suphon-t** [comment]
@lyl12321 Please include a screenshot. That will help identify the issue.

**Comment by lyl12321** [comment]
![](https://raw.githubusercontent.com/lyl12321/picture/master/Screenshot_20190116-231511.png)
![](https://raw.githubusercontent.com/lyl12321/picture/master/Screenshot_20190116-231538.png)

**Comment by lyl12321** [comment]
> @lyl12321 Please include a screenshot. That will help identify the issue.

Ok,upload finished 😀

**Comment by lyl12321** [comment]
Google official Pixel Launcher has this problem too

**Comment by lyl12321** [comment]
Oh i'm sorry.It's all my fault.It possible with my gpu driver bad.Please forgive me.
