### ISSUE TITLE
Restoring from backup problem: does not revert widgets + icons

### ISSUE THREAD

**Issue by jackTaw88** [Deletescape-Media/Lawnchair#1433]
## Description
Restoring from backup, does not revert my widget and icon settings.

## Steps to Reproduce
1. install launcher (first time)
2. add whatapp widget to my home screen
3. open firefox, open any web page, click "settings" --> "page" --> "add page shortcut". it adds new icon to home page of launcher.
4. create backup with all options from launcher
5. remove firefox icon + whatsapp widget
6. restore the latest backup
7. open home screen again
8. On this step I can not see my old whatsapp and firefox icon.

Should I backup Lawnchair data's from adb command line? :(

## Environment
Device: Huawei Mate 10
Android version: 8.0.0
Launcher version: 1.2.0.1884
Rom: Stock Rom

**Comment by bushrang3r** [comment]
I'm having the same issue. I'd really like to use this launcher but the restore feature doesn't work at all.

Device: Galaxy NOTE 4
Android version: 9.0
Rom: Resurrection Remix

**Comment by lawson85** [comment]
I have a similar issue where it tries to put old widgets back even when the appi is not installed, even if the backup is created after uninstalling the widget app

**Comment by omgwtfbbqpls** [comment]
@deletescape Whyyy is this issue closed? Why does it[ keep getting closed?](https://github.com/LawnchairLauncher/Lawnchair/issues/1198) It still isn't fixed.

**Comment by divadsn** [comment]
@omgwtfbbqpls all stale issues got closed due to v2 release a year ago.

**Comment by omgwtfbbqpls** [comment]
@divadsn But this is happening on v2. Isn't this where v2 issues should be reported? If it's closed because it's stale, does that mean it won't be looked into?

**Comment by bushrang3r** [comment]
Oh wow. There's a V2? The Lawnchair website says that the app can be downloaded on F-Droid but V2 is not there. Only the latest 1.x version is on F-Droid. Any plans to put V2 on F-Droid?

**Comment by omgwtfbbqpls** [comment]
> @bushrang3r  Oh wow. There's a V2? The Lawnchair website says that the app can be downloaded on F-Droid but V2 is not there. Only the latest 1.x version is on F-Droid. Any plans to put V2 on F-Droid?

They've had some issues: https://github.com/LawnchairLauncher/Lawnchair/issues/1473

Regarding the backups, does anyone know what the easiest, most reliable, or manual workaround is (if any)? Right now backup/restore is pretty unreliable.
