### ISSUE TITLE
[FR]Dark search bar in Google feed

### ISSUE THREAD

**Issue by weirdeep** [Deletescape-Media/Lawnchair#1434]
## Description

Dark search bar is needed instead of existing in white search bar when Google feed theme is dark.

## Expected Behavior

Either there should be an option or Google search bar should itself be dark themed when Google is dark.

## Actual Behavior

As everything else is dark themed, white Google search bar doesn't match with overall dark themed experience.

## Steps to Reproduce

Give privilege to users as given in the case of dock as well as app drawer.

## Environment

* Device: OP6
* Android version: 9.0
* Launcher version: Latest
* Rom: OS 9.0.3

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
@iamdeep08 We don't have that control over the Google Now feed.

**Comment by divadsn** [comment]
Got confirmed, therefore I'm closing it.
