### ISSUE TITLE
Recent apps in the App drawer not working. 

### ISSUE THREAD

**Issue by miki1606** [Deletescape-Media/Lawnchair#1435]
When I open my apps drawer in the place where the app shortcuts should be, there are always 5 same apps: Photos, Maps, Gmail, Clock, Settings.

When I click on an app to open it ( multiple times) it should appear in the recent apps in the app drawer, but it doesn't.

Instead, the 5 apps I mentioned above stay there, and they don't change.

## Environment

* Device: Samsung Galaxy A5 2017
* Android version: 8.0 Oreo
* Launcher version: Lawnchair v2 2.0 - 825 - ci - alpha
* Rom: Normal

**Comment by divadsn** [comment]
@miki1606 Duplicate, please use the search
