### ISSUE TITLE
[Feature Request] Overview Selection Functionality

### ISSUE THREAD

**Issue by MrMagnifico** [Deletescape-Media/Lawnchair#1438]
## Description

When using the QuickSwitch Magisk module to assign Lawnchair as the recents provider, Android Pie's overview selection seems to cease functioning. This is not the case when the Pixel Launcher is set as the recents provider; the overview selection works with both the Pixel Launcher and Lawnchair, with the obvious caveat of Lawnchair not having the Pie-style recents.

## Expected Behavior

Overview selection should function alongside the Pie-style recents when Lawnchair is set as the recents provider.

## Actual Behavior

When Lawnchair is set as the recents provider using the Quickstep Magisk module, overview selection ceases to function.

## Steps to Reproduce

1.Install the Quickstep Magisk module
2.Set Lawnchair as the recents provider
3.Open the overview/multitasking screen
4.Attempt to make use of overview selection & note that it doesn't work

## Environment

* Device: Redmi Note 5 (whyred)
* Android version: 9.0 Pie
* Launcher version: 2.0-839-ci-alpha
* Rom: Resurrection Remix 7.0.0

**Comment by skittles9823** [comment]
@MrMagnifico This currently isn't possible. It is being looked into however but I wouldn't get your hopes up.
