### ISSUE TITLE
[Feature Request] option to remove search from app drawer

### ISSUE THREAD

**Issue by mister-monster** [Deletescape-Media/Lawnchair#1442]
The pixel launcher, google stock launcher and Trebuchet all have this option. Just an option to turn off the search area at the top of the app drawer.

**Comment by divadsn** [comment]
@mister-monster Duplicate, please use the search

**Comment by nyancrimew** [comment]
@mister-monster This is already possible

**Comment by mister-monster** [comment]
@deletescape no it is not. The search bar can be removed from the desktop, but the app search cannot be removed from the app drawer.

**Comment by divadsn** [comment]
@mister-monster

**Comment by nyancrimew** [comment]
@mister-monster App drawer > search bar > show search bar

**Comment by mister-monster** [comment]
@deletescape v1.2.0.1884 that option does not exist. The only search bar related option in "app drawer" is a toggle to use rounded corners.

**Comment by divadsn** [comment]
@mister-monster Yeah you haven't wrote that anywhere in your issue, as expected by the template we provide

**Comment by divadsn** [comment]
@mister-monster thar option exists in v2 alpha currently, version 1 is no longer being developed.

**Comment by mister-monster** [comment]
@divadsn noted, but I assumed that using the latest release before requesting features was to be expected.

**Comment by mister-monster** [comment]
@divadsn alright, I will wait for the stable release of v2. Thank you.

**Comment by divadsn** [comment]
@mister-monster we are not able to guess and we added a issue template with questions like what Lawnchair version for a reason, right? 😉

It's not meant to be offensive, but it would avoid misunderstandings between us 🙂

**Comment by mister-monster** [comment]
No I am not offended I completely understand.

**Comment by divadsn** [comment]
Great, I'm closing this issue as for now and we'll keep you updated on our social media when v2 will get a stable release (or on GitHub releases) :)
