### ISSUE TITLE
Google Discover Page Labels

### ISSUE THREAD

**Issue by OpenRift412** [Deletescape-Media/Lawnchair#1445]
Just a small nitpick, the text/icon in the headers above each article on the Discover page are slightly off-center. Here's some pictures of them compared to the stock Pixel Launcher.

![](https://i.imgur.com/RXVKcq8.png)![](https://i.imgur.com/fkKvS72.png)

**Comment by divadsn** [comment]
@OpenRift412 We have no control over how the feed is displayed as far as I know.

**Comment by OpenRift412** [comment]
@divadsn that's weird.

**Comment by suphon-t** [comment]
1. [They're aligned in the exact same way as they do on Pixel Launcher](https://i.imgur.com/31EwbxU.png)
2. The Google Feed is completely controlled by the Google App, which is something we can't change.
