### ISSUE TITLE
Feature suggestion: separate landscape layout

### ISSUE THREAD

**Issue by thw0rted** [Deletescape-Media/Lawnchair#1448]
## Description
I just got an LG G7, and I'm trying Lawnchair because the default launcher has some shortcomings, one of which is no landscape mode support.  I was heartened to see that Lawnchair does support landscape, but I'm not sure that the current implementation is suitable for very tall/skinny phones.

Counting the notch, my display is 19.5:9.  I set Lawnchair to use 7 rows, 5 columns, and it looks great in portrait.  (The LG launcher only supports 5x5, and this means enormous amounts of vertical whitespace.)  The problem is, when I rotate the phone, I now have to squeeze 7 rows into a relatively small vertical space, which means tiny icons.

## Expected Behavior
I have two ideas how to solve this.  One, when the device is rotated, swap the row/column settings and restart the launcher.  It's a blunt instrument and I expect behavior to be kind of wonky, but it should be easy to implement.  This would preserve the intent of the user, in that the resulting grid would be the same in both cases.  I'm not sure if it's possible but maybe you could transpose the individual icons along with it -- that is, if you have 4 rows / 2 columns like

````
A B
C D
E F
G H
````

then in landscape you'd use 2 rows / 4 columns and arrange the icons as

````
G E C A
H F D B
````

which is the first example rotated 90 degrees around "G".  Of course there are problems with this approach too, since widgets would have their proportions changed, but most widgets these days can survive some amount of resizing.

The second idea I had for a solution is to have two totally separate sets of home screens, one for each orientation, and swap between them on rotation.  This would let the user make their own decisions about how to use the space.  This would neatly sidestep the widget resizing problem above but mean more initial setup legwork for the user, and I suspect implementation would be less straightforward.

## Actual Behavior
In landscape, anything over 5 rows results in unusably small icons, but anything under 6-7 rows in portrait means enormous amounts of whitespace.

## Steps to Reproduce
Try out landscape mode with 7 or more rows.

* Device: LG G7 ThinQ
* Android version: 8.1
* Launcher version: latest
* Rom: stock

**Comment by AndyCGYan** [comment]
+1 on this; similarly the app drawer should have a separate grid plan too. And by grid plan, I mean being able to customize both rows and columns.
In general, refer to how Nova deals with grid and landscape.

**Comment by thw0rted** [comment]
I'm thinking of trying Nova just for this one thing. I have a dash mount for my phone that I use every day, and right now I have to choose between sideways icons or tiny icons. Both are kind of terrible.
