### ISSUE TITLE
Version 2 on Github?

### ISSUE THREAD

**Issue by dglttr** [Deletescape-Media/Lawnchair#1452]
## Description
I would expect to see all latest commits pertaining to version 2, but instead the development seems to happen on a private branch. Is V2 still going to be open source? And if so, when is it approximately going to be released?
Thanks for your product, and keep up the good work!

## Expected Behavior
The Github repo should be up-to-date with all the new code being written.

## Actual Behavior
Last Github commit is from a few months ago and development of Version 2 of Lawnchair is not openly accessible.

**Comment by nyancrimew** [comment]
@amkcpu V2 sources will be released again in the next few weeks.

**Comment by PaulWoitaschek** [comment]
I just wanted to say that the policy of keeping the source code and latest development secret is really turning me off as a potential contributor.

**Comment by suphon-t** [comment]
@PaulWoitaschek it was not available due to an unfinished 3rd party integration. But now that all's done, V2 sources are public now.
