### ISSUE TITLE
 OpenVPN can't create shortcuts for connections (linked to old #1393)

### ISSUE THREAD

**Issue by guillaumezin** [Deletescape-Media/Lawnchair#1463]
## Description
I installed OpenVPN from Appstore (version 3.0.5 1816). When creating a connection, you can add a shortcut on the launcher when editing profile with "set connect shortcut".

## Expected Behavior

"set connect shortcut" should add a shortcut to OpenVPN profile on desktop home screen

## Actual Behavior

"set connect shortcut" brings to desktop home screen but nothing happens or sometimes the shortcut appears for something like one second then disappears

## Steps to Reproduce

1. Install OpenVPN
2. Create a connection profile
3. When editing the profile, click on "set connect shortcut"

## Environment

* Device: Moto G5 reteu
* Android version: 8.1.0 OPPS28.85-13-6 security patch 2/1/2019
* Launcher version: 2.0-1940-ci-alpha
* Rom: stock rom 8.1.0

This bus is linked to old bug #1393 but still exists for version alpha 2

**Comment by divadsn** [comment]
@guillaumezin Which OpenVPN app, as there are two at least I know.

**Comment by guillaumezin** [comment]
https://play.google.com/store/apps/details?id=net.openvpn.openvpn

**Comment by ghost** [comment]
Check the "Add icon to Home screen" setting under Desktop. If that's turned off, no shortcuts can be made from apps (the same happened to me when trying to make file shortcuts in my file browser). I don't know if this is the intended behavior but that's been my observation.
![Screenshot_20190423-172745_Lawnchair](https://user-images.githubusercontent.com/307077/56617278-7a003800-65ed-11e9-8ee9-0fbcf568a77d.png)

**Comment by guillaumezin** [comment]
Thank you for the tip, but it's a wrong track, this option has always been enabled on my phone, otherwise it prevents newly installed applications to add an icon on home screen, and I want them to be able to do it.
