### ISSUE TITLE
[Feature Request] Raising Icon Size Limits

### ISSUE THREAD

**Issue by jackemerson** [Deletescape-Media/Lawnchair#1464]
## Description
My eyes are rather pathetic and I often struggle with smaller icon packs (even when they're normalised). I'd love to increase Icon sizes higher than the current 150% cap (probably 200% at most).

I'm unsure of the exact impacts this could have on layout consistency, though I assume there would be issues with edge-clipping for larger icons. Perhaps adding a "Raise scale limits" checkbox under advanced settings might allow users to access this functionality, while presenting a warning of possible visual quirks.

With that said, I appreciate this may fall outside the intended scope of this launcher. Currently, I'm increasing my icon sizes (beyond the limits) by editing a backup's preferences.xml and 'restoring' that backup. This is obviously a bit of a clunky workaround but hey, it works (so I'm not in dire need).

## Environment

* Device: Samsung Galaxy S9+
* Android version: 9.0
* Launcher version: 2.0-1940-ci-alpha
* Rom: Stock

Previous Ticket: #1461 (Made just before the 2.0 GitHub roll-out, nothing here.)

**Comment by AxiK101** [comment]
Set screen density to 320 or lower and you will get huge graphics

**Comment by jackemerson** [comment]
> Set screen density to 320 or lower and you will get huge graphics

Appreciate the suggestion, just has a lot of knock-on effects in places that I'm fine with currently.

**Comment by LuminarySage** [comment]
I think you can close this issue now (last one in the changelog)

![image](https://user-images.githubusercontent.com/24306400/60763053-3ccb1400-a03a-11e9-8594-8fa3df253401.png)
