### ISSUE TITLE
Force close in widgets view

### ISSUE THREAD

**Issue by neoscaler** [Deletescape-Media/Lawnchair#1466]
## Description
I run into repeatable force closes with Lawnchair v2.0-1947-ci-calpha while adding widgets to the homescreen. Using a Google Pixel 2 XL running latest Pie.  I can add widgets if I am fast enough though.

## Expected Behavior
App should not crash.

## Actual Behavior
App crashes.

## Steps to Reproduce

1. Longpress homescreen
2. Widgets 
3. Scroll through the list for about 30-60sec 

## Environment
* Device: Google Pixel 2 XL
* Android version: 9.0.0 (04/2019 update)
* Launcher version: v2.0-1947-ci-calpha
* ROM: Stock, no root

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
