### ISSUE TITLE
Support Edge as Search Provider

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Lawnchair#1467]
# Search Activity

`com.microsoft.bingsearchsdk.api.ui.activties.RubyBingSearchActivity`

It *should* also be possible to start this via the SEARCH action.

# Voice Search

There is another activity/action to start voice search/cortana, but I can't immediately recall what it was. Needs to be investigated.

**Comment by TheLBall** [comment]
# Current Progress

## General
I added the Edge search provider to the SearchProviderController and made the base class file, using the generic search icon for now.

The code will probably come later today.

## Text Search
It works, nothing hard once you have the activity name.

## Voice Search
I couldn't find the voice search activity through Activity Launcher. If someone finds it before I upload some code, they can add it. It's unsupported at the moment.

## Why did I format this?
I don't know, I just wanted to.

# Screenshots
![Screenshot_2019-04-08-20-43-16](https://user-images.githubusercontent.com/13513485/55827715-cf5e2480-5ad8-11e9-9eba-80ff74891f91.png)
![Screenshot_2019-04-08-20-43-21](https://user-images.githubusercontent.com/13513485/55827741-e735a880-5ad8-11e9-8a53-f0f1d3a88e8d.png)
![Screenshot_2019-04-08-20-43-24](https://user-images.githubusercontent.com/13513485/55827743-e735a880-5ad8-11e9-9885-cf2371ad3b95.png)

**Comment by nyancrimew** [comment]
Great! This is already really neat even without voice search, not sure if that actually still works anyways.

**Comment by divadsn** [comment]
Add also Edge icon as search provider icon 😎

**Comment by TheLBall** [comment]
#1490 is the pull request.

**Comment by TheLBall** [comment]
# Update
I added the Edge icon.

![Screenshot_2019-04-09-16-23-03](https://user-images.githubusercontent.com/13513485/55832860-7a281000-5ae4-11e9-90fc-228d423dc473.png)
