### ISSUE TITLE
[Enhancement] Unified search experience

### ISSUE THREAD

**Issue by baarkerlounger** [Deletescape-Media/Lawnchair#1469]
## Description
Currently the behaviour of the search bar/pill is dependent on the selected search provider. For example selecting google brings up a typable overlay with search suggestions and only launches the google app once I typed something and clicked search.

With Firefox selected as search provider it, clicking the search bar/pill opens the browser on a search tab straight.

## Expected Behavior
It would make for a more consistent experience if the search bar worked the same way no matter which provider was selected. Ideally that would be close to the google experience with an overlay on the lawnchair desktop itself providing suggestions (provided by the selected search provider) and only launches the browser/app when a search is made. That way search app and browser app could be chosen independently.

- It may not be possible for providers other than google to get this level of integration?

**Comment by divadsn** [comment]
@baarkerlounger Afaik it depends on the app if it has a overlay available, like Sesame does for example.

**Comment by baarkerlounger** [comment]
I assumed it would be something like that and this likely isn't easily possible in the immediate future. Would something like a proxy search app work?

**Comment by nyancrimew** [comment]
The entire idea of how the Search Providers are currently implemented is to provide the user with a search experience they are already familiar with. For some providers (like Seame) we're probably eventually going to add our own layout, for almost every other provider we can't actually get suggestions and the user experience would thus be significantly worse than it is right now.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
