### ISSUE TITLE
Widgets Need to be re-added to Homescreen After Reboot

### ISSUE THREAD

**Issue by BT-Dub** [Deletescape-Media/Lawnchair#1470]
## Description
Whenever I add a Google Keep widget to the homescreen, if I reboot, the widget will no longer be there and I'll have to add it again. This has always been an issue (in the versions I've used) although it only just occurred to me to post it here. I tried it with the Google Drive widget as well and had the same issue.

## Expected Behavior
Widget is retained after reboot.

## Actual Behavior
The widget is no longer there and has to be added again after each reboot.

## Steps to Reproduce

1. Place the widget on the homescreen
2. Reboot device
3. The widget will no longer be there

## Environment

* Device: Xiaomi Mi A1
* Android version: 9.0.0 (March 2019 Security Patch)
* Launcher version: v2.0-1947-ci-alpha
* Rom: Stock, no root

**Comment by divadsn** [comment]
@BT-Dub Is the app installed on the SD card?

**Comment by BT-Dub** [comment]
Yes, is that what's causing the issue?

**Comment by divadsn** [comment]
@BT-Dub Yes, widgets from apps that are stored on the SD card are not available at boot and therefore disappear.

**Comment by BT-Dub** [comment]
@divadsn Actually sorry, my bad, Lawnchair is on the SD card but both Keep and Drive are stored in internal storage.

**Comment by nyancrimew** [comment]
**Initial Research:**

Adding a check somewhere in the call stack to [this](https://github.com/LawnchairLauncher/Lawnchair/blob/d12b30d5333c03969ad340eb9b4e1846c12a6a73/src/com/android/launcher3/LauncherProvider.java#L840) if isAppInstalledOnSD to not remove in that case, or simply defer the entire clean up until after external storage has been mounted

**Comment by divadsn** [comment]
@BT-Dub @deletescape that should not be possible tho.

**Comment by BT-Dub** [comment]
@divadsn @deletescape What should not be possible?

**Comment by divadsn** [comment]
@BT-Dub Moving a launcher to the SD card, as the launcher app should be available immediately at boot, otherwise it can cause unexpected behavior.

**Comment by divadsn** [comment]
Although this here is old, but SD cards are still behaving the same way in Android:
>I know users love their sdcards, but Android is crap at handling them. Apps on the sdcard have all sorts of limitations (such apps can't host widgets). But there are also limitations for the launcher interacting with them. At boot, the apps are invisible so they appear uninstalled and the launcher generally wants to remove shortcuts to uninstalled apps. But no apps on the sdcard. Not every device even allows apps on the sdcard, but there is no way to query this.

https://www.reddit.com/r/MotoG/comments/36rh24/nova_launcher_devs_thoughts_on_apps_on_sdcard/

**Comment by BT-Dub** [comment]
@divadsn So would having the launcher on the SD card mean that it would have to be selected as default launcher again after each reboot?

**Comment by divadsn** [comment]
@BT-Dub good question, but I think yes, as Android will also think that your default launcher app is uninstalled and will show you a prompt to choose another one or fallback to the stock launcher.

**Comment by divadsn** [comment]
Oh and also, Lawnchair doesn't take that much space, so you should be okay with keeping it installed on the internal storage :wink:

**Comment by BT-Dub** [comment]
@divadsn OK thanks, that would explain another issue I was going to bring up about the default launcher being reset on each reboot. I will try moving Lawnchair to internal storage to fix the widget issue. I have it defaulted so all new apps are installed to the SD card and didn't think about the fact it would mess some things up.

**Comment by BT-Dub** [comment]
@divadsn Moving Lawnchair to internal storage fixed the widget issue and the default launcher issue, although now when I first unlock my phone, Lawnchair will crash and then the dialogue will come up asking if I want to use it as the default launcher. Should I open this as a new issue?

**Comment by suphon-t** [comment]
@BT-Dub Yes. And please attach crash logs too.

**Comment by BT-Dub** [comment]
@paphonb OK will do.

**Comment by divadsn** [comment]
@BT-Dub Try clearing the app data and re-setup everything, some old references might be the issue. But send logs too ;)

**Comment by divadsn** [comment]
Closing the issue for now.
