### ISSUE TITLE
"Add automatically" doesn't work when using Sesame Integration

### ISSUE THREAD

**Issue by neoscaler** [Deletescape-Media/Lawnchair#1471]
## Description
Trying to create a shortcut to a person who shares his/her location with you in Google Maps does not work. But a shortcut with the route to your home place is created. Creation works in Pixel Launcher and Action Launcher.

## Expected Behavior
Shortcut to person's location with picture of contact should be created.

## Actual Behavior
Shortcut with the route to your first location (for me home) is created.

## Steps to Reproduce

1. Start Google Maps
2. Navigate to Menu ⇾ Location sharing ⇾ Any contact ⇾ Overflow menu ⇾ Create home screen shortcut

## Environment
* Device: Google Pixel 2 XL
* Android version: 9.0.0 (04/2019 update)
* Launcher version: v2.0-1947-ci-calpha
* ROM: Stock, no root

**Comment by nyancrimew** [comment]
@NeoScaler Are you using the Sesame Integration?

**Comment by neoscaler** [comment]
> @NeoScaler Are you using the Sesame Integration?

Yes, indeed.

**Comment by nyancrimew** [comment]
A current workaround for this issue is to manually drag the shortcut to the Homescreen instead of clicking "Add automatically"

**Comment by nyancrimew** [comment]
This should have been fixed for a while now
