### ISSUE TITLE
Lawnchair Crashes on Reboot

### ISSUE THREAD

**Issue by BT-Dub** [Deletescape-Media/Lawnchair#1474]
## Description

On first unlocking my phone after reboot, a crash dialogue will appear, before asking if I want to use Lawnchair as my default launcher.

## Expected Behavior

Lawnchair works as normal on startup.

## Actual Behavior

Lawnchair crashes on first phone unlock after reboot, followed by a dialogue asking if you want to use it as default launcher.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/48495724/55724386-37423b80-5a03-11e9-8ae1-a28e15846147.png)
![image](https://user-images.githubusercontent.com/48495724/55724548-8ee0a700-5a03-11e9-8bd1-d79e711bf525.png)

1. Reboot phone
2. Unlock for first time 
3. Lawnchair crash dialogue will appear
4. Then prompted to choose default launcher

## Environment

* Device: Xiaomi Mi A1
* Android version: 9.0.0 (March 2019 Security Patch)
* Launcher version: v2.0-1947-ci-alpha
* Rom: Stock, no root

## Logcat

 

```
I couldn't get hold of any crash logs and I don't know how I would get them using the Scoop app because Lawnchair only crashes on reboot, so the Scoop app wouldn't be running yet?
```

**Comment by nyancrimew** [comment]
If you are near a PC with ADB installed please try to run `adb logcat > crashlog.txt` right after starting and after Lawnchair crashed. Otherwise we'll try to find someone who can reproduce this issue as well ;)

**Comment by BT-Dub** [comment]
@deletescape I don't have ADB installed but I could probably get it and run that, although it might be a while before I can do it, sorry.

**Comment by BT-Dub** [comment]
@deletescape Sorry for taking so long to reply, but I think I have found the part of the log where the crash dialogue is shown and maybe what causes it. Let me know if more info is needed and I'll try to get it.
[Lawnchair Crashlog.txt](https://github.com/LawnchairLauncher/Lawnchair/files/3058657/Lawnchair.Crashlog.txt)
