### ISSUE TITLE
Marshmallow folder style

### ISSUE THREAD

**Issue by GreenDragon527** [Deletescape-Media/Lawnchair#1475]
## Description
Is it possible or rather, is it feasible to have Marshmallow style folders in Lawnchair? 

## Expected Behavior
Folder icons in the Android Marshmallow style

**Comment by shubhchan** [comment]
@GreenDragon527 what benefits there will be if it becomes a thing? (I need a good answer)

**Comment by GreenDragon527** [comment]
Hi sorry for late reply, it will add range to customization of folder icons to include the Marshmallow aesthetic. If that isn't a good enough reason I understand.
