### ISSUE TITLE
Dock to Drawer animation : elements overlapping

### ISSUE THREAD

**Issue by Guema** [Deletescape-Media/Lawnchair#1477]
At the moment, swipping up opens the app drawer. But the animation looks wriedly cliped to the app bar

## Description

Wouldn't it be better or more beatiful if the appbar was emcompassed with the search bar inside the fading in white dock

## Expected Behavior

Actual Behavior :

Only search bar is displayed inside the swiping up dock.

## Steps to Reproduce

Just swipe up

## Environment

- Android 8.1
- Nexus5X
- LawnChair v2 last build at this day (10xx) (i install last alpha version everyday)

Here is a visual of the problem

![image](https://user-images.githubusercontent.com/8943532/55729778-14ba1d80-5a17-11e9-961f-33092a5a5d0b.png)

This is a screenshot while swiping up. see how elements overlap on each others on the dock.

**Comment by nyancrimew** [comment]
Can you please also attach a screenshot of your homescreen?

**Comment by Guema** [comment]
> Can you please also attach a screenshot of your homescreen?

Sure : 
![Screenshot_20190408-160452](https://user-images.githubusercontent.com/8943532/55730445-8050ba80-5a18-11e9-8020-769c2dd7a67a.png)

Bottom search bar is disabled.
