### ISSUE TITLE
[Feature Request] Add cover-like gestures for folders

### ISSUE THREAD

**Issue by divadsn** [Deletescape-Media/Lawnchair#1479]
Taken from the [comment on /r/Android by /u/ashenwreck](https://www.reddit.com/r/Android/comments/bajn46/lawnchair_launcher_v2_source_code_got_released_to/ekdkddp/):
> Edit: re-reading what the other person said, the cool thing about it is you have a folder, and you can set it open to the first item in the folder when you click on it, or open the folder when you swipe. The folder will have the appearance of being just the icon for a single app, as it changes to whatever is the first item in the folder.

**Comment by divadsn** [comment]
Nice @deletescape!

**Comment by ghost** [comment]
Was about to request the same thing. Had the full issue typed up, and was suggested this when entering a title.

**Comment by AlkaDragos** [comment]
Was thinking at this since i first tried v2. Not only that you can quickly open the first app (main one)  without any extra tap, but also this is very useful for customization. You won't have the folder icon or generic ones, but the one from main app, and a quick swipe will reveal the others.

**Comment by nezorflame** [comment]
+1 to that - that's probably the only feature which still holds me from abandoning Nova in favor of Lawnchair.

**Comment by shafschwd** [comment]
plz add this i miss this feature after switching from nova
### plz

**Comment by suphon-t** [comment]
Closing as folder covers are now added

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Was thinking at this since i first tried v2. Not only that you can quickly open the first app (main one) without any extra tap, but also this is very useful for customization. You won't have the folder icon or generic ones, but the one from main app, and a quick swipe will reveal the others.


Yes, the feature exist in Lawnchair Legacy version 9.1 alpha 3

This seems to be covered by the current reimplementation tracking issue #2659, since the old Cover Mode / folder swipe-up behavior is still missing from current Lawnchair releases.

- #2659
