### ISSUE TITLE
Bug: "add icon to home screen" doesn't always work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Deletescape-Media/Lawnchair#1480]
This happens on v1.2.0.1884 version code 1884 :
https://github.com/LawnchairLauncher/Lawnchair/issues/1390

It was closed, but it still exists.
Meaning, if you install an app by installing an APK (either via adb or via the device itself), there is no icon being auto created on the launcher.

**Comment by nyancrimew** [comment]
As #1462 states we are no longer accepting reports for v1.x.x builds. This issue does not seem to exist in our v2 builds so far.

**Comment by AndroidDeveloperLB** [comment]
@deletescape But that's what the Play Store has...
Where can I get newer version, then?

**Comment by nyancrimew** [comment]
@AndroidDeveloperLB v2 is currently in alpha any only available on our telegram channel or apkmirror.com. It'll be available as a beta on the play store very soon though

**Comment by AndroidDeveloperLB** [comment]
OK, installed from apk mirror :
https://www.apkmirror.com/apk/deletescape/lawnchair/lawnchair-2-0-1947-ci-alpha-release/lawnchair-2-2-0-1947-ci-alpha-android-apk-download/
meaning verson 2.0.1947-ci-alpha , version code 1947

And it works. Thank you!

**Comment by divadsn** [comment]
@AndroidDeveloperLB You're welcome.
