### ISSUE TITLE
App icon shortcuts won't show after we make few changes to lawn chair app settings. 

### ISSUE THREAD

**Issue by RameshGokamalla** [Deletescape-Media/Lawnchair#1481]
I have been facing this since I know lawnchair V2. App icon popup shortcuts won't show after we change some settings in lawnchair as we want. Reported this in Telegram help group many times surprisingly no one replied to this. Try looking into this issue. And fix if you can

**Comment by nyancrimew** [comment]
The issue template isn't there as a joke, please use it

**Comment by RameshGokamalla** [comment]
WT Funny? Am i looking like came here to play with that template?

**Comment by bohrabhijeet** [comment]
The issue template is there so you can use and make it easier for the developers to know more details about your device environment and resolve the issues you're facing. With this vague report, you are in no way helping us.
