### ISSUE TITLE
Icon reset option is still not included yet

### ISSUE THREAD

**Issue by RameshGokamalla** [Deletescape-Media/Lawnchair#1482]
Waiting this option for so long. Lawnchair does support icon packs but it doesn't support icon reset option this is interesting 😂. Every launcher have this feature except Lawnchair. Add it cause theming all app icons is not possible so we can edit not themed icons to something suitable for that app icon.

**Comment by nyancrimew** [comment]
The issue template isn't there as a joke, please use it
