### ISSUE TITLE
Bring back custom icons reset dialog from V1

### ISSUE THREAD

**Issue by divadsn** [Deletescape-Media/Lawnchair#1484]
Couldn't find which commit or PR it was, but it has to be done.

**Comment by divadsn** [comment]
Found the commit: https://github.com/LawnchairLauncher/Lawnchair-V1/commit/b530ad5afd35c55ed9f7b02b385800c6e5c58d66

**Comment by nyancrimew** [comment]
@divadsn custom icons work completely differently in v2 than in v1 and I'd prefer to switch the dialog for a clickable preference in the icon pack advanced group in v2.

**Comment by divadsn** [comment]
inb4 miss-clicked the preference and lost all custom icons
