### ISSUE TITLE
Swipe down to open app such as PowerShade makes Lawnchair crashing

### ISSUE THREAD

**Issue by AFKDev98** [Deletescape-Media/Lawnchair#1485]
**Description**
I was trying Lawnchair with PowerShade on my vivo nex s, but when I try to swipe down to pull notification (basic app activity) in powerShade, Lawnchair crashes.

**Expected Behavior**

PowerShade pull notification activity should start

**Actual Behavior**

Lawnchair crashes

**Steps to Reproduce**

Open gestures in Lawnchair
set PowerShade pull notification activity to start on swipe down
Swipe down on homescreen

**Device**

Device: Vivo Nex s
Android version: 8.1.0
Launcher version: v2.2.0-1957-ci-alpha
ROM: Stock, FuntouchOS, no root

**Comment by divadsn** [comment]
@Overcustom Please use the issue template.

**Comment by AFKDev98** [comment]
I'm opening a new one with updated description

**Comment by suphon-t** [comment]
Please also add logs.
