### ISSUE TITLE
Unnecessary synchronization of lazy calls

### ISSUE THREAD

**Issue by atzarul** [Deletescape-Media/Lawnchair#1487]
By default, the `by lazy {}` code is synchronized. There are several instances of lazy instantiation where this synchronization is not necessary and it adds unwanted overhead. For example, in BlurScrimView, SpringRecyclerView, TopRoundedCornerView which are view classes and should be touched only by the main thread.

**Comment by nyancrimew** [comment]
If I understand this correctly setting [LazyThreadSafetyMode](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy-thread-safety-mode/index.html) to `NONE` or `PUBLICATION` should remove this overhead, right?
