### ISSUE TITLE
Pixel icon support for 3rd party apps

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#149]
Support 3rd party apps that are eligible for Pixel icons, such as Facebook, Instagram, SoundCloud, Netflix, etc.

**Comment by edisso10018** [comment]
What's the difference to #148?

**Comment by nyancrimew** [comment]
When no icon pack is used and Pixel Icons are enabled circular icons are used from any app providing them in their manifest
