### ISSUE TITLE
Lawnchair gets stuck mid swipe to Google Now panel

### ISSUE THREAD

**Issue by AChep** [Deletescape-Media/Lawnchair#1491]
## Description
This rarely and randomly happens when you swipe to Google Now. After this happens you're no longer able to access Google Now panel.

For me it happened like 3-4 times.

![image](https://user-images.githubusercontent.com/990982/55856594-6a0b4180-5b73-11e9-995a-34eef3ef29f1.png)
![image](https://user-images.githubusercontent.com/990982/55856600-6ecff580-5b73-11e9-9e5f-88470f0b1b2d.png)

## Environment
* Device: OnePlus 6
* Android version: 9.0
* Launcher version: alpha 1947
* Rom: Pixel experience

**Comment by LuminarySage** [comment]
Lmao I got that bug too.

![ezgif com-optimize](https://user-images.githubusercontent.com/24306400/59321887-e02a4280-8ca1-11e9-9344-a75ed70a121a.gif)
