### ISSUE TITLE
Request: allow to import all possible settings from previous launcher

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Deletescape-Media/Lawnchair#1494]
On many launchers, they allow to somehow get all of the app shortcuts and widgets from a previous launcher.
This helps to switch between them.

Please add this feature.

**Comment by tnyeanderson** [comment]
I would have loved this feature migrating from Nova, but it looks like they obfuscate their backup files so they can't be used anywhere else :(

There will have to be mappings for each launcher to the relevant settings in Lawnchair. Perhaps a list of launchers to support will help:

* Evie
* Microsoft Launcher
* Action Launcher

Any others?

**Comment by JonnyTech** [comment]
https://en.wikipedia.org/wiki/List_of_Android_launchers

This one should be easy as there is full source code and comes with many custom rom's:
- [LineageOS Trebuchet](https://github.com/LineageOS/android_packages_apps_Trebuchet)

**Comment by AndroidDeveloperLB** [comment]
But I remember that some launchers somehow import the shortcuts from one another. Maybe even more settings...

**Comment by Ansem93** [comment]
Any hope for this functionality to be added?
I have hyperion Launcher and the only thing stopping me to switch to lawnchair v2 is that I have to set up everything again

**Comment by nate2014jatc** [comment]
I'm in a similar boat to @Ansem93, I'd love to make the switch, but I'd have to recreate a ton of folders and pages

**Comment by AndroidDeveloperLB** [comment]
I've noticed that if you switch from Nova Launcher to Action Launcher, somehow Action Launcher will import all of the shortcuts from Nova Launcher. Not sure about widgets, as I see only blank ones. But shortcuts were indeed imported, and even how many icons to show per line&column.


How come? Can you please check it out?

It didn't even require any permission to ask me. 

Maybe it uses a content provider?

**Comment by AndroidDeveloperLB** [comment]
Seems it is possible, at least for launchers that offer it:
https://android.googlesource.com/platform/packages/apps/Launcher2/+/master/AndroidManifest.xml


```
<!-- The settings provider contains Home's data, like the workspace favorites -->
--
  | <provider
  | android:name="com.android.launcher2.LauncherProvider"
  | android:authorities="com.android.launcher2.settings"
  | android:exported="true"
  | android:writePermission="com.android.launcher.permission.WRITE_SETTINGS"
  | android:readPermission="com.android.launcher.permission.READ_SETTINGS" />


```

**Comment by AndroidDeveloperLB** [comment]
> I would have loved this feature migrating from Nova, but it looks like they obfuscate their backup files so they can't be used anywhere else :(
> 
> There will have to be mappings for each launcher to the relevant settings in Lawnchair. Perhaps a list of launchers to support will help:
> 
> * Evie
> * Microsoft Launcher
> * Action Launcher
> 
> Any others?

You don't have to handle the backup file. Other launchers import from Nova just fine. I think it's the content provider I've mentioned. Please have a look at its manifest. Nova is probably based on Android's launcher even today, including the contentProvider.

**Comment by AndroidDeveloperLB** [comment]
Why close? Was it added?

**Comment by RikKoedoot** [comment]
We are cleaning up our issues, closed this because less launchers support it nowadays

**Comment by rubenheymans-amexio** [comment]
this is preventing me from switching nova -> lawnchair. I need my current shortcuts and widgets setup, it's a lot of work to do it again
