### ISSUE TITLE
Translation section graphic bug

### ISSUE THREAD

**Issue by MarcAnt01** [Deletescape-Media/Lawnchair#1497]
https://github.com/LawnchairLauncher/Lawnchair/issues/1441

**Comment by MarcAnt01** [comment]
Reason of the closure?

**Comment by divadsn** [comment]
@MarcAnt01 It's not a V2 related issues, as we don't have translators included yet on the about page.

**Comment by MarcAnt01** [comment]
@divadsn there were actually, they have just been removed in the latest build. Figured out by myself🙂

**Comment by MarcAnt01** [comment]
Anyway, it would always be a good practise to close issues explaining the reason😉
