### ISSUE TITLE
App shortcuts like 'My apps' stop to work

### ISSUE THREAD

**Issue by neoscaler** [Deletescape-Media/Lawnchair#1498]
## Description
If you create an app short, in my case the 'My apps' app shortcut of the Play store, it is initial working. But at some time (restart of launcher?) the shortcut stops working and does nothing if you click it. Happened now the sixth time, definitely  reproducible. 

## Expected Behavior
Shortcut should always work and start the specific app/intent.

## Actual Behavior
Nothing happens when clicking.

## Steps to Reproduce
1. Create 'My apps' shortcut of Play Store by longpressing the Play Store icon and dragging the 'My apps
 shortcut to the home screen.
2. Wait a few days and/or restart launcher
3. Click the shortcut

## Environment
* Device: Google Pixel 2 XL
* Android version: Android 9.0 (latest patches May)
* Launcher version: Lawnchauir v2 - 1978
* Rom: Stock

**Comment by divadsn** [comment]
@NeoScaler Part of #1495 I guess.

**Comment by suphon-t** [comment]
@davidsn Nah, those are Lawnchair actions.

**Comment by nyancrimew** [comment]
Is this still relevant?
