### ISSUE TITLE
Notification badge issue on v255

### ISSUE THREAD

**Issue by Ochach** [Deletescape-Media/Lawnchair#150]
im on galaxy s8 plus now. last official stock firmware. installed yesterdays update. you have done a great job! all bags i've noticed from previous versions disappeared. but one left. it is a notification badge for stock phone programm. Missed calls dont affect on appearing notification badge.

**Comment by Alyndri** [comment]
Would be good to be able to update from the last release instead of losing all settings and reinstalling every time

**Comment by paphonbth** [comment]
@Alyndri you don't have to uninstall and reinstall anymore since build 223

**Comment by Ochach** [comment]
Would like to add the suggestion for notification badges. On your launcher (lawnchair) notifications usually disappear when you swipe all the notifications from notification panel. I have some sutuations, when i have lots of notifications. On stock launcher i usually swipe them out and clean the noti panel. But notifications dedicated for special apps always leave on dedicated app until i open this app, but on lawnchair noti badges alwayse disappear after cleaning noti panel. i think this problem worth working on

**Comment by fonix232** [comment]
@Ochach Samsung uses their own framework for persistent notification badge display. We haven't reversed it yet, as we are aiming on fixing actual bugs and not making new enhancements and features. However this is already on our to-do list.
