### ISSUE TITLE
Mark strings as untranslatable

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Lawnchair#1500]
There are currently some strings not marked as untranslatable which also show up on crowdin.

Examples:
default_live_wallpaper
app_releases_url
app_donate_url

**Comment by Timbets** [comment]
"dock scale" translation seems to be missing from crowdin

**Comment by nyancrimew** [comment]
@Timbets Yikes, that's still hardcoded, fixing it ASAP as I'm currently working on strings anyways
