### ISSUE TITLE
Large clock cut in landscape

### ISSUE THREAD

**Issue by Timbets** [Deletescape-Media/Lawnchair#1503]
## Description
New large clock is cut and not fully visible when device is turned to landscape orientation. 

Also app names disappear, but that might be by design and not bug.

![Screenshot_20190417-210054_Lawnchair](https://user-images.githubusercontent.com/24968370/56311544-f2cb4400-6156-11e9-8433-45b23b0e8f3e.png)

* Device: Mipad 4
* Android version: 9
* Launcher version: 2.0-1991
* Rom: Carbon

Grid is untouched default (6x6)

**Comment by fbfrank** [comment]
Same in portrait, if display size is set to 'large', or higher. Clock scaling works, but the space used stays standard

https://photos.app.goo.gl/vDzqrabHqvShD4Ks6

**Comment by nyancrimew** [comment]
Closing this as resolved for now as the widget is now resizable. Adjustable font size to further combat this will be added eventually.
