### ISSUE TITLE
I can't put app into desktop

### ISSUE THREAD

**Issue by baotianyang** [Deletescape-Media/Lawnchair#1506]
## Expected Behavior

I can't put app into desktop# Actual Behavior
I can't delete desktop icon

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:xiaomi 9se
* Android version:9.0
* Launcher version: 2.0
* Rom:miui 10

## Logcat

 

```
your log here
```

**Comment by RikKoedoot** [comment]
try to restart lawnchair

**Comment by nyancrimew** [comment]
Closing this as no info has been provided. Please reopen this if it occurs again.
