### ISSUE TITLE
[Feature request] Ability to theme folders with an icon (see Nova as example)

### ISSUE THREAD

**Issue by Sixardyh** [Deletescape-Media/Lawnchair#1507]
See issue #1414

It could be great to have the ability to replace folder icons with the icons from our favourite icon packs :)

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version: latest
* Rom:

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
That’s already added.
