### ISSUE TITLE
Duplicate widget listings

### ISSUE THREAD

**Issue by aar0npjaeger** [Deletescape-Media/Lawnchair#151]
When I go to the list of widgets there are tons of duplicates. Gmail labels abound!

**Comment by aar0npjaeger** [comment]
I also have a ton of duplicates for the Contacts widgets.

**Comment by Dondrejohnson5** [comment]
What I said

**Comment by Dondrejohnson5** [comment]
#131

**Comment by suphon-t** [comment]
Fixed with 9c39106
