### ISSUE TITLE
[feature request] a new app opening animation.

### ISSUE THREAD

**Issue by criptixo** [Deletescape-Media/Lawnchair#1513]
this is my suggestion for a new animation, i hope the dev team consider developing it.

![](https://vimeo.com/331387519)

**Comment by criptixo** [comment]
https://vimeo.com/331387519

**Comment by ghost** [comment]
Action Launcher also has this, so I wouldn't mind seeing this in Lawnchair.

**Comment by lumiqcreative-zz** [comment]
As of now, we don’t plan on implementing custom app opening animations. The drawbacks outweigh the benefits — app opening speeds are reduced considerably when system transitions are overridden by the launcher.
