### ISSUE TITLE
Browser shortcuts do not work

### ISSUE THREAD

**Issue by Hemicrusher** [Deletescape-Media/Lawnchair#1517]
EDIT - 4/21/19

**_It is now fixed in alpha 2027. Didn't see it in the notes, but all is good now._**

Not sure if this is the same issue as "app shortcuts not working".

I use a few internet shortcuts on my home screen. I cannot create these properly in V2. When I add the shortcut from the browser to the desktop, doesn't matter what browser, it makes a link to "New Tab" and not the address that I choose. 

Samsung Galaxy S9 US (SM-G960U1 Unlocked. Android 9 Pie 4.9.112-15119402) Tried shortcuts with Samsung Internet Browser and Chrome. Samsung creates a "New Secret Tab" and Chrome creates a "New Tab". I am making a shortcut to a LAN address, 192.168.0.150. and works in all other launchers I have. On latest LC V2 Alpha....and has not worked in the last three I tried.

**Comment by nyancrimew** [comment]
@dwinnert Please use the issue template, OS version information etc is especially important with issues like this

**Comment by Hemicrusher** [comment]
> @dwinnert Please use the issue template, OS version information etc is especially important with issues like this

Updated

**Comment by Hemicrusher** [comment]
This is now fixed in alpha 2027. 

Thanks
