### ISSUE TITLE
Tapping on Weather Icon on Home screen when using google as weather provider is broken.

### ISSUE THREAD

**Issue by Dazog** [Deletescape-Media/Lawnchair#1518]
## Description

Tapping on Weather Icon on Home screen when using google as weather provider is broken.

Latest Google update has broken this.

Google app version 9.72.1.21.arm64

https://www.androidpolice.com/2019/04/20/google-improves-search-result-cards-material-refresh-additional-information-more-tabs/

## Expected Behavior

Open Google weather results.

## Actual Behavior

Nothing Happens.

## Steps to Reproduce

1. Add Date and Weather icon to homescreen
2. Use google as weather provider.
3. Click on weather icon on homescreen.
4.

## Environment

* Device: Samsung S8+
* Android version: 9.0
* Launcher version: Lawnchair 2 Build 1999
* Rom:

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
This is caused by the Google app and we can't fix it.
