### ISSUE TITLE
Window to icon animation problem

### ISSUE THREAD

**Issue by Timbets** [Deletescape-Media/Lawnchair#1521]
If I have web app or chrome shortcut in home screen, opening normal chrome and exiting moves the window to wrong icon (chrome shortcut) and not the app icon.

## Expected Behavior
Goes to correct icon

## Actual Behavior
It goes to wrong icon

https://dl2.pushbulletusercontent.com/yKEvdFBMXyUofTp0LahHY2TAGTPmda8V/ScreenRec_20190312_131146.mp4

1. Have web app or chrome shortcut on home screen
2. Open chrome
3. Close chrome
4. Transition to wrong icon

* Device: Mipad 4
* Android version: 9
* Launcher version: 2013
* Rom: carbon

**Comment by bohrabhijeet** [comment]
Thanks for the report, the developers will fix it in the future builds.
