### ISSUE TITLE
[Feature request] Make settings UI like fonts menu

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1523]
![screenshot_22 04 2019_16 42 24](https://user-images.githubusercontent.com/49860671/56492199-9c2a8500-651d-11e9-99dd-d0fdd2f4ef63.png)

## Description

Can you use new Oreo-like UI for all settings and add some icons to make it like in the screenshot?

**Comment by lumiqcreative-zz** [comment]
Thanks for the suggestion; this is already planned for the near future.
