### ISSUE TITLE
[Bug] Backup menu has different UI

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1524]
![image](https://user-images.githubusercontent.com/49860671/56493692-810e4400-6522-11e9-8697-2eb8eca0c138.png)

## Description

The interface in Backups menu is noticeably different: back button is gray and font is Roboto

## Steps to Reproduce

1. Open Lawnchair settings
2. Select Backups menu
3. Open backup/Create backup/Restore backup

**Comment by nyancrimew** [comment]
@fordownloads The thing that is actually wrong about the text fields there is that their underline still has the accent, they are disabled and should be fully grayed out.
