### ISSUE TITLE
getting a build error

### ISSUE THREAD

**Issue by sherlockbeard** [Deletescape-Media/Lawnchair#1527]
Android resource linking failed
/home/sid/personal/projectsworking/Lawnchair/res/xml/lawnchair_quickstep_preferences.xml:23: AAPT: error: resource integer/task_corner_radius (aka ch.deletescape.lawnchair.ci:integer/task_corner_radius) not found.

## Steps to Reproduce
cloned the repo and tried to build it.

**Comment by divadsn** [comment]
@sherlockbeard Read the readme again.

**Comment by sherlockbeard** [comment]
i don't get the whole search provider part @divadsn . first time seeing something like it.

**Comment by nyancrimew** [comment]
@sherlockbeard Just read the Building section for now, the part about search providers is simply a guide on how to add more search engines to lawnchair for people that want to have a simple entry point into the project

**Comment by divadsn** [comment]
>i don't get the whole search provider part @divadsn . first time seeing something like it.

I was referencing to that, as selecting the wrong variant causes an error like yours: https://github.com/LawnchairLauncher/Lawnchair#building

**Comment by sherlockbeard** [comment]
mine is showning no build variants . could it be because i am using 3.3.4 ? .

**Comment by sherlockbeard** [comment]
i will try it again after downloading canary version of Android Studio

**Comment by divadsn** [comment]
it's on the left side at the bottom of the project explorer, idk the name on the go

**Comment by sherlockbeard** [comment]
![Screenshot from 2019-04-23 02-25-59](https://user-images.githubusercontent.com/46790654/56531850-58159f80-6572-11e9-84da-5d5b9d5f9e6f.png)

**Comment by divadsn** [comment]
You haven't imported the project into Android Studio correctly, close the project and select "Import Gradle project" from the main screen, then select the cloned repo.

**Comment by sherlockbeard** [comment]
this time it directly told me to update it .
Message -: 
 This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.
 Thanks for the quick replies . will try it after the downloading the latest version :)
