### ISSUE TITLE
Launcher crashes on swipe up (Google Messages)

### ISSUE THREAD

**Issue by lachlan2357** [Deletescape-Media/Lawnchair#1528]
## Description
When I set the swipe up gesture for Google Messages to new conversation, the launcher crashes.

## Expected Behavior
It should launch Google Messages into the new conversation screen

## Actual Behaviour
The launcher crashes

## Steps to Reproduce
1. Add Google Messages to the home screen
2. Go into the swipe gesture option on that icon
3. Select Messages, new conversation. 
4. Try swipe up on the icon

## Environment

* Device: Samsung Galaxy J8
* Android version: Android Oreo 8.0.0
* Launcher version: 2.0 - 2027-ci-alpha
* Rom: Samsung Experience 9.0

**Comment by bohrabhijeet** [comment]
Please attach logcat of the crash.

**Comment by nyancrimew** [comment]
This has been fixed internally
