### ISSUE TITLE
Please reintroduce the Lock desktop option from Lawnchair 1

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#1531]
Please reintroduce the Lock desktop option in Settings > Desktop > Other

This option is essential for the "set up once, run forever" setup. Avoiding accidental moving or removing of app shortcuts & widgets, which can be quite disturbing to some people, especially the elderly. 

Verified that the feature is missing in build 2.0.2035

**Comment by bohrabhijeet** [comment]
The developers haven't forward-ported all the features from v1 yet. The same is on their to-do list and may be implemented soon.

**Comment by barkingbandicoot** [comment]
Is there any other method to lock the desktop?
What is the last version of Lawnchair to have it -do I need to go back to version 1 for this?
Please put on the priority list!
Thanks!

**Comment by suphon-t** [comment]
Closing as implemented.
