### ISSUE TITLE
Norwegian translation from crowdin not applied in v2 alpha

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#1532]
Norwegian translation from crowdin not applied in v2.0.2035, the app has been fully translated:
https://crowdin.com/project/lawnchairandroid/no#

Earlier issues reported about Norwegian language code, which are close:

https://github.com/LawnchairLauncher/Lawnchair/issues/1277
https://github.com/LawnchairLauncher/Lawnchair/issues/407

Norwegian locale on Android confusion exists also in other projects, for example:
https://github.com/AntennaPod/AntennaPod/issues/3059

**Comment by divadsn** [comment]
@eggsgent Before a translation gets applied, it has to be approved by a proofreader 🤷‍♂️

**Comment by eggsgent** [comment]
Hi, the Norwegian translation is up to date and ready to be included in the upcoming version 2 of Lawnchair: https://crowdin.com/project/lawnchairandroid/no#

Please include it in the alpha builds so the strings can be verified in the product before final release, thanks.

**Comment by eggsgent** [comment]
@deletescape Could you please check what happened at Crowdin? All 1390 words were translated by me by 24th November, but now Crowdin shows only 324 translated words!

**Comment by eggsgent** [comment]
Example of translated string "Use Dark Text":

The translated string, taken from activity changelog:
"string does not exist anymore"message: https://crowdin.com/translate/lawnchairandroid/20/en-no#1824

Same string, but untranslated in https://crowdin.com/translate/lawnchairandroid/all/en-no#2183
https://crowdin.com/translate/lawnchairandroid/20/en-no#1824

**Comment by eggsgent** [comment]
Another setback to the Norwegian translation reported in: https://github.com/LawnchairLauncher/Lawnchair/issues/1865

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
