### ISSUE TITLE
[feature request] adaptive icon shapes to at least Android 5.0

### ISSUE THREAD

**Issue by mohammadsyafeeq** [Deletescape-Media/Lawnchair#1533]
## Description
How about add the adaptive icon shapes? Like bringing the adaptive icon option to at least Android 5.0, which applies a round, squircle, teardrop, rounded square, or apply a custom one to all apps. Let's go kick Nova's ass.

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
