### ISSUE TITLE
Since version 2.0.-1991, it cannot be set as the default application

### ISSUE THREAD

**Issue by jan7272** [Deletescape-Media/Lawnchair#1534]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Huawei nova 3
* Android version:9.0.0
* Launcher version: 2.0.-1991
* Rom:4

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
@jan7272 Please add more information to describe the issue.

**Comment by jan7272** [comment]
2.0.1991,2.0.1995 could not be set as default launcher. Huawei Smart Recovery feature blocks settings as default launcher. 2.0.2035 is all o.k.

**Comment by suphon-t** [comment]
So it is fixed, right?
