### ISSUE TITLE
Google Weather Feed Doesn't Show when a Google Search Window is Open

### ISSUE THREAD

**Issue by CyberGW** [Deletescape-Media/Lawnchair#1535]
I've noticed that if I've used the Google app to make a search, and then I try to check the weather in-depth by taking the icon at the top of the launcher, I'm sent to the screen showing my search query and the weather isn't loaded. If I close the window with the query, and select the icon again, then it loads as expected.

**Comment by suphon-t** [comment]
That issue is caused by the Google App and not Lawnchair.
