### ISSUE TITLE
Feature suggestion: separate landscape layout

### ISSUE THREAD

**Issue by thw0rted** [Deletescape-Media/Lawnchair#1537]
## Preface
The original issue (#1448) was closed and I have been waiting for v2 to drop on the Play Store before asking again. It's still not there, but I'm *pretty* sure this wasn't implemented, so I'm opening a new issue in hopes that it continues to get attention.  If I'm wrong, and this was implemented as part of v2, I guess close this one too.  Original text reproduced below:

## Description
I just got an LG G7, and I'm trying Lawnchair because the default launcher has some shortcomings, one of which is no landscape mode support.  I was heartened to see that Lawnchair does support landscape, but I'm not sure that the current implementation is suitable for very tall/skinny phones.

Counting the notch, my display is 19.5:9.  I set Lawnchair to use 7 rows, 5 columns, and it looks great in portrait.  (The LG launcher only supports 5x5, and this means enormous amounts of vertical whitespace.)  The problem is, when I rotate the phone, I now have to squeeze 7 rows into a relatively small vertical space, which means tiny icons.

## Expected Behavior
I have two ideas how to solve this.  One, when the device is rotated, swap the row/column settings and restart the launcher.  It's a blunt instrument and I expect behavior to be kind of wonky, but it should be easy to implement.  This would preserve the intent of the user, in that the resulting grid would be the same in both cases.  I'm not sure if it's possible but maybe you could transpose the individual icons along with it -- that is, if you have 4 rows / 2 columns like

````
A B
C D
E F
G H
````

then in landscape you'd use 2 rows / 4 columns and arrange the icons as

````
G E C A
H F D B
````

which is the first example rotated 90 degrees around "G".  Of course there are problems with this approach too, since widgets would have their proportions changed, but most widgets these days can survive some amount of resizing.

The second idea I had for a solution is to have two totally separate sets of home screens, one for each orientation, and swap between them on rotation.  This would let the user make their own decisions about how to use the space.  This would neatly sidestep the widget resizing problem above but mean more initial setup legwork for the user, and I suspect implementation would be less straightforward.

## Actual Behavior
In landscape, anything over 5 rows results in unusably small icons, but anything under 6-7 rows in portrait means enormous amounts of whitespace.

## Steps to Reproduce
Try out landscape mode with 7 or more rows.

* Device: LG G7 ThinQ
* Android version: 8.1
* Launcher version: latest Play Store, I guess last June or so?
* Rom: stock

**Comment by nyancrimew** [comment]
I feel like the easiest way to actually make a somewhat usable solution for this would be to transpose the layout like this: 

Portrait: 

````
A B
C D
E F
G H
````

Landscape:

````
B D F H
A C E G
````

So essentially just keeping the setup the same (in relation to the screen) but rotating the icons and labels.

All of the solutions would however start getting problematic as soon as a setup contains widgets which aren't square.

**Comment by thw0rted** [comment]
Widgets can be resized, so your 2x4 widget would just become a 2x4 widget, using the transpose you suggested.  (I think our operations are the same, I was just rotating 90 degrees clockwise while you went counter-clockwise.)  Of course, the resized widget might not work the way you'd want it to, but that's why I'm suggesting an option to just have a completely separate home screen in landscape -- maybe if you haven't customized it at all, it uses the transpose of the portrait layout?

I guess that's two features, really.  One, support in-place transpose for landscape, as described above, maybe as an optional behavior in place of how it works today.  Two, support multiple sets of homescreens (akin to "virtual desktops" in Windows, "workspaces" in Linux, "desktop spaces" in Mac) with the ability to make a copy of an existing set, and choose a different default set for each orientation.  Then, you could just copy your portrait layout, set the copy as the default for landscape, and customize it as desired.

I think either would be valuable on its own, but the two suggestions would work well together.

**Comment by SoilMagun** [comment]
+1 Its not there yet... Applications menu layout 5x7 looks good in Portrait mode, but when i rotate my phone to landscape, its looks awful 5x7 (big gapes between apps).
