### ISSUE TITLE
Left Google page has very laggy/stuttery/unsmooth scrolling

### ISSUE THREAD

**Issue by SaadArdati** [Deletescape-Media/Lawnchair#1539]
If you go to the left Google page on your home screen, scrolling is unsmooth both vertically and horizontally. My phone is a Samsung S9.

The non-smooth scrolling happens inconsistently as far as I'm aware and I've been using the app for a while now. It's not rare, it's very common but it's inconsistent.

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
