### ISSUE TITLE
Launcher is very slow.

### ISSUE THREAD

**Issue by Treemindr** [Deletescape-Media/Lawnchair#154]
I've been trying the launcher out for a while and MAN! It is slow! The launcher isn't snappy at all and sometimes there's a 2 second delay when trying to do anything. Could you look into this?

**Comment by fonix232** [comment]
With this amount of details, no. Please detail which actions are slow (e.g. moving icons, opening app drawer, etc.), what phone you're using, which Android version, and which ROM (stock or something custom?).

**Comment by Treemindr** [comment]
I'm using a Moto G4 Plus with LineageOS 14.1 installed. When I move icons it's fine but once I place them there is a two second delay. App drawer opening is fine. Hold down to see shortcuts works but sometimes the animation skins frames or freezes for a second. Pressing the search widget has a second delay before opening.

**Comment by dictvm** [comment]
Can confirm on a Nexus 6P with O DP3 installed. I just uninstalled the previous version with the old certificate and reinstalled and it's been extremely slow so far:

* Drag & Drop stutters
* Dropping an app on the home screen freezes the launcher for about 2s
* While Drag'n'Drop is active, trying to drag apps into a folder is prone to losing the dragged app icon and having to start over again
* Clicking on the Google search bar does nothing but when you're opening another app and go back to the homescreen it'll sometimes open search with a very stuttery animation or it never appears (Assistant launches just fine)

However, thanks for putting up with all the work. It's highly appreciated. 👍

**Comment by digglesworth** [comment]
I can also confirm this.  I am using an S8 on T-Mobile.   I receive all the same issues that dictvm has noted.  I love the launcher.

**Comment by dictvm** [comment]
The search bar issue has improved without doing anything. I just tapped on it as always and it instantly opened, even the animation was smooth. 🤔

**Comment by suphon-t** [comment]
Fixed with 9c39106

**Comment by digglesworth** [comment]
I let it settle in a bit and the Search bar issue is also resolved for me.
