### ISSUE TITLE
Color issue with Notification Dots within folders.

### ISSUE THREAD

**Issue by Hemicrusher** [Deletescape-Media/Lawnchair#1540]
Device - Samsung Galaxy S9, Android Pie. Lawnchair V2 Alpha 2046

Notification Dots are black when showing notifications for apps in folders. This makes the "dot" nearly invisible. I tried switching from black theme etc. within Lawnchair and turning off "Night Mode" within Android. 

Dots look correct on the app within the folder and follow the apps color. 

![Screenshot_20190501-132849_Lawnchair](https://user-images.githubusercontent.com/34189525/57041306-c57e9b80-6c16-11e9-9b21-e08134b1f14a.jpg)

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
