### ISSUE TITLE
request weather feels like

### ISSUE THREAD

**Issue by drizzt09** [Deletescape-Media/Lawnchair#1542]
## Description
Request the weather widget in top right to include more optionally info. I am personally liking to see feels like (humidity and wind chill differences)

## Expected Behavior
When you set it to Google API and click on the widget i see temperature and below in smaller text, the feels like temp
add and extra line to the widget that shows the feels like temperature as well

## Actual Behavior
only shows actual temp

## Steps to Reproduce
I use google weather
Look at the weather widget temp which only has 1 temp. click on the widget which opens in Google Weather which shows actual temp and feels like temp.

## Environment

* Device: Xiaomi MiA1
Android version: 9.0.0
Launcher version: 2.02046 -->

**Comment by suphon-t** [comment]
If you set weather provider as Google, the data is pulled from their widget which doesn't show "Feels like" temperature, so that can't be implemented. Sorry.
