### ISSUE TITLE
"App search" search bar going off screen when accessed via guesture

### ISSUE THREAD

**Issue by Ajshawit** [Deletescape-Media/Lawnchair#1543]
## Expected Behavior
Search bar should be positioned underneath the status bar and be readable

## Actual Behavior
Search bar is above statusbar clipping off-screen. [Screenshot](https://imgur.com/a/muh213b)

## Steps to Reproduce

1. Set "Open app search" as any guesture
2. Perform guesture
3. Search bar appears at top of the screen slightly above status bar
4.

## Environment

* Device: Samsung Galaxy S10+ Exynos
* Android version: 9
* Launcher version: Version 2.0-2066-ci-alpha
* Rom: Stock Rom

## Logcat

 

```
your log here
```

**Comment by Ajshawit** [comment]
This issue only occurs if "Drawer Search Bar" is disabled. If enabled, the issue does not occur.

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
