### ISSUE TITLE
Extremely janky animation when switching between apps

### ISSUE THREAD

**Issue by LaeliocattleyaLustre** [Deletescape-Media/Lawnchair#1544]
## Description

When lawnchair is set as the default recents provider, switching between apps causes the animation to become so choppy 

## Expected Behavior

The animation should be smooth

## Actual Behavior

The animation is too janky

## Steps to Reproduce

1. Set lawnchair as the default recents provider
2. Open any app
3. Try switching to the last app by tapping twice on the recents button 
4. Notice the janky animation

Live example: https://drive.google.com/open?id=1gOP5nR6Uvf5EG0-vIlhdSyY62_RQuSZN

## Environment

* Device: Google Pixel
* Android version: 9.0.0
* Launcher version: 2.0-2048-ci-alpha
* Rom: Stock

**Comment by bohrabhijeet** [comment]
@PerpetualRift Please share a screen recording of the same.

**Comment by LaeliocattleyaLustre** [comment]
> @PerpetualRift Please share a screen recording of the same.

Done.

**Comment by suphon-t** [comment]
Does this happen when you invoke the recents menu with native buttons?

**Comment by LaeliocattleyaLustre** [comment]
> Does this happen when you invoke the recents menu with native buttons?

Yes same thing happens with native buttons

**Comment by LuminarySage** [comment]
I can attest to this. The only time it's smooth is when the pie pill navbar is used. Anything invoking the original three buttons (basically any third party navbar/nav gesture apps) will make the animations look stiff

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
