### ISSUE TITLE
how can drop icon like huawei?

### ISSUE THREAD

**Issue by yuxingfafu** [Deletescape-Media/Lawnchair#1545]
for example
one icon locate at workspce as (3,3) want to drop to (0,0),and then the icons betwon (0,0) and (3,3) auto move one step by step;
like a flow gif：
![84e4c82cc560ccb269ab31d0e6b245f9](https://user-images.githubusercontent.com/7764483/57175437-b6018b80-6e7e-11e9-8d0c-fb0999e2d4a6.gif)

**Comment by yuxingfafu** [comment]
is there someone do this effect? or can give some help thank you very much

**Comment by leanderli** [comment]
Is there have drawer on huawei？

**Comment by yuxingfafu** [comment]
you can try on huawei mobile phone, no drawer on huawei maimang

**Comment by Jnss98b** [comment]
You can already do that though...

![lawnchair icons](https://user-images.githubusercontent.com/24306400/59321155-eb2fa380-8c9e-11e9-8b50-6261bcacc54a.gif)

**Comment by yuxingfafu** [comment]
@Jnss98b not the effect,the gif you provided is  swap the two icon,not like huawei launcher，can change  icon locate between two icon.

**Comment by yuxingfafu** [comment]
@Jnss98b  look at  the gif picture i upload, do you have some solution? thank you
