### ISSUE TITLE
Generated adaptive icon backgrounds bug

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1546]
Sometimes the backgrounds of adaptive icons suddenly change to dark orange/brown instead of the "original" color. This happens unexpectedly and is not caused by an update of any sort.

**Comment by LuminarySage** [comment]
Link to a screen recording showing the bug

Note that Joey is the affected app while Snapdrop was shown for comparison
 https://imgur.com/a/P2gn960

**Comment by nyancrimew** [comment]
This should be fixed now since the rewrite of the Adaptive Icon Generator
