### ISSUE TITLE
Google Feed search bar not visible when there is a Doodle

### ISSUE THREAD

**Issue by bwalsh0** [Deletescape-Media/Lawnchair#1547]
## Description
With the Google Now/Feed integration on Lawnchair v2, past couple versions have consistently had the problem of the Google Search Bar missing only when there is a Google Doodle for that day. Reproducible 100% of the time, and it doesn't seem there's a way to turn the doodle off. No amount of restarting/settings will resolve the issue.

Unsure if this is an issue due to the Google App or Lawnchair's integration, although I have not noticed the issue before switching from Nova.

## Expected Behavior
Google Search Bar should show below the Google Doodle

## Actual Behavior
There is an empty space where the search bar should be

## Steps to Reproduce
(Screenshot at bottom of post due to large size)

1. Wait for a day with a Google Doodle (depends on locale, but there is one today May 6th, 2019 in US)
2. Swipe left from homescreen to Google Feed
3. Observe empty space below Google Doodle where the search bar should be

## Environment
* **Device:**
* **Android version:** 9.0.0
* **Launcher version:** v2 2.0-2048-ci-alpha
* **Rom:** HavocOS 2.4

![Screenshot_Lawnchair_20190506](https://user-images.githubusercontent.com/26880569/57215071-babe6080-6fa0-11e9-9200-303dfd7b2fdc.png)

**Comment by nyancrimew** [comment]
We have no control over how the Google Feed looks apart from the dark/light theme and tint.
