### ISSUE TITLE
App constantly crashes

### ISSUE THREAD

**Issue by ja-som** [Deletescape-Media/Lawnchair#1548]
## Description

I'm not sure what build number it was, but after I updated app just crashes over and over.

## Expected Behavior

Not to crash :)

## Actual Behavior

It crashes after a second.

## Steps to Reproduce

![Screenshot_2019-05-07-00-32-45](https://user-images.githubusercontent.com/5942380/57259597-51058b80-7060-11e9-99d8-1bcd67328a94.jpeg)

1. update
2. press open

## Environment

* Device: Lenovo Tab 4 8 Plus
* Android version: 8.1.0
* Launcher version: 2.0-2053
* Rom: stock 

## Logcat

 

[Lawnchair bug report May 7, 2019 00:32:11.txt](https://github.com/LawnchairLauncher/Lawnchair/files/3150067/Lawnchair.bug.report.May.7.2019.00.32.11.txt)

**Comment by ja-som** [comment]
So, it crashes since build 2027, I think, because I have 2013 on my second device, where I didn't update.

**Comment by Timbets** [comment]
Latest version 2062 started crashing immediately for me, it can't even start.
2057 had no problems (other than bugs I have already filed)
Mipad 4
Android 9
Carbon rom
[logs-2019-05-09-14-11-55.zip](https://github.com/LawnchairLauncher/Lawnchair/files/3161786/logs-2019-05-09-14-11-55.zip)

**Comment by DanGLVK** [comment]
The crash in build 2062 is known and it should be fixed today

**Comment by ja-som** [comment]
On my device it was crashing also with the latest build, but I deleted data for Lawnchair and set everything again and it works fine.

EDIT: it was probably something with my setup, so if someone can give me a hint what might cause that error so I can avoid it in future.

**Comment by suphon-t** [comment]
@ja-som We can't give a hint of anything unless you provide logs.

**Comment by ja-som** [comment]
@paphonb I thought that report file in my first post is enough, if not, then sorry, my bad.

**Comment by suphon-t** [comment]
Oh sorry. That was my fault. Didn't see that.

**Comment by ja-som** [comment]
No problem.

**Comment by nyancrimew** [comment]
Is this still occuring in newer Versions? Please close if this has been fixed

**Comment by ja-som** [comment]
After I reset it, it is OK.
Sorry. Closed.

And thank you for this great launcher.
