### ISSUE TITLE
Allow custom colors for folders and notification dots

### ISSUE THREAD

**Issue by lameventanas** [Deletescape-Media/Lawnchair#1549]
## Description

It would be great if we could customize the background color of folders (and their icons), and notification dots.

## Expected Behavior

This doesn't have to be too complicated, it could be the same color for all folders and all dots.  

## Actual Behavior

Currently all folders have a black background.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by LuminarySage** [comment]
Your "actual behavior" section is not entirely correct. Folder background actually follows the launcher's theme.

**Comment by lameventanas** [comment]
Oh I see.  Anyway, my idea is to have folders with customizable background and icon colors.

Something like Samsung's Touchwiz launcher.

**Comment by PoorPocketsMcNewHold** [comment]
Looking forward for some notification dots color customization. Making it as a pretty satured or contrary color compared to the one from the icon make it a lot easier to be noticed.

**Comment by ohcello** [comment]
The notification dots appear to take on the same color as the icon, which makes them blend in.  I'd love to be able to make them bright red for example so they stand out.... thanks.

**Comment by tueksta** [comment]
+1 - they need to stand out.

**Comment by yasanglass** [comment]
The notification dot color feature is implemented and released. The folder feature is requested on many other issues.
