### ISSUE TITLE
Allow hiding of navigation bar in desktop

### ISSUE THREAD

**Issue by Shadowspear123** [Deletescape-Media/Lawnchair#1552]
Allowing an option to hide the nav bar in the desktop will allow for a cleaner look.

Some other feature requests:
Animated clock icon like in Lawnchair 1
An activity shortcuts widget

**Comment by DanGLVK** [comment]
Lawnchair V2 already supports animated clocks you just need the right app or the right icon pack that supports it

**Comment by Shadowspear123** [comment]
There was an toggle in Lawnchair 1 that allowed clock apps that weren't stock or the google app to be animated. I don't see it in V2

Also, now that you mentioned icon packs, having the ability to change the icon of a single app individually would be useful

**Comment by DanGLVK** [comment]
You can change icons individually,just hold on the icon and tap the pencil or customize option

**Comment by DanGLVK** [comment]
Also I'm not sure how lawnchair V1 animated clocks that didn't support it,I believe it must replace it's icon for one that supports it (which again you can do by editing the clock icon and using one that supports it from an icon pack )

**Comment by Shadowspear123** [comment]
That's funny, when I tab customize, I only get an option to hide the app or move it to a tab, no option to change icon.

**Comment by Shadowspear123** [comment]
tap*

**Comment by nyancrimew** [comment]
Tap on the app icon on the edit screen to change the icon.

**Comment by Shadowspear123** [comment]
Ohhh thank you very much!

**Comment by Shadowspear123** [comment]
Is there still no way to hide the navbar on the desktop?

**Comment by skittles9823** [comment]
@Shadowspear123 You need to either use QuickSwitch or the Fullscreen Gestures (Q) magisk module to do that.

**Comment by Shadowspear123** [comment]
So if i'm not rooted i'm out of luck?

**Comment by skittles9823** [comment]
@Shadowspear123 pretty much yea.
