### ISSUE TITLE
Search results are invisible

### ISSUE THREAD

**Issue by milosmns** [Deletescape-Media/Lawnchair#1554]
## Description

Hi, this started happening a couple of days ago.
Search results from Google's widget are now invisible. 
S10+, latest app and OS updates etc.

https://imgur.com/a/sDZdZDB

# Expected Behavior

It should show visible results, as before.

## Steps to Reproduce

1. Open Lawnchair v2 (pick latest apk)
2. Tap Google search widget
3. Type any content (or just wait for trending)
4. Observe invisible content 
https://imgur.com/a/sDZdZDB

## Logcat

It's UI, logcat won't be of much help. But I'll get it if it's not repro for you.

**Comment by nyancrimew** [comment]
We unfortunately don't have any control over the look of the Google search UI, the UI is entirely provided by Google and any bugs with it are usually caused by Google

**Comment by milosmns** [comment]
It's working on my Pixel though. I was thinking that you might have some
graphical underlay sheet, or maybe theming that you did internally that
might be causing this... any ideas on what I can do to fix it?

**Comment by agoNITE** [comment]
I'm having issues with this as well. The background isn't transparent, but the text is almost unreadable (light grey on a white background). 

Reminds me a lot of the ugly context menu in Windows 10.

**Comment by milosmns** [comment]
@agoNITE Have the same. 

Since I use this launcher only because it has Google support, this is a major pain point. I noticed that the text color changes with my (Samsung) system theme, so I'm expecting that the launcher could also affect Google's theme somehow. It's really making it very annoying.
