### ISSUE TITLE
Icon picker lag

### ISSUE THREAD

**Issue by poperigby** [Deletescape-Media/Lawnchair#1557]
### What's happening
When searching for an icon, the first time I type something into the searchbar, it takes around 4 seconds to load, compared to it being instant the rest of the times I search. 

### What should happen
It should be insant, like the rest of the searches.

### Steps to reproduce
1. Long press an icon
2. Select customize
3. Select an icon pack
4. Search for something
5. Wait

**Comment by nyancrimew** [comment]
@PopeRigby Which icon pack are you testing this with?

**Comment by poperigby** [comment]
[O8](https://play.google.com/store/apps/details?id=com.eytus.android_o_pack)

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
