### ISSUE TITLE
Apps in work profile assigned to custom app drawer tabs gets removed on reboot 

### ISSUE THREAD

**Issue by tarinnik** [Deletescape-Media/Lawnchair#1558]
## Description

Some apps in my work profile are assigned to other tabs in the app drawer, but when I reboot, the apps are removed from the tab I assigned them to and put back in the work profile tab.

## Expected Behavior

Apps in the work profile should stay in the tab I assigned them to.

## Actual Behavior

The apps are put back in the work profile tab upon reboot.

## Steps to Reproduce

1. Assign a work profile app to a custom tab
2. Reboot the device
3. The app should be back in the work profile tab

## Environment

* Device: OnePlus 5
* Android version: 9.0.0
* Launcher version: 2.0-2066-ci-alpha
* Rom: OxygenOS 9.0.5

## Logcat

 

```
your log here
```

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
