### ISSUE TITLE
Big clock clicking not functioning properly

### ISSUE THREAD

**Issue by xpt1x** [Deletescape-Media/Lawnchair#1559]
## Description
Recently updated to v2.0-2066cialpha
After seeing new update about big clock
But now when clicking it ..
Doesn't open default clock app but says ' App isn't installed'

## Expected Behavior
Should open the default clock app of phone

## Actual Behavior
In previous versions opens calendar app but now throws an error !

## Specs
Android: 8.0.0
Emui version: 8.0.0
Device Name: Honor 7x
Device Model: BND-AL10

**Comment by nyancrimew** [comment]
@xpt1x Can you please include your device and Android version.

A lot of default clock apps don't properly implement the intents 🙃. Once I have a few of them I'll work on a workaround.

**Comment by xpt1x** [comment]
Sorry for skipping that info ..
Updated now!

**Comment by ondrejtomecka** [comment]
Same issue here on the Galaxy S10e (S10/S10+).
Android 9
OneUI 1.1
Device Name - Galaxy S10e
Device Model - SM-G9700
Thanks 😊

**Comment by xpt1x** [comment]
@deletescape why not setting the click activity to alarm activity for android to launch default clock of user's phone ?

**Comment by LuminarySage** [comment]
Same for the stock clock app on OnePlus phones

**Comment by DAMaas** [comment]
Can confirm this still exists on my OnePlus 7 Pro. Is there anything I can do to help?

**Comment by manwald** [comment]
Same here on my OP7 - any advices?

Edit: figured out that it works when installing the Google Clock.

**Comment by leebickmtu** [comment]
Default Samsung clock app on Galaxy S8 does not recognize to open either.

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
