### ISSUE TITLE
During swipe up drawer animation, a white shade appears regardless of the theme used

### ISSUE THREAD

**Issue by mah-qurashy** [Deletescape-Media/Lawnchair#1560]
## Description
when swiping up to app drawer, the desktop fades away while getting covered by a white/light grey shadow.

## Expected Behavior
it would be much nicer if that shadow color follows the used theme, so it would be black if using the black theme .. etc.

## Actual Behavior
shadow color does not change with theme, it actually looks much worse using a black/dark wallpaper on the black/dark theme. when you swipe up that light shadow appears briefly during the transition between a dark wallpaper and a dark app drawer. 

## Steps to Reproduce
![Screenshot_20190520-203204_Lawnchair](https://user-images.githubusercontent.com/20822445/58044946-69d26e80-7b41-11e9-8ef5-6cf3dddc144a.png)

## Environment

Device: Samsung Galaxy S7 Edge "hero2lte"
Android version: 8.0.0 
Launcher version: 2.0-2066-ci-alpha
Rom: Samsung Experience 9.0

**Comment by suphon-t** [comment]
When swiping up to open app drawer, the rest of the screen will be tinted with your wallpaper's primary color. This is intentional.

**Comment by mah-qurashy** [comment]
would make much more sense to be either tinted, shaded or toned depending on the theme used
