### ISSUE TITLE
Bottom Google Search List

### ISSUE THREAD

**Issue by januarydayfin** [Deletescape-Media/Lawnchair#1562]
When i clicking by bottom searching bar, text in strings are grey on white background(rly hard to read), but when i delete one of this strings, text transforming in black color.

Before 
https://pp.userapi.com/c852228/v852228090/1260b3/n6Gx-xLu_OE.jpg

After
https://pp.userapi.com/c848732/v848732090/19f7e4/E5Rj5rHd3r8.jpg

Android 9.0 EMUI 9.0 Honor 10 Lawnchair V2 2066-ci-alpha
Confirmed on Asus ZenFone Max Pro M1 ZB602KL 3/32, OnePlus 3T

**Comment by nyancrimew** [comment]
@krayman This is an issue on Googles side regarding night mode and not something we can fix.
