### ISSUE TITLE
New adaptive icon generator not working in recents

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1563]
## Description
New adaptive icon generator in build 2062+ not working properly with PWA (web shortcuts) and settings app in recents.

_Icons on home screen:_
![Screenshot_20190522-014507~2](https://user-images.githubusercontent.com/49860671/58119682-1d1c8f80-7c36-11e9-9e7f-e2cdefaa7581.png)

_Icons in recents:_
![Screenshot_20190522-014541~2](https://user-images.githubusercontent.com/49860671/58119701-2dcd0580-7c36-11e9-9ade-9d6f6f63150d.png)
![Screenshot_20190522-014557~2](https://user-images.githubusercontent.com/49860671/58119702-2e659c00-7c36-11e9-9aad-081686d356ff.png)
![Screenshot_20190522-014532~2](https://user-images.githubusercontent.com/49860671/58119703-2e659c00-7c36-11e9-8eb7-4f1db462a8d7.png)
![Screenshot_20190522-014547~2](https://user-images.githubusercontent.com/49860671/58119704-2efe3280-7c36-11e9-8bcc-8021b982fc0b.png)

## Expected Behavior

Icons in recents must be the same as on home screen.

## Actual Behavior

Icons in recents are different from icons in app drawer/homescreen.

## Steps to Reproduce

1. Open Chrome
2. Go to 9gag.com / vk.com / trashbox.ru
3. Go to 3 dot menu and click "Add to home screen". Chrome will install PWA.
![Screenshot_20190522-014616](https://user-images.githubusercontent.com/49860671/58118853-548a3c80-7c34-11e9-98e4-739be7a11462.png)
4. Open PWA and go to recents.
5. Compare icon in app drawer with icon in recents

## Environment

Device: x00t (Asus max pro m1)
Android: 9.0
Rom: Pixel Experience

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
