### ISSUE TITLE
Bug with popup menu in recents

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1564]
## Description

When you double tap on icon in recents, pop up menu will behave very strange.

## Video
https://drive.google.com/file/d/1tH0lbGmKA9HxfPgy4MvEiBf1Vq66QUDq/view?usp=drivesdk

**Comment by nyancrimew** [comment]
I'm able to reproduce.

Probably an upstream bug, let's try to fix and submit upstream.

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
