### ISSUE TITLE
Dock arrow is misplaced in landscape

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1567]
If the device is rotated to landscape mode before returning to the home screen or recent apps (basically in any app and even in Lawnchair settings works too), the dock arrow will be placed higher (half of the screen's width in my case) than where it's supposed to be at.

Video demonstrating the bug: https://imgur.com/a/NITIfjn

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
