### ISSUE TITLE
[Feature Request] Additional recents customization

### ISSUE THREAD

**Issue by bbq912** [Deletescape-Media/Lawnchair#1569]
Would be nice to have an option to change the recents search bar color and to remove the dock background.

**Comment by LuminarySage** [comment]
@bbq912  The search bar color in recents is tied to the dock search bar color so you can change its color already

**Comment by LuminarySage** [comment]
@deletescape May I suggest that the latter request should be an opacity slider instead of a simple toggle?

**Comment by bbq912** [comment]
@Jnss98b Yes, but I would like to change it separately, to only much the app drawer search bar and to use different color on the home screen. I second the opacity slider though

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
