### ISSUE TITLE
Fonts in shortcuts

### ISSUE THREAD

**Issue by lababiba** [Deletescape-Media/Lawnchair#157]
Fonts in shortcuts are very bold and blurred
![](http://i.imgur.com/MQ9TliV.jpg)
Also, original Pixel Launcher not displaying application logo in shortcut actions.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Treemindr** [comment]
Yeah, I agree. There shouldn't be a shadow under the app label and quickcut icon shouldn't have a shadow under it. 
![6ugfktv](https://user-images.githubusercontent.com/29968331/27965845-ee1fb388-62f1-11e7-9625-6f77eccfc47f.jpg)

**Comment by Dondrejohnson5** [comment]
Hey, Treemindr, what launcher is that?

**Comment by Treemindr** [comment]
That was the Pixel Launcher from Android O
