### ISSUE TITLE
The dock opacity slider is inaccessible when "Background" is toggled off

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1571]
The slider should instead be accessible as long as the dock is not set to hidden because even if "Background" is not toggled on, the dock " card" is still visible in the recent apps screen.

![Screenshot_20190527-021058](https://user-images.githubusercontent.com/24306400/58399242-8aa93100-8025-11e9-97ed-a96218b5001b.jpg)

**Comment by suphon-t** [comment]
That’s not the same thing and isn’t affected by dock transparency slider, so would be less to keep it enabled when dock background is disabled.

**Comment by LuminarySage** [comment]
@paphonb Ok, so you guys disassociated the slider with the recent apps dock in some update but what controls the recents dock opacity now then? At least give us another slider to control that.
