### ISSUE TITLE
Sources/tag for 1.2.1.2000

### ISSUE THREAD

**Issue by ArchangeGabriel** [Deletescape-Media/Lawnchair#1572]
I’ve seen a new release appeared on the PlayStore. I came here looking for a tag so the F-Droid build could be updated, but found none. So, where are the sources for the 1.2.1.2000 release?

**Comment by nyancrimew** [comment]
@ArchangeGabriel The sources are in our V1 archive [here](https://github.com/lawnchairlauncher/lawnchair-v1)

**Comment by ArchangeGabriel** [comment]
Thanks. I suppose the 1.2.1.2000 release corresponds to latest commit? If so, can a corresponding tag be added?

**Comment by nyancrimew** [comment]
@ArchangeGabriel Yeah sure, but I probably won't have time to do that until thursday (busy with work and finals)

**Comment by ArchangeGabriel** [comment]
Thanks, np. :)

**Comment by nyancrimew** [comment]
A tag has been created for todays 1.2.1.2001 update
