### ISSUE TITLE
[Feature request] Dark Sky weather provider.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1573]
I think it would be cool if you could select Dark Sky as a weather provider for the widget. Users could provide their own Dark Sky API Key similar to the OpenWeatherMap implementation.

**Comment by divadsn** [comment]
https://www.theverge.com/2020/3/31/21201666/apple-acquires-weather-app-dark-sky-shut-down-android-wear-os-ios
