### ISSUE TITLE
v2/v1 Swipe down option, does not pull down notifications, Samsung / Android 6

### ISSUE THREAD

**Issue by r3538987** [Deletescape-Media/Lawnchair#1575]
## Description
Two years later, I hoped that this will be fixed, or at least I will get some additional info about why this does not work on my device. This is one last thing I'm missing in this launcher. 
Every other option selected in menu Gestures/Behavior works fine, exception is one that should show notifications. 

## Expected Behavior
Notification shade should appear if mentioned option is enabled, and user swipes down on desktop screen.

## Actual Behavior
Nothing happens. 

## Steps to Reproduce
0. v2 Gestures - Swipe down - Open notifications
1. v1 Behavior - Pull down action - Show notifications
2. Go to main screen/desktop
3. Swipe down

## Environment
* Device: Samsung Galaxy A9 2016 (A9000) 
* Android version: 6.0.1
* v2 Launcher version: 2.0-2078-ci-alpha
* v1 Launcher version: 1.2.0.1884

**Comment by r3538987** [comment]
Posted issue, and found out similar reporter issue - https://github.com/LawnchairLauncher/Lawnchair/issues/378

So, any chance to introduce other method for "Samsungs"?

**Comment by suphon-t** [comment]
> This is related to the Android Version / manufacturer changes, we can not grant that this feature will work for anyone as we are using an unofficial and undocumented method for it

Quoted from the issue you linked.
