### ISSUE TITLE
Icons misalign with Widgets when App Names hidden

### ISSUE THREAD

**Issue by schokotets** [Deletescape-Media/Lawnchair#1576]
Icons misalign with widgets when "Hide App Names" is enabled.

## Expected Behavior
The icons would shift down to be centered in their grid fields.

## Actual Behavior
They stay in the upper part of their grid field.

## Screenshot
![Screenshot_20190601-070128_Lawnchair](https://user-images.githubusercontent.com/13350549/58749696-e9afe100-843d-11e9-86f1-0bacc5cbe610.jpg)

## Environment
* Device: Samsung Galaxy S7
* Android version: 8.0.0
* Launcher version: 2.0-2081-ci-alpha
* Rom: Samsung Experience 9.0

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
