### ISSUE TITLE
Toggleable Change Legacy app icons to force them into a shape

### ISSUE THREAD

**Issue by YosefuJoe1** [Deletescape-Media/Lawnchair#1578]
##Summary
I want to change some apps so they all have the same shape, regardless of it's Legacy-ness

## Description
I would love it if you would do this because if you change it to a specific shape, some don't resize to it, they're using transparent instead of putting it inside a shape

## Expected Behavior
In the Theme options  below the icon shape, have an option to toggle where it goes and reforms all app icons to have the same shape. 

## Actual Behavior
It's not in there

**Comment by nyancrimew** [comment]
@YosefuJoe1 Which Lawnchair version are you on?

**Comment by LuminarySage** [comment]
Isn't what you want simply the toggle that forces adaptive icons (It's called "Create adaptive icons" in Theme settings)?
![Screenshot_20190605-030715](https://user-images.githubusercontent.com/24306400/58937378-3e09d800-8740-11e9-9f5a-516b74de0e93.jpg)

**Comment by LuminarySage** [comment]
@deletescape I'm pretty sure they're one of those people who are still holding on to the Play Store release and/or don't know about the existence of V2 alpha. You should really add a notice in the issue template that V2 exists.
