### ISSUE TITLE
Labels in app drawer black instead of white

### ISSUE THREAD

**Issue by kobiandy** [Deletescape-Media/Lawnchair#158]
I did a clean flash of RR on my Z00A and made lawnchair a system app. Initially labels on icons in app drawer were white but after a reboot it's black now. It makes reading awfully difficult. I hope I'm not alone in this one

**Comment by xmiseggs** [comment]
![media-20170709](https://user-images.githubusercontent.com/29940632/27997887-9508827c-6501-11e7-8d07-ccaccbe66d9e.jpg)

**Comment by nyancrimew** [comment]
Fixed with 1c28b213e73edda1fa57e1f7a84247518a3a438c
