### ISSUE TITLE
Lawnchair will crash if theme is set to "Follow daylight" but system location is turned off

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1584]
OnePlus 6, OxygenOS 9.0.3, Lawnchair 2108

When "Follow daylight" is set after location permission is granted, Lawnchair would crash if location was turned off. This is probably a bug because showing a warning message would be way more appropriate than crashing the whole launcher.

Edit: actually, this will happen more than just the first time. I'm guessing Lawnchair needs to get location again after a certain amount of time, after an update or after a system restart.

**Comment by LuminarySage** [comment]
@paphonb Sorry, I thought since it's reproducible, I wouldn't need to provide any log. Here you go:

[Lawnchair_bug_report_Jun_11,_2019_22_59_48[1].txt](https://github.com/LawnchairLauncher/Lawnchair/files/3282232/Lawnchair_bug_report_Jun_11._2019_22_59_48.1.txt)

**Comment by LuminarySage** [comment]
Actually, this bug doesn't just happen on the first time "Follow daylight" is used because I got it again

Lawnchair_bug_report_Jun_16,_2019_23_30_16[1].txt](https://github.com/LawnchairLauncher/Lawnchair/files/3295189/Lawnchair_bug_report_Jun_16._2019_23_30_16.1.txt)

**Comment by LuminarySage** [comment]
@paphonb Also, can you relabel this issue because I have provided logs and this is one of the more annoying bugs that need to be addressed.

**Comment by nyancrimew** [comment]
This should be fixed now
