### ISSUE TITLE
When using the horizontal orientation on the home screen, the icons on the dock appear too close to the edge (v2)

### ISSUE THREAD

**Issue by aozora-tori** [Deletescape-Media/Lawnchair#1588]
A rather self-explanatory observation, really - other launchers don't place the dock icons too close towards the edge.

![Screenshot_20190616-093342_Lawnchair](https://user-images.githubusercontent.com/51875072/59561486-81731900-9053-11e9-98e8-1af993252e1b.jpg)

![Screenshot_20190616-162910_Lawnchair](https://user-images.githubusercontent.com/51875072/59561615-132f5600-9055-11e9-9417-f087eddb1537.jpg)

**Comment by LuminarySage** [comment]
You forgot to mention that you hid the navbar.

**Comment by aozora-tori** [comment]
> 
> 
> You forgot to mention that you hid the navbar.

oops
even with the navbar around, it grazes a bit too close for comfort though

also, I'm gonna post this pic for comparisons between other launchers
and if the question of icon scaling would be raised: 
left side -> 115%
right side -> 100%

![comparison](https://user-images.githubusercontent.com/51875072/59580076-4c71cf80-9102-11e9-9689-b9512d67e587.png)

**Comment by LuminarySage** [comment]
It's still a non-issue when the navbar is present nonetheless. No one is gonna stare at the screen like that. You have to look at the big picture:

![Screenshot_20190617-012055](https://user-images.githubusercontent.com/24306400/59580234-53ff8d00-909e-11e9-9a03-e177f76ff511.jpg)

**Comment by LuminarySage** [comment]
Legacy navbar in case you wanna be picky

![Screenshot_20190617-012402](https://user-images.githubusercontent.com/24306400/59580323-b5276080-909e-11e9-9fe8-a0142d376c8f.jpg)

**Comment by LuminarySage** [comment]
Anyways, I do agree they need to add more paddings to the dock

**Comment by aozora-tori** [comment]
i do understand where you're coming from -
although my oled burn-in scared bum is keeping me from using the navbar 

anywho, yeah - maybe a touch more padding would do
considering back in V1 the padding was adequate

![Screenshot_20190617-133722_Lawnchair](https://user-images.githubusercontent.com/51875072/59581169-a1174980-9106-11e9-9411-edbec4097930.jpg)

**Comment by Jnss98b** [comment]
> i do understand where you're coming from
The fact that the paddings are totally fine when the navbar is visible. I was just saying that you should mention in your description that the navbar is hidden, not to argue with you if more paddings should be added or not

> my oled burn-in scared bum is keeping me from using the navbar
The navbar has burn in protection. There won't be noticeable burn in anytime soon but to each their own I guess

**Comment by LuminarySage** [comment]
I'd like to add that this should really be fixed soon because fully gestural navigation in Android Q will position the "navbar" at the bottom of the screen all the time in relation to screen orientation so the dock will look weird in landscape in Q for everyone using gesture navigation.

**Comment by nyancrimew** [comment]
I think we really do need to test landscape more frequently
