### ISSUE TITLE
Google clock icon is always the default one in the recent apps screen regardless of what icon you set to it

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1589]
## Description
Like what the title said ~~but I think this issue is only present on devices with Google clock downloaded from the Play Store (basically the built-in clock app is something else)~~. Also, the bottom half of the icon you chose will be shown if you open the drop-down menu in recent apps (tapping on the icon).

## Expected Behavior
The Google clock icon in recent apps is whatever icon you chose

## Actual Behavior
The default Google clock icon is shown in recent apps

## Steps to Reproduce
1. ~~Install~~ Just have the Google clock app on the device, preinstalled or not ~~from Play Store~~
2. Change its icon to something else (I chose the clock icon from Amir's Google Icons pack)
3. Open the Google clock app
4. Go to recent apps and notice that the icon is not the one you set
4.5. Tap on the icon and its bottom half will be the bottom half of the icon you chose

## Environment
* Device: OP 6 (OOS 9.0.3) and Pixel 4 XL (QQ1B.200105.004 - January update)
* Launcher version: 2599

![Screenshot_20190616-221644 1](https://user-images.githubusercontent.com/24306400/59574716-535afc80-9086-11e9-967f-d2995380c049.jpg)![Screenshot_20190616-221856 1](https://user-images.githubusercontent.com/24306400/59574698-42aa8680-9086-11e9-8fdb-b451e8f11527.jpg)![Screenshot_20190615-004820 1](https://user-images.githubusercontent.com/24306400/59574756-74235200-9086-11e9-9e09-df43d5c1e7af.jpg)

**Comment by nyancrimew** [comment]
@paphonb recents icon loader acting up again :upside_down_face:

**Comment by suphon-t** [comment]
Looks fine here. Can't reproduce the issue. 

![](https://i.imgur.com/b2Lg2Nt.jpg)

**Comment by LuminarySage** [comment]
@paphonb  These are my active icon packs if it helps

![Screenshot_20190619-123327](https://user-images.githubusercontent.com/24306400/59783619-84a61900-928e-11e9-8822-d142ccf3506e.jpg)

**Comment by LuminarySage** [comment]
@paphonb Also isn't that Q? Maybe this issue is only on Pie and below?

**Comment by divadsn** [comment]
Works fine here, OnePlus 5T on Pie.

**Comment by LuminarySage** [comment]
How? I even reinstalled Lawnchair and it's still like that. I didn't even load my backup.

**Comment by LuminarySage** [comment]
I think the recents icon is stuck. I changed the clock icon to other icons but the recents icon stays the same.

![Screenshot_20190620-213724](https://user-images.githubusercontent.com/24306400/59891602-c4125980-93a3-11e9-8876-5773c9f0050e.jpg)![Screenshot_20190620-213732](https://user-images.githubusercontent.com/24306400/59891604-c7a5e080-93a3-11e9-872b-b9b9043dd7d9.jpg)

**Comment by LuminarySage** [comment]
So I just switched to a Pixel and even with Google clock preinstalled, its icon in recents is still bugged which means it wasn't just my OnePlus that was bugged.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/72933257-65dd9880-3d2f-11ea-8f40-e00006cb761f.gif)
