### ISSUE TITLE
Uninstall option

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1594]
##Description
Checked option to uninstall app from the popup but seems not available.

## Steps to Reproduce
![Screenshot_20190617-160540](https://user-images.githubusercontent.com/206181/59610723-36700900-911a-11e9-8125-63d3676b09aa.jpg)
![Screenshot_20190617-161004](https://user-images.githubusercontent.com/206181/59610816-7636f080-911a-11e9-9a5a-b292f3e21b1b.jpg)

## Environment
* Device: Oneplus 7 Pro
* Android version: 9
* Launcher version: 2144
* Rom: OxygenOS 9.5.7

**Comment by LuminarySage** [comment]
I'll add that it does show up in the popup menu in the app drawer

![Screenshot_20190618-225424](https://user-images.githubusercontent.com/24306400/59733502-17f23680-921c-11e9-8b5e-1a4e46d7ad79.jpg)

**Comment by suphon-t** [comment]
Working as expected. The uninstall option will only show in the app drawer.
