### ISSUE TITLE
[Feature Request] Folder Names

### ISSUE THREAD

**Issue by dontobi** [Deletescape-Media/Lawnchair#1597]
It would be good if the folder names were collapsible. that would have a clean look (along with the hidden app names).

**Comment by LuminarySage** [comment]
Wdym? Folder names are already hidden if you toggle on "Hide app names"

**Comment by dontobi** [comment]
@Jnss98b I can not confirm. For me, the folder names are displayed even though I have hidden the app name.

**Comment by Jnss98b** [comment]
@dontobi 
![Screenshot_20190626-214229](https://user-images.githubusercontent.com/24306400/60226968-78582800-985b-11e9-974f-aac88d7fdb7a.jpg)
![Screenshot_20190626-214249](https://user-images.githubusercontent.com/24306400/60226969-78582800-985b-11e9-91d6-b339a1b6c5b0.jpg)

**Comment by LuminarySage** [comment]
@dontobi 
![Screenshot_20190626-214407](https://user-images.githubusercontent.com/24306400/60227029-ac334d80-985b-11e9-9700-4aff86793643.jpg)
![Screenshot_20190626-214427](https://user-images.githubusercontent.com/24306400/60227030-ac334d80-985b-11e9-92b2-662449dd653b.jpg)
![Screenshot_20190626-214441](https://user-images.githubusercontent.com/24306400/60227028-ac334d80-985b-11e9-88ca-eb0bdf1461ad.jpg)

**Comment by LuminarySage** [comment]
@dontobi Question, are you using the play store release? Cause that thing is deprecated

**Comment by dontobi** [comment]
![](https://i.imgur.com/jEbxoX7.jpg)

**Comment by LuminarySage** [comment]
I'm pretty sure that's intended behavior

**Comment by cduran** [comment]
The behavior should be, labels for folders hidden too, when the option for "Hide icon labels on desktop" is on.

**Comment by LuminarySage** [comment]
Of course it's not hidden because that's the name shown inside the folder itself. If you don't want folder names then might as well not name them at all.

**Comment by cduran** [comment]
Just downloaded the app on Fdroid and tested the behavior and this is what happens. 
![Screenshot_20190629-141139_Lawnchair](https://user-images.githubusercontent.com/164527/60391185-b8aae680-9aa5-11e9-9a3b-93aa204655bf.png)
![Screenshot_20190629-135933_Lawnchair](https://user-images.githubusercontent.com/164527/60391196-f90a6480-9aa5-11e9-81f1-b964f8c8b7f5.png)
![Screenshot_20190629-135953_Lawnchair](https://user-images.githubusercontent.com/164527/60391201-01629f80-9aa6-11e9-8ab9-72c397b7fb33.png)

**Comment by cduran** [comment]
Just downloaded Version: 2.0-2212-ci-alpha (2212) from apkmirror and it has the same issue.
![Screenshot_20190629-211604_Lawnchair](https://user-images.githubusercontent.com/164527/60392129-7049f380-9aba-11e9-8e7e-889805b291b7.png)

![Screenshot_20190629-212216_Lawnchair](https://user-images.githubusercontent.com/164527/60392147-996a8400-9aba-11e9-97a0-97970c74c548.png)

**Comment by LuminarySage** [comment]
@cduran Look it's not an issue. It's behaving as intended. Just put a space in any folder's name if you don't want it to show inside the folder.
