### ISSUE TITLE
weather in home widget not showing and tabs customization menu broken

### ISSUE THREAD

**Issue by Shadowspear123** [Deletescape-Media/Lawnchair#1598]
The weather in the home desktop widget does not show. Going to the settings, I found the toggle for weather is gone. Previously the weather had been struck at one state before I restarted and found this problem.

When long clicking on a tab in app drawer, the customization menu briefly pops up but goes away before I can interact with it. 

Galaxy s8 on Android 8

**Comment by LuminarySage** [comment]
Have you tried backing up your settings and reinstalling Lawnchair? I can't replicate those behaviors on my S8.

**Comment by nyancrimew** [comment]
Which version of Lawnchair are you using?

**Comment by Shadowspear123** [comment]
I have done a clean install of lawnchair twice to no avail. I am using lawnchair version 2.0 2152-ci-alpha
