### ISSUE TITLE
[Feature Request] Allow assigning custom clock apps for "At glance" widget

### ISSUE THREAD

**Issue by nezorflame** [Deletescape-Media/Lawnchair#1599]
Since it's already possible to rebind weather and calendar, it's a bit puzzling that the "press on time to open the clock app" action can't be changed and requires only the Google Clock application.

**Comment by LuminarySage** [comment]
Uhh, Lawnchair opens your device's default clock app (the default clock app can be any clock app, not just the pre-installed clock app)

**Comment by LuminarySage** [comment]
Just change your default clock app and you will be fine

**Comment by nezorflame** [comment]
I didn't know that, and didn't find any info regarding it, since it refused to work with my default system clock app (in my case it's OxygenOS one).

Now that you've mentioned it, I've flashed a custom ROM and the behaviour here is different:
- the widget allows me to use the default system clock app;
- if I install Google Clock alongside the system one, widget now offers a choice between them.

So I guess it's an OOS bug/misconfiguration, and the widget doesn't see any clock apps for some reason.

**Comment by nezorflame** [comment]
In any case, thanks for the heads up @Jnss98b

**Comment by nyancrimew** [comment]
See #1559 regarding OnePlus clock and some other OEM clock apps not properly opening.

**Comment by LuminarySage** [comment]
@nezorflame OP clock not launching is because of the app itself, not OOS. If you install a third party clock app on OOS then the widget will ask you which clock to launch on the first time too.

**Comment by nezorflame** [comment]
@Jnss98b in my case it was different, otherwise I probably wouldn't create this issue:
- without any 3rd-party clock apps, widget just ignores the tap action with error
- if you install some clock app (like Google Clock), it just opens this app, no questions asked 

If I was to describe this behaviour, I'd say that the OP clock app is simply ignored and is not recognized as a valid clock application.

**Comment by DanGLVK** [comment]
Yeah,since only one clock app (that isn't the OP one) is installed android will launch that app by default no questions asked,try using two clock apps and it should ask you to choose the clock app you want to use,the OP clock doesn't work simply because OP forgot to add support for the intent (command) to invoke the clock app,a workaround would be to hardcode lawnchair to launch the OP clock

**Comment by nezorflame** [comment]
In any case, since @deletescape is already working on the same issue in #1559, we can just wait for the workaround.

**Comment by LuminarySage** [comment]
@DanGLES3 Lol isn't OP clock just a slightly modified version of the AOSP Clock app? How did they even "forget"  to implement alarm intent.

**Comment by DanGLVK** [comment]
Idk,ask OP that,they were the ones that messed up their clock app,if the OP clock app isn't opening it's because it's not responding to the alarm intent
