### ISSUE TITLE
Bug with pixel pill and file

### ISSUE THREAD

**Issue by vsoupaxe** [Deletescape-Media/Lawnchair#160]
![screenshot_20170707-223717_01](https://user-images.githubusercontent.com/8173285/27981995-2babba62-6365-11e7-9136-f2c5e3cc3fdc.png)

Transparent portion of the pixel pill

Also I am unable to uninstall Lawnchair on the Oneplus 3t Version Travis-198. Cannot update to the latest release by installing latest release on top of this version

**Comment by Treemindr** [comment]
Did you select a different launcher to your default before trying to uninstall?

**Comment by vsoupaxe** [comment]
Edit: I am able to uninstall by switching back to the default launcher. However after installing version 255 the issue with the transparent portion still exists

**Comment by Treemindr** [comment]
It's supposed to look like that.

**Comment by vsoupaxe** [comment]
Shouldn't it be a little bit more solid? It seems to be too transparent.

**Comment by Treemindr** [comment]
In the Android 8.0 update, they switched the design to has transparency. Not sure why, but they did. Since Lawnchair backported all the features from 8.0, the pill has the same design.
