### ISSUE TITLE
Can not use AccuWeather source.

### ISSUE THREAD

**Issue by caoli5288** [Deletescape-Media/Lawnchair#1600]
## Description

When I choose AccuWeather in settings It's flash back to disable(AccuWeather installed).

## Steps to Reproduce

1. Open settings.
2. Choose AccuWeather in weather source.
3.
4.

## Environment

* Device: Xiaomi MI 5
* Android version: 9
* Launcher version: 2.0-2152-ci-alpha
* Rom: PE

## Logcat

 

```
your log here
```

**Comment by nyancrimew** [comment]
This is a known issue and will be fixed whenever my schedule allows it

**Comment by caoli5288** [comment]
👍

**Comment by nyancrimew** [comment]
All AccuWeather issues should be fixed now
