### ISSUE TITLE
Gesture Handle to open the Power Menu

### ISSUE THREAD

**Issue by shafschwd** [Deletescape-Media/Lawnchair#1601]
can u guys add a option to bring up 
 power menu with gesture

**Comment by skittles9823** [comment]
@0ANIMEFREAK0 You can do that already via tasker, or any app that you can set a custom action to open the power menu with.

**Comment by shafschwd** [comment]
@skittles9823 
i haven't used tasker idk how to do that

besides i am looking for a free app that can do that since my power button is broken

**Comment by LuminarySage** [comment]
@0ANIMEFREAK0 That's why he said 

> or any app that you can set a custom action to open the power menu with.
