### ISSUE TITLE
Dock search in nightmare can't see searches as the colour is to dull

### ISSUE THREAD

**Issue by OwenM619** [Deletescape-Media/Lawnchair#1606]
## Description

![SmartSelect_20190624-223538_Lawnchair](https://user-images.githubusercontent.com/41874235/60053878-e8867280-96d0-11e9-9adb-114a3cb6b4ba.jpg)

## Expected Behavior
only happens in night mode it should be like in the app drawer, see screenshot

## Actual Behavior

Search box comes up but in white with dim text

## Steps to Reproduce

1.
2.
3.
4.

## Environment

 note 8 lawn chair launcher v2beta, ROM android pie 

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by OwenM619** [comment]
Night mode only this happens.
Clicking on the Google search in Dock.

**Comment by nyancrimew** [comment]
This is a known issue on Google's side, as far as we can tell right now there is no way to improve this from our side.
