### ISSUE TITLE
OxygenOS gestures broken when quickstep is used

### ISSUE THREAD

**Issue by lirannl** [Deletescape-Media/Lawnchair#1607]
OxygenOS's full screen gestures do not work properly when the recents provider is Lawnchair (using QuickSwitch).

## Description
When doing a short swipe up inside other apps, Lawnchair opens the recents menu instead of going home to itself. Also, landscape gestures are completely broken - the recents menu opens and closes immediately.

Also, as a temporary workaround, I tried changing the gestures inside of Lawnchair's Quickstep settings to open Lawnchair when swiping on the right side of the bottom edge, which crashed my entire phone when I tried closing fullscreen landscape apps.

## Expected Behavior
Exactly the same as the OnePlus Launcher when it comes to the gestures.

## Actual Behavior
The description

## Steps to Reproduce
1. Have OxygenOS installed
2. Use QuickSwitch to use Lawnchair as the recents provider + reboot
3. Switch to OnePlus' Gesture navigation

## Environment
* Device: OnePlus 7 Pro
* Android version: 9.0
* Launcher version: Alpha 2176
* Rom: OxygenOS

**Comment by DanGLVK** [comment]
That can't be fixed,the OnePlus gestures are tied to the OnePlus launcher being the recents provider,as soon as you change that they break as lawnchair has no support for OP gestures and will likely never support them as the OP launcher is highly obfuscated making porting the gestures extremely difficult if not impossible
