### ISSUE TITLE
Battery icon is missing in the at a glance widget for battery status OR Battery status is misaligned 

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1612]
I'm assuming there should be a battery icon at the beginning because the battery status is visibly misaligned. If not then the misalignment is the bug

![Screenshot_20190701-013506__01 1](https://user-images.githubusercontent.com/24306400/60412801-98138700-9ba0-11e9-86ec-4697152ff587.jpg)

**Comment by suphon-t** [comment]
Closing as resolved

**Comment by Jnss98b** [comment]
@Aww, I wish it was the battery icon that was missing

**Comment by LuminarySage** [comment]
@paphonb Awww... I was hoping it was the missing battery icon

**Comment by LuminarySage** [comment]
@paphonb Is there a chance you guys would consider the battery icon idea?

**Comment by suphon-t** [comment]
It looks a bit weird with the icon.

![Screenshot_Lawnchair_20190702-142612](https://user-images.githubusercontent.com/8080853/60492748-cd6dc100-9cd5-11e9-8092-528b819fe7fd.png)

**Comment by LuminarySage** [comment]
I think it looks better tbh

**Comment by LuminarySage** [comment]
Maybe you guys can put a switch next to the battery status event to toggle between icon and word
