### ISSUE TITLE
[BUG] Text size for app names in desktop folders is not changing

### ISSUE THREAD

**Issue by Pau1ey** [Deletescape-Media/Lawnchair#1619]
## Description

The text size for apps in desktop folders does not match the size of desktop icon labels or app labels in the app drawer so this seems to be a bug.

## Expected Behavior

Text size for app names in desktop folders should change when a % is selected under the Desktop settings menu.

## Actual Behavior

Text size is not changing.

## Steps to Reproduce

1. Open Lawnchair settings
2. Choose Desktop
3. Select a text size %
4. Restart Lawnchair

## Environment

* Device: Google Pixel 3 XL
* Android version: 10 Q Beta 4
* Launcher version:  2.0-2236-ci-alpha
* Rom: Stock

**Comment by Pau1ey** [comment]
Possibly related bug: Hiding app names on the desktop also hides them in desktop folders. It would be nice to see them in folders but hide names on the actual desktop homescreen.

**Comment by air-em-out** [comment]
I already thumbed up Pau1ey's comment, but I was going to make this same suggestion.

**Comment by Dean-NC** [comment]
Any word on the status of this?

**Comment by omgwtfbbqpls** [comment]
> Possibly related bug: Hiding app names on the desktop also hides them in desktop folders. It would be nice to see them in folders but hide names on the actual desktop homescreen.

A workaround is to enable app names on dekstop/folders, but simply rename the ones on the desktop with an empty spacebar.

**Comment by air-em-out** [comment]
> > Possibly related bug: Hiding app names on the desktop also hides them in desktop folders. It would be nice to see them in folders but hide names on the actual desktop homescreen.
> 
> A workaround is to enable app names on dekstop/folders, but simply rename the ones on the desktop with an empty spacebar.

This is actually a good workaround, and just did this.
