### ISSUE TITLE
[Feature request] A badge to highlight newly installed apps

### ISSUE THREAD

**Issue by enricocid** [Deletescape-Media/Lawnchair#1622]
## Description

A badge or smth else to highlight newly installed apps so user can find them more quickly.

**Comment by LuminarySage** [comment]
May I suggest highlighting the new apps' icons with lawnchair's current accent color? It would be very visible and still works for people who hide app names

**Comment by enricocid** [comment]
@Jnss98b yeah, absolutely. 
Since I'm kinda mad I would like to see the whole icon animated: some kind of blinking reveal animation, i.e. something different.
Anyway the badge will do the job and it is easier to implement, that's why I suggested it (there's already the notifications badges implementation one can profit). I don't know if accent is the best choice, think if you have the app's icon of the same color of the accent. Maybe I'd use the inverted color of the main icon color.😆
