### ISSUE TITLE
[FEATURE REQUEST] Add API for event sources in smartspace widget

### ISSUE THREAD

**Issue by oh1apps** [Deletescape-Media/Lawnchair#1627]
Would be great if 3rd party apps could register as event provider and display their data in smart space. What do you think?

**Comment by LuminarySage** [comment]
As great as this sound, let's be real here. Barely three to four apps will use the API. Instead of wasting time on the API, I suggest that Lawnchair devs take a more active approach by extracting data from notifications or widgets of certain apps and present them in a custom layout
