### ISSUE TITLE
Stretched app icons in search results from app drawer

### ISSUE THREAD

**Issue by ssdd28561** [Deletescape-Media/Lawnchair#1628]
## Description
 With Google as a search provider, when you open "all apps" drawer and try to search for something, corresponding app icons are stretched out vertically. App icons look normal, if you use search field from the main screen.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Pixel 3XL
* Android version: 10, dp4
* Launcher version: version 2.0-2238-ci-alpha
* Rom: stock, QPP4.190502.019

![Screenshot_20190704-185217](https://user-images.githubusercontent.com/8882800/60679216-89beb700-9e8f-11e9-9c1d-f02f839cda77.png)

**Comment by nyancrimew** [comment]
From the quick analysis I did of this at some point we should probably limit the number of apps we send to google for this UI and also send them measurements based on original stock settings. OR we figure out how to change the height and get it fixed that way.
