### ISSUE TITLE
Crashes With black screen. Build: 267

### ISSUE THREAD

**Issue by DanielJohnRoberts** [Deletescape-Media/Lawnchair#163]

**Comment by DanielJohnRoberts** [comment]
Crashes on devices running 6.0.1 and below. Results in a black screen. Tested on Moto G (Falcon) Apologies in advance for mess that is the log.

LOG

build.board: MSM8226
build.bootloader: 0x411A
build.brand: motorola
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: falcon
build.display: krexus_falcon-userdebug 6.0.1 MMB29M 18 test-keys
build.fingerprint: motorola/krexus_falcon/falcon:6.0.1/MMB29M/18:userdebug/test-keys
build.hardware: qcom
build.host: Legacy-Server-1
build.id: MMB29M
build.manufacturer: Motorola
build.model: Moto G
build.product: falcon
build.radio: unknown
build.serial: TA930089KF
build.tags: test-keys
build.time: 1472707213000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 18
version.release: 6.0.1
version.sdk_int: 23

07-08 21:58:27.086 D/audio_hw_primary(716): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
07-08 21:58:27.123 D/AudioFlinger(716): mixer(0xb41ef008) throttle end: th

**Comment by deletescape** [comment]
Known issue, thanks for the report though

**Comment by paphonbth** [comment]
Fixed with #164
