### ISSUE TITLE
Lawnchair crashes when user deletes app search provider

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1630]
## Steps to Reproduce

1. Install Sesame (or other search provider)
2. Enable Sesame integration & set sesame as search provider & restart lawnchair
3. Uninstall Sesame and click on Lawnchair search field
4. Lawnchair crashes
5. Go to settings and try enter to Search or Integration menu
6. Lawnchair crashes

## Expected Behavior

Lawnchair should reset search provider to built-in (like Google (web)) after user deletes app-provider (like sesame, google app)

## Environment

* Device: x00t
* Android version: Pie
* Launcher version: 2268
* Rom: Pixel Experience

**Comment by nyancrimew** [comment]
@paphonb how about approaching this more like smartspace providers and generally only working with class names only for defaulting. This may work without causing recursive issues as our older approach.

**Comment by suphon-t** [comment]
@deletescape Will take a look at this later this week
