### ISSUE TITLE
Adaptive icon shape applies wrong after restoring backup

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1631]
## Video

https://drive.google.com/file/d/1-5ioeMUxgB5rQTuIMRJCE5_A7EvvfApB/view

## Steps to Reproduce

1. Set icon shape to square
2. Create backup
3. Go to android settings & clear lawnchair data
4. Restore backup
5. Icons will be circle but when you hold icon shape will change to square

## Environment

* Device: x00t
* Android version: Pie
* Launcher version: 2268
* Rom: Pixel Experience

**Comment by nyancrimew** [comment]
This should have been fixed with alpha 2279
