### ISSUE TITLE
Toggle to enable At a glance widget is missing

### ISSUE THREAD

**Issue by fbfrank** [Deletescape-Media/Lawnchair#1638]
## Description
Toggle to enable At a glance widget is missing in settings/at a glance widget

## Expected Behavior
Toggle to enable the widget is there

## Actual Behavior
no toggle

## Steps to Reproduce
Screenshot: https://photos.app.goo.gl/7jwaRQHPMXaVWEkN9
same after restart (app and device) and clear cache of app

## Environment
Pixel 2
Android version: 9
Launcher version: 2.0-2279
Rom: Stock

**Comment by nyancrimew** [comment]
The at a glance widget is a regular widget now, you can drag it to the home screen from the widget drawer. On Nougat+ you can actually even drag it out from the Settings screen.
