### ISSUE TITLE
Unblurred line around dock

### ISSUE THREAD

**Issue by Virtheon** [Deletescape-Media/Lawnchair#1640]
## Description

To the left and bottom of the dock, there is a very thin line (perhaps 1-2 pixels wide), which is not blurred. This makes the dock look a little uncomfortable. The line also appears on the left edge of the drawer.

Here is a picture demonstrating the issue:

![image](https://user-images.githubusercontent.com/48177507/60865773-3db89d00-a216-11e9-9e96-8be7d7d3a2cc.png)

(Pay attention to the bottom and left edges, particularly the bottom where it's more visible)

## Expected Behavior

I expect the blur/background of the dock to extend to the edges of the device.

## Actual Behavior

Refer to description.

## Steps to Reproduce

I have not tested many combinations, but these are my settings:

1. Have 'Custom dock opacity' disabled.
2. Enable blur (10%), enable it on everything (including dock & drawer)
4. Set theme to dark, apply it to everything (including dock & drawer)

## Environment

* Device: Samsung Galaxy A8 2018
* Android version: 9
* Launcher version: 1.2.1.2001

**Comment by gre0j** [comment]
Here is another screenshot from me. I didn't notice this line in the last version. 
But i have to add…on my phone (Huawei P20pro) its only visible at the bottom
with a resolution of **1493x720**(HD+)…
![Screenshot_HD+](https://user-images.githubusercontent.com/23266409/61127010-4d521300-a4ae-11e9-94e1-d5810a1bbbbc.jpg)

with **2240x1080**(FHD+) its fine…
![Screenshot_FHD+](https://user-images.githubusercontent.com/23266409/61127038-62c73d00-a4ae-11e9-9047-5cb416c037fe.jpg)

**Comment by Virtheon** [comment]
Mentioning your resolution, good idea.

Mine is 1080x2220, by the way.
