### ISSUE TITLE
[Feature Request] Cover name equal to folder name

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1643]
## Description
Currently when converting a folder to a cover, the name of the cover becomes that of the first app in the cover. Although this might be something some users want, others such as myself would prefer to have the cover's name be the folder name.

## Expected Behavior
Once converting a folder to a cover, have an option to have the cover's name be that of the folder.

## Actual Behavior
Cover's name is equal to that of the first app in the cover.

## Steps to Reproduce
1. Add apps to folder
2. Give folder a name
3. Convert folder to cover
4. Cover displays first app in the cover's name

## Environment
* Device: Samsung Galaxy S9+
* Android version: 9.0.0
* Launcher version: 2.0-2291-ci-alpha
* Rom: OneUI 1.0

**Comment by suphon-t** [comment]
Another toggle would result in bloat, and you can rename the first app instead to change the folder label.

**Comment by ghost** [comment]
Then how about if the folder name is set, use the folder name, if not fallback to the app name? Right now if you open the cover you see the name of the folder, also if you open the cover/folder options.

If not, there isn't much point in displaying the folder name once converted to the cover.

**Comment by suphon-t** [comment]
Will consider that. Thanks for the feedback.

**Comment by Dukko** [comment]
I second @kerosyn suggestion of using the folder's name as the cover's name if the user provided a name for the folder. It's clean and it's a feature I personally miss from action launcher.
