### ISSUE TITLE
u

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1648]
b

**Comment by suphon-t** [comment]
I can’t see the issue.

**Comment by yoannjly** [comment]
For the music it is displayed well: https://image.noelshack.com/fichiers/2019/29/2/1563284444-screenshot-20190716-154001-01.jpg
but for notifications it is displayed oddly not? or it's done on purpose

**Comment by suphon-t** [comment]
It's working correctly. The notification from Snapchat is just formed that way.
