### ISSUE TITLE
App drawer positioned too high after closing an app

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1650]
![Screenshot_Lawnchair_20190714-163429](https://user-images.githubusercontent.com/32299885/61185129-cb9ce980-a655-11e9-9f8a-fa7dc666edd1.png)
Basically, this happend after i closed an app from the Recent apps tab.

**Comment by LuminarySage** [comment]
@TheJeak You should really include device info like model, OS version, etc. because this seems like a device-specific bug

**Comment by ghost** [comment]
I'm currently using a Redmi Note 5 Pro (whyred) running Havoc Os 2.7.

**Comment by ghost** [comment]
The same problem on OnePlus 3T with Havoc OS. Lawnchair installed as a system application from firmware and currently updated to the latest ver. 2.0-2319. and maybe once at fifty transitions to the launcher after the applications are closed, the lower dock bar jumps to the wrong place to the top (just like in the screenshot above), taping on an empty place in the launcher returns the dock bar to the right place
