### ISSUE TITLE
[Feature request] Make Lawnchair's custom At a glance widget available system-wide

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1651]
Currently, the At a glance widget (or Home widget) is only available exclusively to Lawnchair itself (The Actions shortcut isn't). It would be nice if it's available system-wide because there are apps like Popup widget, Widget drawer, Widget screensaver, etc. that make widgets useful beyond the home screen.

![Screenshot_20190713-193425__01](https://user-images.githubusercontent.com/24306400/61188651-79a59500-a650-11e9-8308-7ede23f511cc.jpg)

**Comment by suphon-t** [comment]
This will result in having to maintain two separated codes for the built-in version and an external version.

**Comment by LuminarySage** [comment]
Can't you just use the external version for Lawnchair? What are the downsides? Less integration or performance issues?

**Comment by suphon-t** [comment]
It it will involve using the Android widget manager and I want to avoid that as it brings more state handling to do. Not to mention that normal widgets use RemoteViews which we don’t have control over and doesn’t support animations.

**Comment by LuminarySage** [comment]
I guess maintaining two versions sounds better? Would you guys consider it though? It would be really nice for third-party apps to be able to access Lawnchair's home widget, especially after the recent inclusion of Events.

**Comment by suphon-t** [comment]
> Would you guys consider it though?

No.
