### ISSUE TITLE
[Feature request] Adding an opacity slider for each search bar

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1654]
I would like to make a simple request for an opacity slider each for the dock and the app drawer search bars like the one that already exists for the app drawer itself.

![Screenshot_20190715-225723_LI](https://user-images.githubusercontent.com/24306400/61264399-726aae00-a75a-11e9-905b-bf97378db507.jpg)![Screenshot_20190715-225712](https://user-images.githubusercontent.com/24306400/61264400-739bdb00-a75a-11e9-95f7-e5052c077e29.jpg)

**Comment by DanGLVK** [comment]
You can already adjust the dock search bar transparency,tap on color and adjust the A (Alpha transparency), currently you can't have transparency on the app drawer search bar due to clipping issues

**Comment by LuminarySage** [comment]
@DanGLES3 I know you can do that through color settings but that would mean sacrificing the Follow theme option unlike what's currently possible with the app drawer which can have both Follow theme enabled and adjustable transparency at the same time.

**Comment by DanGLVK** [comment]
The thing is even if that option was added you still wouldn't be able to make the app drawer search bar transparency,that's currently not added due to clipping issues

**Comment by DanGLVK** [comment]
So only the dock would have an opacity slider ATM

**Comment by LuminarySage** [comment]
I mean it would still be nice if only the dock search bar gets an opacity slider for now.

**Comment by LuminarySage** [comment]
The app drawer search bar opacity slider can be implemented later. I wouldn't mind.

**Comment by suphon-t** [comment]
Won't be added as there are different default opacity values in the "Follow theme" option.

**Comment by LuminarySage** [comment]
@paphonb Are you talking about a future release? Currently the Follow theme option has hardcoded values.

**Comment by suphon-t** [comment]
It’s been like this since the beginning of v2.

**Comment by LuminarySage** [comment]
So how come the app drawer can both be set to Follow theme and have adjustable transparency then?

**Comment by suphon-t** [comment]
The app drawer background and the dock search bar background are two different things rendered using different methods.

**Comment by LuminarySage** [comment]
So don't you want to try to find an alternative method instead of just slapping down a reasonable request like this?

**Comment by Jnss98b** [comment]
I think #1652 would be a good workaround

**Comment by suphon-t** [comment]
Sorry, but I can’t find a reasonable way to implement what you want currently.

**Comment by Jnss98b** [comment]
@paphonb #1652 maybe?

**Comment by LuminarySage** [comment]
@paphonb  #1652 might be a good workaround
