### ISSUE TITLE
Let the BugReportService process be optionable !

### ISSUE THREAD

**Issue by DI555** [Deletescape-Media/Lawnchair#1657]
Let the BugReportService process be optionable to load or not!
I suggest an opton 'Bug seport service' with on/off switch.
Thank you in advance!

**Comment by suphon-t** [comment]
Settings -> 3 dots -> developer options -> show bug report notifications

**Comment by DI555** [comment]
Wow, I missed that 3 dots menu, many thanks !!!

**Comment by DI555** [comment]
Still load BugReportService :(((. last build. Switch 'show bug report notifications' is off.
