### ISSUE TITLE
Square of wallpaper in navbar when scrolling in app drawer

### ISSUE THREAD

**Issue by ja-som** [Deletescape-Media/Lawnchair#1658]
## Description

When I open app drawer and I scroll down/up I see a square of my wallpaper on the navigation bar. It "flashes" there. I also tried to reset my settings, and I did not set anything, and the issue persisted.

## Steps to Reproduce

1. open app drawer
2. scroll down or up

## Environment

* Device: Nokia 6.1 (2018)
* Android version: Pie June patch
* Launcher version: 2.0-2319
* Rom: Android One

## Logcat

 

sadly I don't have log, but I have screenshot

![AirPlay_Screenshot_2019-07-16_07-36-49 kopie](https://user-images.githubusercontent.com/5942380/61317779-faf15900-a803-11e9-9bf3-a7ad6a09749a.png)

**Comment by LuminarySage** [comment]
May I suggest backing up Lawnchair settings and reinstall it?

**Comment by ja-som** [comment]
I deleted data for Lawnchair, but the issue persisted.
