### ISSUE TITLE
Pixel widget and camera

### ISSUE THREAD

**Issue by HardStyl3rTV** [Deletescape-Media/Lawnchair#166]
the area of pixel widget (calendar/weather on top) is unavailable for widgets to take it's place when it's disabled. (lol the english)

also, google camera icon is not the pixel one, the rest is ok

**Comment by suphon-t** [comment]
1. Fixed.
2. Apps need to supply their own round icon.

**Comment by itsHardStyl3r** [comment]
Google Camera has got it's own pixel icon.
