### ISSUE TITLE
[Feature Request] Bring back recent app locking feature

### ISSUE THREAD

**Issue by beedu18** [Deletescape-Media/Lawnchair#1663]
## Description
Back in the nougat days, I (and a lot of other users) really liked the ability to lock recent apps so that when I tapped the `Clear all` button, the remaining apps would get flushed but only the locked ones would remain. But, most of the stock android 9 pie ROMs seem to have ignored this key feature. Lawnchair is by far the best launcher one could ask for, this feature would make it the perfect launcher. 

## Expected Behaviour
In the recent apps menu, on clicking the respective app icon, there should be a `Lock` option (in addition to `App info`, `Split screen`, `Force stop`). On clicking the `Clear all` button at the extreme left, only the locked apps should stay in the recents menu.

## Actual Behaviour
No `Lock` option present as of now.

## Environment
* Device: Lenovo ZUK Z2 (plus)
* Android version: 9.0
* Launcher version: 2.0-2319-ci-alpha
* Rom: Viper OS v6.6 (build date: 11/07/2019)

**Comment by LuminarySage** [comment]
I'd like to add that there should be a visual indicator for apps locked in recents. Like a small lock icon in the corner of the app icon in recents for example.

**Comment by hsiktas** [comment]
This is important because some vendors have started to aggressively kill background apps if they are not locked in the recents view.
Here is a good overview of affected vendors: https://kb.adguard.com/en/android/solving-problems/background-work

There is more info here: https://dontkillmyapp.com/

**Comment by nyancrimew** [comment]
@hsiktas We cannot influence this behavior even with locking them in Lawnchairs recents, this will only influence our built in clear all feature

**Comment by DanGLVK** [comment]
As stated in the above comment a launcher simply cannot influence the system's memory management

**Comment by LuminarySage** [comment]
@deletescape @DanGLES3  Yeah, but you guys should still consider adding it to Lawnchair soon though. I've accidentally swiped away apps way too many times that I think any recents provider should come standard with this
