### ISSUE TITLE
Custom labels doesn't work after updates

### ISSUE THREAD

**Issue by xratei** [Deletescape-Media/Lawnchair#1665]
## Description

I have a custom label for my Japanese games (English label since original have Japanese text). I've done the custom label inside the app drawer and also dragged a copy out to home screen so it will automatically copy the custom label too.

The problem is after I update Lawnchair v2 from APK file, the custom labels in my home screen would change to original Japanese label. Deleting the home screen icons and dragging a new copy from app drawer doesn't fix this. A phone restart doesn't help too.

Using 'Reset custom icons' from Theme menu fix the labels but will also delete the custom icons I set. Renaming the affected icon in app drawer into something fixes it too.

## Expected Behavior

Custom labels at home acreen should stay after Lawnchair v2 update.

## Actual Behavior

Custom labels reverts to original label.

## Steps to Reproduce

1. Rename an icon in app drawer
2. Drag the same icon to home screen
3. Update Lawnchair v2 to a newer build
4. Check the custom label of the icon in homescreen
![Screenshot_20190723-174110_Lawnchair](https://user-images.githubusercontent.com/53216986/61703909-2ed4fd00-ad75-11e9-9333-d7ade2205c4f.png)
![Screenshot_20190723-174119_Lawnchair](https://user-images.githubusercontent.com/53216986/61703935-398f9200-ad75-11e9-86e3-3bec07718698.png)

## Environment

* Device: Xiaomi Redmi Note 4X
* Android version: 8.1.0
* Launcher version: 2.0-2338-ci-alpha
* Rom: LineageOS 15.1

## Logcat

 

```
your log here
```

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
