### ISSUE TITLE
Color problem for text in search app

### ISSUE THREAD

**Issue by Wsebastien-fr** [Deletescape-Media/Lawnchair#1666]
## Description
I don't know if the problem described below is linkent Lawnchair or Google search app (personally I think this is related to the launcher) :
As you can see in the screenshots, during the day the text of the popular searches (below the Google search bar) is  dark gray (really too dark) and difficult to read and during night (meaning when night mode is effective) the text in the search bar is light grey (too light) and also difficult to read.

Without night mode :
![Without night mode](https://user-images.githubusercontent.com/53208120/61746165-648cdc80-ad9b-11e9-8b40-5f74183efb75.jpg)

With night mode :
![With night mode](https://user-images.githubusercontent.com/53208120/61746159-60f95580-ad9b-11e9-8e60-e860974641f6.jpg)

## Expected Behavior
Without night mode : the text of popular searches should be light grey (like the arrow on the left of the text).
With night mode : the text should darker.

## Actual Behavior
The text is difficult to read as discribed above.

## Steps to Reproduce
Nothing peculiar, just take a look at the screenshots :
Without night mode : https://drive.google.com/open?id=1q-QqRpaW75H1_g5a55YrkCody0wytv5O
With night mode : https://drive.google.com/open?id=1Er4esiuZZ2oZXtaJneK_TMdGYO91s_og

## Environment
* Device: Oneplus 5
* Android version: 9
* Launcher version: 2.0-2338-ci-alpha
* Rom: OxygenOS 9.0.6

**Comment by divadsn** [comment]
@Wsebastien-fr Looks more like a system issue, have you tried to report it on OnePlus Forums maybe?

**Comment by Wsebastien-fr** [comment]
Well, you might be right because some other people have described similar problems on Oneplus forums (they didn't precise which launcher they used). But still with OnePlus default launcher I don't have this problem (screenshot below).

I will look in more detail in the OnePlus forums ...

![Screenshot_20190723-233600](https://user-images.githubusercontent.com/53208120/61749654-8a1de400-ada3-11e9-90b0-f40b240a0362.jpg)

**Comment by cregkly** [comment]
I have had the same problem for a while now on my 3T. If you find an answer please post it back here.

**Comment by Wsebastien-fr** [comment]
Not finding a solution with Lawnchair. I just tested Nova launcher and found something that could explain Lawnchair's problem:
With Nova, if the search engine is Google App, everything is displayed correctly (first screenshot). If the search engine is Google App Overlay, I encounter the same problems as described above (second screenshot).

Can someone confirm which search engine is used in Lawnchair? Would it be possible to have both of these search modes in Lawnchair's list of search engines?

![Screenshot_20190727-170908](https://user-images.githubusercontent.com/53208120/61996227-5c31eb80-b092-11e9-93e5-9c5da2c7afce.jpg)

![Screenshot_20190727-170925](https://user-images.githubusercontent.com/53208120/61996236-6ce26180-b092-11e9-9fea-2541d22668f5.jpg)

**Comment by smkamranqadri** [comment]
+1 same problem

**Comment by Spulface** [comment]
+1 can confirm it with a Samsung Galaxy S10e.
Same behavior and especially problematic when the device is set to night mode. Works fine with other Launchers, like Rootless Pixel Launcher.

**Comment by DanGLVK** [comment]
Most launchers don't use the overlay search (the one that's broken), use amir's Rootless pixel bridge https://github.com/amirzaidi/AIDLBridge/releases/tag/v3 this will make lawnchair use the fullscreen search instead of the broken overlay search (that Google doesn't fix for some reason)

**Comment by Spulface** [comment]
Awesome, thanks a lot for that hint. I did not know that the bridge will work with Lawnchair and I don't care about the overlay search, so it's a nice workaround.

**Comment by DanGLVK** [comment]
Yeah, hopefully Google one day fixes their overlay search

**Comment by Wsebastien-fr** [comment]
I also confirm this is a good workaround. Thanks for the tip.

**Comment by vineetbhatia88** [comment]
+1

**Comment by Spulface** [comment]
Quick update, and not sure what has happend (besides the September Patch from Samsung for the S10e), but the issue is back now, even with the Pixelbridge. Any ideas? Updating Lawnchair to the latest version did not help.

**Comment by augustomerli** [comment]
The same here, Galaxy s9 on the night mode. Even the workaround with pixel bridge doesn't work.
Is possible to force to open this search in the "light" mode? Because if I don't use the dark mode this issue doesn't happen.
Thank you.

**Comment by DanGLVK** [comment]
@augustomerli Sadly we have no control over how the google app is themed, if you have dark mode the google app will use a dark theme, we can't change that

**Comment by augustomerli** [comment]
@DanGLES3 
I understand. Even with this issue, I think that the lawnchair is one of the best launchers for Android. Here I will manage the problem using a Samsung theme called high_contrast_theme_Ii

**Comment by randomDrops** [comment]
I don't have any problem on this when using other launchers, like OnePlus Launcher and Pixel Launcher.  On the other hand, this occurs in both of my Android devices, OnePlus 6T and Mi Pad 4. Don't know what else I can contribute to resolve the issue.  Thanks.

**Comment by iamjonmiller** [comment]
OnePlus 7 Pro user here, encountered the same issue while using the stock Google search. I think I remember something similar back when using Nova. 

The odd thing is that it is only broken in the assistant pop-up from the dock search:
![Screenshot_20191112-190040](https://user-images.githubusercontent.com/21957977/68729890-08cfa480-0580-11ea-8da4-dc28265176db.jpg)

While if you use the same search engine from the app drawer it's all good:
![Screenshot_20191112-190046](https://user-images.githubusercontent.com/21957977/68729914-14bb6680-0580-11ea-80db-4088cf35e01d.jpg)

**Comment by hubmacfan** [comment]
I do not have night mode enabled , and I am having this problem on the S9+.

**Comment by sobirpangode** [comment]
I'm also having same problem on Oneplus 7 pro running android 10. Any updates on this bug.

**Comment by bohrabhijeet** [comment]
This is not handled by Lawnchair. However, you can use the Pixel Bridge APK to resolve the light text on light background. 

[Download here](https://github.com/amirzaidi/AIDLBridge/releases/tag/v3)

**Comment by ghost** [comment]
What I did is... I downloaded **Google Go** on Google Play.

- Then go to Lawnchair Setting. Search>Search Engine
- Then switch it to Google Go
- But by using Google Go you can't use it in dark theme 
maybe they will make an update to use dark theme. 

I prefer using Google Go and I don't mind the light theme. 
Hopefully this is helpful ☺️

**Comment by contourintegrals** [comment]
This issue IS closed, but the problem has started again (since a Google app update, not sure which one).

Here is the breakdown of what happens:

- Without Pixel Bridge: Overlay-based search, inaccurately coloured dark mode.

- With Pixel Bridge: Full screen search, accurately coloured dark mode, **except the search suggestions**. The search suggestions' background is white, but the text and the arrow next to it is coloured as if it's in dark mode.
