### ISSUE TITLE
The whole screen is covered by a tint in recents in landscape when blur is toggled on

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1669]
## Description

If blur is turned on, there will be a blurred tint of the wallpaper covering the whole screen when you try to take an app to the foreground in recents in landscape mode.

## Steps to Reproduce

1. Enable blur in theme settings
2. Put device to landscape orientation
3. Go to recent apps
4. Notice how the whole screen is overlaid by a blurred tint of the current wallpaper

## Environment

* Device: OnePlus 6
* Android version: 9.0
* Launcher version: 2338
* Rom: OOS 9.0.3

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/61762075-d0247900-ad9e-11e9-860e-8d8a591d4848.gif)

**Comment by LuminarySage** [comment]
Please note that this doesn't happen in portrait at all

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
