### ISSUE TITLE
Dynamic Calendar icon for icon packs

### ISSUE THREAD

**Issue by p0nkr4t** [Deletescape-Media/Lawnchair#167]
GCalendar doesn't show current data(today is 9th, it shows 31st)

**Comment by Dondrejohnson5** [comment]
Did you update the app? If it's on the latest version, the result should be a round icon.

**Comment by SovsOgKartofler** [comment]
Works fine with latest release using default icons. However, it doesn't work with custom icon packs.

**Comment by p0nkr4t** [comment]
Wow, thanks! :)

**Comment by suphon-t** [comment]
Implemented in 32c2109
