### ISSUE TITLE
Weather not showing in home widget

### ISSUE THREAD

**Issue by Shadowspear123** [Deletescape-Media/Lawnchair#1670]
Weather does not show in widget even though it's enabled in settings. 

Galaxy s8 oreo latest version of lawnchair

**Comment by bohrabhijeet** [comment]
Did you check if the ‘weather updates’ option is enabled in Google app's settings?

**Comment by Shadowspear123** [comment]
Yes it is enabled. Heere'san update. After a clean reinstall the wethaer is showing, but it does not correspond to the weather in the google app, it is stuck and does not continously update and neither does the icon

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
