### ISSUE TITLE
[BUG] Icon size fails to revert to home screen defined icon size when moved from dock

### ISSUE THREAD

**Issue by stickman89** [Deletescape-Media/Lawnchair#1673]
## Description
As the title implies, icons on the dock seem to stubbornly retain their dock icon size when placed back on the home screen.

## Expected Behavior
The icon being moved from the dock should inherit the user defined 'home screen icon size' when placed on the home screen.

## Actual Behavior
When your defined 'dock icon size' differs from your defined 'home screen icon size', the 'dock icon size' is kept when the icon has been moved from the dock to your home screen; causing the since moved icon to look inconsistent with the size of other icons on your home screen.

## Steps to Reproduce
1) Ensure 'Home settings' > 'Dock' > 'Icon size' does not match the 'Home settings' > 'Desktop' > 'Icon size'.
2) Move any icon from the dock back to your home screen (Desktop)...
3) Observe the visual anomaly; the icon does not respect/inherit the 'Desktop Icon size', and instead maintains the 'Dock Icon size'.

## Environment
Device: Xiaomi Mi3W
Android version: 9
Launcher version: Version 2.0-2338-ci-alpha
Rom: Havoc 2.6 PQ3B.190605.006

![Screenshot_Lawnchair_20190725-112304](https://user-images.githubusercontent.com/10897072/61868257-e9c5dd80-aed0-11e9-8adf-01570101c127.png)

![Screenshot_Lawnchair_20190725-113906](https://user-images.githubusercontent.com/10897072/61868275-f34f4580-aed0-11e9-9759-0d9104b06b1b.png)

![Screenshot_Lawnchair_20190725-112319](https://user-images.githubusercontent.com/10897072/61868290-fcd8ad80-aed0-11e9-8b59-f5705b59a8ad.png)

![Screenshot_Lawnchair_20190725-112328](https://user-images.githubusercontent.com/10897072/61868296-0235f800-aed1-11e9-9b69-6cf63ce8bcdc.png)
(Observe the size of the moved 'Phone' app icon....)

Best Regards,

Stickman89

**Comment by RikKoedoot** [comment]
Closing because effort has moved to v11
