### ISSUE TITLE
[Feature request] Automatic dark text independent of the current theme

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1674]
Right now only the "Follow wallpaper" option in theme settings will result in automatic dark text on light wallpapers. I think there should really be a toggle for this instead of only including it in one theme setting because it concerns contrast between home screen elements. This also helps that people can toggle it off if they don't want auto dark text.

**Comment by LuminarySage** [comment]
Actually, I just thought of a simpler way. There's a dark text toggle in theme settings already so why not just turn it into a drop-down menu instead? It would include 3 options: on, off, and auto.

**Comment by suphon-t** [comment]
For now you can use the "Text color" option in Settings -> Desktop.

**Comment by LuminarySage** [comment]
That's still only following the theme though. If you set the theme to follow daylight then the text will basically be white regardless of how bright your wallpaper is. What I'm requesting here is basically keep the text color behavior when lawnchair theme is set to follow wallpaper but make a toggle for it instead of just tying it just to the follow theme option.

**Comment by LuminarySage** [comment]
This seems to have been resolved I believe so I'm closing this issue
