### ISSUE TITLE
Lawnchair/Quickstep crashes while playing TuneIn

### ISSUE THREAD

**Issue by BastogneBas** [Deletescape-Media/Lawnchair#1682]
When I'm playing TuneIn Radio, LawnChair crashes every few minutes on the background. 

## Description

It happens every few minutes. So, when I swipe up, to open the Quickstep switcher, it takes a while for it to load, what also happens when you reboot the phone and open the switcher. Or if I press the home button, lawnchair has to load first. This only happens when I'm playing TuneIn. Spotify or any other music app just works fine. Also if I don't play anything, it doesn't crash.
I hope I told it in a understandable way, but if you have questions, feel free to ask.

## Expected Behavior

If I open the app switcher or press the home button, it should just work, and I don't have to wait for it to load.

## Actual Behavior

Lawnchair crashes, and has to load when I open it

## Steps to Reproduce

1. Play a TuneIn radio station (kronehit in my case)
2. And wait for it

[Here's a live sample.](https://drive.google.com/file/d/1dAIYKohrihZA2fG9ri6u9on8dKla4FYd/view?usp=drivesdk) 

## Environment

* Device: OnePlus 5T
* Android version: 9.0.0
* Launcher version: 2.0-2338-ci-alpha
* Rom: LineageOS

## Logcat
https://del.dog/Bastogne_BasLawnchair

**Comment by suphon-t** [comment]
The video doesn't show any crash dialog and your logcat doesn't indicate a crash.

**Comment by suphon-t** [comment]
Closing as no further information was added.
