### ISSUE TITLE
Oneplus weather display on the desktop is not normal.

### ISSUE THREAD

**Issue by Laeoo** [Deletescape-Media/Lawnchair#1688]
Every time I flash the weather in the app, the icon on the desktop will change to a wrong yellow icon #
![Screenshot_20190806-133038_Lawnchair](https://user-images.githubusercontent.com/41740567/62513371-71ef9f80-b84e-11e9-91a6-5e63e8561cf6.png)

**Comment by DanGLVK** [comment]
That's a known issue of the OnePlus weather provider, as a workaround you can use the Google weather icons https://play.google.com/store/apps/details?id=com.naman.gnchronus and enable them in the widget settings of lawnchair

**Comment by Laeoo** [comment]
Thank you
