### ISSUE TITLE
[Bug] Percentage for slider settings split into two lines

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1689]
## Description
Setting with a slider that go upto or exceed 200% get the text displaying percentage number split into two lines.

## Expected Behavior
Display the percentage on a single line, displayed clearly.
Ex:
200%

## Actual Behavior
Splits the percentage into 2 lines.
Ex.
200
%

## Steps to Reproduce

1. Open Lawnchair settings
2. Find a setting with a slider that goes to or past 200%
3. Slide the setting to 200%

## Environment

* Device: Samsung Galaxy S9+
* Android version: 9.0.0
* Launcher version: 2.0-2357-ci-alpha
* Rom: OneUI 1.0

**Comment by RikKoedoot** [comment]
Can you give an example of a slider that does this?

**Comment by ghost** [comment]
Don't know what happened, but it doesn't seem to be happening anymore. Still on same version as when I reported this.

It was happening on
* Display > Icon size
* App Drawer > Icon size
* Dock > Icon size

**Comment by LuminarySage** [comment]
> Don't know what happened, but it doesn't seem to be happening anymore.

Then close the issue
