### ISSUE TITLE
[Feature Request] Hide tab names in app drawer and  implement Oneplus Launcher Hidden Space like feature

### ISSUE THREAD

**Issue by SoumyBhow** [Deletescape-Media/Lawnchair#1690]
I would like to be able to hide the tab names so that the app drawer appears to be normal, but I'm still able to swipe to the left to access extra apps that I want to be hidden from others. I also would like a feature to add a password or pin to be able to access this 'secret' tab. I'm not sure how this password feature will work with Lawnchair being Open-Souce and all so I understand if it's not possible. The main thing that I would like is to hide the tab names.

**Comment by PranavBhattarai** [comment]
@SoumyBhow I was going to make a feature request, but you made it. 

Thanks. 

I also love this concept. I hope this gets implemented in the near future.
