### ISSUE TITLE
Really slow gesture to show notifications (swipe down) 

### ISSUE THREAD

**Issue by WuerfelDev** [Deletescape-Media/Lawnchair#1692]
## Description

The notifications come down really really slow. Its not slow on my OOS OP6, so there must be a bug i guess something that your app doesn't retrofit perfectly to Marshmallow 

## Expected Behavior

It should come down in a nice speed. 

## Actual Behavior

It is really slow

## Steps to Reproduce

1. Get a oneplus one
2. flash CyanogenMod 13
3. install apk
4. swipe down

## Environment

* Device: OnePlus One "bacon"
* Android version: Marshmallow
* Launcher version: Latest
* Rom: CyanogenMod

**Comment by suphon-t** [comment]
This is Android bug that happens only on Marshmallow. Not fixable by us.
