### ISSUE TITLE
Crash while deleting app

### ISSUE THREAD

**Issue by aikudinov** [Deletescape-Media/Lawnchair#1693]
Just had a crash while deleting app from homescreen:
https://del.dog/oxikuyelix.sql

**Comment by milindgoel15** [comment]
First update ur lc

**Comment by msfjarvis** [comment]
> Just had a crash while deleting app from homescreen:
> [del.dog/oxikuyelix.sql](https://del.dog/oxikuyelix.sql)

Use the latest version of LC and please don't blindly remove the error template, it exists for good reason.

**Comment by aikudinov** [comment]
I know its not good, but im on vacation with limited internet access, so I thought any stack trace might help or i'll simply forget about it later. I cant reproduce it with neither version anyway, tried several times.

Thanks for doing a great job anyway.
