### ISSUE TITLE
Inconsistent setting

### ISSUE THREAD

**Issue by GabrielMGitHub** [Deletescape-Media/Lawnchair#1694]
## Description

When installing the launcher the icons shown are the same as the system.
![20190809_131937](https://user-images.githubusercontent.com/8754997/62793979-4d433400-baa9-11e9-97ea-602543c6fa6f.jpg)

After going into Settings and clicking Theme the icons change to circle alone without me changing the settings, Lawnchair should continue to use the system default and not change the setting to Circle alone.
![Screenshot_20190809-132122_Lawnchair](https://user-images.githubusercontent.com/8754997/62794175-ccd10300-baa9-11e9-8dd7-636d0bd8d48e.jpg)
![Screenshot_20190809-132137_Lawnchair](https://user-images.githubusercontent.com/8754997/62794190-d35f7a80-baa9-11e9-8260-3b2edaee92f1.jpg)
![Screenshot_20190809-132148_Lawnchair](https://user-images.githubusercontent.com/8754997/62794197-d8bcc500-baa9-11e9-8ad9-b0d43618603a.jpg)

## Expected Behavior

Look up

## Actual Behavior

Look up

## Steps to Reproduce

Look up

## Environment

* Device:
* Android version: 9.0
* Launcher version: 2.0-2357-ci-alpha
* Rom: Samsung Stock Rom S8+ One UI 1.0

## Logcat

 

```
your log here
```

**Comment by fonix232** [comment]
Samsung's main apps' icons are NOT adaptive icons, that's why they do not change shape. If you enable the forced adaptive icon generator, that should solve it.

**Comment by RikKoedoot** [comment]
@fonix232 he probably already did that, as the messages and camera icons are round

**Comment by GabrielMGitHub** [comment]
I think you did not understand the question.  It has nothing to do with the adaptive icon, but when starting Lawnchair, the icons start adaptive to the system format, but when you open the settings it changes to circle icons alone.  I have to set adaptive icons back as system default and it works normal.  This launcher is full of inconsistency between what is activated on first boot and then changes or deactivates when opening settings the first time.

pt_br
Acho que vocês não entenderam o questionamento. Não tem nada haver com o ícone adaptativo, mas sim ao iniciar o Lawnchair, os ícones iniciam adaptativos para o formato do sistema, mas ao abrir as configurações muda para ícones em círculo sozinho. Tenho que setar de novo os ícones adaptativos como padrão de sistema e funciona normal. Este launcher está cheio de inconsistência entre o que vem ativado na primeira inicialização e depois muda ou desativa ao abrir as configurações a primeira vez.

**Comment by GabrielMGitHub** [comment]
Fixed build alpha-2375:
- Fix wrong icon shape default value (by paphonb).
