### ISSUE TITLE
Icons not searchable in icon-picker?

### ISSUE THREAD

**Issue by Noxis73** [Deletescape-Media/Lawnchair#1695]
I spent almost 3 hours to replace my icons, due to missing a search field in the icon picker. Lawnchair is a great Launcher though, thanks!

**Comment by RikKoedoot** [comment]
![Screenshot_20190809-192532](https://user-images.githubusercontent.com/29402532/62797250-85fc0100-badb-11e9-8741-635a4a7d4a67.jpg)
What version are you using? As there definitely is a searchbar, look in the screenshot

**Comment by Noxis73** [comment]
Thanks for fast reply.... just checked my version.. fdroid got me v1 😒   just installed v2, now it works. thanks! 👍🏻👍🏻

**Comment by HyknuF** [comment]
thanks for quick reply.. just checked my version. fdroid got me v1 for somehow. installed v2, now it works .. thanks!

**Comment by RikKoedoot** [comment]
No problem,  yeah fdroid hasn't forked v2 yet so they still use v1, good to see it works now

**Comment by Noxis73** [comment]
ah i see.. thanks again, and great job! 👌🏻👌🏻👌🏻
