### ISSUE TITLE
[Feature Request] Add Canadian English as a language option

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1705]
## Description
Wanted to help translate the app in anyway I can, so I wanted to help edit or add Canadian English (en_ca) on crowding, but it's not there. I have no issue with doing them all as it's pretty simple. It's a mixture of both American English and British English. Some words are spelt with American spelling (eg "Program") while others are spelt with British (eg "Colour").

## Expected Behavior
Canadian English (en_ca) should be a translation option in crowding for this project.

## Actual Behavior
No Canadian English (en_ca) translations available, so cannot translate.

## Steps to Reproduce
1. Go to crowding page
2. Search for english
3. No Canadian English is found

## Environment
* Device: Samsung Galaxy S9+
* Android version: 9.0.0
* Launcher version: 2.0-2357-ci-alpha
* Rom: OneUI 1.0

**Comment by bohrabhijeet** [comment]
@kerosyn Languages cannot be added/removed by the translators. It has to be added by the admin of the crowdin project.

**Comment by ghost** [comment]
@bohrabhijeet I understand that. Before posting this I looked through the crowdin project to see if I could add the language myself, which I couldn't. That's why I submitted the issue so it could be added. Once added I can do the translation.

**Comment by bohrabhijeet** [comment]
@kerosyn A’ight, but a lot of languages will increase the size of the app. Untill a sufficient amount of users don't ask for the language, we don't really add it.

**Comment by fonix232** [comment]
@bohrabhijeet if Lawnchair would adopt the App Bundle build target, it wouldn't be a problem 😉 And from a bundle, one can generate a universal APK as well, while Play Store installs would retain small size (and dynamically loaded languages as well!).

**Comment by LuminarySage** [comment]
Well, Lawnchair doesn't even have a play store release yet so utilizing app bundle would do nothing for now really
