### ISSUE TITLE
[Feature request (or Bug maybe?)] App drawer search bar alpha transparency customization

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1708]
I'm not sure if this wasn't implemented in Lawnchair or just a bug but there's currently no way to adjust the app drawer search bar transparency while the same is possible for the dock search bar. Please consider implementing it if it's not a bug.

**Comment by skittles9823** [comment]
@Jnss98b That's intentional. Allowing the app drawer search bar to go transparent makes some ugly ui issues arise to do with the bar.

**Comment by LuminarySage** [comment]
@paphonb So you're just gonna close the issue instead of finding a way to fix it?

**Comment by suphon-t** [comment]
As @skittles9823 said, it's intentional.

**Comment by LuminarySage** [comment]
@paphonb Yes I knew that. However, wouldn't the preferred solution be finding a workaround instead of just never implementing it? I don't really care if it's gonna take a while, just don't dismiss such a legitimate feature request.

**Comment by suphon-t** [comment]
@Jnss98b If you have searched, you'd know that this has been a thing for months and so far we haven't found a way to smoothly clip the search bar out without performance penalties.

**Comment by LuminarySage** [comment]
Added in 2380 if anyone was wondering
