### ISSUE TITLE
Does Weather Still Work in Lawnchair v1?

### ISSUE THREAD

**Issue by 0pLuS0** [Deletescape-Media/Lawnchair#1709]
## Description

I'm using a OnePlus 5T with LineagOS microG 16.0 PIE. I installed Lawnchair 1.2.1.2001 from F-Droid and I signed up for an OpenWeatherMap API and when I enable the Weather in Lawnchair nothing happens.

Does Weather still work in v1, and do I need any Google Framework installed for this to work, or can this work with LineageOS microG?

## Expected Behavior

I'm hoping Weather still works in v1?

## Actual Behavior

Nothing

## Steps to Reproduce

1. Install LineageOS microG 16.0
2. Install Lawnchair 
3. Install 1.2.1.2001 from F-Droid
4. Enable Weather in Lawnchair and add my OpenWeatherMap API

## Environment

* Device:
* Android version: PIE
* Launcher version: 1.2.1.2001 from F-Droid
* Rom: LineageOS microG 16.0

## Logcat

 

```
your log here
```

**Comment by LuminarySage** [comment]
What are you even doing here? This is the issue tracker for V2...

**Comment by 0pLuS0** [comment]
Well forgive me, I wasn't paying attention, anyhow it's working...

**Comment by LuminarySage** [comment]
It's fine. You should really migrate to V2 though, V1 is basically deprecated at this point.

**Comment by 0pLuS0** [comment]
I've got it working, my mistake...

Well I don't see any v2 in F-Droid, is it going to be in it soon?

Thanks

**Comment by LuminarySage** [comment]
Not sure when but for now official V2 alpha builds are released through this Telegram channel: https://t.me/lawnchairci

**Comment by 0pLuS0** [comment]
Well I don't want to mess with Alpha and I don't use Telegram....

Thanks

**Comment by LuminarySage** [comment]
It's "alpha" by name but releases from the last couple of months have been pretty stable and are pretty much daily driver material at this point. You should really give it a try. At this point, I bet there are more people running V2 than V1.

**Comment by 0pLuS0** [comment]
Ok, sounds good on the Alpha part, but I don't use Telegram, don't care, or want Telgram...

Cheers

**Comment by DanGLVK** [comment]
@0pLuS0 You can also find our alpha builds on apkmirror https://www.apkmirror.com/apk/deletescape/lawnchair/

**Comment by LuminarySage** [comment]
@DanGLES3 Yeah that too, almost forgot about apkmirror

**Comment by 0pLuS0** [comment]
ok thanks

**Comment by darkmorpher** [comment]
If you want to use Google Awareness API engine for weather, then v1 (1.2.1.2001) still works with "Google" app installed and long proper location permission was given. If nothing shows up, disable it from menu and add the widget version instead.
Tested on Omni, Lineage, AOSPA.

**Comment by 0pLuS0** [comment]
I said I had the weather working in v1, it was my mistake....

**Comment by darkmorpher** [comment]
Yeah saw that after I replied.
FYI, it also works on latest v2 (more weather sources) if you decide to try it out.

**Comment by 0pLuS0** [comment]
v1 is fine for now, since it's easy to grab out of F-Droid...
