### ISSUE TITLE
[Feature request] Make the desktop lock feature more accessible

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1711]
Currently, if you want to move widgets or icons, rename apps and folders, resize widgets, etc., you would need to go all the way into desktop settings to unlock it, which is 1 tap & hold (might be different depending what gesture you set the home screen pop-up to) and 3 taps.

I think a "Lock/Unlock desktop" button should be added to the home screen pop-up menu (furthermore, add a toggle to turn that button on and off because I know there are people who don't want such button in the home screen pop-up). Additionally, it would be nice to have it mappable to gestures too (e.g., tap and hold to lock/unlock desktop).

**Comment by stephendt** [comment]
This is actually the primary reason for me not switching to Lawnchair. I deploy a lot of devices for seniors, and a lot of them have mobility issues. I need to be able to allow for seamless unlocking of the desktop otherwise they will never be able to figure out how to customise their desktop.
