### ISSUE TITLE
[Feature Request] 3 swipe screenshot

### ISSUE THREAD

**Issue by FANMixco** [Deletescape-Media/Lawnchair#1714]
Would be possible to add an option for taking screenshots with gestures? Maybe like in many Phones with the Triple Swipe, I haven't found anything related. Thanks!

**Comment by suphon-t** [comment]
That's not something a launcher can do.

**Comment by FANMixco** [comment]
> That's not something a launcher can do.

Why not @paphonb? Can you explain it? You already have some custom gestures and probably, it can be added to trigger the screenshot action. Maybe something like this:

https://www.mytrendin.com/taking-screenshot-particular-view-android-programmatically-using-kotlin/

**Comment by LuminarySage** [comment]
@FANMixco The link you posted talks about apps taking screenshots of their own activities, not anywhere in the system
