### ISSUE TITLE
How do I build this correctly?

### ISSUE THREAD

**Issue by AndyCGYan** [Deletescape-Media/Lawnchair#1718]
## Description

I'm trying to experiment with some changes for personal use, but before that, naturally I gotta do a successful build first, and I can't (kinda, see below).

## Expected Behavior

Build succeeds and when installed behaves the same as the latest version available on [APKMirror](https://www.apkmirror.com/apk/deletescape/lawnchair/).

## Actual Behavior

The "building" section of the readme doesn't really offer much, other than pointing me to a range of variants to use.
`quickstepLawnchair*[Debug|Optimized]` variants can be built successfully, but when installed throw a ton of Bug Reports and LeakCanary stuff.
Aside from that, I immediately noticed a difference between the build product and the APKMirror build:
![Screenshot_20190820-235207_Lawnchair](https://user-images.githubusercontent.com/18655204/63363556-694aad80-c3a6-11e9-92fd-e0247b649c73.png)
![Screenshot_20190820-235250_Lawnchair](https://user-images.githubusercontent.com/18655204/63363559-694aad80-c3a6-11e9-83ce-622c258788fc.png)
Note that the margin to the right of the dock exists in the APKMirror build but is totally gone in the build product.
`quickstepLawnchair*Release` variants fail with the below errors:
```
LawnchairApp.kt: (42, 12): Unresolved reference: squareup
LawnchairApp.kt: (67, 13): Unresolved reference: LeakCanary
```

## Steps to Reproduce

...just build?

## Environment

Latest Android Studio and dependencies (installed fresh today, in fact).
Latest source synced from `alpha` branch.

**Comment by DanGLVK** [comment]
@AndyCGYan the reason for the differences between your build and the one from apkmirror is that the sources in GitHub weren't updated yet, also the bug reports and leak canary can both be disabled from the developer options of lawnchair, the leak canary thing is something that comes enabled when you build a dev variant of lawnchair

**Comment by AndyCGYan** [comment]
@DanGLES3 
I grabbed an older APKMirror release and checked, you're right about the difference. I just didn't expect such a crucial (IMO) UI element can still be "bugged" in a very recent release...
Being able to turn them off in what I build is cool, but surely there has to be a variant that does away with them (or has them off by default), as that's how the APKMirror releases behave? I imagine those can only be the `*Release` variants, but as said those can't be built right now.

**Comment by nyancrimew** [comment]
All our Release builds are built via our CI server. There are several environment variables read in our build file which make those builds behave differently than normal local builds. You should be able to set these flags locally to get equivalent builds.

**Comment by AndyCGYan** [comment]
@deletescape Do you mean that the `*Release` variants *need* these envvars to even build properly?

**Comment by nyancrimew** [comment]
@AndyCGYan the current checks for whether leakcanary should be enabled only check for the env vars at build time and not the buildvariant as well, but the leakcanary library is never included on the release variant. This is a little logical error which leads to the builds currently being broken on release variants.

**Comment by AndyCGYan** [comment]
@deletescape Okay, since it can be manually disabled I'll let it slip. I'll wait for up-to-date source and then start my modding attempts.
