### ISSUE TITLE
App crashes when I change global search provider

### ISSUE THREAD

**Issue by Cyanic76** [Deletescape-Media/Lawnchair#1720]
## Description
I just clicked on Launcher Settings > Search > Global Search Provider and got a list of options.
Then, I clicked on the one that wasn't selected (app search) and the app freeze. The app crashes 2 seconds later.

## Expected Behavior
I would've be able to change the search provider but as the app crashes when I try, I am not able to change it.

## Actual Behavior
The app freeze when I select `App Search` and crashes

## Steps to Reproduce
Not sure if these steps will work on your phone but worked on mine

1. Long press on the launcher
2. Click on `Home Settings`
3. Click on `Search`
4. Click on `Global search provider`.

## Environment

* Device: Nokia 5.1
* Android version: Android 9 (updated, was on android 8)
* Launcher version: 2.0-914-ci-alpha
* Rom: Android One

**Comment by ghost** [comment]
@duPlex6 Possible explanation as to why this is happening: u'r using 2.0-914-ci-alpha, the current version is 2.0-2382-ci-alpha. u should probably update, but then again u'r just over 1.400 builds behind, no biggie.

**Comment by suphon-t** [comment]
Closing this now. Please reopen if the issue still exists in the latest alpha.

**Comment by Cyanic76** [comment]
oh okay thanks anyway
