### ISSUE TITLE
App drawer tab config menu will disappear immediately

### ISSUE THREAD

**Issue by linsui** [Deletescape-Media/Lawnchair#1721]
## Description

When long pressing on tab(personal or work, etc) in app drawer, a manu will show up. But it will disappear immediately unless I press on it before I stop pressing on tab.

## Expected Behavior

Menu shouldn't disappear.

## Actual Behavior

It will disappear immediately unless I press on it before I stop pressing on tab.

## Steps to Reproduce

1. Long press on a tab(personal or work, etc) in app drawer.
2. A menu shows up.
3. The menu will disappear immediately.

## Environment

* Device: Xiaomi Mi 6
* Android version: 9
* Launcher version: 2.0-2382
* Rom: AOSP

See https://gitlab.com/oldosfan/librechair/issues/12#note_206286166

![MP4_20190822_153358](https://user-images.githubusercontent.com/36977733/63497084-a13f1700-c4b2-11e9-93a1-98837d3e1d1c.gif)

**Comment by LuminarySage** [comment]
Can't reproduce it on my OP6

![ezgif com-resize](https://user-images.githubusercontent.com/24306400/63488546-5eaf1780-c47d-11e9-862b-59d3c5b05476.gif)

**Comment by milindgoel15** [comment]
It works fine for me here too.

A screen record of it would be better tho to look into this by devs

**Comment by linsui** [comment]
I upload a screen record. Don't know how to make a gif, sorry...

**Comment by LuminarySage** [comment]
You don't have to make a gif. Just record your screen and convert the video in to a gif using some website (because github doesn't accept mp4 for some reason)

**Comment by linsui** [comment]
I find an app to covert vedio to gif :joy: Have updated.

**Comment by milindgoel15** [comment]
@linsui did u tried clearing data and seeing it again if it happens?

**Comment by milindgoel15** [comment]
@Jnss98b damn 189 games😱😱

**Comment by linsui** [comment]
Don't know how to clear data but I installed a brand new lawnchair to reproduce this problem...

**Comment by LuminarySage** [comment]
@linsui You can clear data in settings
![Screenshot_20190822-155303](https://user-images.githubusercontent.com/24306400/63545321-18959a80-c4f5-11e9-93f3-7645d30a69bd.jpg)![Screenshot_20190822-155316](https://user-images.githubusercontent.com/24306400/63545329-1c292180-c4f5-11e9-977c-eef3d4366be7.jpg)![Screenshot_20190822-155322](https://user-images.githubusercontent.com/24306400/63545332-1d5a4e80-c4f5-11e9-8ad9-f32078ffb625.jpg)

**Comment by LuminarySage** [comment]
Also, do you still experience the same problem after reinstalling lawnchair?

**Comment by linsui** [comment]
Yeah, I can reproduce this after clearing data and reinstalling.
I found that if I press on the tab for a short time the menu won't disappear but if I keep pressing on the tab the menu will disappear when I stop pressing.

**Comment by LuminarySage** [comment]
> I found that if I press on the tab for a short time the menu won't disappear but if I keep pressing on the tab the menu will disappear when I stop pressing.

That also doesn't happen on my device either

**Comment by linsui** [comment]
I can't either reproduce this problem on Xiaomi Mi Pad 4... Is there any other thing I can do?
