### ISSUE TITLE
Web search engine bypasses ad blockers.

### ISSUE THREAD

**Issue by psmiddy** [Deletescape-Media/Lawnchair#1722]
## Description
When Search engine: Google (web) is selected in Lawnchair v2, it will use the default web browser to display search results.

When search is initiated from within Samsung Internet Browser and an adblocker is installed, Google ads are blocked from search results.

When the search is initiated from Lawnchair v2, it will display the search using Samsung Internet Browser but it will not block Google ads.

## Expected Behavior
When Search engine: Google (web) is selected in Lawnchair v2, it will use Samsung Internet Browser to display search results and block the ads.

The results from the Google Search widget should mirror the results from the browser.

## Actual Behavior
Although the google search is displayed in the browser and the url is exactly the same as if I searched from within the browser, the adblocking is bypassed and ads are displayed in the search results.

Watch video here: https://linksharing.samsungcloud.com/1566518928175CDJrlya

## Steps to Reproduce
1. Install Samsung Internet Browser
2. Enable Adblocker 
3. Verify that Google Search ads are blocked
4. Set Samsung Internet Browser as default browser
5. Enable Google web search in Lawnchair
6. Search via Lawnchair and see ads.

## Environment
Device: Samsung Galaxy S9+
Android version: 9.0.0
Launcher version: 2.0-2382-ci-alpha
Rom: OneUI 1.0

![20190823_100637_1](https://user-images.githubusercontent.com/16343313/63559262-f3a43480-c593-11e9-8f4a-468b220f01b7.gif)

**Comment by nyancrimew** [comment]
This is most likely a bug (or feature, who knows) within Samsung Internet and not something we can influence. This is definitely not intentional on our side and we're simply making use of standard Android features to open an URL in a browser.

**Comment by fonix232** [comment]
The adblocker is clearly working (there are two ads blocked), however the filtering seems to be off. Notified acquaintance at Samsung who has contacts in the Internet dev team, they'll check it out.

Could you please paste the exact URL for both the manually launched search and the Lawnchair initiated one?
