### ISSUE TITLE
2D placement of all desktops. Feature.

### ISSUE THREAD

**Issue by DI555** [Deletescape-Media/Lawnchair#1724]
Now possible to add and switch desktops to right place by swaping to left(.
Would be great to add and switch them to left&right and up&down!!!
So would be possible use desktops in 2D dimension! (aka 'crossword's stile' or 'sqware style' of placement)
It will needed flown by touch visual icon , with placement of all desktops (dots) with the main(home) one (colored dot) and possibility to set it.
Dear devs, I hope its a great idea! What do you think?

**Comment by Jnss98b** [comment]
I guarantee you this will definitely not be implemented. Not only does it conflict with the notification shade and app drawer gestures (admittedly they can be turned off but still) but it also doesn't add much usability at the cost of additional complexity to the home screen

**Comment by LuminarySage** [comment]
I can guarantee you this will definitely not be implemented. Not only does it conflict with the notification shade and app drawer gestures (admittedly they can be turned off but still) but it also doesn't add much usability at the cost of additional complexity to the home screen.

**Comment by DI555** [comment]
I hope will no any conflicts with those stuff, may be possible settings of gestures position working fields , like horisontal upper and lower borders , wich will set gestures fields of using desktops swipes (in a center) and swipes of notification shade and app drawer !!!
And this will be cool))!!!

**Comment by DI555** [comment]
this feature is very useful, it lets being of desktop in more degrees!

**Comment by yasanglass** [comment]
> this feature is very useful, it lets being of desktop in more degrees!

Dimensions*

Also, I don't think this feature will ever be implemented as @Jnss98b said already. Too complex without bringing any actual benefits and has tons of side effects that require lots of UI/UX changes.
