### ISSUE TITLE
Alarms that are set by other apps and that are not used for real alarm clock are also captured by desktop widget.

### ISSUE THREAD

**Issue by buttonfly1000** [Deletescape-Media/Lawnchair#1727]
Alarms that are set by other apps and that are not used for real alarm clock are also captured by desktop widget.

## Expected Behavior
Only alarms set through clock app are shown in desktop widget.

## Actual Behavior
All alarms are shown in desktop widget.

## Environment

* Rom: mokee
* Device: MI 6X
* Android version: 9
* Launcher version:2.0.2382-ci-alpha

**Comment by suphon-t** [comment]
Which desktop widget are you talking about? There is no alarm info shown in Lawnchair.
