### ISSUE TITLE
[Feature Request] Android 10 Opening Animation

### ISSUE THREAD

**Issue by ndzaky97** [Deletescape-Media/Lawnchair#1729]
Is it possible to port Android 10 opening app animation to Android Pie and older ? It's not necessary, but it'll be nice addition. Take your time if it's possible. Thank you so much.

**Comment by DanGLVK** [comment]
We will need Q sources first to even know if it's possible, and if it is possible it will only work with quickswitch (magisk module) and Android Pie, the Q animation is just way too complex to port to the standard animation framework of Android 8 and bellow
