### ISSUE TITLE
Background Cellular usage

### ISSUE THREAD

**Issue by lunim** [Deletescape-Media/Lawnchair#173]
I am seeing occasional background data usage on cellular even with background usage disabled for the app.  On average I see a few hundred KB per day.

What data would be in use by Lawnchair?

I am running version 255.

**Comment by nyancrimew** [comment]
The only thing which would make sense here is that this is actually Firebase (firebase will soon be removed from the app) logging analytics, Lawnchair doesn't use network connection itself.

**Comment by nyancrimew** [comment]
In the future the app will have a built in updater and will thus also create a bit of network usage, but it will probably be a lot less than right now because we won't be collecting as much analytics data as we are now anymore
