### ISSUE TITLE
BUG lawnchair crash when i try to remove an app from desktop inside a directory

### ISSUE THREAD

**Issue by gpdevsoft** [Deletescape-Media/Lawnchair#1731]
I have two app ( vanilla music and samsung's radio app) inside a directory on desktop, when i long press on vanilla music and tap "remove",  for remove from directory, lawnchair crash.

## Environment

* Device: Samsung Galaxy 
* Android version: 8.1.0
* Launcher version: 2.2.0-2382-ci-alpha
* Rom: samsung experience 9.5

## Logcat

 

```
your log here
```

Lawnchair bug report 03 set 2019 10:46:19 Lawnchair version: 2.0-2382-ci-alpha (2382) build.brand: samsung   version.release: 8.1.0 version.sdk_int: 27 error: Uncaught exception --------- beginning of stacktrace java.lang.RuntimeException: item: ShortcutInfo(id=36 type=APP container=35 screen=0 cell(0,0) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Radio)modelItem: ShortcutInfo(id=36 type=APP container=desktop screen=2 cell(2,3) span(1,1) minSpan(1,1) rank=1 user=UserHandle{0} title=Radio)Error: ItemInfo passed to checkItemInfo doesn't match original 	at com.android.launcher3.model.ModelWriter$UpdateItemBaseRunnable.<init>(ModelWriter.java:423) 	at com.android.launcher3.model.ModelWriter$UpdateItemRunnable.<init>(ModelWriter.java:374) 	at com.android.launcher3.model.ModelWriter.moveItemInDatabase(ModelWriter.java:161) 	at com.android.launcher3.model.ModelWriter.addOrMoveItemInDatabase(ModelWriter.java:106) 	at com.android.launcher3.folder.FolderPagedView.arrangeChildren(FolderPagedView.java:353) 	at com.android.launcher3.folder.FolderPagedView.arrangeChildren(FolderPagedView.java:309) 	at com.android.launcher3.folder.Folder.rearrangeChildren(Folder.java:1078) 	at com.android.launcher3.folder.Folder.rearrangeChildren(Folder.java:1068) 	at com.android.launcher3.folder.Folder.closeComplete(Folder.java:696) 	at com.android.launcher3.folder.Folder.access$500(Folder.java:94) 	at com.android.launcher3.folder.Folder$8.onAnimationEnd(Folder.java:659) 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552) 	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294) 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079) 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146) 	at android.animation.AnimationHandler.-wrap2(Unknown Source:0) 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54) 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 	at android.view.Choreographer.doCallbacks(Choreographer.java:723) 	at android.view.Choreographer.doFrame(Choreographer.java:655) 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 	at android.os.Handler.handleCallback(Handler.java:790) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:164) 	at android.app.ActivityThread.main(ActivityThread.java:7000) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by LuminarySage** [comment]
Next time, just upload the log file instead of copying and pasting its content
