### ISSUE TITLE
Andriod 10 Gesture Navigation Support

### ISSUE THREAD

**Issue by cdfasnacht** [Deletescape-Media/Lawnchair#1733]
Please add support to Lawnchair 2 for Android 10's new Gesture Navigation.

On my Pixel 3 the default Pixel Launcher supports it and when I switch to Lawnchair 2.0-2384-ci-alpha it's disabled and says this launch doesn't support the new gesture navigation.

**Comment by DanGLVK** [comment]
@chrisfasnacht That is something only Google can fix, they disabled the gestures on third party launchers because it's currently broken

**Comment by LuminarySage** [comment]
Adding to what @DanGLES3 said, if your phone is rooted, you can get QuickSwitch and set Lawnchair as the recents provider to get it to work soon after they had updated it with Android 10's Quickstep so check back later. @DanGLES3 Do you guys have plans to add that soon?

**Comment by DanGLVK** [comment]
@Jnss98b Merging the Q launcher3 code will take some time as there are a lot of conflicts in the code

**Comment by LuminarySage** [comment]
@DanGLES3 But it'd still be done before Samsung manages to update their latest flagships to OneUI 2.0 right? 😁

**Comment by DanGLVK** [comment]
@Jnss98b Who knows? Our developers aren't machines lol, they can't work 24/7 on the Q merge

**Comment by LuminarySage** [comment]
@DanGLES3 Yeah Ik that. Was just cracking a joke

**Comment by kbirger** [comment]
XDA suggested that this functionality is tied to the launcher being a system app. They even listed a line of code ostensibly from the source of Android.

I was unable to set lawnchair up as a system app using Titanium Backup, but perhaps somebody else could give it a shot and see if it works.

**Comment by LuminarySage** [comment]
@kbirger I already mentioned above QuickSwitch; the app was literally made to turn a capable launcher into the recents provider. No need for unorthodox solutions. However, Lawnchair is not updated with Android 10's quickstep yet so it can't provide the new gestural navigation yet. Just be patient.

**Comment by LuminarySage** [comment]
This makes me wonder, what would happen right now if Lawnchair is set as the recents provider on 10 and gestural navigation is used? @DanGLES3

**Comment by DanGLVK** [comment]
@Jnss98b A. Not only you wouldn't be able to do that as quickswitch now blocks you from using an launcher incompatible with your current Android version

B. Also all this would do is cause lawnchair to crash repeatedly (as seem by previous reports of users setting lawnchair as the provider on Q)

**Comment by LuminarySage** [comment]
> quickswitch now blocks you from using an launcher incompatible with your current Android version

Does that mean Lawnchair can't even be set as the recents provider at all on 10? Not even with just 3 button navbar or Pie gestures?

**Comment by DanGLVK** [comment]
@Jnss98b The thing is, it's not just about the gestural navigation, lawnchair currently does not work as a provider on Q as the quickstep (recents) code on Q is signficantly different (you can't just use a Pie provider on Q or vice versa)

**Comment by DanGLVK** [comment]
In our merging of the Q launcher3 code we're currently forced to build a separate APK for each, while we were able to get Q gestures on Pie (yup, thank paphonb for that) it still needs a separate Pie and Q APK due to the way each OS handles the recents provider

**Comment by LuminarySage** [comment]
@DanGLES3 Gotcha, thanks for the info! Really looking forward to 10's quickstep merge

**Comment by skittles9823** [comment]
@kbirger Titanium backup can't systemise apps on android 10 as the file system is read only. You just use magisk if you wish to modify system now.

**Comment by kbirger** [comment]
@Jnss98b I think you're conflating the ability to set as a recents provider and the gesture navigation. They are two separate things in android 9. Quickswitch isn't necessarily the solution to everything.

You can force the gesture overlay right now using an adb command, but it doesn't quite "work"  due to missing APIs

**Comment by suphon-t** [comment]
@kbirger The inability to use gesture navigation on 3rd party launchers is because Google couldn’t finish it in time. Right now, there is no other way to use gesture navigation with Lawnchair except with QuickSwitch (or manually doing what QuickSwitch does)

**Comment by LuminarySage** [comment]
@kbirger I feel like you don't even know what you're talking about cause I'm getting Android 10 gestural nav precisely because I set Android 10's stock launcher as the recents provider on my Android 9 phone lol (thanks to @paphonb btw).
![Screenshot_20190912-100901](https://user-images.githubusercontent.com/24306400/64791219-65452200-d545-11e9-8797-aa27f57d2636.jpg)

**Comment by kbirger** [comment]
Android 9, custom rom, not relevant

**Comment by LuminarySage** [comment]
@kbirger That's the default ROM lol. Why are you so quick to assume stuff? Did you even read what I typed? I literally said that I got it because I used quickswitch with Android 10's stock launcher, the damn launcher that was uploaded to AOSP, not because of some custom ROM.

**Comment by LuminarySage** [comment]
Not to mention even if I did use custom ROM, which Pie ROM provides Android 10 gestures exactly?

**Comment by kbirger** [comment]
This should be possible now that the source is released

https://www.androidpolice.com/2019/09/04/android-10-source-code-aosp/

**Comment by skittles9823** [comment]
@kbirger the work on the Q merge has already been going on internally for a short while. Once all the features are back and it's stable enough, there will be a public beta. At a minimum that'll take 1-2 months. It could be more though.

**Comment by miguelcaravantes** [comment]
I am interesting in this

**Comment by CritLoren** [comment]
How often will the Q builds be released? It's been a month since the last one and the latest lawnchair apk doesn't support q navigation

**Comment by DanGLVK** [comment]
@m-vlad a new build has been released early this month on our telegram channel

**Comment by maximousblk** [comment]
Samsung just launched it's One UI 2 for two of the non flagship phones namely m20 and m30 in India.

I really love this launcher and want to keep using it but it doesn't support the new gesture navigations and switches back to the three button navigations.

Please make it work because there is no cleaner launcher that has a native Google now feed on the home page

**Comment by DanGLVK** [comment]
@maximousblk That's not up to us, we already support the Android 10 gestures on our prealpha builds but Samsung won't allow gestures on third party launchers, only way to get around it is with root

**Comment by maximousblk** [comment]
Then is there any way to get lawnfeed independent of lawnchair?

**Comment by DanGLVK** [comment]
@maximousblk No, it's impossible to make lawnfeed work with the stock launcher (if that's what you want), you would need to find another launcher that has the Google feed integrated

**Comment by maximousblk** [comment]
Any alternative way to get Google discover feed any how without root

**Comment by DanGLVK** [comment]
@maximousblk Use another launcher that has the Google feed (Lawnchair, Hyperion, Rootless Pixel Launcher etc)

**Comment by maximousblk** [comment]
This problem is fixed in action launcher if that helps

> @maximousblk Use another launcher that has the Google feed (Lawnchair, Hyperion, Rootless Pixel Launcher etc)

@DanGLES3 for that matter all other launchers have the same issue. I use lawnchair for it's minimal nature without compromising in features. Others are shoving their pro features on their users even if they don't want it. Lawnchair doesn't do that making it lighter. If any launcher can do that, I'm listening.

And if there would be a subreddit for this project, it would be awesome. It doesn't look good asking for help in an issue thread.

Edit: I didn't do my research about the subreddit

**Comment by DanGLVK** [comment]
@maximousblk btw no action launcher didn't do anything, that article title is clickbaity, all they did was add exclusion zones for the back gestures, IT DOES NOT TRULY SUPPORT THE ANDROID 10 GESTURES

**Comment by DanGLVK** [comment]
No Launcher can truly support the Android 10 gestures without root, the API is completely restricted to system apps

**Comment by skittles9823** [comment]
> And if there would be a subreddit for this project, it would be awesome. It doesn't look good asking for help in an issue thread.
> 
> Edit: I didn't do my research about the subreddit

Yea unfortunately the subreddit doesn't have much user support going on. We need some more community members to come in and assist in that part.

I may go through and make a post about bringing in some moderators to assist with that at some point soon.

**Comment by maximousblk** [comment]
I can do some of the mod work if that's ok

**Comment by LuminarySage** [comment]
> > And if there would be a subreddit for this project, it would be awesome. It doesn't look good asking for help in an issue thread.
> > Edit: I didn't do my research about the subreddit
> 
> Yea unfortunately the subreddit doesn't have much user support going on. We need some more community members to come in and assist in that part.
> 
> I may go through and make a post about bringing in some moderators to assist with that at some point soon.

There's a Lawnchair subreddit? Oh I gotchu👌. You should pin a message on the Telegram group telling people about its existence too. Maybe more people will come to the subreddit and help out too.

**Comment by maximousblk** [comment]
There is a telegram for lawnchair?

**Comment by DanGLES3** [comment]
@maximousblk @lccommunity

**Comment by DanGLVK** [comment]
@maximousblk https://t.me/lawnchairci

**Comment by nahtnam** [comment]
I am a little confused, it looks like Action Launcher supports it: https://9to5google.com/2019/12/21/action-launcher-android-gesture-navigation/ I even downloaded it on my S10 and it works perfectly. What is going on?

**Comment by DanGLVK** [comment]
@nahtnam No. It's been stated already that they merely added exclusion zones for the back gestures nothing more,  supporting gestures is restricted to system apps only

Even if you get gestures working on another launcher they're still handled by the stock launcher, true integration with gestures is not possible for third party launchers

**Comment by nahtnam** [comment]
Ah I see, very unfortunate that google would do this

**Comment by DanGLVK** [comment]
@nahtnam They restricted integration with gestures to system apps because they require giving the Launcher very dangerous system level permissions, it wouldn't be wise to give those permissions to regular apps

**Comment by nahtnam** [comment]
Shouldn't Google create some sort of API or abstraction that will allow launchers to safely work with the new gesture system?

**Comment by DanGLVK** [comment]
@nahtnam I mean they kinda already work on the December patch, they look bad but they work

**Comment by maximousblk** [comment]
Any update since then? I am still waiting for the gesture support. I prefer this launcher over one UI. Please, is there any thing that can be done or any workarounds?

**Comment by CritLoren** [comment]
> Any update since then? I am still waiting for the gesture support. I prefer this launcher over one UI. Please, is there any thing that can be done or any workarounds?

The gesture support has been there for months, just use the latest alpha Q build from the telegram release channel and use QuickSwitch to switch the recents app to Lawnchair.

**Comment by nahtnam** [comment]
> > Any update since then? I am still waiting for the gesture support. I prefer this launcher over one UI. Please, is there any thing that can be done or any workarounds?
> 
> The gesture support has been there for months, just use the latest alpha Q build from the telegram release channel and use QuickSwitch to switch the recents app to Lawnchair.

You need root for QuickSwitch right?

**Comment by DanGLVK** [comment]
@nahtnam unfortunately yes, if you need gestures on third party launchers without root that's something only your manufacturer can do (and even then the gestures will be slightly downgraded when using a third party launcher without quickswitch)

**Comment by maximousblk** [comment]
@m-vlad I tried the latest alpha build and it seemed to work until I set it as default launcher. What is that all about?

**Comment by DanGLVK** [comment]
@maximousblk if your system does not allow gestures on third party launchers whenever you change your default launcher the gestures will be disabled

**Comment by 4rz0** [comment]
Any news on this? It has been a while and a new Android version has been release.

EDIT: Nevermind, see #2074.

**Comment by Tony-Stark25** [comment]
> In our merging of the Q launcher3 code we're currently forced to build a separate APK for each, while we were able to get Q gestures on Pie (yup, thank paphonb for that) it still needs a separate Pie and Q APK due to the way each OS handles the recents provider

Anything changed now?? It's still the same problem after 2 years. Please tell if there's an solution.
