### ISSUE TITLE
[Feature request] Move desktops or add empty ones

### ISSUE THREAD

**Issue by Ch1llb0** [Deletescape-Media/Lawnchair#1741]
It would be great to get a feature to be able to move desktops left and right.

In addition to that it would be great to add an empty desktop to whatever position - e.g. between the first and the second existing desktop to be able to create a completely new one. When removing a widget from the left most desktop, the empty desktop disappears and it's a lot of work to add it again by moving all of the icons one desktop to the right one by one.

**Comment by LuminarySage** [comment]
> It would be great to get a feature to be able to move desktops left and right.

Are you referring to being able to rearrange home screen pages? That's already in development and is coming soon

**Comment by Ch1llb0** [comment]
That's exactly right. Perfect!

Another addition: With, I believe, Samsung's launcher it's possible to adjust which of the pages should be the default home screen a press of the home button is getting you to. Could this be added to this launcher as well? Would be handy to be able to set another page than the most left one as default...

**Comment by LuminarySage** [comment]
That's also in development iirc

**Comment by Ch1llb0** [comment]
Great stuff! Hoping to see these features soon.

**Comment by ingenika** [comment]
Yes, I think this is the best feature I would like to have right now.

**Comment by infernix** [comment]
Will this also include setting any specific page as the home page?

**Comment by LuminarySage** [comment]
@infernix Read above

**Comment by Mitch9378** [comment]
@Jnss98b what fork/branch is this work being done on?

**Comment by karanimaan** [comment]
Hi, has this been implemented yet?

**Comment by SuperDragonXD** [comment]
Superseded by #2683; I'd recommend moving discussion there
