### ISSUE TITLE
[Feature request] Home widget should have settings for which Google Calendars to pick from/should include URL subscribed Google Calendars

### ISSUE THREAD

**Issue by Kattochan** [Deletescape-Media/Lawnchair#1743]
## Description
The home widget has the ability to show your Google Calendar events. This does not work for calendars added to Google Calendar through a URL, however. I would very much like to see my university schedule on my home screen through this widget. 

## Expected Behavior
The home widget shows the calendar events from my university URL synced calendar from Google Calendar.

## Actual Behavior
This does not happen. The widget only shows events that fall under the "My calendars" tab in Google Calendar desktop version, not "other calendars"

## Steps to Reproduce
1. Set up the widget
2. Make sure all event sources are on and in the right order
3. Check calendar permissions
4. Notice how university calendar events do not show up.

## Environment
* Device: Nexus 5x
* Android version: 9.0 Pie
* Launcher version: 2.0-2408
* Rom: Pixel3Rom with Francokernel

**Comment by devanshux** [comment]
Yes please! i cannot see the events that where added from a link from skysports . i hope you guys consider this.

**Comment by thinkgadgetsme** [comment]
I am also experiencing the similar issue. The widget does not pull any information from the calendar.
