### ISSUE TITLE
[Feature Request] Add option to manually set navigation icon and status bar light/dark mode in desktop

### ISSUE THREAD

**Issue by ibnu-ja** [Deletescape-Media/Lawnchair#1747]
## Description
Beside the use of automatic color mode from wallpaper, it also need manual toogle button in case navbar color looks very bad.

**Comment by PerLycke** [comment]
Second this, some wallpapers are darker at the bottom and lighter at the top so would be a good addition to be able to manually toggle the navigation bar color separately from the status bar icons color
