### ISSUE TITLE
[Dev Question] Getting the layout of the shortcuts and their spacing for use in another app

### ISSUE THREAD

**Issue by BrandonShihabi** [Deletescape-Media/Lawnchair#1748]
I know that this probably isn't what you guys want in your issues section, but I have no idea how else to contact you guys. 

I am making an app that replicates the gestures on iPhone, however, in order for the closing animation to work, I need to access the location of the different apps on the homescreen, something I have no idea how to accomplish. It would be great if you guys could give a way for me to import the layout of lawnchair in order to get these values, just like how other launchers have an import layout from ___ launcher function. 

Thank you so much!

**Comment by LuminarySage** [comment]
> but I have no idea how else to contact you guys.

At the bottom of Lawnchair's README.md

https://twitter.com/lawnchairapp (this account is for posting memes so don't bother)
https://t.me/lawnchair
https://forum.xda-developers.com/android/apps-games/lawnchair-customizable-pixel-launcher-t3627137

**Comment by BrandonShihabi** [comment]
I'm so stupid, thank you!
