### ISSUE TITLE
Translations for all languages

### ISSUE THREAD

**Issue by nyancrimew** [Deletescape-Media/Lawnchair#175]
Translators for all Languages wanted.

* Comment here before starting to work on your language, this way it is made sure that not multiple persons are working on the same language!
* Translate here on [crowdin](http://translate.lawnchair.info)
* Improvements to the English strings are also accepted and appreciated (you need to make a github PR for that)

**Comment by Wolforpion** [comment]
Hi,
I can help with the Arabic translation if you need that.
Not sure how to do this, but really interested in helping.

**Comment by nyancrimew** [comment]
Thanks a lot @Wolforpion! I have added a link to a small guide on how to use the translation editor in Android Studio

**Comment by fonix232** [comment]
I'd also suggest to remove all unused strings and resources from the app, for easier management.

For translations, I'd suggest to use either [Crowdin](https://crowdin.com/) or [Localize.im](https://www.localize.im/) - I'd prefer Crowdin since I have experience with it, and it is free for open source projects.

**Comment by wyjek** [comment]
Hi,
I'd like to translate it in Polish.
edit: How to open a Pull Request?

**Comment by fonix232** [comment]
@wyjek for a PR, you need to fork the project, make modifications to the `alpha` branch, and when you're done, press the big "Create pull request" button in your fork's header area.

**Comment by wyjek** [comment]
@fonix232 do you know where are the files I have to translate?

**Comment by Wolforpion** [comment]
so we will have a string file to edit?

**Comment by nyancrimew** [comment]
@Wolforpion Moved to crowdin now, link is in the issue description

**Comment by Wolforpion** [comment]
Page not found

**Comment by nyancrimew** [comment]
@Wolforpion I messed up with the link, fixed now

**Comment by Wolforpion** [comment]
should i keep the symbols like (Show %1$s) in the translation?

**Comment by fonix232** [comment]
@Wolforpion stuff like `%1$`, `%2$` are parameters. They come from a different part, and should be kept within the translation too. E.g. if you translate `(Show widgets)` (where `widget` is the parameter already in place), you need to put the parameter to the proper place.

**Comment by Wolforpion** [comment]
what is the process for approval?

**Comment by Niwton** [comment]
I'll translate to português brazil

**Comment by Arceer** [comment]
I can help out with the Swedish translation

**Comment by nyancrimew** [comment]
@Wolforpion the most voted translation is the one used in lawnchair

**Comment by abc0922001** [comment]
I'll translate to Traditional Chinese

**Comment by p0nkr4t** [comment]
I can translate to Russian :)

**Comment by Arrow-C** [comment]
我想要中文

**Comment by hbbxmjbb** [comment]
Could I help the Chinese translation of China?

**Comment by abc0922001** [comment]
@Arrow-C  @hbbxmjbb  https://crowdin.com/project/lawnchairandroid

Submit your translation here

**Comment by 9AC8E2** [comment]
i can help you in chinese (≖ᴗ≖)✧

**Comment by JosephKnight12** [comment]
I can help with the Spanish is my languaje

**Comment by XNJ4** [comment]
I can translate to French if you want 😉

**Comment by Martin005** [comment]
I would like to translate to Czech :)

**Comment by RamiroLB** [comment]
I can help with spanish translation.

**Comment by AxiK101** [comment]
I complete greek translation. When will u implement it?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by seebz** [comment]
The app's name must be corrected in french.

It actually show "Lanceur3" (Launcher3 in french) instead of "Lawnchair".

**Comment by datinnovator** [comment]
Hi!

I can help you out with the Japanese translations...

**Comment by mraliaras** [comment]
Hi,
I can help with the Turkish translation if you need that.

**Comment by delirium-dj** [comment]
Hey guys,
I can help with the translation on Serbian - potential 10 millions of users.

**Comment by ghost** [comment]
Do you need Chinese translator? Maybe I can give a hand

**Comment by pablomeza10** [comment]
I can help with spanish.

**Comment by repires** [comment]
I can help with Portuguese! 😁

**Comment by hassie-dash** [comment]
Hey, I can help contribute to UK (en-rGB) English localisations. I'll do this via a pull request as there are only minor differences.

**Comment by Dytek** [comment]
I can help translate it into Dutch.

**Comment by REY29** [comment]
i can help translate  in to Ukrainian

**Comment by ricardo-franco** [comment]
I can help with the portuguese translate.

**Comment by t3m1X** [comment]
I could and would like to help translate to Catalan, it's not on the list yet, but I'd be willing to start the translation.

**Comment by YanSilveira** [comment]
I would like to help translate to Portuguese Brazil

**Comment by kkwebworld** [comment]
hindi translation done... waiting for approval

**Comment by snakelord757** [comment]
Hi,I can help with translation for Russian language

**Comment by ghost** [comment]
Hi I can help with Tamil language

**Comment by franco98silva** [comment]
Hi! I will help with the Spanish translation. Will there be a translation into Latin American Spanish? I can also help with that!
In the current translations of the app to Spanish there are many misspellings and I was helping to correct them.

**Comment by Lyooox** [comment]
I can help with the spanish  😁

**Comment by hugwalk** [comment]
I can help the Chinese(Taiwan) translate! Will start it soon.

**Comment by ghost** [comment]
@deletescape What if the most voted translation is wrong or insufficient? Why are there no proofreaders? (I would apply for German here)

**Comment by iamprompt** [comment]
I can help with Thai

**Comment by nyancrimew** [comment]
@edisso10018 You can report incorrect translations and I will look into them. We already have 3 proofreaders for german (including me)

**Comment by maxsundellold** [comment]
I can help with Swedish

**Comment by Juleo97** [comment]
If needed I can help with french!

**Comment by Nek12** [comment]
Belarussian and russian from me

**Comment by eggsgent** [comment]
Norwegian nb-NO translation completed, old translations reviewed and edited (new suggestions added).

**Comment by bohrabhijeet** [comment]
@eggsgent Alright, thanks

**Comment by eggsgent** [comment]
Hi again, I just updated to version 1.2.0.1878 from Google Play and the app language is set to English although system language is nb-NO.

The Norwegian translation (app strings) was fully translated on May 21st I think, then the additional 45 new strings added 4 days ago were also translated. Could it be that the Norwegian translations are not used by Android because of the locale code? "values-no", while Norwegian locale for Android is nb-NO. The alpha build (Lawnchair-v2-alpha_134.apk) is also presented in English when device language is set to Norwegian. 

https://github.com/LawnchairLauncher/Lawnchair/blob/4548b004353d901b8e660f842859a10ddcd8b663/app/src/main/res/values-no/strings.xml

**Comment by divadsn** [comment]
@eggsgent hmm, thanks for letting us know, I will try to see what language code is given instead.

**Comment by CryoTheRenegade** [comment]
Just wondering, what languages still need to be added?

**Comment by bohrabhijeet** [comment]
@CryoRenegade Check our crowdin project

**Comment by CryoTheRenegade** [comment]
Thanks

**Comment by eggsgent** [comment]
@divadsn Did you find the root cause? It would be nice to see the translation live in a functional app (preferably officially released), to verify that they look good in a product. Thanks for looking into it.

**Comment by KasraIDK** [comment]
I can help with Persian translation.

**Comment by rimasx** [comment]
Hi. I could translate to estonian.

**Comment by maturabg** [comment]
Would like to translate to Bulgarian

**Comment by zackbyte-dev** [comment]
I can help to translate in Spanish

**Comment by bohrabhijeet** [comment]
@GaboZac61 Yes you can. You just need to have a crowdin account for that. 👍🏻

**Comment by fonix232** [comment]
Guys, if anyone makes another "I can translate to X" comment, I'm gonna close the discussion on the ticket... Stop talking and go to Crowdin for translation, it's much more appreciated!

**Comment by rimasx** [comment]
There is no estonian language for Lawnchair on Crowdin.

**Comment by fonix232** [comment]
@rimasx I've added Estonian, feel free to start translating!
