### ISSUE TITLE
[Bug] Unable to swipe up for app drawer via Quickstep when dock is hidden

### ISSUE THREAD

**Issue by squabbi** [Deletescape-Media/Lawnchair#1752]
Steps to reproduce:

1. Hide dock.
1. Open any app.
1. Swipe up for Quickstep.
1. Then swiping again will not pull up app drawer.

Could it be possible that AOSiP's Quickstep is old and causing this?

Lawnchair v2.2399
AOSiP 9

**Comment by skittles9823** [comment]
@squabbi Is Lawnchair the recents provider? If so it's got nothing to do with launcher3.

However if Lawnchair is the recents provider this isn't a bug. On the Pie base you need the dock to swipe up to recents, you should be able to swipe up on the navbar though.

Once the Q rebase is public however, you can swipe up and hold anywhere on the home screen to open recents so this won't be an issue anymore.
