### ISSUE TITLE
At a glance widget font is smaller on Wednesday

### ISSUE THREAD

**Issue by darkwolzarD** [Deletescape-Media/Lawnchair#1753]
Not sure if it is intended but at a glance widget font is smaller only on Wednesday, preview image shows correct size.

Device: Samsung Galaxy S10e
Android version: 9.0.0
Launcher version: 2.0-2408

![Screenshot_20190918-090652_Lawnchair](https://user-images.githubusercontent.com/10445143/65102083-3f5fc780-d9f4-11e9-91e3-82efe6ec2ef6.jpg)
![Screenshot_20190921-090719_Lawnchair](https://user-images.githubusercontent.com/10445143/65102084-3f5fc780-d9f4-11e9-981e-aa8e9a0e098a.jpg)

**Comment by suphon-t** [comment]
That's normal. Automatic text sizing is implemented to ensure the widget looks good with additional space on the left and right side.
