### ISSUE TITLE
[Feature Request] Allow search auto complete results to replace the text in the search input.

### ISSUE THREAD

**Issue by h77ps** [Deletescape-Media/Lawnchair#1764]
## Description

This is not a bug, but a feature request. When using search it would be nice to be able to click somewhere on one of the search autocomplete list items and have that item replace the text in the search box. This would make searching using multiple words far less painful. 

## Expected Behavior

Here is an example. Say you want to search for "Maryland Renaissance Festival Hours". As you start typing "Mary..." you get a list of autocomplete result mostly for the word "maryland". Instead of clicking on the auto complete item to search for the word it would be nice to have a button to click and insert the autocomplete list item in the search input field so that I can continue typing the rest of the search string. Or maybe this could be a setting that can change the default behavior of the autocomplete list item click.

Very often I would end up typing something like "Maryland Ren....", the first result would be "Maryland Renaissance Festival". I would click that and a search will be performed in my prefered search engine, then I would edit the search field in that search engine to add stuff like "Hours". Since this would be faster than having to type in the whole search string of "Maryland Renaissance Festival Hours". 

## Actual Behavior

If you click on an autocomplete list item it searches for that item immediately without allowing you to add additional search terms.

## Steps to Reproduce

1. Use the search on any multi word search string.
2. Pick any of the autocomplete search list items.
3. You'll immediately perform a search even if you want to add additional terms.

## Environment

* Device: Pixel 2
* Android version: 10
* Launcher version: 2.0-2408
* Rom: stock

**Comment by RikKoedoot** [comment]
you were talking about the google search right? if so, we are not the ones in control of that
