### ISSUE TITLE
[Feature Request] Option to disable shadow in Home Widget

### ISSUE THREAD

**Issue by shrirambalaji** [Deletescape-Media/Lawnchair#1765]
Hello! :wave:

Thanks for this amazing project! It'd be great to have an option to disable the shadow in the Home widget if possible.

![image](https://user-images.githubusercontent.com/11358903/66250329-df408380-e75e-11e9-96a2-c46df5557c99.png)

**Comment by LuminarySage** [comment]
I'm pretty sure TextView either comes with shadow or doesn't and it can't be changed by simply switching a value
