### ISSUE TITLE
[Feature Request] Could you please make a transition animation for Apps exit and back to launcher

### ISSUE THREAD

**Issue by xiawenke** [Deletescape-Media/Lawnchair#1772]
## Description & Expected Behavior

Some Android UI now already have a transition animation while returning to launcher: the screenshot of App become smaller and smaller, and finally disappear, then back to launcher.

I just considering if the Lawnchair could have an transition animation that icon of the App move back to where it displayed on the launcher follow by the Android UI's animation.

## Actual Behavior

Only transition animation of Android UI gas been shown while returning to the launcher.

**Comment by skittles9823** [comment]
@xiawenke Good exit animations aren't exactly doable with the animation API as restricted as it is. Only way to get good animations is to be a privileged app (QuickSwitch grants these permissions to the recents provider btw) but other then that the only animation that has an exit animation is blink as it's pretty simple and works well for both opening and closing apps.
