### ISSUE TITLE
App drawer remains open when launching app, quickly closes on home swipe

### ISSUE THREAD

**Issue by lunim** [Deletescape-Media/Lawnchair#1774]
## Description
When launching an app from the drawer, then returning home, the app drawer is still expanded, but closes quickly.

## Expected Behavior
When returning home, app drawer should not be visible.

## Actual Behavior
App drawer briefly visible, then animates close

## Steps to Reproduce
1. Open app drawer
2. Launch app
3. Press home button or use home gesture

Video: https://imgur.com/a/g6ODSth

## Environment
* Device: OnePlus 7 Pro and Galaxy Tab S2
* Android version: Oxygen OS 10.0.1 and Android 7
* Launcher version: 2.0-2497

**Comment by suphon-t** [comment]
This is due to how OnePlus implemented the gestures. It can't be fixed on our side.

**Comment by lunim** [comment]
@paphonb It also happens on my Galaxy Tab S2

**Comment by lunim** [comment]
@paphonb I've also tried a few other launchers, they don't have this issue.
