### ISSUE TITLE
Restarts on Unlock

### ISSUE THREAD

**Issue by WajahatAliAbid** [Deletescape-Media/Lawnchair#1776]
Lawnchair keeps restarting each time I unlock the screen. I'm running the latest beta (October 12 update) currently but it has been doing this in last update as well. I'm using Huawei Y9 with Android 9. I tried resetting it but it didn't work. Can you help diagnose this?

**Comment by suphon-t** [comment]
The issue template is there for you to fill. Please include more details such as logs or screen recordings.

**Comment by suphon-t** [comment]
Closing as no further information was given.
