### ISSUE TITLE
App drawer doesn't close when launching app

### ISSUE THREAD

**Issue by lunim** [Deletescape-Media/Lawnchair#1783]
## Description
When launching an app from the drawer, then returning home, the app drawer is still expanded, but closes quickly.

## Expected Behavior
When returning home, app drawer should not be visible.

## Actual Behavior
App drawer briefly visible, then animates close

## Steps to Reproduce
1. Open app drawer
2. Launch app
3. Press home button

## Environment
* Device: Galaxy Tab S2
* Android version: Android 7
* Launcher version: 2.0-2497

**Comment by AlexFL1188** [comment]
Bumping this issue as I have noticed this as well with my OnePlus 6T with Android 10 app version 2.0-2581. it's not related to gestures either. Even with on screen buttons it does it as well.

**Comment by Noxis73** [comment]
Same issue here with latest v.2581. Not having this behavior with pre-alpha version 2546.

edit: same behavior when I start an app from home screen and app drawer.

Device: OnePlus6, latest OmniRom 10.

**Comment by AlexFL1188** [comment]
Also to note that if you change the "App launch transition" to "blink" it seems the issue goes away or gets less noticable, at least for me.

**Comment by lunim** [comment]
@AlexFL1188 Thanks for the tip, it seems to help with my devices too.  Not my favorite animation, though.

**Comment by zlshames** [comment]
This still happens on the latest version. Quite annoying actually. Is this a fixable issue?

**Comment by suphon-t** [comment]
Fixed with 4b9ce87
