### ISSUE TITLE
Home widget not showing information

### ISSUE THREAD

**Issue by AvinashK13** [Deletescape-Media/Lawnchair#1785]
Hi,
Device:- Oneplus 7t

Issue:-
Home widget not showing information
Tried restarting the lawnchair, but still getting this.
Sorry don't know how to provide logs for this issue.

![Screenshot_20191019-172728](https://user-images.githubusercontent.com/35093918/67144655-66661f00-f268-11e9-81b2-af2c682d4dcb.jpg)

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
Remove “debug” from your event providers.
