### ISSUE TITLE
Hide apps in the "Manage apps" view under Categorization

### ISSUE THREAD

**Issue by CorePoint** [Deletescape-Media/Lawnchair#1787]
Hey, it would be nice if apps that are already in a Folder could be hidden from the list under "Manage Apps". 
When you try go put a great number of apps into folders it's pretty hard to do because the list still shows the apps that are already in folder.
As an alternative the apps that are already in a folder could be dropped to the bottom in a separated list for the case a user wants to put an app into multiple folders.

Thank you for your work!

**Comment by mindrunner** [comment]
Yeah, just spent an hour to organize my apps. +1 fir hiding already categorized as well as already hidden apps.

**Comment by ghost** [comment]
I would also like to see this, but as an sort option. Example of possible sort options:
- Hide/Show apps in other tabs
- Hide/Show hidden apps
