### ISSUE TITLE
[Bug] F-Droid says "This app is no longer maintained"

### ISSUE THREAD

**Issue by orangemango** [Deletescape-Media/Lawnchair#1788]
## Description

On F-Droid the app is tagged as "no longer maintened".
> NOTE: This app is no longer maintained, its repo was archived.

https://f-droid.org/en/packages/ch.deletescape.lawnchair.plah/

**Comment by suphon-t** [comment]
V1 is no longer in development anymore and F-Droid's policy makes it impossible to publish V2 on F-Droid.

**Comment by rugk** [comment]
What is the problem with v2? Is not it completely FLOSS?

**Comment by rugk** [comment]
Ah oaky just found https://github.com/LawnchairLauncher/Lawnchair/issues/1473
