### ISSUE TITLE
[Feature Request] Home button opens search

### ISSUE THREAD

**Issue by orangemango** [Deletescape-Media/Lawnchair#1789]
It would be awesome to be able to use the Home button to open the searchbox (and open the keyboard) !

And thank you for this good looking and trustworthy app :)

**Comment by LuminarySage** [comment]
Please just look around for a little bit before you post a feature request.
Settings -> Gestures -> Home Button

![Screenshot_20191108-003123](https://user-images.githubusercontent.com/24306400/68452045-3226b400-01bf-11ea-978b-7290368d8407.jpg)
