### ISSUE TITLE
[build] assembleAospLawnchairDev build break

### ISSUE THREAD

**Issue by junwei-ren** [Deletescape-Media/Lawnchair#1790]
## Description
When I want to build .assembleAospLawnchairDev it failed.  But build assembleQuickStepLawnchairDev is OK.

## Actual Behavior
Build break.  Error log:

> Task :compileAospLawnchairDevDebugKotlin
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairApp.kt: (41, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairApp.kt: (193, 50): Unresolved reference: RecentsActivity
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (36, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (37, 20): Unresolved reference: systemui
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (38, 20): Unresolved reference: systemui
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (41, 68): Unresolved reference: TaskKeyLruCache
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (43, 9): Unresolved reference: NormalizedIconLoader
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (48, 5): 'createNewIconForTask' overrides nothing
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (48, 48): Unresolved reference: Task
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (54, 26): Unresolved reference: mContext
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (57, 24): Unresolved reference: createBadgedDrawable
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (69, 9): Unresolved reference: getAndUpdateActivityInfo
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (69, 50): Cannot infer a type for this parameter. Please specify it explicitly.
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (72, 21): 'return' is not allowed here
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (76, 22): Unresolved reference: createNewIconForTask
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (80, 16): Unresolved reference: createBadgedDrawable
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (80, 76): Unresolved reference: mContext
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (85, 26): Unresolved reference: getBitmapInfo
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (87, 16): Unresolved reference: mDrawableFactory
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (59, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (210, 67): Unresolved reference: LauncherRecentsView
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (324, 28): Unresolved reference: getDefaultSwipeHeight
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairOverviewCallbacks.kt: (24, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairOverviewCallbacks.kt: (28, 66): Unresolved reference: OverviewCallbacks
...

## Steps to Reproduce
Pull the code and type command below to build

./gradlew assembleAospLawnchairDev

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairApp.kt: (41, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairApp.kt: (193, 50): Unresolved reference: RecentsActivity
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (36, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (37, 20): Unresolved reference: systemui
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (38, 20): Unresolved reference: systemui
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (41, 68): Unresolved reference: TaskKeyLruCache
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (43, 9): Unresolved reference: NormalizedIconLoader
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (48, 5): 'createNewIconForTask' overrides nothing
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (48, 48): Unresolved reference: Task
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (54, 26): Unresolved reference: mContext
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (57, 24): Unresolved reference: createBadgedDrawable
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (69, 9): Unresolved reference: getAndUpdateActivityInfo
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (69, 50): Cannot infer a type for this parameter. Please specify it explicitly.
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (72, 21): 'return' is not allowed here
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (76, 22): Unresolved reference: createNewIconForTask
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (80, 16): Unresolved reference: createBadgedDrawable
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (80, 76): Unresolved reference: mContext
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (85, 26): Unresolved reference: getBitmapInfo
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairIconLoader.kt: (87, 16): Unresolved reference: mDrawableFactory
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (59, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (210, 67): Unresolved reference: LauncherRecentsView
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairLauncher.kt: (324, 28): Unresolved reference: getDefaultSwipeHeight
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairOverviewCallbacks.kt: (24, 20): Unresolved reference: quickstep
Lawnchair/lawnchair/src/ch/deletescape/lawnchair/LawnchairOverviewCallbacks.kt: (28, 66): Unresolved reference: OverviewCallbacks
```

**Comment by suphon-t** [comment]
That’s expected. We don’t support building the non-quickstep variant.
