### ISSUE TITLE
Folders in Dock

### ISSUE THREAD

**Issue by mindrunner** [Deletescape-Media/Lawnchair#1793]
## Description
I am able to create folders in the dock by moving app icons over each other. Also, I have all my apps in the drawer organized in folders. But I am not able to move/copy those folders to the dock.

## Expected Behavior
Can move folder to dock like an app.

## Actual Behavior
Folder does not move at all.

## Steps to Reproduce

1. create folders in launcher settings
2. try to move folder to dock

## Environment

* Device: Oneplus 5
* Android version: 9
* Launcher version: 2.0-2500-ci-alpha
* Rom: OxygenOS 9.0.9

**Comment by MKoen** [comment]
Fully agree! Created an issue related to this. [Issue](https://github.com/LawnchairLauncher/Lawnchair/issues/1817)

**Comment by mindrunner** [comment]
Why do we need another issue for this?

**Comment by MKoen** [comment]
> Why do we need another issue for this?

Your issue only refers to moving folders to a dock; mine is about moving folders to the home screen.
I don't want the devs to only apply it for the dock.

**Comment by mindrunner** [comment]
Ok, got it. Should be treated the same in my opinion. But this bugtracker seems pretty dead anyways. Haven't gotten any response from devs here yet.

**Comment by MKoen** [comment]
Thought making an extra (related) issue would draw there attention - but seems not to. Looks pretty deas here.

**Comment by theLittleBigZ** [comment]
Has this feature been implemented?
