### ISSUE TITLE
YouTube PIP (YouTube premium) mode doesn't work properly

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1799]
## Description
YouTube PIP (YouTube premium) mode doesn't work properly when lawnchair  is running as default launcher. So when you are watching a YouTube video and you go home or recents apps, audio keep playing but video PIP (or playing notification) are hidden. On this scenario, video comes to front when keyboard shows up or (sometimes) when you touch down right corner of device screen.

## Expected Behavior
Video should keep playing on PIP mode.

## Actual Behavior
Missing PIP mode strange behavior.

## Steps to Reproduce
Play a video on YouTube app with premium account and go to home

1. You need YouTube premium account or enable YouTube PIP mode somehow.
2. Open YouTube app
3. Play a video
4. Go home or recents  app

## Environment

* Device: Oneplus  6T
* Android version: 10.0
* Launcher version: 2.0-2506
* Rom: OOS 10.0

**Comment by divadsn** [comment]
@estapagu That's a general issue with any quickstep provider, a workaround is to press home and then open recents

**Comment by ghost** [comment]
> @estapagu That's a general issue with any quickstep provider, a workaround is to press home and then open recents

When you press home youtube PIP doesn't work, video is missing. So if you press home and then open recents, behavior is the same, PIP missing.
