### ISSUE TITLE
App shortcut bubble text is blurry

### ISSUE THREAD

**Issue by ankurk91** [Deletescape-Media/Lawnchair#180]
Hi, 
First thanks for your awesome work.
I have installed **Lawnchair-255.apk** on my Moto g4 play (Android 6.0.1) and it works fine. 
However, i have some feedbacks.

Take a look at these screenshots.
#### Blurry text (current)
![blur-text](https://user-images.githubusercontent.com/6111524/28064713-55a07e66-6653-11e7-9e19-92e8f8c50b00.png)

#### Sharp text (expected)
![should-be-like-this](https://user-images.githubusercontent.com/6111524/28064718-5c4d44ec-6653-11e7-9a2b-5e271c9312f6.png)

As you can see currently the app shortcut bubble text has too much [text shadow](https://www.w3schools.com/cssref/css3_pr_text-shadow.asp).

Was it intentional? Or maybe I am only who see this as an issue.
Thanks.

**Comment by nyancrimew** [comment]
Fixed already, but not yet released on stable channel
