### ISSUE TITLE
Question: Is Lawnchair v2 Still in Alpha?

### ISSUE THREAD

**Issue by 0pLuS0** [Deletescape-Media/Lawnchair#1802]
Hello,

I was looking over the site https://lawnchair.app/ and saw that on APKMirror only Alpha releases, but on this URL there is a beta listed;

https://www.apkmirror.com/apk/deletescape/lawnchair/lawnchair-2-0-328-ci-beta-release/

I'm assuming this Beta is a fake?

THANKS

**Comment by DanGLVK** [comment]
@0pLuS0 build 328 was incorrectly mislabeled as a beta

**Comment by 0pLuS0** [comment]
@DanGLES3 ok...

Can we please get the APK for download here on the Github Repo?

Also, there's no update ability built in? So what's the best way to update?

THANKS

```P.S. Can v2 go on F-Droid too?```

**Comment by divadsn** [comment]
Play Store version has v2 beta version, you can stick to that if you want automatic updates:
https://lawnchair.app/getbeta

**Comment by 0pLuS0** [comment]
I use microG, so I don't use Google, and then I use F-Droid, but if I want to get apps from the PlayStore I use AuroaStore.

So I looked online at the PlayStore and all I see is v1 not v2;

https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah

```P.S. I don't know if there's something to F-Droid in regards to developmental software in a alpha, or beta stage, but it sure would be nice to get v2 on F-Droid, since v1 is...```

**Comment by DanGLVK** [comment]
@0pLuS0 join the beta channel, V2 is currently published as a beta of V1

**Comment by 0pLuS0** [comment]
I don't use Google, Gmail, etc., as I mentioned I use F-Droid...

BUT if for some reason I might want an app that's from the PlayStore I'll use AuroaStore.

I thought to join I need to signup through Gmail?

```P.S. We shouldn't have to join anything, that's part of the reason a Repo like Github exists, to get what we need here...```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Play Store version has v2 beta version, you can stick to that if you want automatic updates:
> https://lawnchair.app/getbeta

Two years no updates.

**Comment by RikKoedoot** [comment]
We have been updating at t.me/lawnchairci, and you can also check GitHub releases
