### ISSUE TITLE
Crash when opening App list on latest beta

### ISSUE THREAD

**Issue by Wyall** [Deletescape-Media/Lawnchair#1811]
## Description

After newest update, when I swipe up to open the app list, lawnchair crashes and says alpha has to be between 0 and 255. Only happened after update

## Expected Behavior

App list should open, no crash

## Actual Behavior

Crashes

## Steps to Reproduce

Swipe up to open app list, crash. Don't know the reason this is suddenly happening after the update.

## Environment
https://del.dog/ugopebetig

**Comment by nyancrimew** [comment]
@Wyall We're working on this, thanks for the log

**Comment by nyancrimew** [comment]
@Wyall This has been fixed now and a new build should start rolling out soon

**Comment by Wyall** [comment]
@deletescape Just got it, works again. Thanks!
