### ISSUE TITLE
Crashes constantly

### ISSUE THREAD

**Issue by ChristosBouronikos** [Deletescape-Media/Lawnchair#1812]
Crash report here.
https://del.dog/arutojowuy

**Comment by nyancrimew** [comment]
@1chriis1 An update with a fix for this should be available on the playstore

**Comment by ChristosBouronikos** [comment]
OK this might be the best customer experience ever! 
Thanks a lot, it's fine now. Sorry about that.
Also super quick reply.  Hats off to you sir!
