### ISSUE TITLE
[Feature Request] Be able to drag&drop app drawer folders to home screen

### ISSUE THREAD

**Issue by MKoen** [Deletescape-Media/Lawnchair#1817]
## Description
Being able to drag and drop categorised folders feom the app drawer to the home screen. And kinda synchronise the droppef folder on the home screen when you add apps to that category/folder.

## Expected Behavior
Drag and drop folder from app drawer to home screen. And synchronise those folders on the home screen.

## Actual Behavior
"Holding" a folder in the app drawer doesn't do anything.

## Steps to Reproduce
Try holding a folder in the app drawer.

## Environment

* Device: Samsung Galaxy S8
* Android version: 9
* Launcher version: 2.0
* Rom: ONE UI 1.0

**Comment by ghost** [comment]
So basically instead of being a copy of the folder, it's a shortcut to the folder. Drag new app into the desktop folder, the main categorized folder is too?

**Comment by MKoen** [comment]
> So basically instead of being a copy of the folder, it's a shortcut to the folder. Drag new app into the desktop folder, the main categorized folder is too?

Exactly!
