### ISSUE TITLE
Squirle icons

### ISSUE THREAD

**Issue by TheOkayMan** [Deletescape-Media/Lawnchair#182]
After using the 'use pixel icon's I get squirle icons, instead of round icons. http://i.imgur.com/EbWPufN.jpg Nexus 5x Android O DP3

**Comment by fonix232** [comment]
Just a slight correction, that's a rounded rectangle. A squircle is a shape between a circle and a square. See attached.
![image](https://user-images.githubusercontent.com/371847/28071489-62269448-6650-11e7-893c-427546752590.png)
![image](https://user-images.githubusercontent.com/371847/28071529-7cfde5a0-6650-11e7-96bc-2ee6c354aac6.png)

**Comment by ghost** [comment]
I think in android o Google apps have 2 variants of icons, circle for pixel phones and rounded square for nexus phones. So the launcher uses the icons designed for nexus. I have them rounded square as well (not all, but this is for Google to fix)
