### ISSUE TITLE
[Feature request] Add (manual) sort options in app drawer

### ISSUE THREAD

**Issue by tylla** [Deletescape-Media/Lawnchair#1820]
## Description
Currently the App drawer lists the apps in alphabetical order which is OK with a few apps, but more-and-more problematic above a certain number of apps.
A feature should be included for the user to allow manually reordering the apps and potentially move between tabs/folders.

Related issues:
#1241 - I suppose this was still for the 1.x version, hence closed.

## Expected Behavior
When tap-and-holding an app in the App drawer, one should be able to reposition the app relative to other apps, maybe be able to move the app to other tab as well.
This could use exactly the same mechanics as on the Home screen (maybe even enabling the Folders behavior). The current "add to home/desktop/dock screen" feature could be solved by leaving a small gap on the lower part of the drawer (while dragging an app icon) with a "Home/Desktop" label which would show the Desktop if icon was placed over it for a small interval.

## Actual Behavior
When tap-and-holding an app in the App drawer, the pop-up menu displays and the moment the user tries to drag the app icon, the App drawer is closed and the user is only able to place the app icon on the desktop/dock.

## Steps to Reproduce
1. Open App drawer
2. Tap-and-hold on any app icon
3. After the pop-up menu opens drag the app icon
4. The App drawer closes immediately, leaving only the Desktop and Dock as drop targets.

## Environment
* Device: Unihertz Atom "Atom"
* Android version: 9
* Launcher version: 2.0.2500
* Rom: Unihertz_Atom_20190826

**Comment by tylla** [comment]
This is still an issue.

**Comment by tylla** [comment]
As was mentioned in #2777 it could be brought together with the other sort options, which would make sense.

**Comment by page200** [comment]
Please reopen the issue.

By the way, after the user has manually reordered apps in the drawer, newly installed apps can/should appear at the end of the list. That way, users can easily find and test recently installed apps without having to remember all their names.
