### ISSUE TITLE
Crash when accessing to grid size settings 

### ISSUE THREAD

**Issue by mrxx0** [Deletescape-Media/Lawnchair#1829]
I was accessing to the launcher settings and when I click on grid size the launcher simply crashed.

Lawnchair version 2.0-2546
OnePlus 7 Pro on Oxygen OS 10.0.1

Here is the crash log :
 

 https://del.dog/mececetege

**Comment by CritLoren** [comment]
Same. Using the alpha Q build. This and occasional crashes from using the new recents is what's currently making this unstable for me.

**Comment by DanGLVK** [comment]
Disable blur

**Comment by suphon-t** [comment]
Fixed in new build
