### ISSUE TITLE
Icon's titles

### ISSUE THREAD

**Issue by lababiba** [Deletescape-Media/Lawnchair#183]
Icon's titles in app drawer are different colors (black and white)
![Titles](http://i.imgur.com/Ua5IwmC.jpg)

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
This is fixed after a restart of the Launcher (Settings > Debug > Restart Lawnchair) but it is definetly a bug

**Comment by suphon-t** [comment]
Fixed
