### ISSUE TITLE
Unchanged icon shape option is gone, please bring it back

### ISSUE THREAD

**Issue by hzulla** [Deletescape-Media/Lawnchair#1839]
Hi,

thanks for the major upgrade and congratulations!

The old lawnchair used to have an icon shape option "None" (or was it "unchanged"? I don't recall the exact wording). With it, the icons would be just the way the app developers stored them in the app binary.

The new lawnchair is missing that option. There are multiple possible shapes, but lawnchair now forces each icon to adapt to these shapes. I find that unpleasing, as some icons look bad when forced to fit in an icon shape.

Please bring back the "None" shape option.

Thank you so much.

**Comment by nyancrimew** [comment]
@hzulla This actually exists in a newer version of Lawnchair which is currently still in a testing phase, it will reach the Play Store as soon as possible

**Comment by hzulla** [comment]
Wonderful, thank you so much!

**Comment by hzulla** [comment]
@deletescape is there any progress on this issue? It still doesn't work as expected with the current version of Lawnchair. Thanks so much!

**Comment by SuperDragonXD** [comment]
*Really late* reply to this issue, but in the latest versions (Lawnchair 11 Alpha 1+), it already exists in the form of "Auto Adaptive Icons". Disable this in General > Auto Adaptive Icons to do your requested feature. Closing this issue due to it being added.

**Comment by hzulla** [comment]
Thank you!
