### ISSUE TITLE
[Feature Request] Auto Sorting of Icons in Folders

### ISSUE THREAD

**Issue by beyertom** [Deletescape-Media/Lawnchair#1842]
## Description
Add a option to sort the icons/shortcuts in a folder on the homescreen by alphabet automatically

## Expected Behavior
In the settings of a folder on the homescreen (the menu where you can change the name or the icon of a folder) add following:
Option if the content of the folder should get automatically sorted by alphabet or if the user wants to sort the icons manually

## Actual Behavior
When adding a new icon to a folder it gets added at the end; you have to change the order manually.

**Comment by timjosten** [comment]
I miss this feature too. But I see it in an easier way to implement. Just add a menu to a folder with "Sort" menu item. When you click it, folder gets sorted alphabetically.
