### ISSUE TITLE
[FR] Allow Smart Folders on desktop

### ISSUE THREAD

**Issue by zilexa** [Deletescape-Media/Lawnchair#1848]
Smart Folder feature would allow a user to select his favourite app of a folder on the desktop that will be opened when the folder is touched. Swiping up on that folder would simply open the folder. 
The smart folder should show the selected favourite app icon with some indication that a folder is behind it.

**Comment by EbonJaeger** [comment]
Having the default press action on a folder open an app and not the folder seems like very unintuitive behavior. I could see if it swiping on it opened the app, though.

**Comment by thewithz** [comment]
@EbonJaeger That's how the smart folders work when in the dock. It's actually super helpful once you get used to it.

**Comment by zilexa** [comment]
@thewithz 
I switched from Lawnchair to Microsoft Launcher, it is basically the same but with all the most useful features that never made it into Lawnchair: Smart folder, 2 page dock, default homescreen selection and even a microgrid for widgets, so that you can easily put your widgets precisely on the screen, instead of adhering to your icon grid. 
Just do not opt-in to any of their features that require an account or internet connection, do not give it permissions to address book when it asks for it. It will work perfectly, without sharing your data or using the cloud for 'smart' features. 
The result is the most clean Android Launcher that stays very close to the regular launcher, without all google shizzle on your screen.

**Comment by nwithers-ecr** [comment]
@zilexa good to know, thank you. I've switched to KLWP and KWGT and just made it myself
