### ISSUE TITLE
Incorrect restore from Q pre-alpha version to non Q version (eg. Play Store version)

### ISSUE THREAD

**Issue by serovar** [Deletescape-Media/Lawnchair#1850]
## Description
If I restore a backup taken on the Q pre-alpha version (q_pre_alpha-2546) on the non Q version (Play Store 2.0-2581), the backup is not restored correctly.

## Expected Behavior
The backup can be restored correctly.

## Actual Behavior
It can't.

## Steps to Reproduce
1. Take a backup on the Q pre-alpha version.
2. Restore it on the non Q version.  

![Screenshot_20191203-140223](https://user-images.githubusercontent.com/6732420/70053417-519dda80-15cd-11ea-9f4b-62000f969e93.png)
![Screenshot_20191203-140247](https://user-images.githubusercontent.com/6732420/70053418-519dda80-15cd-11ea-9ac8-9821deff4497.png)

## Environment
* Device: Pixel 2 XL
* Android version: 10
* Launcher version: q_pre_alpha-2546, 2.0-2581
* Rom: Stock

**Comment by DanGLVK** [comment]
It's a known issue, due to their different codebases Q build backups will not work correctly on non Q builds.

**Comment by suphon-t** [comment]
The database structure is changed in the Q version. Restoring a backup from the Q version is basically downgrading the database and we don’t support that.
