### ISSUE TITLE
[FR] Dock in overview (recent apps) with Android 10 gesture navigation

### ISSUE THREAD

**Issue by nickpwhite** [Deletescape-Media/Lawnchair#1856]
## Description
In stock Pixel Launcher, the overview (recent apps menu) shows the dock at the bottom with the ability to swipe up to open the app drawer. It would be nice to have this feature in Lawnchair. This is with Android 10 gesture navigation enabled (with the December update to enable this feature in 3rd party launchers).

## Expected Behavior
![pixel_launcher_overview](https://user-images.githubusercontent.com/8175555/70100958-4dcb8180-15e8-11ea-8261-ebe842200f61.png)

## Actual Behavior
![lawnchair_overview](https://user-images.githubusercontent.com/8175555/70100963-51f79f00-15e8-11ea-8992-6f618b2c9358.png)

## Steps to Reproduce
1. Enable new gesture navigation
2. Open overview by swiping up from the bottom of the screen and holding

## Environment
* Device: Pixel 3 "blueline"
* Android version: 10
* Security patch level: December 5, 2019
* Launcher version: 2.0-2581 
* Rom: Stock

**Comment by DanGLVK** [comment]
Not possible, Lawnchair has no control over the recents panel, that's entirely handled by the Pixel launcher,  the pixel launcher is the one deciding to hide the dock, we can't change that (unless you're rooted)

**Comment by nickpwhite** [comment]
Thanks for the quick response, much appreciated!

**Comment by skittles9823** [comment]
@nickpwhite Yea you need to use QuickSwitch for that functionality.
