### ISSUE TITLE
App drawer close animation everytime I clear recent apps

### ISSUE THREAD

**Issue by SlowNicoFish** [Deletescape-Media/Lawnchair#1858]
## Description

I experience this issue when i close all my recent apps and currently have the appdrawer open.
This issue is considered a bug because i think the animation looks out of place.
The animation is not visible when only pressing the "home" button.

## Expected Behavior

The screen should show the desktop without the animation

## Actual Behavior

The appdrawer makes a closing animation after closing recent apps.

## Steps to Reproduce

https://gfycat.com/tanordinarygreendarnerdragonfly
1. Open appdrawer
2. Open an app
3. Go to recent apps  and clear all
4. The app drawer will make an animation which I think is a bug

## Environment

* Device: Pixel 3 XL stock rom
* Android version:  10 November patch
* Launcher version: 2.0-2589 (Play store)
* Rom: stock

**Comment by kmaraz** [comment]
The same on Android 10 (OxygenOS 10.0.1) for OnePlus 6T.

**Comment by divadsn** [comment]
@kmaraz That must be funny when you have a lot of apps open /s

**Comment by SlowNicoFish** [comment]
Yeah. This and the ability to hide the scrollbar in the app drawer is my only stopping me from using lawnchair over nova. As soon as they are fixed I'm over to lawnchair in a second

**Comment by kmaraz** [comment]
I would add, that my case is maybe a little bit different:
1. swipe up to open drawer
2. open an app
3. move app to the background by swiping up
4. app will fade with an animation as expected, but when animation is finished: there is an closing drawer animation. it should not be there
note: if you open app from main desktop screen, there is only one animation, which is correct behavior
