### ISSUE TITLE
Search bar widget top cut off sometimes

### ISSUE THREAD

**Issue by aswild** [Deletescape-Media/Lawnchair#1860]
## Description
When I set up the home screen to have 6 rows (instead of the default 5) and use the new Lawnchair search bar widget, the top of the widget is cut off. It functions, but doesn't look great. The issue isn't seen if I use the default number of 5 rows.

## Expected Behavior
Search bar should be displayed normally.

## Actual Behavior
Top of search bar is chopped off if widget is 1 row tall. Widget is misaligned in the resizing bounding box. See screenshots below (from Pixel 3 AVD in emulator)

![image](https://user-images.githubusercontent.com/11742669/70211643-99bf1900-1703-11ea-99ba-8219cc4cac1a.png)

![image](https://user-images.githubusercontent.com/11742669/70211729-cd9a3e80-1703-11ea-8100-6d4e51bd40b2.png)

## Steps to Reproduce
1. Change default 5x5 (rows x cols) desktop to 6x5
2. Add the 1x5 Lawnchair Search Box widget
3. Resizing the widget to 2 rows fixes the cropping (but then it consumes 2 rows of my home screen)

## Environment
* Device: Pixel 3
* Android version: 10
* Launcher version: 2.0-2589, and also latest commit 0b71dc40
* Rom: Stock ROM, Nov 2019 update
* Same behavior in the Android emulator (Pixel 3 AVD with Q Google APIs image)

**Comment by aswild** [comment]
I was playing around with this and I think the issue is related to how `minBottom` is set in HotseatQsbWidget.getBottomMargin() (https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/src/com/google/android/apps/nexuslauncher/qsb/HotseatQsbWidget.java#L337)

The `profile.getInsets()` margin is bypassed when coming up with `rect` when `widgetMode` is true, but it isn't bypassed when computing `minBottom`. If I change these variables around, I can get it to center correctly for my device resolution, but I don't know enough about all these layout things to come up with a proper fix that would work across devices.

(P.S. thanks a ton for making Lawnchair easy to build "out of the box" without any crazy dependencies or manual steps, it's much nicer than other apps I've hacked on)

**Comment by SuperDragonXD** [comment]
Closing this issue since this is related to Lawnchair V2, and we don't support it anymore.
