### ISSUE TITLE
Transparent dock in recents?

### ISSUE THREAD

**Issue by calbruc** [Deletescape-Media/Lawnchair#1861]
I just restored from a Titanium backup and had a question. Is the dock on the Android 10 recents supposed to be transparent? I could have sworn it was. Mine currently looks like this screen shot, which doesn't seem right to me. Am I going crazy? Is there a way to switch it back if I'm not crazy?

![Screenshot_20191205-110508](https://user-images.githubusercontent.com/25110361/70253386-1e845400-1751-11ea-962b-8765de7a273f.png)

**Comment by DanGLVK** [comment]
Yes it is meant to be transparent, check the opacity of your dock

**Comment by calbruc** [comment]
Oops, yeah, I should have mentioned that. Dock is as expected on home screen.

![Screenshot_20191205-112454](https://user-images.githubusercontent.com/25110361/70253882-137df380-1752-11ea-8d4f-317f2d70f8b3.png)

**Comment by LuminarySage** [comment]
> Yes it is meant to be transparent, check the opacity of your dock

Didn't you guys grey out that slider when background dock is disabled from a long time ago

**Comment by LuminarySage** [comment]
Also, how do the app cards even have rounded corners? Aren't they just rectangle on the latest pre-alpha build?

**Comment by DanGLVK** [comment]
@Jnss98b actually it depends on wether rounding is enabled on the ROM, if it's enabled Lawnchair will use the stock rounding values

**Comment by LuminarySage** [comment]
@DanGLES3 Is there a way to tweak that with root or even xposed? I have a substratum theme that does just that but it doesn't even affect the whole system (i.e. the notification shade is rounded correctly but the power menu isn't)

**Comment by DanGLVK** [comment]
@Jnss98b You can try the G-Visual mod module, it probably won't affect your recents but it will round most of your UI

**Comment by LuminarySage** [comment]
@DanGLES3 Is custom recents corner radius getting fixed on pre-alpha soon or is it intended to be like that?

**Comment by SuperDragonXD** [comment]
Closing this issue due to this relating to Lawnchair 2 (we no longer support older versions) and because the "integrated dock/app drawer" no longer exists in Lawnchair 11+.
