### ISSUE TITLE
[REQUEST] advanced search

### ISSUE THREAD

**Issue by nihal697** [Deletescape-Media/Lawnchair#1863]
Hi, Can Lawnchair have search like KISS launcher where you can type any letter from an app name and it will show the possible apps.
Example : For "youtube" onr can search "ytb" and the apps will be shown that have Y , T and B in a series in their name. The sorting of the searched apps can be done by last used frequency.
It is a great feature to have. Thanks.

**Comment by nyancrimew** [comment]
This is already possible with the fuzzy searching capabilities Lawnchair currently has

**Comment by nihal697** [comment]
![Screenshot_20191206-165048](https://user-images.githubusercontent.com/47318989/70319753-f5c89100-181a-11ea-84d2-fc3607abf598.jpg)
![Screenshot_20191206-165032](https://user-images.githubusercontent.com/47318989/70319764-fe20cc00-181a-11ea-9260-d533c89c83d5.jpg)

> This is already possible with the fuzzy searching capabilities Lawnchair currently has

Hi, currently, if I search just 'yt' , 'youtube' doesn't show up. I got to type 'ytb' instead. I was wondering if it was possible to show up all the possible apps that have 'y' and 't' in a series. ( This was just an example)
See the screenshots for reference please.
