### ISSUE TITLE
Samsung Music isn't appear in At a Glance widget as Now playing

### ISSUE THREAD

**Issue by JJonnick** [Deletescape-Media/Lawnchair#1868]
## Description
When I play music from Samsung Music it doesn't appear in the **At a glance**.

## Expected Behavior

When listening to a song from Samsung Music should show the song in the **At a glance** as Google Play Music or Spotify

## Actual Behavior

Instead of showing the song shows the following configuration in this case **Greetings** or **Battery Status** _(my configuration)_

## Steps to Reproduce

1. Setting the order **At a glance** (unread notifications, now playing, google app, greetings, battery status)
2. Play any song with Samsung Music

## Environment
* Device: Samsung Galaxy S6
* Android version: 7.0
* Launcher version: 2.0-2589
* Rom: Stock ROM (SM-G920F)

**Comment by DanGLVK** [comment]
@JJonnick Samsung Music uses a non-standard media notification in which Lawnchair cannot parse music info from, there is nothing we can do about it
