### ISSUE TITLE
Weird Recents behaviour in Q-pre-alpha builds

### ISSUE THREAD

**Issue by th3an7** [Deletescape-Media/Lawnchair#1873]
## Description

No matter what settings in "Recents" are, on Android 9.0 I still have 10 recents look (like I am using full gesture mode).
Also none of the settings affect actual "Recents" look - corner rounding, blur background (works only when "blur background" is turned on in "Theme")
Is this intended behaviour?

Note: I am using QuickSwitch to use Lawnchair as recents provider.

![Screenshot_20191211-020034_Lawnchair](https://user-images.githubusercontent.com/13398380/70582833-1f3b4100-1bbc-11ea-8558-9f2d4730d6f4.png)
![Screenshot_20191211-020131_Lawnchair](https://user-images.githubusercontent.com/13398380/70582838-219d9b00-1bbc-11ea-83c2-16a2ac6b2d7b.png)

## Environment

* Device: Sony Xperia X (D2303, suzu)
* Android version: 9.0
* Launcher version: 2.1-2599-ci-q-pre-alpha (although this happens with pretty much every "q-pre-alpha" build)
* Rom: LineageOS 16.0

Kinda offtopic: Folders have this weird gray-ish border and their background is in different color than on previous builds (slightly brighter, not matching other "dark mode" backgrounds - like in stock Pixel Launcher when in dark mode)

**Comment by DanGLVK** [comment]
Corner rounding is broken on the prealphas and it's intentional that recents blur only works when blur is enabled on theme settings, also could you be more specific, what exactly do you mean by Android 10 look?

**Comment by suphon-t** [comment]
This is normal. Blur option will only work if you enable blur in themes settings first. Corner radius is a known issue.

**Comment by th3an7** [comment]
What I meant by "Android 10 look" is I cannot scroll through recent apps why swiping right/left - only switch back to last opened app.

**Comment by DanGLVK** [comment]
Could you perhaps send a video demonstrating the issue? (send the video inside a zip file)

**Comment by skittles9823** [comment]
@th3an7 You mean with the navbar? You must scroll multiple times for it to go through more apps.

**Comment by th3an7** [comment]
I hope streamable links are fine?
This is how it looks now:
https://streamable.com/t7a9e

And this is how it should look (default on Android 9.0, behaviour on older Lawnchair builds - used other launcher but you get the point)
https://streamable.com/ufdg3

**Comment by DanGLVK** [comment]
@th3an7 Ohhh, that's the Quick Switch gesture, such thing was removed on the Android 10 Launcher3 sources

**Comment by th3an7** [comment]
So to get it back I need to use old Lawnchair non q builds? (maybe those in Play Store... still using 2.0-2500-ci-alpha)

**Comment by DanGLVK** [comment]
@th3an7 Yes, only the Pie based builds (like play store Lawnchair) have the Quick Switch gesture

**Comment by th3an7** [comment]
Alright, thanks @DanGLES3 :D
