### ISSUE TITLE
[FR] Emulated app open/close animations from stock Android 10.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1879]

**Comment by DanGLVK** [comment]
Such thing is not possible (specially without root), the stock opening/closing animations of Android 10 are made using the Remote Animations API, and such API is only available to System apps, if you have root and Android 9/10 you can use the Quickswitch magisk module and the prealpha builds of Lawnchair to get the Android 10 animations

**Comment by DanGLVK** [comment]
And replicating that animation using the standard animations API is simply impossible
