### ISSUE TITLE
Feature request : New line per letter in drawer

### ISSUE THREAD

**Issue by nathanael-h** [Deletescape-Media/Lawnchair#1880]
Hello, 
What do you think of adding an option to have a new line per letter in the drawer. I had this in previous Lineage Trebuchet and now miss it. 

Maybe, with some help to start, I could work on it. 

![image](https://user-images.githubusercontent.com/7300309/70900043-45b40e80-1ff8-11ea-9d7c-60f286204492.png)

**Comment by mtomana** [comment]
Grouping apps by first letter would be great! +1 from me :)

**Comment by nathanael-h** [comment]
Hello @paphonb what do you think of this feature ? Maybe I could work on it. But before starting something I'd like to have your opinion. Thanks 🙂

**Comment by nathanael-h** [comment]
I still would like to have this feature. Before trying a PR I would like to have some advices, like would this feature be accepted upstream ? Some quick tips about to starting the code? 
Ping @yasandev or @patrickbaumann or @paphonb 🙂

**Comment by yasanglass** [comment]
I don't see any reason for it not getting accepted if it's toggle-able and matches the rest of the UI. Although I can tweak the UI a little bit afterward myself as well. 

The only tip I can think of is to just take a look at earlier versions of Lawnchair (before the rewrite), and if they have this feature just see how they have implemented it.
