### ISSUE TITLE
Lawnchair won't install

### ISSUE THREAD

**Issue by KevinParnell** [Deletescape-Media/Lawnchair#189]
I currently have the Lawnchair 237 APK installed and am using it and loving it, but it appears I am unable to install the 255 APK with an error that it is not installed. I'm running Android 5.1 lollipop.
![screenshot_2017-07-12-18-21-33](https://user-images.githubusercontent.com/15918185/28142495-178b31de-672f-11e7-9fa3-a6966f5a9044.png)

**Comment by Arceer** [comment]
Did you uninstall 237 before installing 255?

**Comment by KevinParnell** [comment]
No am I supposed to?

**Comment by Arceer** [comment]
Yes

**Comment by Arceer** [comment]
238 is the last one you have to uninstall. Going forward all the new ones will have the same signature so you'll be able to just update it.

**Comment by KevinParnell** [comment]
Thanks.

**Comment by KevinParnell** [comment]
Since updating, Lawnchair crashes on launch.

**Comment by Arceer** [comment]
Try a reboot and/or a clean install, so remove it completely and install a fresh one. If that doesn't work try and supply further information regarding the crash.

**Comment by KevinParnell** [comment]
Already did all of that, and where would I find a log file? All it says is that the app stopped working.

**Comment by KevinParnell** [comment]
Huh, now it's working.

**Comment by KevinParnell** [comment]
How do I access my settings? The pinching thing is not doing anything.

**Comment by suphon-t** [comment]
Long press an empty area.

**Comment by KevinParnell** [comment]
Thanks!
