### ISSUE TITLE
More than welcome UI/UX improvements

### ISSUE THREAD

**Issue by stavros3006** [Deletescape-Media/Lawnchair#1890]
Super great launcher, probably the best out there. But still there are a few things missing/bugging in order to be fully perfect:

1. When using a dark/black theme, both the app drawer background and the app shortcuts are black. Design-wise this looks quite bad as there is no visual differentiation between the drawer background and the app shortcut background, but it just looks like a bad black cutout on top of everything. Maybe the app shortcuts should use a a very dark grey background, but still different than the pure black app drawer (like Nova has them) or maybe add the option of app shortcuts getting a background color based on the icon;

2. The Google search bar could use some visual polish. The G/Google logo is not equally separated from the margins of the search bar horizontally and vertically. It has a bigger horizontal margin and is more separated on the left. This results in the search bar looking like it's being squashed;

3. The notifications counter could use some reworking. The number displayed inside the bubble is too big compared to the entire notification bubble size and because of that, sometimes depending on the number displayed looks off center (for example if the number is 1 which is in most cases). Lowering the font size would visually improve the notifications a lot;

4. The drawer arrow appears to be the smallest I've ever seen on any launcher. Proportion-wise to the rest of the UI elements, it is very small and it gets lost in the entire space among the elements;

5. Possibly add the option for the settings menu to be able to switch back to Roboto. The Google Product Sans font is a visual eyesore.

**Comment by LuminarySage** [comment]
> Possibly add the option for the settings menu to be able to switch back to Roboto

Look around a little bit maybe? It's in Theme settings
![Screenshot_20191225-143216](https://user-images.githubusercontent.com/24306400/71449820-e9519d00-2723-11ea-818b-be9bbc5f53d1.jpg)

**Comment by stavros3006** [comment]
> > Possibly add the option for the settings menu to be able to switch back to Roboto
> 
> Look around a little bit maybe? It's in Theme settings
> ![Screenshot_20191225-143216](https://user-images.githubusercontent.com/24306400/71449820-e9519d00-2723-11ea-818b-be9bbc5f53d1.jpg)

Completely and correctly understand the request/suggestion before making a snide remark maybe?

I meant for the font of the labels in the settings menu of which you've posted a screnshot yourself. Those are always in Product Sans.

**Comment by lawson85** [comment]
Backup to be put in the Actions shortcut or make compatible with Tasker would be amazing
