### ISSUE TITLE
Subgrid positioning - Re-request

### ISSUE THREAD

**Issue by ohcello** [Deletescape-Media/Lawnchair#1893]
Allow Icons and Widgets to be placed in between set grid

This has been requested in 2018, which at that time was considered to be a Nova exclusive, but since Microsoft launcher now also has SG positioning, I'm wondering if you'd consider adding it to your Product Roadmap? 

Thanks.

**Comment by replete** [comment]
The reasons I'm still using Nova Launcher are (in order of usefulness):
- Larger grid size (I use 14x9)
- Disable dock
- widget padding removal
- sub-grid alignment (helpful for fitting widgets into display and maximising the usable space - helpful if you want your homescreen to be a useful dashboard)

Really want to use Lawnchair, definitely is the best option and not far off being a Nova Launcher replacement no-brainer

**Comment by Atulin** [comment]
.

**Comment by uestueab** [comment]
Came here to ask for any updates. This features has ben asked for 7years. Any official statement from the devs?
