### ISSUE TITLE
Blur effect doesn't work with dynamic wallpaper

### ISSUE THREAD

**Issue by marticztn** [Deletescape-Media/Lawnchair#1894]
Blur effect on docker and drawer doesn't work with dynamic wallpaper, is there any way to solve this?

**Comment by LuminarySage** [comment]
Pretty sure it's intended behavior because Android doesn't really have a standard blur API so only live wallpapers can't really be blurred in real time. It might be possible but it won't really be as efficient.  You could make a feature request for it though.

**Comment by marticztn** [comment]
@Jnss98b Thanks!
