### ISSUE TITLE
Double click suspend not work

### ISSUE THREAD

**Issue by lollita** [Deletescape-Media/Lawnchair#1899]
## Description
Double click suspend not work in version 2 but worked in version 1.

**Comment by DanGLVK** [comment]
@lollita What build of V2 are you using?

**Comment by lollita** [comment]
Instead it show accessibility option.
Double click gesture search instead work.

**Comment by lollita** [comment]
2.0-2589

**Comment by DanGLVK** [comment]
@lollita Grant Lawnchair accessibility access

**Comment by lollita** [comment]
It worked now,
Ty very speed support :-)

**Comment by nalladev** [comment]
https://github.com/LawnchairLauncher/lawnchair/issues/2081#issuecomment-3588656848
