### ISSUE TITLE
Color mismatch between fast scroll popup and its scrollbar

### ISSUE THREAD

**Issue by es0329** [Deletescape-Media/Lawnchair#190]
#### Steps to reproduce:
1. Open launcher's app drawer
2. Touch recycler's scrollbar
3. Scroll vertically

#### Expected behavior
- Fast scroll popup appears beside scrollbar in matching color themes

#### Observed behavior
- Mismatch in color themes between fast scroll popup and scrollbar

#### Environment
- Version: Travis-653
- Device: OnePlus 5 (A5000)
- Operating System: OxygenOS 4.5.5 (Android 7.1.1)

#### Sreenshot (cropped)
![app_drawer](https://user-images.githubusercontent.com/819901/28147082-176f15b8-674c-11e7-9b70-5c6507b48cf9.png)

**Comment by suphon-t** [comment]
Fixed with fef0080
