### ISSUE TITLE
Vertical List in Drawer

### ISSUE THREAD

**Issue by inexplicabro** [Deletescape-Media/Lawnchair#1902]
Bring back "Vertical List" option in drawer settings.

**Comment by omeryagmurlu** [comment]
Yes please, the lack of this option keeps me from upgrading to v2 and I'm sure there are others like me too.

**Comment by ouzowtf** [comment]
The app drawer scrolls vertically currently. Maybe you mean horizontally?

**Comment by inexplicabro** [comment]
Nope. The option should make the Drawer appear as a list of apps that goes down vertically. There was an option in LC v1 that did this.

**Comment by omeryagmurlu** [comment]
> The app drawer scrolls vertically currently. Maybe you mean horizontally?

Here is an image of the asked behaviour
![Screenshot_20200119-152219_Lawnchair](https://user-images.githubusercontent.com/8201544/72682646-9c1cdd00-3acf-11ea-8976-fa0bf1b083d6.jpg)

**Comment by chivoyage** [comment]
This makes me stay on v1 too. Moreover it's really annoying that play store updates v1 to v2. They have different feature sets.

**Comment by edoardoo** [comment]
Same here. 
Please add back this feature.

**Comment by omeryagmurlu** [comment]
I've migrated to Niagara. It doesn't support the new Android gesture
system, but is still better than having to content with a subpar app menu.
