### ISSUE TITLE
[Feature request] browser's shortcuts to app drawer

### ISSUE THREAD

**Issue by mirakzen** [Deletescape-Media/Lawnchair#1904]
## Description

Many browsers and web pages provide creating shortcuts to homescreen.
![Screenshot_20200113-135757_Lawnchair](https://user-images.githubusercontent.com/10774652/72250477-b86ed480-360c-11ea-906a-2a92930c3a2b.jpg)
Is it possible to move/copy them to app drawer?

## Possible Behavior

After creating homescreen shortcut user goes to lawnchair's settings to drawer settings and tags needed shortcuts to copy to app drawer. After that user can delete shortcut from homescreen

**Comment by bigrjsuto** [comment]
Would love to see this. So many apps aren't needed and web shortcuts are more than enough. At the same time I love a minimalist homescreen.
