### ISSUE TITLE
Unable to build sucessfully

### ISSUE THREAD

**Issue by fantasticrahulrai** [Deletescape-Media/Lawnchair#1906]
## Description

How to build this thing, I am banging my head from last 10 days reading your readme and trying to get a sucessfull build. The app crashes on the startup, your build varients sucks.

## Expected Behavior

Please come up with proper documentation on how to build and what all those build variants mean so that I can contribute to this already great launcher.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
Please at least include a stack trace so we can know what's wrong.

**Comment by suphon-t** [comment]
Closing as no further information was provided.
