### ISSUE TITLE
Allow Search Pill to be blurred

### ISSUE THREAD

**Issue by olego** [Deletescape-Media/Lawnchair#1916]
## Description

I cannot blur the Search Pill in V2.
In V1, I was able to change the Search Pill's blur settings by going to Theme -> "Apply theme on: [x] Search Bar".  Even when Search Bar was reduced to a pill, its background was still blurred.

In V2, it looks like the Search Bar is a widget and it cannot be blurred.  I really miss the look of V1.

## Expected Behavior

Search Pill should be blurred.

## Actual Behavior

No way to blur the Search Pill.

## Environment
* Device: Pixel 3a
* Android version: 10
* Launcher version: 2

**Comment by SuperDragonXD** [comment]
Late reply, but since V2 is no longer supported, this feature will unfortunately won't be worked on. Also closing since this is relevant to the older versions only (we no longer support older versions).
