### ISSUE TITLE
Wallpaper doesn't fit screen when auto-rotating on lock screen

### ISSUE THREAD

**Issue by entodoays** [Deletescape-Media/Lawnchair#1918]
The wallpaper adjusts to fit the screen when unlocked, but it doesn't adjust when the device is locked and leaves a black strip at the side.

## Expected Behavior
The wallpaper should zoom to the edge of the screen just as it does when unlocked.

## Actual Behavior
Already described above.

## Steps to Reproduce

1. Set a custom image as wallpaper.
2. Turn the device in portrait mode.
3. Lock the device.
4. Press power button, but leave device locked.
5. Rotate the device in landscape format.

## Environment
* Device: Samsung Galaxy Tab S2 SM-t813
* Android version: 9.0
* Launcher version: 2.0-2589
* Rom: LineageOS 16.0

**Comment by suphon-t** [comment]
Lawnchair doesn’t control the lock screen. You should ask Samsung support instead.
