### ISSUE TITLE
[Feature request] Hide apps already in other categories

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1919]
When adding apps to a new category (Settings-> Drawer -> Categories -> Create/Edit a Folder/Tab and then Manage Apps), it's a bit cumbersome (depending on total number of apps you have) to go through the default list of basically all apps, when some of them may be already organized on another category (tab/folder).
While I understand it is possible to have a given app in different categories, I think it would be cool to have a checkbox at the top or similar, something like "Hide apps already categorized" or "Only show apps not in another category".
This way it would be faster and straightforward to organize apps, for this particular use case (using categories, and apps belonging to a single category).

Is this something that could be considered or not frowned upon if contributed to the repo?

**Comment by pionearly** [comment]
Would definitely be helpful! Especially for users with 100+ apps. Sorting those can be a chore and sadly the automatically sorting categories do not work reliably enough yet.

**Comment by dbogdanov** [comment]
Alternatively, the list of apps presented to select from can be split in two: 
1) apps with no category assigned
2) apps with category assigned, perhaps mentioning their current category (an app can be in multiple categories, and it may be useful to know them)

Another less intrusive change: keep the generic list as it is now, but show the apps' categories if assigned. This will help to determine uncategorized apps visually.

**Comment by Atulin** [comment]
Ashamed as I am to admit it, I do have quite a lot of apps installed which makes scrolling through all of them for each of the 5-6 categories a bit tedious. Being able to hide them, or splitting into

* assigned to this category
* unassigned
* assigned to other categories

would be great.

**Comment by Atulin** [comment]
.

**Comment by yasanglass** [comment]
This is literally an enhancement for a feature that does not exist anymore.

**Comment by jonas-a-haller** [comment]
This is really still the same missing feature. Can that be realized?
