### ISSUE TITLE
[UX] Shift key on by default in search, "Every Word Is Capitalized"

### ISSUE THREAD

**Issue by quenz** [Deletescape-Media/Lawnchair#1920]
When you use the search, the shift key is automatically pressed. Every Word Is Capitalized Like This When You Type.

## Expected Behavior
The shift key should not automatically be pressed. It should be lowercase by default.

## Actual Behavior
Every word is capitalized as you type.

## Steps to Reproduce
1. Tap the search bar
2. Type a few words

## Environment
* Device: Google Pixel XL
* Android version: 10
* Launcher version: 2.0-2589
* Rom: Default

**Comment by divadsn** [comment]
@Quenz And now what's the actual bug? The search is case insensitive, no matter how you enter the text.

**Comment by quenz** [comment]
@divadsn I guess it's more of a UX thing. It's just not expected. Also if you misspell something in a DDG search, it will correct to all lowercase, which is additionally distracting. Maybe it's just me. I've never seen the behavior it in any other launchers, namely Pixel/AOSP.
