### ISSUE TITLE
[BUG] Unable to access widgets tapping on them on Xiaimi

### ISSUE THREAD

**Issue by StarCruiser75** [Deletescape-Media/Lawnchair#1922]
## Description
Hi, I'm using version 2.0-2589 on a Xiaomi Mi Mix 3, Android 9, MIUI 11.0.4, and I have problems to access widgets tapping on it.
The only work around to "activate" a given widget, is to open first the corresponding app from the app drawer and then go back to the Launcher page. At this point the actions for that specific widget are again active (e.g. on a weather widget, when I tap it should open the weather conditions). But this restored condition only lasts until I open another app, because after that the widgets go back to their "un-tappable" state.
Just to avoid doubts, the same widgets with another Launcher work as designed.

## Expected Behavior
When I tap on any widget I expect that an action is triggered (depending on the widget). For example, when I tap on a weather widget it should open the weather conditions, or when I tap on a calendar entry of a calendar list widget, it should open the event details.

## Actual Behavior
When I tap on any widget, nothing happens. Long tap instead is not affected by any issue.

**Comment by viktorsml** [comment]
I have the same problem but maybe it's not an issue with the launcher. I found [this solution](http://c.mi.com/thread-2706602-1-0.html) and it worked for me on a Redmi 5 Plus.

**Comment by StarCruiser75** [comment]
...OMG... Thank you so much! This worked beautifully, I never imagined that could be the solution...
Closing the issue.
