### ISSUE TITLE
[Feature Request] Cycle homescreen scrolling

### ISSUE THREAD

**Issue by harshlele** [Deletescape-Media/Lawnchair#1923]
## Description
The default quickstep launcher lets you cycle homescreen scroll. So when you scroll right on the right-most homescreen, it goes to the left-most homescreen. It would be nice if that would be available on lawnchair (I can work on this issue, btw)

* Device: Nokia 6.1
* Android version: 10
* Launcher version: 2.0-2589
* Rom: Android 10

**Comment by LuminarySage** [comment]
>The default quickstep launcher lets you >cycle homescreen scroll.

Lawnchair leans more towards the Pixel Launcher actually and that's not the case there.

Anyways this would be a great addition as long as it's a toggle in settings.

**Comment by harshlele** [comment]
hey, i was looking at the code and managed to build and run it on my device with the quickstepLawnchairDevDebug build variant. But i seem to get no logs in my logcat other than 1 entry from onLauncherStart. How do i make it show logs in android studio 

edit: nvm i figured it out. now to actually understand the code itself :p

**Comment by Ygarr** [comment]
Actual for 	
Lawnchair 2 2.1-2621-ci-q-merge
April 27, 2020
version.
Still not implemented

**Comment by PoisonDarterz** [comment]
Bumping this issue as it might be a nice to have feature which is feasible to be implemented

**Comment by smlpt** [comment]
Bumping again because this would still be a nice feature
