### ISSUE TITLE
Upgrade to Android X

### ISSUE THREAD

**Issue by fantasticrahulrai** [Deletescape-Media/Lawnchair#1927]
## Description

Please Upgrade to Android X
Breaks compatibility with firebase

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by msfjarvis** [comment]
But Lawnchair does not use Firebase, so why is this an issue on our repo?

**Comment by nyancrimew** [comment]
The Android 10 based versions will use AndroidX anyways, we usually don't do this kind of changes of our own to keep upstream compatibility as far as possible. If you need this in your fork you're on your own.
