### ISSUE TITLE
Android Q Quickstep Support

### ISSUE THREAD

**Issue by nift4** [Deletescape-Media/Lawnchair#1930]

**Comment by ibnu-ja** [comment]
If you mean QuickSwitch magisk module, use latest build on apkmirror. It already support QuickSwitch.

**Comment by strikersix23** [comment]
Quickstep code is already in but I don't know if its enabled for android 10

**Comment by nift4** [comment]
I know. It is not so easy...
Each Android version has it's own Launcher version (the Launcher is getting updated).
But the Android Q Launcher3 is not yet merged into Lawnchair. That's the reason some special features (like this) do not work on Android Q. The Lawnchair team already has alpha versions available where this is merged, but not correctly working, else it would not be an alpha.

**Comment by DanGLVK** [comment]
@nift4 actually the reason why it's a prealpha atm is not because the Q gestures are broken but rather some customization features are either partially or fully broken, the gestures themselves work fine

**Comment by nift4** [comment]
> @nift4 actually the reason why it's a prealpha atm is not because the Q gestures are broken but rather some customization features are either partially or fully broken, the gestures themselves work fine

I'm not talking about gestures in any way 😉
But I understand if you did not understand me, I'm not the best in English.

I meant that the whole Lawnchair isn't working correctly, not only the special things.

**Comment by SuperDragonXD** [comment]
Late reply, but you can use the Lawnchair 10 Alphas for QuickSwitch support (even if it's slightly buggy). Closing this issue.
