### ISSUE TITLE
Laggy app drawer

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1932]
## Description

When QUICKSTEP_SPRING feature flag enabled app drawer will got laggy animation.

Maybe I shouldn't post this bug because it's expreremental feature? 
P.s. I really like wallpaper blurring and spring effects. You have never done such cool features before.

## Expected Behavior

Drawer animation must not be laggy

## Steps to Reproduce

1. Enable QUICKSTEP_SPRING feature flag 
2. Open drawer
Video: https://drive.google.com/file/d/1-3h9vMGXBhmVMlVWGj2PAhGl40vuFDuA/view?usp=drivesdk

## Device
* Device: ASUS ZenFone Max pro M1
* Android version: 9.0
* Launcher version: 2608
* Rom: Havoc 2.9
* Lawnchair is default quickstep provider, QuickSwitch not installed

**Comment by skittles9823** [comment]
@fordownloads Yea I'd not recommend using anything in feature flags, they're experimental and shouldn't be in the public developer options.

Just keep them at their default states.

**Comment by fordownloads** [comment]
@skittles9823 Okay, I will not report it.
Why this build was deleted?

**Comment by DanGLVK** [comment]
@fordownloads 2608 wasn't meant to be released, it was a leaked build and it was already taken down, so I recommend you to not use that build
