### ISSUE TITLE
[Feature request] Allow icons to display outside of dock/folders when using 'swipe up'

### ISSUE THREAD

**Issue by adbenj** [Deletescape-Media/Lawnchair#1934]
Not actually sure whether this constitutes a feature request or a bug report, but currently, when you swipe up on an appropriately customised icon in the homescreen dock or folder, the icon displays behind the top boundary of the dock/folder rather than in front of it. Someone else has noted the issue with a screenshot here, but it hasn't been assigned or received a dev response: https://github.com/LawnchairLauncher/Lawnchair/issues/1704

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Not actually sure whether this constitutes a feature request or a bug report, but currently, when you swipe up on an appropriately customised icon in the homescreen dock or folder, the icon displays behind the top boundary of the dock/folder rather than in front of it. Someone else has noted the issue with a screenshot here, but it hasn't been assigned or received a dev response: [#1704](https://github.com/LawnchairLauncher/lawnchair/issues/1704)

This is only historically related, but it mentions swipe-up behavior on customized icons in dock or folders.

- #2659
