### ISSUE TITLE
Feature Request: App drawer widget.

### ISSUE THREAD

**Issue by 5p0ng3b0b** [Deletescape-Media/Lawnchair#1936]
## Description
Add access to the app drawer without swiping.
If using a keyboard cursors or gamepad, access to the app drawer is not possible.
Makes access easier for non touchscreen devices.
Doesn;t need to be on the homescreen by default, just an optional widget.

## Expected Behavior
An app drawer widget to open the app drawer shown in the widgets list.

## Actual Behavior
Non existent.

**Comment by marie-bnl** [comment]
I don't know if these are the exact translations on an english phone but I succeeded having it by 

Long press on home screen --> Widget --> Lawnchair : Action --> Open the applications menu
