### ISSUE TITLE
[Feature Request] At a Glance widget suggestions

### ISSUE THREAD

**Issue by aozora-tori** [Deletescape-Media/Lawnchair#1938]
Would it be possible to have extra date format options for the At the Glance widget (eg. if week-day-month is the default, there could be options like MMM-dd-EEE and such)?

Also, would having custom text as a data source be feasible too (also a weather source option, too)?

**Comment by LuminarySage** [comment]
I'm pretty sure this changes based on the language and region of your device

**Comment by aozora-tori** [comment]
> I'm pretty sure this changes based on the language and region of your device

it does, but perhaps custom formatting options may be nice to have

**Comment by rbarcelona** [comment]
I agree, I think that would be nice.

Besides, I'd also like to suggest allowing users to customize at what time they should get the messages. I'd like to have them activated, but it really doesn't fit in with the culture of my region. It's telling me “Good night” when it's still 3 hours until sunset and I'm not even thinking of having dinner. I'd be great to be able to customize this behavior so it better fits my lifestyle.
