### ISSUE TITLE
Notification access screen shows wrong title

### ISSUE THREAD

**Issue by xpusostomos** [Deletescape-Media/Lawnchair#1939]
## Description
In desktop settings, when you select Notification dots for the first time, it takes you into Android "Notification access" settings, where it shows you the list of all the apps that are permitted to access notifications. All the items listed there are the names of Apps, EXCEPT lawnchair, which is entitled "show notification dots". If one did not recognise the Lawnchair icon, one wouldn't even know which item it was prompting you to select.

## Expected Behavior
Every item in Android "notification access" list should be the name of an app, so it should say here "Lawnchair" 

## Actual Behavior
shows "show notification dots"

## Steps to Reproduce

1. On a new lawnchair installation, go to desktop settings, show notification dots. If it isn't a new installation, I guess you can go into Android settings and find "notification access" screen.

## Environment

 Device: Samsung Galaxy Note 9
Android version: 9
Launcher version: 2.0-2589

`

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
