### ISSUE TITLE
Filtering / searching in search bar (drawer) is slow

### ISSUE THREAD

**Issue by jokay** [Deletescape-Media/Lawnchair#1941]
On Version `1.x` the filtering / searching in the search bar was very fast but now on Version `2.x` it's much slower.

## Description
When filtering / searching for an app it takes up to `12s` (Xperia X Compact).
This depends on the device but even with a newer one it takes up to `10s` (Fairphone 3).
(`2s` for Version `1.x`)

The device has about `75` (non-system) apps.

## Expected Behavior
Faster filtering.

## Actual Behavior
Slow filtering.

## Steps to Reproduce
1. Open Drawer
2. Enter search criteria in the search bar
3. Wait
4. Wait more :wink: 

## Environment
* Device: Fairphone 3
* Android version: 9
* Launcher version: 2.0-2589
* Rom: Stock

## Logcat
Sorry no `logcat` ...

**Comment by divadsn** [comment]
@x-jokay Please define slow filtering, as even I with 70 apps on a Snapdragon 665 cannot reproduce your issue 🤔

**Comment by jokay** [comment]
@divadsn `12s` in Version `2.x` vs `2s` in Version `1.x`.

May be it has something to do with the `Hidden App Shortcuts` feature?

**Comment by jokay** [comment]
Just resetted the `Hidden Apps Shortcuts` but the problem persists (on multiple devices).

**Comment by jokay** [comment]
Ok, found the cause.

Search Engine was set to `DuckDuckGo` instead of `App Search`.

Now it works as expected 👍

**Comment by divadsn** [comment]
Oh boy, nevermind then :smile:
