### ISSUE TITLE
Wallpaper position gets lost after saving

### ISSUE THREAD

**Issue by cooperka** [Deletescape-Media/Lawnchair#1947]
It worked until at least 3 weeks ago, but today in version 2.0-2589 I can no longer set a wallpaper position (see screenshots).

Note: Android seems to know the correct position, because it appears correctly immediately after phone reboot, but as soon as Lawnchair launches the photo position is lost again.

Correct position before saving:
![Screenshot_20200222-230044](https://user-images.githubusercontent.com/2047062/75105491-b06d6180-55c8-11ea-87a0-34bf0e962a12.png)

After saving, position gets lost and image is rendered all the way left:
![Screenshot_20200222-230055](https://user-images.githubusercontent.com/2047062/75105489-aea39e00-55c8-11ea-98fb-573f87fed724.png)

Original photo for reference:

![received_203072404143222](https://user-images.githubusercontent.com/2047062/75105485-a51a3600-55c8-11ea-9d46-746b52f4e6b6.jpg)

I've tried with numerous different photos and they all have the same issue.

Android 9.0, Pixel 2 XL

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11, cute cat
