### ISSUE TITLE
Can someone tell me which Android Studio version can be used to build Lawnchair?

### ISSUE THREAD

**Issue by lfork** [Deletescape-Media/Lawnchair#1949]
Can someone tell me which Android Studio version can be used to build Lawnchair?

**Comment by strikersix23** [comment]
In my experience always use the latest stable version

**Comment by divadsn** [comment]
It's actually Canary being used if I remember correctly

pon., 9 mar 2020, 14:55 użytkownik Adrian Griffin <notifications@github.com>
napisał:

**Comment by strikersix23** [comment]
Thanks for the information
