### ISSUE TITLE
Not fully blured tray and menu

### ISSUE THREAD

**Issue by p0nkr4t** [Deletescape-Media/Lawnchair#195]
There's a thin stripe on the right edge of the tray, which is transparent, not blured
https://photos.app.goo.gl/XAQI7wvbrrz04rf02

**Comment by LinuxLlama** [comment]
There's a blur feature?

**Comment by p0nkr4t** [comment]
Yup

**Comment by LinuxLlama** [comment]
I can't seem to find it.

**Comment by p0nkr4t** [comment]
Download the latest release

**Comment by divadsn** [comment]
Is it still an issue? @p0nkr4t
