### ISSUE TITLE
[bug] Folder icons are getting cut on the sides 

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1954]
## Description

Folder icons are getting cut on the sides 
at Home screen and at the dock (only folders icons except for default folder lawnchair icon)
* Happens on every icon that I choose for a folder
![Screenshot_20200308-220728_Lawnchair](https://user-images.githubusercontent.com/61948600/76170437-cf97f180-6179-11ea-99fb-cd500cb08b06.jpg)
![Screenshot_20200308-220753_Lawnchair](https://user-images.githubusercontent.com/61948600/76170458-fb1adc00-6179-11ea-981a-e39814a3eb0e.jpg)
![Screenshot_20200309-102819_Lawnchair](https://user-images.githubusercontent.com/61948600/76195729-da39a180-61e0-11ea-90b5-66fbf6dd1136.jpg)
![Screenshot_20200309-102813_Lawnchair](https://user-images.githubusercontent.com/61948600/76195743-e45ba000-61e0-11ea-90a9-610ba7bfe73e.jpg)

## Expected Behavior

 Folder icon should look like the other icons
## Actual Behavior

Folder icons are getting cut on the sides
at Home screen and at the dock (only folders icons except for default folder lawnchair icon)
## Steps to Reproduce

**Home screen**
0.Changing in settings(Lawnchair settings) in Theme icon shape to circle.

1.Create a folder (by putting app on app at home screen).

2.Changing icon.

**Dock**
0.Changing in settings(Lawnchair settings) in Theme icon shape to circle.

1.changing the setting for the dock from 5 number of icons to 6.

2.At home screen Create a folder (by putting app on app at home screen).

3.Changing icon.

4.Dragging the folder to the dock.

## Environment

* Device:Samsung Galaxy S8 
* Android version:9
* Launcher version:2.1-2616-ci-q-pre-alpha
* Rom:Official (One UI1)

## Logcat

 

```
your log here
```

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
