### ISSUE TITLE
Home screens reappear after being removed from 'arrange pages' screen

### ISSUE THREAD

**Issue by enndubyu** [Deletescape-Media/Lawnchair#1956]
## Description

Can't seem to permanently remove an entire screen of shortcuts (particularly annoying if you install a lot of apps and they get auto-added to home screens)

## Expected Behavior
Removed pages should stay removed.

## Actual Behavior
Removed pages are visible again next time I return to home screen with swipe up from bottom gesture.

## Steps to Reproduce

1. Add apps to home screen (mine were auto-added after install in case that's relevant)
2. Remove screens by long-pressing desktop -> arrange pages' -> long press and select remove
3. Navigate away from home screen (into an app)
4. Return to home screen and notice previously removed pages are back

## Environment

* Device: Pixel 4 XL
* Android version: 10
* Launcher version: 2.1-2616-ci-q-pre-alpha
* Rom: Stock (QQ2A.200305.003)

Quickswitch has been used to enable lawnchair as recents provider, in case this is relevant

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
