### ISSUE TITLE
[BUG] Lawnchair crashes on applying icon to a web app

### ISSUE THREAD

**Issue by akr2002** [Deletescape-Media/Lawnchair#1959]
## Description

Lawnchair crashes on applying icon to a web app. The icon does not get applied.

## Expected Behavior

Icon gets applied

## Actual Behavior

Lawnchair crashes without applying the icon

## Steps to Reproduce

https://drive.google.com/file/d/1Huvf_pAdlRNLzbmNpURXpGT3wAXBui1w/view?usp=drivesdk

## Environment

* Device: Vivo V5 Plus (Vivo 1611)
* Android version: 7.1.2
* Launcher version: 2.0-2589
* Rom: Funtouch OS_3.1

## Logcat

 

[crash.log](https://github.com/LawnchairLauncher/Lawnchair/files/4329205/crash.log)

**Comment by bohrabhijeet** [comment]
Thanks for reporting. I have shared the crash log internally.

**Comment by akr2002** [comment]
The bug seems to be fixed. Closing.
