### ISSUE TITLE
Can't change dock icon count

### ISSUE THREAD

**Issue by uzamapg** [Deletescape-Media/Lawnchair#1962]
## Description
You cannot change dock icon count to more than 6 icons. 

## Expected Behavior
It should change to more than 6 icon counts like to 8 or 9.

## Actual Behavior
The icon count slider doesn't move forward than 6 icons

## Steps to Reproduce
1.Open lawnchair settings
2.go to dock
3.swipe to icon count and tap
4.change dock icon count at the bottom

## Environment
Device: Huawei Honor 7C
Android version: 8.0.0
Launcher version: 2.1.2616
Rom: EMUI 8

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
