### ISSUE TITLE
[Feature Request] Ability to set default homescreen page

### ISSUE THREAD

**Issue by timjosten** [Deletescape-Media/Lawnchair#1964]
It is now impossible to set default page on homescreen. When you click the Home navigation button, it always gets to the first page.

**Comment by timjosten** [comment]
Or can someone just say where to hardcode that value? I really miss it bad.

**Comment by timjosten** [comment]
OK, I have found myself.
`private static final int DEFAULT_PAGE = 0;`
defined here:
src/com/android/launcher3/Workspace.java

**Comment by DimitrakisT** [comment]
+1
I want to have a page on the left of the home

**Comment by Warden20** [comment]
+1
I want to have a page on the left of the home

**Comment by iFUCKINGHATEcomputers** [comment]
> OK, I have found myself.
> `private static final int DEFAULT_PAGE = 0;`
> defined here:
> src/com/android/launcher3/Workspace.java

Can you edit this in the installed app or do you have to compile shit? Compiling and reinstalling wouldn't be that bad, except the in-app backup/restore function is dysfunctional (as mentioned elsewhere), so restoring settings would be a pain in the ass.
