### ISSUE TITLE
[BUG] Touch and hold option for widgets not working.

### ISSUE THREAD

**Issue by ItIsOHM** [Deletescape-Media/Lawnchair#1966]
## Description
The touch and hold gesture/option for dragging the icons, for showing the shortcut bubble and for putting widgets on the home screen isn't working. 

## Expected Behaviour
I should be able to put widgets on the homescreen via this particular gesture/option. Also the shortcut bubble isn't showing up due to which it's difficult to uninstall an application. 

## Actual Behavior
It just doesn't work. I keep holding it, but nothing happens.

## Steps to Reproduce

1. Open up the widget panel. 
2. Touch and hold any widget. 
3. Normally it should be available to drag on the homescreen, but now it doesn't even move from there.

## Environment

* Device: Samsung Galaxy J7 Duo (2018)
* Android version: 9.0
* Launcher version: 2.0-2589
* Rom: OneUI 1.1

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
