### ISSUE TITLE
"Add Microphone Icon to widget" feature

### ISSUE THREAD

**Issue by p0nkr4t** [Deletescape-Media/Lawnchair#197]
I think not everyone likes Assistant icon, so why not to give 'em a choice?

**Comment by nyancrimew** [comment]
This would basically be a step back as I ditched the mic icon for the assistant one, and adding more and more choices is basically bloating the launcher and not what I am aiming for

**Comment by ljgp6** [comment]
There are some who do not have google  assistant so an option to switch would be nice . thanks
