### ISSUE TITLE
Better support for multiple (work) profiles

### ISSUE THREAD

**Issue by phhusson** [Deletescape-Media/Lawnchair#1970]
This is a feature request.

I'm planning to use multiple work profiles to implement multiples app container, like for instance one Google, one Facebook, one Google-work.
The framework is pretty easy to enable, and my ROMs will enable it in the future, however a bigger issue is the UX.

One part of this is in Lawnchair, here are few things I've noticed when enabling 3 profiles:
- It kind-of works, that's honestly pretty amazing, congrats!
- On Lawnchair 1.x, I got 3 folders called "Work", which is I think pretty adequate for "containers", but this feature has disappeared in Lawnchair 2.x
- However Lawnchair 1.x didn't show the actual names of the profiles, just "Work", so when there are 3 profiles, it's hard to know which folder is which profile.
- System apps available inside profile are shown in "all apps" three times in "Professional" tab (once per profile). I think a solution would be to have one tab per profile?
- It looks like Lawnchair 2 is limited to two profiles (which is already great! since it's out of android spec), while I think a decent limit would be perhaps 5?
- Possibly, it would be nice that if an app exists only in one container, then it is listed in all apps, so that it's more transparent to the user (but since the user can already drag-n-drop profile's app to desk, this is perhaps counter-productive)

If you want to try this yourself you can try this:
-edit /system/build.prop to have:
ro.debuggable=1
fw.max_users=10
persist.sys.max_profiles=10
- create users with `adb shell pm create-user --profileOf 0 --managed Google`

Thanks for your project, and I hope you'll find this interesting to work on!

**Comment by LindaFerum** [comment]
Hey, I'm just dropping in here to let everyone know that if you want to do this kind of thing in a modern-ish android in 2025 you can follow a recipe I cooked for "semi-safely*" rooted GrapheneOS 

https://github.com/GrapheneOS/os-issue-tracker/issues/5507#issuecomment-2927941446

Will test with Lawnchair soon enough and maybe report back (if something breaks) 

*Opinions on intrinsic root un-safeness notwithstanding, we can all agree that rooting while preserving locked bootloader and a reliable OTA update schedule is safe-ER than alternatives
