### ISSUE TITLE
Some type of freeze when launching shortcut with no gui

### ISSUE THREAD

**Issue by eNV25** [Deletescape-Media/Lawnchair#1974]
## Description

Some shortcuts in long press menu of apps are supposed to run in the background, so when launched screen should stay same or close menu. But lawnchair goes into a state where no icons are visible but things are still there. Only way to exit this state is blindly tapping until u launch something.

Only tested on music app Musicolet, has long press shortcuts resume and shuffle play.

This worked in other launchers so I assumed it's lawnchairs issue.
Worked on shade launcher

## Expected Behavior
Long press menu should close or stay.
Everything should be fine

## Actual Behavior

Some shit don't even know

## Steps to Reproduce

1. Install Musicolet and set up.
2. Long press icon.
3. Press resume or shuffle play.

* Device: Huawei y9 2029
* Android version: 9
* Launcher version: 2.0-2589 beta
* Rom: EMUI 9.1

**Comment by eNV25** [comment]
This is not an issue when launching from swipe up action

**Comment by eNV25** [comment]
Also happens when opening do nothing app.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
