### ISSUE TITLE
Global Search Not Showing Websites

### ISSUE THREAD

**Issue by BOB74j** [Deletescape-Media/Lawnchair#1977]
The Google search bar in the app drawer does not display website results, whether or not Global Search is enabled in Lawnchair settings.

## Description
The Google search bar in the app drawer does not display website results. This is true regardless of whether Global Search is enabled or disabled in Lawnchair's Drawer settings. Only app shortcuts are shown. Pressing the enter key after typing text simply launches the most closely matched app name or a Play Store search. The hint text for the Use Global Search option indicates that web results should be available, but they are not.

The search bar on the desktop is not affected by this issue.

## Expected Behavior
Typing in the app drawer search bar should offer real time web search suggestions, as in the desktop search bar, when Use Global Search is enabled.

## Actual Behavior
Only app results are shown in the app drawer search bar, regardless of the Use Global Search setting.

## Steps to Reproduce

Issue is demonstrated in [this screen recording](https://drive.google.com/open?id=1-pRiiFbdBKN0_4iORRzKz0BGctI_KmPZ).

1. Enable search bar and Use Global Search in the Drawer settings of Lawnchair settings
2. Return to the app drawer
3. Type anything in the search bar
4. No web results are shown

## Environment

* Device: Motorola Moto G5 Plus
* Android version: 9.0
* Launcher version: 2.1-2616-ci-q-pre-alpha
* Rom: Pixel Experience 9.0

**Comment by bwalsh0** [comment]
Can confirm, experiencing the same issue on the same launcher version. Home screen search bar works as expected but drawer does not.

Device: OnePlus 7 Pro
Android: 10 (Oxygen OS 10.0.3.GM31CB)

**Comment by major-mayer** [comment]
I have a somewhat similar issue.
I really love startpage as a search engine, but the behavior in lawnchair is really weird.
Mostly it justs launches the browser (Firefox) and displays the search results as it should.
But sometimes it just starts the Google play store and searches for anything that I typed in there.

The lack of consistency is really frustrating, if it didn't work at all I could probably live with it, but this way... 
This issue happens to me in the homescreen and in the app drawer unlike to the OP.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
