### ISSUE TITLE
Incorrect widget pixel dimensions reported by Lawnchair

### ISSUE THREAD

**Issue by drmrbrewer** [Deletescape-Media/Lawnchair#1979]
The app which I develop relies on getting accurate pixel dimensions for its widget, so that it can render a bitmap that will fit exactly inside it... for both portrait and landscape home screen orientations.

However, on Lawnchair, some users are reporting that the bitmap doesn't exactly fill the widget space.  It seems to me that the pixel dimensions being reported by Lawnchair don't quite match the actual widget size.

I've created a [sample app](https://bitbucket.org/drmrbrewer/my-test-application) to demonstrate this.  After installation:

(1) orient phone in portrait orientation
(2) place a widget on the home screen and just accept the default in the config activity
(3) hit UPDATE on the widget to draw a green bitmap that (should) exactly fill the entire widget outline, with no gaps
(4) now rotate the home screen to landscape orientation
(5) hit UPDATE on the widget to redraw the green bitmap

For some devices, the green bitmap doesn't quite fill the widget exactly... there are small blue-coloured gaps top and bottom... the bitmap doesn't quite fit the widget outline exactly.  Example:

![Screenshot_20200420-140609_Lawnchair](https://user-images.githubusercontent.com/9009792/79762551-cecab180-831a-11ea-8d9e-8a1d20654655.png)

This suggests that the widget dimensions are not being reported correctly by Lawnchair. 

The key function in the code is `WidgetInfo.getWidgetDimensionsInDp()`.

It would be great if this could be fixed in Lawnchair (or if you can tell me how I should be getting the pixel dimensions) so that widgets like mine can work correctly.  I have a workaround which allows a correction factor to be specified, but it's not ideal.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
