### ISSUE TITLE
Dock widget support.

### ISSUE THREAD

**Issue by Mr-Perezident** [Deletescape-Media/Lawnchair#198]
This is a feature request. I don't know if this is possible, but could someone add support for widgets in the dock area?   

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
Thats like the new pixel style with search bar at the bottom i guess

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
