### ISSUE TITLE
"App Search" searches the original names of apps, rather than customized names 

### ISSUE THREAD

**Issue by outloudvi** [Deletescape-Media/Lawnchair#1981]
## Description
"App Search" in drawer searches the original names of apps, which means that you cannot search an app by its displayed name, if you've changed it in the drawer. I think it's an occasional mistake, but maybe it's by design...

## Expected Behavior
"App Search" search the names of apps by its customized names, if the user has changed it in the drawer.

## Actual Behavior
"App Search" search the original names of apps, even if the user has changed it in the drawer.

## Steps to Reproduce
1. Change the display name of an app in drawer
2. Search the customized name in "App Search"
3. The app doesn't appear in the result

## Environment
* Android version: 10
* Launcher version: 2.1-2616-ci-q-pre-alpha
* Rom: LineageOS 17.1

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
