### ISSUE TITLE
When using Family link, this tablet forgets that Lawnchair2 should be the default launcher

### ISSUE THREAD

**Issue by hzulla** [Deletescape-Media/Lawnchair#1982]
Hi there,

I have installed Lawnchair2 on my kid's tablet running Android 9. It's a Lenovo TB8705f, which seems to run a mostly unmodified Android 9.

The tablet is restricted using Google Family Link, which offers parents a way to limit app availability and usage time on the kid's device. Family Link also locks the device at a chosen time, and unlocks it in the morning.

In the morning, the device will ask again if the default launcher should be the pre-installed Lenovo launcher or Lawnchair2.

I googled around and did not find other mentions of Family Link causing the device to forget the default launcher setting.

It's unclear where the fault lies. I will report this to the Family Link developers, as well.

Thanks for an awesome launcher & all the best.

**Comment by hzulla** [comment]
How to reproduce:

- Set up an Android device for your kid using Family Link.
- Install Lawnchair2 on that device.
- Make it the default launcher.
- Using parents' family link app, set up a "bedtime schedule" for the device's kid user for automatic lock/unlock.
- Lock the device using parents' family lock app
- Unlock the device using parents' family lock app
- Use the device and you will now find Android asking you if Lawnchair2 or the manufacturer's launcher app should be the default choice.
- Make Lawnchair2 the default launcher.
- Family link lock device / unlock device / repeat.

**Comment by hzulla** [comment]
I have contacted Google Family Link support with ticket "4-3443000030774" and they told me that Lawnchair2 is the problem here. I'm sceptical of that and asked the Google support team to forward my bug report to the Family Link developers so that they can have a look.

**Comment by hzulla** [comment]
Halleluja, the Google Family Link support tells me that "because Lawnchair2 makes changes to the Android system, we cannot guarantee it to work properly with Family Link" and tells me again that the fault lies with Lawnchair2.

**Comment by suphon-t** [comment]
Lawnchair doesn’t make changes to the system by itself because any normal android app can’t do that.

**Comment by hzulla** [comment]
I'm well aware of that. It appears the support team wants to avoid escalating my bug report to the Family Link developers and so shifting the blame is their first response. 😕

**Comment by MyNameIsNotAvailable** [comment]
The same behavior is with the Microsoft Launcher App. Googles Family Link always reset the standard launcher back. The family link is not realy useful with this bug.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
