### ISSUE TITLE
Automate lawnchair backup using adb

### ISSUE THREAD

**Issue by khrj** [Deletescape-Media/Lawnchair#1983]
Hi.
Lawnchair contains an amazing inbuilt backup feature
I wanted to put this in a script, any way to automate it using the command line?
Thanks

**Comment by lawson85** [comment]
+1 Or Tasker and MacroDroid

**Comment by khrj** [comment]
@lawson85 [Easer](https://f-droid.org/packages/ryey.easer/) and [LibreTasks](https://f-droid.org/en/packages/libretasks.app/) are good open source alternatives to Tasker and MacroDroid

**Comment by lawson85** [comment]
> @lawson85 [Easer](https://f-droid.org/packages/ryey.easer/) and [LibreTasks](https://f-droid.org/en/packages/libretasks.app/) are good open source alternatives to Tasker and MacroDroid

Thanks but I like MD best. Are there any intents that will at least launch the backup restore page

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
