### ISSUE TITLE
Lawnchair crashes while adding apps to Folder(s) from app drawer.

### ISSUE THREAD

**Issue by Boilookhere** [Deletescape-Media/Lawnchair#1985]
## Description
Lawnchair crashes and force closes while adding/moving apps into folder(s) from app drawer with an error "java.lang.IndexOutOfBoundsException: Index: 16, Size: 16"
The index & size values in the error output changes sometimes to 19&19, 15 &15, 16&16 etc.

## Expected Behavior
The app/its icon must be moved into specified folder and same must be removed from the drawer.

## Actual Behavior
Lawnchair crashes and spits out an error mentioned above and app will not be moved into the folder.

##Steps to Reproduce

https://drive.google.com/file/d/12x_7c6-9CKKFmlVPTdYChmWg_KXGfe5y/view

##Device info

* Device: SM-N975F/DS (Exynos 9825)
* Android version: 10
* Launcher version: Version 2.1-2616-ci-q-pre-alpha
* Rom: OneUi 2.1

Log:

https://del.dog/ufilequmai.txt

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
