### ISSUE TITLE
Lawnchair crashes while opening its Desktop settings

### ISSUE THREAD

**Issue by sambul13** [Deletescape-Media/Lawnchair#1986]
Description
When integrated and installed with a NikGapps package, Lawnchair crashes and force closes while opening its Desktop settings

Expected Behavior
Should open Desktop settings

Actual Behavior
Lawnchair crashes and force closes while opening its Desktop settings

##Steps to Reproduce

Open Lawnchair Settings - Desktop. See the app crashed.

##Device info

Device: Xiaomi Redmi Note 3 Pro
Android version: 10
Launcher version: Version 2.1-2616-ci-q-pre-alpha
Rom: HavocOS 3.4 Q
Log: https://del.dog/yrfeparere.go

**Comment by sambul13** [comment]
The issue is fixed by the user installing [QuickSwitch](https://github.com/skittles9823/QuickSwitch/releases) Magisk module, and using it to make Lawnchair the Android Recent apps provider. Alternatively, latest Lawnchair release from Telegram channel can be sideloaded to ROM instead of NikGapps Lawnchair module.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
