### ISSUE TITLE
Dock issue

### ISSUE THREAD

**Issue by JackoMJ** [Deletescape-Media/Lawnchair#1989]
### Description
Setting 2 rows in the dock settings don´t work.
There is just one row available.

Restoring a backup of Lawnchair 2 2.0xxx displays 2 icons on top of each other with no way to add icons to a second row.

### Expected Behavior
Icons will be add to second row of dock

### Environment
Device: Mate 9
Android version: 9
Launcher version: 2.1-2621
Rom: Stock ROM Huawei

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
