### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by kenobijim** [Deletescape-Media/Lawnchair#199]
Hi! Can you also add the weather update on the irremovable clock widget like on the Pixel? :)

**Comment by devang98** [comment]
Yep, guess you need to add location permission to the launcher to get the weather update as on the Pixel, I love the launcher however with the weather missing it's a bummer for me and what is stopping me from making it my daily driver

**Comment by marco136** [comment]
Dang I'm liking this launcher too. The ability to keep it pixel stock with the Google now news feed, but now additionally I get to install an icon pack. The only thing that is a bummer for me is the weather widget at the top right not working. It's bringing me to the calendar and days event not found. I just want my weather to display and have it go to the weather when I click on the widget. Do you think this is an easy fix? Thanks.

**Comment by AxiK101** [comment]
I think the devs had mentioned that they will add a weather service simular to stock pixel style after they manage to fix most of the bugs tha launcher allready has. Its going to come eventually

**Comment by marco136** [comment]
Thanks for answering.

**Comment by drew5494** [comment]
+1
