### ISSUE TITLE
Launcher Crash Report (Xiaomi Mi 9, Lawnchair v2.1)

### ISSUE THREAD

**Issue by roman-ta27** [Deletescape-Media/Lawnchair#1990]
_Lawnchair version 2.1_

Been having some issues with crashing of the lawnchair launcher recently. The only thing I can attribute it to currently is the Google (web) search bar, I could eventually be wrong. I'll update with more logs if I notice other possible reasons for crashes.

## Expected Behaviors
(Patch for crash)

## Actual Behavior
App crashes and I'm sent over to the last open application

## Steps to Reproduce
Unfortunately I can't provide proof on this, as it isn't something that happens on every search. The issue only presents itself every now and then (only been using the launcher for about 24h XD), after executing search on the Google (web) searchbar.
![Screenshot_20200502-151621](https://user-images.githubusercontent.com/64643890/80865181-e7768800-8c87-11ea-96d6-28fb6ae4bd9d.jpg)
(the searchbar on my dock is what I was using to search)

## Environment

Device: Xiaomi Mi 9 "cepheus"
Android version: 10
Android Launcher version: 2.1.0
Rom: Paranoid Android Quartz 2 
Rooted with latest Magisk: v20.4
QuickSwitch Magisk module: v3.1.6-2

![Screenshot_20200502-152506](https://user-images.githubusercontent.com/64643890/80865348-21945980-8c89-11ea-9480-24c621642f60.jpg)
Maybe this helps?

## Logcat

Most recent log: https://del.dog/izingoging
_(will update with more, when more crashes occur)_

**Comment by siffreinsg** [comment]
I have the same problem. I don't know about yours but mine is the same as in #1935

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
