### ISSUE TITLE
Dock , the option " show second row " not work.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1991]
when I open the option " show second row" , the dock have no change.

![Screenshot_Lawnchair_20200506-002049](https://user-images.githubusercontent.com/48119814/81091047-3dba2400-8f31-11ea-8ac5-f99862745bd5.png)

![Screenshot_Lawnchair_20200506-002101](https://user-images.githubusercontent.com/48119814/81091061-40b51480-8f31-11ea-8ede-1c2fb70de226.png)

ｌａｗｎｃｈａｉｒ　ｖｅｒｓｉｏｎ　：　2.1－2621－ｃｉ－ｑ－ｍｅｒｇｅ

ｒｏｍ　：　ａｒｒｏｗ　ｏｓ

**Comment by rzfzr** [comment]
I had the same problem for a long time

**Comment by rzfzr** [comment]
@0xdream the playstore version has the two row option working, but does not work with quickswitch....

**Comment by ghost** [comment]
ok, fine, I give up this software.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
