### ISSUE TITLE
The swipe up from dock gesture performs whatever action is set for the swipe up gesture

### ISSUE THREAD

**Issue by ebirtaid** [Deletescape-Media/Lawnchair#1996]
## Description

The only setting for swipe up from dock that seems to work independent of the swipe up gesture is show drawer, every other option I have tried just executes the swipe up gesture.

## Expected Behavior

Swiping up from the dock should execute the desired action (in my case launching an app) instead of executing the swipe up gesture. 

## Actual Behavior

The swipe up gesture is executed (in my case, launching a different app than the swipe up from dock gesture).

## Steps to Reproduce

1. Set the swipe up gesture to open app, select an app.
2. Set the swipe up from dock gesture open app and select a different app, or to anything other than open drawer.
3. Swipe up from the dock.
4. Observe the swipe up gesture get executed.

## Environment

* Device: Google Pixel 3a
* Android version: 10
* Launcher version: 2.0-2589
* Rom: Stock

**Comment by ikt** [comment]
I'm having a similar issue at the moment, fresh install, pixel 2, I've set swipe up from dock to open the draw (same as pixel launcher style) but instead it opens the app switcher. I just tried changing it to some other things but it won't change from app switcher...

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
