### ISSUE TITLE
Multiline / Custom Label Support for Folders

### ISSUE THREAD

**Issue by sabaatworld** [Deletescape-Media/Lawnchair#1997]
![Screenshot_20200521-120215__01](https://user-images.githubusercontent.com/2452471/82596186-c0f78e80-9b5b-11ea-9ee4-204a87d5aefa.jpg)

There needs to be proper spacing for multiline label inside folders. It will prevent the label from getting overlapped as shown in the screenshot.

I also noticed that custom labels don't work with folders.

Please fix this.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
