### ISSUE TITLE
Dock icons issue in landscape mode.

### ISSUE THREAD

**Issue by Davidjarod11** [Deletescape-Media/Lawnchair#1998]
## Description
When selecting the height of the grid at 7 and the size of the desktop icons at 150% , the dock icons break in landscape mode, this problem is related to the size of the desktop icons, because the more height the grid has the smaller the desktop icons have to be so that the dock icons do not break in landscape mode.
Other combinations between the height of the grid and the size of the desktop icons also occur this problem and dock icons break, this should not happen since they are not exaggerated values that are used to break dock icons.

## Expected Behavior
The dock icons should not break in landscape mode when increasing the size of the desktop icons , it should be as shown in this picture.

Landscape, width 4, height 7, Icon Count 4........ 100% desktop icons size and 150% dock icons size
![3e0fd2f7-e189-4cfe-95bc-aa7f81d76f6b](https://user-images.githubusercontent.com/47721967/82605341-61a97680-9b7b-11ea-9571-f2ddd2720885.jpg)

## Actual Behavior
When increasing the size of the desktop icons the dock icons break in horizontal mode.

Lansdcape ,width 4, height 7, Icon Count 4............150% desktop icons size and 150% dock icons size
![efb92f50-bb7e-45ff-ba43-6c600df68d37](https://user-images.githubusercontent.com/47721967/82604019-3a51aa00-9b79-11ea-8e94-087458179028.jpg)

Reducing the size of the dock icons is not the solution and causes the same result.

Landscape, width 4, height 7, Icon Count 4........ 150% desktop icons size and 100% dock icons size
![292ded40-7c00-4472-99bb-d13ccc247023](https://user-images.githubusercontent.com/47721967/82608940-2b6ef580-9b81-11ea-86ab-e8da8ac7a8a3.jpg)

## Steps to Reproduce

1.Set the grid to width 4, height 7, Icon Count 4.
2.Increase the size of the desktop icons to 150%. 
3.Placing the phone in landscape mode
4.Look at the broken dock icons

## Environment

* Device: Redmi k20
* Android version: 10
* Launcher version: 2.1-2621
* Rom: Pixel Experience

I hope and can solve this problem because it limits personalization, on the other hand the portrait mode works perfectly, I only see this problem in the landscape mode, sorry for my bad English and thank you very much for your work.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
