### ISSUE TITLE
the blur doesn`t work

### ISSUE THREAD

**Issue by Easonzero** [Deletescape-Media/Lawnchair#200]
the blur doesn`t work for search bar，and it becomes transparent。

**Comment by fonix232** [comment]
Are you using a live wallpaper?

**Comment by Easonzero** [comment]
No....

**Comment by Easonzero** [comment]
Can you provide a option to decide whether turn on/off blur?

**Comment by nyancrimew** [comment]
@Easonzero there is an option to turn blur on and off already
