### ISSUE TITLE
Darkmode not working when you click the serachbar on the home screen

### ISSUE THREAD

**Issue by raynerdsz25** [Deletescape-Media/Lawnchair#2000]
## Description

When i click on the serachbarbon home screen it opens but the by is white and font light greyish which is not visible this is when phone is on dark mode. Other places it works fine

## Expected Behavior

Bg should be dark and font light grey that is visible

## Actual Behavior

Bg white and font light gretly

## Steps to Reproduce

1. https://photos.app.goo.gl/PxvYXH2ArV8EcfgJ7 - actual behaviour

2. https://photos.app.goo.gl/shD4hEmyKEWSKtK3A - expected behaviour

## Environment

* Device: Realme X2 Pro
* Android version: 10.0
* Launcher version: 2.0-2589
* Rom: Realme UI 1.0

## Logcat

 

```
your log here
```

**Comment by DanGLVK** [comment]
https://github.com/amirzaidi/AIDLBridge/releases/tag/v3 install the Pixel bridge

**Comment by noahhhi** [comment]
> https://github.com/amirzaidi/AIDLBridge/releases/tag/v3 install the Pixel bridge

It works but get a different search UI after install this.😂

**Comment by raynerdsz25** [comment]
> https://github.com/amirzaidi/AIDLBridge/releases/tag/v3 install the Pixel bridge

Works thanks

**Comment by apo208** [comment]
Works thanks!!

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
