### ISSUE TITLE
[Feature request] Close app drawer after app run

### ISSUE THREAD

**Issue by lampaczcz** [Deletescape-Media/Lawnchair#2002]
## Description
Starting application from app drawer and closing/killing application, app drawer is visible and you must close it.  You can test it on clock app or settings app.

## Expected Behavior
After clicking on app from app drawer, app drawer should be closed. Home screen or last used screen should be visible.

## Actual Behavior
After closing app, you are still in app drawer.

## Steps to Reproduce
1. Show app drawer
2. Run app (settings)
3. Click back or kill app
4. You are back in app drawer

## Environment
* Device: Redmi Note 4
* Android version: 10
* Launcher version: 2.0-2589
* Rom: Lineage 17.1

I know that android 10 isn't fully supported but it was same on version 9.

**Comment by GrigalashviliT** [comment]
same problem with me, after closing app, you are still in app drawer or after killing app, app drawer closing animation is shown. please fix this
device: google pixel 3
android version: 10
Launcher version: 2.0-2589

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
