### ISSUE TITLE
[Feature Request] Disable Alphabetic Scrolling

### ISSUE THREAD

**Issue by domenicw1** [Deletescape-Media/Lawnchair#2003]
## Description
When you have few app icons in your App Drawer, scrolling just a bit will cause the scrollbar to jump across the screen because of Alphabetic scrolling, which is pretty distracting. Although this issue is in the Pixel Launcher too, there should be an option to disable it
https://streamable.com/66mfpg

## Expected Behavior
Option to disable Alphabetic Scrolling, making the Scrollbar act like a normal one

## Actual Behavior
There is no such option.

## Steps to Reproduce

Scroll in the App Drawer

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
