### ISSUE TITLE
[BUG] Launcher is crashing everytime when i try to do a search by typing in the search bar in the app drawer.

### ISSUE THREAD

**Issue by SubD06** [Deletescape-Media/Lawnchair#2004]
**Description**

It's exactly like how i wrote and It's been like that since February 7 update.

**Environment**

- Device : Xiaomi Mi 9 Lite

- Android Version : Android 10

- MIUI Version : MIUI 11.0.2.0 Stable EEA

- Current version of the launcher : 2.1-2627-ci-q-merge

**Logcat**

https://del.dog/dalicaytta

**Comment by eraser989** [comment]
Me too
Lineage OS 17.1 
Poco f1 
Magisk woth quick switch

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
