### ISSUE TITLE
feature request - enable the "Search Apps" text field to be in focus when you pull up the app drawer.

### ISSUE THREAD

**Issue by rmahnovetsky** [Deletescape-Media/Lawnchair#2008]
There was a feature requested a while back to "enable the "Search Apps" text field to be in focus when you pull up the app drawer."

I noticed it was mentioned that the feature was included in lawnchair v2 but I cant find it anywhere. Reference @faroit "This option is available with the gesture options in V2"

_Originally posted by @deletescape in https://github.com/LawnchairLauncher/Lawnchair/issues/1126#issuecomment-410992846_

Does the enabling the focus feature exist or is it yet still to be implemented? As I would love to have the search bar have focus to reduce a click.

**Comment by noggynoggy** [comment]
You can go to settings → gestures and just set it to open "launch app search" or something. 

that way it'll open the keyboard when you're opening it, so u can search for the app u want

**Comment by rmahnovetsky** [comment]
Thanks, "launch app search" did the trick. The keyboard now opens up and the focus is in the search field. Perfect :)
