### ISSUE TITLE
[DUPLICATE] [BUG] Non-Google search bar doesn't search on the browser when the search string is too long for predictions

### ISSUE THREAD

**Issue by Groctel** [Deletescape-Media/Lawnchair#2009]
## Description

As the title says, when you press the search bar with a search engine that opens in the browser (eg DuckDuckGo) it opens the drawer search bar and from there you type your query, press Enter, and the browser opens with the search page. Since the bar that opens is the one in the drawer, when the search string is too long for predictions, the search query isn't sent to the browser but to Google Play to search an app. There's no way to search on the browsing engine when this happens.

## Expected Behavior

Pressing Enter should send the search query to the browser every time.

## Actual Behavior

When the search string is too long, it can only be sent to the repository app (Play Store, F-Droid...), not the browser.

## Steps to Reproduce

1. Set Settings/Dock/"Show Search Bar" to `true`
2. Set Search/"Search Engine" to an *in Browser* engine (eg DuckDuckGo)
3. Press the search bar at the bottom of the home screen
4. Start typing the search query until predictions disappear
5. Read with despair how the bar shows *No apps found matching "%s"*
6. The only button is *SEARCH FOR MORE APPS*
7. Pressing Enter sends the query to repository apps only
8. ???
9. Deficit

### Screenshot walkthrough

Steps 1-3: The search bar is at the dock.

![](https://i.imgur.com/dpkkihE.png)

Steps 4-6: Typing a "long" search string.

![](https://i.imgur.com/5H6nPsX.png)

Step 7: I can only send the query to Play Store and F-Droid.

![](https://i.imgur.com/mp3aeaP.png)

![](https://i.imgur.com/f71agU3.png)

Extra: Searching for a short string works fine when predictions are available.

![](https://i.imgur.com/tZQo3Cq.png)

![](https://i.imgur.com/Xe4kI1C.png)

## Environment

* Device: Xiaomi Mi Mix 3 5G
* Android version: 10.0
* Launcher version: 2.0-2589
* Rom: LineageOS 17.1

**Comment by fezboy** [comment]
Just a note, this isn't a problem with the *length* of the string, per say, just whether or not the search engine has suggestions for it.
![Screenshot_20200618-162915](https://user-images.githubusercontent.com/31973884/85081557-25b8ff80-b181-11ea-84ad-0b2c27446cca.png)

So a better title might be "...when search engine doesn't provide suggestions"

Also of note, it works properly if the search engine doesn't have a suggestion but the app searching does:
![Screenshot_20200618-172310](https://user-images.githubusercontent.com/31973884/85084066-8bf55080-b188-11ea-8f12-6169fc4e4d5e.png)

Pressing search here will search duckduckgo in the browser.

**Comment by Groctel** [comment]
In my very personal opinion, pressing the search engine bar should always set the searching context exclusively to the chosen search engine. However, I understand it can be a refactoring pain to implement this from the ground up.

**Comment by ghost** [comment]
Seems like a duplicate of #1742.

**Comment by Groctel** [comment]
@hyperfekt  It is. Thanks for the reference!
