### ISSUE TITLE
[Feature Request] Dragable Folders in App Drawer

### ISSUE THREAD

**Issue by privatmamtora** [Deletescape-Media/Lawnchair#2010]
#  Description
App Drawer: using folders for categorization
I would like to be able to drag and drop.
I guess there are 2 things you can do with this.

1. Drag and drop to Launcher page (desktop)
2. Reorder folders of app drawer (this is a nice to have, I know we can change folder order in the lawnchair settings)

## Expected Behavior
By dragging to page, a copy of the folder is made on the desktop.

Making changes to a drawer category folder should also update the copy on the desktop. 

But changes would only be in one direction.
Whatever is done to the folder on the desktop should not update the category folder in app drawer.

## Environment
* Device: Mi Mix 2 "Chiron"
* Android version: 9.0. 0
* Launcher version: 2.1.0
* Rom: OneUI 1.2

* Device:
* Android version: 10
* Launcher version: 2.0-2589
* Rom: crDroid

PS: thanks for the launcher

**Comment by njakes** [comment]
This would be a great addition to the new releases

**Comment by privatmamtora** [comment]
Remove stale
