### ISSUE TITLE
Ability to change a specific app icon #2

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#202]
This goes along with Issue #196. In other launchers, you can choose an image to set as an app icon. This should be in Lawnchair. Another feature is to select any icon from an icon pack to an app. For example, there are multiple dialer colors for the dialer. When the icon pack is applied, it only uses one color and is not possible to change. If this is added, the dialer icon could be chosen from a menu with all the icons from the icon pack in it. It would work like how Nova Launcher works in a way.

**Comment by jay-chorus** [comment]
Yes indeed, such functionality is most welcome... But I'm entire sure how it'll be implemented in the code.

**Comment by LinuxLlama** [comment]
Yeah, it probably would be very hard.

**Comment by suphon-t** [comment]
Implemented with f5500d84
