### ISSUE TITLE
Apps Being Added to Home Screen

### ISSUE THREAD

**Issue by icydius** [Deletescape-Media/Lawnchair#2023]
## Description

Is there any way to disable apps from being added to the home screen? I didn't opt-in for that.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment]
It's in Lawnchair Settings -> Desktop -> Add New Shortcuts to Desktop

**Comment by icydius** [comment]
OMFG, how'd I miss that??!! Thank you!!
