### ISSUE TITLE
Lawnchair is the only launcher that prevents KLCK - Kustom Lock from working

### ISSUE THREAD

**Issue by Skyyblaze** [Deletescape-Media/Lawnchair#2030]
First of I love Lawnchair and would like to use it as my default launcher but sadly it's the only launcher I tried that stops my custom lockscreen app from working.

I'm using a Xiaomi Mi 8 running Android 10 QKQ1.190828.002 MIUI 11.0.5.0 Global with Kustom Lock - KLCK. The custom lockscreen app works by drawing over other apps when the device is locked but it doesn't disable the System Lockscreen. It never caused any issues with any other launcher and it theoretically works with Lawnchair aslong as I don't set it as my default launcher.

The second I do that KLCK disappears and only the System Lockscreen shows, when I clear defaults from Lawnchair KLCK reappears instantly so the issue definitely lies with Lawnchair. Could someone elaborate what's going on here?

**Comment by suphon-t** [comment]
This issue happens after switching to any launcher, so it's on Kustom Lock side. I found the workaround is to just restart Kustom Lock and then it works properly.

**Comment by Skyyblaze** [comment]
> 
> 
> This issue happens after switching to any launcher, so it's on Kustom Lock side. I found the workaround is to just restart Kustom Lock and then it works properly.

That sadly doesn't seem to be the case on my end, I made a short video to illustrate that this issue happens for me only as soon as Lawnchair is set as default and immediately is resolved as soon as another launcher takes the default again. No matter the amount of restarting KLCK, reinstalling KLCK or rebooting my device makes KLCK show when Lawnchair is set as default so I definitely see the issue with Lawnchair and not Kustom.


[Lawnchair issue.zip](https://github.com/LawnchairLauncher/Lawnchair/files/5011927/Lawnchair.issue.zip)

**Comment by Skyyblaze** [comment]
Someone on a Discord suggested I should try the latest nightly with the Q features merged in and it still happens with this version too as a heads-up. If I can help to resolve this in any way I would be more than happy to provide logs or do other debug testing. I also posted this on the Kustom Subreddit to get the attention of the developer(s) there too.

**Comment by Skyyblaze** [comment]
A little update on this, I found an old Mi4c running Android 7 with MIUI 10 and it exhibits the exact same behavior with Lawnchair only. One thing I noticed here, it seems that Lawnchair prevents the auto-unlock from working which is why KLCK fails.

I didn't notice it on my Mi 8 but since the Mi4c is slow KLCK never shows up immediately, first the system lockscreen appears and then the Unlock Sound is heard following by KLCK appearing. As soon as Lawnchair is default the Unlock Sound never comes and as such KLCK also never appears.

I also found an old Nexus 4, will try my results there later.

**Comment by Skyyblaze** [comment]
Alright I tested it on a Galaxy S10 and that also shows the same behavior, as soon as Lawnchair and only Lawnchair is set as default, KLCK is unable to show, as soon as defaults are cleared or any other launcher takes over it works again.

Here's the relevant data for the S10:

Android version: 10
Kernel: 4.14.117-18725736
Build: QP1A.190711.020.G975USQS4DT46

So this is not a MIUI problem, Lawnchair does something different than other launchers that collides with KLCK.
