### ISSUE TITLE
Issue with search bar

### ISSUE THREAD

**Issue by M4TH1EU** [Deletescape-Media/Lawnchair#2036]
## Description

When typing ~10 characters in the search bar with duckduckgo as search engine, lawnchair crash.

## Expected Behavior

Should simply open for me firefox with duckduckgo.

## Actual Behavior

Close Lawnchair and says that it crashed.

## Steps to Reproduce

(With Duckduckgo (web) as search engine in settings)
1. Go to the apps drawer
2. Write in the search bar
3. The launcher should crash
4.

## Environment

* Device:Samsung Galaxy A50
* Android version: 10
* Launcher version: 2.1.2627
* Rom: One UI 2.0

## Crash Report
https://del.dog/ythooppiji

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
