### ISSUE TITLE
Opening app from app drawer and then going to home causes weird drawer animation close

### ISSUE THREAD

**Issue by Ezzahhh** [Deletescape-Media/Lawnchair#2037]
## Description

If you open an app through the app drawer (instead of on the desktop) and then you go back to the desktop (swiping up gesture for me on OnePlus 7 Pro) the app will begin close animation, close, and then the drawer will suddenly appear and then disappear. I assume this is a bug as it does not happen when going to desktop from an app opened from the desktop and is pretty distracting.

**NOTE** I just discovered that if I disable the nav gestures and use the normal buttons (back, home, recent) the problem is resolved. I've heard of Android 10 gesture problems so I'm not sure if it's a launcher related bug or Android itself.

## Expected Behavior

Application opened from app drawer should exit to desktop without showing the app drawer.

## Actual Behavior

Application will close normally but app drawer will briefly appear and then disappear to the desktop. Do not experience on other launchers.

## Steps to Reproduce

1. Swipe up or open up app drawer.
2. Open any app in the app drawer.
3. Go to desktop by swiping with gestures.

## Environment

* Device: OnePlus 7 Pro GM1917
* Android version: 10
* Launcher version: 2.0-2589
* Rom: OOS 10.3.4.GM21AA, Rooted, xXx No-Limits 11.7 installed 

## Logcat

 

No crashing was experienced

**Comment by emincangencer** [comment]
Try using QuickSwitch.

**Comment by thinkgadgetsme** [comment]
I have also observed the same issue.

**Comment by emincangencer** [comment]
> I have also observed the same issue.

You need to use QuickSwitch.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
