### ISSUE TITLE
Turn off screen open Accesibility settings

### ISSUE THREAD

**Issue by magarcan** [Deletescape-Media/Lawnchair#2039]
## Description
When you select "Turn off screen", from gestures or shortcut widget whats appens is that Accesibility settings page is loaded.

Turn off sceeen waiting" actions works OK instead.

## Steps to Reproduce
1.Open Launcher settings
2. Pick double touch
3. Turn off screen (as action)

## Environment
* Device: Redmi Note 9 S
* Android version: 10
* Launcher version: 2.0-2589
* Rom: Miui 11.0.4

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
