### ISSUE TITLE
Search bar colors are messed up

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2043]
I am currently using Lawn chair with dark mode enabled (true black). Whenever I open up the search bar, it is white and the search suggestions are gray. This makes reading the suggestions difficult and doesn't fit will with a dark theme. Is it possible that the true black setting is causing this issue? ![Screenshot_20200828-123839_Lawnchair.jpg](https://user-images.githubusercontent.com/61721397/91592205-2e217980-e92c-11ea-993b-ac80143322c7.jpg)

**Comment by Heisenberg399** [comment]
I will be able to fix this...shall I try?

**Comment by RikKoedoot** [comment]
Late reply sorry, but if you're still experiencing this, install pixel bridge: https://github.com/amirzaidi/AIDLBridge/releases/latest/download/pixelbridge.apk
Closing because effort has been moved to v11
