### ISSUE TITLE
Move drawer's search bar to the button of the screen

### ISSUE THREAD

**Issue by zakthedev** [Deletescape-Media/Lawnchair#2044]
## Description
The search bar on the drawer's screen is way on the top and it should be in the bottom where users can reach it easily.

## Expected Behavior
- Search bar on the bottom of the screen.

## Actual Behavior
- Search bar on the top of the screen.

## Steps to Reproduce
- Open Drawer

## Environment
* Android version: 9.0.0
* Launcher version: 2.0-2589

**Comment by Heisenberg399** [comment]
Hey..I can work on this if you don't mind

**Comment by brumik** [comment]
Please correct the title, I accidentally duplicates the issue (button instead of bottom typo)

**Comment by brumik** [comment]
@Heisenberg399 Is this feature worked on?

**Comment by jgeusebroek** [comment]
This would be an awesome feature.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
