### ISSUE TITLE
[Request] ability to configure any app as an alternative to Google Feed

### ISSUE THREAD

**Issue by m-p-3** [Deletescape-Media/Lawnchair#2045]
Would it be possible to attach any arbitrary app to the left panel instead of Google Feed, let's say the Feedly, Inoreader, or any other app, even widget(s) in full screen? That'd be more useful than what Google offers right now.

**Comment by guilhermetod** [comment]
I've just seen Microsoft Launcher's feed has the option to add any widget to it and is really amazing. Lawnchair + Microsoft Feed would be a perfect match.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by RikKoedoot** [comment]
Also in v10 we had this option, but apps had to support it, only homefeeder did

**Comment by m-p-3** [comment]
> Closing because effort has been moved to v11

Should I reopen a new request for v11?

**Comment by RikKoedoot** [comment]
I'll open this one back up, don't know why I closed it as it's a feature request, not a bug report

**Comment by Elaborendum** [comment]
The feature is still unavailable.
