### ISSUE TITLE
Search Bar not vertically centered to bounding box

### ISSUE THREAD

**Issue by jeengbe** [Deletescape-Media/Lawnchair#2048]
## Description
Lawnchair's Search widget is not vertically centered in its bounding box. Instead, it is aligned to the very bottom, no matter the height of the widget bounds.

## Expected Behavior
I presume the padding is meant to be equal both above and below the search bar..

## Actual Behavior
![20200908_123239](https://user-images.githubusercontent.com/51749023/92466068-d60e3100-f1cf-11ea-9ea4-2590ff7453b9.jpg)

## Steps to Reproduce
Use the widget, I guess?
If you cannot reproduce the issue it might be related to my settings. Post a reply and I'll share my backup file.

## Environment
* Device: Samsung Galaxy S7
* Android version: 8.0.0
* Launcher version: 2.0-2589 (Most recent one from Play Store)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
