### ISSUE TITLE
Crashes unexpectedly

### ISSUE THREAD

**Issue by marchingon12** [Deletescape-Media/Lawnchair#2049]
## Description

Upon scrolling through the app drawer, Lawn chair unexpectedly crashes at random times.

## Expected Behavior

Should not crash.

## Actual Behavior

Crashes and switches to original launcher to default launcher.

## Steps to Reproduce

1. Scroll around home page.
2. Scroll around app drawer.
3. Possibly clicking the info button when long pressing an app.
4. -

## Environment

* Device: Huawei Mate 20
* Android version: 10.0.0
* Launcher version: 2.1-2161-ci-q-pre-alpha
* Rom: EMUI 10.1

## Logcat

 

[https://del.dog/mockutarob](https://del.dog/mockutarob)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
