### ISSUE TITLE
In Android 11, Lawnchair will close when you go to home screen by swiping up from the bottom

### ISSUE THREAD

**Issue by yudai-nkt** [Deletescape-Media/Lawnchair#2050]
I'm not sure if Lawnchair is responsible for this issue. Feel free to close if it turns out to be otherwise.

## Description

Lawnchair will end when you close an app by swiping up from the bottom even if Lawnchair is set to the default launcher. This didn't happen with Android 10.

## Expected Behavior

Lawnchair should remain in work.

## Actual Behavior

Launcher is fallen back to Pixel Launchar (in my case)

## Steps to Reproduce

1. Open any app
2. Close the app by swiping from the bottom
3. You'll see a different launcher than Lawnchair

<details>
    <summary>Reproduction step in animated GIF</summary>
    <img src="https://user-images.githubusercontent.com/13291527/92546811-6c089100-f28e-11ea-9357-f7b40b9c9a3e.gif" alt="reproduction step" width="40%">
</details>

## Environment

* Device: Google Pixel 4
* Android version: 11 (build number: RP1A.200720.009)
* Launcher version: 2.0-2589
* Rom: N/A

**Comment by gpolydoros** [comment]
Yes, it happened with my Pixel 4 as well, but if you keep going to Settings and selecting Lawnchair as your default launcher, it stops reverting back to the Pixel Launcher. It may seem futile at first, but after repeating that step for 4-5 times, at least in my case, Android decided to stick with Lawnchair. Worth a try.

**Comment by spookymyo** [comment]
> I'm not sure if Lawnchair is responsible for this issue. Feel free to close if it turns out to be otherwise.
> 
> ## Description
> Lawnchair will end when you close an app by swiping up from the bottom even if Lawnchair is set to the default launcher. This didn't happen with Android 10.
> 
> ## Expected Behavior
> Lawnchair should remain in work.
> 
> ## Actual Behavior
> Launcher is fallen back to Pixel Launchar (in my case)
> 
> ## Steps to Reproduce
> 1. Open any app
> 2. Close the app by swiping from the bottom
> 3. You'll see a different launcher than Lawnchair
> 
> Reproduction step in animated GIF
> ## Environment
> * Device: Google Pixel 4
> * Android version: 11 (build number: RP1A.200720.009)
> * Launcher version: 2.0-2589
> * Rom: N/A

It happens on every third party launcher I try. I've found that first going to settings and selecting Pixel launcher as default and then opening the third party launcher and setting it to defusing from within that apps settings works first time for me.

**Comment by j13ag0** [comment]
On my Pixel 3a, there is no need to close an app.  Just swipe up from the bottom to expose the list of apps - Lawnchair has died.... but
Then, next day, everything seems fine.  Problems with LawnChair have evaporated.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by CheryMarie** [comment]
You need to change your default home page in settings and this problem will stop x
