### ISSUE TITLE
lawnchair crashed due to a glitch

### ISSUE THREAD

**Issue by Manasvi-human** [Deletescape-Media/Lawnchair#2052]
## Steps to Reproduce

1. Download Seasame
2. Go to lawnchair and choose seasame to use for app drawer and home screen searches.
3. After that use seasame once or as much as you like.
4. Then uninstall seasame.
5. Then Lawnchair will crash.

## Logcat
..

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
