### ISSUE TITLE
LawnchairV2 removes StockApps when closed restarted (Dialer, Contacts Gallery)

### ISSUE THREAD

**Issue by DSDV** [Deletescape-Media/Lawnchair#2053]
Hi,

i love your launcher even if it has no applock/privacy function! 

but when my phone restarts or lawnchair crashes all the stock apps are removed from the desktop and need manual replacement from the launcher ever time!

eg my contacts, dialer, gallery app are all gone every single time lawnchair gets closed or restarted. custom apps like signal are not removed. but replacements like a custom dialer will also get removed.

with kind regards

PS: sorry for my bad english

PPS: im on MIX2 and MIX2s with LinageOS 17.1 (updated) which is Android 10 based.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
