### ISSUE TITLE
[BUG] Only some widgets open intents on click

### ISSUE THREAD

**Issue by jso8910** [Deletescape-Media/Lawnchair#2056]
## Description

Whenever I want to open a widget's intent, it doesn't work. It works with stuff like the Google News widget, but with stuff like the KWGT widgets and the Easy XKCD widget, it doesn't open into the app.

## Expected Behavior

When I click on a clickable widget, it should do something (eg opening an app). 

## Actual Behavior

It does nothing

## Steps to Reproduce

1. Go to Lawnchair
2. Add a widget not made by Google or Lawnchair that should do something on click
3. Try to click on it

## Environment

* Device: Xiaomi Mi 9 SE
* Android version: Android 10 (MIUI 12)
* Launcher version: 2.0-2589
* Rom: MIUI

**Comment by apo208** [comment]
I have the same issue with Xiaomi mi 9.

**Comment by apo208** [comment]
It seems like it's not lawnchair issue. You should set full permissions on the widget's app.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
