### ISSUE TITLE
support for android 7.0

### ISSUE THREAD

**Issue by joelocandol** [Deletescape-Media/Lawnchair#2057]
In the newers version of the app that are uploaded in Apkmirror, support for versions of Android before 7.1 has been dropped. This will be only on the beta version or it would be permanent?

**Comment by DI555** [comment]
i also vote for android 5.0+ support, please!!!

**Comment by chromer030** [comment]
I hope new development cover android 7.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
