### ISSUE TITLE
please, builds 2.0-2589/2.0-2587 support/fork feature

### ISSUE THREAD

**Issue by DI555** [Deletescape-Media/Lawnchair#2058]
## Description

this versions are last of android 5.0 working on

## Expected Behavior

Please support those 2.0x versions, we have tons of devices on Android 5.0+ , don't drop those versions!

**Comment by DanGLVK** [comment]
unfortunately due to our small team and the current state of development we will most likely only be capable of maintaining one build/branch, if anyone wishes they can fork the beta/stable builds and continue their development

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
