### ISSUE TITLE
Double Tap to sleep does not work

### ISSUE THREAD

**Issue by thinkgadgetsme** [Deletescape-Media/Lawnchair#2059]
Double Tap to sleep gesture doesn't work. It opens the Android accessibility settings page.

## Expected Behavior

Double Tap to sleep gesture should lock the screen when triggered.

## Actual Behavior

It opens the Android accessibility settings.

## Steps to Reproduce

1. Open Lawnchair Home Settings
2. Navigate to Gesture settings
3. Select double tap to sleep
4. Navigate to desktop/home
5. Double Tap to lock the screen.

## Environment

* Device: OnePlus 6T
* Android version: 10.0
* Launcher version: latest alpha version launched in June 2020
* Rom: OxygenOS 10.3.5

## Logcat

 

```
your log here
```

**Comment by fonix232** [comment]
Did you enable the Lawnchair accessibility permissions? You need it for double tap to sleep, as apps without accessibility access cannot put the phone to sleep.

**Comment by thinkgadgetsme** [comment]
Yes, accessibility service is turned on for lawnchair. I have tried turning it off and on again but that doesn't work either.

**Comment by ghost** [comment]
it also happened to my old phone 6 months ago...

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by nalladev** [comment]
https://github.com/LawnchairLauncher/lawnchair/issues/2081#issuecomment-3588656848
