### ISSUE TITLE
[Feature] Add option for a slideshow wallpaper

### ISSUE THREAD

**Issue by tomc128** [Deletescape-Media/Lawnchair#2060]
I'd really love a feature baked into the launcher to create a slideshow of wallpapers which could cycle at a determined interval.

Although there are live wallpaper apps that do this, they do not work with the blur effect in the launcher, so a baked in solution would be far nicer and probably less performance intensive.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
