### ISSUE TITLE
Better compatibility with gestures

### ISSUE THREAD

**Issue by UltraBlackLinux** [Deletescape-Media/Lawnchair#2061]
## Description

Its hard to use the gestures mode, since I just open the dock.

## Expected Behavior

It should trigger the gesture instead of the dock

## Actual Behavior

It opens the dock

## Steps to Reproduce

1. Enable gestures
2. Try to access the opened-apps-list - good luck lol

## Environment

* Device: Razer Phone
* Android version: 10
* Launcher version: 1.2.1.2001
* Rom: LineageOS

## Possible Solution
Make the dock only open, if the swipe starts at a specific y-coordinate

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
