### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by chromer030** [Deletescape-Media/Lawnchair#2062]
Thank you for this lovely and great launcher , it's definitively one of the best.
but is development over ? any new release ?

**Comment by Atulin** [comment]
The last update to any branch was 5 months ago. So, yeah.

**Comment by p3yot3** [comment]
I third this.

**Comment by divadsn** [comment]
https://twitter.com/lawnchairapp/status/1286590567573606400?s=20

**Comment by divadsn** [comment]
Any issue asking for ETAs will be closed with no further comment.

We welcome all pull requests to that branch, with fixes for current bugs, and will try to release alpha builds with them.
