### ISSUE TITLE
Add the ability to have different profiles

### ISSUE THREAD

**Issue by zisis912** [Deletescape-Media/Lawnchair#2064]
Add the ability to have multiple profiles that you can easily switch from one to another. For example, when i feel like it, i just switch a profile and the icon size, widgets, wallpaper, icon pack, and more change. It would be a nice addition.

**Comment by iFUCKINGHATEcomputers** [comment]
That would be a great feature. 
If the backup/restore functions worked well, then it would be possible to use them to save different configurations instead.
Unfortunately they're unreliable (#1198 #1433), and I don't know if that's going to be looked into if development resumes.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
