### ISSUE TITLE
Adjustable Dock Padding

### ISSUE THREAD

**Issue by vsnthdev** [Deletescape-Media/Lawnchair#2065]
## Description
Ability to add some padding to the dock. Below is my home screen for Lawnchair 👇

<a href="https://user-images.githubusercontent.com/24322511/95681571-31cc3f80-0bfe-11eb-8863-5e717c3c3d40.jpg" target="_blank" rel="noopener"><img height="240px" src="https://user-images.githubusercontent.com/24322511/95681571-31cc3f80-0bfe-11eb-8863-5e717c3c3d40.jpg" /></a>

and below is the dock from the stock launcher 👇

<a href="https://user-images.githubusercontent.com/24322511/95681748-39d8af00-0bff-11eb-9385-30780a3565a3.jpg" target="_blank" rel="noopener"><img height="240px" src="https://user-images.githubusercontent.com/24322511/95681748-39d8af00-0bff-11eb-9385-30780a3565a3.jpg"/></a>

## Expected Behavior
A slider for dock width padding 🙂

## Actual Behavior
No way to officially adjust dock padding 😕

## Environment
* Device: Xiaomi Poco X3 "Karna"
* Android version: 10.0.0
* Launcher version: 2.0-2589
* Rom: MIUI 12

I just love this launcher 😍 and kudos 👏 to all the developers. Thank you! 🤗

**Comment by ghost** [comment]
YES, YES, YES, YES, YES. We only have vertical height padding for some reason 😂

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
