### ISSUE TITLE
No apply default lawnchair v. 761

### ISSUE THREAD

**Issue by xmiseggs** [Deletescape-Media/Lawnchair#207]
Version 761. In the "Moto g5 plus" .. does not let it start .. restarting again asks Launcher to apply .. and the widget is deleted

**Comment by xmiseggs** [comment]
http://www.subirimagenes.com/imagedata.php?url=http://s2.subirimagenes.com/imagen/9767892quickscreencapture20.png

http://www.subirimagenes.com/imagedata.php?url=http://s2.subirimagenes.com/imagen/9767891quickscreencapture20.png

**Comment by Treemindr** [comment]
Version 761? I can only download 255.

**Comment by Treemindr** [comment]
NVM I got it.

**Comment by xmiseggs** [comment]
Canal telegram Lawnchair CI

**Comment by intelligentcasanova** [comment]
Still an issue?
