### ISSUE TITLE
You can't directly paste into the Google Search Bar like on Stock Pixel Launcher

### ISSUE THREAD

**Issue by ars4l4n** [Deletescape-Media/Lawnchair#2073]
## Description

When you want to Copy-Paste text into Launchair Launchers Searchbar in the home screen by longpressing it it will just show a "costumize" popup rather than "paste" like the Stock Pixel Launcher does.
You'd have to short-press on it once to be allowed to insert text which is a workflow disadvantage.

## Why I think my suggestion suits better

After shortpressing it, the searchbar will move to the top of the screen so you'll have to "hunt it throughout the screen" with your finger before making your action rather than it just being there. I think that's less intuitive and that the stock launcher is doing it right with this one.

Lastly, considering that you can costumize the bar in the launcher settings page anyway and it isn't a thing you do regularly compared to pasting text into the searchbar I'd consider the "paste"-popup the better option compared to the "costumize"-popup.

## What I tried to circumvent the issue 
I wondered if the issue persists if you use a different searchbar widged/provider
Within the Launchair Launcher searchbar options I tried "Google", "Google App" as well as some other providers
I tried the official Chrome Search Widged and the Google Search Widged. But I never got the expected behaviour.
Third party search widgeds like "Google Go" or "Searchbar Ex" didn't do the trick either.

## Environment

* Device: Google Pixel 3
* Android version: 10
* Launcher version: 2.0-2589

**Comment by RikKoedoot** [comment]
Closing because we're focusing efforts on V11

**Comment by ars4l4n** [comment]
> Closing because we're focusing efforts on V11

do you plan to implement this in v11 though?

**Comment by RikKoedoot** [comment]
I cannot say for sure, will reopen just in case
