### ISSUE TITLE
[Bug] Opening At a Glance settings crashes Launcher

### ISSUE THREAD

**Issue by edapm** [Deletescape-Media/Lawnchair#2077]
## Description
Opening the At A Glance settings through the Lawnchair settings or by clicking customise in the widget menu on the home screen causes the app (launcher and settings) to crash

## Expected Behavior
Opens settings and allows changes

## Actual Behavior
Settings open and go blank, launcher does not respond (only way to stop this is to reboot)

## Steps to Reproduce
1. Open Lawnchair Settings
2. Click "At A Glance"

## Environment
* Device: Xiaomi Redmi 9
* Android version: 10.0.0
* Launcher version: 2.0-2589
* Rom: MIUI 11.0.9

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
