### ISSUE TITLE
Doesn't Render Properly In Splitscreen

### ISSUE THREAD

**Issue by Phuntis** [Deletescape-Media/Lawnchair#2078]
When in split screen it renders as though the navbar isn't there making the search bar render and bottom of the drawer appear underneath the navbar

**Comment by RikKoedoot** [comment]
What version of lawnchair is this? And could you show a screenshot?

**Comment by Phuntis** [comment]
I can't reproduce it now but I could in the past so I'm gonna say it was somehow accidentally fixed since then or maybe it just doesn't happen on newer android versions as I'm on the latest Android beta sorry
