### ISSUE TITLE
Accessibility service status is not recognised

### ISSUE THREAD

**Issue by thinkgadgetsme** [Deletescape-Media/Lawnchair#2081]
## Description
I have configured double tap to sleep. Accessibility service is enabled to enable this feature. However, Lawnchair doesn't recognise that the service is enabled and prompt to enable accessibility service again and again.

## Expected Behavior
Sleep mode should be activated.

## Actual Behavior
Sleep mode is not activated. User is asked to enable accessibility service repeatedly.

## Steps to Reproduce
1. Access Lawnchair settings, navigate to Gestures - Double Tap - Sleep
2. Come back to Home screen
3. Double tap to activate sleep mode

## Environment
* Device: OnePlus 6t
* Android version: 10.0
* Launcher version: 2.1-2627-ci-q-merge
* Rom: Oxygen OS 10.3.8

**Comment by BobSaiyaman** [comment]
I have the same issue. Just keeps opening the accessibility menu when I double tap to sleep. 

Xiaomi Redmi Note 9 Pro. 
MIUI 12.0.2.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by nalladev** [comment]
Same issue here — Accessibility permission shows as granted, but the feature only works again if I toggle the permission off and back on.
on Samsung Galaxy M21
