### ISSUE TITLE
New Splitscreen Bug

### ISSUE THREAD

**Issue by Phuntis** [Deletescape-Media/Lawnchair#2082]
When in splitscreen while using 2 or 3 button nav the dock shortcuts display behind the dock search bar

![Screenshot_20210221-211133.png](https://user-images.githubusercontent.com/78653137/108708659-a21e9200-7509-11eb-9cc3-fe6ccd962996.png)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
