### ISSUE TITLE
At a Glance Splitscreen Sizing Issue

### ISSUE THREAD

**Issue by Phuntis** [Deletescape-Media/Lawnchair#2083]
When in splitscreen the at a glance widget appears smaller than in fullscreen

![Screenshot_20210222-152520.png](https://user-images.githubusercontent.com/78653137/108729207-31d03a80-7522-11eb-8767-79928ab19e66.png)
![Screenshot_20210222-152250.png](https://user-images.githubusercontent.com/78653137/108729133-21b85b00-7522-11eb-8736-87627c8f4d79.png)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
