### ISSUE TITLE
App drawer "number of columns" not changing

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2084]
## Description

I just want to change the number of columns in app drawer

## Expected Behavior

Number of columns should change to 3

## Actual Behavior

Doesn't change
![IMG_20210223_080518](https://user-images.githubusercontent.com/59839368/108796233-4528e780-75ae-11eb-9d6c-b9d81563ebc4.jpg)
![IMG_20210223_080533](https://user-images.githubusercontent.com/59839368/108796237-4823d800-75ae-11eb-8e21-608f6854d8bc.jpg)

## Steps to Reproduce

1. Settings
2. App drawer
3. Change Number of Columns
4. See app drawer

## Environment

* Device: Redmi Note 7
* Android version: 10
* Launcher version: 10.0 Alpha 8
* Rom: MIUI 12.0.2

## Logcat

 

None

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
