### ISSUE TITLE
App drawer animation bugging when exiting apps with gestures on

### ISSUE THREAD

**Issue by Dzikucpedal** [Deletescape-Media/Lawnchair#2086]
## Description
When you open an app in the app drawer, then exit it using the gesture from the bottom of the screen, the app drawer closing animation quickly happens before going back to home screen.

## Expected Behavior
When you open an app and then exit it, it should go back to home screen animation instead of app drawer and then home screen animation, as it is in OneUI and I think many other launchers.

## Actual Behavior
As stated above. The app drawer closing animation kind of flickers quickly.

## Steps to Reproduce
1. Open app drawer
2. Open any app
3. Exit the app (using home screen gesture from the bottom of the screen)

## Environment
Device: Samsung Galaxy S20 FE 5G
Android version: 11.0
Launcher version: Lawnchair 10 Alpha 8
Rom: OneUI 3.1

**Comment by RikKoedoot** [comment]
Closing because we are focusing efforts on lawnchair V11
