### ISSUE TITLE
At A Glance widget should open up local weather app, if available

### ISSUE THREAD

**Issue by omentic** [Deletescape-Media/Lawnchair#2089]
## Description
Tapping the weather portion of the At A Glance widget should open up an installed weather app if possible.

## Expected Behavior
The expected behavior would be for Lawnchair to try to open a weather app, and if that doesn't exist, open up a page in a browser.

## Actual Behavior
Lawnchair launches Accuweather (or any other weather provider) in a new browser window and doesn't check for installed weather apps.

## Steps to Reproduce

1. Install a weather app and Lawnchair launcher
2. Place the "At a Glance" widget on the homescreen and set it up to show the weather.
3. Tap the left side date and observe it opens the calendar.
4. Tap the right side weather and observe it opens up a new browser window.

## Environment

* Device: Pixel 4a
* Android version: 11
* Launcher version: 2.0-2589
* Rom: GrapheneOS

**Comment by SuperDragonXD** [comment]
This issue (feature request really) will now be tracked on #2626. Therefore closing this issue.
