### ISSUE TITLE
Drawer fade in with transparent dock

### ISSUE THREAD

**Issue by LorenzBischof** [Deletescape-Media/Lawnchair#209]
It seems drawer fade in while swiping up broke between version 616 and 625. This only happens when transparent dock is enabled. Still a problem in 766.

**Comment by suphon-t** [comment]
Can you post a video? I can't reproduce the issue from my end.

**Comment by LorenzBischof** [comment]
https://youtu.be/s8OOIm8eGQw It works fine if I enable blur
