### ISSUE TITLE
[Feature Request] Option to optionally disable app drawer

### ISSUE THREAD

**Issue by mmoole** [Deletescape-Media/Lawnchair#2096]
## Description
This is a feature request for adding an option to disable the app drawer. Like this, it would have the app using only the so called Desktop and all apps would then land there.
This would enhance simplicity for users (then there would be only one location for starting a specific app) and even attract more users.
Also there are some launches that offer this as a feature, and people even teamed up to fork for 'Lawndesk' which has this feature.
Incorporating the option directly in the app would reduce variants of Lawnchair and more users would be attracted to switch over from other proprietary launchers that offer this feature like from Samsung etc...

## Expected Behavior
The user can tick/untick the option 'Disable App Drawer (all Apps are moved to desktop)'
If this is activated, then the user can no more navigate to the app drawer. All apps that where previously only displayed in the app drawer but not on the desktop will then be added at the right hand 'end' of the desktop, thus adding more pages if needed.

## Actual Behavior
An option like this is not present.

## Additional Comments
Another option to think about would be 'Disable Home Screen' since that is also a feature that people are looking for in a launcher. I would suggest to make this available as a feature, too.
Like this Lawnchair would stand out in the competition because it would be suitable for a broader base of users and like this also gain more fans.
But if Lawnchair offers both variants, then it would make more sense to have a choice like 'Launcher Operating Mode':
* Desktop and App Drawer
* Desktop only
* App Drawer only

**Comment by JoshuaACasey** [comment]
Additional app drawer feature request: I would love the ability to have folders in the app drawer. It's the one feature from nova launcher that I WISH existed in the default launcher (pixel launcher since I have a pixel phone). I personally hate how I have to scroll in the app drawer to find the app I want because it's not organized into folders

**Comment by Darthagnon** [comment]
I would love an option to disable the App Drawer, too. The abandoned Lawnchair fork, [Lawndesk](https://github.com/renzhn/Lawndesk), disables the app drawer. I'm not sure about Omega Launcher (which is based off Lawnchair if I remember rightly).

Related issues: #2381, #2394

**Comment by CyberShadow** [comment]
Bump, currently I use Lawndesk, but it would be cool to have it in an actively maintained open source launcher.

**Comment by topsy-turvy99** [comment]
#2394

**Comment by Amorphous404** [comment]
Duplicate Of #2096?

**Comment by odmfl** [comment]
you can try the following app https://github.com/Launcher3-dev/MXLauncher/releases/tag/0.0.1

it's hard work but it's been implemented in this launcher works well
it is in Chinese but in the end it is understood.
We would have to adapt it here
The commits are as follows:
https://github.com/Launcher3-dev/MXLauncher/commit/6c21cd43e3ba6369ff9a7c6c87aed7cd3645342a
https://github.com/Launcher3-dev/MXLauncher/commit/135b469bb1a49a67a8851111ac0585cff9ddcdb2
https://github.com/Launcher3-dev/MXLauncher/commit/cf16de5b2a60d9ffbc902350e4a0178f72117ed6
https://github.com/Launcher3-dev/MXLauncher/commit/10ad298dd4e1a9b46d0147b7ec7f25495176b744

**Comment by SuperDragonXD** [comment]
Well you can "disable" the app drawer using a workaround:

Simply change the "Swipe Up" gesture to not launch the app drawer. Then you technically can't access it now.

**Comment by CyberShadow** [comment]
> Simply change the "Swipe Up" gesture to not launch the app drawer.

This is only meaningful if bundled together with a guarantee that all apps are reachable from the desktop (like on an iPhone). That's the hard part.

**Comment by odmfl** [comment]
It's difficult, but there are commits that you can follow, in the end it was implemented on a stock launcher3, so if it works there, it should work here too, it's a lot of work but it can be done.  We are hoping for devs, or some PR

**Comment by Darthagnon** [comment]
Related: https://github.com/LawnchairLauncher/lawnchair/issues/3068

A pity that this feature is not planned; a good drawer-less launcher is still sorely lacking for Android, especially as Nova (which could be configured drawerless in a hacky way) [went bad](https://www.ghacks.net/2022/07/19/nova-launcher-and-sesame-search-have-been-acquired-by-branch/).

**Comment by kipusoep** [comment]
Still looking for something like this today.

**Comment by gurmeetim** [comment]
> Still looking for something like this today.

It available in nighlty version please check

**Comment by kipusoep** [comment]
Ah yes I see, thanks for the heads-up @gurmeetim!
I installed it, but swiping through the different home screen pages stops working for some reason.
Going back to page 1 using the navigation button fixes it, but any clue what's going on?

**Comment by gurmeetim** [comment]
> Ah yes I see, thanks for the heads-up [@gurmeetim](https://github.com/gurmeetim)! I installed it, but swiping through the different home screen pages stops working for some reason. Going back to page 1 using the navigation button fixes it, but any clue what's going on?

It is expected as it is in initial phase.its added recently. Ther r some bugs .have to wait for fixed by the devs

**Comment by kipusoep** [comment]
Yeah no problem. It was kind of hard to get to the last pages (it created 8 pages or so), but when I'm done grouping and moving everything I will only have 3, so if it's stuck then, that's not a big issue.

**Comment by MrSluffy** [comment]
closing this : dd3725c30d8a974e9651cbe29074689201658d40
