### ISSUE TITLE
Weather Widget isn't working

### ISSUE THREAD

**Issue by JuliGplus** [Deletescape-Media/Lawnchair#21]
Isn't it possible to have the weather instead of displaying the date in the Homescreen?
In the normal Pixel Launcher it works...

Thx

**Comment by deletescape** [comment]
With the code from Pixel Launcher weather only work when the app requesting it is Pixel Launcher. I will try to make my own custom implementation of the weather display in the future

**Comment by RWOne** [comment]
Why not change the app name and allow it's weather to display, seems easier...

**Comment by TokedUp** [comment]
Oh please make this work. This launcher would be perfect with it. For some reason I can't live without this widget

**Comment by shashikant-ng2** [comment]
First, Thank you very much for this cool launcher. Eagerly waiting for the weather widget to be working.. Amir did it int he launcher 3 and it was working...

**Comment by deletescape** [comment]
@shashikant-ng2 Amir is using the Pixel Launcher package name for his launcher (which I won't and can't do) which is what made this work. A custom implementation is coming soon though

**Comment by shashikant-ng2** [comment]
That would be great... Thank you.. 😊

**Comment by lpen21** [comment]
Can just use Chronus which has a Pixel widget and date that can be customized to look pretty close to Pixel style. That widget has options for dark sky, weather underground and a few other providers and it's pretty stable.

**Comment by shashikant-ng2** [comment]
But that doesn't match the pixel weather widget...

**Comment by lpen21** [comment]
You can customize it to look like the pixel pill or 2-3 different options.

**Comment by marco136** [comment]
Above you stated you would implement a fix soon which was about 25 days ago. Just wondering where the ETA is on this item. Thanks for the good work you have done so far.

**Comment by philgood** [comment]
Any further updates with getting the weather Incorporated?

**Comment by lpen21** [comment]
Yes weather implemented in version 962
You can get link on page 123 of Lawnchair thread XDA. Once installed you
need to allow permission for location to Lawnchair and you can then choose
Google weather as the provider. Still kind of buggy in my opinion so I'm
still using Chronus Pixel widget. The current widget refreshes a bit slow
for my taste.
