### ISSUE TITLE
Mismatched icons

### ISSUE THREAD

**Issue by MspMarik** [Deletescape-Media/Lawnchair#210]
![img_20170715_133521](https://user-images.githubusercontent.com/30062050/28241454-c85082aa-6962-11e7-9489-11b4128a0ce9.png)
As shown here the "Play Games" icon does not match the other "Play" icons. Has this been fixed? Or is this an issue with my phone's theming conflicting with the theming of the launcher? I have Huawei Honor 6x Android 7.0.

**Comment by suphon-t** [comment]
Google's problem for not adding a rounded version of the icon.
