### ISSUE TITLE
[Bug][11 dev]Icon change doesn't works correct

### ISSUE THREAD

**Issue by Pandemic-XDA** [Deletescape-Media/Lawnchair#2102]
Icon pack changer works not so good on 11 dev build like on lc for a10
Example: when you download glass icon pack by ambor here
https://play.google.com/store/apps/details?id=com.ambor.iconpack
It changes on previous lawnchair but not on the dev 11 build.. I tested it.
Hopefully it can be fixed because on previous version of lc like 9.1 alpha 3 it works fine. 
Test it also please then you will see :)

**Comment by Pandemic-XDA** [comment]
Any dev looking into this ? 😊

**Comment by msfjarvis** [comment]
You'll be informed when they are. Spamming the issue asking why your vaguely worded 'bug' isn't being triaged on priority doesn't help anything.

**Comment by Pandemic-XDA** [comment]
> You'll be informed when they are. Spamming the issue asking why your vaguely worded 'bug' isn't being triaged on priority doesn't help anything.

Oke and sorry mate, i understood 😊👌

**Comment by RikKoedoot** [comment]
Does this still occur?

**Comment by Pandemic-XDA** [comment]
> Does this still occur?

Yes

**Comment by RikKoedoot** [comment]
closing this issue as this is not a lawnchair issue.
