### ISSUE TITLE
Lawnchair 11 on Android 10

### ISSUE THREAD

**Issue by sbs8331** [Deletescape-Media/Lawnchair#2106]
Just installed Lawnchair 11 on my Moto G7 Power running Android 10.  It installed but gets a forced close when trying to load.  I know your Telegram announcement said it hadn't been tested on earlier versions, so I thought I'd give it a try.  Thanks.

**Comment by Pandemic-XDA** [comment]
Its for android 11 and not 10 ! Clearly mentioned.

**Comment by sbs8331** [comment]
I knew it hadn't been tested but missed that it was exclusive to 11.  Apologies.  Just thought I'd give it a try.

**Comment by sbs8331** [comment]
> Its for android 11 and not 10 ! Clearly mentioned.

I knew it hadn't been tested but missed that it was exclusive to 11.  Apologies.  Just thought I'd give it a try.

**Comment by chromer030** [comment]
@Pandemic-XDA , If it's only for android 11 , so why minimum android target is set on 9 ? (Min: Android 9.0 (Pie, API 28))

**Comment by sbs8331** [comment]
Actually, in reviewing the Telegram announcement, it's not clear that the release is only for Android 11, only that it's been tested on just 11.  I was trying to help, so I hope the somewhat snarky post above isn't indicative of how those who are willing to help test will be responded to going forward.

**Comment by suphon-t** [comment]
Hey, @sbs8331. I'm sorry for the rude comment by the person above. You are correct to understand that the release is not only for 11, but it's only tested on 11. 

In your case of force closing, please send a stack trace of the crash. It will be very helpful for debugging.

**Comment by sbs8331** [comment]
> Hey, @sbs8331. I'm sorry for the rude comment by the person above. You are correct to understand that the release is not only for 11, but it's only tested on 11.
> 
> In your case of force closing, please send a stack trace of the crash. It will be very helpful for debugging.

I have the stack trace (53 MB) in Dropbox.  Not sure how to send to you.  Can't drop it here.  Thanks.

**Comment by divadsn** [comment]
> > Hey, @sbs8331. I'm sorry for the rude comment by the person above. You are correct to understand that the release is not only for 11, but it's only tested on 11.
> > In your case of force closing, please send a stack trace of the crash. It will be very helpful for debugging.
> 
> I have the stack trace (53 MB) in Dropbox. Not sure how to send to you. Can't drop it here. Thanks.

Create a share link and send it to us via pm on Telegram or attach to an email and send to bugreport(äŧ)lawnchair.info

**Comment by ghost** [comment]
Lawnchair 11 will have support for older Android versions. But atm, you could use Lawnchair 2. 🙂

**Comment by chromer030** [comment]
@yusefyebra , could you please tell us which Android versions ?

**Comment by ghost** [comment]
@chromer030 I believe Android 10 and 9 would have support for L11. I'm not sure about Android 8 because I don't know the minimum API Level.
