### ISSUE TITLE
Dragging icons around causes stutter

### ISSUE THREAD

**Issue by Sidewinder53** [Deletescape-Media/Lawnchair#211]
Whenever I'm moving an icon on my homescreen, it becomes stuck for a few seconds as soon as I move over another app or touch other UI elements. I'm on a Nexus 5 (16GB) with stock ROM and no other modifications.

Here's a quick screen-recording of the issue: https://streamable.com/gby36

**Comment by LinuxLlama** [comment]
This has been fixed in a beta update. If you join the beta channel with Telegram you can use it.
