### ISSUE TITLE
[BUG] Editing tab under Categorization with tabs on OnePlus 6T on OxygenOS(10.3.9) causes the "Work" tab(s) in the list to duplicate.

### ISSUE THREAD

**Issue by SscSPs** [Deletescape-Media/Lawnchair#2110]
So, I encountered this bug while browsing randomly though settings, 
Here is telegram(lawnchair help group) link where I shared the video of reproducing this bug: https://t.me/lccommunity/535165
I went through the code to find out why its happening, 
I've only tested it on my phone(OnePlus6T, OOS 10.3.9), Someone else tested it on one other device(not sure which one) and they didn't face this issue.
Here are my findings:

[Here](https://github.com/LawnchairLauncher/Lawnchair/blob/10-alpha/lawnchair/src/ch/deletescape/lawnchair/groups/DrawerTabs.kt#L260) ```obj.put(KEY_ID, user.toString().replace("\\D+".toRegex(), "").toLong())``` we create a toString for Profile object, we use the user's toString() to get the identifier.

[Here](https://github.com/LawnchairLauncher/Lawnchair/blob/10-alpha/lawnchair/src/ch/deletescape/lawnchair/groups/DrawerTabs.kt#L68) ```val profile = Profile.fromString(context, type.substring(TYPE_PROFILE_PREFIX.length))``` we try to get Profile object fromString(reverse of toString, theoretically), it calls a different method,  ```UserManagerCompat.getInstance(context).getUserForSerialNumber(obj.getLong(KEY_ID))``` [here](https://github.com/LawnchairLauncher/Lawnchair/blob/10-alpha/lawnchair/src/ch/deletescape/lawnchair/groups/DrawerTabs.kt#L285)

Where it gets the output from a cached map of serial->User, which is filled in at [UserManagerCompatVNMr1.enableAndResetCache()](https://github.com/LawnchairLauncher/Lawnchair/blob/10-alpha/src/com/android/launcher3/compat/UserManagerCompatVNMr1.java#L109)

Now the regex out from toString for User gets a different output than ```mUserManager.getSerialNumberForUser(user)```(used in enableAndResetCache) on my device(OOS 10.3.9, and possibly others as well), this causes it to be treated as a new tab added(and i'm not sure what else)

One solution is to update UserManagerCompatVNMr1's enableAndResetCache() and use the same regex to get the serial for user to put in map, But this userCache is used in other places as well, so need to look at what else will be affected and how.
Other solution is to call the ```mUserManager.getSerialNumberForUser(user)```(same as used in enableAndResetCache) in profile's toString rather than doing the string reading. and then get the User object from userCache.

**Comment by RikKoedoot** [comment]
closing this issue as we are working on v12 only, this does not have this issue.
