### ISSUE TITLE
Desktop Folder does not change color as theme

### ISSUE THREAD

**Issue by Ali5001** [Deletescape-Media/Lawnchair#2118]
Folder in desktop always be in dark mode even if i am using white theme full launcher is white but folder is dark

![Screenshot_20210330-203105202](https://user-images.githubusercontent.com/81635058/113007736-4a261b80-9198-11eb-9364-4308c69d1e01.jpg)

It's a small bug but it is kinda irritating... 

Thanks

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
