### ISSUE TITLE
Shortcut tab is somewhat off-screen

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#212]
Take a close look at these pictures:
![screenshot_2017-07-15-08-12-48](https://user-images.githubusercontent.com/29732079/28244330-0ec41492-69b6-11e7-86cf-ffd409b29b47.png)
![screenshot_2017-07-15-08-12-59](https://user-images.githubusercontent.com/29732079/28244331-164085f2-69b6-11e7-8b4e-7f38076ed2b4.png)
![screenshot_2017-07-16-19-24-05](https://user-images.githubusercontent.com/29732079/28252193-6a0845e8-6a5c-11e7-9dc5-60a919d35362.png)
(3rd photo is from v818)

Plus, to remind you, the icons and their text in folders do not change when the icons and text are resized

**Comment by Dondrejohnson5** [comment]
Also, I'm seriously missing out on Nougat app shortcuts on my Lollipop device. Again, Nova Launcher is a perfect example

**Comment by guest4711** [comment]
Works for me (1.1.1258)
