### ISSUE TITLE
Sort apps inside folders

### ISSUE THREAD

**Issue by Rootzpower** [Deletescape-Media/Lawnchair#2120]
Hello,

It's possible to implement an option to sort alphabetic apps inside folders?

Scenario:

We add folder in main screen and start adding apps with no sort.
1 chrome 
2 whatsapp
3 Spotify 

If we add a option to sort alphabetic the apps will display like this:
1 chrome
2 Spotify 
3 whatsapp

Without this option if we add others apps later will be messy alfaphedic

**Comment by meistr91** [comment]
But you can rearrange apps manually in the desktop folders, which is more handy feature

**Comment by Rootzpower** [comment]
Several launcher have that option. It's very useful.

**Comment by Amorphous404** [comment]
> Several launcher have that option. It's very useful. 
Please add you comment on #2843,and if possible close this, to help reduce same request tickets, i requested some extra tweaks related to folder aswell.

**Comment by Rootzpower** [comment]
https://github.com/LawnchairLauncher/lawnchair/issues/2843
