### ISSUE TITLE
Arrange pages non-functional

### ISSUE THREAD

**Issue by Oplopanax-horridus** [Deletescape-Media/Lawnchair#2121]
This applies to Android 11 on Pixel 4a, Lawnchair 2.0-2589.

In the arrange pages screen, I cannot drag pages to rearrange, nor do have the option to add a new page. Also, from the home screen, dragging an icon or widget to the edge does not trigger a new page as it used to.

At the same time that I attempted to rearrange pages (entered the arrange pages screen) multiple folder icons on the home screen began displaying a small black dot/circle over the upper right corner of the icon. This applies to some, but not all, folder icons.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
