### ISSUE TITLE
Scrollbar in drawer "remembers" apps' unedited names, causing e.g. ...C, D, T, D, E...

### ISSUE THREAD

**Issue by YoshiRulz** [Deletescape-Media/Lawnchair#2123]
Renaming "Phone" to "Dialer", for example, will move it up to the D apps, but long pressing the scrollbar shows an extra, misplaced T group.

Lawnchair 2.0-2589 from Google Play Store
LineageOS 17.1-20201208-NIGHTLY (Android 10, Linux 4.9)
OnePlus 6 "enchilada"

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
