### ISSUE TITLE
[Feature request] Have scrollbar in drawer only scroll to focused app when offscreen

### ISSUE THREAD

**Issue by YoshiRulz** [Deletescape-Media/Lawnchair#2124]
...instead of the current behaviour, which is trying to scroll so the focused app is at the top of the screen. I think not scrolling the screen unless necessary would be a nicer UX.

Lawnchair 2.0-2589 from Google Play Store
LineageOS 17.1-20201208-NIGHTLY (Android 10, Linux 4.9)
OnePlus 6 "enchilada"

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
