### ISSUE TITLE
BIG PROBLEM. Square Button -  Recent Apps  not working.   

### ISSUE THREAD

**Issue by goyetus** [Deletescape-Media/Lawnchair#2126]
I cant use Lawnchair 2  (I really love it) .  

Problem:
In Miui 12  and Android 11  ,    when you press the Square Button,  screen is 100% Empty. 
You can not move between open apps  with this bug,  so I have to uninstall Lawnchair.

Working fine in MIUI 12 and Android 10. 

I tryed:
- Give all permission from MIUI 
- Delete cache 
- Restart several times
- Install last version from Playstore
- Install last beta version from apkmirror

Please,  fix the problem.   
Any way I can help?

Regards!!

**Comment by RikKoedoot** [comment]
I'm not sure but it might be an issue with miui itself, what version number of lawnchair are you using? (Settings>about)

**Comment by RikKoedoot** [comment]
Closing because it is in fact a miui issue
