### ISSUE TITLE
[Feature Request] Cover-like gestures for folders in Lawnchair 11

### ISSUE THREAD

**Issue by rodrigost23** [Deletescape-Media/Lawnchair#2128]
This is already a feature in Lawnchair 9 and 10, but it's missing from 11 rewrite. I don't know if all features from V2 is going to be present in the new version, but this is the one feature that's keeping me from moving.

(See #1479)

**Comment by RikKoedoot** [comment]
the intention is to add all features to v11

**Comment by vaisakhv** [comment]
Please do add this feature. This is forcing me to roll back to lawnchair v2 or use another launcher like Nova.

**Comment by VictorVow** [comment]
Still relevant.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Still relevant.



> 

👍

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Still relevant.

**Comment by VictorVow** [comment]
Bump.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Remove stale label

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Remove stale label

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Remove stale label

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> This is already a feature in Lawnchair 9 and 10, but it's missing from 11 rewrite. I don't know if all features from V2 is going to be present in the new version, but this is the one feature that's keeping me from moving.
> 
> (See [#1479](https://github.com/LawnchairLauncher/lawnchair/issues/1479))


Yes, the feature exist in Lawnchair Legacy version 9.1 alpha 3

This older request appears to be tracked by #2659 now, as Cover Mode was available in older Lawnchair versions but still does not seem to be present in current releases.

- #2659
