### ISSUE TITLE
Widget selection screen background

### ISSUE THREAD

**Issue by ankurk91** [Deletescape-Media/Lawnchair#213]
Hi,
Widget selection screen colors are not expected.

#### Current screen
![current-screen](https://user-images.githubusercontent.com/6111524/28244373-235171c4-6a07-11e7-9421-4bf9188819d2.png)

#### Expected screen
![expected-screen](https://user-images.githubusercontent.com/6111524/28244375-34f3100e-6a07-11e7-94fb-6a95e447257b.png)
Above screen taken from **amirzaidi/Launcher3**

- Lawnchair v255
- Moto g4 play
- Android 6.0.1

If this has been fixed then please (pre) release a new version.
Thanks.

**Comment by nyancrimew** [comment]
Just because something looks different in a pretty much unrelated launcher this doesn't mean it is broken and needs to be fixed

**Comment by nyancrimew** [comment]
We'll look at it though
