### ISSUE TITLE
Relicensing to Apache 2.0

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2132]
With input from @msfjarvis, I suggest we relicense Lawnchair 11 to Apache 2.0 to streamline the inclusion of the Launcher3 source code in Lawnchair. This change requires written approval from all contributors. @AgentFabulous, @SphericalKat, and @msfjarvis – please comment on this Issue and let me know if you agree. Cheers!

**Comment by SphericalKat** [comment]
I agree, I prefer permissive licenses in general

**Comment by msfjarvis** [comment]
I agree to have my changes relicensed under Apache 2.0

**Comment by AgentFabulous** [comment]
Fine by me! Apache 2.0 it is.

**Comment by ghost** [comment]
Thanks, everyone! I am now locking this conversation.
