### ISSUE TITLE
[Feature request] Home screen only

### ISSUE THREAD

**Issue by Pantyhose-X** [Deletescape-Media/Lawnchair#2134]
Home screen only
* All your apps will be shown on the Home screen.
* Show all apps on home screen
![Screenshot_20210427-093745](https://user-images.githubusercontent.com/42504385/116172999-df004280-a75f-11eb-8048-50c44f2308ca.jpg)

**Comment by fs1995** [comment]
I agree this would be a nice feature. I don't believe any open source launcher has a home screen only option, which is one of the few things I miss about iOS.

**Comment by ghost** [comment]
This actually is a good feature for people that don't like app drawers!

**Comment by Elsie19** [comment]
> I agree this would be a nice feature. I don't believe any open source launcher has a home screen only option, which is one of the few things I miss about iOS.

I believe the Bliss launcher has the option. It's very iOS like
