### ISSUE TITLE
default search bar ripple effect behavior 

### ISSUE THREAD

**Issue by hpnightowl** [Deletescape-Media/Lawnchair#2148]
## Current Behavior
- This is how our current behavior looks like while tapping it is like  a rectangle  as you can see here in this image https://imgur.com/BCndKQB

## Expected Behavior
- this should be expected as shown in this picture https://imgur.com/Pt60qHE

## Possible Solution
- By creating a background with a mask for Search Bar separately  (you can check the #possible implementation  commit)

## Context (Environment)
- default aosp Search bar  ( non golang environment)

## Possible Implementation
- One of the possible implementation that i did is this https://github.com/hpnightowl/lawnchair/commit/f50e71e6141880709ed8b06d96c70b99a3fb7f3d (https://imgur.com/Pt60qHE)

**Comment by etahamad** [comment]
![Screenshot_20210513-071656](https://user-images.githubusercontent.com/53538887/118081254-40105300-b3bb-11eb-8f89-4d67774e9854.png)
+ ^

**Comment by hpnightowl** [comment]
@etahamad my bad , didn't get you, can you explain briefly? are you talking about width not matching or overlapping?

**Comment by ghost** [comment]
Thanks for reporting!

**Comment by ghost** [comment]
I’ve fixed the bug using `setClipToOutline`; see commit 541d74c. @etahamad – would you be able to open a separate Issue for the problem shown in your screenshot?

**Comment by etahamad** [comment]
![Screenshot_20210513-164648~2](https://user-images.githubusercontent.com/53538887/118143047-37476d80-b40b-11eb-906d-541f039d885a.png)
are you sure? 
*latest gh actions build*

**Comment by etahamad** [comment]
actually it does fixed with the default search bar, but it's still the same with Google Go's search bar.
