### ISSUE TITLE
RTL quickstep issue

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2150]
# Current  Behavior
When trying to scroll to the previous app, that's go the right, with an RTL language (like Arabic) it does not actually let you scroll there (see recording) 
https://user-images.githubusercontent.com/29402532/118392105-07c97880-b638-11eb-8f5b-f1de55bcf281.mp4

# Expected Behavior
Being able to scroll to the right

# Context (Environment)
RTL enabled
Lawnchair 11 Alpha 4

**Comment by thatAkiraFox** [comment]
Still happening on v11 Alpha 5 but now the dock search bar also becomes unaligned (shifts to the left).

**Comment by Abdu11ahAS** [comment]
This issue started happening from v11 alpha 4 (when the "clear all" button got added) , every was fine before
