### ISSUE TITLE
[Feature Request][QuickSwitch] Thumbnail switcher instead of big card

### ISSUE THREAD

**Issue by isral** [Deletescape-Media/Lawnchair#2154]
Current android task switcher (recent apps) only show 1 big task.
It will be more useful if the tasks are small (in grid?) so I can see a lot of tasks in 1 screen.
Thanks.

**Comment by RikKoedoot** [comment]
This would be very hard, i don't think it would be done but keeping it open just in case

**Comment by isral** [comment]
@RikKoedoot 
I tried Lawnchair 12.1.0 Alpha 4 using smallest width 600dp (simulate 7" tablet) on LineageOS 20 (Android 13).
It show 2 rows of recents apps.
Can I ask the feature to be available on phone (smallest width < 600dp)?
Thanks

Edit: Sorry, I just read: "This repository is currently in maintenance mode".
