### ISSUE TITLE
Crash when trying to toggle "show at a glance widget"

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2158]
# Current  Behavior
Crash

# Expected Behavior
Enable/disable the at a glance widget
 
# Screenshot and/or log
https://del.dog/attorrirfu
https://user-images.githubusercontent.com/29402532/120678631-96dbea80-c498-11eb-9a93-f46f596f64b2.mp4
# Context (Environment)
Lawnchair Version 11.0-alpha.4+3bf8b97.debug

**Comment by RikKoedoot** [comment]
# Current Behavior
Crash

# Expected Behavior
Enabling or disabling the searchbar

# Screenshot and/or log
https://del.dog/unisyrapim
https://photos.app.goo.gl/LufwVVZv55dCZi5J8

# Context (Environment)
Lawnchair Version 11.0-alpha.4+3bf8b97.debug
Might be related to #2158

**Comment by RikKoedoot** [comment]
I'll be adding all crashes I find here as they seem to be the same thing

**Comment by RikKoedoot** [comment]
Home screen columns: https://del.dog/ebololyrfa
Home screen rows:
https://del.dog/nanufeliph
Home screen icon size:
https://del.dog/xuturofagh
Home screen label size: https://del.dog/fullalylle
Dock grid:
https://del.dog/ivunugorul
Drawer grid:
https://del.dog/wogruxerri
Drawer icon size:
https://del.dog/iposymicyl
Drawer label size:
https://del.dog/lonucysili
Folder max rows:
https://del.dog/stuckucose
Folder max columns:
https://del.dog/lerolekiro

They seem to all be the same but to be sure I added them all

Also for some after slider bars they get stuck in between the snapping points after crashing
![Screenshot_20210603-184415.jpg](https://user-images.githubusercontent.com/29402532/120681741-fab3e280-c49b-11eb-97bc-fdba7f5572fe.jpg)

**Comment by suphon-t** [comment]
Fixed in 72166d3.
