### ISSUE TITLE
Bug: not always opening accessibility settings

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2160]
# Current  Behavior
After double tapping and pressing "open settings" it doesn't always open accessibility settings, I found when lawnchair's app info page is opened in the background it opens that instead of the accessibility menu

# Expected Behavior
It'd open accessibility always
 
# Screenshot and/or log
https://photos.app.goo.gl/ZmnaHoFPrYQNzUhH7

# Context (Environment)
Lawnchair Version 11.0-alpha.4+3bf8b97.debug

**Comment by suphon-t** [comment]
I'm not sure if there's a way to fix this. We just send the accessibility settings intent and the rest is up to the system.
