### ISSUE TITLE
Bug: unable to hide google wallpapers

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2161]
# Current  Behavior
Google wallpapers does not show up in the hide app list

# Expected Behavior
it does show up
 
# Screenshot and/or log
![IMG_20210603_203313_478.jpg](https://user-images.githubusercontent.com/29402532/120694950-0eb31080-c4ab-11eb-9fd0-6e3691aa9ebe.jpg)
![IMG_20210603_203315_352.jpg](https://user-images.githubusercontent.com/29402532/120694962-11ae0100-c4ab-11eb-92c2-72524c69afef.jpg)

# Context (Environment)
Version 11.0-alpha.4+4cd1921.debug

**Comment by suphon-t** [comment]
It's supposed to be hidden by default, but the default app filter failed to instantiate. Fixed in fd23b44.
