### ISSUE TITLE
minWidth & minHeight are lost when an Widget with a configure activity is added 

### ISSUE THREAD

**Issue by mohand1993** [Deletescape-Media/Lawnchair#2162]
When adding an Widget that has a configure activity it's minWidth and minHeight attributes are getting lost, causing the Widget to get minimized beyond these limits if been moved (after already being placed) somewhere where it doesn't fit

**Comment by Y0191** [comment]
I would add one issue to this, there is a problem in A11, when adding a widget that is supposed to be 4x1 (length x height), it is added as 4x2.
There is unfortunately no way to drag its height up or down (see the screenshot, you can only drag left or right)![photo_2021-06-05_21-33-11](https://user-images.githubusercontent.com/85409786/120901824-afd5ce80-c645-11eb-9456-5eed622205f3.jpg)

**Comment by RikKoedoot** [comment]
Could you tell me what app that is, and your grid size? as i just tested it with a 4x1 widget and this does not occur for me (this being the 4x1 widget becoming a 4x2 widget)

**Comment by Y0191** [comment]
Sure, app is Yandex Weather (https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin), my grid size is 4x7.  Even in the preview section this widget's name says '4x1'. Though I clearly recall the vertical size option was present when I used the LawnChair for A10 on my previous phone.

**Comment by RikKoedoot** [comment]
You are right about the rescaling of widgets, that is just the default L3 behavior now, I guess the old lawnchair behavior will be implemented later. Ill try the widget and see if this happens for me too

**Comment by Y0191** [comment]
Thank you for the information! Glad this is not a specific app bug, hope the devs will correct it soon.

**Comment by RikKoedoot** [comment]
I just tested the widget, on my default grid (4x5) it reads that it is a 4x1 widget, when i change to 4x7 grid, it reads that it is a 4x2 widget, the same happens to all other normally 4x1 widgets. I am guessing this is because the widgets would be too small if they were 4x1 on that grid size so it chooses to be 4x2, but without the vertical resizing you have no choice. The fix here would be to have custom widget resizing added back to v11 imo.

**Comment by Y0191** [comment]
Oh okay, nice to hear that! Yes I recall when I made it 4x1 on A10 LawnChair, it was small but perfectly readable haha. Hope they add custom widget resizing, right.
