### ISSUE TITLE
At a glance is not displaying properly

### ISSUE THREAD

**Issue by jasonwsvt** [Deletescape-Media/Lawnchair#2164]
![Screenshot_20210605-091719](https://user-images.githubusercontent.com/71233413/120892995-edebd780-c5de-11eb-8ad1-052ac43ed794.png)
![Screenshot_20210605-091626](https://user-images.githubusercontent.com/71233413/120892996-ee846e00-c5de-11eb-9154-b9468ef4adca.png)

**Comment by RikKoedoot** [comment]
ofcourse, The widget size is too small for it to fit. Make it bigger.

**Comment by ghost** [comment]
Rik 😂

**Comment by jasonwsvt** [comment]
Oh but you are wrong!  It is plenty big sometimes.  See?

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
