### ISSUE TITLE
[Feature Request] Add option to remove the labels (text under icons) for A11

### ISSUE THREAD

**Issue by Y0191** [Deletescape-Media/Lawnchair#2165]
Please add an option to completely remove the app icon labels (application name under each icon) for any future A11 LawnChair version. Currently there is only an option to change its size from 50% to 150%. Thank you in advance!

**Comment by RikKoedoot** [comment]
this is a feature from older version's of lawnchair and will make a return in v11

**Comment by Y0191** [comment]
> this is a feature from older version's of lawnchair and will make a return in v11

Thank you so much for the info! Glad to hear it will eventually appear!

**Comment by ghost** [comment]
Also do note that all the features you see in Lawnchair 2 will come back in Lawnchair 11 like Hide Apps, Plugins and more. Its just that the devs are starting from scratch again. 🙂

**Comment by RikKoedoot** [comment]
It has been added to the desktop, keeping the request open because appdrawer label hide hasn't been added yet

**Comment by RikKoedoot** [comment]
Closing now because it has been implemented now, will come in a future update
