### ISSUE TITLE
[Feature request] add the thing where the wallpaper kind of zooms out when opening the app drawer

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2168]
If you have a Pixel or maybe any other device running A11, you may have noticed that when you start to pull the app drawer, the wallpaper moves in some way. You know what I mean here? Um, what if we added that to L11 just to give it a little bit more of a Pixel flair? :>

I may add more feature requests once I go ahead and keep using L11 daily.

Thanks for working on the app continously! Appreciate it.

**Comment by RikKoedoot** [comment]
From what I know this needs to be at the system level, so closing this feature request
