### ISSUE TITLE
Cannot compile with latest src checkout

### ISSUE THREAD

**Issue by rasfarrf5** [Deletescape-Media/Lawnchair#2170]
Hi Lawnchair,

I would like to contribute to lawnchair app. When I fork and and run the app, I'm getting below error from Android Studio Artic Fox version 2020.3.1 Beta 3 (mac)

`
> Task :processAospWithQuickstepDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":" ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml","position":{"startLine":306}}],"original":"ERROR: ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml:307: AAPT: error: resource style/Theme.Acknowledgements (aka com.android.launcher3:style/Theme.Acknowledgements) not found.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":" ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml","position":{"startLine":310}}],"original":"ERROR: ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml:311: AAPT: error: resource style/Theme.Acknowledgements (aka com.android.launcher3:style/Theme.Acknowledgements) not found.\n    ","tool":"AAPT"}

> Task :mergeLibDexAospWithQuickstepDebug
> Task :desugarAospWithQuickstepDebugFileDependencies
> Task :mergeExtDexAospWithQuickstepDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processAospWithQuickstepDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml:307: AAPT: error: resource style/Theme.Acknowledgements (aka com.android.launcher3:style/Theme.Acknowledgements) not found.
         
     ERROR: ../Android/lawnchair/build/intermediates/packaged_manifests/aospWithQuickstepDebug/AndroidManifest.xml:311: AAPT: error: resource style/Theme.Acknowledgements (aka com.android.launcher3:style/Theme.Acknowledgements) not found.
`

**Comment by suphon-t** [comment]
I apologize for the lack of documentation on the build procedure. 
Please make sure to select the following build variants:
<img width="584" alt="Screen Shot 2564-06-06 at 20 18 08" src="https://user-images.githubusercontent.com/8080853/120925778-51235a00-c704-11eb-8c5f-f0deeba9cbd1.png">

**Comment by rasfarrf5** [comment]
Thanks for your reply. It works well. Appreciate your quick response.

Please help to update it in README. 👍🏼
