### ISSUE TITLE
swipe up to home is not working properly in Launchair 11 alpha 5

### ISSUE THREAD

**Issue by fazilsheik96** [Deletescape-Media/Lawnchair#2171]

**Comment by RikKoedoot** [comment]
Please give an actual explanation. We cannot fix it if you don't give any information

**Comment by fazilsheik96** [comment]
if i switch to different app by swiping navigation bar(gesture bar) then swipe up to home doesn't respond and it does only after 2 attempts

**Comment by RikKoedoot** [comment]
Are you using quickswitch?

**Comment by SuperDragonXD** [comment]
Likely an issue with all third party launchers, and may be fixed by using QuickSwitch. Maybe updating the app could work too.

Also closing this issue since it's related to an older version of Lawnchair. (We no longer support old versions)
