### ISSUE TITLE
Lawnchair 11 didn't pick all the icons from iconpack

### ISSUE THREAD

**Issue by mintyleaf** [Deletescape-Media/Lawnchair#2178]
Lawnchair 11 (alpha 5) didn't pick all the icons from iconpack (delta)

Here the lawnchair, look at dodo pizza one, for example (also metro, metamask and other stock oversaturated in comparsion with pack icons):
![one](https://user-images.githubusercontent.com/17470408/122670795-774cfd80-d1cc-11eb-97f5-a3822daa6f8c.jpg)

Here is the stock trebuchet, all the icons picked up (but undisableable icon masking drives me crazy):
![two](https://user-images.githubusercontent.com/17470408/122670797-787e2a80-d1cc-11eb-9ebc-22148f960f13.jpg)

**Comment by RikKoedoot** [comment]
Does this still occur on alpha 6?

**Comment by mintyleaf** [comment]
sorry, missed that reply)
it didn't happen for a quite long time (I'm sitting on the latest build from actions)
so I assume that this can be closed
