### ISSUE TITLE
Wow!

### ISSUE THREAD

**Issue by RWOne** [Deletescape-Media/Lawnchair#218]
Caught this out the gate Till, you had code up and waited for the APK.

Just awesome.

Ok, question. Curious, why are you opposed to app naming to get pixel weather?

I realize you're working on your own implementation, my thought is this, could that be a toggle?

Wanting a stock look, speaking only for me, the pixel wx is all I need on the HP, I use a radar app (rainy days) and am good.

It does keep it in line with stock features ...

Awesome implementation of all the rest!

**Comment by AxiK101** [comment]
Maybe Google doesn't allow it. This is like a clone of pixel launcher yet so deep modded that can't be named like the original. Rights etc

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment]
@AxiK101 Unfortunately not, it is the Dev's choice. If internally matched to pixel launcher it will grab the weather, its been demonstrated in other pixel launcher apps ported to AOSP launcher, such as Amir's:
https://github.com/amirzaidi/Launcher3/releases/

I'm only wondering at the reasoning, it may be easier to just allow it to grab the pixel weather and turn time to other custom edits, etc.

**Comment by fonix232** [comment]
@RWOne the reason is that we want to get Lawnchair on the play store soon, and such, package name cannot match the Pixel Launcher's.
