### ISSUE TITLE
[Feature Request] App locker

### ISSUE THREAD

**Issue by rasfarrf5** [Deletescape-Media/Lawnchair#2180]
Hi Lawnchair Team,

I like would to have App locker feature with this Lawnchair. Most of the other famous apps has this feature and it is very useful in security.

**Comment by skittles9823** [comment]
App lockers are a dime a dozen and apps for them are incredibly easy to get around. If you want one that actually works well it has to come packaged in the os.

**Comment by rasfarrf5** [comment]
Exactly, But I don't want to complicate things. Just simple locker when you click on the launcher icon with fingerprint to unlock and proceed.

**Comment by skittles9823** [comment]
Again, thats insecure when implemented launcher side. You can open locked apps from notifications, recents, adb, etc.

It's a completely useless and redundant feature unless it's implemented in the OS level.
