### ISSUE TITLE
(Feature Request) Add Resart button.

### ISSUE THREAD

**Issue by manan4480** [Deletescape-Media/Lawnchair#2184]
I would like to request the devs to add restart button in the settings page.

**Comment by Kimbrezen** [comment]
There is one, You just have to tap on the 3 dots then "Restart"
![Screenshot](https://user-images.githubusercontent.com/76803613/127824890-b0fbd5b9-dd6d-4be0-b6e0-a236f98aec8d.png)

**Comment by RikKoedoot** [comment]
Available in v2/v9/v10, now also in v11
