### ISSUE TITLE
Anyone managed to get Google Feed work on Lawnchair 11?

### ISSUE THREAD

**Issue by k3lt** [Deletescape-Media/Lawnchair#2187]
I tried everything, can't get it to work.

**Comment by RikKoedoot** [comment]
What is everything? Are you using lawnfeed 3? Do you have the Google app installed (not the Google go app)
Also please provide more info on the environment, eg. device and rom

**Comment by k3lt** [comment]
I tried force closing the launcher, clearing data & cache, uncheck / check Feed setting multiple times, and same goes to Google app. I'm using normal Google app, not "Go".
The only Lawnfeed i tried was the one available from the official website https://lawnchair.app/lawnfeed/ so 2.1-2598 i guess.

Moto G5, LineageOS 18.1.

**Comment by DanGLVK** [comment]
> I tried force closing the launcher, clearing data & cache, uncheck / check Feed setting multiple times, and same goes to Google app. I'm using normal Google app, not "Go".
> The only Lawnfeed i tried was the one available from the official website https://lawnchair.app/lawnfeed/ so 2.1-2598 i guess.
> 
> Moto G5, LineageOS 18.1.

That lawnfeed version wasn't designed for Lawnchair v11, you need Lawnfeed v3 

https://www.apkmirror.com/apk/lawnfeed-2/

**Comment by k3lt** [comment]
Your link doesn't work but i'll look it up thanks.

**Comment by DanGLVK** [comment]
> Your link doesn't work but i'll look it up thanks.

https://www.apkmirror.com/apk/lawnchair/lawnfeed-2/lawnfeed-2-dev-release/lawnfeed-dev-android-apk-download/
