### ISSUE TITLE
about Google search bar

### ISSUE THREAD

**Issue by pragyantpradab** [Deletescape-Media/Lawnchair#2189]
When I touch or click google logo in Google search bar , it should open Google feeds page bit it os not working. i am clicking on logo but nothing is happening.

**Comment by RikKoedoot** [comment]
What lawnchair version are you talking about? In v11 this is working for me

**Comment by SuperDragonXD** [comment]
Closing this issue since this is likely fixed in a later version. Also, tapping on the logo/empty area will show the Google search bar.
