### ISSUE TITLE
spacing for widgets on homescreen

### ISSUE THREAD

**Issue by bryandesrosiers** [Deletescape-Media/Lawnchair#2194]
Since switching to Lawnchair Ive noticed spacing on widgets has been off.

Coming from Microsoft Launcher, i was able to have my weather widget fit perfect above my dock, with out any portions of the widget going over top of the dirt pile of my wall paper.

 In Lawnchair the widget is either leaving empty spaces on either left or right when shortening the widget. 

Images are attached to visual.

Apps used:

Lawnchair Launcher
GeoWeather Weather App

On Android 11

![Screenshot_20210804-045557_Lawnchair](https://user-images.githubusercontent.com/1483955/128153449-04b25a84-9a44-476e-8575-e02118662490.jpg)

![Screenshot_20210804-045530_Lawnchair](https://user-images.githubusercontent.com/1483955/128153441-ed153809-e3f3-446d-9946-cefe5534fac0.jpg)

**Comment by HammyHavoc** [comment]
Can confirm this visual bug.

**Comment by RikKoedoot** [comment]
This is logical, as one widget is way smaller vertically than the other one, if you make that one taller it will be able to fill out the horizontal space. You can edit your grid size to have more spaces in the vertical axis. This way you can make the widget a better size

**Comment by bryandesrosiers** [comment]
Reply to rikkoedoot's reply:

Your input seems to have given me a work around. Thanks alot. Marking as closed.
