### ISSUE TITLE
Scrollbar initial mixup on release 2.0-2589

### ISSUE THREAD

**Issue by mark-mkram** [Deletescape-Media/Lawnchair#2195]
In the app drawer if I give an icon a custom name which puts it in a different place on the alphabetically ordered list, then scroll over it with the scrollbar I can see the icons original initial in the new position.
Only happened once, cant recreate it.
I'll post a screenshot if i manage to recreate it.

**Comment by mark-mkram** [comment]
There!
![Screenshot_20210805-054602](https://user-images.githubusercontent.com/82494152/128287868-d5428390-9b48-47bb-ba6f-b4d8d0f9101f.jpg)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
