### ISSUE TITLE
Ability to remove X icon from shortcuts.

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#220]
A new feature was added that now has a "Remove" option in the icons long press menu. I understand why some may like this (bigger phones like Galaxy S8+) but I see no use for it myself. Could we have a toggle to remove that X icon in the settings? That would be great for people with smaller phones that can drag the icon to the remove label at the top. _I find the quickcut menu looking too cluttered now._

![screenshot_20170716-083206](https://user-images.githubusercontent.com/29968331/28249044-a8ddf26c-6a03-11e7-9a08-6c1bf9db0dd6.png)

**Comment by suphon-t** [comment]
Removed in 6c032bb
