### ISSUE TITLE
Option to remove the "Don't stay up too late!" message on the At A Glance widget

### ISSUE THREAD

**Issue by HammyHavoc** [Deletescape-Media/Lawnchair#2200]
Working with clients on different timezones whilst working remotely means these messages are non-applicable for me.

*Somebody* out there has to work the grave shift too. This was a complaint of mine with Microsoft Launcher too. It isn't adding any functionality, and whilst it might seem playful, I'd rather just have a cleaner, more functional launcher.

**Comment by RikKoedoot** [comment]
You know you can disable it right? Go to settings, home widget, event sources, and here drag the "contextual messages" source to below the line
