### ISSUE TITLE
Alpha and Beta Testing on Google Play Store 

### ISSUE THREAD

**Issue by 123-bott** [Deletescape-Media/Lawnchair#2202]
First of all, I know that there is beta testing in Google Play Store, but it's not being updated (for now) and you just use Telegram/Other to distribute the beta app. 

Please use/update the beta testing in Google Play Store because I want to use the new version of Lawnchair without checking if there's a new update every time because you don't use GPS. I also don't want to download through Telegram because I don't want to install through downloading the APKs. It's the issue of security, not because I'm lazy to do so. 

Many also are not aware that there are new versions of Lawnchair because of this. 

If you're not confident about it being in Beta Testing you should use Alpha Testing first.

**Comment by RikKoedoot** [comment]
We are already testing in alpha, that's what the telegram channel is for. Also there is no security issue with installing Lawnchair apk's if it's from an official source, also in recent android versions you need to separately give each app the ability to install apk's, if you only give telegram the ability, and only install Lawnchair from our telegram channel, there are 0 security issue.

**Comment by 123-bott** [comment]
> We are already testing in alpha, that's what the telegram channel is for.

But my real problem is you have to always check for updates unlike if you put it in GPS, the auto-update feature will automatically update the apps. 

> also in recent android versions you need to separately give each app the ability to install apk's

Most of my devices I use are older Android 7 and below. But I have devices with updated Android 11.

**Comment by divadsn** [comment]
> the auto-update feature will automatically update the apps

As long as we can't ensure that updates can break things, we prefer that users update manually so they don't end up with broken phones or broken home screens.

**Comment by lawson85** [comment]
How annoying. I'll just use another launcher if you're not going to update via the play store

**Comment by divadsn** [comment]
> 
> 
> How annoying. I'll just use another launcher if you're not going to update via the play store

As I wrote above, until we don't get stable enough releases, we will not push builds to the Play Store :shrug:

**Comment by RikKoedoot** [comment]
By the way, you wouldn't have to keep checking for updates, you get a telegram notification when one is out. But V11 is not ready for play store release.

**Comment by lawson85** [comment]
If Lawnchair 11 and 12 are about, is there not a way to put precious versions on the play store? I'm stuck on 2.0-2589

**Comment by skittles9823** [comment]
As far as I'm aware the current playstore listing won't be used anyway, we've changed the package name so we'd need a new listing. As far as alpha builds go, for testing purposes it's much easier to just keep builds on telegram as it's easier to get feedback in the groups. The main issue with playstore alpha testing is it would cause the playstore listing to get tanked reviews due to people not even interested in testing using it, experiencing bugs and giving it a 1 star before even reporting a bug.
