### ISSUE TITLE
App icon above folder icon

### ISSUE THREAD

**Issue by DavidGreen63** [Deletescape-Media/Lawnchair#2203]
When attempting to drop an App into a folder, it overlapped the folder rather than being added to the folder's contents. 

This took me by surprise as I initially thought that the App icon had replaced the folder, until a tap and hold revealed the folder underneath.

It is probably an effect of the overlap option being checked active, but it is an effect that was not expected.

**Comment by RikKoedoot** [comment]
This is to be expected when overlapped placement is enabled, so it's not a bug
