### ISSUE TITLE
Lawnfeed plugin no longer working

### ISSUE THREAD

**Issue by mindplay-dk** [Deletescape-Media/Lawnchair#2205]
In the past 1-2 days, the lawnfeed plugin appears to have stopped working.

On my mobile, it says "it looks like there was an error signing into your account" - but the icon in the corner shows my face, so it is logged in. Pressing "try again" makes it spin forever.

On my tablet, it was the same thing, so I tried installing the latest version of Lawnchair, downloaded the plugin and installed it again - here it says, "something went wrong - couldn't connect to discover", again, my face is displayed, and pressing "retry" doesn't help.

I've restarted and cleared caches etc. - doesn't seem to help.

I wonder if they changed the APIs on the server side or something?

**Comment by mindplay-dk** [comment]
Well, this is really strange - the "Discover" feed in the actual Google app is dead as well. I've never used it before, so I don't know if it did work, but it's the same nonsense message - it thinks I'm not logged in, but the icon in the corner clearly shows that I am.

Anyhow, this might not be a problem with the plugin at all?

![Screenshot_20210818-073246](https://user-images.githubusercontent.com/103348/129842951-9b6b173b-b618-4929-a8bd-6ea2e00a5816.png)

**Comment by RikKoedoot** [comment]
This has nothing to do with lawnfeed

**Comment by mindplay-dk** [comment]
As of this morning, the app and the plugin are both working normally again - so they obviously do have something in common?

Go figure.

**Comment by RikKoedoot** [comment]
The app and the home screen feed are both coming from the google app, so if they fix it it will fix both.

**Comment by mindplay-dk** [comment]
It worked for a few days and now it's dead again.

Am I the only one having this problem?

**Comment by RikKoedoot** [comment]
Are you able to swipe to the feed page but nothing shows up? Or can't you even swipe to the page? As the first one has nothing to do with lawnfeed, that is a google problem. The second one is a lawnfeed problem though

**Comment by mindplay-dk** [comment]
Yes, I can swipe to it - there was just the nonsense message about logging in... Now it's different though - now it spins for a while, then says "can't refresh discover right now", so maybe they're working on something? Seems unlikely though, for Google to have something like this completely out of service for days on end.

Am I the only one seeing this though? Does it work for other people? If so, I suppose it might be account specific, or network specific, and so on. Again, this seems unlikely, as my phone and tablet are on different provider networks, and the issues consistently occur on both...

**Comment by RikKoedoot** [comment]
Lawnfeed does not control anything in the google app. It only makes the feed show up in lawnchair, anything in the feed is from google. This is an issue with google somehow.

**Comment by mindplay-dk** [comment]
I dig that, just still wondering if I'm the only one seeing this?
