### ISSUE TITLE
Recent apps automatically cleared

### ISSUE THREAD

**Issue by nor-ric** [Deletescape-Media/Lawnchair#2206]
One thing I find very annoying about the stock Pixel launcher is that the overview/recents/quickstep screen automatically clears all apps but the last 3-4 after some time of inactivity (about 8-10 hours I think).
I've noticed Lawnchair does the same.
Any idea how to get around this and disable this behaviour? Perhaps "recentsIconCacheSize" or "recentsThumbnailCacheSize" integers (found in quickstep/res/values/config.xml) could be related? Any other suggestion? Thanks

**Comment by RikKoedoot** [comment]
This might be an Android thing instead of a launcher thing, but personally I do not have a clue if that's the case
