### ISSUE TITLE
Blur in settings.

### ISSUE THREAD

**Issue by DanielJohnRoberts** [Deletescape-Media/Lawnchair#221]
Please could there be a way to change blur in the settings UI. Perhaps a slider toggle like for the app drawer? Much appreciated.

**Comment by intelligentcasanova** [comment]
There is already a slider in the settings to set the blur radius for the blurred UI elements.
If you mean the amount of blur of the settings page, this changes with the overall blur radius.

**Comment by intelligentcasanova** [comment]
close #221

**Comment by nyancrimew** [comment]
:man_facepalming:
