### ISSUE TITLE
Crash when long pressing an icon after placing a widget in homescreen from an external app

### ISSUE THREAD

**Issue by AlessandroGandolfi** [Deletescape-Media/Lawnchair#2210]
https://catbin.up.railway.app/ofoguguxow

OnePlus 6 rooted with QuickSwitch
ShapeShift OS 2.7 (Android 11)
V11 Alpha 6

It's a really rare crash for me but I reported it in case it could create problems in other scenarios too.
I reproduced it by long pressing an icon after selecting a widget from an "external" app, in my case it was Overdrop (weather app) but I think it is reproducible with KWGT too. 
I can upload a video to Drive to show how to reproduce the bug if needed.

**Comment by RikKoedoot** [comment]
does this still occur on lawnchair 12 alpha 4?
