### ISSUE TITLE
Small trigger area when creating folders in landscape mode

### ISSUE THREAD

**Issue by slaszt** [Deletescape-Media/Lawnchair#2212]
I am trying to create multiple folders on the desktop and, in landscape orientation, the area that triggers the creation of a folder is very small on my tablet, so creating folders is extremely difficult. The icons will simply rearrange themselves instead of creating or adding to the desired folder.

I am using a 2018 Amazon Fire HD 8, if that helps. I have tried creating folders in both portrait and landscape orientations and only portrait mode works how it's supposed to.

**Comment by RikKoedoot** [comment]
What lawnchair version are you talking about?
