### ISSUE TITLE
Doesn't work with quickswitch on a10

### ISSUE THREAD

**Issue by niam0t** [Deletescape-Media/Lawnchair#2213]
![Screenshot_20210820-191326846](https://user-images.githubusercontent.com/58494481/130291928-af16e382-5a7b-4b90-8f42-3a6c9e1adb9d.jpg)

**Comment by RikKoedoot** [comment]
Known and documented

**Comment by niamotullah** [comment]
Thanks.. wish it's gonna fixed soon
