### ISSUE TITLE
[Feature Request] Add toggleable option to turn on/off the app drawer strech when swiping from different angles (explanation in the comments/description).

### ISSUE THREAD

**Issue by zzahkaboom24** [Deletescape-Media/Lawnchair#2214]
Lawnchair version: 11.0-alpha.6+e79a8bb.release

Screenshots or Videos of the "problem": https://streamable.com/bgc16a

Further details: I personally dont like the stretch that it does at the upper part of the app drawer when opening it and i might not be the only one, i hope the request isnt too much for the dev team to handle since i dont know what easier and whats harder, either way thanks for reading my feature request :).

**Comment by zzahkaboom24** [comment]
Also apparently the same happens when reaching the end of the app drawer and still swiping up and the same strech happens when you swipe down from the bottom to go up in the app drawer but at the bottom part this time.

I hope to be able to deactivate those things too in the future

**Comment by sinus-x** [comment]
Did you try toggling the spring effect? Settings > App drawer > Spring effect.

**Comment by zzahkaboom24** [comment]
> Did you try toggling the spring effect? Settings > App drawer > Spring effect.

![Screenshot_20211020-154649_Lawnchair](https://user-images.githubusercontent.com/42496614/138105362-a8681d82-b269-4fdb-ac89-fdcb3e3eccad.png)

If i would have that feature, i would have tried it it by then, but no. There is no Spring effect in it.

**Comment by suphon-t** [comment]
Closing as this is fixed in the upcoming release. (top part of drawer doesn't stretch anymore)
