### ISSUE TITLE
Too much space when google search is removed from the dock

### ISSUE THREAD

**Issue by drishal** [Deletescape-Media/Lawnchair#2215]
in alpha 6 there is too much space in the app dock after the google search is removed, something like this 
![lawnchair alpha 6](https://user-images.githubusercontent.com/32875739/130316858-3b45cc13-a9c2-403a-9cc3-e4a5d86197a2.jpeg)

however alpha 5 is a little better 
![lawnchair alpha 5](https://user-images.githubusercontent.com/32875739/130316873-b362341a-11ea-475c-8bf6-900d552b8122.jpeg)

My suggestion: better to reduced the space to how it looks like in shady launcher
![shady](https://user-images.githubusercontent.com/32875739/130316896-147c6cdb-0c11-4186-8f1b-d2e1fe5f4a6a.jpeg)

Note: the only way to temporarily fix this is to increase the row size, which again looks a bit...awkward   

Device: Excalibur (redmi note 9 pro max)
ROM: crdroid

**Comment by RikKoedoot** [comment]
I quite like the padding, so in my opinion it should be toggle, or maybe set with a slider or presets

**Comment by xanda-escuyer** [comment]
Is this the same issue we are seeing here?

![Screenshot_20220207_232434_app lawnchair](https://user-images.githubusercontent.com/15840995/153455993-0580dd4e-3704-44cb-b16c-dce4374e0488.jpg)

Huawei Y5II (AMN-LX29)
EMUI 9.1.0 (Android 9/Pie)
Lawnchair 12 Alpha 5

**Comment by Doomsdayrs** [comment]
It's an absolute joke with how much padding it has. 
![Screenshot_20220210-163936_Lawnchair](https://user-images.githubusercontent.com/38189170/153501035-53f11f1f-a500-417b-b5d2-aa17290e6e4b.png)

Enough to make the dock have another row of icons.

**Comment by RikKoedoot** [comment]
Are you people still experiencing it in the latest build of 12.1?

**Comment by Doomsdayrs** [comment]
![Screenshot_20220601-130510_Lawnchair](https://user-images.githubusercontent.com/38189170/171460871-908c9a82-6c96-48fc-a7eb-cea45a99b9c0.png)
This still occurs with the latest version.


To be precise, the current work around is to increase column and row count. But there is still a noticeable gap even then.

**Comment by markcellus** [comment]
The dock area appears to be on a separate grid than upper icon area. Why not just have everything be on the same grid?

**Comment by Doomsdayrs** [comment]
Bump for still a thing

**Comment by xanda-escuyer** [comment]
Ditto.

**Comment by chipironcin** [comment]
Workaround for me was changing "Dock size" to be 66% instead of "Auto"
