### ISSUE TITLE
some  widgets not  properly resizing vertically

### ISSUE THREAD

**Issue by drishal** [Deletescape-Media/Lawnchair#2216]
increasing the number of home screen rows  fixes issue #2215  
but then it now breaks the vertical resizing of bigger widgets which have extra empty space like the clock widget 

if I increase the number of home screen rows the dock gap reduces, but then I can't make some widgets like the clock one from vertical smaller
![clock issue android](https://user-images.githubusercontent.com/32875739/130317628-46636ead-b56f-4d5a-9f09-55375b79cfcb.jpeg)

**Comment by drishal** [comment]
(note: and also when adding more widgets after that, lawnchair crashes and resets the number of rows thus more issues when resizing)

**Comment by RikKoedoot** [comment]
Could you provide a crash log for that crash?

**Comment by drishal** [comment]
> Could you provide a crash log for that crash?

will try and attempt to make that crash again 
happens only after sometime of trying to customize it 
also what is the best way of collecting the logs?

**Comment by RikKoedoot** [comment]
1. Download and install the Scoop app
2. Grant permissions to the app using either root or via adb using the command adb shell pm grant taco.scoop android.permission.READ_LOGS
3. Reproduce the crash
4. Upload the stacktrace to catbin
5. Paste link of the crash log here

**Comment by tnyeanderson** [comment]
I'm also affected by this, specifically with the clock widget shown above, which is preventing me from laying out my home screen the way I would like :( back to nova for now, but keeping a very close eye on this...

In my view, there should be a toggle where I can essentially do a mask on the widget... as in: I can make the widget any size and shape that I want. It might have parts cut off (masked), but it would prevent these kinds of things and offer more flexibility. Not sure if this is possible based on how widgets are handled, but I've noticed the issue with nova as well on certain screen sizes, where widgets won't size the way I want them to. Even if it's a per-widget toggle that says "I'm an expert, let me choose the size and shape" it would really give the user more control. I always seem to feel like the widget is telling *me* what its size is, and it can be frustrating.

**Comment by ghost** [comment]
Same here.
Widgets are leaving ton of white spaces on screen.
This makes some widgets simply unusable.
![Screenshot_20211223-094124_Lawnchair](https://user-images.githubusercontent.com/77554817/147255762-3b33562d-a3fc-43f7-8cd9-e4505400aec4.png)
