### ISSUE TITLE
AppLock Function

### ISSUE THREAD

**Issue by DSDV** [Deletescape-Media/Lawnchair#2222]
Hi,
I'm using Lawnchair for a very long time now. Even the switch to the non open source V2 version. 
But sadly since android 10 it doesn't support an applock/privacy function.
Pls add the option to lock selected apps behind a code. 
Many apps like signal or certain gallery's support this function but sadly not every app and it would be highly appreciated if lawn chair could fix this.

With kind regards

**Comment by RikKoedoot** [comment]
Our opinion on app lockers is that it's too easy to bypass if it's not on a system level, this is why we do not implement them

**Comment by DSDV** [comment]
> > 
> Our opinion on app lockers is that it's too easy to bypass if it's not on a system level, this is why we do not implement them 

this is true. But it's also true for windows login s and nearly everybody uses them. 

It may be a simple switch of the launcher, but it's a hurdle to get a phone and install a new launcher while you hold it just so you can for example read some text.
Its no a security feature which protects against serious attacks. It's a security feature which protects against "missclicks" from curious eyes.
If you are worried that this might me misunderstood place a warning when enabling it showing the simplicity at which it can be bypassed.

**Pls reconsider the implementation!**
