### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by TymanWasTaken** [Deletescape-Media/Lawnchair#2227]
Occasionally, some widgets like now playing history or sound search will just grey out and not work when pressed, saying "Shortcut isn't available". Also it doesn't seem to be happing anymore but a few days ago it said "App not installed" while opening apps from the search bar (the apps are installed, and did open). I am on a Pixel 4xl.

**Comment by SuperDragonXD** [comment]
The "app shortcuts" will not work if you don't set Lawnchair as the default launcher (which is very likely). Closing this issue due to it being an issue with your default launcher settings and not Lawnchair itself.

**Comment by SuperDragonXD** [comment]
The "app shortcuts" will not work if you don't set Lawnchair as the default launcher (which is very likely). Closing this issue due to it being an issue with your default launcher settings and not Lawnchair itself.
