### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by FernFranc** [Deletescape-Media/Lawnchair#2229]
1.)It would be great if At a Glance was replaced with Live Space present on Android 12 and would it be possible to get the Global search and search Ui present in the Pixel Launcher on Android 12?

2.)Also an option to pick which animation you want to use for the popup menu for example: Android 12 or 11 ect.

3.)When scrolling through the app drawer the search bar covers the whole top section of the screen.

Hope this isn't too much :).

**Comment by RikKoedoot** [comment]
This will have to wait till the sources of android 12 are out

**Comment by RikKoedoot** [comment]
Closing as options 1 and 3 are present
