### ISSUE TITLE
Small glitches

### ISSUE THREAD

**Issue by Thebear375** [Deletescape-Media/Lawnchair#223]
Widget drawer remains light theme after choosing dark theme. Also app drawer caret or arrow drops below dock icons when transparent dock is chosen

**Comment by RWOne** [comment]
Confirm the app caret below dock on transparency, but is that so bad?

Screen indicators are gone as well, but I don't miss 'em ...

**Comment by nyancrimew** [comment]
The arrow dropping below the dock is a desing choice and thus an intended feature

**Comment by RWOne** [comment]
Location works fine for me, I think it's good there between the dock and navbar ...

**Comment by Thebear375** [comment]
Not a problem for me, was only pointing out the location change when dock is transparent. Would prefer the widget picker change when dark theme is chosen if possible. Otherwise it keeps getting better on each update.

**Comment by suphon-t** [comment]
Fixed with 82473b8
