### ISSUE TITLE
Lawnchair 11 Alpha 6.1 on Oxygen OS 11 

### ISSUE THREAD

**Issue by impr4t** [Deletescape-Media/Lawnchair#2234]
Hi 
The lawnchair launcher 11 Alpha 6.1 works flawlessly on my OnePlus 8 but it doesn't have the features , all the old features are not here. It's just empty. When will we be getting allt hose features back ?

Attached files : 

![Screenshot_20210921-220611](https://user-images.githubusercontent.com/61603856/134211049-73c948aa-e1a0-4904-9f7c-3501807c45c7.jpg)
![Screenshot_20210921-220615](https://user-images.githubusercontent.com/61603856/134211057-4830e78d-1e6e-4dad-b4ad-ed395467eac4.jpg)

**Comment by RikKoedoot** [comment]
It's a rewrite and we intend on getting old features back
