### ISSUE TITLE
Customize icons?

### ISSUE THREAD

**Issue by Nikoichu** [Deletescape-Media/Lawnchair#2236]
This is more of a question than an issue. In the drawer menu when you go to editing the name of an app, you can click the icon to change it (presumably?), but the only option is the already existing icon. How do you add custom icons? It would be really cool if this is possible, since a lot of apps have icons that are outdated and/or don't comply with icon shape customizations from the OS.

**Comment by OxygenCobalt** [comment]
You can only mass-apply an icon pack from the settings on Lawnchair 11. I've already raised this issue in #2201, but so far there has been no progress.

**Comment by RikKoedoot** [comment]
@OxygenCobalt this has nothing to do with your issue

**Comment by OxygenCobalt** [comment]
I misunderstood then. I apologize.

**Comment by Nikoichu** [comment]
I guess it's still a nice feature request to be able to change app icons.

**Comment by RikKoedoot** [comment]
In the latest lawnchair builds this is already possible.
