### ISSUE TITLE
Desktop Has a Delay When Closing an App

### ISSUE THREAD

**Issue by qfaq** [Deletescape-Media/Lawnchair#2237]
Hello. Is there a way to fix this issue where the desktop will often freeze or lag for a second or so, making it impossible to open an app. It can get really irrating.

Here is a video showing the issue:
https://user-images.githubusercontent.com/49662620/134821199-5ddf659c-da34-4665-8cbb-ba3738950a4b.mp4

**Comment by RikKoedoot** [comment]
Could you test if this happens with other third party launchers (so not your stock launcher please)

**Comment by qfaq** [comment]
Here it is with Nova launcher:

Uploading Screen_Recording_20210926-154935_Chrome.mp4…

**Comment by qfaq** [comment]
Here it is with Nova launcher:

https://user-images.githubusercontent.com/49662620/134826976-76f797e7-80b1-482c-846d-b07ec019b3df.mp4

**Comment by Jamminroot** [comment]
Having the same issue, any updates on this?

**Comment by andrewrabert** [comment]
I notice this intermittenly occuring with any third-party launcher.

Device: Pixel 5
OS: LineageOS 18.1 (latest, updated weekly)
Launchers Tested: Lawnchair, KISS Launcher, Nova Launcher

**Comment by Jamminroot** [comment]
Yup, also noticed that on a few other launchers.
Are you using third party icon packs, as I now suspect that it might be the reason for a delay?
Also having this issue fixed in a launcher would really be a big improvement - as it seem to be a common, yet, not addressed problem :(

**Comment by DanGLVK** [comment]
> Yup, also noticed that on a few other launchers. Are you using third party icon packs, as I now suspect that it might be the reason for a delay? Also having this issue fixed in a launcher would really be a big improvement - as it seem to be a common, yet, not addressed problem :(

This issue is most likely caused by the transitional delay between going from the stock launcher (providing the recents and gestures) to your current launcher, lowering animations may help but unless you're rooted that cannot be fixed, it's outside the launcher's control
