### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by jark006** [Deletescape-Media/Lawnchair#2239]
shortcut don't show when long press the app icon. Only show 'app info'.
The function was normal before.Then one day it didn't appear.
Clearing data is invalid, even after uninstalling and reinstalling.

## Lawnchair11Alpha6.1:
![Screenshot_20210928-020738.jpg](https://user-images.githubusercontent.com/21077255/134963654-99100e48-e127-4762-8cbe-c24fec17b663.jpg)

## But it work on OPlaunch(oneplus6):
![Screenshot_20210928-020628__01.jpg](https://user-images.githubusercontent.com/21077255/134963574-fd0cd2a1-c270-4b02-a1e3-0144f2a86f29.jpg)

System: Hydrogen OS 10.0.10
Phone: oneplus 6

**Comment by RikKoedoot** [comment]
You'll need to set Lawnchair as your default launcher for them to show up

**Comment by jark006** [comment]
> You'll need to set Lawnchair as your default launcher for them to show up

It's already set to default launcher.

**Comment by siju-s** [comment]
Tested now on Android 12. Works fine if you set the `Lawnchair` as the default Home app from Phone Settings.

**Comment by SilverGreen93** [comment]
I have the same issue with Lawnchair 15.Dev.(#19). How do I enable app shortcuts in the long-press menu?
I have the launcher set as default. Android 16 (HyperOS 3).
