### ISSUE TITLE
no icon notification Viber and WhatsApp

### ISSUE THREAD

**Issue by kirillk8888** [Deletescape-Media/Lawnchair#224]
There is no icon notification of the first message in Viber and whatsapp. Appear after the second message.

**Comment by xmiseggs** [comment]
Try it, I've solved it with rebuilding the icon database and rebooting. Thank you.

**Comment by kirillk8888** [comment]
It did not help. The notification icon is only displayed after receiving the second message.

**Comment by AxiK101** [comment]
He is right. Viber notifications don't work. Strange....

![](http://i.imgur.com/n9nsrA2.png)

![](http://i.imgur.com/K7zCIP4.png)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
I can confirm that WhatsApp notifications indeed only show up after second message.

**Comment by AxiK101** [comment]
Yeap, viber too

**Comment by intelligentcasanova** [comment]
Is there a way to fix this issue?

**Comment by kirillk8888** [comment]
No solution to the problem?
