### ISSUE TITLE
[feature request] Setting to pull drawer with focus in search box

### ISSUE THREAD

**Issue by lfr** [Deletescape-Media/Lawnchair#2249]
Currently when we pull the drawer to search for apps, we have to touch the search box in order to make the keyboard appear, which is tedious in big phones as it's all the way at the top.

It would be nice to have as a setting an option that when we pull the drawer, they keyboard also shows up so you can start typing app names right away, instead of having to first touch the search box at the top.

**Comment by debnath-d** [comment]
This is the only thing stopping me from using the app. I can start using it as soon as this is implemented (this should be fairly simple to implement).

**Comment by matthewkeating** [comment]
+1  This would be an enormous usability improvement.

**Comment by suphon-t** [comment]
This is already in the app drawer settings.

<img src="https://user-images.githubusercontent.com/8080853/166186826-dfad12e6-e55c-41fc-a6d8-432d7de0ee00.png" height="500">

**Comment by lfr** [comment]
I don't understand, my settings screen looks nothing like this, I'm running version 2.0-2589 and it says there's no updates in the store 🤔

**Comment by RikKoedoot** [comment]
That's Lawnchair 12. Check the release section on our GitHub. It's still in alpha so that's why it's not on the Play Store
