### ISSUE TITLE
Dark theme based on system for A9 in latest A12 alpha 6.1

### ISSUE THREAD

**Issue by Rixon46** [Deletescape-Media/Lawnchair#2252]
On lawnchair A12 alpha 6.1 there is no option for dark theme based on device theme for android 9 but on lawnchair 9 and lawnchair 10 there is an option. So, please consider to add back the dark theme based on device theme for A9 devices in upcoming lawnchair versions.

**Comment by RikKoedoot** [comment]
Please do not report bugs or missing features from the action build

**Comment by suphon-t** [comment]
Reopening as this is also valid for v11
