### ISSUE TITLE
Feature request: Restore: add warning

### ISSUE THREAD

**Issue by wrmike1** [Deletescape-Media/Lawnchair#2254]
Accidentally "restored" old home screen icons.

What happened:
Accidentally "restored" old home screen icons, including for apps that had been deleted long, long ago.

What I expected to happen:
A warning screen first that says:
 > Seriously, you want to restore your home screen to the icons from March 13, 2020. Are you f-ing nuts? Half the apps are not installed anymore. Are you sure you don't want to make a backup of your current home screen before screwing up your phone???

Sorry for the rant. Thank you for the software, but this really hurt!

**Comment by RikKoedoot** [comment]
Backup is not implemented yet

**Comment by wrmike1** [comment]
> Backup is not implemented yet

> Did you do the restore in the Lawnchair 12 version?
> 
> I can't figure out how to do a restore (or backup) at all! How did you do it? I have a backup generated from the Lawnchair 10 version I've been using for ages, but could never find what they did with the feature.

I am a bit confused here. Backup most certainly seems to be implemented on my phone.

Lawnchair version 2.0-2589 is what I have installed right now.
Pixel 3
Android 12
To get to Backup: Open Lawnchair settings > Tap "Back Up and Restore" > then I tapped my old saved "settings" from March 31, 2020. 

Thanks!
