### ISSUE TITLE
Which release should I choose for Android 10?

### ISSUE THREAD

**Issue by iaeiou** [Deletescape-Media/Lawnchair#2257]
Hi there,

I would like to install Lawnchair on Android 10. The release page counts numerous file:

- android
- android-security
- android-platform
- android-vts

Which one should I choose for a _stable_ installation on Android 10?
And where to find the APK?

Thanks!

**Comment by etahamad** [comment]
Lawnchair 10.0 -> Android 10
Lawnchair 11.0 -> Android 11
And so on, you can install Lawnchair 11.0 on Android 10 but it might lead to unexpected behavior, stick with 10 if you faced something.

**Comment by etahamad** [comment]
Latest released apps: https://t.me/lawnchairci
Latest CI apps: https://github.com/LawnchairLauncher/lawnchair/actions

**Comment by iaeiou** [comment]
Hi @etahamad and thanks for having a look,

> Latest released apps: https://t.me/lawnchairci

I'm not on Telegram sorry

> Latest CI apps: https://github.com/LawnchairLauncher/lawnchair/actions

The branch `10` is not run by any workflow, so Lawnchair 10.0 cannot be found there, am I missing something?

**Comment by GEkuL** [comment]
> > Latest released apps: https://t.me/lawnchairci
> 
> I'm not on Telegram sorry

Install Telegram if want be up to date.
Talking about Lawnchair for A10, I seems like the best thing to use is Lawnchair 10.0, yet it has bugs, and since developers moved to 11.0, there will be no updates for 10.0 at least in near future.

Here's the link to latest 10.0 version. 
https://t.me/lawnchairci/1512
Should be downloadable even without tg account (but it's better to be there :)

You can also check up F-droid, but there're old versions as far as I remember.

**Comment by iaeiou** [comment]
Hi @GEkuL, and thanks for having a look,

> Here's the link to latest 10.0 version.
> https://t.me/lawnchairci/1512
> Should be downloadable even without tg account

The link it's not working without account, unfortunately. I tested with Firefox and Chromium 😭

> there will be no updates for 10.0 at least in near future

Thanks for the news!

> You can also check up F-droid, but there're old versions as far as I remember.

Yes I'm using this version since a year now and everything is fine, even if no update was made for 2 years.

I'll stick with the Fdroid version until the APK is made available outside of Telegram ([See this review to understand why I decided not to install Telegram](https://foundation.mozilla.org/en/privacynotincluded/telegram/)).
Note that I don't ask the whole dev to happen outside of Telegram, but it would be nice to publish the releases on GitHub for example.

Glad to see that Lawnchair project is still alive, thanks!

**Comment by felixkrohn** [comment]
> it would be nice to publish the releases on GitHub for example.

You mean like https://github.com/LawnchairLauncher/lawnchair/releases ?

**Comment by RikKoedoot** [comment]
They are in the release tab

**Comment by iaeiou** [comment]
> They are in the release tab

Thanks! But the branch `10` is not run by any workflow, so **Lawnchair 10.0 cannot be found there**, am I missing something?

**Comment by RikKoedoot** [comment]
Then on t.me/Lawnchairci or https://www.apkmirror.com/apk/deletescape/lawnchair/lawnchair-10-0-alpha-8-release/
