### ISSUE TITLE
Can it works on WSA?

### ISSUE THREAD

**Issue by shanyan-wcx** [Deletescape-Media/Lawnchair#2259]

**Comment by PeterNjeim** [comment]
Yes. This has been fixed by this: https://github.com/LawnchairLauncher/lawnchair/pull/2373. You need to compile it from source if you want to use it though, or you can wait for another version to release with the fix included.

**Comment by DanGLVK** [comment]
> Yes. This has been fixed by this: #2373. You need to compile it from source if you want to use it though, or you can wait for another version to release with the fix included.

He could alternatively get the APK from our GitHub actions page

**Comment by PeterNjeim** [comment]
I did not see that, thanks for letting me know. However since the goal is to run Lawnchair in WSA, and not simply debug it, I don't think using a debug build would be a good alternative as the performance would be worse.

Also, this issue should be closed as the issue has been resolved
