### ISSUE TITLE
Blur Support for A12 Quickstep

### ISSUE THREAD

**Issue by alejandro097** [Deletescape-Media/Lawnchair#2260]
It'd be great if one could have the option to make quickstep overview blurry/transparent.

**Comment by SuperDragonXD** [comment]
Late, but has been added in V12.1, won't be ported to V12. Closing this issue.

**Comment by RikKoedoot** [comment]
Blur support was always there, but only if blur is enabled on your device (we use android's blur system), which for some needs some tweaking. It was back in V12 aswell but then the regents were opaque
