### ISSUE TITLE
Google Search Bar is not showing in the dock.

### ISSUE THREAD

**Issue by bellbot890** [Deletescape-Media/Lawnchair#2262]
My search bar is broken it is not showing google search bar.
![Screenshot_2021-10-25-00-57-28-14_0249cd5c2fc47eaaf112d323a2502966](https://user-images.githubusercontent.com/92586625/138609628-40c96f90-0fc3-436f-8410-de08f11ddbd7.png)

**Comment by Mayank-9018** [comment]
Do you have Google App disabled? This happened on my device which had Google disabled.
