### ISSUE TITLE
Recents doesn't show wallpaper 

### ISSUE THREAD

**Issue by Promethilaus** [Deletescape-Media/Lawnchair#2265]
Recents doesn't show wallpaper with Android 11 lineage os on sony Xperia 10
![Screenshot_20211025-185501_Lawnchair](https://user-images.githubusercontent.com/92402601/138749041-261a5d03-b73e-4d61-8e5a-542f74d976df.png)

**Comment by RikKoedoot** [comment]
Not a bug, this is how Android 12 does it. If you go yo settings, general, tint backgrounds. And then change accent to your wallpaper color, it will theme like material you
