### ISSUE TITLE
[feature request] add android 12's select and share feature in recent apps

### ISSUE THREAD

**Issue by eyad-elghareeb** [Deletescape-Media/Lawnchair#2269]
In android 12 i use quick switch which is great but i miss the select features from pixel launcher , I don't know if it is going to be possible or not but i hope to see it added

**Comment by RikKoedoot** [comment]
It is a pixel exclusive feature, if you install the Google lens app, you can get a button for Google lens which also allows you to select stuff (restart Lawnchair after installing lens for it to show up)

**Comment by znbaboy** [comment]
> It is a pixel exclusive feature, if you install the Google lens app, you can get a button for Google lens which also allows you to select stuff (restart Lawnchair after installing lens for it to show up)

I hope this can be implemented natively as many people use Lawnchair as a means to de-google and having to download Google Lens and use the Google app defeats the purpose.
