### ISSUE TITLE
Crash when I open Lawnchair settings.

### ISSUE THREAD

**Issue by D3ZOXY** [Deletescape-Media/Lawnchair#2271]
[2021-10-26-19-22-39.txt](https://github.com/LawnchairLauncher/lawnchair/files/7419823/2021-10-26-19-22-39.txt)

**Comment by suphon-t** [comment]
I couldn't find a crash in the log you posted. Can you try using [Scoop](https://github.com/TacoTheDank/Scoop/releases/tag/v2.3.1)?

**Comment by D3ZOXY** [comment]
FATAL EXCEPTION: Binder:6095_2
Process: app.lawnchair, PID: 6095
java.lang.AbstractMethodError: abstract method "void android.view.IRemoteAnimationRunner.onAnimationStart(android.view.RemoteAnimationTarget[], android.view.IRemoteAnimationFinishedCallback)"
	at android.view.IRemoteAnimationRunner$Stub.onTransact(IRemoteAnimationRunner.java:106)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

**Comment by suphon-t** [comment]
Which Android version are you on? And are you using QuickSwitch?

**Comment by D3ZOXY** [comment]
Android 11. I don't use QuickSwitch.
Realme X2 (RMX1991).

**Comment by FrzMtrsprt** [comment]
Same here on Android 8.1, LineageOS 15.1.

**Comment by SuperDragonXD** [comment]
Late reply, but it could be fixed in the later versions (Lawnchair 12.1). Also closing since this is relevant to the older versions only (we no longer support older versions).
