### ISSUE TITLE
Search Bar is not returning apps

### ISSUE THREAD

**Issue by mariuske** [Deletescape-Media/Lawnchair#2275]
The Search Bar is not returning any installed apps when doing a search as expected.

Lawnchair version: 12.0 Alpha 2

Model name: Samsung Galaxy S20+ 5G
Android version: 11
One suI version: 3.1

**Comment by YRSB** [comment]
The same here.
Lawnchair version: 12.0 Alpha 4
Android version: 12
It works before OTA. I updated my ROM(the ROM update Law's version from alpha 3 to alpha 4) ,and then the search bar return nothing.

**Comment by mariuske** [comment]
After upgrade from alpha 3 to 4, the search bar suddenly returns app result for me.

**Comment by YRSB** [comment]
🤔hmmm... Still don't know what caused this bug. Maybe they'll fix it soon.

**Comment by ro6kie** [comment]
According to the Lawnchair admins, you need to have Android System Intelligence installed as a system app and that should fix the problem, though I haven't tried it yet so idk if it fixes the problem or not.
