### ISSUE TITLE
Glitch when closing app suggestions bubble.

### ISSUE THREAD

**Issue by madvinegar** [Deletescape-Media/Lawnchair#228]
You long press on an icon and the bubble with the app suggestions appears. When this "bubble" disappears most of the times an annoying glitch appears (like a ghost bubble on the opposite down side for 1 millisecond).

Any way to include the notification badges on apps?

Otherwise the launcher is fantastic. Keep up the good work.

**Comment by nyancrimew** [comment]
Notification badges are already added, give lawnchair notification access for it to work

**Comment by ankurk91** [comment]
@deletescape 
Does it work on Android 6.x ?

**Comment by RWOne** [comment]
Yes.

**Comment by fonix232** [comment]
I was only able to reproduce this one time on my Galaxy S8. It is probably a bug coming from the animation framework as our animations are well defined and work just fine 99% of the time.

**Comment by madvinegar** [comment]
I cannot get the notification badges to work even after giving access to the lawnchair. S7 edge, nougat 7.0, stock rom

**Comment by RWOne** [comment]
~Badges were not introduced on 7.0, you need to be on 7.1.x variant.~
