### ISSUE TITLE
Hide apps on homescreen from drawer

### ISSUE THREAD

**Issue by Donkey-Doug** [Deletescape-Media/Lawnchair#2280]
Make it possible to automatically hide apps in the app drawer that are present on the home screen. Like a "no duplicates" option.

**Comment by quassy** [comment]
For reference: This was requested quite often (see for example #1642 #1352 #1336 #145), got positive feedback but then unfortunately closed without a comment. I would be keen to know if this feature is still being considered.

**Comment by bfcns** [comment]
Shame that this is closed.
