### ISSUE TITLE
Change search provider

### ISSUE THREAD

**Issue by squidink7** [Deletescape-Media/Lawnchair#2284]
I know this was a feature back in the v2 days, however it would be nice to see it return in v12. No hurry, but being able to change the google search bar at the bottom to something like duckduckgo or even just local device/apps search would be nice for privacy reasons among others.
And thanks for taking the time to work on such an awesome open source project! y'all rock.

**Comment by laraib07** [comment]
Maybe implement this as implemented in shade launcher. It uses other app's search widget as dock. If I am not wrong, previous versions used its own widgets with no text on search bar.
