### ISSUE TITLE
Crash after launching

### ISSUE THREAD

**Issue by bkazoo** [Deletescape-Media/Lawnchair#2286]
Device: POCO X3 NFC (MIUI 12.5.3, Android 11)
Lawnchair 12 alpha 2
Logs: https://katb.in/canigavojeg

Lawnchair crashes after a few seconds of being launched.

The issue does not occur if I first install Lawnchair 11 alpha 6.1, run it once, then upgrade to Lawnchair 12 alpha 1 or 2.

**Comment by bkazoo** [comment]
Lawnchair 12 Dev (#&#x2060;502)
Logs: https://katb.in/rafamiresik

**Comment by bkazoo** [comment]
Still reproducible in Lawnchair 12 alpha 3.
Logs: https://katb.in/dowufojefug

**Comment by bkazoo** [comment]
FATAL EXCEPTION: main
Process: app.lawnchair, PID: 5581
android.view.InflateException: Binary XML file line #16 in app.lawnchair:layout/work_apps_edu: Drawable app.lawnchair:drawable/work_card with resource ID #0x7f0804c8
Caused by: android.content.res.Resources$NotFoundException: Drawable app.lawnchair:drawable/work_card with resource ID #0x7f0804c8
Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x109006f
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1144)
	at android.content.res.Resources.loadColorStateList(Resources.java:1156)
[...]

**Comment by felixkrohn** [comment]
I have the same error on LC 12a3 running on android 10 (/e/ OS/LineageOS).
I do have a work profile (managed by [shelter](https://gitea.angry.im/PeterCxy/Shelter/)), and when I disable the work profile the crash does not occur anymore.
Additionnal info: it seems also _not_ to occur when work profile is active, but all applications are "frozen" (=no app shortcuts exist to applications referring to the work profile)
Seeing the error occors whithin  app.lawnchair:drawable/work_card I assume this is related. Happy to help debugging

**Comment by bkazoo** [comment]
Unable to reproduce on Lawnchair 12.1 Alpha 1.
