### ISSUE TITLE
Pixel 6 pro Android 12 - calendar widget works after placing in the desktop and fails later 

### ISSUE THREAD

**Issue by hubertmeier** [Deletescape-Media/Lawnchair#2287]
Pixel 6 pro Android 12 - calendar widget works after placing in the desktop and fails later "Fehler beim Laden des Widgets"

After a reboot of the Phone it works again, but later it fails again

**Comment by progranadegrinder** [comment]
Having the same problem, Lawnchair crashes with YT Musics widget and the Google weather doesn't work for hours then does idk
