### ISSUE TITLE
Searchbar Icons

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#2289]
When apply accent to Searchbar enabled. The new Material You colors are causing the Searchbar icons to have rough edges. Need some image cleanup. Pixel 5 Android 12. Most noticeable on assistant microphone and lens icons.

**Comment by suphon-t** [comment]
Can you attach images for comparison?

**Comment by iOSXPC** [comment]
![comparison](https://user-images.githubusercontent.com/1809251/141602005-a11a10eb-5b0f-45ba-8f27-3ae117e049aa.png)
