### ISSUE TITLE
Status Bar Text

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#2292]
Option to force dark status bar text. White on light is hard to see.

**Comment by GatherStar** [comment]
![Screenshot_20211106-160601_Lawnchair](https://user-images.githubusercontent.com/50571479/140602982-6d29cb9b-c674-459c-9eb5-76f5e0c5a0e0.jpg)
Me too, and if you wallpaper is dark it's hard to see quick bar.

**Comment by RikKoedoot** [comment]
Did you crop this image or do you have a real weird aspect ratio

**Comment by GatherStar** [comment]
Black is part of the picture.It makes my pad look slimmer
