### ISSUE TITLE
Bypass F-droid delay by creating and allowing users to add a Lawnchair repo to f-droid.

### ISSUE THREAD

**Issue by anon2828226** [Deletescape-Media/Lawnchair#2296]
for example the NewPipe team made a repo so that during a time of heavy development updates could be sent out without delay. https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by kafisc1** [comment]
Sounds like a great idea to me!

**Comment by Donkey-Doug** [comment]
+1
