### ISSUE TITLE
Widget Resizing Issue

### ISSUE THREAD

**Issue by cyberlog69** [Deletescape-Media/Lawnchair#2303]
Can't Resize the widgets add into the homescreen on Realme UI 2.0 Android 11

**Comment by ueen** [comment]
Pixel 4a 5G same issue (alpha3)

**Comment by jackleson** [comment]
same on OnePlus 7t lineageOS 18.1 with lawnchair 12 alpha 3. I don't think they have implemented that in lawnchair 12 yet tbh.
