### ISSUE TITLE
Accent color on Search bar barely visible in light mode

### ISSUE THREAD

**Issue by Mayank-9018** [Deletescape-Media/Lawnchair#2306]
Accent color on Search bar icons are barely visible(looks like grayscale) in light mode.
Light mode:
![Screenshot_20211103-103142](https://user-images.githubusercontent.com/77046231/140012427-6154607d-2a21-4ab2-bf71-5327f88713ba.png)
Dark mode:
![Screenshot_20211103-103153](https://user-images.githubusercontent.com/77046231/140012436-a2758e24-2bb1-4d41-9249-2890313c7218.png)

**Comment by suphon-t** [comment]
This is working as intended
