### ISSUE TITLE
Widget error

### ISSUE THREAD

**Issue by phiotmg** [Deletescape-Media/Lawnchair#2307]
When I add google photo widget in home screen, it crashed and can't be added. Look at following video.

https://user-images.githubusercontent.com/93658451/140065785-6c2245ad-36ee-4be9-8580-c594104fd547.mp4

**Comment by RikKoedoot** [comment]
closing because #2312 is the same issue and they provided logs

**Comment by RikKoedoot** [comment]
closed due to lack of logs
