### ISSUE TITLE
Widget size mismatched

### ISSUE THREAD

**Issue by KatJillianne** [Deletescape-Media/Lawnchair#2309]
(Issue) Incorrect widget size at custom grid size (other than default 5x5):
![Screenshot_20211103-222225_Lawnchair](https://user-images.githubusercontent.com/78527672/140090166-f8059426-ed7f-4de3-8b37-862f24b542e8.png)

**Comment by suphon-t** [comment]
Explained in [https://t.me/lccommunity/580285](https://t.me/lccommunity/580285)
