### ISSUE TITLE
Change icon, new messages

### ISSUE THREAD

**Issue by xmiseggs** [Deletescape-Media/Lawnchair#231]
For example when changing the WhatsApp icon and receiving a new message does not display the new message ball in the new icon. View image.

http://s2.subirimagenes.com/otros/previo/thump_9768723img20170717143922.jpg

**Comment by xmiseggs** [comment]
<a href='http://www.subirimagenes.com/otros-img20170717143922-9768723.html'><img src='http://s2.subirimagenes.com/otros/previo/thump_9768723img20170717143922.jpg' alt='subir imagenes' border='0'></a>

**Comment by fonix232** [comment]
Lawnchair has no control over the notification icon displayed.

**Comment by xmiseggs** [comment]
It is solved by rebuilding the icon database and rebooting. Thank you.
