### ISSUE TITLE
Widget Resize Bug

### ISSUE THREAD

**Issue by mcspidey95** [Deletescape-Media/Lawnchair#2311]
For some widgets like google photos and another widget, the widgets are only resizable either vertically or horizontally, and not both.
Here's a screen recording.

https://user-images.githubusercontent.com/90018162/140463043-a79dd638-a4c0-481c-8f0c-171c7e25d1fb.mp4

**Comment by suphon-t** [comment]
This is because some widgets have a minimum size constraint to prevent breaking the layout. We'll add an option to ignore the constraint later.
