### ISSUE TITLE
The overview button stops working some time after boot on Android 12

### ISSUE THREAD

**Issue by vctls** [Deletescape-Media/Lawnchair#2313]
Pixel 3, Android 12, 2021-10-05 update
The overview button stops working some time after boot. Click animation is shown but nothing happens. Rebooting or switching to the stock Pixel launcher and back “fixes” the problem for a moment.
Not sure what can be done from Lawnchair, it seems other third party launchers are also having that problem:
https://www.reddit.com/r/Pixel4a/comments/qm3x3a/overview_button_does_not_react_since_android_12/

**Comment by suphon-t** [comment]
As /u/LyleJay mentioned, it's an issue in Android itself and only Google can fix it.

**Comment by vctls** [comment]
All right, thanks for clarifying the issue.
