### ISSUE TITLE
Custom Accent Colors

### ISSUE THREAD

**Issue by rufus582** [Deletescape-Media/Lawnchair#2314]
Is it possible to add the ability to type in a hex color code as the accent color?🤔

And also, for any wallpaper, I notice that the accent color is picked based on the wallpaper background color. This makes the app icons basically black and white on amoled wallpapers, where only the bg color is black and there are colorful shapes that are scattered throughout the wall. 
So is it possible to add an option to pick the prominent color for every wallpaper, instead of the background color?🤔

**Comment by SuperDragonXD** [comment]
Now available in Lawnchair 12.1 Alpha 4. Closing this issue.
