### ISSUE TITLE
Quick Actions Missing

### ISSUE THREAD

**Issue by ajudi46-zz** [Deletescape-Media/Lawnchair#2315]
Unable to find quick actions in any apps after long pressing it , I have already set lawnchair as a default launcher app 
Error screenshot - 
![Screenshot_20211106-144219.jpg](https://user-images.githubusercontent.com/36822947/140604584-ee8b6943-bf75-4657-ab7b-919279c3ef32.jpg)

Phone - OnePlus 6T
Rom - Stock Rom
OS - Oxygen OS 11

**Comment by mayanksh3khar** [comment]
> Unable to find quick actions in any apps after long pressing it , I have already set lawnchair as a default launcher app Error screenshot - ![Screenshot_20211106-144219.jpg](https://user-images.githubusercontent.com/36822947/140604584-ee8b6943-bf75-4657-ab7b-919279c3ef32.jpg)
> 
> Phone - OnePlus 6T Rom - Stock Rom OS - Oxygen OS 11

Unrelated, but can you tell how did you get those themed icons on non Google apps. TIA

Am on V12A3 build in OP7P using KOSP A12 custom ROM

**Comment by tomskra** [comment]
Same problem on Samsung Galaxy S20 (Android 12 & One UI 4). Quick Actions works only in App Drawer when you type app name. With Long press actions not work.

![Screenshot_20220210-153800_Lawnchair](https://user-images.githubusercontent.com/11139471/153430431-a59cb732-6059-4c4c-b91d-207894a190be.jpg)
![Screenshot_20220210-153807_Lawnchair](https://user-images.githubusercontent.com/11139471/153430440-4562c4a1-b75b-4836-bbd3-359f1ba193d8.jpg)
![Screenshot_20220210-153819_Lawnchair](https://user-images.githubusercontent.com/11139471/153430456-d2fb31df-665a-40a9-b733-7b982951ff60.jpg)
