### ISSUE TITLE
Cannot override system launcher

### ISSUE THREAD

**Issue by you-just-got-cyberpunked** [Deletescape-Media/Lawnchair#2318]
I'm unable to set lawnchair as my launcher. Whenever is press Home, it goes to the system one. Didn't find a way to manually set it in system settings and 'set as default launcher' in lawncheair does nothing. 

The whole thing happened randomly, while the phone was running. I didn't fiddle with anything, there wasn't even a system update. Reinstalling lawnchair didn't work.

Using lawnchair 2.0-2589, but the same problem happened with the latest alpha.
Phone: realme 6
OS: realme UI 2021.10.09

edit: found it in system settings, it was just poorly translated.

**Comment by RikKoedoot** [comment]
This sounds like colorOS being colorOS, try setting Lawnchair in settings, apps, default apps, home app
