### ISSUE TITLE
Delete homescreens

### ISSUE THREAD

**Issue by sagarsumit03** [Deletescape-Media/Lawnchair#232]
Hi, I am not able to delete the home screen.

**Comment by sagarsumit03** [comment]
I am not able to manage my home screens as if i press home navigation button which home screen should be set as default

**Comment by RWOne** [comment]
This launcher is similar to stock.

To remove a screen, remove all its items.

The home screen will always be the first one when started, with feed to left and additional screens added as you drag items to it in overview.

**Comment by guest4711** [comment]
@sagarsumit03 See also #308

_Sent from my Samsung GT-I9295 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
