### ISSUE TITLE
how to implement strech scroll view?

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2323]
can anyone help me how to implement the strech scroll view from android 12 in my app

**Comment by suphon-t** [comment]
Take a look at [this class](https://github.com/LawnchairLauncher/lawnchair/blob/12-dev/lawnchair/src/app/lawnchair/ui/StretchRelativeLayout.kt)

**Comment by ghost** [comment]
> Take a look at [this class](https://github.com/LawnchairLauncher/lawnchair/blob/12-dev/lawnchair/src/app/lawnchair/ui/StretchRelativeLayout.kt)

Thanks...but now how do apply it to every layouts?

**Comment by msfjarvis** [comment]
> > Take a look at [this class](https://github.com/LawnchairLauncher/lawnchair/blob/12-dev/lawnchair/src/app/lawnchair/ui/StretchRelativeLayout.kt)
> 
> Thanks...but now how do apply it to every layouts?

We can't give you a step by step guide about Android development in our issue tracker, please seek help in an appropriate channel such as StackOverflow.
