### ISSUE TITLE
Hidden apps reappear in App Drawer intermittently

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2324]
After selecting Hide App, the app seems to suddenly appear in the app drawer again.
I can't work out what is causing it, but can happen within a matter of a minute at times.

**Comment by federico-ntr** [comment]
It happened to me also, but only after disabling some system apps (they were hidden too). I disabled an app and then I noticed a hidden app showed. I had to untick and tick to make it disappear again, and then, after disabling another app it happened again.

I'm using a Pixel 6 with Android 12 stock, unrooted and locked.

@jslawler did you notice if the bug happened in similar conditions?

**Comment by ghost** [comment]
> It happened to me also, but only after disabling some system apps (they were hidden too). I disabled an app and then I noticed a hidden app showed. I had to untick and tick to make it disappear again, and then, after disabling another app it happened again.
> 
> I'm using a Pixel 6 with Android 12 stock, unrooted and locked.
> 
> @jslawler did you notice if the bug happened in similar conditions?

Hi @federico-ntr,

I wasn't able to force it to happen. It happened twice in the space of a day before I reported it. The first time I thought I'd toggled hidden apps off. Upon discovering it was turned on, I toggled it off, then back on, hiding the app.
Approximately 1 minute later, it had reappared. Below, I've stated a few of the actions I presumed I'd used around that time that may have somehow caused the bug.

I tried:
- Restarting the device
- Force closing the hidden app
- Clearing the hidden app cache
- Clearing the hidden app storage
- Toggling network usage via hidden app customise menu
- Clearing the hidden app from recents
- Clearing all recents

OnePlus 6, LineageOS 18.1, no root, unlocked

**Comment by Donkey-Doug** [comment]
I have the same issue.

LineageOS based on android 10
Xiaomi Mi 9T Pro

**Comment by Donkey-Doug** [comment]
I don't know how to trigger the bug, but I managed to record it when it happend. For me, the problem fixes itself:


https://user-images.githubusercontent.com/50382414/156901498-2f6819b1-20c0-4236-8f55-3b8713069c4d.mp4

**Comment by vrpcse** [comment]
I think, I could reproduce it in a certain way. 
1.Open a hidden app after searching from app drawer search.
2. Use that hidden app for a while.
3. Exit that app using only back key.
4. Now open the app drawer if in home screen or if still in search results page (step 1), use the back key and open app drawer.
5. Now I could see all hidden apps in app drawer.
6. Not able to reproduce again at the same day. Next day, following all these steps, i was able to reproduce

**Comment by federico-ntr** [comment]
I can confirm this happened to me in the recent past following this flow.

Il mar 15 mar 2022, 13:23 rajapandi_vijayakumar ***@***.***>
ha scritto:
