### ISSUE TITLE
Dock disappeared

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2325]
I've been running LC alpha 3 since the day it was released to the public.
About a minute ago after waking the device, the dock disappeared permanently.

Force closing, and clearing cache did not fix the issue.
I had to clear app storage data.

OnePlus 6, LineageOS 18.1, no root, unlocked

**Comment by SuperDragonXD** [comment]
Late reply, but it should be fixed in the later versions (Lawnchair 12.1). Also closing since this is relevant to the older versions only (we no longer support older versions).
