### ISSUE TITLE
FC on moving app from App Drawer to Dock

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2326]
After raising #2325, and setting up LC 12 Alpha 3 again, dragging Outlook.app from the App Drawer to the Dock caused LC to FC.

App generated logs attached.

[Lawnchair bug report 12 Nov 2021 21:30:53.txt](https://github.com/LawnchairLauncher/lawnchair/files/7527285/Lawnchair.bug.report.12.Nov.2021.21.30.53.txt)

**Comment by suphon-t** [comment]
This was fixed in acad5e5. A new release with the fix will be published soon.
