### ISSUE TITLE
Wallpaper is not centered

### ISSUE THREAD

**Issue by caniculabv** [Deletescape-Media/Lawnchair#2331]
Wallpaper is not centered. Samsung Galaxy S21 Android 11.

**Comment by CanKolay5677** [comment]
I have that issue too hole is should be at the top left corner (A21s)

![Screenshot_20211117-211259_Lawnchair](https://user-images.githubusercontent.com/80613396/142258230-e055abe3-ec5d-4918-8b01-bbb9c54b0e31.jpg)

**Comment by hipblo** [comment]
Mine also is not centered at all, tried everything and still have the same issue :/

**Comment by SuperDragonXD** [comment]
Sorry for the late reply, but try disabling wallpaper scrolling (Home Settings > Home Screen > Scroll Wallpaper) and see if it fixes the issue.
