### ISSUE TITLE
Ghost icon after moving app out of folder on desktop

### ISSUE THREAD

**Issue by lijandrew** [Deletescape-Media/Lawnchair#2339]
S10+ running Android 11

Ghost icon disappears after restarting launcher

https://user-images.githubusercontent.com/39812702/143264285-49dfda08-0c96-4104-9674-e808bfa15021.mp4

**Comment by RikKoedoot** [comment]
I see you are not using the latest lawnchair version. could you check if it also happens on lawnchair 12?

**Comment by lijandrew** [comment]
> I see you are not using the latest lawnchair version. could you check if it also happens on lawnchair 12?

Didn't realize Play Store version is outdated. Problem solved by updating to v12 via apk
