### ISSUE TITLE
Samsung Galaxy Buds 2 controller widget wrong size

### ISSUE THREAD

**Issue by Randomblock1** [Deletescape-Media/Lawnchair#2340]
Lawnchair says the widget is 4x2 but Nova Launcher correctly identifies it as 4x1. Weird. Samsung has a configuration screen when placing it down, so that might be tripping it up.

**Comment by Randomblock1** [comment]
Now that I've updated my Android, it seems like it's no longer crashing, just incorrectly recognizing the size.

**Comment by RikKoedoot** [comment]
https://t.me/lccommunity/580285 check this message

**Comment by Randomblock1** [comment]
Ok, I found a workaround. Just set the grid size to 4x5, place the widget, and resize it again. It will be 4x1 again.
