### ISSUE TITLE
device search in app drawer stopped working

### ISSUE THREAD

**Issue by elea11** [Deletescape-Media/Lawnchair#2342]
Since actions build #601 (commit https://github.com/LawnchairLauncher/lawnchair/commit/4230a382e4e8aa9b8195a7802fc6a220322d2dcc) my device search doesn't even show apps anymore. What's meant by "if the service is enabled" in the commit? Seems to be related.

- Device, ROM, Setup:
- Pixel 4a 5G (bramble)
- protonAOSP 12.0.0
- microg
- search to browser (app from f-droid)

There were three suggestions to solve the issue:
1. Rollback to an older actions build (#600) than the aforementioned.
2. Rollback to an older build of Android System Intelligence (S.10 --> S.8) does not help, contrary to what was claimed on the Telegram help chat.
3. Neither clearing app data does anything

**Comment by suphon-t** [comment]
This was already fixed in 9b9fa4f.

**Comment by elea11** [comment]
Yes indeed. Thanks for the quick response.
