### ISSUE TITLE
navigationbar is blocking the add to home screen button

### ISSUE THREAD

**Issue by beetrootpotatocarrot** [Deletescape-Media/Lawnchair#2345]
![Screenshot_20211127-192838_Lawnchair](https://user-images.githubusercontent.com/81223029/143710241-bece69b3-dcff-465b-a703-039894a1000a.png)

**Comment by SuperDragonXD** [comment]
Issue should be fixed in the later versions. If it still doesn't work, it's more of an OEM issue than a Lawnchair one. Closing this issue
