### ISSUE TITLE
Lawnchair doesn't Adapt to Material You Accent in Android 12

### ISSUE THREAD

**Issue by Exotic-Lambo** [Deletescape-Media/Lawnchair#2350]
There's this weird bug in Lawnchair 12 Alpha 4 in My Device Running Android 12 Pixel UI

Whenever I apply New Wallpaper lawnchair stays on Previous Accent. In settings it display the correct system accent but whole lawnchair app remains on old accent I tried restarting Lawnchair too and switching between wallpaper accent and system accent too but nothing fixed the Issue

After that I went to System settings>Themes to reapply accent and It worked

I tried restarting lawnchair just to check and Bam I got that Old Accent that is Brown

technically I am stuck on brown accent unless I reapply it from system themes section or Use Predefined or Wallpaper Aceent

I can't even take logs of this issue as it appears in weird pattern 

Here's The Video
https://user-images.githubusercontent.com/88485170/144113123-6363ea3c-a9ce-4f0b-815f-d52902d74cec.mp4

And my current homescreen
![msg-1141195437-597484](https://user-images.githubusercontent.com/88485170/144112717-49614fa8-dd45-4a6b-991c-af63ab065c23.jpg)

Original Messages in Lawnchair Help and Feedback
https://t.me/lccommunity/597473
https://t.me/lccommunity/597484

**Comment by SuperDragonXD** [comment]
Try updating to the later versions of Lawnchair, it may have been fixed. Also closing since this is relevant to the older versions only.
