### ISSUE TITLE
Request for editing app drawer icons

### ISSUE THREAD

**Issue by ishaanrathodd** [Deletescape-Media/Lawnchair#2352]

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
You can already edit icon. Just tap it. ![IMG.jpg](https://user-images.githubusercontent.com/46166740/145435224-49c01901-f14a-4fa4-8f5b-a16e0cde67f9.jpg)

**Comment by RikKoedoot** [comment]
He requested it to be added in v12, which doesn't have it

**Comment by ishaanrathodd** [comment]
Yes v12 alpha 4 doesn't have the feature to edit icons individually

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Where you find this version? There is no release on GitHub or stores. Not even for beta tester.

Why does newer versions include less features? Isn't that a downgrade?

**Comment by RikKoedoot** [comment]
https://github.com/LawnchairLauncher/lawnchair/releases here is a link to all releases. its also available at t.me/lawnchairci.

Since v11 we are rewriting lawnchair (hence the missing features). they will slowly return in the future aswell

**Comment by SuperDragonXD** [comment]
Late reply, but the feature has been added in Lawnchair 12.1+. Simply long press an icon on the app drawer > "Customize" > Choose an icon. As a side effect, it also changes the icon on the home screen. Since this was added, closing this issue.
