### ISSUE TITLE
Feature Request: Option to hide work profile section of app drawer

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2356]
Would it be possible to add some way to completely hide the work profile section of the app drawer? I tried hiding every work profile app, but it still shows the empty drawer (screenshot below).

Thank you!

![Screenshot_20211202-092640](https://user-images.githubusercontent.com/93940677/144440933-8c7a5a98-cd4e-4a82-905e-3296d4d2dd15.png)

**Comment by Qxji** [comment]
This would be amazing!!
