### ISSUE TITLE
I can't switch apps in recent apps

### ISSUE THREAD

**Issue by iBabu007** [Deletescape-Media/Lawnchair#2357]
Why it can't show recent apps ?
I can't show recent apps and can't switch apps.
Please suggest any solution.

**Comment by iBabu007** [comment]
No, this problem is not resolved.

**Comment by Amorphous404** [comment]
> No, this problem is not resolved.

Which Lawnchair Version?
ROM?
Android Version?
Using Quickswitch?

**Comment by iBabu007** [comment]
12.1
Stock Android
Android 10
No

**Comment by iBabu007** [comment]
Please help me

**Comment by SuperDragonXD** [comment]
Does it still persist even in the latest version?

**Comment by iBabu007** [comment]
Hi sir, don't close it.
Actually it's android version is Android 10.
That's why it can't work.
Google blocked 3rd party launchers.
See this image
![Screenshot_20221123-224803](https://user-images.githubusercontent.com/65340361/203714503-77e817ae-a626-4482-acae-6e370b080123.png)
