### ISSUE TITLE
Lawnchair force closes after app that's had its icon changed manually is updated via play store

### ISSUE THREAD

**Issue by jwigley24** [Deletescape-Media/Lawnchair#236]
For example, I'm using a custom icon pack (viral), and I changed the Instagram icon manually using the new feature added in version 818, and everything was fine. Once the Instagram app updated via play store, lawnchair automatically force closes and anytime I try opening it again it force closes - I have to clear data to get it to open again.

I tested this a couple times. If using a custom icon pack, but not changing any app icons manually, then all is fine when an app updates in the play store. This only happens when an app that you've manually changed the icon for is updated at some point via the play store.

**Comment by suphon-t** [comment]
Fixed by b231ac7.
