### ISSUE TITLE
The Chinese name software does not sort correctly in the "Drawer".

### ISSUE THREAD

**Issue by Ookvkin1oO** [Deletescape-Media/Lawnchair#2361]
In the "Drawer" screen. Some of the programs with Chinese names are not correctly sorted and ordered.
在“抽屉”里，部分中文名的软件排序错误

![Screenshot_20211204_160714](https://user-images.githubusercontent.com/67348571/144702930-1d459cd4-d780-459b-bdfe-1e19d97c5bb2.jpg)

**Comment by FrzMtrsprt** [comment]
What do you mean by "not sorted correctly"? From what I see they're all correctly sorted by their Pinyin.

Also Lawnchair 11 or earlier versions aren't actively maintained any more, so they aren't likely to be updated. You may want to move to Lawnchair 12 instead.

“排序错误”指的是什么呢？ 图中的应用都按拼音正确排序了啊。

此外，Lawnchair 11 或更早版本已经不再维护了，所以不太可能会再更新，建议更新到 Lawnchair 12。
