### ISSUE TITLE
Lawnchair crashed

### ISSUE THREAD

**Issue by ydmkavinda** [Deletescape-Media/Lawnchair#2363]
Lawnchair bug report Dec 7, 2021 11:01:07 version: 12.0 Alpha 4 (120004) commit: 2cce1b0 build.brand: Nokia build.device: SLD_sprout build.display: 00WW_2_400_SP07 build.fingerprint: Nokia/Starlord_00WW/SLD_sprout:10/QKQ1.191014.001/00WW_2_40H:user/release-keys build.hardware: qcom build.id: QKQ1.191014.001 build.manufacturer: HMD Global build.model: Nokia 6.2 build.product: Starlord_00WW build.type: user version.codename: REL version.incremental: 00WW_2_400_SP07 version.release: 10 version.sdk_int: 29 display.density_dpi: 356 error: Uncaught exception java.lang.NullPointerException 	at e5.b$b.onClick(Unknown Source:47) 	at android.view.View.performClick(View.java:7140) 	at android.view.View.performClickInternal(View.java:7117) 	at android.view.View.access$3500(View.java:801) 	at android.view.View$PerformClick.run(View.java:27355) 	at android.os.Handler.handleCallback(Handler.java:883) 	at android.os.Handler.dispatchMessage(Handler.java:100) 	at android.os.Looper.loop(Looper.java:214) 	at android.app.ActivityThread.main(ActivityThread.java:7397) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by RikKoedoot** [comment]
please provide some more info on how it crashed

**Comment by SuperDragonXD** [comment]
Closing this issue due to: User not providing information & issue is likely fixed in newer versions.
