### ISSUE TITLE
App search not working

### ISSUE THREAD

**Issue by keyjeyelpi** [Deletescape-Media/Lawnchair#2366]
![Screenshot_20211208-093636](https://user-images.githubusercontent.com/49813589/145132818-3750dc04-a58c-49b6-8a1d-5f57feba6ffe.png)
Search doesn't work on Lawnchair 12 Pixel Experience (Android 12)

**Comment by mclarence** [comment]
I am having this issue as well on rooted pixel 6 pro running android 12. Running the alpha 4.

When it is enabled in quickswitch, the above issue occurs, when its not it works normally.

EDIT:
Downgraded to alpha 3 and it appears to be working again.

**Comment by drishal** [comment]
Same here, tried it on evolution x ROM 
seems like pixel and pixel based roms are having issues with search

**Comment by bkvishal** [comment]
Yes, the issue still persists in Derpfest 12 custom rom when quickswitch is enabled.
