### ISSUE TITLE
Not compatible with 12L

### ISSUE THREAD

**Issue by FrzMtrsprt** [Deletescape-Media/Lawnchair#2369]
Lawnchair is marked "Not compatible with Android 12" in QuickSwitch on Android 12L Beta 1, due to Lawnchair's targetSdkVersion being 31 instead of 32.

**Comment by skittles9823** [comment]
Known issue. Just need to set [this](https://github.com/LawnchairLauncher/lawnchair/blob/b93878528ebd29fce5befd4b5a3e02850657d660/lawnchair/AndroidManifest.xml#L106) to 32 and test recents changes.

**Comment by suphon-t** [comment]
This is the intended behavior as the API is changed. We'll have to wait until Google drops 12L source to incorporate the changes.
