### ISSUE TITLE
Crashes when battery saver is on.

### ISSUE THREAD

**Issue by ctnlaring** [Deletescape-Media/Lawnchair#237]
Whenever I press the home button with battery saver on the app crashes and my phone reverts to stock launcher.

Nexus 6p
Android 8.0 OPP3
Not rooted
Stock kernel
Unlocked bootloader

**Comment by drew5494** [comment]
Same here except I'm not rooted  Android 8.0

**Comment by ctnlaring** [comment]
I'm sure it's having issues with some new battery saving feature in O

**Comment by fonix232** [comment]
Since O is not finalized yet, and we do not have devices to test such bugs, I'd refrain from promising anything regarding such issues. After the official release of O, with the finalized APIs and subsystems, if this still happens, we will look into it.

**Comment by 00raq00** [comment]
Fixed
