### ISSUE TITLE
App suggestions

### ISSUE THREAD

**Issue by RafalManka** [Deletescape-Media/Lawnchair#2371]
When I install the "Lawnchair 2" app from the play store, I can see suggested apps on top of the App Drawer. 
![suggestions](https://dl3.pushbulletusercontent.com/dAtjbnC0wUrtUFydjM9nT3gdl7BQThqr/Screenshot_20211210-123634.png)

But when I clone Lawnchair project here from GitHub and run in Android Studio by using variant `lawnQithQuickStepDebug` , suggested apps are not shown. A permission dialog also does not pop up.

Why is this the case? Do I need to run it with other flavors? Is that even possible? or is that feature not supported at this point in time?

Sorry if I'm asking a stupid question, started working on this code just recently.

**Comment by Degl1** [comment]
don't get that 4 year old Lawnchair.

**Comment by SuperDragonXD** [comment]
Late reply, but could you rename the title to "[FEATURE] Re-add app suggestions"?

Also, the current versions of Lawnchair needs root access and Android System Intelligence to show app suggestions. Lawnchair basically gets the data from that app. Therefore, there's no option for that.

They may re-add app suggestions soon for non-root users (in the form of getting usage access and manually processing and showing it), but can't give an ETA though.
