### ISSUE TITLE
Text in lawnchair is missing shadows and it's making it hardly readable

### ISSUE THREAD

**Issue by soredake** [Deletescape-Media/Lawnchair#2375]
Pixel Launcher:
![Screenshot_20211130-103351131](https://user-images.githubusercontent.com/5204968/145864154-60d35595-5501-436a-8101-39d8ea7e4b8a.jpg)

Lawnchair:
![Screenshot_20211130-103924773](https://user-images.githubusercontent.com/5204968/145864360-fc5e5214-b930-43b4-88be-e1f9b08d86c0.jpg)
![Screenshot_20211130-103325517](https://user-images.githubusercontent.com/5204968/145864362-8905231c-5f76-47d2-928d-67bcddd43f6c.jpg)

**Comment by RikKoedoot** [comment]
Lawnchair does have a shadow, it's less pronounced though. Also what Lawnchair version is this?

**Comment by soredake** [comment]
Lawnchair 12 Alpha 4 on android 11.

**Comment by soredake** [comment]
Better shadow defaults and shadow settings will be good.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Recent version gained some shadows, but i think it still needs more of them.

**Comment by soredake** [comment]
Okay bot, you win.
