### ISSUE TITLE
Lawnchair affects system navigation gestures

### ISSUE THREAD

**Issue by AlgebraManiacABC** [Deletescape-Media/Lawnchair#2379]
I have two devices I use Lawnchair with (can you tell I'm a fan?): Google Pixel 3a and Moto One 5G Ace. My Pixel has had Lawnchair since it was Android 10 or even 9, and is now 12. My Moto is Android 10 (unfortunately...).

The two devices have different effects when using Gesture Navigation (the one from Pie). Expected behavior is that of my Pixel:
* Swiping up from the bottom of the screen in any app shows the home screen
* Swiping up from the bottom of the screen in any app (or the launcher) and holding at quarter-to-mid-height shows recent apps
* Swiping right or left along the bottom of the screen in any app (or the launcher) cycles through recent apps
* Swiping right from the left of the screen sends the "back" button

These gestures work as intended on my Moto as well using the default launcher. However, with Lawnchair:
* Swiping up still shows home
* Swiping up and holding does not show recent apps. It tries to go home (no matter where I hold).
* Swiping right or left along the bottom of the screen doesn't do anything. Some apps actually use it as input, causing headaches.
* Swiping right from the left of the screen does correctly send "back"

I used to use the 2-button or "pill" navigation on my Pixel (and was bummed to see it scrapped), and it worked as intended as well (although it was more obviously a system input then, since a whole navbar was still dedicated to it).

Both Lawnchair versions are equivalent: 2.0-2589

**Comment by StevenAlexander44** [comment]
Is this the same problem as described in #2051? If so, I also have this problem on the Moto G Play running android 11

**Comment by AlgebraManiacABC** [comment]
> Is this the same problem as described in #2051? If so, I also have this problem on the Moto G Play running android 11

No. That issue is about a navbar which is always shown.

My issue is about gesture navigation not working as intended with Lawnchair.

**Comment by Degl1** [comment]
This is hard to fix as Google cucked gestures on 3rd party launchers. Only way to fix is either QuickSwitch or LawnChair Module.

**Comment by SuperDragonXD** [comment]
Late reply, but it's impossible to fix unless you have root access (or QuickSwitch) since the API is only accessible to system launchers. Closing this issue.

**Comment by derzahla** [comment]
I am experiencing the same problem here. **rooted** pixel 5, android 13. installed lawnchair as a magisk module.  please advise, I have root, how can I make this work?
