### ISSUE TITLE
Auto reapply current icon pack when changing wallpaper or device theme

### ISSUE THREAD

**Issue by rodrigoswz** [Deletescape-Media/Lawnchair#2383]
Currently there are some icon packs with Monet (Dynamic Material You) support that are also changed with Dark Theme turned on or off.

Which is amazing but there is a limitation: the icon colors of these Icon Packs are only updated if the icon pack is reapplied.

It would be perfect if Lawnchair 12 could automatically reapply the current Icon Pack to fix this limitation.

Some examples of Icon Packs with Monet support:
- https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark
- https://play.google.com/store/apps/details?id=iconpack.onsurface.monet

**Comment by topsy-turvy99** [comment]
#2866
