### ISSUE TITLE
Launcher client (Google feed) not connected in release version

### ISSUE THREAD

**Issue by ducky94tb** [Deletescape-Media/Lawnchair#2387]
When I use version Alpha 4, 
Lawnchair.12.Alpha4.apk
There is no feed at minus one page

**Comment by RikKoedoot** [comment]
Did you install Lawnfeed v3?

**Comment by ducky94tb** [comment]
On debug version, not not to install Lawnfeed apk.
Is it different between debug and release version?

**Comment by RikKoedoot** [comment]
Yes. The release version needs Lawnfeed, due to how the discover feed works, only debug apps can access the feed, this is why debug builds of Lawnchair can access it. For release builds we have lawnfeed because of that.
