### ISSUE TITLE
Add Android 8.0 support 

### ISSUE THREAD

**Issue by phantomboy0** [Deletescape-Media/Lawnchair#2388]
Add Android 8.0 support  for Lawnchair v12

**Comment by Degl1** [comment]
I think it is quite hard to make as it is a minimum Android API level dependant.

**Comment by suphon-t** [comment]
> I think it is quite hard to make as it is a minimum Android API level dependant.

That’s not true. Lawnchair 12 currently supports down to Android 8.0.
