### ISSUE TITLE
Per Icon Customisation

### ISSUE THREAD

**Issue by Raul1198** [Deletescape-Media/Lawnchair#2389]
An option to set custom icon from icon packs. For example linebit doesn't have icon for Nekogram X (yes I can request for it to linebit dev but no request accepted when doing a request in the linebit app) , if lawnchair would support Icon customisation I could set telegram icon for Nekogram X like in old lawnchair 10. For now the only option support is Hiding from app drawer and changing lable when an app is long pressed

![Screenshot_20211225-120141_Lawnchair](https://user-images.githubusercontent.com/29801315/147378972-bcadc3ac-92fa-44b7-9b55-a3cf988c2fc8.png)

**Comment by ghost** [comment]
I would also like to have this feature in the launcher.

**Comment by Ishaanrathod09** [comment]
Want this feature too!

**Comment by Graydenn** [comment]
Please! Necessary feature

**Comment by thegyanipintu** [comment]
+1 for this feature. Some icon themes incorrectly set icons for even primary applications like phone. So per icon customization from any of the installed icon packs would be a great feature. For reference, Ruthless launcher already does this.

**Comment by Orphen1989** [comment]
+1

**Comment by Degl1** [comment]
Yes add individual app icons. And add themed icon option too. So I could select a certain themed icon for a certain app.

**Comment by ghost** [comment]
Lack of this feature is what I'm on old Lawnchair & probably prefer Nova. I'm still waiting for this 👉👈

**Comment by Raul1198** [comment]
Already available in Lawnchair 12 Alpha 5 as an experimental feature

**Comment by RikKoedoot** [comment]
@pc00per it's in the experimental features menu in the top right 3 dot menu, enable it.
