### ISSUE TITLE
Google Button in top disappears and is unresponsive

### ISSUE THREAD

**Issue by Xyolyp** [Deletescape-Media/Lawnchair#239]
Sometimes nur I can't tell when, the Google pill won't reakt to taps or won't even show up at all on screen.
I have a Nexus 6P with stock Android 7.1.2

**Comment by RWOne** [comment]
Sometimes backing out after making a change to the app it no longer shows, in this cases I just went to debug and restarted the app.

**Comment by Xyolyp** [comment]
It appears randomly after I unlock my phone or press the home button while having any app opened. I guess it hapens sometimes eben the launcher initialises.

**Comment by abtExp** [comment]
Facing similar issues, the pill disappears and I've to go to settings and toggle it to make it reappear (on Moto g 2014(titan))

**Comment by Younes-L** [comment]
Similar issue with the rounded search bar here

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
Btw isn't this a duplicate of #27 ?

**Comment by Xyolyp** [comment]
@Younes-L No we don't talk about the notification stuff on the icons but the search pill in the top left corner on the homescreen.

**Comment by Younes-L** [comment]
@Xyolyp https://github.com/Deletescape-Media/Lawnchair/issues/27#issuecomment-308840709

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Xyolyp** [comment]
@Younes-L I'm sorry, you are right
