### ISSUE TITLE
Non app drawer

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2394]
Brings a option to disable app drawer and send all apps to the home page, like the images from moto app launcher 11
![Screenshot_20211228-175159](https://user-images.githubusercontent.com/95529548/147606276-2a5cbb85-78b8-430c-aceb-3c6d82920aa9.png)
![Screenshot_20211228-175145](https://user-images.githubusercontent.com/95529548/147606277-8600ae46-652f-43fd-bca6-ea9903254d0a.png)
![Screenshot_20211228-175203](https://user-images.githubusercontent.com/95529548/147606278-10fa2f82-0baa-4add-aa17-0ad179376fc6.png)
![Screenshot_20211228-175139](https://user-images.githubusercontent.com/95529548/147606279-d5a51bfa-ef38-4dba-84cd-10a3f905133e.png)

**Comment by linuxd3v** [comment]
There is lawndesk - which is a fork of lawnchair - without the app drawer.  
Unfortunately its last updated 2 years ago - works fine though.  I would 100℅ love this to be a standard feature in lawnchair though.

**Comment by Amorphous404** [comment]
Duplicate of #2096 ?

**Comment by odmfl** [comment]
you can try the following app https://github.com/Launcher3-dev/MXLauncher/releases/tag/0.0.1

it's hard work but it's been implemented in this launcher works well
it is in Chinese but in the end it is understood.
We would have to adapt it here
The commits are as follows:
https://github.com/Launcher3-dev/MXLauncher/commit/6c21cd43e3ba6369ff9a7c6c87aed7cd3645342a
https://github.com/Launcher3-dev/MXLauncher/commit/135b469bb1a49a67a8851111ac0585cff9ddcdb2
https://github.com/Launcher3-dev/MXLauncher/commit/cf16de5b2a60d9ffbc902350e4a0178f72117ed6
https://github.com/Launcher3-dev/MXLauncher/commit/10ad298dd4e1a9b46d0147b7ec7f25495176b744
