### ISSUE TITLE
Return themed icons to lawnchair without lawnicons needed.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2399]
The new dev version showed that the themed icons will be moved to lawnicons, but this is counterintuitive. At least, merge lawnicons to the lawnchair.

**Comment by SuperDragonXD** [comment]
Unfortunately, having Lawnicons as a source of themed icons is a final decision made by the devs for ease of maintenance, to prevent unnecessary commits/prs simply to add icons, and to better manage the themed icons. The devs will not Lawnicons to Lawnchair. Therefore, closing this issue.
