### ISSUE TITLE
Circular Icons

### ISSUE THREAD

**Issue by akapu1** [Deletescape-Media/Lawnchair#24]
Hi.. love your work. Could you please add the automatic circular icons feature like pixel phone for supported app icons..? It will be awesome..

**Comment by deletescape** [comment]
Thanks for opening this issue, had it on my mentsl to do list already but forgot to open an issue for it :joy:

**Comment by akapu1** [comment]
Another thing... I have noticed that the "opened folder" is always in the middle of the screen in-spite of the position of the folder location. Check screenshot. Is it feature of bug..? I prefer normal location. Thank you.
![screenshot jun 15 2017 4_34_22 pm](https://user-images.githubusercontent.com/29450017/27177603-bb36a0ea-51e8-11e7-9d49-9c1deed9bc8e.png)

**Comment by amirzaidi** [comment]
That's a bug I can't reproduce, what device are you using?
Also, circle launcher icons are supplied by the system, I can't force them as far as I know

**Comment by akapu1** [comment]
I am using on Galaxy S8.

And about circular icons... Action Launcher 3 has this feature under icon and animation... If you go to settings to display to icon style and select "round", all apps support pixel's round style automatically turned to round icon.. no icon pack needed... This feature does not require rood and or any other system modifications.. thought I haven't found this feature in any other launcher... Kindly check action Launcher 3 by yourself. I think it can be implemented... Thank you.

**Comment by akapu1** [comment]
check my screenshots of action launcher 3:
![screenshot_20170615-192015](https://user-images.githubusercontent.com/29450017/27183448-6b611204-5200-11e7-955e-70afd7098e1a.png)
![screenshot_20170615-192236](https://user-images.githubusercontent.com/29450017/27183459-73d76370-5200-11e7-8f0f-e328412c04b4.png)

**Comment by amirzaidi** [comment]
Okay I'll look at it, thank you I did not know it
