### ISSUE TITLE
Add to F-Droid repository

### ISSUE THREAD

**Issue by frauhottelmann** [Deletescape-Media/Lawnchair#240]
Hi, keeping the app up to date would be very easy if you submit it to f-droid: https://gitlab.com/fdroid/rfp/issues

"F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device."

**Comment by dimqua** [comment]
In order to complies with [F-Droid's inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy), Lawnchair's devs need to provide f-droid build flavor without non-free dependencies like Google Play Services.

**Comment by osirase** [comment]
I can't wait to see this land in F-droid!

**Comment by guest4711** [comment]
It runs fine on my devices without g-apps. So it should be no problem to build it without using non-free libraries...

**Comment by JonnyTech** [comment]
Runs well for me on my non-gapps phone (microG installed)

**Comment by ildar** [comment]
Filed https://gitlab.com/fdroid/rfp/issues/319

**Comment by Thrilleratplay** [comment]
The GApps requirement only looks like it is only for AwarenessWeather.  It shouldn't too difficult to exclude this for an fdroid build.   The Microsoft Analytics looks like it would be a larger issue.

**Comment by ildar** [comment]
We seem to have a good progress building FOSS version, see
https://gitlab.com/fdroid/rfp/issues/319
@deletescape , @paphonb , developers, I just wanted to be sure you don't
mind adding Lawnchair to F-Droid. Thanks!

**Comment by ildar** [comment]
Guys? Yes is yes, no is no.
In the meanwhile OpenLauncher earns new users on F-Droid 😀

**Comment by JackL54** [comment]
Can we get an update on fdroid release status?

**Comment by nyancrimew** [comment]
Yes, Lawnchair can be added to F-Droid (previously discussed with @ildar via email)

**Comment by fonix232** [comment]
@deletescape Please review PR #806, and if all's good, we should merge & release to F-Droid (and soon after that, Play Store).

**Comment by guest4711** [comment]
f-droid version is online ( Lawnchair (Pixel Launcher features plus customizability) - https://f-droid.org/app/ch.deletescape.lawnchair.plah )

**Comment by ildar** [comment]
Hm! I didn't know the task completed. Thought it's still to make the Foss
flavour and get rid of the NonFreeUpstream antifeature!
