### ISSUE TITLE
Feature Request: Ability to backup/restore settings and homescreen setup.

### ISSUE THREAD

**Issue by thegyanipintu** [Deletescape-Media/Lawnchair#2401]
Resetting phone or sometimes accidentally wiping data of apps causes all the homes creen customisations and settings to reset back to default and at least in some cases for people like me, it takes a lot of time and efforts to put everything back as it was.

A feature to export these settings to a file and restore later will really help.

**Comment by ghost** [comment]
Currently the only way is to titanium/Migrate backup through root. I'm still waiting for this, as devs slowly start pushing these features one by one.

**Comment by suroot66** [comment]
same issue, I have 400+ apps installed 👍

**Comment by SuperDragonXD** [comment]
They'll add it soon™. Just wait. (Or help with the development of Lawnchair)

**Comment by SuperDragonXD** [comment]
Late, but they have added it in Lawnchair 12.1 Alpha 3. Closing this issue since it has been added.
