### ISSUE TITLE
Home screen icons and folders disappear or  app icons moved into different folders after modifying home screen grid.

### ISSUE THREAD

**Issue by vaisakhv** [Deletescape-Media/Lawnchair#2403]
I had this issue multiple times now. Normally I have multiple folders in my main page and some more app icons in the other page.
Now if I edit the row and/or column numbers in the home screen grid, all or most of the icons and/or folders will disappear. Even if a folder has not disappeared the contents of that folder most certainly will not be what I initially had.

Please look into this issue..
Also please do bring back the "lawnchair settings" backup and restore option

My environment 

Device model : Iqoo 7
Manufacturer : Iqoo, Vivo
Android Skin : Funtouch OS 12
Android version : 12
Lawnchair : v12 alpha 04

**Comment by replete** [comment]
I've also had this problem on FDroid latest version.

When dragging in apps to a launcher folder on the home screen,  sometimes a second copy of the icon would be added near or above the 'At a glance' feature and removing that extra copy, sometimes, would also remove the one inside a folder
