### ISSUE TITLE
Bug: App not installed

### ISSUE THREAD

**Issue by FBIAgent05** [Deletescape-Media/Lawnchair#2408]
When you open a shortcut from a browser (Add to home screen), it does not open, and a toast shows up "App not installed".

**Comment by RikKoedoot** [comment]
Which Lawnchair version are you using

**Comment by FBIAgent05** [comment]
> Which Lawnchair version are you using

2.0-2589

**Comment by RikKoedoot** [comment]
Closing this issue as it's a known bug, and we are not updating that version anymore. We are working on Lawnchair 12 at the moment, this does not have this issue.
