### ISSUE TITLE
Live Icon

### ISSUE THREAD

**Issue by devang98** [Deletescape-Media/Lawnchair#241]
Could you add Live icon's (weather, calendar , clock, etc) to the launcher to make it more awesome

**Comment by AxiK101** [comment]
Is it even possible? I mean calendar is there, clock s possible as we have seen, weather etc on the other hand? 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxLlama** [comment]
It seems that Android 8.0 _may_ have that feature in the works and if true than that might make it into Lawnchair.

**Comment by devang98** [comment]
I have seen weather, clock and calendar on MIUI and Oxygen OS, thus it is possible, even Notes have a live icon

**Comment by jimmyroche** [comment]
I believe the way it works in action is by using a shortcut widet (1x1) with dynamic properties instead of an icon.

**Comment by marcinciarka** [comment]
I can choose MIUI live icon (it shows current data when trying to pick it), but in the launcher it's static :(
