### ISSUE TITLE
Search redirects to app provider (e.g. Play Store/F-Droid) when there are no search suggestions

### ISSUE THREAD

**Issue by quenz** [Deletescape-Media/Lawnchair#2410]
When using a search engine like Google or DuckDuckGo, and I type something that will not show any dropdown search results, then tap the search icon on my keyboard, it tries to search on an app provider (asks me to pick between Google Play and F-Droid), instead of searching for my query using the search engine I chose.

**Comment by major-mayer** [comment]
I can confirm this issue and its really old. This happens to me since years I would say.

**Comment by suphon-t** [comment]
The app drawer search bar is used for searching apps. If you want to search the web, please use the dock search bar instead.

**Comment by major-mayer** [comment]
Please don't close this.
If you select DuckDuckGo (e. G.) as your dock search engine, it uses the same search bar for the dock and the  app drawer and thus also opens the Play Store.

**Comment by RikKoedoot** [comment]
This is from an old Lawnchair version that we are not working on anymore. But install the DDG app and select duckduckgo in settings (not duckduckgo web)

**Comment by major-mayer** [comment]
You are right. I didn't know that the version that's currently on Google play is actually 3 years old 😮.
However the new alpha version that you can download doesn't seem to support any other search engine at all apart from Google. 
But there is an wip PR for this, that's nice.
