### ISSUE TITLE
Cross-version Backup / Restore

### ISSUE THREAD

**Issue by weareblahs** [Deletescape-Media/Lawnchair#2416]
This might be a feature request, or something like that.

Any plans to implement backup and restore features on Lawnchair 12? Because if users need to migrate LC 10 to 12 then they can restore from a Lawnchair 10 backup.

**Comment by DanGLVK** [comment]
Backup and restore support is planned, however cross-version data migration will likely take awhile (likely when Lawnchair 12 Is about to release on the play store where this will be necessary) as Lawnchair 10 and 12 are significantly different from each other

**Comment by rhysperry111** [comment]
This seems like the most relevant ticket to ask: Is there any way to move from the Play Store version to the Github version while keeping as many settings as possible? Lawnchair 14 doesn't recognize backups made in the old version at all.
