### ISSUE TITLE
Microphone button in the search bar

### ISSUE THREAD

**Issue by Azazel2222** [Deletescape-Media/Lawnchair#2418]
It is possible to make the microphone button in the search bar open voice search instead of assistant. I am from Ukraine and there is no assistant in our language

**Comment by ljgp6** [comment]
I agree with i also have no assistant, it would be nice if there would be an option to select provider of voice search

**Comment by maxelo** [comment]
this please!

**Comment by ljgp6** [comment]
This please my set is almost perfect and functional except thr mic button is not functional. Please. Thank you

**Comment by ljgp6** [comment]
Please I would be very happy uf anyone can look at this ty
