### ISSUE TITLE
Feature Request: Something like the Oneplus Hidden Space

### ISSUE THREAD

**Issue by mrjammock** [Deletescape-Media/Lawnchair#2419]
I'd love to have my favorite feature of the Oneplus Launcher, the Hidden Space feature, in Lawnchair.
Hidden Space is basically where apps, hidden from app drawer are stored.
Apps stored in the Hidden Space can also not be found by searching in the app drawer (unlike the "Hide apps from app drawer" - feature in Lawnchair).
The Hidden space can be accessed by swiping to the right on the app drawer. You can also enable password/fingerprint protection, so the hidden space can only be accessed with the phones default lock screen unlock method.
Here are some pictures:

![Screenshot_20220113-183349~2.jpg](https://user-images.githubusercontent.com/95573703/149381054-3a2a82bb-61be-4fb7-bde5-d364bcaf2f52.jpg)

![Screenshot_20220113-183406~2.jpg](https://user-images.githubusercontent.com/95573703/149381075-2f9e0362-0bd8-488f-b38f-724b691b3a51.jpg)

![Screenshot_20220113-183416~2.jpg](https://user-images.githubusercontent.com/95573703/149381090-00619da7-1cef-4e66-ba88-154745b148d1.jpg)

**Comment by Donkey-Doug** [comment]
Lawnchair has a "hide" feature and what you are describing is a "vault" feature.

**Comment by mrjammock** [comment]
@Donkey-Doug ah ok thx yeah that's what I mean 🙏

**Comment by Amorphous404** [comment]
Couldn't find the ticket earlier, it seems i created a similar ticket #2778, but my request was to make the hidden apps directly accessible via three Dot vertical menu that can be placed at the top of the app drawer without the password protection as it a pseudo protection, the same app can be launched from different locations with needing the password
