### ISSUE TITLE
App suggestions

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#242]
Why this isn't icluded in the settings menu?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
Because it is not implemented yet.

**Comment by AxiK101** [comment]
@deletescape Oh i see, if it's in the "to do" list then lets wait for it👍

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
Duplicate of #62
