### ISSUE TITLE
Lawnchair reported bugs

### ISSUE THREAD

**Issue by i1last** [Deletescape-Media/Lawnchair#2420]
[Lawnchair bug report Jan 13, 2022 230559.txt](https://github.com/LawnchairLauncher/lawnchair/files/7865678/Lawnchair.bug.report.Jan.13.2022.230559.txt)
[Lawnchair bug report Jan 13, 2022 230443.txt](https://github.com/LawnchairLauncher/lawnchair/files/7865679/Lawnchair.bug.report.Jan.13.2022.230443.txt)

**Comment by i1last** [comment]
Another bug report
[Lawnchair bug report Jan 14, 2022 170849.txt](https://github.com/LawnchairLauncher/lawnchair/files/7870866/Lawnchair.bug.report.Jan.14.2022.170849.txt)

**Comment by RikKoedoot** [comment]
Please explain what caused these crashes. Otherwise it's not that useful to us

**Comment by i1last** [comment]
> 

The last time I added a lot of applications to the same folder and Lawnchair started to behave strangely, followed by an error message. In the first two cases I don't remember what happened

**Comment by Hngga** [comment]
Please help
https://sg.docworkspace.com/d/sAHyd-4m3t-CVAZKVxMOrpxQ
