### ISSUE TITLE
Feature request: option for themed icons in app drawer

### ISSUE THREAD

**Issue by Kalpu-24** [Deletescape-Media/Lawnchair#2425]
I wish i could use monet themed icons in app drawer too 🙂.

**Comment by samcuxx** [comment]
It would be really nice

**Comment by mu198** [comment]
Yes, I'm still waiting for the update

**Comment by mrjammock** [comment]
Good idea, I'd love that too 👍

**Comment by vaisakhv** [comment]
This will be a cool feature if it's possible to add.. 
Some devices might have issues. I'm using a vivo phone with funtouch is 12 most of the time my dynamic color picker fails nd has to restart the launcher..also most of icon packs which supports Monet based theming dnt work in this.

If this is just my phone acting weird do let me know plz.
 My environment
- Device : iqoo 7 5G
- Manufacturer : Vivo (iqoo)
- OS : Funtouch OS 12
- Android version : 12
- Lawnchair : v12 Alpha v4

**Comment by brxken128** [comment]
Yeah I came here requesting exactly this, it would really bring it all together.

@RikKoedoot what are your thoughts?

It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.

**Comment by DanGLVK** [comment]
> Yeah I came here requesting exactly this, it would really bring it all together.
> 
> @RikKoedoot what are your thoughts?
> 
> It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.

Although this would make scrolling through the app drawer to look for an app somewhat confusing when all app icons look almost exactly the same

Just a thought

**Comment by brxken128** [comment]
> > Yeah I came here requesting exactly this, it would really bring it all together.
> > 
> > @RikKoedoot what are your thoughts?
> > 
> > It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.
> 
> Although this would make scrolling through the app drawer to look for an app somewhat confusing when all app icons look almost exactly the same
> 

The option to toggle it on/off for users who want it and users who don't would resolve that issue. I personally can distinguish between the material you apps just fine, and I'm sure some others can too, but if not they could just toggle the setting.

**Comment by DanGLVK** [comment]
> > > Yeah I came here requesting exactly this, it would really bring it all together.
> > > @RikKoedoot what are your thoughts?
> > > It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.
> > 
> > 
> > Although this would make scrolling through the app drawer to look for an app somewhat confusing when all app icons look almost exactly the same
> 
> The option to toggle it on/off for users who want it and users who don't would resolve that issue. I personally can distinguish between the material you apps just fine, and I'm sure some others can too, but if not they could just toggle the setting.

Fair enough ig

**Comment by brxken128** [comment]
> > > > Yeah I came here requesting exactly this, it would really bring it all together.
> > > > @RikKoedoot what are your thoughts?
> > > > It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.
> > > 
> > > 
> > > Although this would make scrolling through the app drawer to look for an app somewhat confusing when all app icons look almost exactly the same
> > 
> > The option to toggle it on/off for users who want it and users who don't would resolve that issue. I personally can distinguish between the material you apps just fine, and I'm sure some others can too, but if not they could just toggle the setting.
> 
> Fair enough ig

Would you mind raising this request to the development team please? I feel as though it's a rather desired feature (take a look at this thread alone) and it seems fairly trivial to add.

**Comment by DanGLVK** [comment]
> > > > > Yeah I came here requesting exactly this, it would really bring it all together.
> > > > > @RikKoedoot what are your thoughts?
> > > > > It seems quite trivial to add, and would look a whole bunch nicer than having potentially two different icons for a single app.
> > > > 
> > > > 
> > > > Although this would make scrolling through the app drawer to look for an app somewhat confusing when all app icons look almost exactly the same
> > > 
> > > 
> > > The option to toggle it on/off for users who want it and users who don't would resolve that issue. I personally can distinguish between the material you apps just fine, and I'm sure some others can too, but if not they could just toggle the setting.
> > 
> > 
> > Fair enough ig
> 
> Would you mind raising this request to the development team please? I feel as though it's a rather desired feature (take a look at this thread alone) and it seems fairly trivial to add.

Trust me, they already know, every single GitHub issue/Pull request message shows up as a message on the Admin Telegram group

**Comment by RikKoedoot** [comment]
I'll put my thoughts here since you asked: I agree with Dan, for usability it's really bad imo, but if it's a toggle I would not mind.

**Comment by SuperDragonXD** [comment]
Late reply, but has been fulfilled as a optional feature in Lawnchair 12.1. Enable in `Home Settings > General > Icon Style > Themed Icons > Home Screen & App Drawer` Therefore, closing this issue.
