### ISSUE TITLE
Crushing when trying to use lawchair settings.

### ISSUE THREAD

**Issue by Mal677** [Deletescape-Media/Lawnchair#2426]
Basically crushes when I try to access 'dock' section in settings.What I went thru to get to that point:
-Installed,made default launcher
-Opened settings
-opened drawer section changed column count from 5 to 4(no effect,still 5 when I launch dock)
-changed icon shape to circle
-changed search bar from Google to App search
-exited app,reopened, tried to open dock,crash....

Using version 2.0-2589 on Android 10 device

**Comment by RikKoedoot** [comment]
Closing this issue as we are focusing effords on development of Lawnchair 12
