### ISSUE TITLE
Quickswitch on Rooted One UI

### ISSUE THREAD

**Issue by rufus582** [Deletescape-Media/Lawnchair#2428]
Fist of all, I wanna thank the lawnchair team for giving me a pixel experience on my home screen, with the quickswitch, themed icons and all❤

I want to report some major bugs in lawnchair recent apps, on rooted One UI 3.1 with Android 11:
1. The split screen button doesn't work as expected. When I tap on it, it just puts the app on the top half of the screen. When I try to tap on another app from recent apps, I'm not on split screen anymore.
2. The Screenshot button doesn't work at all. Tapping on it does nothing.

I've attached a [Screen Recording](https://drive.google.com/file/d/1xhGUeKXM-uTwMd7n3gRCOpXV8tK5jGf8/view?usp=drivesdk), with the mentioned bugs. It would be nice if these are solved, or options are given, so that we can disable these options as a whole.

**Comment by Degl1** [comment]
It is a Samsung thing. Samsung has patched QuickSwitch. You could use the LawnChair module.

**Comment by RikKoedoot** [comment]
@ps1-hagrid That's not true. And those Lawnchair modules are unofficial, they can cause more issues

**Comment by Degl1** [comment]
Pretty sure Samsung has patched QuickSwitch for the most part. Doesn't work on my A40 running OneUI 3.1. And those modules can be easily uninstalled. And those modules have worked better for me than QuickSwitch. As QuickSwitch usually bugs out the Pixel launcher.

**Comment by skittles9823** [comment]
if said modules want to make a PR, the quickswitch module itself is open source so it wouldn't be hard for people to expand my samsung check to put files where they need to go. https://github.com/skittles9823/QuickSwitch/blob/master/quickswitch#L136

**Comment by rufus582** [comment]
> Pretty sure Samsung has patched QuickSwitch for the most part. Doesn't work on my A40 running OneUI 3.1. And those modules can be easily uninstalled. And those modules have worked better for me than QuickSwitch. As QuickSwitch usually bugs out the Pixel launcher.

I'm not asking for the lawnchair devs to fix the screenshot and split screen button. If they can, we'll and good. If they can't, I'm sure they can allow us to remove or hide those buttons, so that the UI doesn't have any dummy buttons.

**Comment by rufus582** [comment]
> It is a Samsung thing. Samsung has patched QuickSwitch. You could use the LawnChair module.

Could you please give me a link to this lawnchair module? Or are you talking about the launcher itself?🤔

**Comment by skittles9823** [comment]
> Could you please give me a link to this lawnchair module? Or are you talking about the launcher itself?🤔

They're referring to if QuickSwitch doesn't work at all. If it works for you then there isn't a need for third party modules. (QuickSwitch itself has nothing to do with recents, it just gives the launcher access to its APIs)

**Comment by rufus582** [comment]
> > Could you please give me a link to this lawnchair module? Or are you talking about the launcher itself?🤔
> 
> They're referring to if QuickSwitch doesn't work at all. If it works for you then there isn't a need for third party modules. (QuickSwitch itself has nothing to do with recents, it just gives the launcher access to its APIs)

I mean it works for me, but I'd like to see a way to remove the screenshot button at the bottom. That's why I'm asking...

**Comment by skittles9823** [comment]
Features like those would need to be added launcher side. Paphon can correct me if I'm wrong but I think something like that or at least similar is in the works.

**Comment by rufus582** [comment]
> Features like those would need to be added launcher side.

Yeah. I too feel the same thing.

> Paphon can correct me if I'm wrong but I think something like that or at least similar is in the works.

Oh. That's great news🤩. Hoping to see it released soon🤞

**Comment by rufus582** [comment]
![Screenshot_20220130-105659_Lawnchair](https://user-images.githubusercontent.com/68699122/151687906-6194b75a-96db-4bee-b8ba-da5e60d68d68.png)
Seems that the option to enable and disable those buttons are added now. That closes this issue. Thanks @paphonb 😊
