### ISSUE TITLE
Notification bubble's poiner out of center

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#243]
Not sure if this may be described as a bug more like graphic miscalculation, I attach some screenshots from both pixel & lawnchair apps, found some glitches that should be fixed:
On quickshortcuts bubbles, the pointing tale of the bubble isn't centered with the icon both in app drawer and desktop.
Lastly, when i touch the date widget now it opens calendar app but i get a floating msg that says "new event not found" (🤔)
![](http://i.imgur.com/ZMkbiRq.jpg)

![](http://i.imgur.com/12mMlMd.jpg)

![](http://i.imgur.com/3TNph0A.jpg)

![](http://i.imgur.com/IGmhZNr.jpg)

![](http://i.imgur.com/qWE37O9.jpg)
 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxLlama** [comment]
Yep, same here. I was just about to create an issue.

**Comment by AxiK101** [comment]
This is quite old. It was a matter of time someone to mention it..😚

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment]
I don't have that issue with the calendar, but I'm using another cal app to open links by default if that helps ...

**Comment by suphon-t** [comment]
Fixed with 04f85ad
