### ISSUE TITLE
Something in Lawnchair/QuickSwitch stopped my finger print scanner from working on the always on display

### ISSUE THREAD

**Issue by Peekale** [Deletescape-Media/Lawnchair#2430]
Alright so I'll try to be as detailed as possible here. I'd like to preface this by saying I've managed to fix this issue after trying A LOT of things, and what ended up fixing it was uninstalling lawnchair alpha 4, QuickSwitch and lawnfeed. I was then able to reinstall installing alpha 3 (all my settings were reset from the uninstall) and then upgrading to 4 (not sure if you'd have to do anything with 3 but that's just what I was doing from troubleshooting). I haven't reinstalled lawnfeed but if anyone would like me to try that to see if it caused a problem I can.

I'm on a Pixel 6 that I just recently rooted with the latest magisk canary (at the time of writing it's 5f4cd50c). I'm running the January patch from google.

Superuser access has been given to QuickSwitch, Repainter, and Vanced Manager. At one point I had substratum but I don't have it anymore.

I have a deny list with just google pay in it, and my modules are Extra Volume Steps by mysiak, fullscreen/immersive gestures, magiskhide props, quickswitch, and universal safetynet fix.

Ok so with that all out of the way, the problem is simple. A couple of days ago I noticed that when my phone was locked and showing the always on display, the fingerprint scanner wouldn't activate. I'd have to actually turn the screen on for it to work. I tried uninstalling every combination of things I could try, including taking off anything that hid magisk, uninstalling the magisk app, revoking super user access to everything, etc. What I hadn't been trying was uninstalling lawnchair, so none of my uninstall combinations really did anything. What ended up working today, was when I decided to fully uninstall quickswitch AND lawnchair at the same time. Everything else was installed and given access at this point, but just uninstalling lawnchair made my fingerprint scanner work again.

I've since tried toggling things in the lawnchair settings to see if I can find anything that would maybe be causing the issue but I haven't found it. So I don't know if this was a one-off issue or some weird conflict with programs, but I figured I'd document it here in case anyone else happens to experience it or if it's an issue that isn't isolated to my phone.

If there's any other info or anything I can provide just let me know!

**Comment by gotenksIN** [comment]
logcat and dmesg should be enough

**Comment by Peekale** [comment]
> logcat and dmesg should be enough

How should I go about getting that for you?

**Comment by gotenksIN** [comment]
@Personzoo adb logcat or apps like Matlog would help with former
(adb logcat > log.txt for example)
you can do dmesg > /sdcard/dmesg.txt in a root adb shell 
(adb shell, su, grant perms, then use the command sent above)

**Comment by Peekale** [comment]
I think I have what you want, but if not just lemme know.
[dmesg.txt](https://github.com/LawnchairLauncher/lawnchair/files/7918295/dmesg.txt)
[logcat.txt](https://github.com/LawnchairLauncher/lawnchair/files/7918296/logcat.txt)

**Comment by gotenksIN** [comment]
> I think I have what you want, but if not just lemme know. [dmesg.txt](https://github.com/LawnchairLauncher/lawnchair/files/7918295/dmesg.txt) [logcat.txt](https://github.com/LawnchairLauncher/lawnchair/files/7918296/logcat.txt)

thanks, I'll get a friend of mine with raviole to check as well
