### ISSUE TITLE
Long app switcher delay when opening it by using the slide up gesture

### ISSUE THREAD

**Issue by lc-at** [Deletescape-Media/Lawnchair#2431]
I am using Samsung Galaxy A21s (One UI?) and I am also using the gesture method for navigation. The gesture method that I am referring to is the elimination of navigation buttons (back, home, and app switcher) and they are replaced with gestures.

With that option enabled, the swipe up from bottom gesture is used to open the app switcher. This conflicts with the gesture Lawnchair is using to open the app drawer. When I do the gesture, an app drawer pops up, and for a second later then the app switcher popped. I have tried disabling the Lawnchair's swipe up to open app drawer gesture and it kind of worked, but with a delay. I think it would be nicer if there is an option to eliminate the delay.

**Comment by rufus582** [comment]
That delay, is because samsung made to be so. There is nothing that the lawnchair devs can do about it. It's samsung's fault.

**Comment by flug8** [comment]
There is actually a solution. Download the Lawnchair 12 dev build (at least #969). Then choose in the new gesture tab the home button gesture and select for example Tasker Secondary as app. Now create a tasker task that opens the recent apps menu. Now set the launch of the tasker secondary app as event. Now if you press the home button or if you swipe up, you'll see the recent apps menu. In most cases without a delay

**Comment by lc-at** [comment]
Thanks for all the folks involved. I am closing this issue as I am currently using a different phone now.
