### ISSUE TITLE
Website has unreadable words

### ISSUE THREAD

**Issue by jidanni** [Deletescape-Media/Lawnchair#2432]
Visit https://lawnchair.app/

You will see that the image of the lawn chair, in white overwrites the words below it in white, making the words unreadable.

**Comment by RikKoedoot** [comment]
Could you show a screenshot? Does not happen here. Though, keep in mind the website is fairly outdated

**Comment by jidanni** [comment]
![Screenshot_20220125-164255.jpg](https://user-images.githubusercontent.com/1230959/150942225-c4486b55-408f-47a3-83ed-fa304bfd76c5.jpg)

**Comment by SuperDragonXD** [comment]
Late reply, but can confirm the issue. Also, could you create an issue in [the website repo](/LawnchairLauncher/lawnchair.app) instead? This repo is for the app only. Thanks.

**Comment by jidanni** [comment]
Issues aren't enabled there.

**Comment by SuperDragonXD** [comment]
Oh, nevermind then. Still unsure whether this is the right place to post an issue about the website though. Might prolly send a internal message to the devs about this.
