### ISSUE TITLE
Website mentions G+ community

### ISSUE THREAD

**Issue by jidanni** [Deletescape-Media/Lawnchair#2433]
https://lawnchair.app/ mentions G+ community, but that no longer exists.

**Comment by m-p-3** [comment]
Seems like the change was committed but wasn't pushed to the live website.

https://github.com/LawnchairLauncher/lawnchair.app/pull/15

https://github.com/LawnchairLauncher/lawnchair.app/commit/a7a230ee3160f98cf420877438e6fa6e689c2243

**Comment by SuperDragonXD** [comment]
Late reply, but it was pushed. Closing this issue due to it being fixed.
