### ISSUE TITLE
How to enable Lawnicons in the first place?

### ISSUE THREAD

**Issue by im-coder-lg** [Deletescape-Media/Lawnchair#2434]
Hi,

I have been testing Lawnchair and I installed Lawnicons. But it doesn't show up in the Lawnchair settings, so is this a glitch or what else?

PS: I installed Lawnicons from it's debug APK.

**Comment by RikKoedoot** [comment]
It is not an iconpack so it does not show up in the iconpack list. You just have to enable themed icons

**Comment by im-coder-lg** [comment]
So does it also appear on the app drawer? If not, then how can I enable it there?

**Comment by RikKoedoot** [comment]
Google made themed icons not show up in the appdrawer, we followed this. There is no way to enable it right now
