### ISSUE TITLE
Can't open dual apps

### ISSUE THREAD

**Issue by prayag17** [Deletescape-Media/Lawnchair#2435]
Hello, I am unable to open dual apps on my Xiaomi Mi 11x with Miui 12.5. I have given all the permission to lawnchair but it won't open, it just shows can't open the app, I even made it a system admin app but that didn't work.

Android:11
OS: MIUI 12.5.7_ALIOTHIN
Lawnchair: 12 DEV

**Comment by moshpirit** [comment]
I use a Xiaomi as well with MIUI 12 and have the same issue

**Comment by prayag17** [comment]
It seems to work on miui 13 now

**Comment by moshpirit** [comment]
Shouldn't it work on MIUI 12 as well?
