### ISSUE TITLE
Feature Request: Make it possible to add a new page, but *left* from the home page

### ISSUE THREAD

**Issue by mrjammock** [Deletescape-Media/Lawnchair#2436]
On some launchers, you're able to open a new page left to the homepage.
I personally like this alot.
"But how does the Launcher know, which page is the homepage?", you might be asking.
Well, for this, there has to be a "set this page as homescreen"-button.
I'll add a screenshot, so you can see what I mean.

![Screenshot_20220126-100159.jpg](https://user-images.githubusercontent.com/95573703/151134249-cceb21f4-a999-4d52-a5f1-5172a4a6680c.jpg)

**Comment by masrlinu** [comment]
I am also missing this 😊
