### ISSUE TITLE
Lawnchair crash when use themed icon

### ISSUE THREAD

**Issue by Hngga** [Deletescape-Media/Lawnchair#2437]
Lawnchair crash when i use themed icon

https://sg.docworkspace.com/d/sADA_csG3t-CVAfX0ytKrpxQ

**Comment by SuperDragonXD** [comment]
Should be fixed in a later version of Lawnicons. If you are using an older debug build (pre-Lawnicons 1.0), please update to the latest version. If it still doesn't work (which is highly unlikely), try using a debug version of the app. Closing this issue.
