### ISSUE TITLE
Lawnchair crash when add widget on homescreen

### ISSUE THREAD

**Issue by gurmeetim** [Deletescape-Media/Lawnchair#2445]
Lawnchair is crashing when ad any widget to homescreen when feed and at a glance off.device samsung a50 android 11 one ui 3.1.latest github action build

**Comment by RikKoedoot** [comment]
Please provide a crashlog. Otherwise we cannot do much

**Comment by gurmeetim** [comment]
I sent on discord bug report 
![Screenshot_20220131-211503_Discord](https://user-images.githubusercontent.com/71697311/151825637-1d25fb34-822f-4d40-ae41-52e0fd9a9b94.jpg)

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with the error in the crash log you sent in Discord) are now being tracked on #2820. Closing this issue.
