### ISSUE TITLE
Add more android 12 specific features from Android 12L

### ISSUE THREAD

**Issue by fisforfaheem** [Deletescape-Media/Lawnchair#2446]
If possible

**Comment by DanGLVK** [comment]
> If possible

What features exactly? Mind you that for proper/full Android 12L support we'll have to wait until it is open source so we can base Lawnchair on it

**Comment by fisforfaheem** [comment]
Ok Thanks for minding me :), I meant Tablet related improvements... or is
this launcher feature complete on android 12.... and won't add anything
from android 12L if it launches..



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/01/22,
03:26:04 AM

**Comment by RikKoedoot** [comment]
As Dan said, we will have to wait till the sources get released before we dan state what we will add to Lawnchair.

**Comment by fisforfaheem** [comment]
Ok, thanks for the clarification.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/01/22,
01:57:57 PM
