### ISSUE TITLE
Lawn icons wont apply 

### ISSUE THREAD

**Issue by fisforfaheem** [Deletescape-Media/Lawnchair#2451]
The lawnicons are not being applied at all, in the settings it won't show the lawnicons, eve though i have installed them.

**Comment by DanGLVK** [comment]
> The lawnicons are not being applied at all, in the settings it won't show the lawnicons, eve though i have installed them.

Lawnicons isn't an icon pack, it's an addon for the themed icons feature which you enable in general settings and they only apply on the homescreen
