### ISSUE TITLE
Navigation Gestures and Wallpaper Misalignment

### ISSUE THREAD

**Issue by Dragonzroar** [Deletescape-Media/Lawnchair#2452]
The navigation gesture of going to the next app does not work with the lastest alpha 5 version. When I try to swipe on the bottom of the screen to go to the next app nothing happens.

The other issue is the wallpaper being misaligned. When I select the wallpaper I want to use and position it where I want it, when I apply it it will shove it to the right of where I wanted it. Issue now here https://github.com/LawnchairLauncher/lawnchair/issues/2455#issue-1124979337

I'm running Android 12 on the Pixel 6 Pro.

**Comment by RikKoedoot** [comment]
Could you send a screen recording of the first issue? And could you make a different issue about the wallpaper misaligned?

**Comment by Dragonzroar** [comment]
Here's a recording of me using the navigation guesture on Nova Launcher and then trying it in Lawnchair. 
![screen-20220205-101607_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/66227323/152650223-c4a66bed-66a0-403d-ab82-e7295fd8d468.gif)

**Comment by Dragonzroar** [comment]
Made a new issue for the wallpaper misalignment here https://github.com/LawnchairLauncher/lawnchair/issues/2455#issue-1124979337
