### ISSUE TITLE
Bug when clearing all apps

### ISSUE THREAD

**Issue by 1alessandro1** [Deletescape-Media/Lawnchair#2457]
Version tested: Lawnchair 12 Alpha 5 released on 2022/02/04

In this video you can clearly see the annoying bug which tells you for a millisecond "No recent apps"

https://streamable.com/7un64q

Can this be removed permanently, or if it's not a bug but a feature, could you add the option to disable it?

Thank you

**Comment by suphon-t** [comment]
This happens with **all** third-party launchers and can only be fixed with the QuickSwitch module if you have Magisk.

**Comment by 1alessandro1** [comment]
Thanks @paphonb for your quick response. So I only have to flash this module: 

https://github.com/skittles9823/QuickSwitch/releases/download/3.2.1/QuickSwitch-Updater.zip


and reboot?

Should I care to uninstall Lawnchair 12 Alpha 5 first?

**Comment by suphon-t** [comment]
Install [this APK](https://github.com/skittles9823/QuickSwitch/releases/download/3.2.1/QuickSwitch-v3.2.1.apk), open it and select Lawnchair on the menu. Your phone will automatically restart.
