### ISSUE TITLE
Source Tarball for Lawnchair 2.0-2589

### ISSUE THREAD

**Issue by onkoe** [Deletescape-Media/Lawnchair#2461]
Hello,
Does anyone happen to have a source tarball for Lawnchair 2.0-2589 from F-droid? I'd love to take a look and make some edits for a personal setup, but the F-droid site only shows Lawnchair 1.2.1.2001 and lower, which are much lower versions than I'd like. In addition, the app only allows you to download the APK. 

Many thanks,
Onkoe

**Comment by SuperDragonXD** [comment]
You can find the latest zip (no tarball) for Lawnchair 2 at https://github.com/LawnchairLauncher/lawnchair/tree/9-stable; click "Code" > "Download Zip" after that.
