### ISSUE TITLE
"Hide from app drawer" does not work at all.

### ISSUE THREAD

**Issue by Grabstertv** [Deletescape-Media/Lawnchair#2467]
![SmartSelect_20220208-154613_Lawnchair](https://user-images.githubusercontent.com/49114212/152972400-58a31698-fc7c-4adc-a40d-fe5f61f2f529.jpg)

### Details:
- Galaxy A52 4G
- Android 12, OneUI 4
- Lawnchair v12 alpha 5

**Comment by SuperDragonXD** [comment]
Try updating to the later versions (Lawnchair 12.1) and see if it fixes the issue. Also closing since this is relevant to the older versions only.
