### ISSUE TITLE
Scrolling to home screen view not working after home button pressed

### ISSUE THREAD

**Issue by tomskra** [Deletescape-Media/Lawnchair#2472]
Step to reproduce: 
1) scroll to second view on home screen
2) press home button

Device:
Samsung Galaxy S20 (Android 12 & One UI 4.0)

Video:
https://photos.app.goo.gl/M7oYaeYtV66tHL2m9

Logs:
[logcat_02-10-2022_14-00-15.txt](https://github.com/LawnchairLauncher/lawnchair/files/8041110/logcat_02-10-2022_14-00-15.txt)

**Comment by georgeplendl** [comment]
This is also occurring when using the gesture navigation built into my phone. Swiping up on a secondary home screen doesn't take me to the primary home screen. It's quite frustrating as it takes me about 8 swipes at the bottom of the screen to get it back to the primary home screen.

Note: This gesture works flawlessly on the default Pixel 6 launcher.

Device:
Google Pixel 6 Pro

Version:
Android 12
