### ISSUE TITLE
Recent apps not showing on OneUI 3

### ISSUE THREAD

**Issue by Reiux** [Deletescape-Media/Lawnchair#2475]
When I'm on my home screen and press on recent button, my recent apps is not showing. Is it a bug on OneUI because it's also the same problem on Nova7.

**Comment by lublak** [comment]
I have the same issue on Lineageos 12.1.
First it opens, but after a while it is no longer possible.

**Comment by SuperDragonXD** [comment]
Yes, it is a bug on OneUI (actually Android as a whole). To fix this, you'll need root/QuickSwitch. Closing this issue
