### ISSUE TITLE
Replace Lawnfeed with other features/views

### ISSUE THREAD

**Issue by tushar09** [Deletescape-Media/Lawnchair#2477]
I want to show some other views instead of Lawnfeed. Like how much steps user took, current location, latest events etc. 
This is a huge project. I cant find and understand where and how to achieve this. Till now I can understand there's something to do with ENABLE_MINUS_ONE_PREF.

Can anyone please help me with where or in which file I need to write my own code?

**Comment by suphon-t** [comment]
You'd have to build said functionalities in another app and let Lawnchair connect to it. You can take a look at [FabianTerhorst/DrawerOverlayService](https://github.com/FabianTerhorst/DrawerOverlayService) for a barebones launcher overlay implementation. 

There is also another custom overlay as well: [iTaysonLab/HomeFeeder](https://github.com/iTaysonLab/HomeFeeder). This might be useful for you.

**Comment by tushar09** [comment]
@paphonb I have successfully installed the HomeFeeder app ([iTaysonLab/HomeFeeder](https://github.com/iTaysonLab/HomeFeeder)). I studied Lawnchair codebase a lot but could not understand how to connect this app with lawnchair.

I have changed the value of `bridgePackages`  in `FeedBridge.kt` as follows:
```
private val bridgePackages by lazy { listOf(
            PixelBridgeInfo("com.google.android.apps.nexuslauncher", R.integer.bridge_signature_hash),
            BridgeInfo("ua.itaysonlab.homefeeder", R.integer.homefeed_signature_hash)) }
```
Then I ran the release version of Lawnchair having the Homefeeder app installed in the phone. And it's not working. 
I have installed Lawnchair from branch `10-dev`
Homefeeder signature hash is: `0x887456ed`

**Comment by suphon-t** [comment]
If you’re on Lawnchair 10, it already supports HomeFeeder out of the box. You just have to set it in the settings menu.

**Comment by tushar09** [comment]
It's not working. I cant see any option for homefeeder other than Google feed. If I try to turn it on, it shows the dialog to download the lawnfeed. But Homefeeder is installed already.
Please see the below picture:


![Screenshot_1645210940](https://user-images.githubusercontent.com/9745378/154746416-41eb5bcf-1613-4131-8d07-e662eefa472d.png)
.

**Comment by Degl1** [comment]
I just use DiscoverKiller by Kieron Quinn and it works like a charm

**Comment by tushar09** [comment]
@ps1-hagrid does it work with Lawnchair 12?

**Comment by Degl1** [comment]
Yeah DiscoverKiller works with LawnChair 12. Using it currently too. Just install LSPosed and then install DiscoverKiller(Ignore the Xposed warning).

**Comment by tushar09** [comment]
@ps1-hagrid Thanks a lot for the help. I have successfully installed the discover killer and its working. But the problem is if I run Lawnchair 12 in release mode it's not working. Does it mean it's only available in debug mode?

**Comment by RikKoedoot** [comment]
it does not matter what launcher you use for discovery killer, neither what version of lawnchair. it just replaces the google feed with something else. you just need lawnfeed v3 to have the google feed in lawnchair v12, then discovery killer will replace stuff on google's end.

**Comment by Degl1** [comment]
I don't have LawnFeed but it still works as long the Google QuickSearchBox is installed

**Comment by RikKoedoot** [comment]
on release builds you need lawnfeed, on debug builds you do not. you also do not need it if you are using quickswitch.

**Comment by tushar09** [comment]
@RikKoedoot I have installed release build of Lawnchair 12. Feed is enabled from settings. And also installed lawnfeed v3. But still not working.

**Comment by RikKoedoot** [comment]
What exactly is not working, the feed or the feed replacement?

**Comment by tushar09** [comment]
Feed is not working. I will work on feed replacement later. But first I am not able to see the Lawnfeed v3 in action. In lawnchair 12 the left most page is not opening where feeds are shown. @RikKoedoot

**Comment by tushar09** [comment]
Another thing is I have successfully completed all the things I wanted in **Lawnchair 10(branch 10-dev**) after a very hard work. I have replaced the feeds with my own app and it is working very smoothly. There I can show my own views and implement new ideas. But the problem is when I update the target sdk version to 30 it crashs. And because of this I can't publish it in playstore. @RikKoedoot

**Comment by tushar09** [comment]
Ahh. What a moment!!. Finally I solved it and I am able to set my custom feeds in Lawnchair 12. Thanks god and thanks a lot to you guys.
![Screenshot_20220312-232439](https://user-images.githubusercontent.com/9745378/158028294-f7698051-bc0c-4b70-8ac9-06a98b94055c.jpg)

**Comment by DCMoolah** [comment]
@tushar09 How did you get it to work?

**Comment by dot166** [comment]
how do you link homefeeder to lawnchair 12.1
