### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by qp5** [Deletescape-Media/Lawnchair#2479]
### Describe the bug

Hi
LawnChair is supper cool, though for 1year now, 
on closing open apps, icon flashes:  
"No item found"
 - always appears, after last open app is closed.

Thank you
John
https://github.com/qp5

Found a closed issue:
posted here with no reply?
https://github.com/LawnchairLauncher/lawnchair/issues/1975

### Steps to reproduce

1. open any app
2. close that app
3. icon flashes: "No recent items"

### Expected behavior

.

### Screenshots

.

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

### Additional context

.

**Comment by msfjarvis** [comment]
Issue is incomplete and unactionable.
