### ISSUE TITLE
Feature Request: Disable Dock

### ISSUE THREAD

**Issue by Hngga** [Deletescape-Media/Lawnchair#2481]
disable dock for more space to widget. :)

Like this:
![Screenshot_2022_0216_155606](https://user-images.githubusercontent.com/96458907/154229935-cff6e413-3f29-4f6d-bd7d-c013e523b416.png)

**Comment by ghost** [comment]
Just go to settings and find Dock Style and set to hidden

**Comment by RikKoedoot** [comment]
Closing, same as #2327
