### ISSUE TITLE
Feature request: Add option to remove the search bar from home screen

### ISSUE THREAD

**Issue by RagibHasin** [Deletescape-Media/Lawnchair#2487]
My main driving point for using Lawnchair (stable) was that it allowed the user to remove the search bar from the home screen. But recently stumbling upon the new Lawnchair 12 alpha has left me disappointed.

Please consider adding the option to remove the search bar.

**Comment by DanGLVK** [comment]
> My main driving point for using Lawnchair (stable) was that it allowed the user to remove the search bar from the home screen. But recently stumbling upon the new Lawnchair 12 alpha has left me disappointed.
> 
> Please consider adding the option to remove the search bar.

That's already an option, look in the dock settings

**Comment by RagibHasin** [comment]
Sorry for bothering you, really 😛. I misunderstood what dock is. Thank you very much for your prompt response.

**Comment by RagibHasin** [comment]
BTW, is there any plan to reintroduce custom icon shapes?

**Comment by DanGLVK** [comment]
> BTW, is there any plan to reintroduce custom icon shapes?

While it's planned to bring many/most options from v9 into v12, can't provide any guarantees at the moment that this option will come back
