### ISSUE TITLE
aesthetic problem

### ISSUE THREAD

**Issue by Shwhise** [Deletescape-Media/Lawnchair#2490]
### Describe the bug

Realme UI 2.0, When I click on the search engine at the bottom of the screen, it opens without effect. It looks bad.

### Expected behavior

...

### Screenshots

https://user-images.githubusercontent.com/100424583/155730709-b293eb37-d851-4855-8386-6a9df0bc1703.mp4

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by Shwhise** [comment]
![Screenshot_2022-02-25-17-56-21-80_99c04817c0de5652397fc8b56c3b3817.jpg](https://user-images.githubusercontent.com/100424583/155736779-62859f0f-da38-4435-af1c-8a1c130477db.jpg)

**Comment by yurikodesu** [comment]
It's same with me too

**Comment by SuperDragonXD** [comment]
First of all, that's not Lawnchair 12, that's V2 (and we don't support old versions anymore). Also, it's more like Google removing that feature/animation than Lawnchair removing it. Therefore closing this issue
