### ISSUE TITLE
Lawnchair Alpha 5 not displaying app shortcuts

### ISSUE THREAD

**Issue by mrjammock** [Deletescape-Media/Lawnchair#2491]
![Screenshot_20220226-170052.jpg](https://user-images.githubusercontent.com/95573703/155850027-780024b0-5893-4773-8045-a07cf64c7b32.jpg)

Alpha 5 just "killed" the app shortcuts.
On Alpha 4, everything was normal, but on Alpha 5 I don't have the app shortcuts.
I find those very useful, especially with Google Calendar

**Comment by fredgolightly** [comment]
Set as default launcher?

**Comment by mrjammock** [comment]
@fredgolightly
Yup, it is

**Comment by SuperDragonXD** [comment]
Same issue too.

**Comment by SuperDragonXD** [comment]
Although the app shortcuts show in the app drawer, which is weird

**Comment by SuperDragonXD** [comment]
Uploading Record_2022-03-18-15-19-10_67d7f8591eff9881972c1169b8bca2d8.mp4…

**Comment by SuperDragonXD** [comment]
https://user-images.githubusercontent.com/70206496/162612857-44f6de47-3c4d-407a-82e3-d9f42a4963a4.mp4

**Comment by mrjammock** [comment]
@SuperDragonXD hmm, my Lawnchair doesn't show it in the app drawer 🤔

**Comment by SuperDragonXD** [comment]
> @SuperDragonXD hmm, my Lawnchair doesn't show it in the app drawer 🤔

Wdym?

**Comment by SuperDragonXD** [comment]
This bug still exists on the 12L builds.
