### ISSUE TITLE
[BUG] Crashing

### ISSUE THREAD

**Issue by Degl1** [Deletescape-Media/Lawnchair#2494]
### Describe the bug

Latest #667 build of LawnChair just plain crashes and refuses to open.

### Steps to reproduce

1. Download latest dev build of LawnChair(https://github.com/LawnchairLauncher/lawnchair/suites/5476403232/artifacts/174609029)
2. Install it
3. See it crash

### Expected behavior

I expected the new LawnChair build to work.

### Device information

- Device: Poco F3(`alioth`)
- OS: xdroidCAF 12 24/02/22 with N0Kernel battery edition and Magisk+QuickSwitch
- App version Dev #667

**Comment by RikKoedoot** [comment]
Next time try to include a crashlog, luckily I have the same crash so I can deliver one. https://katb.in/onudufezixe

**Comment by Degl1** [comment]
https://hastebin.com/ewulabiwoh
here is the crash log for the latest #672
