### ISSUE TITLE
[BUG] Accessibility not detected

### ISSUE THREAD

**Issue by Donkey-Doug** [Deletescape-Media/Lawnchair#2502]
### Describe the bug

I have configured double tap to sleep. Accessibility service is enabled to enable this feature. However, Lawnchair doesn't recognise that the service is enabled and prompt to enable accessibility service again and again.

### Steps to reproduce

Double tap to sleep
Asks to enable accessibility, but it is already enabled

### Expected behavior

Sleep

### Device information

- Device: Xiaomi Mi 9T Pro
- OS: Lineageos android 10
- App version: 12.0.0 Alpha 5

**Comment by DanGLES3** [comment]
> ### Describe the bug
> I have configured double tap to sleep. Accessibility service is enabled to enable this feature. However, Lawnchair doesn't recognise that the service is enabled and prompt to enable accessibility service again and again.
> 
> ### Steps to reproduce
> Double tap to sleep Asks to enable accessibility, but it is already enabled
> 
> ### Expected behavior
> Sleep
> 
> ### Screenshots
> _No response_
> 
> ### Device information
> * Device: Xiaomi Mi 9T Pro
> * OS: Lineageos android 10
> * App version: 12.0.0 Alpha 5
> 
> ### Additional context
> _No response_

Make sure to whitelist Lawnchair from any system restriction

Read the guide from www.dontkillmyapp.com

**Comment by AdamKopf** [comment]
Same issue. Double tap opens the accesibility settings even though Lawnchair is already admin app. Worked before - it's possible that it stopped working after installing a Button Remapper.
Samsung S10e
OneUI 3
Lawnchair 2.0-2589
