### ISSUE TITLE
10-dev with target sdk 30

### ISSUE THREAD

**Issue by tushar09** [Deletescape-Media/Lawnchair#2504]
I want to build release app from branch 10-dev. But when I set the targetSdkVersion to 30, the app crashs. Is there any chance/possibilities to achieve it?

**Comment by SuperDragonXD** [comment]
Late reply, but why do you want to do that though? Seems unnecessary, considering that Lawnchair supports Android 11+ even without changing the target SDK. Is there any reason why you'd want to do that?
