### ISSUE TITLE
Recents settings don't change

### ISSUE THREAD

**Issue by PeterKW** [Deletescape-Media/Lawnchair#2505]
Fairphone 4 Android 11 Lawnchair Version 12.0.0 Dev (#658)

Nothing seems to change in recents menu when I toggle the options. 

Is there any way to debug this further?

![Screenshot_20220310-214004.png](https://user-images.githubusercontent.com/13779157/157759268-e8689ed6-cff6-4c9c-9833-d7cdc86b03d8.png)

**Comment by RikKoedoot** [comment]
This menu only shows for development purposes. if you're not rooted and using quickswitch it won't do anything. It's hidden on userfacing alpha releases.

**Comment by PeterKW** [comment]
> This menu only shows for development purposes. if you're not rooted and using quickswitch it won't do anything. It's hidden on userfacing alpha releases.

Ah okay, that makes sense
