### ISSUE TITLE
Fairphone 4 Android 11 Lawnchair Version 12.0.0 Dev (#658)

### ISSUE THREAD

**Issue by PeterKW** [Deletescape-Media/Lawnchair#2506]
![Screenshot_20220310-214004.png](https://user-images.githubusercontent.com/13779157/157759268-e8689ed6-cff6-4c9c-9833-d7cdc86b03d8.png)

Fairphone 4 Android 11 Lawnchair Version 12.0.0 Dev (#658)

Nothing seems to change in recents menu when I toggle the options. 

Is there any way to debug this further?

Also, just as a query. Is there plan to port some of the features from Version 9.1 Alpha 3 to version 12 such as the Categorise Applications Tabs?

![Screenshot_20220310-222908.png](https://user-images.githubusercontent.com/13779157/157765627-c6597bd0-62a0-4e8c-b26b-f114228dcf35.png)

**Comment by RikKoedoot** [comment]
I already replied about the first part asked about. Please don't open a new issue about that when we close the old one. We do plan on porting features from old Lawnchair builds
