### ISSUE TITLE
[BUG] Icon picker issue in particular icon pack (delta icon pack).

### ISSUE THREAD

**Issue by parzival-cmd** [Deletescape-Media/Lawnchair#2507]
So I am seeing a bug where only icons are showing upto 'O' alphabet in delta icon pack, while using icon picker.

 ![IMG_20220311_202044_918.jpg](https://user-images.githubusercontent.com/55645257/157891153-010eea6d-1695-4e96-9163-8bd2c210a888.jpg)

**Comment by danielyor** [comment]
Can confirm on my device too. Results stop after the "O" tab/category of the icon pack and even searching doesn't yield results (ex. searching for "Telegram"). Delta works just fine globally and with other launchers so I'm sure it's not a Delta issue.
Also I couldn't replicate this bug on the popular Pixel icon pack even though it has more than twice the amount of icons, so maybe something's going on with the categories.

I know that per-icon customization is still experimental but I hope this bug can be fixed soon!

**Comment by suphon-t** [comment]
Fixed in 918515a

**Comment by parzival-cmd** [comment]
Thank you so much👍🏻🎊
