### ISSUE TITLE
[BUG] Lawnfeed not working

### ISSUE THREAD

**Issue by pokemaster974** [Deletescape-Media/Lawnchair#2509]
### Describe the bug

When I use Lawnfeed, I can only see news displaying but if I click on news or on settings, it doesn't open anything.

### Steps to reproduce

1. Go to Lawnfeed
2. Click on news or on your profile (upper right) then on settings
3. See error

### Expected behavior

Opening news or options

### Device information

- Device: Xiaomi Mi 9
- OS: crDroid 8.2 (Android 12)
- App version: Lawnchair 12 Alpha 5 + Lawnfeed 3

**Comment by SuperDragonXD** [comment]
Late reply, but please see https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#lawnfeed-does-not-work on how to fix this issue.
