### ISSUE TITLE
[BUG] Lawnchair crashes when opened

### ISSUE THREAD

**Issue by markonije** [Deletescape-Media/Lawnchair#2510]
I have the newest version from Google Play Store, on Android 8, OneUI 1.0, Galaxy S8.
I have no idea why is this happening.
Will update if anything changes.

**Comment by markonije** [comment]
I restarted the phone, cleared cache and everything. Still crashen, even if I just don't touch it.

**Comment by RikKoedoot** [comment]
Please fill out the form provided when opening issues. Also provide a log next time
