### ISSUE TITLE
Add all old settings in Lawnchair 12

### ISSUE THREAD

**Issue by Secret-chest** [Deletescape-Media/Lawnchair#2512]
* Full theme customization (rn you can only select one color and it will tint everything)
* Full font customization (Inter sucks)
* Wide widgets! It was cool
* ...

**Comment by charlesmema** [comment]
Also
•Folder icon Customisation

**Comment by nin0-dev** [comment]
Will you understand that they do a REWRITE of Lawnchair? Wait for new features.

**Comment by nin0-dev** [comment]
- Full theme customisation: It's the thing behind A12's dynamic colours.
- Full font: Set Roboto if needed. They won't add Google Sans as it's proprietary. If you want to get Pixel-like labels, use Inter Medium.
- Wide widgets: just wait.

**Comment by Secret-chest** [comment]
> Full font: Set Roboto if needed. They won't add Google Sans as it's proprietary. If you want to get Pixel-like labels, use Inter Medium.

I didn't want Google Sans, but even if I change the font, I get Inter in the search bar.

**Comment by Secret-chest** [comment]
> Full theme customisation: It's the thing behind A12's dynamic colours.

Then can there be an option to set everything manually?

**Comment by suphon-t** [comment]
> Will you understand that they do a REWRITE of Lawnchair? Wait for new features.
