### ISSUE TITLE
[BUG] latest build of lawnchair(12.5), crashing after i updated to my realme phone

### ISSUE THREAD

**Issue by charlesmema** [Deletescape-Media/Lawnchair#2513]
### Describe the bug

My device were a realme device (RMX2061_11_C.21), then i updated to the new version RMX2061_11_C.22 and suddenly lawnchair doesn't work and this is the log report 

`Lawnchair bug report 15 Mar 2022 3:00:53 pm
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: realme
build.device: RMX2061L1
build.display: RMX2061_11_C.22
build.fingerprint: realme/RMX2061/RMX2061L1:11/RKQ1.201112.002/1645205058225:user/release-keys
build.hardware: qcom
build.id: RKQ1.201112.002
build.manufacturer: realme
build.model: RMX2061
build.product: RMX2061
build.type: user
version.codename: REL
version.incremental: 1645205058225
version.release: 11
version.sdk_int: 30
display.density_dpi: 408

error: Uncaught exception

java.lang.ClassCastException: com.android.launcher3.model.data.WorkspaceItemInfo cannot be cast to com.android.launcher3.model.data.FolderInfo
	at com.android.launcher3.model.QuickstepModelDelegate.modelLoadComplete(QuickstepModelDelegate.java:11)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:75)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:254)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

### Steps to reproduce

1. have realme device that was updated to realme ui2.0 + android 11
2. install launcher
3. update it again but to the latest version(RMX2061_11_C.22)
4. system will choose lawnchair to launch (if it is the default home launcher)
5. crashes
6. tries to launch again
7. crashes again and again until system choose to stop it

### Expected behavior

Lawnchair crashes

### Device information

- Device: realme
- OS: updated android 11(?; idk if this is right)
- App version  12.0.0 Alpha 5

### Additional context

lawnchair crashes after updating phone

**Comment by SuperDragonXD** [comment]
Try updating to Lawnchair 12.1, it could probably fix the issue. Also it's more or less an issue with Realme than Lawnchair. Anyways, closing this issue.
