### ISSUE TITLE
[Feature Request] Swipe down -> Close all apps

### ISSUE THREAD

**Issue by rahulduhan** [Deletescape-Media/Lawnchair#2514]
Ability to swipe down to close all apps in recents menu.

**Comment by ComValer** [comment]
would be nice to have such option to switch to (it shouldn't be necessary, cause rn the Swipe down on Home screen opens the Quick settings panel). If you can turn off or on the option ("Swipe down closes all apps") - then good if when it's off - it ll open Quick settings panel

**Comment by rahulduhan** [comment]
As I commented, I want to work it in only recent menu
