### ISSUE TITLE
Lawnchair goes blank and becomes non responsive

### ISSUE THREAD

**Issue by EVRPR** [Deletescape-Media/Lawnchair#2515]
Sporadically, when returning home from an app or recents, the launcher becomes completely blank and non responsive. Sometimes it takes a while to redraw, other times I need to switch back to Pixel Launcher and then go back to Lawnchair to get it to reset.

When it happens, nothing responds to touch input except the quick settings. Lanwfeed doesn't work, app drawer doesn't pop up, and the home screen only shows wallpaper and gesture bar. Home screen doesn't respond to touches or inputs.

Has been happening since Android 12L Beta 3 and now with QPR3 on a stock and bootloader locked Pixel 6 with Lawnchair 12 alpha 5 and all future developer builds.

**Comment by EVRPR** [comment]
This behavior is still happening randomly on latest Lanwchair 12.1 builds.

**Comment by CaptainColdAJ** [comment]
This issue is still occurring in the MIUI phones like POCO and most of the OPPO phones. Please look into these random crashings and try to fix it.
