### ISSUE TITLE
[Feature Request] Protected Apps

### ISSUE THREAD

**Issue by pixincreate** [Deletescape-Media/Lawnchair#2516]
Although hidden apps have it's own caveats of unable to access in any way once it is hidden (like 3 finger swipe to access hidden apps or anything such), it is useful to have a separate option for protecting apps with a password or fingerprint tat prompts the user before allowing to open the app by any means (either loading from RAM i.e. recents or launching app from drawer).

An example for that would be launcher3 itself (Trebuchet on LineageOS that default launcher) for reference.

**Comment by pixincreate** [comment]
@Goooler , mind looking into this?

**Comment by Goooler** [comment]
I'm afraid have no time to do this.

**Comment by pixincreate** [comment]
> I'm afraid have no time to do this.

So, closing is the only option?
