### ISSUE TITLE
[BUG] Bootloop on Android 12L when using Lawnchair as Recents provider

### ISSUE THREAD

**Issue by ubergeek77** [Deletescape-Media/Lawnchair#2517]
### Describe the bug

I maintain my own custom ROM. Since I wanted to use Lawnchair in my ROM, I replaced the stock AOSP launcher with Lawnchair. In order to provide Lawnchair with the permissions it needs to provide the recents screen, I used this module that grants Lawnchair the required permissions:

https://github.com/SuperiorOS/android_vendor_lawnchair

This is similar to how the QuickSwitch module does it, but more direct - it properly grants the right permissions directly in the build, without root, and without the QuickSwitch app. If you look at that `Android.bp` file, you can see that this module overrides `Launcher3`, thus removing `Launcher3` from the build.

This was working fine for me on Android 12. The recents screen was working fine, I had the benefit of using the extra buttons on the recents screen, and everything was great.

However, as of the Android 12L update, presumably due to Monet being added, Lawnchair can no longer be used as the recents provider. Lawnchair itself works fine, but if you set Lawnchair as the default Home app and then open the recents screen, SystemUI will crash, and the device will reboot. But upon reboot, SystemUI immediately crashes again on the lockscreen. This results in a bootloop.

I tried to get around this by removing the `overrides` section in the above module's `Android.bp`, so that the default launcher was added to the build alongside Lawnchair. Unfortunately, since my build gives Lawnchair the correct permissions to be the recents provider, setting Lawnchair as the default Home app also switches the recents screen, which appears to be causing the crash. I presume I could continue to use Lawnchair if I simply exclude it from my build and then sideload it, but I really wanted to use Lawnchair for its ability to act as a recents provider.

I don't have a device where I can test the QuickSwitch Magisk module, but I can assume that this would also happen for QuickSwitch users on Android 12L. 

### Steps to reproduce

1. Create a custom ROM build that [gives Lawnchair the correct permissions to act as the recents provider](https://github.com/SuperiorOS/android_vendor_lawnchair)
2. Set Lawnchair as the default Home app
3. Open the recents menu
4. You are now bootlooping

### Expected behavior

I expected the recents functionality of Lawnchair to continue to work as it did on Android 12.

### Device information

- Device: Pixel 3 XL and Pixel 6 Pro (tested on both)
- OS: Custom, modified CalyxOS 3.3.0, Android 12L
- App version:12.0.0 Alpha 5

**Comment by DanGLVK** [comment]
> ### Describe the bug
> I maintain my own custom ROM. Since I wanted to use Lawnchair in my ROM, I replaced the stock AOSP launcher with Lawnchair. In order to provide Lawnchair with the permissions it needs to provide the recents screen, I used this module that grants Lawnchair the required permissions:
> 
> https://github.com/SuperiorOS/android_vendor_lawnchair
> 
> This is similar to how the QuickSwitch module does it, but more direct - it properly grants the right permissions directly in the build, without root, and without the QuickSwitch app. If you look at that `Android.bp` file, you can see that this module overrides `Launcher3`, thus removing `Launcher3` from the build.
> 
> This was working fine for me on Android 12. The recents screen was working fine, I had the benefit of using the extra buttons on the recents screen, and everything was great.
> 
> However, as of the Android 12L update, presumably due to Monet being added, Lawnchair can no longer be used as the recents provider. Lawnchair itself works fine, but if you set Lawnchair as the default Home app and then open the recents screen, SystemUI will crash, and the device will reboot. But upon reboot, SystemUI immediately crashes again on the lockscreen. This results in a bootloop.
> 
> I tried to get around this by removing the `overrides` section in the above module's `Android.bp`, so that the default launcher was added to the build alongside Lawnchair. Unfortunately, since my build gives Lawnchair the correct permissions to be the recents provider, setting Lawnchair as the default Home app also switches the recents screen, which appears to be causing the crash. I presume I could continue to use Lawnchair if I simply exclude it from my build and then sideload it, but I really wanted to use Lawnchair for its ability to act as a recents provider.
> 
> I don't have a device where I can test the QuickSwitch Magisk module, but I can assume that this would also happen for QuickSwitch users on Android 12L.
> 
> ### Steps to reproduce
> Steps to reproduce the behavior:
> 
> 1. Create a custom ROM build that [gives Lawnchair the correct permissions to act as the recents provider](https://github.com/SuperiorOS/android_vendor_lawnchair)
> 2. Set Lawnchair as the default Home app
> 3. Open the recents menu
> 4. You are now bootlooping
> 
> ### Expected behavior
> I expected the recents functionality of Lawnchair to continue to work as it did on Android 12.
> 
> ### Screenshots
> _No response_
> 
> ### Device information
> * Device: Pixel 3 XL and Pixel 6 Pro (tested on both)
> * OS: Custom, modified CalyxOS 3.3.0, Android 12L
> * App version:12.0.0 Alpha 5
> 
> ### Additional context
> _No response_

This happens because Lawnchair did not yet merge the Android 12L Launcher3 base, so it won't be usable as a recents provider on 12L until it does so

**Comment by ubergeek77** [comment]
Makes sense.

Looking forward to the merge!

**Comment by ubergeek77** [comment]
Can this be left open until it is resolved?

People will likely be looking for issues regarding QuickSwitch not working. Wouldn't it be better to keep this one open so they don't create duplicate issues?

**Comment by SuperDragonXD** [comment]
Late response, but Lawnchair 12.1 (12L) has already been released. I think that you can close this issue.

**Comment by ubergeek77** [comment]
Yep
