### ISSUE TITLE
[Feature Request] Need updates on Play Store

### ISSUE THREAD

**Issue by opticSquid** [Deletescape-Media/Lawnchair#2518]
I am a normal user of this launcher. As I see all the releases are getting stuck in pre release stage. When can we expect new updates the launcher. In Play Store the update was way back in 2019.

**Comment by SuperDragonXD** [comment]
Well, Lawnchair 12 is currently in Alpha, so I don't think the developers will release a version of it to the playstore, unless it is now in beta (which may take a long time). Also, many features are still unfinished, so do you want a unfinished version of Lawnchair to go to the play store?

**Comment by julianfairfax** [comment]
> Well, Lawnchair 12 is currently in Alpha, so I don't think the developers will release a version of it to the playstore, unless it is now in beta (which may take a long time). Also, many features are still unfinished, so do you want a unfinished version of Lawnchair to go to the play store?

Considering the latest version on the Play Store is 3 years old and the latest version on F-Droid is also 3 years old but even more behind than the Play Store version, any update to the Play Store and F-Droid versions is better than the current versions.

Yes, I know that F-Droid wouldn't accept Lawnchair in its current form, but a solution for that has already been found: https://github.com/LawnchairLauncher/lawnchair/issues/1473#issuecomment-481542592 and only needs to be implemented, to finally close what is also a 3 year old issue.

**Comment by Degl1** [comment]
Well I think their biggest goal for now is getting the launcher out of alpha. Then the Play Store/F-Droid versions will probably see an update.
