### ISSUE TITLE
[BUG] After rotating the phone to landscape mode google search bar vanishes

### ISSUE THREAD

**Issue by opticSquid** [Deletescape-Media/Lawnchair#2519]
### Describe the bug

After rotating the phone to Landscape mode the Google Search bar vanishes from Home Screen.

### Steps to reproduce

1. Go to `Home Screen`
2. Rotate the phone to `Landscape Mode`.

### Expected behavior

Google Search bar should remain visible in Landscape mode too.

## This is in `Portrait Mode`
![Screenshot_2022-03-20-13-37-42-29](https://user-images.githubusercontent.com/59192460/159153875-2c7983fb-b917-484a-be86-4cf7c3e7e31b.jpg)
---
## This is in `Landscape Mode`
![Screenshot_2022-03-20-13-37-49-94](https://user-images.githubusercontent.com/59192460/159153969-5d688695-c4b7-47bb-8159-d1c6a02ba4ef.jpg)

### Device information

- Device: [e.g. Oppo A5s]
- OS: [e.g. stock ROM Android version 8.1.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by yasanglass** [comment]
I think that's just how it works and not a bug?!

**Comment by suphon-t** [comment]
Yep. This is the intended behavior.
