### ISSUE TITLE
Folder style like launcher Evie 

### ISSUE THREAD

**Issue by gothakaz** [Deletescape-Media/Lawnchair#252]
Hi guys

Brilliant launcher 😀 with only 2 requests suggestions please

Take a look at how the launcher Evie delivers folders.... It's very cool and would make your launcher complete..

Also the hight of the Google search bar, chance of the option to scale ?

**Comment by Mr-Perezident** [comment]
This is mostly a stock-ish launcher, so I don't know about this idea.

**Comment by gothakaz** [comment]
Thanks for the quick update, how about transparent folders please 😀

Sent from Alto
On Wednesday, 19 July 2017 at 17:47 MrPerezident10 <notifications@github.com> wrote:

This is mostly a stock-ish launcher, so I don't know about this idea.

**Comment by jtwp** [comment]
I think this is a good idea. You've allowed blur, which isn't very stock-ish and having folder shapes would allow people to match them with their icons.

**Comment by versavius** [comment]
I do like the Evie launcher but with the transparent option now for the background it is mostly like Evie :)

Are you talking about the Google search bar on the app drawer?

**Comment by rajumark** [comment]
idea -> create folder activity transparent and user android default class shared element transition and move all view to another view
