### ISSUE TITLE
Cant run pwa from home screen

### ISSUE THREAD

**Issue by H3n-beep** [Deletescape-Media/Lawnchair#2520]
When i add a pwa and and press it on the homescreen, nothing happens, it looks like the pwa  needs a permission , changed launcher and tried again and the pwa launched fine. Im using chromium for using the PWAs

**Comment by RikKoedoot** [comment]
Closing because this bug report does not follow the bugreport template that is provided, please fill it out so we have enough information: https://github.com/LawnchairLauncher/lawnchair/issues/new?assignees=&labels=&template=bug_report.yaml&title=%5BBUG%5D+
