### ISSUE TITLE
[BUG] Quickswitch doesn't work on Android 12.1

### ISSUE THREAD

**Issue by Peekale** [Deletescape-Media/Lawnchair#2521]
### Describe the bug

With the latest version of Android 12 (March 2022 Patch, also known as 12L) on my Pixel 6, Lawnchair is not seen as compatible with Quickswitch and cannot be enabled.

### Steps to reproduce

1. Install latest versions of lawnchair 12, and Quickswitch on the latest version of Android 12
2. Open quickswitch to change the recents provider
3. You'll notice that quickswitch is saying it's not compatible.

### Expected behavior

I'm supposed to be able to go into quickswitch and select lawnchair, as with all previous versions of android 12.

### Screenshots

![Screenshot_20220322-092046](https://user-images.githubusercontent.com/36945659/159476433-0e8e362e-0428-4825-b170-8ca5caa771ba.png)

### Device information

- Device: [Google Pixel 6]
- OS: [stock ROM Android version 12L March Patch, Rooted with latest Magisk Canary]
- App version [12.0.0 Alpha 5]

### Additional context

From what I read from the quickswitch developer on the XDA forums, this seems to be a lawnchair issue and not a quickswitch issue? Here's the post in question:

https://forum.xda-developers.com/t/module-p-q-r-s-3-2-0-quickswitch-universal-quickstep-switcher.3884797/post-86540237

I'm not educated on the matter just wanted to post it here in case it helps?

This is probably already a known issue with 12L but I didn't see a bug report for it.

**Comment by SuperDragonXD** [comment]
Lawnchair's base hasn't been updated to Android 12L (yet), so that. See #2517 too.

**Comment by Peekale** [comment]
> Lawnchair's base hasn't been updated to Android 12L (yet), so that. See #2517 too.

Ah I didn't spot that issue. Well if the devs want to close this report I guess they could!

**Comment by SuperDragonXD** [comment]
Lawnchair now has a 12.1 release, so you can close this issue now.

**Comment by Soudini** [comment]
I have the same issue using the latest version of Lawnchair and Quickswitch.

![Screenshot_2022-08-29-11-03-06-10_87db87a91f635a88b611e4e74b8c91b8.jpg](https://user-images.githubusercontent.com/45032247/187165393-fae8402f-2c40-4a4f-aaf2-ded97f12229c.jpg)

**Comment by Anonymous941** [comment]
Still happening on the 12.1.0 alpha 4, installed from the IzzyOnDroid repo.
