### ISSUE TITLE
[BUG]  Couldn't change the icon size on tablet in horizontal.

### ISSUE THREAD

**Issue by Moderpach** [Deletescape-Media/Lawnchair#2522]
### Describe the bug

Couldn't change the icon size on tablet in horizontal. When I change the size in setting, it wouldn't work.

### Steps to reproduce

1. Keep horizontal.
2. Change the size of icon on home screen.
3. Back to the home screen.
4. The icon size wouldn't change.

### Expected behavior

Icon size can be changed when horizontal.

### Device information

- Device: [e.g. Lenovo Tab P12 Pro]
- OS: [e.g. ZUI 13]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by migueltrigobaulo** [comment]
Even after changing icons in portrait, if you rotate screen icons will show in the default size, but works as intended in app drawer
