### ISSUE TITLE
[BUG] 'Blur Page Backgrounds' Option draw tiny little rainbow dots

### ISSUE THREAD

**Issue by ahsaan64** [Deletescape-Media/Lawnchair#2523]
# Option disabled:
![Screenshot_2022-03-28-12-46-40-664_ch.deletescape.lawnchair.plah.jpg](https://user-images.githubusercontent.com/102504284/160334200-2fd19237-8119-464d-85c0-1df965cfb8a5.jpg)

# Option enabled:
![Screenshot_2022-03-28-12-47-19-969_ch.deletescape.lawnchair.plah.jpg](https://user-images.githubusercontent.com/102504284/160334233-d6fbb009-cb48-4a51-b671-3329f7b3f60e.jpg)

# Phone Spesifications:
- Model Name: Redmi 9C
- Android 10
- MIUI version: MIUI Global 12.0.12 Stable
- CPU: MediaTek MT6765G Helio G35 (12 nm)
- GPU: PowerVR GE8320

**Comment by SuperDragonXD** [comment]
Using Lawnchair 2?

**Comment by ahsaan64** [comment]
Correct, I'm using Lawnchair 2 Ver 2.0-2589

**Comment by keyjeyelpi** [comment]
That's a mediatek issue rather than a lawnchair issue

**Comment by ahsaan64** [comment]
I'm not sure, I had the other launcher app and it works fine

![Screenshot_2022-03-28-15-09-09-416_com.bllocosn.jpg](https://user-images.githubusercontent.com/102504284/160355067-8d5c4f31-4b4f-425d-bfef-75aa0907b8f2.jpg)

![Screenshot_2022-03-28-15-09-13-172_com.bllocosn.jpg](https://user-images.githubusercontent.com/102504284/160355036-3b9e85ea-cb40-4e48-b510-d522073a78bf.jpg)

**Comment by RikKoedoot** [comment]
Closing this issue as development is focused on Lawnchair v12
