### ISSUE TITLE
Please add optional full theme customization

### ISSUE THREAD

**Issue by Secret-chest** [Deletescape-Media/Lawnchair#2526]
I got this reply:
* Full theme customisation: It's the thing behind A12's dynamic colours.

I get it, but can there be an option to opt-out of this and set all colors however you want.

I would also like to be able to change more things to how they looked before A12 - but I understand you're doing a rewrite. I'll just want to see this being considered and I'll wait for it.

**Comment by RikKoedoot** [comment]
1, you already opened an issue about this.
2, you can change the accent color in Lawnchair, making the material you follow the accent color.

**Comment by SuperDragonXD** [comment]
Here's how you change it:

https://user-images.githubusercontent.com/70206496/161056483-63d7e825-2710-4096-8032-ae5cf7c79f3d.mp4

**Comment by Secret-chest** [comment]
> Here's how you change it:
> 
> https://user-images.githubusercontent.com/70206496/161056483-63d7e825-2710-4096-8032-ae5cf7c79f3d.mp4

You can't change the background separately.

**Comment by Secret-chest** [comment]
keep open

**Comment by RikKoedoot** [comment]
This most likely won't get added

**Comment by Secret-chest** [comment]
bump

**Comment by Secret-chest** [comment]
> This most likely won't get added

I'll stay with L11 🙃
