### ISSUE TITLE
[SUGGESTION] Outline for covered icons

### ISSUE THREAD

**Issue by meyverick** [Deletescape-Media/Lawnchair#2528]
I would like to suggest to add an option to show an inside stroke/"inside outline" of color choice around covered icon (icon in cover mode in the dock).

I love this feature but many times I forgot that an icon is in cover mode so I finally don't use it 😂

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> I love this feature but many times I forgot that an icon is in cover mode so I finally don't use it 😂

This request depends on Cover Mode itself being available again, which is currently tracked in #2659.

- #2659
