### ISSUE TITLE
Icon scale not working

### ISSUE THREAD

**Issue by benmadethis** [Deletescape-Media/Lawnchair#253]
Just tried to increased the icon size for the first time. Got stick in a crash loop. I cleared all of Lawnchair's data and tried again to re-produce the bug. Now it won't work at all. No matter what scale I choose (between 30% and 150%) it has no effect on the icons size.

Lawnchair build 818
Nexus 7 (2013)
Android 7.1.2 (LineageOS 14.1)
Rooted with Magisk 13.3

**Comment by benmadethis** [comment]
Just rebooted my tablet and the change in icon size has taken effect. If I try and change the icon scale again it won't apply unless I reboot of force stop Lawnchair.

**Comment by repires** [comment]
Same here. Oneplus 5

**Comment by intelligentcasanova** [comment]
Is still issue still present in the latest build?
