### ISSUE TITLE
[SUGGESTION] Ability to have Widgets in App Drawer

### ISSUE THREAD

**Issue by ComValer** [Deletescape-Media/Lawnchair#2534]
### Describe the bug

I knooow it sounds strange, but let me explain this: when you wandering App Drawer - it might be little annoying and monotone to just have app icons. So I'd like to have an ability to place the Widgets into the App Drawer just like on the Screenshots.

The suggested Way: they will pin their position on the left higher corner, and will automatically move if the displayed apps amount will change. Every widget will simply take the amount of icons (in order to be placed) based on its size (3x1=3, 1x2=2, 1x1=1, 5x2=10, and etc) Ye there should be some additional case workarounds, but mostly its supposed to be a primitive system
And at all, it's suggested as an additional system, so you'll just able to use it or not (might be turned on/off or even modified in the settings). 😃😃 ✌️

### Steps to reproduce

NaB

### Expected behavior

NaB

### Screenshots

![Screenshot_20220410-233459](https://user-images.githubusercontent.com/72487083/162639282-6f94c7ca-26ef-4e32-8a53-05c42e8a3943.jpg)
![Screenshot_20220410-232631](https://user-images.githubusercontent.com/72487083/162639284-b50d6499-479c-45c8-8d6a-80488fd19096.jpg)
![Screenshot_20220410-232247](https://user-images.githubusercontent.com/72487083/162639292-228d0d6d-ebf1-4d20-8ba5-db8a77c8d73d.jpg)

### Device information

NaB

### Additional context

*NaB - Not a Bug

**Comment by ComValer** [comment]
The screenshots are just virtual representation of the suggestion in the realized state.

**Comment by Degl1** [comment]
Well I'd assume just disablng the app drawer would be better for you? As there is no point in having widget support to cludder the app drawer.
