### ISSUE TITLE
Lawnchair website outdated

### ISSUE THREAD

**Issue by yurikodesu** [Deletescape-Media/Lawnchair#2537]
Any plans to update lawnchair website? I can help a bit because I know a bit about HTML and CSS. I think that the website should show our latest changes done to lawnchair instead of looking like dead outdated shit.

**Comment by SuperDragonXD** [comment]
There are plans (see in https://github.com/LawnchairLauncher/lawnchair.app/tree/next), but it hasn't been updated for Lawnchair 12

**Comment by Degl1** [comment]
Well I think they're planning on getting the Lawnchair out of Alpha first. But be sure to make pull requests with updates you'd think would be fit.

**Comment by yurikodesu** [comment]
> Well I think they're planning on getting the Lawnchair out of Alpha first. But be sure to make pull requests with updates you'd think would be fit.

Oh ok got it
