### ISSUE TITLE
Weather is not showing up on right top corner of the home screen

### ISSUE THREAD

**Issue by johndoe422** [Deletescape-Media/Lawnchair#254]
I am using this launcher in my Redmi Note3 running Resurrection Remix Rom (Nougat 7.1.2)  16-Jul-17 build. The launcher shows the day & date on the top right portion of the screen, whereas Pixel launcher shows the weather in that area.

**Comment by maximemhd** [comment]
#21

**Comment by mehmetcanbozkus** [comment]
Best Launcher

**Comment by suphon-t** [comment]
Duplicate of #21
