### ISSUE TITLE
[SUGGESTION] More icon shapes from Lawnchair 2

### ISSUE THREAD

**Issue by severtheskyline** [Deletescape-Media/Lawnchair#2541]
### Describe the bug

As of Lawnchair 12 Alpha 5, Lawnchair only have 4 icon shapes:
-The system one
-Circular
-Squircle
-Rounded square 
Now, this is better than any other vanilla launcher out there, but is nowhere near as close as the old Lawnchair 2 (And Lawnchair 10, before the rewrite).
There are the next missing shapes:
-Square
-One UI
-Cilinder
-Teardrop

### Steps to reproduce

1. Go to 'General'
2. Click on 'Icon Shapes'
3. See the only icon shapes there. 

### Expected behavior

More icon shapes (Or at least parity between the old Lawnchair and the slick new Lawnchair). 

### Screenshots

Old:
![Screenshot_20220417-144244](https://user-images.githubusercontent.com/79670265/163731404-6b373e2f-6092-43ed-9495-452c51a1d065.png)
New:
![Screenshot_20220417-144250](https://user-images.githubusercontent.com/79670265/163731417-57f88902-6695-42b8-971c-f71ac2c8b6ab.png)

### Device information

- Device: [ LG Stylo 6 ]
- OS: [ LG UX 9 on Android 10 ]
- App version [ 12.0.0 Alpha 5 ]

### Additional context

I would love the old squared ones to be in the new Lawnchair, they look similar to Android Go, and pretty good.

**Comment by yasanglass** [comment]
Lawnchair 12 supports 8 icon shapes and based on my brief testing, they all work and are unique. Not sure why the UI only lets the user choose between 4 options. I can do a simple PR that adds support for this but there is probably a reason behind the limitation.

https://github.com/LawnchairLauncher/lawnchair/blob/c868e32c97d9630f93f10ffd143c3fd736cca6d9/lawnchair/src/app/lawnchair/icons/shape/IconShape.kt#L284-L302

**Comment by severtheskyline** [comment]
It could be a UI bug, but why select such specific shapes to appear? Seems interesting.

**Comment by RikKoedoot** [comment]
I asked @paphonb, he said the code is copied from V2, but he does not remember why we did not use all shapes.

**Comment by SuperDragonXD** [comment]
Someone has made a PR for this issue now. I guess we should just wait until they merge it.

**Comment by yasanglass** [comment]
PR was merged. Probably should close this now. @PandoraHayami

**Comment by severtheskyline** [comment]
Right. Lovely!
