### ISSUE TITLE
Add an AMOLED background. black color.

### ISSUE THREAD

**Issue by sdfsd2** [Deletescape-Media/Lawnchair#2543]
![photo_2022-04-21_02-41-41](https://user-images.githubusercontent.com/102774950/164342113-002ad63f-5f23-4e68-9253-5e24f7a16154.jpg)

I know. this feature has not yet been implemented.

**Comment by Degl1** [comment]
Do you mean app drawer pinned apps? This would seem pointless as there is a thing called the home screen.

**Comment by sdfsd2** [comment]
black color. close this topic?

**Comment by SuperDragonXD** [comment]
Somewhat late response, but you should probably rename the title to "Add an AMOLED background" or something similar, since the current title isn't the most descriptive
