### ISSUE TITLE
[BUG] Crash when adding clock widget

### ISSUE THREAD

**Issue by tiagogaspar8** [Deletescape-Media/Lawnchair#2546]
### Describe the bug

Hi,

So, I recently updated the my phone to android 12 and since then when I add some widgets (this bug is specifically for the Google clock widget) lawnchair crashes.

### Steps to reproduce

1. Go to widgets
2. Click on the Google clock widget
3. Place it
4. Select "transparent" or "solid" it doesn't matter
5. Lawnchair crashes

### Expected behavior

The widget is added and lawnchair doesn't crash

### Screenshots

N/A

### Device information

- Device: OnePlus 8
- OS: latest Stock ROM with Android 12 EU
- App version: 12.0.0 alpha 5

### Additional context

I believe there's no need for additional context, any doubt just say! Also available for testing of course

Will keep this updated as versions come out.

Crash log:
[Lawnchair bug report 21 Apr 2022 22_45_14.txt](https://github.com/LawnchairLauncher/lawnchair/files/8535395/Lawnchair.bug.report.21.Apr.2022.22_45_14.txt)

**Comment by hipblo** [comment]
Same here bro.
I was able to get the widget on the screen by restarting the phone and trying to add it right after, but after 20 minutes the app crashes again.

Device: Samsung Galaxy A71.

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with this  specific error) are being tracked on #2820. Closing this issue.
