### ISSUE TITLE
[BUG] app drawer slider animation error

### ISSUE THREAD

**Issue by xilegod026** [Deletescape-Media/Lawnchair#2547]
### Describe the bug

Janky slider scrolling animation in the app drawer

### Steps to reproduce

1. Go to homescreen
2. Swipe open app drawer
3. Scroll around

### Expected behavior

A smooth animation instead of a janky one.

### Device information

- Device: Realme 8 5g (4gb/128gb)
- OS: Android 11 based on RealmeUI2.0
- App version 12.0.0 Alpha 5

**Comment by xilegod026** [comment]
Here's the screen record as I forgot to add it whole opening issue

https://photos.app.goo.gl/jdPwZEmBYKbEHCHE8

**Comment by ComValer** [comment]
Won't you mind if I upload the vid of mine Lawn chair 12.0.0 Alpha 5?
Just got the same Realme 8, and I did updated to the latest Realme UI 2.0 that indeed fixed the bugs I got in system)(

**Comment by xilegod026** [comment]
> Won't you mind if I upload the vid of mine Lawn chair 12.0.0 Alpha 5? Just got the same Realme 8, and I did updated to the latest Realme UI 2.0 that indeed fixed the bugs I got in system)(

Yes please

**Comment by xilegod026** [comment]
It needs a fix for that bug. It looks very. Weird. And the stock realmeUI launcher is kinda too locked for me, especially with the icon size lock in the drawer and no support for icon packs

**Comment by xilegod026** [comment]
If this is for all realme devices, maybe a whole fix in alpha 6 for Realme devices will be cool

**Comment by ComValer** [comment]
> > Won't you mind if I upload the vid of mine Lawn chair 12.0.0 Alpha 5? Just got the same Realme 8, and I did updated to the latest Realme UI 2.0 that indeed fixed the bugs I got in system)(
> 
> Yes please

Do you want me to upload it to your vid album? In this case allow me to Upload media there
You Can see me there already, but I'm not able to do upload anything \

**Comment by SuperDragonXD** [comment]
It's likely to be a Realme issue, since on ColorOS the drawer works fine.

Maybe rename the issue to have `(Realme)` on the title?

**Comment by ComValer** [comment]
> It's likely to be a Realme issue, since on ColorOS the drawer works fine.
> 
> Maybe rename the issue to have `(Realme)` on the title?

Here's the thing there's no such bug on My Realme 8
It's already disapproved

**Comment by xilegod026** [comment]
> Do you want me to upload it to your vid album? In this case allow me to Upload media there You Can see me there already, but I'm not able to do upload anything \

Yes, enabled collaboration.
