### ISSUE TITLE
Suggestion: Drag app drawer folders to home screen

### ISSUE THREAD

**Issue by JoshuaACasey** [Deletescape-Media/Lawnchair#2554]
I just made the bewildering discovery that you can't tap and hold folders in the app drawer to drag them onto the home screen (you have to drag the individual apps onto the home screen and then put them into a folder--which is obviously tedious). It would be much appreciated if you could allow dragging folders from the app drawer onto the home screen (or dock)

**Comment by RikKoedoot** [comment]
You're talking about Lawnchair 2, we are not working on that anymore, we are working on Lawnchair 12, sadly it does not have appdrawer folders yet.
