### ISSUE TITLE
Cant open recent apps via geasture while using lawnchair 12.0.0 dev 687

### ISSUE THREAD

**Issue by gmp009** [Deletescape-Media/Lawnchair#2557]
Hi I am using Galaxy S21 FE OneUI 4.1 with Android 12 and used Lawnchair Alpha 5 and Dev 687 both have weird issue I am not able to open recent apps while pulling my gesture line up other than that all is working fine for me Can you please do something for that.

**Comment by RikKoedoot** [comment]
That's a Samsung issue, try holding it for longer.
