### ISSUE TITLE
Adding a new icon shape (Feature request)

### ISSUE THREAD

**Issue by hakunama1ata** [Deletescape-Media/Lawnchair#2559]
Please add pebble icon shape to the launcher

**Comment by yasanglass** [comment]
Can you be more specific about what a "Pebble" icon shape looks like?

**Comment by hakunama1ata** [comment]
![image](https://user-images.githubusercontent.com/67356841/183653641-f4ed84fb-8418-4d44-8481-c8a8610ca658.png)
![image](https://user-images.githubusercontent.com/67356841/183653755-f9a191c3-e2e1-4cef-b699-7e31917b57ec.png)

**Comment by hakunama1ata** [comment]
> Can you be more specific about what a "Pebble" icon shape looks like?

![image](https://user-images.githubusercontent.com/67356841/183653927-336035f7-13dc-4c08-8b3b-4a172c63eaa3.png)
![image](https://user-images.githubusercontent.com/67356841/183653992-8ef07f72-4668-4eb5-8902-1647b35d3a6d.png)

**Comment by hakunama1ata** [comment]
@yasandev  🥹

**Comment by msfjarvis** [comment]
> @yasandev 🥹

Please do not bump the issue and spam the developers if you don't have anything new to add. If you want things to move faster you should send a pull request, not puppy eyes.
