### ISSUE TITLE
[BUG]  Doesn't work at all on Android 13 (beta).

### ISSUE THREAD

**Issue by callmeluffy** [Deletescape-Media/Lawnchair#2560]
### Describe the bug

Continuously keeps crashing in Android 13 beta. Can't even launch apps.

### Steps to reproduce

Open any app through launcher , it crashes. We also get a bug report which I'm trying to share.

Link : https://drive.google.com/file/d/1hZrPn2DSFVaR0cVqLUT4dhhOnfy-4P9o/view?usp=drivesdk

### Expected behavior

Normal working 

### Device information

- Device: [e.g. Google Pixel 6]
- OS: Android 13 beta
- App version [e.g. 12.0.0 Alpha 5]

**Comment by jcrabapple** [comment]
I've seen this behavior as well. Android 13 beta. Pixel 6 Pro. Can't open Lawnchair settings or launch apps.

**Comment by Darkham42** [comment]
As @RikKoedoot said [there](https://github.com/LawnchairLauncher/lawnchair/issues/2553) it'll be fix in next release.
