### ISSUE TITLE
[BUG] [A12.1 Dev #698] Share Quick Action in Recent Apps not working

### ISSUE THREAD

**Issue by pranavsetpal** [Deletescape-Media/Lawnchair#2563]
### Describe the bug

I installed the latest [A12.1 Dev #698] lawnchair on my device [davinciin] and used Quickswitch to use the Recent Apps.
Turned on Share button and tested it but did not work. All others do.

P.S. Pardon if this isn't enough information this is my first issue and doesn't seem like any more data is there to be given.

https://user-images.githubusercontent.com/68775426/167575144-39a59fcb-3eb7-4dfa-a324-cbef288c883a.mp4

### Steps to reproduce

Steps to reproduce the behavior: [Assumed Lawnchair made as Recent Apps Provider via Quickswitch]
1. Click and Hold on Home Screen
2. Click On Home Settings
3. Open the 'Recent Apps' tab
4. Enable 'Share' in 'Quick Actions'
5. Swipe Up and Hold to Enter the Recent Apps Menu [Gesture Navigation] / Click on the 'Square' button on the bottom of your screen to Enter the Recent Apps Menu [3-Button Navigation]
6. Click on the Share Button
7. See literally nothing happen [No error message comes as well]

### Expected behavior

On clicking the share button it should directly show me to whom I want to share it with, it being the screen of the highlighted app in the Recent Apps section, similar to taking a screenshot and sending, but rather just sending directly without saving said screenshot.

### Device information

- Device: Redmi K20 / Mi 9t [davinci] (davinciin for me)
- OS: DotOS 6.0 Beta
- App version 12.1 Dev #.698

**Comment by suphon-t** [comment]
Fixed in fd595b9
