### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jasjamjos** [Deletescape-Media/Lawnchair#2567]
### Describe the bug

My phone has desktop mode hen connected to usb c output.. it didnt recognize the lawnchair so i switched to my default home screen.. after then when i tried to switch back to lawnchair it keeps crashing 

[Link to the log](https://gist.github.com/jasjamjos/404bf898a7d431c9bba806d13d6d7629) 

### Steps to reproduce

1. Set lawnchair as default
2. Connect usb c display output and gp to desktop mode
3. Set launcher to the default or stock launcher
4. Disconnect to desktop mode

### Expected behavior

App crashing over and over

### Screenshots

![Screenshot_20220511-145400](https://user-images.githubusercontent.com/27815533/167787241-918d297f-4a63-494f-b537-32cba9f4cd7b.png)

### Device information

- Device: LG V50
- OS: stock android 11
- App version: 12.0.0 Alpha 5

**Comment by SuperDragonXD** [comment]
Update to Launcher 12.1+, should fix the issue (since the release removed Lawnchair's built in desktop mode and relied to the stock one instead. Closing this issue.
