### ISSUE TITLE
Bugs Report ( Build 818 ) 

### ISSUE THREAD

**Issue by Bikoo03** [Deletescape-Media/Lawnchair#257]
- Reorganizing icons on home screen stuck sometimes(Unable to select them)
- Hanging when we try to long press in the homescreen to enter Lawnchair settings
- Pixel Pill disappears after returning from Lawnchair settings (Sometimes)
- Stuck when trying to press the power button to unlock
- Not proper sync of Google Now Tab (Takes time loading)
- The whole screen totally stuck sometimes
- Music player widget problem (Using Shuttle+ here, the play button is bit buggy)

Hope it helps 👍

**Comment by intelligentcasanova** [comment]
I experienced the long press to access settings problem too. After having changed something in the settings, long press on home screen won't work. Only after pressing the android recent apps button and home button I am able to access the wallpapers/widgets/settings.

**Comment by Chaphasilor** [comment]
+1 for the pill diasppearing.

**Comment by Martin005** [comment]
After I first installed and opened the Lawnchair, a window popped up with blank changelog.

![screenshot 20 7 2017 17_42_45](https://user-images.githubusercontent.com/10096404/28426406-4b8e4c88-6d73-11e7-956c-8f224bb02685.png)

**Comment by Chaphasilor** [comment]
@Martin005 yeah, same for me, although this is not too big of a deal...
