### ISSUE TITLE
Enhance the hiding apps functionality

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2570]
Currently when we hide apps and search them in the search bar the hidden apps are displayed as search results.
Instead of this a better system can be implemented. Example like how it is done in oppo phones.

1. Let us select which app to hide 
2. Then force us to create a password which starts and ends with asterisks or star marks
3. Then instruct the user that in order to access the hidden apps we have to enter this code in the search bar
4. After the code is entered we can find the list of hidden apps

**Comment by Amorphous404** [comment]
Duplicate of #2419 ?
