### ISSUE TITLE
Enable resizing of widgets

### ISSUE THREAD

**Issue by pdmnhn** [Deletescape-Media/Lawnchair#2572]
https://user-images.githubusercontent.com/42073602/167903584-6c5522ad-d60a-4a6b-839c-3300414db245.mp4

**Comment by suphon-t** [comment]
If a widget doesn’t support resizing, you can’t resize it.

**Comment by pdmnhn** [comment]
Other launchers like the Lawnchair in play store, Nova launcher support this. As seen in the video the widget adds an empty space around it and not able to resize the widgets is an undesirable bug.
