### ISSUE TITLE
[BUG] Lawnchair doesn't work with dynamically updating icon packs

### ISSUE THREAD

**Issue by Braffolk** [Deletescape-Media/Lawnchair#2573]
### Describe the bug

Icon packs or shortcut creators like Dynamic Material You icon pack and Themed Icons should automatically be updating their colors to match wallpaper changes, but because Lawnchair caches icons and does not detect changes, this isn't possible.

### Steps to reproduce

1. Install dynamic material you iconpack: https://play.google.com/store/apps/details?id=iconpack.onsurface.monet&hl=en&gl=US
2. Enable icon pack
3. Change wallpaper
4. See how icons don't change.

### Expected behavior

Icons should update with wallpaper changes. Using Lawnicons is not a solution, because it has few icons and does not support creating themed shortcuts. 12 000 in the case of Dynamic Material you. 

### Device information

- Device: Pixel 3A
- App version both beta 5 and build #714

**Comment by rafifos** [comment]
Icons aren't being updated when toggling dark mode as well. Some themes have different icons for it, like the onDynamic Icon Pack.
