### ISSUE TITLE
[Feature] Add Blur again to Lawnchair

### ISSUE THREAD

**Issue by Adish08** [Deletescape-Media/Lawnchair#2575]
Please add the Blur feature in Lawnchair 12 as in previous Lawnchair versions.

**Comment by panda4k** [comment]
It would be a smart choice for it to be an option. Some people disable blur for performance.

**Comment by nonetrix** [comment]
Please add this

Also it's worth noting Android recently added a API for blurring which could improve performance of this effect in theory however it will only work on Android 12+

https://blog.stylingandroid.com/rendereffect-blur/
