### ISSUE TITLE
[BUG] I am not seeing the smartspace widget from 12.1-dev

### ISSUE THREAD

**Issue by prayag17** [Deletescape-Media/Lawnchair#2576]
### Describe the bug

Hello, I am unable to see the smartspace widget from 12.1-dev branch's apk

### Steps to reproduce

1. Install debug apk from actions
2. Open lawnchair 12.1

### Expected behavior

Smartspace widget should be visible in the widget panel

### Device information

- Device: Mi 11x
- OS: stock ROM Android version 12.0
- App version: 12.1.0 dev build 723

**Comment by RikKoedoot** [comment]
that is because it is not enabled by default yet. it will be enabled in later builds

**Comment by prayag17** [comment]
Ohk thanks
