### ISSUE TITLE
System Accent Color doesn't works properly

### ISSUE THREAD

**Issue by kerimgrande** [Deletescape-Media/Lawnchair#2583]
I use 12 Dev and when I wanted to select my System accent color, it turned blue instead of green. Restarting didn't work. Reapplying the Color Pallette in One UI Home didn't work either.

**Comment by suphon-t** [comment]
If restarting didn't work I think it might be One UI's fault, because Lawnchair is reading the accent color from the system itself. Does color changing works in other apps?

**Comment by kerimgrande** [comment]
> If restarting didn't work I think it might be One UI's fault, because Lawnchair is reading the accent color from the system itself. Does color changing works in other apps?

It definitely worked in Lawnchair 12 Alpha 5 @paphonb

**Comment by suphon-t** [comment]
> It definitely worked in Lawnchair 12 Alpha 5 @paphonb

And the relevant code hasn't been changed since.

**Comment by kerimgrande** [comment]
> > It definitely worked in Lawnchair 12 Alpha 5 @paphonb
> 
> And the relevant code hasn't been changed since.

oh alright. i fixed it through restarting my phone tho. thanks!
