### ISSUE TITLE
[FEATURE] Disable App Drawer or Move Drawer to Home Screen Page

### ISSUE THREAD

**Issue by TotalChris** [Deletescape-Media/Lawnchair#2585]
Although it seems silly, I've tried to use Lawnchair to mimic an iOS setup to minimize my digital addiction. In Lawnchair v1, the gestures can be changed so that a swipe up will not trigger the app drawer. I have all my apps I need placed on my home screen and I'd like to do this, but I suppose it would have to come with the Gestures system to function similarly.

Another way to do this would be like Smart Launcher does, where different launcher components like the News Feed, search, and App Drawer can be shifted to different swipe-directions of the home screen. I like this feature but I hate Smart Launcher so it would be nice to see it implemented in LC.

**Comment by Amorphous404** [comment]
Duplicate of #2096
