### ISSUE TITLE
 [BUG] Problem with Enable taskbar 

### ISSUE THREAD

**Issue by 2036648790** [Deletescape-Media/Lawnchair#2589]
### Describe the bug

After I repeatedly switch from the app to the desktop, there is a problem with the Enable taskbar, it only has a white bar after opening the app

### Expected behavior

I hope to have fun using Enable taskbar

### Screenshots

![Screenshot_20220517-001216_Chrome](https://user-images.githubusercontent.com/53891152/168637218-6a9d830d-d53d-4053-af58-1e70f7eee1e3.png)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

### Additional context

I am using version 739, and it will freeze when there is a problem. The system is Android 12. I feel that the launcher setting interface is a bit stuck, and I hope to optimize stability and fluency

**Comment by suphon-t** [comment]
You can long press to expand it.

**Comment by 2036648790** [comment]
This is the first time I report a bug, please forgive me for any shortcomings

**Comment by 2036648790** [comment]
> 

Wow! I really didn't know there was this operation, thanks a lot! 😉
