### ISSUE TITLE
[BUG] 崩溃

### ISSUE THREAD

**Issue by 2036648790** [Deletescape-Media/Lawnchair#2590]
### Describe the bug

https://ctrl-v.app/raw/4fNgTzk

### Expected behavior

increase stability

### Screenshots

https://ctrl-v.app/raw/4fNgTzk

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

### Additional context

Suddenly crashed in my normal use

**Comment by suphon-t** [comment]
This crash only happens in debug builds and doesn't affect usage
