### ISSUE TITLE
[BUG] Apps cannot be moved from drawer to desktop

### ISSUE THREAD

**Issue by 2036648790** [Deletescape-Media/Lawnchair#2591]
### Describe the bug

When I turn on the tablet mode, when I move the applications to the desktop one by one, the desktop is abnormally stuck for a while, and it is like this every time after that 

After testing, I don't have this problem if I don't turn on tablet mode

The animation also freezes when I open the app after this problem

### Expected behavior

Hope the developers solve this problem

### Screenshots

Sorry, I can't provide this

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by suphon-t** [comment]
Unfortunately we’re going to need more details. A screen recording would be very helpful. Also, what do you mean by turning on tablet mode?

**Comment by 2036648790** [comment]
打 Turning on tablet mode refers to Enable taskbar

https://user-images.githubusercontent.com/53891152/168745265-bf0ecc1c-ff17-46ee-9471-13f904126cc5.mp4

**Comment by suphon-t** [comment]
The taskbar feature is provided as-is. We don’t currently support it.
