### ISSUE TITLE
Themed icons 

### ISSUE THREAD

**Issue by Vysakhkj** [Deletescape-Media/Lawnchair#2592]
Dear Developers, 
     Kindly provide themed icons for the following:-
1. Clock 
com.sec.android.app.clockpackage
2. Calendar 
com.samsung.android.calendar
3. Vflat
com.voyagerx.scanner
4. Radio 
com.sec.android.app.fm
5. Manglish keyboard 
com.clusterdev.malayalamkeyboard
6. Samsung Pay Mini 
com.samsung.android.spaymini
7. Google opinion rewards 
com.google.android.apps.paidtasks
8. Stokie 
com.harry.stokie
9. Samsung Video library 
com.samsung.android.videolist
10. Malayalam Dictionary 
Syamu.Dictionary.Sarada
11. Refox wall
amoledwallpapers.foxywall
12. Blackhole 
com.shadow.blackhole

**Comment by RikKoedoot** [comment]
Please use the lawnicons repo for icon requests only

**Comment by Vysakhkj** [comment]
> Please use the lawnicons repo for icon requests only
Ok. Thank you 😊 👍🏻
