### ISSUE TITLE
Fonts not applying to every part of the launcher.

### ISSUE THREAD

**Issue by nonyonah** [Deletescape-Media/Lawnchair#2594]
Hey, changing the fonts doesn't really apply the new fonts to every part of the launcher, like the at a glance widget, the settings app, the long pressed notifications, and the notification count are still stuck on the default launcher font even after changing my font.

**Comment by SuperDragonXD** [comment]
Read the text in the launcher settings
![Screenshot_2022-05-17-17-59-14-43_bedf565a1c91b6ed5418146c1d5b0124.jpg](https://user-images.githubusercontent.com/70206496/168785673-dffd1c0f-36e3-4d28-a286-8ed3979d32b7.jpg)
Also, font customization is also experimental, so that too.
