### ISSUE TITLE
[BUG] Toggle option not properly animating unless leaving screen

### ISSUE THREAD

**Issue by SuperDragonXD** [Deletescape-Media/Lawnchair#2598]
### Describe the bug

With the new "toggle" or something from M3 Design in Lawnchair 12.1, the toggle doesn't animate on open. It does animate when you close it, but it doesn't when you open the toggle. (It's kinda hard to explain in words, so see screen recording)

### Steps to reproduce

1. Go to any submenu with toggles
2. Find any toggle, e.g. "Notification Count"
3. Turn that toggle off (if it isn't already)
4. Turn it on again
5. See bug

### Expected behavior

The toggle should properly animate

### Screenshots

https://user-images.githubusercontent.com/70206496/168829126-03a990f2-919f-4fe7-b58d-36d3ef58603a.mp4

![Screenshot_2022-05-17-22-06-49-95_bedf565a1c91b6ed5418146c1d5b0124](https://user-images.githubusercontent.com/70206496/168830553-5cef7ca1-9120-48ad-b03f-b0c8c4539d51.jpg)

### Device information

- Device: Oppo A92
- OS: Android 11 ColorOS 11
- App version: Lawnchair 12.1 `#860`

### Additional context

The bug appears to be fixed if you exit the specific submenu and re-enter again.

**Comment by RikKoedoot** [comment]
Weirdly this doesn't happen for me
OnePlus 7
Android 12.1 kosp
Lawnchair 12.1

**Comment by SuperDragonXD** [comment]
Well, one user ([on discord](https://discord.com/channels/803299970169700402/808429446125322301/976036102966247424)) also reported that this happens on his stock android device.

What is the specific Lawnchair dev build you are using though?

**Comment by RikKoedoot** [comment]
#861

**Comment by Leyzymoy** [comment]
Support, faced the same problem, Android 10 MIUI 12.1, Redmi note 7.

**Comment by amisukarei** [comment]
s21ultra on crdroid GSI
Have the exact same issue

**Comment by SuperDragonXD** [comment]
Seems to be fixed on Dev `#951`, so I'll close this issue. (Sometimes the animation can lag, though)
https://user-images.githubusercontent.com/70206496/171760438-d72e277d-2b20-4e54-9645-99f8f0c6e0e5.mp4

**Comment by notroger7** [comment]
how do you get the dev builds?

**Comment by SuperDragonXD** [comment]
Well, I guess the issue is still not fully fixed... I guess the issue should remain open until we're sure that it is fixed for most devices

**Comment by SuperDragonXD** [comment]
> how do you get the dev builds?

https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#development-versions

**Comment by notroger7** [comment]
But the problem remains, I found out that this problem is also affected by the density of the screen, at 400dpi bug remains at 450dpi works as it should + this is affected by the duration of the animation 

-Switch Animation #2723

**Comment by notroger7** [comment]
@SuperDragonXD the issue is solved on Dev build #981 for me, go and have a look :)

**Comment by SuperDragonXD** [comment]
Nice that the issue has been fixed for your device. Some users might have the issue tho, so I guess let's just wait till we see that no one will report any issue.

I'll leave this open for 1 week, no replies = assume issue fixed
