### ISSUE TITLE
"Event not found" toast when opening GCalendar via clock

### ISSUE THREAD

**Issue by Chaphasilor** [Deletescape-Media/Lawnchair#260]
Everytime I click on the clock in the Google too bar, the Calendar opens normally, but there is a toast popup saying "Event not found". Maybe it's calling the wrong activity?

**Comment by G0ldenSp00n-zz** [comment]
I fixed this bug and issued a pull request.  Hopefully should be fixed by next release.

**Comment by AxiK101** [comment]
Nope, not fixed for me. Xperia XA Ultra, 7.0 stock android

**Comment by G0ldenSp00n-zz** [comment]
You have to wait till it is accepted by the author, and then you might have to wait till a patch is pushed.

**Comment by suphon-t** [comment]
Fixed with #274
