### ISSUE TITLE
[BUG] At a Glance will change size according to icon size

### ISSUE THREAD

**Issue by fantasy467** [Deletescape-Media/Lawnchair#2600]
### Describe the bug

When the icon size is modified, the size of At a Glance will also change.

### Expected behavior

The size of At a Glance should be fixed, but the search box in the dock should be adjustable in height to match the scaling of the icon.

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by suphon-t** [comment]
This is expected, as the widget is part of the home screen grid.

**Comment by fantasy467** [comment]
> 这是意料之中的，因为小部件是主屏幕网格的一部分。

So can you adjust the size of At a Glance individually?

**Comment by suphon-t** [comment]
> So can you adjust the size of At a Glance individually?

Disable At a Glance in settings, and drag it from the widgets picker instead. That way you can place it anywhere and adjust its size.
