### ISSUE TITLE
Unable to build lawnchair 12.1

### ISSUE THREAD

**Issue by binishmatheww** [Deletescape-Media/Lawnchair#2603]
Hi,
I'm trying to build the lawnchair app by cloning this repo.

But, I'm getting this error. 

C:\lawnchair\src\com\android\launcher3\allapps\AllAppsContainerView.java:83: error: cannot access SpringRelativeLayout
public class AllAppsContainerView extends StretchRecyclerViewContainer implements DragSource,
       ^
  class file for com.android.launcher3.views.SpringRelativeLayout not found.

Am I missing something ? 

I followed the steps in the readme.

**Comment by suphon-t** [comment]
Did you select the correct build variant?

**Comment by binishmatheww** [comment]
> Did you select the correct build variant?

Yes. 
Actually, I found a workaround for this issue by creating a SpringRelativeLayoutKotlin.kt class (copied everything from SpringRelativeLayout into it) and replacing all occurrences of SpringRelativeLayout with it.
I ran the app successfully.
