### ISSUE TITLE
[Features request] Things that may be interesting 

### ISSUE THREAD

**Issue by zzinkoo** [Deletescape-Media/Lawnchair#2605]
The At a Glance widget looks awesome, but I've found some things that may be interesting to add
•Flashlight toggle when the flashlight is on
•Notification Preview
•Connected devices
•Download progress
•Font change and size change

For the Pill
•An unninstal option

For color pallete
•More options for based on wallpaper colors.

For app drawer
•Custom app sections and folders
•Sesame shortcut search

For the home screen dock
•Resizable and customizable search bar
•Multiple pages

**Comment by rj10rd** [comment]
Great suggestion

**Comment by mikecharles** [comment]
Is there a reason the At a Glance widget doesn't feature all the suggestions that the Pixel Launcher version has (eg. events, reminders, alarms, etc.)?
