### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by xilegod026** [Deletescape-Media/Lawnchair#2606]
### Describe the bug

Make the At a Glance Widget size adjustable.  

### Steps to reproduce

No need.

### Expected behavior

With the home layout set to 10x10, the At A Glance widget seems tiny as compared to my other widgets, and it becomes kinda annoying to squeen (if that's not a word, it is now) my eyes to look at the weather. So please add a slider for it to be adjustable.

### Device information

- Device: Realme 8 5g
- OS: RealmeUI 3.0 based on Android version 12.0
- App version: 12.1 Dev 784

**Comment by xilegod026** [comment]
Uhhh......smol correction, it's lawnchair v12.1 dev 874

**Comment by SuperDragonXD** [comment]
You could simply disable the At A Glance from the home screen, and insert it manually:
https://user-images.githubusercontent.com/70206496/169168124-7c6512f5-6e3a-40fe-a371-02b9789bfd2b.mp4
