### ISSUE TITLE
Quickswitch not working on ONEUI 4.1

### ISSUE THREAD

**Issue by filipkamenski** [Deletescape-Media/Lawnchair#2609]
### Describe the bug

I'm on Rooted Galaxy a52s 5g with ONEUI 4.1. I updated Lawnchair from the latest 12 to 12.1 alpha 1. After the update finished I saw a message that my phone isn't on Android 12.1 and quickswitch can't use Lawnchair as recents provider.  

### Steps to reproduce

Update Lawnchair to 12.1 on oneui 4.1

### Expected behavior

I expect to be able to use quickswitch with Lawnchair on my device. If I understand correctly ONEUI 4.1 is Android 12.1. 

### Screenshots

![Screenshot_20220518-202513_QuickSwitch](https://user-images.githubusercontent.com/71707405/169104576-8f7374d6-de75-49f7-80d6-d8567b568e05.png)

### Device information

- Device: Samsung Galaxy A52s 5g
- OS: OneUi 4.1 may security update
- App version: Lawnchair 12.1 alpha 1;

**Comment by suphon-t** [comment]
This is intended (won't fix).

**Comment by filipkamenski** [comment]
That's ok. Can anybody explain to me why it is intended? Are you dropping support on other devices or is Android 12.1 not OneUI 4.1. Will things change in the future?

**Comment by suphon-t** [comment]
OneUI 4.1 is not Android 12.1. That's why it's not compatible.
