### ISSUE TITLE
Pinch gesture not working

### ISSUE THREAD

**Issue by Chaphasilor** [Deletescape-Media/Lawnchair#261]
I had the pinch for overview gesture enabled, but everytime I tried pinching on the homescreen, nothing happened. Depending on how exactly I swiped my fingers, it activated the other gestures like the notification shade, app drawer or Google feed.
I'm not sure what exactly this "overview" is, although I think it's the same as when you long-press on the homescreen...

**Comment by jise** [comment]
> I'm not sure what exactly this "overview" is, although I think it's the same as when you long-press on the homescreen...

Yes, it is. And it works as it should in the latest Lawnchair versions. So this issue could be closed I think,
