### ISSUE TITLE
Aurora store support

### ISSUE THREAD

**Issue by andsofine** [Deletescape-Media/Lawnchair#2616]
it would be nice if there was support for the Aurora store too (besides f-droid)

**Comment by NomadicDeveloper22** [comment]
Isn't Aurora store just the playstore? But a different client

**Comment by RikKoedoot** [comment]
It is

**Comment by msfjarvis** [comment]
There's nothing to do here for Lawnchair.

**Comment by andsofine** [comment]
> There's nothing to do here for Lawnchair.

why? I have ungoogled rom. and when i click "search for more apps" the launcher crashes. and it seems to me that the ability to select the application in which the search will be performed (F-droid client, or aurora store) would solve this problem

**Comment by msfjarvis** [comment]
> > There's nothing to do here for Lawnchair.
> 
> why? I have ungoogled rom. and when i click "search for more apps" the launcher crashes. and it seems to me that the ability to select the application in which the search will be performed (F-droid client, or aurora store) would solve this problem

Why is none of this in the body of your issue then? We're not going to dream up what you're exactly trying to report if you can't bother using the bug report template we've added for this specific reason.

**Comment by andsofine** [comment]
hell, I'm dumb, I thought that the pinned issue meant f-droid support inside app.

**Comment by andsofine** [comment]
> > > There's nothing to do here for Lawnchair.
> > 
> > 
> > why? I have ungoogled rom. and when i click "search for more apps" the launcher crashes. and it seems to me that the ability to select the application in which the search will be performed (F-droid client, or aurora store) would solve this problem
> 
> Why is none of this in the body of your issue then? We're not going to dream up what you're exactly trying to report if you can't bother using the bug report template we've added for this specific reason.

should i recreate the issue?
