### ISSUE TITLE
Visual bug when going home on the home screen.

### ISSUE THREAD

**Issue by ianmlunaq** [Deletescape-Media/Lawnchair#2617]
### Describe the bug

Visual bug when doing gesture to go home on the home screen. It _only_ seems to happen when using **gesture navigation** as opposed to the three button navigation.

### Steps to reproduce

1. Go to the home screen
2. Do the swipe up gesture to go home

### Expected behavior

https://user-images.githubusercontent.com/55558104/169427309-a6583399-a530-42d3-a772-85e6251ddecc.mp4

This is the expected behavior from the stock pixel launcher.

### Screenshots

https://user-images.githubusercontent.com/55558104/169427677-173d4726-b7bc-4121-979d-e1ef62bc132c.mp4

This is what happens when you do the same thing on Lawnchair.

### Device information

- Device: Google Pixel 5a
- OS: Stock Android 12
- App version: 12.1.0 Alpha 3

**Comment by DanGLVK** [comment]
> ### Describe the bug
> Visual bug when doing gesture to go home on the home screen. It _only_ seems to happen when using **gesture navigation** as opposed to the three button navigation.
> 
> ### Steps to reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to the home screen
> 2. Do the swipe up gesture to go home
> 
> ### Expected behavior
>  screen-20220519-104212.2.mp4 
> This is the expected behavior from the stock pixel launcher.
> 
> ### Screenshots
>  screen-20220519-103840.3.mp4 
> This is what happens when you do the same thing on Lawnchair.
> 
> ### Device information
> * Device: Google Pixel 5a
> * OS: Stock Android 12
> * App version: 12.1.0 Alpha 3
> 
> ### Additional context
> _No response_

Could you verify if this behavior occurs on other third party launchers?, using gestures on third party launchers has always been known for causing weird animations

**Comment by ianmlunaq** [comment]
Welp... it seems to be happening on all the other 3rd party launchers I could download.

**Comment by andsofine** [comment]
same

**Comment by suphon-t** [comment]
> same

To repeat what @DanGLES3 said: It's a normal thing when you use *any* third-party launchers, and there is no way to fix it unless you have root.
