### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by cyberlog69** [Deletescape-Media/Lawnchair#2618]
### Describe the bug

Dev Team,
Please add a clock on at a glance widget.

### Steps to reproduce

1. Go to 'Home Setting'
2. Click on 'At a Glance'

### Expected behavior

No time/clock on at a glance widget

### Screenshots

![Screenshot_2022-05-20-09-43-59-32_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/52593341/169449169-b2f2c4b7-1b6b-4846-993d-504f3120aef5.jpg)

### Device information

Realme Narzo 30A

**Comment by yasanglass** [comment]
This feature was added on #2650. Should be closed.
