### ISSUE TITLE
[Feature] Widget in App Drawer, Allow overlap, Lock layout

### ISSUE THREAD

**Issue by AustinLaurient** [Deletescape-Media/Lawnchair#2621]
### Describe the bug

Allow overlap is not available in the Lawnchair 12.1, and Lock layout does too

### Steps to reproduce

Null

### Expected behavior

Allow overlap and lock layout cameback, in a better way (got improved)

Widget can be place in app drawer (somehow makes it happened)

Also folder in app drawer too?

### Screenshots

Null

### Device information

Null

### Additional context

Null

**Comment by yasanglass** [comment]
Lock & overlap are now implemented. Widget support for App Drawer is not planned.
