### ISSUE TITLE
[Feature Request] Swipeable/MultiplePages in Dock

### ISSUE THREAD

**Issue by AlbiDR** [Deletescape-Media/Lawnchair#2623]
### Describe the bug

Dear Dev, 
As the first releases for A12 are out and as Lawnchair keeps on improving and improving with every update, I find myself unable to switch to this launcher because of a simple missing feature: the ability to increase the number of pages the Dock has ("swipeable" horizontally). This feature exists on Nova and is extremely useful for increasing the productivity of your homescreen without sacrificing screen estate or needing a whole new homescreen page.

This feature has been discussed for many years and many claim that it would be a great addition.
https://www.reddit.com/r/LawnchairLauncher/comments/d6wn2t/dock_any_way_to_have_multiple_swipeable_pages/

It was even issued on GitHub more than once in the past:
https://github.com/LawnchairLauncher/lawnchair/issues/562
https://github.com/LawnchairLauncher/Lawnchair/issues/636
https://github.com/LawnchairLauncher/Lawnchair/issues/1306

### Steps to reproduce

After enabling this from the settings, the user can set the number of pages the dock has.

### Expected behavior

From the homescreen, the user can horizontally scroll on the dock (as it would for scrolling through homescreen pages) and show a secondary set of apps. This secondary set will be/have the same exact features as the primary one (just like different homescreen pages would).

### Screenshots

https://user-images.githubusercontent.com/97815338/169548614-8bbf38d0-5745-4a4d-bdd2-182ec3fa7a55.mp4

### Device information

- Device: any
- OS: any
- App version: latest

### Additional context

As I mentioned above, this feature has been requested in the past and mentioned on some blog posts such as reddit, some of the commenters pointed out (just like me) that this is the only feature holding them from abandoning NovaLauncher and get on the much better Lawnchair. 

note: I truly would like to switch but I strongly rely on this feature.

**Comment by ArchinDeepakTV** [comment]
I would also like some haptic feedback on things. Like dock swiping gives haptic feedback. Notification scrolling gives haptic feedback. And the at a glance widget scrolling gives haptic feedback. That would be really nice

**Comment by BHUSHAN7988** [comment]
Please take a look at this feature it will make lawnchair so much better and with quick switch it's goona be much better then any launcher

**Comment by AlbiDR** [comment]
@BHUSHAN7988 Yes! This feature would be the absolute killer - I'm positive it would get many diehard NovaLauncher users actually change to the better Lawnchair.
Multiple pages on dock AND hidden folders behind apps' icons (like in the video I posted) that are accessible through a swipe up gesture. These two feature are absolutely fundamental

**Comment by HoreaM** [comment]
I would really love to have this feature too! And the haptic feedback suggestion would make it perfect imo.

**Comment by AlbiDR** [comment]
@ArchinDeepakTV haptic feedback would be nice in my opinion but only IF the settings would allow to choose the intensity of the vibration - if it defaulted to system settings I would not use the feature and disable it. But an extremely gentle vibration could be very nice.

**Comment by ArchinDeepakTV** [comment]
Is there any way for you guys to stack widgets like in iOS? That would be a killer feature

**Comment by AlbiDR** [comment]
@ArchinDeepakTV I'm not sure how these features you mention relate with my initial suggestion but sure i guess, that would be a cool feature. You might be able to achieve that through KWGT

**Comment by ArchinDeepakTV** [comment]
Widget stack means there will be widgets one on top of another and they will be swipeable

**Comment by AlbiDR** [comment]
@ArchinDeepakTV i guess i see your point. That's a really good feature on its own but it might be necessary for apps themselves to make stackable widgets and not only the launcher

**Comment by topsy-turvy99** [comment]
I requested some dock related features #2775 (Point No 7), this feature is also included just referencing it as you added a video demonstration of it.

**Comment by AlbiDR** [comment]
Has the development gone a bit stale? I wonder what are the chances for this little feature to actually be implemented. It would be so little but yet so effective (and it would kill a chunk of the competition, since it would allow people like me to actually switch to Lawnchair completely)
