### ISSUE TITLE
[FEATURE REQUEST] Swipe down to search 

### ISSUE THREAD

**Issue by gerardovasquez307** [Deletescape-Media/Lawnchair#2625]
I use nova launcher primarily to be able to customize the swipe down gesture and incorporate it with sesame search. A feature to toggle swipe down to search would be great, however with time a gesture customization option would be awesome. The implementation of this has already been done for swipe up to open app drawer and open search is already there, but muscle memory always makes accidental swipe down to toggle notification bar as this behavior is present in many default launchers.

**Comment by SuperDragonXD** [comment]
Swipe down to open App Search has been implemented in Lawnchair 12.1 Alpha 4, alongside gesture customization. Closing this issue.
