### ISSUE TITLE
Flickering of home screen icons when navbar is tapped (Lawnchair recents via Quickswitch)

### ISSUE THREAD

**Issue by AnonRS3** [Deletescape-Media/Lawnchair#2627]
### Describe the bug

In the latest version of Lawnchair using QuickSwitch on Android 12, a visual bug / flickering occurs when the gesture navigation bar is tapped. This happens often when the user taps elements close to the gesture navigation bar. The home screen flickers briefly on screen, then disappears. 

### Steps to reproduce

1. Tap near/on the gesture bar. 
2. Flickering of home screen occasionally happens 

### Expected behavior

Tapping near or on the gesture navigation bar shouldn't cause this visual flickering. It becomes especially annoying and prevalent when using apps with tap-able elements on the lower portion of the screen. 

### Screenshots

Below I am tapping on and around the navbar:

https://user-images.githubusercontent.com/54009117/169640258-199cf680-a17f-4445-96d9-5881f1361795.mp4

### Device information

- Device: Google Pixel 4
- OS: CalyxOS 3.5.0 (Android 12)
- App version: Lawnchair 12.1.0 Alpha 3 with QuickSwitch

**Comment by MarissaRS** [comment]
Issue fixed itself in CalyxOS 5.3.1

**Comment by AnonRS3** [comment]
Issue fixed itself in CalyxOS 3.5.1
