### ISSUE TITLE
Lawnfeed occasionally doesn't work 

### ISSUE THREAD

**Issue by DJRCX** [Deletescape-Media/Lawnchair#2630]
Occasionally, swiping from left to right.... Google feed doesn't show up. Mostly happens when the device is offline

**Comment by SuperDragonXD** [comment]
Late reply, but already answered in the FAQ page since this is a common issue: https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#lawnfeed-does-not-work. Also your device being offline likely contributes for Google Discover disappearing. Closing this issue.
