### ISSUE TITLE
Themed icon won't change color after wallpaper changed

### ISSUE THREAD

**Issue by alexchiu100014** [Deletescape-Media/Lawnchair#2631]
### Describe the bug

Lawnchair should get Accent color (or themed icon color) from the wallpaper,but this feature is broken in 12.1 alpha 3
(It worked on 12.0 alpha 5)

### Steps to reproduce

1.Open home Settings
2.Select General->Colors->Accent Color
3.Select Wallpaper under Dynamic
4.And nothing changed
(Accent color should change depend on my wallpaper color)

### Expected behavior

It should follow my wallpaper color,but it stuck on blue
(Not Google blue)

### Screenshots

12.1 Alpha 3
![Screenshot_2022-05-21-16-28-12-95_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/48598830/169663743-7d98d211-59e6-4107-b337-3898839ed0ce.jpg)
![Screenshot_2022-05-22-01-59-08-31_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/48598830/169663785-a8a49dde-afb8-45e1-8987-abb413365472.jpg)
12 Alpha 5
![Screenshot_2022-05-21-16-29-23-33_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/48598830/169663801-3f23882b-6c45-4ceb-83a2-e105b3fcb772.jpg)

### Device information

- Device: Realme GT Master Edition (RMX3363)
- OS: Android 12 with ColorOS 12
- App version 12.1 Alpha 3
- I think this problem is not caused by my device,because in 12 Alpha 5 ,this feature work properly.

**Comment by RikKoedoot** [comment]
are those icons from a lawnicons fork? or are they from an iconpack?

**Comment by alexchiu100014** [comment]
> are those icons from a lawnicons fork? or are they from an iconpack?
> 

I use a fork called cayicons

**Comment by alexchiu100014** [comment]
It turns out that my Lawnchair have self-repaired.
I was using my phone,and all of a sudden,themed icon color changed.

**Comment by dr460nf1r3** [comment]
Still having the issue on the latest debug apk at the time of writing using Ondynamic Material You icon pack from the Play Store. Applying a new Color via Repainter.

**Comment by RikKoedoot** [comment]
These iconpacks are using workarounds and are not really themed icons, if you want to have actual themed icons that update when you change wallpaper use the lawnicons addon

**Comment by dr460nf1r3** [comment]
I see, also found another open issue which corresponds to this problem. https://github.com/LawnchairLauncher/lawnchair/issues/2573
