### ISSUE TITLE
[Feature Request] Make "At a Glance" Size Adjustable.

### ISSUE THREAD

**Issue by Genos666** [Deletescape-Media/Lawnchair#2634]
Please add a size slider for "At a Glance" so that the users can change its size.

Currently the size depends on the "Home Screen Grid", if we uses a 10x10 grid, then the "At a Glance" widget becomes so small.

So please make it's size adjustable if possible.

**Comment by suphon-t** [comment]
Disable At a Glance in settings, and drag it from the widgets picker instead. That way you can place it anywhere and adjust its size.
