### ISSUE TITLE
[BUG] Battery status in 'at a glance'

### ISSUE THREAD

**Issue by rj10rd** [Deletescape-Media/Lawnchair#2635]
### Describe the bug

Doesn't show battery status in at a glance when connected to Bluetooth earbuds.
![Screenshot_20220523-003535_Lawnchair](https://user-images.githubusercontent.com/43381912/169711680-dffc6c66-2f1d-44b6-a50a-8f46fec4c62d.png)
![Screenshot_20220523-003533_Lawnchair](https://user-images.githubusercontent.com/43381912/169711682-927b1c8f-bd74-4f0b-80f5-1e2c9564f30e.png)

### Steps to reproduce

Turn on at a glance and connect to Bluetooth earbuds,it will show day and date at place of battery status

### Expected behavior

Batter status should be shown when connected to Bluetooth earbuds

### Device information

- Device: Poco X2
- OS: EvoX android 12.1
- App version : 12.1.0 dev (928)

**Comment by yasanglass** [comment]
This is not a bug. Even the device's battery is not shown on Glance when it's discharging & not low. Although this sounds like a cool feature to be added later on.
