### ISSUE TITLE
[Feature Request] Summary

### ISSUE THREAD

**Issue by StudioDribDrab** [Deletescape-Media/Lawnchair#2638]
One of the biggest things I love about Niagara launcher is the Notification summary, 
If lawnchair could introduce a similar feature with there awesome android design style something like IOS notification summary
Would absolutely love it! 👍👍

**Comment by yasanglass** [comment]
@RoguePug Can you provide some screenshots of the feature?

**Comment by StudioDribDrab** [comment]
> @RoguePug Can you provide some screenshots of the feature?

![Screenshot_20220523-183935.png](https://user-images.githubusercontent.com/87250159/169779503-e33b5685-8c16-4b9c-afa2-3705b413fdcd.png)

**Comment by StudioDribDrab** [comment]
> @RoguePug Can you provide some screenshots of the feature?

Sorry I can't supply a screenshot of my summary since I only get it every Morning,
