### ISSUE TITLE
[REQUEST] Android O Pixel Launcher navigation bar/buttons in app drawer

### ISSUE THREAD

**Issue by impossibru-is-nothing** [Deletescape-Media/Lawnchair#264]
Just wondering if you were able to use the Android O style nav bar/buttons when expanded, as opposed to what's showing up in the app drawer currently? The Android O Pixel Launcher nav bar/buttons look more cleaner and aesthetic in my opinion, and match the overall UI of the status bar when expanded as well. I'm sure people know what I'm talking about, but if not, I've attached a photo to show what I mean:

![nav buttons](https://user-images.githubusercontent.com/30331068/28460871-a577c7fa-6e46-11e7-9141-4b1fc1b85ac1.png)

**Comment by rvictorr** [comment]
IIRC that's a part of a new API introduced in O, so it's not possible on API < 26

**Comment by ricknout** [comment]
Yup, see here:
https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR

**Comment by RWOne** [comment]
Related, can the shaded area of the nav bar be darkened slightly more when the app drawer is expanded?

Not an issue if a dark theme is used, but IMHO against a light background, just a touch more to bring it out, right now it is transparant and the icons look washed out against the rest of the white background in the drawer.

An example would be to scroll the drawer down and see the grey color of the bounce animation versus what the nav bar background is now.

**Comment by suphon-t** [comment]
Already implemented for O and above.
