### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2642]
Make clear all option in recents as  a button like in pixel launcher/trebuchet launcher in Android 12.1
![Screenshot_20220524-082211_Lawnchair~2](https://user-images.githubusercontent.com/104545685/169939402-79ef3dbd-a5a7-4273-a895-1ae2db9571a2.png)

**Comment by RikKoedoot** [comment]
Already there

**Comment by ghost** [comment]
> Already there

Not a12.1 style

![Screenshot_20220524-202017_Pixel Launcher~2](https://user-images.githubusercontent.com/104545685/170065849-53dfbba4-93f4-475a-a082-a4ec253fcb23.png)
That type of clear all button present in pixel launcher and trebuchet launcher

**Comment by msfjarvis** [comment]
Making everything identical to Pixel Launcher is not necessarily an improvement.

**Comment by ghost** [comment]
> Making everything identical to Pixel Launcher is not necessarily an improvement.

But default lineage os launcher also has this type of clear all button 
It looks good compared previous a12 one thats why saying 🙂
I hope you will understand btw latest lawnchair is very good 🤩

**Comment by SuperDragonXD** [comment]
1. Rename the issue title to "Change the "Clear all button" at the left side of the overview to the filled style"
2. Has been implemented: [https://github.com/LawnchairLauncher/lawnchair/commit/8dc2da4249ffcf9ae762f5392f11e3f9cf676433](commit `8dc2da4`)
