### ISSUE TITLE
[BUG] Unable to give the app notification access

### ISSUE THREAD

**Issue by Graydenn** [Deletescape-Media/Lawnchair#2646]
### Describe the bug

When I follow through the prompts to enable notification access (specifically for the At a Glance widget), I get to the phone's notification access screen. After trying to enable access, the alert in my screenshot appears.

Looking on the Android 13 Beta page it seems like they changed how some privacy/security features work, thus me thinking it's an app problem.

### Steps to reproduce

1. Tap the "Tap to Set Up" widget when first enabling the At a Glance widget
2. Tap "Change Settings" on the notification access alert that pops up
3. Tap "Notification Dots"
4. Tap "Change Settings" on the popup
5. After being taken to the Settings app, choose Lawnchair from the list 
6. Attempt to toggle the "Allow notification access" switch

### Expected behavior

I'd expect to be able to give the app notification access.

### Screenshots

![Screenshot_20220524-064528](https://user-images.githubusercontent.com/42272058/170017648-70a7061c-78bb-4b71-aced-d8a2f09110c2.png)

### Device information

- Device: Pixel 6 Pro
- OS: Android 13 Beta 2
- App version: 12.1.0 Dev (930)

**Comment by Graydenn** [comment]
Alright, so I've discovered [an article](https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/) explaining how to solve this.

1. Go to the Lawnchair app page in the main apps menu.
2. Tap the three dots menu in the top right of your screen.
3. Tap "Allow restricted settings" and authenticate.
4. Go back through the Lawnchair prompts and you should be able to enable the setting.

Gonna close this now but I hope this'll help someone in the future.

**Comment by UAVXP** [comment]
I have the same issue, and I cannot find "Allow restricted settings" nor 3 dots in the app settings

**Comment by sp6691151-source** [comment]
STYLE
