### ISSUE TITLE
third-party app stores to search through them

### ISSUE THREAD

**Issue by andsofine** [Deletescape-Media/Lawnchair#2648]
I have ungoogled rom. and when i click "search for more apps" the launcher crashes. and it seems to me that the ability to select the application in which the search will be performed (F-droid client, or aurora store) would solve this problem
it would also be nice if, in the absence of Google Play, the launcher automatically uses (if available) one of the installed app stores

**Comment by yasanglass** [comment]
I dont have any issues launching F-Droid from the search. It even shows the F-Droid icon for me. I tested on the latest 12.1 commit.

![Screenshot_20220612_141715](https://user-images.githubusercontent.com/41836211/173227494-574a2ae0-58bf-4c7a-b006-a8eabdf8a143.png)
