### ISSUE TITLE
Request - darken nav bar background in 7.1.1

### ISSUE THREAD

**Issue by RWOne** [Deletescape-Media/Lawnchair#265]
Can the nav bar background be darkened slightly?

On transparent and light background, it is nearly invisible in the app drawer, justa  shade darker would add contrast to the area with the nav bar icons ...

I know it has been implemented for O, but for 7.1.1 ?

**Comment by suphon-t** [comment]
As I said in #264, this is fixed in bb80c8f

**Comment by matteocontrini** [comment]
What about having a transparent navigation bar? Nova already has it
