### ISSUE TITLE
[BUG] Recent Apps doesn't show consistently last app as first to show

### ISSUE THREAD

**Issue by jucasagr** [Deletescape-Media/Lawnchair#2652]
### Describe the bug

When using "swipe left" to leave an app to enter another one, and later using "swipe up" to enter in "recent apps", there is an issue where the "recent apps" list goes all the way left, not to the last app you minimize.

### Steps to reproduce

Open App
Swipe left to minimize
Open another App
Swipe left again to minimize
Swipe up to open recent apps
The list will go all the way to the left

### Expected behavior

Show last app (most recent)

### Screenshots

https://user-images.githubusercontent.com/105809355/170331766-1ac73c1a-85d2-42c9-95b7-fe9e5aed0629.mp4

### Device information

- OnePlus 6
- Evolution X ROM Android version 12.1]
- 12.1.0 Alpha 3

**Comment by suphon-t** [comment]
This is a Pixel Launcher bug. Unrelated to Lawnchair.
