### ISSUE TITLE
[BUG] Black Accent color is showing as blue 

### ISSUE THREAD

**Issue by awasay905** [Deletescape-Media/Lawnchair#2655]
Starting from 12.1 alpha 1 the accent color from black wallpapers is being shown as blueish. You can see in screenshot of lawnchair 12.1 (above) and 12(below) using same wallpaper. 

![Screenshot_20220526-010826_Lawnchair~2](https://user-images.githubusercontent.com/55891247/170571573-56e3c385-999c-4d4d-87a3-231e0c16c77c.png)
![Screenshot_20220526-010750_Lawnchair~2](https://user-images.githubusercontent.com/55891247/170571590-065727d6-4909-4adf-bbed-d6ec225842fb.png)

**Comment by suphon-t** [comment]
In 12.1 we switched to Google's palette generator. This is a normal behavior of the generator.

**Comment by debritde** [comment]
Can we please stop this useless and crappy Google Color Chooser thing?
When i choose black (#000000) as my color, i want BLACK (#000000) as my color and not blue because Google calculated it.
That is the most stupid bullshit i ever saw in design programmations and it has absolutely no advantage

**Comment by debritde** [comment]
> In 12.1 we switched to Google's palette generator. This is a normal behavior of the generator.

stop it. nobody wnats it and it prevents everyone to choose a simple amoled black color design.
It is just useless bullshit.
I wanna choose what 9 get and not choose something and google choose what i really get. Dafaq!?
