### ISSUE TITLE
[BUG] Themed icons powered by Lawnicons do not update in One UI 4.1

### ISSUE THREAD

**Issue by pratyakshm** [Deletescape-Media/Lawnchair#2656]
### Describe the bug

Whenever I change the color palette in my phone, themed icons do not update the colors and still show colors from an older color palette.

### Steps to reproduce

1. Update your device's wallpaper.
2. Set a color pallette of your choice from **Android Settings > Wallpaper and style**.
3. Colors of app icons on the homescreen are not consistent with the chosen color palette.

### Expected behavior

Changes to Color palette are reflected in Lawnchair's app icons on the home screen.

### Device information

- Device: Samsung Galaxy M31s (SM-M317F)
- OS: One UI Core 4.1 based on Android 12
- App version: 12.1.0 Alpha 3

### Additional context

A workaround of this issue is available. 
1. Go to Lawnchair's app info in Android Settings.
2. Clear cache and force stop Lawnchair
3. Revisit Lawnchair homescreen
4. App icon colors are refreshed and now follow the color palette.

Bug Frequency: All the time

**Comment by RikKoedoot** [comment]
What app is providing themed icons?

**Comment by pratyakshm** [comment]
@RikKoedoot it's Lawnicons. Got the APK file from https://t.me/lawnchairci/1549.

**Comment by RikKoedoot** [comment]
Thanks, could you include that in the title of the issue?

**Comment by pratyakshm** [comment]
Done @RikKoedoot!

**Comment by Blank-Slate7** [comment]
I can confirm this is an issue, it only changes if you force stop the lawnchair app

**Comment by Blank-Slate7** [comment]
themed icons work well for me? I'm using a Samsung galaxy note 10 + running one ui 4.1 and when I change the theme colour it changes

**Comment by Blank-Slate7** [comment]
I don't know what the underlying issue is but it's definitely not consistent
