### ISSUE TITLE
[BUG] At a glance font issue 

### ISSUE THREAD

**Issue by exkpwn** [Deletescape-Media/Lawnchair#2658]
### Describe the bug

The new at a glance widget doesn't follow system fonts
Neither the font selections from the lawnchair app

It's always "inter" no matter what

### Steps to reproduce

General - fonts- select anything/sans-serrif or add ttf nothing works

### Expected behavior

Should follow system fonts or anything selected 

### Device information

- Device: Raphael
- OS: 12.1
- App version 12.1 Alpha 3

**Comment by SuperDragonXD** [comment]
See #2594. It may be added in the future, just not now.
