### ISSUE TITLE
Lawnchair v.1.2.1 vs 12.1 - how to get the same feeling and interactions?

### ISSUE THREAD

**Issue by moshpirit** [Deletescape-Media/Lawnchair#2661]
I've been using Lawnchair for many years and I recently discovered that beyond the F-droid version (1.2.1) the development continues. So I went to the official Telegram channel and downloaded the last apk.

The problem is that it feels like it's a zoomed out version of the 1.2.1. How can I get the widgets and icons to use better the space of the screen? I leave some [screenshots here](https://imgur.com/a/j5IFjFJ) to make it clearer.

I also noticed that I can no longer change the icons one by one, just use a whole different package for all icons.

And the 2 requests that I wanted to ask for are not developed yet: using dual apps as separate apps and being able to have a feed without depending on Google (as you guys are implementing, which I imagine it's going to be fantastic, but I won't enjoy because I prefer not to use Gapps). 

I imagine that the last version is much better than the one I'm using, but I'd like to keep having the same interactions.

**Comment by RikKoedoot** [comment]
The sidepadding is a change done by google. There is no way of changing the side padding as of now. You can still edit app icons one by one.

**Comment by moshpirit** [comment]
I see, but then, why isn't a change that I can see on v. 1.2.1? In which version did this start happening (approx)?

>You can still edit app icons one by one.

Hmm, OK, I'll keep searching

**Comment by RikKoedoot** [comment]
It started with v11
