### ISSUE TITLE
[BUG] Icon's not reloading after day/night theme change

### ISSUE THREAD

**Issue by Ziadhussain** [Deletescape-Media/Lawnchair#2667]
### Describe the bug

The icons themed by an external icon pack app like "pix material you icon pack " doesn't change its color automatically (light to dark or dark to lite ) while the themed icons by lonicons do that automatically when turning the system dark mode on /off

### Steps to reproduce

1.apply pix material you icon pack ( and toggle the option of lonicons themed icons on ) too
 2. Turn on dark mode (system) 
 3. Head to the homepage and you'll notice that the icons themed by the icon pack didn't change color from light to dark while lonicons icons did automatically
 4. Force restart the launcher and you 'll see it changed color to dark

### Expected behavior

I expected the themed icons by external icon pack to change theme automatically (dark to light and light to dark ) like lonicons icons themed

### Screenshots

![Screenshot_2022-05-30-02-36-17-58_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/105359583/170898720-509a3d57-2a78-4864-8d1e-57537285aaa7.jpg)
![Uploading Screenshot_2022-05-30-02-36-49-91_67d7f8591eff9881972c1169b8bca2d8.jpg…]()

### Device information

- Device:  Oppo Realme 8 4G (RMX3085) With android 12.
- OS: Realme UI 3.0 based on android 12 (by oppo realme corp.
- App version : lawnchair 12.1 alpha 3

**Comment by arpanadlakhiya** [comment]
Second this, I am also facing this issue where in the icon pack needs to be re-applied in order to change from light to dark theme or vice versa
