### ISSUE TITLE
[BUG] Shortcuts sometimes get wiped

### ISSUE THREAD

**Issue by DUOLabs333** [Deletescape-Media/Lawnchair#2673]
### Describe the bug

Sometimes, the shortcuts on the home page gets wiped

### Steps to reproduce

Not sure how it happens (can't reproduce reliably).

### Expected behavior

For the shortcuts not  to get wiped intermittently.

### Device information

- Device: [e.g. Google Pixel 6] Google Pixel 6
- OS: [e.g. stock ROM Android version 12.0] Android 12
- App version [e.g. 12.0.0 Alpha 5] 12.1.0 Alpha 3

### Additional context

This sometimes happen on Google's official Launcher (which ironically why I switched to this one).

**Comment by SuperDragonXD** [comment]
Wdym by "wiped"? Also, could you send a screenshot?

**Comment by DUOLabs333** [comment]
I already restored it, but it's just my home screen without my shortcuts.

**Comment by SuperDragonXD** [comment]
Oh I got confused on "shortcuts", I thought you meant the app shortcuts instead of the app icons in the home screen.

Well, you could always back up your home screen on Lawnchair

**Comment by DUOLabs333** [comment]
No, I did mean app shortcuts.

**Comment by DUOLabs333** [comment]
Also, backing up causes Lawnchair to crash (with `java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps` --- but that's another issue).

**Comment by DUOLabs333** [comment]
Comment

**Comment by SuperDragonXD** [comment]
Have you tried updating to the latest version? Also, iirc shortcuts get wiped or unclickable because Lawnchair isn't set as the default launcher.

**Comment by DUOLabs333** [comment]
I have, and I do. To be fair, this has only happened once before, so it's hard to reproduce it.

**Comment by DUOLabs333** [comment]
It happened again.

**Comment by SuperDragonXD** [comment]
Did you have a prompt to change the default launcher or no?

**Comment by DUOLabs333** [comment]
No, it sticks with Lawnchair as my launcher.

**Comment by DUOLabs333** [comment]
After it happened a few more times, I realized that not all shortcuts get wiped --- only those in a group.
