### ISSUE TITLE
Feature request: replace Google Feed with any shortcut.

### ISSUE THREAD

**Issue by Degl1** [Deletescape-Media/Lawnchair#2681]
I'd like to replace the Google Feed shortcut with any app or action I'd like without the need for DiscoverKiller. Because I don't have the Velvet app installed but I'd like to use that gesture without Google Velvet.

**Comment by usergitty** [comment]
This would be nice especially for degoogled users. Maybe even a custom made feed? " Lawn Now" for v13 :)
