### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by PatrzKomuUfaszGb** [Deletescape-Media/Lawnchair#2682]
### Describe the bug

can you add option in recent apps for lock app? Thank you 😃

### Steps to reproduce

No errors

### Expected behavior

Will be bloc app. Wil be not possible clear that one app what will be blocked 

### Screenshots

No screen shot

### Device information

- Device: OnePlus 8 
- OS: crDroid Android version 12.1
- App version  12 .1.0 Alpha  3

**Comment by RikKoedoot** [comment]
Closing, same as #2034
