### ISSUE TITLE
Auto update calender icon

### ISSUE THREAD

**Issue by YAJATapps** [Deletescape-Media/Lawnchair#269]
when the day has changed the calender date does not changes. i have to reset the icon pack or rebuild icon pack database to change to current date.

**Comment by p0nkr4t** [comment]
Did you enable "Use rounded Icons" option?

**Comment by YAJATapps** [comment]
No

**Comment by nyancrimew** [comment]
It properly works (atleast for iconpacks) since a few versions

**Comment by YAJATapps** [comment]
Now it is working when I updated to latest version.
