### ISSUE TITLE
[Feature Request] Copy from Recents View 

### ISSUE THREAD

**Issue by Genos666** [Deletescape-Media/Lawnchair#2691]
Please add the ability to copy text and image from the recents view, just like in pixel launcher.

**Comment by RikKoedoot** [comment]
Not possible, it's a pixel exclusive feature. If you install the Google lens app you'll get a Google lens button in recents with almost the same functionality

**Comment by Genos666** [comment]
> Not possible, it's a pixel exclusive feature. If you install the Google lens app you'll get a Google lens button in recents with almost the same functionality

k thanks
