### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dpenchuk** [Deletescape-Media/Lawnchair#2692]
### Describe the bug

Lawnchair crashed... Why?  For the second time in a week...

### Expected behavior

Solve the problem....

### Screenshots

![Screenshot_20220608-083452468 (1)](https://user-images.githubusercontent.com/107097868/172541713-87045836-ae71-435d-bcbc-e010a5c50789.jpg)

### Device information

- Device: [e.g. Xiaomi Redmi Note 8]
- OS: [e.g. ResurrectionRemix Android version 10]
- App version [e.g. 10 Alpha 8]

**Comment by RikKoedoot** [comment]
Closed due to v10 not being supported, and the lack of crash logs
