### ISSUE TITLE
Remove shadow on icons

### ISSUE THREAD

**Issue by keyjeyelpi** [Deletescape-Media/Lawnchair#2695]
So, I'm using a combination of lawnicons and pix material you, and I noticed that there were shadows on the pix material you, but not on lawnicons. At first I thought it was a pix material you problem, but when I tried the stock icons, the shadows were still there. Please add an option to remove the shadow from icons.

TL;DR Add option to remove shadow on icons since lawnicons don't have shadows.

**Comment by yasanglass** [comment]
Closing as its a duplicate of #2800
