### ISSUE TITLE
[BUG] At a glance RTL issues

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2698]
### Describe the bug

When using RTL, the alignment is not correct. The date is still left aligned 

### Steps to reproduce

1. Enable RTL
2. See the at a glance widget 

### Expected behavior

Both the date and weather should be right aligned 

### Screenshots

![Screenshot_20220609-095217_Lawnchair](https://user-images.githubusercontent.com/29402532/172795149-63786434-8527-45d8-8c94-7824b12fe419.png)
![Screenshot_20220609-095220_Lawnchair](https://user-images.githubusercontent.com/29402532/172795720-4b7b03ab-1721-4252-906e-958b71a83409.png)

### Device information

- Device: OnePlus 7
- OS: KOSP Android 12.1
- App version: 12.1.0 Dev (#958)

**Comment by yasanglass** [comment]
Just created a PR that fixes this but I found another issue:

I can NOT swipe to the other Glance tab and all my attempts just open Google Feed or swipe to the next page on Home. The swipe can be easily done when the language is English (and probably on the rest of LTR languages). After several attempts, I was not able to swipe to the second page of Glance even once.

**Comment by RikKoedoot** [comment]
That issue seems to only be caused when using the smartspace. I do not have it when I place at a glance as a widget
