### ISSUE TITLE
[BUG] Crash when adding widgets

### ISSUE THREAD

**Issue by Scramzi** [Deletescape-Media/Lawnchair#2699]
### Describe the bug

When i want to put a widget about samsung weather, another widget, calendar, the launcher crash, as you can see in the video samsung health widget work fine BUT

when i remove the widget which works fine like the health widget and put it again in the same place it crashes, the same problem happens with all widgets

### Steps to reproduce

1. Go to home screen and keep press until menu appears
2. Click on Widgets
3. Scroll down to your widget
4. Drag the widget into the home screen and add widget
5. See error

### Expected behavior

to work fine

### Screenshots

https://user-images.githubusercontent.com/107284378/173168163-02cd4101-32ba-4b31-89fc-5805c46b45ea.mp4

https://user-images.githubusercontent.com/107284378/173168407-efa39b86-8b7b-4b77-9994-3d020ddd8cc8.mp4

[Lawnchair bug report Jun 10, 2022 232901.txt](https://github.com/LawnchairLauncher/lawnchair/files/8882972/Lawnchair.bug.report.Jun.10.2022.232901.txt)
[Lawnchair bug report Jun 10, 2022 233541.txt](https://github.com/LawnchairLauncher/lawnchair/files/8882986/Lawnchair.bug.report.Jun.10.2022.233541.txt)

### Device information

- Device: [Samsung Galaxy S9 G960U1]
- OS: [Android 10 One UI 2.5]
- App version [12.1.0 Alpha 3]

### Additional context

sorry for bad english its my first time submitting an issue i hope everything is well explained and videos to work fine.
i used another widget and samsung weather app as example, the first .txt file is another widget crash and the second .txt file is samsung weather crash

**Comment by SuperDragonXD** [comment]
https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#adding-widgets-crashes-lawnchair

Might want to make a compilation of all these widget crashing issues

**Comment by Scramzi** [comment]
> https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#adding-widgets-crashes-lawnchair
> 
> Might want to make a compilation of all these widget crashing issues

i believe it happens only in my device, tried the same 12.1.0 launcher and widgets works fine at Galaxy A10s

**Comment by qamarq** [comment]
This happens in the case of all widgets that have to choose their parameters, e.g. the appearance of your weather or selecting a Google account in keep notes. Adding such widgets works if Lawnchair 12 is not set as the main one in the system. You can change to the basic phone launcher, open Lawnchair, add a widget and again set Lawnchair as the main launcher

**Comment by SleepDaemon** [comment]
I also have this issues, the app is Geometric Weather

[Lawnchair bug report Jun 23, 2022 10_38_19 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/8965262/Lawnchair.bug.report.Jun.23.2022.10_38_19.AM.txt)

Phone: Samsung S22+ (256gb) (Qualcom Chip Variant)
OS: Latest OneUI
Lawnchair Version: 12.1 Alpha 3

```
Lawnchair bug report Jun 23, 2022 10:38:19 AM
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: g0q
build.display: SP1A.210812.016.S906EXXU2AVF1
build.fingerprint: samsung/g0qxxx/g0q:12/SP1A.210812.016/S906EXXU2AVF1:user/release-keys
build.hardware: qcom
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-S906E
build.product: g0qxxx
build.type: user
version.codename: REL
version.incremental: S906EXXU2AVF1
version.release: 12
version.sdk_int: 31
display.density_dpi: 450
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by SleepDaemon** [comment]
> This happens in the case of all widgets that have to choose their parameters, e.g. the appearance of your weather or selecting a Google account in keep notes. Adding such widgets works if Lawnchair 12 is not set as the main one in the system. You can change to the basic phone launcher, open Lawnchair, add a widget and again set Lawnchair as the main launcher

ill do this, but i hope they fix this by stable release

**Comment by Scramzi** [comment]
> 

i tried it, keeps crashing even if lawnchair is not set as the default launcher

**Comment by Scramzi** [comment]
> This happens in the case of all widgets that have to choose their parameters, e.g. the appearance of your weather or selecting a Google account in keep notes. Adding such widgets works if Lawnchair 12 is not set as the main one in the system. You can change to the basic phone launcher, open Lawnchair, add a widget and again set Lawnchair as the main launcher

i tried it, keeps crashing even if lawnchair is not set as the default launcher

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with this  specific error) are being tracked on #2820. Closing this issue.

**Comment by Kuphi** [comment]
> This happens in the case of all widgets that have to choose their parameters, e.g. the appearance of your weather or selecting a Google account in keep notes. Adding such widgets works if Lawnchair 12 is not set as the main one in the system. You can change to the basic phone launcher, open Lawnchair, add a widget and again set Lawnchair as the main launcher

Thanks! This workaround still works! Just wasted 3 hours with various weather widget apps. Nothing worked before I found this workaround.

Can devs fix this in the next release?
