### ISSUE TITLE
Adding website shortcuts from browser

### ISSUE THREAD

**Issue by lpen21** [Deletescape-Media/Lawnchair#270]
After adding website shortcut to home screen pressing shortcut icon does not link to websites.
And nothin happens. Was working fine build 828

**Comment by RWOne** [comment]
More info needed, latest build is 818.

Stock N6, 7.1.1, on 818, can't duplicate using chrome. Shortcuts added to screen and when used opens fine.

**Comment by lpen21** [comment]
Works fine on version 818, problem became evident build 832. I m using Moto g 4+ 7.0 stock.

**Comment by Younes-L** [comment]
Hi, 
Using 832 and 836, I encounter the same issue with X-plore shortcuts, when I tap on a shortcut nothing happens.

OnePlus One A0001/Bacon, running Slim7 Dev-DM Beta 0.27 (AOSP+CAF), 7.1.2

Lawnchair is set as default

**Comment by suphon-t** [comment]
Fixed with 896b5b1

**Comment by lpen21** [comment]
Awesome, thanks for quick fix
