### ISSUE TITLE
(Suggestion) Auto-reapply icons when changing wallpaper/mode

### ISSUE THREAD

**Issue by keyjeyelpi** [Deletescape-Media/Lawnchair#2701]
Please add a functionality to auto-reapply icons when changing wallpapers or from light to dark mode and vice versa. It'll be helpful for apps that have material you such as pix icon pack.

PS, also add uniformity on lawnicons and icon packs. I've noticed that lawnicons are shadowless whereas icons have shadow.

**Comment by arpanadlakhiya** [comment]
Second this suggestion, this works in Hyperion and Niagara launcher, it would be good to have in Lawnchair as well

**Comment by topsy-turvy99** [comment]
#2866

**Comment by SuperDragonXD** [comment]
Superseeded by #2882.
