### ISSUE TITLE
The color of texts on homescreen is not changing properly

### ISSUE THREAD

**Issue by cubem10** [Deletescape-Media/Lawnchair#2703]
### Describe the bug

If I use wallpaper that has both bright and dark parts, the color of texts on homescreen does not change properly, like color of texts on At a glance widget of screenshot below. 

### Steps to reproduce

1. Set a wallpaper which has both bright and dark parts.
2. See color not changing properly.

### Expected behavior

The color of texts on white background should change to black, as reading white texts on white background is not easy.

### Screenshots

![Screenshot_20220612-194741_Lawnchair](https://user-images.githubusercontent.com/60423448/173229621-95484a4e-c7d7-46bf-8efc-497c68917610.jpg)

### Device information

- Device: Samsung Galaxy S10 (SM-G973N, beyond1lteks)
- OS: Stock Android 12 with One UI 4.1
- App version: 12.1.0 Dev (958)

**Comment by yasanglass** [comment]
As far as I know, the Glance text is only supposed to have a shadow for these situations and its color never changes.

**Comment by cubem10** [comment]
> As far as I know, the Glance text is only supposed to have a shadow for these situations and its color never changes.

When I set wallpaper to completely white one, its color changed to black. ![Screenshot_20220612-235619_Lawnchair.jpg](https://user-images.githubusercontent.com/60423448/173239230-2cb06cf9-42c1-4ad9-bc45-33c41b0d17cc.jpg)

**Comment by yasanglass** [comment]
Uh... my bad then. I guess this means it just hasn't detected the previous wallpaper as light. I guess the only 100% fix is to add a manual switch since you always can find some wallpaper that isn't properly detected. I will look into adding a manual switch.

**Comment by SuperDragonXD** [comment]
Superseded by #2759 due to it having more/better details
