### ISSUE TITLE
[BUG] Interacting with certain widgets causes Lawnchair to crash

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#2704]
### Describe the bug

When placing a widget on the home screen that allows the user to navigate through certain aspects of the widget without the need to open the corresponding app, lawnchair crashes when certain navigation buttons on said widget is pressed

### Steps to reproduce

1. Go to 'Widgets'
2. Scroll down to 'Google News'. Long press and add its widget to the home screen
3. Click on the left or right navigation button on the bottom right side of the right

### Expected behavior

It is expected that the widget will navigate to its next or previous page

### Screenshots

![Screenshot_20220612-095517_Lawnchair](https://user-images.githubusercontent.com/29732079/173236747-099a4e09-e0a2-4cb5-8e9a-83b02fdba484.png)
![Screenshot_20220612-095807_Lawnchair](https://user-images.githubusercontent.com/29732079/173236824-4a8b4f55-7adb-46a4-9ac8-6c8cfe81bb93.png)

### Device information

- Device: [OnePlus 9 5G]
- OS: [Custom ROM Android version 12.1]
- App version [12.1.0 Alpha 3]

**Comment by i-am-wololo** [comment]
I have this issue too but with the Spotify widget.
Here's the crash report https://katb.in/puvuxibajuh

**Comment by Scramzi** [comment]
same happens to me with digital wellbeing widget
crash report; https://pastebin.com/8qG2Hivn

**Comment by EvertonMJunior** [comment]
Same happens with Outlook Calendar widget and Focus To-Do widget.
Outlook Calendar crash report: https://pastebin.com/KJXNTdun
Focus To-Do crash report: https://pastebin.com/DGX9Qt6c

**Comment by SuperDragonXD** [comment]
Should be fixed on latest build (Lawnchair 12.1 Alpha 4). Closing this issue.
