### ISSUE TITLE
[Feature] Add Brave search to list of search engines 

### ISSUE THREAD

**Issue by obiwanconobi** [Deletescape-Media/Lawnchair#2706]
### Describe the bug

I would just like to use Brave search from the search bar 

### Steps to reproduce

 N/A

### Expected behavior

N/A

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by JoshuaKimsey** [comment]
Would love to see Brave Search added. Or at least the ability to add our own custom search engines to the search bar. That might be an even better move overall. :)
