### ISSUE TITLE
[BUG] After June security patch some widgets causing launcher to crash

### ISSUE THREAD

**Issue by Genos666** [Deletescape-Media/Lawnchair#2707]
### Describe the bug

After June security patch some widgets causing launcher to crash when interacting with the widget.

### Steps to reproduce

[ should be on **JUNE SECURITY PATCH** ]
1. Go to 'Widgets'.
2. Scroll down to 'Spotify' or 'Retro Music'. Long press and add its widget to the home screen.
3. Now click on the play button.
4. Launcher will crash.

### Expected behavior

When we click on play button on the widget it is expected that it should play a song.

### Device information

- Device: OnePlus 9R
- OS: Proton AOSP 12.1
- App version 12.1.0 Dev

### Additional context

```
Lawnchair bug report 14-Jun-2022 11:52:24 am
version: 12.1.0 Dev (#12) (12010003)
commit: 2dae9f2
build.brand: OnePlus
build.device: lemonades
build.display: SQ3A.220605.009.B1
build.fingerprint: google/raven/raven:12/SP2A.220505.002/8353555:user/release-keys
build.hardware: qcom
build.id: SQ3A.220605.009.B1
build.manufacturer: OnePlus
build.model: OnePlus 9R
build.product: lemonades
build.type: user
version.codename: REL
version.incremental: 1655061309
version.release: 12
version.sdk_int: 32
display.density_dpi: 411
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method registerRemoteAnimationForNextActivityStart(Ljava/lang/String;Landroid/view/RemoteAnimationAdapter;)V in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
	at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(QuickstepInteractionHandler.java:12)
	at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:882)
	at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
	at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6555)
	at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6403)
	at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1199)
	at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28811)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7877)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Chouffy** [comment]
I can also reproduce this error, using widget from Todoist.
Interesting enough, this doesn't occur with few others, like Firefox or Google Calendar.

* Lawnchair `version 12.1.0 Alpha 3` with QuickSwitch enabled
* OnePlus 6
* LineageOS `19-20220614-NIGHTLY-enchilada` (on Android 12)
* Android security update `June 5, 2022`

**Comment by KawaiiHachimi** [comment]
I reproduce this error too, using widget from [Salt Player](https://play.google.com/store/apps/details?id=com.salt.music&hl=en_US&gl=US).
* Lawnchair version 12.1.0 Dev(# 960) with QuickSwitch enabled
* Redmi K30 Ultra
* PixelExperience_Plus_cezanne-12.1-20220612-1349-UNOFFICIAL.zip (self-built)
* Android security update June 5, 2022
  
I just found that it also happened on the default PixelLauncher on PE-Plus(June build), but not on [ponces' gsi](https://github.com/ponces/treble_build_pe/releases/tag/v414-plus) and PE(non-Plus, June build) 😳
---
The latest version has fixed
https://github.com/LawnchairLauncher/lawnchair/actions

**Comment by firefinchdev** [comment]
I am also getting exact same issue. Latest version (from [Github Actions](https://github.com/LawnchairLauncher/lawnchair/actions)) did not fix the issue.

**Comment by suphon-t** [comment]
> I am also getting exact same issue. Latest version (from [Github Actions](https://github.com/LawnchairLauncher/lawnchair/actions)) did not fix the issue.

Can you attach a log?

**Comment by firefinchdev** [comment]
@paphonb 
```
07-25 11:04:13.305 14660 14660 E AndroidRuntime: FATAL EXCEPTION: main
07-25 11:04:13.305 14660 14660 E AndroidRuntime: Process: app.lawnchair.twelvel, PID: 14660
07-25 11:04:13.305 14660 14660 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method registerRemoteAnimationForNextActivityStart(Ljava/lang/String;Landroid/view/RemoteAnimationAdapter;)V in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(QuickstepInteractionHandler.java:66)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:882)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6555)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6403)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1199)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.performClick(View.java:7455)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.performClickInternal(View.java:7432)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.access$3700(View.java:835)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:28810)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:938)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Looper.loopOnce(Looper.java:201)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:288)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7870)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by dhirenvasnani** [comment]
I am also on June Security Patch. I placed every app widget on Homescreen. But there wasn't any issue for me.
I am on debug #1001
![Screenshot_2022-07-25-16-27-00-297_app lawnchair](https://user-images.githubusercontent.com/87919051/180762414-a311d2b4-077d-43e9-9639-699ae42c4531.jpg)

**Comment by firefinchdev** [comment]
Placing is not an issue. Triggering action causes the issue.
Try installing [TradingView](https://play.google.com/store/apps/details?id=com.tradingview.tradingviewapp), or [Bluetooth Audio Widget](https://play.google.com/store/apps/details?id=mag.com.bluetoothwidget.free). Place widget on home page.
For TradingView, tap on refresh icon on top right. Launcher crashes.

**Comment by dhirenvasnani** [comment]
I tried Bluetooth Audio Widget app,
Connected my BT Speaker with phone interacted with the widget, everything was fine

**Comment by skittles9823** [comment]
I should mention this issue only happens on Android 12.1 with the June patch, If you for some reason never got Android 12.1 but did get the June patch there won't be any crashes.

**Comment by firefinchdev** [comment]
@skittles9823 agree with you, I have A12.1 with June security patch, and getting this error.

**Comment by dhirenvasnani** [comment]
@skittles9823 Oh, thanks for mentioning. I am on Android 10 with June Security Patch.

**Comment by firefinchdev** [comment]
Was able to fix.
Change: https://github.com/LawnchairLauncher/lawnchair/pull/2799

**Comment by suphon-t** [comment]
> @paphonb 
> 
> ```
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime: FATAL EXCEPTION: main
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime: Process: app.lawnchair.twelvel, PID: 14660
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method registerRemoteAnimationForNextActivityStart(Ljava/lang/String;Landroid/view/RemoteAnimationAdapter;)V in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(QuickstepInteractionHandler.java:66)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:882)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6555)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6403)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1199)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.performClick(View.java:7455)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.performClickInternal(View.java:7432)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View.access$3700(View.java:835)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:28810)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:938)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Looper.loopOnce(Looper.java:201)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:288)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7870)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 
> 07-25 11:04:13.305 14660 14660 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> 
> ```

You're using a very old build. That's definitely not latest.

**Comment by firefinchdev** [comment]
I tried using latest build from `12.1-dev` branch: [Link: At the time of this comment](https://github.com/LawnchairLauncher/lawnchair/suites/7490782446/artifacts/307548076).
Working fine now.

**Comment by suphon-t** [comment]
Closing as this was already fixed.
