### ISSUE TITLE
[FEATURE] Use Max Frame Rates . 

### ISSUE THREAD

**Issue by yudhir** [Deletescape-Media/Lawnchair#2708]
### Describe the bug

It is running at 60 Hz , so phones supporting 120Hz seems laggy as they are forced to choose 60Hz . 

### Steps to reproduce

App Drawer scrolling . 

### Expected behavior

Smooth like Native launcher that support automatic frame rates . 

### Device information

Android 12  . Real Me . Realme UI 3

### Additional context

https://developer.android.com/guide/topics/media/frame-rate

**Comment by ComValer** [comment]
This app don't require an ability to get "smart 120Hz" but it will set it if you'll set "120Hz everywhere", not "smort choice". Checked on my Realme 8i

**Comment by suphon-t** [comment]
Lawnchair works with 120hz without any modifications. It's the realme software that's limiting framerate if you can only get 60.
