### ISSUE TITLE
[BUG] some more RTL issues

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2717]
### Describe the bug

Found some more RTL issues, the screenshots explain themselves 

### Steps to reproduce

1. Enable RTL
2. Go check appdrawer search, widget search, and the fuzzysearch settings option

### Expected behavior

RTL on the searchbars, and the period in fuzzy search subtext be in the correct position.

### Screenshots

![Screenshot_20220620-105134_Lawnchair](https://user-images.githubusercontent.com/29402532/174564955-74edd8f9-0053-4b47-9f13-008cacc9b7ea.png)
![Screenshot_20220620-104533_Lawnchair](https://user-images.githubusercontent.com/29402532/174564964-f1ba69a1-c93e-4138-9187-f74c768348b0.png)
![Screenshot_20220620-104522_Lawnchair](https://user-images.githubusercontent.com/29402532/174564967-6a506de8-d87f-4706-93f2-0dc6b029fccb.png)
![Screenshot_20220620-103745_Lawnchair](https://user-images.githubusercontent.com/29402532/174564969-0aaf1f9a-548f-458c-8127-d5f81c77b6cd.png)

### Device information

Device: OnePlus 7
OS: Android 12.1 KOSP
App version: 12.1.0 Dev (#968)

**Comment by yasanglass** [comment]
Just tested it & it looks like it happens only when the layout is RTL but the text isn't. So it is not an issue for languages that Lawnchair is fully translated in.
