### ISSUE TITLE
[BUG] Lawnchair settings feel laggy compared to other apps

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#2719]
### Describe the bug

I do not fully know since when it is, but it's either since the last stable build or a developer build after that. But for me the settings menu feels really laggy. Scrolling isn't smooth any more and toggling settings also takes a second.

### Steps to reproduce

1. Use the settings for a bit

### Expected behavior

Less lag in the settings menh

### Device information

- Device: OnePlus 7 
- OS: Android 12.1 KOSP 
- App version: 12.1.0 Dev (#968)

**Comment by SuperDragonXD** [comment]
Prolly an issue with your device settings, could you check if something is limiting performance or similar? Can't really reproduce in any of my devices...

You can try:
1. Restarting the app
2. Restart your phone
3. Re-install the app

> toggling settings also takes a second.

It actually depends on the setting. Some settings, like disabling the search bar, need a few changes on the back-end and may cause a few seconds of delay. (Prolly add a "toggling state tbh")

Some settings, like disabling home screen rotation, shouldn't take long for the toggle to rotate

**Comment by RikKoedoot** [comment]
Oh you're  right, I forgot that I had disabled some cores with FKM.
