### ISSUE TITLE
[FEATURE REQUEST] Open Recent Apps Menu with a Gesture

### ISSUE THREAD

**Issue by flug8** [Deletescape-Media/Lawnchair#2720]
I really loved the feature in Nova launcher, when you had the option to shortly swipe up when you are on the home screen and were able to launch the recent app's menu. By default, you have to swipe up and hold it for about 1.5s until the menu appears. A short swipe up is useless. Now the gestures have been added to lawnchair 12. Now you are able to set an action for a short swipe up from the home button. 
Now, it would be nice if we would have the option to open the recent app's menu when we perform a gesture. Anyone able to add this? I hope this isn't too difficult.

**Comment by RikKoedoot** [comment]
Workaround for untill it's added: https://drive.google.com/file/d/11fiUNgq8Am1NEJ1akQK1GOGFgAU7Y5m9/view?usp=drivesdk
Install tasker, import this task, then in Lawnchair set a gesture to open an app, then select tasker secondary.
Edit: I just saw your comment on another issue and I see you're aware of this exact thing.

**Comment by flug8** [comment]
The only problem is that this method does not really run smoothly, and I sometimes get high delays. Hope it gets added soon...
