### ISSUE TITLE
[BUG] system theme

### ISSUE THREAD

**Issue by TeaqariaWTF** [Deletescape-Media/Lawnchair#2721]
### Describe the bug

system does not follow theme

### Expected behavior

should follow system theme

### Screenshots

![Screenshot_20220621-005801_Lawnchair](https://user-images.githubusercontent.com/90970076/174682633-4651541a-ce0a-4054-a4ee-c70fc9b03497.png)
![Screenshot_20220621-005750_Lawnchair](https://user-images.githubusercontent.com/90970076/174682648-63882bfe-901d-4fc7-bcdd-74bf0a8ddd0e.png)

### Device information

- Device: [Poco X3 NFC]
- OS: [ArrowOS 12.1]
- App version [ 12.1.0 Dev (#969)]

**Comment by RikKoedoot** [comment]
Please fill out the title

**Comment by flug8** [comment]
Temporary solution: Force Stop Lawnchair, then clean app cache, now it should work again.

**Comment by TeaqariaWTF** [comment]
> Geçici çözüm: Lawnchair'i Durdurmaya Zorlayın, ardından uygulama önbelleğini temizleyin, şimdi tekrar çalışması gerekir.

yes but this problem occurs every time restarting the device
