### ISSUE TITLE
Switch Animation

### ISSUE THREAD

**Issue by Leyzymoy** [Deletescape-Media/Lawnchair#2723]
### Describe the bug

Incorrect switch animation. 

### Steps to reproduce

Go to settings
Click on any setting with a switch element
Incorrect animation

### Expected behavior

Go to settings
Click on any setting with a switch element
Correct animation without disabling animation duration in system developer settings

### Device information

- Device: Redmi Note 7
- OS: MIUI 12.5, Android Q
- App version 12.1.0 Dev 969 (12010003)

**Comment by RikKoedoot** [comment]
Could you show or explain what the incorrect animation is?

**Comment by RikKoedoot** [comment]
Closing, copy of #2598

**Comment by Leyzymoy** [comment]
> Closing, copy of #2598

But the problem remains , I found out that this problem is also affected by the density of the screen, at 400dpi bug remains at 450dpi works as it should + this is affected by the duration of the animation

**Comment by RikKoedoot** [comment]
Yes the issue remains, but your issue is the same as #2598, we close duplicate issues. Could you reply with the dpi thing under #2598?
