### ISSUE TITLE
[BUG] Switch not animating, certain features can't work until app is restarted 

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#2724]
### Describe the bug

The switches / toggles do not work properly on my phone. The toggles change colour but don't animate. I tried changing the theme colour but it is buggy and doesn't change. I find this bug only on some devices as on my other android 12 device it works fine but the theme issue persists.

### Steps to reproduce

1. Go to lawnchair settings
2. Click on any toggle 
3. See error

### Expected behavior

The switch should animate properly but it doesn't.

### Screenshots

![Screenshot_20220620-195907_VLC](https://user-images.githubusercontent.com/93768823/174697180-bf446460-558b-4665-a10f-80ed9a6c0303.jpg)

https://streamable.com/0v9dg7

### Device information

- Device: Samsung SM-G985F
- OS: OneUI 4.1 Android 12
- App version 12.1 Alpha 3

**Comment by notroger7** [comment]
sorry I accidentally closed this lawnchair team please take a look at this

**Comment by SuperDragonXD** [comment]
It's interesting that the toggles still don't animate for some devices... (See also #2598, think should re-open)

**Comment by RikKoedoot** [comment]
Closing, #2598 is reopened
