### ISSUE TITLE
[FEATURE REQUEST] search box transparency 

### ISSUE THREAD

**Issue by sergioad** [Deletescape-Media/Lawnchair#2725]
Hello all devs, could someone please add dock search box transparency? The fact I can not see my whole wallpaper bothers me, I like having the search box too, so for me a transparent search box is ideal

![Screenshot_20220620-211844](https://user-images.githubusercontent.com/5375145/174703945-9628f348-2e79-4730-8cf3-d2686b38c04b.png)

BTW I would also suggest you to use the Google search box Lens button instead of the official button if you are using the voice search button instead of the assistant one

**Comment by topsy-turvy99** [comment]
Just referring to it as i included this option too in feature request list related to dock in #2775
