### ISSUE TITLE
[Feature Request] Consistent search box in app drawer 

### ISSUE THREAD

**Issue by kahanzammi** [Deletescape-Media/Lawnchair#2727]
### Describe the bug

I would like to suggest to make the search box in the app drawer to behave similar to the search box in Lawnicons app (consistent while scrolling up and down).

### Steps to reproduce

1. Open the app drawer.
2. Scroll down
3. Rounded rectangular search box disappears.

### Expected behavior

While scrolling up and down, rounded rectangular search box should remain the same (similar to Lawnicons app interface).

### Screenshots
![Screenshot_20220621-214755_Lawnchair](https://user-images.githubusercontent.com/105884763/174865888-d56dffdb-fea6-4de4-8d28-f64d287351a8.jpg)

### Device information

- Device: Galaxy S8 
- OS: Android 9
- App version 12.1 dev

**Comment by suphon-t** [comment]
This is the intended behavior.
