### ISSUE TITLE
Error resizing widgets 

### ISSUE THREAD

**Issue by qamarq** [Deletescape-Media/Lawnchair#2731]
### Describe the bug

I mean, you can not freely reduce the height of widgets and they are far from the edge of the phone which takes up too much space. For example, if you have a widget for creating notes os Google, then adding it to the home page appears in the form of a square and although it can be reduced in other launchers, here you can not change the height. In general, widgets are very little variable size. 

### Video 
The main launcher is Lawnchair in version v2, the application is Lawnchair v12, at the beginning I open v12 and the widget does not decrease and in v2 it normally decreases 

https://youtu.be/c91RNrTaJGE

### Steps to reproduce

1. Go to add widget page 
2. Click on Google keep widget for add notes 
3. I added to the home screen 
4. I could not reduce it to a rectangle, even though on other launchers it is possible and then it changes the color and arrangement of the buttons. This is the case with every widget

### Expected behavior

The widget decreased from square to rectangle as in other launchers and he did not want to shrink and was still a square 

### Device information

- Device: Samsung Galaxy A41
- OS: Android 12 with One UI 4.1
- App version new 12.1.0 ALPHA 3

**Comment by SuperDragonXD** [comment]
Can freely resize the widget in the latest version to the above format(s), so should be fixed in Lawnchair 12.1+. Therefore closing this issue.

**Comment by Amorphous404** [comment]
Devs are working on this feature, you can follow #2822 👍
