### ISSUE TITLE
Crash when clicking a bookmark in Bromite's widget

### ISSUE THREAD

**Issue by k2helix** [Deletescape-Media/Lawnchair#2734]
### Describe the bug

If the bookmarks widget of Bromite is placed, clicking a bookmark will crash Lawnchair

### Steps to reproduce

1. Go to Widgets and add Bromite bookmark
2. Click on a bookmark from the widget
3. Crash

### Expected behavior

The widget should work fine and open the bookmark 

### Device information

- Device: Sony Xperia XA2
- OS: LineageOS 19 (A12L)
- App version: 12.1.0 Alpha 3
Crash info below
[Lawnchair bug report 24 Jun 2022 12_29_25.txt](https://github.com/LawnchairLauncher/lawnchair/files/8975522/Lawnchair.bug.report.24.Jun.2022.12_29_25.txt)

**Comment by SuperDragonXD** [comment]
Should be fixed in Lawnchair 12.1 Alpha 4. Closing this issue
