### ISSUE TITLE
Use material-color-utilities as fallback for Android phones that dont support Material You

### ISSUE THREAD

**Issue by lorandcompany** [Deletescape-Media/Lawnchair#2738]
It's a library by Google that contains the algorithm for creating Material You palettes.

https://github.com/material-foundation/material-color-utilities

**Comment by SuperDragonXD** [comment]
Uh... Lawnchair already has an algorithm to also have Material You on Android 11 and below devices. Is there any difference or something from Lawnchair's implementation?

Also, it may/may not be used already inside Lawnchair, not sure though.

**Comment by lorandcompany** [comment]
Oh yeah kdragon's implementation is already in Lawnchair. (Its much better than what Google does too 👍)

My bad. I'm closing this issue.
