### ISSUE TITLE
Update workflows 

### ISSUE THREAD

**Issue by xs1vr** [Deletescape-Media/Lawnchair#2742]
Delete debug and release workflows and combine them into one (one workflow should provide both debug and release APKs because people actually do heavily rely on action artifacts — even some official ROMs include debug version of the lawnchair as the main launcher xd) (also last update to the alpha branch (the one release workflow uses) was in February, 3.6k commits ago)

Hence one action should have:
- Debug APK
- Release APK

**Comment by SuperDragonXD** [comment]
It's nice to have that, but the problem is that the developer builds are for development purposes: they aren't suitable for release. If they are, we would have many alphas by now.

I think you can also manually compile Lawnchair with the `release` flag or similar, too.

**Comment by xs1vr** [comment]
> It's nice to have that, but the problem is that the developer builds are for development purposes: they aren't suitable for release. If they are, we would have many alphas by now.
> 
> I think you can also manually compile Lawnchair with the `release` flag or similar, too.

I understand that, but as I said — many ROM maintainers actually include them with their ROMs because they don't want/know how to build a release apk from the source — and because it's not a debug release, it becomes hella unresponsive, probably because of the all debug stuff..I actually do compile them myself so it's not a problem for me 😁 
Also, Android Repository (telegram) provides latest apk built for release build but many people don't know about it (#981)

**Comment by skittles9823** [comment]
> I understand that, but as I said — many ROM maintainers actually include them with their ROMs

Fact of the matter is, they shouldn't be using builds from artifacts as the default launcher in their ROM, and instead should be using the released alphas.

**Comment by xs1vr** [comment]
> > I understand that, but as I said — many ROM maintainers actually include them with their ROMs
> 
> Fact of the matter is, they shouldn't be using builds from artifacts as the default launcher in their ROM, and instead should be using the released alphas.

Yes, I know, but hell nah they need to put something in the changelog 🙄

**Comment by skittles9823** [comment]
@xslvrxslwt And that&#x27;s our problem why exactly?

**Comment by paphonb** [comment]
Debug APKs provide more useful information when trying to debug an issue (they’re called “debug” for a reason), and release APKs can’t replace that. If you want to use it, you’ll have that accept that
