### ISSUE TITLE
Widget icons not matching lawnicons/icon pack

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#2744]
### Describe the bug

The app icons shown in the 2nd screenshot do not correspond to the app icons shown in the first screenshot. Hopefully it's fixed later.

### Steps to reproduce

1. Long press
2. Click on widgets
3. See the icons
4. Go to the app drawer
5. Apps don't correspond lmao

### Expected behavior

apps should correspond like nova launcher, Hyperion, etc.

### Screenshots

![Screenshot_20220701-084730_Lawnchair](https://user-images.githubusercontent.com/93768823/176801248-45d32b05-2208-42fd-8a13-a606747b2663.jpg)
![Screenshot_20220701-084650_Lawnchair](https://user-images.githubusercontent.com/93768823/176801251-09e7cbd7-71e3-490c-a9ae-c6550dfaa8ab.jpg)

### Device information

- Device: Samsung SM-A125F
- OS: OneUI 3.1.1 android 11
- App version 12.1.0 Alpha 3

### Additional context

hehehehaw

**Comment by SuperDragonXD** [comment]
Try restarting the app to see if the issue persists? (Home Settings > 3-dots menu > Restart Lawnchair)

**Comment by notroger7** [comment]
@SuperDragonXD it doesn't work

**Comment by notroger7** [comment]
I tried to like tinker with the app but it still stays

**Comment by notroger7** [comment]
Uh @SuperDragonXD this still is present in the latest lawnchair dev version

sorry for ping but this still occurs

**Comment by SuperDragonXD** [comment]
It seems like the widget menu uses the system icons instead of the currently applied icon pack in Lawnchair. Not sure how to change this though. But it's more or less not a bug though, just a oversight when the icon pack implementation was added.
