### ISSUE TITLE
Light wallpaper support 

### ISSUE THREAD

**Issue by kahanzammi** [Deletescape-Media/Lawnchair#2745]
I found current light wallpaper support is only limited to icons and dock search widget.

UPDATE: Just now tested in a Android 12 device. It works as I suggested in Android 12. So that this issue should be only related to older versions of Android.

![Screenshot_20220702-134948_Lawnchair](https://user-images.githubusercontent.com/105884763/176995524-bf526da9-041d-42b9-b499-68c201be4ddb.jpg)

It would be nice to have light wallpaper support similar to pixel launcher.

![google-pixel-6](https://user-images.githubusercontent.com/105884763/176995543-aef66145-edb1-4521-86b5-ccbedbd02573.jpg)

**Comment by SuperDragonXD** [comment]
Superseded by #2759 due to it having more/better details.

Also, the status bar can be manually set to be dark. The other widget (not At A Glance) can't really be fixed, since it isn't controlled by Lawnchair.
