### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by naeemgithub0** [Deletescape-Media/Lawnchair#2746]
### Describe the bug

Music widget not working 

### Expected behavior

Music widget button not working... launcher restart..

### Screenshots

![Uploading Screenshot_20220702-213456_Lawnchair.png…]()

### Device information

- Device: [e.g. Redmi note 10 pro]
- OS: [e.g. crdorid Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by SuperDragonXD** [comment]
Please provide a proper title. Also, the image didn't upload properly. Logs are also missing.
