### ISSUE TITLE
[Feature request] add quick wallpaper picker

### ISSUE THREAD

**Issue by Seandylan123** [Deletescape-Media/Lawnchair#2747]
### Describe the bug

Hi i would like to see quick wallpaper picker lawnchair and a option to turn it on or off

### Steps to reproduce

1. Go to 'lawnchair settings'
2. Click on 'home screen'
3. Scroll down to 'general'
4. Enable quick wallpaper picker and press and hold on your home screen it will be based on what wallpapers you used

### Expected behavior

E

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

### Additional context

A feature request

**Comment by tropicaaal** [comment]
would like to see this as well
