### ISSUE TITLE
Recents provider for A12 compatibility issue . 

### ISSUE THREAD

**Issue by altCK129** [Deletescape-Media/Lawnchair#2751]
### Describe the bug

on A12 it shows in quickswitch that this recents provider is not compatible with Android 12 , any solution for this issue? 

### Expected behavior

It should support A12

### Device information

Moto g60 , Android 12 , latest version of lawnchair 12.1

**Comment by skittles9823** [comment]
@krrishkap Use Lawnchair 12.0.0, 12.1.0 only works on Android 12.1
