### ISSUE TITLE
Wallpaper sliding to the left when setting from pictures with wider aspect ratio

### ISSUE THREAD

**Issue by FightingPhantom** [Deletescape-Media/Lawnchair#2753]
### Describe the bug

While setting wallpapers that have wider aspect ratio, the wallpaper slides to left when I set it even with scroll wallpaper switched off. While setting it looks perfect, but after setting it slides to left. On lockscreen and other launcher the wallpaper looks the same, but when I enter Lawnchair 12.1, I can see the change. When switching to other launcher without re-setting the wallpaper, it looks like the preview but things change as soon as I enter Lawnchair.

### Steps to reproduce

1. Select your favourite picture with a wider aspect ratio than your device
2. Set it as your wallpaper 
3. Now go to home screen and see the difference 
4. Switch between different launchers and notice the slight shift of wallpaper 

### Expected behavior

Wallpaper will shift to the left.

### Screenshots

![Screenshot_20220706-211558_Lawnchair](https://user-images.githubusercontent.com/108801311/177591031-b0904c8c-bfcf-40e4-9452-b79ce747a797.jpg)
![Screenshot_20220706-211603_Lawnchair](https://user-images.githubusercontent.com/108801311/177591046-4a0b0cea-d4d3-4a01-8370-bf6bfc1ad024.jpg)

### Device information

- Device: Samsung S20 FE 5G ( G781B )
- OS: ONE UI 3.1 based on Android 11
- App version 12.1.0 Alpha 3

**Comment by Amorphous404** [comment]
Duplicate of #2331 ?

**Comment by SuperDragonXD** [comment]
Try disabling wallpaper scrolling (Home Settings > Home Screen > Scroll Wallpaper) and see if it fixes the issue.
