### ISSUE TITLE
[Feature Request] Dark mode integration to wallpaper

### ISSUE THREAD

**Issue by extropyst** [Deletescape-Media/Lawnchair#2754]
It would be great if they integrated a functionality so that the color of the wallpaper changes depending on the activation of the dark mode.
I saw this functionality in the latest version of Gnome (with Fedora), and I think it's great how the color of the image is integrated with the system.

Currently in android there are two applications that allow you to do something similar to this although in a limited way. However, I think it would be better if it were integrated into the launcher itself. Here is the source code for both:
 https://github.com/cvzi/darkmodewallpaper
https://github.com/patzly/doodle-android

**Comment by Username1-a** [comment]
Yeah, that would be cool

[Just don't understand why this feature is still not implemented in Android itself, I think it should've been there since the Android 10, when system dark theme arrived (Just like it was in iOS)]
