### ISSUE TITLE
[Feature Request] Add quick select wallpapers on long press on the homescreen

### ISSUE THREAD

**Issue by minhdangoz** [Deletescape-Media/Lawnchair#2755]
### Describe the bug

![Screenshot_20220708_104009](https://user-images.githubusercontent.com/3844258/177912764-47bef950-a0e2-4961-9a2d-b52669ac3db1.png)

This is Pixel Launcher on Android 13 (Tiramisu)

### Steps to reproduce

1. Go to Homescreen
2. Long press on empty space
4. See preview

### Expected behavior

Show the wallpaper picker

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 13.0]
- App version 13

**Comment by Seandylan123** [comment]
A great idea they should integrate that but why not create a pull request
