### ISSUE TITLE
[Feature request] add a option to also use light colors and dark colors to theam icons

### ISSUE THREAD

**Issue by Seandylan123** [Deletescape-Media/Lawnchair#2758]
### Describe the bug

I kind of like to use that the because it can be a little bit more exciting

### Steps to reproduce

1. Go to 'lawnchair settings'
2. Click on 'general'
3. Scroll down to 'icon pack'
4. Enable thamed icons and click on the option to also use a second accent color

### Expected behavior

E

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by kahanzammi** [comment]
I second this. Would love to have an option to set manual background / foreground colors for themed icons.
