### ISSUE TITLE
[BUG] add option to change at a glance text from white to black to better accomodate lighter wallpapers.

### ISSUE THREAD

**Issue by linusrg1** [Deletescape-Media/Lawnchair#2759]
### Describe the bug

When you have a light wallpaper applied the at a glance widget text stays ligit, when it should be dark for better visibility.

### Steps to reproduce

Apply a ligit wallpaper the text does not turn dark, and there is no option to make it dark.

### Expected behavior

For the text to either automatically turn dark or to have the option to turn the text dark in the at a glance settings page. 

### Device information

- Device: Galaxy s9 
- OS: derpfest 12.1 July patch 
- App version 12.1.0 alpha 3.

**Comment by kahanzammi** [comment]
A workaround is to use "Light" theme option under General settings.
But it only works for very very light wallpapers.

**Comment by kahanzammi** [comment]
I believe this is no more an issue in recent Dev builds. Fonts color now support lighter wallpapers better.

![Screenshot_20220718-184803_Lawnchair](https://user-images.githubusercontent.com/105884763/179540924-e79b79f7-4b21-4bb0-9a41-656764676134.jpg)

**Comment by yasanglass** [comment]
This is an issue on almost every launcher, the automatic detection isn't always accurate for many wallpapers. Having an option to manually choose the text colors would be really useful.

**Comment by linusrg1** [comment]
> This is an issue on almost every launcher, the automatic detection isn't always accurate for many wallpapers. Having an option to manually choose the text colors would be really useful.

It really would.

**Comment by yasanglass** [comment]
I am planning to implement this feature soon.
