### ISSUE TITLE
Rounded Corners on Folders

### ISSUE THREAD

**Issue by jtwp** [Deletescape-Media/Lawnchair#276]
As it says. Rounded corners on folders. This would then match the overall pixel theme and match the long press popup which has them too.

Example I made:

https://drive.google.com/file/d/0B84hVgh-7CxoZ3hYd2kyT0xyYVk/view?usp=drivesdk

**Comment by suphon-t** [comment]
Doesn't look as nice as the concept when implemented because of some other factors. But might think about implementing this again in the future.

![Screenshot](http://i.imgur.com/3tnNmrR.jpg)

**Comment by jtwp** [comment]
@paphonbth It looks brilliant! It's just how it should be. Some people might not like it (can't see why) but if it could be an option then even better.

**Comment by jtwp** [comment]
@paphonbth Also see you use squirqle icons. You know a nice squirqle (or other) folder icon would look lovely along side them ;-)

**Comment by RWOne** [comment]
I think it comes down to blur or no blur, I'm good either way.

@paphonbth, dumb question, newbie on GitHub, but how might I test new builds? (In thinking I don't have the knowledge to compile, but who knows? :) )

**Comment by suphon-t** [comment]
Clone the repo and open it in Android Studio. You can find tutorials on the internet.

**Comment by RWOne** [comment]
Thanks! Will look into it...
