### ISSUE TITLE
More customization for app shortcuts and folders.

### ISSUE THREAD

**Issue by CrynTox** [Deletescape-Media/Lawnchair#2763]
### Describe the feature

Add the ability to change the name and the icons of app shortcuts.

Add the ability to change folder background color and transparency(when they're closed and opened).

### Why would it be useful to add?

Would make theming more consistent.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

I really don't think that's necessary since I believe I explained it simply.
The shortcuts work like on Lawnchair v2.
And as for the folders just color and transparency.
Edit:
On second thought... here
![Imagepipe_1](https://user-images.githubusercontent.com/88785107/178496533-469df904-5265-4605-9bdd-ba397a9f13d5.jpg)

**Comment by coxde** [comment]
This is a reasonable feature request, should not be closed.
