### ISSUE TITLE
[FEATURE]  hide nav bar on home screen

### ISSUE THREAD

**Issue by Rikudo8** [Deletescape-Media/Lawnchair#2764]
### Describe the feature

Please add an option to hide nav bar on home screen for android 10 devices that didn't have navbar with gestures

### Why would it be useful to add?

For have more screen ratio

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

*

**Comment by SuperDragonXD** [comment]
Lawnchair *does not* handle the lock screen, only the home screen.

If I remember correctly, the navbar only shows when you try to unlock the device using the PIN/password/etc. So it doesn't really waste that much screen area on the lock screen.

**Comment by Rikudo8** [comment]
No on home screen no on lock screen

**Comment by RikKoedoot** [comment]
Oh, you wrote lockscreen though, will reopen
