### ISSUE TITLE
[FEATURE] Icon Request support in Lawnchair or Lawnicons/Allow multiple icon pack support

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#2765]
### Describe the feature

before i explain, i will say that the multiple icon pack support somewhat existed in lawnchair v2, however, the icon request support definitely didn't exist. 

Allow some code to allow lawnicons or lawnchair to get icon request support so that we can request our icons we have, so that it benefits both the user, and devs [explained below]

Allow multiple icon pack support because one icon pack may not support all the apps we use. I

### Why would it be useful to add?

1. lawnicons only support like 10% of my icons 
2. The devs would know what apps general users use so they can prioritise
3. icons would look very neat and consistent
4. multiple icon pack support eliminates the need to purchase paid icon packs like borealis that has 25k+ icons

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![photo_2022-07-14_18-25-50](https://user-images.githubusercontent.com/93768823/178961948-d0a68c54-6067-4a4e-bdae-d63986df8ce1.jpg)

picture of lawnicons + ondynamic icon pack

![photo_2022-07-14_18-28-59](https://user-images.githubusercontent.com/93768823/178963422-5b3df1ef-22b5-47c4-aba7-b950764dc353.jpg)

picture of how multiple icon pack works

### Additional context

I suggest the devs get inspired from the existing OnDynamic Icon Pack [https://play.google.com/store/apps/details?id=iconpack.onsurface.monet&hl=en_SG&gl=US](url) and apply it to lawnicons because that icon pack only supports android 12 and above and my phone will only support android 11 :(

The multiple icon pack support existed in Lawnchair v2 and it was wonderful to use, however the lawnicons feature defo didn't exist in lawnchair v2. 

and btw I'm not using my phone im still young

**Comment by Blank-Slate7** [comment]
wait i didnt mean to add the tags I didn't even know how to

**Comment by notroger7** [comment]
wait what i can add tags???

**Comment by msfjarvis** [comment]
You can not. They were automatically added by the issue template.

**Comment by SuperDragonXD** [comment]
Well, regarding your first point "Icon Request support in Lawnchair or Lawnicons", you can always post an issue in [Lawnicons](https://github.com/LawnchairLauncher/lawnicons/issues) regarding an icon request. (Might want to create issue templates to that, so people can easily request icons and other stuff.) I don't think a UI in the app is really needed though.

For your second point, not sure but it may be re-added in the future. Can't give you a specific date, the devs don't know when they'll add it.
