### ISSUE TITLE
[BUG] When using any gestures app, gesture "recents" shows previous app instead of the current

### ISSUE THREAD

**Issue by GutUser3** [Deletescape-Media/Lawnchair#2766]
### Describe the bug

I use gestures app "Vivid Navigation Gestures" (but bug was present when I was using FNG as well) to assign right edge swipe up to recents.
But sometimes instead of showing the current app, it shows the previous one or jumps to some random app, which is really frustrating at times.
It appears regardless what gesture I assign the recents to be.
I've confirmed that it's not the system bug, since I've used different pixel launcher based launcher that didn't have it. But it's functionality wasn't comparable to what lawnchair had to offer

### Steps to reproduce

1. Use any gesture application 
2. Assign any gesture to recents
3. Might be normal a few times, but it will start appearing 
4. Recents jump to previous app, or any other, except the current

### Expected behavior

Recents to show current app

### Device information

- Device: [Oneplus 8]
- OS: [Evolution X 6.6]
- App version: [Dev #989]

### Additional context

I am on the dev build, but I started using it hoping to get rid of the probem in the first place. So that's not an issue

**Comment by RikKoedoot** [comment]
Are you using quick switch aswell?

**Comment by GutUser3** [comment]
Yes. Latest 3.3.1

**Comment by suphon-t** [comment]
Can you attach a recording of the issue? Currently I don't understand it.

**Comment by GutUser3** [comment]
I tried just now, but it doesn't occur when recording since recents page (the rest of ui doesn't) starts to lag and runs at 40ish fps. 

Maybe I can explain better: when you go to recents, you expect to see the app you just used, but sometimes when I do the gesture using the app (the problem doesn't occur if you swipe the usual way from the lower part of the screen) it jumps to the previous or any random app.
