### ISSUE TITLE
ADD ANIMATIONS LIKE PIXEL LAUNCHER 

### ISSUE THREAD

**Issue by GabriLex** [Deletescape-Media/Lawnchair#2769]
### Describe the feature

The animations of the apps on the home screen are not done well because they do not return to the app icon but disappear in the home, while with the pixel launcher or other launchers they return.

### Why would it be useful to add?

Yes to improve experience with this Launcher 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://mega.nz/file/t3pAjDBC#_yao7NSpbXxebJzGyvwJkjmL7EtrTOuq_1MHVYUmVx8

**Comment by keyjeyelpi** [comment]
This is already possible, but needs root. If you have root, use quickswitch.

**Comment by GabriLex** [comment]
Works, thanks you but now I don't have the option to select the textIl 16 lug 2022 14:13, keyjeyelpi ***@***.***> ha scritto:
This is already possible, but needs root. If you have root, use quickswitch.
