### ISSUE TITLE
ADD SELECT BUTTON ON TASK MANAGER 

### ISSUE THREAD

**Issue by GabriLex** [Deletescape-Media/Lawnchair#2771]
### Describe the feature

You can select text or copy images on task manager 

### Why would it be useful to add?

Yes, a lot

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220716-153408_Avvio app Pixel](https://user-images.githubusercontent.com/98557097/179357164-88117790-05a4-4717-bfc3-2e9c3301d602.png)

### Additional context

No

**Comment by SuperDragonXD** [comment]
If you have QuickSwitch, you can instead use Google Lens as a replacement for the "Select" feature.

**Comment by GabriLex** [comment]
Thanks you but if you can integrate like that of google it's perfectIl 17 lug 2022 11:42, SuperDragonXD ***@***.***> ha scritto:
If you have QuickSwitch, you can instead use Google Lens as a replacement for the "Select" feature.

**Comment by suphon-t** [comment]
> Thanks you but if you can integrate like that of google it's perfectIl

No, that’s not possible.

**Comment by pixincreate** [comment]
> If you have QuickSwitch, you can instead use Google Lens as a replacement for the "Select" feature.

How? You need Android System Intelligence to get text select working on Pixel launcher

**Comment by SuperDragonXD** [comment]
Google Lens does not require Android System Intelligence. It just needs the Google app installed.

**Comment by pixincreate** [comment]
> Google Lens does not require Android System Intelligence. It just needs the Google app installed.

I'm aware of that. I spoke about the pixel launcher instead.:)

> If you have QuickSwitch, you can instead use Google Lens as a replacement for the "Select" feature.

How can you select Google lens in quickswitch? You asked the the other guy to open so to make screenshot and scan everytime?

**Comment by SuperDragonXD** [comment]
Oh, I see. Well here are the steps to do that:

Once you have QuickSwitch, first enable the "Lens" toggle in Home Settings > Recents

Then go to the recents screen, andvclick "Lens

After that, something like this should show up:

![Screenshot_2022-08-08-14-49-50-84_680d03679600f7af0b4c700c6b270fe7.jpg](https://user-images.githubusercontent.com/70206496/183356748-13ce7a30-2507-4c1e-afb2-49da72ef65fd.jpg)

Click "Text", and select your text

**Comment by pixincreate** [comment]
Gotcha!
Which version of Lawn chair have that lens option visible in Recents option? I'm currently on latest debug build and that option doesn't exist. @SuperDragonXD

**Comment by SuperDragonXD** [comment]
Well, it should be available on Lawnchair 12+ if I remember correctly. Note that you should have QuickSwitch though

**Comment by pixincreate** [comment]
> Well, it should be available on Lawnchair 12+ if I remember correctly. Note that you should have QuickSwitch though

I'm on Lawnchair 12.1 Dev (# 1013) currently. FYI I've changed the recents provider to Lawnchair with quickswitch already

**Comment by RikKoedoot** [comment]
You need to install the lens app aswell. Closing this issue as we won't implement text select like on the pixel launcher, as we already have lens and select is not possible to port.

**Comment by RikKoedoot** [comment]
You did not see that
