### ISSUE TITLE
[FEATURE] Please Restore Back The Previous Rounded Square Shape

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2776]
### Describe the feature

The Previous **Lawnchair 12.1 Alpha 3** Had Some Extra Few Icon Shapes, 
![IMG_20220718_181731_421~2](https://user-images.githubusercontent.com/96917972/179515125-f9a59900-3db9-4a1f-9771-2f371017f997.jpg)

Which Is Missing From The Latest **Dev Build 12.1 #996**
![Screenshot_2022-07-18-18-12-56-67_67d7f8591eff9881972c1169b8bca2d8~2](https://user-images.githubusercontent.com/96917972/179516344-e044a076-a931-4106-9506-fe8ba3ec0951.jpg)

Idk If The Devs Decided To Nuke It, But Please Back The **Ios Icon Shape**.
![Screenshot_2022-07-18-18-23-16-54_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/96917972/179515460-1782c389-62b7-4900-affb-b204029141f9.jpg)
The Center One Is Ios Shape

### Why would it be useful to add?

Ios Shape Is Preferred By Some Users, And I Personally Use It To Match The Unthemed Icons  With Icon Pack That Has Ios Shape

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Attached Above

**Comment by SuperDragonXD** [comment]
I actually wanted to make an issue about this, but forgot...

Well, it was removed by @paphonb in [this commit](https://github.com/LawnchairLauncher/lawnchair/commit/79c38a3f970c9aa3175e30027c0d4e77e8c1c03f), unsure why the icon shapes need cleanup though.

**Comment by Amorphous404** [comment]
Same here 😅, Hope they add it back especially the ios shape

**Comment by RikKoedoot** [comment]
It's still there, rounded rectangle is now what iOS was. We generally removed icons that we thought were too much/not that good looking

**Comment by SuperDragonXD** [comment]
It's still nice to have the option though...

**Comment by Amorphous404** [comment]
> It's still there, rounded rectangle is now what iOS was. We generally removed icons that we thought were too much/not that good looking

It's not the same as you can see from the screenshot i posted above, the two icons next to Lawnchair app icon doesn't match the shape of lawnchair app icon that follows the ios shape

**Comment by RikKoedoot** [comment]
That's because the other two apps do not follow the ios/rounded rectangle

**Comment by Amorphous404** [comment]
> That's because the other two apps do not follow the ios/rounded rectangle 

The  Rounded Square Shape Doesn't Follow The Same Shape,
For Confirmation I Switched To Previous Build

Current #996 Dev Build
(Rounded Square Shape)
0![Screenshot_2022-07-18-19-59-57-86_67d7f8591eff9881972c1169b8bca2d8~2.jpg](https://user-images.githubusercontent.com/96917972/179534993-5f7453f9-9f14-4a2d-9bf3-719bc47913fb.jpg)

Old Build #956 Dev Build 
(Rounded Square Shape)
(Where It Had The Same Shape)
![Screenshot_2022-07-18-19-58-59-47_67d7f8591eff9881972c1169b8bca2d8~2.jpg](https://user-images.githubusercontent.com/96917972/179535141-b10c4c71-4574-4337-a1a8-c44be87b8e34.jpg)

**Comment by Amorphous404** [comment]
> That's because the other two apps do not follow the ios/rounded rectangle

I The Current Rounded Square Doesn't Follow The Same Shape Of Lawnchair v2
![Screenshot_2022-07-19-21-11-13-37_3b881d4c06d4cbc1b5e5ddba75e2aac5](https://user-images.githubusercontent.com/96917972/179792586-8c36cadb-53fb-4fa3-b7c7-f7d402ef5902.jpg)


My Suggestion Will Be To Please Restore The Old Shape Of Rounded Square, And Have Ios Shape Have The Same shape That The Current Rounded Square Have

**Comment by Amorphous404** [comment]
I Don't know which In  which Version it got fixed, but now with 1029 dev build, the previous Rounded Square Shape Is Back, and now it has a preview for all the icon shape too 🔥,

I'm closing this ticket, Thank You
