### ISSUE TITLE
[FEATURE] Option To Sort Apps In App Drawer

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2777]
### Describe the feature

A Three Vertical Dot Menu Button Can Be Added On The Top Right Corner Of Search Bar, To Add An Option To Sort Apps 
1. By **Name**
2. By **Usage**
3. By **Installation Time**

In App Drawer Especially To Sort By Installation Time.

Even My Stock Oxygen Launcher And Smart Launcher Have It

Demo

**Stock Oxygen Launcher** 
![Screenshot_2022-07-18-19-21-24-98_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/96917972/179530061-11a2c339-723b-4fd3-8592-06a982ed1710.jpg)

**Smart Launcher**
![Screenshot_2022-07-18-19-14-20-43_39cdc23507af3cd1237ce5ff0636726d~2](https://user-images.githubusercontent.com/96917972/179530920-2934725f-255b-43d2-afa2-881fa79bd9f4.jpg)

![Screenshot_2022-07-18-19-13-24-03_39cdc23507af3cd1237ce5ff0636726d~2](https://user-images.githubusercontent.com/96917972/179530949-2486fd48-38aa-4608-8d0e-a31148ad09fa.jpg)

### Why would it be useful to add?

It's Useful For User To Figure Which All Apps Was Installed Recently, And Which All Apps Are Old, So Can Uninstall It,

Same With Based On Usage If The Devs Don't Mind Adding It, But I Prefer The Installation Time More, It's Qol Things That Helps User Experience With The Launcher.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Attached Above

**Comment by Amorphous404** [comment]
I'm not much into the custom user sort order in app drawer but it has been requested in #1820, maybe it can be added as forth option

**Comment by tylla** [comment]
I agree with the "add as 4th option" opinion. It should definitely go there.
