### ISSUE TITLE
[FEATURE] Option To Directly Access All Hidden Apps From App Drawer

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2778]
### Describe the feature

I Really Like The Feature To View **All The Hidden Apps Directly From App Drawer** In Smart Launcher, I Hope Others Will Like It Too

I Hope Lawnchair Launcher Provides The Same Option in Vertical Three Dots Menu To Access The Same.

**Three Dot Menu (Hidden Apps)**
![Screenshot_2022-07-18-20-15-33-40_39cdc23507af3cd1237ce5ff0636726d~2](https://user-images.githubusercontent.com/96917972/179543999-ea7a826f-2174-438c-857e-833173e985dd.jpg)

**Hidden App Drawer Page Option**
![Screenshot_2022-07-18-19-47-08-72_39cdc23507af3cd1237ce5ff0636726d~2](https://user-images.githubusercontent.com/96917972/179544265-626e2a8d-459c-4f10-a65a-956a6339fe1e.jpg)

Maybe Some Users Won't Like To Directly Access The Hidden App Drawer From The App Drawer, For Them A Toggle Can Can Be Provided In Lawnchair Settings To Not Show The Hidden Apps Option In The Vertical Three Dot Menu.

### Why would it be useful to add?

Not All User Hide Apps For Privacy, User Like Me To Keep The Apps Drawer Clean By Hiding Not Much Used Apps And Icon Packs & Widgets Apps, But Sometime Need To Access Them But Can't Easily Recall Which All Apps Are Installed After Sometime To Search It From App Drawer Search, So One Has To Go To Lawnchair Settings And Checkout Which All Apps Are Hidden

And Some User Don't Want Their Hidden Apps To Be Included In Search Results, It Might Be Useful For Them Aswell.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Attached Above

**Comment by DragonEggBedrockBreaking** [comment]
I think this is a a relevant and useful feature.
