### ISSUE TITLE
Ho to create folder on app drawer?

### ISSUE THREAD

**Issue by sombresu** [Deletescape-Media/Lawnchair#2781]
I've searched google found nothing. There's no categorization option anywhere. 

Lawnchair 12.10
Android 11
Miui 12.5

**Comment by yasanglass** [comment]
It's not possible on the current version.

**Comment by blogmangit** [comment]
please lawnchair team add this feature its been a while we really need this feature.

**Comment by Amorphous404** [comment]
Duplicate of #2471

**Comment by SuperDragonXD** [comment]
Actually mark as a duplicate of #2471
