### ISSUE TITLE
[BUG] Dragging App icons to create a folder adds a duplicate to the default home screen

### ISSUE THREAD

**Issue by rluetzner** [Deletescape-Media/Lawnchair#2784]
### Describe the bug

This happens when creating a folder on a home screen (or in the dock). When an App icon is dragged on top of another it creates or adds it to the folder, but will also generate a linked duplicate on the default home screen.
_Linked_, because removing the duplicate will also remove the App icon from the folder.

This only happens when creating a new folder or dropping an icon on a _closed_ folder. If a folder exists and I wait for the contents to be shown, I can add another icon correctly.

Right now that is also a possible workaround:
1. drag an icon on top of another to create a new folder,
2. drag the same icon again, but wait for the folder to open,
3. add it,
4. remove the duplicate icon from the default home screen.

### Steps to reproduce

1. Open the app drawer
2. Drag an App icon on top of another icon that already exists on a home screen (or in the dock).
3. A folder is created.
4. Navigate to the default home screen.
5. A duplicate of the App icon you dragged has been created.
6. Drag that to the top of the screen to remove it.
7. Look at the folder from before. The icon is gone. Possibly the folder as well.

### Expected behavior

The App icon should be added only to the folder. No duplicate should be created.

### Device information

- Device: realme 7
- OS: stock ROM Android version 11.0
- App version 12.1.0 Alpha 3 from F-Droid

**Comment by rluetzner** [comment]
Weird. I just tried it again and was unable to reproduce the issue. Maybe it's because I was running Lawnchair for the first time yesterday. Other than that I can't see what I did differently.

**Comment by dhirenvasnani** [comment]
This issue is fixed Latest debug (#999) version.
I tried to reproduce the issue but nothing happened

**Comment by omentic** [comment]
I also encountered this issue, running Lawnchair for the first time, on the latest alpha version. 

If it's fixed on devel then fantastic :+1:

**Comment by mauritsivs** [comment]
Alpha 4 still has this issue for me

**Comment by formula-spectre** [comment]
I am encountering the same problem; 
android 14, graphene OS, pixel 6a

**Comment by formula-spectre** [comment]
experiencing this with the lasted debug build (march, 07/03/24)
same phone
