### ISSUE TITLE
Please update material you searchbar background color

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#2791]
### Describe the feature

please correct the homescreen searchbar Material You background color ... the correct Android system color is N1-800 ... see attached image of current Pixel Launcher searchbar.

### Why would it be useful to add?

It properly matches material you. The old color code from Android 11 (N1-900) is just wrong and outdated.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![searchbar](https://user-images.githubusercontent.com/1809251/180623554-c47cb133-243e-4e69-b0e8-3626b252d601.png)

### Additional context

Thank You in advance.

**Comment by RikKoedoot** [comment]
Please rename the title to reflect your feature request
