### ISSUE TITLE
Please add open/closing animation API for non-root users

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#2793]
### Describe the feature

Please add the app open/closing animation API for non-root users.

### Why would it be useful to add?

This would make the user experience more pleasing to non-root users. See attached example.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![animation](https://user-images.githubusercontent.com/1809251/180626227-2c4b409b-fa27-4024-8fe2-a759691f2a9a.gif)

### Additional context

Example is from Hyperion Launcher. Animation API for non-root users.

**Comment by RikKoedoot** [comment]
Please rename the title to reflect your feature request

**Comment by Manu99it** [comment]
It existed before. Not from the start, but like in lawnchair 10 or 11, I don't remember correctly

**Comment by Manu99it** [comment]
. to keep open
