### ISSUE TITLE
Lawnfeed 3 not working

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#2794]
### Describe the bug

Lawnfeed 3 not working

### Steps to reproduce

1. Install Lawnfeed 3
2. Swipe Left
3. See error (no feed)

### Expected behavior

1. Install Lawnfeed 3
2. Swipe Left
3. See Google Feed

### Device information

- Device: [Google Pixel 5]
- OS: [stock ROM Android version 13 beta 4]
- App version: [12.1.0 Dev (1001)]
- Lawnfeed 3 version dev

### Additional context

Thank you in advance.

**Comment by RikKoedoot** [comment]
Please rename the title to reflect your feature request. Try restarting lawnchair

**Comment by iOSXPC** [comment]
Multiple restarts ... After swipe left ... feed opens only once then no more.

**Comment by metalfoxdev** [comment]
Go to lawnchair settings, home setting s and turn on feed

**Comment by iOSXPC** [comment]
That is already enabled, since install. It's the first thing I check.

**Comment by BenKmann** [comment]
I have the same Bug. Works only once, and it is activated in settings.
Also same versions installed.
Galaxy S20 FE Android 12.

**Comment by SuperDragonXD** [comment]
Late reply, but already answered in the FAQ page since this is a common issue: https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#lawnfeed-does-not-work. Closing this issue
