### ISSUE TITLE
[FEATURE] Add Some Few More Extra Gesture Triggers & Shortcuts 

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2797]
### Describe the feature

**Gestures:**

1) Swipe Up From Dock
→Seperate From Swipe Up Gesture
→ Present In Lawnchair v2

2) Swipe Left
→ Will Trigger If Google Feed Is Turned Off
→ Present In Nova Launcher

3) Swipe Right
→ Will Trigger Only
• If There A Single Homescreen Page
• At The Last Page If There Are Multiple Pages
• When Infinite Scroll Is Turned Off If Added In Future
(Currently Not Present)
→ Present In Nova Launcher

• And If Possible Add Infinite Scroll
→ Seamlessly Swipe Between First And Last Page
→ Present In Nova Launcher

4) Two Finger Swipe Up
→ Present In Nova Launcher

5) Two Finger Swipe Down
→ Present In Nova Launcher

**Addition Of Few For Gesture Controls:**

1) Open App Shortcut

2) Toggle On/Off Status Bar

3) Toggle On/Off Dock

4) Open Quick Settings (Notification Panel QS Tiles)

5) Trigger Google Assistant

### Why would it be useful to add?

Give More Control To Power Users

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Some Are Present In Lawnchair v2

And Some Of Them Are From Nova Launcher:
https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher

**Comment by Amorphous404** [comment]
#2285 - App Shortcuts

**Comment by Amorphous404** [comment]
#2045 - Point No 2

**Comment by Amorphous404** [comment]
#2473 - Point No 3

**Comment by icarusinthewings** [comment]
Commenting on the swipe left gesture- That would only be available on the first page, right?
Just allowing it to trigger the opening of an app would be sufficient to replace the feed, but it would be more convenient for it to be implemented like the Google feed.

**Comment by Amorphous404** [comment]
> Commenting on the swipe left gesture- That would only be available on the first page, right?
> Just allowing it to trigger the opening of an app would be sufficient to replace the feed, but it would be more convenient for it to be implemented like the Google feed.

Yes, only on a homescreen, will only work if the google feed is turned off.

Idk if you're aware but you can call google feed by swiping left, you'll need to install lawnfeed app to make it work.

**Comment by icarusinthewings** [comment]
> > Commenting on the swipe left gesture- That would only be available on the first page, right?
> > Just allowing it to trigger the opening of an app would be sufficient to replace the feed, but it would be more convenient for it to be implemented like the Google feed.
> 
> Yes, only on a homescreen, will only work if the google feed is turned off.
> 
> Idk if you're aware but you can call google feed by swiping left, you'll need to install lawnfeed app to make it work.

I know. I was talking about replacing the Google feed with a third party app (RSS Feed, etc.)

**Comment by Amorphous404** [comment]
> > > Commenting on the swipe left gesture- That would only be available on the first page, right?
> > > Just allowing it to trigger the opening of an app would be sufficient to replace the feed, but it would be more convenient for it to be implemented like the Google feed.
> > 
> > Yes, only on a homescreen, will only work if the google feed is turned off.
> > 
> > Idk if you're aware but you can call google feed by swiping left, you'll need to install lawnfeed app to make it work.
> 
> I know. I was talking about replacing the Google feed with a third party app (RSS Feed, etc.)

That's what my proposed idea is, so users can replace it with any of their apps/shortcuts/activities etc for swipe left instead of google feed, that way you would be able to set your own RSS feed when you swipe left:)

**Comment by icarusinthewings** [comment]
This will still be a helpful feature, so let's prevent this from becoming stale.

**Comment by icarusinthewings** [comment]
Still something needed

**Comment by ELY3M** [comment]
any update on this function?

**Comment by lavilao** [comment]
+1
