### ISSUE TITLE
[BUG] Search Bar Related Issues (12.1.0 Dev #1001)

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2798]
### Describe the bug

**1st Bug:**
When Search Bar Is Toggled Off For App Drawer, And Swipe Up Gesture Is Set To Open App Search, The Search Bar Is Invisible, One Can Still Search It But Can't See What's Being Typed.

![Screenshot_2022-07-24-17-12-26-89_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/96917972/180646008-ddfc7ef4-0e1b-46c0-9a30-80742f903512.jpg)

Solution: Even Though The App Search Bar Is Toggled Off For App Drawer, When The Gesture Is Set To Open App Search It Should Temporarily Show Up The Search Bar.

**2nd Bug:**
When Automatic Show Keyboard Is Toggled On, And Show Search Bar Is Toggled Off, The Show Keyboard Is Still On, Which Results The Same As App Search Gesture.

Solution: When Show Search Bar Is Toggled Off, It Should Also Disable The Automatic Show Keyboard

### Steps to reproduce

Describe The Bug Section Is Self Explanatory 

### Expected behavior

Mentioned Above

### Screenshots

Posted Above

### Device information

- Device: OnePlus 10 Pro
- OS: OxygenOS 12.1
- App version 12.1.0 Dev #1001

**Comment by kahanzammi** [comment]
I believe when the search bar in app drawer is turned off, related functions should be globally disabled (gesture, keyboard etc).

**Comment by Amorphous404** [comment]
> I believe when the search bar in app drawer is turned off, related functions should be globally disabled (gesture, keyboard etc).

That's what I mentioned, only when an app search is set to a gesture, the search bar should show up, if it's globally disabled one wouldn't be able to do app search completely

**Comment by Amorphous404** [comment]
Not fixed :(
