### ISSUE TITLE
Pixel line under dock remains transparent on S8

### ISSUE THREAD

**Issue by anxnenko** [Deletescape-Media/Lawnchair#280]
On Samsung Galaxy S8, if choosen white, dark or black theme, especially with blur option, there's a "line" with an height of 1/2 pixels that remains "transparent": the effect applied on the dock (white, black or dark, and blurred) leave this "unthemed" Pixel line under the dock.

It's clearly visible with bright backgrounds and dark/black theme with blur effect applied...and the bug remains even with app drawer on screen.

It seems that the dock isn't completely "placed" on the bottom of the screen...

Hope my explaining was clear. Here's a screenshot with the bug, in order to let you see what I'm talking about:
https://drive.google.com/file/d/0B5xlR6HIUv23U0JYWHVxVmJ6VGc/view?usp=drivesdk

**Comment by anxnenko** [comment]
NOTE: this issue appear to be present only if the S8 resolution is set to FHD+.

**Comment by AxiK101** [comment]
Whats your icon pack man?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by anxnenko** [comment]
It's "Antimo" from Sikebo Giraz.

**Comment by fonix232** [comment]
@AxiK101 please try to keep unrelated questions out of the issue ticket
system!

**Comment by AxiK101** [comment]
@fonix232 Sorry mate, my bad

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mirthel** [comment]
Same issue here, but it's also present in all the stock resolutions, I only noticed once when I was switcing themes, but I go for an all black theme so I don't see it very often, but wanted to add that it is present in all resolutions, and as OP said, it's when blur is activated in dark mode.
