### ISSUE TITLE
[FEATURE] Add option for shadows

### ISSUE THREAD

**Issue by keyjeyelpi** [Deletescape-Media/Lawnchair#2800]
### Describe the feature

Add an option in settings > general to enable/disable shadows for both icon packs and lawnicons.

### Why would it be useful to add?

Uniformed look since icon packs have shadows whereas lawnicons don't, which could be clearly seen on some material you icon.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Nova Launcher

**Comment by Amorphous404** [comment]
Yes, please make this happen, lawnicons without Shadows looks odd

![Screenshot_2022-08-23-11-20-54-39_3822ac0e29cfec8970059bb21d01f05e~2.jpg](https://user-images.githubusercontent.com/96917972/186080406-c3955211-88db-4117-91d9-c579451830da.jpg)

**Comment by Amorphous404** [comment]
It seems It's a duplicate of #2695

**Comment by yasanglass** [comment]
It is a duplicate but since this has better formatting, ill close the other one.
