### ISSUE TITLE
[BUG] Lawnchair Crashes when interacting with widgets

### ISSUE THREAD

**Issue by abdalmoniem** [Deletescape-Media/Lawnchair#2804]
### Describe the bug

When interacting with widgets that have dedicated buttons for doing some actions, lawnchair crashes. for example using next, previous and play/pause buttons on a music app widget. clicking on the widget itself opens the application with no errors.

here's the crash log url: https://bin.kv2.dev/~62e3d76b08bb984d9dc6383d
![Screenshot_20220729-144940_Lawnchair](https://user-images.githubusercontent.com/11904264/181764892-36a95c69-a8e7-4b8b-a0b7-fb6b56672cef.png)

N.B. this issue only happens if the phone is rooted, otherwise everything works fine.

### Steps to reproduce

1. Add widget with buttons on homescreen (e.g. music app widget)
2. Tap on any button on the widget (e.g. play/pause on a music app widget)
3. See error

### Expected behavior

Buttons work on widgets

### Screenshots

![Screenshot_20220729-144940_Lawnchair](https://user-images.githubusercontent.com/11904264/181765380-2335c76a-f1fb-4e78-889d-85cba12de433.png)

### Device information

- Device: OnePlus 6T
- OS: AwakenOS 2.9 custom ROM build 15072022 Android 12.1
- App version: 12.0.0 Alpha 5

### Additional context

only on rooted phones, whether the app is given SU permissions or not.

**Comment by steewbsd** [comment]
Can reproduce with OpenWeather widget, pressing refresh button. In my case, error seems to be different, but producing same result.
![Screenshot_20220801-171503_Lawnchair](https://user-images.githubusercontent.com/26441684/182182350-8adc23ad-7fda-4152-93de-d4fba3c51daa.png)

**Comment by abdalmoniem** [comment]
fixed in lawnchair 12 Alpha 4
