### ISSUE TITLE
Blur Radius

### ISSUE THREAD

**Issue by p0nkr4t** [Deletescape-Media/Lawnchair#281]
https://youtu.be/G4wAcwPp5ww

**Comment by AxiK101** [comment]
Yeah, ths is also happening on icon & text sizes. If you let them at 100% they go at 98%. Also some percentages don't appear in scale like the video shows. Definitely a bug 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
