### ISSUE TITLE
[FEATURE] Add option to increase size of At a Glance 

### ISSUE THREAD

**Issue by dercodeling** [Deletescape-Media/Lawnchair#2812]
### Describe the feature

A slider preference in the AaG settings that allows users to increase the size of this widget.

### Why would it be useful to add?

I use a 6×10 grid to be able to move widgets more precisely and to mimic a second dock row while that feature isn't here yet, but doing so means the AaG-Widget is tiny and barely readable.
![image](https://user-images.githubusercontent.com/66414314/182866916-39bb5539-d1ec-4ef5-a463-b0d545bdb199.png)

Of course, another option would be to make the widget size absolute and independent of the grid size.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Quick mockup of how it might look:
![Unbenannt](https://user-images.githubusercontent.com/66414314/182870831-28dfbab9-7437-4612-b402-6aff9da9d58d.png)

### Additional context

Note: this was partially possible in V2 as back then the AaG-widget was just a regular home screen widget that could be resized to a certain extent, but it wasn't an available setting so I picked not available above.

**Comment by SuperDragonXD** [comment]
> Note: this was partially possible in V2 as back then the AaG-widget was just a regular home screen widget that could be resized to a certain extent, but it wasn't an available setting so I picked not available above.

It is also possible actually, as seen here:
https://user-images.githubusercontent.com/70206496/182884076-3c508cad-3dbb-4e76-af24-8f32a3682c18.mp4

**Comment by dercodeling** [comment]
Ahh, thanks! That works for me
