### ISSUE TITLE
Option To Clip Icons Inside Folder Shape

### ISSUE THREAD

**Issue by rustzz** [Deletescape-Media/Lawnchair#2813]
### Describe the feature

Implement squared folders

### Why would it be useful to add?

If in folder located >2 applications then icon hover folder border

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Squircle folder icon (get shape from lawnchair "Home settings">"General">"Icon shape")
![sketch1659722381743.png](https://user-images.githubusercontent.com/74064444/183134777-3e9814c5-91f5-47a4-8f5b-18df25682b35.png)

Sorry for drawing

**Comment by Amorphous404** [comment]
Ah, what you're trying to request is for an option to clip icons inside the folder shape, just like this one
https://github.com/LawnchairLauncher/lawnchair/issues/2852#issuecomment-1222800308

Note: it will be better if you can change the title to "Option To Clip Icons Inside Folde Shaper"

**Comment by rustzz** [comment]
> Ah, what you're trying to request is for an option to clip icons inside the folder shape, just like this one [#2852 (comment)](https://github.com/LawnchairLauncher/lawnchair/issues/2852#issuecomment-1222800308)
> 
> Note: it will be better if you can change the title to "Option To Clip Icons Inside Folde Shaper"

yep, title edited
