### ISSUE TITLE
[FEATURE] / [BUG] Better handling of "At a Glance Position"

### ISSUE THREAD

**Issue by kotah81** [Deletescape-Media/Lawnchair#2817]
### Describe the feature

In a lot of device i've installed Lawnchair on, the At a Glance context wasn't properly aligned. :/
I guess a good way of dealing with it is let user move it to fit better.

It would also be great for users that would want to move it to the middle or right.

### Why would it be useful to add?

More customisation!

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### My Concept : (made using Pixel's At A Glance)

![LawnchairGlanceConcept](https://user-images.githubusercontent.com/104696918/183525011-85301b2d-44ea-4f7b-a4d2-72ce2a81a975.png)

### How it normally looks :

![Screenshot_20220809-002225_Lawnchair](https://user-images.githubusercontent.com/104696918/183525322-9c100919-4fd3-410a-b918-a14632116af8.png)

### Additional context

The concepts shots were taken on a Xiaomi Mi 11! (codenamed venus)
Using the latest Lawnchair 12 release at the moment. (Alpha 4)

**Comment by Amorphous404** [comment]
You can already do that in Lawnchair 12.1 by turning off the at the glance widget and adding it as a widget from widget page
