### ISSUE TITLE
[BUG] Incorrect fastscroll animation 

### ISSUE THREAD

**Issue by Leyzymoy** [Deletescape-Media/Lawnchair#2823]
### Describe the bug

Incorrect fastscroll animation if use custom grid settings

### Steps to reproduce

1. Go to settings/home screen/layout
2. Click on Home screen grid 
3. Choose custom values
4. Going to menu apps and check fastscroll

### Expected behavior

Correct fastscroll animation for all values in grid

### Device information

- Device: Xiaomi Redmi Note 7
- OS: Android 10, MIUI 12.5
- App version 12.1 Dev build 1019

**Comment by SuperDragonXD** [comment]
Could you provide a screen recording or similar?

**Comment by Leyzymoy** [comment]
> Could you provide a screen recording or similar?

yes i can, but not here due to file size limit, i can send you video in telegram if you don't mind 
@Leyzymoy my id in tg

**Comment by Leyzymoy** [comment]
Bug partially fixed in Dev #1025
Thank
