### ISSUE TITLE
Alpha 4: won't reload dynamic icons after launcher restart

### ISSUE THREAD

**Issue by asaada83** [Deletescape-Media/Lawnchair#2826]
# Description:
This is a regression from alpha 3. Previously when using a material you dynamic icons pack a launcher restart was enough to reload the dynamic icons and match them to a new wallpaper. With the following dev releases and also in alpha 4 a launcher restart is no longer enough. Now you have to apply a different icon pack and reapply the dynamic icon pack for it to take affect.

# Devices: 
Samsung S22 and Pixel 6
# Steps to reproduce:
* apply material you dynamic icon pack
* change wallpaper
* (Samsung S22 only) change color palette to match wallpaper
* restart lawnchair (home settings -> 3 dots -> restart lawnchair)

**Comment by topsy-turvy99** [comment]
#2866

**Comment by SuperDragonXD** [comment]
Superseded by #2882; icon refreshing issues will be moved to that issue for better organization.
