### ISSUE TITLE
Feature request: granular control over dark/black theme

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#283]
The ability to choose what componenets of the ui are affected by dark/black theme.
I for instance I like dark theme on everything except for pill widget and folder icons, which i would prefer to keep on light theme. 
perhaps we can have options for:
-app drawer
-folder background
-folder icon 
-shortcuts background
-etc...

**Comment by LinuxLlama** [comment]
I agree! I'd love to use the dark theme with the white shortcuts and search bar.
