### ISSUE TITLE
[FEATURE] Allow User To Manually Adjust Dock Padding/Whitespace

### ISSUE THREAD

**Issue by alabotski** [Deletescape-Media/Lawnchair#2832]
### Describe the feature

When I disabled search in dock
There a lot of free space

### Why would it be useful to add?

It will be more pretty have more compact dock without search

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220811_173644](https://user-images.githubusercontent.com/439337/184210518-b7e6465f-1527-43b2-9415-66fc5b49f4da.png)

**Comment by Amorphous404** [comment]
This can be achieved by providing an option to manually adjust the padding of dock just like Nova launcher

![IMG_20220822_230130.jpg](https://user-images.githubusercontent.com/96917972/185983755-fdb625b2-ad9c-4881-bf58-f38a90be23be.jpg)

This feature can be added along with the other dock related customization requested in #2775

Note: @alabotski it will be great if you can change the title to " Allow User To Manually Adjust Dock Padding/Whitespace"

**Comment by Amorphous404** [comment]
#1745

**Comment by Amorphous404** [comment]
#2215

**Comment by source124** [comment]
Please reopen this. It should **also** apply to the space above the dock. Lawnchair 2 was very good in this regard.
