### ISSUE TITLE
[BUG] AppDrawer

### ISSUE THREAD

**Issue by alabotski** [Deletescape-Media/Lawnchair#2833]
### Describe the bug

When I open app drawer
Status bar is transparent
When I scroll it menu status bar become gray

### Steps to reproduce

1. Go to 'AppDrawer'
2. See status bar
3. Scroll down to
4. See error (status bar)

### Expected behavior

status bar should stay transparent

### Screenshots

![Screenshot_2022-08-11-20-10-49-2042561648](https://user-images.githubusercontent.com/439337/184217322-160da9f4-7119-49fa-93ba-7fdb8afb46d8.png)
![Screenshot_2022-08-11-20-10-55-0960279123](https://user-images.githubusercontent.com/439337/184217329-12c300de-0196-4246-8218-1426651c6d1a.png)

### Device information

- Device: Lenovo Legion
- OS: android 10
- App version [Lawnchair 12.1.0 Alpha 4](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4)

**Comment by Amorphous404** [comment]
Now toggle off the Show Status Bar under lawnchair settings>home and check the status bar area 🥲

**Comment by alabotski** [comment]
@topsy-turvy99 
I turned it off but it got worse

![image](https://user-images.githubusercontent.com/439337/186299924-56c54d6e-3d0d-4e6b-b4a8-aac0c39f9cf9.png)
![image](https://user-images.githubusercontent.com/439337/186299939-ba8282ff-423b-42d0-92fd-59ae306893ea.png)
