### ISSUE TITLE
(Sugestion) At a glance

### ISSUE THREAD

**Issue by Zzzinko** [Deletescape-Media/Lawnchair#2834]
Make the at a glance widget an separated app to make it usable on another launchers.

**Comment by Golde2341** [comment]
You can add at a glance widget if you install lawnchair and add lawn chair widget to the another launcher![Screenshot_20220813-170605_Lawnchair.png](https://user-images.githubusercontent.com/85361118/184512171-2eadb2ca-fae3-402e-8f4e-64f9741a6781.png)

**Comment by kahanzammi** [comment]
Are you sure? I can't see Lawnchair widget when I switch to Pixel launcher. Tested in few phones with different launchers. Lawnchair widget only appears when you are on Lawnchair.

![Screenshot_20220814-154612_Pixel Launcher](https://user-images.githubusercontent.com/105884763/184535404-53e50fc6-0cb4-4cc3-a593-f33efc92c2f5.png)

**Comment by Amorphous404** [comment]
> Are you sure? I can't see Lawnchair widget when I switch to Pixel launcher. Tested in few phones with different launchers. Lawnchair widget only appears when you are on Lawnchair.
> 
> ![Screenshot_20220814-154612_Pixel Launcher](https://user-images.githubusercontent.com/105884763/184535404-53e50fc6-0cb4-4cc3-a593-f33efc92c2f5.png)
> 

That not possible, idk why @Golde2341 is confusing the users seeking for help

**Comment by Golde2341** [comment]
> > Are you sure? I can't see Lawnchair widget when I switch to Pixel launcher. Tested in few phones with different launchers. Lawnchair widget only appears when you are on Lawnchair.
> > 
> > ![Screenshot_20220814-154612_Pixel Launcher](https://user-images.githubusercontent.com/105884763/184535404-53e50fc6-0cb4-4cc3-a593-f33efc92c2f5.png)
> > 
> 
> That not possible, idk why @Golde2341 is confusing the users seeking for help  

Sorry my mistake

**Comment by Amorphous404** [comment]
Duplicate of #2662
