### ISSUE TITLE
Groups or Folder on App Drawer.

### ISSUE THREAD

**Issue by blogmangit** [Deletescape-Media/Lawnchair#2835]
### Describe the feature

Create folder inside app drawer like separate groups. 

### Why would it be useful to add?

Useful to sort different apps.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

This feature existed in v2

**Comment by msfjarvis** [comment]
You've already commented on https://github.com/LawnchairLauncher/lawnchair/issues/2781, please do not open duplicate issues. Spamming like this does not change the priority of a feature.
