### ISSUE TITLE
[FEATURE]  Dynamic widget colors based on their position on the wallpaper 

### ISSUE THREAD

**Issue by kahanzammi** [Deletescape-Media/Lawnchair#2838]
### Describe the feature

One of my favorite features of Pixel launcher is it's ability to dynamically set widget colors based on their position on the home screen and wallpaper color of that location. Note: only material you enabled widgets supported. Would like to see same in Lawnchair. Screenshot is for reference.

![Screenshot_20220814-150700_Pixel Launcher](https://user-images.githubusercontent.com/105884763/184534428-7dc812c5-63bc-4842-a7f2-5936f58e89ba.png)

### Why would it be useful to add?

That brings one of the unique Pixel features to Lawnchair.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Screenshot attached above.

**Comment by pacjo** [comment]
Hey, can we reopen this? Maybe it'd be easier after latest launcher3 merge.
