### ISSUE TITLE
Remove apps from menu

### ISSUE THREAD

**Issue by Leyzymoy** [Deletescape-Media/Lawnchair#2839]
### Describe the feature

If enabled, the delete application button disappears from the top of the screen and appears when you long press in the pop-up menu: Settings | Widgets | About | Remove app 

### Why would it be useful to add?

This method of deletion is much more convenient on large screens

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

p-o-p from CPL Launcher
![IMG_20220814_180509](https://user-images.githubusercontent.com/50266837/184540738-4f73c8ff-ff02-4fbd-afee-70069787028a.jpg)

**Comment by Amorphous404** [comment]
![IMG_20220823_091725.jpg](https://user-images.githubusercontent.com/96917972/186065399-b3cf95f3-e961-4675-8d19-539f08aeb1a0.jpg)

Suggestion: The option can be added under Lawnchair Settings>Home
