### ISSUE TITLE
[FEATURE] Tweaks To Improve Overall Experience With The Folder

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2843]
### Describe the feature

Add A Three Vertical Dot At The Bottom Of The Folder That Gives User The Following Options:

1) ~~Select Apps~~
- ~~Allows User To Select The Apps Directly From The Folder, Without Having To Drag And Drop Every Apps That User Wants In A Folder)~~
- ~~Available In Nova Launcher~~

2) Sort Apps
- Tapping On It Will Sort The Apps In Folder A-Z, Re-tapping On It Restore User Set Order
- Available In Nova Launcher

3) Rename Folder
- Repostion It To Three Vertical Dot Menu
- Currently We Can Directly Tap On The Name After Opening The Folder But I Hate The Sometimes When User Touch On It Accidentally, It Pulls Up The Keyboard/Sometimes Even Renamed It
- Available In Nova Launcher

4) Cover Mode
- To Set The Tap Action To Open The First App In The Folder.
- Swipe Up To Open The Folder
- Available In Lawnchair v2

### Why would it be useful to add?

Will Help User In Organising Their Setups With Ease (Less Actions) And Improve Overall Experience With The Launcher.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Three Vertical Dot Button
![IMG_20220815_000038](https://user-images.githubusercontent.com/96917972/184550839-d5ab0ac4-60f8-4a19-8c85-dbf445775c87.jpg)
Vertical Dot Menu Options
![IMG_20220815_000213](https://user-images.githubusercontent.com/96917972/184550842-15619746-d644-4d89-94e3-68c12a0649e1.jpg)
Select Apps For Folder Selection Screen
![IMG_20220815_000327](https://user-images.githubusercontent.com/96917972/184550850-4930e169-e9c9-412a-b519-d7a1887b25f9.jpg)
Cover Mode
![Screenshot_2022-08-15-00-25-27-95_3b881d4c06d4cbc1b5e5ddba75e2aac5](https://user-images.githubusercontent.com/96917972/184551022-9d17a8ba-12d0-493f-9d8c-16cb6d70963d.jpg)

**Comment by Rootzpower** [comment]
Sort option will be very useful

**Comment by bitokulo** [comment]
Why to put ~~it~~ renaming in vertical dots instead of directly tapping on the folder's name?
