### ISSUE TITLE
[BUG] Click on an icon in the Dock opens the Drawer

### ISSUE THREAD

**Issue by Verhoeckx** [Deletescape-Media/Lawnchair#2849]
### Describe the bug

When I click on a icon in the Dock it opens the Drawer instead of opening the application I clicked on.   

The issue doesn't always occur. I guess it happens 50% of the time.  
I don't think it's me being clumsy; I never had this issue in the default Android Launcher,

### Steps to reproduce

**Preconditions:**
- Lawnchair is installed and set as the default Android Launcher.
- The Desktop and the Dock are visible.
- Both contain application icons.

<br>

**Steps to reproduce the behavior:**
1. Click on app icon in the Dock.
2. The Drawer is opened.

### Expected behavior

I expected the application that I clicked on to be launched (for example Whatsapp).

### Device information

- Device: Fairphone 4
- OS: Android version 11.0
- App version: 2.0-2589

### Additional context

First I had two rows in the Dock and I thought that was the problem, but I now have set the Dock to one row and the issue still occurs.

**Comment by dhirenvasnani** [comment]
@Verhoeckx  The Lawnchair Version you mentioned is no longer supported

**Comment by Verhoeckx** [comment]
_Oh, sorry, you are right!_

 I installed it with F-Droid and I thought I had the latest. Maybe remove it from F-Droid or update it?

Thanks for the feedback!

**Comment by dercodeling** [comment]
@Verhoeckx Actually, the new version is also on Fdroid, but as a separate app, I imagine part of the reason being the team and package name changes.

**Comment by Verhoeckx** [comment]
What do you mean with 'as a separate app'?

I can't find the new version of Lawnchair in the default F-Droid repository.

**Comment by dercodeling** [comment]
Oh, sorry, you're right, it's not on the default Fdroid repo. It's on "[IzzyOnDroid F-Droid Repo](https://apt.izzysoft.de/fdroid/repo/app.lawnchair_12010005.apk)" which my Fdroid client shows as well.

**Comment by Verhoeckx** [comment]
Ah, now I can find it!

I already installed Lawnchair through the website so I'm not going to use the LzzyOnDroid repository.

Thanks for helping me! I will now close the issue.
