### ISSUE TITLE
[QUESTION] I may need some support with old devices.

### ISSUE THREAD

**Issue by SteveZMTstudios** [Deletescape-Media/Lawnchair#2851]
### Describe your question or ask for support

as you know,i am using Android 6.0.1.
but the newest alpha test mode is too advanced to install into my device.
![IMG_20220818_202506](https://user-images.githubusercontent.com/98326195/185394177-4aeac447-0e72-499f-9d61-756fdf372376.jpg)
if i try installing the latest apk file, my package installer(com.android.packageinstaller) will go on strike.
(There was a problem parsing the package.)
So could i still find the latest alpha version for my device?
Thank you.
ps.Due to the domestic network environment and the policies of our government, I can't publish it on discord and telegram

**Comment by SteveZMTstudios** [comment]
You may ask why I don't upgrade my device to the latest version?
Well, since my device provider has stopped supporting this device, I need to install an lite launcher.
Most people recommend Lawnchair launcher in our bbs.
And the launcher made by our equipment provider is not very good.(It will take up too much memory.)

**Comment by m-p-3** [comment]
Have you considered flashing a custom ROM, notably a LineageOS ROM for your device?

**Comment by kahanzammi** [comment]
I recommend you to try version 2 (https://www.apkmirror.com/apk/deletescape/lawnchair/).
You need at least Android 8/9 to run latest builds.

**Comment by SteveZMTstudios** [comment]
Yes, I tried.but there's a problem of unlock bootloader.
My OEM didn't give to any customers 
Thanks all of yours idea, I'll try installing on my devices.
(๑╹ヮ╹๑)ﾉ

**Comment by SuperDragonXD** [comment]
Well, as stated by the above, Lawnchair 12.1 only supports Android 8.1 and above. You can use Lawnchair 2 instead (supports Android 5+). Closing this issue
