### ISSUE TITLE
Folder Icon

### ISSUE THREAD

**Issue by bappa555** [Deletescape-Media/Lawnchair#2852]
### Describe the bug

On Oxygen OS 12, for the folder icon, also are showing out side of the folder. This is not the case with Lawnchair 2.
It looks much better in the old version. Can any one make the folder icon like Lawnchair 2.

![Screenshot_2022-08-20-10-18-44-85_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/29393112/185729397-cffa9cf0-f12b-46f2-af94-3a44336b1b0e.png)

### Steps to reproduce

1. On Oxygen OS 12, create a folder on desktop.
2. Set the icon shape to circle
 It should reproduce the issue. It may reproduce on other devices also, but I don't have any other device to test.

### Expected behavior

Icons of Apps within the folder should be within the folder only.

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

**Comment by Amorphous404** [comment]
First of all what you're requesting is a feature and not a bug and has nothing to do with your stock Launcher, in Lawnchair 12 by default the icons overlap the folder shape.

Second, i don't understand why you're referring OxygenOS 12, where as in device information you mentioned Google Pixel 6.

Now coming to your request, what your asking is for is allow user to Clip The Icons Inside The Folder, Which can be added inside Lawnchair Settings>Folder

![IMG_20220822_225013](https://user-images.githubusercontent.com/96917972/185999721-217753d8-2cfc-41ac-a6fe-2d586c47722a.jpg)
Demonstration from Nova Launcher.

Note: Kindly Edit The Post And Make It Clear Or Recreate A Fresh Request With Feature Request Template

**Comment by Amorphous404** [comment]
And it seems it's a duplicate of #2813
