### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by techlxrd** [Deletescape-Media/Lawnchair#2855]
### Describe the bug

If I add a website Shortcut to my homescreen it says App isn't installed

### Steps to reproduce

1. Go to 'a Browser'
2. Click on 'Add webpage to homescreen'
3. Open webpage shortcut from your homescreen

### Expected behavior

Normally it will open the webpage from the shortcut like an app. 

### Screenshots

No screenshot

### Device information

- Device: [Huawei Y5 2019] 
- OS: [stock ROM Android version 9.0]
- App version [e.g. 12.1.0 Alpha]

### Additional context

I hope it will be fixed soon

**Comment by yasanglass** [comment]
Please create an issue with an appropriate title (and fill out the issue form)
