### ISSUE TITLE
[FEATURE] Add rounded edges to recent app windows

### ISSUE THREAD

**Issue by ORafaelBr** [Deletescape-Media/Lawnchair#2857]
### Describe the feature

They are rounded edges that would be seen in the recent apps window, just like the original version of Android 12

### Why would it be useful to add?

I know that the purpose of the app is to bring the Android 12 home screen, this feature will bring even more of the new look of Android

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220821-084655-814](https://user-images.githubusercontent.com/111688437/185791636-98050e9e-c193-4fc6-aa74-1dc9481f0637.png)

the feature would appear in the window shown above but instead of the border being square it would be rounded

### Additional context

The feature is just a visual improvement to make it look more like Android 12

**Comment by SuperDragonXD** [comment]
What's your Android & Lawnchair version? If I remember correctly, Lawnchair 11 Alpha 6+ should have an option to customize the rounded corners (if you have QuickSwitch)

**Comment by ORafaelBr** [comment]
> What's your Android & Lawnchair version? If I remember correctly, Lawnchair 11 Alpha 6+ should have an option to customize the rounded corners (if you have QuickSwitch)

Lawnchair 12.1.0 Alpha 4

**Comment by SuperDragonXD** [comment]
If you have QuickSwitch, simply change the settings at Home Settings > Recents as seen below:

![Screenshot_2022-08-21-21-19-51-70_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/70206496/185792846-711f8c18-0040-4d89-bd79-7c00f9a89aff.jpg)

Otherwise, it can't be customized unfortunately

**Comment by SuperDragonXD** [comment]
Closing since I have already stated how to change the rounded corners.
