### ISSUE TITLE
Change folder shape

### ISSUE THREAD

**Issue by xmha97** [Deletescape-Media/Lawnchair#2858]
### Describe the feature

Change folder shape to rectangle

### Why would it be useful to add?

Because all of my icons is rectangle.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

I think on the Nova launcher I can change shape of folders

**Comment by RikKoedoot** [comment]
Folders follow icon shape, change your icon shape to square in lawnchair settings
