### ISSUE TITLE
[DISCUSSION] Home Screen for changing UI 

### ISSUE THREAD

**Issue by William150722** [Deletescape-Media/Lawnchair#2860]
### About this discussion

Hi all, I wonder to know is that possible to change the position of search bar in Home Screen from bottom to top? 

![Screenshot_20220822-133028_Lawnchair](https://user-images.githubusercontent.com/111726325/185846745-e4502466-85be-4db7-85c7-773376518ae9.jpg)

Furthermore, I wanted to know how to hide the date time there as well. Thanks all.

**Comment by Amorphous404** [comment]
You already requested it in #2862 with a proper title, better to close this ticket
