### ISSUE TITLE
[FEATURE] Make Lawnchair Search Bar Available As Widget

### ISSUE THREAD

**Issue by William150722** [Deletescape-Media/Lawnchair#2862]
### Describe the feature

Can it possible to change the position of the search bar?

### Why would it be useful to add?

So far just able to show or hide the search bar wonder if possible to add a setting to allow change position of the search bar.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220822-133028_Lawnchair](https://user-images.githubusercontent.com/111726325/185901681-ba1900c7-6804-4a52-a9c1-0c0e2b0c7535.jpg)

### Additional context

Furthermore, can also hide the date and time at the home screen there as well.

**Comment by Amorphous404** [comment]
![IMG_20220822_224611.jpg](https://user-images.githubusercontent.com/96917972/185980612-573fb57b-c685-416c-b715-0f21622fa2b0.jpg)
Demonstration From Nova Launcher

I think it's possible by making the search bar available as a widget just like the Lawnchair At The Glance Widget.

**Comment by William150722** [comment]
Hi @topsy-turvy99 thanks for the reply, I wonder how to archive it? 

val enableHotseatQsb = BoolPref("pref_dockSearchBar", true, restart) -> to set a flag to false to hide the search bar but no setting to move the dock search bar.

Kindly give some advise on customise it. Thanks.

**Comment by Amorphous404** [comment]
The feature is not yet added in Lawnchair 12.1.0, i just posted a screenshot from nova launcher to demonstrate the feature

Edit: It will better if you rename the title to "Make Lawnchair Search Bar Available As Widget"

**Comment by William150722** [comment]
Hi @topsy-turvy99 noted on this. Thanks for your help.

**Comment by William150722** [comment]
Hi @topsy-turvy99 is this features added? Make Lawnchair Search Bar Available As Widget
