### ISSUE TITLE
Search bar replace on dock bar

### ISSUE THREAD

**Issue by ShojibSarsilmaz** [Deletescape-Media/Lawnchair#2863]
### Describe the feature

Please add this option to replace widget on search bar in dock bar.

### Why would it be useful to add?

It's more more Beautiful and useful

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220822_174057](https://user-images.githubusercontent.com/91554795/185914481-1e84cfa3-2571-433f-b60a-646119f3f526.jpg)

### Additional context

My English so bad any mistake please forgive

**Comment by Amorphous404** [comment]
Indeed it will be a great feature to add, i already requested along with some other dock related customization in #2775 (Point No 4)
