### ISSUE TITLE
[FEATURE] List Of All Icon Packs That Should Auto Refresh When It Triggers Changes i.e Day/Night & Dynamic (System Color Pallete) (Android 12+)

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2866]
### Describe the feature

There are few icon packs available in Play Store that supports/changes based on system settings i.e day/night theme, Dynamic Icons that follows system color pallet (Android 12+)

There are few launchers out there that already supports auto refresh of this icon packs i.e Hyperion Launcher, Niagara Launcher, AIO Launcher etc.

It will be great if Lawnchair also joins the list.

So i'm sharing all the list of icon packs and their package name as well that should auto refresh when it register changes:

**List Of Day/Night Icon Packs:**

1) Pix Minimal Black/White
- com.pashapuma.pixminimal.iconpack

2) Pix Monochrome
- com.pashapuma.pix.material.mono

3) Lavien Adaptive Black/White
- osmanonurkoc.lavien.black.white

Android12+ (Day/Night + Changes Color Too Based On Material You)

4) Pix Material You Light/Dark
- com.pashapuma.pix.material.you.dark

5) OneYou Icons
- com.pashapuma.oneyou.icons

6) Dynamic Material You
- iconpack.onsurface.monet

7) Lavien Adaptive For You
- osmanonurkoc.lavien.foryou

8) Lavien Adaptive For You Outline
- osmanonurkoc.lavien.foryou.outline

**List Of Material You (Monet) Based Icon Packs (Android12+):**

1) Pix Material You Icons
- com.pashapuma.pix.material.you.iconpack

2) Pix Material You Light/Dark
- com.pashapuma.pix.material.you.dark

3) OneYou Icons
- com.pashapuma.oneyou.icons

4) Dynamic Material You
- iconpack.onsurface.monet

5) Dynamic Light
- iconpack.onsurface.monet.light

6) Dynamic Dark
- iconpack.onsurface.monet.dark

7) Lavien Adaptive For You
- osmanonurkoc.lavien.foryou

8) Lavien Adaptive For You Outline
- osmanonurkoc.lavien.foryou.outline

### Why would it be useful to add?

It's involves a quite a few steps a user need to perform to refresh the icons everytime and it's tedious

One Has To Go To Lawnchair Settings>General>Icon Style>Switch To Another Icon Pack>Then select the same icon pack again. 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

*

**Comment by topsy-turvy99** [comment]
@yasandev there are 3-4 request regarding the auto refresh icon thing, so i created a new ticket, listing all the app name along with their package name, maybe you can merge all these to reduce the duplicates for the same issue

Thank You

**Comment by SuperDragonXD** [comment]
Closing this issue and moving contents as a reply to #2882.
