### ISSUE TITLE
[BUG] Auto Adaptive Icons Delays In Refreshing The Icons

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2868]
### Describe the bug

When Any Change Is Made To Auto Adaptive Icons i.e Toggling On/Off Auto Adaptive Icon Or Changing Background Lightness, It Doesn't Reflect The Changes Instantly, Sometimes Even Launcher Restart Doesn't Help.

Fix: Change Icon Shape To Refresh The Icons

### Steps to reproduce

1. Go to 'Lawnchair Settings'
2. Click on 'General'
3. Scroll down to 'Auto-Adaptive Icons' & Make Any Changes
4. See The Changes Doesn't Instantly Reflect On The Launcher 

### Expected behavior

It Should Instantly Refresh The Icons & Reflect The Changes

### Screenshots

Check The Time Difference, It Doesn't Auto Refresh
![Screenshot_2022-08-23-14-11-48-66_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/96917972/186114214-67c3eae2-5875-49dd-a81e-f77ac99062f3.jpg)
![Screenshot_2022-08-23-14-14-28-37_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/96917972/186114253-88391778-789b-41b7-a93e-92150467a989.jpg)

### Device information

- Device: [OnePlus 10 Pro]
- OS: [Oxygen OS12.1 Android 12]
- App version [12.1.0 Dev Build 1048]
- This Issue Persist On Stable Build Too

**Comment by SuperDragonXD** [comment]
Superseded by #2882; icon refreshing issues will be moved to that issue for better organization.
