### ISSUE TITLE
Icon creation bug 

### ISSUE THREAD

**Issue by Leyzymoy** [Deletescape-Media/Lawnchair#2873]
### Describe the bug

When moving an application from the menu to a folder, sometimes it happens that another application icon is created on the home screen

### Steps to reproduce

1. Go to menu apps
2. LongClick to any app
3. add to any home screen folder 
4. See error on the Home screen 

### Expected behavior

creating an icon in a folder without randomly creating an icon on the home screen 

### Device information

- Device: Xiaomi Redmi Note 7
- OS: Android 10, MIUI 12.5
- App version: 12.1.0 #1053

**Comment by SuperDragonXD** [comment]
Could you send a video explaining this? Thanks

**Comment by louisamand** [comment]
Yes I do have the same problem.
From app drawer drag and drop an app inside of an existing folder of the home screen and the icon will duplicate: one icon will go in the folder and another in the home page (sometimes overlapping other icons).
- Pixel 6 on Android 13
