### ISSUE TITLE
[FEATURE] Change At The Glance Date & Time Format & Show Upcoming Alarm 

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2874]
### Describe the feature

Current Format With Date Only: ✅
EE , MMM d
(Wed, Aug 24)

Current Format With Date & Time: ❌
MMMM d, hh:mm a
(August 24, 5:30 PM)

Expected Format With Date & Date: ✅
EE , MMM d, hh:mm a
(Wed, Aug 24, 5:30 PM)

Or Allow User To Manually Change The Format
(Screenshot Attached Below)

**Upcoming Alarm Option:**

And If Possible Add A Toggle To Show Upcoming Alarm Between Date, Time & Weather, When An Alarm Is Set
(Screenshot Attached Below)

### Why would it be useful to add?

*

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![InShot_20220824_172123296](https://user-images.githubusercontent.com/96917972/186416084-67ab600e-3eee-43c2-81a7-c569b3eeb1d5.jpg)

**Comment by iBabu007** [comment]
Not only this if possible then add big clock option 
See this
![Screenshot_20220810-100151_1](https://user-images.githubusercontent.com/65340361/186887344-725b4709-e7f4-4fd9-91d4-bb0a689edd5e.png)

**Comment by Amorphous404** [comment]
![Screenshot_2022-08-26-17-59-37-85_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/96917972/186903720-6324fb69-3fd0-40e0-9704-7866a11770d7.jpg)

Why not, it looks good, and the option was also available in Lawnchair v2
