### ISSUE TITLE
Hide navbar pill on home screen

### ISSUE THREAD

**Issue by Golde2341** [Deletescape-Media/Lawnchair#2875]
### Describe the feature

It could be good an option that hides nav bar pill when you go to home screen.

It could work with root or make lawnchair in full screen

### Why would it be useful to add?

It uses iOS nav bar concept

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220824-073528_Google Play Store](https://user-images.githubusercontent.com/85361118/186420145-dc773c89-ccf4-4982-b425-3b2811227b5f.png)
![Screenshot_20220824-073604_Lawnchair](https://user-images.githubusercontent.com/85361118/186420162-df59630f-f975-4aee-9ffb-ce4914bc1c28.png)

**Comment by kahanzammi** [comment]
There is a Magisk module to change the color. That mean, it is possible to customize navigation pill. May be you can suggest the module developer to add transparent option while in home screen.
Module url: 
https://github.com/TheAttila/Gesture-Themes/releases

![Screenshot_20220824-225010_Pixel Launcher](https://user-images.githubusercontent.com/105884763/186500393-fda7f2a8-48a5-409e-867c-5ff18a5371dd.png)
