### ISSUE TITLE
[QUESTION] Icons on tablets are too small

### ISSUE THREAD

**Issue by Markellas** [Deletescape-Media/Lawnchair#2880]
### Describe your question or ask for support

Hello, I really liked your Lawnchair 12 Beta, but I wanted to install it on a tablet and unfortunately found that the icons on the tablet were too small on the big screen.

Please could you make better support for larger devices with horizontal orientation such as tablets?

Thanks in advance

**Comment by RikKoedoot** [comment]
Can't you just increase the icon size?

**Comment by kahanzammi** [comment]
> ### Describe your question or ask for support
> Hello, I really liked your Lawnchair 12 Beta, but I wanted to install it on a tablet and unfortunately found that the icons on the tablet were too small on the big screen.
> 
> Please could you make better support for larger devices with horizontal orientation such as tablets?
> 
> Thanks in advance

Feature you are looking for is already available in Lawnchair settings. There are various icon size settings. Just increase them to match your taste.

**Comment by Markellas** [comment]
Yes, I've seen it, but for some reason the size increases very little on tablets and still looks very small. If you turn the tablet upside down, the view is normal, but in the horizontal position it is bad

**Comment by Markellas** [comment]
> Can't you just increase the icon size?

It doesn't normally work in the horizontal position :/

**Comment by RikKoedoot** [comment]
Could you provide screenshots? I don't have this issue on my tablet

**Comment by Markellas** [comment]
> Could you provide screenshots? I don't have this issue on my tablet

Here it is

![Screenshot_2022-08-29-08-51-28-281](https://user-images.githubusercontent.com/105635627/187132134-69e44c91-96dd-465f-ba8b-856737aef4c4.jpeg)

The icons in this screenshot are at maximum size (150%), at 100% size they are extremely small, at maximum size however they are not big enough either

**Comment by fourofspades** [comment]
Seeing a similar issue Lenovo M10 Gen 3, Android 12.

Increasing the icon size chops off the icons in the drawer.  (Which even at 100% are hovering really close to the bottom already).

100%
![Screenshot_20220829-095433](https://user-images.githubusercontent.com/61576868/187165090-54aab094-e715-4424-93f1-dfd456ea2935.jpg)


150%
![Screenshot_20220829-095505](https://user-images.githubusercontent.com/61576868/187164912-7fb03a40-874f-473b-a60b-618e2dc0a727.jpg)

**Comment by Markellas** [comment]
In addition to the above information, I have this problem on a Lenovo Tab M10 FHD Plus with Android 10 installed

**Comment by fourofspades** [comment]
I guess this need a bug label to get noticed? Can someone add one please?

**Comment by fourofspades** [comment]
Not fixed

**Comment by fourofspades** [comment]
Not fixed

**Comment by Markellas** [comment]
Still not fixed
