### ISSUE TITLE
[QUESTION] Actions -> Dev version dont have the same signature?

### ISSUE THREAD

**Issue by passeee** [Deletescape-Media/Lawnchair#2883]
### Describe your question or ask for support

When trying to install the dev version from actions, i always get the error that they dont have the same signature, than the already installed app. 
Im currently on Lawnchair 12.1 Dev # 1048
![Screenshot_20220825-221436](https://user-images.githubusercontent.com/96446439/186762336-7a35b860-721c-41de-9477-8904235685a4.png)
![Screenshot_20220825-164609](https://user-images.githubusercontent.com/96446439/186762341-810a2987-d4b8-44b0-910e-ab46f5e74cd5.png)

**Comment by RikKoedoot** [comment]
It's either a problem with lawnchair itself. Or you've downloaded it from an unofficial source and they've modified the apk.

**Comment by passeee** [comment]
As the title says I downloaded from "actions" tab

**Comment by passeee** [comment]
Download apks with the same tag "12.1" and it works fine now.
