### ISSUE TITLE
Request to change the option below to open the background list from right angle to rounded angle

### ISSUE THREAD

**Issue by LQ2002** [Deletescape-Media/Lawnchair#2884]
### Describe your question or ask for support

![8b9a812836197a83b232ce0239e74f6](https://user-images.githubusercontent.com/50812010/186804624-60f5d5ef-68bb-48f9-ac73-523c756263be.jpg)
The button below the request to change the background list becomes rounded

**Comment by SuperDragonXD** [comment]
Well, it's already slightly rounded, but I guess it could be changed to be more rounded. Also I think the "Feature Request" template suits more for this issue.
