### ISSUE TITLE
[FEATURE] Battery Percentage in At A Glance

### ISSUE THREAD

**Issue by deybedanta** [Deletescape-Media/Lawnchair#2885]
### Describe the feature

There should be an option to view battery percentage to show in At A Glance, preferably beside the weather.
It shouldn't be really obnoxius. Below is an example on how it could work:

26 August, 12:34
☁️ 33°C • 90%

### Why would it be useful to add?

People like me who hid the status bar on home screen don't have to open status bar every time we need to see the percentage.

### Example(s)

26 August, 12:34
☁️ 33°C • 90%

no time:
26 August
☁️ 33°C • 90%

**Comment by Amorphous404** [comment]
I agree,
• Plain battery percentage next to weather
• While Charging ⚡ followed by battery percentage.


**Mock Up:**
![Battery Percentage.jpg](https://user-images.githubusercontent.com/96917972/186887683-d6f5b6aa-0ebc-47ec-bfb8-d41e867edbe0.jpg)

I'm even okay, if the devs decide to add a dedicated line to show battery info.

**Mock Up:**
![IMG_20220826_161150.jpg](https://user-images.githubusercontent.com/96917972/186888193-d62b22c3-8720-492d-bb18-7ac452a0c9ee.jpg)

**Comment by Amorphous404** [comment]
This modification can be tied with other ATG feature requests in #2874 & #2876

**Comment by kahanzammi** [comment]
> ### Describe the feature
> There should be an option to view battery percentage to show in At A Glance, preferably beside the weather. It shouldn't be really obnoxius. Below is an example on how it could work:
> 
> 26 August, 12:34 ☁️ 33°C • 90%
> 
> ### Why would it be useful to add?
> People like me who hid the status bar on home screen don't have to open status bar every time we need to see the percentage.
> 
> ### Example(s)
> 26 August, 12:34 ☁️ 33°C • 90%
> 
> no time: 26 August ☁️ 33°C • 90%

I don't think it's a good idea to show battery % next to weather. It can be easily misinterpreted as humidity %.

**Comment by Amorphous404** [comment]
It won't be activated by default, a toggle would be there to enable it, user will be aware when he enables it, and theirs already preview available under at the glance settings so that'll not be an issue 🤷‍♂️

Or it can be moved before the the weather widget, just like Niagara launcher does and it didn't confuse any user

![Screenshot_2022-08-27-00-14-49-19_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/96917972/186971689-67e3c63d-f5bc-4c53-adc6-cd440b5ee713.jpg)

**Comment by kahanzammi** [comment]
I would read it as : 
Lightning, 29% humidity, cloudy and 26c temperature 😉
Each line should carry inter-related information.

**Comment by kahanzammi** [comment]
I just noticed, Lawnchair already does a great job when battery status is really needed. This is even not available in Pixel launcher. Bravo.

![Screenshot_20220826-233824_Lawnchair~2](https://user-images.githubusercontent.com/105884763/186979274-6a36f785-08cf-43d1-8680-c7104a35ca7c.png)

**Comment by Amorphous404** [comment]
> I would read it as : 
> Lightning, 29% humidity, cloudy and 26c temperature 😉
> Each line should carry inter-related information. 

![HiShoot_20220827_051810.png](https://user-images.githubusercontent.com/96917972/187004782-c5700847-36ef-45bd-86c0-e82ae822e182.png)

I have been using a Niagara Launcher For Over A Year Now, Till to this day not a single user reported, finding any difficulty or reading it the wrong way 🤣

But yes, if you or the devs think it's not okay to put the weather and the battery indicator in the same line I'm okay with another line for battery widget (posted the reference above) 🤷‍♂️

**Comment by kahanzammi** [comment]
Well, I respect that everyone can have their own opinion and wish. In case anyone interested, I'm using the Google battery widget, that not only displays the phone battery state, but my Bluetooth earbuds when they are connected.

![Screenshot_20220827-123326_Pixel Launcher](https://user-images.githubusercontent.com/105884763/187022864-70407c8e-fc00-4d51-b3e4-923989f534e0.png)

**Comment by Amorphous404** [comment]
It's exclusive to Google pixel device sadly 🥲, i personally used it while i was on a custom rom it's great 👍
