### ISSUE TITLE
[BUG] Phone Battery Draining Rapidly After Installing Lawnchair 12.1.0 Alpha 4

### ISSUE THREAD

**Issue by jmcglock** [Deletescape-Media/Lawnchair#2888]
### Describe the bug

After updating to Lawnchair 12.1.0 Alpha 4, my battery is draining rapidly.
After uninstalling Lawnchair, my battery is not longer draining rapidly. 

This is the first time I have seen such an issue with the alpha builds of Lawnchair 12. 

Hardware: OnePlus 9 5G (T-Mobile Variant).

### Steps to reproduce

1. Battery on phone drains faster than normal after installing latest alpha build of Lawnchair. 

### Expected behavior

In previous alpha builds, battery was not affected. 

### Device information

- Device: OnePlus 9 5G (T-Mobile Variant)
- OS: Oxygen OS 12
- App version: 12.1.0 Alpha 4

### Additional context

Thanks Lawnchair Team!

**Comment by kahanzammi** [comment]
Have you tried uninstalling and reinstalling then configure it from scratch?

**Comment by jmcglock** [comment]
Yes. I have uninstalled and used the default launcher for a day. Battery lasted all day. 

Reinstalled Lawnchair, battery lasted half the day. 

That was the only change I made to the phone that would have drained the battery.

**Comment by kahanzammi** [comment]
What does your battery usage screen in Android settings says. Is Lawnchair consuming higher percentage of battery? Also I would try changing Lawnchair app battery setting to restricted from Android app settings. Also you may try removing all widgets from Lawnchair to check if any of the widgets are the culprit.

**Comment by jmcglock** [comment]
> What does your battery usage screen in Android settings says. 

Lawnchair was hovering around 5% of all battery use after the update. I usually expect to get around 10-11 hours of screen on time. 

> Also you may try removing all widgets from Lawnchair to check if any of the widgets are the culprit. 

I have the same widget running with my stock launcher and the battery is not affected. The only widget I run is "Another Widget". 

If you all don't think it's caused by the latest update, no worries. I will still wait for the next alpha build before reinstalling. 

Thanks.

**Comment by yasanglass** [comment]
As far as I know, there haven't been any significant changes that could cause high battery consumption on the new releases (alpha 2-4). It might just be the stock launcher being more optimized for your specific device.

Also, not sure how high 5% is for launchers, but it doesn't sound too high. **95%** of the battery drain is caused by other services & apps which probably means the battery draining issue is not really related to Lawnchair.

**Comment by kahanzammi** [comment]
Try to disable both dock search bar, at a glance and Google feed (if you're using them). Most of the time Google play services is the culprit for battery drain, but that doesn't show up in stats.

**Comment by kahanzammi** [comment]
I remember once I tried Another Widget and that used significant percentage of battery in my Galaxy. Uninstalled after one day use.

**Comment by jmcglock** [comment]
Thanks for the help. I'll wait for the next release. 😀👍

**Comment by jmcglock** [comment]
Closed issue. Will wait for next alpha build.

**Comment by blackma9ick** [comment]
I still notice excessive battery usage coming from Lawnchair with default settings and default home screens on 12.1.0 Alpha 4, although per the pinned issue, we are finally closer to a release with potential improvements regarding battery usage.

However my patience has ran out, so I will now test a build of the latest commit at time of writing, and see if there is any improvement. I recommend anyone to try and do so, if they wish to use Lawnchair without crazy battery drain.
