### ISSUE TITLE
Select Text option similar to pixel launcher

### ISSUE THREAD

**Issue by firefinchdev** [Deletescape-Media/Lawnchair#2890]
### Describe the feature

Currently if lawnchair is set as Recents Providers, there is an option to open Lens app with the screenshot of the current app.
On Pixel launcher, a user can directly select Text. Moreover, rhe text selection happens on device.
It's a pretty useful, handy and great utility feature that can be introduced to Lawnchair.

### Why would it be useful to add?

Same as above

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Same as above

**Comment by SuperDragonXD** [comment]
See https://lawnchair.app/faq/#wheres-the-select-feature-of-the-recents-screen for the reason why this won't happen. Closing this issue.
