### ISSUE TITLE
Lawnchair being non-compatible with quickswitch module on Android 12 Xiaomi miui 13

### ISSUE THREAD

**Issue by sho-blackz** [Deletescape-Media/Lawnchair#2891]
### Describe the bug

Lawnchair is not compatible with quickswitch on Android 12 

### Steps to reproduce

1. Go to magisk & install quickswitch.
2. Reboot & then give root permission to it.
3. Open the quickswitch app

### Expected behavior

I expected it to give gesture navigation on MIUI with lawnchair 

### Screenshots

![Screenshot_2022-08-27-21-39-47-279_xyz paphonb quickstepswitcher](https://user-images.githubusercontent.com/112008643/187068944-77607c75-11f9-4f71-837e-89dd66240bc4.jpg)

### Device information

- Device: Xiaomi 11i (Indian version with china rom)
- Model no.:210911161
-OS: stock rom MIUI CHINA  13.0.4 stable
-Android version: 12.0
- App version: 12.1.0 Alpha 4

### Additional context

If you can help me with this annoying discomfort of MIUI ,which does not let as change the launcher without giving navigation bar at the bottom.

**Comment by lewisdoesstuff** [comment]
I don't believe 12.1 versions are compatible with QS on Android 12.0, use a 12.0.x version and you should be fine.

**Comment by SuperDragonXD** [comment]
What the above said. You can search "Lawnchair 12.0 apkmirror" Google to see the file. Closing this issue.
