### ISSUE TITLE
Fullscreen folders (or tweaked 5x5 folder layout)

### ISSUE THREAD

**Issue by Username1-a** [Deletescape-Media/Lawnchair#2893]
### Describe the feature

It would be great to have fullscreen folder option, so you could keep app icons and labels in folders same size as the ones on a home screen. 

Right now app icons and labels in folders scaled dynamically according to Max Folder Colums and Rows parameters and they're getting a bit small on 5 colums/5 rows layout and in lanscape orientation. 

Furthermore, instead of fullscreen folders, you could just tweak the 5 colums/5 rows folder layout to occupy the entire width of the screen anyway, because, as you know, by default home screen and dock uses 5 icon column layout, so you could just match the icons size in a folder to those on the home screen and dock (I attached screenshot that more clearly visualize that inconsistency between folder and home screen/dock icons).

### Why would it be useful to add?

It would improve the consistency between home screen/dock and folder icons sizes. Plus, it's just more comfortable to tap on a bigger icon.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220828-211420_Lawnchair](https://user-images.githubusercontent.com/47947180/187089480-27aacffc-b1cd-494a-8bac-92d6d675c9f4.png)
![Screenshot_20220828-210603_Lawnchair](https://user-images.githubusercontent.com/47947180/187089513-6d0203e2-9794-48d9-b066-a3cc0b4668ab.png)

**Comment by synuhaan** [comment]
I agree. Right now im using launchers within launchers to make clean and efficient pages.

So what do you guys think about this idea as sub-pages where you can place apps, as well as widgets 

(I now bypassed this by using a separate launcher as 'big folder ')
