### ISSUE TITLE
Request to add Grid style multitasking style

### ISSUE THREAD

**Issue by LQ2002** [Deletescape-Media/Lawnchair#2896]
### Describe the feature

The fastest way to find background task software

### Why would it be useful to add?

Improve multitasking ability

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![image](https://user-images.githubusercontent.com/50812010/187334350-78aa0f17-dd80-4ad4-bd53-f78f7fa2d358.png)

**Comment by SuperDragonXD** [comment]
This is technically possible if you have QuickSwitch and a 600dp+ min width screen, in which the taskbar also automatically appears. Although I guess having the option to toggle it on smaller DPIs might be better.
