### ISSUE TITLE
Smaller Dock Icons

### ISSUE THREAD

**Issue by akapu1** [Deletescape-Media/Lawnchair#29]
Hi.. 

I think dock icons are smaller than desktop icons which looks odd in my opinion... It should be symmetrical in both Dock and Desktop.. or even app drawer..

Thank you. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MicheleLele** [comment]
+1 Me too noticed this bug.

**Comment by amirzaidi** [comment]
It's the default in Launcher3, the easy fix is to import Pixel Launcher's profiles in device_profiles.xml

**Comment by TokedUp** [comment]
Same here. Nexus 6P ODP3

**Comment by LautaroBel97** [comment]
+1 I also noticed this. 

_Sent from my Samsung SM-J710MN using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
@amirzaidi it's what I did, but everyone complained that my change actually changed something and it doesn't look like before... :joy: :unamused:

**Comment by nyancrimew** [comment]
Icon size can be changed in settings, so if you want icons to have the same size in dock / drawer as on home screen, you can do this in settings
