### ISSUE TITLE
White Google Icon

### ISSUE THREAD

**Issue by Makozor** [Deletescape-Media/Lawnchair#290]
Can be set the White Google icon with out the blur efect??

**Comment by fonix232** [comment]
What would be the point? Without blur, the Google icon (the pill) is white already.

**Comment by RWOne** [comment]
True, perhaps what the OP wants is a black (or I would suggest a shade of grey) Google Icon choice in the Google Pill instead of the multicolored one.   White on white would look .... unwise.  :)

**Comment by LinuxLlama** [comment]
I think what he meant was when you switch the theme to dark or black, instead of using a colored G, you could toggle it to white. Honestly not a bad idea.

**Comment by RWOne** [comment]
I agree, the multicolored "G" looks terrible on anything but white.

**Comment by Makozor** [comment]
Yea Thats what i meant, or the blur efect be set separated, like just the pill or just the folders, etc
