### ISSUE TITLE
[BUG] Custom Icon with Lawnicons enabled doesnt work

### ISSUE THREAD

**Issue by passeee** [Deletescape-Media/Lawnchair#2901]
### Describe the bug

When Lawnicons is enabled, the custom icon wont show up.
It is set, because after selecting a custom icon the button "reset custom icon" shows up.
Probably because of Lawnicons is an overlay and not an iconpack itself.

### Steps to reproduce

1. Go to Home screen
2. Click on an App that has Lawnicons enabled
3. Select a custom icon
4. See the same Lawnicons icon

### Expected behavior

See the selected custom icon

### Device information

- Device: [e.g. Google Pixel 6 Pro]
- OS: [e.g. stock ROM Android version 13.0]
- App version: [e.g. 12.1.0 Dev 1067]

**Comment by SuperDragonXD** [comment]
Intended behavior.

> Probably because of Lawnicons 
is an overlay and not an iconpack itself.

That's the reason. Lawnicons is tied to the app package name, and not the actual icon. We currently don't plan having the option to change Themed Icons icons to custom ones.
