### ISSUE TITLE
[FEATURE] Adding recently used apps 

### ISSUE THREAD

**Issue by hakunama1ata** [Deletescape-Media/Lawnchair#2902]
### Describe the feature

Add an option to enable suggestions on top of the app drawer. Suggestions can be based on recent activity and most used apps, based on usage access

### Why would it be useful to add?

It will help to access apps a lot faster

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20220902-075959_Nova Launcher](https://user-images.githubusercontent.com/67356841/188045896-bd7ca5f0-d7ec-428c-8819-173ea6c0971d.png)
The top part shows app suggestions based on usage access

**Comment by ShojibSarsilmaz** [comment]
But very useful if suggestions apps on dock bar or recent apps on dock bar ( without root & custom recovery)
