### ISSUE TITLE
[BUG] SD Maid app Crash

### ISSUE THREAD

**Issue by nacrz** [Deletescape-Media/Lawnchair#2906]
### Describe the bug

SD Maid app crashes when using the Launcher

### Steps to reproduce

1. Use Lawnchair
2. Open app drawer
3. Error

### Expected behavior

Getting to use the launcher

### Screenshots

![Screenshot_20220905-093411](https://user-images.githubusercontent.com/112835446/188343454-799cc76f-5f58-4282-a60d-97562db8bf07.png)

### Device information

- Device: [ Sony Xperia XZ2 ]
- OS: [ Stock Rom Android version 9.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by yasanglass** [comment]
It doesn't crash when you open it from other launchers?
