### ISSUE TITLE
Edit Folder Icons Like Normal Icons

### ISSUE THREAD

**Issue by jtwp** [Deletescape-Media/Lawnchair#291]
One nice feature I'd like to see is to be able to change the Folders to any other icon from icon packs. This allows you to choose say a sports icon for all your sports apps and keeps all the icons consistent in look and size.

**Comment by Stevie7000** [comment]
I'm surprised this isn't a more popular request. I know many if us are trying to save the world or at least start getting up earlier in the mornings, but gosh, if we could get these folders customised, it would be heading in the right (NOT in a politics in a sense) direction.

**Comment by Offerel** [comment]
I hope such a feature would be integrated.

**Comment by StarGW-net** [comment]
Completed? How do I change the folder icon? I cannot seem to do it!
