### ISSUE TITLE
[BUG] Double tap to sleep no longer works through root access

### ISSUE THREAD

**Issue by MarcoDjallo** [Deletescape-Media/Lawnchair#2910]
### Describe the bug

Hello,

as written in the title, I recently installed a freshly compiled update for lawnchair, and now the double tap to suspend in homescreen doens't work anymore through root. I have to enable the accessibility service, and suspending this way is slower and a little bit glitchy (screen turns on for a second after locking).

Thanks for your support

### Steps to reproduce

1. Enable "suspend" function in gestures
2. Double tap to suspend

### Expected behavior

I expect the screen to shut off instantly, as it was using root.

Now instead it required to enable accessibility service; then, after I double tap, the screen locks, turns on for a second, and turns off again.

### Device information

Device: Poco F2
OS: Android 12L, CrDroid 8.8
Lawnchair Version: 12.1.0 Dev #1063

**Comment by SuperDragonXD** [comment]
This is a known issue with the 12L builds; for now, we currently haven't fixed it yet.
