### ISSUE TITLE
I can't find some strings to translate 

### ISSUE THREAD

**Issue by Rafael2616** [Deletescape-Media/Lawnchair#2915]
### Describe your question or ask for support

I would like to know if there is a way I can redo some translations, which are poorly created by other users, but I can't find them in the Crodwin search. When I download the translation file they appear, but I don't know how to change them in the Project

Language: Portuguese - Brazil pt-BR
Strings: 
Current:

</trans-unit>
      <trans-unit id="1947" resname="search_provider">
        <source>Search Provider</source>
        <target state="translated">Procurar Provedor</target>

</trans-unit>
      <trans-unit id="1617" resname="dock_label">
        <source>Dock</source>
        <target state="translated">Ancorar</target>

Translate to:

</trans-unit>
      <trans-unit id="1947" resname="search_provider">
        <source>Search Provider</source>
        <target state="translated">Provedor de Pesquisa</target>

</trans-unit>
      <trans-unit id="1617" resname="dock_label">
        <source>Dock</source>
        <target state="translated">Dock</target>

**Comment by SuperDragonXD** [comment]
The links can be found in https://lawnchair.crowdin.com/translate/c26ac9577fbf791d8e74aae2a00d05d4/49/en-ptbr#1947 and https://lawnchair.crowdin.com/translate/c26ac9577fbf791d8e74aae2a00d05d4/49/en-ptbr#1617 ; have edited them and they will be available on next release. Thanks for the heads-up! (Also closing this issue.)
