### ISSUE TITLE
[BUG] Lawnchair Icon appearing in App Drawer

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#2916]
### Describe the bug

Lawnchair icon appearing in the app drawer, I know I can hide it but it should not be there in the first place

### Steps to reproduce

1. Go to app drawer
2. Scroll down
3. See error

### Expected behavior

Lawnchair icon should not be there

### Screenshots

![photo_2022-09-07_19-56-19](https://user-images.githubusercontent.com/93768823/188872870-81626544-c0e9-474e-ad28-7b242ccb1acc.jpg)

### Device information

- Device: SM-A125F
- OS: OneUI 4.1 Android 12 Rooted with Magisk
- App version: 12.1.0 Dev (1096)

**Comment by SuperDragonXD** [comment]
Do you have Lawnchair 2 (from playstore) or Lawnchair 9-10 alphas installed?

**Comment by notroger7** [comment]
No when I press the icon the app drawer closes

**Comment by notroger7** [comment]
I don't have another lawn chair installed

**Comment by Goooler** [comment]
Duplicate of #3120
