### ISSUE TITLE
Option to have a white notification count

### ISSUE THREAD

**Issue by louisamand** [Deletescape-Media/Lawnchair#2923]
### Describe the feature

Would it be possible to add the option to have the number in the notification count written in white instead of black?

### Why would it be useful to add?

It would make the readability better for dark colored dot notifications.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220909-184315](https://user-images.githubusercontent.com/54344684/189401357-6602e0ef-439f-491c-8705-8eb39fb17d57.png)
![Screenshot_20220909-181822](https://user-images.githubusercontent.com/54344684/189401942-753c5166-7dc9-4a74-9260-3dd238db8a47.png)

**Comment by yasanglass** [comment]
The Notification Dot's text color is selected automatically to have the most contrast. I am not sure if the option to select the text color will be added any time soon but you can try selecting a darker background color to force it to select white as the text color.

**Comment by louisamand** [comment]
Thanks a lot!
I darkened it a little and the font is now white :)

**Comment by yasanglass** [comment]
Great :) Adding custom color support to it is pretty easy actually but I am afraid of the preferences for Notification Dots becoming too confusing and/or too much in general.
