### ISSUE TITLE
Immersive Folders

### ISSUE THREAD

**Issue by KirmesTVAustria** [Deletescape-Media/Lawnchair#2932]
### Describe the feature

Please add immersive (Fullscreen) Folders 

### Why would it be useful to add?

For more place of icons

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220911-173340](https://user-images.githubusercontent.com/93053377/189536057-b7f85a84-7106-4ea9-a898-c8105eb8dad3.png)

Screenshot from Nova Launcher

**Comment by KirmesTVAustria** [comment]
> ### Describe the feature
> Please add immersive (Fullscreen) Folders
> 
> ### Why would it be useful to add?
> For more place of icons
> 
> ### Did the feature exist in Lawnchair v2? (Play Store version)
> No
> 
> ### Example(s)
> ![Screenshot_20220911-173340](https://user-images.githubusercontent.com/93053377/189536057-b7f85a84-7106-4ea9-a898-c8105eb8dad3.png)
> 
> Screenshot from Nova Launcher
> 
> ### Additional context
> _No response_

Please add it

**Comment by Vivimagic** [comment]
![Screenshot_20240825-224848](https://github.com/user-attachments/assets/dc570bfe-a214-443d-a0f9-5fd29098b873)
Full screen folders would be a great utility especially if it can make it lower on the screen for one hand access.
