### ISSUE TITLE
[BUG] Cannot update debug apk without uninstalling

### ISSUE THREAD

**Issue by rufus582** [Deletescape-Media/Lawnchair#2937]
### Describe the bug

I don't know why I can't update the official debug builds of lawnchair. For normal users, this might be just a minor issue, but for rooted users like me, who uses quickswitch too, it's a total mess.

### Steps to reproduce

1. Have a debug apk installed (from GitHub actions)
2. Try to update to a more recent build
3. App has package conflicts error while installation

### Expected behavior

App is supposed to update itself without error, considering this is the official debug build.

### Screenshots

![Screenshot_20220912-211442_Package installer](https://user-images.githubusercontent.com/68699122/189698905-aaed08a0-f9cb-43ea-a080-bde873e6bd04.png)
![Screenshot_20220912-211631_Lawnchair](https://user-images.githubusercontent.com/68699122/189698917-24bc2264-f5b4-40d7-b02c-368f581d0fe4.png)

### Device information

- Device: Samsung M31s
- OS: Pixel Experience Plus GSI V415.1
- App version: 12.1.0 Dev 1117 (trying to update to 1120)

**Comment by suphon-t** [comment]
The debug builds from GitHub actions are in no way “official”. It also includes builds from other branches which are not reviewed yet. We provide no support for such builds. The only official builds are the ones published on the release page and on our telegram channel.
