### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by anbzerc** [Deletescape-Media/Lawnchair#2946]
### Describe the feature

It would be pretty cool to make a cover mode for folder 

### Why would it be useful to add?

Because it's practical

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![PXL_20220915_171742168 MP](https://user-images.githubusercontent.com/66829188/190469910-c8e8571c-4c80-46ff-b9bb-6e5d66008e11.jpg)
![PXL_20220915_171746278 MP](https://user-images.githubusercontent.com/66829188/190469981-900c9c31-386e-40c1-ba75-c77ea3a134ea.jpg)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
This looks like the same Cover Mode folder request now tracked in #2659, although it seems to have been closed mainly because the issue title was incomplete.



- #2659
