### ISSUE TITLE
[FEATURE] Cover mode

### ISSUE THREAD

**Issue by anbzerc** [Deletescape-Media/Lawnchair#2947]
### Describe the feature

It would be pretty cool to make a cover mode for folder 

### Why would it be useful to add?

Because it's practical

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![PXL_20220915_171742168 MP](https://user-images.githubusercontent.com/66829188/190470752-abf5407d-17b0-4c05-a7fc-eaf02c77c0d4.jpg)
![PXL_20220915_171746278 MP](https://user-images.githubusercontent.com/66829188/190470763-88a665b5-ab60-4ae6-8fec-b11c220bf15e.jpg)

**Comment by thor9898** [comment]
It would be nice if you could swipe down to open instead of only being able to swipe up

**Comment by SephGER** [comment]
I am also missing this feature.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> ### Describe the feature
> 
> It would be pretty cool to make a cover mode for folder
> ### Why would it be useful to add?
> 
> Because it's practical
> ### Did the feature exist in Lawnchair v2? (Play Store version)
> 
> Yes
> ### Example(s)
> 
> ![PXL_20220915_171742168 MP](https://user-images.githubusercontent.com/66829188/190470752-abf5407d-17b0-4c05-a7fc-eaf02c77c0d4.jpg) ![PXL_20220915_171746278 MP](https://user-images.githubusercontent.com/66829188/190470763-88a665b5-ab60-4ae6-8fec-b11c220bf15e.jpg)
> ### Additional context
> 
> _No response_


Yes, the feature exist in Lawnchair Legacy version 9.1 alpha 3

This appears to be covered by the current tracking issue #2659, since it asks for the same Cover Mode behavior for folders that existed in Lawnchair v2.

- #2659
