### ISSUE TITLE
Apply icons via gallery app

### ISSUE THREAD

**Issue by SadLinusGuy0** [Deletescape-Media/Lawnchair#2949]
### Describe the feature

Apply icons from image, along with icon packs

### Why would it be useful to add?

Theming. People upload cool icons for various apps that aren't in icon packs (you see this on Pinterest a lot). Edit: You can also make invisible icons this way as well

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20220915_200352](https://user-images.githubusercontent.com/113133532/190488037-a89651db-5047-43a7-8779-e0a6bcaabf40.jpg)
Lawnchair 2 Play Store version

**Comment by algatern** [comment]
Another request for this feature. I have a folder of custom icon PNGs I would like to choose for each icon. I have been using LawnDesk launcher which has this feature, but it is no longer updated.

**Comment by icarusinthewings** [comment]
This would be awesome, and I used it in Lawnchair v2.
I have some custom-designed icons to extend my icon pack.

**Comment by SadLinusGuy0** [comment]
Is this going to be considered?

**Comment by icarusinthewings** [comment]
Stale bot is annoying.

**Comment by RhaenysDraugwen** [comment]
I would love this feature, I want to make custom icons but not have to code them into an icon pack.
