### ISSUE TITLE
Dock 

### ISSUE THREAD

**Issue by Baker0o7** [Deletescape-Media/Lawnchair#2951]
Hi thanks for your hard work really loved the launcher can you please add option in the dock where by can add second row instead of only one thank you👍

**Comment by SuperDragonXD** [comment]
Please use the issue forms (specifically, the [feature request](https://github.com/LawnchairLauncher/lawnchair/issues/new?assignees=&labels=feature%2Cenhancement&template=feature_request.yaml&title=%5BFEATURE%5D+) one) if you want to create a feature request. Closing this issue.
