### ISSUE TITLE
[BUG] Jitters In Scroll Bar Animation In App Drawer 

### ISSUE THREAD

**Issue by Shail9802** [Deletescape-Media/Lawnchair#2953]
### Describe the bug

Jitters In ScrollBar of App Drawer while scrolling and Fast scrolling after changing the home screen grid size to 7×10

### Steps to reproduce

1.Go to 'Home Settings'
2.Click on 'Home Screen'
3.Scroll down to 'Grid Size'
4.Set Size to 7×10 and Apply
5.Go to App drawer now
6.See error

### Expected behavior

Smooth animations of Scroll bar in App Drawer !

### Device information

- Device: [Poco X4 Pro ]
-OS: [EvolutionX (Custom ROM)]
-App version: [e.g. 12.1.0 Alpha 4]

### Additional context

This is fixed when cleared data !

**Comment by SuperDragonXD** [comment]
Please provide a screen recording of this issue. Thanks.

**Comment by Shail9802** [comment]
> Please provide a screen recording of this issue. Thanks.

I tried to attach it to the issue but it wasn't taking a video in it !

**Comment by Shail9802** [comment]
[ScreenRecord of the Bug Faced](https://rctiahmedabad-my.sharepoint.com/:v:/g/personal/196400316560_rctiahmedabad_gujgov_edu_in/EbULiOYkkypPtfsdBbvNUT4BE--aprpnMDtE9Xa2eMqhgg?e=YbZS4C) 

> Please provide a screen recording of this issue. Thanks.

**Comment by Anderhar** [comment]
Confirming the same problem on my old Xiaomi with 5-inch screen running LineageOS 18 and observing the identical effect in the Neo Launcher.

**Comment by Anderhar** [comment]
Here is a recording that clearly shows how the slider makes one "jerk" at the beginning of the movement and then goes off-screen at the end of the bar. Depending on the amount of applications, number of columns, and row height, the number and depth of these "jerks" may also vary. (Captured on Lawnchair 12.1.0 Alpha 4).
![recording](https://user-images.githubusercontent.com/98178689/200146785-498c9ff9-13f3-4601-b165-7dde89148853.gif)

**Comment by Unofficial-Life** [comment]
It's a real problem and a headache because of this I can't change home screen grid.
Please reopen this issue, It's still present in latest dev versions pls have a look at it.
