### ISSUE TITLE
Immersive Folders 

### ISSUE THREAD

**Issue by KirmesTVAustria** [Deletescape-Media/Lawnchair#2959]
### Describe the feature

Add immersive Folders 

### Why would it be useful to add?

More Space on one Folder Page

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20220911-173340](https://user-images.githubusercontent.com/93053377/190881177-9125c1b3-500e-48db-b8a8-b563248c567b.png)
Screenshot vom Nova Launcher 

### Additional context

Please add it

**Comment by KirmesTVAustria** [comment]
Please add it

**Comment by KirmesTVAustria** [comment]
Please add it

**Comment by KirmesTVAustria** [comment]
Please add it

**Comment by Vivimagic** [comment]
Could be a lot more simple like this
![Uploading Screenshot_20240825-224848.png…]()
