### ISSUE TITLE
Resizing 'At a Glance' widget 

### ISSUE THREAD

**Issue by sharang701** [Deletescape-Media/Lawnchair#2962]
### Describe the feature

It's not a new feature rather an enhancement. I want the 'At a Glance' widget to resize because initially it's size is okay but as soon as I increase the home screen apps grid , it starts to become smaller and smaller.

### Why would it be useful to add?

It's useful to add because it gives an added customization to home screen independent of home screen apps grid.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Just a resizing ability of at a glance widget.

**Comment by SuperDragonXD** [comment]
A recommended workaround is to disable the "At a Glance" option in Settings > At a Glance, and manually add the "Lawnchair" widget (if you have A12, make sure it has the aag preview and a description "At a Glance") to have resizing options.

**Comment by sharang701** [comment]
Got it. Thank you so much.
