### ISSUE TITLE
[FEATURE] can you bring "swipe up on folder to open an app" back , please

### ISSUE THREAD

**Issue by quro13** [Deletescape-Media/Lawnchair#2974]
### Describe the feature

can you bring "swipe up on folder to open an app" back , please.

### Why would it be useful to add?

i usually group apps with same function into a folder, e.g ott apps, shopping apps, multimedia apps. And I usually use one of each folder. I like this function on Lawnchair 2 on Play store.
But it is gone in version 12.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Swipe up a folder to open an app

**Comment by RyanUnicorn** [comment]
I also want this back too, one of my favorites feature in the previous version.
With this I don't need to shove all my ugly folder to the second page just to make my home look nice.

**Comment by suma01245** [comment]
If appropriate to say here despite the issue marked as closed, this is still a much desired feature.
