### ISSUE TITLE
[BUG]  Homescreen Spacing Issues 

### ISSUE THREAD

**Issue by M00NJ** [Deletescape-Media/Lawnchair#2975]
### Describe the bug

Disabling icon labels on the homescreen results in odd spacing between the app rows.
I initally thought disabling icon labels simply hides the labels wich makes the spacing between the apps look off, but comparing the screenshots shows that the spacing actually increases even more when labels are disabled. You can reduce the space again by increasing the number of rows in the app grid, but that also shrinks the size of all the widgets on your homescreen. Wich is especially annoying for the at a glance widget because it can't be readjusted. 

### Steps to reproduce

1. Go to 'Settings'
2. Click on 'Home Screen'
3. Scroll down to 'Icons'
4. Turn off 'Show Labels'

### Expected behavior

When disabling icon labels the spacing between the rows should be readjusted to the same size as the spacing between the columns so it always stays even.

### Screenshots

![Screenshot_20220922-111538](https://user-images.githubusercontent.com/82398591/191714935-725f8fda-9fa7-4ff2-b592-531574d4368f.png)
![Screenshot_20220922-111824](https://user-images.githubusercontent.com/82398591/191714950-dfd1eeb9-a04c-4dbd-ac01-80fdbdb98809.png)

### Device information

- Device: Google Pixel 4a
- OS: Stock Android version 13.0
- App version: 12.1.0 Alpha 4

**Comment by fboender** [comment]
For those running into this problem, if you increase the number of rows on the home screen, the vertical spacing between icons reduces. You can change this in Settings -> Home screen -> Layout -> Home screen grid.

The same thing also works horizontally.

You can increase the icon size (Settings -> Home screen -> Icons -> Icon size) to further decrease the spacing between icons.
