### ISSUE TITLE
[BUG] Clicking on Home on a secondary desktop doesn't slide to the main desktop

### ISSUE THREAD

**Issue by kud** [Deletescape-Media/Lawnchair#2978]
### Describe the bug

Usually on launchers, when you're on a secondary desktop, clicking on the "home" button slides you to the main desktop.

Here on lawnchair, it tries to do it as well but it stucks to the secondary desktop.

### Steps to reproduce

1. Go to a secondary desktop
2. Click on "home" button
3. Lawnchair tries to go the the main desktop but doesn't succeed

### Expected behavior

Going to the main desktop.

### Device information

- Device: OnePlus 6T
- OS: Android 11
- App version: 12.1.0 Alpha 14

**Comment by kud** [comment]
👋🏻

**Comment by Goooler** [comment]
Is your rom ColorOS or OxygenOS?

**Comment by kud** [comment]
I'm on their official OS from OnePlus. I'm on a OnePlus 6T.

**Comment by Goooler** [comment]
So is it ColorOS or OxygenOS?

**Comment by kud** [comment]
`OxygenOS 11.1.2.2`

Did not know it was the name of the OS 😌

**Comment by Goooler** [comment]
Seems it's still the OxygenOS, can you take a screen record for me?

**Comment by kud** [comment]
Here we go:

https://user-images.githubusercontent.com/655838/215781044-e26abdb9-81ad-4964-aba6-19abf4a0f27d.mp4

**Comment by Goooler** [comment]
It seems like switching pages but going back to the second one?

**Comment by kud** [comment]
Yeah that's right. 

On any secondary desktops, when you click on the home button, it tries to come back to the first one (which should do) but can't do it and stays on the current desktop.

**Comment by Goooler** [comment]
Weird, I'll investigate it later.

**Comment by kud** [comment]
Thank you @Goooler 😌

**Comment by kud** [comment]
:D
