### ISSUE TITLE
[Feature] Sort of Chinese and English

### ISSUE THREAD

**Issue by famlar** [Deletescape-Media/Lawnchair#2986]
### Describe the feature

# Engligh
> About the sorting problem of Chinese and English
# Chinese
> 关于中英文的排序问题

### Why would it be useful to add?

# English
> Separate sorting makes me often need to swipe to the bottom to click apply(eg Google, Gmail, YouTube)
# Chinese
> 分离的排序使我常常需要滑动到底部来点击应用（例如Google，Gmail，YouTube）

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

#  About the sorting problem of Chinese and English
## Problem
>  中英文的排序是分离的，但这是不对的，拼音同样是按照英文的顺序排列，不应当是分离的
## Version 
>  Lawnchair 12.0.0 Alpha 5
## Screenshot 
<img src="https://user-images.githubusercontent.com/78424351/192603664-e6f6dc80-06eb-45b2-ba20-10d175c92daf.png" width="25%" height="25%">

### Additional context

# Wrong sort
- 电话
- Chrome
# Correct ordering
- Chrome
- 电话

**Comment by Goooler** [comment]
I'll take a look.

**Comment by famlar** [comment]
Ok, Thank you very much.

**Comment by Goooler** [comment]
@Simple-2021 You can download apk from https://github.com/LawnchairLauncher/lawnchair/actions/runs/3538139448 for a test.

**Comment by eric1932** [comment]
Check this post out: https://sakari.top/2022/android-language/

**Comment by Goooler** [comment]
刚刚试过了，执行 `adb shell settings put system system_locales zh-CN,zh-Hans-CN` 对于 Pixel Launcher 是有用的，同时现在 Lawnchair 也支持在没有执行上一步的情况下做到中英文混排，开启上一步后排序结果也完全一致

**Comment by famlar** [comment]
@Goooler Thank you very much.
