### ISSUE TITLE
[BUG] quickswitch Lawnchair 12 is "Not compatible with android 13"

### ISSUE THREAD

**Issue by Divyansh-HAL9000** [Deletescape-Media/Lawnchair#2987]
### Describe the bug

Lawnchair Version 12.1.0  Alpha 4 is not supporting quickswitch

### Steps to reproduce

updated my phone to Android 13

### Expected behavior

quickswitch should open

### Device information

- Device: [e.g. POCO  X2]
- OS: [e.g. Cherish OS ROM Android version 13.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by SuperDragonXD** [comment]
Intended behavior. Lawnchair hasn't been rebased yet to support Android 13. See also #2922 to see if we have builds available or not.
