### ISSUE TITLE
[BUG] App crashes when trying to delete website shortcut

### ISSUE THREAD

**Issue by xLingyOS** [Deletescape-Media/Lawnchair#2993]
### Describe the bug

https://katb.in/cepoluwofet

### Steps to reproduce

1. Go to desktop
2. Hold on the website shortcut
3. Click "Delete" button
4. App crashes

### Expected behavior

I wanted to remove the site shortcut from the desktop

### Device information

- Device: Redmi Note 8 Pro
- OS: MIUI 12.5.7 RGGEUXM Android 11
- App version: 12.1.0 Dev #23 from 12.1-dev-localization

**Comment by Goooler** [comment]
Need your log.
