### ISSUE TITLE
[BUG] Title on app list isn't readable

### ISSUE THREAD

**Issue by kud** [Deletescape-Media/Lawnchair#2994]
### Describe the bug

When you use the app list, and you want to read the name of the current app, it's hard to read.

### Steps to reproduce

1. Start any app
2. Click on the square button on Android
3. Try to read the title of an app

### Expected behavior

Maybe add a shadow on the text

### Screenshots

![Screenshot_20221002-190131](https://user-images.githubusercontent.com/655838/193466788-e880af13-0fff-4d8b-a844-123a6b1435e2.jpg)

### Device information

- Device: OnePlus 6T
- OS: 12
- App version: 12.1.0 Alpha 4

**Comment by zammikahan** [comment]
I believe this is OnePlus's own app switcher that Lawnchair doesn't have control on.
You may need to switch to QuickSwitch to customize the app switcher.
