### ISSUE TITLE
[FEATURE] Ability to resize widget any size

### ISSUE THREAD

**Issue by adamkhldanial** [Deletescape-Media/Lawnchair#2997]
### Describe the feature

Example: Google Calendar schedule widget has 2x4 size and it is unable to change its size, especially the widget height while using Lawnchair launcher, and it really takes up space in the home screen. It is not limited to Google Calendar widget too, Todoist widget also having difficulties to adjust its widget height, where I'm unable to decrease the height.

### Why would it be useful to add?

To prevent the widget takes too much space in the home screen, and makes it obnoxious when user using their phone.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_2022_10_03_16_07_53_59_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/78545904/193529950-5329fafb-9014-464b-b8e3-aa94c694abad.jpg)

**Comment by kahanzammi** [comment]
I think it's a limitation of your phone
This is mine

![Screenshot_20221005-075340](https://user-images.githubusercontent.com/105884763/193978202-af1fdf31-9006-4c90-97e6-66b054d0a691.png)

**Comment by kblee0** [comment]
It can be used as a 1x1 size widget in Samsung OneUI home, but there is a problem that only 2x2 size is available in lawnchair. 
I hope to develop a feature that can be resized to any size soon.

**Comment by kahanzammi** [comment]
I believe it's again boil down to number of grids and resolution. In my S22+, I'm on 4x6 grids. Calendar widget in one UI only goes upto 2×2.
