### ISSUE TITLE
Inconsistent Google white pill

### ISSUE THREAD

**Issue by uzair-inamdar** [Deletescape-Media/Lawnchair#300]
On touching the white pill, the animation is laggy. Also, at times touching the pill does not do anything.

**Comment by nyancrimew** [comment]
This is caused by the google app, we can't do anything about it

**Comment by Younes-L** [comment]
@deletescape thanks for the answer, may I ask why does this happen exactly ? The Google app also makes Nova's search bar laggy, but it works consistently... Battery optimization perhaps ? 

Edit : tried disabling battery optimization for both lawnchair and Google app, no change.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
