### ISSUE TITLE
[BUG] Inconsistent display of app icons

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#3001]
### Describe the bug

The icons are not consistently displayed... if I try to search for authy, the widgets pane show it in system format, the search shows it in icon pack format, and the app recommendations show it in lawnicons format.

### Steps to reproduce

1. Apply icon pack
2. Use lawnicons
3. Open widgets pane and look at the icons 
4. Open app drawer and search
5. See the inconsistency...

### Expected behavior

Mainstream standardised proper display of icons

### Screenshots

![photo_2022-10-05_11-37-22](https://user-images.githubusercontent.com/93768823/193976572-f78d997a-2589-411e-a604-833d39648218.jpg)
![photo_2022-10-05_11-37-16](https://user-images.githubusercontent.com/93768823/193976576-23004665-d213-4d8d-a9a7-45cd01581db3.jpg)
![photo_2022-10-05_11-37-12](https://user-images.githubusercontent.com/93768823/193976579-d11a3a3a-0032-4e0d-b5e3-1ddda09f157a.jpg)
![photo_2022-10-05_11-36-55](https://user-images.githubusercontent.com/93768823/193976581-807c060b-123f-40c1-8139-294d5868b296.jpg)
![photo_2022-10-05_12-01-02](https://user-images.githubusercontent.com/93768823/193978736-d5a9a10a-ebd4-4872-bc56-66a8b7f043fa.jpg)

### Device information

- Device: Samsung Galaxy A52
- OS: OneUI 4.1 Android 12
- App version: 12.1.0 Dev 1169

**Comment by luximus-hunter** [comment]
This isn't a bug. Go to the Lawnicons github and fill in the icon request there

**Comment by SuperDragonXD** [comment]
Alongside what it said above, the themed icons are only shown in the **home screen and app drawer** as seen in Home Settings > General > Icon Style. There is *no* mention of it displaying in the widgets menu, or the Lawnchair settings screen. As for the app drawer search result, the code hasn't been implemented yet, maybe create a feature request for this. Closing this issue.
