### ISSUE TITLE
[FEATURE]  Transparent icon background 

### ISSUE THREAD

**Issue by kahanzammi** [Deletescape-Media/Lawnchair#3003]
### Describe the feature

It would be nice to have an option to make icon background transparent when themed icons (with Lawnicons) used. Below is a workaround that I'm using wallpaper with same color as icon background.

### Why would it be useful to add?

That could bring visual appeal to the home screen by eliminating some clutter.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221005-192327](https://user-images.githubusercontent.com/105884763/194108724-72e7047b-0584-4c62-ad5a-446122c423f8.png)

![Screenshot_20221005-192337](https://user-images.githubusercontent.com/105884763/194108903-3431bac4-4ad4-49de-892e-8132a508c13b.png)

**Comment by naveenccmsd** [comment]
@kahanzammi  tried hardcoding trasparanet background, results looks good. loved it. 
![WhatsApp Image 2022-10-09 at 11 28 20 PM](https://user-images.githubusercontent.com/7315975/194772275-fe6d2505-0bb6-4f46-ae94-11e7f133c1ec.jpeg)
![WhatsApp Image 2022-10-09 at 11 21 22 PM](https://user-images.githubusercontent.com/7315975/194772279-6cf85c41-aeea-40dc-b1d4-29bd007bbd0b.jpeg)

**Comment by zammikahan** [comment]
Awesome, you made my day  :-)

To be honest, once I got used to it, very hard to go back to icons with filled background.
Drawback with my workaround is; always I have to stick to the mono color wallpaper that goes with the icon background color.

**Comment by naveenccmsd** [comment]
@zammikahan , Have already made the changes and rasied PR #3011 . 
However I still the icon may not matched with background, example see below impage , the accent color/icons color are fectched based on walpapper's dominet color but it will not fit well in some part of the wallpapper and it's not possible to update the color to match every part of wallpapper. I'm not sure if this would accepted by repo owners. I'm atlease expecting to have this option as experimental feature and let user to change accent color If needed.

![WhatsApp Image 2022-10-09 at 11 28 20 PM](https://user-images.githubusercontent.com/7315975/194847605-10cdb89d-7788-4e45-90d5-826df1751892.jpeg)

**Comment by kahanzammi** [comment]
Yes, user may need to use a custom color to distinguish the icons from wallpaper in this situation.

**Comment by kahanzammi** [comment]
Even now some wallpapers do make the home screen unusable.

![Screenshot_20221010-182645](https://user-images.githubusercontent.com/105884763/194889316-5fdb83ca-3e0e-4979-9405-9f4112d4151b.png)

**Comment by kahanzammi** [comment]
This can be a use case for transparent icon background.

![Screenshot_20221010-195906](https://user-images.githubusercontent.com/105884763/194908287-62f5b6e5-58e8-4bb4-8daa-228a2fe7dda3.png)

**Comment by kahanzammi** [comment]
Tried the build 1181. Seems it crashes.
I'm on Android 13.

**Comment by SuperDragonXD** [comment]
As always, if something crashes, **please** provide a log. Stating "it crashes" isn't really useful for debugging

**Comment by kahanzammi** [comment]
After installing 1181 it behaved fine. But when changed to themed icon, background turned into white and gave me dialog with close app and wait options. No way to capture debug. Only status bar was accessible. Anyway I'll do a fresh install again and test. During the installation I noticed Google play protect gave me a warning.
