### ISSUE TITLE
[BUG] Drawer confusing text alignment

### ISSUE THREAD

**Issue by meyverick** [Deletescape-Media/Lawnchair#3006]
### Describe the bug

The bottom vertical alignment creates confusion because it looks like the text is linked to the icon under it.

### Steps to reproduce

Change icon size and row space.
Open the drawer.

### Expected behavior

Top vertical alignment.

### Screenshots

https://ibb.co/ns2WDrq

### Device information

- Device: realme GT Master
- OS: 12
- App version: latest available on the store.

**Comment by SuperDragonXD** [comment]
Maybe try increasing the row height? Since having top vertical alignment will make the spacing look ugly. Also iirc, the icon label alignment doesn't change when changing the icon/row size.

**Comment by meyverick** [comment]
> Maybe try increasing the row height? Since having top vertical alignment will make the spacing look ugly. Also iirc, the icon label alignment doesn't change when changing the icon/row size.

Unfortunately, increasing row height makes the drawer ugly...

![Screenshot_2022-10-07-08-50-27-22_3b881d4c06d4cbc1b5e5ddba75e2aac5](https://user-images.githubusercontent.com/101877847/194485755-cf36aefe-071d-4385-ba4c-3d6066986670.jpg)

The spacing between the icon and it's name is too big, reducing it could make it better.
