### ISSUE TITLE
[FEATURE] Use default Android Material You icons supplied by app developers

### ISSUE THREAD

**Issue by Arbee4ever** [Deletescape-Media/Lawnchair#3008]
### Describe the feature

I want the ability to use the icons supplied by the developer for material you for apps that fo support it, as i like for example the spotify Icon more than the one provided by Lawnicons. Also this would make some unknown apps someone might have able to fit into the design scheme aswell.

### Why would it be useful to add?

More Icons following the design scheme and more customizability.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)
Material You:
![Screenshot_20221008-084215~2](https://user-images.githubusercontent.com/45911516/194694208-02a72774-63e2-4c9d-a6fb-76c0078eae71.png)
Lawnicons:
![Screenshot_20221008-085158](https://user-images.githubusercontent.com/45911516/194694209-ab24155c-014b-4dcf-8ba5-7eab716c192a.png)

**Comment by SuperDragonXD** [comment]
Will be added when Lawnchair 13 comes out. For now, we won't implement it in Lawnchair 12.1.

**Comment by Arbee4ever** [comment]
Any ETA on it's release?

**Comment by SuperDragonXD** [comment]
I don't know. We only work on Lawnchair on our free time, so we can't really give an ETA.
