### ISSUE TITLE
[FEATURE] Option to drag app from app drawer to uninstall while lock home screen is enabled

### ISSUE THREAD

**Issue by laraib07** [Deletescape-Media/Lawnchair#3009]
### Describe the feature

In normal settings you can uninstall any app from app drawer by dragging it to the top right corner of home screen. But when the "Lock home screen" is enabled, you cannot.

### Why would it be useful to add?

It would get easier to uninstall apps from app drawer even when "lock home screen" is enabled.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221009-033149_Lawnchair](https://user-images.githubusercontent.com/25507825/194729285-d5577617-e1e0-4e2e-ad52-072e500048e4.png)

### Additional context

N/A

Edit: Tried to make it more clear.

**Comment by SuperDragonXD** [comment]
The *literal* purpose of "Lock Home Screen" is for you to *not* change the layout. This includes preventing the user from uninstalling an app (either accidentally or intentionally). If we allow doing that, it renders the option useless; might as well not show that option in the first place.

If you wish to uninstall an app, you can disable that option, uninstall, then re-enable it. Closing this issue.

**Comment by laraib07** [comment]
@SuperDragonXD The literal purpose of "Lock Home Screen" is to prevent any changes on home screen. What I am asking is to be able to drag app from app drawer to uninstall. And If I dragged it to home screen nothing will happen, as it is locked.

**Comment by SuperDragonXD** [comment]
Oh okay. The current behavior doesn't really allow that because it is assumed that dragging an app from the app drawer to the home screen means that you are also putting an app to the desktop, alongside the tools. Not sure how feasible it'll be to implement this feature, but I'll re-open this issue.

(Also in the development builds, the long-press popup has a direct feature of uninstalling the specific app.)

**Comment by laraib07** [comment]
While Locked home screen is enabled, the icon in the drawer cannot be changed.

**Comment by SuperDragonXD** [comment]
Well, checked the code and "home screen" basically applies to the whole launcher UI (not including the settings screen), not just the main "workspace" (homescreen) UI. Maybe having better wording could be better tbh?
