### ISSUE TITLE
App Drawer Icon Label Truncated 

### ISSUE THREAD

**Issue by baadnewz** [Deletescape-Media/Lawnchair#301]
For apps with longer label (app name) it truncates the text (check the picture for the Samsung... apps) . Can it be made to split the long text in 2 lines? 
![screenshot_20170725-184438](https://user-images.githubusercontent.com/661635/28581296-8b1b54ae-716a-11e7-9b4c-4544fbfb2d91.png)

**Comment by Rawi666** [comment]
I'd like to see this simple feature implemented as well :)
