### ISSUE TITLE
Apply Accent Color Enabled by Default

### ISSUE THREAD

**Issue by naveenccmsd** [Deletescape-Media/Lawnchair#3013]
### Describe the feature

Enable `Apply Accent Color` for `search bar` by default. Currennlty it;s disable by default.

### Why would it be useful to add?

As Themed accent color applied to launcher by default , the UI will look cleaner if same enabled by default for search bar insted of enabling it manually.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![WhatsApp Image 2022-10-10 at 11 38 39 AM](https://user-images.githubusercontent.com/7315975/194814649-171606d6-af3f-4f14-8a9e-0e300f6c2855.jpeg)

### Additional context

I would like to hear feedback on this change.

**Comment by SuperDragonXD** [comment]
The reason on why we don't have it enabled by default is that it doesn't really look well without themed icons (and themed icons requires an app). If we had enabled it by default, we would also need to require Lawnicons to be installed. Also it takes 3-5 seconds to enable the option.

**Comment by naveenccmsd** [comment]
@SuperDragonXD , Thanks for your reply .

I see accent were appiled to most of the components by defaut except themed icons , atleast on android 12 (which i'm using).
Example the clock widget ( you can see in below image) used accent color  (system/color choosed in lawnchair) by default.
So thought If search bar with accent color enabled by default would gives much cleaner look. 

Before:

![WhatsApp Image 2022-10-10 at 3 55 03 PM (1)](https://user-images.githubusercontent.com/7315975/194846071-1e3e8cad-b8db-4b42-8647-9cd92a8c33e3.jpeg)

After :
![WhatsApp Image 2022-10-10 at 3 55 03 PM](https://user-images.githubusercontent.com/7315975/194846096-be862c43-c4a9-43c2-819c-8f839b7ed984.jpeg)


If this would degrade performance in anyway then better keep it disabled by default.

**Comment by SuperDragonXD** [comment]
Well, it doesn't really degrade performance, but I'm not really sure whether to have it by default or not. I'll tell this to the team.

**Comment by naveenccmsd** [comment]
> Well, it doesn't really degrade performance, but I'm not really sure whether to have it by default or not. I'll tell this to the team.

Thanks

**Comment by SuperDragonXD** [comment]
After some discussion with the team, we have enabled the feature by default as see in https://github.com/LawnchairLauncher/lawnchair/commit/b35eb21843b858cd4b84f60c9369ff460e913734.
