### ISSUE TITLE
[FEATURE] Only show hidden app in search when its full name is typed

### ISSUE THREAD

**Issue by laraib07** [Deletescape-Media/Lawnchair#3019]
### Describe the feature

In search result, only when full name of hidden name is typed, it will be shown.

### Why would it be useful to add?

It will make it easier to access hidden app without exposing it in fuzzy Search results.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221012-223359_Lawnchair](https://user-images.githubusercontent.com/25507825/195404883-2c214e2d-94a0-454a-8418-a938c64a484a.png)

**Comment by DevPJ9** [comment]
Hello, @laraib07 I would like to contribute.
