### ISSUE TITLE
[FEATURED] Add the new android 13 search bar style

### ISSUE THREAD

**Issue by OpsDani** [Deletescape-Media/Lawnchair#3023]
### Describe the feature

Add the new style of the android 13 app drawer search bar.

### Why would it be useful to add?

aesthetic change

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Google-Android-13-Pixel-launcher-issues](https://user-images.githubusercontent.com/97104388/195514530-b4b282ac-01bb-45e2-9da3-1a7b334dd20d.jpg)

**Comment by yasanglass** [comment]
Can you provide pictures?

**Comment by OpsDani** [comment]
SammyFans

**Comment by yasanglass** [comment]
Um, I guess the pictures somehow didn't load for me when I left the comment lol.

**Comment by OpsDani** [comment]
> Um, I guess the pictures somehow didn't load for me when I left the comment lol.

Have you already seen it? I would like you to redesign the search bar to the new style of Android 13 beta

**Comment by yasanglass** [comment]
I do have the "beta" search bar on my emulators. It has a pretty nice transition once you click on it.

The option to use it could be nice but I don't know if any one (at least in the core team) has plans to implement it soon.

**Comment by OpsDani** [comment]
> 

well, hopefully it will be added soon, it's a very nice aesthetic change.
