### ISSUE TITLE
[BUG] battery widget no longer works after Android 13 update

### ISSUE THREAD

**Issue by Delvar** [Deletescape-Media/Lawnchair#3024]
### Describe the bug

The battery level widget was working on A12 but after updating to A13 it now shows the error, Problem Loading Widget. The widget works on standard loader.

### Steps to reproduce

1. Go to home screen
2. Long hold to get menu
3. Press widgets
4. Search down for battery widget
5. Drag widget to desktop
6. See the error, Problem Loading Widget

### Expected behavior

It would be nice to see the battery levels.

### Device information

- Device: Google Pixel 6
- OS:  stock ROM Android version 13.0, TP1A.221005.002
- App version: Version 2.0-2589

### Additional context

I only recently updated to A13 and it used to work fine on A12

**Comment by vrushank29** [comment]
I think all widget doesn't work after Android 13 version.

**Comment by RikKoedoot** [comment]
Which widget do you mean? The one included in android or the one in the lawnchair at a glance widget? If it's the second, what doesn't work about it?

**Comment by Delvar** [comment]
> Which widget do you mean? The one included in android or the one in the lawnchair at a glance widget? If it's the second, what doesn't work about it?

I'm referring to the android widget, under setting service battery, not the lawn chair at a glance Widget, sorry for not being clear.

**Comment by jmcglock** [comment]
Same issue here. Battery does not work for at a glance widget.

**Comment by SuperDragonXD** [comment]
Does it work in other launchers (like Pixel Launcher, etc)? If not, ig it's an A13 issue and not a Lawnchair issuem

**Comment by Delvar** [comment]
Sorry, it seems I was using the App Store version of Lawn chair, I had no idea it was an old unsupported version, I had assumed it was an up to date dev build.

I have side loaded the later version from your website, Version 12.1.0 Alpha 4, and the setting service battery widget now works as expected.

I have the useless lawn chair "at a glance" disabled as I don't like the position on the home screen and can't move it. Though I tested the battery indicator for that but it doesn't shown anything, maybe a permission issue?

Anyway my initial problem is resolved by switching to the side loaded version.

Thank you, and sorry for the mix up.

**Comment by SuperDragonXD** [comment]
> I have the useless lawn chair "at a glance" disabled as I don't like the position on the home screen and can't move it. 

You can actually move it by:

1. Disable the "At A Glance" or "Show on Home Screen" setting in Settings > At a Glance
2. Open the Widgets menu
3. Find the "Lawnchair" widget, and place it there. If you're using A12, it should have a description "At A Glance" and the preview of it.
4. Place it anywhere on the home screen, resize it, etc.

**Comment by Delvar** [comment]
Thank you, I had no idea it was also a standard widget too.
Thanks.
