### ISSUE TITLE
[BUG] Adjusting home screen grid size resets widget positions and reorders dock

### ISSUE THREAD

**Issue by Terrance** [Deletescape-Media/Lawnchair#3028]
### Describe the bug

Changing the number of rows or columns of the home screen grid, whether increasing or decreasing, resizes each of my widgets to 1x1 and places them in the bottom-left corner.  It also seems to reorder my dock folders to a different but reproducible order (perhaps ordered by creation time?), even if I only adjust rows and not columns.

### Steps to reproduce

1. Settings > Home Screen > Home Screen Grid
2. Increase rows by 1
3. Observe preview layout (pressing Apply produces the layout as shown)

### Expected behavior

With an increase of rows or columns, existing items can and should stay in their grid positions, leaving extra space for repositioning after the grid size change.

It's less clear on a decrease -- I wouldn't mind just the removal of widgets overflowing the new grid size if that's shown in the preview first.

### Screenshots

<details>
<summary>Current layout</summary>

![Screenshot_2022-10-13-18-30-36-66_67d7f8591eff9881972c1169b8bca2d8_](https://user-images.githubusercontent.com/4025899/195667894-5c460cc5-4a58-4069-8659-b895af996ff2.png)
</details>

<details>
<summary>Resulting layout after increasing columns or rows by 1 (note the dock folder order as well as the widgets)</summary>

![Screenshot_2022-10-13-18-30-42-87_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/4025899/195667902-1cb98480-f93c-4b55-89fd-faec33e2b3dd.jpg)
</details>

### Device information

- Device: OnePlus Nord CE
- OS: OxygenOS 12.1 (Android 12)
- App version: 12.1.0 Alpha 4

**Comment by Terrance** [comment]
No new releases since this was raised, so still an issue.

**Comment by Terrance** [comment]
Still no change.

(Seeing as the repo itself appears to be in maintenance mode, perhaps the stale bot should be disabled for the time being?  If no new releases are being made, issues raised against the latest version will continue to be relevant.)

**Comment by Terrance** [comment]
As above, no change since this was raised.

**Comment by Johnny-Larue** [comment]
Still a problem.
