### ISSUE TITLE
[FEATURE] Force Themed Icons / Default Themed Icons

### ISSUE THREAD

**Issue by naveenccmsd** [Deletescape-Media/Lawnchair#3039]
### Describe the feature

The Idea is to have an option to use default themed icons if no themed icons found.

### Why would it be useful to add?

This will give clean UI.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Example we can create Alphabets icons in lawnchair/lawnicon and use App's first letter as default icons if no icons found.

**Comment by naveenccmsd** [comment]
Don't think this necessary now as we can update icons from lawnicon in future release.

**Comment by ghost** [comment]
Hope we can reopen this and use upstream AOSP launcher implementation for forced icon theming.
