### ISSUE TITLE
Option to make hidden apps appear in search

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#304]
A simple way to reorganize the app drawer and reduce the clutter without completely losing access to hidden apps :)

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
We want that

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gauzeehom** [comment]
good idea

**Comment by pkerga** [comment]
Yes, good idea

**Comment by AxiK101** [comment]
it's a must feature
