### ISSUE TITLE
Android O DP4 Battery drainage

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#305]
I updated to DP4 and since then i got a huge battery drain from Lawnchair.
![screenshot_20170725-203751](https://user-images.githubusercontent.com/29924801/28588043-68f3782a-7179-11e7-8267-b6727e83ac04.png)

**Comment by dictvm** [comment]
Can't reproduce on Nexus 6P with DP4 and latest Lawnchair release. ![Screenshot](https://dl2.pushbulletusercontent.com/9MWojPEMmpToQdEfIuuy2jdzw82E0TmC/Screenshot_20170726-110400.png)

**Comment by javiersantos** [comment]
Battery drain for me too. Nexus 5X with DP4.

![Battery drain](http://i.imgur.com/aUcBrX9.png)

**Comment by ShadowRedel** [comment]
I tried to remove the Weather options and the battery consumption decreased in half. I think that the weather refresh time have something to see

**Comment by 5haney** [comment]
I have weather turned off, notification dots off and blur off but I still see high drain on O.
Not sure if it's lawnchair or just the way O reports it since I see high battery on other launchers too (nova, action and pixel) and when using Google now launcher, Google app shows much higher usage.

**Comment by ShadowRedel** [comment]
On the Android 8.0 (Final) y tried to left the movile turned on at night and these were the results: 
![screenshot_20170825-145207](https://user-images.githubusercontent.com/30420859/29714989-abcf64d0-89a5-11e7-939c-c773e6d6743f.png)
