### ISSUE TITLE
[FEATURE] Ability to enable app suggestion via app data usage permissions

### ISSUE THREAD

**Issue by OpsDani** [Deletescape-Media/Lawnchair#3055]
### Describe the feature

Possibility to enable app suggestions, on devices without Android System Intelligence, through app data usage permissions.

### Why would it be useful to add?

Adding this possibility would be good for devices that do not have Android System Intelligence.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20221025-192642](https://user-images.githubusercontent.com/97104388/197908859-0c7bcec2-5800-4075-af07-c9266df07fee.jpg)

**Comment by ShojibSarsilmaz** [comment]
But this feature can be add enable on dock bar on lawnchair. 
Like Pixel 6, 6 pro, 7 & 7 pro

**Comment by OpsDani** [comment]
Please read carefully before commenting!

**Comment by SadLinusGuy0** [comment]
If this was to be implemented, would it work for recent apps on the dock like on pixels?
