### ISSUE TITLE
[BUG] Dock settings changes entire homescreen

### ISSUE THREAD

**Issue by OmegaSunkey** [Deletescape-Media/Lawnchair#3056]
### Describe the bug

When changing how many icons the dock can have, the homescreen reorders entirely and the widgets become smaller than before.

### Steps to reproduce

1. Go to Settings > Dock
2. Click on Dock Icons
3. Go back to Homescreen
4. See everything rearranged

### Expected behavior

The homescreen should not change.

### Device information

- Device: Samsung J7 2017 (j7xelte)
- OS: Nusantara Project LTS 1.1 Android 10 Q Release UNOFFICIAL
- App version: 12.1.0 Alpha 4

**Comment by SadLinusGuy0** [comment]
A similar sort of thing happens when changing home screen grid size

**Comment by Goooler** [comment]
https://user-images.githubusercontent.com/10363352/215498829-86076543-4650-42a9-8a9f-ee6b6f2cfe60.mp4
