### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by compscidoggo** [Deletescape-Media/Lawnchair#3062]
### Describe the bug

Lawnchair crashes when attempting to reorganize the app drawer by dragging and dropping an app.

### Steps to reproduce

1. Swipe up to the app drawer
2. Press and hold an app icon
3. Move the icon around
4. Crashes

### Expected behavior

The app should drag when you press and hold and move it around.

### Device information

- Device: Samsung Galaxy S22 Ultra
- OS: Android 12, One UI 4.1
- App version: 12.1.0 Alpha 4

### Additional context

[Lawnchair_bug_report_Oct_28_2022_72336_PM.txt](https://github.com/LawnchairLauncher/lawnchair/files/9892436/Lawnchair_bug_report_Oct_28_2022_72336_PM.txt)

**Comment by OMGrant** [comment]
This is also affecting me. Same exact issue.
