### ISSUE TITLE
[FEATURE] Be able to disable app drawer

### ISSUE THREAD

**Issue by diamara-nauka** [Deletescape-Media/Lawnchair#3068]
### Describe the feature

Like on my oneplus. It would be nice to have an "all app on desktop" mode and be able to disable the drawer.

### Why would it be useful to add?

It's convenient to have a all app on desktop if you do not have a lot of app

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_2022-10-31-09-44-54-89_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/3962335/198968193-fa1c202b-9dac-460d-836c-9df62dde7cdc.jpg)

![Screenshot_2022-10-31-09-45-01-13_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/3962335/198968231-b379223c-5eb8-441e-ab80-602f1931498a.jpg)

**Comment by Weirdo1312** [comment]
This would great, I want an actively developed open source launcher based on aosp that has this feature but I couldn't find any, there is lawndesk based on lawnchair
https://github.com/renzhn/Lawndesk
but it doesn't have the latest bug fixes because the last commit was 2 years ago

**Comment by TaylanTatli** [comment]
> This would great, I want an actively developed open source launcher based on aosp that has this feature but I couldn't find any, there is lawndesk based on lawnchair [renzhn/Lawndesk](https://github.com/renzhn/Lawndesk) but it doesn't have the latest bug fixes because the last commit was 2 years ago

I've been looking for a launcher with this feature for days. Unfortunately, there are not many options. I love having everything right in front of my eyes on the home screen. That way, it's easier to find things. So sad I can't just install Samsung/Xiaomi launcher like a regular app, or not having an open source alternative.
