### ISSUE TITLE
[FEATURE]  Quick Switch Support for A13

### ISSUE THREAD

**Issue by icrackiphone** [Deletescape-Media/Lawnchair#3070]
### Describe the feature

Quick Switch support for Android 13 asop custom roms. On evolution X 7.2 a13 on my OnePlus 8 quick switch won't allow me to select lawn chair as my recents provider. 

### Why would it be useful to add?

Having native multitasking and gestures and smooth animations working along side lawn chair on my a13 custom ROM would be a great user experience. 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221031-021756_QuickSwitch](https://user-images.githubusercontent.com/13232235/198974886-355a4487-1510-4792-ab8a-4e5d06b11911.png)

**Comment by InvisibleBacon** [comment]
I am very interested in this feature. I would be happy to help with a fix if a dev was able to help get me oriented.

**Comment by Sergij-SApcPro** [comment]
I also really need this feature. Is there a workaround?

EDIT: I found an alternative! Here it is: https://github.com/saitamasahil/Lawnchair_Magisk

**Comment by ghost** [comment]
same
