### ISSUE TITLE
[FEATURE] Add black theme variant for the launcher

### ISSUE THREAD

**Issue by Username1-a** [Deletescape-Media/Lawnchair#3074]
### Describe the feature

Please, in the future, add black theme variant for the Lawnchair 12 (f black folders, app drawer, pop-up menus, laucher settings backgrounds), like it was in V2.

As of now, when changing Monet theme brightness to complete black through the Repainter app or in ROM settings, there's still these ugly grey folder backgrounds present in Lawnchair 12 (erd attached screenshot), while the other parts of the app actually looking great in black.

### Why would it be useful to add?

It would look better for some people + looks better on Amoled screens. Also, it would allow enabling black theme for those users who are using Lawnchair 12 on pre-Android 12 versions of the OS (As I've said before, Android 12 at least has Monet+Repainter).

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20221101-021107_Lawnchair](https://user-images.githubusercontent.com/47947180/199127812-753ab348-d2e0-4d09-9a95-24c94e76e105.png)
![Screenshot_20221101-021030_Lawnchair](https://user-images.githubusercontent.com/47947180/199127831-28910d9e-c9b5-4d53-9345-2609cb7e3004.png)
![Screenshot_20221101-021007_Lawnchair](https://user-images.githubusercontent.com/47947180/199127850-51b04dff-abc5-40b6-b4f6-1e2201af5674.png)

**Comment by OpsDani** [comment]
Create a pull request, they'll review and decide if they think it's worth adding to the Launcher or not.
