### ISSUE TITLE
[BUG]  Shortcuts not working neither on Home Screen nor in App Drawer

### ISSUE THREAD

**Issue by Ryder9013** [Deletescape-Media/Lawnchair#3077]
### Describe the bug

When I hold on any app. For Example - Play Store, it doesn't show "My Apps" shortcut. I have set the launcher as default and restarted the phone as well.

### Steps to reproduce

1. Go to 'Home Screen or App Drawer
2. Hold on any app
3. There are no shortcuts shown on any app

### Expected behavior

Shortcuts should be visible 

### Screenshots

![Screenshot_20221101-182813_Lawnchair](https://user-images.githubusercontent.com/75566707/199257199-7496a698-ee2d-48d2-a7fe-68badff4f52d.jpg)

### Device information

- Device: Samsung M51
- OS: One UI 4.1 Android 12
- App version: 12.1.0 Alpha 4

**Comment by Goooler** [comment]
I can repro this on Samsung S21+ (Android 12 with OneUI 4.1) and Note9 (Android 10 with OneUI 2.5).

<img src="https://user-images.githubusercontent.com/10363352/215656769-c046842d-a9b1-4e63-aa98-cc5d55288d07.jpg" width="25%" height="25%">

**Comment by Goooler** [comment]
I can repro this on all devices now, it might be a regression.

**Comment by gurmeetim** [comment]
Is also same on one ui 3 samsung A50 android 11

**Comment by MrSluffy** [comment]
Shortcut only show if lawnchair is default home

**Comment by MrSluffy** [comment]
![Screenshot_20231224-200703](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/171ad3c8-e4ba-4494-91a2-d0aa6fe8d889)

**Comment by Ryder9013** [comment]
> Shortcut only show if lawnchair is default home

The problem is in One UI not AOSP. and yes the launcher was set to default.

**Comment by MrSluffy** [comment]
> > Shortcut only show if lawnchair is default home
> 
> The problem is in One UI not AOSP. and yes the launcher was set to default.

issue still occur in current `14-dev`?

**Comment by Goooler** [comment]
Seems it's only happened on Samsung. I can't repro this on Pixel. Yeah, 14-dev as well.

**Comment by gurmeetim** [comment]
I use nova launcher which show app short cut.so this is a lawnchair issue.

**Comment by Ryder9013** [comment]
> > > Shortcut only show if lawnchair is default home
> > 
> > 
> > The problem is in One UI not AOSP. and yes the launcher was set to default.
> 
> issue still occur in current `14-dev`?

Tried on Samsung M51 One UI 4.1 with 14-dev. Seems to be working now I guess.

**Comment by gurmeetim** [comment]
New debug build is working fine on shortcuts.It seems fixed i can cnfirm it on a50 android 11 one ui 3.1

**Comment by MrSluffy** [comment]
use latest lawnchair 14

**Comment by huangyxi** [comment]
Still not working on OxygenOS 14.0 (Android 14) with Lawnchair 14 Beta 2, even when set as the default launcher.

![1701713841832_ pic](https://github.com/LawnchairLauncher/lawnchair/assets/32028289/01004593-a93a-4add-a754-15cf4d8a4059)

**Comment by xsm2** [comment]
It also doesn't work on HyperOS (Android 13)

**Comment by 1sakshamgaur** [comment]
same problem and it happened automatically one day I use the shortcuts daily and they disappeared one day
Android 12 Oxygen OS 12 Lawnchair 14 Beta 2 I reinstalled the app but nothing happens

**Comment by sjain882** [comment]
same problem on Lawnchair Beta 3, One UI 6.1 Samsung S23+ Android 14. All permissions enabled for Lawnchair

**Comment by tiendnm** [comment]
same problem on Lawnchair 14 Beta 3, Google Pixel 7 Pro, Android 15.
