### ISSUE TITLE
Blank splash screen on Android 12

### ISSUE THREAD

**Issue by mrugtangy** [Deletescape-Media/Lawnchair#3078]
### Describe the bug

All my google apps and other apps that uses the new Android 12 splash screen are launching with a blank splash screen without the app's icon in the center.

### Steps to reproduce

1. Get the Launcher
2. Open an app using the Launcher.

Note : Must have Android 12+.

### Expected behavior

The app should launch with a proper splash screen with the app's icon in the center.

### Device information

- Device: Samsung A02s
- OS: Android 12 (One Ui Core 4.1)
- App version: 12.1.0 Alpha 4

**Comment by suchithm** [comment]
Observed the same issue that is happening only in Android 12+
MAUI with platform specific splash screen

**Comment by mrugtangy** [comment]
> Observed the same issue that is happening only in Android 12+
> MAUI with platform specific splash screen

It's not a platform-specific issue. It's actually because of the quickstep api.

It can be fixed by either turning the launcher into a system app using /system/app mover or any other similar app if you're not on Android 12.1 (For Lawnchair 12.1).

Or

You can use the QuickSwitch method to fix it if you're on Android 12.1.

Note that both method needs root access.
