### ISSUE TITLE
[FEATURE] customize notification center

### ISSUE THREAD

**Issue by jd-solanki** [Deletescape-Media/Lawnchair#3079]
### Describe the feature

I bought new Android mobile and didn't liked the overall UI.

I found this launcher, and loved it even more when I found it is OS.

I like the launcher but unfortunately my notification center is still boring.

Can this launcher modify the notification center as well?

### Why would it be useful to add?

Align notification center ui with the rest is the launcher ui

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221101_232840](https://user-images.githubusercontent.com/47495003/199304725-e0214950-92cb-4780-9569-c6a76d689826.jpg)

As you can I am using the launcher but notification center is ugly 

### Additional context

This can be also separate app is We can't provide it with launcher

**Comment by suphon-t** [comment]
No. A launcher can not modify the notifications center.
