### ISSUE TITLE
Suggestion: Homepage screens management

### ISSUE THREAD

**Issue by ohayoubaka** [Deletescape-Media/Lawnchair#308]
It would be nice if Lawnchair had some homepage screen management, such as being able to add blank pages, and set the default page to be used on the launcher startup or as a shortcut from a home button press. Think of the way Nova Launcher does it.

**Comment by Williwood** [comment]
And also have infinite scrolling!

**Comment by fonix232** [comment]
Infinite scrolling is not possible because of Google Now.

**Comment by Williwood** [comment]
Okay, but if I or someone else doesn't use Google Now. Should it be possible then?

**Comment by guest4711** [comment]
@ohayoubaka See also #232 and #75
