### ISSUE TITLE
[FEATURE] Add hyphenation to icon names

### ISSUE THREAD

**Issue by cherpu** [Deletescape-Media/Lawnchair#3087]
### Describe the feature

I think this feature should be added as it will help get rid of abbreviations

### Why would it be useful to add?

This will improve the appearance of the launcher and expand its functionality

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![2022-11-05 00-09-23_1667588993](https://user-images.githubusercontent.com/117478895/200056692-d3605bb1-3a16-436c-a86a-375d6443fadc.PNG)

**Comment by Dogway** [comment]
Rather than dumb hyphenation I would break up on the first whitespace (if existant) if full length is going to be abbreviated.
