### ISSUE TITLE
Icon and Icon text scale resetting to 98%

### ISSUE THREAD

**Issue by uzair-inamdar** [Deletescape-Media/Lawnchair#309]
This only happens when you set these scales to 100%, after which they automatically go back to 98% on going back and reopening the UI setting.

**Comment by hassie-dash** [comment]
Essentially what is happening is that the rounding is causing some numbers to be missed. I don't think there is a way to fix that, unless we keep the range between the minimum and maximum at 100.

![screenshot 54](https://user-images.githubusercontent.com/26469286/28619230-4b3bf8c6-71ff-11e7-9b5b-c323b3543e2c.png)
