### ISSUE TITLE
Microphone icon on google pill widget

### ISSUE THREAD

**Issue by korbendalos** [Deletescape-Media/Lawnchair#31]
There should be a microphone icon on the google pill once "ok google" command activated.

**Comment by amirzaidi** [comment]
I didn't add it because it is ugly IMO

**Comment by korbendalos** [comment]
Thats a pity :) Maybe perform this as an optional stuff (with feasibility to hide/show this icon).?
I'm pritty sure somebody doesn't think it is ugly. 
BTW, anyway great job man!

**Comment by deletescape** [comment]
There is an option for it :blush:
Settings (with a lot of customizability) can be found when long pressing on the home screen and then pressing the settings icon there
