### ISSUE TITLE
pill icon and time/weather  issue

### ISSUE THREAD

**Issue by 8ball11** [Deletescape-Media/Lawnchair#310]
With lawnchair the weather doesn't display only ever shows the date, it works with amirzaidis' Launcher3   but not here  is this just some config error that i'm doing?

![screenshot_20170726-142408](https://user-images.githubusercontent.com/30452931/28604491-4f0f4e80-720e-11e7-90d0-b5726ac511c6.png)

**Comment by AxiK101** [comment]
Weather not working. Its a future request

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
