### ISSUE TITLE
[FEATURE]  Do you plan to add dynamic icon support for com.android.deskclock too?

### ISSUE THREAD

**Issue by peterge1998** [Deletescape-Media/Lawnchair#3103]
### Describe the feature

Title basically says all. Its the default clock on graphene:
Version 13

com.android.deskclock
versionCode 33

targetSdk 29
minSdk 33

Installed: 01.01.2009; 01:00

### Why would it be useful to add?

Because the dynamic stuff looks great with my calendar (etar)!

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

A clock with moving hands...
What should i say more?

**Comment by naveenccmsd** [comment]
@peterge1998 , yes Already started working on it.
