### ISSUE TITLE
Multi-Window Support for Lawnchair Settings 

### ISSUE THREAD

**Issue by FernFranc** [Deletescape-Media/Lawnchair#3105]
### Describe the feature

Multi-Window Support in Lawnchair Settings.

### Why would it be useful to add?

This would make navigation on large displays and foldables easier.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

<img width="1352" alt="unnamed" src="https://user-images.githubusercontent.com/81488600/201328672-d815cc7a-6408-4142-a94e-a62170d34cd9.png">
<img width="1352" alt="unnamed (1)" src="https://user-images.githubusercontent.com/81488600/201328711-98ba1b08-615c-48f4-a2e1-0d1b84020017.png">

This is an example of Multi-Window Support.

**Comment by icarusinthewings** [comment]
Would recommend adding "in settings" to the title :)

**Comment by icarusinthewings** [comment]
It's not stale please!
