### ISSUE TITLE
[FEATURE] Change app drawer text spacing

### ISSUE THREAD

**Issue by Kuphi** [Deletescape-Media/Lawnchair#3113]
### Describe the feature

I like a compact app drawer that lists as many apps as possible. Reducing "Row Height" to a low value, specifically 0%, results in the text being bad positioned. Instead of being directly below the apps, there is a space between the text and the app. It looks like the text belongs to the app icon below and not the app icon above.

Please introduce an option to control this more precisely or change the default spacing of the text.

![photo_2022-11-15_12-17-44](https://user-images.githubusercontent.com/64360528/201907539-27d7e688-d88a-41a0-a88e-51bfeac09c21.jpg)
![photo_2022-11-15_12-17-48](https://user-images.githubusercontent.com/64360528/201907535-aa56befe-5182-4d84-9f5e-ee6b9f17693a.jpg)

### Why would it be useful to add?

Allows a good looking compact app drawer.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

-

**Comment by Yadokingu** [comment]
I would love the same option for the home screen. I like to put a lot of rows on the screen, which results in about the same mismatch as seen above. 
Being able to manually control the padding between icon and text would be the best solution.
