### ISSUE TITLE
Implementation of a color picker preference 

### ISSUE THREAD

**Issue by hassie-dash** [Deletescape-Media/Lawnchair#312]
Hey, I was wondering if you have plans of implementing a color picker preference to replace a text based list preference. 

I am currently working on adding one into the launcher so that I can show the end result. 

The color picker itself is an open source library but needs a few edits which I am doing. The color picker has support for changing hue/saturation and the transparency. ![](http://i.imgur.com/BhD36QP.png)

**Comment by dictvm** [comment]
The picker on the screenshot doesn't look like it adheres to the Material Design guidelines.

**Comment by KieronQuinn** [comment]
If we're being strict to the guidelines, I highly recommend [this colour picker library](https://github.com/jaredrummler/ColorPicker), which I've used personally and offers a good compromise between material design (the preset picker) and custom colours with the palette picker.

**Comment by hassie-dash** [comment]
I like it, I think its a good balance between strict material design and preset depending on what the user wishes to use. I can start editing the library to pull out extra un-necessary features and implement it to see how it would behave with the launcher.

**Comment by enricocid** [comment]
If You are interested I've developed a simple theme preference where user can see colors previews

https://github.com/enricocid/ThemePreference

![screenshot_20170816-212307](https://user-images.githubusercontent.com/7274841/29403704-658830d2-8339-11e7-82b0-89895e469583.png)
![screenshot_20170816-212252](https://user-images.githubusercontent.com/7274841/29403705-658c2b1a-8339-11e7-867d-892f322e3dde.png)
