### ISSUE TITLE
[FEATURE] Include Ecosia as search provider

### ISSUE THREAD

**Issue by mesteryui** [Deletescape-Media/Lawnchair#3122]
### Describe the feature

Include the search engine ecosia to the search providers in lawnchair

### Why would it be useful to add?

Because give more options to users

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Uploading Screenshot_20221120-191410_Lawnchair.png…]()

**Comment by Goooler** [comment]
Feel free to send a PR.
