### ISSUE TITLE
Feed Displays A Blank Screen [BUG] 

### ISSUE THREAD

**Issue by KrisYadao** [Deletescape-Media/Lawnchair#3123]
### Describe the bug

After upgrading Galaxy S22 Ultra to Android 13, the Feed on the left page of the home screen randomly goes blank. The only way to fix this is to go into the Lawnchair settings and uncheck/recheck the enable Feed box.

### Steps to reproduce

Bug happens randomly, but seems like it could be related to clearing apps on the native app switcher.

### Expected behavior

Feed should always be present and accessable when enabled.

### Device information

Galaxy S22 Ultra
Android 13
Lawnchair 12.1.0 Alpha 4
Lawnfeed 3

**Comment by KrisYadao** [comment]
Also, battery optimization for Lawnchair and Lawnfeed are set to unrestricted.

**Comment by Akxe** [comment]
I have the same thing on Flip 3. But not only that it is blank, it sometimes does not appear ta all, something's I cannot swipe left for it to appear at all.

**Comment by kbexit** [comment]
For me, I have to go into app info for the Google app, force stop, clear cache, and it works. Have to repeat this step every now and then. 
Edit: turned off battery optimization for the Google app to see if this remedy's it. Hopefully it doesn't kill my battery in the process. 

Edit 2: That didn't work. Had to force close Google app and clear cache for it to work again.

**Comment by kbexit** [comment]
![Screenshot_20221125-194435.png](https://user-images.githubusercontent.com/102698001/204066041-2d29fa6c-7fc0-43cd-b95e-6ab45e52e938.png)

This is how the feed displays every now and then. Only work around is what I said above.

**Comment by SuperDragonXD** [comment]
Not an issue with Lawnfeed or Lawnchair, but the Google app itself. They broke something in their latest versions, so you can only do these to fix the issue: clear cache/force stop or uninstall recent updates.

An explanation from one of the devs on Nova Launcher (also applies to Lawnchair and other launchers):

> It's the google app. The integration with the google app is literally just Nova sending scroll events over so that the Google app can draw it's own window with it's own content. If Google is drawing a window, even a blank one, Nova has done it's job and has no more control

[Source on Nova Launcher Discord](https://discord.com/channels/466300922767736844/466300923430305793/888512002698379324)

**Comment by KrisYadao** [comment]
> Not an issue with Lawnfeed or Lawnchair, but the Google app itself. They broke something in their latest versions, so you can only do these to fix the issue: clear cache/force stop or uninstall recent updates.
> 
> An explanation from one of the devs on Nova Launcher (also applies to Lawnchair and other launchers):
> 
> > It's the google app. The integration with the google app is literally just Nova sending scroll events over so that the Google app can draw it's own window with it's own content. If Google is drawing a window, even a blank one, Nova has done it's job and has no more control
> 
> [Source on Nova Launcher Discord](https://discord.com/channels/466300922767736844/466300923430305793/888512002698379324)

Why does disabling then renabling the Feed inside the Lawnchair settings fix it? Does that cause the Google app to reload or something? 

https://youtube.com/shorts/TZgcliHDJ8k?feature=share

**Comment by SuperDragonXD** [comment]
Well, I guess it makes the Google app re-render the contents again. Not really sure though.

**Comment by kbexit** [comment]
> > Not an issue with Lawnfeed or Lawnchair, but the Google app itself. They broke something in their latest versions, so you can only do these to fix the issue: clear cache/force stop or uninstall recent updates.
> > 
> > An explanation from one of the devs on Nova Launcher (also applies to Lawnchair and other launchers):
> > 
> > > It's the google app. The integration with the google app is literally just Nova sending scroll events over so that the Google app can draw it's own window with it's own content. If Google is drawing a window, even a blank one, Nova has done it's job and has no more control
> > 
> > [Source on Nova Launcher Discord](https://discord.com/channels/466300922767736844/466300923430305793/888512002698379324)
> 
> Why does disabling then renabling the Feed inside the Lawnchair settings fix it? Does that cause the Google app to reload or something? 
> 
> https://youtube.com/shorts/TZgcliHDJ8k?feature=share

That doesn't fix it for me, I have to force close Google itself entirely. I guess one size doesn't fit all here.

**Comment by kbexit** [comment]
Turned off battery optimization for both Lawnchair and Google. Attempting to see if this works. So far so good. 
Update: did not work. Curse you Google!!!!

**Comment by KrisYadao** [comment]
I haven't experienced this bug in a while now. I assume Google must have made a change on their side that resolved the issue.
