### ISSUE TITLE
[BUG] Hard to trigger fast scroller in app drawer

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3126]
### Describe the bug

I can't trigger the fast scroller on my OnePlus 8t, I've also tried it out on Pixel 6 and Samsung S8, and it's hard to trigger.

### Steps to reproduce

https://user-images.githubusercontent.com/10363352/203715095-4471cd6b-b1a9-403a-ae0d-9eaf3fbb26aa.mp4

### Expected behavior

Can trigger it easily, we may need to expand the touch scope in width to recognize drag gestures in the app drawer.

### Device information

- Device: OnePlus 8t
- OS: Android 11
- App version: the latest

**Comment by Goooler** [comment]
Also presents on my Moto X40.

**Comment by Amorphous404** [comment]
https://user-images.githubusercontent.com/96917972/219869993-8656ba24-595a-4906-95db-d808d443c106.mp4

Slightly improved (10%), but still very hard to trigger it effectively, also after scrolling a little further, i can't trigger the scroller at all :(

**Comment by Amorphous404** [comment]
@Goooler

**Comment by Goooler** [comment]
Can this work without work profile?

**Comment by Amorphous404** [comment]
Is it possible to disable the work tab in Lawnchair, Kinda like Nova that I'm not aware of?

![Screenshot_2023-02-18-21-54-19-99_3822ac0e29cfec8970059bb21d01f05e.jpg](https://user-images.githubusercontent.com/96917972/219876915-54e86a6b-c989-426d-907c-7e03590d089e.jpg)


Currently i can't delete the work profile from the system.

**Comment by Goooler** [comment]
https://support.google.com/work/android/answer/7029561?hl=en
https://www.techtarget.com/searchmobilecomputing/tip/How-to-delete-or-disable-an-Android-work-profile
