### ISSUE TITLE
REMOVE ICONS LG G6 NO OPTION

### ISSUE THREAD

**Issue by washthecat** [Deletescape-Media/Lawnchair#313]
No option to remove icons when press icons on homescreen (only edit and app info appear as options)

**Comment by fonix232** [comment]
Because there's no remove option.

**Comment by RWOne** [comment]
Set lawnchair as default launcher and retry.

**Comment by washthecat** [comment]
It is set as default, still not there, works fine in another phone which has a custom rom.  Also a bit flaky moving icons etc on home screen on G6.  Thanks anyway, not sure why my post was closed

**Comment by KieronQuinn** [comment]
Can you not drag the icon to the top of the screen to remove? The delete icon was removed from the long press menu a bit ago

**Comment by washthecat** [comment]
Yes thanks that works fine, sorry for my confusion
