### ISSUE TITLE
[BUG]  Crash clicking on "icon style"

### ISSUE THREAD

**Issue by filcorti** [Deletescape-Media/Lawnchair#3131]
### Describe the bug

Lawnchair crashes everytime I tap on icon style

### Steps to reproduce

1. Go to General Settings
2. Click on Icon style
3. Crash

### Expected behavior

Should give me the chance to change icon style

### Device information

- Device: Pixel 6
- OS: T1B3.221003.008
- App version: 12.1.0 Dev (#1394)

**Comment by KirmesTVAustria** [comment]
I also have it on my Samsung Galaxy A53 5G with Android 13

**Comment by zhuohoudeputao** [comment]
I met this, too. Perhaps because Android added a new 'Themed icon' toggle in settings
