### ISSUE TITLE
Icons getting duplicated/linked

### ISSUE THREAD

**Issue by Drwaffles90** [Deletescape-Media/Lawnchair#3132]
### Describe the bug

If you drag an application from the lower section that shows installed apps straight into a folder on the quick access dock, it will get duplicated on the home screen page too.. Sometimes removing that duplicated icon removes both icons and in my Instance the folder too.

### Steps to reproduce

1. Goto lower app draw
2. Drag icon to quick access dock
3. Go back to lower app draw
4. Drag another icon over that same icon (create a folder)
5.  You'll see a duplicate was created on the desktop
6. Remove duplicate from the home page and the folder will also be deleted from the dock

### Expected behavior

Duplicate not created in the process.

### Screenshots

![Screenshot_20221126-224254](https://user-images.githubusercontent.com/38597936/204086973-b00906de-eb1e-4fe3-835f-61af579e7193.png)

### Device information

- Device: [e.g. Google Pixel 7 Pro 
- OS: [e.g. stock ROM Android version 13??
- App version: just downloaded, so current.

**Comment by jgottlander** [comment]
I have the same issue, just installed the latest alpha.

Device information

    Device: Fairphone 4
    OS: Android 11, FP4.FP4I.A.175.20221207
    App version: 12.1.0 alpha 4

**Comment by Goooler** [comment]
Can u provide a screen record? Seems I can't repro this on my device.

**Comment by Zelaf** [comment]
https://user-images.githubusercontent.com/10819462/216111895-e1a06e7f-d92b-4071-a866-d254bfb95aa0.mp4

I decided to make a video! I'm having this issue as well on my Fairphone running the new Android 12 update. Had it as well on the Fairphone when running LineageOS 20.

Edit: Very curious, after the crash from the video (This is unrelated to this issue however. I think there's another issue related to running out of memory open) it seems like it's not happening now.

**Comment by Goooler** [comment]
The duplicate is showing when you are dragging an icon into a folder in Workspace instead of Dock now. I'll investigate it later.
