### ISSUE TITLE
[FEATURE] allow for picking custom dynamic icons

### ISSUE THREAD

**Issue by nonetrix** [Deletescape-Media/Lawnchair#3138]
### Describe the feature

Allow for changing the used icon on lawnicons via lawnchair for example changing the icon of simple dailer to a dynamic one which currently isn't possible

### Why would it be useful to add?

For apps that don't have a lawnicons icon but already have a icon that would fit perfectly like a phone, calendar, and weather app for example

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221127-220021](https://user-images.githubusercontent.com/45698918/204191970-2958865f-d312-443d-a143-b4d42de168e9.png)
![Screenshot_20221127-220651](https://user-images.githubusercontent.com/45698918/204191978-af2000bd-acef-42c1-8734-9bdc8033ebdc.png)
![Screenshot_20221127-220656](https://user-images.githubusercontent.com/45698918/204191985-e2bcd4a4-a690-4bec-93b1-131595864fa9.png)
![Screenshot_20221127-220702](https://user-images.githubusercontent.com/45698918/204191994-7c3a1e98-a619-4a04-b4fb-0cf73dd661c9.png)

**Comment by zhuohoudeputao** [comment]
It seems lawnicons is not recognized on Android12.1, too.

**Comment by naveenccmsd** [comment]
@zhuohoudeputao this functionality is already added to lawnchair but the changes not finished yet for lawnicons.please wait for changes to be added to lawnicons.

If you want , You can try below debug version for now. 
https://github.com/LawnchairLauncher/lawnicons/actions/runs/3556396187

**Comment by zhuohoudeputao** [comment]
> 

Actually, I installed the latest build and lawnicons.
![Screenshot_20221130-141141_Settings](https://user-images.githubusercontent.com/35682614/204721830-2557608e-4c7e-4f0f-a49b-4b29bac7efc8.png)
![Screenshot_20221130-141437_Lawnchair](https://user-images.githubusercontent.com/35682614/204721897-9478840c-26c4-46ee-b566-da8fb938cbd5.png)

**Comment by naveenccmsd** [comment]
as I told the lawnicons build is not ready yet. So you will have to for sometime.

**Comment by nonetrix** [comment]
This is still relevant

**Comment by NiciTheNici** [comment]
For anyone stumbling on this issue: This is already fixed, but not in any stable release yet. Install a development version from [this repo](https://github.com/LawnchairLauncher/lawnicons/actions) to use the fixed app today:

> For the development versions with new icons, go to the [Actions](https://github.com/LawnchairLauncher/lawnicons/actions) tab, click the first workflow run, and scroll and find the Debug Apk.
