### ISSUE TITLE
[BUG] Quickswitch doesn't work with v12.1+

### ISSUE THREAD

**Issue by doriandejong** [Deletescape-Media/Lawnchair#3139]
### Describe the bug

Quickswitch(v3.3.1) doesn't work with Lawnchair 12.1+ and does with Lawnchair 12.0+

### Steps to reproduce

In Quickswith I can't enable it Lawnchair v12.1+ but can with v12.0

### Expected behavior

That Quickswith works as it does with Lawnchair 12.0+

### Screenshots

![169104576-8f7374d6-de75-49f7-80d6-d8567b568e05](https://user-images.githubusercontent.com/79090547/204354016-9b461128-0732-4776-b752-406e2cc35cbf.png)

It's an older picture but, I tested it with newer alpha's to.

### Device information

- Device: Samsung m31
- OS: android 12, one UI, 4.1
- App version: 12.1+
- Magisk: 25.2
- QuickSwitch: 3.3.1

### Additional context

If this isn't a bug(i'm sorry), how can i get quickswitch to work with Lawnchair 12.1+?

**Comment by keyjeyelpi** [comment]
It's a OneUI thing. I experienced the same thing when I was using OneUI, but when I used AOSP, it worked just fine.

**Comment by tobylaifun** [comment]
it might work with Android 12l, i think

**Comment by tobylaifun** [comment]
it only works with Android 12l
> This branch houses the codebase of Lawnchair 12.1, currently in alpha and based on Launcher3 from Android 12.1. 
(from the readme)
