### ISSUE TITLE
[FEATURE] Lawnchair Searchbar

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#3162]
### Describe the feature

update the searchbar to the correct material you accent colors

### Why would it be useful to add?

provide a more aesthetically pleasing consistency by using up to date material you standards as provided by Google

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![1670721450848](https://user-images.githubusercontent.com/1809251/206881985-264b6529-93dc-46f1-8e99-46bcde233423.png)

**Comment by KirmesTVAustria** [comment]
I would also like it if the Lawnchair team would add the Pixel Launcher Colors
