### ISSUE TITLE
[FEATURE] Searchbar Widget Replacement

### ISSUE THREAD

**Issue by iOSXPC** [Deletescape-Media/Lawnchair#3165]
### Describe the feature

add support to replace the searchbar with a different search widget

### Why would it be useful to add?

give users a more freedom of customization and control 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

1) see how Nova Launcher 8.0.3 allows selecting a replacement widget for the searchbar
2) alternative method: enable a two row dock option and we can place whatever widget we please

**Comment by McMacMick** [comment]
This, please.  Also, widgets are not able to be resized any less than 2 rows high.

**Comment by McMacMick** [comment]
Any possibility of this?  I know one of the Dev versions has an option for the Google bar, but a KWGT option would be ideal.

Thank you for all the work you guys put in!
