### ISSUE TITLE
[BUG] Order of icons on dock changes after boot

### ISSUE THREAD

**Issue by robw-nl** [Deletescape-Media/Lawnchair#3166]
### Describe the bug

Every time I boot the order of the icons on the dock is changed.  

### Steps to reproduce

Drag icons in the right order
Boot
See the items in another order
Repeat

### Expected behavior

Order should be persistent

### Device information

Google Pixel 7 Pro 256GB
Android 13, latest patches
Lawnchair 12.1.0 Alpha 4

**Comment by Goooler** [comment]
Can't repro this on my Moto X40 (Android 13).

**Comment by robw-nl** [comment]
I think it happens when you made certain config changes, so it doesn't
happen always. I'll see if I can figure out when it occurs.
