### ISSUE TITLE
Crash when deleting one of two apps from a folder on the home screen [BUG] 

### ISSUE THREAD

**Issue by jforseth210** [Deletescape-Media/Lawnchair#3170]
### Describe the bug

When deleting an app from a folder on the homescreen, the app crashes if only one app is left.

### Steps to reproduce

1. Create a folder on the home screen with two apps on it.
2. Open the folder
3. Tap and hold on one of the apps
4. Click the × to remove an app
5. App crashes

### Expected behavior

For the app to place the remaining app in the location previously occupied by the folder.

### Device information

- Device: Samsung Galaxy S20 FE 5G
- OS: Android 12
- App version: Version 2.0-2589

**Comment by Goooler** [comment]
Need logs.

**Comment by jforseth210** [comment]
Where would I find them?

**Comment by Goooler** [comment]
From the notification after crashing.

**Comment by jforseth210** [comment]
Hmm. I'm able to reproduce the crash, but I'm not receiving a notification from Lawnchair. The system: "Lawnchair keeps stopping: App Info/Close App/Send Feedback", popup doesn't seem to show up every time and when it did, the "Send Feedback" app crashed on me too. Will try again later.
