### ISSUE TITLE
[FEATURE]  Custom icons for PWAs

### ISSUE THREAD

**Issue by j0lol** [Deletescape-Media/Lawnchair#3179]
### Describe the feature

Add support for adding custom icons to installed PWAs.

### Why would it be useful to add?

While apps can be used for making web shortcuts with custom icons, this is not extended to PWAs. If you attempt to make a shortcut in one of these apps, it will just open in the designated web browser instead of being a standalone app. Adding custom icons to PWAs would allow users to theme PWAs without losing functionality like notifications, offline viewing, etc.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

im not sure what to put here

**Comment by icarusinthewings** [comment]
This issue should be closed, because it's basically a duplicate of #2674.
PWAs, at least in Firefox, are implemented as shortcuts.

**Comment by Goooler** [comment]
Duplicate of #2674
