### ISSUE TITLE
[FEATURE] Add option to make themed icon background transparent

### ISSUE THREAD

**Issue by Adish08** [Deletescape-Media/Lawnchair#3182]
### Describe the feature

The transparent background of app icon makes the Homescreen feel more Minimal and Cool !

### Why would it be useful to add?

Nice question tho.
Mentioned above :)

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

NA

**Comment by ghost** [comment]
Try making a shortcut widget using:
https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&gl=US (after that make the icon lawnicons)

**Comment by bitokulo** [comment]
Do you mean how everytime an app's icon doesn't fit the format (square, circle, etc), it fills the remaining space with white? That's a pain for some apps... It should indeed have an option to not white out blank space, just keep it transparent.
