### ISSUE TITLE
[FEATURE] Make Folder Open Animation like Pixel Launcher and also add automatic naming of folder names like Pixel Launcher

### ISSUE THREAD

**Issue by Adish08** [Deletescape-Media/Lawnchair#3183]
### Describe the feature

Make Folder Open Animation like Pixel Launcher, which feels more consistent and smooth

Add automatic naming of folder names like Pixel Launcher feature looks great

### Why would it be useful to add?

Because Lawnchair is a great launcher and this would make it top-notch.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

NA

**Comment by ghost** [comment]
I'm pretty sure this would be impossible without the user rooting..
