### ISSUE TITLE
[BUG] Lawnchair not automatically adding apps to Homescreen when installing them using APK

### ISSUE THREAD

**Issue by Adish08** [Deletescape-Media/Lawnchair#3185]
### Describe the bug

When I try to install an application with .apk file, Lawnchair is not adding it to the HomeScreen.

### Steps to reproduce

1. Go to 'apkmirror.com'
2. Click on 'Any Application'
3. Scroll down to 'Download'
4. Install the downloaded apk
5. See error

### Expected behavior

It should add the app to homescreen automatically

### Screenshots

NA

### Device information

- Device: [Poco F4]
- OS: [ProtonPlus Android 13]
- App version: [12.1 Alpha 4 ]

**Comment by Goooler** [comment]
This is expected behavior.
