### ISSUE TITLE
[FEATURE] Ability to choose page indicator style + Style addition request

### ISSUE THREAD

**Issue by Palloxin** [Deletescape-Media/Lawnchair#3188]
### Describe the feature

The ability for users to choose the style of the page indicator since currently you can't. I also would like to propose the first new style (see example section) and it is nothing new, just a copy from a native launcher of huawei that is very good looking but simple.

### Why would it be useful to add?

The current one sucks. Also, the customization of things is not a bad thing. About the new style, it is pleasant to the eyes in my opinion.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://user-images.githubusercontent.com/75091899/208122956-93fd812a-5b88-4c1a-9bb9-d69bd33b550d.mp4

![Screenshot_20221216-154338](https://user-images.githubusercontent.com/75091899/208123510-eec6aaf5-4eba-4f52-bbfd-234e3f0ae9b5.jpg)
this screenshot is for taking the misure of the elements of the page indicator

### Additional context

Take in mind that another known launcher (nova) has the ability to choose the page indicator AND they have added this "kind" of style to their option. The point i want to make is that they did a terrible job and i hope you see the difference avoiding the same mistake. This is how it is on nova:

https://user-images.githubusercontent.com/75091899/208125094-a9a8a932-54a9-4c4a-9dca-22408790ec23.mp4

the circles are too big, too near and the colors is not right (between the circle of the current page and the other is too "near"). it is better if you replicate the same colors of the huawei launcher using a color picker from the screenshot.
The launcher i took the video is Huawei Home. i can extract the apk of that app if you need it.

**Comment by Palloxin** [comment]
https://user-images.githubusercontent.com/75091899/208137285-a22147f5-6ef4-411f-8901-06a39b14656c.mp4

I forgot to add that this happens when i pick an icon to move it: the points start to distance themself for each other

**Comment by Palloxin** [comment]
It is still a good feature suggestion

**Comment by Palloxin** [comment]
.

**Comment by algatern** [comment]
This is a good idea. Even if just an option to disable the page indicator altogether. The horizontal line doesn't complement Lawnchair's design.
