### ISSUE TITLE
[FEATURE] Aesthetic improvement of the menu that appears in the desktop when you hold on an empty space

### ISSUE THREAD

**Issue by Palloxin** [Deletescape-Media/Lawnchair#3189]
### Describe the feature

The changes are substantial so i am not able to list them with words  so check the example section. 

### Why would it be useful to add?

The current one is not good looking, seems old fashionated and the QoL layout is not good either compared to the one i will propose (see example section)
I think the advantages of it are obvious if you see the video. If you don't, ask me what you don't get just from watching the video :)

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

My suggestion:

https://user-images.githubusercontent.com/75091899/208129128-a52e76e2-ba30-41d2-af7d-1fdeb0b59930.mp4

Actual Lawnchair(for comparison):

https://user-images.githubusercontent.com/75091899/208130092-c4cfc74a-f0fe-4a21-b3c8-a8527ec7b60d.mp4

1. As you can see(first video) just holding on an empty space of the desktop will show up all the options that already appear doing the same thing on the current version of the app, plus the ability to choose the animation between the change of pages.
2. Ability to add new pages directly there;
3. 
![IMG_20221216_162512](https://user-images.githubusercontent.com/75091899/208131214-745c32d1-0422-4e71-9a04-d5e771b3b04f.jpg)
![IMG_20221216_162500](https://user-images.githubusercontent.com/75091899/208131253-91330c86-9d17-4037-ab68-3899b4c65070.jpg)
Just comparing the two, the Lawnchair one loses easily, hands down just aesthetically speaking without talking about the QoL improvements that the suggestion can bring.
4. transition option easly reachable
5. On the utility of the new widget part, i am not sure if it is better. The differences are not even substantial so i don't think a change for that is really needed
6. 
![IMG_20221216_163419](https://user-images.githubusercontent.com/75091899/208133399-ab819c22-7983-40c4-a460-9f137f46aedc.jpg)
all these options are already present and reproposed in a better form in the improvement i presented to you. So one doesn't lose advantages of the actual one (lawnchair) if the improvement disposition is implemented

### Additional context

The app i took the video from is Huawei Home, a huawei launcher of my huawei p8 lite 2017 android 8 miui 8.
I can extract the apk and give it to you if you need it. Also if you need other material just ask for it ;)

**Comment by Palloxin** [comment]
I just noticed there is a more recent version of Lawnchair  alpha 4, i was using the play store version.
Anyway i just checked and there is not much difference. my suggestion is still valid

**Comment by keyjeyelpi** [comment]
Lawnchair's goal is to make a Pixel Launcher that's more customizable, not replace Nova Launcher. I doubt that page scrolling would be one of the things they'd add.

**Comment by Palloxin** [comment]
you can't deny it is better on aesthetic and utility

**Comment by ghost** [comment]
Eeehh.. kinda looks worse, and doesn't match lawnchair's style... Don't like this feature request.. :)

**Comment by Palloxin** [comment]
.
