### ISSUE TITLE
The application fails (crashes)

### ISSUE THREAD

**Issue by Pedro1999** [Deletescape-Media/Lawnchair#319]
The application crashes many times when you exit after modifying any settings on it. Nexus 5X Android O DP4

**Comment by Alexd13trich** [comment]
I had this problem on the 6P as well. Stopped crashing when I turned off transparent app drawer and pixel icons. Used a custom Android O icon set instead

**Comment by VinceCgto** [comment]
I've been having frequent crashes as well. I've seen it crash after changing the default system language, when updating apps or just completely random.

Restoring the settings by going to 'Import settings' makes the app crash again. Database restoring works but to a certain degree (it doesn't restore the custom icons or widgets, don't know if this is intended behavior).

Phone: Oneplus 3T Android 7.1.1

**Comment by Risku119** [comment]
It crashes everytime on Redmi Note 3.

**Comment by Risku119** [comment]
Please developer do sth. About it..
