### ISSUE TITLE
[BUG] Lawnfeed is not working in vietnam

### ISSUE THREAD

**Issue by thanhvuongx** [Deletescape-Media/Lawnchair#3194]
### Describe the bug

i cant use lawnfeed in vietnam

### Steps to reproduce

1. install  'lawnfeed in my dad phone'
2. Click on 'install'
3. See not working

### Expected behavior

Lawnfeed before is working

And today is not working

### Screenshots

See Is Screen Recording

https://user-images.githubusercontent.com/120753695/208189635-34519f18-6c17-4df0-a438-8d44dcb99d38.mp4

### Device information

- Device: [Galaxy A52s 5G]
- OS: [stock ROM Android version 12.0 One UI 4.1]
- App version: [12.1.0 Alpha 4]

**Comment by AngelofVerdant** [comment]
Have you tried reproducing the  bug with somebody that is outside of Vietnam or use a VPN to confirm that it is a geographical issue??

**Comment by thanhvuongx** [comment]
> Have you tried reproducing the bug with somebody that is outside of Vietnam or use a VPN to confirm that it is a geographical issue??

no i not use vpn

**Comment by AngelofVerdant** [comment]
> > Have you tried reproducing the bug with somebody that is outside of Vietnam or use a VPN to confirm that it is a geographical issue??
> 
> no i not use vpn

Try using a VPN and see if it behaves the same way

**Comment by thanhvuongx** [comment]
> > > Have you tried reproducing the bug with somebody that is outside of Vietnam or use a VPN to confirm that it is a geographical issue??
> > 
> > 
> > no i not use vpn
> 
> Try using a VPN and see if it behaves the same way

NO

**Comment by mon-jai** [comment]
Not working in Taiwan too. Running the latest apk built with CI.

**Comment by thanhvuongx** [comment]
guys is working for me someone closed is issue now
