### ISSUE TITLE
[BUG] Double tap to sleep regression after commit db5d280

### ISSUE THREAD

**Issue by osm0sis** [Deletescape-Media/Lawnchair#3204]
### Describe the bug

After the addition of https://github.com/LawnchairLauncher/lawnchair/commit/db5d280df90dafe35ed7739d1373de635c0bfeb7 now Double tap to sleep only vibrates and nothing else happens.

I've tried setting the Double tap gesture to None and back to Sleep, and disabling Lawnchair's Accessibility service and enabling it again, but it makes no difference.

### Steps to reproduce

1. Install a Dev build # 1463 or later
2. Double tap the desktop to try to sleep
3. Nothing happens anymore
4. Downgrading to a previous Dev build gets it working again.

### Expected behavior

Double tap to sleep should turn off the screen and sleep the device.

### Device information

- Device: OnePlus 9 Pro
- OS: Lineage 19.1 20221220 nightly (Android 12L)
- App version: Lawnchair 12.1.0 Dev (# 1463 or later) + QuickSwitch 3.3.1 + Magisk Canary 25205, set as current recents provider

**Comment by MadMan5645** [comment]
I just submitted an issue for nearly the same thing hoping it gets fixed soon!
