### ISSUE TITLE
[BUG] Square button Stops working

### ISSUE THREAD

**Issue by Zephyr918** [Deletescape-Media/Lawnchair#3205]
### Describe the bug

After a while, the square button just stops working. Happens at random. Not using anything special. Not rooted. Restarting the phone, or lawn chair fixes the issue temporarily. 

### Steps to reproduce

I am unsure.
Just using it for any unspecified amount of time causes the issue.

### Expected behavior

Square button should work.

### Device information

- Device: Google Pixel 4a
- OS: Stock rom Android 13 October security patch
- App version: 12.1.0 Alpha 4

**Comment by EliasHasle** [comment]
I have a similar issue. My square button leads to a pop-up that says Quickstep has crashed. Which is weird, since Quickstep was the launcher app that was included on my phone. I would expect that selecting Lawnchair as launcher would make it intercept square button presses too.
