### ISSUE TITLE
Pill widget weather style - At a Glance alternatives 

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#3207]
### Describe the feature

At a Glance widget is a major feature of pixel launcher from day one. Weather widget and search function in a shape of a pill was introduced on Pixel 1 phone and all pixel lovera were thrilled. As pixel phones evolved, so did the glance widget, providing useful information directly on your desktop, such as calendar events, weather conditions, reminders, timers, nest camera info etc. Customized aosp based launchers such as Lawnchair itself gave us some useful customisation on glance widget like text size, different weather providers, weather icon pack support, clock and date styles. During time, many versions dropped support of such features. It would be lovely to have access on all these missing features on latest builds of Lawnchair again, especially pill style with big nice weather icons i do prefer more🤤

### Why would it be useful to add?

What's more to ask? Just customisation on max level. Glance widget is dope, give access to notification messages, bring back pill weather style, make us happy again!

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![IMG_20221222_105432](https://user-images.githubusercontent.com/17604453/209096221-82961098-30ab-4c17-bdda-789c191d311d.jpg)

**Comment by ghost** [comment]
Kwgt packs? You can try that! Although they cost money, I think it's pretty worth it
