### ISSUE TITLE
[BUG] Themed Icons(Lawnicons) turning off automatically 

### ISSUE THREAD

**Issue by dhirenvasnani** [Deletescape-Media/Lawnchair#3208]
### Describe the bug

Themed icons turn off automatically if I change any Lawnchair's setting or uninstall any app.

### Steps to reproduce

Steps to reproduce the behavior:- 
Uninstall any app, Change any settings (under Lawnchair).

See error

### Expected behavior

Themed Icons should not turn off after changing any setting or uninstalling any app.

### Device information

- Device: Poco C3
- OS: MIUI 12 based on Android 10
- App version: #1470

### Additional context

None

**Comment by matteopt** [comment]
Also happening on:
- Device: Huawei P10
- OS: EMU 9.1.0 / Android 9
- App version: 12.1-dev https://github.com/LawnchairLauncher/lawnchair/commit/848ae402c85d4843916ba709837f501a13202ffe

When setting themed icons ON, installing/uninstalling apps or changing certain settings resets themed icons to OFF.

**Comment by J-khatri** [comment]
Same issue happens on oxygenOS 13  

Lawnchair Dev build 12.1 ( #1491)

Lawnicons 1.2.0

**Comment by rushiiMachine** [comment]
Also happening on:
- Device: Pixel 6
- OS: ProtonAOSP 12.4.1 (root) / Android 12
- App version: 12.1-dev  2681ddf

Happens to me when restarting lawnchair

**Comment by rushiiMachine** [comment]
Still an issue

**Comment by 4A8** [comment]
this still occurs to me

**Comment by Dschingan** [comment]
Same

CrDroid 8.10 A12L 
Lawnchair 12.1.0 Dev

**Comment by MerkKey** [comment]
Reopen this issue
Why hasn't anyone fixed this bug yet? It's been years
