### ISSUE TITLE
Notification badges not consistently working

### ISSUE THREAD

**Issue by macuduranti** [Deletescape-Media/Lawnchair#321]
Sometimes they tend to disappear after having been working for some time.
Also I would like to know if when reading for example one conversation from whatsapp and leaving others unread the notification badge should disappear or be there until all messages are read.

**Comment by uzair-inamdar** [comment]
+1. Usually happens after restarting the phone, but it has happened without turning off the phone as well. I have to toggle off and re-enable the notification access for Lawnchair for the dots to come back. I'm on Android O DP4.

**Comment by versavius** [comment]
I noticed i have had this issue also. The fix suggested by the op resolved it for me.

I am using stock Samsung 6.0.1 on a s7edge

**Comment by korbendalos** [comment]
+1 android 7.0 samsung galaxy note 5

**Comment by callmemulo** [comment]
Disabling and re-enable notification access does not fix the problem. WhatsApp still no dot. At least for me. Is there any other suggestion?

**Comment by jerryn70** [comment]
+1 marshmallow 6.0.1 moto x play
