### ISSUE TITLE
[BUG] Conversion = 'End of String'

### ISSUE THREAD

**Issue by validcube** [Deletescape-Media/Lawnchair#3218]
## Heads up
> **I'm not fluent in English, I apologise if my English is not easily understandable to most people.**

### Describe the bug

I'm experiencing lag and crashes after upgrading to debug build `Lawnchair V12.1 Dev (#1485)`, _upgraded from `Lawnchair V12.1 Dev (#1240~ish)` (very old)._

### Steps to reproduce

Steps to reproduce the behaviour:
1. Build Lawnchair `12.1-dev` latest commit or download Lawnchair latest [debug version](https://github.com/LawnchairLauncher/lawnchair/actions/workflows/build_debug_apk.yml)
2. Go to Settings, then "At a Glance" section
3. Observe the issue (Lawnchair lagged)
4. Now, go back and go to the home screen section
5. Observe the issue (Lawnchair crashed `Conversion = 'End of String'`)

### Expected behaviour

Lawnchair shouldn't be lagging out when you open Settings and Lawnchair shouldn't be crashing when you open subsetting.

### Video

https://user-images.githubusercontent.com/93124920/209946004-27574838-7f44-4cfe-acd3-8571020956ed.mp4

### Device information

- Device: Samsung M23 5G (SM-M236B)
- OS: One UI 5.0 (Android 13) - [1st November 2022](https://source.android.com/docs/security/bulletin?hl=en)
- App version: 12.1.0 Dev `(#1485)`

### Additional context

https://katb.in/inipijosika

**Comment by Goooler** [comment]
It should happends on several language envs.
