### ISSUE TITLE
Able to change closing/opening app animation 

### ISSUE THREAD

**Issue by Jendueki** [Deletescape-Media/Lawnchair#3233]
### Describe the feature

Able to change the animation when closing or opening an app

### Why would it be useful to add?

It will make the launcher smoother to use

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://user-images.githubusercontent.com/122082035/211186030-0372d824-2bbf-4f44-9b95-7d7f423880a2.mp4

https://user-images.githubusercontent.com/122082035/211186035-880cca34-70b6-48f7-98b4-c2217f16464a.mp4

### Additional context

The first video is from nova launcher, as you can see when I open the app it will pop up from the app. When I close the app, it will shrink into the app icon and wiggle a bit just like what you can see on the iOS device.

**Comment by Digitalbullits** [comment]
https://drive.google.com/file/d/11GtbFwq6gpgzL3tWwOkfTxCLRx1tP9-l/view?usp=drivesdk

Are you using the correct version of lawn chair for your device? Is lawn chair your recents provider? This works already

**Comment by Jendueki** [comment]
> https://drive.google.com/file/d/11GtbFwq6gpgzL3tWwOkfTxCLRx1tP9-l/view?usp=drivesdk
> 
> Are you using the correct version of lawn chair for your device? Is lawn chair your recents provider? This works already

I'm currently running the latest version, maybe is my device problem? I currently using the nothing phone 1
