### ISSUE TITLE
At a glance widget  settings

### ISSUE THREAD

**Issue by Jendueki** [Deletescape-Media/Lawnchair#3235]
### Describe the feature

Able to show notifications on lawnchair at a glance widget and resize the size of the widget, the current at a glance widget is too small and also it only show date and time, but not day.

### Why would it be useful to add?

The old at a glance widget on lawnchair v2 is just too good, not only it look good and it's very convenient to use and blends in my setup very well, I always like to open apps through notifications.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20230108-165205~2](https://user-images.githubusercontent.com/122082035/211188010-d5ae706a-966f-40ac-9115-7cb5298c4846.png)

**Comment by Digitalbullits** [comment]
You can do this simply by manually adding the widget
![Screenshot_20230112-110141](https://user-images.githubusercontent.com/52849956/212117479-dfc83808-b276-406c-a685-491661e1bcc7.png)
