### ISSUE TITLE
[FEATURE] Support android 13 Quickswitch

### ISSUE THREAD

**Issue by arandomhooman** [Deletescape-Media/Lawnchair#3249]
### Describe the feature

Self evident 

### Why would it be useful to add?

Because it would be the first launcher to actually use your product (Lawnchair made quickswitch). Quickswitch is also useless at the moment

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

None

**Comment by arandomhooman** [comment]
Pleaseeeeee support your own project.

**Comment by SeriousHornet** [comment]
It must be a no brainer. Lack of quickstep currently hinders the usage of Lawnchair in Android 13 to a great extent. Please add the support. Thanks.

**Comment by moiSentineL** [comment]
indeed. +1

**Comment by liu-wanshun** [comment]
you can try this

https://github.com/liu-wanshun/LauncherC/actions/runs/4437419072

**Comment by arandomhooman** [comment]
While I am sure it is a great launcher, we are looking for Lawnchair. On a better note, I found a modded version of Lawnchair that does support Quickswitch. Y’all tell me if you want it. Works very well.

**Comment by shiimo** [comment]
> While I am sure it is a great launcher, we are looking for Lawnchair. On a better note, I found a modded version of Lawnchair that does support Quickswitch. Y’all tell me if you want it. Works very well.

I would like that, where did you get it?

**Comment by arandomhooman** [comment]
I will send in one hour, when I get home from school.

**Comment by arandomhooman** [comment]
Very sorry, I won’t be able to send today. I do not have time to refind it.

**Comment by arandomhooman** [comment]
I will send sometime tomorrow. If I don’t, remessage

**Comment by shiimo** [comment]
> I will send sometime tomorrow. If I don’t, remessage

Okay please let me know, I've tried many others but all of them crashes the moment I set them in quickswitch. 😭

**Comment by arandomhooman** [comment]
https://t.me/mrsluffy_releases

**Comment by shiimo** [comment]
> https://t.me/mrsluffy_releases

How did you get it to work?
I first installed the module under magisk, then rebooted.
After, I set it as default provider under quickswitch and then rebooted.

Then finally, I set it as my default launcher using quick switch or my default launcher settings in my system but the launcher crashes with the following error -

java.lang.SecurityException : Permission Denial : createSearchSession from pid=15059, uid=10290

I noticed this same error on under debug apks that is stated to work on Android 13.

**Comment by shiimo** [comment]
> https://t.me/mrsluffy_releases

I tried it without quickswitch this time installed only the magisk module but still the same error..

**Comment by EugeneDP89** [comment]
> > https://t.me/mrsluffy_releases
> 
> I tried it without quickswitch this time installed only the magisk module but still the same error..

From the tg channel 
How to install:
1. Extract lawnchair (dev.apk) from module and install apk.
2. Install QuickSwitch APK.
https://github.com/skittles9823/QuickSwitch/releases
3. Open quickswitch and switch recents provider to lawnchair
4. Reboot and done

So you just installing extracted apk and changing quickswitch provider, like you do with regular lawnchair releases

**Comment by KrazyDeinos** [comment]
Doesn't work after  GOOGLES QPR2 update

**Comment by vladtdr** [comment]
> https://t.me/mrsluffy_releases

omfg i cant believe this worked!!! ive been trying to make it work for 3 or 4 hours now

**Comment by NullCode1337** [comment]
> Doesn't work after GOOGLES QPR2 update

+1 recents is broken on QPR2
edit: install quickswitch and https://github.com/saitamasahil/Lawnchair_Magisk, works on QPR2

**Comment by reyqn** [comment]
This is still an issue

**Comment by jacobchins** [comment]
Still an issue. The above solution of lawnchair magisk does work, but using a Pixel Fold it causes issues with the home button/taskbar. I'm hoping for an Android 13-14 update to lawnchair someday that fixes this!

**Comment by osm0sis** [comment]
There's also the visual issue in the modded Lawnchair of the scrollbar in the app drawer not being as close to the edge as it should be, so the icons are crowded together as well.

I've requested the source changes for the quickstep compatibility so it can be considered for inclusion here by @Goooler et al.

https://github.com/saitamasahil/Lawnchair_Magisk/issues/11

https://github.com/saitamasahil/Lawnchair_Magisk/tree/main/system/priv-app/Lawnchair

But unfortunately they're under no obligation to reveal the source since it's Apache license.

Edit:

Presumably here's the start from @MrSluffy, but someone who knows their way around Lawnchair would have to clean it up and update it for the Dec 2022 and QPR2 issues: https://github.com/LawnchairLauncher/lawnchair/pull/3159

**Comment by KTibow** [comment]
Confused here.

https://lawnchair.app/ says that it has QuickSwitch support, so I don't get why this issue is open. Does it stop working above Android 12?

> Lawnchair made quickswitch

No? I can't find any evidence the person who made QuickSwitch has any relation with Lawnchair.

**Comment by osm0sis** [comment]
Yep, works up to Android 12 but 13+ require changes to get it working. And yeah, paphonb is/was a dev for both.

**Comment by neins** [comment]
Same boat here. Just bought Red magic 8 pro and its launcher (and UI in general) are big mess. I am used to native Pixel laucher on my previous Pixel 3a. I hope it will be release for Android 13

**Comment by osm0sis** [comment]
Nope, still broken.

**Comment by pacjo** [comment]
After recent PRs GitHub action builds are working just fine for me. 

I'm using quickswitch apk 3.3.1 on SparkOS 13.8 (A13, September security patch) on global Redmi Note 10 Pro

**Comment by osm0sis** [comment]
Absolutely right! The new 13-dev branch is working now! 🥳

@Goooler this can be closed as completed! 🙌

**Comment by jacobchins** [comment]
Woot woot! Are the changes between 13 and 14 large? Is there any ETA on a 14 version?

**Comment by MrSluffy** [comment]
Closed as 13-dev branch support QS in A13

**Comment by arandomhooman** [comment]
@MrSluffy My device does not work with it. Every time I applied it, it refused to open launcher.

**Comment by MrSluffy** [comment]
> @MrSluffy My device does not work with it. Every time I applied it, it refused to open launcher.

Specify the device if possible provide a logs, it's kinda hard to be a magician to guess the issue really

**Comment by arandomhooman** [comment]
@MrSluffy I apologize, but I cannot provide logs as I just today wiped and unrooted the device for trade in. The device is a SM-T870 Galaxy Tab S7.
