### ISSUE TITLE
Some glitch

### ISSUE THREAD

**Issue by kici8** [Deletescape-Media/Lawnchair#325]
- like #228: most of the time when you close the shortcut a glitch appears (ghost bubble on the opposite down side).
<img width="462" alt="schermata 2017-07-27 alle 16 42 31" src="https://user-images.githubusercontent.com/26869679/28676495-0d29794a-72eb-11e7-9e16-227dae083931.png">

- when you close Google Now the dock has a bit of delay. 
<img width="462" alt="schermata 2017-07-27 alle 16 43 29" src="https://user-images.githubusercontent.com/26869679/28676441-f2a1c4ce-72ea-11e7-8a0a-c29ece1c85a3.png">

**Comment by RWOne** [comment]
Can't dupe here.

Post phone, room or stock etc ..........

**Comment by kici8** [comment]
OnePlus 3t OxygenOS 4.1.6.

**Comment by TomiOhl** [comment]
#cannotreproduce on Xiaomi Mi5S / MIUI8 / Android 7.0 / Lawnchair build 939

**Comment by TomiOhl** [comment]
Update: the ghost bubble issue is there after updating to android 7.1.2
