### ISSUE TITLE
Icon pop-up glitch

### ISSUE THREAD

**Issue by Arqamsidd24** [Deletescape-Media/Lawnchair#328]
When column size is 5, pop-up by holding the middle app on the main screen goes out of the screen.

**Comment by Arqamsidd24** [comment]
![screenshot_20170728-153144](https://user-images.githubusercontent.com/20754412/28714118-6b35eb66-73ab-11e7-8bf7-47d6d97bfca9.png)

**Comment by suphon-t** [comment]
Larger column sizes are not designed for small screens.
