### ISSUE TITLE
[FEATURE] Option to adjust dock size

### ISSUE THREAD

**Issue by felixaszx** [Deletescape-Media/Lawnchair#3289]
### Describe the feature

Trying to shrink the height of dock when search bar is disabled?

### Why would it be useful to add?

Its really unconfutable when there is a huge blank, and it was supported in Lawnchair2

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20230129_180734_Lawnchair](https://user-images.githubusercontent.com/101950667/215360910-125eab4d-5c26-4c32-96c6-e17cfa8ce317.jpg)
This huge gap

**Comment by tslnox** [comment]
I second that, with gesture navigation (no nav bar) the gap is even more horrendous.

**Comment by MrSluffy** [comment]
go to Dock -> Bottom Padding
