### ISSUE TITLE
Higher res weather icons / additional icons?

### ISSUE THREAD

**Issue by hassie-dash** [Deletescape-Media/Lawnchair#329]
Hey, I wanted to ask if you needed higher res weather icons or if 144x144 was fine. When I noticed the file sizes, I assume they were extracted from Pixel Pill Widget (Pro) app. Do you need any other icons? / higher res? The max res I have is 512x512.
Ty.

**Comment by fonix232** [comment]
I've already threw up the idea of turning them into vector drawables, which should be the optimal thing. However I won't have the time until tomorrow, so if you think you're up to the task, feel free to do it 😃

**Comment by hassie-dash** [comment]
I've never made vector drawables before but I can definitely try :P

**Comment by AxiK101** [comment]
Plz make them like stock google icons

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hassie-dash** [comment]
#335

**Comment by AxiK101** [comment]
Thanks for reverting to google weather icons. Yes, i am happy now😂😂

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hassie-dash** [comment]
You can see the icons in the xxxhdpi drawable folder. They are the same icons from the Google weather page.

**Comment by RWOne** [comment]
Yes, thanks!
