### ISSUE TITLE
App drawer - Hide Search Apps option

### ISSUE THREAD

**Issue by versavius** [Deletescape-Media/Lawnchair#331]
![screenshot_20170728-130803](https://user-images.githubusercontent.com/11394779/28716622-25d3f640-7396-11e7-90e4-c565a1252637.png)

**Comment by versavius** [comment]
Is it possible to have an on/off option for searching through the installed apps in the app drawer, i just would like to disable the option but i know people do use it so an enabled/disabled option would work for everyone just like in the stock launcher on android 6.

Thanks

**Comment by sabith-mk** [comment]
Thank you @fonix232. I just came here to raise this issue.

**Comment by mattcooperkay** [comment]
Would love the option too. Never use it.

**Comment by ChristopheVersieux** [comment]
Why has this issue been closed?
I cannot find this option...

**Comment by fonix232** [comment]
@ChristopheVersieux a closed issue does not mean an implemented feature.
