### ISSUE TITLE
[BUG] google keep widget shows 'problem loadind widget'

### ISSUE THREAD

**Issue by tonydiep** [Deletescape-Media/Lawnchair#3315]
### Describe the bug

. Lawnchair on samsung tablet cannot display google keep widget
. Widget displays properly in lawnchair on phone
. Google widget does look different so google may have a separate widget for tablets

### Steps to reproduce

1. Add google keep notes widget on tablet 
2. Widget shows "problem loading widget"

### Expected behavior

Widget shows contents of google keep notes

### Device information

- Device: samsung s6 lite 
- OS: Samsung's stock android 12
- App version:

**Comment by tonydiep** [comment]
Might have to do with the Google Keep widget's updates to support Android 13. I notice Keep widget looks totally different in Trebuchet and OneUI 5.

**Comment by Mystic-duck** [comment]
![Screenshot_20230225-074311](https://user-images.githubusercontent.com/126313578/221342931-19e1fe0e-3c2e-4799-998c-32a05f479162.png)
Hi, i have the same problem for like a month :

Device : pixel 4a 5g G025E
Android 13
Build number : TQ1A.221205.011
Lawnchair version : version 2.0-2589
Google keep version : version 5.23.022.00.90

Works like a charm on default pixel launcher, but won't load on lawnchair



Edit : it seems to be fixed, it's working again in lawnchair for me with the new Google keep update version 5.23.102.03.90

**Comment by apoloapolo** [comment]
I had to go back to Google keep's version 5.22.502.03.09 then the widget works, newer versions don't work.

I have a Galaxy S21 (Exynos) One UI 5.1 Android 13.

**Comment by sopatt** [comment]
![Screenshot_20230310_002837_Lawnchair](https://user-images.githubusercontent.com/6844086/224265193-e93447d3-d15e-4c0c-b773-70da82ebc0c3.jpg)
![Screenshot_20230310_003337_Lawnchair](https://user-images.githubusercontent.com/6844086/224265245-a5176760-8539-43cc-8905-f38aa27d5a09.jpg)

I have this problem on my Samsung a14 and my moto g. It's the widget that shows the notes (left side on the screenshot). Wild guess it's a permissions issue.

**Comment by sopatt** [comment]
> I had to go back to Google keep's version 5.22.502.03.09

How?

I figured it out. I Googled archive apks. In the play store I pulled up keep, Uninstaller, installed old apk, and back in play store set keep to not auto-update.

**Comment by tonydiep** [comment]
FYI I've installed current keep widget in current lawnchair in android 9 and the widget looks fine. I notice the widget has rectangular corners instead of Android 13s rounded corners.

**Comment by sopatt** [comment]
As of today I tried updated lawnchair and widget and it still bugs out.

**Comment by tonydiep** [comment]
Seems to be working now.

**Comment by Mystic-duck** [comment]
The issue is occuring again with the latest update of google keep.

**Comment by tonydiep** [comment]
Somebody suggested using version 12 on GitHub and I can confirm it shows Google Keep widget correctly. 

However it, like most other 3rd party launchers, can't handle recents / overview gesture consistently.

**Comment by wrmike1** [comment]
This may be the same bug:

The Gmail widget shows "Widget failed to load".
Pixel 6a, Android 13, Lawnchair 2, v 2.0-2589

Been like that for 2-3 months.

**Comment by aJIEw** [comment]
After updating to Google Keep 5.23.3xx, the widget is not loading again, and after downgrading to 5.23.1xx, it's working now. My current solution is to disable auto update and wait until this is fixed (whether it's the Google Keep or Lawnchair).
