### ISSUE TITLE
[BUG] Lawnfeed links not working

### ISSUE THREAD

**Issue by gregchak** [Deletescape-Media/Lawnchair#3336]
### Describe the bug

When tapping on any item in lawnfeed nothing happens. A browser doesn't open, nothing. I can tell that I've tapped it because I get the ripple, but nothing happens. The favorite button and menu button seem to work but the share button does not. Like when tapping the tile, the share button doesn't do anything.

### Steps to reproduce

1. Go to lawnfeed feed
2. Tap on any of the items in the feed
3. Nothing happens

### Expected behavior

Links open in browser

### Device information

Device: Samsung Galaxy Tab S3 SM-T820
OS:Lineage variant based on Lineage 20 (20-20230102-UNOFFICIAL-gts3lwifi)
App version: Lawnchair 12.1 alpha 4, Lawnfeed 3

### Additional context

I have the same problem using v2 from the Play store. Because of this it does make me think it's something with my device or config, but I can't seem to find anything that would be causing this issue.

**Comment by ghost** [comment]
I don't know what you're talking about, it works just fine for me? Try re-installing.
