### ISSUE TITLE
[FEATURE] add pixel animations for pixel-based or stock android software

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3347]
### Describe the feature

Stock android or pixel-based software aka AOSP based software on android 12 has a secret animation code which allows android launchers to have animations (without root)

### Why would it be useful to add?

Makes it more of a pixel experience

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Use hyperion or nova launcher in pixel-based stock android or aosp based roms

**Comment by SlowNicoFish** [comment]
Not sure if this is relevant
https://android.googlesource.com/platform/packages/apps/Launcher3/+/30ac97d9386736c3322a3277f74523497627b9f5
