### ISSUE TITLE
Option to hide the dock

### ISSUE THREAD

**Issue by sabee93** [Deletescape-Media/Lawnchair#3354]
### Describe the feature

Option to hide the dock on the homescreen. This was already available in the last Play Store version. I'm still sticking to the play store version just for this feature but would be great if this was added to the latest version so I can switch over.

### Why would it be useful to add?

Never thought about it until I tried it, but this allows the additional home screens to have full screen widgets, which look pretty neat. And I don't need the dock to be showing up on every home screen. i.e. if I'm swiping towards the other homescreens, I've already decided I'm not looking for the apps on the dock.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20230308-091116](https://user-images.githubusercontent.com/12422252/223565237-36e8d724-78d6-4399-a557-505feebb9c59.png)

**Comment by ghost** [comment]
Yes! I don't know why they haven't added that to the new versions... It would be so useful!

**Comment by Meyu-Sys** [comment]
I second this

**Comment by Meyu-Sys** [comment]
This would be a really useful feature as the spacing between the dock and regular icons has always been annoying and limiting
