### ISSUE TITLE
Recent History to App Drawer

### ISSUE THREAD

**Issue by Kaisar870** [Deletescape-Media/Lawnchair#3357]
### Describe the feature

Could you please bring back App Recent History on Top of the App Drawer? Like the pixel launcher.

### Why would it be useful to add?

This is very handy for day-to-day use.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot (Mar 8, 2023 1_01_05 PM)](https://user-images.githubusercontent.com/75267509/223645424-ccb2d960-9dd6-4d60-b5db-419d5d056d85.png)

**Comment by nettnikl** [comment]
I second this. But asking for clarification, you are talking about *recently used/opened* apps, yes?
In that case let me add a suggestion - give us an option to have the most *recently installed* apps there, too. (In an optimal world i'd like to have both there, in two lines, or even swipeable)

**Comment by Kaisar870** [comment]
Thank you for your response! I really appreciate your effort great work!
Yes, I'm talking about recently used/opened apps in the App drawer
similar to the pixel launcher and lawnchair v2 in Play Store.. I think I
don't want recently installed apps too in the app drawer but swipeable may
be a good idea. Maybe search bar customization would be great too
similar to the dock in the recent version of lawnchair.

Again thank you so much for your hard work.

Regards
Kaisar

**Comment by Kaisar870** [comment]
Also, two lines may be messy, we're pretty used to 3 to 4 apps frequently.
I really like the pixel launcher but I'm used Lwanchair for a long time coz
customization.

**Comment by nettnikl** [comment]
Apart from the little misunderstanding about my contributions to this project, i fully agree with you!

I was just thinking about an easier to implement solution as a stepping stone. I suppose an additional line would be quite easy, and would also do the trick, until we have a swiping solution.

**Comment by guifarias31** [comment]
A recent/frequent used apps on the drawer would be so nice!

**Comment by randomlyalex** [comment]
2025 and I've come back Nova, and just realised how much I used this feature!

**Comment by randomlyalex** [comment]
2025 and I've come from Nova, and just realised how much I used this feature!

**Comment by PhilZ-cwm6** [comment]
One so useful feature in daily use when searching missing when trying to switch from Nova
