### ISSUE TITLE
[BUG] cannot add any widgets on OneUI 4.1

### ISSUE THREAD

**Issue by tonydiep** [Deletescape-Media/Lawnchair#3381]
### Describe the bug

Cannot drag widget to desktop

### Steps to reproduce

1. Add widget
2 long press and drag as the screen instructions say

Result: long pressing does not select widget or let you drag it

### Expected behavior

Long press selects widget

### Device information

- Device: Samsung note 10 plus
- OS: latest stock Android 12. OneUI 4.1
- App version: current as of 2023-03-21

**Comment by ghost** [comment]
Try new versions of lawnchair! (not on play store)

**Comment by tonydiep** [comment]
Thanks! Lawnchair 12 alpha works. Can add widgets. Google Keep widget working.

**Comment by Goooler** [comment]
Alright, I'm closing this issue for now.

**Comment by ghost** [comment]
Why'd you close this as "not planned" shouldn't it be complete?

**Comment by 0xLunch** [comment]
Just came to add I'm on OneUI 6 on a Samsung Galaxy 23.
Maybe only one or two widgets can be placed. Majority of them simply and silently disappear once adding to home screen.

Using 14-dev from 2 days ago (from forked repo that releases built apks)
