### ISSUE TITLE
[FEATURE] Add Alpha versions to Google playstore

### ISSUE THREAD

**Issue by W1zardK1ng** [Deletescape-Media/Lawnchair#3384]
### Describe the feature

The google playstore version of Lawnchair is no longer supported on Android 13.
It shows the message as **This app isn't available for your device because it was made for an older version of android**

### Why would it be useful to add?

Would like to download the app from Playstore instead of side loading it, hope we can use the Play Store Beta channel option.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![image](https://user-images.githubusercontent.com/110819956/226835928-cafb0b3e-0686-4bdf-aa6d-25bc2ecb11f2.png)

**Comment by ghost** [comment]
I'm pretty sure, they're not gonna do that... I'm pretty sure, they said that they are gonna add to play store once lawnchair 3 is done!
