### ISSUE TITLE
Folder in docks reverting to light theme

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#340]
I use dark theme but folder icon keeps returning to white 🤔

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
Any idea when this bug will be fixed??😂

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
Fixed
