### ISSUE TITLE
[BUG] Time Taking swipe gesture

### ISSUE THREAD

**Issue by v12p3r** [Deletescape-Media/Lawnchair#3406]
### Describe the bug

I use the swipe gestures in samsung. When using it to access the task changeer from home screen of lawnchair, it takes some time and i have to hold for a solid seconds

### Steps to reproduce

1 set nav bar to swipe gestures
2 go to home screen in lawnchair
3 do the gesture to access the app switcher

### Expected behavior

it is supposed to come up instantly like how it does when in an app, but it is delayed

### Device information

- Device: Samsung Galaxy A33 5G
- OS: Android 13
- App version: v12.1.0 Alpha 4

**Comment by ghost** [comment]
This is more of a problem of Samsung. If I'm not mistaken?
