### ISSUE TITLE
What is a leak Canary?

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#3426]
So I tried the lawnchair dev Version. (Just to see if there was anything new) and a notification of "leak Canary" popped up, I tapped it and it checked and game me 1 distinct leak:

LawnchairLawncher leaked

┬───
│ GC Root: Global variable in native code
│
├─ com.google.android.libraries.launcherclient.LauncherClient$OverlayCallback
│  instance
│    Leaking: UNKNOWN
│    Retaining 8.8 MB in 28286 objects
│    ↓ LauncherClient$OverlayCallback.mClient
│                                     ~~~~~~~
├─ com.google.android.libraries.launcherclient.LauncherClient instance
│    Leaking: UNKNOWN
│    Retaining 98 B in 3 objects
│    mActivity instance of app.lawnchair.LawnchairLauncher with mDestroyed =
│    true
│    ↓ LauncherClient.mActivity
│                     ~~~~~~~~~
╰→ app.lawnchair.LawnchairLauncher instance
​     Leaking: YES (ObjectWatcher was watching this because app.lawnchair.
​     LawnchairLauncher received Activity#onDestroy() callback and
​     Activity#mDestroyed is true)
​     Retaining 8.6 MB in 25833 objects
​     key = fad46316-b8b3-4741-a1fd-47c2fd93a922
​     watchDurationMillis = 28929
​     retainedDurationMillis = 23926
​     mApplication instance of app.lawnchair.LawnchairApp
​     mBase instance of android.app.ContextImpl

METADATA

Build.VERSION.SDK_INT: 33
Build.MANUFACTURER: samsung
LeakCanary version: 2.10
App process name: app.lawnchair.debug
Class count: 33929
Instance count: 382377
Primitive array count: 223176
Object array count: 40752
Thread count: 45
Heap total bytes: 41484515
Bitmap count: 436
Bitmap total bytes: 40941852
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/app.lawnchair.debug/databases/preferences
Db 2: open /data/user/0/app.lawnchair.debug/databases/app_icons.db
Db 3: open /data/user/0/app.lawnchair.debug/databases/launcher_8_5_4.db
Stats: LruCache[maxSize=3000,hits=172115,misses=332872,hitRate=34%]
RandomAccess[bytes=17437343,reads=332872,travel=167673935331,range=50807979,size
=61605174]
Analysis duration: 21135 ms

Should I be worried about this?

**Comment by Lunxara** [comment]
Would love to know this as well, I imagine it's not supposed to be implemented and I hope to see a new dev release that removes the leaks from the app. There are older dev releases that don't have this however I'm unsure what the most recent release without it is :(

**Comment by ghost** [comment]
Yeah, I don't even know what are the reprucutions of a leak, I assume it's a bad thing but idk in what way? i did like this Dev update (minor changes such as changing the home settings icon and adding system settings entry) but the leak threw me off. I will close this issue when the new Dev update (without the leak) comes!

**Comment by Goooler** [comment]
We use [LeakCanary](https://github.com/square/leakcanary) to detect memory leaks, if you want a release build from each commit, you can try my fork at https://github.com/Goooler/LawnchairRelease

**Comment by ghost** [comment]
thanks! ill check out your fork!
