### ISSUE TITLE
Weather doesn't update itself

### ISSUE THREAD

**Issue by JuliGplus** [Deletescape-Media/Lawnchair#344]
Only if i reboot the launcher...

//Is it possible to have the weather data by my gps position? That would be a great feature too...

**Comment by ghost** [comment]
This happens to me too.

**Comment by RWOne** [comment]
Confirmed here, likely they are aware of it and the location based refresh requests ...

**Comment by tlzxsun** [comment]
It seems the default weather refresh time is 30 hours according to the code if I am not wrong...`    private static final int DELAY = 30 * 3600 * 1000;
...
private void refresh() {
        if (!stopped) {
            mApi.getCurrentWeather();
            mHandler.postDelayed(this, DELAY);
        }
    }`

**Comment by fonix232** [comment]
@tlzxsun it indeed was, but @deletescape fixed it a bit ago :)

**Comment by tlzxsun** [comment]
@fonix232 Yep, I see it. Work like a charm
