### ISSUE TITLE
weather works?

### ISSUE THREAD

**Issue by xmiseggs** [Deletescape-Media/Lawnchair#345]
Hi, I have doubts about how the weather works:

Is the temperature automatically updated?

Will the weather be developed for location based on the current location?

If I have a city introduced from another country, could it be done by clicking on the weather to open this city that I have indicated?

Thank you very much for your work, it's very very good.

Congratulations.

**Comment by RWOne** [comment]
Related, it states entering a country code, could the description show an example? I wouldn't know to do 1, 01 or +1, +01 before City and state in my case ...

**Comment by xmiseggs** [comment]
When you enter the city, the temperature is displayed correctly and it stays the same forever, it does not change automatically, it does not matter if you enter the code in front of it or enter it just like OpenWeatherMap, as the comment shows but does not automatically update. It only changes if I press on the weather and show the date and pulse again on the date and change the weather.

Example:
+34 Madrid
+34-91 Madrid
Madrid
Madrid, ES (like OpenWeatherMap)
