### ISSUE TITLE
Notification dots with now playing not working

### ISSUE THREAD

**Issue by omarmohamedmoustafa** [Deletescape-Media/Lawnchair#3451]
### Describe the bug

At a glance
Now playing (notification dots should be enabled)
Enabling notification dots take me to the main notificaions settings 
I have allowed special access for notifications to Lawnchair but no good results

### Steps to reproduce

1. Go to 'At a glance'
2. Click on 'now playing'
3. Click on 'Change Settings'
4. Click on 'notification dots'
5. See error

### Expected behavior

I expect to be able to allow notification access to lawnchair and boom done..

### Screenshots

![Screenshot_20230506_144559_Lawnchair](https://user-images.githubusercontent.com/93324483/236622442-da9c3d56-736c-4e95-ae30-db943d266d49.png)
![Screenshot_20230506_144609_Lawnchair](https://user-images.githubusercontent.com/93324483/236622443-3e0d0e0f-c250-4dba-a9b0-4aaf34243a0f.png)
![Screenshot_20230506_144615_Lawnchair](https://user-images.githubusercontent.com/93324483/236622446-d98d7042-da1c-45dc-9834-dcc8211b9b9d.png)
![Screenshot_20230506_144621_Lawnchair](https://user-images.githubusercontent.com/93324483/236622448-f8af0ae4-b373-4ddb-9b1a-809478d45284.png)
![Screenshot_20230506_144625_Settings](https://user-images.githubusercontent.com/93324483/236622449-9940977b-950b-4db9-93f2-84f2a41d9839.png)
![Screenshot_20230506_144637_Settings](https://user-images.githubusercontent.com/93324483/236622450-ddaa3ded-7460-4765-aefc-349d2829c591.png)
![Screenshot_20230506_144645_Settings](https://user-images.githubusercontent.com/93324483/236622452-400f27d2-41c2-4dc3-8bd2-3d365da23988.png)

### Device information

Device Samsung galaxy A52
OS stock Android 13 oneui 5.1
App version : 12.1.0.alpha 4

**Comment by omarmohamedmoustafa** [comment]
Any help ?

**Comment by KTibow** [comment]
FYI to anyone else:
You should be able to find the setting using the search function in your settings app (search for "app badge" or "notification dot"), and it should work once enabled.
If you think it shouldn't need notification dots (like I do): There actually isn't an issue for this yet, the closest is one person who said that in the Discord.
