### ISSUE TITLE
Weather/Date info for greek

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#346]
I post two pics, one from original pixel launcher (1st pic), one from Lawnchair (2nd). Plz look how the number of the date on weather widget shows on pixel launcher. At greek you add the day first, then the number of the date, for example 23, then the month. Can you fix it plz? Thanks
![](http://i.imgur.com/Hwv7aEW.png)

![](http://i.imgur.com/e7dKJCW.png)
 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pkerga** [comment]
So in french :
"Day of the week'" "number for the day of the month'" "month'" 
And no ","
Thanks

**Comment by nyancrimew** [comment]
@AxiK101 please provide a PR for this if possible, we have no way of knowing all languages so we depend on Pull Requests for those format changes (see Pull Requests for other languages as an orientation)

**Comment by fonix232** [comment]
@deletescape Couldn't we move these strings too to the actual language
files from donottranslate.xml? That way Crowdin edits could also fix these
kind of issues.

**Comment by nyancrimew** [comment]
@fonix232 we could do that, but only with enough context provided to explain what this string is used for, as the string in it self is pretty unclear

**Comment by pkerga** [comment]
as i know, three way for date format 

    big-endian (year, month, day), e.g. 1996-04-22 or 1996.04.22 or 1996/04/22
    little-endian (day, month, year), e.g. 22.04.1996 or 22/04/1996 or 22-04-1996 or 22 April 1996
    middle-endian (month, day, year), e.g. 04/22/1996 or April 22, 1996 

[https://en.wikipedia.org/wiki/Date_format_by_country](url)

**Comment by pkerga** [comment]
Trying but i can't creat a PR for
Improve weather widget time for french Language
I think it should work as in Portuguese...

**Comment by AxiK101** [comment]
have no idea what a pr is or how to create it

**Comment by nyancrimew** [comment]
@AxiK101 no need to do anything, this will be fixed once new translations are imported
