### ISSUE TITLE
[FEATURE]  Add Android 14 beta 2 visual design changes!

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#3467]
### Describe the feature

Recently google released the android 14 beta 2 update, and it has some really nice stylistic changes!

### 2. Redesgined menu's and animations: <br> <img src="https://github.com/LawnchairLauncher/lawnchair/assets/123305689/a317ee75-6f42-4bfd-afeb-62feeee5348f" width="250">

The rest are not able to be added in a launcher!

### Why would it be useful to add?

'cause it would look good ^_^

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Already shown above!

**Comment by ThatOneCalculator** [comment]
Why was this closed as not planned?

**Comment by ghost** [comment]
> Why was this closed as not planned?

Lawnchair seems doesn't seem to be taking issue rn, but I'll re-open it just in case.

**Comment by ThatOneCalculator** [comment]
Bumping this, as this now appears to be part of Launcher3, so the effect could be taken straight from the source.

**Comment by validcube** [comment]
> The new dots when scrolling through a page

This effect can be achieved by enabling `SHOW_DOT_PAGINATION` in Lawnchair's Developer (Debug) menu.

**Comment by ThatOneCalculator** [comment]
How do you open the developer menu?

**Comment by ThatOneCalculator** [comment]
Works as expected!

**Comment by MrSluffy** [comment]
Closed as it's already exists after merge launcher3 A14

https://github.com/LawnchairLauncher/lawnchair/assets/36076410/17315bda-b640-4c16-864e-4f77398ca590
