### ISSUE TITLE
Question: Google Play Store?

### ISSUE THREAD

**Issue by versavius** [Deletescape-Media/Lawnchair#347]
Hi just wondering if your planning on releasing your app on the Google play store?

**Comment by hassie-dash** [comment]
It won't be possible unfortunately as of yet, because Google Now only works in app debug mode and debug builds are not allowed on the Play Store.

**Comment by versavius** [comment]
Thanks for answering that makes sense was just curious if it was on there as I could not find it :)

**Comment by vanillajonathan** [comment]
How about release a version on Google Play Store without Google Now support?

**Comment by suphon-t** [comment]
Google Now support is now possible. But there are more things preventing a play release.

**Comment by divadsn** [comment]
We had many issues, for example someone have claimed the original package name, so we tried until now to get the old package name back, but now many of us are busy as holidays are over.
