### ISSUE TITLE
Unable to create folders.

### ISSUE THREAD

**Issue by Abcdefghilkjnm** [Deletescape-Media/Lawnchair#3472]
### Describe the bug

I tried to create folder of 2 apps and then instead of forming a folder ,a icon stays on top of another.

https://github.com/LawnchairLauncher/lawnchair/assets/113312069/45db37ee-3c85-48c4-bf1f-a2cbf89cd9b0

### Steps to reproduce

1. Go to 'homescreen'.
2. Create a folder of 2 apps. 
3. Then 1 icon sits on other one. A few times 

### Expected behavior

Form a folder

### Device information

- Device: [Nokia c20+]
- OS: [Android 11 go edition]
- App version: [12.1.0 Alpha 4]

**Comment by saulhdev** [comment]
You might have the overlap option enabled. Go to Settings > Home Screen > Allow overlap
