### ISSUE TITLE
[FEATURE] blurred overview & dock

### ISSUE THREAD

**Issue by bitokulo** [Deletescape-Media/Lawnchair#3489]
### Describe the feature

There could be an option to blur the ~~background~~ wallpaper on the overview and on dock. Plus, there could be an option for a background colour of the dock.

### Why would it be useful to add?

I think it could be pretty if well done, also helps distinguish where's the dock and where's the desktop

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Like this Plasma Dock with blur:
![KDE Dock with blur](https://github.com/LawnchairLauncher/lawnchair/assets/134810902/dba076ae-9bd0-4dce-9477-86a19c5e4e70)

### Additional context

Maybe a 'resizable' blurring option?

**Comment by mihawk90** [comment]
This already exists (unless I'm misunderstanding your request).
edit: To clarify, it exists in v2 (the Play Store version), not in the Alphas though (from what I can find).

First, you'll want to enable background blur:
Settings > Theme > Style
* [x] Blur (Blur page backgrounds)
* Blur Intensity: whatever you like

Then you need to enable a background for the Dock and Drawer respectively:

Settings > Dock > Style
* Dock Style: *Custom*
* [x] Show Background
* Background Colour: *Set by Theme* (default) or whatever you like
* Opacity: 1% or whatever you like
* Dock Size: whatever you like

Settings > Drawer > Style
* Opacity: 1% or whatever you like
* Background Colour: *Set by Theme* (default) or whatever you like

**Comment by bitokulo** [comment]
This repository is for the new version, it is virtually unrelated to the Play Store version.
Edit: I mean, you could just say it will be added soon as that is the goal of this project.

**Comment by mihawk90** [comment]
Well, I can't say that for sure since I'm not a developer ;)

My post was aimed at your response to "Did the feature exist in Lawnchair v2? (Play Store version)" which was "No". This was merely a correction that yes, it does exist in v2, which in turn means it would not be a *new* feature request for 12, but rather a request for porting an existing feature.

Sorry for the confusion.

**Comment by bitokulo** [comment]
Oh! Thank you! I have a hard time spotting stuff, I'm sorry x)

**Comment by bitokulo** [comment]
I'm closing, since this will be added as the promise of adding every feature from v2.
