### ISSUE TITLE
Enhancement: can not relaunch launcher

### ISSUE THREAD

**Issue by versavius** [Deletescape-Media/Lawnchair#349]
Once I install the APK lawn chair is set as my default launcher.

The issue is that if I change my launcher to another launcher and then want to set it back to lawn chair I can not easily do this.

I would propose that following to solve this:

1. Lawnchair has an icon in my add drawer which launchers the lawnchair app. This allows.me to get into the lawnchair app.

2. When opening lawnchair if it is.not the default launcher it should alert you so you can set lawnchair as the default launcher

**Comment by versavius** [comment]
This is how Evie handles this issue, a note in the app drawer telling the user lawnchair is not the default launcher and promoting the user to click to set Evie as the default launcher. I would propose doing the same in lawnchair, this makes it easy if your like me and experiment information and comparing different launchers.


![screenshot_20170729-133329](https://user-images.githubusercontent.com/11394779/28744872-bd86b884-7462-11e7-8c35-e5ddb3134350.png)

**Comment by RWOne** [comment]
"The issue is that if I change my launcher to another launcher and then want to set it back to lawn chair I can not easily do this."

In Android:
Settings -> Type "Home" in search or go directly to "Home App" Then:

In Home app, select the default.

Nothing needs to change in the launcher here.

**Comment by versavius** [comment]
I would say having the items as I mentioned above would make the app more user friendly, it's the same with app permissions we can all grant access from the settings tab but having a popup appear at the right time asking for th relevent permission needed is more user friendly.

I would.still say this is needed

**Comment by RWOne** [comment]
Packing features that can already be accomplished thru the OS isn't needed, coding time and energy can be used to get features and s things one cannot already perform thru the OS.
