### ISSUE TITLE
Tray transparency

### ISSUE THREAD

**Issue by MaGaRCaN** [Deletescape-Media/Lawnchair#35]
How can I make tray 100% transparent?

**Comment by deletescape** [comment]
By tray you mean the list of all apps?

**Comment by MaGaRCaN** [comment]
I mean the icons that appear in the lower part of the desktop (in settings you can choose the amount of them you want ti have).

**Comment by deletescape** [comment]
Right now there is no option to make it fully transparent, but I can implement this pretty easily, maybe tomorrow already :blush:

**Comment by MaGaRCaN** [comment]
Awesome. Thanks!
