### ISSUE TITLE
[BUG] App Crushed with lawnicons 

### ISSUE THREAD

**Issue by Kyawrarzar** [Deletescape-Media/Lawnchair#3514]
### Describe the bug

Lawnchair 12.1.0 Alpha 4 was crushed when I use with lawnicons. App crushed when I setup lwanicons with themed icon option.
I can't use Lawnchair with lawnicons. 

### Steps to reproduce

1.Go to 'Home Settings>> General >> Icon Style'
2.Click on 'lawnicons'
3.Select 'Themed Icons>> Home Screen and App Drawer '
4.Back to 'Home'
5.See error

### Expected behavior

I am using lawnchair 12.1.0 Alpha 4 and I love to use pixel theme icon. So, I downloaded lawnicons from official website.
After installed, I go to 'Home Settings' to setup (Home Settings>> General>> Icon Style). I selected 'lawnicons' and
In 'Themed Icons', I selected 'Home Screen and App Drawer'.
And 'App crushed' was happened.

### Screenshots

![Screenshot_20230623_172028](https://github.com/LawnchairLauncher/lawnchair/assets/118373857/e08be009-b467-4142-9754-39805ffb4af0)

### Device information

- Device: Vivo V20SE (V2022)
- OS: Android version 12
- App version: 12.1.0 Alpha 4

### Additional context

content://app.lawnchair.fileprovider/log_files/f867c69a/Lawnchair%20bug%20report%20Jun%2023%2C%202023%205%3A14%3A10%20PM.txt

**Comment by Goooler** [comment]
Can you paste the stacktrace here?

**Comment by eesanta** [comment]
Having the same problem and seems like same error with themed icons
