### ISSUE TITLE
[BUG]  Can't disable / hide Searchbar at bottom

### ISSUE THREAD

**Issue by Huddeij** [Deletescape-Media/Lawnchair#3526]
### Describe the bug

Can't hide nor disable Lanchair's searchbar on the desktop of my phone. 

### Steps to reproduce

1. Keep holding finger on empty space on desktop
2. Tap on Home Einstellungen
3. Tap on Startseite
4. Scroll down to Statusleiste
5. Deactivate Suchleiste

### Expected behavior

The searchbar should not be there after deactivating

### Device information

- Device: Xiaomi Mi 11i
- OS: e/os 1.11-s20230512288805-dev-haydn
- App version: 12.1.0 alpha 4

**Comment by Goooler** [comment]
It works, see 
<img src="https://github.com/LawnchairLauncher/lawnchair/assets/10363352/d4175cc3-7c91-4871-a115-9c5074abfa9c" width="25%" height="25%">
