### ISSUE TITLE
[FEATURE] Please re-add large numbers of columns/rows

### ISSUE THREAD

**Issue by Kommynct** [Deletescape-Media/Lawnchair#3528]
### Describe the feature

With the latest version of lawnchair it's limited to 10x10, I used to use 19x10. This genuinely makes the recent version unusable for me.

### Why would it be useful to add?

because my phone has significantly more height than vertical space, and I want every space to be the size of an icon.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

n/a

**Comment by kbexit** [comment]
This is available in the latest debug version: 2019 
Experimental settings 
![Screenshot_20230718-115518](https://github.com/LawnchairLauncher/lawnchair/assets/102698001/3c0b8f8c-c75d-4d9d-9568-143f6296f1cb)
