### ISSUE TITLE
[FEATURE] Recents on home button tap

### ISSUE THREAD

**Issue by funforgiven** [Deletescape-Media/Lawnchair#3529]
### Describe the feature

An option to open recents when using gestures, specifically on Home Button Tap.

### Why would it be useful to add?

People without quick switch can access recents without lag.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

In Nova, you can open recents using Home Button Tap and it works instantly without root acces.

![Screenshot_20230705_035227_Nova7](https://github.com/LawnchairLauncher/lawnchair/assets/35855146/2677c448-e55a-45cb-a9b6-abc229eb0321)

### Additional context

I hope it is a minor feature enough to implement since Lawnchair already supports Home Button Tap. However, this feature probably needs accessibility as I observed in Nova, so user should probably be redirected to accessibility page to give accessibility permission to Lawnchair.

**Comment by Sadwhy3** [comment]
Bump

**Comment by Hyphrio** [comment]
bump

**Comment by Sadwhy3** [comment]
Stupid bot
