### ISSUE TITLE
[FEATURE] allow search bar to be on the left or right side in big screen devices

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3535]
### Describe the feature

With the pixel tablet released it should make sense that if you have a big screen device the search bar will be automatically left for easier navigation to the search bar

### Why would it be useful to add?

Navigation and consistency

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Google-Pixel-Tablet-lead](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/c87c5ba1-4de8-4c84-ae1d-d7bbe5ab71a5)

### Additional context

The feature should work with 6 by 5 grid

**Comment by SeanDylan** [comment]
With the debug release it doesn't allow the search bar to be left or right instead of top or bottom what it should have done is that it would move the search bar to left or right and have a option to make it left or right or top or bottom
![Screenshot_20240622-205830](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/f92e7be3-0774-4963-ab3e-3f3b00ae8e1f)

**Comment by Glitch808** [comment]
![Screenshot_20240727_192039_Lawnchair (Debug)](https://github.com/user-attachments/assets/f279aa69-b41f-4eb6-98e2-b13b183683bf)
Same for me
