### ISSUE TITLE
[BUG] Lawnfeed doesn't work

### ISSUE THREAD

**Issue by BGGR101** [Deletescape-Media/Lawnchair#3538]
### Describe the bug

Lawnfeed doesn't show up

### Steps to reproduce

1. Go to home screen
2. Swipe left
3. Nothing shows up

### Expected behavior

Lawnfeed should appear

### Device information

- Device: Realme GT 2
- OS: Latest RUI
- App version: latest

### Additional context

Tried reinstalling both lawnfeed and lawnchair doesn't work (also tried using play store version still nothing)

**Comment by BGGR101** [comment]
restarting fixed the issue

**Comment by KTibow** [comment]
@BGGR101 if resolved please close the issue
