### ISSUE TITLE
[FEATURE] Foldable Optimization 

### ISSUE THREAD

**Issue by kbexit** [Deletescape-Media/Lawnchair#3539]
### Describe the feature

Pixel Fold.
It doesn't break or anything in the unfolded position, however it stretches the screens out all the way and it breaks some widgets transitioning back and forth between folded and unfolded. Most noticeable with the Google Photos widget.

Is there anyway we can have it optimized a little more for Foldable? I think if Lawnchair takes the same approach as the Pixel Launcher and makes it two screens unfolded and one screen folded it would be ready 100% for foldables.

### Why would it be useful to add?

Some widgets break or look distorted and can't adjust back to back. May be better to have it like the Pixel Launcher.

Edit: Dock search widget also breaks. Does not expand. 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

.

**Comment by jacobchins** [comment]
Seconded!

**Comment by Slion** [comment]
Would love to see this implemented too.

**Comment by Lxxrxns** [comment]
I really need this!
