### ISSUE TITLE
Weather? 

### ISSUE THREAD

**Issue by Makozor** [Deletescape-Media/Lawnchair#354]

**Comment by Makozor** [comment]
How do i set weather on? Since i used this launcher i never seen how

**Comment by LinuxLlama** [comment]
What version are you on?

**Comment by Makozor** [comment]
818

**Comment by LinuxLlama** [comment]
Then you're not on the right version. If you want to try the weather option, you have to join the beta channel.

**Comment by Makozor** [comment]
How do i join tho

**Comment by LinuxLlama** [comment]
https://t.me/lawnchairchannel

**Comment by ghost** [comment]
I joined the thing but how do I get into the beta channel

**Comment by LinuxLlama** [comment]
Do you see a group called Lawnchair CI in Telegram?

**Comment by ghost** [comment]
No. I only see "Lawnchair"

**Comment by ghost** [comment]
K I found it

**Comment by ghost** [comment]
What's the latest version? The latest version I see is #822 and that doesn't seem to have weather.

**Comment by LinuxLlama** [comment]
Scroll down to the bottom

**Comment by Makozor** [comment]
Anyone direct link to download weather option pls

**Comment by LinuxLlama** [comment]
You have to join the beta channel
