### ISSUE TITLE
is this compatible with GrapheneOS and if so or not please put that in the FAQ

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3551]
### Describe the feature

To detail if this is GrapheneOS friendly

### Why would it be useful to add?

Informative

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

.

### Additional context

GrapheneOS is an alternative harded OS

**Comment by KTibow** [comment]
pretty sure this is just another launcher app
if you don't have a grapheneos device: if android launchers tend to work on grapheneos then this should probably work
if you do have a grapheneos device: try it and see

**Comment by RustoMCSpit** [comment]
> pretty sure this is just another launcher app if you don't have a grapheneos device: if android launchers tend to work on grapheneos then this should probably work if you do have a grapheneos device: try it and see

it works

**Comment by KTibow** [comment]
in that case this issue can be closed
