### ISSUE TITLE
[FEATURE] add to f droid

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3552]
### Describe the feature

add to f droid

### Why would it be useful to add?

foss community

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

othrr apps

**Comment by KTibow** [comment]
Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah
Newer versions: this issue is a duplicate of #1473

**Comment by RustoMCSpit** [comment]
> Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah Newer versions: this issue is a duplicate of #1473

close this then

**Comment by KTibow** [comment]
lol im not a project maintainer, i can't close issues
you can close this issue yourself though, see that button right next to the comment button?

**Comment by RustoMCSpit** [comment]
not stale

**Comment by Magicrafter13** [comment]
> Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah Newer versions: this issue is a duplicate of #1473

The problem with #1473 is that it's locked, which is not conducive to discussion. There are still many out there who desire a proper F-Droid build instead of being forced to build the project themselves due to privacy/freedom concerns.
