### ISSUE TITLE
[FEATURE] icon transparency slider

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3554]
### Describe the feature

slide in settings and icons become transparebt so you can see the backgroubd

### Why would it be useful to add?

pretty

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

.

**Comment by RustoMCSpit** [comment]
should apply to qidgets too, would br cool if you coukd individually pick how transparent each one was

**Comment by RustoMCSpit** [comment]
> should apply to qidgets too, would br cool if you coukd individually pick how transparent each one was

or have a transparent wave effect where from top left to bottom right the apps become more / less transparent like mexican wave

**Comment by KTibow** [comment]
you could try icon packs with thin lines

**Comment by RustoMCSpit** [comment]
> you could try icon packs with thin lines

i could but a transparency slider should be there too
