### ISSUE TITLE
[FEATURE] cache cleaner

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3558]
### Describe the feature

https://github.com/bmx666/android-appcachecleaner

### Why would it be useful to add?

self explanatory

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

https://github.com/bmx666/android-appcachecleaner

**Comment by KTibow** [comment]
this is definitely outside the scope of a launcher app
