### ISSUE TITLE
[FEATURE] replace google discover

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3559]
### Describe the feature

https://github.com/KieronQuinn/DiscoverKiller

### Why would it be useful to add?

foss

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

https://github.com/KieronQuinn/DiscoverKiller

**Comment by KTibow** [comment]
fyi lawnchair doesn't have a feed by default
issue that may or may not solve your problem: https://github.com/LawnchairLauncher/lawnchair/issues/2477

**Comment by RustoMCSpit** [comment]
not stale
