### ISSUE TITLE
[FEATURE] control color of apps text and distance from the bottom of app

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3562]
### Describe the feature

.

### Why would it be useful to add?

.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

.

**Comment by KTibow** [comment]
please clarify, your wording is confusing

**Comment by RustoMCSpit** [comment]
> please clarify, your wording is confusing

hex color of the labels of the app should be adjustable, the labels distance from the bottom of the app top

**Comment by KTibow** [comment]
> the labels distance from the bottom of the app top

what is an "app top"?
do you just mean spacing between the icon and the label?

**Comment by RustoMCSpit** [comment]
> > the labels distance from the bottom of the app top
> 
> what is an "app top"? do you just mean spacing between the icon and the label?

*'app too'

**Comment by RustoMCSpit** [comment]
> > the labels distance from the bottom of the app top
> 
> what is an "app top"? do you just mean spacing between the icon and the label?

yeah the spacing

**Comment by RustoMCSpit** [comment]
not stale
