### ISSUE TITLE
[FEATURE] potentially feasible widget designs

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3563]
### Describe the feature

https://github.com/MrGizmo123/sxw

not sure if it's do-able but stuff like that built in

### Why would it be useful to add?

looks sick

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

https://github.com/MrGizmo123/sxw

**Comment by KTibow** [comment]
i think this is outside the scope of lawnchair - you can probably find a custom widget app that does this somewhere

**Comment by RustoMCSpit** [comment]
not stale
