### ISSUE TITLE
There is a bug on MIUI wallpaper

### ISSUE THREAD

**Issue by Arrow-C** [Deletescape-Media/Lawnchair#357]
When I use the MIUI with lawnchair, the wallpaper will only be left in the upper left corner after a while

**Comment by jacksonhvisuals** [comment]
Don't use MIUI wallpaper! (lol jk) but more seriously, what build and Android Version are you on?

**Comment by TomiOhl** [comment]
I can confirm the same on Mi5S / MIUI8 / Android 7.0 / Lawnchair build 939.

**Comment by noelaugustin** [comment]
Same on MIUI 8.5.2 Android 6.0.1 on Redmi Note 3

**Comment by nyancrimew** [comment]
We can't really affect how the Wallpaper is rendered as this is done by Android. This is a bug with MIUI and not fixable by us

**Comment by noelaugustin** [comment]
So, when I choose the option to change the wallpaper from the launcher, it says that the image can't be loaded. For wallpaper to be changed, I have to go to gallery and then change the wallpaper
