### ISSUE TITLE
[Feature] Moving Multiple App At Once

### ISSUE THREAD

**Issue by Ryu-droid283** [Deletescape-Media/Lawnchair#3577]
### Describe the feature

i would like to request a function to move multiple apps at once instead of dragging it one per one. I believe it could save more time. forgive me for my selfish request 🙇‍♂️

### Why would it be useful to add?

verily, i believe it could save more time 

### Did the feature exist in Lawnchair v2? (Play Store version)

i do not know since play store state that the app is on older version 

### Example(s)

.

### Additional context

.

**Comment by KTibow** [comment]
can you elaborate - do you mean a bulk select mode, or just the ability to go into a mode where you don't have to hold to drag one?

**Comment by Ryu-droid283** [comment]
yeah yeah, the bulk select mode😃
