### ISSUE TITLE
[FEATURE] replacement for google discover

### ISSUE THREAD

**Issue by dot166** [Deletescape-Media/Lawnchair#3578]
### Describe the feature

An option to have an RSS feed or app instead of discover feed when you swipe left on the home screen

### Why would it be useful to add?

It would let phones that are degoogled use the swipe left feature

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Discover killer (I do not have the link I have just heard of it)

**Comment by KTibow** [comment]
also see:
- #3559
- #2477
