### ISSUE TITLE
Black empty navbar shown on non-navbar device when adding widget.

### ISSUE THREAD

**Issue by moonheart** [Deletescape-Media/Lawnchair#358]
Travis-939
When adding Widget from long press menu, is shows a black empty navbar since I dont't have a navbar.
Don't know if this issue is ROM related. I have LineageOS unofficial.

![screenshot_20170730-131538](https://user-images.githubusercontent.com/15916990/28750841-a004e4da-7529-11e7-89a2-e5197b18189f.png)

**Comment by TomiOhl** [comment]
I can confirm this on Xiaomi Mi5S with MIUI8.

**Comment by fonix232** [comment]
![screenshot_20170731-172233](https://user-images.githubusercontent.com/371847/28784909-1b7b852e-7615-11e7-9c40-85a50a3c4a78.png)

Works fine on my S8.

**Comment by moonheart** [comment]
@fonix232 I think this is because you have navbar.

**Comment by wangmation** [comment]
@moonheart I've also tried on my S7 edge CHN and HTC One E8 CHN,the blank space must be NavBar itself.E8 gots NavBar on its Official Sense 7.0(Android 6.0.1).

**Comment by LinuxLlama** [comment]
On LineageOS, if I enable "Expanded Desktop" (which is immersive mode on every app) I have this same problem.

**Comment by moonheart** [comment]
@wangmation this must happens on devices without navbar.
