### ISSUE TITLE
At a glance (smartspace) add option change calendar and weather provider

### ISSUE THREAD

**Issue by dot166** [Deletescape-Media/Lawnchair#3587]
### Describe the feature

When I had the google app and google calendar the weather in my area and events on google calendar appeared under the date and time

### Why would it be useful to add?

I would be able to see weather information and calendar events on smartspace without having the google app and google calendar installed

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![signal-2023-08-15-16-16-56-144](https://github.com/LawnchairLauncher/lawnchair/assets/62702353/f5186c74-eede-4165-ac3f-183fb7b8b75e)

### Additional context

The screenshot is from when the google app was installed

**Comment by jf916** [comment]
The screenshot is from when the google app was installed

**Comment by KTibow** [comment]
i can get weather but how is lawnchair supposed to get your calendar? like you have to have some sort of calendar app installed

**Comment by dot166** [comment]
yes i do have a calendar app installed. i have the default lineageOS etar calendar app installed

**Comment by marmistrz** [comment]
Could Lawnchair possibly integrate with https://github.com/WangDaYeeeeee/GeometricWeather ?
