### ISSUE TITLE
[BUG] Glitchy ellipsis 

### ISSUE THREAD

**Issue by KTibow** [Deletescape-Media/Lawnchair#3589]
### Describe the bug

Example 1: 
![image](https://github.com/LawnchairLauncher/lawnchair/assets/10727862/45e30972-ddf7-4cc4-92da-48086884679e)
Lawnicons has enough space to write its full name, but it is truncated instead.

Example 2:
![image](https://github.com/LawnchairLauncher/lawnchair/assets/10727862/febaa2a0-9cf5-4310-ba09-1ec4e6541757)
It should display as "Compose...", but the name ("Compose Material Catalog") is misaligned, and the ellipsis itself is truncated due to that.

### Steps to reproduce

Reproducing:
1. Set your drawer's columns to 5 or so, something that truncates enough
2. Find an app with a long name
3. Find it in the drawer

### Expected behavior

[for more clarity these are described in "Describe the bug"]

### Screenshots

[for more clarity these are in "Describe the bug"]

### Device information

- Device: GM1917
- OS: OxygenOS 12
- App version: 12.1.0 Alpha 4

**Comment by KTibow** [comment]
damn time flies
/unstale

**Comment by MrSluffy** [comment]
This issue still occur in `14-dev`?

**Comment by KTibow** [comment]
Does that support older versions of Android? (My phone won't go past 12)

**Comment by MrSluffy** [comment]
> Does that support older versions of Android? (My phone won't go past 12)

Yes support A9-A14, for QuickSwitch A14

**Comment by KTibow** [comment]
Should I get it from the latest Actions build?

**Comment by KTibow** [comment]
I can reproduce this issue on Lawnchair 14.

**Comment by MrSluffy** [comment]
Can you try latest nightly if still persists reopen this issue
