### ISSUE TITLE
Twice Sound Played When Press Google Assitant Button

### ISSUE THREAD

**Issue by moonheart** [Deletescape-Media/Lawnchair#360]
When press the Google Assistant button, the sound effect played for twice.

**Comment by jacksonhvisuals** [comment]
What build are you on?

**Comment by moonheart** [comment]
@jacksonhvisuals on Travis-931, and I downloaded Travis-939 got the same problem.

**Comment by jacksonhvisuals** [comment]
@deletescape I can confirm as well. A7.1.1
