### ISSUE TITLE
[FEATURE] android 13 quickstep

### ISSUE THREAD

**Issue by dot166** [Deletescape-Media/Lawnchair#3601]
### Describe the feature

lawnchair would have support for android 13 quickstep api

### Why would it be useful to add?

trebuchet is rubbish so i would like lawnchair to be able to support android 13 quickstep

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

recents menu but lawnchair providing it

**Comment by osm0sis** [comment]
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/3249
