### ISSUE TITLE
[FEATURE] Transient Taskbar

### ISSUE THREAD

**Issue by monefiera** [Deletescape-Media/Lawnchair#3603]
### Describe the feature

This is the new taskbar added in A13 QPR2. It is similar to the iPad on any tablets.

### Why would it be useful to add?

I and many others use Lawnchair on our tablets. This taskbar helps us a lot in using A13 Tablet comfortably.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![android-13-qpr2-taskbar-a](https://github.com/LawnchairLauncher/lawnchair/assets/83483662/7637dcee-994c-4a6a-bd45-14e4a6a96832)
![android-13-qpr2-transient-taskbar-2](https://github.com/LawnchairLauncher/lawnchair/assets/83483662/9415b421-9a54-4d36-add1-28ceab9b62c6)
the images from (https://9to5google.com/2023/01/10/android-13-qpr2-taskbar/) & (https://crast.net/227133/enabled-android-13-qpr2-ready-for-desktop-mode-new-back-gesture-separate-ringtone-volume-and-more/)

**Comment by osm0sis** [comment]
Already works on my tablet with Lawnchair on 13.

**Comment by monefiera** [comment]
If you don't mind, please let me know what version it is available.
Is [the latest Debug #2088](https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-12-1-0-dev-2088-release/lawnchair-debug-12-1-0-dev-2088-android-apk-download/) ok?

**Comment by osm0sis** [comment]
I noted it with these hacked versions which allow it to be Quickstep/Recents with the Magisk Quickswitch module. It also "works" (i.e. shows the Dock contents) with the CI builds when not the Recents provider, with a compatible one like Lineage's Trebuchet.

https://github.com/saitamasahil/Lawnchair_Magisk/tree/main/system/priv-app/Lawnchair

**Comment by monefiera** [comment]
Thanks. I'll try it.
