### ISSUE TITLE
[FEATURE] Add support for 'Pixel Search'

### ISSUE THREAD

**Issue by kymerea** [Deletescape-Media/Lawnchair#3606]
### Describe the feature

Add support for [pixel search](https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch&hl=en&gl=US), an app which replicates the search found in google phones

### Why would it be useful to add?

This would be the perfect search widget for google as it is almost identical to the real pixel version. It should also be a relatively easy implementation aswell.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Screenshots of how the app look can be found [here](https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch&hl=en&gl=US)

**Comment by validcube** [comment]
Already added in #3442

**Comment by rodrigoswz** [comment]
It's not working

![Screenshot_20231025-121951_Lawnchair.png](https://github.com/LawnchairLauncher/lawnchair/assets/14058427/28fc9079-98a2-4fa0-b0a3-95a6bc010065)

When I tap the search bar it forwards me to Play Store to download Pixel Search (but it's already installed)

**Comment by alabotski** [comment]
@ItxWeird 
I have the same problem
It forward me to Play Store
