### ISSUE TITLE
Weather doesn't update.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#361]
The weather doesn't update. It is stuck on the same temperature for a few hours now.

**Comment by ellenswamy** [comment]
Mine has been updating without issues...

**Comment by ghost** [comment]
That doesn't mean it works for everybody. Why was this issue closed?
You can see it the picture I attached that Lawnchair says it's sunny outside but it's the middle of the night. Also the temperature, indicated by google, is 24 degrees. The weather can be fixed only by restarting Lawnchair (it will show a moon after restarting and the correct temperature).
![screenshot_2017-07-31-00-35-28](https://user-images.githubusercontent.com/29509650/28757313-8b653836-7588-11e7-9cd1-ea282b7a2fa4.png)
