### ISSUE TITLE
[BUG] Themed Icons Stuck in Light/Dark Mode

### ISSUE THREAD

**Issue by TechD123** [Deletescape-Media/Lawnchair#3612]
### Describe the bug

I use the official Lawnchair themed icons. As is often the case, some apps don't have themed icons, so I long pressed on these and selected some that fit visually from the Lawnchair icon pack. 

I did this in light mode. However, when my phone switched to dark mode, the icons I manually selected stayed light. If I select the appropriate icons _again_ while in dark mode, it turns them dark, but as soon as dark mode is deactivated, these apps again stay the way they are and look out of place.

Thank you for working on Lawnchair!

### Steps to reproduce

1. Select an app without themed icons and long press
2. Tap on Customize
3. Select an icon from the Lawnchair themed icons pack
4. Wait until the device switches dark mode on/off
5. Notice that icon is out of place, as it hasn't switched to light/dark mode

### Expected behavior

All icons should respect the current dark mode setting (i.e. on/off) and change their color accordingly.

### Device information

- OS: Latest CalyxOS based on AOSP/Android 13
- App version: 12.1.0 Alpha 4

**Comment by q234rty** [comment]
Seems to be already fixed in recent CI builds on the 12.1-dev branch.

**Comment by ThatOneCalculator** [comment]
Fixed, this should be closed
