### ISSUE TITLE
[FEATURE] At a glance widget on lock screen

### ISSUE THREAD

**Issue by laespada249** [Deletescape-Media/Lawnchair#3618]
### Describe the feature

Add at a glance widget on lock screen

### Why would it be useful to add?

Because it's going to be as usefull as on home screen

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![image](https://github.com/LawnchairLauncher/lawnchair/assets/115735431/8afd9768-3413-4747-9fc7-98b91cc68972)

### Additional context

Home screen going to be customizable separately from lock screen

**Comment by KTibow** [comment]
> Home screen going to be customizable separately from lock screen

That's not possible. Launchers can't control your lock screen without doing some hacky workarounds that totally replace it.
