### ISSUE TITLE
[FEATURE] support installing on Android 13

### ISSUE THREAD

**Issue by akostadinov** [Deletescape-Media/Lawnchair#3625]
### Describe the feature

Hello, when I try to install to Pixel 7 with latest Android 13 updates I can't. I mean in google play the phone appears grayed out so install can't start.

### Why would it be useful to add?

It is not usable at all without this support.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![image](https://github.com/LawnchairLauncher/lawnchair/assets/1408661/5e3dc05b-ae63-4e18-a73a-d72bd5e805c4)

**Comment by KTibow** [comment]
You missed the part about Lawnchair 2 being the older, deprecated version
Download the APK from https://lawnchair.app/downloads/

**Comment by sam2002jain** [comment]
Hey!! Can I try to solve this issue if you let me get into this..??

**Comment by Goooler** [comment]
Tracked by #3739.
