### ISSUE TITLE
[BUG] Can't Customize Icons for Google Home Automations on Home Screen

### ISSUE THREAD

**Issue by shipon88** [Deletescape-Media/Lawnchair#3631]
### Describe the bug

So with Google seeming to slowly kill off their Action Blocks app (or something, it's been completely broken for about a week now.) I've tried to use the built in shortcut in the Google Home App to have Automation shortcuts instead.

Adding the Automation Shortcut to the homepage works, but the icon is ugly. I tried to customize the icon by holding down the icon and customizing it like I would any other, but doing so results in the launcher crashing, restarting and the icon removing from my home screen all together.

Not sure if it's a "bug" or just a missing functionality, but I'd love to be able to customize these.

### Steps to reproduce

1. Go to 'Google Home App'
2. Open an Automation
3. Add Automation to Home Screen (Phone with Arrow button)
4. Click and hold on the new icon to open the settings
5. Click the image of the icon to select a new icon from installed packs
6. Select a new icon

### Expected behavior

I expect to be able to change the icon to any icon from my installed icon packs. 

### Screenshots

![GJy9t0A](https://github.com/LawnchairLauncher/lawnchair/assets/80291321/2dd1efd5-22d9-4f1c-9c46-dddddbd9b118)
![CHytfMc](https://github.com/LawnchairLauncher/lawnchair/assets/80291321/1bf58ab8-88f3-4c01-afb9-4ad9b4efa30e)

### Device information

- Device: Google Pixel 5A
- OS: Android 13
- App version: 2.0-2589

**Comment by KTibow** [comment]
Send crash report
(Also is customizing shortcut icons even a thing?)

**Comment by shipon88** [comment]
No crash report is produced. The launcher just simply restarts itself (and launcher default settings are reset, pressing the home button prompts me to choose a launcher.) 

Idk if customizing shortcut icons are supposed to be a thing, but the functionality to customize it is there as if it were any other icon

**Comment by KTibow** [comment]
I tried adding a shortcut just now (Lawnchair itself said "1 shortcut"), it behaves as any other widget

**Comment by shipon88** [comment]
If it's behaving as a widget, how come it can't be resized or modified like a widget, and is instead treated by the launcher like an app icon?

**Comment by KTibow** [comment]
> how come it can't be resized or modified like a widget

Because it has a fixed size and no edit button

> and is instead treated by the launcher like an app icon

You can't edit the icon or the name in my testing, so I wouldn't say that

**Comment by shipon88** [comment]
trying to rename it also crashes the launcher for me.

![Screenshot_20230923-132938](https://github.com/LawnchairLauncher/lawnchair/assets/80291321/91a237cb-3389-4dd8-b6d6-3352a78a5428)
![Screenshot_20230923-133038](https://github.com/LawnchairLauncher/lawnchair/assets/80291321/cb522bf1-0b88-4ced-b1a6-17d490f1aae4)

**Comment by KTibow** [comment]
wait, you're on lawnchair 2? i don't think that version is still being developed

**Comment by shipon88** [comment]
it appears that i am. oops
