### ISSUE TITLE
Inconsistent notification dots

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#364]
In this screen recording you can see that the chrome app has no notifications, the icon on the dock is fine but the one in the app drawer has a dot that shows nothing

https://photos.app.goo.gl/pLAFKX18y7p1wfVj2

v931

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jacksonhvisuals** [comment]
What build are you on?

**Comment by Younes-L** [comment]
@jacksonhvisuals build 931

It also happens with telegram but differently, the dot is cleared but the system notification is not !

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
it seems like this issue got fixed some time ago, haven't encountered it for a while.

**Comment by Younes-L** [comment]
and it happened again. it fixed itself as I pulled the notification shade to start screen recording 🤔

**Comment by Younes-L** [comment]
@deletescape I finally got the little sneaker on record !
[Here it is](https://photos.app.goo.gl/TXYLijyl3UvEewYe2)
