### ISSUE TITLE
[BUG] Searching for icons does not work

### ISSUE THREAD

**Issue by q234rty** [Deletescape-Media/Lawnchair#3655]
### Describe the bug

Searching for icons does not work when trying to override app icons.

### Steps to reproduce

1. Install lawnchair and lawnicons
2. Try to customize an app's icon
3. Select lawnicons as icon source
4. Input something into the search bar
5. Observe that the icons don't seem to be filtered at all.

### Expected behavior

The icons are filtered according to the search input.

### Device information

- Device: Motorola X40
- OS: LineageOS 20
- App version: 12.1.0 Dev from https://github.com/LawnchairLauncher/lawnchair/actions/runs/6431134375

### Additional context

It was working on 12.1.0 Alpha 4.

**Comment by MrSluffy** [comment]
fixed [here](https://github.com/LawnchairLauncher/lawnchair/commit/bfc1cd7cf45933fa4a58aa4894625729b769b29e)

**Comment by MrSluffy** [comment]
Fixed bfc1cd7cf45933fa4a58aa4894625729b769b29e
