### ISSUE TITLE
[BUG] Icon Pack Studio (IPS) not using theme

### ISSUE THREAD

**Issue by jo-chemla** [Deletescape-Media/Lawnchair#3656]
### Describe the bug

Tried both on latest release from github releases, as well as latest artifact from build-debug-apk github action. 
If Icon Pack Studio is installed, then it appears in Lawnchair `Settings - General - Icon Style`. However, selecting IPS as Icon Pack does not apply the Icon Pack currently selected in Icon Pack Studio. Is this how the IPS feature is supposed to work? Thanks for the feedback!

### Steps to reproduce

1. Install Icon Pack Studio, download a few themes, install as apk
1. Go to Lawnchair `Settings - General - Icon Style`
1. Select `Icon Pack Studio`
1. Pack is not applied

### Expected behavior

Pack selected in Icon Pack Studio should be applied - or at least a modal which would let the user select the desired icon pack from IPS could appear.

### Device information

- Device: Google Pixel 7 Pro
- OS: Stock Android 14
- App version: 12.1.0 Dev `#2186`

### Additional context

When exporting an Icon Pack from Icon Pack Studio, then an apk can be installed which installs the pack as an app. The bad behavior from IPS is that when exporting another Icon Pack, then the second Icon Pack overrides (updates) the first one. So cannot easily switch between multiple icon packs to choose the right one.

**Comment by MrSluffy** [comment]
I'm not sure if this is a bug, I tried in other third party launcher and it's the same (Not applying) unless it's manually change one by one you can check more [https://docs.smartlauncher.net/other-products/iconpackstudiofaq](https://docs.smartlauncher.net/other-products/iconpackstudiofaq)

**Comment by jo-chemla** [comment]
Thanks for trying with other launchers. I would have thought that if lawnchair offers that feature, that would have been to use icons from the currently selected IPS pack, or at least have an option to update the icons from the pack when they are newer. Any feedback from the team would be appreciated.
