### ISSUE TITLE
Shortcut "Remove" behaves different than drag-n-drop "Remove"

### ISSUE THREAD

**Issue by Chaphasilor** [Deletescape-Media/Lawnchair#366]
I noticed that when there's only one app left on a page, the pages gets automatically removed when you  drag the app onto the "Remove" option. This is the expected behavior. If you long-press the app though, the same options as the drag-n-drop one pop up as nougat shortcuts. if you choose the "Remove" option here, the app itself gets removed, but the page does not. You can't remove the page from the overview now, the only way to remove it is to place another app onto the page and remove it again via drag-n-drop.

**Comment by suphon-t** [comment]
The remove shortcut is now removed.
