### ISSUE TITLE
[BUG] icon display for Android tablet 

### ISSUE THREAD

**Issue by kil011** [Deletescape-Media/Lawnchair#3663]
### Describe the bug

Once I set home screen icon size to 150, those in dock will not display property 

### Expected behavior

Hope on high ppi devices, it could perform like Google tablet, which means the search bar at the left side and so on

### Screenshots

![Screenshot_20231013-010759](https://github.com/LawnchairLauncher/lawnchair/assets/67146465/a94c65d8-1203-461b-ab06-3073de70a6bc)

### Device information

- Device: Lenovo tab p12 pro
- OS: stock ROM Android version 13.0
- App version:  12.1.0 Alpha 4

**Comment by alabotski** [comment]
@KIL011 
Hi I have the same bug with my Xiaomi MiPad 4 and ArrowOS
Settings - Display - Display size and text

When I use minimal display size
I have such problem

[Screenshot_20240117_213236](https://github.com/LawnchairLauncher/lawnchair/assets/439337/9ca296f7-f7ff-4f31-ad65-9084999ba8c3)
[Screenshot_20240117_213246](https://github.com/LawnchairLauncher/lawnchair/assets/439337/a6bccee7-0cc4-4abb-a2f9-0d7891fbfafe)

But when I increase it. All become good.

[Screenshot_20240117_213350](https://github.com/LawnchairLauncher/lawnchair/assets/439337/59400550-e369-4b1e-92bf-e6862561ceb7)
