### ISSUE TITLE
 [BUG] New Apps Don't Show on Home Screen

### ISSUE THREAD

**Issue by TechD123** [Deletescape-Media/Lawnchair#3664]
### Describe the bug

APKs installed from the browser (Fennec) or Obtainium show up on the home screen when the appropriate setting is toggled in Lawnchair settings, while APKs installed via Droid-ify do not.

### Steps to reproduce

1. Enable appropriate setting in Lawnchair under home screen settings
2. Download any app via Droid-ify
3. Notice that the new app is visible in the app drawer, but not the home screen

### Expected behavior

App should show up on the home screen

### Device information

- OS: Latest CalyxOS based on Android 13
- App version: 12.1.0 Alpha 4

**Comment by TechD123** [comment]
The issue is still present.

**Comment by MrSluffy** [comment]
Use latest lawnchair
