### ISSUE TITLE
[BUG] no more weather on at a glance after new Google app update

### ISSUE THREAD

**Issue by rikudo830** [Deletescape-Media/Lawnchair#3666]
### Describe the bug

With new update from Google app the weather is not showed any more

### Steps to reproduce

1. Go to 'home settings'
2. Click on 'at a glance'
3. Scroll down to 'at a glance provider select lawchair and select show weather'

### Expected behavior

Weather must be showed at a glance 

### Screenshots

/
![Screenshot_20231014-063138](https://github.com/LawnchairLauncher/lawnchair/assets/65352884/9d5ae19d-efe1-404c-9aeb-4195cc063ef4)

### Device information

- Device: [Sony Xperia 1 mark 4]
- OS: [stock ROM Android version 13.0]
- App version: [12.1.0 Alpha 4]

**Comment by KannaHayabusa** [comment]
Same.

**Comment by Cornfedsonic92** [comment]
Having the same issue here, galaxy s23 ultra

**Comment by Everythintechyt** [comment]
Same issue with s8+

**Comment by AndersonARS** [comment]
Same problem on Motorola moto g 5G plus Android 11. It started after updating the Google app. Try using the beta version of it without success.

**Comment by winnipeg21** [comment]
Getting the same issue on my Pixel 7 Pro. Thought it was a location permission issue but everything seems ok. Using android 14 preview (build # U1B2.230922.010)

**Comment by thoweeth** [comment]
The same problem, both on the latest Alpha version from a year ago and the latest Dev

**Comment by ldugaduga** [comment]
I found a solution. Uninstall google updates and then re install it again. It works in my redmi note 12

**Comment by winnipeg21** [comment]
> I found a solution. Uninstall google updates and then re install it again. It works in my redmi note 12

This is most likely a temp solution. Looking at my pixel 7 I see no app by that name. As well most google apps you can not uninstall.

**Comment by ldugaduga** [comment]
> > I found a solution. Uninstall google updates and then re install it again. It works in my redmi note 12
> 
> This is most likely a temp solution. Looking at my pixel 7 I see no app by that name. As well most google apps you can not uninstall.

this app is what i mean
![Screenshot by Dropbox Capture](https://github.com/LawnchairLauncher/lawnchair/assets/1259202/2ed9d999-a10f-4da6-ad0c-6dfc3c4c6216)

**Comment by rikudo830** [comment]
> > > I found a solution. Uninstall google updates and then re install it again. It works in my redmi note 12
> > 
> > 
> > This is most likely a temp solution. Looking at my pixel 7 I see no app by that name. As well most google apps you can not uninstall.
> 
> this app is what i mean ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1259202/279220111-2ed9d999-a10f-4da6-ad0c-6dfc3c4c6216.png)

Thanks a lot it works

**Comment by theLee3** [comment]
This works for a while, but inevitably disappears again on my Pixel 7 Pro. I think it disappears once something else is shown by the At a Glance widget (i.e. Now Playing, Upcoming Schedule, etc.), but I'm not positive that's the trigger.

**Comment by ldugaduga** [comment]
It works in mine just disable auto update and patch the google up to
version 14.32.17.28. and dont update it to latest version.

**Comment by theLee3** [comment]
Thanks @ldugaduga , I understand that workaround, but we shouldn't have to avoid updates for it to work. I am trying to provide some insight into where the issue may be located so that it can be addressed.

Could this feature have worked due to [stolen code](https://www.androidcentral.com%2Fapps-software%2Fdeveloper-claims-lawnchair-took-pixel-launcher-code&usg=AOvVaw3Cc8hvfWZHnEYYg1emwPzb&opi=89978449) from Google's Pixel launcher... and is that why it is now broken? If so, it may not be easily fixed.

**Comment by winnipeg21** [comment]
I doubt this would help, just loaded up my phone with Lawnchair at a glance disabled and got this error (attached as image). 

The proposed workaround can possibility lead to further issues down the road imo. Even if at a glance it's self can be solved maybe add a widget instead?
![Screenshot_20231121-134659](https://github.com/LawnchairLauncher/lawnchair/assets/9980707/0a8350ab-5135-43a7-a1b3-bf246663d48f)
