### ISSUE TITLE
[FEATURE]  QuickSwitch support on Android 14

### ISSUE THREAD

**Issue by FordCorn** [Deletescape-Media/Lawnchair#3673]
### Describe the feature

QuickSwitch to be compatible on Android 14.

### Why would it be useful to add?

Lawnchair had this feature in previous versions of Android but lacks support on Android 14.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20231017-161737~2](https://github.com/LawnchairLauncher/lawnchair/assets/63467807/ed70cb13-abb1-42b8-9fac-7c04bfe5f13e)

### Additional context

I am using a Pixel 7 with GrapheneOS.

**Comment by rainyskye** [comment]
(unrelated to lawnchair specifically)

@FordCorn Are you running QuickSwitch somehow rootless? Or are you rooted on GrapheneOS? 

Thanks :)

**Comment by FordCorn** [comment]
Yes I am rooted, I use GrapheneOS with Magisk Delta. GrapheneOS has no issue being rooted at all, exactly the same like I was using the stock Pixel rom, just without Google deeply embeded into the device.

(I did not mean to close and reopen the issue, mistapped on my phone)

**Comment by move-some** [comment]
+1

**Comment by MrSluffy** [comment]
Support now in `14-dev` branch
