### ISSUE TITLE
App Shortcuts Backport?

### ISSUE THREAD

**Issue by wangmation** [Deletescape-Media/Lawnchair#368]
It seems like there's a switch in Lawnchair's Debug menu option,that could enable the App Shortcut function on the Android version lower than 7.1? I couldn't find this so maybe I should ask this question for confirmation.

Thanks.

I use Samsung Galaxy S7 edge(hero2ltechn) in Official Android 7.0 OS(Samsung Experience 8.1)

**Comment by moonheart** [comment]
Long press "Debug menu", it will show the App Shortcuts Backport switch.

**Comment by gena01** [comment]
Looks like this is no longer available? Am i missing something? I'd love to have an app shortcut on desktop/dock

**Comment by amirzaidi** [comment]
As far as I know, Lawnchair V2 includes the backported app shortcuts by default.

**Comment by bohrabhijeet** [comment]
@amirzaidi , Yes it does.

**Comment by gena01** [comment]
I am on 1.2 release (from the play store). Should i wait for v2 beta?

**Comment by bohrabhijeet** [comment]
@gena01 You can install the alpha version of v2 from t.me/lccommunity.

**Comment by gena01** [comment]
@abhijeetbohra installed v2-328 beta. I am on Android 8.0 and i don't see that option

**Comment by bohrabhijeet** [comment]
@gena01 v2 alreaady has the app shortcuts. There's no toggle for it. You just have to make it the default launcher for app shortcuts to work.
