### ISSUE TITLE
[FEATURE] Search bar coloring issue

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#3680]
### Describe the feature

Lawnchair search bar don't match the colors

### Why would it be useful to add?

Looks better

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20231021_005003_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/e777071c-098f-4454-b705-0962e25f0cf5)
![Screenshot_20231021_004926_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/55a344a2-8d3d-4992-94c5-eedba7a3e9c8)

### Additional context

Also it would be great if we get the app drawer search bar look like this
![Screenshot_20231016_204324_Discord](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/88ecfbad-bde7-4a80-b8d9-23bc8e2c5040)
Thanks...

**Comment by SuperDragonXD** [comment]
Fixed on https://github.com/LawnchairLauncher/lawnchair/commit/28412aa2ec72b18d88c6680b2c76251c49396ca2. The latter should be in a new issue.
