### ISSUE TITLE
Recents Tab 

### ISSUE THREAD

**Issue by redcatxus** [Deletescape-Media/Lawnchair#3686]
### Describe the bug

When you open recent apps tab from a landscape oriented app, the tab will show nothing, and you can't tap on anything to check, since there's nothing there. whilst opening the tab from portrait orientation, everything seems to work fine.

### Steps to reproduce

1. Go to an app that's landscape oriented, a game for example.
2. simply click on the recents button at the bottom of your phone
3. you'll notice that there's no recently opened app there, when you have some patiently waiting for you.
4. you can either tap on the button again to open your most recently opened app, or just dismiss everything.

### Expected behavior

you should see recently opened apps

### Screenshots

![Screenshot_20231025-143746](https://github.com/LawnchairLauncher/lawnchair/assets/137791992/a947e3a9-92f3-4965-bc0e-e6f894e25e0c)
when opened with portrait screen
![Screenshot_20231025-143758](https://github.com/LawnchairLauncher/lawnchair/assets/137791992/4790d51d-c215-4060-abe4-eef2620ea5c7)
when opened with landscape screen 

### Device information

- Device: Infinix HOT 10 Play
- OS: XOS v7.6.0, Android 11
- App version: Lawnchair 12.1.0 Alpha 4

**Comment by FordCorn** [comment]
@redcatxus QuickSwitch would most likely fix this, since you are on Android 11 it should work.
https://github.com/skittles9823/QuickSwitch
They don't have QuickSwitch support on Android 14 (what I am using) so I have a similar issue.

**Comment by FordCorn** [comment]
You must be rooted however, forgot to mention that.
