### ISSUE TITLE
[FEATURE] App drawer search bar.

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#3687]
### Describe the feature

New app bar search bar.

### Why would it be useful to add?

Because it looks outdated newer one looks cool.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20231025_211409_Discord](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/f395a45a-7065-4317-9d7d-a659907ef08d)

### Additional context

✌🏻

**Comment by Secret-chest** [comment]
Also the current one doesn't respect font.
