### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by lovelysurel** [Deletescape-Media/Lawnchair#3691]
### Describe the feature

Stack widget

### Why would it be useful to add?

To access different widget at the same time and save the space on homescreen. Neat.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20231027-152059_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/129295306/95141b4c-efae-4056-a25d-5d474b476902)

**Comment by MrSluffy** [comment]
Close this duplicate #3956 and have better description 
- #3956
