### ISSUE TITLE
[BUG] Space below app drawer not reclaimed if search bar is disabled

### ISSUE THREAD

**Issue by clustor** [Deletescape-Media/Lawnchair#3692]
### Describe the bug

With search bar enabled
![Screenshot_20231027-165626_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/15720802/d75cfb08-c8a7-4455-828a-9cca8b54e790)

After disabling search bar, you can see that space below app drawer is not utilized. I would have expected the app drawer to go to the bottom row of the screen. 
![Screenshot_20231027-165419_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/15720802/f515a924-e321-477e-9320-03bb6115f679)

### Steps to reproduce

1. Disable "Show Search Bar" under Settings/Dock
2. Observe that search bar is not shown but app drawer remains at the same space. 

### Expected behavior

I would have expected the app drawer to move down at the bottom of the screen. 

### Device information

- Device: Samsung Galaxy Note 8
- OS: Stock Android 9
- App version: 12.1.0 Alpha 4

**Comment by fredgolightly** [comment]
Same, came here to post

**Comment by MrSluffy** [comment]
Fixes e28d20dde3c887cb793729841016970cf7d74dcc
