### ISSUE TITLE
[Request] Translate the app to Dutch (NL)

### ISSUE THREAD

**Issue by RoySchutte** [Deletescape-Media/Lawnchair#37]
I would love to contribute in the translation of your app. However, I cannot find a translatable strings file. It seems that the strings are in "Lawnchair/res/xml/launcher_preferences.xml" instead of "/values/strings.xml" am I right?

**Comment by deletescape** [comment]
A lot of the strings from the custom settings are not yet extracted to string resources as a lot of them change every release, translating them already would just create additional work in the future, but thanks for the interest in helping
