### ISSUE TITLE
[BUG] At a glance is not showing weather info on Android 14, Pixel 7

### ISSUE THREAD

**Issue by bappa555** [Deletescape-Media/Lawnchair#3701]
### Describe the bug

The at a glance widget is not showing weather information on Android 14

### Steps to reproduce

1. Go to home screen of Pixel 7 running on Android 14 
2. See at a glance widget, it only shows date, weather details not showing 

### Expected behavior

At a glance widget should show weather details

### Device information

- Device:  Google Pixel 7
- OS: stock ROM Android version 14
- App version: 12.1.0 Alpha 4

**Comment by theLee3** [comment]
This is not due to Android 14, but rather the Google app. Try the solution provided [here](https://github.com/LawnchairLauncher/lawnchair/issues/3666#issuecomment-1786206280).

**Comment by bappa555** [comment]
Thank you, this works.

**Comment by Ravi-Kishor** [comment]
Google app upto version 14.33.12.28 its fine...just uninstall all updates and install this specfic version from apkmirror and don't upadte from PS.

**Comment by st0neh** [comment]
> This is not due to Android 14, but rather the Google app. Try the solution provided [here](https://github.com/LawnchairLauncher/lawnchair/issues/3666#issuecomment-1786206280).

That "solution" only works until you get the new weather page pushed to your device then it breaks again.

And using an old out of date version of the Google app is not a "solution" either.
