### ISSUE TITLE
[BUG] 12.1.0 Alpha 4 (12010005) is sometimes not responsive after device has been in idle, Android 14

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#3704]
### Describe the bug

12.1.0 Alpha 4 (12010005) is sometimes not responsive after device has been in idle, Android 14.

App drawer cannot be accessed by swiping up, nothing happens.
Pressing on folders on home screen open one of the apps inside the folder, as if the folder did not exist, and the event went on to the app shortcut one level down.

### Steps to reproduce

No clear pattern to when this happens, but usually happens after some time in idle or after using messaging apps and then reopening the screen.

### Expected behavior

No freezing / unresponsiveness

### Device information

version: 12.1.0 Alpha 4 (12010005)
commit: https://github.com/LawnchairLauncher/lawnchair/commit/b7ad08c775ceee31c9f0715a9f71acb661b4380f
build.brand: samsung
build.device: o1s
build.display: UP1A.231005.007.G991B
build.fingerprint: samsung/o1sxeea/o1s:14/UP1A.231005.007/G991B:user/release-keys
build.hardware: exynos2100
build.id: UP1A.231005.007
build.manufacturer: samsung
build.model: SM-G991B
build.product: o1sxeea
build.type: user
version.codename: REL
version.incremental: G991B
version.release: 14
version.sdk_int: 34
display.density_dpi: 480
isRecentsEnabled: false

**Comment by FordCorn** [comment]
+1 Happening on my Pixel 7 aswell with the same symptoms.

**Comment by yobert** [comment]
For me, this bug is more likely to trigger the longer my phone sits idle. I can always work around it by re-locking and unlocking the screen with my fingerprint, but it's pretty annoying. (Lawnchair 2.0-2589, Android 14)

**Comment by eggsgent** [comment]
Issue still present in Lawnchair 14 beta 2, please reopen if possible.

**Comment by FordCorn** [comment]
This is still a major issue

**Comment by dannygwardle** [comment]
Still an issue for me too.
