### ISSUE TITLE
[BUG] [13-dev] Restoring a backup will not restore widgets

### ISSUE THREAD

**Issue by thatAkiraFox** [Deletescape-Media/Lawnchair#3729]
### Describe the bug

Restoring a previously-created backup will fail to restore widgets, leaving blank space instead.

### Steps to reproduce

1. Create a backup with any widget on the home screen
2. Restore the backup that has just been created
3. Lawnchair will correctly restore the home screen layout but will fail to restore widgets

### Expected behavior

Lawnchair should be able to restore widgets alongside all the icons.

Also, in case a widget is no longer available, Lawnchair should show some sort of message to the user with this information.

### Device information

- Device: OnePlus 6 (any device really)
- OS: LineageOS 20, Android 13
- App version: `13-dev #2296`

**Comment by MrSluffy** [comment]
Error log : 

```
E  Removing invalid widget: id=465
2023-11-18 18:17:50.091 28854-28854 ModelWriter             app.lawnchair.debug                  D  removing items from db com.google.android.calendar. Reason: [AppWidgetManager cannot find provider for that widget id. It could be because AppWidgetService is not available, or the appWidgetId has not been bound to a the provider yet, or you don't have access to that appWidgetId.]
```

**Comment by znbaboy** [comment]
also happens with shortcuts

**Comment by znbaboy** [comment]
Widgets restore now! But shortcuts still disappear

**Comment by ghost** [comment]
Please re open. The bug is not fixed.

**Comment by MrSluffy** [comment]
what version you using?

**Comment by ghost** [comment]
Version 15.0.0 3369d0a

**Comment by MrSluffy** [comment]
That's not official, use latest nightly!
