### ISSUE TITLE
Google Now tab not working

### ISSUE THREAD

**Issue by panagiac** [Deletescape-Media/Lawnchair#373]
Hi,

I'm using Lawnchair on a Meizu M3 Note with Flyme 6.1.0.0 (based on 5.1 Lollipop).
Launcher is working perfectly, but if I swipe to right, the Google Now tab doesn't appear.

Any ideas?
Thanks!

**Comment by LinuxLlama** [comment]
I've heard that Flyme doesn't come with Google Services. Do you have the Google Services installed? If you don't, that's why Google Now isn't there. If you do have Google Services, this is a bug.

**Comment by panagiac** [comment]
Hi! Thanks for the reply. I actually have Google Services Framework
installed via "Google Installer".

Il 31/lug/2017 23:32, "reCoded" <notifications@github.com> ha scritto:

**Comment by nyancrimew** [comment]
You need Google Services + the google app installed, the google app needs to be up to date for this to work

**Comment by mjeshurun** [comment]
Google now feed is not showing even when the latest Google Search app is installed on Meizu Pro 6, flyme 6.1.0.0G
