### ISSUE TITLE
[BUG] Dock Icons is being removed

### ISSUE THREAD

**Issue by amanrajOO7** [Deletescape-Media/Lawnchair#3732]
### Describe the bug

I've step dock icons count to 7 & have placed 7 icons but after systemui restarts or I restart lawnchair 2 icons gets removed from the dock automatically.

### Steps to reproduce

1. Go to dock settings & set dock icons count to 7.
2. Place 7 icon at dock
3. Restart the lawnchair 
4. 2 dock icon will be removed from the dock

### Expected behavior

Dock Icons should be same as before.

### Screenshots

![Screenshot_20231116-121042_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/46120388/673eb9e1-5ff3-484c-8247-b4494c7f127c)
![Screenshot_20231116-121034_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/46120388/a856575c-6838-4197-8ed7-fa55d25cd643)

### Device information

- Device: POCO F1
- OS: DerpFest 14
- App version: 13-dev

**Comment by wrongway213** [comment]
I'm experiencing precisely the same behavior on all 13-dev builds as well.

OS: RisingOS A13, August SPL
Device: Pixel 7
App version: 13-dev branch, all versions

As OP stated, anything that restarts either SystemUI or LawnChair results in losing the two furthest right icons in your dock. I normally don't like to +1 bug reports, but as OP is on A14 and I'm on A13 I was hoping to eliminate A14 as a variable.
