### ISSUE TITLE
[BUG] App search is broken on 13-dev

### ISSUE THREAD

**Issue by q234rty** [Deletescape-Media/Lawnchair#3740]
### Describe the bug

With 13-dev it seems that when searching for apps and there's only one result, one can only open the app by clicking the icon, and clicking the area with the app name opens an app store to search for apps instead.

### Steps to reproduce

1. Use app search to search for an app
2. Make it so that there's only one result
3. Click on the app name in the result.
4. Observe that an app store is opened to search for an app.

### Expected behavior

The app in the result is opened instead of an app store.

### Device information

- Device: Motorola X40
- OS: LineageOS 20 Unofficial
- App version: 13 Dev (https://github.com/LawnchairLauncher/lawnchair/actions/runs/6905222079)

**Comment by pacjo** [comment]
Clicking enter will also open the app. Video below.

https://github.com/LawnchairLauncher/lawnchair/assets/56438628/129eb185-aa79-4944-adf2-fd9bb90372a1
