### ISSUE TITLE
[BUG] Crash when interacting with widget

### ISSUE THREAD

**Issue by uurcan7** [Deletescape-Media/Lawnchair#3746]
### Describe the bug

lawnchair crashes when I click on any widget

### Steps to reproduce

1. add widget
2. click on it
3. see the crash

### Expected behavior

Not crash

### Device information

- Device: RedMi Note 8
- OS: Evolution X 8.0.2 18.11.2023
- App version: 13 Dev 

### Additional context

[Lawnchair (Debug) bug report 19 Kas 2023 ÖÖ 44807.txt](https://github.com/LawnchairLauncher/lawnchair/files/13401895/Lawnchair.Debug.bug.report.19.Kas.2023.OO.44807.txt)

**Comment by MrSluffy** [comment]
This bug should fix by this e994660cb053ecf5eeecd4d117a6f5827ec25bfe

**Comment by MrSluffy** [comment]
Fixed e994660cb053ecf5eeecd4d117a6f5827ec25bfe
