### ISSUE TITLE
[BUG] Searching Hidden Apps Doesn't Work

### ISSUE THREAD

**Issue by Alpointernet** [Deletescape-Media/Lawnchair#3754]
### Describe the bug

When you try to search hidden apps -hide in search results is NOT selected- it doesnt show the hidden app in search.

### Steps to reproduce

1. Go to 'App Drawer'
2. Click on 'Search'
3. Search 'Hidden App'

### Expected behavior

It should have show me the hidden app.

### Device information

- Device: [Samsung Galaxy A54]
- OS: [Android 13 OneUI 5.1]
- App version: [13 Dev 2354]

**Comment by MrSluffy** [comment]
Please specify which 13-dev version since this commit d4c79f060eb21e6fde9b5a6fbe004ef145e15016 should fixed it

**Comment by MrSluffy** [comment]
https://github.com/LawnchairLauncher/lawnchair/assets/36076410/d7684a53-9cc6-49be-8568-b60a6baae162

**Comment by Alpointernet** [comment]
> document_6262771043006418419.mp4

It doesnt do the same thing on me. It doesnt show the app even with show when full name is typed. (I enabled it)

**Comment by MrSluffy** [comment]
What version are you using?
