### ISSUE TITLE
The themed icons showed in Home screen & App drawer

### ISSUE THREAD

**Issue by mortim** [Deletescape-Media/Lawnchair#3756]
### Describe the bug

The themed icons are showed in Home Screen and App Drawer.

### Steps to reproduce

- Go to Lawnchair settings
- Go to 'Icon packs'
- Go to 'Themed icons'

### Expected behavior

but it should apply only the theme icon for Home screen.

### Screenshots

![Screenshot_20231122-133407](https://github.com/LawnchairLauncher/lawnchair/assets/33499834/350ff60b-02c0-4b4b-b94d-9d24690e666b)
![Screenshot_20231122-133436~2](https://github.com/LawnchairLauncher/lawnchair/assets/33499834/70970a7c-9491-480b-840f-71f1e53d6fd6)

### Device information

- Device: Google Pixel 8
- OS: [Android 14]
- App version: [12.1.0 Alpha 4]

**Comment by pacjo** [comment]
You can somewhat fix it but toggling settings between all 3 (off, home screen, home and app drawer) and maybe also uninstalling and reinstalling lawnicons.

It took some time but It worked for me, though I don't know what I did exactly.

**Comment by mortim** [comment]
> You can somewhat fix it but toggling settings between all 3 (off, home screen, home and app drawer) and maybe also uninstalling and reinstalling lawnicons.
> 
> It took some time but It worked for me, though I don't know what I did exactly.

I reinstalled and it works, thanks !

**Comment by pacjo** [comment]
I wouldn't close it, it's still a bug.

**Comment by mortim** [comment]
> I wouldn't close it, it's still a bug.

I understood the problem and I think it's definitively not a bug, the 'Themed icons' is in order to change the color icons, it's a an adaptive color regarding to homescreen wallpaper color.
