### ISSUE TITLE
[FEATURE] Use SEPARATE-RECENT-ACTIVITIE which will add closing animation for apps

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3762]
### Describe the feature

In launcher3 i found code which has separate recent activity which adds the closing animations for custom launchers adding this feature would improve launcher experience and using closing animations without quick switch

### Why would it be useful to add?

The launcher experience would be enhanced for non rooted users

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20231124-193845](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/eca9ef39-67a9-4538-88b0-06fd0ce98ec2)
This can be found in developer options if possible

### Additional context

Maybe this feature was used in launchers such as hyperion and nova this should work with android 12 devices but not with i think android 11 lower

**Comment by MrSluffy** [comment]
It's already there, to access FEATURE FLAGS 

type `/lawnchairdebug` in all app search


https://github.com/LawnchairLauncher/lawnchair/assets/36076410/de7f78d8-fb3e-4f2e-8990-7470f06ae580

**Comment by SeanDylan** [comment]
> It's already there, to access FEATURE FLAGS
> 
> type `/lawnchairdebug` in all app search
> 
>  VID_20231124_230934_124.mp4

It's need to be enabled by default or implemented without using debug menu

**Comment by MrSluffy** [comment]
> > It's already there, to access FEATURE FLAGS
> > type `/lawnchairdebug` in all app search
> > VID_20231124_230934_124.mp4
> 
> It's need to be enabled by default or implemented without using debug menu

No it doesn't need to enable by default, since it break for user who used QuickSwitch, maybe we can add an option under Gesture category

btw I tested and it's support 11 up to 13 for 10 doesn't do anything , I'll test it in 14 later on

**Comment by SeanDylan** [comment]
> > > It's already there, to access FEATURE FLAGS
> > > type `/lawnchairdebug` in all app search
> > > VID_20231124_230934_124.mp4
> > 
> > It's need to be enabled by default or implemented without using debug menu
> 
> No it doesn't need to enable by default, since it break for user who used QuickSwitch, maybe we can add an option under Gesture category
> 
> btw I tested and it's support 11 up to 13 for 10 doesn't do anything , I'll test it in 14 later on
> 
> 

It makes sense but my solution is to included in general or home by default it should be turned off what can be turned on for none quick switch users

**Comment by SeanDylan** [comment]
> > > It's already there, to access FEATURE FLAGS
> > > type `/lawnchairdebug` in all app search
> > > VID_20231124_230934_124.mp4
> > 
> > It's need to be enabled by default or implemented without using debug menu
> 
> No it doesn't need to enable by default, since it break for user who used QuickSwitch, maybe we can add an option under Gesture category
> 
> btw I tested and it's support 11 up to 13 for 10 doesn't do anything , I'll test it in 14 later on
> 
> 

I agree with you adding it in the general option will be good news for users who don't want to root but have animations like this
Probably most people already use android 11 so it would be a good option to add
