### ISSUE TITLE
[BUG] Widget sheet incorrect theme for work tab's background

### ISSUE THREAD

**Issue by validcube** [Deletescape-Media/Lawnchair#3766]
### Describe the bug

This bug appear in `13-dev` branch, the background for work/user switcher tab (something) uses the wrong colour

### Steps to reproduce

Steps to reproduce the behaviour:
1. Turn on light mode (and don't forget your sunglasses :trollface:)
2. Open the Widget sheet
3. See the background behind work tab

### Expected behavior

the background should be primaryContainer or the correct semantic colour of the material 3 design

### Screenshots

It's a little hard to see, the work tab shows white background when it should be primary container

![image](https://github.com/LawnchairLauncher/lawnchair/assets/93124920/6e75520a-650f-46a7-9c8a-58e47664f269)

### Device information

- Device: Samsung M23 5G
- OS: Android 13 Release 1 (One UI 5.1)
- App version: Lawnchair 13 Dev [(2354)](https://github.com/LawnchairLauncher/lawnchair/actions/runs/6939998488)

**Comment by validcube** [comment]
Ah, apparently the background uses System Accent colour instead of Lawnchair's colour so that's why they're mismatched.

Additionally, the widget list card is also mismatched.

![image](https://github.com/LawnchairLauncher/lawnchair/assets/93124920/161ff2a8-295c-4ad6-9083-744c56dadac6)

**Comment by MrSluffy** [comment]
What you mean by widget list card mismatched? Is there a proper matched?

**Comment by validcube** [comment]
> What you mean by widget list card mismatched? Is there a proper matched?

Whoops, by mismatched I mean the colour uses the System Accent colour instead of Lawnchair.

**Comment by SuperDragonXD** [comment]
This issue is already fixed by the latest development build. Closing this issue.
