### ISSUE TITLE
[FEATURE] Search bar is too close to the gesture navigations.

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#3770]
### Describe the feature

Most of the time when I'm trying to use the nav bar I accidentally tap the search bar.

### Why would it be useful to add?

It feels like a bug?

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20231125_140234_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/e2217237-8308-4f80-a4ed-7e9498a39168)

### Additional context

![Screenshot_20231125_141103_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/73cce6a6-4355-460a-a527-27609c181bdc)
In the lawnchair 12 it wasn't like this

**Comment by MrSluffy** [comment]
Fixed : e28d20dde3c887cb793729841016970cf7d74dcc
