### ISSUE TITLE
Google Calendar widget goes blank without `ENABLE_WIDGET_HOST_IN_BACKGROUND`

### ISSUE THREAD

**Issue by ThatOneCalculator** [Deletescape-Media/Lawnchair#3771]
### Describe the bug

After turning.my phone on and off, the Google Calendar widget goes blank except for the plus button. Resizing it doesn't help, only removing and re-adding it. 

### Steps to reproduce

1. Add Calendar widget
2. Turn phone off and on

### Expected behavior

Doesn't go blank

### Screenshots

![Screenshot_20231125-084814](https://github.com/LawnchairLauncher/lawnchair/assets/44733677/fd393aa6-e0e5-4ac9-b959-91eebc65b28f)

### Device information

- Device: Pixel 7
- OS: GrapheneOS 14
- App version: https://github.com/LawnchairLauncher/lawnchair/commit/3e9ff6e0951babfecebc5f502bdf2049c39f4e5e

### Additional context

Doesn't happen on any other launcher

**Comment by ThatOneCalculator** [comment]
Manually enabling `ENABLE_WIDGET_HOST_IN_BACKGROUND` seems to have fixed this.

**Comment by MrSluffy** [comment]
Is this the one? [GrapheneOS](https://grapheneos.org/#grapheneos) it seems lawnchair having a lot of issue in this OS, I tested in stock pixel using emulator and custom roms no issue.

Let's wait for other OS to up this issue

**Comment by MrSluffy** [comment]
> Manually enabling `ENABLE_WIDGET_HOST_IN_BACKGROUND` seems to have fixed this.

It will cause a lot of battery usage when we able this `ENABLE_WIDGET_HOST_IN_BACKGROUND` by default

**Comment by ThatOneCalculator** [comment]
> Is this the one? [GrapheneOS](https://grapheneos.org/#grapheneos) it seems lawnchair having a lot of issue in this OS, I tested in stock pixel using emulator and custom roms no issue.

Yeah, that's it

**Comment by ThatOneCalculator** [comment]
The thing is, on other launchers in GrapheneOS (Launcher3, Kvæsisto, Quick Draw), this issue doesn't occur.

**Comment by MrSluffy** [comment]
> The thing is, on other launchers in GrapheneOS (Launcher3, Kvæsisto, Quick Draw), this issue doesn't occur.

Yeah, will try to build the os later this month on my device and try to fix it

**Comment by amanrajOO7** [comment]
Tried on DerpFest A14 on POCO F1. Didn't faced this.

**Comment by MrSluffy** [comment]
Is still an issue in `14-dev`?

**Comment by ThatOneCalculator** [comment]
Yes

**Comment by MrSluffy** [comment]
`ENABLE_WIDGET_HOST_IN_BACKGROUND` Already enabled by default after merge launcher3 A14

**Comment by MrSluffy** [comment]
It should fixed the issue

**Comment by ThatOneCalculator** [comment]
It still happens sometimes though, even with it enabled

**Comment by ThatOneCalculator** [comment]
This no longer seems to be an issue.
