### ISSUE TITLE
[BUG] Launcher back anim is not working on Android 13

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3775]
### Describe the bug

Android 13 intro the animation of swiping back and returning to launcher, but this is not working after we merge AOSP 13 code, it's a grate behavior, we should fix it.

### Steps to reproduce

1. Click an icon on home screen.
2. Back to home screen.

### Expected behavior

It works.

### Device information

- Device: Google Pixel 6, Moto X40.
- OS: Android 14, Android 13.
- App version: 13

**Comment by Goooler** [comment]
CC @MrSluffy

**Comment by MrSluffy** [comment]
Please send screen record of expected and bug cuz I'm not using A14 yet

**Comment by Goooler** [comment]
I'm not sure why this screen record for Lanwchair is not complete, but I'm tapping the same icons on different launchers. This behavior doesn't work for me on both A13 and A14 devices.

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/e91a9d1f-6a17-4898-ad0a-31a8b65c623a

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/a8781f37-4969-45d8-9319-389dd78dd82e

**Comment by MrSluffy** [comment]
Yeah it's blank, btw the moto launcher is stock launcher for your device or third party without QS? 

the behavior your expecting from lawnchair only available with QS, but since we haven't support/ merge 14, it's expected behavior.

**Comment by Goooler** [comment]
Moto Launcher is the stock launcher, and this device is on A13.

**Comment by MrSluffy** [comment]
Here's on my end, I'm using QuickSwitch btw

https://github.com/LawnchairLauncher/lawnchair/assets/36076410/bd8b1c7e-b4d1-49c9-96f4-0a02bce273e6

**Comment by MrSluffy** [comment]
here's video with button 

https://github.com/LawnchairLauncher/lawnchair/assets/36076410/8ad6456c-c1bf-4dca-aeaf-7c6273ca0658

**Comment by Goooler** [comment]
After using QS:
```
java.lang.NoSuchFieldError: No instance field rotationChange of type I in class Landroid/view/RemoteAnimationTarget; or its superclasses (declaration of 'android.view.RemoteAnimationTarget' appears in /system/framework/framework.jar!classes3.dex)
  at com.android.launcher3.QuickstepTransitionManager.getRotationChange(QuickstepTransitionManager.java:1276)
  at com.android.launcher3.QuickstepTransitionManager.getOpeningWindowAnimators(QuickstepTransitionManager.java:655)
  at com.android.launcher3.QuickstepTransitionManager.composeIconLaunchAnimator(QuickstepTransitionManager.java:400)
  at com.android.launcher3.QuickstepTransitionManager.-$$Nest$mcomposeIconLaunchAnimator(Unknown Source:0)
  at com.android.launcher3.QuickstepTransitionManager$AppLaunchAnimationRunner.onAnimationStart(QuickstepTransitionManager.java:1776)
  at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$2(LauncherAnimationRunner.java:95)
  at com.android.launcher3.LauncherAnimationRunner.$r8$lambda$1wv0QB4xe8XmIzQ8-HXfT0gdXvs(Unknown Source:0)
  at com.android.launcher3.LauncherAnimationRunner$$ExternalSyntheticLambda0.run(Unknown Source:12)
  at android.os.Handler.handleCallback(Handler.java:984)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loopOnce(Looper.java:238)
  at android.os.Looper.loop(Looper.java:357)
  at android.app.ActivityThread.main(ActivityThread.java:8118)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

**Comment by MrSluffy** [comment]
> After using QS:
> 
> ```
> java.lang.NoSuchFieldError: No instance field rotationChange of type I in class Landroid/view/RemoteAnimationTarget; or its superclasses (declaration of 'android.view.RemoteAnimationTarget' appears in /system/framework/framework.jar!classes3.dex)
>   at com.android.launcher3.QuickstepTransitionManager.getRotationChange(QuickstepTransitionManager.java:1276)
>   at com.android.launcher3.QuickstepTransitionManager.getOpeningWindowAnimators(QuickstepTransitionManager.java:655)
>   at com.android.launcher3.QuickstepTransitionManager.composeIconLaunchAnimator(QuickstepTransitionManager.java:400)
>   at com.android.launcher3.QuickstepTransitionManager.-$$Nest$mcomposeIconLaunchAnimator(Unknown Source:0)
>   at com.android.launcher3.QuickstepTransitionManager$AppLaunchAnimationRunner.onAnimationStart(QuickstepTransitionManager.java:1776)
>   at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$2(LauncherAnimationRunner.java:95)
>   at com.android.launcher3.LauncherAnimationRunner.$r8$lambda$1wv0QB4xe8XmIzQ8-HXfT0gdXvs(Unknown Source:0)
>   at com.android.launcher3.LauncherAnimationRunner$$ExternalSyntheticLambda0.run(Unknown Source:12)
>   at android.os.Handler.handleCallback(Handler.java:984)
>   at android.os.Handler.dispatchMessage(Handler.java:104)
>   at android.os.Looper.loopOnce(Looper.java:238)
>   at android.os.Looper.loop(Looper.java:357)
>   at android.app.ActivityThread.main(ActivityThread.java:8118)
>   at java.lang.reflect.Method.invoke(Native Method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
> ```
Not fix this crash yet, but it's duplicate from #3733

**Comment by MrSluffy** [comment]
can you try to surround this with catch? [getRotationChange ](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/quickstep/src/com/android/launcher3/QuickstepTransitionManager.java#L1275C7-L1275C7) and build it, or try to introduce a better fix that will be great

**Comment by Goooler** [comment]
Catching it works for me, should we send a PR to do this?

**Comment by MrSluffy** [comment]
yeah you can, also add this too #3733 so it will be closed too when merge since it's similar based on the crash log

**Comment by Goooler** [comment]
But I found a new issue, Recents doesn't show recent apps correctly.

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/f7ee38d5-ade9-4601-a1a2-27293308cc7f
