### ISSUE TITLE
[BUG] Recents is empty [A13]

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3777]
### Describe the bug

After fixing #3733, I can set Lawnchair 13 as the default Recents provider by QS, but there is no recent apps shown in Recents.

### Steps to reproduce

1. Open some apps.
2. Open Recents.

### Expected behavior

Apps show in Recents.

### Screenshots

The screenshot is wrong on my phone, I just shot from the other phone.

<img src="https://github.com/LawnchairLauncher/lawnchair/assets/10363352/24062a49-d268-49e9-89d6-a30563cb329f" width="33%" height="33%">

### Device information

- Device: Moto X40
- OS: Android 13
- App version: 13

**Comment by a1623382** [comment]
I have same problem. At the same time, I also collected logs like this : https://katb.in/unuserabapo

**Comment by Manasx100** [comment]
Same problem and recents sometimes crashes lawnchair

**Comment by Manasx100** [comment]
Recents started crashing
Logs: https://pastebin.com/vpfJv7sf

**Comment by Goooler** [comment]
Seems this has been gone after I upgraded my phone to A14 and LC14.

**Comment by MrSluffy** [comment]
> Seems this has been gone after I upgraded my phone to A14 and LC14.

Yes, but should be supported and fix too in A13

**Comment by ujwal246** [comment]
Fix when sir ? 🥲
