### ISSUE TITLE
Older Lawnicons Forks are not working.

### ISSUE THREAD

**Issue by Ravi-Kishor** [Deletescape-Media/Lawnchair#3782]
### Describe the bug

Older lawnicon forks like RK Icons, Team files Lawnicons etc, are not eveb detected when installed, in the themed icon source. Ofc in Lawnchair 13-dev branch.

### Steps to reproduce

Install older themed icon source and its now showing or detected in lawnchair dev 13 branch.

### Expected behavior

There should be option to select themed icon source.

### Device information

OS: Android 13

**Comment by MrSluffy** [comment]
I'll change this to feature, enhancement cause it's intended behavior

**Comment by MrSluffy** [comment]
and please update the title accordingly
