### ISSUE TITLE
[FEATURE] `GestureNavContract` support

### ISSUE THREAD

**Issue by tropicaaal** [Deletescape-Media/Lawnchair#3784]
### Describe the feature

Technically a dupe of #2856, although it was closed as stale a while back and I thought I might open an issue focusing a more specific and realistic implementation for rootless users.

Since Android 11 or so, many launcher3-based system launchers and some OEMs such as Samsung have offered the [`GestureNavContract`](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/src/com/android/launcher3/GestureNavContract.java) class to third party launchers as a method of providing better animations to users without the need for something like QuickSwitch.

While not being exactly the same, the animations are an improvement over the current "scale-to-the-middle" effect that apps do by default. Lawnchair currently doesn't seem to use this API, although other launchers such as nova, hyperion, and niagra have implemented animations using this API to [pretty good success](https://twitter.com/prjkt_io/status/1551634957030010881).

### Why would it be useful to add?

Offers a better experience/opening and closing animations for rootless users and those who do not use quickswitch.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://github.com/LawnchairLauncher/lawnchair/assets/42101043/978662bf-79f7-4a97-a545-fb1386818b06

https://twitter.com/prjkt_io/status/1551634957030010881

### Additional context

Before A13, there was a [bug](https://issuetracker.google.com/issues/202864574) where the animations tended to end early, although this has been fixed in AOSP and by many OEMs following Android 13's release.

**Comment by MrSluffy** [comment]
Thanks for the effort for creating this issue, I'll mark this Duplicate #3762

**Comment by RouxTheCaster** [comment]
Most needed feature ever tho
