### ISSUE TITLE
Weather icon, 8:00 am also shows the night

### ISSUE THREAD

**Issue by gedoor** [Deletescape-Media/Lawnchair#379]
![photo_2017-08-02_08-10-17](https://user-images.githubusercontent.com/22701807/28852209-1af1ef9e-775a-11e7-9153-cab06b600df7.jpg)

**Comment by AxiK101** [comment]
Weather in general isn't too accurate yet

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
