### ISSUE TITLE
The lower left corner of the phone icon appears on a box, gif

### ISSUE THREAD

**Issue by gedoor** [Deletescape-Media/Lawnchair#380]
![gif_20170802082211](https://user-images.githubusercontent.com/22701807/28852523-4faa7a74-775c-11e7-80f7-a0d8da226b9c.gif)

**Comment by suphon-t** [comment]
@gedoor Do you have any non-touch input methods?

**Comment by gedoor** [comment]
@paphonb no

**Comment by gedoor** [comment]
Press the Menu key, and then press the Back key

**Comment by gedoor** [comment]
Pixel launcher does not have this problem

**Comment by skittles9823** [comment]
@gedoor its menu, then home key for me to reproduce.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
