### ISSUE TITLE
[Bug] App closing animation and Recents (Root)

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#3800]
### Describe the bug

1. Sometimes app Closing animation doesn't meet the app icon.
2. 'Recents' doesn't store any apps.

Device - Samsung F22
Software - A13 based One UI 5.1 core rooted 

### Steps to reproduce

Only Developer knows 

### Expected behavior

Na

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/117264003/de7717d1-8d47-48ed-8b3d-b95ce640c3c9

### Device information

Device - Samsung F22
Software - A13 based One UI 5.1 core rooted 
App version - Lastest #2442

**Comment by Goooler** [comment]
Empty Recents related to #3777.

**Comment by ujwal246** [comment]
Issue fixed. Recents working perfectly.
Thanks to amazing developer.

**Comment by MrSluffy** [comment]
Done

**Comment by MrSluffy** [comment]
Don't close yet since the linked branch haven't merge yet in 14-dev , it will automatically close once merge
