### ISSUE TITLE
[BUG] Touching App Label Opens Play Store on Search Results

### ISSUE THREAD

**Issue by Alpointernet** [Deletescape-Media/Lawnchair#3817]
### Describe the bug

When you touch on the searched apps label, it does open Play Store.

### Steps to reproduce

1. Go to 'App Drawer'
2. Click on 'Search'
3. Search the 'App'
4. Touch on the 'Label of the app"
5. See error

### Expected behavior

It should have opened the app.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/128177629/923842b4-1eb9-42b0-b54d-b537c2cf81da

### Device information

- Device: [Galaxy A54]
- OS: [Android 14 OneUI 6]
- App version: [13 dev 2487]

### Additional context

When you click on the apps icon, it does open the app. Like it should. (I did show on the video)

**Comment by MrSluffy** [comment]
duplicate #3740
