### ISSUE TITLE
[BUG] Icons very close to the search bar

### ISSUE THREAD

**Issue by TheJNXx** [Deletescape-Media/Lawnchair#3818]
### Describe the bug

The smaller the icons, the more they stick to the search bar

### Steps to reproduce

1. Go to Lawnchair V13
2. Set icons to a lower value
2. See error

### Expected behavior

Which will separate the search bar

### Screenshots

![20231202_151035](https://github.com/LawnchairLauncher/lawnchair/assets/108956098/3073fa38-41a3-4af1-b943-a0252a9c401d)

### Device information

- Device: [Samsung A02]
- OS: [Android 10 One Ui Core 2.5]
- App version: [Lawnchair 13 Dev 2485]

### Additional context

The failure could be due to not having navigation gestures, my phone does not have them by default, if I force them the lawnchair crashes

**Comment by MrSluffy** [comment]
Fixes on this e28d20dde3c887cb793729841016970cf7d74dcc
