### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by joshuah345** [Deletescape-Media/Lawnchair#382]
1. Ability to sort folders and app drawer
2. Bulk add apps to folder from checklist or drawer

**Comment by zlyfer** [comment]
An option to switch between google now and oneplus shelf would be nice!

**Comment by fonix232** [comment]
Please stop cluttering the issue system. If you want a feature, create a separate issue for it (one bug, one issue; one feature, one issue). This goes both for @joshuah345  and @zlyfer
