### ISSUE TITLE
[BUG] [Lawnchair 13] Stretch Animations of the App Drawer Doesn't Work On Android 11

### ISSUE THREAD

**Issue by chathushkaimasara** [Deletescape-Media/Lawnchair#3827]
### Describe the bug

Stretch Animation on App drawer on Lawnchair doesn't work. The stretch animations are working every where on launcher but not on the App drawer.

### Steps to reproduce

1. Go to the home screen
2. Swiped Up to See app drawer
3. App drower appeared Without Stretch Animations

### Expected behavior

App drawer should have Stretch Animation Like On Android 12 and above

### Screenshots

Lawnchair 13

https://github.com/LawnchairLauncher/lawnchair/assets/143923312/f8cee4f2-bf95-4f44-9bcd-59651e4cc283

Lawnchair 12.1

https://github.com/LawnchairLauncher/lawnchair/assets/143923312/69184b0c-aae2-4e91-8f01-7354bb6f79bf

### Device information

- Device: [Samsung Galaxy M02]
- OS: [One UI Core 3.1, Android 11]
- App version: [Lawnchair (Debug) 13 Dev (#2487)]

### Additional context

No Additional Context

**Comment by SuperDragonXD** [comment]
Fixed in https://github.com/LawnchairLauncher/lawnchair/commit/ee62c8774656a3364f9928fc06133c13caa9bf32
