### ISSUE TITLE
App crashes after icon selection

### ISSUE THREAD

**Issue by jay-chorus** [Deletescape-Media/Lawnchair#383]
The launcher always crashes whenever I change the icon for any system app, especially the dialer app. Specifically, if I want another variant of the same icon (which they include in the icon pack), that's what causes the app to crash. There's an prompt after the crash saying; 'Lawnchair cannot be used, please give permissions'. Even after allowing all permissions, it still crashes and displays the prompt again.

**Comment by suphon-t** [comment]
@jay-chorus Lawnchair version?

**Comment by jay-chorus** [comment]
It's version 818

On Aug 2, 2017 2:49 PM, "paphonbth" <notifications@github.com> wrote:

@jay-chorus <https://github.com/jay-chorus> Lawnchair version?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Deletescape-Media/Lawnchair/issues/383#issuecomment-319695886>,
or mute the thread

**Comment by paphonb** [comment]
@jay-chorus This is fixed in unreleased versions.

**Comment by suphon-t** [comment]
This is fixed but not released yet.
