### ISSUE TITLE
[BUG] Text outside highlighted area in search

### ISSUE THREAD

**Issue by pacjo** [Deletescape-Media/Lawnchair#3838]
### Describe the bug

When searching for an app with long name, text can appear outside of the highlighted area. Minor visual bug not affecting functionality.

### Steps to reproduce

1. Open search
2. Type name (or just part) of an app with long name

### Expected behavior

Whole text would fit inside highlighted area.

### Screenshots

![Screenshot_20231209-110759_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/56438628/2a76943e-d563-4322-8525-35007bc8576e)
![Screenshot_20231209-110815_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/56438628/44481b8d-51dc-4592-a3b0-9e08619ff3a6)

### Device information

- Device: Redmi Note 10 Pro global (sweet)
- OS: crDroid 9.11 (A12, November security patch)
- App version: GH action (i think this commit: be8bb75)

**Comment by MrSluffy** [comment]
Close as it's remove after A14 merge

**Comment by pacjo** [comment]
Actually, it seems to still be present in this one: https://github.com/Goooler/LawnchairRelease/releases/tag/14.0.0-20240203 .

I don't think it's just an issue with Goooler's fork.

![Screenshot_20240207-133318_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/56438628/4bfa4c7a-062a-40e7-a018-5e8362d9d5d9)
