### ISSUE TITLE
[FEATURE] Option to disable dock

### ISSUE THREAD

**Issue by GuiSousa135** [Deletescape-Media/Lawnchair#3839]
### Describe the feature

Option to fully disable the dock and the search widget.

### Why would it be useful to add?

This function would allow the user more space on the main screen to place widgets or app icons.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Like the Neo Launcher implementation.

![Screenshot_20231209-111511_Neo Launcher](https://github.com/LawnchairLauncher/lawnchair/assets/55188286/eabd737d-4f88-4db3-8186-93ff7b5bd27b)

**Comment by MrSluffy** [comment]
#2327
