### ISSUE TITLE
Dark folders revert to light

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#384]
It's a bug in latest versions, can you fix it plz?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
Here what i mean:

![](http://i.imgur.com/rrNpABu.png)

![](http://i.imgur.com/XNC8gBB.png)

![](http://i.imgur.com/sQLViSP.png)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
Duplicate of #340 

But why are you creating two issues for the same bug?
