### ISSUE TITLE
[BUG]  Notification Dots

### ISSUE THREAD

**Issue by adewalemudasiru** [Deletescape-Media/Lawnchair#3840]
### Describe the bug

Hi, I just installed lawnchair 12 apha 4. Enabled notification Dots but after a reboot notification dot stops showing. I've tried turning of and on but doesn't work either... Is there a solution for that?

### Steps to reproduce

1. Go to Lawnchair settings
2. Click on General 
3. Scroll down to notification Dots and enable it

### Expected behavior

Show notification count for msgs

### Device information

- Device: [Tecno Spark 2]
- OS: [Stock ROM Android version 10]
- App version: [2.1.0 Alpha 4]

**Comment by breversa** [comment]
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/4563?
