### ISSUE TITLE
[BUG] Random app opens everytime i leave an app and try to open another one

### ISSUE THREAD

**Issue by Tanzim73** [Deletescape-Media/Lawnchair#3843]
### Describe the bug

When I leave an app and quickly tap on any other app, a random app opens every time instead of the one i clicked. And if I tap on any blank space on the home screen my most recent app opens. I have to wait for around a second or else this happens every time. 

### Steps to reproduce

1. Open any app. 
2. Leave it quickly or spend some time in it, it doesnt matter. 
3. Open any other app on the home screen as soon as you are at the home screen. 
4. The bug happens and a random app would open up insted of the one you clicked. 

### Expected behavior

I should be able to open any app as soon as I leave another app. 

### Device information

- Device: Galaxy S10 plus
- OS: One ui 4.1 android 12
- App version: 12.1.0 Alpha 4

**Comment by MrSluffy** [comment]
use latest lawnchair 14
