### ISSUE TITLE
[BUG] changing dock settings merges desktops

### ISSUE THREAD

**Issue by BlackLotus** [Deletescape-Media/Lawnchair#3844]
### Describe the bug

changing dock settings for how many dock icons are displayed merges desktops.
I had icons spread across multiple Desktops, after changing the count from 8 to 9. after that all icons were on desktop 1

### Steps to reproduce

1. put icons in multiple Desktops
2. go into the settings and change the max number of icons for the dock
3. curse because all your icons Wege moved

### Expected behavior

The Desktops should keep all positions for all icons

### Device information

- Device: OnePlus 5
- OS: LineageOS 20 microg (Android 13)
- App version: 12.1.0 Alpha 4 fdroid

**Comment by MrSluffy** [comment]
Closes : 916da31036bef25312cb284f023b8dc38fdfa51c
