### ISSUE TITLE
[BUG] Widgets Blink When You Go to Homescreen

### ISSUE THREAD

**Issue by Alpointernet** [Deletescape-Media/Lawnchair#3845]
### Describe the bug

When you go back to homescreen from an app, the widgets does disappear and comes back (this happens in a very short time)

### Steps to reproduce

1. Go to the homescreen from an app
2. See error

### Expected behavior

It should show the widgets without any blinking.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/128177629/b84c51fd-8d5c-4417-9aa3-d1646deeaf1b

### Device information

- Device: [Galaxy A54]
- OS: [Android 14 OneUI 6]
- App version: [13 dev 69]

**Comment by cyberastr4l** [comment]
Hey, just a question not related to this, I see you have a Samsung, how did you get the AOSP icons on the top? Did you use #hex installer? If yes, does it fully work with Android 14 One UI 6?

**Comment by MrSluffy** [comment]
Does still occur in `14-dev`?  I cant reproduce this in `14-dev`,  
Seems like fixed after launcher3 14 merge

can you confirm in your end

**Comment by Alpointernet** [comment]
> Does still occur in `14-dev`? I cant reproduce this in `14-dev`, Seems like fixed after launcher3 14 merge
> 
> can you confirm in your end

It still happens. Also sorry for seeing it late.

**Comment by MoTheAmazing** [comment]
I see the same thing on lawnchair 14 with android 13 one ui 5.1.
