### ISSUE TITLE
Apply new page swiping animation to paged At A Glance

### ISSUE THREAD

**Issue by ThatOneCalculator** [Deletescape-Media/Lawnchair#3849]
### Describe the feature

Applying this animation:

https://github.com/LawnchairLauncher/lawnchair/assets/44733677/12d763f0-5c8f-4e16-bbb4-81a4789204ff

To these AAG dots:

https://github.com/LawnchairLauncher/lawnchair/assets/44733677/79991d9d-41db-44f8-8d71-3c28c1ccda72

### Why would it be useful to add?

Visual consistency 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

**Comment by MrSluffy** [comment]
Is this smartspacer? if yes, create an issue here : https://github.com/KieronQuinn/Smartspacer

**Comment by ThatOneCalculator** [comment]
Gotcha. I thought it might be here since the Smartspacer developer said that he used a Lawnchair SDK to make the swipeable component
