### ISSUE TITLE
[BUG] Just Black Screen on Android 8

### ISSUE THREAD

**Issue by Axel1805** [Deletescape-Media/Lawnchair#3864]
### Describe the bug

Here's me hoping that lawnchair will still be compatible on older Android versions such as Android 8😔

After installing lawnchair 13 debug version, and setting it as the default home screen, when going back to the home screen all I see is just black, no app response, no changes, just black, like the entirety of my screen is covered in black, waited for a couple of minutes or so but nothing happens.

### Steps to reproduce

You could possibly experience this only on Android 8 devices

Just download and install the latest Lawnchair (debug) 13 dev
After that open or use the launcher and then there the "black screen" problem

### Expected behavior

It's the Debug version so
I already expected bugs to happen, 

### Screenshots

![Screenshot_2023-12-16-22-43-24-52](https://github.com/LawnchairLauncher/lawnchair/assets/129747640/9ae2c41d-f0f9-4fde-aed6-854cbc793a37)

### Device information

- Device: Oppo A3s CPH1853
- OS: Android version 8.1.0, ColorOS version V5.2.1
- App version: Lawnchair (debug) 13 dev

**Comment by MrSluffy** [comment]
It's expected not to work in A8 as per the ff :

https://github.com/LawnchairLauncher/lawnchair/commit/e994660cb053ecf5eeecd4d117a6f5827ec25bfe https://github.com/LawnchairLauncher/lawnchair/commit/5931c9afecd826bb3463a863212e681f46383bd0

If you want to support A8, Please change label to FEATURE Add compatibility to A8 etc...
