### ISSUE TITLE
[BUG] Android 13 App gesture control for swiping into apps from home screen not working.

### ISSUE THREAD

**Issue by mahiatlinux** [Deletescape-Media/Lawnchair#3865]
### Describe the bug

Usually, when you swipe left or right on the gestures control bar on the home screen, it opens an already opened app. But with Lawnchair, the app flashes on the display, then it quickly reverts to the home screen. This is the issue.

### Steps to reproduce

1. Go to home screen.
2. Try to swipe right or left on gesture navigation to open recent apps.
3. Instantly jumps back to home screen without going into app.

### Expected behavior

As you wipe the gesture control from the home screen, it should go to an open app.

### Device information

- Device: Samsung Galaxy S20 FE 5G
- OS: Android 13, Samsung.
- App version: 12.1.0 Alpha 4

**Comment by mahiatlinux** [comment]
It does not work with any versions!

**Comment by mahiatlinux** [comment]
It simply flashes the app, then jumps back to homescreen.

**Comment by mahiatlinux** [comment]
@MrSluffy How is this outdated?
This is the latest version Lawnchair.

**Comment by MrSluffy** [comment]
The lawnchair `12.1.0 Alpha 4` is part of the branch `12.1-dev` which is no longer active, the current active branch is `14-dev`

**Comment by mahiatlinux** [comment]
> The lawnchair `12.1.0 Alpha 4` is part of the branch `12.1-dev` which is no longer active, the current active branch is `14-dev`

Can you please send the link to download it? I can't seem to find it. Thanks!!!
