### ISSUE TITLE
Swipe down gesture to "show notification panel" not working on latest debug

### ISSUE THREAD

**Issue by AndrewDallas** [Deletescape-Media/Lawnchair#3869]
### Describe the bug

Latest debug does not allow swipe down to show notification panel. All other gestures working as expected 

### Steps to reproduce

Steps to reproduce the behaviour

Set swipe down to show notification panel in gestures.
Swipe down
Nothing happens . Also no vibration feedback either.

### Expected behavior

When swiping down once set to show notification panel is set, the notification panel should show.

### Device information

- Device: Google Pixel 6
- OS: QPR beta 2 android 14
- App version: debug version 134

**Comment by Ravi-Kishor** [comment]
Same issue in A13 Oct Patch.

**Comment by MrSluffy** [comment]
fixed now in this e50e2e8231502ef8250c2c7580a5e09018fabe0f
