### ISSUE TITLE
No responsive icons for Chrome-Shortcuts

### ISSUE THREAD

**Issue by zlyfer** [Deletescape-Media/Lawnchair#387]
I added a website via Chrome to the homescreen (the website is responsive and supports standalone shortcuts). My iconpack MIUI 8 rounds the coners of every app icon and ususally the shortcuts of chrome as well (at least in my standard launcher). But Lawnchair doesn't.
Will there be a chance to support that?

**Comment by tigerstown** [comment]
Having same issue on Lawnchair and 8.0 just FYI

**Comment by tigerstown** [comment]
Sorry I miss read the issue. My issue is when adding a chrome shortcut to homescreen it doesn't appear at all on my pixel XL and 8.0.
