### ISSUE TITLE
[BUG]  App Order Is Not Alphabetical (Again)

### ISSUE THREAD

**Issue by Alpointernet** [Deletescape-Media/Lawnchair#3872]
### Describe the bug

App order is not alphabetical.

### Steps to reproduce

1. Go to 'App Drawer'
2. See error

### Expected behavior

It should show me the apps on alphabetical order.

### Screenshots

![Screenshot_20231218_004000_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/128177629/9c391168-c6a1-45c4-8894-d5b291970fef)

### Device information

- Device: [Galaxy A54]
- OS: [Androis 14 OneUI 6]
- App version: [14 dev 147]

### Additional context

This is the same issue I did opened before. 
The animation when you open the app drawer = this bug

**Comment by MrSluffy** [comment]
Oh, The bulk process was set by default in launcher3 A14, we need to reconfigure those

**Comment by MrSluffy** [comment]
Hi I pushed related patch, can you try this build https://github.com/LawnchairLauncher/lawnchair/actions/runs/7242333924

**Comment by Alpointernet** [comment]
> Hi I pushed related patch, can you try this build https://github.com/LawnchairLauncher/lawnchair/actions/runs/7242333924

Yeah, this did fix the problem. Thanks.
