### ISSUE TITLE
Warn that Recents cannot be customized without QuickstepSwitcher

### ISSUE THREAD

**Issue by ThatOneCalculator** [Deletescape-Media/Lawnchair#3884]
### Describe the bug

None of the settings for Recents seem to have any effect. 

### Steps to reproduce

1. Go to Home Settings
2. Select Recents
3. Change any settings 
4. Swipe up to see that none of the changes have applied

### Expected behavior

Settings changed in Recents apply

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/44733677/76ed6cd5-e5f7-41a6-adeb-bb7ed8561a57

### Device information

- Device: Google Pixel 7
- OS: GrapheneOS 14 Beta UQ1A.231205.015.2023121200
- App version: https://github.com/LawnchairLauncher/lawnchair/commit/d0b805d6b9fda7351c3dc291b04479028975e088

**Comment by senposage** [comment]
Confirm to not work here as well

**Comment by MrSluffy** [comment]
Are you using quickswitch?

**Comment by AndrewDallas** [comment]
Same. Never worked for me. 🤷

**Comment by MrSluffy** [comment]
![Screenshot_20231219-054739](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/de92a594-5dfa-4e45-936f-cb33c656fa41)

Recent option is enable in debug build, if you're not using quickswitch and set lawnchair as recent provider it won't take effect

**Comment by ThatOneCalculator** [comment]
No, I don't use QuickSwitch as my device is not rooted.

**Comment by senposage** [comment]
I don't use quick switch. I am rooted but I don't see where to install the apk for it I'm on the latest dev build

**Comment by MrSluffy** [comment]
> I don't use quick switch. I am rooted but I don't see where to install the apk for it I'm on the latest dev build

Please check https://t.me/QuickstepSwitcherReleases/132

**Comment by ThatOneCalculator** [comment]
@MrSluffy Is there any way to get this working without Quickstep? If not, can we get a warning in that part of the settings that you ***need*** Quickstep?

**Comment by senposage** [comment]
module is broken causes system-ui to not load correctly on boot  resulting in soft brick
evox A14 QPR1 kitsue magisk

**Comment by MrSluffy** [comment]
Warning will do, but this option will hide in release build, it's only show in debug for troubleshooting purposes

**Comment by MrSluffy** [comment]
> module is broken causes system-ui to not load correctly on boot resulting in soft brick evox A14 QPR1 kitsue magisk

Module by Quickswitch? Please report in quickswitch support

**Comment by ThatOneCalculator** [comment]
On this note, is there any way to adjust how Recents looks without rooting?

**Comment by MrSluffy** [comment]
> On this note, is there any way to adjust how Recents looks without rooting?

Not possible

**Comment by senposage** [comment]
quickswitch is fraught with problems and instablity I suggest not supporting it with offical releases rather make it an experimental option
there is several problems I have had 
1. its breaking the secure unlock screen after reboot by attempting to allow biometric unlock when pin unlocks are MANDATORY after reboot this cause the launcher to get stuck in limbo 12-18 17:30:04.722  3844  3844 D VRI[LawnchairLauncher]: Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false

2.  during install the module is not properly configuring the default launcher which was the cause of the system-ui softbrick

both issues have been reported in the telegrame but this is far to unstable to be included in a release 

[quickswitchlogs evox-A14-PIXEL6-KITSUNEMAGIKS.zip](https://github.com/LawnchairLauncher/lawnchair/files/13709142/quickswitchlogs.evox-A14-PIXEL6-KITSUNEMAGIKS.zip)

**Comment by MrSluffy** [comment]
> quickswitch is fraught with problems and instablity I suggest not supporting it with offical releases rather make it an experimental option there is several problems I have had
> 
> 1. its breaking the secure unlock screen after reboot by attempting to allow biometric unlock when pin unlocks are MANDATORY after reboot this cause the launcher to get stuck in limbo 12-18 17:30:04.722  3844  3844 D VRI[LawnchairLauncher]: Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
> 2. during install the module is not properly configuring the default launcher which was the cause of the system-ui softbrick
> 
> both issues have been reported in the telegrame but this is far to unstable to be included in a release
> 
> [quickswitchlogs evox-A14-PIXEL6-KITSUNEMAGIKS.zip](https://github.com/LawnchairLauncher/lawnchair/files/13709142/quickswitchlogs.evox-A14-PIXEL6-KITSUNEMAGIKS.zip)

I'm not sure it's rom specefic, I'm used and test it LOS 21, Paranoid Android and Pixel OS never faced such an issue
