### ISSUE TITLE
Use the behavior of Pixel Launcher when the weather information is unavailable

### ISSUE THREAD

**Issue by mydarknight** [Deletescape-Media/Lawnchair#389]
The behavior of weather/date widget of Google Pixel launcher is:
Display date and year first(both two rows are full filled with informations), and display the weather info when the weather info is available.

The behavior of weather/date widget of Lawnchair is:
If the weather option set to enabled state, the weather widget (first row) is hidden or just displayed with ERROR.

I think the behavior of Pixel Launcher is better.

**Comment by AxiK101** [comment]
That whould be best solution for not showing that error on weather ehen in offline mode. Date widget should automatically enable in that state

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
@AxiK101 no need to repeat the content of the issue, this just generates useless notification for **EVERY** watcher on this project

**Comment by fonix232** [comment]
@AxiK101 keep abusing the issue system and you will be blocked from the
repo. This is your first, last and final warning.
