### ISSUE TITLE
[FEATURE] Add Custom Search Bar with an App

### ISSUE THREAD

**Issue by TBNRDev** [Deletescape-Media/Lawnchair#3890]
### Describe the feature

I would like a feature to add an app called "Pixel Search" on Google Play/GitHub for the search bar.
See: [Pixel Search on Google Play](https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch)

### Why would it be useful to add?

It would be amazing to see and use the Pixel Launcher Search Bar in my favorite Lawnchair 12 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![image](https://github.com/LawnchairLauncher/lawnchair/assets/108610517/b0e9dea0-6e11-452d-9ed2-3efd2bd29ece)
![image](https://github.com/LawnchairLauncher/lawnchair/assets/108610517/421057f7-294b-4954-b4ce-c24497716f2c)

### Additional context

I've seen a new development for the search bar in the Launcher but that would be included in Lawnchair 12?

**Comment by MrSluffy** [comment]
We already have Lawnchair advance search #3785 be8bb75d95eb69ef404d33a85b0b67d40bcde86d

**Comment by MrSluffy** [comment]
For including in Lawnchair 12, 
no, since tha active branch is `14-dev`

**Comment by validcube** [comment]
This issue can be resolved, Pixel Search support has been added for a while now
* see: https://github.com/LawnchairLauncher/lawnchair/pull/3442

Use the latest `12.1-dev`, `13-dev` or `14-dev` build for it; *for 13 and 14, I would recommend checking out Lawnchair's advanced search feature.*
