### ISSUE TITLE
[BUG] Taskbar crash

### ISSUE THREAD

**Issue by gaussandhisgun** [Deletescape-Media/Lawnchair#3891]
### Describe the bug

Opening the start menu in the taskbar crashes the launcher. #3888 (the message referenced is mine). No, #3889 did not fix it. 

### Steps to reproduce

1. Enable the taskbar in Recents settings
2. Go anywhere else
3. Open the app menu
4. Catch a crash

### Expected behavior

Menu opens

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/63512006/e7f0a20d-6f64-49bc-9479-ef8a2c4cccf2

### Device information

- Device: miatoll
- OS: GhostOS 2023-11-23, Android 14
- App version: 14 Dev 194

### Additional context

https://katb.in/uhadorasanu

**Comment by src52** [comment]
I experience the same issue, with the same build on a stock Pixel 6.

**Comment by gaussandhisgun** [comment]
yay, its not my ROM being weird for once!

**Comment by gaussandhisgun** [comment]
Seemingly fixed, at least it does not crash in build 373.

**Comment by MrSluffy** [comment]
The fixed not been merge in 14-dev no need to close manually as it will close once the linked branch is merge
