### ISSUE TITLE
[BUG] Back button on drawer search with no text does not do anything

### ISSUE THREAD

**Issue by bkazoo** [Deletescape-Media/Lawnchair#3893]
### Describe the bug

Back button does not do anything when using the applications drawer search with no text

### Steps to reproduce

1. Go to applications drawer
2. Click on Search apps. Keyboard will open.
3. Click on Android's back navigation button
4. **Nothing happens. Keyboard stays open.**

5. Type anything in the search box
6. Click on Android's back navigation button
7. Keyboard is hidden. An additional click on back will return you to Home screen.

### Expected behavior

The behavior with and without text in the search box should be the same, the keyboard should hide and an additional click should return you to the Home screen.

### Screenshots

[Screen_recording_20231219_165118.webm](https://github.com/LawnchairLauncher/lawnchair/assets/4998824/82772a6c-c643-4133-be80-ac5c4721216b)

### Device information

App version: 14 Dev (#200)

Same on two devices tested:

Device 1:
- Device: Medium Phone, Android Studio emulator
- OS: Android 14 ("UpsideDownCake") x86_64 (Google Play)

Device 2:
- Device: POCO F5
- OS: Android 13 (MIUI Global 14.0.9)

**Comment by gaussandhisgun** [comment]
can confirm on my miatoll running android 14. to note: using the gesture does let you close the keyboard.

**Comment by MrSluffy** [comment]
Fixed 1aaaa2fbb2e16ee492c8091fcaa334eb6f230c15
