### ISSUE TITLE
Changing grid only applies to page 1

### ISSUE THREAD

**Issue by baruchin** [Deletescape-Media/Lawnchair#39]
When changing grid size (columns or rows) the change is only visible in page 1 of homescreen, instead of all pages.
When changing grid size (let's say to 5 columns), the date widget scales down to that grid, like the image below. Am I doing something wrong?
![screenshot_20170626-115351](https://user-images.githubusercontent.com/3922419/27554010-49eeec28-5a6a-11e7-817b-334e2116c8c5.png)

**Comment by deletescape** [comment]
Probably an issue I haven't noticed yet, thanks for the report

**Comment by baruchin** [comment]
This seems to be fixed in latest release, isn't it?

**Comment by deletescape** [comment]
@baruchin I don't know, didn't really change anything but if it works now you can close this issue

**Comment by baruchin** [comment]
Yes, it works now. Hope doesn't get broken for next release. In the mean time, I'll close this issue.
