### ISSUE TITLE
Search bar voice icon tweak and Google Maps&Chrome Shortcuts Backport

### ISSUE THREAD

**Issue by mydarknight** [Deletescape-Media/Lawnchair#390]
Some countries and regions can not use Google assistant now, so I think it is useful to and an option to provide voice icon selection.

Backport Shortcuts feature don't work for maps and chrome due to limitations, so I think special tweaks of these two or more apps is useful for users without 7.1+.

**Comment by suphon-t** [comment]
Maps and Chrome uses 7.1 shortcut API so it won't be added.
