### ISSUE TITLE
[FEATURE] or [BUG] Support for Foldable Devices Missing...

### ISSUE THREAD

**Issue by orionbg** [Deletescape-Media/Lawnchair#3901]
### Describe the feature

Hello Dev team,
It appears that support for Foldable devices is gone in the Launchair 14 Dev builds (i tested build 215).
In the officially available Launchair version, the app can distinguish between the two screens and allow setting app grids, icon sizes, wallpapers for both separately but in the 14 dev build no such options.

### Why would it be useful to add?

So that people using foldable devices would also benefit from one of the best Android launchers out there.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

You can probably get the code needed from the Pixel launcher v14.

**Comment by ciferkey** [comment]
I am still interested in this feature.

**Comment by DHernan** [comment]
Still want as well. Wonder why it got taken out

**Comment by MrSluffy** [comment]
Check lawnchair 16
