### ISSUE TITLE
[BUG] Top Shadow Enables Itself

### ISSUE THREAD

**Issue by Alpointernet** [Deletescape-Media/Lawnchair#3904]
### Describe the bug

When you disable the top shadow, it does come back after some time.

### Steps to reproduce

1. Go to 'Launcher Settings'
2. Click on 'Home Settings'
3. Disable 'Top Shadow'
4. After some time, the shadow comes again
5. See error

### Expected behavior

It should stay disabled when you disable it.

### Device information

- Device: [Galaxy A54]
- OS: [OneUI 6 Android 14]
- App version: [14 dev 215]

### Additional context

When the top shadow enables itself again, it doesnt turn on itself on the settings menu. Its disabled on the settings but its actually enabled.

**Comment by thatAkiraFox** [comment]
I have further info about this.

Lawnchair 14 dev build `#262`, the shadow re-appears when interacting with the drawer: opening and closing the drawer or even slightly pulling up the dock and releasing it makes the shadow appear, even if (as said by @Alpointernet) the toggle in the settings remains unchanged.

Android 13, LineageOS 20 (so no QuickSwitch).
