### ISSUE TITLE
Lawnchair 818 release not working with Redmi 4

### ISSUE THREAD

**Issue by manoj1983** [Deletescape-Media/Lawnchair#391]
Hello,

Latest release 818 is not working with Redmi 4 mobiles phones and gets crashed. Tried in several handsets. Please have a look.

**Comment by thecipherman** [comment]
It's working for me

**Comment by CreativeUsern** [comment]
Not working for me either on my nexus 5x w\ lineage.

**Comment by aadhithyasekar** [comment]
It's crashing whenever I open it. -Moto X Play

**Comment by pjtsearch** [comment]
It happens on my LG V20 whenever I restart the phone.  I have to delete the app and the app and then reinstall the app.

**Comment by CreativeUsern** [comment]
Do any of you have dark mode or blur on? those seemed to be what broke it for me.

**Comment by pjtsearch** [comment]
No, I don't

**Comment by intelligentcasanova** [comment]
Please try to install the latest release: https://github.com/Deletescape-Media/Lawnchair/releases/tag/1.0.1063 and see if the crashes still occur.

**Comment by manoj1983** [comment]
Yes, it is working great with no issues at all, just ocassionally restarts.

**Comment by pjtsearch** [comment]
Now it works perfectly! Thanks Deletescape!

**Comment by intelligentcasanova** [comment]
Can this issue now be closed? @manoj1983 @deletescape

**Comment by manoj1983** [comment]
Thanks a lot @deletescape, this issue should be closed now.
