### ISSUE TITLE
[FEATURE] Ability to Set Dock Spacing When Search Widget Hidden

### ISSUE THREAD

**Issue by FordCorn** [Deletescape-Media/Lawnchair#3910]
### Describe the feature

This feature was a default thing in Lawnchair 12.1, you had the ability to hide the search and it would somewhat keep some the spacing from when the search bar was there. It would be nice to have this ability in Lawnchair 14 aswell, currently it behaves by shoving the dock and all the icons right to the bottom of the screen screwing with any muscle memory I had before.

### Why would it be useful to add?

Having the option for the dock to be a certain distance away from the bottom of the screen when disabling the search widget would be a nice addition.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

**Lawnchair 12.1 | Search Widget Disabled**
![Screenshot_20231222-164337](https://github.com/LawnchairLauncher/lawnchair/assets/63467807/80f76333-1844-4d74-8817-2fff40990326)

**Lawnchair 14 | Search Widget Disabled**
![Screenshot_20231222-164339](https://github.com/LawnchairLauncher/lawnchair/assets/63467807/ebc7a6d0-a78f-476c-9546-8ab33b0ebb72)

**Comment by RouxTheCaster** [comment]
Hey sorry to bother, what's the name of the widget that you're using in that screenshot?
