### ISSUE TITLE
[BUG] - Improve Icons Adaptive check

### ISSUE THREAD

**Issue by binoysankar** [Deletescape-Media/Lawnchair#3911]
### Describe the bug

Default icons for Teams and Amazon Music looks pretty good as shown below and when i enable the auto adaptive icons these 2 icons are considered non-adaptive icons and converts to adaptive icons which IMO should not be. PFB images with and without adaptive icons enabled.
Another example is between the Amazon siblings as shown below. They have the same icon layout but when enabling auto adaptive icons option in LC only one is considered non adaptive.

### Steps to reproduce

1. Go to 'Home Settings' and enabled 'Auto Adaptive Icons' option.
2. Go to Home screen or App drawer and notice the difference before and after enabling the above option.

### Expected behavior

I know this is because of the icons which doesn't support adaptive feature. But if Lawnchair can improve the check for certain apps like i mentioned above would be great.

### Screenshots

![Screenshot_20231223-060832](https://github.com/LawnchairLauncher/lawnchair/assets/10673905/3b70643f-41ae-45e8-ab55-44c0494236be)
![Screenshot_20231223-060752](https://github.com/LawnchairLauncher/lawnchair/assets/10673905/dc36ace4-8497-471b-a3b1-4aa9c5ee2608)
![Screenshot_20231222-220935](https://github.com/LawnchairLauncher/lawnchair/assets/10673905/c6626fb6-ece3-4977-9fef-60dd6afecc4c)
![Screenshot_20231222-220833](https://github.com/LawnchairLauncher/lawnchair/assets/10673905/9505b7c6-679a-4ebf-8415-07294c59084e)

### Device information

- Device: [Google Pixel 7
Pro]
- OS: [Stock ROM Android version 14]
- App version: [A14 dev test builds]

**Comment by Gravarty** [comment]
Still happening in the beta version of Lawnchair.

**Comment by DancingEmptier667** [comment]
Can confirm that it's still happening on the latest nightly build
