### ISSUE TITLE
[FEATURE] Search bar coloring issue 

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#3913]
### Describe the feature

It's darker then the themed icons 

### Why would it be useful to add?

When I'm using dark a wallpaper I barely can see it.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20231223_180009_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/45660e31-3d77-4fcc-a2f2-f09a76f0edae)
 
![Screenshot_20231223_180026_One UI Home](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/4563d866-6b35-406e-bb5d-680c0bfcbbe3)

### Additional context

It might not be the best feature but... thanks

**Comment by gaussandhisgun** [comment]
isn't it supposed to be a [BUG] if its an *issue*?

**Comment by RouxTheCaster** [comment]
> isn't it supposed to be a [BUG] if its an _issue_?

Whatever it is 🫤

**Comment by MrSluffy** [comment]
duplicate 
- #3680

**Comment by KTibow** [comment]
@MrSluffy if this is a duplicate then you should close it as "not planned" and mark it as a official duplicate
