### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gurmeetim** [Deletescape-Media/Lawnchair#3917]
### Describe the bug

Lawnchair crashed when adding widget to homescreen

### Steps to reproduce

Try settings the widget on homescreen lawnchair crashed immediately

### Expected behavior

Lawnchair should not crash

### Device information

- Device: [ Samsung A50]
- OS: [stock ROM Android Version 11]
- App version: [14 Dev (#1)]

### Additional context

Lawnchair bug report 26 Dec 2023 8:40:51 am version: 14 Dev (#1) (14) commit: 6414751 build.brand: samsung build.device: a50 build.display: RP1A.200720.012.A505FDDS9CWA2 build.fingerprint: samsung/a50dd/a50:11/RP1A.200720.012/A505FDDS9CWA2:user/release-keys build.hardware: exynos9610 build.id: RP1A.200720.012 build.manufacturer: samsung build.model: SM-A505F build.security.level: 2023-01-01 build.product: a50dd build.type: user version.codename: REL version.incremental: A505FDDS9CWA2 version.release: 11 version.sdk_int: 30 display.density_dpi: 420 isRecentsEnabled: false error: Uncaught exception java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference 	at com.android.launcher3.Launcher.completeAddAppWidget(Unknown Source:18) 	at com.android.launcher3.Launcher.lambda$completeTwoStageWidgetDrop$4(Unknown Source:1) 	at com.android.launcher3.Launcher.o(Unknown Source:0) 	at com.android.launcher3.a1.run(Unknown Source:8) 	at com.android.launcher3.Workspace$5.run(Unknown Source:12) 	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2) 	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554) 	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301) 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086) 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146) 	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37) 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54) 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008) 	at android.view.Choreographer.doCallbacks(Choreographer.java:809) 	at android.view.Choreographer.doFrame(Choreographer.java:740) 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995) 	at android.os.Handler.handleCallback(Handler.java:938) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:246) 	at android.app.ActivityThread.main(ActivityThread.java:8653) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by MoTheAmazing** [comment]
I have the same issue. Android 13 one ui 5.1

**Comment by Alpointernet** [comment]
You can try that if you dont want it to crash when adding widget:

Make your default launcher another launcher, add/edit your widget, then make lawnchair default again.

**Comment by MoTheAmazing** [comment]
That works thank you.
