### ISSUE TITLE
[BUG] App drawer is empty

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3920]
### Describe the bug

Installing the latest debug build causes search results and app drawer to be empty for some reason

### Steps to reproduce

1. Go to 'App drawer'
2. See error

### Expected behavior

Icons are supposed to load and search results should not be empty

### Device information

- Device: [Teclast T40 pro]
- OS: [Android version 12.0]
- App version: [Lawnchair 14 dev]

### Additional context

![Screenshot_20231227-201308](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/126efa00-a3f0-41e1-a6a0-f205e3234668)

**Comment by MrSluffy** [comment]
Enable bulk or disable web suggestion fix the issue

**Comment by SeanDylan** [comment]
> Enable bulk or disable web suggestion fix the issue

It does not work other debug builds don't have this issue

**Comment by MrSluffy** [comment]
> > Enable bulk or disable web suggestion fix the issue
> 
> It does not work other debug builds don't have this issue

What version? It's been a while no changes in search result

**Comment by SeanDylan** [comment]
I figured out it actually happens when you set the app drawer padding to 1% and higher
I am not sure why this happened and i'm really confused

**Comment by SeanDylan** [comment]
> > > Enable bulk or disable web suggestion fix the issue
> > 
> > 
> > It does not work other debug builds don't have this issue
> 
> What version? It's been a while no changes in search result

Any version with the padding feature for the app drawer

**Comment by MrSluffy** [comment]
> > > > Enable bulk or disable web suggestion fix the issue
> > > 
> > > 
> > > It does not work other debug builds don't have this issue
> > 
> > 
> > What version? It's been a while no changes in search result
> 
> Any version with the padding feature for the app drawer

Ok create separate issue, and make sure title is accurate like "Padding causing empty drawer if Greater than 1% or higher in big device" etc
