### ISSUE TITLE
[BUG] Padding in app drawer greater than 1% in big screen devices causes empty app drawer

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3921]
### Describe the bug

This is almost a same issue as my closed issue but the explanation was more away from the padding of the app drawer i realize that the padding from the app drawer that is greater than 1% can cause the apps and search results to disappear

### Steps to reproduce

1. Go to 'launcher settings'
2. Click on 'app drawer'
3. Scroll down to 'padding'
4. Set it more than 1%
5. See error

### Expected behavior

Apps and search results should show normally

### Screenshots

![Screenshot_20231227-201308](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/60f04142-f58c-4d7b-94d6-1136e20a19ee)

### Device information

- Device: [Teclast T40 pro (may happen with big screen devices)]
- OS: [Android version 12.0+]
- App version: [Lawnchair 14 dev]

### Additional context

There's also a bug where when reaching 2% padding almost no icons will appear at all just the scrolling

**Comment by SeanDylan** [comment]
This did not fix it only thing that it did is it disappears when it set on 2% setting it on 3% causes it to do the same thing probably even with a fixed for this it just could be from 4%

**Comment by SeanDylan** [comment]
![Screenshot_20231229-141304](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/0c2ee597-a789-404c-b306-b22182c0a103)
This is what i mean this is set to 10% for example and setting it to 3% will cause the same thing it needs to be optimized for big screen devices fully

**Comment by MrSluffy** [comment]
> ![Screenshot_20231229-141304](https://private-user-images.githubusercontent.com/104182251/293317881-0c2ee597-a789-404c-b306-b22182c0a103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzEyMjksIm5iZiI6MTcwMzgzMDkyOSwicGF0aCI6Ii8xMDQxODIyNTEvMjkzMzE3ODgxLTBjMmVlNTk3LWE3ODktNDA0Yy1iMzA2LWIyMjE4MmMwYTEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNjIyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGYxNGRmZThkNWU0MzVhYWU3OTc5YzcxZmVhMzA5ZjA3NWNmYzFhNjM2M2VlZGI5YmFmM2VhMjM1YTMxYzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bKDCI_kTWi1KUbej5fssLw-W_DQJKnXquCAHXPbuAUY) This is what i mean this is set to 10% for example and setting it to 3% will cause the same thing it needs to be optimized for big screen devices fully

Have you tried clean install?
