### ISSUE TITLE
[BUG] setting app drawer padding to more than 2% still causes empty app drawer

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3927]
### Describe the bug

Technically it is another issue of the same report but the pull request didn't help it instead it just made it so that 3% will give a empty app drawer

### Steps to reproduce

1. Go to launcher settings
2. Select app drawer
3. Set padding to more than 2%

### Expected behavior

Drawer is not empty

### Screenshots

![Screenshot_20231229-141304](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/494e84c6-473a-4a8a-a233-97c7a7c2b420)
This is a same screenshot from my other issue but however it's still happens

### Device information

- Device: [Teclast T40 pro]
- OS: [Android version 12.0]
- App version: [14 dev]

### Additional context

Setting it to three won't really help with it

**Comment by MrSluffy** [comment]
What debug version # you using?

**Comment by MrSluffy** [comment]
Fixed f792ed7aae75d7f81d7dd28d5cf3d926a85b8788

**Comment by SeanDylan** [comment]
It's working now and the padding is working as it should now there's no reason to do a 200 thanks
