### ISSUE TITLE
[BUG] Smartspacer not showing correctly when dock is enabled

### ISSUE THREAD

**Issue by greed-d** [Deletescape-Media/Lawnchair#3933]
### Describe the bug

When you have no dock Smartspacer shows correctly but when I enable dock the Smartspacer has wrong padding and words get cut off

### Steps to reproduce

1. Go to 'Home setting'
2. Click on 'Dock'
3. Select a dock provider
4. Go to Home screen to see the error

### Expected behavior

Smartspacer shows correctly 

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/58597122/2ec0c9b3-bf54-4d8d-b885-8fd0f0f5d643

### Device information

- Device: POCO F3[alioth]
- OS: GhostOS [Lineage based AOSP ROM](Android 14)
- App version: v14 Dev (215)

**Comment by MrSluffy** [comment]
is this exists in latest # 257? https://github.com/LawnchairLauncher/lawnchair/actions/runs/7381643722

**Comment by MrSluffy** [comment]
https://github.com/LawnchairLauncher/lawnchair/assets/36076410/cc4565c3-fb87-4c6a-ae7a-f6a46733152b

Fixed in latest debug
