### ISSUE TITLE
[BUG] Label size is not respected in folders

### ISSUE THREAD

**Issue by theLee3** [Deletescape-Media/Lawnchair#3936]
### Describe the bug

Adjustments to the label size are not used in folders.

### Steps to reproduce

1. Go to 'Home Settings > Home Screen'
2. Scroll down to 'Icons'
3. Set 'Label Size` to anything other than 100%
4. Create a folder (or check a pre-existing folder)
5. See that label sizes do not match that of apps on Home Screen

### Expected behavior

Label sizes of apps in folder should match that of label sizes on Home Screen or have a separate label/icon size setting under 'Home Settings > Folders'.

### Device information

- Device: [Google Pixel 7 Pro]
- OS: [stock ROM Android version 14]
- App version: [12.1.0 Alpha 4 & 14-dev]

**Comment by MrSluffy** [comment]
![BeFunky-collage (4)](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/253e0cf1-4ca4-4176-bd42-50505bf8be6f)
- Done 1c44d0310e62dc6d727933ad642ac040e522e770
