### ISSUE TITLE
[ENHANCEMENT] Dock bar animation crop App -> Home

### ISSUE THREAD

**Issue by twoone-3** [Deletescape-Media/Lawnchair#3939]
### Describe the bug

I'm using a third version of lawnchair https://github.com/Goooler/LawnchairRelease, and I have reported this problem to the author but the author said it is a problem with the upstream repo.

https://github.com/LawnchairLauncher/lawnchair/assets/62778573/f632ed0f-b73e-48d2-80a8-3c5e126ba72a

Like in the video, using gestures to return to the desktop will make the dock icon look bad. In addition, I am using quick switch 3.3.1 as my software to switch recents.

### Steps to reproduce

It has been explained above

### Expected behavior

When I return to the desktop, the icon in the dock bar will be missing the upper part.

### Device information

- Device: POCO F5
- OS: Aospa uvite Android version 14
- App version: 14.0.0 (third version)

### Additional context

I clearly know that I am using a third-party version, but when I reported it to the third-party author, he said it was an upstream issue, so please don't close this issue directly, maybe it's just a Quick Switch compatibility issue

**Comment by MrSluffy** [comment]
This is expected behavior if the app to home swipe is high if normal swipe this is unnoticeable remember launcher3 doesnt comes with searchbar dock.

**Comment by twoone-3** [comment]
> This is expected behavior if the app to home swipe is high if normal swipe this is unnoticeable remember launcher3 doesnt comes with searchbar dock.


https://github.com/LawnchairLauncher/lawnchair/assets/62778573/6e34b916-1a63-4157-aedf-7150f112720d

oh I update quick switch to 3.3.7 and download a ci version of lawnchair, just like your said, the faster I swipe, the more animation is noticeable
