### ISSUE TITLE
[BUG] Search bar is annoying to use

### ISSUE THREAD

**Issue by KTibow** [Deletescape-Media/Lawnchair#3944]
### Describe the bug

The app drawer search bar is much harder to use in Lawnchair 14.
When you type something, it takes 500ms for it to redisplay the results.
Even if you turn off web suggestions, there is no way to remove the "search on startpage" or "search on play store" entries.
When you delete your search query, the keyboard automatically closes for no good reason. This behavior *still* persists even if you have "automatically show keyboard" on.
It's possible to get into a out-of-sync state where even when you deleted your search query, the keyboard is still open, and it only shows results from your search query.

### Steps to reproduce

1. Install Lawnchair 14
2. Flick up to open app drawer
3. Tap search bar
4. Experience bad things

### Expected behavior

It should have an experience that's the same or better than in Lawnchair 12. Improve the logic for the search input to fix keyboard input, fix the app list to not get out of sync, make the search process faster, and allow all extra entries to be disabled.

### Device information

- Device: OnePlus 7 Pro
- OS: OxygenOS 12
- App version: 14

**Comment by MrSluffy** [comment]
Disable web suggestion

**Comment by ThatOneCalculator** [comment]
You can disable startpage suggestions, which helps a lot with speed 

![Screenshot_20240107-131755.png](https://github.com/LawnchairLauncher/lawnchair/assets/44733677/aa187704-d5df-4d40-a525-c0b327ac1b31)

**Comment by Striffly** [comment]
```
Even if you turn off web suggestions, there is no way to remove the "search on startpage" or "search on play store" entries.
When you delete your search query, the keyboard automatically closes for no good reason. This behavior still persists even if you have "automatically show keyboard" on.
It's possible to get into a out-of-sync state where even when you deleted your search query, the keyboard is still open, and it only shows results from your search query.
```

I have all these issues too

**Comment by Striffly** [comment]
Why close it ? The issues seems relevant to be fixed

**Comment by Striffly** [comment]
Thanks for the update
However, there's still one problem among those mentioned above :
```
Even if you turn off web suggestions, there is no way to remove the "search on startpage" or "search on play store" entries.
```
Can you solve it too?

Thank you

**Comment by MrSluffy** [comment]
There's nothing to solve since there's no option/not implemented

**Comment by KTibow** [comment]
> There's nothing to solve since there's no option/not implemented

I can't tell if you're saying that there is no "search on [startpage/play store]" suggestion or if you're just saying that "solve" is the wrong word. The point of that request is that there should be an option to disable those suggestions.

**Comment by manavkulshrestha** [comment]
Is there a fix for the keyboard close when removing a query. It's insanely annoying
