### ISSUE TITLE
[BUG] Pixel 6a freezes when swiping from one screen to another

### ISSUE THREAD

**Issue by lailung** [Deletescape-Media/Lawnchair#3951]
### Describe the bug

I am using Pixel 6a on Android 14.
The phone frequently freezes when i change from one screen to another. The workaround then is to put the phone into standby mode and reactivate again. Sometimes it then flipps to the screen i tried to go before it froze.
This can also happen within an app, but less frequent.
I uninstalled lawnchair and reinstalled it to experience less frequent freezes than before, but it still happens.

### Steps to reproduce

1. Use one homescreen
2. Try to move to another
3. Phone freezes and no manipulation is possible without standby and reactivation

### Expected behavior

I would expect a clean move from one screen to another, or clean handling of apps.

### Device information

- Device: Google Pixel 6a
- OS: Android 14 after Dec23 security update
- App version:

**Comment by MrSluffy** [comment]
Please specify lawnchair version

**Comment by lailung** [comment]
I am in Lawnchair version 2.0-2589

Thank you

**Comment by MrSluffy** [comment]
please use latest nightly if still persists reopen this issue
