### ISSUE TITLE
[BUG] Blurring application windows in the recent list

### ISSUE THREAD

**Issue by bnhlll** [Deletescape-Media/Lawnchair#3962]
### Describe the bug

Under certain conditions, blur extends to windows

### Steps to reproduce

Launcher settings ->
recent ->
enable translucent background->
Go to recent and watch

### Expected behavior

No blur effect on windows

### Screenshots

![Screenshot_20240112-130354_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/57818513/b903323e-44f1-41e4-b8be-1ca2112f8863)
![Screenshot_20240112-130400_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/57818513/99905325-bbce-496b-9ba5-a14dcc1f0448)
![Screenshot_20240112-130405_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/57818513/c95bd8b4-e333-4b7e-bce5-d0c1f2548d3f)

### Device information

- Device: [Oneplus9]
- OS: [custom ROM Android version 13.0]
- App version: [14 dev]

**Comment by pacjo** [comment]
Even though I appreciate opening the issue, searching isn't that hard. [#2762](https://github.com/LawnchairLauncher/lawnchair/issues/2762)

**Comment by gaussandhisgun** [comment]
yeah, except that one was *fixed* in lawnchair 12, and 14 dev uses a different base, so it is yet to be fixed *there*

**Comment by pacjo** [comment]
I don't know. For me it's a regression and instead of creating a new issue, that one should be reopened.

Since this one is already opened and that one doesn't look like it will be, we can left this situation as is.

**Comment by MrSluffy** [comment]
fixed 30f77e5f434b8a637664e6aec6419e57f8522137
