### ISSUE TITLE
Search bar App drawer

### ISSUE THREAD

**Issue by TataEverywere** [Deletescape-Media/Lawnchair#3965]
### Describe the feature

Make search bar on app drawer following search bar on homescreen

### Why would it be useful to add?

Because to make more look tidy and also pixelize looks

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20230824-210632_Pixel Launcher](https://github.com/LawnchairLauncher/lawnchair/assets/87556077/69beea46-46e0-4cf8-b423-16c40eeb8e8d)

**Comment by MrSluffy** [comment]
Closed duplicate
- #3924

**Comment by Debjit-007** [comment]
Have we have this ?
So why the hell you closeed it ?

**Comment by MrSluffy** [comment]
> Have we have this ? So why the hell you closeed it ?

Can't you read? It's duplicated issue
