### ISSUE TITLE
[FEATURE] updating the search bar colors

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#3966]
### Describe the feature

Currently in dark mode search bar color is N1-900 but it should be N1-800

### Why would it be useful to add?

When using a dark wallpaper it almost disappears :(

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20240102-001808](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/cd95dd72-d39b-4ae7-9a71-1f47ad283228)
 
![Screenshot_20240113_115736_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/7cfa1745-ae38-400d-9fc1-7dd8812c2306)

### Additional context

I appreciate your work.

**Comment by CommanderRaiker** [comment]
Hello, I don't like the last changes on the search bar background. Now it's a way to bright. 

It's not easy to find the best color. Depending on the background, it may or may not look good.

I think the background of the search bar should go with Google Pixel default launcher or fit with the pixel widget backgrounds (clock, calendar, weather,...)

**Comment by RouxTheCaster** [comment]
> Hello, I don't like the last changes on the search bar background. Now it's a way to bright.
> 
> It's not easy to find the best color. Depending on the background, it may or may not look good.
> 
> I think the background of the search bar should go with Google Pixel default launcher or fit with the pixel widget backgrounds (clock, calendar, weather,...)

It's doesn't work like this, clock and weather widgets are different colors and original pixels don't have that type of coloring on the search bar.
