### ISSUE TITLE
951 - Cannot switch weather provider

### ISSUE THREAD

**Issue by RWOne** [Deletescape-Media/Lawnchair#397]
In 950, change was to add Google API key, on 951, but weather provider still greyed out. Am I missing something else I have to enable elsewhere?

Also 951, question, nice catch on refresh rate, is 30 min the default on Pixel as well, or less? Just asking ...

**Comment by nyancrimew** [comment]
Enable Location access for Lawnchair, to allow switching between providers.

On the Pixel launcher the weather is refreshed by the Google app, I don't know what the refresh rate is there

**Comment by RWOne** [comment]
Ahh Till, sorry, it's early morning here, just did that ☺️ and was posting to close when you did ...
