### ISSUE TITLE
[FEATURE] app drawer google search bar 

### ISSUE THREAD

**Issue by ArturMartic** [Deletescape-Media/Lawnchair#3975]
### Describe the feature

please add google search bar on app drawer

### Why would it be useful to add?

it looks clean and looks like pixelize

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![IMG_20240116_180515_730](https://github.com/LawnchairLauncher/lawnchair/assets/152477013/e092ac50-be07-499b-8f81-d37d8f55b7ee)

**Comment by RouxTheCaster** [comment]
That'd be a great feature, current one looks outdated tbh.

**Comment by MrSluffy** [comment]
- #3959
- #3924

**Comment by Debjit-007** [comment]
Yaa that search bar will be great current one is actually not that much good it really looks like shit

**Comment by Americapax** [comment]
Yes

**Comment by MrSluffy** [comment]
already added in latest nightly
