### ISSUE TITLE
[FEATURE] Horizontal View for app drawer

### ISSUE THREAD

**Issue by gurmeetim** [Deletescape-Media/Lawnchair#3981]
### Describe the feature

Horizontal View for drawer like Microsoft launcher with dots indicator at the bottom

### Why would it be useful to add?

It will be usefull for all users.With vertical scroll users have to continue scroll the list and  has to see the screen to locate the diserable app.With horizontal view apps open in blocks like in 4×5grid mean 20 apps in one page(block).Only swip once and locate desirable app with less screen time.specifically who has samsung devices with horizontal view app drawer and Microsoft launcher user can shift to lawnchair  launcher

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://drive.google.com/file/d/1-Y4UAmSKCVD7X-HIBd5ZYGXXe4CL13Tm/view?usp=drivesdk

### Additional context

It will be valuable addition for lawnchair

**Comment by gurmeetim** [comment]
Devs should look into this.

**Comment by imsys** [comment]
This is the main thing keeping me on nova

**Comment by gurmeetim** [comment]
Devs shoild look into this feature.it will be beneficial for all users

**Comment by gurmeetim** [comment]
Devs should look into this feature.it will be beneficial for all users

**Comment by imsys** [comment]
Closed as complete? I just installed the nightly build and couldn't find it.

**Comment by gurmeetim** [comment]
> Closed as complete? I just installed the nightly build and couldn't find it.

I made a new request .please upvote and comment this request:-https://github.com/LawnchairLauncher/lawnchair/issues/5135#issuecomment-2571520241
