### ISSUE TITLE
[BUG] Artifacts around the icons when going back to the home screen

### ISSUE THREAD

**Issue by gfandrea** [Deletescape-Media/Lawnchair#3983]
### Describe the bug

When I go back to the home screen there are some artifact around the icon.
The artifacts are there with every icon pack and also in Nova launcher and Niagara Launcher

The artifacts are NOT there with an icon dimension of 130% and up

### Steps to reproduce

1. open an app from an icon in the home screen
2. Close it with a swipe
3. the icon should animate going back to the original position without showing artifact

### Expected behavior

No artifacts around the icons

### Screenshots

![screen-20240118-155833_exported_4530](https://github.com/LawnchairLauncher/lawnchair/assets/34663993/b2ee5051-d0f5-4d1c-ae4c-518edc6a4740)

### Device information

- Google Pixel 8
- OS: Android 14 qpr2 beta
- App version: Debug 14 dev 336

**Comment by Laurenzana** [comment]
For me, the artifacts are still there above 130%

**Comment by foXaCe** [comment]
Good morning
I also have a pixel 8 and the same problem

**Comment by Pyntux** [comment]
Only when 1-3 icons are in folder, everything is OK, 4 and more icons, there are visual glitches....

 I am using Pixel 8 with lattest Gooler build...

**Comment by iamtiagodev** [comment]
Is there any update on this? 🤔 Workarounds are also appreciated!

If I disable animations (phone settings) I no longer see the artefacts, however, I would like do disable just this animation and not all of them, otherwise it affects the overall experience of the device.

**Comment by Pyntux** [comment]
I found that problems with this does not exists when using 3 button navigation. So there is problem only when using gestures navigation...

**Comment by znbaboy** [comment]
this does NOT occur when setting Lawnchair as the "recents provider" using quickswitch

**Comment by Pyntux** [comment]
> this does NOT occur when setting Lawnchair as the "recents provider" using quickswitch

So we need to root our phones to use quickswitch, if I am right? :) 

Maybe this is important information on the way to solving the error, but it is not a solution to the problem IMHO....

**Comment by znbaboy** [comment]
> > this does NOT occur when setting Lawnchair as the "recents provider" using quickswitch
> 
> So we need to root our phones to use quickswitch, if I am right? :)
> 
> Maybe this is important information on the way to solving the error, but it is not a solution to the problem IMHO....

yeah, pretty sure it only works on rooted phones. Its not worth it though. The Lawnchair recents is very buggy and slow

**Comment by herbanonymous** [comment]
Phone: Pixel 7 (Manufactured 2022)
Android: 14 (Build AP2A.240905.003)
Lawnchair: 14 (Beta 3)
![Screenshot_20240912-205121](https://github.com/user-attachments/assets/29b0541f-2304-431b-9e41-ae3eae4430ca)

**Comment by MrSluffy** [comment]
fixed in `15-dev`
