### ISSUE TITLE
Google weather api

### ISSUE THREAD

**Issue by ellenswamy** [Deletescape-Media/Lawnchair#399]
The Google weather API is working, but it does not seem to be updating once it grabs the temperature.

**Comment by RWOne** [comment]
I hesitantly post to agree.
If I leave the phone alone for over 30 minutes to an hour, opening, the widget is the same, toggling to calendar and back it remains the same, though a check of my GNow feed, or pressing to get to the weather page, shows the weather and updates in some cases, but the widget remains at what it was.

I know this is large feature to integrate, I'm also not sure if, we use the Google API to blank out the city field, or leave it with a country code and city. I'm patient enough to wait as you awesome dev's look at it, or educate us as to usage, etc.

I think that the overall app development has been fantastic!  My hope is, that if there are still issues implementing it, those can be overcome ...

**Comment by hassie-dash** [comment]
The Google Weather API does not use the Google app but instead uses the Awareness Api which is done via Google Play services. This data is cached for around 3 hours by the API or until the temperature changes by 3 degrees, before new weather data is downloaded.

This API also does not allow manual location entry, it only works by using your GPS to get the location. 

The actual Google Weather API is not available for public use unless the package name is changed to the Pixel Launcher.

The devs won't be able to do anything about this until Google changes how the API works or by making the retrieval of weather data from the Google app public. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment]
@hassie-dash, Thank you for the detailed explanation!

I did some research myself and see where Google killed access to the API directly, they whacked a lot of third party apps back then due to that, sigh ...

Thanks for being patient and indulgent, now that we know the score, we'll just have to buck up and live with the best implementation you guys can give us.  :)

**Comment by ghost** [comment]
The weather did not auto-update after 8 hours and a change in temperature by 10 degrees.

**Comment by gedoor** [comment]
@hassie-dash Change the package name to Pixel Launcher. Can I automatically update the weather?

**Comment by hassie-dash** [comment]
@gedoor Changing the package name now wouldn't work, because the devs have removed the Google Weather implementation as part of cleanup. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ellenswamy** [comment]
Since the API no longer works, can weather.com be added as a source? That is what Google uses anyways

**Comment by nyancrimew** [comment]
@ellenswamy weather.com has no public api. Google Awareness API has been added as an alternative provider, this should provide results which are

1. Location based
2. Accurate
3. Pretty similar to the values displayed inside Google Now

**Comment by RWOne** [comment]
I think it's like what I posted in the community thread, OCD - one opens weather an you want it all to be synched right then and there,but we'll have to accept things as they are...

It's still the best launcher out there.  :)

**Comment by hassie-dash** [comment]
Weather.com instead teamed up with Weather Underground to form the Weather Underground API. From experience, this is accurate and has native support for party/mostly cloudy/sunny weather conditions.

The only downside is that you get 500 free calls, unlike OWM which provides 50,000.

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ivancuric** [comment]
IBM bought both of them recently. They have their own api now: https://console.bluemix.net/docs/services/Weather/index.html

**Comment by nyancrimew** [comment]
@ivancuric if you feel like paying for this expensive as hell api for us, feel fre :joy:

**Comment by ivancuric** [comment]
Whoah sorry! Didn't check the price!

**Comment by ghost** [comment]
I recommend you to add Weather Underground, is the better weather provider in my opinion.
Thanks for your app!
