### ISSUE TITLE
[FEATURE] Yandex search in dock-panel search-widget

### ISSUE THREAD

**Issue by Rail-TH** [Deletescape-Media/Lawnchair#3992]
### Describe the feature

There are quite a large number of people in the CIS who use the Yandex search engine, so I consider its addition to the search widget in the dock bar a necessity
![photo_2024-01-21_20-28-08](https://github.com/LawnchairLauncher/lawnchair/assets/100100752/5bf3365b-3302-4f5a-a3dd-13f9321f01ff)
![photo_2024-01-21_20-28-06](https://github.com/LawnchairLauncher/lawnchair/assets/100100752/549759fe-7d7d-436d-b24f-cdeabd485c7f)

### Why would it be useful to add?

1. More options in choosing a search engine
2. I'll be glad and give you a hug
3. Яндекс очень распространённая поисковая система, и этот факт заставляет задуматься

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![photo_2024-01-21_20-33-50](https://github.com/LawnchairLauncher/lawnchair/assets/100100752/f685b1a5-9e05-4ab2-a8ef-d3f28ff8cf69)

**Comment by bnhlll** [comment]
The developer should know that this search engine is distributed only in Russia

**Comment by Rail-TH** [comment]
> The developer should know that this search engine is distributed only in Russia

At first: not only in Russia

At second: This does not negate the fact that there is a huge number of users using this search engine. If Google was created in the USA, it does not mean that it is distribyted only in the USA

**Comment by Username1-a** [comment]
In general, an option for adding custom search engine URL (like in many browsers out there) would be much appreciated, so that user could use the desirable search engine that isn't available from the git-go
