### ISSUE TITLE
[FEATURE] Add support for changing the search bar in the dock with a widget

### ISSUE THREAD

**Issue by eldonita** [Deletescape-Media/Lawnchair#3996]
### Describe the feature

As the title says I would like to have the possibility to change the search bar on the dock with a custom widget like the ones from pix material you light/dark like the image in the example

### Why would it be useful to add?

It would add more customisation options

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![IMG_20240122_104545_089](https://github.com/LawnchairLauncher/lawnchair/assets/121272988/564c9594-2970-47ea-9d32-f82feb57f511)

**Comment by SuperDragonXD** [comment]
Duplicate of #3029
