### ISSUE TITLE
[BUG] Lawnchair 12.1.0 Alpha 4 crash every time the phone charge reach 100%

### ISSUE THREAD

**Issue by ale5000-git** [Deletescape-Media/Lawnchair#3999]
### Describe the bug

Lawnchair 12.1.0 Alpha 4 on HUAWEI P20 Lite crash every time the phone charge reach 100%.

[Lawnchair bug report 18 gen 2024 21 54 33.txt](https://github.com/LawnchairLauncher/lawnchair/files/14024739/Lawnchair.bug.report.18.gen.2024.21.54.33.txt)

### Steps to reproduce

1. Charge the phone to 100%.
4. See the error

### Expected behavior

No crash

### Device information

- Device: HUAWEI P20 Lite
- OS: stock ROM Android version 9
- App version: 12.1.0 Alpha 4

**Comment by ale5000-git** [comment]
@MrSluffy
It is the latest that I found in the release section on GitHub.

**Comment by MrSluffy** [comment]
> @MrSluffy It is the latest that I found in the release section on GitHub.

Please read label description Thanks 👍

**Comment by ale5000-git** [comment]
Is there any plan to have automated releases from current/active branch?

**Comment by MrSluffy** [comment]
use latest lawnchair 14
