### ISSUE TITLE
[BUG] Unable to open app drawer or homescreen app

### ISSUE THREAD

**Issue by PerzonPL** [Deletescape-Media/Lawnchair#4000]
### Describe the bug

On Pixel 7 with latest version od app, sometimes i cant open app drawer on home screen or open any app from homescreen - no response when i select anything. I need to lock and unlock my phone and then it works fine

### Steps to reproduce

Close any app and go to home screen, and try to open app drawer or run any app from homescreen

### Expected behavior

I want to be able to use homescreen apps at all

### Device information

Google Pixel 7, stock android 14, 12.1.0 Alpha 4

**Comment by MrSluffy** [comment]
use latest lawnchair 14
