### ISSUE TITLE
Hide System Clock When On Home Screen

### ISSUE THREAD

**Issue by FernFranc** [Deletescape-Media/Lawnchair#4002]
### Describe the feature

It would basically be an option in Lawnchair's settings to hide the system clock. The feature can only show up when rooted or when Lawnchair is granted the necessary adb permissions.

(adb shell pm grant "lawnchair_package_name" android.permission.WRITE_SECURE_SETTINGS)

### Why would it be useful to add?

It would replace the redundancy of having the time being shown in the status bar and the built in At a Glance widget.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![IMG_20240123_210503](https://github.com/LawnchairLauncher/lawnchair/assets/81488600/7565d7a5-9bd5-4429-9c1b-479382456fe6)

**Comment by MrSluffy** [comment]
closes : 34db5dd80140862e313482a3eb2df1cf5fb1cd3c
