### ISSUE TITLE
Top screen got grey out in app drawer when scroll down

### ISSUE THREAD

**Issue by chanh2018** [Deletescape-Media/Lawnchair#4011]
### Describe the bug

In app drawer with transparent, when scroll down the top part of screen got grey or dark

### Steps to reproduce

1. Go to app drawer
2. Scroll down
3. Top part of screen got grey

### Expected behavior

It should be no grey section anywhere in screen if transparent was set in app drawer

### Screenshots

![Screenshot_20240125-060546_Lawnchair_1](https://github.com/LawnchairLauncher/lawnchair/assets/65605997/efa5aa86-2cf5-4ef4-8c0b-4851a9a19308)

### Device information

- Device: Pixel 4A 5G
- OS: Android 14 stock rom
- App version: Lawnchair 14 debug version CI#379

**Comment by rsnnn** [comment]
Same happening here, Lineage 19
