### ISSUE TITLE
Artifacts around icon when closing app

### ISSUE THREAD

**Issue by Laurenzana** [Deletescape-Media/Lawnchair#4020]
### Describe the bug

There are usually visual artifacts around an icon when closing any app, these usually take the form of yellow colored lines or dots surrounding the icon.

### Steps to reproduce

1. Close an app
2. See artifacts

### Expected behavior

1. Close an app
2. Not see artifacts

### Screenshots

[
![Screenshot_20240126-205023](https://github.com/LawnchairLauncher/lawnchair/assets/89566262/d2eda6fd-fe39-45bc-8aba-abf3ce9527e9)
](url)

### Device information

- Device: Google Pixel 8
- OS: Stock ROM Android 14
- App version: Lawnchair 14 Dev (#406) market

**Comment by MrSluffy** [comment]
#3983

**Comment by MrSluffy** [comment]
duplicate : #3983
