### ISSUE TITLE
Returning to home screen animations

### ISSUE THREAD

**Issue by FL4R3ZZZ** [Deletescape-Media/Lawnchair#4022]
### Describe the feature

Returning to home screen animations for users without quickswich

### Why would it be useful to add?

Improve user experience for non rooted users

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Only while returning to the home screen
 
https://github.com/LawnchairLauncher/lawnchair/assets/155435187/c23e4985-3c1a-48e2-b342-108fdc7d7385

**Comment by FL4R3ZZZ** [comment]
I ment no in the lawnchair 2 question

**Comment by SuperDragonXD** [comment]
This feature is already implemented in Lawnchair *development* builds via the `GestureNavContract` api. Note that it only works in Android 11 and above, and may also not work for all devices — if it doesn't animate in your device, I'm afraid it doesn't support it. There's no other way to have these without that api (or via QuickSwitch, which requires root).

As such, this issue will be closed.
