### ISSUE TITLE
[BUG] Search Bar placeholder not hidden 

### ISSUE THREAD

**Issue by Morjacmd** [Deletescape-Media/Lawnchair#4024]
### Describe the bug

When I hide the search bar in the drawer, there is still a block in this place and it is not hidden.

### Expected behavior

Hide this block when I hide the search bar.

### Screenshots

![Screenshot_20240128-091044_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/22863466/35c7156e-6877-4048-ad0c-0518296bd807)

### Device information

- Device: Google Pixel 6
- OS: Android 14 
- App version: 14 Dev

**Comment by MrSluffy** [comment]
Duplicate : #4011
