### ISSUE TITLE
[BUG] Tap Recents button but back to home screen

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#4025]
### Describe the bug

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/3c6a98ed-3793-4b3b-a61b-4b29d08e5f7d

### Steps to reproduce

1. Open an app
2. Click Recents button.
3. Back to home screen as you see.

### Expected behavior

This is a regression from #3948.

### Device information

- Device: Moto X40
- OS: A14
- App version: b585d3fa64d370c942ebccdb86400d1dd3b93d26

**Comment by MrSluffy** [comment]
https://github.com/LawnchairLauncher/lawnchair/assets/36076410/98e982c8-229b-4c04-ba4d-c80dedf547ce

I can't reproduce this

**Comment by Goooler** [comment]
It's a little random.

**Comment by Goooler** [comment]
Seems this has gone on the latest build.
