### ISSUE TITLE
[BUG] latest cl version is always crashing using github folder and the settings for market is crashing

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#4029]
### Describe the bug

After adding widget transitions the launcher is crashing using the market will work but opening settings is crashing it too

### Steps to reproduce

1. Go to 'Lawnchair'
2. See error

### Expected behavior

Settings in market is opening properly and and github the launcher is working properly

### Device information

- Device: [Teclast T40 pro]
- OS: [Android version 12.0]
- App version: [CL up to adding widget transitions]

### Additional context

https://katb.in/relurehohig
https://katb.in/tizijikijez
https://katb.in/gehimozuzaj

**Comment by MrSluffy** [comment]
done : 38ace537d49ef2be89dc7d91376fa6eb5ecd7406
