### ISSUE TITLE
Widget sheet not respecting custom theme/font

### ISSUE THREAD

**Issue by SuperDragonXD** [Deletescape-Media/Lawnchair#4032]
### Describe the bug

The widget picker bottom sheet does not respect the custom accent color and custom fony provided by Lawnchair.

### Steps to reproduce

1. Change Accent Color to something else
2. Change font (`fontHeading` and related, Debug Menu) to something else
3. Open widget picker sheet

### Expected behavior

The widget sheet should respect the custom colors and fonts provided

### Screenshots

![Screenshot_2024-01-30-16-27-47-35_ddf77c0951adecdce93c9ca870602d33](https://github.com/LawnchairLauncher/lawnchair/assets/70206496/70a811bd-a3cf-4eb0-93a5-8965c3c4646d)

### Device information

- Device: Oppo F9
- OS: ColorOS 7 (Android 10)
- App version: Lawnchair Dev `#436`

### Additional context

#3766 is a related issue, although it is already fixed. This is also likely broken by the Android `14` merge.

(Also there are some parts in the Launcher3 UI that are not themed by Lawnchair's custom colorings.)

**Comment by MrSluffy** [comment]
- Close : f686b13f8b629be9f90805a2f1f02bd7e24aa8fc
