### ISSUE TITLE
[BUG] Dock icons get cut off while going home when search bar is disabled

### ISSUE THREAD

**Issue by redline-soee** [Deletescape-Media/Lawnchair#4037]
### Describe the bug

When swiping to go home the top of the icons in the dock gets cut off during the animation, if the search bar is disabled. 

https://github.com/LawnchairLauncher/lawnchair/assets/25106499/9c80c3f0-29c9-442d-b1a2-0bdfd850b98f

### Steps to reproduce

1. Go to Lawnchair dock settings and disable the search bar
2. From any app swipe up to go home
3. See error in the animation 

### Expected behavior

Expected behavior is showing full icons

### Screenshots

![Screenshot_20240131-122118_Nagram](https://github.com/LawnchairLauncher/lawnchair/assets/25106499/632f2395-a89c-480c-94f4-56895b105f1b)

### Device information

- Device: [Redmi Note 10 Pro]
- OS: [stock ROM Android version 14.0]
- App version: [e.g. 14.0.0 (88e7000)]

**Comment by MrSluffy** [comment]
Fixed 61055a67854bc44ea8f0e41d5d90137aa78597fa
