### ISSUE TITLE
[BUG] Double-click Recents button, black screen shows when switching APPs 

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#4045]
### Describe the bug

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/0186b8b4-a5c6-4cce-8f28-0f5e0b831b8b

### Steps to reproduce

1. Open the first app.
2. Open the second app.
3. Double-click Recents button.

### Expected behavior

No black screens.

### Device information

- Device: Moto X40
- OS: A14
- App version: f72919cf35890528dead3b7b5c99f2c3a74f4e12

**Comment by MrSluffy** [comment]
I can't reproduce this

**Comment by Goooler** [comment]
Have you set LC as the QS provider?

**Comment by harmit03** [comment]
Black screen  also appears with gesture navigations. In 5 home swipes there is one occurence where the app exits but home screen never shows up and sticks to black screen.

Also latest lawnchair 14 behaves irregularly when opening wallpaper and styles app.

A13, Lineage OS, Lawnchair is the quickswitch provider

**Comment by Goooler** [comment]
Seems this has gone with the latest build.

**Comment by harmit03** [comment]
Where can i get the latest build? (Haven't seen any lawnchair 14 release since a month)

**Comment by Goooler** [comment]
You can try out https://github.com/Goooler/LawnchairRelease/releases

**Comment by harmit03** [comment]
The latest build 

> You can try out https://github.com/Goooler/LawnchairRelease/releases

The lateat build still has the black screen issue, it is present even in geature navigations.
Around every 8 home swipe you get one black screen when yhe aops don't show up.

(Using on A13, LineageOS)

**Comment by Goooler** [comment]
You can download it from https://github.com/Goooler/LawnchairRelease/actions/runs/8019597485, I'll draft a new release in days.
