### ISSUE TITLE
[BUG] lawnchair setting force close on open

### ISSUE THREAD

**Issue by gfandrea** [Deletescape-Media/Lawnchair#4052]
### Describe the bug

when I open the setting via long press on the home screen, the setting page open, but force close immediatly
I have tryed to uninstall and reinstall lawnchair

PS: I have the same problem with the latest Goooler version (just installed)
[Lawnchair (Debug) bug report 6 feb 2024 065656.txt](https://github.com/LawnchairLauncher/lawnchair/files/14176510/Lawnchair.Debug.bug.report.6.feb.2024.065656.txt)

### Steps to reproduce

1. long press on the home screen
2. Click on setting
3. the setting page will open
4. the setting page will close

### Expected behavior

I should be able to open the app setting

### Device information

- Device: Google PIxel 8
- OS: Android 14 qpr2 beta
- App version: dev 450

**Comment by MrSluffy** [comment]
This is problem from the fork not here, I just check, gooler tried to migrate android to androidx.

**Comment by gfandrea** [comment]
Sorry, but I have the same problem on the official dev build 450
I installed the goooler version just to check if was working on that version.

**Comment by MrSluffy** [comment]
I'm using a14 and work's fine
