### ISSUE TITLE
[BUG] Weather not visible in At a Glance widget with Assistant off, visible on lockscreen

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4053]
### Describe the bug

Weather is missing/not visible in At a Glance widget with Assistant off.
Feature is enabled in both Lawnchair's settings and At a Glance/Assistant's settings.
It's visible and correctly showing location and weather data on lockscreen, Google app is updated too.

### Steps to reproduce

1. Disable Assistant (I mean completely turn off in Assistant's settings)
2. Weather missing/not visible

### Expected behavior

Weather is visible and correctly showing location and weather data on lockscreen, should be on homescreen too.

### Device information

- Device: [Google Pixel 8]
- OS: [stock ROM Android version 14.0]
- App version: [Goooler's latest release]

**Comment by MrSluffy** [comment]
Weather in at glance is tied google if you disable it weather too. Close this as not plan or create new issue something like add other weather provider source etc.

**Comment by MrSluffy** [comment]
Weather in at glance is tied google if you disable it and so the weather too. Close this as not plan or create new issue something like add other weather provider source etc.

**Comment by ghost** [comment]
Hi
Could you please explain why it's working on lockscreen but not on homescreen?

**Comment by ghost** [comment]
@MrSluffy @Goooler please re-open the issue.
This problem is present and it's a Lawnchair's issue as I just set the stock launcher and, with Google Assistant OFF, weather IS PRESENT on homescreen too.
This has nothing to do with Google Assistant being disabled, it's a Lawnchair's issue.

**Comment by MrSluffy** [comment]
> @MrSluffy @Goooler please re-open the issue. This problem is present and it's a Lawnchair's issue as I just set the stock launcher and, with Google Assistant OFF, weather IS PRESENT on homescreen too. This has nothing to do with Google Assistant being disabled, it's a Lawnchair's issue.

Try adding google widget in homescreen, the weather is hook from Google Widget you can just check the code https://github.com/LawnchairLauncher/lawnchair/blob/cbc67cdf2832e2ebdccb82020aac69f92cc2b3ba/lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt

**Comment by MrSluffy** [comment]
https://github.com/LawnchairLauncher/lawnchair/assets/36076410/def7ece0-7fac-4cf7-8a34-4a4b9bede321

**Comment by ghost** [comment]
![Screenshot_20240308-075618~2](https://github.com/LawnchairLauncher/lawnchair/assets/88372360/16bc648f-a644-495b-a9f4-277429ccf609)
![Screenshot_20240308-075630~2](https://github.com/LawnchairLauncher/lawnchair/assets/88372360/17d63d01-2550-400f-ad25-47420684d43a)
![Screenshot_20240308-075634~2](https://github.com/LawnchairLauncher/lawnchair/assets/88372360/62506957-129f-4783-b607-8e70a12289af)
![Screenshot_20240308-075651~2](https://github.com/LawnchairLauncher/lawnchair/assets/88372360/a10b17c3-b1a1-49b6-8ea9-94cd73cd98b7)
These are the Assistant settings, disabled under both Assistant's general settings and system settings.

I tried adding the google widget but, it's not the at a glance (has different appearance) and lawnchair crashes and doesn't add it to the homescreen.

I'm using latest goooler release.

EDIT: I wasn't using the latest googler release, now I'm on the latest and I can add Google widget without crashing but it shows "Assistant disabled".
Stock At a Glance widget on stock launcher (the one you can't remove) shows weather just fine and also opens weather app fine, location is fine too.

**Comment by ghost** [comment]
Hi again @MrSluffy
Please check my updated answer above.

**Comment by guniens** [comment]
Hi @MrSluffy 

Why has this been closed?
I've the same issue as OP, Google Assistant on or off and weather SHOWS correctly on Pixel launcher while ISN'T SHOWN in Lawnchair.

Please fix this or at least give us an option to use a third party weather provider.

Thanks in advance!
