### ISSUE TITLE
Animated clock icon sync error?

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#406]
I think it's one hour back... 
![](http://i.imgur.com/Kg7iSiS.jpg)
 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment]
Agreed, at first I thought it wasn't moving at all, I installed near the top of the hour, but the hour hand was still near the previous one. (3 versus nearer to 4, and didn't "jump" to 4 on the hour change).

I apologise, for it being 4am, I need to go unconscious again, so I can't wait long enough to confirm if my hour hand is moving at all here, when I wake I'll recheck. 😉

**Comment by suphon-t** [comment]
Should be solved now.
