### ISSUE TITLE
Wrong Norwegian language code

### ISSUE THREAD

**Issue by olafapl** [Deletescape-Media/Lawnchair#407]
It seems like the language code used for the Norwegian translations are wrong. The language code in use is "no-rNO" – it should be "nb-NO", "nb", or just "no". I'm guessing this might have something to do with some Crowdin configuration?

**Comment by nyancrimew** [comment]
no-rNO is correct, this is the way it is written on Android (also there is a version of just no), the r in no-rNO stands for region, so this would mean **no**rwegian from **r**egion **NO**rway

**Comment by olafapl** [comment]
Oh, my bad. I haven't worked too much with Android locales (or Android at all). However, I cannot seem to make the translations -- Norwegian translations, exclusively -- come into play on any device I've tried. This, coupled with my limited research on Android locales, made me think there was something going on with the language code. There could be something going on on my end, although I'm not sure what that might be ... Thanks, though.

**Comment by nyancrimew** [comment]
I'm not sure how much of the Translations for Norwegian are imported into the app already, this could also be the source of your issu

**Comment by olafapl** [comment]
I forgot to mention that I've tried inspecting the apk (latest from [https://lawnchairmirror.duckdns.org](https://lawnchairmirror.duckdns.org)), and the values-no-rNO directory does contain a translated strings.xml file.

**Comment by olafapl** [comment]
I took a closer look, and you're clearly right – not all translations are imported into the values-no-rNO directory. Ha ha, oh well ... Appreciate you work, man!
