### ISSUE TITLE
[FEATURE] Pixel like search bar in drawer 

### ISSUE THREAD

**Issue by Debjit-007** [Deletescape-Media/Lawnchair#4075]
### Describe the feature

![IMG_20240215_100329_098](https://github.com/LawnchairLauncher/lawnchair/assets/119999168/3fdc4a8c-094e-48b7-aac4-bd248699febf)
Pixel phone use this search bar form Android 12 but lawncher has disconnected it after lawncher 10 so please bring it back 🙏🏻🙏🏻🙏🏻 

### Why would it be useful to add?

It will be useful just because you can actually search via pixel search or via YouTube search or bing and it will be more close to pixel launcher 

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Uploading Screenshot_20240215-100930.png…]()

### Additional context

And please add option to change the search provider so that we can actually change whatever we want we can actually search for apps or we can actually search in Bing or we can search in YouTube etc

**Comment by MrSluffy** [comment]
Duplicate #3924

**Comment by RouxTheCaster** [comment]
> Duplicate #3924

At least is there any plans for that feature?
