### ISSUE TITLE
[BUG] landscape mode

### ISSUE THREAD

**Issue by Pauloesfola** [Deletescape-Media/Lawnchair#4079]
### Describe the bug

Can you adjust APP drawer to full size of the screen when in landscape mode?
![Screenshot_20240216-232230](https://github.com/LawnchairLauncher/lawnchair/assets/158363132/124f17ad-ca21-4e64-a99a-a5e52b23a47c)

### Expected behavior

Full size APP drawer

### Screenshots

![Screenshot_20240216-232230](https://github.com/LawnchairLauncher/lawnchair/assets/158363132/9028c0f0-bd25-44e9-9323-245a3b5ed17c)

### Device information

- Device: Google pixel 7
- OS: Android version 14
- App version: 14

**Comment by MrSluffy** [comment]
Duplicate #4065
