### ISSUE TITLE
Lawnchair Version 12.1.0 Alpha 4 Crash and Not Responding

### ISSUE THREAD

**Issue by MuditJadhhav** [Deletescape-Media/Lawnchair#4083]
### Describe the bug

I was on Instagram and just closed the app to return to the home screen when I got an error from Android in a pop-up telling Lawnchair isn't responding. It just gave the option to close Laawnchair and then to select a default home launcher app. I chose the Moto Home App. But I found that my official phone launcher was now weird and it was looking very different from which I set it to when I last time left it before installing Lawnchair. I had to readjust every app. I had installed and applied Lawnicons too, but the original Moto icon arrangement was not good when I switched back. Like the horizontal alignment of the icons was not proper. I had to reboot my phone and the rebooting took longer than usual. I got a notification from Lawnchair telling that it had some crash and gave an error code and an option to upload crash report. However, when I uploaded the crash report it showed fail and I was retrying even though it was failing (no network issue). Now I have uninstalled Lawnchair and Lawnicons and the system is working fine.

### Expected behavior

These types of crashes have occurred before too however during that time I used to get an option to "Wait" until Lawnchair responds and it used to work well after that.

### Screenshots

I couldn't get a screenshot.

### Device information

- Device: Motorola E32s
- OS: My UX Android Version 12
- App version:12.1.0 Alpha 4
- System specifications: 3 GB RAM, 32 GB ROM, 6.50-inch (720x1600), MediaTek Helio G37, 5000mAh

**Comment by MrSluffy** [comment]
use latest lawnchair 14
