### ISSUE TITLE
[BUG] Contact search card

### ISSUE THREAD

**Issue by spottech** [Deletescape-Media/Lawnchair#4087]
### Describe the bug

When you click on the search result to send an SMS or make a call directly from the card, the call remains on the keypad without a number and the SMS sets the recipient to "0" or creates a conversation with no recipient

⚠️ Only with contact lists other than Google's

### Steps to reproduce

1. Go to 'search bar ans search contact'
2. Click on 'Call or sms'
3. See error

### Expected behavior

*

### Screenshots

![Screenshot_20240221-142624](https://github.com/LawnchairLauncher/lawnchair/assets/13060777/8014e349-fc34-4505-b96e-7d66bc3a4ebb)
![Screenshot_20240221-142624](https://github.com/LawnchairLauncher/lawnchair/assets/13060777/f6087a20-e8c2-4131-a316-2974504c784d)
![Screenshot_20240221-142736](https://github.com/LawnchairLauncher/lawnchair/assets/13060777/c8428c4c-e2c8-49f5-97c2-69fb9c797a50)

### Device information

- Device: Google Pixel 7
- OS: stock ROM Android version 14.0
- App version: 14 Dev 513

**Comment by MrSluffy** [comment]
That your contact has phone number or not? I'm on A14 and it's working
