### ISSUE TITLE
[BUG] Folder Artifacting

### ISSUE THREAD

**Issue by znbaboy** [Deletescape-Media/Lawnchair#4092]
### Describe the bug

Artifacting around folders after closing out of an app opened from within the folder

![Screenshot_20240220-134835_Lawnchair~2](https://github.com/LawnchairLauncher/lawnchair/assets/52028136/900b3afb-b99b-4fa6-a9f6-8f312e7456b4)

### Steps to reproduce

1. Launch app from folder on home screen 
2. Close out of app going back to home screen 

### Expected behavior

Shouldn't be any artificing

### Device information

Device: Pixel 7 Pro
OS: LineageOS 20 (February 13th build)
Lawnchair version: 14.0.0-20240203

**Comment by MrSluffy** [comment]
I'm on los too never faced this, please use latest debug

**Comment by znbaboy** [comment]
This is already on the latest version off Googlers fork which seems to already be the latest debug?

**Comment by upbox-org** [comment]
It's an old bug which is tracked here: #3983 
Close this please.
