### ISSUE TITLE
[BUG] Keyboard disappears after removing last character in app drawer search

### ISSUE THREAD

**Issue by D3SOX** [Deletescape-Media/Lawnchair#4095]
### Describe the bug

Keyboard disappears after deleting last character in app drawer search. This is a major UX flaw when you need to fix a typo. It only happens when you've already had put text in there before.

### Steps to reproduce

1. Enable in app drawer settings
   * show search bar
   * automatically show keyboard (optionally for this)
3. Open app drawer
4. Type something in the search bar
5. Remove it until the input is empty

### Expected behavior

Keyboard stays

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/24937357/c5052393-0c3a-4dc9-8e00-afe9f6b151ff

### Device information

- Device: Google Pixel 8 Pro
- OS: CalyxOS 5.4.0
- App version: Debug artifact from 74fac1db6027fedeae23c477dad2bd033ac30634

### Additional context

Happens in my case with [FlorisBoard](https://github.com/florisboard/florisboard/)

**Comment by sarojpanda44** [comment]
Same issue with Gboard.

**Comment by daniel4911** [comment]
Same issue with sam keyboard.

**Comment by D3SOX** [comment]
Fix doesn't seem to work for me. One time it worked but now it's hiding the keyboard again

**Comment by D3SOX** [comment]
Still happening with the latest build from `14-dev` branch as of now (commit 5677ec6e794a9a3ecf1ea6fe54ddefcaaa429d33). Additionally it fails to open the keyboard when trying to open the app drawer it really fast after swiping up to go to the homescreen. Please reopen

**Comment by D3SOX** [comment]
Can somebody please at least reopen this issue for tracking? I can try to resolve it myself in the next days ^^

**Comment by kymerea** [comment]
Bump

**Comment by D3SOX** [comment]
I tried to compile Lawnchair btw but I failed so sadly this is still an issue

**Comment by kymerea** [comment]
Can anyone else try and fix this? Its fairly annoying and I have no knowledge on his to code android apps so I couldn't fix it myself

**Comment by sarojpanda44** [comment]
Tested and working in dev version #1014. Great fix!

**Comment by D3SOX** [comment]
Yup works great for me too thanks a lot for fixing

**Comment by kymerea** [comment]
Can also confirm that it's working, thank you so much for solving this issue, can't want for the next beta release (I know I can use dev, I choose not to)
