### ISSUE TITLE
At a glance cropped for Smartspacer

### ISSUE THREAD

**Issue by sarojpanda44** [Deletescape-Media/Lawnchair#4096]
### Describe the bug

I'm using Smartspacer as At a glance provider and the Smartspacer is cropped on each side. In version #314 the margin crop was minor (ignorable) but in version #450 it's too much cropped.

Difference is the Pixel launcher home screen grid is 5x5 and in Lawnchair the home screen grid is 5x6.

It is fixed if I change the grid to 5x5 but I prefer to have more rows and want the At a glance not to be impacted regardless of the grid size.

![Screenshot_20240226-135638](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/e28425fc-f8dc-4df7-a242-95b58ca13396)

### Steps to reproduce

1. Install and configure Smartspacer.
2. In the Home screen option change the layout grid to 5x5
3. In the Lawnchair experimental features enable "At a glance provider selection"
4. Go to At a glance and enable "Show on Home Screen”
5. Below that click the option and change the provider to Smartspacer.
5. Check the At a glance content.
6. Go back to Lawnchair home screen option and change layout grid to 5x6.

7. Come back to the home screen and verify the Smartspacer contents.

### Expected behavior

Irrespective of changing the home screen grid size, the Smartspacer At a glance contents on the sides should not be cropped. It doesn't crop contents for default Lawnchair At a glance.

### Device information

- Device: Google Pixel 7 Pro
- OS: stock ROM Android version 14.0
- App version: 14 Dev 314

**Comment by st0neh** [comment]
The at a glance should really be separate from the grid setting. If you set the grid setting too high the at a glance is TINY lol.

**Comment by ghost** [comment]
Not fixed in Lawnchair 14 Beta 1.

**Comment by NiXTheDev** [comment]
This became way worse in Lawnchair 14 beta 2
![Screenshot_20240403-172245.png](https://github.com/LawnchairLauncher/lawnchair/assets/105677206/c8dcff70-e88c-4cb1-bf2b-e54e21a27c24)

(Beta 1 screenshot for example:)
![Screenshot_20240403-163008_Lawnchair.png](https://github.com/LawnchairLauncher/lawnchair/assets/105677206/ccfa17a3-4105-47c7-98b5-19b0bf6f113f)

**Comment by 88572** [comment]
Latest Smartspacer update does not help.

**Comment by ghost** [comment]
> Latest Smartspacer update does not help. 

It's most likely related to Lawnchair's padding, not Smartspacer. Lawnchair 12 has it all fine.

**Comment by slogar25** [comment]
Fixed on grids up to 6x7 on debug version #729
6x8 grid still cropped off screen

**Comment by sarojpanda44** [comment]
Not sure which phone you are using. But it's not working for me on my Pixel 7 Pro on Dev #729.
![Screenshot_20240411-094156](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/b85c5877-8cc0-4c30-a75a-22ea4b0a4cbe)

**Comment by slogar25** [comment]
> Not sure which phone you are using. But it's not working for me on my Pixel 7 Pro on Dev #729. ![Screenshot_20240411-094156](https://private-user-images.githubusercontent.com/27029904/321527967-b85c5877-8cc0-4c30-a75a-22ea4b0a4cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDUwMDAsIm5iZiI6MTcxMjg0NDcwMCwicGF0aCI6Ii8yNzAyOTkwNC8zMjE1Mjc5NjctYjg1YzU4NzctOGNjMC00YzMwLWE3NWEtMjJlYTRiMGE0Y2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE0MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMzRiY2JkOWExN2IxOGRhZTk0OGNmOTIwMzVjNGVjZmQzN2MyYTc3OTI1NmJlOWQzODJhMTEwNTQ3N2I2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53h0wQqxdkblTHEP4ActXLbgg0J076RoZ8-YCtjx4K8)


Im on Pixel 8 Pro. Working on 6x7 grid
![Screenshot_20240411-100817](https://github.com/LawnchairLauncher/lawnchair/assets/4675147/51953f1c-e386-42b4-bd8f-52eabb82affd)

**Comment by sarojpanda44** [comment]
I was playing around with more settings and did some restarts. Somehow is fixed note for me. Guess is fixed. Just need a fresh configuration.
![Screenshot_20240413-201007](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/9220c529-a540-4595-8d34-453b315f1bf1)

**Comment by sarojpanda44** [comment]
So now I know. I reduced the Dock Bottom padding from 100 to 80 and it fixed the Smartspacer padding issue.
It is working for you because you are not using Dock

**Comment by ujwal246** [comment]
> Not sure which phone you are using. But it's not working for me on my Pixel 7 Pro on Dev #729. ![Screenshot_20240411-094156](https://private-user-images.githubusercontent.com/27029904/321527967-b85c5877-8cc0-4c30-a75a-22ea4b0a4cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTk0MTMsIm5iZiI6MTcxMzg5OTExMywicGF0aCI6Ii8yNzAyOTkwNC8zMjE1Mjc5NjctYjg1YzU4NzctOGNjMC00YzMwLWE3NWEtMjJlYTRiMGE0Y2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE5MDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjllYjNjODEzZjlhYmE1M2YwMDcxMjE0OGQ5ZjJkNTEyMDc0Y2UyMmEzODRkMWU4Y2NlNTBiMDIzZGU0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKB0IUTY271krANvl7LKoDVZ4jGpvDciiUYkXnAy2aw)

(Offtopic) What app you used for pixel clock font widget?

**Comment by sarojpanda44** [comment]
It's kwgt widget. 
Write me on Telegram @sarojpanda44 for the kwgt export.

**Comment by MrDodojo** [comment]
3x3 grid
Unihertz jelly (star)
![Screenshot_20240428-135851](https://github.com/LawnchairLauncher/lawnchair/assets/47711280/6c96fdc4-b546-4a00-82e3-e8dc93153a52)
![Screenshot_20240428-140105](https://github.com/LawnchairLauncher/lawnchair/assets/47711280/2c3156de-d7dd-46de-9af8-2145ef665e41)
Only happens to the smartspacer one. Does get fixed when changing minimum width to 360 instead of 320, but then the rest of the phone becomes unusable.

**Comment by CoelacanthusHex** [comment]
Only 5x6 grid works on my device..。

**Comment by MrDodojo** [comment]
@SuperDragonXD, this issue is still present. 
![Screenshot_20240819-150000~2](https://github.com/user-attachments/assets/a11e17ba-2756-4405-8096-ae6e0c6c2d19)

**Comment by SuperDragonXD** [comment]
Are you using the Nightly versions?

**Comment by MrDodojo** [comment]
Called lawn chair (debug) right? I got the one from releases with the
commits from 2 days ago. I do have A very small screen(unihertz jelly)

**Comment by SuperDragonXD** [comment]
Could you try testing the latest nightly release to see if it fixes the issue?

**Comment by MrDodojo** [comment]
Still an issue

**Comment by TarsiSurdi** [comment]
This bug is not fixed, just installed Lawnchair on my Samsung phone and the Smartspacer at a glance content was cropped with no way to adjust padding :(
