### ISSUE TITLE
Excessive Battery Drain with Nexus 5X Android DP4 (O)

### ISSUE THREAD

**Issue by Pedro1999** [Deletescape-Media/Lawnchair#410]
Consumption up to 500 mAh and even more.

It happen with all the versions I've tried, 818 and up, last one V.1.0.984.

It's a shame because I really like this Launcher, but with this battery drain it is impossible to have it installed.

**Comment by Dondrejohnson5** [comment]
Same here.
Don't forget RAM usage. Mine for Lawnchair is about 100-130 MB. That's a problem for a phone with only 1 GB of RAM.

**Comment by Pedro1999** [comment]
Yes, of course, but in my case the most important thing is the excessive battery drainage.

I really like this Launcher, but if they do not solve this problem I will have no other option than to uninstall it since this battery consumption is inadmissible.

**Comment by suphon-t** [comment]
From screenshots I've seen,  CPU time on both foreground and background is really low and if CPU time is low, battery consumption should be low too.  It's possible that the calculations are incorrect because you are running a prerelease OS.

**Comment by iH8c0ff33** [comment]
@paphonb That's probably it, I'm getting 38% reported from OS (actually never checked before) but accubattery reports 1.4%. My SoT didn't change since I installed lawnchair, so I think that's just a problem with DP4 reporting wrong percentage.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Pedro1999** [comment]
Hi, @paphonb 

If all of the applications that I have installed (and come preinstalled) in my phone work correctly (all of them) and the battery percentage is also normal, and the only one that does not work correctly is this Launcher. ¿Where do you think the problem comes from, is the OS or this application? Personally I think it's the Lawnchair app that does not work properly with Android 8.0, or at least not on the Nexus 5X with Android 8.0.

**Comment by suphon-t** [comment]
@Pedro1999 Can you post a screenshot of detailed usage in settings?

**Comment by Pedro1999** [comment]
@paphonb Yes os course. With a total battery consumption of only 33% this application has already consumed 206mAh.
![01](https://user-images.githubusercontent.com/30476929/29029886-7e4f3a1e-7b89-11e7-8d02-b75e8320b1a6.jpg)
![02](https://user-images.githubusercontent.com/30476929/29029890-7f65951a-7b89-11e7-9d26-74592cbcb531.jpg)
![03](https://user-images.githubusercontent.com/30476929/29029887-7e501bfa-7b89-11e7-89fe-62a2bda7952f.jpg)
![04](https://user-images.githubusercontent.com/30476929/29029888-7e52c7a6-7b89-11e7-876b-4bf07de09092.jpg)

**Comment by iH8c0ff33** [comment]
@paphonb I have only 6min of active usage and 0min of background, still it says 331mAh, which I think is impossible with so little usage. While battery usage of telegram is really low even though active usage is 39mins (96mAh).


![Lawnchair](http://i.imgur.com/M6BSFYK.png)

![Telegram](http://i.imgur.com/oSKF1K4.png)

![AccuBattery](http://i.imgur.com/noGaTVR.png)


_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
If CPU usage is low and real battery life is not changed, that means the calculations are incorrect.

**Comment by dimitrovmaksim** [comment]
Same here, 21% in the stock battery monitor, 0.8% in GSam. But to be fair i don't feel an impact on the SOT
![screenshot_20170808-071726](https://user-images.githubusercontent.com/20456492/29056254-4fbc74d8-7c0a-11e7-9197-ce30dac9f03d.png)
![screenshot_20170808-071808](https://user-images.githubusercontent.com/20456492/29056255-4fbd6668-7c0a-11e7-9fc8-a25dbceb3de0.png)

**Comment by Pedro1999** [comment]
Hi, @paphonb 

I installed an App (GSam Battery) to control this issue and see if Lawnchair has an excessive consumption, or if with Android does not indicate well the battery consumption.

What I say again is that it is strange that it is only this application that gives problems with the % of battery.

Anyway, thank you very much for your time.

**Comment by suphon-t** [comment]
No matter if it's the only app or not. If there is no impact then it's the OS' fault.
