### ISSUE TITLE
Fix the at a glance padding for smart spacer provider 

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4103]
### Describe the feature

As of writing this, the latest development version is #570 on Lawnchair 14, but the feature still isn't added.
Usually, when using the normal at a glance provider on Lawnchair, it's more centered. That isn't the case for smart spacer.

### Why would it be useful to add?

Smartspacer would feel more native with the padding, not too much to the sides.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Smart spacer's padding
![1000004045](https://github.com/LawnchairLauncher/lawnchair/assets/147082067/f3540464-02ea-4c26-979a-b7bb425096c3)
Lawnchair's padding
![1000004044](https://github.com/LawnchairLauncher/lawnchair/assets/147082067/84086413-1042-4eda-bbb3-fc9199c7905e)

Request: make padding for both the same

**Comment by RouxTheCaster** [comment]
Not just smartspacer but all of the widgets have this problem.

**Comment by ghost** [comment]
> Not just smartspacer but all of the widgets have this problem.

Seems to be so, I guess?

I've also tested this on Lawnchair 12, and the smart spacer worked beautifully with good padding.
![1000004056.jpg](https://github.com/LawnchairLauncher/lawnchair/assets/147082067/459ad1c2-5a6c-4834-bdfe-49604fd8a0c1)

So it's also only a dev version issue.

**Comment by sarojpanda44** [comment]
I have also created a bug for it.

https://github.com/LawnchairLauncher/lawnchair/issues/4096#issue-2154161035
