### ISSUE TITLE
[BUG] Crash when opening home settings of lawnchair

### ISSUE THREAD

**Issue by shailantani** [Deletescape-Media/Lawnchair#4106]
### Describe the bug

I'm running the latest debug version of lawnchair, and its crashing whenever I open the home settings and try scrolling on the settings page.

### Steps to reproduce

1. Long press on home screen
2. Click on home settings button
3. Scroll on the page or wait for around 4-5 seconds

### Expected behavior

The home settings page is supposed to scroll but instead the app freezes and eventually crashes, without scrolling

### Device information

- Device: Google Pixel 7a
- OS: stock ROM Android version 14.0 qpr 3 beta 1
- App version: 14 Dev (debug)

### Additional context

Heres the crash report:

Lawnchair (Debug) bug report 03-Mar-2024 4:04:09 pm
version: 14 Dev (#573) (14)
commit: b377784
build.brand: google
build.device: lynx
build.display: AP21.240119.009
build.fingerprint: google/lynx_beta/lynx:14/AP21.240119.009/11395453:user/release-keys
build.hardware: lynx
build.id: AP21.240119.009
build.manufacturer: Google
build.model: Pixel 7a
build.security.level: 2024-02-05
build.product: lynx_beta
build.type: user
version.codename: REL
version.incremental: 11395453
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.IllegalStateException: scroll observation scope does not exist
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.checkForContentCapturePropertyChanges(AndroidContentCaptureManager.android.kt:332)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.contentCaptureChangeChecker$lambda$0(AndroidContentCaptureManager.android.kt:145)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager.$r8$lambda$1XDFQ87DMU0Pr1CSBqiV4PdF6bM(Unknown Source:0)
	at androidx.compose.ui.contentcapture.AndroidContentCaptureManager$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8516)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by SuperDragonXD** [comment]
Hey there,

Thanks for bringing this to our attention. It seems like there's [an issue with Pixel devices](https://issuetracker.google.com/issues/325667060) on Android 14. While it's fixed internally at Google, it's not yet available to the public. As a result, we may need to delay merging the Preference UI refactor PR until the fix is published to the public repositories. You may use the builds at `14-dev` though, since they are more stable.

Appreciate your understanding!

**Comment by shailantani** [comment]
> Hey there,
> 
> Thanks for bringing this to our attention. It seems like there's [an issue with Pixel devices](https://issuetracker.google.com/issues/325667060) on Android 14. While it's fixed internally at Google, it's not yet available to the public. As a result, we may need to delay merging the Preference UI refactor PR until the fix is published to the public repositories. You may use the builds at `14-dev` though, since they are more stable.
> 
> Appreciate your understanding!

Thanks a lot for your response. My bad, I should've checked for the issue in googles issuetracker. Anyways, so this issue cant be fixed until a software update right?

oh btw, I tried the 14-dev branch builds as well. They too seem to have this issue.

**Comment by steviek** [comment]
Just a random internet citizen passing through here from a Google search, looks like it's fixed in compose-ui in alpha now starting with 1.7.0-alpha02

Thanks for the bug link!

**Comment by AndrewDallas** [comment]
Having this same issue of course, I take it we have to wait on Google's end right now? Thanks 👍

**Comment by steviek** [comment]
If you don't want to use alpha, I think it won't be in stable until 1.7.0 probably

**Comment by AndrewDallas** [comment]
For a non developer kind of guy , what exactly does that mean? Quite a while or ? Just curious as I love LC and miss using it already ☹️

**Comment by shailantani** [comment]
Idk how, but the error has stopped popping up for me. 
Im running 14 dev (612)

**Comment by MrSluffy** [comment]
use latest lawnchair 14
