### ISSUE TITLE
Search bar widget accent colors doesn't match

### ISSUE THREAD

**Issue by sarojpanda44** [Deletescape-Media/Lawnchair#4107]
### Describe the bug

The Lawnchair Search bar widget accent colors doesn't match in the light theme. There colors looks faded/greyed out. It looks correct in the dark theme.

Light theme
![Screenshot_20240304-073612](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/c51ab9a9-3e5f-4cc5-a559-f2099403a9e2)

Dark theme
![Screenshot_20240304-073648](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/5a56b8a5-d534-4739-be5b-5a8ac346d1a9)

### Steps to reproduce

1. Go to Lawnchair Home Settings and select Dock
2. Enable Dock
3. In the Search Bar Widget select Lawnchair
4. Enable Apply Accent Colors
5. Set /enable system wide light theme from System Settings, Display, Dark theme (off)
6. Check the colors of the Dock search bar widget
7. Enable the dark theme and check the colors

![Screenshot_20240304-074534](https://github.com/LawnchairLauncher/lawnchair/assets/27029904/4da6cfcc-6c6d-4bff-94a1-0eebc2f1038b)

### Expected behavior

The accent colors should look similar in both themes or in the darker shade. Not greyed out

### Device information

- Device: Google Pixel 7 Pro
- OS: Stock ROM Android version 14.0
- App version: 14 Dev 314

**Comment by RouxTheCaster** [comment]
I don't think this is a bug.

**Comment by sarojpanda44** [comment]
> I don't think this is a bug.

You mean the grey colored Search bar is okay in light theme?

**Comment by RouxTheCaster** [comment]
> > I don't think this is a bug.
> 
> You mean the grey colored Search bar is okay in light theme?

That's because the color you are using. Try different colors.
![Screenshot_20240305_132522_Discord](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/4a6cf281-b8c0-4ba7-8e5f-31d546c1ebae)
