### ISSUE TITLE
The Google search pill shortens.

### ISSUE THREAD

**Issue by nachiketdk** [Deletescape-Media/Lawnchair#412]
The Google search pill shortens after changing the grid size from default to 5x5. 
My device - Nubia N1 lite, Running Android 6.0
![screenshot_20170806-104008](https://user-images.githubusercontent.com/29353816/29000781-4a8ea8cc-7a94-11e7-89b4-8ce752c88701.png)
How can i get it like this?
![3794013b-487f-489d-a5f9-6af566d70572](https://user-images.githubusercontent.com/29353816/29000798-dccb4664-7a94-11e7-9e73-0ee6fbb8fb78.jpg)

**Comment by suphon-t** [comment]
The search pill width will be equal to icon width.
