### ISSUE TITLE
Issues with icon display in app drawer and home screen

### ISSUE THREAD

**Issue by Richard38907** [Deletescape-Media/Lawnchair#4121]
### Describe the bug

On the lawnchair 14 dev #450 (and other 14 versions), I noticed blur icons compared to the lawnchair 12.1 versions.

### Steps to reproduce

1. Go to 'Home Settings'
2. Click on 'General'
3. Scroll down to 'Change icon style'
4. Set the same icon size on both lawnchair versions.
5. See error

### Expected behavior

Icons are a little bit blurred on 14#450 compared to 12.1.

### Screenshots

![Screenshot_20240312-160631](https://github.com/LawnchairLauncher/lawnchair/assets/148692265/2fc12a5d-7b0e-476f-a2f2-23379a51b2a8)
![Screenshot_20240312-160851](https://github.com/LawnchairLauncher/lawnchair/assets/148692265/bd993d0d-2fee-4dd8-bf40-b8dc32d558ae)

### Device information

- Appareil : [par exemple Google Pixel 6]
- OS : [par exemple ROM d'origine version Android 12.0]
- Version de l'application : [par exemple 12.1.0 Alpha 4]

### Additional context

The bug appears on my two phones (OxygenOS 14 and Pixel experience 13)

**Comment by Richard38907** [comment]
I m also facing another bug on lawnchair 14 when I set the icons to the largest size. This is correctly displayed on 12.1
![Screenshot_20240312-161053](https://github.com/LawnchairLauncher/lawnchair/assets/148692265/79f64292-dd17-48c7-ae6c-311650ab9bed)
![Screenshot_20240312-161545](https://github.com/LawnchairLauncher/lawnchair/assets/148692265/605945da-15cb-4eef-bb21-3d2266c47aeb)

**Comment by MrSluffy** [comment]
use latest lawnchair 14
