### ISSUE TITLE
App crashed when placing icons 

### ISSUE THREAD

**Issue by H34TW4V3** [Deletescape-Media/Lawnchair#4123]
### Describe the bug

Lawnchair crashed when attempting to place an icon into a fold on the home screen and also when attempting to access the settings menu

### Steps to reproduce

1. Swipe up to access the app drawer
2. Press and hold an app icon
3. Please the icon over another icon to start creating a folder
4. Lawnchair crashed 

### Expected behavior

A new folder to be created on the home screen 

### Screenshots

[Uploading Lawnchair (Debug) bug report 12 Mar 2024 21:55:34.txt…]()

### Device information

- Device: Google Pixel 7A (lynx)
- OS: Android 14 Beta QPR 3 (Recently downgraded from Android 15 DP1)
- App version: Latest nightly build

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
