### ISSUE TITLE
[FEATURE] Neo-Feed support

### ISSUE THREAD

**Issue by Handrail9** [Deletescape-Media/Lawnchair#4134]
### Describe the feature

Supporting third party feed providers, such as neo feed.
https://github.com/NeoApplications/Neo-Feed

### Why would it be useful to add?

I use a degoogled ROM, many others do as well, and dont have the capability to use GFeed

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

This would work the same as google feed, except its whatever the third party feed is instead of Gfeed. For example Neo Feed shows an RSS feed

**Comment by sabbaghpierre** [comment]
I'd definitely love this integration. Having Lawnchair with the RSS feeds that NeoFeed provides would be a dream come true.

**Comment by MillionsToOne** [comment]
There is a feed provider setting, but doesn't allow to set every app as feed. Only smarspacer and Google afaik.

**Comment by validcube** [comment]
Lawnchair does support Neo-Feed (and anything that is an feed) it's just not whitelisted as an feed, I actually try using Neo-Feed but however it's kinda broken so I've decided not to make an PR to whitelist it and if you'd liked to try you can disable the whitelist on the Lawnchair Debug Settings `pref_ignoreFeedWhitelist`

**Comment by Handrail9** [comment]
edit 2: For those wondering, the flag is on the latest Dev release, and Neo feed works absolutely stunningly. I'd say it functions better here than it does on Neo launcher. Really hoping the devs add it to the whitelist.
edit: figured out where it got moved to
https://github.com/LawnchairLauncher/lawnchair/issues/3762#issuecomment-1825804227


> if you'd liked to try you can disable the whitelist on the Lawnchair Debug Settings `pref_ignoreFeedWhitelist`


Can you tell me how to get here and what version youre using? I tried the developer options from the home settings activity on V12 alpha 4 and theres nothing about the feeds there, the Dev options look to be removed in V14 alpha 2, as well as the latest development builds. What am I missing?

**Comment by pr0927** [comment]
Hi all, I created a feature request for the same thing, with my search skills for this thread failing me.

I see these last two comments - however it seems in the latest developer builds of Lawnchair, im not seeing any options to toggle such a thing on (experimental features, or elsewhere?). Is this still doable right now, or disabled entirely?

**Comment by Handrail9** [comment]
@pr0927 Click the comment link (3762) in my last comment and watch the video, it should show you how to do it there. Just tested it on the latest nightly and it still seems to work. Although NeoFeed now seems to be broken. I cant actually open articles anymore :(

**Comment by seadx6-neo** [comment]
I am also interested in having Neo feedas a feed provider, not long ago I de-Googled my phine only keeping the play store, photos and Google contacts for convenience, now that I can not count with the Google feed my only way of still having a news feed is Neo Feed, I did as @Handrail9 suggested and works like a charm! 

We need this

**Comment by pr0927** [comment]
> @pr0927 Click the comment link (3762) in my last comment and watch the video, it should show you how to do it there. Just tested it on the latest nightly and it still seems to work. Although NeoFeed now seems to be broken. I cant actually open articles anymore :(

Thank you, got it working!

Except...can't actually open any articles - either inside Neo Feed nor via browser. :(

**Comment by RyanHope** [comment]
> Lawnchair does support Neo-Feed (and anything that is an feed) it's just not whitelisted as an feed, I actually try using Neo-Feed but however it's kinda broken so I've decided not to make an PR to whitelist it and if you'd liked to try you can disable the whitelist on the Lawnchair Debug Settings `pref_ignoreFeedWhitelist`

how does one enable the debug settings?
