### ISSUE TITLE
[BUG] always FC on oneui 6.0

### ISSUE THREAD

**Issue by Maytagh** [Deletescape-Media/Lawnchair#4136]
### Describe the bug

If I have a split-screen view in background,then use gesture to look them,then it will crash
All versions on lawnchair(debug) and quickswitch.

https://github.com/LawnchairLauncher/lawnchair/assets/163851869/53af79a7-b0be-4d2c-b5f5-5916fcce973e

screen recording

![64fefc28dc0de5e8668e281f3d8a71c9](https://github.com/LawnchairLauncher/lawnchair/assets/163851869/27add3a9-8df0-441c-81b8-fca6b92f85df)

L14 bug report

### Steps to reproduce

1. Start a split-screen multitask 
2. Switch multitask
3. Crash

### Expected behavior

On oneui 5.1 multitask cards appears normally

### Device information

- Device: [SM-X619]
- OS: [Oneui 6.0]
- App version: [All]

**Comment by MrSluffy** [comment]
Send error logs!

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
