### ISSUE TITLE
[BUG] Icons loses Clarity 

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4139]
### Describe the bug

When changing the Iconpack size from Homescreen /app drawer , Icons looks less sharped and pixelated.

### Steps to reproduce

Change Iconpack size to 110% or more

### Expected behavior

Icons should look sharp and clear on every Iconpack size.

### Screenshots

![Screenshot_20240319_214546_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/36e5ae12-0366-402c-b2ae-7356e66e0377)
Icons looks sharp on default size 100%

![Screenshot_20240319_214530_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/fdb9b85b-e8a6-495d-96e6-9a7d1ec576d1)
 Icons looks less sharp and pixelated
Size - 110%

### Device information

- Device: Samsung F22
- OS: Android 13 One UI 5.1
- App version: # 616

**Comment by MrSluffy** [comment]
Close this as lawnchair doesn't control the quality of the custom icons

**Comment by Richard38907** [comment]
Same problem here. When I set the grid to 4x6 and more or 5x5 and more, the icon size becomes smaller and when I try to restore the previous icon size, I set it to 120% -> blurred.
Lawnchair 12.1 doesn't have this bug.
