### ISSUE TITLE
Backport Adaptive Icons

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#414]
Backport Adaptive Icons to pre O Android versions

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PR1D3S** [comment]
Nice if possible...

**Comment by AxiK101** [comment]
So the backport is now officiall. But only a few apps do change shape and they are mostly system apps from google

**Comment by nyancrimew** [comment]
@AxiK101 yes, because only those apps currently support adaptive icons, and that's definetly not Lawnchairs fault :wink:
