### ISSUE TITLE
[BUG] Recent apps button didn't work on Infinix Hot 30i,Lawnchair 12 alpha 4.

### ISSUE THREAD

**Issue by Kiki012184** [Deletescape-Media/Lawnchair#4142]
### Describe the bug

The bug that i couldn't open recent apps (3 stripe) button in my device `infinix hot 30i` indonesia.

### Steps to reproduce

1. Just click the recent app button

### Expected behavior

Open app recents

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/62149576/b66ec967-4923-4531-9217-50e2ff15cdfe

### Device information

- Device: Infinix Hot 30i x699
- OS: XOS based on android 12
- App version: e.g. 12.1.0 Alpha 4

**Comment by MrSluffy** [comment]
Use latest lawnchair

**Comment by Kiki012184** [comment]
I do

**Comment by Treveler0** [comment]
On Infinix "Recent apps" Activity (and Swipe to Home gesture) is wired to stock launcher (XOS launcher). Without them it doesn't work (checked on my Infinix Hot 40i). Same in search how to fix this.

**Comment by ShahCheema** [comment]
> On Infinix "Recent apps" Activity (and Swipe to Home gesture) is wired to stock launcher (XOS launcher). Without them it doesn't work (checked on my Infinix Hot 40i). Same in search how to fix this.

I'm facing the same issue with my Infinix Note 11. The recents button (in three button navigation) doesn't work while both home and recents gestures (in gestural navigation) don't work. This happens when we install any third party launcher like Nova or Lawn chair and uninstall the stock XOS launcher via Shizu Tools Debloater and Shizuku. The stock XOS launcher takes up a lot of RAM and has no customization.

**Comment by ShahCheema** [comment]
@MrSluffy

**Comment by Kiki012184** [comment]
> > On Infinix "Recent apps" Activity (and Swipe to Home gesture) is wired to stock launcher (XOS launcher). Without them it doesn't work (checked on my Infinix Hot 40i). Same in search how to fix this.
> 
> I'm facing the same issue with my Infinix Note 11. The recents button (in three button navigation) doesn't work while both home and recents gestures (in gestural navigation) don't work. This happens when we install any third party launcher like Nova or Lawn chair and uninstall the stock XOS launcher via Shizu Tools Debloater and Shizuku. The stock XOS launcher takes up a lot of RAM and has no customization.

I ain't rooting my device,or using shizuku neither.
Just pure average lawnchair user without that part.

**Comment by ShahCheema** [comment]
I haven't rooted either, just used shizuku/shizu tools to uninstall the
crappy XOS launcher. But because of recents button and gesture issues, I
have to keep it installed alongside any third party launcher. Otherwise the
issues persist. But I can't waste Ram on having both XOS and third party
launchers, so I'm back to using it standalone; disabled every ad and zero
screen etc.

PS Shizu tools allowed me to uninstall alot of bloatware including Folax
App, Infinix Club apps, AI gallery etc. Phone runs very smooth and snappy
now.

**Comment by hitokirihahn** [comment]
the only workaround with this if you want o remove XOS launcher is you install Launcher with ROOT, i've faced this problem before and can be fixed with installing nothing launcher from magisk module or another launcher same way from magisk.

**Comment by Treveler0** [comment]
> the only workaround with this if you want o remove XOS launcher is you install Launcher with ROOT, i've faced this problem before and can be fixed with installing nothing launcher from magisk module or another launcher same way from magisk.

On newer Unisoc phones main trouble is Bootloader unlocking - t606/t616 hasn't "fastboot flashing unlock" function. So you cannot safe flash boot/custom😢 (accurate you can... but get the Brick then).
Yes - Magisk is better variant if your bootloader unlockable

**Comment by hitokirihahn** [comment]
> > the only workaround with this if you want o remove XOS launcher is you install Launcher with ROOT, i've faced this problem before and can be fixed with installing nothing launcher from magisk module or another launcher same way from magisk.
> 
> On newer Unisoc phones main trouble is Bootloader unlocking - t606/t616 hasn't "fastboot flashing unlock" function. So you cannot safe flash boot/custom😢 (accurate you can... but get the Brick then). Yes - Magisk is better variant if your bootloader unlockable

oh i see, this is sucks then. this one thing is annoying they tied recent apps with their launcher. when i first encounter this problem it made me crazy for days then just out of curiosity i tried install launcher from magisk module and then VOILA it works. My phone are Infinix ZERO 5G and Infinix Hot 8

**Comment by ShahCheema** [comment]
Thanks! Didn't want to root phone, so ended up losing recent apps and home
gestures so to uninstall the crappy XOS launcher. I'm using Kvaesitso
launcher with Dynamic Spot (Dynamic island) that lets me quick change apps
😅.

**Comment by avijtt** [comment]
is there no other alternative for non rooted phone?
