### ISSUE TITLE
[BUG] Firefox android sometimes stuck in a weird state when searching

### ISSUE THREAD

**Issue by q234rty** [Deletescape-Media/Lawnchair#4143]
### Describe the bug

When using the url bar to search in firefox android, after searching for something, firefox is sometimes stuck in a weird state(see the screenshot). Initially I though this is a firefox bug, but I can no longer repro after downgrading lawnchair to the `#496` CI build.

### Steps to reproduce

1. Use firefox android
2. Try to search for something using the url bar
3. Press enter and notice something similar to the screenshot

### Expected behavior

The UI should not be in such a weird state.

### Screenshots

![ResizedImage_2024-03-22_09-35-29_1109](https://github.com/LawnchairLauncher/lawnchair/assets/11485439/8491e275-f6f0-490c-bb9c-f05d2edf14a8)

### Device information

- Device: Motorola X40
- OS: LineageOS 20
- App version: CI build on 14-dev `#622`

### Additional context

The OSK in use is fcitx5-android, in case that's relevant.

**Comment by MrSluffy** [comment]
Lawnchair doesn't control Firefox's search behavior.

**Comment by q234rty** [comment]
Pretty sure this is related to lawnchair...
I manually bisected using CI builds and `#506` works fine while `#507` is broken.
As such I suspect https://github.com/LawnchairLauncher/lawnchair/commit/6146a4a6f84bc0cae6c65603c656d2e54264fe3a is the culprit.
Also on `#507` opening a download file in firefox sometimes does not bring up the "open with" dialog while the background is still shadowed. This does not happen on `#506`.

**Comment by MrSluffy** [comment]
The commit you mentioned it's not related how the Firefox search behavior, Firefox is different app!

**Comment by ammargitham** [comment]
Hi. For what it's worth, I can say that this behaviour does happen only with quickswitch + Lawnchair. It does not occur with Pixel Launcher. And I think the description of the issue is a bit wrong. This issue happen whenever there is a screen transition in any app. The screen gets stuck in the prev screen and only be fixed by tapping the bottom of the screen.

**Comment by CoelacanthusHex** [comment]
> Hi. For what it's worth, I can say that this behaviour does happen only with quickswitch + Lawnchair. It does not occur with Pixel Launcher. And I think the description of the issue is a bit wrong. This issue happen whenever there is a screen transition in any app. The screen gets stuck in the prev screen and only be fixed by tapping the bottom of the screen.

yes, I meet it in all apps as well.

**Comment by ammargitham** [comment]
@q234rty Thanks for pointing out that commit! I reverted that change locally on the latest commit and all seems good now. No freezes!

**Comment by ammargitham** [comment]
@q234rty, @CoelacanthusHex Maybe you've already saw this, but that commit got reverted. So the latest ci build should resolve this problem.
