### ISSUE TITLE
Widgets such as bixby vision and canvas cause launcher to crash

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4152]
### Describe the bug

Seems like widgets with pop up/selection options to change themes or activities are the ones that all crash. 
[Lawnchair bug report Mar 25, 2024 8-19-01 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/14749273/Lawnchair.bug.report.Mar.25.2024.8-19-01.AM.txt)
[Lawnchair bug report Mar 25, 2024 8-17-20 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/14749280/Lawnchair.bug.report.Mar.25.2024.8-17-20.AM.txt)

### Steps to reproduce

Hold home screen to Open widgets setting

Go to widgets with pop up option such as Bixby vision or canvas

Drop on homescreen

Select anything from pop up option

App crashes after you click add

### Expected behavior

The widget to be on the home screen but it just disappeared and the app crashed

### Device information

- Device: Galaxy A54
- OS:OneUI 6/ Android 14
- App version: 12.1.0 Alpha 4

### Additional context

[Lawnchair bug report Mar 25, 2024 8-17-20 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/14749319/Lawnchair.bug.report.Mar.25.2024.8-17-20.AM.txt)
[Lawnchair bug report Mar 25, 2024 8-19-01 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/14749320/Lawnchair.bug.report.Mar.25.2024.8-19-01.AM.txt)

**Comment by Bruhipie** [comment]
You are using an older version of Lawnchair, this bug report will be ignored. You should get a newer dev version and try to reproduce.

**Comment by ghost** [comment]
> You are using an older version of Lawnchair, this bug report will be ignored. You should get a newer dev version and try to reproduce.

I just tried on [Lawnchair 12.1.0 Dev (#1491) test](https://www.apkmirror.com/apk/lawnchair/lawnchair-3/lawnchair-3-12-1-0-dev-1491-release/) and it's the same problem

**Comment by Bruhipie** [comment]
> > You are using an older version of Lawnchair, this bug report will be ignored. You should get a newer dev version and try to reproduce.
> 
> I just tried on [Lawnchair 12.1.0 Dev (#1491) test](https://www.apkmirror.com/apk/lawnchair/lawnchair-3/lawnchair-3-12-1-0-dev-1491-release/) and it's the same problem

That's also old mate. You get the latest debug APKs from [Github Actions](https://github.com/LawnchairLauncher/lawnchair/actions)
The latest one being: https://github.com/LawnchairLauncher/lawnchair/actions/runs/8405471762.
Download the Debug Apk zip, extract it and you'll find two folders with two apks, install any one of them and try to reproduce it again.

**Comment by MrSluffy** [comment]
Use latest lawnchair
