### ISSUE TITLE
[feature request] Verically-aligned apps drawer

### ISSUE THREAD

**Issue by artem** [Deletescape-Media/Lawnchair#416]
Hi! Is it possible to implement drawer similar to one that Evie Launcher has?
Screenshot: http://imgur.com/a/cRdx9

**Comment by cabban** [comment]
![screenshot_20170813-081311](https://user-images.githubusercontent.com/19514493/29246563-4b8fec20-7fff-11e7-9270-3f965565db12.png)
Yes would love to with this and the letters on left also 
Great suggestion 
@ab123321 
Please @deletescape

**Comment by suphon-t** [comment]
Implemented

**Comment by cabban** [comment]
Thank
U but not quite correct. No letters like his and mind pictures 😀please add this 
@paphonb
