### ISSUE TITLE
[BUG] Screen touches may be delayed (One UI 5.1 core)

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4165]
### Describe the bug

Sometimes while using app, 
""App isn't optimised for the latest version of Android. Screen touches may be delayed or not recognised"  message pops out.
and touches not works.

Mrsluffy v6 version works good.
This problem is happening on later builds.

### Steps to reproduce

1. Open any apps
2. Use it for some times
3. You will get this message and screen touches will not work

### Expected behavior

Screen touches should work normally.

### Screenshots

![Screenshot_20240331_181008_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/444bff26-a702-4c24-843e-5679dbafac75)
![Screenshot_20240331_181001_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/c62a00fe-a805-49db-a443-1bf3b44de333)

### Device information

- Device: Samsung F22
- OS: Android 13 based One UI 5.1 core 
- App version: latest Lawnchair beta 2

**Comment by MrSluffy** [comment]
Close this since it will occur in other slow end device since it's debug build
