### ISSUE TITLE
Transparent / blurred navigation controls (on LG G6 LG UX 7.0)

### ISSUE THREAD

**Issue by stefanvanruiten** [Deletescape-Media/Lawnchair#417]
Hi,

On my stock LG G6 running UX UI based on Android 7.0 the navigation controls are always a solid black bar even when I've set the dock to be blurred.

Some other screenshots on telegram show a transparent navigation bar and in Nova launcher and action launcher for example my navigation bar can be set to match the dock.

Can this be enabled for lawnchair as well, now it's looking really out of place.

Thanks.

**Comment by Mackerel71** [comment]
Set the App Scaling to 18:9.  Also, set the wallpaper app to the same so that they will fit correctly.

**Comment by stefanvanruiten** [comment]
yes, that semi works I've noticed already and am currently running it like that. However it's sub-optimal since for example it won't remain transparant when swiping to and from Google Now feed and afterwards has to refresh the nav bar to make it transparant again. 

In Nova / Action for example the display scaling is set to the default 16,7:9 and that seems to give a smoother endresult, although the workaround is better then nothing of course :)

**Comment by Mackerel71** [comment]
That is true.  I never really noticed it since I switched from Nova to Lawnchair.  Hopefully it will be something the developers address. They seem to be good about adding new features and addressing bugs.

**Comment by nyancrimew** [comment]
We already tried a few fixes for this issue in the past, but it is quite hard to fix, so it could take a while, but we're working on it

**Comment by stefanvanruiten** [comment]
Yeah I've noticed in the telegram group all your efforts, +1
