### ISSUE TITLE
[BUG]  Nightly version crashes on Android 14

### ISSUE THREAD

**Issue by SilverTears1** [Deletescape-Media/Lawnchair#4176]
### Describe the bug

Nightly version crashes on Android 14

### Steps to reproduce

1. Crashes On launch 

### Expected behavior

be executed correctly

### Device information

- Device: Xiaomi Mi 10T lite
- OS: PixelOS ROM Android version 14
- App version: Nightly

**Comment by mvmike** [comment]
Duplicates https://github.com/LawnchairLauncher/lawnchair/issues/4175
