### ISSUE TITLE
[BUG] Multitasking doesn't work with Quickswitch (Android 10)

### ISSUE THREAD

**Issue by TheJNXx** [Deletescape-Media/Lawnchair#4177]
### Describe the bug

Being in recent causes Lawnchair to crash when being in an app

### Steps to reproduce

1. Go to an app
2. Tap the recent button
3. See error

### Expected behavior

That lawnchair does not crash

### Device information

- Device: Samsung A022M
- OS: One Ui Core - Android 10
- App version: Lawnchair 14 Dev 675

### Additional context

[Lawnchair (Debug) bug report 3 abr. 2024 2﹕25﹕16 a. m..txt](https://github.com/LawnchairLauncher/lawnchair/files/14848660/Lawnchair.Debug.bug.report.3.abr.2024.2.25.16.a.m.txt)

**Comment by MrSluffy** [comment]
this should be fixed in latest beta 3 if still persists please reopen this issue
