### ISSUE TITLE
Themed icons can't be set

### ISSUE THREAD

**Issue by HighUI-Dev** [Deletescape-Media/Lawnchair#4181]
### Describe the bug

When chosing app drawer or home screen and lockscreen in themed icons it always stays off, and doesn't apply lawnicon.

### Steps to reproduce

1. Go to Settings
2. Click on General
4. Scroll down to Icon style
5. Choose home screen or app drawer as themed icon
6. It doesn't change and stay off

### Expected behavior

What expected to happen is basically changing the home screen or app drawer or both's icons to the themed icons

### Device information

- Device: POCO F3
- OS: Android 13, MIUI 14.0.8
- App version: 14.0.0 beta 1

**Comment by MrSluffy** [comment]
Install lawnicons

**Comment by HighUI-Dev** [comment]
I do have it installed ಠ⁠_⁠ಠ

**Comment by madison696969** [comment]
i got the same issue

**Comment by kurtbahartr** [comment]
Let's try to troubleshoot this together.

@HighUI-Dev, have you tried manually restarting the launcher (either from launcher's developer options or from Lawnchair app info in Android Settings)? You're also using MIUI 14 so it might also be Xiaomi's fault for breaking some apps' internal "Restart" behavior. I have a Redmi Note 10S on which I can try to replicate this very issue if and when it's (the phone is) fixed.

If that doesn't work, try uninstalling Lawnicons and reinstalling it *after making sure Lawnchair is installed and fully set up*, as that was what fixed this in @madison696969's case - Huge thanks to her for telling me about this.

Please get back to this issue with the results after trying these out, whether if they worked or not and the current behavior if they didn't, so I can try to think of more solutions.
