### ISSUE TITLE
[BUG] Quickswitch not working in beta version

### ISSUE THREAD

**Issue by gerardovasquez307** [Deletescape-Media/Lawnchair#4186]
### Describe the bug

Hi guys, I have been using debug builds and have been using quickswitch with it on latest oxygen os 14 on my oneplus 11 successfully. I have seen minor issues with debug versions such as lag after having too many recent apps show up and can clear out the bug by clearing all tasks. I un-installed dev build and installed beta release and went to quickswitch to use lawnchair 14 dev (#13) this is the beta release. I have trying rebooting, resetting recents provider and I cannot get lawnchair recents provider to be used. I open quick switch and always see that oneplus provider is still being used. U installing beta and switching back to latest debug build also does not resolve this issue. 

### Steps to reproduce

1. Install latest beta lawnchair build. 
2. Set recents provider to lawnchair 
3. Reboot and see that recents provider not working

### Expected behavior

Lawnchair recents provider to be used for quickswitch

### Device information

- Device: Oneplus 11
- OS: OxygenOS 14 (Android 14)
- App version: lawnchair beta 1

**Comment by gerardovasquez307** [comment]
Saw the beta 2 come out. This is still not resolved in beta 2

**Comment by Bruhipie** [comment]
I have it fixed on my device. 
You need to use QuickSwitch version 3.3.8 (uploaded zip from quickswitch telegram group).
Steps that i followed:
1. Use Reset option inside quick switch app to prevent any issues. Reboot
2. Install Lawnchair 14 Beta 2. Install QuickSwitch 3.3.8 (given here). Reboot
3.  Select Lawnchair 14 Beta 2 in QuickSwitch app.
[QuickSwitch-3.3.8.zip](https://github.com/LawnchairLauncher/lawnchair/files/14853687/QuickSwitch-3.3.8.zip)

**Comment by gerardovasquez307** [comment]
> I have it fixed on my device. You need to use QuickSwitch version 3.3.8 (uploaded zip from quickswitch telegram group). Steps that i followed:
> 
> 1. Use Reset option inside quick switch app to prevent any issues. Reboot
> 2. Install Lawnchair 14 Beta 1. Install QuickSwitch 3.3.8 (given here). Reboot
> 3. Select Lawnchair 14 Beta 1 in QuickSwitch app.
>    [QuickSwitch-3.3.8.zip](https://github.com/LawnchairLauncher/lawnchair/files/14853687/QuickSwitch-3.3.8.zip)

I can confirm this fixes the quickswitch issue thanks so much!
