### ISSUE TITLE
[BUG] blur does not work anymore

### ISSUE THREAD

**Issue by askorbinovaya-kislota** [Deletescape-Media/Lawnchair#4187]
### Describe the bug

blur in app menu was working on lawnchair 12, but does not work anymore in lawnchair 14

### Steps to reproduce

1. open the app menu
2. background is not blurred

### Expected behavior

it should be blurred

### Screenshots

lawnchair 12:
![Screenshot_2024-04-03-16-19-09-275_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/105155938/02cc795d-a378-4451-a6ae-722e7c032886)
lawnchair 14:
![Screenshot_2024-04-03-17-59-35-001_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/105155938/9c2f4a93-705b-4de4-80a6-425a826b792d)

### Device information

- Device: Mi 10T Lite
- OS: miui 13.0.8, android 12
- App version: 14 beta 2
- `ro.surface_flinger.supports_background_blur` is 1

**Comment by MrSluffy** [comment]
Unfortunately we have a guard for this, we only allow A13+ since some A12 oem is crashing here for your reference : [`BlurUtils.java`](https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/systemUIShared/src/com/android/systemui/shared/system/BlurUtils.java#L31)

**Comment by kymerea** [comment]
> Unfortunately we have a guard for this, we only allow A13+ since some A12 oem is crashing here for your reference : [`BlurUtils.java`](https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/systemUIShared/src/com/android/systemui/shared/system/BlurUtils.java#L31)

I'm on android 13 and the blur does not work for me?
