### ISSUE TITLE
[BUG] invalid apk for v14 beta 2

### ISSUE THREAD

**Issue by Sxderp** [Deletescape-Media/Lawnchair#4189]
### Describe the bug

Downloaded the apk from Github. Attempted to "update" with Package Installer. I get a warning that the APK is invalid.

### Steps to reproduce

Download APK. Attempt install. 

### Expected behavior

The software installs. 

### Screenshots

![Screenshot_20240403-113419_Package_installer](https://github.com/LawnchairLauncher/lawnchair/assets/6609453/fe790342-6f22-4f5b-83bb-d34093a53ed8)

### Device information

- Device: Asus Zenfone 9
- OS: A 14
- App version: 14.0.0 beta 2

**Comment by Sxderp** [comment]
Doing an uninstall first allowed me to install. A bit annkoying as I have to redo my settings but at least it installed..

**Comment by cooperka** [comment]
hi @Sxderp, can you please re-open this issue? 

i am experiencing the same issue when trying to upgrade and i don't think uninstalling is an appropriate solution here (unless there's some technical reason why it's necessary, but it's not mentioned in the release notes).

system: Pixel 8, Android 14
current version: 12.1.0-alpha4
attempted version to install: 14.0.0-beta2

NOTE:
14.0.0-beta1 installs successfully (and runs as a completely separate app in parallel with v12), but 14.0.0-beta2 can't be installed on top of beta1 either; same error message.

**Comment by dunxd** [comment]
Same issue on Samsung Galaxy A54 5G running latest security updates.

**Comment by crhbetz** [comment]
Fwiw, you can backup your settings and restore after uninstalling and updating. You'll have to redo widgets though and a couple of settings I had to redo too. Took me maybe 3 minutes but still, this is a bug I also experienced (Pixel 8, latest GrapheneOS).

**Comment by dunxd** [comment]
Not acceptable to me. I have a lot of widgets to control Home Assistant - recreating them all is not a trivial task for me. 

Last time I upgraded the backup/restore did not work at all. Is that now fixed, minus widgets?

My preference would be ability to upgrade rather than delete then reinstall and configure from what is backed up.

**Comment by crhbetz** [comment]
Just no be clear, I'm also only a user.

`Last time I upgraded the backup/restore did not work at all. Is that now fixed, minus widgets?`

I backed up from latest previous release, uninstalled, installed v14 beta 2, successfully restored. I was missing widgets + **some** settings (I can remember icon and font size).
