### ISSUE TITLE
Hide dock bug

### ISSUE THREAD

**Issue by hassie-dash** [Deletescape-Media/Lawnchair#419]
Hiding the dock seems to cause bigger space between each row in the app drawer. 

![Dock enabled](http://i.imgur.com/J2jYgqf.png)

![Dock hidden](http://i.imgur.com/xQvPsgF.png)

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
I can confirm this bug.
