### ISSUE TITLE
[BUG] The minimum value of the "Row Height" is 70%

### ISSUE THREAD

**Issue by GuiSousa135** [Deletescape-Media/Lawnchair#4191]
### Describe the bug

The problem is that it is impossible to reduce the "Row Height" value to numbers below 70%, which makes the app grid very "separate".

Example:

![Screenshot_20240403-134911_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/55188286/bf8a2f9a-6458-4536-8b06-71df638586de)

### Steps to reproduce

1. Go to Home Settings 
2. Click on 'App Drawer'
3. Scroll down to 'Grid'
4. See the minimum value of the Row Height (70%)

### Expected behavior

It should be possible to select values ​​smaller than 70%, such as 50%, 30%, and others.

### Screenshots

![Screenshot_20240403-133448_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/55188286/f7281737-ea68-4e76-962c-7760d99f72b4)

### Device information

- Device: Samsung S20 FE
- OS: stock ROM OneUI Android v12
- App version: 14 beta 2

**Comment by GuiSousa135** [comment]
I just found that the problem is with the "Show Labels" option, when this option is disabled, the space dedicated to the application name does not disappear, only the text disappears. The correct way would be to disappear both the text and the space that this text occupies (this is what happened in the previous version, before Lawnchair 14, however, in these new releases this operation is not done correctly).

**Comment by Matth7878** [comment]
I think it's a duplicate to issue #4663 which have a fix in latest nightly.

**Comment by tgex0** [comment]
Yes, indeed. The App Drawer 'Row height' can now be reduced down to a minimum value of 30% in the latest nightly.

**Comment by SuperDragonXD** [comment]
As this feature is available in the later nightly builds, I'll close this issue.
