### ISSUE TITLE
Lawnchair communicates to Startpage.com when go into Home Settings

### ISSUE THREAD

**Issue by chanh2018** [Deletescape-Media/Lawnchair#4192]
### Describe the bug

When goto Home Settings, Lawnchair starts to link to Startpage.com through 2 IP addresses:
172.67.149.19:443
104.21.41.176:443

### Steps to reproduce

1. Go to Home Settings

### Expected behavior

Expecting not contact to any IP address.

### Device information

- Device: Pixel 4A
- OS: stock ROM Android version 14.0
- App version: Lawnchair 14 Beta 2

**Comment by SuperDragonXD** [comment]
Hey there,

Lawnchair does not connect to Startpage when entering Home Settings: https://github.com/search?q=repo%3ALawnchairLauncher%2Flawnchair+startpage&type=code&p=1

Instead, Lawnchair settings connect to our website at https://lawnchair.app/live-information.json. This is to present important announcement information.
