### ISSUE TITLE
[BUG] Latest Beta release flagged as `Trojan`

### ISSUE THREAD

**Issue by vedxp** [Deletescape-Media/Lawnchair#4193]
### Describe the bug

The latest released beta, 14.0.0.Beta.1 is being flagged as Trojan on VirusTotal.

I wonder this is just a false-positive, but still need to confirm if there's any chance it might get fixed.

### Steps to reproduce

1. Download the latest beta release
2. Scan the apk on VirusTotal

### Expected behavior

It should not be flagged as `Trojan`. It was not the issue with the version `12.1.0.Alpha.4` and older.

### Device information

- Device: Motorola G54 5G
- OS: stock ROM Android version 13
- App version: 14.0.0.Beta.1

### Additional context

Here's the link to the scan result: https://www.virustotal.com/gui/file/9e529287ea06cb254a79660566db5eda4cc4500d73fb73b1ee9bd369bebf3894/summary

**Comment by vedxp** [comment]
Edit: It's the same with the releases compiled by @Goooler also.

Here's the scan result of his latest build (14.0.0-20240326):
https://www.virustotal.com/gui/file/58f35d5f707938ec4a4a4556daaa301b869f1adeae35992da764e9c691141d5c

**Comment by RustoMCSpit** [comment]
duplicate https://github.com/LawnchairLauncher/lawnchair/discussions/3899
