### ISSUE TITLE
Widgets cannot be resized vertically

### ISSUE THREAD

**Issue by Artuto** [Deletescape-Media/Lawnchair#4206]
### Describe the bug

I cannot resize widgets vertically like I was able in Lawnchair 13.

### Steps to reproduce

1. Put a widget on the home screen
2. Try to resize it vertically

### Expected behavior

Be able to change the size of the widget.

### Device information

- Device: Oppo Reno6 Lite
- OS: Android (ColorOS) 13
- App version: 14 beta 2

**Comment by MrSluffy** [comment]
Your widget does not support resizing vertically

**Comment by Artuto** [comment]
But it did in Lawnchair 13.

**Comment by MrSluffy** [comment]
What's the widget name?

**Comment by Artuto** [comment]
> What's the widget name?

It's the calendar widget from Google Calendar.

Here with Lawnchair 14:

![Screenshot_2024-04-04-20-18-22-11_67d7f8591eff9881972c1169b8bca2d8.jpg](https://github.com/LawnchairLauncher/lawnchair/assets/9273973/0f85975c-edb9-4b1e-9281-0311b014ed85)

And this is Lawnchair 13:

![Screenshot_2024-04-04-20-18-52-94_feb200cf5a4d605c26203d3de6e25b8a.jpg](https://github.com/LawnchairLauncher/lawnchair/assets/9273973/8da7aff9-47f7-4b98-80c2-ccd09f375519)

**Comment by MrSluffy** [comment]
Did you enable widget constraint and force resize? ![Screenshot_20240405-102244_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/b85ac4c1-435c-46d8-a224-96d56350524f)

**Comment by Artuto** [comment]
I did not know that option existed, v13 just did it automatically. That fixed it, thank you.
