### ISSUE TITLE
[Feature] Option to display app names on two lines

### ISSUE THREAD

**Issue by dontobi** [Deletescape-Media/Lawnchair#4207]
### Describe the feature

In the settings under App Drawer, there should be a switch with which you can display the app names in one or two lines.

### Why would it be useful to add?

Some app names are very long and I think it looks stupid if they are abbreviated with "...".

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

N/A

**Comment by CoelacanthusHex** [comment]
There is an option in the Debug Menu, but it has a strange algorithm for non-Latin characters: it will never break between Chinese characters (Chinese has only a rule that can't break before some punctuations, we can break between any Chinese characters), so a Chinese name still keeps one line. Even worse, if an application name is some Chinese characters plus some Latin characters, it will display as "first line is Chinese characters, but the end was truncated, and the second line is other Latin characters"

**Comment by ThatAspou** [comment]
Hello, this might be a stupid question but is this Debug Menu accessible in lawnchair 14 beta 2

**Comment by Matth7878** [comment]
@dontobi why did you close it?
@CoelacanthusHex  where is debug menu ? I can't find it? I only see an experimental menu and there is no option to display app names on 2 lines for home?

**Comment by dontobi** [comment]
The function can be found under App overview. Simply scroll all the way down there.
