### ISSUE TITLE
[BUG] Drawer isn't full screen on Tab S9 Android 14

### ISSUE THREAD

**Issue by fredgolightly** [Deletescape-Media/Lawnchair#4213]
### Describe the bug

Drawer isn't full screen on Tab S9 Android 14

### Steps to reproduce

1. Swipe up to open drawer

### Expected behavior

Full-screen app drawer opens like on v12a4

### Screenshots 
https://ibb.co/BCbdMT2

_No response_

### Device information

Tab S9
Android 14
14.0.0b2

**Comment by MrSluffy** [comment]
This is not a bug, this how launcher3 works after launcher3 A13 source

**Comment by fredgolightly** [comment]
I still think this is crazy, no other launcher opens the app drawer using only half the screen. The default One Ui, Pixel launcher, and old lawnchair launchers opened the drawer fully on tablets but only this limits the view of the open drawer. Could this be changed to make more sense and fit with how all other launchers work at all?

**Comment by SuperDragonXD** [comment]
You can always change the horizontal padding/margin to 0, but the spacing will be stretched.

**Comment by fredgolightly** [comment]
It's the vertical space. Legacy lawnchair uses all the space, but the current betas & 14dev play store only shows the app drawer in the bottom half of my screen as per https://iili.io/dUNPtQ1.png
