### ISSUE TITLE
[BUG] Weird icon cutoff in dock? LOS20 + QuickSwitch

### ISSUE THREAD

**Issue by GaucovyAero** [Deletescape-Media/Lawnchair#4214]
### Describe the bug

The icons in the dock get cut off for a while if I do a large swipe to homescreen with gesture navigation.

### Steps to reproduce

1. Make sure dock is on and gesture navigation turned on
2. Do a large swipe to homescreen and the dock icons will get slightly cut off

### Expected behavior

The icons should not get cut off during the animation.

### Screenshots

![Screenshot_20240404-145939_MiXplorer](https://github.com/LawnchairLauncher/lawnchair/assets/85581164/722f8c09-856f-46ad-976c-b7af787fa296)

https://github.com/LawnchairLauncher/lawnchair/assets/85581164/1a6d6003-1d2d-41aa-b7de-dfdc2b58c8d4

### Device information

- Device: Xiaomi Poco F3 8/256
- OS: LineageOS 20 (Android 13)
- App version: non-mainline https://github.com/LawnchairLauncher/lawnchair/actions/runs/8551793746, from 2024/04/04, issue also reproducible on Lawnchair 14 Beta 2

### Additional context

QuickSwitch 4.0.2
Turning off the dock works around the issue.

**Comment by MrSluffy** [comment]
Reduce bottom padding
