### ISSUE TITLE
[BUG] pixel 6 Pro april patch crash after launch

### ISSUE THREAD

**Issue by wesked** [Deletescape-Media/Lawnchair#4216]
### Describe the bug

Lawnchair bug report 4 апр. 2024 г. 17:01:17 version: 14 Beta 2 (15) 
commit: ff7f459 
build.brand: google
 build.device: raven 
build.display: AP1A.240405.002
build.fingerprint: google/raven/raven:14/AP1A.240405.002/11480754:user/release-keys 
build.hardware: raven 
build.id: AP1A.240405.002
build.manufacturer: Google 
build.model: Pixel 6 Pro 
build.security.level: 2024-04-05 
build.product: raven
build.type: user 
version.codename: REL 
version.incremental: 11480754
 version.release: 14 
version.sdk_int: 34 
display.density_dpi: 560
 isRecentsEnabled: true 
error: Uncaught exception java.lang.NoSuchMethodError: No interface method destroyInputConsumer(Ljava/lang/String;I)Z in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)  at com.android.systemui.shared.system.InputConsumerController.registerInputConsumer(Unknown Source:14)  at com.android.quickstep.TouchInteractionService.onUserUnlocked(Unknown Source:58)  at com.android.quickstep.m8.run(Unknown Source:2)  at com.android.launcher3.util.RunnableList.add(Unknown Source:7)  at com.android.launcher3.util.LockedUserState.runOnUserUnlocked(Unknown Source:7)  at com.android.quickstep.TouchInteractionService.onCreate(Unknown Source:63)  at android.app.ActivityThread.handleCreateService(ActivityThread.java:4865)  at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2365)  at android.os.Handler.dispatchMessage(Handler.java:107)  at android.os.Looper.loopOnce(Looper.java:232)  at android.os.Looper.loop(Looper.java:317)  at android.app.ActivityThread.main(ActivityThread.java:8501)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

### Steps to reproduce

1. Start phone
2. See error

### Expected behavior

So that the interface and gestures work properly

### Device information

- Device: Google Pixel 6pro
- OS: Stack ROM with April patch
- App version: 14 Beta 2 (15)

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
