### ISSUE TITLE
App shortcut doesn't show up on pop-up menu

### ISSUE THREAD

**Issue by Fluntyy** [Deletescape-Media/Lawnchair#4217]
### Describe the bug

Lawnchair doesn't show app shortcut on pop-up menu but it does show up on app search.

### Steps to reproduce

N/A

### Expected behavior

Lawnchair should detect app shortcut on pop-up menu because it does on app search.

### Screenshots

![Screenshot on pop-up menu](https://github.com/LawnchairLauncher/lawnchair/assets/106996695/b4c43ae1-620b-4b45-a773-63cb0a36a4bc)
![Screenshot on app search](https://github.com/LawnchairLauncher/lawnchair/assets/106996695/d4ee25f0-1da7-48f1-9e45-e515daa0c12f)

### Device information

- Device: OPPO A78 4G (CPH2565)
- OS: ColorOS 13.1 (Android 13)
- App version: 14 Beta 2

**Comment by MrSluffy** [comment]
Did you set launcher as default home?

**Comment by MrSluffy** [comment]
Did you set lawnchair as default home?

**Comment by Fluntyy** [comment]
> Did you set lawnchair as default home?

Yes

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
