### ISSUE TITLE
[BUG] weird visual glitch when closing apps

### ISSUE THREAD

**Issue by DrSamuelHayden** [Deletescape-Media/Lawnchair#4219]
### Describe the bug

The transition back to the home screen when closing an app causes a visual bug

### Steps to reproduce

1. Go to any app
2. Close it
3. The weird visual bug is there

### Expected behavior

I expect it to not do this

### Screenshots

![Screenshot_20240404-024029](https://github.com/LawnchairLauncher/lawnchair/assets/28829448/12549ecb-384b-402f-92a1-4d0a76388fe0)

### Device information

- Device: Pixel 6a
- OS: Android 14 Beta QPR3
- App version: 14 Beta 2

**Comment by MrSluffy** [comment]
Duplicate : #3983
