### ISSUE TITLE
[BUG] 14 beta 2 - gestures - back button tap - glitchy

### ISSUE THREAD

**Issue by spice42** [Deletescape-Media/Lawnchair#4221]
### Describe the bug

if you set 'back button tap' in 'gestures' to open an app, like 'clock' 

it would work with swipe back gesture of android 14 in lawnchair 12 alpha latest

it now does work initially after setting it but then stops working completely after reboot/restart of lawnchair 

![Screenshot_20240405-054909_Trebuchet](https://github.com/LawnchairLauncher/lawnchair/assets/113236440/1a40823e-22ce-406c-9db2-d485b9e6e6d3)

### Steps to reproduce

1. Go to 'home settings'
2. Click on 'gestures'
3. Scroll down to 'back button tap'
4. Set it to open an app
5. swipe back on screen
6. reboot device and check if it still works 

### Expected behavior

swiping back should open the app set

### Device information

- Device: Samsung Galaxy S10e
- OS: LineageOS 21.0
- App version: Lawnchair 14 beta 2

**Comment by MrSluffy** [comment]
Working fine here :  https://streamable.com/5mv2f5

**Comment by spice42** [comment]
still not working here

https://github.com/LawnchairLauncher/lawnchair/assets/113236440/cb010c66-df88-411d-a628-b42823220dcf

not a big deal though. can leave it closed if you like ✌️
