### ISSUE TITLE
[BUG] Unable to set as recents provider in quickswitch

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4225]
### Describe the bug

Selected lawnchair to be the recents provider, rebooted but still, bcz of this app opening animations are broken?

### Steps to reproduce

1. Go to QuickSwitch
2. Click on Lawnchair
3. It will Reboot automatically

### Expected behavior

It should have selected lawnchair as default

### Screenshots

![Screenshot_20240405-122032_QuickSwitch](https://github.com/LawnchairLauncher/lawnchair/assets/113865986/c390f5fb-85e3-4819-9b11-5f7fec093cbc)

### Device information

- Device: Poco X4 Pro 5G (veux)
- OS: LineageOS 21, Android 14, QPR2
- App version: 14 Dev (#712) also in beta 2

**Comment by MrSluffy** [comment]
Use quickswitch version 3.3.0, if still error open issue in quickswitch community

**Comment by ghost** [comment]
> Use quickswitch version 3.3.0, if still error open issue in quickswitch community

Okay
