### ISSUE TITLE
[BUG] Lawnchair 14 beta 2 - Screen touches may be delayed issue on One UI 5.1 core

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4227]
### Describe the bug

Sometimes while using app,
""App isn't optimised for the latest version of Android. Screen touches may be delayed or not recognised" message pops out.
and touches not works.

Mrsluffy v6 version works great without any problem.
Lawnchair 14 beta 2 sometimes show this issue.

### Steps to reproduce

1.Open any apps
2. Use it for some times
3. You will get this message and screen touches will not work

### Expected behavior

Touches should work normally.

### Screenshots
![Screenshot_20240405_155451_Chrome](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/b3a5f2b1-9db0-4384-8e44-f276fb4fa457)

![318268357-c62a00fe-a805-49db-a443-1bf3b44de333](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/937a6ef6-33d7-4834-9d6e-842ca3d4a3b8)

### Device information

- Device: Samsung F22
- OS: Android 13 One UI 5.1 core
- App version: Lawnchair 14 beta 2

**Comment by MrSluffy** [comment]
This issue does not pertain to Lawnchair; Lawnchair is not responsible for managing the behavior of other apps.

**Comment by ujwal246** [comment]
But sir your unofficial version V6 works great.
No such screen touches problems on that version.
So I guess this is Lawnchair problem.
