### ISSUE TITLE
[Bug] Shortcuts issues

### ISSUE THREAD

**Issue by MaxFour** [Deletescape-Media/Lawnchair#423]
Hi, dear developers :) Please fix bug with shortcuts in landscpae mode. It`s happens when on shortcuts more than 2 points.

Thank you!

Sorry my not good English :(

![screenshot_20170807-084112](https://user-images.githubusercontent.com/26022907/29012041-c534224c-7b51-11e7-8d8e-f8e1ec32ce29.png)
![screenshot_20170807-084119](https://user-images.githubusercontent.com/26022907/29012042-c535ecbc-7b51-11e7-82e9-3eed88144ef7.png)
![screenshot_20170807-084939](https://user-images.githubusercontent.com/26022907/29012043-c539c29c-7b51-11e7-9f56-0eaf29f95209.png)

**Comment by Dondrejohnson5** [comment]
Same here. I had that problem before Landscape and Shortcuts.
