### ISSUE TITLE
[BUG] Lawnchair 14 broken on all Android 8 devices

### ISSUE THREAD

**Issue by Fede2782** [Deletescape-Media/Lawnchair#4230]
### Describe the bug

New Lawnchair 14 Beta doesn't work on any Android 8 device. Previous versions worked correctly. 

### Steps to reproduce

Just try to install Lawnchair 14 Beta on any Android 8 or 8.1 device and it won't start. I tried on a Lenovo (8.1), Motorola (8.1) and Huawei (8.0) device. 

### Expected behavior

I should be able to use and start Lawnchair or the minSdkVersion should be increased to a more recent version. 

### Screenshots

N/A because of nothing happens

### Device information

- Device: Lenovo Tab 4 8 and Motorola Moto G5S Plus
- OS: Stock Rom, Android 8.1.0
- App version: Lawnchair 14 Beta 1 and 2. Tried also with latest actions and nightly

**Comment by Chris1320** [comment]
I am also having the same issue. Lawnchair 14 Beta 2 on Android 8.1.0 is stuck at a black screen when I start it.

**Comment by verlain3** [comment]
The same thing is happening here. I tried the newly released Lawnchair 14 Beta 1 from today and the issue is still present.

Android version 8.1.0
