### ISSUE TITLE
HAPPY BIRTHDAY

### ISSUE THREAD

**Issue by fonix232** [Deletescape-Media/Lawnchair#424]
Since it's the coming to age of our Greatest Developer, I suggest we celebrate here on this occasion!

So guys, send all the whores, cocaine, and other unspeakable stuff in the way of @deletescape - he deserves it! 

🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂

**Comment by AxiK101** [comment]
Lol, happy b-day

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
Bday is over 😂
