### ISSUE TITLE
[FEATURE] Add option to remove "Search with startpage"

### ISSUE THREAD

**Issue by naiyerasif** [Deletescape-Media/Lawnchair#4241]
### Describe the feature

I don't use web search, and I don't use startpage. There's an option to disable web search. But there's no option to remove "Search with startpage" from the searchbox options.

### Why would it be useful to add?

I don't want to see "Search with startpage" in my face when I don't use it. It is a visual clutter for me.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20240407-220106](https://github.com/LawnchairLauncher/lawnchair/assets/19614213/cb7a0c63-c833-445f-b50a-81e37c7bda97)

**Comment by SuperDragonXD** [comment]
This has been already heen added in the latest developement/nightly builds: Disabling Web suggestions (via Startpage) will now disable that option.
