### ISSUE TITLE
[BUG] Drawer search box looks not right

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [Deletescape-Media/Lawnchair#4243]
### Describe the bug

Search box in drawer doesn't look right.

### Steps to reproduce

1. Go to 'Drawer'
2. Scroll down the 'app list'
3. See error

### Expected behavior

At least it shouldn't fill by background color.

### Screenshots

Part of the screenshot area contains sensitive data, so covered by white square, sorry.

Screenshot before scroll:

![Screenshot_20240408_100634](https://github.com/LawnchairLauncher/lawnchair/assets/10773245/317acc4d-f91c-4eab-aa5f-94cf89de03b3)

Screenshot after scroll:

![Screenshot_20240408_100933](https://github.com/LawnchairLauncher/lawnchair/assets/10773245/44b7f005-308f-4112-b9cd-554571e3d894)

### Device information

- Device: [Google Pixel 2]
- OS: [stock ROM Android version 11.0]
- App version: [Nightly 14 Dev `#724`] https://github.com/LawnchairLauncher/lawnchair/commit/9dbe79fefc71dbdd81eb1e9e3ca6020d72242d70

**Comment by mhtvsSFrpHdE** [comment]
This bug also exists in 14 beta 2, so I try nightly but still see this visual error.

https://github.com/LawnchairLauncher/lawnchair/releases/tag/v14.0.0-beta2

**Comment by Bobbydew1** [comment]
I think this is not a bug, i actually like this feature

**Comment by mhtvsSFrpHdE** [comment]
> I think this is not a bug, i actually like this feature

I'm not sure if not politeness to mention other launcher, example of "hyperion" launcher, this one's search box remains rounded and small, unchanged during scroll.

Android 11 pixel launcher search box too. If finally refused to provide a customization to make it looks not obtrusive for me (insist on being different), this is just another story of Gnome (in Linux world).

**Comment by mhtvsSFrpHdE** [comment]
Ok, this is not a bug, [Lawnchair 12.1.0 Alpha 4](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4) has same behavior.
