### ISSUE TITLE
Changing the system light/dark mode two times = black screen

### ISSUE THREAD

**Issue by Bobbydew1** [Deletescape-Media/Lawnchair#4244]
### Describe the bug

Lawnchair become unresponsive when system light/dark theme turned on and off two times without going back to the home screen (staying in the quick setting while turning on/off the light/dark theme)

### Steps to reproduce

1. Change your system light/dark two or more times
2.  Dont go to the home screen while chaging

### Expected behavior

Will be fixed the next update 

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/165025149/98c48cd1-44bf-491a-a5ff-311579f80554

### Device information

- Device: wiko 10
- OS: stosck rom android 12
- App version: 14 beta 2

### Additional context

Lawnchair did not give the crash log after the crash

**Comment by MrSluffy** [comment]
If crash send error logs here

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue and please send logs
