### ISSUE TITLE
[BUG] Can not take screenshots or screen record

### ISSUE THREAD

**Issue by Shubhamkr4** [Deletescape-Media/Lawnchair#4250]
### Describe the bug

Cannot take screenshots or screen record when in home screen, app drawer or recents pannel.
Taking a screenshot just produces the picture of the wallpaper 

### Steps to reproduce

Just take a screenshot

### Expected behavior

Screenshot or screen record should be taken of what is actually displayed and not only the wallpaper 

### Screenshots

![Screenshot_20240409-084630](https://github.com/LawnchairLauncher/lawnchair/assets/131890976/2573142d-6286-4efe-85c3-afd3b70a30cd)

### Device information

- Device: Motorola edge 20(berlin)
- OS: Android 13
- App version: Lawnchair 14 beta 2(but this was happening in every version I tried including alphas too

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
