### ISSUE TITLE
Broken app closing animation 

### ISSUE THREAD

**Issue by Bobbydew1** [Deletescape-Media/Lawnchair#4253]
### Describe the bug

When i tap the screen while the app closing animation is still running the icons get stuck 

### Steps to reproduce

1. Open an app
2. Close the app using swipe gesture
3. While the app closing animation is running tap anywhere the screen 
4. See the error 

### Expected behavior

App closing animation gonna be fixed and optimized

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/165025149/a49939eb-32ac-46bb-961e-b06b65f713a2

### Device information

- Device: wiko 10
- OS: stock rom android 12 
- App version: 14 Beta 2

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by Bobbydew1** [comment]
> Can you try and check latest nightly if still persists reopen this issue

Still the same issue, not fixed

**Comment by ioslife** [comment]
This is still happening @MrSluffy
