### ISSUE TITLE
[BUG] Broken icons for indirectly opened applications

### ISSUE THREAD

**Issue by rgedwqeghb** [Deletescape-Media/Lawnchair#4261]
### Describe the bug

When an application is not opened directly from the launcher, its icon is a regular one, not a custom one

(I am using QuickSwitch 3.3.1)

### Steps to reproduce

1. Long press on the app and tap on any shortcut or open one app from the other (for example by clicking the link)
2. Go to the recent 
3. See error

### Expected behavior

App icon should be custom, not regular

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/108678488/1dbce4dc-d944-4971-84bb-7346cb993aee

### Device information

- Device: Google Pixel 6
- OS: custom ROM Matrixx 10.3.1 Android version 14.0
- App version: 14 beta 2
- QuickSwitch version: 3.3.1

**Comment by MrSluffy** [comment]
This is not handle by launcher splash screen : https://developer.android.com/develop/ui/views/launch/splash-screen
