### ISSUE TITLE
Notification icons bug

### ISSUE THREAD

**Issue by leon0399** [Deletescape-Media/Lawnchair#427]
Some issues with notification icons 

![Bug](https://i.imgur.com/Eue4MY8_d.jpg?maxwidth=640&shape=thumb&fidelity=high)

_Отправлено с моего Xiaomi MI 5 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fonix232** [comment]
What would be the bug?

**Comment by leon0399** [comment]
@fonix232 the vk icon wasn't big on previous versions

_Отправлено с моего Xiaomi MI 5 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
