### ISSUE TITLE
[BUG] When using Smartspacer as the At A Glance provider, the At A Glance widget gets incorrectly sized

### ISSUE THREAD

**Issue by obvionaoe** [Deletescape-Media/Lawnchair#4274]
### Describe the bug

When I enable Smartspacer as the At A Glance provider the At A Glance widget gets incorrectly sized and puts information off screen

### Steps to reproduce

1. Go to Lawnchair Settings
2. Click on At A Glance
3. Change provider to Smartspacer
4. Go back to home screen
5. See error

### Expected behavior

The widget should have the correct size

### Screenshots

![Screenshot_20240412-113759_Lawnchair (1)](https://github.com/LawnchairLauncher/lawnchair/assets/35278323/07665d8d-37c0-44e4-a4e5-19a244bdf596)

### Device information

- Device: Asus Zenfone 11
- OS: ZenUi Android 14
- App version: 14 Beta 2

**Comment by srappan** [comment]
Can repro.

- Pixel 6 Pro
- GrapheneOS 
- Android 14
- Version 14 Dev (763)

**Comment by obvionaoe** [comment]
Any news?

**Comment by MrDodojo** [comment]
Can repro too. 
![Screenshot_20240428-135851](https://github.com/LawnchairLauncher/lawnchair/assets/47711280/b621ec37-6dbd-4cc4-9822-90f3d31bbb76)

**Comment by obvionaoe** [comment]
I did a little debugging and figured out that the issue is due to the At A Glance scaling when the Home Screen grid size is changed. The weird thing is this only happens when using Smartspacer as the provider. At least on my phone

**Comment by amrbashir** [comment]
I can confirm that it happens with SmartSpacer only when the grid size is changed from default

**Comment by CoelacanthusHex** [comment]
I have some discovery but don't know wether it is related.

Upstream said SmartSpacerView as a replacement for BcSmartpaceView in Pixel Launcher based launcher or QSB search fragment in Launcher3 based launcher.
https://github.com/KieronQuinn/Smartspacer/wiki/9.-SDK:-Client-SDK-(for-Launchers)#adding-smartspacers-views

And I remember Lawnchair is based on Launcher3, so Lawnchair should use QSB search fragment. But Lawnchair use BcSmartspaceView actually:
https://github.com/LawnchairLauncher/lawnchair/blob/bf612c3dc275b4da01fdfa486e008149f3f2d4ca/res/layout/smartspace_smartspacer.xml#L2-L3
The builtin smartspace seems use QSB search fragment:
https://github.com/LawnchairLauncher/lawnchair/blob/bf612c3dc275b4da01fdfa486e008149f3f2d4ca/lawnchair/res/layout/smartspace_container.xml#L2-L3

**Comment by obvionaoe** [comment]
that could be it, I'll try and test it if I have time later today

**Comment by Udaychakraborty** [comment]
Me facing this problem too 😞
![Uploading Screenshot_2024-06-16-07-26-16-118_app.lawnchair.debug.jpg…]()

**Comment by Smudge8373** [comment]
Any news?

**Comment by srappan** [comment]
This is still broken on 14 beta 3
![Screenshot_20240821-170510](https://github.com/user-attachments/assets/a2a6efd6-a5af-486b-8735-67044bc0dec7)

![Screenshot_20240821-170519](https://github.com/user-attachments/assets/224526b2-7c58-4ffc-9ff3-830b27abf686)

Please reopen

**Comment by obvionaoe** [comment]
It breaks as soon as you go above 5 for the home grid columns.
