### ISSUE TITLE
Google Now on Tap on main screen

### ISSUE THREAD

**Issue by leon0399** [Deletescape-Media/Lawnchair#428]
Google Now on Tap should look like on [1], but now it looks like [2]
![1](http://i.imgur.com/DRI51tN.png)

![2](http://i.imgur.com/Nu9X8qS.png)

_Отправлено с моего Xiaomi MI 5 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fonix232** [comment]
You linked the same image twice

**Comment by leon0399** [comment]
@fonix232 updated

**Comment by fonix232** [comment]
Okay. Well, we can't influence the way how GNow on Tap works.

**Comment by nyancrimew** [comment]
@leon0399 the way it looks on the second screen is google now on tap in the launcher mode

**Comment by leon0399** [comment]
@deletescape so, There is no way for to force Launcher mode? 

_Отправлено с моего Xiaomi MI 5 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
