### ISSUE TITLE
Wrong icon for Dialer (LineageOS, GrapheneOS)

### ISSUE THREAD

**Issue by x9136** [Deletescape-Media/Lawnchair#4281]
### Describe the bug

Since #2555 is closed without a solution, we return to the issue.

Incorrect icon is assigned to the Dialer from LineageOS and GrapheneOS for unknown reasons. If you change the icon manually, it does not change either. Works only when "Home Screen & App drawer" selected in the "Themed Icons" settings.

Detailed discussion
https://github.com/LawnchairLauncher/lawnicons/issues/1728

### Steps to reproduce

Install LineageOS or GrapheneOS → Install Lawnchair and Lawnicons → Select Lawnicons in Lawnchair and try "Off" or "Home screen" in the "Themed Icons" settings.

### Expected behavior

Dialer has the correct icon for any selection in the "Themed Icons" setting.

### Screenshots

![image](https://github.com/LawnchairLauncher/lawnchair/assets/60105060/7504d471-6b52-41bd-9801-eab0ef7dc07f)

### Device information

Device: -
OS: LineageOS, GrapheneOS
App version: 14 Beta 2

**Comment by E8Ib** [comment]
Same on HyperOS

**Comment by alpha4041** [comment]
it does edit the icon but not the themed one

**Comment by E8Ib** [comment]
Maybe it's because Contacts and Dailer are both `com.android.contacts`.

```
<!-- Contacts -->
<item component="ComponentInfo{com.android.contacts/com.android.contacts.activities.PeopleActivity}" drawable="contacts"/>

<!-- Phone -->
<item component="ComponentInfo{com.android.contacts/com.android.contacts.activities.TwelveKeyDialer}" drawable="phone"/>
```

**Comment by x9136** [comment]
> Maybe it's because Contacts and Dailer are both com.android.contacts.

I do not know which OS you are talking about, but you are right about this OS. I'll take that into account. However, this is not the only issue.

**Comment by CaptainColdAJ** [comment]
The same is happening for MIUI devices. Instead of phone app, the contacts app is showing in the favourites tray in the home screen, just because both share the same apk name,. Could you help with this issue and get a possible fix.

**Comment by MrSluffy** [comment]
Can you try and check latest nightly lawnicons if still persists reopen this issue
