### ISSUE TITLE
[BUG] Crash on Android 8

### ISSUE THREAD

**Issue by Artem13327** [Deletescape-Media/Lawnchair#4285]
### Describe the bug

-

### Steps to reproduce

-

### Expected behavior

-

### Device information

- Device: Honor 7A Pro
- OS: EMUI 8.0.0 Android 8.0.0

### Additional context

Yes, I know that Android 8 is quite old and no longer receives updates, but I would still like this launcher on an old device

**Comment by Fede2782** [comment]
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/4230
