### ISSUE TITLE
[BUG] Does not support full screen gestures with HyperOS

### ISSUE THREAD

**Issue by poetabdullah** [Deletescape-Media/Lawnchair#4287]
### Describe the bug

I have tried many times to apply the launcher but each time it forces me to shift to 3 button navigation while I am trying to set it as a default launcher. 

### Steps to reproduce

1. Go to Settings
2. Scroll Down and see Apps.
3. Navigate to Manage Apps
4. Go the Lawnchair
5. Set it as a default launcher.

### Expected behavior

I have watched online reviewers saying that Lawnchair has resolved the issues related to full screen gestures on Android, but it does not work for me. I have seen devices of other brands and they seem to have almost perfect version of full screen gestures even without the custom ROM or the rooted device.

### Device information

- Device: [Xiaomi Redmi note 12]
- OS: [stock ROM Android version 14]
- App version: [Lawnchair 14 Beta 2]

### Additional context

Non functioning of full screen gestures is the only issue that bars me from shifting to Lawnchair completely.

**Comment by E8Ib** [comment]
![No_Gesture_MIUI](https://github.com/LawnchairLauncher/lawnchair/assets/167000236/101c8ae2-15c3-4bd3-9486-309a0077ed71)
[I'm on Xiaomi’s MIUI, and gesture navigation isn’t available.
Xiaomi has fully integrated gesture navigation into their MIUI System Launcher with the MIUI 12/Android 11 update (source), and this prevents users of third-party launchers from enabling gesture navigation. If you want to use a third-party launcher with gesture navigation, you can contact Xiaomi and request that they bring it back. In the meantime, you can download these apps that provide a similar feel to gesture navigation on any Android version.](https://help.niagaralauncher.app/article/7-gesture-navigation)

**Comment by poetabdullah** [comment]
> ![No_Gesture_MIUI](https://github.com/LawnchairLauncher/lawnchair/assets/167000236/101c8ae2-15c3-4bd3-9486-309a0077ed71)
> [I'm on Xiaomi’s MIUI, and gesture navigation isn’t available.
> Xiaomi has fully integrated gesture navigation into their MIUI System Launcher with the MIUI 12/Android 11 update (source), and this prevents users of third-party launchers from enabling gesture navigation. If you want to use a third-party launcher with gesture navigation, you can contact Xiaomi and request that they bring it back. In the meantime, you can download these apps that provide a similar feel to gesture navigation on any Android version.](https://help.niagaralauncher.app/article/7-gesture-navigation)

Wasn't this also the case with other mobile manufacturers since it also didn't work on other devices when I owned them.

**Comment by E8Ib** [comment]
> Wasn't this also the case with other mobile manufacturers since it also didn't work on other devices when I owned them. 

On my vivo device it works correctly, maybe only some of the devices don't work properly.

**Comment by FernFranc** [comment]
This is not a Lawnchair issue, the problem lies with your OEM.

**Comment by Xalose** [comment]
I have the same issue, same device, except it disables system-wide swipe gestures, even when not using the app.
