### ISSUE TITLE
Weather Widget don't work on device 

### ISSUE THREAD

**Issue by yudiyamawaki** [Deletescape-Media/Lawnchair#429]
I tried everything, but nothing. Don't appear the weather and i think the calendar so ugly. Someone can help me to active this? Thanks!

![print](https://user-images.githubusercontent.com/30805247/29035641-b9f83f28-7b72-11e7-90e2-55e1a0c8cbc7.jpg)

**Comment by hassie-dash** [comment]
You need to enable the Weather via the Launcher settings under Pixel Style. Make sure to add your open weather map api key when building the source. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yudiyamawaki** [comment]
How can i do this?

**Comment by hassie-dash** [comment]
If you're using the release version, you can wait until the next version is released which will include the weather. 

If you're comfortable, you can download the source from the alpha branch, manually build it in Android Studio, add your Open weather map api key as a variable and build the apk. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
This issue can be closed @deletescape.
