### ISSUE TITLE
App icons overflows

### ISSUE THREAD

**Issue by panchalbhavya2210** [Deletescape-Media/Lawnchair#4291]
### Describe the bug

When i scroll down to bottom of the app drawer, there's a glitch when icons stretches the icon overlaps the search bar.

### Steps to reproduce

1. Go to App drawer
3. Scroll down to bottom of the app drawer

### Expected behavior

The icons will overlap the search bar.

### Screenshots

![Screenshot_2024-04-16-08-48-08-60_67d7f8591eff9881972c1169b8bca2d8](https://github.com/LawnchairLauncher/lawnchair/assets/94476517/3185e00b-8389-4233-b4eb-bb851af2953f)

### Device information

- Device: Realme narzo 20a
- OS: Realme UI 2.0 , Android 11
- App version: 14 beta 2

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
