### ISSUE TITLE
[BUG] The app opening animation does not work

### ISSUE THREAD

**Issue by alpha4041** [Deletescape-Media/Lawnchair#4295]
### Describe the bug

The app opening animation does not work correctly, when clicking an app icon the app just opens without an animation.

### Steps to reproduce

1. Click an app icon
2. See the missing animation

### Expected behavior

There should be an animation starting from the icon.

### Device information

- Device: Xiaomi 11 Lite 5G NE
- OS: LineageOS 21
- App version: 14 Dev (# 743)

**Comment by MrSluffy** [comment]
Can you try and check latest nightly or for smooth animation use quickswitch if still persists reopen this issue
