### ISSUE TITLE
Android 7.0* no Shortcuts

### ISSUE THREAD

**Issue by alexandrumarcel** [Deletescape-Media/Lawnchair#43]
I'm on Android 7.0 and when I hold an icon I only get Edit, Widget and App Info. Could you find a way to make this work?

**Comment by deletescape** [comment]
The other shortcuts only work with 7.1+ right now (from your title + actual issue text I can't tell if you are on 7.0 or 7.1)

**Comment by alexandrumarcel** [comment]
I already said that I'm on 7.0 .. well I hope you'll find another way to implement this in 7.0 version. 😊😊

**Comment by fishears** [comment]
The confusion is caused by the issue title "Android 7.1 no Shortcuts" which conflicts with the issue description "I'm on Android 7.0..." so actually you were not clear on this point.

**Comment by alexandrumarcel** [comment]
Ooo.. I wasn't paying attention to the title. Sorry about this

**Comment by TokedUp** [comment]
I'm using DP3 O and I don't have the short cuts either

**Comment by deletescape** [comment]
Shortcuts also only work if the launcher is set as default launcher, this is a limitation by Android itself

**Comment by alexandrumarcel** [comment]
@TokedUp If you are on 7.0 the other shortcus won't work as deletescape said above.. So we must wait for him to make them work on Android 7.0

**Comment by fishears** [comment]
TokedUp is on 8.0

**Comment by alexandrumarcel** [comment]
Oh.. My bad :)

*Hiding in corner*

**Comment by TokedUp** [comment]
It's working now. I had to give the launcher permissions for Phone and Storage for some reason

**Comment by deletescape** [comment]
@TokedUp Storage is required for the wallpaper picker (should not have anything to do with the shortcuts though) and I will have to investigate what phone permission is used for myself (and if it is actually even needed)

**Comment by Sparky853** [comment]
Is it possible to make these work on 6.0.1 or is this a limitation of the OS itself?

**Comment by haecker-felix** [comment]
I'm here with android 7.0 and shortcuts are not working. Maybe there is a way to implement this. Nova launcher have shortcut support on 7.0 ;)

**Comment by monreal** [comment]
The feature also works on Action Launcher on Android 7.0, however I do not know if other launchers have to use hacks in order to get it working. If this is the case I would prefer to not have this in Lawnchair and wait for 7.1.

**Comment by ghost** [comment]
@monreal

If you look at the shortcuts UI is different than Lawnchair UI so I think this is the problem. And I think Google change the Shortcuts code so is different than Pixel Launcher from Android 7.0 .

**Comment by suphon-t** [comment]
Other launchers get shortcuts working from 5.0 to 7.0 by manually reading the manifest file which is not implemented in Lawnchair yet.

**Comment by Rekt7** [comment]
Hello, Im on 7.1.1, Oneplus 3T. App shortcuts are not working for me, I have set the launcher as default with all permissions. It shows only Remove, edit and app info.

P.S. not even remotely close to anything with programming, just noticed an issue and came here. Thanks.

**Comment by suphon-t** [comment]
Please move this discussion to #233
