### ISSUE TITLE
"3D Touch" options don't work on my device

### ISSUE THREAD

**Issue by yudiyamawaki** [Deletescape-Media/Lawnchair#430]
Apps like, youtube, play store, chrome and others on drawer or start screen dont work "3d touch"options, in the Nova Launcher works, but not here, some help for this?
![print 2](https://user-images.githubusercontent.com/30805247/29035750-246e0540-7b73-11e7-9b3b-49d68c96ab19.jpg)

**Comment by intelligentcasanova** [comment]
You can enable app shortcuts by long pressing debug settings. Furthermore, it says: "Very experimental and slow. Do not report bugs if this is enabled."

**Comment by intelligentcasanova** [comment]
Closed #430

**Comment by silentgurdian** [comment]
After the backport the shortcuts show up but don't actually work in case of apps like gmail and keep. They just take me to the main app screen. Mostly prevalent with google apps.

**Comment by suphon-t** [comment]
In those cases, they might have a version check.
