### ISSUE TITLE
Add Feature for using Blur on App Drawer Background

### ISSUE THREAD

**Issue by KirmesTVAustria** [Deletescape-Media/Lawnchair#4308]
### Describe the feature

Please add an option to use Blurry Background on Drawer
![Screenshot_20240418-110943](https://github.com/LawnchairLauncher/lawnchair/assets/93053377/c230a5c6-e8de-4cdd-b2f0-77c3f8d95917)

### Why would it be useful to add?

Because it looks nice on some Backgrounds

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Uploading Screenshot_20240418-110943.png…]()
Like this but Blurry

**Comment by doonv** [comment]
This feature does exist in Lawnchair V2.
