### ISSUE TITLE
[BUG] Drawer crashing when dismissing app on Pixel 7a with GrapheneOS

### ISSUE THREAD

**Issue by LethalStarfish** [Deletescape-Media/Lawnchair#4316]
### Describe the bug

Lawnchair 2 drawer crashes sporadically after dismissing/closing an app by swiping up to view all active apps and then swiping away an app to close it. Afterwards, drawer is frozen over main home screen, but no apps can be opened. Swiping up to open drawer again seems to open an invisible drawer such that apps can be opened, but if I scroll through the "invisible drawer" different apps will open than the frozen icons on my home screen. Cannot swipe away frozen drawer, but drawer resets after turning off and turning back on screen. Problem does not happen consistently, but happens frequently. 

### Steps to reproduce

Steps to reproduce the behavior: (sporadic, not consistent. Unsure of exact method to reproduce bug)
1. Swipe up from dock to display active apps
2. Swipe away an active app to close it
3. Return to home screen
4. Open app drawer
5. Sometimes drawer will then freeze

### Expected behavior

Open app drawer without it freezing.

### Device information

- Device: [Pixel 7a]
- OS: [GrapheneOS (Android 14)]
- App version: [2.0-2589]

**Comment by MrPozor** [comment]
I am observing exactly the same bug on a Pixel 7a with stock Android 14.

**Comment by LethalStarfish** [comment]
Bug seems to be resolved after latest Android update, build # 2024051500.

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
