### ISSUE TITLE
[BUG] App Drawer Opacity Setting Hides Navigation Bar

### ISSUE THREAD

**Issue by BrilliantTrees** [Deletescape-Media/Lawnchair#4317]
### Describe the bug

Pixel 8 Unrooted handset

My preferred wallpaper is a simple solid black background and on Lawnchair 14.2 Beta this works perfectly in the Home Screen and App Icon Text and Navigation Bar icons appear in White as a nice contrast to the black background (I don't use gesture navigation and prefer the old school 3 button navigation icons).

If I adjust the App Drawer Background Opacity setting to 0% (To get a Black Background) in the App Drawer then the App Text Icon colours auto changes from Black to White Text to mimic the look of the Home Screen

However the 3 navigation buttons don't appear to change colour and remain Black (On Black background) so are now invisible in the App Drawer.

The invisible buttons still work so touching screen where 3 buttons ought to appear performs the required function

### Steps to reproduce

1. Go to '..Home Settings.'
2. Click on App Drawer'....'
Select 'Background Opacity and reduce to 0%'

### Expected behavior

Unless I'm doing something wrong in another setting I would expect the 3 navigation buttons to auto change colour to White as the App Icon Text does and remain visible for use in the App Drawer

### Device information

- Device: Google Pixel 8]
- OS: [estock ROM Android version 14.0]
- App version: [e.g. 14.1.0 Beta 2]

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
