### ISSUE TITLE
[BUG] Unable to add any widget

### ISSUE THREAD

**Issue by saloniamatteo** [Deletescape-Media/Lawnchair#4320]
### Describe the bug

Any attemp to add any widget results in a LawnChair crash, and no widget added.

### Steps to reproduce

1. Open "widgets" tab
2. Select any widget
3. Drag and drop it to the home screen
4. Try to add it

### Expected behavior

No crash, obviously, and a working widget.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/28765699/c3f92576-6319-4b52-8a35-6d0a3efa5c74

### Device information

- Device: Samsung Galaxy A54
- OS: Android 14 (One UI 6)
- App version: 14.0 Dev `#774`

### Additional context

The main culprit seems to be `com.android.launcher3.CellLayout.getUnusedHorizontalSpace()`

Here is the log:

```
FATAL EXCEPTION: main
Process: app.lawnchair.debug, PID: 14419
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.launcher3.CellLayout.getUnusedHorizontalSpace()' on a null object reference
	at com.android.launcher3.Workspace.getFinalPositionForDropAnimation(Workspace.java:3137)
	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:3164)
	at com.android.launcher3.Launcher.completeTwoStageWidgetDrop(Launcher.java:1086)
	at com.android.launcher3.Launcher$3.run(Launcher.java:999)
	at com.android.launcher3.Workspace.removeExtraEmptyScreenDelayed(Workspace.java:952)
	at com.android.launcher3.Workspace.lambda$removeExtraEmptyScreenDelayed$3(Workspace.java:922)
	at com.android.launcher3.Workspace.$r8$lambda$qJmEWteEMIDxIhPN0xohUE9-Gbo(Unknown Source:0)
	at com.android.launcher3.Workspace$$ExternalSyntheticLambda13.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by Serantek97** [comment]
Same issue.

**Comment by dunxd** [comment]
I am unable to add many widgets but not getting a crash with all of them.

## Working
* Contacts > Direct dial
* Contact > Direct message
* WhatsApp > Contact
* Google Maps > Friend location
* Google Photos > Your memories 

## No crash, No Widget
Adding these brings up the preview then settings but no widget is added
* BBC Weather > Nearby
* Clock (Samsung?)
* Home Assistant > All widgets

The home assistant widgets are the ones that are most disappointing to not be able to add. I use these to turn lights on and off and other things. Show stopper for me.

Samsung Galaxy A53 5G
Android 14/One UI 6.0
Lawnchair 14 beta 2

**Comment by saloniamatteo** [comment]
After trying several widgets, I can narrow the issue to be custom widgets, as in custom theme and/or custom size.

Widgets that have a fixed size (that do not open a customization menu) will work 99% of the time.

Widgets that can be resized, but do not offer styling (e.g. light/dark mode, transparency, etc.) will work as well, most of the time.

Widgets that can be styled and resized, will never work, at least for me.

**Comment by dunxd** [comment]
I had 6 Home Assistant widgets installed with Lawnchair 2, but adding any more was crashing Lawnchair. 

I switched to Lawnchair 14 hoping things were better, but _much_ worse.

**Comment by saloniamatteo** [comment]
Example 1: fixed size, non-styleable widget

![Screenshot_20240427_191021_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/0ab13854-eac2-4a15-adc0-c84de93f4be6)

Added without any issue, works properly:

![Screenshot_20240427_191029_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/6d662443-112f-4e8e-841f-ebaa4b1664ca)

Example 2: styleable widget

![Screenshot_20240427_191115_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/a56c8d28-eec5-43a7-9cce-a0d5a376a9d0)

Customisation menu. Pressing the "Save" button causes a Lawnchair crash.

![Screenshot_20240427_191222_Clock](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/8d0c4437-7969-4da7-b91b-2e0ba814979a)

**Comment by saloniamatteo** [comment]
Another example: non-styleable widget, that can be resized:

![Screenshot_20240427_191743_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/b13479a0-8492-4f5f-9300-1505b181ad4c)
![Screenshot_20240427_191747_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/28765699/91fee1ab-e7a7-422d-8dff-2f3b2f01fce9)

**Comment by dunxd** [comment]
Workaround is to set a different launcher as your default. After doing this, open Lawnchair and you can add the widget succesfully. Then set Lawnchair back as the default Launcher.

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by DJohnston79** [comment]
This issue is still présent and seems to be like the guy above said about fixed sized widgets and customisable ones. Ridiculous that t only really affects weather widgets and such... The fix above doesn't work, either. On pixel 8.pro

**Comment by hojdars** [comment]
The issue is still present in the latest AppStore release.

**Comment by shoummashams** [comment]
The workaround is not working for me on 15 beta 1, Sony Xperia 5 V, Android 14.

**Comment by matiiass** [comment]
This error persists and does not work Switch Launcher

**Comment by andrewakel** [comment]
Issue persists as of December 31st, 2025, fix does not work

**Comment by IGN-Styly** [comment]
Same using latest nightly

**Comment by Maverynthia** [comment]
Same. Work around doesn't work. using latest app store one as well.
