### ISSUE TITLE
[BUG] crash after Adjust layout (upgrade from 12.0.0 alpha 5)

### ISSUE THREAD

**Issue by chuwza** [Deletescape-Media/Lawnchair#4327]
### Describe the bug

Hi, I use 12.0.0 Alpha 5. And I installed 14 beta 2 straight away and everything was fine until I modified the layout, I changed the layout from 5×5 to 5×4,and then crash; I tried upgrading to 12.1.0 first, backing up the lawnchair, then restored the backup in 14 beta 2, crash again. I hope this bug is fixed, because if this bug is not fixed, then it means that anyone upgrading from a lower version will need to config their lawnchair layout that has hundreds of apps again!

### Steps to reproduce

1、Upgrade from 12.0.0 Alpha 5 to 14 beta 2
2、Adjust the layout from 5×5 to 5×4
3、Lawnchair crash
4、The Lawnchair layout is reset and there is no app on the Lawnchair.

### Expected behavior

Lawnchair doesn't crash and the layout is successfully modified

### Screenshots

![Screenshot_20240426-141553_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/30049891/9d133dfe-36d7-41a9-b3fa-523364d66d3e)
![Screenshot_20240426-141617_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/30049891/1137c303-71f4-42ff-9a78-c60db06d8087)
![Screenshot_20240426-151440_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/30049891/51a14432-7462-4ef5-9c89-41c5902e1171)
![Screenshot_20240426-150705_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/30049891/834f760c-2fbe-4220-bd10-501791410a30)

### Device information

- Device: [OnePlus 5T]
- OS: [Mokee Android 11]
- App version: [12.0.0 Alpha 5 to 14 Beta 2]

### Additional context

https://katb.in/pitahowamed

**Comment by githubcatw** [comment]
Changing the amount of icons in the dock causes a crash with the same error too. I'm using a Pixel 6 on Android 15 beta 1.

**Comment by dbrand666** [comment]
When I increased the number of rows from 7 to 8 it didn't crash but I lost all my icons including the dock. Interestingly, the preview does show that the icons will be lost.

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
