### ISSUE TITLE
Revert to default Lawnchair settings

### ISSUE THREAD

**Issue by intelligentcasanova** [Deletescape-Media/Lawnchair#433]
Possibly an option to revert to the default Lawnchair settings could be useful. Optionally even per settings page: UI, Pixel style, Behavior.

**Comment by Dondrejohnson5** [comment]
Just go to the settings and clear Lawnchair data. Don't do this if you want to keep your layout

**Comment by intelligentcasanova** [comment]
That's the point; keeping your layout but resetting the settings.
