### ISSUE TITLE
Font text color mismatch between HomeScreen and App Drawer

### ISSUE THREAD

**Issue by Ansarmughal99** [Deletescape-Media/Lawnchair#4333]
### Describe the bug

There is bug whenever the new wallpaper is set or device change into dark mode. The color of the text of the App Name  on the App drawer is the same in color to lockscreen walpaper. While the color of the text font of the App name on the Home Screen  remains in  white color.
Below are the screen shot 
Pic 1 from Home screen
Pic 2 from App Drawer.

### Expected behavior

App Font mainly depend on Lockscreen Wallpaper also font color of text are different n App Drawer And Home screen.

### Screenshots

Below are the Screenshot 
Pic 1 from HomeScreen 
Pic 2  from App Drawer 
![Screenshot_2024-04-27-22-06-11-57_67d7f8591eff9881972c1169b8bca2d8_1](https://github.com/LawnchairLauncher/lawnchair/assets/74392407/7d5003f9-5064-4a11-aa6f-b41072da0fa1)![1000076387.jpg](https://github.com/LawnchairLauncher/lawnchair/assets/74392407/0a3a5ad1-1297-4020-a563-151bfb65be4f)

### Device information

- Device: [Realme gt neo 2]
- OS: [Android 13 color os verison 13]
- App version: [Lawnchair 14 Beta 2 ]

**Comment by MrSluffy** [comment]
this is intended behaviour
