### ISSUE TITLE
[BUG] Pressing home button to get to 1st page doesn't work

### ISSUE THREAD

**Issue by funn-hue** [Deletescape-Media/Lawnchair#4335]
### Describe the bug

When I go to the second page of the home screen, I can't go to the 1st page by clicking the home button once. I have to click it multiple times at once for it to work.

### Steps to reproduce

1. Switch to page 2
2. Click the home button

### Expected behavior

It's supposed to go to the 1st page of the home screen, but fails.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/152728509/2b662946-b76e-4844-b002-19df56d9e557

### Device information

- Device: Samsung Galaxy A52s 5G, A528B
- OS: One UI 6.0, Android 14 with November security patches 
- App version: Lawnchair 14 Beta 2

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
