### ISSUE TITLE
[BUG] Cannot install 14 beta 2

### ISSUE THREAD

**Issue by Akxe** [Deletescape-Media/Lawnchair#4341]
### Describe the bug

I have downloaded the APK from Github. opened it, it prompted me to update the current app, and then it said that the APK is probably invalid. Beta 1 did install and even ran, but you instruct to install beta 2 instead...

### Steps to reproduce

1. Have Lawnchair v12.1.0 Alpha 4 installed
2. Download 14.0.0 Beta 2 (https://github.com/LawnchairLauncher/lawnchair/releases/tag/v14.0.0-beta2)
3. Install it 

### Expected behavior

Expected to work

### Device information

- Device: Samsung Flip 2
- OS: stock ROM Android version 14.0
- App version: 12.1.0 Alpha 4 => 14.0.0 Beta 2

**Comment by githubcatw** [comment]
This is probably because the version code (a number that Android uses to determine if the version of an app is newer than another) of 14 beta 2 is lower than the one of 12.1 alpha 4, so Android considers it to be a downgrade. The only way to update to 14 beta 2 from 12.1 seems to be to reinstall it.

**Comment by Akxe** [comment]
Is there a way to reinstall it without losing all of my settings? Some kind of setting export?

--------

Found it in the top right settings...

**Comment by Etzio-TUI** [comment]
I've never had 12.4 or any previous version of Lawnchair. Attempted download of 14.0.0 beta 2 and I get the same thing as me ruined above. Running a S24U latest android 14 version. APK downloads, asks to update immediately, then open. Upon opening it crashes. Says "bug"

**Comment by Etzio-TUI** [comment]
Mentioned*** not ruined.

**Comment by Akxe** [comment]
@Etzio-TUI You can edit your old post and delete the next one. Better than 2 comments
