### ISSUE TITLE
[BUG] Black square around the icon when closing an app

### ISSUE THREAD

**Issue by tobiasongithub13** [Deletescape-Media/Lawnchair#4342]
### Describe the bug

A black square appears around the icon when closing an app that is opened from the app drawer and the app is in the home screen. This does not happen when closing an app opened from the home screen 

### Steps to reproduce

1. Go to the app drawer
2. Click on any app
3. Swipe up to the home screen (aka going to the home screen)

### Expected behavior

I expected it to not have the black square around the icon

### Screenshots

(excuse the background music I was too lazy to pause it hehe...)
https://github.com/LawnchairLauncher/lawnchair/assets/142713875/b5684759-9f12-48fe-a25a-a57b80cad2c7

### Device information

- Device: realme Note 50 
- OS: stock ROM Android 13
- App version: 14 Beta 2

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
