### ISSUE TITLE
[BUG] Artifacting around icons after closing app

### ISSUE THREAD

**Issue by znbaboy** [Deletescape-Media/Lawnchair#4344]
### Describe the bug

Artifacting around folders after closing out of an app opened from within the folder

### Steps to reproduce

1. Launch app from folder on home screen
2. Close out of app going back to home screen
3. See error

### Expected behavior

Shouldn't be artificing

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/52028136/ed2cb82b-67c6-4f3e-b187-0b245c814faa

### Device information

Device: Pixel 7 Pro
OS: LineageOS 21 (April 23rd build)
Lawnchair version: 14-dev.Nightly-b87e880-CI_801

**Comment by gordongw** [comment]
I can confirm I am getting the same artifacting. 
Device: Pixel 7 Pro 
OS: GrapheneOS 2024050300
Lawnchair Version: 14 beta 2

**Comment by upbox-org** [comment]
Related: #3983

**Comment by znbaboy** [comment]
UPDATE: this does NOT occur when setting Lawnchair as the "recents provider" using quickswitch

**Comment by MrSluffy** [comment]
fixed in `15-dev`

**Comment by znbaboy** [comment]
This still occurs on the latest Googler build
