### ISSUE TITLE
Widget Placement

### ISSUE THREAD

**Issue by TYSLAYER01** [Deletescape-Media/Lawnchair#4347]
### Describe the bug

When I try to place either a calendar widget or spotify widget the launcher crashes. 

### Steps to reproduce

Step 1 : go to widgets
Step 2 : place a calender widget

### Expected behavior

I expected the widget to place normally and be usable

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/168590221/cb1eb459-c5df-43b7-9283-b230a4137fe1

### Device information

- Device: [e.g. Samsung Galaxy S24+]
- OS: [e.g. stock ROM Android version 14.0]
- App version: [ V14.0 beta 1]

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
