### ISSUE TITLE
[BUG] App drawer hides status bar until I swipe down on the invisible notification bar

### ISSUE THREAD

**Issue by pSub** [Deletescape-Media/Lawnchair#4359]
### Describe the bug

The app drawer the status bar (using some fade-out animation). That is fine with me, albeit unnecessary. However, once I close the app drawer the status bar stays invisible. If I open an app using the app drawer, the status bar reappears, but closing the app lets the status bar disappear again. I have to swipe down on the (invisible) status bar, to make it visible again.

### Steps to reproduce

1. Open the app drawer
2. Close the app drawer

### Expected behavior

The status bar is visible when the app drawer is closed.

### Device information

- Device: Fairphone 5
- OS: CalyxOS 5.6.3
- App version: 14 Beta 2

**Comment by DeadSecTr** [comment]
Can confirm that

**Comment by custompyramidfellow** [comment]
Need to second that. This behaviour is really disturbing. 
  * Device: Fairphone 4
  * OS: /e/OS v2.0 (Android 12)
  * App version: 14 Beta 2

I looked in settings but didn't find any option to turn this off. Maybe this is meant to be a feature but there should at least a option to turn this automatic fading out of the status bar off.

**Comment by custompyramidfellow** [comment]
@pSub @DeadSecTr 
I just discovered that this bug/feature has now been addressed. If you install the latest nightly of Lawnchair:

Home Settings -> Home Screen -> Status bar -> Show status bar -> toggle ON

![lawnchair_status_bar](https://github.com/user-attachments/assets/32855eb9-c661-4132-9595-77838d8f6ba0)

Thanks to Lawnchair devs for implementing this 👍

**Comment by pSub** [comment]
That is great and indeed solves my issue. Thank you @custompyramidfellow for pointing me to the fix! Much appreciated.

**Comment by karfau** [comment]
I found this issue because I assumed the status bar is not shown, but because of the Screenshot above I checked all the toghles and found that it "re-appeared" when turning of the "Dark status bar" toggle.
