### ISSUE TITLE
Blinking weather icon conditions bug

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#436]
On latest build there is this funny bug. Weather icon conditions are constantly blinking, long press not working to revert to date widget when weather is doing so

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
This has already been fixed by commit 7b915ab.

**Comment by AxiK101** [comment]
Yeap,thanks

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
Please close this issue.

**Comment by AxiK101** [comment]
@intelligentcasanova I can't, not an admin in this thread..

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
You can close your own issues @AxiK101.
