### ISSUE TITLE
[FEATURE] Modern Accent Color 

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#4371]
### Describe the feature

With android 14 update they also updated the accent colors 

### Why would it be useful to add?

Current one is outdated

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

I got them from Hyperion launcher and reddit

![Screenshot_20240509_005407_hyperion](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/1fd53310-9929-4aa1-b1da-f69029cd8d79)
![Screenshot_20240509_003649_hyperion](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/815863ae-67f6-4c07-a911-f188f11d623c)
![20240509_005456](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/b8beb732-0a06-4a0d-b6db-81f214e15d46)
![20240509_005534](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/ac77c9d0-05ff-4cc4-942b-103d728d997e)

### Additional context

I don't really know the color codes for them but I know y'all get what I'm saying. 
![Screenshot_20240509_005945_hyperion](https://github.com/LawnchairLauncher/lawnchair/assets/118173136/ec462ae6-2cbf-4225-9feb-fb6e9d31dac6)

**Comment by fisforfaheem** [comment]
good

**Comment by MrSluffy** [comment]
Impl : f131f287ee5d2446d8a6b4acaf0094a2aeb989bf

**Comment by fisforfaheem** [comment]
available on latest nightly??? also kindly makes its change log better
