### ISSUE TITLE
[BUG] I don't know why this happens 

### ISSUE THREAD

**Issue by FranVitor0** [Deletescape-Media/Lawnchair#4376]
### Describe the bug

for some reason the denial of xiaomi's "Gestures" system is not compatible with the launcher, when I add lawnchair as the default launcher the system simply switches to the three-button bar.

### Steps to reproduce

I can't even describe it :_

### Expected behavior

.

### Screenshots

![Screenshot_2024-05-10-21-31-44-237_com miui home](https://github.com/LawnchairLauncher/lawnchair/assets/169503724/73eebd4a-9fd3-434a-bfb6-ae25e794c143)

### Device information

- Redmi Note 12 (4G)

### Additional context

..

**Comment by pacjo** [comment]
This is just Xiaomi being Xiaomi. No way to fix it. Only the stock launcher gets the privilege of using gestures for navigation.

**Comment by MrSluffy** [comment]
Memeui moment
