### ISSUE TITLE
Notification bubbles out of screen edges

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#438]
On costume column settings or screen dpis there is this behavior of bubbles. If i recall it right, costume launchers such as Nova & Action, gave a solition to this problem by moving bubbles inside the screen margins. Is it possible to make it work on Lawnchair too? Thanks
![](http://i.imgur.com/265kkqL.jpg)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
Duplicate of #212
