### ISSUE TITLE
[BUG] widgets on non active home screen get squeezed look when switching phone screen to landscape mode

### ISSUE THREAD

**Issue by tbalden** [Deletescape-Media/Lawnchair#4389]
### Describe the bug

The widgets get squeezed look on a non active home screen when switching phone screen to landscape mode in an app. Like browsing so in chrome and then back to portrait mode and go to home screen and swipe to the non active home with the widget. 
This is in a 6x6 icon layout.

### Steps to reproduce

0. Place a 4x2 or a 2x4 and so on widget on any home screen
1. Move to another home screen, so the other with the newly placed widget gets the non active home screen
2. Go to Chrome
3. Click on switch to landscape mode when rotating the phone, then switch back
4. Go back to home screen then swipe to the one with the widget
5. See error

### Expected behavior

The widgets remain with properly sized area on the non active home screens too 

### Screenshots

This is how it will get squeezed look:
![Screenshot_20240514-124236](https://github.com/LawnchairLauncher/lawnchair/assets/1277993/d90f374c-9535-4e04-ab82-9e5001705685)
Long tap, this shows the real borders that aren't getting filled
![Screenshot_20240514-124249](https://github.com/LawnchairLauncher/lawnchair/assets/1277993/2ca2506c-65cc-4794-ac44-6b185cbd3a5b)
The correct look for the size:
![Screenshot_20240514-124256](https://github.com/LawnchairLauncher/lawnchair/assets/1277993/484058cf-c308-427e-aa74-f97279bbca13)

### Device information

- Device: Google pixel 8 pro
- OS: stock 14
- App version: latest dev nightly and latest beta too

**Comment by derwerbebriefkasten** [comment]
Same effect here, with 3rd party weather widget as well as with native clock widget.

Device information

    Device: Google pixel 7a
    OS: stock 14
    App version: 14 beta 2

Wrongly scaled after returning to portrait
![Screenshot_20240520-164723~2](https://github.com/LawnchairLauncher/lawnchair/assets/42896973/8e17c77e-3bc0-4da2-8272-1550abaeb948)

When manually sizing widgets they re-scale correctly
![Screenshot_20240520-164737~2](https://github.com/LawnchairLauncher/lawnchair/assets/42896973/4eafc52a-bcbc-4e03-b81a-fcf7cd0fee77)

**Comment by jordigarcl** [comment]
Same here! Happening with (but not limited to) Loop habit tracker app widgets.
```
Device: Google pixel 7
OS: stock 14
App version: 14 beta 2
```

**Comment by Bikutoso** [comment]
Another one with the issue. It's annoying to because i frequently use the clock widget.
```
Device: Google Pixel 6a
OS: Stock 14
App version: 14 beta 2
```

**Comment by Zettroke** [comment]
Have this issue with a clock widget, seems to be caused by `Remove Size Constraints` option. Disabling it helped

**Comment by derwerbebriefkasten** [comment]
thanks @Zettroke for that hint; my setting `Remove Size Constraints` on Pixel 7a was disabled, so it didn't work in my case.
I've tried both options  `Remove Size Constraints` and `Enforce Widget Resizing` in any combination before, but none of it made it work.

**Comment by tbalden** [comment]
Updated to latest built nightly which contains the supposed fix ( BigScreen support)
It didn't help unfortunately. 

![Screenshot_20240622-080728](https://github.com/LawnchairLauncher/lawnchair/assets/1277993/0a7d0b69-707e-47dd-9fd5-d7e7bcf64f0c)

**Comment by tbalden** [comment]
Testing further the new nightly, I can report that in case the home screens doesn't get fully reloaded like before the fix, it seems to work. When I'm moving out from a landscape browser, it gets to render stuff in the background and so freezes for a little bit, but the widgets seems to be ok

**Comment by derwerbebriefkasten** [comment]
Just saw #4637 and retestet this bug with nightly from today.
It is still not working on my Pixel 7a, clock widget as well as weather widget resize wrongly after returning to portrait mode.
I've tried all combinations with 'remove size constraints' and 'enforce widget resizing', no change in behaviour.

Anyone else still have this problem?

Device: Pixel 7a
OS: stock ROM Android version 14
App version: 14 beta 2 (website download), nightly from 2024-08-17, Lawnchair.Debug.14-dev.Nightly-CI_1225-d20ef2a.apk

**Comment by HazilMohamed** [comment]
I don't think this issue is fixed. Happening on latest beta.  Everytime when I switch back from Landscape to portrait. Restarting lawnchair fixes issue.
