### ISSUE TITLE
Adaptive Icon shape option missing

### ISSUE THREAD

**Issue by JuliGplus** [Deletescape-Media/Lawnchair#439]
Hi, on my Nexus 6p DP4 is no option to select it, but on my Nexus 5x I can change the shape. Thx.

**Comment by intelligentcasanova** [comment]
Duplicate of #414. Please search issues before opening a new one.

**Comment by suphon-t** [comment]
@intelligentcasanova this is not a duplicate. He stated that he is running on O.

**Comment by SovsOgKartofler** [comment]
Running v1.0.1063 on a 6P O DP4, and i have the option available to me.

**Comment by JuliGplus** [comment]
@paphonb im on this version too, i reinstalled the launcher, i deleted every thing, but it doesn't appear, i don't know why, the animated clock works with the default square shape, like i said, on my Nexus 5x the option appears. (my  6p: angler-row-vn1 opp4.170623.014)

**Comment by JuliGplus** [comment]
I recognized that the option is missing in my real pixel launcher too, but it was there... So i googled a little bit. And you must have the developer options activate. I don't know why I disabled it.

**Comment by patsissons** [comment]
Is this mentioned anywhere? Had a hard time figuring out how to enable circle icons until I stumbled upon this closed issue.
