### ISSUE TITLE
Bug dock 

### ISSUE THREAD

**Issue by 01angel33** [Deletescape-Media/Lawnchair#4391]
### Describe the bug

I'm Spanish, sorry if I don't understand something. I have a bug that is like the applications transfers to the dock

### Expected behavior

Estaba ordenando mi pagina de inicio y veo que sucede eso

### Screenshots

![Screenshot_2024-05-15-07-40-44-255_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/128076784/f0c176de-03b4-42e3-b831-f433eaff0115)

### Device information

- Device: ,[Xiaomi MI 9]
- OS: [MIUI 12, Android 10 stock]
- App version: [Lawnchair 14 Beta 2]

### Additional context

After It crashes sometimes

**Comment by luckytoad999** [comment]
Haber soy español y te puedo ayudar si quieres pero la verdad es que no entiendo el problema

**Comment by 01angel33** [comment]
> Haber soy español y te puedo ayudar si quieres pero la verdad es que no entiendo el problema 

Que grande, x fin uno español. Lo que pasa esq tengo un Xiaomi mi 9 con MIUI 12 en stock y pues como que me traspasa la aplicación en el dock sabes, no sé, ya lo solucione más o menos pero bueno, quería reportar eso

**Comment by luckytoad999** [comment]
> > Haber soy español y te puedo ayudar si quieres pero la verdad es que no entiendo el problema 
> 
> Que grande, x fin uno español. Lo que pasa esq tengo un Xiaomi mi 9 con MIUI 12 en stock y pues como que me traspasa la aplicación en el dock sabes, no sé, ya lo solucione más o menos pero bueno, quería reportar eso

A vale perfecto, haber aun así prueba a reiniciar el launcher

**Comment by MrSluffy** [comment]
Please elaborate it more clearly, screenshot or screen Record will also help

Thanks

**Comment by 01angel33** [comment]
> > > Haber soy español y te puedo ayudar si quieres pero la verdad es que no entiendo el problema 
> > 
> > Que grande, x fin uno español. Lo que pasa esq tengo un Xiaomi mi 9 con MIUI 12 en stock y pues como que me traspasa la aplicación en el dock sabes, no sé, ya lo solucione más o menos pero bueno, quería reportar eso
> 
> A vale perfecto, haber aun así prueba a reiniciar el launcher 

Lo hice varias veces, lo que pasa es que como que se juntan las aplicaciones del dock con lo de demás sabes

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
