### ISSUE TITLE
issues on pixel 8a [BUG] 

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4393]
### Describe the bug

I installed it today on my pixel 8a, and there were a couple broken things:
1) Themed icons didn't work. When i try to apply themed icons, the entire phone goes black. I have to go to settings, and force stop the app to be able to go to my home screen again.
2) Changing the home screen app grid option makes the native pixel launcher bug out.

edit: I restarted the app, the phone, and I reinstalled lawnicons. It seems to be working now.

### Device information

- device: pixel 8a
- android 14 UD2A.240505.001.B1
- app version: beta 2

**Comment by MrSluffy** [comment]
done d20ef2a164f40ab756372ecdc93cfa5583625b93
