### ISSUE TITLE
[BUG] App crashes when chaging icons.

### ISSUE THREAD

**Issue by rkb87del4627** [Deletescape-Media/Lawnchair#4394]
### Describe the bug

The app crashes when i attempt to set icons to transparent background. it does not crash when im just changing icons.

### Steps to reproduce

1. Go to 'Home Settings'
2. Click on General
3. Scroll down to transparent themed icons and turn on.

### Expected behavior

it shouldnt crash and cause screen to blink  

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/169739772/a5d46377-2c52-40e0-b48d-79d625198f3a

### Device information

- Device: Samsung Galaxy Tab S9 Fe
- OS : Stock Android 14  (one Ui 6)
- App version: Lawnchair Beta 2

**Comment by MrSluffy** [comment]
The icons you using does not support transparent theme icon

It only support lawnicons atm
