### ISSUE TITLE
[BUG] it's shows charging in the at a glance even when it's not charging

### ISSUE THREAD

**Issue by XxRiKxX** [Deletescape-Media/Lawnchair#4400]
### Describe the bug

The at a glance shows that the device is charging when it's not.

### Expected behavior

To not show charging when it's not

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]
Poco f4. Infinity x rom Android 14. Lawnchair nightly latest

**Comment by MrSluffy** [comment]
Fixed latest nightly build
