### ISSUE TITLE
Google search widget not having lens

### ISSUE THREAD

**Issue by starbroker** [Deletescape-Media/Lawnchair#4407]
### Describe the feature

Google lens button in google search widget of lawnchair 

### Why would it be useful to add?

It is available in pixel devices .

### Did the feature exist in Lawnchair v2? (Play Store version)

NO

### Example(s)

.

**Comment by MrSluffy** [comment]
Install google lens in playstore

**Comment by N2022062** [comment]
change dock - search bar - search bar widget to google search bar 
BUT it too long  than pixel launcher
