### ISSUE TITLE
[BUG]  Lawnchair crashes when opening recents or swiping home from an app

### ISSUE THREAD

**Issue by Pizzabroodje** [Deletescape-Media/Lawnchair#4409]
### Describe the bug

Lawnchair crashes when opening recents or swiping home from an app. 
When within Lawnchair itself, the recents work fine.

On the previous version of the Nothing ROM it worked fine, but after updating to Nothing OS 2.5.5 not anymore (doesn't seem to be QPR2 though, as recents do switch to Lawnchair)

### Steps to reproduce

1. Open any app
2. Swipe home from that app, or swipe to open recents

### Expected behavior

Expected is that Lawnchair goes to the homepage when swiping home, or opens recents when doing the gesture for that. Instead of that it crashes.

### Device information

- Device: [Nothing Phone 2]
- OS: [Nothing OS 2.5.5 (By Arter97)]
- App version: [latest nightlys and 14 beta 2]

### Additional context

[Lawnchair (Debug) bug report 15 May 2024 040102.txt](https://github.com/LawnchairLauncher/lawnchair/files/15392626/Lawnchair.Debug.bug.report.15.May.2024.040102.txt)

**Comment by MrSluffy** [comment]
this issue should be fixed in latest beta 3 if still persists please reopen this issue
