### ISSUE TITLE
Add translation distributors in settings menu

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#441]
Can you icluded all the different laungange translators in your sub menu of Lawnchair's summery under App Icon Designer?😋😋

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
This would be a list of 177 persons, and as Crowdin doesn't provide a way to export the names of all translators this is not possible for now, I don't want to copy paste 177 or more names every time we create a new bigger release

**Comment by AxiK101** [comment]
You said you wouldn't but you did... Thanks!!

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
