### ISSUE TITLE
[BUG] Wdiget Search Keyboard not opened

### ISSUE THREAD

**Issue by awmalik45** [Deletescape-Media/Lawnchair#4410]
### Describe the bug

Then I try to open widget screen keyboard, its show and instantly hide

### Steps to reproduce

1. Long Click on Home Screen
2. Click on Widget
3. Click on Search Bar
4. Keyboard show and hide instantly 

### Expected behavior

Keyboard show and not hide util click on other views or backpressed

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by MrSluffy** [comment]
Fixed : 43a5cc701163dcbf9ad3d44879eae07c243a359d
