### ISSUE TITLE
Google feed not working 

### ISSUE THREAD

**Issue by starbroker** [Deletescape-Media/Lawnchair#4413]
### Describe the bug

Google not working 

### Expected behavior

It was working but when i switched to smartspacer and then back to google feed 
, google feed not working

### Device information

- Device: samsung s20 fe 5g
- OS: Android version 13
- App version: launcher 14 beta 2

**Comment by MrSluffy** [comment]
Please use alternative [aidlbridge](https://github.com/amirzaidi/AIDLBridge/releases)
