### ISSUE TITLE
[BUG] Cant change icon shape

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4414]
### Describe the bug

No matter what i do, im unable to change app icon shape from teardrop to any of the other ones.

Im on a pixel 6 with calyxos and no microG.

### Steps to reproduce

1. Go to settings
2. Click on theme
3. Click on icon shape
4. Try to change it
5. Doesn't work. (on my phone at least)

### Expected behavior

I expwcted to be able to change icon shape.

### Device information

- Device: Goolge Pixel 6
- OS: CalyxOS (Android 14)
- App version: 1.2.0.1884

**Comment by MrSluffy** [comment]
Please use latest version, old version is no support atm

**Comment by ghost** [comment]
Where do i find it? Github, f-droid, or what?

-------- Original Message --------

**Comment by MrSluffy** [comment]
https://lawnchair.app/downloads/
