### ISSUE TITLE
[BUG] Lawnchair 14 keeps crashing when opening home screen settings 

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4416]
### Describe the bug

Hello, since I downloaded Lawnchair 14 beta 2, it keeps crashing whenever opening home settings, I've tried clear data and uninstall, and the same issue 

### Steps to reproduce

1. Go to 'home screen'
2. Click on 'home settings 
3. Scroll down to 'settings'
java.lang.RuntimeException: Unable to stop activity {app.lawnchair/app.lawnchair.Launcher

### Expected behavior

Wanting to open settings and modify the home screen.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/137871802/cfe18e8d-8cf3-481e-9068-a37293704acd

### Device information

- Device: [Motorola e22]
- OS: [stock ROM Android version 12]
- App version: [14 beta 2]

### Additional context

https://katb.in/unofemuziye

**Comment by fisforfaheem** [comment]
+1

**Comment by Harshil-Mehta-13** [comment]
Yes it's also coming in my oneplus nord running android 12. please patch it bro.

**Comment by MrSluffy** [comment]
> Yes it's also coming in my oneplus nord running android 12. please patch it bro.

Have you tried latest debug build?
