### ISSUE TITLE
A request to add Android 14 like themed icons  Natively in the launcher [FEATURE] 

### ISSUE THREAD

**Issue by Debjit-007** [Deletescape-Media/Lawnchair#4420]
### Describe the feature

So if you have Android 14 and turn on the theme icons you will get the feature but in older Android like Android 13 or Android 12th you are not able to get the new themed icon feature but some launchers like smart launcher provide set natively

### Why would it be useful to add?

It will be useful to get the same look as Android 14 in older Android

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Uploading Screenshot_20240526-185126.png…]()
![Uploading Screenshot_20240526-070215.png…]()

**Comment by MrSluffy** [comment]
impl here : f131f287ee5d2446d8a6b4acaf0094a2aeb989bf
