### ISSUE TITLE
[FEATURE] NEW MATERIAL YOU COLORING LANGUAGE

### ISSUE THREAD

**Issue by Luel71** [Deletescape-Media/Lawnchair#4426]
### Describe the feature

Lawnchair's current material you design language is outdated. Still stuck on Android 12.

### Why would it be useful to add?

As I said it's outdated.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![68wgyvfj0vuc1](https://github.com/LawnchairLauncher/lawnchair/assets/171044895/fc6ad42f-d7b4-457b-ac74-ec512108e2bb)
![43j08bjvfavc1](https://github.com/LawnchairLauncher/lawnchair/assets/171044895/5b4852b1-1e21-454f-b01e-7684a4e185ad)
![Screenshot_20240528_165809_Sync](https://github.com/LawnchairLauncher/lawnchair/assets/171044895/e18688ac-f325-401a-88ca-062a66d1cdeb)
![nyfahn6ibdvc1](https://github.com/LawnchairLauncher/lawnchair/assets/171044895/c234128b-718c-4d87-88af-68fce4db61e9)

### Additional context

Lawnchair team does not seem to deal with issues much, please provide solutions to the issues when you have time.💚

**Comment by MrSluffy** [comment]
Can you drop the second wallpaper?

**Comment by Luel71** [comment]
> Can you drop the second wallpaper?

Sorry dude those pictures are not mine I found them from reddit. But I'll try to find it.

**Comment by MrSluffy** [comment]
impl here : f131f287ee5d2446d8a6b4acaf0094a2aeb989bf
