### ISSUE TITLE
Fastscroll Popup background color

### ISSUE THREAD

**Issue by intelligentcasanova** [Deletescape-Media/Lawnchair#443]
After enabling and disabling the "Extract accent color from wallpaper" setting, the app drawer scroll label still shows the previous accent colour from the wallpaper.

**Comment by nyancrimew** [comment]
This is probably just an issue in how we are applying this setting, makes the color go back to default though?

**Comment by intelligentcasanova** [comment]
The accent colour of all other items does indeed go back to the default blue, but only the scroll popup stays the colour picked from the wallpaper.

**Comment by intelligentcasanova** [comment]
Now I see it is working correctly with the latest build.
