### ISSUE TITLE
[BUG] Icons disappear on the home screen

### ISSUE THREAD

**Issue by spacemedia10** [Deletescape-Media/Lawnchair#4435]
### Describe the bug

Hello, when you return to the home screen in the launcher, the icons disappear, you have to unlock again, clear the applications again, sometimes you have to try 2-3 times, it is quite annoying. Is there any way to fix this? Phone model : oneplus 12 , Android version 14

### Steps to reproduce

When I return to the home screen, the icons at the bottom disappear

### Expected behavior

A more stable version with this bug resolved once and for all

### Screenshots

![IMG_20240530_100102](https://github.com/LawnchairLauncher/lawnchair/assets/40752978/6321ac0a-7713-4b92-8b51-d13a87d67b10)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]
Oneplus 12  , oxygenos ,  android 14 , lawnchair alpha 14 alpha 3

**Comment by MrSluffy** [comment]
There is no lawnchair alpha 14 alpha 3, send proper version of the lawnchair you use
