### ISSUE TITLE
[BUG] Lawnchair crashes on devices under SDK version Q

### ISSUE THREAD

**Issue by richardioo** [Deletescape-Media/Lawnchair#4448]
### Describe the bug

We get this crash:

```
Caused by java.lang.IllegalStateException: Unsupported SDK version
       at app.lawnchair.compat.LawnchairQuickstepCompat.<clinit>(LawnchairQuickstepCompat.kt:44)
       at com.android.launcher3.QuickstepTransitionManager.registerRemoteTransitions(QuickstepTransitionManager.java:1159)
       at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:242)
       at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:307)
       at com.android.launcher3.Launcher.onCreate(Launcher.java:541)
```

Because of this code in `LawnchairQuickstepCompat`:
```kotlin
val factory: QuickstepCompatFactory = when {
    ATLEAST_U -> QuickstepCompatFactoryVU()
    ATLEAST_T -> QuickstepCompatFactoryVT()
    ATLEAST_S -> QuickstepCompatFactoryVS()
    ATLEAST_R -> QuickstepCompatFactoryVR()
    ATLEAST_Q -> QuickstepCompatFactoryVQ()
    else -> error("Unsupported SDK version")
}
```

### Steps to reproduce

1. Get a device under Android Q
2. Open Lawnchair
3. It will crash

### Expected behavior

It should support under Q.

### Device information

- Device: [Google Pixel 6]
- OS: [stock ROM Android version 9.0]
- App version: [newest `14-dev`]

**Comment by SuperDragonXD** [comment]
Are you using QuickSwitch? Lawnchair 14 doesn't support QuickSwitch (or being a Recents provider) on Android 9.

**Comment by guniens** [comment]
> Are you using QuickSwitch? Lawnchair 14 doesn't support QuickSwitch (or being a Recents provider) on Android 9.

Does the latest nightly build work with QuickSwitch and Android 14 QPR2 (Pixel 8)
Thanks

**Comment by SuperDragonXD** [comment]
If I remember correctly, yes. Support for that was added in a PR.

Edit: #4417

**Comment by MrSluffy** [comment]
@Goooler can you check this pls? Thanks

**Comment by MrSluffy** [comment]
Are you using quickswitch? Recent compat only for A10-A14 atm
