### ISSUE TITLE
Implement a search function in icon selector again?

### ISSUE THREAD

**Issue by owengraven** [Deletescape-Media/Lawnchair#445]
I'm using the minimale icon pack, but on 818 I get the selector with a search function.

in the newest version, i only get a long list with all icons without search function.. which makes it extra time consuming to get the icons how I want them since it has different colored icons for the same app.

Thanks! awesome work!

**Comment by nyancrimew** [comment]
We desperately need a search function, but you can actually swipe right and left to browse the categories of your icon pack

**Comment by AxiK101** [comment]
Thats sure a must feature

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by owengraven** [comment]
Still takes far longer than via de icon pack app itself, but I do understand it's on the list. Could there be an option to choose between icon selector meanwhile? like a toggle if you want lawnchair to handle icon selection or leave it to the icon pack apps? 

If not, I understand, you're doing awesome work so keep on going, thanks a lot!

**Comment by nyancrimew** [comment]
Using the external icon selectors of the icon packs caused crashes in the past, this is the reason why we switched to our own implementation
