### ISSUE TITLE
Launcher shortcuts

### ISSUE THREAD

**Issue by silentgurdian** [Deletescape-Media/Lawnchair#446]
So launcher shortcuts got backported and they are looking amazing, However a few things seem like they need some modifications:-
1) I have a Moto G XT1033( 320 dpi) and the default rows assigned by lawnchair is 4. When I make it 5 the launcher shortcuts for the middle icon are cutoff at the edge. While 4 may be the default value I would like to get a 5 column grid without this shortcut cropping.
2) The shortcuts when added to the home screen as separate icons are quite small( almost the same size as the app icon on their lower right corner) and thus looks inconsistent with the other icon sizes.
3) Seems a few launcher shortcuts were not imported for some reason( like the maps shortcuts). These are present in Nova in android 5.1 so I am guessing they aren't exclusive to Nougat like the chrome or clock shortcuts. They were also not added after Nova included sesame and were available for a long time. A look into the issue would be great.

**Comment by Younes-L** [comment]
I have the same issue on build 1209

![](http://i.imgur.com/R6bV9If.png)


_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
