### ISSUE TITLE
[FEATURE] Material Ew

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [Deletescape-Media/Lawnchair#4460]
### Describe the feature

Add the option to disable Material You

### Why would it be useful to add?

Material You is pig disgusting

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

The halcyon era before the cross-eyed wunderkind at G**gle conjured up that UI abortion

### Additional context

Bottom text

**Comment by Luel71** [comment]
What in the actual fuck is this??
