### ISSUE TITLE
[BUG] App icons misplaced

### ISSUE THREAD

**Issue by 0xAbdiiii** [Deletescape-Media/Lawnchair#4465]
### Describe the bug

When i open an app from the home screen and close it by swiping up from the bottom of the screen, the app's icon gets placed in the top left corner of the home screen and until i tap anywhere on the screen, it's stuck there. It doesn't happen when using the left or right swipe gestures to close the app.

### Steps to reproduce

1. open an app
2. close the app with swipe up gesture
3. see that the app's icon is stuck on top left of the home screen

### Expected behavior

the app icon should retain it's previous position on the home screen.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/92924943/96928290-7674-4139-91f7-25ae419f6cb5

### Device information

- Device: Xiaomi Redmi A1+
- OS: Android 12 (GO edition)
- App version: 14

**Comment by iamtheabdi** [comment]
I forgot to mention that my device is not rooted and i don't use quick switch. Because the last time i had rooted (a few months ago), quick switch kept reverting my recents provider back to my default launcher after restarting device.

**Comment by su1cidalma9iac** [comment]
s

**Comment by 0xAbdiiii** [comment]
Closing this issue because it doesn't happen for me anymore with Quickswitch.

**Comment by pedrom34** [comment]
I think it's the same issue for me: #5081
