### ISSUE TITLE
[FEATURE] for lawnchair nightly update logs, dont include the dependancy updates

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#4466]
### Describe the feature

including dozens of dependency updates is just clutter, could you stash them away

### Why would it be useful to add?

prevent clutter

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

.

**Comment by osm0sis** [comment]
Only including the latest entry for each dependency would be ideal.
