### ISSUE TITLE
[BUG] Setting Lawnchair as the default Home app does not survive a reboot

### ISSUE THREAD

**Issue by RigacciOrg** [Deletescape-Media/Lawnchair#4469]
### Describe the bug

I installed the **Lawnchair** apk and set it as the default **Home app** from Android _Settings_ => _Apps & notifications_ => _Default apps_. Everything seems to work OK, but if I reboot the device, the stock Home app **BvLauncher** is restored.
This bug does not exist if I use other launchers, eg. the Rootless Pixel Launcher from F-Droid or the Home Launcher from the Google Play (NOTICE: in my opinion the Home Launcher app is an illegal fork of Lawnchair because it does not include info about being a derived work).

### Steps to reproduce

1. Install the Lawnchair.14.0.0.Beta.2.apk package.
2. Set it as the Home app from the Android Settings menu.
3. Reboot the device.
4. Check what is the currently selected Home app.

### Expected behavior

The Lawnchair app should remain the Home app selected.

### Device information

- Device: BlackView BV5300 Pro
- OS: Stock Android 13 with Magisk 26.4 root
- App version: Lawnchair.14.0.0.Beta.2.apk

**Comment by MrSluffy** [comment]
Lawnchair launcher doesn't handle setting the default app. This is controlled by the device itself.

**Comment by RigacciOrg** [comment]
I noticed some facts:

- The Lawnchair clone app named **Home Launcher** shows a pop-up at firts start, suggesting to set itself as the Home app. The Lawnchair app does not do that.
- If I go to _Apps & notifications_ => _Device & app notifications_, choose Lawnchair and then tap _Allow notification access_, I get the error **Restricted setting - For your security, this settings is currently unavailable**. The clone app Home Launcher instead can have all the access granted.

Can be this a limitation imposed by the Android o.s. because the app was installed from the apk package instead of the Google Play store? Or should the app ask the operating system some more permissions?

**Comment by RigacciOrg** [comment]
I found a workaround to let **_Lawnchair as default Home app_** to survive the reboot: install the **QuickSwitch** Magisk module and set Lawnchair as default Home app. This required Magisk and root permissions.

- Lawnchair 14.0.0.Beta.2
- Magisk 26.4
- QuickSwitch v4.0.2

**Comment by RigacciOrg** [comment]
It is required the **QuickSwitch 4.0.3** Magisk module to allow Lawnchair to be both the **Home app** and the **Recents provider** (the list of opened apps accessible through the soft navigation button of Android system bar).

The previous version 4.0.2 makes Lawnchair only to survive as Home app across reboots, but it cannot set it as the recents provider (which remained set to BvLauncher).

Notice that the QuickSwitch works in this way: it removes Lawnchair as "user installed" app and **put it into the Magisk module**. Then - at boot time - Magisk merges the Lawnchair app into the running system in _systemless_ mode, i.e. without modifying the actual system partition. Promoting Lawnchair as system app, allows the QuickSwitch module also to set it as the recents provider.

So the versions I used are:

- Lawnchair 14.0.0.Beta.2
- Magisk 26.4
- QuickSwitch v4.0.3
