### ISSUE TITLE
[BUG] Can't update to Lawnchair 14 Beta 2

### ISSUE THREAD

**Issue by Maks7594** [Deletescape-Media/Lawnchair#4471]
### Describe the bug

I cannot update Lawnchair as it shows an error message

### Steps to reproduce

1. Open the APK
2. Press Update

### Expected behavior

It should update the app

### Screenshots

![Screenshot_20240610-161845](https://github.com/LawnchairLauncher/lawnchair/assets/72873506/78835df2-4f3b-4d02-871e-8a1bc3aac3ec)

### Device information

- Device: moto g54 5G
- OS: Stock ROM Android 13
- App version: 12.1

**Comment by Maks7594** [comment]
The screenshot says something about the package being corrupted or something, I tried to download from both GitHub and the website

**Comment by 0xAbdiiii** [comment]
I can't find the discussion (or issue) that explained why this is happening but it was due to version numbering being messed up in the code.

Edit: #4361

**Comment by 0xAbdiiii** [comment]
For updating the app right now you would have to backup your Lawnchair config, uninstall the older version and install the Lawnchair 14 and restore your backup.

**Comment by Maks7594** [comment]
Thanks, it worked.
