### ISSUE TITLE
[FEATURE] Google search bar in app drawer

### ISSUE THREAD

**Issue by swarits1ngh** [Deletescape-Media/Lawnchair#4493]
### Describe the feature

Google search bar in app drawer like on e pixel because the current search bar looks boring.

### Why would it be useful to add?

Google search from drawer and access to voice search from drawer.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20240620-095958~2](https://github.com/LawnchairLauncher/lawnchair/assets/173330591/3b2b7a7a-804a-4ef5-9b86-603728904944)

**Comment by SuperDragonXD** [comment]
This has been implemented in the nightly builds.

**Comment by swarits1ngh** [comment]
I don't see it
