### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by OneX001** [Deletescape-Media/Lawnchair#4494]
### Describe the feature

Google Pixel control center 

### Why would it be useful to add?

For me it will replace my current control center one ui 3. it's pretty ugly, Since lawnchair did a great job replicating google pixel launcher so i would love to see the control center made for all others android device. I also hope it's customizable like allow to change or move the screen brightness slider, or even change the toggle icon. I hope i see this feature on neither lawnchair 15 or 14 beta 3. keep up the great work!

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![thread-168773453-2126007681684130957](https://github.com/LawnchairLauncher/lawnchair/assets/173374806/23c7cfd7-2009-4023-bd7f-39abaac1b25d)

**Comment by Luel71** [comment]
This isn't something lawnchair team should do. You can use custom roms or magysk modules for it but don't expect this from lawnchair.
