### ISSUE TITLE
[BUG] Tablet homescreen is a bit broken 

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#4498]
### Describe the bug

After the pull request "Add support for big screen devices" bugged the homescreen 

1st, Even without the search bar the labels don't show 
2nd, the dock icons are too close to each other 
3rd, The search bar is too far to the dock

### Steps to reproduce

1. Go to 'Lawnchair'
2. See error

### Expected behavior

The search bar is to be closer to the dock,
Icons should have labels
Icons should consistently be a bit more separated

### Screenshots

![Screenshot_20240622-205830](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/178373a1-5355-45c2-a850-e6b351105b5a)
![Screenshot_20240622-210641](https://github.com/LawnchairLauncher/lawnchair/assets/104182251/33f161fa-5188-4227-9262-929189b4f0b2)

### Device information

- Device: [Teclast T40 pro]
- OS: [stock ROM Android version 12.0]
- App version: [14 debug]

**Comment by Glitch808** [comment]
Same for me

**Comment by harmit03** [comment]
Would you mind sharing the screen shot of app drawer with 40% padding?
It seems the cause is padding related issue.Maybe...

**Comment by SeanDylan** [comment]
> Would you mind sharing the screen shot of app drawer with 40% padding? It seems the cause is padding related issue.Maybe...

Sorry if i'm late but what does it have to do with the app drawer?

**Comment by harmit03** [comment]
> > Would you mind sharing the screen shot of app drawer with 40% padding? It seems the cause is padding related issue.Maybe...
> 
> Sorry if i'm late but what does it have to do with the app drawer?

Recently a commit was done that broke  things like horizontal padding, i think this issue was also introduced by the same merge so I was just cross checking.

**Comment by SeanDylan** [comment]
> > > Would you mind sharing the screen shot of app drawer with 40% padding? It seems the cause is padding related issue.Maybe...
> > 
> > 
> > Sorry if i'm late but what does it have to do with the app drawer?
> 
> Recently a commit was done that broke things like horizontal padding, i think this issue was also introduced by the same merge so I was just cross checking.

![Screenshot_20240714-161840](https://github.com/user-attachments/assets/4ea547eb-77ed-4961-b3d2-2fab5c271291)
![Screenshot_20240714-161837](https://github.com/user-attachments/assets/9589017d-b8f9-4511-9564-bc9be912bf65)
Doesn't seem like anything

**Comment by SeanDylan** [comment]
![Screenshot_20240724-111814](https://github.com/user-attachments/assets/04c1e550-b7f3-433b-a16b-52876512e67e)
Oh wait sorry here is it
![Screenshot_20240724-111818](https://github.com/user-attachments/assets/0bd0cab8-2138-446b-aeae-1bd3c0efd1ba)
