### ISSUE TITLE
Color notification badges/dots

### ISSUE THREAD

**Issue by omartosca** [Deletescape-Media/Lawnchair#450]
Dots are still blue without the tinting from the icon.

It might be cool to have the option to tint the dots dynamically.

This are from Pixel Launcher O-DP2 and O-DP4.

![image](https://user-images.githubusercontent.com/1566591/29087628-2403a668-7c3c-11e7-80df-a43c9aebc392.png)

**Comment by suphon-t** [comment]
Dots colors are already tinted to icon's color.
