### ISSUE TITLE
[BUG] Widget font is to big 

### ISSUE THREAD

**Issue by ABH3-4** [Deletescape-Media/Lawnchair#4501]
### Describe the bug

when I add widgets like device care in Samsung the font is to big and even I resize it is still too big 

### Expected behavior

fix this issue with an update that when you resize the widget the font becomes smaller 

### Screenshots

![photo_2024-06-23_15-20-55](https://github.com/LawnchairLauncher/lawnchair/assets/135860563/0c5afa23-3fd0-403f-bbfe-a0921de4b10f)

### Device information

- Device: [Samsung S24 Ultra]
- OS: [OunUI 6.1]
- App version: [14 Beta 2]

**Comment by MrSluffy** [comment]
This is not handle by lawnchair but the app widget itself
