### ISSUE TITLE
[BUG] Adaptative M3 icons not showing up on Honor/MagicOS devices

### ISSUE THREAD

**Issue by tamarindojuice** [Deletescape-Media/Lawnchair#4502]
### Describe the bug

Same after enabling the toogle for M3 color icons under settings they work fine on stock launcher but don't appear on Lawnchair, still same colorful stock icons. 

### Expected behavior

M3 icons to display 

### Screenshots

![Screenshot_20240624_124057](https://github.com/LawnchairLauncher/lawnchair/assets/2258137/dacb450a-47b7-4b01-a340-ee5ef8215b52)

### Device information

- Device: Honor Magic 5 Lite
- OS: MagicbOS 8, Android 13
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by MrSluffy** [comment]
Please install lawnicons : https://lawnchair.app/downloads/

**Comment by tamarindojuice** [comment]
It's already installed, that was not the problem at all.
