### ISSUE TITLE
Main screen bug [BUG] 

### ISSUE THREAD

**Issue by Saci30** [Deletescape-Media/Lawnchair#4503]
### Describe the bug

For example I watch a video on YouTube and try to exit directly to main screen Icons glitch like on screen shots below 
8 really start to hate it , been using the app for almost a year 
Hope you guys fix it

Am on Samsung with android 13 ,OneUI 5.1

### Expected behavior

When try to exit to the main screen, Icons on the main page they glitch and appear top right side
Check video 

### Screenshots

![Screenshot_20240624175816~2](https://github.com/LawnchairLauncher/lawnchair/assets/173716712/004e6511-0e3b-48bf-b3dd-fc61ffa71dfc)
![Screenshot_20240624175921~2](https://github.com/LawnchairLauncher/lawnchair/assets/173716712/b2e83ecf-c69a-4431-8ba4-80c2afb487f0)
![Screenshot_20240624175839](https://github.com/LawnchairLauncher/lawnchair/assets/173716712/8400a52f-3692-4eb0-a5a7-b49f26322f64)

### Device information

- Device: [Samsung A51 5g]
- OS: [android 13 OneUI 5.1 ]
- App version: [ 14 beta 2 ]

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by Saci30** [comment]
Hi there
I'm not sure if I understand you well
If you talking about that issue which happens when exit to the home screen
YES is still happening

But I don't see any update for the app
