### ISSUE TITLE
[BUG]  Home Screen Icons

### ISSUE THREAD

**Issue by kelvinkad** [Deletescape-Media/Lawnchair#4506]
### Describe the bug

Whenever I change the grid of the home screen, Icons are reset and I lost all my customizations.

### Steps to reproduce

1. Organize some icons on the home screen as you desire
2. Go to "home settings" "home screen" "home screen grid" and change for example, from 5x5 to 5x8, just change this option.
4. go back to home screen and see the icons you just chose disappeared and replaced by default icons.

### Expected behavior

The home screen icons should always be the same I chose, even when I change grid. If my chamge doesn't fit on one screen, then automatically replaces the icons on two pages.

### Device information

- Device: Samsung Galaxy (I tested in 3 different models)
- Android 10; 13; 15

**Comment by 0xAbdiiii** [comment]
I'm using the latest nightly and this commit did not make any difference. :/
![Screenshot_20240818-202548](https://github.com/user-attachments/assets/d256879b-7368-43f1-b424-6d1bc308a512)
Before changing layout:
![Screenshot_20240818-202555](https://github.com/user-attachments/assets/53a4c26a-f047-4a86-bfae-1640ddbbb85c)
![Screenshot_20240818-202604](https://github.com/user-attachments/assets/1933801a-a46d-4581-9a0a-f96408df117f)
After changing layout:


I'm still losing my customization.

**Comment by 0xAbdiiii** [comment]
Unless, this bug is about something entirely different. In that case, do forgive me for not understanding what the issue is really about.

**Comment by 0xAbdiiii** [comment]
![Screenshot_20240818-203314](https://github.com/user-attachments/assets/cbd3da40-e035-4578-8baf-93d7536163b2)
It seems like the initial preview generated in settings is inaccurate. After applying the new grid size, i still have the same icons on home screen but their position is different (which idk if is the correct behavior).

![Screenshot_20240818-203347](https://github.com/user-attachments/assets/0ea16b79-93d4-479f-99fc-fec4b6b1af2c)
Before the commit, going back to previous grid settings after applying new grid settings would bring back my previous home screen setup iirc. But now it pushed the icons from my second home screen page to the first one. Now i have only one home screen page.

**Comment by MrSluffy** [comment]
this is entirely different bug, the position is causing by something called GridOccupancy, which will be fix in upcoming days https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/util/GridOccupancy.java#L8

**Comment by 0xAbdiiii** [comment]
Ah, i see!
