### ISSUE TITLE
Dark theme in Android O

### ISSUE THREAD

**Issue by Pedro1999** [Deletescape-Media/Lawnchair#451]
@deletescape @paphonb

It is possible extend dark theme to the settings menu, notification bar and quick settings? Because right now they are white with Android O DP4.

Apart spending more battery, it is not aesthetic and not fits with the dark theme that applies to other areas like the application drawer.

Thanks alot for your time and your nice Launcher.

![screenshot_20170808-204730](https://user-images.githubusercontent.com/30476929/29089430-7b8e038e-7c7c-11e7-9b49-5ad1c294a0ad.jpg)
![screenshot_20170808-204714](https://user-images.githubusercontent.com/30476929/29089437-7ff8871e-7c7c-11e7-8fd7-b9f00482974b.jpg)

**Comment by gcantoni** [comment]
They are a different thing: the launcher isn't linked to them.
