### ISSUE TITLE
Horizontal padding does not work in lawnchair nightly.

### ISSUE THREAD

**Issue by Udayg1** [Deletescape-Media/Lawnchair#4513]
### Describe the bug

Changing the horizontal padding value in app drawer settings in launcher does not work.

### Steps to reproduce

1. Go to home settings
2. Click on app drawer 
3. Scroll down to horizontal padding 
4. Changing it do nothing 

### Expected behavior

Should have changed the margin from the edges in app drawer. 

### Device information

- Device: Motorola moto g71
- OS: Android 12
- App version: lawnchair nightly d131945

**Comment by CoelacanthusHex** [comment]
And the horizontal padding seems be locked on very thin value.

**Comment by Bruhipie** [comment]
+1
Seems to not work in builds after June 20th. Dont know which commit exactly creates the issue

**Comment by SuperDragonXD** [comment]
I'll probably look into it later and fix this, but it is related to https://github.com/LawnchairLauncher/lawnchair/commit/930d0e6cd751b42d4af53603c631491b8e8852f6 (specifically the changes in `Launcher.java`: `allAppsLeftRightPadding`).

**Comment by Udayg1** [comment]
lawnchair/res/values/config.xml - line 133 value has something to do with this problem I believe.

**Comment by harmit03** [comment]
> lawnchair/res/values/config.xml - line 133 value has something to do with this problem I believe.

have you tried making any changes yourself and testing?
if so does it solve the issue?
