### ISSUE TITLE
Weather Underground provider

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#452]
Please consider adding the option to use Weather underground as provider with a personal key. Google awareness api is really not that great or accurate. Wunderground is super accurate and matches the temp shown in Google app almost 100% of the time (at least for me)

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by devang98** [comment]
Or you can also consider Accuweather, however I am loving the Google API, this is now my daily driver
