### ISSUE TITLE
[FEATURE] 'com.android.quickstep.RecentsActivity' not working while One UI home can do

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#4521]
### Describe the feature

add recent activity with work in Samsung and can replace default Launcher

### Why would it be useful to add?

Recent Activity

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

com.android.quickstep.RecentsSettingsActivity

**Comment by NekoMimiOfficial** [comment]
It exists?
Even on the latest nightly, you'll need to use quickswitch 3.3.4 since the latest version doesn't work consistently 

I'm using lawnchair 14.0.0-20240626 as my current recents provider on Samsung one UI 2

**Comment by MrSluffy** [comment]
Use quickswitch!

**Comment by ghost** [comment]
@NekoMimiOfficial @MrSluffy , THANKS!!!
