### ISSUE TITLE
[FEATURE] Add option to make folder popup's background transparent 

### ISSUE THREAD

**Issue by onlylove943** [Deletescape-Media/Lawnchair#4522]
### Describe the feature

An opacity slider for folder popup's background. There's a opacity slider for icon background already but when you tap the folder and it pops up, the background is still in gray color. Please add an option for that.
![Screenshot_20240628-041241_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/20055460/cc02208d-bdf9-4e32-9f8c-601eedfb631b)

### Why would it be useful to add?

It would make home screen much better to see and would be great to make a transparent theme.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20240628-041241_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/20055460/d53cf548-3786-463b-9fb7-2def242e7249)
Gray background should be transparent or blur.

**Comment by tom22k** [comment]
Or even just being able to change the colour.
