### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Th3-C0der** [Deletescape-Media/Lawnchair#4525]
### Describe the bug

I am unable to give Lawnchair notification access.

### Steps to reproduce

Try to give lawnchair notification access

### Expected behavior

.

### Screenshots

![Screenshot_20240628-154410](https://github.com/LawnchairLauncher/lawnchair/assets/152851285/83a3729c-eee0-471c-943c-85c8ac86f071)

### Device information

- OS: Android 14
- App version: 14.Dev.#1043

**Comment by Bruhipie** [comment]
This is not a bug. You need to turn off Restricted Setting by going into App Info of Lawnchair, select the menu button (top right 3 dots) and select turn off restricted setting.
Suggestion: before creating an issue, try searching your problem on the internet. Helps reducing non-bug issues.
