### ISSUE TITLE
[BUG] Horizontal Padding is broken

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4527]
### Describe the bug

App drawer Horizontal Padding is broken

### Steps to reproduce

App drawer > Horizontal padding

### Expected behavior

Work as intended.

### Device information

- Device: Samsung F22
- OS: Android 13 One UI 5.1
- App version: Latest debug build 1046

**Comment by Unofficial-Life** [comment]
I think its mainly due to this commit 930d0e6

devs please take a look once

**Comment by harmit03** [comment]
Maybe there is something hin this file 

...lawnchair/src/app/lawnchair/allapps/views/SearchResultRightLeftIcon.kt

I am not sure but just seems like it.

**Comment by harmit03** [comment]
Duplicate of #4513
