### ISSUE TITLE
Accent color 

### ISSUE THREAD

**Issue by a220** [Deletescape-Media/Lawnchair#453]
I'm sorry if this is a dumb question or has been answered already. Is there plans to have the accent color customizable? For some reason my accent color just wants to stay blue, even when I select extract accent color from wallpaper, most of the time it just gives me blue 

Other than that, great update. much more stable than 818. Thank you

**Comment by Willet1978** [comment]
I will agree with this. The blue color accent of Nexus completely does not fit with teal of Nexus.

**Comment by a220** [comment]
yeah a simple hex color code support would go a long way with the accent color... also maybe hex color code support for pixel indicator arrow (above dock)

**Comment by John-Gee** [comment]
I was looking for that and I'm happy to say it's in the current beta.
