### ISSUE TITLE
[BUG] Searching hidden apps with two or more chars not working  Lawnchair 14 dev

### ISSUE THREAD

**Issue by vrpcse** [Deletescape-Media/Lawnchair#4531]
### Describe the bug

app search not listing the hidden app when typing more characters in search box. 

### Steps to reproduce

Steps to reproduce
1. Open app drawer
2. Type a hidden app's name, example 'chess' char by character

Observations:
1. Hidden app chess was displayed when typed 'ch'
2. Hidden app chess was not displayinf when typed 'chess'
Same with another hidden app hotstar. Displayed when typing 'h', not displayed with 'ho'. . 

### Expected behavior

Expectations:
Searched hidden app listed when typed character sequence is matching. 

### Screenshots

![Screenshot_20240630-223844](https://github.com/LawnchairLauncher/lawnchair/assets/67140701/55d4addf-7163-45ed-b8c6-6f77876c0086)
![Screenshot_20240630-223850](https://github.com/LawnchairLauncher/lawnchair/assets/67140701/cc1a5a5c-6bd0-4a32-bf74-dab81c143473)

### Device information

- Device: Google Pixel 6a
- OS: stock ROM Android 15 beta 3
- App version: Lawnchair 14 Dev # 1049 build

**Comment by Unofficial-Life** [comment]
its not for hidden but for any app

edit : it seems to me that when a result should show only one application it just goes behind the search bar layout and as well doesn't open with quick open(enter)

**Comment by Unofficial-Life** [comment]
Seems like turning off web suggestions from the drawer search settings fixed it

**Comment by vrpcse** [comment]
Web suggestions option was already turned off when I observed this issue.

**Comment by HyperWinX** [comment]
Same issue. Android 11

**Comment by Illustar0** [comment]
Same issue. Android 14

**Comment by HyperWinX** [comment]
Also issues like i have app "Tubular", and when i type "T" there is no "Tubular" in search results

**Comment by SuperDragonXD** [comment]
Hello. This issue should be fixed now in the later nightly builds (in relating to Lawnchair not showing single app results). Feel free to comment if it isn't.

**Comment by vrpcse** [comment]
Hi, 
I checked with #1217 and it looked okay. 
Today I can't get any hidden apps in the search results even though the 'show hidden app in search tesults' is set to always.

**Comment by SuperDragonXD** [comment]
Have you tried restarting Lawnchair first?

**Comment by vrpcse** [comment]
After restarting Lawnchair, able to see hidden apps in search results. I will update here if I encounter the issue again.
