### ISSUE TITLE
Crash caused by now playing + yt music (also happening with yt music clients)

### ISSUE THREAD

**Issue by AlessandroGalvan** [Deletescape-Media/Lawnchair#4537]
### Describe the bug

as in the title, lawnchair (tried the stable, 14 beta 2 and nightly) keeps crashing because of yt music or any other yt music client. Very frustrating.

### Steps to reproduce

Play music on yt music
enable "now playing" (and notification access)
go to launcher and should crash, if it doesn't crash try spamming the home button.

### Expected behavior

display "now playing" with the correct info, just lile with spotify

### Device information

- Device: Samsung Galaxy s21+
- OS: one ui 6.1, android 14
- App version: 14 beta 2 (tried all of them tho)

**Comment by AlessandroGalvan** [comment]
realized the problem is with the notification access. I never changed setup since months so I really don't know what is causing this, only thing changed is i installed the june security update days ago but the bug presented itself only today. I will update if i find the cause.
Edit: wiped all notifications and now it's fixed. Welp

**Comment by Om-hr** [comment]
Similar problem happened to me when I play any music on Spotify, vimusic or spotube. it stops in the middle of the songs & crashes, the notification keeps showing me but music stops cuz the app is stopped maybe in background..

If you find any solution pls tell me ...

I'm on Android 14

**Comment by MrSluffy** [comment]
Please send crashlog!
