### ISSUE TITLE
Black screen and inaccessible app drawer

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [Deletescape-Media/Lawnchair#4539]
### Describe the bug

Occasionally, but seemingly inevitably, when opening the app drawer at a random point, it won't visibly open the drawer, but instead turn my wallpaper black and become stuck, pressing the home screen apps opens completely unrelated apps, and I cannot swipe left or right to other pages of the home screen. The issue does not resolve itself unless I restart my phone or go to settings and switch the default home app to something else and then back again to lawn chair. This seems to occur with increasing frequency, and is now happening about every 2-3 hours for me, and a few days ago it was just twice a day roughly. 

### Steps to reproduce

Steps to reproduce the behavior: (it's intermittent)
1. Go to home screen 
2. Scroll up to open app drawer
3. See error

### Expected behavior

It opens the app drawer visibly, does not set my wallpaper to black, and generally just works 

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/115472706/528fc807-ec8d-42bc-8d4c-14ae0db13c32

### Device information

- Device: Google Pixel 8 Pro 
- OS: Stock Pixel Android 14 (AP2A.240605.024)
- App version: Tested on both 14 Beta 2 and July 2nd Nightly

**Comment by Unofficial-Life** [comment]
try with wallpaper depth effect off 

> lawnchair settings > home screen

**Comment by SimplyAnotherAnon** [comment]
> try with wallpaper depth effect off 
> 
> > lawnchair settings > home screen

This seems to have fixed the issue, will update if it reappears again but thanks for the workaround!

**Comment by SimplyAnotherAnon** [comment]
> try with wallpaper depth effect off 
> 
> > lawnchair settings > home screen

So, unfortunately - the issue persists. The only change with turning off wallpaper depth effect is now the home screen wallpaper does not turn black - it just stays the same. But, the actual issue of being unable to open the app drawer, apps on the home screen disappearing for no reason, and opening completely unrelated apps, well, it's still an issue that occurs even with that setting off.

**Comment by jp1995** [comment]
I'm on Pixel 7a and this issue has been annoying me since release of v14. However, for me I can resolve it by cycling the power button and when I unlock the phone it's fixed. No idea what's causing it though.

**Comment by SimplyAnotherAnon** [comment]
Is this gonna get fixed at some point because lawnchair is currently literally unusable, I cannot set it as my main launcher due to this unaddressed major bug

**Comment by c4tz** [comment]
This seems to be the same issue as https://github.com/LawnchairLauncher/lawnchair/issues/3934

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
