### ISSUE TITLE
No indication of what number UI slider refers to

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4548]
### Describe the bug

In 'Drawer search -> Web suggestions', the slider "Maximum number of suggestions in search results" shows no numbers so the user does not know what number each slider setting refers to.

### Steps to reproduce

1. Go to 'Drawer search'
2. Select 'Search algorithm -> Global search'
3. Click 'Web suggestions'
4. Enable 'Web suggestions' in pop-up
5. See "Maximum number of suggestions in search results'... slider has no corresponding numbers (perhaps due to string being too long?)

### Expected behavior

Slider should show its corresponding setting number to the right-hand side of the label.

### Screenshots

![Screenshot_2024-07-06-10-39-09-995_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/160293965/067af65c-d445-4f52-a16f-be16b420aea9)

### Device information

- Device: POCO X5 5G
- OS: HyperOS 1.0.4.0.UMPEUXM (latest stock)
- App version: Lawnchair.Debug.14-dev.Nightly-CI_1060-c15a758.apk

**Comment by tgex0** [comment]
Just checked... works fine with a shorter string (numbers appear to the right of the string as expected).

(Similar problem to https://github.com/LawnchairLauncher/lawnchair/issues/4547 but different string.)

However, my phone uses a European/EEA stock ROM with English (United Kingdom) language/locale but I noticed that Lawnchair uses the strings from the values-en-rCA/strings.xml (Canadian English) file. If this is not intentional, please let me know and I'll open a new bug report. Thanks.

**Comment by sarojpanda44** [comment]
It's visible for other options like Apps & Shortcuts, People and Files. There also UI string are long

**Comment by sarojpanda44** [comment]
If the UI string jumps to second line then it's messed up. I think it's fixable by giving fixed width to the number field on the right side.
