### ISSUE TITLE
[BUG] First search result icon sometimes (but not always) highlighted with oval background

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4549]
### Describe the bug

In the drawer search, the first search result icon is sometimes (but not always) highlighted with an oval background.
It is inconsistent and I'm not sure if it should be there at all.

### Steps to reproduce

1. Go to the app drawer
2. Type "li" in the search bar
3. The Lightroom icon shows up first in the search results (fine so far)
4. Type "lig" in the search bar
5. The Lightroom icon is now highlighted with an oval background (even though it is not the only app beginning with "lig")

NB These steps apply to my own device's apps and the screenshots I've supplied but I expect similar results would be seen on other devices.

### Expected behavior

Unsure when (or if at all) the highlighting should be used. It doesn't seem to follow any logical pattern (at least to me) at the moment.

### Screenshots

![Screenshot_2024-07-06-10-41-00-940_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/160293965/ce318e32-6d78-400b-89d8-97e54e5ce429)
![Screenshot_2024-07-06-10-41-04-601_app lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/160293965/d9ea48f2-8081-434c-8d8b-a9b54bdfdd58)

### Device information

- Device: POCO X5 5G
- OS: HyperOS 1.0.4.0.UMPEUXM (latest stock)
- App version: Lawnchair.Debug.14-dev.Nightly-CI_1060-c15a758.apk

**Comment by MrSluffy** [comment]
@SuperDragonXD can you check? Thanks

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
