### ISSUE TITLE
Drawer search only finding upper case first letter

### ISSUE THREAD

**Issue by JonnyTech** [Deletescape-Media/Lawnchair#455]
Searching for an app with the drawer search bar only matches the first character as upper case regardless of whether an upper or lower case character is entered. Example: l matches Lawnchair but not lawnchair

**Comment by Younes-L** [comment]
It works fine here, what build are you on ? 
1065 here

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JonnyTech** [comment]
The latest release from https://github.com/deletescape-media/lawnchair/releases is 1063

Where do I get 1065 from?

**Comment by JonnyTech** [comment]
The image below is an example:

![search](https://user-images.githubusercontent.com/3584732/29117191-3f9b5ba0-7cf5-11e7-88fa-1816661c94e5.gif)

No C**a**mer**a**, C**a**lcul**a**tor, G**a**llery, File M**a**n**a**ger, Se**a**rch, ...

**Comment by nyancrimew** [comment]
As far as I understand the search algorithm this is intended behaviour to keep the results clutter free. Nobody would actually search for "a" and expect "Camera" to appear as a result. I might consider rewriting the search algorithm in the future and sorting by relevance, but for now this doesn't have high enough priority.

**Comment by JonnyTech** [comment]
But why does it find D**A**Vdroid and Osm**A**nd?

**Comment by nyancrimew** [comment]
Because upper case letters followed by another uppper case letter usually indicate an abbrevation (where each letter stands for a single word) and upper case letters in the middle of a word indicate combined words

**Comment by JonnyTech** [comment]
Thanks for the clarification. If you do ever find the time, it would be great so see the search function have an option for partial name matching like [FAST](https://github.com/ligi/FAST) does.
