### ISSUE TITLE
App shortcuts indicator 

### ISSUE THREAD

**Issue by ACHOKAMAN** [Deletescape-Media/Lawnchair#457]
Knowing which app has app shortcuts and which doesn't can be very tough...but since this app make it is easier,and it is user-friendly ..i think it will be awesome to have an indicator to show which apps have shortcuts just the way adw,yahoo aviate launcher and action launcher....i know you don't like to duplicate things but is a nice exclusive feature for convenience and beauty too

**Comment by suphon-t** [comment]
No. This would make the homescreen cluttered.
