### ISSUE TITLE
[FEATURE] TOGGLE FOR DISABLING THE APP SHADOW 

### ISSUE THREAD

**Issue by Luel71** [Deletescape-Media/Lawnchair#4570]
### Describe the feature

A toggle for disabling the shadows behind the app icons.

### Why would it be useful to add?

Looks awful when I use light mode on 

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20240715_160017_Lawnchair](https://github.com/user-attachments/assets/18aaf883-34f3-44d6-a52b-b7543dde1a70)
Top one has no shadows, bottom one has.

### Additional context

Thanks in advance.

**Comment by Unofficial-Life** [comment]
Those are not shadows but app icon background to remove them there is already a setting for it, General > Transparent themed icons (it works with lawniacons)

**Comment by Luel71** [comment]
> Those are not shadows but app icon background to remove them there is already a setting for it, General > Transparent themed icons (it works with lawniacons)

Dude I don't mean that... Look at the yt music icon closely.
![Screenshot_20240717_001334_Lawnchair](https://github.com/user-attachments/assets/dd87cacb-edb9-4af5-8a08-0324542161c7)
Ofc I'm not talking about the icon background

**Comment by Luel71** [comment]
Some icons have it some of em don't.

**Comment by Luel71** [comment]
Don't look at the inside of the icon look outside

**Comment by Unofficial-Life** [comment]
![IMG_20240717_141329_248](https://github.com/user-attachments/assets/e6e855e6-1e33-49b1-800b-c86b70f64589)
If you mean this then this is app icon background

**Comment by Unofficial-Life** [comment]
And I think you mean filled icons not shadows?

**Comment by Luel71** [comment]
> And I think you mean filled icons not shadows?

No

**Comment by Luel71** [comment]
![Screenshot_20240717_123659_Nova Launcher](https://github.com/user-attachments/assets/94edb315-1615-4e15-98b0-08c3065c5ea0)

Dude it's clear as a sunny day that icons has shadows behind them...

**Comment by Luel71** [comment]
![Screenshot_20240717_123615_Nova Launcher](https://github.com/user-attachments/assets/9878914c-f8a7-4668-848e-bee52a8958e4)

There's a toggle for that in Nova launcher

**Comment by Unofficial-Life** [comment]
Why can't you believe those are app icon background and to remove them i already told you the settings for it if its name is shadow in nova doesn't mean its same on all + if you see on any other launcher they all have it because that's how adaptive icons are

**Comment by Luel71** [comment]
> Why can't you believe those are app icon background and to remove them i already told you the settings for it if its name is shadow in nova doesn't mean its same on all + if you see on any other launcher they all have it because that's how adaptive icons are

Dude are you slow or sumn??
![Screenshot_20240717_135821_Lawnchair](https://github.com/user-attachments/assets/b8ad21aa-1265-4138-a6a0-09a406d4a507)

I'm not talking about this...

**Comment by Luel71** [comment]
![Screenshot_20240717_140227_Nova Launcher](https://github.com/user-attachments/assets/a6d9e7fd-f5f0-4312-b969-286ce13de475)
![Screenshot_20240717_140258_Nova Launcher](https://github.com/user-attachments/assets/59496452-77ea-49f9-bc3b-c5ef154e100b)

You clearly can see the difference...

Top one has the "shadows" option enabled.
Bottom one disabled

**Comment by gsture** [comment]
I can clearly see the shadows and depending on the situation the icons look better/more clear without them.

Would be a useful option.

**Comment by Luel71** [comment]
> I can clearly see the shadows and depending on the situation the icons look better/more clear without them.
> 
> Would be a useful option.

Finally someone understands.
