### ISSUE TITLE
[BUG] Widgets on inactive pages become contorted after screen rotation changes in an app

### ISSUE THREAD

**Issue by pikuse** [Deletescape-Media/Lawnchair#4571]
### Describe the bug

If you change the screen rotation, (for example, in an app like YouTube) most widgets on inactive pages get tiny or contorted.

### Steps to reproduce

1. Rotate the screen in your current app (not Lawnchair)
2. Go to home
3. Swipe to inactive pages (e.g. not the one you landed on when you did step 2)
4. Widgets look weird

### Expected behavior

The widgets look normal. (not like the attachments below)

### Screenshots

![Screenshot_2024-07-16-00-14-37-19_ddf77c0951adecdce93c9ca870602d33](https://github.com/user-attachments/assets/54f2c2c3-6bc8-461e-bc93-f1deac06d45f)

https://github.com/user-attachments/assets/39bb6578-c4fb-42c0-a166-35ecaa35a03a

### Device information

- Device: OnePlus Nord 3
- OS: OxygenOS 14.0.0.520
- App version: 14 (Nightly-9572494)

### Additional context

Supposed to be fixed by #4461.
Widget settings seem to not do much.

**Comment by SimplyAnotherAnon** [comment]
Can confirm on Android 14 Pixel 8 Pro, same issue, latest Nightly.

**Comment by noadc218** [comment]
I wasn't sure what was triggering it until I saw this, but I'm having the exact same issue on my Pixel 7, running Android 14, build AP2A.240705.004, Lawnchair version 14, nightly build 1120

**Comment by dontobi** [comment]
I can confirm this bug. I have the same problem on my Google Pixel 8 (Android 14) and the Google Photos widget.

**Comment by pikuse** [comment]
Seems to be fixed as of latest nightly builds, but I don't know which one exactly.
