### ISSUE TITLE
[BUG] [Nightly build ]app layout shift

### ISSUE THREAD

**Issue by Lost-Saint** [Deletescape-Media/Lawnchair#4576]
### Describe the bug

App layout shift

https://github.com/user-attachments/assets/1e4c6a9a-34a5-4e16-8bc1-5f2bb2f65c0c

### Steps to reproduce

1. Click on a natural landscape app
2. Click home button
3. Layout shift

### Expected behavior

No layout shift

### Device information

- Device: Samsung Galaxy 21 ultra
- sreen res: 1440 x 3200 pixels, 20:9 ratio (~515 ppi density)
- OS: stock android 14
- App version: Lawnchair 14.Dev. (# 1084)

**Comment by MrSluffy** [comment]
Can you add more description on this?, seems looks fine to me

**Comment by Lost-Saint** [comment]
what type of info you need?

**Comment by MrSluffy** [comment]
fixed in `15-dev`
