### ISSUE TITLE
Calendar live icon not updating

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#458]
Probably mentioned before but most of the times this icon nit updating at 00:00, or not at all, only if i refresh icon database. Yes, i have enabled circular icons, yes, i have test it with icon packs too. Not working

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
One hour after midnight and still calendar icon not updated...
![](http://i.imgur.com/E5ctgOP.jpg)

![](http://i.imgur.com/9c3I9zZ.png)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
For me it never updates :/
Using Google calendar. (It does update on Nova and Pixel)

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dondrejohnson5** [comment]
The same delay happens to me too

**Comment by callmemulo** [comment]
what i did, i reset the icon. then it change.
