### ISSUE TITLE
[BUG] Drawer search closes keyboard when last character is deleted

### ISSUE THREAD

**Issue by navilite** [Deletescape-Media/Lawnchair#4580]
### Describe the bug

When searching the app drawer, deleting all the characters closes the keyboard automatically.

### Steps to reproduce

1. Open the app drawer
2. Type in the Search box
3. Delete all the characters in the search box
4. See that the keyboard disappears

### Expected behavior

The keyboard should not be automatically dismissed when the last character is deleted.

### Device information

- Device: Samsung Galaxy S6 Lite (SM-P610)
- OS: stock ROM Android version 13.0
- App version: Lawnchair.Debug.14-dev.Nightly-CI_1092-493c49e

### Additional context

The Pixel launcher doesn't dismiss the keyboard when the final character is deleted. This is a minor irritation, particularly if you mistype the first character.

**Comment by sarojpanda44** [comment]
This issue has been fixed and is working. Latest tested on 14.Dev.#1097.
Not sure if it's broken in nightly version

**Comment by sarojpanda44** [comment]
Check issue 
https://github.com/LawnchairLauncher/lawnchair/issues/4286

**Comment by MrSluffy** [comment]
fixed 43a5cc701163dcbf9ad3d44879eae07c243a359d
