### ISSUE TITLE
Not working on DP4

### ISSUE THREAD

**Issue by cyberon** [Deletescape-Media/Lawnchair#459]
Latest couple versions are not working on the Nexus 6P running Android O DP4.

**Comment by iH8c0ff33** [comment]
@cyberon Which versions? I had no problems with 1.1.0.1075 and 1.1.0.1076

**Comment by cyberon** [comment]
Both versions you mentioned.

**Comment by hassie-dash** [comment]
In what way exactly?

**Comment by cyberon** [comment]
Fresh install and it won't start.

**Comment by hassie-dash** [comment]
Can you provide a screenshot of the error which you are getting?

**Comment by cyberon** [comment]
Not getting any error, it's just a empty screen.

**Comment by SovsOgKartofler** [comment]
I'm on a Nexus 6P running vanilla Android O DP4 with Lawnchair v1.0.1063 and everything works as expected.

You should probably provide more information about you setup if you expect the devs to be able to reproduce.

**Comment by cyberon** [comment]
Workaround is to install 964, 1.0.9992 then I can update with any newest version.
