### ISSUE TITLE
Global search need to tap icon, tapping text opens search

### ISSUE THREAD

**Issue by D3SOX** [Deletescape-Media/Lawnchair#4591]
### Describe the bug

When searching for an app and the global search is enabled tapping the text opens a search, only tapping the icon opens the app

### Steps to reproduce

1. Enable global search
2. Search for an installed app
3. Tap the text and it opens a search
4. Tap the icon and it opens the app

### Expected behavior

Always open the app

### Screenshots

https://github.com/user-attachments/assets/28e45cd2-7854-47c4-93c0-5099de5ac45b

### Device information

- Device: Google Pixel 8 Pro
- OS: CalyxOS 5.9.0 (Android 14)
- App version: 14.Dev.(# 1009) (https://github.com/LawnchairLauncher/lawnchair/commit/4044c71)

**Comment by MrSluffy** [comment]
Caused here : cf18b4bf7925f33eb2d223a81f38af1e5d190105

**Comment by SuperDragonXD** [comment]
As a note, I have yet to pushed my newer changes to fix this issue. Will probably do that later.
