### ISSUE TITLE
[BUG] Lawnchair crashing when opening the Wallpaper and style settings 

### ISSUE THREAD

**Issue by EmpireMatrix** [Deletescape-Media/Lawnchair#4606]
### Describe the bug

I'm under an /e/OS official release. Lawnchair keeps crashing when I open the Wallpaper and Style setting.

### Steps to reproduce

1-Go to 'Settings>Wallpaper and Style'
2-Lawnchair immediately crashes
Or
1-Long click on the home page
2-choose wallpaper and style

### Expected behavior

Lawnchair do not close unexpectedly

### Device information

- Device: Samsung Galaxy S7
- OS: /e/OS 2.2-s Android version 12.0
- App version: 14 beta 2 and nightly (both crash)

### Additional context

https://katb.in/iqaxuyeqiqi (14 beta 2)
https://katb.in/gufozisasar (nightly)

**Comment by MrSluffy** [comment]
Seems like it got conflicted in your default launcher, I believed e/os is use launcher3 too, can you share me which e/os version you using, if possible send e/os source code, I'll take a look into it Thanks

**Comment by EmpireMatrix** [comment]
Hi @MrSluffy 

Thanks for tour answer, here are the information you're asking for:

/e/OS version: 2.2-s-20240716417774-stable-herolte

Source code repo: https://gitlab.e.foundation/e/os/releases/-/releases/v2.2-s

This bug has been been occurring for a while, even with previous version of the ROM. /e/ is, indeed, using launcher3 but only for the app switch. The default launcher is Bliss. For an unknown reason it is impossible to use launcher3 as the home launcher because it's already integrated but remains unused somehow.

Edit: here's the link to the dev version for my specific device : https://images.ecloud.global/dev/herolte/

**Comment by EmpireMatrix** [comment]
Bug is still occuring in 14 beta 3, do you need that bug report too @MrSluffy ?

**Comment by MrSluffy** [comment]
hi can you try in `15-dev` build thanks

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
