### ISSUE TITLE
Assistant button size..

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#461]
Can you make it a bit shorter? I think both buttons are way too long one next to another.. That's the default screen density, 360 dpi
![](http://i.imgur.com/Ay0BhTz.png)
 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
No, the buttons are exactly the size they are meant to be, and the way it was designed by google
