### ISSUE TITLE
[FEATURE] App drawer background blur

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4614]
### Describe the feature

Background blur in app drawer improves app drawer aesthetics.

### Why would it be useful to add?

For aesthetics.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20240801_202126_Smart Launcher](https://github.com/user-attachments/assets/2536c8ee-2847-4e5c-8bf8-0e47fbc2c7bd)
Smart launcher background blur

![Screenshot_20240801_203212_Lawnchair](https://github.com/user-attachments/assets/8cb4c2ee-de37-4fb2-9aae-071cb3977147)
Lawnchair 14 app drawer opacity 

Smart launcher app drawer looks much better.

**Comment by sarojpanda44** [comment]
This will be a nice welcome feature
