### ISSUE TITLE
[BUG] Not setting latest wallpaper color to icon pack

### ISSUE THREAD

**Issue by sarojpanda44** [Deletescape-Media/Lawnchair#4615]
### Describe the bug

The launcher is not setting the latest wallpaper color to the icon packs when switching from dark mode to light mode and vice versa.
I'm using dynamic wallpaper which changes color from daylight greenish to blueish night theme. When the dark mode changes the launcher is changing the colors in the launcher settings, dock, app drawer but is not updating the color in the icon pack. I need to manually restart the launcher to fix the icon pack color.
Check screenshots.

![Screenshot_20240802-084928](https://github.com/user-attachments/assets/57900971-b557-4303-95e2-720ea87773ad)
![Screenshot_20240802-085127](https://github.com/user-attachments/assets/dbd67870-318d-43fb-896f-70def9022564)
![Screenshot_20240802-132053](https://github.com/user-attachments/assets/ee2d605b-fd21-469e-b7a6-62b7782f6c32)

### Steps to reproduce

1. Use "Chill live wallpaper" or anything similar which changes color of wallpaper with time.
2. Wait for the evening or when the night theme kicks in. If not locked, lock the phone and unlock it. The launcher should change theme to match the wallpaper.
3. The colors of the icon pack doesn't match to the wallpaper color.
4. Go to launcher Home settings and 3 dots, Restart launcher.
5. The icons should now pick the wallpaper color.

### Expected behavior

The Launcher should look for the latest wallpaper colors when changing the theme color.

### Device information

- Device: [Google Pixel 7 pro]
- OS: [stock ROM Android version 14.0]
- App version: [Lawnchair debug 14.Dev#1125]
- Wallpaper: Chill Live Wallpaper

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
