### ISSUE TITLE
[BUG] notification settings bottom popup overlaps with bottom bar

### ISSUE THREAD

**Issue by coffandro** [Deletescape-Media/Lawnchair#4617]
### Describe the bug

I try to enable notification dots, it gives an error about settings, settings button is underneath system button bar.

### Steps to reproduce

1. Go to 'home settings'
2. Click on 'general'
3. Scroll down to 'notification dots'

### Expected behavior

The popup shows up and allows me to change the settinga

### Screenshots

![Screenshot_20240803-062850_Lawnchair](https://github.com/user-attachments/assets/807e723e-b077-416b-a1a5-d44ac2108100)

### Device information

- Device: FP4
- OS: Lineage OS 21, Android 14
- App versio: 14.0 rc2

**Comment by RivanParmar** [comment]
This issue can be closed now, as it has been fixed in the latest Nightly build with #4289
