### ISSUE TITLE
[BUG] [nightly] Settings - Dock untranslated

### ISSUE THREAD

**Issue by Stephan-P** [Deletescape-Media/Lawnchair#4618]
### Describe the bug

The menu option Settings - Dock is untranslated

### Steps to reproduce

1. Go to Settings
2. Menu option Dock is not translated
3. Select Dock and notice that the title Dock is not translated as well. Probably the same string.
4. In [Crowdin](https://lawnchair.crowdin.com/), the string Dock does not exist

### Expected behavior

In [Crowdin](https://lawnchair.crowdin.com/), the string Dock should be available for translation

### Screenshots

![Screenshot_20240803-211335](https://github.com/user-attachments/assets/26d24e2c-8b59-4ae7-b325-2a304d8382da)

### Device information

- Device: Google Pixel 7a
- OS: GrapheneOS 2024072800
- App version: 14.dev build 1139

**Comment by MrSluffy** [comment]
Please check latest 15-dev : 
![image](https://github.com/user-attachments/assets/3cb2c7c2-2b30-42c2-b5a1-39680cb548a9)
