### ISSUE TITLE
Google calander tasks icon mixed up with weather icon in at a glance widget.

### ISSUE THREAD

**Issue by Udayg1** [Deletescape-Media/Lawnchair#4634]
### Describe the bug

Adding a task in calander shows up fine in at a glance widget but I have weather enabled whose icon gets mixed up with that of that task's.

### Expected behavior

Both should have their own icons.

### Screenshots

![Screenshot_20240807-185939 (1)](https://github.com/user-attachments/assets/3e7c596f-6593-449d-82d1-647668887db7)
![Screenshot_20240807-185935 (1)](https://github.com/user-attachments/assets/9909c4ea-69c1-4ab2-8d0e-b91e287cf60e)

### Device information

- Device: moto g71 
- OS: Android version 12.0
- App version: nightly

**Comment by MrSluffy** [comment]
please report it in smartspacer thanks
