### ISSUE TITLE
Clock widget auto-resizes [BUG] 

### ISSUE THREAD

**Issue by bendbound** [Deletescape-Media/Lawnchair#4637]
### Describe the bug

Android clock widget resizes to a small grid size automatically.

### Steps to reproduce

Place stock clock widget on home screen with medium size (e.g., 2x3).
Continue normal behavior, including lock/unlock.
At some point, notice that the clock widget has resized to minimum size.
Editing the widget by adjusting size handles resets to correct size.

### Expected behavior

Size stays the same regardless of device use.

### Device information

- Device: Pixel 6a
- OS: stock ROM Android version 14
- App version: 14 beta 2 (website download)

**Comment by derwerbebriefkasten** [comment]
Sounds like that portrait/landscape issue [https://github.com/LawnchairLauncher/lawnchair/issues/4389]

Same issue here
Device: Pixel 7a
OS: stock ROM Android version 14
App version: 14 beta 2 (website download), nightly from 2024-08-17, Lawnchair.Debug.14-dev.Nightly-CI_1225-d20ef2a.apk

**Comment by MrSluffy** [comment]
fixed in `15-dev`
