### ISSUE TITLE
[BUG]  call button not working correctly on contact search

### ISSUE THREAD

**Issue by Pauloesfola** [Deletescape-Media/Lawnchair#4638]
### Describe the bug

On APP DRAWER, when you search for a contact, the Phone Call button is not working correctly. After pressing the phone icon, the phone APP opens with an incorrect telephone number.

### Steps to reproduce

1. Go to APP DRAWER 
2. Click on the Search field
3. Search for a contact name
4. Press the phone ícon to Call that contact
5. See the phone number that appears on the Call screen...

### Expected behavior

When you press the phone ícon, should appear the correct phone number for that contact

### Screenshots

![Screenshot_20240808-235853~2](https://github.com/user-attachments/assets/5ff9c642-ad2f-40b6-8f15-9871cf055f44)

### Device information

- Device: Google Pixel 7a
- OS: Android version 14
- App version: 14.Dev.(1173)

**Comment by MrSluffy** [comment]
This is known, to fix this you need to clear the existing dialed number, since if you go back to phone app the number is still there. so if you try to call, the number you selected will be appended in the existing. hope this helps

**Comment by Pauloesfola** [comment]
It doesn't make sense. It should be corrected...

**Comment by MrSluffy** [comment]
lawnchair doesn't have control on the phone app unfortunately, if there's a programmatically way you can up here so we can take a look into it

**Comment by Pauloesfola** [comment]
The problem is with the phone number that Lawnchair is sending to the phone app. It is sending a set of wrong numbers along with the contact's phone number. Where are the wrong numbers coming from?

![Screenshot_20240810-174931](https://github.com/user-attachments/assets/4ccf1dfa-0c42-405b-bf74-61dcca234805)

**Comment by Pauloesfola** [comment]
I think the problem is with the PLUS sign in the international dial code of the contact's phone number. 

I think Lawnchair is not interpreting +351 correctly. 

If the contact's phone number is saved with the international prefix dial code (for example, +351918345678), Lawnchair sends an incorrect number to the phone application...

Can you test this situation?
