### ISSUE TITLE
"failed to get app filter" error

### ISSUE THREAD

**Issue by lpen21** [Deletescape-Media/Lawnchair#464]
When changing icon pack  get toast with above mentioned error. I am on latest build 1.1.0.1079. not sure how long this bug has been there.

**Comment by guest4711** [comment]
See also #542 which could be related to.

**Comment by lpen21** [comment]
I uninstalled/reinstalled Lawnchair and issue is resolved

**Comment by guest4711** [comment]
So you may close it... Thanks.
