### ISSUE TITLE
[BUG] crash creating backup

### ISSUE THREAD

**Issue by TheNeutrinoRaged** [Deletescape-Media/Lawnchair#4645]
### Describe the bug

Lawnchair crashes when try to create a backup

### Steps to reproduce

1. Go to home settings
2. Click on three dots
2. Click on create backup
4. crash with error java.lang.SecurityException: Op READ_MEDIA_IMAGES ignore for package app.lawnchair

### Expected behavior

Create a screenshot screen should show up, instead lawnchair restarts

### Screenshots

![image](https://github.com/user-attachments/assets/5b362e6f-5ce4-4a61-8104-3dfd2ba4bf56)

### Device information

- Device: Google Pixel 8a
- OS: Android 15 beta 4.1 AP31.240617.010
- App version: Version 14 Beta 2

### Additional context

[Lawnchair bug report 10 Aug 2024 15_38_37.txt](https://github.com/user-attachments/files/16569955/Lawnchair.bug.report.10.Aug.2024.15_38_37.txt)

**Comment by atuy1219** [comment]
While I'm not a developer, I've encountered a similar issue and would like to suggest a potential solution.

Please try navigating to Home Settings > Three-dot menu > App Info > Permissions > Photos & Videos and changing the setting to "Always allow all". This may resolve the problem.

**Comment by MrSluffy** [comment]
this should be fixed now in latest dev build
