### ISSUE TITLE
[BUG] Light/dark switch is not working properly on system themed icons

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4652]
### Describe the bug

Title 

### Expected behavior

Should work fine.

### Screenshots

https://github.com/user-attachments/assets/03f7ead4-d2c5-4e09-aed1-182e3eb56fbc

### Device information

- Device: Samsung F22 
- OS: One UI 5.1
- App version: Latest nightly build 1209

**Comment by sarojpanda44** [comment]
It works fine for me in debug version. Icons change theme from dark to light and reverse then Dark mode toggle changes.

**Comment by ujwal246** [comment]
I'm here specifically talking about system themed icons

Select system icons as Homescreen and lockscreen  themed icons

**Comment by sarojpanda44** [comment]
I'm not sure if I 'm understanding you correctly. But the themed icons change to dark shade when I enable dark theme.

https://github.com/user-attachments/assets/f57b77bb-8624-4341-9b62-55bc466ac181

**Comment by ujwal246** [comment]
You are using material you iconpack which works normally.
I'm talking about device "system icons".
Anyway I got the solution these are in hand of lawnchair. They can't fix this. I'm closing this issue.
![Screenshot_20240820_181225_Lawnchair](https://github.com/user-attachments/assets/e6a7fba8-a2fc-48ce-9dac-e18b27e4e6f4)

**Comment by sarojpanda44** [comment]
> I'm here specifically talking about system themed icons
> 
> Select system icons as Homescreen and lockscreen themed icons

Here you might have meant with "Home screen & app drawer"?

**Comment by sarojpanda44** [comment]
![Screenshot_20240820-145110](https://github.com/user-attachments/assets/6679bd61-e66c-4252-bc7c-67fec7eb6954)
I have same setting

**Comment by sarojpanda44** [comment]
To get the icons follow your system dark theme setting, you need to select the icon pack that supports the dark and light theme. In my case I have Pix Material You Light/Dark selected.

**Comment by ujwal246** [comment]
Select "system icons" (lawnchair image)
then check light/dark switch
