### ISSUE TITLE
Widget drawer is too white despite black theme

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#466]

**Comment by suphon-t** [comment]
More descriptions?

**Comment by Younes-L** [comment]
@paphonb I'm using black theme everywhere but the drawer looks like this :/

![](http://i.imgur.com/8yTe4fS.png)

As far as I remember it wasn't always like this, not a big deal but worth pointing out ?

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
The widget drawer looks this way regardless of which theme you're using. This could possibly be improved by styling per theme.
