### ISSUE TITLE
[BUG] "Maximum number of apps in search results" not used (always 5)

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4662]
### Describe the bug

The "Maximum number of apps in search results" does not seem to be used. It always seems to be 5, no matter what the slider is set at.

### Steps to reproduce

1. Go to 'Drawer search'
2. Click on 'Apps & Shortcuts'
3. Change the "Maximum number of apps in search results" slider to something other than 5
4. Click 'Apply'
5. Try a search and you'll see the maximum number of apps in search results is always 5

### Expected behavior

The "Maximum number of apps in search results" should reflect the corresponding slider's value (and not always be 5).

### Screenshots

N/A

### Device information

- Device: POCO X5 5G
- OS: Xiaomi HyperOS 1.0.5.0 UMPEUXM (Stock, up-to-date)
- App version: Lawnchair Nightly Lawnchair.Debug.14-dev.Nightly-CI_1225-d20ef2a.apk

**Comment by Mudit-pip** [comment]
i want to fix this issue.
