### ISSUE TITLE
[BUG] [Nightly] home screen, dock and app box twitching/vibrating

### ISSUE THREAD

**Issue by Farajo001** [Deletescape-Media/Lawnchair#4665]
### Describe the bug

When opening the launcher the home screen twitches and vibrates and the app box as well

### Steps to reproduce

1. Open the launcher
2. That's it

### Expected behavior

I was expecting the launcher to not vibrate and work like it should

### Screenshots

https://github.com/user-attachments/assets/206978db-944d-44e1-9dfc-72e926e5b5bf

### Device information

- Device: Moto E5 Play
- OS: stock ROM Android version 8.1
- App version: Nightly 14

**Comment by MrSluffy** [comment]
@Goooler do you have any idea what causing this?

**Comment by Goooler** [comment]
No.

**Comment by Farajo001** [comment]
Forgot to mention that it's Android Go 8.1, my E5 Play is the South American version, codename Pettyl

**Comment by Farajo001** [comment]
@Goooler does that help or do I need to tell you that my phone has a dp of 376 which by changing it, kinda solves the problem but then the home screen disappears, only the app box and the pop up work

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
