### ISSUE TITLE
[BUG] Heavy lag/screen tearing in nightly

### ISSUE THREAD

**Issue by gsture** [Deletescape-Media/Lawnchair#4667]
### Describe the bug

I experience heavy lag/screen tearing when scrolling anywhere in the app with the lawnchair 14 Nightly. Beta 2 does not have this and is smooth. 

### Steps to reproduce

1. Anywhere in app. 

### Expected behavior

Normal smooth scrolling like with lawnchair 14 beta 2.

### Device information

- Device: Google Pixel 8
- OS: GraoheneOS 14 (AP2A.240805.005)
- App version: Lawnchair 14 Nightly up to 18-08-2024

**Comment by SuperDragonXD** [comment]
Nightly builds are built differently from normal builds: they are debuggable, which means that they have developed-related code that slows performance. Thus, this is intentional.
