### ISSUE TITLE
[BUG] Switching Dock on affects App Drawer layout

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4669]
### Describe the bug

Switching the Dock on affects the icon size, label size, horizontal padding (and row height?) of the icons in the app drawer. (The change in row height might just be a result of everything else shrinking.)

### Steps to reproduce

1. Check App Drawer layout
2. Go to 'Home Settings -> Dock'
3. Switch 'Show dock' on 
4. Check App Drawer layout once again and notice the differences (see screenshots below for examples)

### Expected behavior

I would expect switching the Dock on to not affect the App Drawer layout..

### Screenshots

With 'Show dock' switched off:

![Screenshot_2024-08-18-19-36-23-416_app lawnchair](https://github.com/user-attachments/assets/e9d75c44-3dbc-419a-ac8c-7b57c9a55504)

With 'Show dock' switched on:

![Screenshot_2024-08-18-19-36-39-037_app lawnchair](https://github.com/user-attachments/assets/90ec7118-2b1c-496a-aca5-617a980d074e)

### Device information

- Device: POCO X5 5G
- OS: Xiaomi HyperOS 1.0.5.0 UMPEUXM (latest stock)
- App version: Nightly Lawnchair.Debug.14-dev.Nightly-CI_1237-97a62ef.apk

### Additional context

This bug sounds similar to #4260 but #4260 does not explicitly mention the 'Show dock' switch (and I can't actually replicate #4260 as described on my own phone).

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by tgex0** [comment]
> Can you try and check latest nightly if still persists reopen this issue

Checked on 28106e6. Looks like it's fixed. Thank you!
