### ISSUE TITLE
[FEATURE] ADD "OPEN RECENTS" TO GESTURES PAGE

### ISSUE THREAD

**Issue by RouxTheCaster** [Deletescape-Media/Lawnchair#4671]
### Describe the feature

Add an option to use "recent apps" when pressing home button

### Why would it be useful to add?

For the ones that cant use Quickswitch for gestures.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20240819_124055_Nova Launcher](https://github.com/user-attachments/assets/49441f60-b529-4f39-b7d1-90942470683f)

### Additional context

Thanks in advance.

**Comment by ghost** [comment]
This would be so good. The launcher Kvaesitso has this feature, and it makes getting to the recents page so much faster. Instead of swiping up and holding for a second or two, swiping up on the home button/nav bar immediately opens the recents page
