### ISSUE TITLE
[FEATURE] Can you reduce memory usage for lawnchair? (at least make launchair optimized for old devices)

### ISSUE THREAD

**Issue by FarizGD** [Deletescape-Media/Lawnchair#4675]
### Describe the feature

optimization

### Why would it be useful to add?

old *cough* device.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

idk

### Additional context

...

**Comment by MrSluffy** [comment]
closes : https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly
