### ISSUE TITLE
Weather not updating

### ISSUE THREAD

**Issue by ellenswamy** [Deletescape-Media/Lawnchair#468]
google awareness api is working, but does not seem to be updating. When i click to switch from the date and back to weather it does update. but will not do it automatically. Running dp4 and location is turned on. Any thoughts?

Thanks

**Comment by nyancrimew** [comment]
Our weather updating function isn't that stable right now, it is easily possible that it just fails, we definetly need to improve this

**Comment by pabdel86** [comment]
That is weird. OpenWeatherMap works better for me, because it match with the real temperature, but it does NOT updating automatically. i have to click to switch to the date, back and it does updated. :(
Nexus 6 with Android 7.1.1

**Comment by RIPT1DE** [comment]
Just a suggestion: you could set the awareness api weather to update when Google now is refreshed or is updated automatically because that is also how it happens in the pixel launcher. 

EDIT: Just found out that what I said was not possible. However you could use the fence api to get a callback when weather is updated.

**Comment by pabdel86** [comment]
Now, i got an error when i try to click at date to switch to weather. Just remains the date instead the temperature. OpenWeatherMap stop working. Regarding Google Awareness API does not work correctly neither.

**Comment by ildar** [comment]
Did you think of unlinking weather update from whatever awareness API?
Maybe is better to update on New connection available + Update timeout, just like all other weather apps do?

**Comment by ekerazha** [comment]
This issue makes the weather "widget" useless, it's like having a static image.

**Comment by ildar** [comment]
https://github.com/Deletescape-Media/Lawnchair/issues/468
Please search before you post.

**Comment by ekerazha** [comment]
Guess where I posted

**Comment by Brottweiler** [comment]
Personally I've experienced that the weather updates maybe once or twice a day. In morning it was showing 0C, until the middle of the day when it switched to 9C, and has been on 9C since then even if the current temp in google weather app says 4C.
