### ISSUE TITLE
[BUG] Not able to add widgets on home screen

### ISSUE THREAD

**Issue by starbroker** [Deletescape-Media/Lawnchair#4682]
### Describe the bug

https://github.com/user-attachments/assets/b89b3c06-ece4-4cad-9675-2f8f991bd9cc

Widget not showing on home screen

### Steps to reproduce

I have restarted lawnchair but not able to fix
All permissions are already allowed for widgets

### Expected behavior

Widget showing on home screen.

### Device information

- Device: Samsung S20 FE 5G
- OS: One UI 5.1
- App version: 14 beta

**Comment by DhananjayPorwal** [comment]
I'm having a similar problem, when I tried to add widget, the app crashes.

**Comment by FortyGazelle700** [comment]
I have found that you can't add widgets that  popup with a configuration window, other widgets work without this work.

**Comment by CuriousLocky** [comment]
I am having the same issue with the latest nightly build

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by CuriousLocky** [comment]
> Can you try and check latest nightly if still persists reopen this issue

I'm still having this issue in the latest build (1781) @MrSluffy
