### ISSUE TITLE
[BUG] No App opening and closing animations

### ISSUE THREAD

**Issue by msalmonw** [Deletescape-Media/Lawnchair#4683]
### Describe the bug

I installed the version 14 on my pixel 8 yesterday just to be able to install custom icons. The problem I noticed after a while is that there are no app opening and closing animations. After tapping an app, it doesn't fluidly get bigger and bigger to occupy the whole screen (default launcher behavior), rather it's an instant switch to the app in full screen. Same goes for when backing out from the app.

### Steps to reproduce

1. Tap an app from home screen/app drawer

### Expected behavior

Clear and fluid opening and closing animations like the default pixel launcher

### Device information

- Device: Pixel 8
- OS: Android 14
- App version: 14 Alpha 2

**Comment by BlueGradientHorizon** [comment]
Did you enable Quickstep for Lawnchair via QuickSwitch? See [FAQ](https://lawnchair.app/faq/#the-app-openclose-animations-look-buggy)

**Comment by msalmonw** [comment]
oh, my bad then for not reading the FAQ. so it is not possible to have the proper animations on a non-rooted device? I cannot root my device because most banking apps do not work then so that is a bummer.

**Comment by MrSluffy** [comment]
Can you try and check latest nightly and quickswtch if still persists reopen this issue
