### ISSUE TITLE
[BUG] Beta 3 - App Symbol Scale gets not applied to widgets like before

### ISSUE THREAD

**Issue by L3-N0X** [Deletescape-Media/Lawnchair#4684]
### Describe the bug

I have scaling of Apps enabled in the settings and previously (Beta 2) the widgets were the same size than the app icons. But now they seem to stay at 100% scale.
The issue applies to all the widget sizes

### Steps to reproduce

1. Add any widget
2. Use a App Icon Scale of more than 100%
3. Compare resize box of widgets with app icon size/check if apps line up with widgets

### Expected behavior

The widgets should line up with the app icons. So the Box of the widget should also scale with the app icon scale so it is possible to create widgets which will line up with the app icons

### Screenshots

Before (see Do not Disturb and Wifi Widget from KWGT) [Beta 2]
![Screenshot_20240817-162722_Lawnchair](https://github.com/user-attachments/assets/dc2c5894-3a2d-4bc0-a929-0715cef08d3b)

After [Beta 3]
![Screenshot_20240821-162945_Lawnchair](https://github.com/user-attachments/assets/f24866e9-2860-40e9-9107-d003ba8da16f)

### Device information

- Device: Poco M4 Pro 4G
- OS: Android 13, Lineage OS 20
- App version:  v14.0.0-beta3

**Comment by kosmoz** [comment]
I'm not sure if this is related, but I see a similar change, even with scale at 100%. It looks like the widget width is now constrained to the app icon size, while previously it was more like the width of the app icon text. Widget height seems unaffected, which results in a "squished" appearance.

![Screenshot_20240822-065827_1](https://github.com/user-attachments/assets/8a6534de-286f-46f4-ae35-c3ddd9006cc6)

**Comment by MrSluffy** [comment]
Enable force widget resize and remove size constraint in Lawnchair Settings -> Home

**Comment by kosmoz** [comment]
> Enable force widget resize and remove size constraint in Lawnchair Settings -> Home

Unfortunately, that doesn't seem to resolve this issue for me.
