### ISSUE TITLE
Lawnchair 14 beta 3 crashing 

### ISSUE THREAD

**Issue by lohithsingh** [Deletescape-Media/Lawnchair#4685]
### Describe the bug

The latest update is crashing on the lenovo tab m10hd

### Expected behavior

The app to open

### Screenshots

Crash report
https://katb.in/ividudojeco

### Device information
Lenovo tab M10 HD 
Stock Android 11
14 beta 3

**Comment by ivanddiaz** [comment]
I got the exact same problem, using a Lenovo YT-X705F running Android 10.

[Lawnchair bug report 27 ago. 2024 100916 p. m..txt](https://github.com/user-attachments/files/16786290/Lawnchair.bug.report.27.ago.2024.100916.p.m.txt)

**Comment by ivanddiaz** [comment]
Dear @MrSluffy,

It seems the fix was released but that's still not merged in 14-dev due to CI test failure: https://github.com/LawnchairLauncher/lawnchair/actions/runs/10517402334/job/29141433416

Thank you!
