### ISSUE TITLE
[Bug] Google Feed doesn't work

### ISSUE THREAD

**Issue by unk0wn-u53r** [Deletescape-Media/Lawnchair#4698]
### Describe the bug

On the latest Dev #1264 from Apkmirror, Google Feed is working native without any bridge.. 🙃 I think in the latest Lawnchair 14 Beta 3 there's something messed up with the code.

### Steps to reproduce

Want just open the Google Feed

### Expected behavior

Google Feed is enabled in the Options, so the Feed should be opening but nothing happen when you swipe right.

### Device information

- Device: [Redmagic 9 Pro]
- OS: [Android 14, Security Patch from May]
- App version: [14 Beta 3]

**Comment by sarojpanda44** [comment]
Same issue for me. Working fine in Dev version but broken in Beta 3

**Comment by tgex0** [comment]
I'm pretty sure I read somewhere that the feed requires that the APK be a 'debug' version to work (like the dev version from APKMirror). The official Lawnchair 14 Beta 3 APK is a 'release' APK (not a 'debug' APK).
Try installing Lawnfeed 3 (which _is_ a 'debug' APK) alongside Lawnchair 14 Beta 3: https://github.com/LawnchairLauncher/lawnfeed/releases/download/v3.0.0/Lawnfeed.3.apk

**Comment by bdodroid** [comment]
Lawnchair 14 beta 3 + Lawnfeed doesn't work unfortunately. 
The debug build from APK mirror is the only way I have found to use Google feed so far.

**Comment by tgex0** [comment]
I know this is just a workaround rather than an actual bugfix but try aidlbridge or pixelbridge: https://github.com/amirzaidi/AIDLBridge/releases/tag/v3
Both work for me with Lawnchair 14 Beta 3 (just checked).

**Comment by ciferkey** [comment]
It would not let me install pixelbridge apk as I got the message:
> App not installed as package appears to be invalid.

But I can confirm I was able to install the aidlbridge apk, select it as a feed provider in setting and access it on Lawnchair 14 Beta 3.

**Comment by Lehmanator** [comment]
> I know this is just a workaround rather than an actual bugfix but try aidlbridge or pixelbridge: https://github.com/amirzaidi/AIDLBridge/releases/tag/v3 Both work for me with Lawnchair 14 Beta 3 (just checked).

What do these APKs do?

**Comment by tgex0** [comment]
> What do these APKs do?

I don't know the ins and outs but they are basically working alternatives to [Lawnfeed ](https://github.com/LawnchairLauncher/lawnfeed)(which seems to be broken at the moment).
