### ISSUE TITLE
[BUG] Widgets of pineapple lock screen aren't visible on home screen.

### ISSUE THREAD

**Issue by Attigliuzzo** [Deletescape-Media/Lawnchair#4699]
### Describe the bug

I use Pineapple lock screen from F-droid, its widgets are full usable with stock launchers of my devices.
Under lawnchair when i try to add them to my home they don't appear on my home.

### Steps to reproduce

1. install Pineapple lock screen from F-Droid;
2. add its widget to the home screen;
3. nothing happens.

### Expected behavior

The widgets should have been added to the homepage.

### Device information

I use lawnchair 14.0.0 beta3 on:

-Xiaomi Pad 6 and Hyperos 1.0.9;
-Poco F3 and Crdroid 10.5.

**Comment by nailerNAS** [comment]
Might be related, same issue with Greenify, 'Sleep and Hibernate' widget. Also Tasker's task widgets can't be put in folders, both things worked on previous F-Droid release.

**Comment by MrSluffy** [comment]
even in pixel launcher seems can't add too!
