### ISSUE TITLE
Lawnchair auto-update function

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#470]
Maybe add an engine for the launcher to automatically download and install updates? Rhat whould be very helpful and time saver. Thanks

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
Lawnchair has such a function but it currently doesn't work. 

Stable releases will soon be on the Play Store

**Comment by fonix232** [comment]
I think I'll be removing it, and re-add Firebase logging before going on the Play Store.

**Comment by AxiK101** [comment]
Great news!! Playstore edition 😎🎆

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guest4711** [comment]
It would be much more better to have it on f-droid (see #240)

**Comment by fonix232** [comment]
We'll be moving to the Play Store soon, so this is not important anymore.
