### ISSUE TITLE
[BUG] App icons glitch after exiting/minimizing app

### ISSUE THREAD

**Issue by Atmosquare13** [Deletescape-Media/Lawnchair#4701]
### Describe the bug

I have just downloaded the Lawnchair 14 beta 3 and i noticed this bug that has been bugging me. When i minimize/exit the app in the background, the app icons glitch out and change their location. I was hoping if there was a fix for this If i didn't know.

### Steps to reproduce

1. Go in an app with landscape orientation 
2. Minimize/exit the app in the background
3. See error

### Expected behavior

App icons remain in their location.

### Screenshots

Video of the bug:
https://youtu.be/dhnVjBkCz0E?si=HI87mJKVFwZo4nC6

### Device information

- Device: Infinix Note 30
- OS: XOS 14
- App version: 14 beta 3

**Comment by MrSluffy** [comment]
if you want to have smooth closing animation I recommend using quickswitch or such
