### ISSUE TITLE
[BUG] Cropped Smartspacer in At a Glance

### ISSUE THREAD

**Issue by sarojpanda44** [Deletescape-Media/Lawnchair#4704]
### Describe the bug

The top margin of Smartspacer is cropped in latest Dev version and Beta 3 version.

### Steps to reproduce

Install and configure Smartspacer as At a glance provider and configure Music target to test.
When you play music the album art is visible but the top part is cropped.

It was not like this before.

### Expected behavior

The top margin should not crop any part of the Smartspacer.

### Screenshots
![Screenshot_20240822-171603](https://github.com/user-attachments/assets/80f1fbd1-6e54-47a1-b65f-9fc524ce13b8)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by SuperDragonXD** [comment]
Hello,

The cropped album art is not a bug but a feature of the Music target of smartspacer:

![Screenshot showing Music target setting, showing the album art option](https://github.com/user-attachments/assets/10277e1f-200c-48a0-9e99-bd38e0bb7a29)

Enable the option "Use square album art" if you don't wish for it to be cropped.

**Comment by sarojpanda44** [comment]
Are you kidding me?? I have been using Lawnchair and Smartspacer for months and the cropping mentioned in the Smartspacer notes is not what's I'm reporting. Screenshots attached from two different Dev versions

Dev 1175
![markup_1000052749](https://github.com/user-attachments/assets/26daea7b-1194-4300-96c3-b6b858f1452a)

Dev 1241
![markup_1000052750](https://github.com/user-attachments/assets/9aa6feb7-c64a-4b6f-bf0c-c681d9a6b1e7)

Observe the album art top curve corners are not smooth.

**Comment by sarojpanda44** [comment]
@SuperDragonXD please reopen the issue.

**Comment by SuperDragonXD** [comment]
Oh I see, apologies for that. This might be somewhat related to #4703, so re-opening.

A before-and-after image would've been helpful as well.

**Comment by sarojpanda44** [comment]
It's now fixed. Thanks
![Screenshot_20240824-235920](https://github.com/user-attachments/assets/3b7325a8-24ce-4ea3-8bc7-dc452e16d62d)
