### ISSUE TITLE
[BUG] Crashing After Every Reboot

### ISSUE THREAD

**Issue by YouSummoner** [Deletescape-Media/Lawnchair#4707]
### Describe the bug

After Lawnchair is set as default in QuickSwitch, it crashes after every reboot.

Crash Report: https://paste.crdroid.net/4l0u0a

### Steps to reproduce

1. Set Lawnchair as default in QuickSwitch 
2. Reboot the device 

### Expected behavior

Lawnchair should open normally.

### Device information

- Device: [Realme XT]
- OS: [Matrixx Android 14 QPR2]
- App version: [14 Beta 3 and Nightly-CI_1278-11ebddb and 14.0.0-20240823 by Goooler]

**Comment by MrSluffy** [comment]
fixed in `15-dev`
