### ISSUE TITLE
App shortcuts not working on LineageOS 14.1

### ISSUE THREAD

**Issue by jackmort37** [Deletescape-Media/Lawnchair#471]
Hi,
I just installed latest release (v1.0.1063), and using LineageOS 14.1 build of 08/08/2017 for Nexus 5 (so Android 7.1.2), and app shortcuts are not working : I only get edit, widget and app information instead of application shortcuts.
Lawnchair is set as default launcher and all permissions have been granted (Location, Storage and Phone).
How could I get you some debug logs/information to help investigate ?
Thanks.

**Comment by nyancrimew** [comment]
Logs would be great!

**Comment by guest4711** [comment]
Not all apps have shortcuts.  Good starting point are "chromium" or "MiXplorer" which support them while other apps don't.

**Comment by suphon-t** [comment]
@jackmort37 More informations?

**Comment by jackmort37** [comment]
Hi, 
Sorry I didn't had time to get some logs. However, I know there's only few apps with such shortcuts, I was running some tests with Google Agenda. 
So I just tried, same issue. 
I wiped cache, uninstall app, rebooted phone and reinstalled et voilà : it's working fine! 
Maybe some corrupted file in cache... 
Sorry for the trouble and anyway, thank you for your support!
