### ISSUE TITLE
[BUG]  At a glance Weather icon not opening app

### ISSUE THREAD

**Issue by islandlex** [Deletescape-Media/Lawnchair#4711]
### Describe the bug

On launchair 2 ( 2.0-2589 ) Android 8, 9 and 14
Dont know if this is a bug or an intended change but "At a glance - weather" icon used to open the weather app when clicked on. Now it opens a firefox web page  - and there is no widget to add the stock weather app to home screen 

### Steps to reproduce

1. Home screen at a glance widget
2. Click on weather icon 
3. Weather app should open
4. Firefox web page opens instead

### Expected behavior

Clicking on the weather icon should pop up the detailed weather app 

### Device information

- Device: Huawei y7 Pro , Honor 8a, POCO F1
- OS: Huawei stock A8, - Huawei stock A9, - F1 custom [BERYLLIUM] crDroid v10.7 [16.08.2024]
- App version: 2.0-2589

**Comment by MrSluffy** [comment]
fixed in `15-dev`
