### ISSUE TITLE
[BUG] Icon/folder label text not showing outside of drawers and folders

### ISSUE THREAD

**Issue by AmiiiiKo** [Deletescape-Media/Lawnchair#4716]
### Describe the bug

In short, there is no label text below the icons outside of the drawer and folders. Text does not show in or out of the dock.

Text shows normally inside folders and the drawer, albeit quite small inside folders but that may be due to the high res but small screen (1600 x 2560 on an 8.8in screen)

There is text size controls in the OS, I have resized the text to no avail. I have toggled everything I could on/off in an attempt to get the text to show to no avail.

It does show in other launchers and did show in the prior version.

### Steps to reproduce

1. Go to the main screen
2. See no text below icons or folders

### Expected behavior

Text should show
Toggling text on should show the text in the dock as well

### Screenshots

![no text](https://github.com/user-attachments/assets/1a773847-a819-4cc2-9073-077cddbe2119)

### Device information

- Device: Lenovo Legion Y700 (2023) TB320FC
- OS: ZUI 16.0.336
- App version: 14 Beta 3 from F-droid

**Comment by Necr0man** [comment]
Same issue on a POCO F6. Also tried every option but I can't get text to show below icons on main pages.

**Comment by jsmr1** [comment]
Fall into the same trap 2 times last week. 
Solution (for me): Go to the system settings -> Display -> display size + text -> Set font and display size not more than the half of the bar.

Then one can set the font and icon size in the lawnchair Home-settings -> Start display

The font size in the apps will unfortunately adjusted by the system settings, which are maybe to small.

**Comment by AmiiiiKo** [comment]
> Fall into the same trap 2 times last week. Solution (for me): Go to the system settings -> Display -> display size + text -> Set font and display size not more than the half of the bar.
> 
> Then one can set the font and icon size in the lawnchair Home-settings -> Start display
> 
> The font size in the apps will unfortunately adjusted by the system settings, which are maybe to small.

For me that would mean having text too small to read due to the resolution of the tablet, the text is already very small,

**Comment by MrSluffy** [comment]
fixed in `15-dev`
