### ISSUE TITLE
[BUG] Lawnchair 14 Beta 3 crashing on Huawei MediaPad M6

### ISSUE THREAD

**Issue by viplmad** [Deletescape-Media/Lawnchair#4719]
### Describe the bug

The 14 Beta 3 crashes on startup on Huawei MediaPad M6.

Things I tried:
- Clean install of 14 Beta 2 works fine.
- Clean install of 14 Beta 3 (from GitHub or F-Droid) crashes.
- Similar bug for Lenovo https://github.com/LawnchairLauncher/lawnchair/issues/4685 has similar exception in attached log. I tried installing the latest nightly 192cb03 (https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly) which includes a fix for that issue but still crashes. I attach logs from this crash below.

Thanks in advance.

### Steps to reproduce

1. Install 14 Beta 3
2. Open app

### Expected behavior

The app to open.

### Device information

- Device: Huawei MediaPad M6 (SCM-W09)
- OS: Android 10.0 (EMUI 11.0.0)
- App version: 14 Beta 3 

### Additional context

Logs from 14 Beta 3: https://katb.in/osodaduvoca
Logs from latest nightly (192cb03): https://katb.in/dubenudozax

**Comment by ivanddiaz** [comment]
Hi I'm facing the same problem using latest Nightly `(version: 14.Dev.(#1297) (14000203))` the problem persists :( 
Using Lenovo YT-X705F and Android 10.

https://katb.in/igasexeyude

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue

**Comment by viplmad** [comment]
Can confirm it now opens up. Thanks.

**Comment by ivanddiaz** [comment]
I also confirm. Thank you!
