### ISSUE TITLE
[FEATURE] Neo Feed for Custom Feed

### ISSUE THREAD

**Issue by pr0927** [Deletescape-Media/Lawnchair#4723]
### Describe the feature

Alternative feed option to Google Feed.

### Why would it be useful to add?

Self-hosted RSS feeds (like via FreshRSS .opml files) can be imported and take the place of algorithmic nonsense.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://gitlab.com/NeoApplications/Neo-Feed

### Additional context

Neo Feed was designed for Neo Launcher but should work with Lawnchair and other similarly-rooted FOSS launchers, I would think?

**Comment by validcube** [comment]
👋 It appear that this PR is a duplicated of #4134 while I'm not here to make any moderational judgement (just here to inform about workaround.)

Here's a workaround how to get Neo Feed on Lawnchair:
https://github.com/LawnchairLauncher/lawnchair/issues/4134#issuecomment-2068019768

**Comment by pr0927** [comment]
Oops, wow my search skills were terrible, OK. Thanks. Will make comments there.
