### ISSUE TITLE
[BUG] Translation string for 'Icon size' mislabelled in certain languages

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4726]
### Describe the bug

The text for 'Icon size' (used in the Home Screen and App Drawer settings) is 'R.string.icon_sizes'.
However, in the 'strings.xml' file for certain languages, the corresponding lines are mislabelled as `<string name="icon_size">` (i.e. 'icon_size' rather than 'icon_sizes').

Languages affected:
- values-en-rGB
- values-he
- values-id
- values-ku
- values-sw

### Steps to reproduce

Check source files.

### Expected behavior

`<string name="icon_sizes">` should be used (rather than `<string name="icon_size">`) in all 'strings.xml' files.

### Device information

- Device: N/A
- OS: N/A
- App version: Lawnchair.Debug.14-dev.Nightly-CI_1290-4c9b8b0.apk

**Comment by SuperDragonXD** [comment]
This is more-or-less an issue with the users translating the strings on Crowdin alongside some strings, which tbh isn't really checked too often.

**Comment by tgex0** [comment]
OK, no problem. I'm not familiar with Crowdin and thought I should at least point it out.
