### ISSUE TITLE
NO weather widget

### ISSUE THREAD

**Issue by mansoorali890** [Deletescape-Media/Lawnchair#473]
I have a lg x power. the only issue I have is that you added the weather api to the pill widget but the screen ovelay detection is not letting me. I disabled screen overlay of every app including systemUI just to see what's wrong. still the popup was coming up that screen overlay was detected. I dont't know that much of technical details but I loved lawnchair and I could see the weather info on launcher3 from which lawnchair is based. please let me know how to fix this.

**Comment by nyancrimew** [comment]
You can also grant permissions from the app info screen by manually enabling them there.
