### ISSUE TITLE
[BUG] Goggle calendar monthly view widget

### ISSUE THREAD

**Issue by Pseudosan** [Deletescape-Media/Lawnchair#4731]
### Describe the bug

when i first added the widget it showed all of my events, after a while, few hours or more, the widget hides most of the event information. after shrinking and returning the widget to it's original size, the icons return.

Coming from Nova launcher, I've not come across this until using Lawnchair

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to homepage and view widget
2. long hold on widget to adjust sizing 
3. Shrink widget and then return to original size
4. View calendar as it's supposed to look

### Expected behavior

The widget shows all information and icons at all times

### Screenshots

https://github.com/user-attachments/assets/d67d3309-4953-4f27-901a-43ce5ea08337

![Screenshot_20240814-160115](https://github.com/user-attachments/assets/94d26b16-6e7e-4f47-bec0-95fe89847825)
![Screenshot_20240819-155901](https://github.com/user-attachments/assets/6bf00656-a031-424e-ab77-a71ab4a09c24)

### Device information

- Device: Google Pixel 7 pro
- OS: Stock Android 14 AP2A
- App version: 14 Beta 2

**Comment by BobbyByrne** [comment]
I'm on Beta 3 and in experiencing a similar issue. 

Below is how my habits widgets often look. I either have to resize all of them or trigger the home screen to rerender another way. I typically use the home screen rotation feature to do this quickly. 

![Screenshot_20240916-164506](https://github.com/user-attachments/assets/8b9d3857-4f20-409e-9c93-79e2020ac19c)

This is how they are supposed to look. 

![Screenshot_20240916-164535](https://github.com/user-attachments/assets/409344f6-2dec-419e-8764-45e91f2ea9d1)

**Comment by Minituff** [comment]
Noticing this as well. It also seems to happen with the clock widget, it resizes itself randomly.

**Comment by KeronCyst** [comment]
Heck, I couldn't even get Loop's checkmark widgets to appear at all; they simply crash Lawnchair beta 3 when I try to drag them to any spot whatsoever. Shortcuts also can't be renamed. I debate over returning to Nova...

**Comment by MrSluffy** [comment]
this should be fixed in latest `15-dev`
