### ISSUE TITLE
[BUG] Beta3, app drawer vertical distance doesn't change

### ISSUE THREAD

**Issue by BaukeZwart** [Deletescape-Media/Lawnchair#4737]
### Describe the bug

When changing the app drawer vertical distance in settings it won't change anything in app drawer

### Steps to reproduce

1. Go to 'setting'
2. Click on 'app drawer'
3. Scroll down to 'vertical distance'
4. Change the setting, noting happens

### Expected behavior

change the  vertical distance

### Device information

- Device: OnePlus 9 Pro
- OS: OxygenOS 14.0
- App version: Beta 3

**Comment by Delta0001** [comment]
I also have this issue. Default configured to 5 icons but only 4 show. Changing settings does nothing. Pixel 6 Pro

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
