### ISSUE TITLE
There's too much space bellow the dock icons.

### ISSUE THREAD

**Issue by skintask** [Deletescape-Media/Lawnchair#474]
Compared with previous builds now there's more space bellow the dock icons than above. This is causing the dock to be taller than before and the icons don't seem to be centered in the dock. This is just a minor UI issues but annoys me and make the launcher seem off. Please revert back to previous builds.

**Comment by skintask** [comment]
I'm in version 1.1.0.1124.

**Comment by nyancrimew** [comment]
No, I will not revert back because the new sizing algorithm fixed a lot of other sizing issues. What I will do though is improve this new algorithm.
