### ISSUE TITLE
[BUG] Keeps Crashing

### ISSUE THREAD

**Issue by CuriousTree-5** [Deletescape-Media/Lawnchair#4743]
### Describe the bug

When I open the app it just gives a message "Lawnchair has crashed" and when I try to re-open it crashes again. What do I do?

### Steps to reproduce

1. Install the app
2. Open it
3. It gives a screen with your wallpaper
4. It crashes

### Expected behavior

I expected it to open and start

### Screenshots

Im too lazy

### Device information

- OS: [Android version 10]
- App version: [14]

### Additional context

https://katb.in/dosizazexiq

**Comment by MrSluffy** [comment]
this should fixed in latest build
