### ISSUE TITLE
[BUG] If animations are disable, cliking home screen to minimize app should not produce animation

### ISSUE THREAD

**Issue by gnomiik** [Deletescape-Media/Lawnchair#4749]
### Describe the bug

In my settings, the Animator, Transition, and Window animations are all disabled. Yet, when clicking on the home button which goes back to the Lawnchair home, you will still see a minimize animation of the app minimizing. There should be no animation if animations are disabled in the system.

### Steps to reproduce

1. Open any app
2. Click the home button
3. You will see an animation of the app being minimized

### Expected behavior

The expected behavior is that if all system animations are disabled, then when clicking on the home button to go back to the lawnchair home screen there should be no app minimization animation.

### Device information

- Device: Google Pixel 7
- OS: Android 14
- App version: Lawnchair 14 beta 3

### Additional context

At the minimum if system animation settings are ignored, at least provide a disable animations setting in lawnchair to disable the app minimization animation if that is an easier fix for the devs.

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
