### ISSUE TITLE
[BUG] App search unable to handle search strings of more than one or two characters

### ISSUE THREAD

**Issue by camnealie** [Deletescape-Media/Lawnchair#4755]
### Describe the bug

I have an ongoing issue (multiple versions of Lawnchair now, which makes me think it's device specific or everyone would be shouting about it)

When I use the app search, the app I'm after might show up for the first few letters, depending on the app. Eg typing 'f' might bring up facebook, but typing 'fa' filters it out.

For both search algorithms (App Search and Global search (on-device)), apps that should be hidden in search results show up anyway. 

I understand that the FAQ suggests deleting updates to Android System Intelligence - not applicable in my case, that app isn't on my device. Good chance there's a huawei equivalent app that's doing the damage here.

### Steps to reproduce

Open app drawer
start typing the name of the app you're after
app (may) appear, depending on how many other search results there are
At some point (usually within three search characters) no apps remain to select from.

### Expected behavior

open app drawer
start typing the name of app you want to go to 
the apps filter down as you type, until just the app that matches your search remains
click on app to use

### Screenshots

https://github.com/user-attachments/assets/5226b293-9a50-4a32-9208-0acb335861bb

### Device information

- Device: Huawei Noa 5T
- OS: EMUI 12.0.0
- App version: 14.Dev.(#1067)

**Comment by SuperDragonXD** [comment]
You are using an outdated build as this has been fixed in the latest nightly builds (or even in the Beta 3 builds).
