### ISSUE TITLE
[BUG] Rounding/precision errors in calculator search

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4756]
### Describe the bug

There are a few rounding/precision errors when using the search input as a calculator.

### Steps to reproduce

1. Try pi*0, result is 0E-15 (0 would be a more useful answer)
2. Try pi*1.000, result is 3.141592653589793000 (there are not three zeros in the decimal expansion of pi at that position)
3. Try 2.0*6.0, result is 6.00 (most calculators would just display 6)
4. Try1/3*3, result is 0.9999999999999999 (technically, an infinite number of 9s here _would_ equal 1 but 1 would be the expected result)

### Expected behavior

I would expect the results of the calculator search to be the same as that of any other calculator.

I expect the reason for (2) above is that pi is truncated/rounded to 15 decimal places before the calculation is performed. (This would apply to e as well.)
I expect the reason for (3) above (and also the reason for the trailing zeros in (2)) is that the precision for the result is increased, knowing that more decimal places might be required for the result.

### Device information

- Device: POCO X5 5G
- OS: HyperOS 1.0.5.0 EEA (latest stock)
- App version: Lawnchair.Debug.14-dev.Nightly-CI_1319-8f89197.apk

**Comment by tgex0** [comment]
Looks like 1, 2 and 3 above can be resolved by changing:
```
        val result = Expressions()
            .eval(query)
            .toString()
```
... to:
```
        val result = Expressions()
            .eval(query)
            .stripTrailingZeros()
            .toPlainString()
```
... on line 15 of lawnchair/src/app/lawnchair/search/algorithms/data/Calculation.kt

3 out of 4 ain't bad, I guess.

**Comment by SuperDragonXD** [comment]
Feel free to make a PR on this (alongside the other issue you made), since I don't have time to further look into the issue yet.

**Comment by tgex0** [comment]
Thanks. The code I posted _does_ fix the trailing zeros problem for the result but, with the fix in place, the equation shown in the result tile (below the result) no longer syncs with the exact search input if the result does not change (i.e. if the user enters 5*2.0 and adds further zeros, the further zeros are not updated in the equation).
Essentially, more work is required before a PR.

**Comment by CoelacanthusHex** [comment]
It may be better to use an existing calculator library such as qalculate. This library has been used in similar projects like KRunner of KDE.
https://github.com/Qalculate/libqalculate
There is a Android port of this library: https://github.com/jherkenhoff/libqalculate-android
