### ISSUE TITLE
[FEATURE] Removal of Renderscript toolkit

### ISSUE THREAD

**Issue by Digitalbullits** [Deletescape-Media/Lawnchair#4757]
### Describe the feature

It's my understanding that renderscript toolkit began depreciation with android 12. I noticed Renderscript toolkit upon decompilation of the latest beta release apk

### Why would it be useful to add?

Google advised migrating away from Renderscript toolkit as we move towards an era with newer performance and image manipulation tools to keep up with androids fast paced advancement in these areas, especially with APIs geared towards AI and neural blah blah blah crap, so it's highly possible that the app isn't performing as well as it possibly could if up to date methods were used. I'm not complaining at all, and I appreciate everything. Just something I noticed and wanted to bring forward. Thanks!

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://developer.android.com/guide/topics/renderscript/migrate

Link to android developer documentation 

### Additional context

Thanks guys!

**Comment by CoelacanthusHex** [comment]
Important thing:
> Although the RenderScript intrinsics functions continue to function after the RenderScript deprecation, they may execute **only on the CPU** rather than the GPU.
