### ISSUE TITLE
[BUG] Uninstalling apps from work profile is broken

### ISSUE THREAD

**Issue by gsture** [Deletescape-Media/Lawnchair#4758]
### Describe the bug

Long pressing an app icon in the work profile and choosing uninstall does not uninstall the app but the launcher gives the message that the app isn't installed. 

### Steps to reproduce

1. Go to work profile
2. Long press an app icon
3. Select uninstall
4. See "App isn't installed" error. 

### Expected behavior

Uninstall the app like in main profile. 

### Screenshots

![Screenshot_20240903-070555~2](https://github.com/user-attachments/assets/c5382b44-f7b0-4f46-a428-811ff6f1ed22)

### Device information

- Device: Google Pixel 8
- OS: GrapheneOS 14 (AP2A.240805.005) 
- App version: 14 beta 3

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue

**Comment by TheRedCyclops** [comment]
This can be reproduced in the latest nightly

**Comment by gsture** [comment]
> This can be reproduced in the latest nightly

Just tested this. Issue is indeed still there.

**Comment by TheRedCyclops** [comment]
@MrSluffy could you please reopen this issue?
