### ISSUE TITLE
[BUG] Wallpaper Depth Effect Does Not Work

### ISSUE THREAD

**Issue by FrenchToucan** [Deletescape-Media/Lawnchair#4759]
### Describe the bug

Wallpaper Depth Effect doesn't work when enabled.

### Steps to reproduce

1. Go to 'Home settings'
2. Click on 'Home screen'
3. Toggle on 'Wallpaper depth effect'
4. Return to your home screen, open an app with an icon on your home screen, then swipe from the bottom of your screen to return home.

### Expected behavior

Window should appear to disappear into the icon.

### Device information

- Device: Pixel 8
- OS: 15 QPR1 Beta 1.1
- App version: 14.0.0 (fcb1ded)

**Comment by AndrewDallas** [comment]
Same here. Pixel 6. A15 beta same as OP.

**Comment by FrenchToucan** [comment]
GestureNavContract issue: https://issuetracker.google.com/issues/366867005?pli=1
