### ISSUE TITLE
Luncher not saving my widgets

### ISSUE THREAD

**Issue by dmacher** [Deletescape-Media/Lawnchair#476]
Moto x style Android 7.0 stock rom latest app version alpha v1.0.1063.
After setting everything on desktop and restarting the phone all widgets are missing. Apps shortcuts are there. All permission given to the luncher and set it as main one. Tried reinstalling with no success. Please give me a fix for this superb luncher.

**Comment by benzeyf** [comment]
have a same problem

**Comment by dmacher** [comment]
Found a solution in luncher topic at xda here is the link:
https://forum.xda-developers.com/android/apps-games/lawnchair-customizable-pixel-launcher-t3627137/post73129911
In short you must transfer app from SD card to internal storage.
