### ISSUE TITLE
Merge `android15-release` from AOSP

### ISSUE THREAD

**Issue by SuperDragonXD** [Deletescape-Media/Lawnchair#4760]
Source code: https://android.googlesource.com/platform/packages/apps/Launcher3/+/refs/heads/android15-release

Potentially breaking changes:
* Private space
* App archiving
* New Quickstep APIs

**Comment by AndrewDallas** [comment]
Exciting! 👍

**Comment by SuperDragonXD** [comment]
From internal discussion, we would pay the contributor (MrSluffy) the following:
* $50 - Android 15 merge, without any critical crashes (like we can open the app in all supported versions)
  * By opening the app: we can open the home screen, folders, app drawer, search, home settings, and other bottom sheets (without crashing)
* $50 - fix QuickSwitch, fix any missing features/regressions, fix other crashes, and fix other bugs that are related to the merge

**Comment by AndrewDallas** [comment]
I'll donate $20 myself as well 🙏💪

**Comment by 88572** [comment]
I'm not able to financially contribute, but I offer a "Thanks ❤️".

**Comment by phoropter** [comment]
I would also like to put a $50 bounty on the ability to add private space apps to the home screen. Perhaps a similar implementation to what shelter offers for apps you set to auto-freeze?

**Comment by valtoree** [comment]
Yeh def need to be able to add to homescreen. Thanks for bounty.

**Comment by nathangur** [comment]
I'll add $20 dollars to the bounty since I found out the lawnchair's search can't find private spaces if it's hidden.

**Comment by Goooler** [comment]
Merged in #4818.

**Comment by gsture** [comment]
Good job! Time for a new beta release 🥳
