### ISSUE TITLE
[BUG] blank screen

### ISSUE THREAD

**Issue by Plum107** [Deletescape-Media/Lawnchair#4761]
### Describe the bug

When clicking an app it often brings up a blank screen rather than the actual app itself.

### Steps to reproduce

This happens from time to time but I can force it to happen by switching between apps quickly.

### Expected behavior

No blank screen 

### Screenshots

https://github.com/user-attachments/assets/2a1cdbff-2e97-4557-bb8f-6d88117756cf

### Device information

- Device: Google Pixel 5
- OS: stock ROM Android version 14.0
- App version: 14 beta 3

### Additional context

This does not happen on the pixel launcher but only the lawnchair launcher.

**Comment by MrSluffy** [comment]
Set lawnchair as recent provider if still persists reopen this issue
