### ISSUE TITLE
[FEATURE] Lock Apps in Recent Screen

### ISSUE THREAD

**Issue by chuwza** [Deletescape-Media/Lawnchair#4778]
### Describe the feature

Lock Apps in the Recent Tasks screen so that locked Apps are not cleared when using Clear All Apps

### Why would it be useful to add?

Cleaning up the background is an action that is definitely done, but sometimes YouTube is playing a video and I don't want to clean up YouTube, this Feature allows me to clean up the background and keep YouTube at the same time.It's worth noting that this Feature has existed for a long time on customized Launcher from manufacturers like Xiaomi, OPPO, and so on, so hopefully Lawnchair gets on board soon.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![IMG_20240908_134313](https://github.com/user-attachments/assets/71b0f068-14fc-437d-853d-2f564b7e114d)

https://github.com/user-attachments/assets/31ce833d-15cd-4ce5-b393-9c3662911c1f

**Comment by MrSluffy** [comment]
it already have one but diff impl : 594dc1c3d25187761e9265b7017ae6d408ce1a5d
