### ISSUE TITLE
[BUG] Lawnchair crash after click “lock app” on Android 11

### ISSUE THREAD

**Issue by chuwza** [Deletescape-Media/Lawnchair#4779]
### Describe the bug

Lawnchair is fresh install.
And Lawnchair will crash when using the “lock app” function.

### Steps to reproduce

1. Go to 'recent screen'
2. Click on 'lock'
3. See error, lawnchair crash

### Expected behavior

the app is locked and Lawnchair has no crash.

### Screenshots

This is log
https://katb.in/uraxovazabu

This is video

https://github.com/user-attachments/assets/5a76e135-07d0-4def-9ed2-2fd2de7e4b0f

### Device information

- Device: [OnePlus 5T]
- OS: [Mokee ROM Android version 11.0]
- App version: [14.Beta 3]

**Comment by MrSluffy** [comment]
please uninstall and use quickswitch! 
![image](https://github.com/user-attachments/assets/5a63b8a6-b4f1-4b97-876e-bf6fc6e54f38)
the permission is already there :https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/lawnchair/AndroidManifest.xml#L32

I assume your using module etc, or the overlay not properly created using quickswitch I suggest to uninstall and reinstall and reapply recents via quickswitch
