### ISSUE TITLE
[BUG] QuickStep cannot be accessed while using 2 button navigation in a app 

### ISSUE THREAD

**Issue by hrzndelta** [Deletescape-Media/Lawnchair#4781]
### Describe the bug

Normally, 2 button navigation uses swipe up gesture to open QuickStep. Except when using Lawnchair's QuickStep, swiping up bring me back to home screen, in the home screen only QuickStep does launch
(Sorry for bad English)

### Steps to reproduce

1. Set navigation mode to 2 button navigation
2. Install QuickSwitch via magisk
3. Set Lawnchair as default QuickStep
4. Open a random app
5. Swipe up on navbar bring it back to home screen

### Expected behavior

Swiping up open up QuickStep

### Device information

- Device: Samsung Galaxy A23 5G (SM-A236E)
- OS: LineageOS 21 (Android 14 GSI)
- App version: 14.Beta 3
- Magisk: 27.0
- QuickSwitch: 4.0.3

**Comment by MrSluffy** [comment]
Closing this since no support in 2 button since google already dropped 2 nav in android 15

Create new feature request instead
