### ISSUE TITLE
[BUG] Different themed icon size

### ISSUE THREAD

**Issue by fumoshroom** [Deletescape-Media/Lawnchair#4782]
### Describe the bug

Uneven themed icon size

### Steps to reproduce

1. General>Icon style>Themed icon source to Lawnicons and change the Themed icons options to home screen
2. Restart lawnchair if settings did not get applied
3. Add phigros shortcut from app drawer to the home screen

### Expected behavior

Icon size is smaller compared to other themed icons

### Screenshots

![IMG_20240909_142114](https://github.com/user-attachments/assets/23a78c8c-bdce-4181-8d20-652b16fe515b)

### Device information

- Device: Redmi Note 12 Turbo
- OS: AOSPA uvite beta
- App version: 14.dev.(d7e3f32)

### Additional context

My guess for the reason is that the app Phigros' default icon in the app drawer is square shaped, which caused its size to be reduced compared to other icons, and this change carries to its themed icon in the home screen, despite not being square anymore

**Comment by MrSluffy** [comment]
fixed in `15-dev`
