### ISSUE TITLE
Bug,  Turning on one handed moddid this.

### ISSUE THREAD

**Issue by GeneralKaos666** [Deletescape-Media/Lawnchair#4787]
Lawnchair bug report Sep 9, 2024 8:37:04 PM version: 14.Beta 3 (14000203) commit: 6f4a812 build.brand: nubia build.device: NX769J build.display: REDMAGICOS9.0.20_NX769J_GB build.fingerprint: nubia/NX769J-UN/NX769J:14/UKQ1.230917.001/20240903.163725:user/release-keys build.hardware: qcom build.id: UKQ1.230917.001 build.manufacturer: nubia build.model: NX769J build.security.level: 2024-08-01 build.product: NX769J-UN build.type: user version.codename: REL version.incremental: 20240903.163725 version.release: 14 version.sdk_int: 34 display.density_dpi: 408 isRecentsEnabled: false error: Uncaught exception java.lang.SecurityException: Settings key: <one_handed_mode_enabled> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable. 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3288) 	at android.provider.Settings$Secure.getStringForUser(Settings.java:6582) 	at android.provider.Settings$Secure.getIntForUser(Settings.java:6802) 	at android.provider.Settings$Secure.getInt(Settings.java:6796) 	at com.android.launcher3.util.SettingsCache.updateValue(Unknown Source:30) 	at com.android.launcher3.util.SettingsCache.onChange(Unknown Source:1) 	at android.database.ContentObserver.onChange(ContentObserver.java:170) 	at android.database.ContentObserver.onChange(ContentObserver.java:188) 	at android.database.ContentObserver.onChange(ContentObserver.java:224) 	at android.database.ContentObserver.lambda$dispatchChange$0(ContentObserver.java:304) 	at android.database.ContentObserver.$r8$lambda$ZTAX5Dz0QB2gJk_nBFGhENlKHoI(Unknown Source:0) 	at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10) 	at android.os.Handler.handleCallback(Handler.java:958) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loopOnce(Looper.java:238) 	at android.os.Looper.loop(Looper.java:352) 	at android.app.ActivityThread.main(ActivityThread.java:9230) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

**Comment by MrSluffy** [comment]
fixed in `15-dev`
