### ISSUE TITLE
[BUG] shortcuts can't show when searching the app in the app drawer

### ISSUE THREAD

**Issue by chuwza** [Deletescape-Media/Lawnchair#4794]
### Describe the bug

Hi, I know Lawnchair has been having a bug that App shortcuts will gone sometimes. But I found the solution on the official website and that's it.(You can still view app shortcuts by searching the app until you see only the app and a list of its shortcuts.)
![屏幕截图 2024-09-11 184701](https://github.com/user-attachments/assets/11bbbce9-bdd7-42e4-9bbb-cc369316ebe5)

 But I found that when the bug appears and shortcuts go away, App Drawer still has no shortcuts. to note, I have set Lawnchair 14.beta 3 as the default Launcher and used Magisk QuickSwitch, and most importantly, I did that(view app shortcuts by searching the app until you see only the app and a list of its shortcuts.), but I still can't search for the shortcuts.

Please fix this bug! The solution on the official website doesn't work!

### Steps to reproduce

1. Go to 'app drawer'
2. Search the 'Play Store'
3. didn't show Play Store's shortcuts

### Expected behavior

show the Play Store‘shortcuts in the app drawer

### Screenshots

![IMG_20240911_210512](https://github.com/user-attachments/assets/50a5509e-7e7f-4bbf-aaaf-d1b8c3181aa8)

### Device information

- Device: [OnePlus 5T]
- OS: [Mokee 11.0]
- App version: [14.beta 3]

**Comment by MrSluffy** [comment]
use latest `15-dev` make sure to set lawnchair as default home

![Screenshot_20241204-220152_Lawnchair](https://github.com/user-attachments/assets/d50e2078-9b05-4541-bc15-43fbe58e9a4e)
