### ISSUE TITLE
App drawer should not overlay navigation bar

### ISSUE THREAD

**Issue by guest4711** [Deletescape-Media/Lawnchair#480]
I have softkeys enabled on my devices(s). LanwChairs application drawer is using all the screen's space even this part used by navigation bar.
I'd like if I can tell LawnChair to leave a bottom margin for my navigation bar as other launchers (e.g. Trebuchet) do. This could be done using a slider in the setting, which is used to define the margin (which should default to 0).

**Comment by guest4711** [comment]
![screenshot_20170811-095249](https://user-images.githubusercontent.com/26175945/29209465-f2334cba-7e8e-11e7-9422-f9fdd48c6fff.png)
Sorry, did not manage to submit screenshots using octodroid. Had to use browser.

**Comment by guest4711** [comment]
![screenshot_20170811-095424](https://user-images.githubusercontent.com/26175945/29209467-f887b31c-7e8e-11e7-8af4-dffeca83f979.png)

Having a bottom margin.

**Comment by Younes-L** [comment]
Nova does this too, and I think it looks cool ^^

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
This is the expected behavior.

**Comment by guest4711** [comment]
Who does expect it? And what should I expect? I expect a clean and functional interface... And with a settable margin everyone could choose what she or he wants...
