### ISSUE TITLE
[BUG] no Labels are shown on Homescreen 

### ISSUE THREAD

**Issue by fbfrank** [Deletescape-Media/Lawnchair#4806]
### Describe the bug

In Settings enabled, no Labels are shown on Homescreen. Neither for folders nor single Apps 

### Steps to reproduce

Settings enable labels

### Expected behavior

Show labels on Homescreen

### Screenshots

![Screenshot_20240912-175215](https://github.com/user-attachments/assets/85e3169c-937c-40aa-a2f0-c2b437814a0a)
![Screenshot_20240912-175155](https://github.com/user-attachments/assets/ad522a91-8e78-43b3-857d-0b47d274cf23)

### Device information

- Device: Google Pixel 9
- OS: latest GrapheneOS
- App version: lawnchair 14 dev

**Comment by fbfrank** [comment]
Changing grid to 4 (!) vertical brings back the labels. However, I need 7 vertical WITH labels. Additionally - in App overview it's possible to have two lines labels, in Homescreen it's missing.

**Comment by Ante0** [comment]
For me, if I enable labels, it will not do anything on the home screen. It does however add a bigger gap between the icons in the app drawer.

Pixel 7 Pro
Android 15 beta

**Comment by snoweuph** [comment]
Same Bug for me on Latest Andy Yann Lineage Android 13 GSI.
Really Annoying.
I would be fine with missing Labels on App Icons, but really want them on the Folders

**Comment by TruongTanLuc201270** [comment]
There is no labels on Home screen bug but need to be fixed.
My device is Samsung Galaxy S7, SM-G930W8, android 8.
I use early acess of Lawnchair, version 14.Dev(d7e3f32), downloaded from Google Play.
![Screenshot_20241107-004142_Lawnchair](https://github.com/user-attachments/assets/208c535f-5a54-4f56-b4d1-1c6b4a8f0c40)

**Comment by MrSluffy** [comment]
this should be fixed in latest `15-dev`
