### ISSUE TITLE
[BUG] App crashes when selecting General -> Icons -> Icon style (current dev source)

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4807]
### Describe the bug

App crashes when selecting General -> Icons -> Icon style (current dev source).
 
I built a custom APK based on the current dev source to test my icon for #4798.
The icon failed to display correctly and I noticed that the app crashed when selecting General -> Icons -> Icon style.

I then built a fresh APK from just the current dev source (none of my own custom code this time) and the app still crashes when selecting General -> Icons -> Icon style.

I realize that this is a custom-built APK using dev source but I thought I should give you a quick heads up as it looks like it might be related to commit #4554.

I've tested this on a couple of phones (see below for details) with the same results.

### Steps to reproduce

1. Go to 'General'
2. Scroll down to 'Icons'
3. Click 'Icon style'
4. App crashes (see screenshot for error text)

### Expected behavior

App should not crash when selecting General -> Icons -> Icon style.

### Screenshots

![Screenshot_2024-09-12-19-04-06-911_com miui bugreport](https://github.com/user-attachments/assets/bfd2b706-4f4d-4a79-8d34-835bdeff1cb7)

### Device information

- Device: Tested on two phones: POCO X5 5G and Xiaomi MI 8
- OS: HyperOS 1.0.8.0 (stock) on POCO X5 5G, Lineage 21 (Android 14) on MI 8
- App version: Custom APK, current dev source at time of writing this report

**Comment by SuperDragonXD** [comment]
Could you send a version of the crash logs that isn't obfuscated?

**Comment by tgex0** [comment]
[crashlog.txt](https://github.com/user-attachments/files/16985918/crashlog.txt)

**Comment by Goooler** [comment]
Thanks for the report!
