### ISSUE TITLE
[BUG] Lawnchair pops up as a "regular" app in Android's recent applications.

### ISSUE THREAD

**Issue by BigPebble123** [Deletescape-Media/Lawnchair#4816]
### Describe the bug

Lawnchair pops up as a "regular" app in Android's recent applications.

### Steps to reproduce

Steps to reproduce the behavior.

Method one:
1. Open any app
2. Use a gesture or button to show recent apps
3. Click on the side to exit the screen of recent applications
4. Again use the gesture or button of recent applications
5. Repeat step 3 and 4 few times
6. Lawnchair will crash (you can say it by trying to use the recent apps gesture)
7. Open the app again
8. Use a gesture or button to show recent apps
9. Close the app
10. Open the recent apps menu again
11. Lawnchair will appear

Method two:
1. Open any app
2. Go to recent apps screen
3. Click on the side to exit the screen of recent applications
4. Repeat steps 2 and 3 until Lawnchar appears

### Expected behavior

Lawnchair should not appear in recent applications screen.

### Screenshots

https://github.com/user-attachments/assets/80ccb57e-0cd4-4172-a681-f47a16dacef3

### Device information

- Device: Google Pixel 7 Pro
- OS: LineageOS 21 (20240820)
- App version: 14.Beta 3

**Comment by loxoron218** [comment]
I'm also experiencing this! Anyone knows why it happens?
It looks like it happens "randomly" after a couple of times of swiping up, but I haven't been able to reproduce it predictably.

I'm using the Google Pixel 9 with the latest version of GraphenOS, in case it mattered :)

**Comment by MrSluffy** [comment]
To resolve this issue please set lawnchair as recent provider 

If still persists while lawnchair set as default recents provider re-open this
