### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by Ansarmughal99** [Deletescape-Media/Lawnchair#4832]
![Lawnchair bug report 17 Sept 2024 11:43:21 am.txt](https://github.com/user-attachments/files/17023712/Lawnchair.bug.report.17.Sept.2024.11.43.21.am.txt)

Crash every single day

**Comment by MrSluffy** [comment]
out of memory seems like lawnchair doesn't support low end device anymore

Please use lawnchair legacy instead
