### ISSUE TITLE
[Feature Request] Resizable folder icon

### ISSUE THREAD

**Issue by SovsOgKartofler** [Deletescape-Media/Lawnchair#484]
I'd be great to be able to resize the folder icon. That way folder icons could be of the same size as other icons.

**Comment by Dondrejohnson5** [comment]
Same

**Comment by devgar** [comment]
When I change icons size, folders are also resized. This is solved

**Comment by SovsOgKartofler** [comment]
@devgar Not it's not. What i request is an option to set folder and icons sizes independently.
