### ISSUE TITLE
[FEATURE] Add Support for More Search Providers in Web Suggestions

### ISSUE THREAD

**Issue by lvanoverberghe** [Deletescape-Media/Lawnchair#4846]
### Describe the feature

I would like to request the addition of more search provider options for Lawnchair's Web Suggestions feature. Currently, only Startpage is available, but it would be beneficial to have alternatives like DuckDuckGo.

### Why would it be useful to add?

Proposed Enhancement:

- Add more search provider options, allowing users to choose their preferred engine for Web Suggestions.
- Implement functionality similar to Niagara Launcher and Pixel Search, where users can search within the app drawer, and if no local results are found, pressing "Enter" triggers a web search using the selected search provider.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![FgqIZywWYAI-rth-2906540909](https://github.com/user-attachments/assets/8e83f820-4451-4b24-9a45-cb5d899f6879)

![websearch-368825141](https://github.com/user-attachments/assets/2905ed23-5a4a-4f18-be6a-bba6ee663f6a)

**Comment by MrSluffy** [comment]
![Screenshot_20241215-030613_Lawnchair](https://github.com/user-attachments/assets/ae1ddc8f-fcb8-446b-a8be-ccf23fd19cc5)
