### ISSUE TITLE
Open/close app drawer sluggish

### ISSUE THREAD

**Issue by FantasieGamer** [Deletescape-Media/Lawnchair#485]
The app drawer is very sluggish when opening and closing animation is shown. Using latest release on a nexus 6p running Android O DP4. 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
Some more info such as videos?

**Comment by FantasieGamer** [comment]
It doesn't happen 100% of the time, I'll try to record the problem when it happens again.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guest4711** [comment]
See also #533

**Comment by eyronic** [comment]
Heres a pic of gpu bars if its gonna help. I tried opening and closing the app drawer and its kind of sluggish. Using Redmi Note 3 Pro 3GB RAM. SD650 CPU.  Adreno 510 GPU. https://goo.gl/photos/7s64nEk6iaFdR49D9

**Comment by Ajaja** [comment]
I have this problem on my old slow smartphone. Please could you add an option to disable the changing transparency effect in the  app drawer opening/closing animation?

**Comment by nonnymoose** [comment]
I have the same problem. The gpu profiler bars go all the way up the screen, too. Could you please make it a little... easier to animate the app drawer?
