### ISSUE TITLE
[BUG] Can't Add Widgets 

### ISSUE THREAD

**Issue by pao297** [Deletescape-Media/Lawnchair#4856]
### Describe the bug

i can't add a widget. for example: apple music, anything widget that are customizable like widgeet. the only widgets you can add is mostly google apps, and widgets that are fixed or not customizable. 

### Steps to reproduce

1. hold screen
2. tap on widgets
3. add widgets
4. then after you add it, some animation happens and it'll not be add

### Expected behavior

i expected to add the widget

### Device information

- Device: [infinix hot 40]
- OS: [xos 13.5.0]
- App version: [14.beta3]

**Comment by kaheichanturtle** [comment]
Set your stock launcher to default first, then add the widget. Then, set lawnchair to default.

Why? Lawnchair said that this bug is known but they have no fixes yet, so for the meantime, this is the way that allows you to add a widget.

**Comment by n3t-admin** [comment]
> Set your stock launcher to default first, then add the widget. Then, set lawnchair to default.
> 
> Why? Lawnchair said that this bug is known but they have no fixes yet, so for the meantime, this is the way that allows you to add a widget.

I'd like to clarify the instructions a bit (since I'm having the same bug on A15): once you set the other launcher as default, start Lawnchair from the app drawer, add the widget there (not on the other launcher you set as default), then switch default to Lawnchair again, as in the instructions.

**Comment by MrSluffy** [comment]
fixed in `15-dev`

**Comment by tsunderswapElnina** [comment]
> Set your stock launcher to default first, then add the widget. Then, set lawnchair to default.
> 
> Why? Lawnchair said that this bug is known but they have no fixes yet, so for the meantime, this is the way that allows you to add a widget.

I'm a **Samsung** User and with **Inicio de One UI** will not work.

**Comment by tsunderswapElnina** [comment]
Also fixed in `15 Dev` Version
[Check here for more details](app.lawnchair)
