### ISSUE TITLE
Weather OpenWeatherMap not updating automatically

### ISSUE THREAD

**Issue by pabdel86** [Deletescape-Media/Lawnchair#486]
Seen some comments, i see that Google Awareness works for many people, but not for me, basically does not match with the real temperature and not updating at all. OpenWeatherMap option apparently works better for me, because it match with the real temperature, but it does NOT updating automatically. i have to click to switch to the date, back and it does updated. :( Any help?
Nexus 6 with Android 7.1.1

**Comment by suphon-t** [comment]
Please move to #468
