### ISSUE TITLE
[BUG] Lawnchair 14 Crashing

### ISSUE THREAD

**Issue by KenSp-UX** [Deletescape-Media/Lawnchair#4862]
### Describe the bug

Lawnchair 14 crashing when opening app or selected lawnchair as home app. Im on android 10.

### Steps to reproduce

1. Launch lawnchair

### Expected behavior

The app crashes when opening app

### Device information

- Device: Huawei MatePad 10.1
- OS: Android 10
- App version: Lawnchair 14 beta 3 or Lawnchair Nightly (im using latest version) 

### Additional context

Crash report :https://katb.in/yipurufanez

**Comment by Walter0799** [comment]
Same on

    Device: Nokia X20
    OS: Android 14
    App version: Lawnchair 14 beta 3

**Comment by KenSp-UX** [comment]
Someone help me

**Comment by KenSp-UX** [comment]
Help!

**Comment by MrSluffy** [comment]
fixed here 46f8e92df9064b2f57858afe2e4f5b3d09757b72
