### ISSUE TITLE
[BUG] Glitching/Flickering

### ISSUE THREAD

**Issue by YashjitPal** [Deletescape-Media/Lawnchair#4863]
### Describe the bug

The widgets and the icons are glitching whenever I'm clicking the home button and also when I'm exiting the app. Im coming across a lot of the issues. The version of the app is the latest on Google Play store

https://github.com/user-attachments/assets/2961786c-c735-47cb-81d5-6a214b6074d7

### Steps to reproduce

1. Go to the launcher
2. Click on any app
3. Click the home button and leave the app

### Expected behavior

The expected behaviour should be normal. The apps and widgets shouldn't flicker or glitch and when clicked the home button again after reaching the homescreen, it should send me to the first home window

### Screenshots

https://github.com/user-attachments/assets/f196b0e1-097d-4644-b5af-feefb986b22b

### Device information

- Device: Realme Narzo 70 5g
- OS: realme ui 5.0
- App version: I'll provide 2 app versions I have tried the bug. One is beta 3 and the other I'll attach photo
![Screenshot_2024-09-29-11-07-16-08_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/429c32b7-9b2d-4479-8ffa-cd190afc75cc)

### Additional context

I think the issue is happening because of the app only. Because the widgets and everything works perfect I tried on nova launcher, smart launcher, etc. but it's glitching on lawnchair only. I have two lawnchairs on my phone. One is from the website and one is from Google play. Both of them have the same issue...

I think if we solve the issue that when I press the home button, it stays at the home home tab and doesn't redirect to the first home tab, the widgets issue will also be solved

P.s.: the problem started happening from today. It was all normal till yesterday. +  clearing data also didn't work

Please help me fix it, I don't wanna reset my phone again for this 😭

**Comment by MrSluffy** [comment]
please reopen if still persists in latest nightly

**Comment by viv24pt** [comment]
Issue still persists in latest nightly   

https://github.com/user-attachments/assets/fd58f6ca-a8c1-4cff-98f7-0333e7b3df7e

**Comment by edent** [comment]
Happening on the latest nightly of 15 (942d07e) didn't happen on 14.

I'm on Android 15 (GrapheneOS Pixel 8 Pro). Happy to supply more details of necessary.

**Comment by MrSluffy** [comment]
This is not latest nightly

**Comment by edent** [comment]
@MrSluffy you're quite right, sorry. Latest nightly from here doesn't flicker.

**Comment by MrSluffy** [comment]
Closes fixed in latest nigthly
