### ISSUE TITLE
Volte symbol doesn't turn black in app drawer.

### ISSUE THREAD

**Issue by nachiketdk** [Deletescape-Media/Lawnchair#487]
![screenshot_20170811-213519](https://user-images.githubusercontent.com/29353816/29221668-4094ad10-7edd-11e7-88f3-8c17e780fe51.png)
![screenshot_20170811-213529](https://user-images.githubusercontent.com/29353816/29221701-5b4649a2-7edd-11e7-908d-5c2ec503ce95.png)
It is not clearly visible.

**Comment by suphon-t** [comment]
ROM issue.

**Comment by leon0399** [comment]
@PrecedentBrute what's the icon pack?

_Отправлено с моего Xiaomi MI 5 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nachiketdk** [comment]
@leon0399 It is O icons - Android O icon pack.
https://play.google.com/store/apps/details?id=com.themezilla.android_o_icon&hl=en
