### ISSUE TITLE
[BUG] Smartspacer "Too many bind requests" random crashes

### ISSUE THREAD

**Issue by RWCoding58** [Deletescape-Media/Lawnchair#4874]
### Describe the bug

Lawnchair has been occasionally crashing suddenly with the error message being `java.lang.IllegalStateException: Too many bind requests(999+) for service Intent { act=com.kieronquinn.app.smartspacer.MANAGER pkg=com.kieronquinn.app.smartspacer }`. I'm not sure what causes the crash except that it obviously has something to do with the Smartspacer app, but I haven't noticed any abnormal behaviour that might have caused it. 

### Steps to reproduce

Honestly not sure how to trigger the crash since it happens occasionally, though it's usually either when I close an app to go to the home screen or go to an app from the home screen. 

### Expected behavior

Not crash

### Device information

- Device: Samsung A42 5G
- OS: Android 12 (stock) 
- App version: 14 Beta 3

### Additional context

Link to crash log: https://katb.in/epowefigeqo

**Comment by MrSluffy** [comment]
dangggg. How many plugin you using? please report it here : https://github.com/KieronQuinn/Smartspacer

**Comment by RWCoding58** [comment]
Only plugin I'm using is the Notifications Plugin, I'll make an issue there soon

**Comment by MrSluffy** [comment]
closes since issue is not from lawnchair
