### ISSUE TITLE
Feature Request: Add App Signing Certificate SHA-256 Hash to README

### ISSUE THREAD

**Issue by NarwhalPrince** [Deletescape-Media/Lawnchair#4878]
### Describe the feature

Hello,

I would like to request that the app signing certificate SHA-256 hash be added to the GitHub README for this project. 

### Why would it be useful to add?

This would greatly assist with verifying the authenticity of APKs downloaded from non-trusted sources, such as directly from GitHub or other websites, compared to trusted sources like the Google Play Store or Accrescent.

By including this information, users can easily use tools like [AppVerifier](https://github.com/soupslurpr/AppVerifier) to confirm the APK's authenticity before installation.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

An example can be seen here:

https://github.com/beemdevelopment/Aegis?tab=readme-ov-file#verification

**Comment by NarwhalPrince** [comment]
The hash can be obtained using `apksigner --print-certs`.

It should also be posted elsewhere like the website.

**Comment by validcube** [comment]
> The hash can be obtained using `apksigner --print-certs`.
> 
> It should also be posted elsewhere like the website.

👋 @NarwhalPrince, can you please check if this is what you were hoping for!

https://github.com/BoringExperiments/lawnchair/tree/pave-path-v4?tab=readme-ov-file#verification

**Comment by NarwhalPrince** [comment]
Yes! Those match. For the GitHub releases, the signing hash will need to be posted somewhere other than GitHub.

**Comment by validcube** [comment]
> Yes! Those match. For the GitHub releases, the signing hash will need to be posted somewhere other than GitHub.

For now, the issue will be resolved by #4973

I'll add signing hash to lawnchair.app and anywhere where it's applicable (and I can contribute to)
