### ISSUE TITLE
[BUG] Crashing when launching

### ISSUE THREAD

**Issue by matthew777777** [Deletescape-Media/Lawnchair#4887]
### Describe the bug

Crashing when trying to open since 14 beta 3

### Steps to reproduce

1. Go to github and download and install app
2. Click on app

### Expected behavior

Working and launching

### Device information

- Device: Huawei Matepad 10.4 2021
- OS: Harmony OS 2.0 ( Android 10)
- App version: Latest 14.3 and later

### Additional context

https://katb.in/fuhamiyusix
[Lawnchair (Debug) bug report Oct 12, 2024 8:53:50 AM.txt](https://github.com/user-attachments/files/17349114/Lawnchair.Debug.bug.report.Oct.12.2024.8.53.50.AM.txt)

**Comment by KenSp-UX** [comment]
lol
Same problem

**Comment by matthew777777** [comment]
Can some help ?

**Comment by MrSluffy** [comment]
fixed in latest `15-dev` build
