### ISSUE TITLE
[BUG] Distance between status bar and app drawer

### ISSUE THREAD

**Issue by dontobi** [Deletescape-Media/Lawnchair#4903]
### Describe the bug

The distance between the status bar and the app drawer is very small or non-existent (see screenshot). I do not use a search bar in the app drawer.

### Steps to reproduce

1. Go to App drawer
2. Scroll down

### Expected behavior

The distance between the status bar and the app drawer should be slightly larger.

### Screenshots

![Screenshot_20241016-175812](https://github.com/user-attachments/assets/f0a2a7ba-8540-4292-b789-31cd46f8194a)

### Device information

- Device: Google Pixel 8
- OS: Stock Android 15
- App version: 14.0.0 (6624004) - Goooler Release  from 20241012

**Comment by MrSluffy** [comment]
fixed in latest `15-dev` build
