### ISSUE TITLE
Icons in 'all icons' are duplicated

### ISSUE THREAD

**Issue by jahirfiquitiva** [Deletescape-Media/Lawnchair#491]
So, when I enter icon picker and choose an app and then scroll through the 'all icons' section, it shows duplicated icons. Some even appear 3, 4 and more times.

**Comment by suphon-t** [comment]
They are displayed exactly how your icon pack specified.

**Comment by jahirfiquitiva** [comment]
@paphonb 

No, they aren't.

Actually there are 2 'all icons' sections. One specified by the icon pack (which is correct), and one that seems to be the result of mixing the icons in all the other categories, which results in duplicated items

**Comment by suphon-t** [comment]
Some icon packs don't have the 'All icons' section.
The first one will show every icon provided by the icon pack.

**Comment by jahirfiquitiva** [comment]
@paphonb 
That's fine. But the first one should exclude and filter duplicates, since some icon packs put many icons in multiple categories
