### ISSUE TITLE
[BUG] Google widgets glitch out after using a fullscreen landscape app

### ISSUE THREAD

**Issue by rickymohk** [Deletescape-Media/Lawnchair#4910]
### Describe the bug

When returning home from a fullscreen landscape app, Google widgets such as weather, clock etc., which are not on the page you return to, glitch out. Can recover after screen rotation.

### Steps to reproduce

1. Navigate home screen to a page which the Google widgets are NOT on
2. Launch a fullscreen landscape app
3. Quit the app
4. Navigate home screen to where the Google widgets are on and see them glitch out
5. Rotate the screen to landscape and back to portrait, see the widgets recover

### Expected behavior

The widgets do not glitch out

### Screenshots

![Screenshot_20241017-165746](https://github.com/user-attachments/assets/51d6acc1-f16d-456d-a047-9a32bed51581)

### Device information

- Device: Google Pixel 8
- OS: Android 15
- App version: 14.Dev.(d7e3f32)

**Comment by MrSluffy** [comment]
fixed in latest `dev` build
