### ISSUE TITLE
[BUG] 修改默认上滑收拾不生效

### ISSUE THREAD

**Issue by mengxiabing** [Deletescape-Media/Lawnchair#4911]
### Describe the bug

修改默认上滑手势不生效，请问如何正确设置

### Expected behavior

修改默认上滑手势不生效，请问如何正确设置

### Screenshots

![image](https://github.com/user-attachments/assets/7d08f63e-81f2-4ff1-8f40-e1aba9dfd87b)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
