### ISSUE TITLE
Google search bar broken 

### ISSUE THREAD

**Issue by ccarrier012** [Deletescape-Media/Lawnchair#4912]
### Describe the bug

Google search bar in dock is broken. It will not open the search

### Steps to reproduce

1. Go to 'homepage'
2. Click on 'google search bar'
3. See error

### Expected behavior

The search bar should open the Google search from the homepage 

### Device information

- Device: [Google Pixel 7]
- OS: [stock ROM Android version 15.0]
- App version: [14, Play Store]

**Comment by sarojpanda44** [comment]
Guess it's a issue after the Android 15 update. For me it is the same. Updated to A15 last night.

**Comment by wehpogi** [comment]
Same issue. The bug happened on android 15 update. These are my observations. 

Mic icon is working
Setting the dock to google website is working
Set the dock to other 3rd party app. They are working. 

I think it is not a pure a15 issue. There are something need to update on launching the google app. 
If it is take too long to fix the problem in lawnchair. Try installing pixel search. It can launch google app with no problem

**Comment by sarojpanda44** [comment]
Thanks for the suggestion. I have temporarily changed it to Google widget.

**Comment by ruicayanan** [comment]
> Same issue. The bug happened on android 15 update. These are my observations.
> 
> Mic icon is working Setting the dock to google website is working Set the dock to other 3rd party app. They are working.
> 
> I think it is not a pure a15 issue. There are something need to update on launching the google app. If it is take too long to fix the problem in lawnchair. Try installing pixel search. It can launch google app with no problem

ok. and don't forget to set up as search provider in Lawnchair. and wow pixel search last update was June 16 2023 and it can launch the Google app. not sure what happening here

**Comment by MrSluffy** [comment]
fixed in latest `dev` build
