### ISSUE TITLE
[BUG] App shortcuts broken

### ISSUE THREAD

**Issue by ccarrier012** [Deletescape-Media/Lawnchair#4913]
### Describe the bug

When long pressing on apps on the home screen or app drawer does not pull up app shortcuts. 

### Steps to reproduce

1. Go to 'home screen or app drawer'
2. Click on 'any app for shortcuts'
3. See error

### Expected behavior

Long pressing an app icon should bring up a menu that includes app shortcuts. 

### Device information

- Device: [Google Pixel 7]
- OS: [stock ROM Android version 15.0]
- App version: [14, play store]

**Comment by sarojpanda44** [comment]
This is working for me in Andoird 15

**Comment by MrSluffy** [comment]
fixed in latest dev build, and make sure to set lawnchair as default home

**Comment by gajanand-jm** [comment]
Can you pls share dev build link? can't see under releases

**Comment by 0xAbdiiii** [comment]
> Can you pls share dev build link? can't see under releases

click on releases instead of the latest release, it will be labeled as a "pre-release". dev build means the nightly here.
