### ISSUE TITLE
[BUG] PLAY STORE VERSION ALERT

### ISSUE THREAD

**Issue by babarocketbay** [Deletescape-Media/Lawnchair#4919]
### Describe the bug

the popup in settings on the latest google play build for "we are on google play" alongside the others cant be dismissed permanantly.

### Steps to reproduce

1. open lawnchair
2. press and hold>home settings
3. swipe away 2 popups
4. close settings
5. press and hold>home settings

### Expected behavior

swipe away for the popups in settings, they stay permanantly

### Screenshots

![Screenshot_20241019-123703](https://github.com/user-attachments/assets/668d6326-4b60-414b-ba09-bba1bed5f3bf)
![Screenshot_20241019-123720](https://github.com/user-attachments/assets/4e787a70-a46a-4899-b0b6-2e27d360ccd7)
![Screenshot_20241019-123805](https://github.com/user-attachments/assets/01a72222-eaea-4b2e-9e1e-43c6e182ee27)

https://github.com/user-attachments/assets/26ed7a92-3ce6-47b5-ae24-8373c1b14a16

### Device information

- Pixel 7 pro
- OS: PixelOS [android 14+15] persisted in both
- App version: 14.dev.d7e3f32

**Comment by 0xAbdiiii** [comment]
This should be fixed with #4722 but the Play Store version is built from an earlier commit so it didn't make it into there.
