### ISSUE TITLE
[BUG] (OneUI No Root) Exiting application with Predictive Back Gesture will cause Lawnchair to crash

### ISSUE THREAD

**Issue by NicholasFlamy** [Deletescape-Media/Lawnchair#4923]
### Describe the bug

Same issue as #3812 except when the launcher crashes, the phone locks and reloads. I tested on Nightly#1532 and had the same issue, but no crash notification with logs appeared.

Might be Samsung's fault? (Tested on Samsung device.)

### Steps to reproduce

1. Set Lawnchair as home app.
2. Reboot (So Lawnchair is launcher on boot.)
3. Open any app with predictive back gesture support, e.g. hold down and open home settings.
4. Try to use back gesture (Instantly starts to crash)

Note: Workaround found
1. Open the stock (OneUI Home) launcher (Doesn't even have to be set as default, just has to be opened.)
2. Close it
3. Predictive back gesture back to home screen works normally on Lawnchair.

(I can automate this workaround using Tasker, Go Home action with OneUI Home as the package, just has to open the launcher and then the launcher can be exited.)

### Expected behavior

Show back gesture animation and not crash.

### Device information

- Device: Samsung Galaxy S22
- OS: stock Samsung OneUI 6.1 Android 14 (Unrooted)
- App version: 14 Beta 3 and Nightly

**Comment by validcube** [comment]
Mhm, this is odd, I can't reproduce it on my end. Tried with Lawnchair Settings (as shown on video), Google Calculator and Lawnicons.

https://github.com/user-attachments/assets/a57fb479-3708-47b2-9698-6e154758a334

Samsung M23 - Android 14 - One UI 6.1 - August 1st 2024
* Predictive Back animations is on

**Comment by NicholasFlamy** [comment]
> Mhm, this is odd, I can't reproduce it on my end. Tried with Lawnchair Settings (as shown on video), Google Calculator and Lawnicons.
> 
>  Screen_Recording_20241022_041411_Lawnchair.Debug.mp4 
> Samsung M23 - Android 14 - One UI 6.1 - August 1st 2024
> 
> * Predictive Back animations is on

Do you get the predictive back gesture animation for back to home on the stock OneUI Home launcher? (I do.)

If not, I would guess Samsung either only rolled it out to S-series phones or only to certain regions (I'm North America).

Issue where I posted a demo of it working: #4249

**Comment by validcube** [comment]
> > Mhm, this is odd, I can't reproduce it on my end. Tried with Lawnchair Settings (as shown on video), Google Calculator and Lawnicons.
> > Screen_Recording_20241022_041411_Lawnchair.Debug.mp4
> > Samsung M23 - Android 14 - One UI 6.1 - August 1st 2024
> > 
> > * Predictive Back animations is on
> 
> Do you get the predictive back gesture animation for back to home on the stock OneUI Home launcher? (I do.)
> 
> If not, I would guess Samsung either only rolled it out to S-series phones or only to certain regions (I'm North America).
> 
> Issue where I posted a demo of it working: #4249

Huh, well I guess this is a bug with One UI 6.1 (on my end) where applications with predictive back don't have back-to-home screen animation because I used to be able to do it on One UI 5.x (surprised it took me too long to notice it)

**Comment by NicholasFlamy** [comment]
> > > Mhm, this is odd, I can't reproduce it on my end. Tried with Lawnchair Settings (as shown on video), Google Calculator and Lawnicons.
> > > Screen_Recording_20241022_041411_Lawnchair.Debug.mp4
> > > Samsung M23 - Android 14 - One UI 6.1 - August 1st 2024
> > > 
> > > * Predictive Back animations is on
> > 
> > 
> > Do you get the predictive back gesture animation for back to home on the stock OneUI Home launcher? (I do.)
> > If not, I would guess Samsung either only rolled it out to S-series phones or only to certain regions (I'm North America).
> > Issue where I posted a demo of it working: #4249
> 
> Huh, well I guess this is a bug with One UI 6.1 (on my end) where applications with predictive back don't have back-to-home screen animation because I used to be able to do it on One UI 5.x (surprised it took me too long to notice it)

That's funny (but unfortunate), you lost the feature and I gained the feature.

**Comment by MrSluffy** [comment]
this issue still persists latest nightly?

**Comment by NicholasFlamy** [comment]
Please don't close the issue without any resolution. You asked if it's still an issue and closed the issue. How should I respond?

Can confirm that the issue still occurs in [`Lawnchair.Debug.15-dev.Nightly-CI_1778-2c5cc56.apk`](https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.15-dev.Nightly-CI_1778-2c5cc56.apk).

Here is the tasker project (I made it myself) I have been using as a workaround for the time being:
taskerproject://H4sIAAAAAAAAAO2VW2vbMBTHn9NPIQyDFool2bIdgWJYd+kCgw7asWdhq4kaxw6ykm3ffro4qeM4edjlbU86PkeXc37/I4s98XYl1HuuOWjVLAhAuZOzAAdA72ZBGuIwjoL8asK+qOZZVsJN2hgbTwOwE7PARSesKLkWOc4iSilGeBoRxKB32rDowjHBNIkiSuKYQXEIP1d80eZTBr1hXbLMsXGYwX5Vci11rtVWMOht613LEplNGXSG9dRrkT9sRA0eavF1Dj41awGelub7XdW0Alx/lD/AHS9W4F60eqsEuNsubhi0y+zyDztRa1di0dSoX6CpsClFTjA2ZVnL+TZK5qZOO9jl0K23tGCHqyP3Igq9J/eCzoCLKY0QTeK0D67mJrXrb2rFVRPegMfvUhdL8Jlv62IpVGtS513uG1m2DpkzrEc7T3qL6a2FpL3f5WYTsrZV3yWmjYHTYUqEoBgnJEnHtPRSR1mGSV9LK1x6EM6SvW+cEK+YLS+MeuDeFlo2tUuEF7oDlPXBR0mf+7xTiauFncyrWYAC6GOPWu1j2G8U+xCD/hjHwBZ+CiA7ARBPTfkZIaPNjKIUZRhnNB0CyI4AjHbk36CCY9TH0isd7UsfHs6gmXVCEftdJ2zHVf7GJNAoqX8yaD/dXDh3jT1YtYePR+BHR/CPQvH5EBmEeqclQ6V7sfRCF2Tnt5xe2JIex3rdM1QG/6Yyhw74r8gfKnLuPtOxxylJEkLP/9DMG5XQ4X2ml+7z6xX+1/+xvGjWYSuKkNelamQZ8s0mrLrH4NBHI2D86N/5/OoX6fWaO/UHAAA=

(It opens (not sets as default, simply launches it) the OneUI Home app (Samsung default launcher) and then triggers going home, which is equivalent to home button/home gesture.)

**Comment by MrSluffy** [comment]
close this since no crash logs! Please don't expect Dev has device as same as yours

**Comment by NicholasFlamy** [comment]
> close this since no crash logs! Please don't expect Dev has device as same as yours

Please let me know how to obtain crash logs, the only thing I found was this: https://lawnchair.app/faq/#lawnchair-v12-alpha-3

This tells me to get them from the notification, but Lawnchair did not send a notification.

Edit: Yes, notifications are enabled, including all notification categories.

**Comment by MrSluffy** [comment]
Please make sure upload status is enabled

Once enabled any crashes within the lawnchair should be catch

https://streamable.com/agjktt

**Comment by NicholasFlamy** [comment]
The button to trigger a crash results in crash logs:

https://github.com/user-attachments/assets/389d7943-04c5-4990-9711-12c353f4c327

The issue I am reporting does not:

https://github.com/user-attachments/assets/1c1784a6-e63a-4b51-a72b-155cf386104e

**Comment by MrSluffy** [comment]
Alrightyy then lawnchair is not crashing when using predictive

**Comment by NicholasFlamy** [comment]
I guess the whole Springboard (or wtv it's called, the Android System UI, I think it's Springboard on iPhone) is crashing, the weird thing is it also happens with Nova (just installed it to confirm).

**Comment by NicholasFlamy** [comment]
> Might be Samsung's fault? (Tested on Samsung device.)

It might be like I said in the original post. Samsung breaking stuff, since simply opening their launcher causes this to no longer be a problem.
