### ISSUE TITLE
[BUG] Visual bug when closing apps

### ISSUE THREAD

**Issue by leonorlazami** [Deletescape-Media/Lawnchair#4927]
### Describe the bug

When closing apps, small yellow dots appear around the closed app window. This issue occurs consistently, regardless of the icon pack in use. It seems like a visual glitch that impacts the user interface.

### Steps to reproduce

1. Close any open app.
2. Observe the appearance of yellow dots in the area where the app was closed.

### Expected behavior

The app should close without any visual glitches, and no dots should appear.

### Screenshots

![image](https://github.com/user-attachments/assets/8fa58887-55fc-44fe-9e25-301c730cc57c)

### Device information

- Device: Google Pixel 8 Pro
- OS: Android version 14
- App version:  14.Dev(d7e3f32)

### Additional context

This happens with every icon pack, so it seems unrelated to the icon pack being used.

**Comment by An-anonymous-coder** [comment]
I reproduced this

```
GrapheneOS 2024102400 (Android 15)
Pixel 8
Lawnchair v14.0.0-beta3
```

**Comment by MrSluffy** [comment]
fixed in `15-dev`
