### ISSUE TITLE
[FEATURE] Private Space

### ISSUE THREAD

**Issue by krzemyczek** [Deletescape-Media/Lawnchair#4928]
### Describe the feature

New Android 15 feature allowing separate apps in one profile

### Why would it be useful to add?

Better experience. Privacy space is excellent feature for GrapheneOS allowing easy separating google.play services from the rest of the phone

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20241023-083018_1](https://github.com/user-attachments/assets/aebe9816-9800-40d0-8d6e-44b2caa99c60)
Grapheneos launcher private space support

### Additional context

I know that it has no importance, but still I think that it is good to have feature request here.

BTW. Thanks for the greatest open source home launcher so far!

**Comment by krzemyczek** [comment]
Oh, there are 2 other, I searched "privacy space" that's why I didn't find other ones

**Comment by IamSingh01** [comment]
+1
