### ISSUE TITLE
Weird shadow appears behind search bar in app drawer

### ISSUE THREAD

**Issue by jahirfiquitiva** [Deletescape-Media/Lawnchair#493]
This happens when 'remember position' is enabled. And one scrolls to somewhere below the very top, and then closes the app drawer. Since it isn't at the very top, it always shows this ugly thing.

![screenshot_20170812-090141 01](https://user-images.githubusercontent.com/10360816/29241422-f6bf412a-7f3e-11e7-977b-8c821610ceaf.png)

**Comment by suphon-t** [comment]
This is an Android bug and is fixed in Nougat.

**Comment by jahirfiquitiva** [comment]
@paphonb 

I'm using Android 7.1.2 and it's happening

**Comment by suphon-t** [comment]
Whatever version, it's still an Android bug.

**Comment by jacksonhvisuals** [comment]
Noticed this as well on my Pixel 2 XL, Android 8.1. Practically makes the "remember position" option unusable. Either we fix it, or we need to remove the option to remember position.

**Comment by jahirfiquitiva** [comment]
@jacksonhvisuals 
Please don't remove it. I like it. It's pretty useful.
