### ISSUE TITLE
Search bar randomly stops working

### ISSUE THREAD

**Issue by SomeDudeBrosky** [Deletescape-Media/Lawnchair#4933]
### Describe the bug

I am running the official website release of lawnchair on Android 15. I do not know why but the search bar has completely stopped working. I've restarted lawnchair and cleared storage cache and the issue persists.

### Steps to reproduce

Unknown

### Expected behavior

Search function at bottom of home screen does not function.

### Screenshots

https://github.com/user-attachments/assets/6710cd1e-bd8b-40db-ae03-12ca8fd910e7

### Device information

- Device: Google pixel 8 pro
- OS: stock Android 15
- App version: 14.Beta 3

**Comment by MrSluffy** [comment]
fixed in `15-dev`
