### ISSUE TITLE
Improve Freeform

### ISSUE THREAD

**Issue by keyjeyelpi** [Deletescape-Media/Lawnchair#4935]
### Describe the feature

Turning apps into windows. It'd be cool to have it mimick the behaviors of bubble

### Why would it be useful to add?

- Using tiny windowed app when multitasking is easier. 
- Some apps such as Grab don't have a PiP mode and tracking orders would be easier on the go. 

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

See HyperOS implementation for reference

**Comment by MrSluffy** [comment]
This is Android implementation itself
