### ISSUE TITLE
[BUG] Infinity Recreate

### ISSUE THREAD

**Issue by ZL114514** [Deletescape-Media/Lawnchair#4937]
### Describe the bug

When do any changes on it, it will recreate Infinitely. But restarting system UI can't stop. Only changing the launcher or restarting phone can help 

### Steps to reproduce

1. Use the QuickSwitch
2. Enable the Lawnchair for both launcher and switch 
3. Do any changes like changing wallpaper

### Expected behavior

Stop recreate 

### Device information

- Device: xaga
- OS: drepfest 13
- App version: recent nighty

**Comment by MrSluffy** [comment]
Hi can you share more info about this like log, Thanks!
