### ISSUE TITLE
[BUG] Icons added twice and both removed

### ISSUE THREAD

**Issue by andreapx** [Deletescape-Media/Lawnchair#4938]
### Describe the bug

Sometimes when I add an icon to the home screen it adds it twice. It happened only when adding them directly to a folder.
The second icons that it automatically adds is in the first home and they are over the clock widget and overlapped (allow overlap is turned off).
If I remove the icons that it automatically adds, it also deletes the one I've added (in the folder).

### Steps to reproduce

1. add n icon directly to a folder
2. in the first home page there is a second icon of the app I've just added
3. remove this last icon
4. the icon added to the folder get removed

### Expected behavior

An icon app is added once in the position selected

### Device information

- Device: Pixel 7
- OS:stock ROM Android version 15.0
- App version: 14.Beta 3

**Comment by ccyybn** [comment]
Same problem, I think it's not always reproducible, sometimes you restart the launcher and it goes away

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly
