### ISSUE TITLE
[FEATURE] Let hidden apps appear in search results

### ISSUE THREAD

**Issue by popogomo** [Deletescape-Media/Lawnchair#4944]
### Describe the feature

If we hide an app, it won't appear in search results when we search for it from app drawer. This is inconvenient as not every hidden app is useless, for example, some apps have Settings shortcut that we might want to hide to tidy app drawer but we might still want to access it.

### Why would it be useful to add?

For example, some apps have Settings shortcut that we might want to hide to tidy app drawer but we might still want to access it. In this case, we will have to go back to settings and unhide the app to access it, then hide it again which is inconvenient.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

As described

**Comment by 0xAbdiiii** [comment]
but.. what's this...? ![Screenshot_20241030-100016.png](https://github.com/user-attachments/assets/c054bc03-faee-419a-8f8f-d61a0743012f)

![Screenshot_20241030-100031.png](https://github.com/user-attachments/assets/c6e971dd-ee64-4374-b232-ca9973ae5ad4)

**Comment by popogomo** [comment]
Strangely, I don't see this option in the latest beta (14 Beta.3 from F-Droid). The screenshot is attached.

![img1](https://github.com/user-attachments/assets/00135f69-6937-45ab-b01f-e07081e256f9)

**Comment by 0xAbdiiii** [comment]
see #1473 

i didn't know there was an official Fdroid release. Try downloading from Github releases.

**Comment by validcube** [comment]
> Strangely, I don't see this option in the latest beta (14 Beta.3 from F-Droid). The screenshot is attached.
> 
> ![img1](https://private-user-images.githubusercontent.com/118138132/382418389-00135f69-6937-45ab-b01f-e07081e256f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTgzOTksIm5iZiI6MTczMDU1ODA5OSwicGF0aCI6Ii8xMTgxMzgxMzIvMzgyNDE4Mzg5LTAwMTM1ZjY5LTY5MzctNDVhYi1iMDFmLWUwNzA4MWUyNTZmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNDM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGRmNzM3NjJlYTdiZjljNmQxODU1YTAxMTEyMTcyYTY1ODU2YjNlZmMwM2I3ZDM1Nzk3MTk0MmY5MzhlY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6-ReOmqEIkofD5TC69D4jDCeDTVRsY_bxplrd1G9ZjY)

The option only appears when you hide at least one application.

**Comment by popogomo** [comment]
> > Strangely, I don't see this option in the latest beta (14 Beta.3 from F-Droid). The screenshot is attached.
> > ![img1](https://private-user-images.githubusercontent.com/118138132/382418389-00135f69-6937-45ab-b01f-e07081e256f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTgzOTksIm5iZiI6MTczMDU1ODA5OSwicGF0aCI6Ii8xMTgxMzgxMzIvMzgyNDE4Mzg5LTAwMTM1ZjY5LTY5MzctNDVhYi1iMDFmLWUwNzA4MWUyNTZmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNDM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGRmNzM3NjJlYTdiZjljNmQxODU1YTAxMTEyMTcyYTY1ODU2YjNlZmMwM2I3ZDM1Nzk3MTk0MmY5MzhlY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6-ReOmqEIkofD5TC69D4jDCeDTVRsY_bxplrd1G9ZjY)
> 
> The option only appears when you hide at least one application.

Thanks a lot, it did the trick! A bit tricky to find but its there ))

**Comment by popogomo** [comment]
The feature is already present
