### ISSUE TITLE
[BUG] home screen layout shrinks sometimes with smaller widget and app icons

### ISSUE THREAD

**Issue by amithvik1** [Deletescape-Media/Lawnchair#4946]
### Describe the bug

Usually whenever I exit an app the app icons move up by some space and the custom widget (kustom) also shrinks down and when I resize the widget it glitches out sometimes

This is however fixed when I restart my phone or lawnchair itself

### Steps to reproduce

Doesn't have any specific steps just returning back to the homescreen triggers it to resize the icons and reposition the apps sometimes (not always)

### Expected behavior

The apps should not switch from original place and the size of the widget should remain same as before
Screenshot 1 is the original 
Screenshot 2 is the one after the bug 

### Screenshots

![Screenshot_20241029-083705_Lawnchair](https://github.com/user-attachments/assets/fbb13acc-b7e8-4732-bea1-47bcb3d5f9d8)
![Screenshot_20241029-083649_Lawnchair](https://github.com/user-attachments/assets/d0eec83d-b00c-4426-a40d-61db5fcde556)

### Device information

- Device: [samsung m31s]
- OS: [estock ROM Android version 12.0]
- App version: 14 beta.3

**Comment by ghost** [comment]
Eu também tenho esse problema.
Às vezes do nada reduz o tamanho de alguns ícones de aplicativos.

**Comment by MrSluffy** [comment]
fixed in latest `15-dev` build
