### ISSUE TITLE
[BUG] Gesture Navigation Bar Takes Up Space and Prevents Access to Buttons in Games

### ISSUE THREAD

**Issue by NintendxVC** [Deletescape-Media/Lawnchair#4960]
### Describe the bug

I have been using Lawnchair as my default launcher and discovered that this app is responsible for keeping the gesture navigation bar visible when rotating the screen during games.

When entering games in horizontal mode, the navigation bar sometimes does not disappear, remaining visible. This prevents tapping any button in the occupied area, as if the bar is overlaying the game screen.

A behavior that can be replicated is that when rotating the screen within the game by 180°, the bar appears centered, preventing touch in the area it occupies but allowing touch in the previously overlaid area.

Additionally, when exiting the game with the phone in vertical mode, the bar appears in the center of the left side of the screen and remains visible after leaving the game.

### Steps to reproduce

**Note:** Have gesture navigation enabled.

**Steps to reproduce behavior 1:**
1. Start a game that is by default in horizontal mode.
2. Observe the error on the right side of the screen. (My phone is set to rotate to the left; I don’t know if this is standard for others.)

**Steps to reproduce behavior 2:**
1. Start a game that is by default in horizontal mode.
2. In horizontal mode, pull up the navigation bar twice to open recent apps.
3. Click again on the game.
4. Observe the error at the bottom of the screen.
5. Rotate the phone 180°.
6. Observe the error in the center of the screen.

**Steps to reproduce behavior 3:**
1. With the game open and showing the error described in step 2, part 4, go back to Home.
2. Observe the error on the left side of the screen.

**Note:** Some games do not show any errors until transitioning between apps (like Identity V), while others may disappear after rotating the screen 180° once or twice (like SKY). The games experiencing this issue are Cytus II and Phigros.

### Expected behavior

What I expected was that when entering the game in horizontal mode, the navigation bar would position itself at the bottom of the screen and disappear. When I pulled up, it should appear and remain at the bottom while accessing recent apps in horizontal mode. If I entered another app or returned to Home in vertical mode, the bar should slide down and remain visible.

### Screenshots

Behavior 1
![Screenshot_20241104-001831](https://github.com/user-attachments/assets/dec5673d-bd6e-4217-bffb-ae38019370f4)

Behavior 2
![Screenshot_20241104-003634](https://github.com/user-attachments/assets/3e91c00e-740a-4a07-9e45-ca9b9b2ad9cb)
![Screenshot_20241104-010640](https://github.com/user-attachments/assets/02db866f-3fd3-42d3-9c67-09ca66c62344)

Behavior 3
![Screenshot_20241104-003054](https://github.com/user-attachments/assets/cd85ae81-ae38-4bb8-ab6e-fe1d57d60e4e)

### Device information

- Device: [Moto One Fusion+]  
- OS: [stock ROM version Android 11.0]  
- App version: [12.1.0 Alpha 4, 14.Beta 3, and Nightly]

**Comment by thatAkiraFox** [comment]
I'm gonna assume you're not using QuickSwitch.

This is probably an issue with Android itself, since it sometimes also happens on my Pixel 8 running the default Pixel Launcher on the stock ROM.

If you are indeed not using QuickSwitch then that would explain why you're facing this issue so frequently, as using a third party launchers makes this issue appear more often (in my experience).

**Comment by NintendxVC** [comment]
@thatAkiraFox In fact, I don't use QuickSwitch because my phone is not rooted, but I've never had any related problems with my default launcher, in this case Motorola's Moto App Launcher (Launcher 3).

**Comment by thatAkiraFox** [comment]
As I said, it *can* happen with the stock launcher too, but using third party launchers makes the issue occur more often. 

All of this to say that Lawnchair has no control over this issue.

**Comment by NintendxVC** [comment]
@thatAkiraFox I understand, thanks for this.
