### ISSUE TITLE
Adding widget to home screen causes crash

### ISSUE THREAD

**Issue by EthanZeigler** [Deletescape-Media/Lawnchair#4968]
Adding a widget from the Foreca app (weather) is causing Lawnchair to crash. When attempting to upload the error log, it fails so I'm reporting it here manually instead.

![Lawnchair bug report Nov 5, 2024 4:31:11 PM.txt](https://github.com/user-attachments/files/17638826/Lawnchair.bug.report.Nov.5.2024.4.31.11.PM.txt)

Any widget from the app causes it. I understand it might be the widget's fault but Lawnchair itself shouldn't be crashing from it regardless.

**Comment by validcube** [comment]
The issue is fixed, try the latest Lawnchair version. (Lawnchair 14 Beta 3)

**Comment by EthanZeigler** [comment]
The error is fixed! But the root issue doesn't seem to be. I'm unable to add widgets whatsoever. I went back and checked the last beta release and confirmed it wasn't specific to one app. It's all of them.

Now adding a new widget causes other widgets to reload but the added one never appears. Same behavior on beta 2 with the added error warning.

**Comment by adamk33n3r** [comment]
I also cannot add any widgets. I drag and place, choose settings. And then nothing happens.

**Comment by MrSluffy** [comment]
fixed in `15-dev`
