### ISSUE TITLE
[BUG] [DUPE] #4875 A10 icon picker opens launcher settings instead

### ISSUE THREAD

**Issue by NekoMimiOfficial** [Deletescape-Media/Lawnchair#4974]
### Describe the bug

when trying to change an icon from an icon pack (lawnicons) the icon picker doesnt show up but instead the launcher settings

### Steps to reproduce

1. Long click an app  
2. Click customize  
3. Tap the icon  
4. Gets redirected to launcher settings

### Expected behavior

opens the icon picker

### Device information

- Device: [Sadsung Galaxy J6]
- OS: [OneUI 2.0 Android 10]
- App version: [Goooler fork 20241101] (and it also happened since the next Goooler release after the app store release)

**Comment by tgex0** [comment]
Dupe of #4875.

**Comment by NekoMimiOfficial** [comment]
My bad
