### ISSUE TITLE
[BUG] widget 

### ISSUE THREAD

**Issue by tronderbataljon** [Deletescape-Media/Lawnchair#4977]
### Describe the bug

When adding Acalendar widget (month), the widget looks fine at first, but after some time ut look totally stretced 

### Steps to reproduce

1. Add a Aca month widget on second home screen 
2. Use phone for some time 
3. Scroll back to widget screen 

### Expected behavior

Should look good all the time 

### Screenshots

![Screenshot_20241105-135924](https://github.com/user-attachments/assets/558fb8e5-fc91-487b-a881-7ed2ca3400de)

### Device information

- Device: Google pixel 9 pro 
- OS: stock android 15 
- App version: lawnchair 14 v3

**Comment by tronderbataljon** [comment]
![Screenshot_20241105-230340](https://github.com/user-attachments/assets/97104527-3692-405c-b55b-2d35484e1cdf)

**Comment by MrSluffy** [comment]
fixed in `15-dev`
