### ISSUE TITLE
[BUG] weather widget does not respect units setting

### ISSUE THREAD

**Issue by CamronBorealis** [Deletescape-Media/Lawnchair#4981]
### Describe the bug

The weather widget no longer shows temperature in Celsius.

### Steps to reproduce

1. Add the temperature widget to the home screen 
2. Click temperature on the weather widget
3. In the open Google app, open settings and set the Weather Units to Celsius
4. Look at the temperature on the weather widget 

### Expected behavior

Temperature is shown in Celsius

### Device information

- Device: Google Pixel 8
- OS: stock Pixel Android 15
- App version: v14.0.0.0-beta3

**Comment by MrSluffy** [comment]
this is from google weather sides, since we hook the weather unit from google

**Comment by jp1995** [comment]
But what's the solution for the user then? Probably a large part of the userbase dont want to convert to celsius every time they look at the widget.
