### ISSUE TITLE
[BUG] quick switch issues

### ISSUE THREAD

**Issue by yakat-web** [Deletescape-Media/Lawnchair#4982]
### Describe the bug

i have an issue with quick switch when i want to switch providers
it gives an error message

### Steps to reproduce

1.open quick switch
2.select lawnchair
3.error message

### Expected behavior

i've allready tested 14 beta 3 ,2,1 and dev release too

### Device information

- Device: mi 11 lite 5g
- OS: lineage os 21
- App version:14 beta 3

**Comment by CoelacanthusHex** [comment]
What's the error message? Could you provide the content of it?

BTW, I meet a crash about quickstep, see https://github.com/LawnchairLauncher/lawnchair/issues/4965

**Comment by 0xAbdiiii** [comment]
This might help you.

https://github.com/skittles9823/QuickSwitch/issues/73

**Comment by 0xAbdiiii** [comment]
@CoelacanthusHex can you use Lawnchair 15 with Quickswitch? It crashes instantly for me but i can use it when it's not the recents provider.

**Comment by CoelacanthusHex** [comment]
> @CoelacanthusHex also, can you use Lawnchair 15 with Quickswitch? It crashes instantly for me.

It crashed for me too. See https://github.com/LawnchairLauncher/lawnchair/issues/4965

> Can use it without setting it as recents provider though.

I got the same crash backtrace.

**Comment by 0xAbdiiii** [comment]
@CoelacanthusHex i can launch it normally with #4978 but can't while it's set as the recents provider.

**Comment by berkekbgz** [comment]
> This might help you.
> 
> [skittles9823/QuickSwitch#73](https://github.com/skittles9823/QuickSwitch/issues/73)

After applying this, it patches lawnchair with no error but recents provider still stuck on Quickstep. Does anyone has fix?

Android 14
Lawnchair 14 Beta 3
QuickSwitch 4.0.3
Magisk 28.1

**Comment by 0xAbdiiii** [comment]
> > This might help you.
> > 
> > [skittles9823/QuickSwitch#73](https://github.com/skittles9823/QuickSwitch/issues/73)
> 
> After applying this, it patches lawnchair with no error but recents provider still stuck on Quickstep. Does anyone has fix?
> 
> Android 14
> Lawnchair 14 Beta 3
> QuickSwitch 4.0.3
> Magisk 28.1

check your documents folder in storage to see if you have any Quickswitch logs
