### ISSUE TITLE
[BUG] 'Pixel Search' search provider redirects me to the google play store

### ISSUE THREAD

**Issue by Momen-MKadry** [Deletescape-Media/Lawnchair#4985]
### Describe the bug

I chose the search provider to be the Pixel Search app and when I click on the search bar it opens the Google Play Store even though I have the app installed

### Steps to reproduce

1. Ensure [Pixel Search](https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch&pcampaignid=web_share) is installed
2. Go to Lawnchair's 'Home Settings'
3. Click on 'Dock'
4. Click on 'Search Provider'
5. Choose 'Pixel Search'
6. Return to home screen.
7. Tap the search bar

### Expected behavior

'Pixel Search' app should open and you could use it to search

### Device information

- Device: Samsung Galaxy A35 5G
- OS: Android 14
- App version: 14.Beta.3

**Comment by MrSluffy** [comment]
this should fix now in latest nightly

**Comment by tfriedel** [comment]
this is happening for me also.
