### ISSUE TITLE
[BUG] can't long press on icons to customize them android 15

### ISSUE THREAD

**Issue by greysstreet** [Deletescape-Media/Lawnchair#4986]
### Describe the bug

I can no longer customize icons in my app drawer by long pressing on them to prompt the 'customize' option to open along with uninstall and app info. any fixes for this? it's been a while since android 15 has been out and still problems. I can't install v3 or nightly either 

### Steps to reproduce

1. go to app drawer 
2. long press on any app 
3. no "customize" option is there

### Expected behavior

when you long press you should see the customize option 

### Device information

pixel 9 xl pro
running android 15

**Comment by thatAkiraFox** [comment]
Make sure that the "lock home screen layout option" in Lawnchair Settings > Home is turned off

**Comment by MrSluffy** [comment]
fixed : 4e96bd45c9bade9fa19381a158644b6494db2c95
