### ISSUE TITLE
Edit app dialog is not themed

### ISSUE THREAD

**Issue by intelligentcasanova** [Deletescape-Media/Lawnchair#499]
The edit app dialog stays white no matter which theme you've selected.

**Comment by AxiK101** [comment]
Screenshot?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
![screenshot_20170813-104258 2](https://user-images.githubusercontent.com/30270698/29248277-74d64042-8014-11e7-88fb-7cad51783322.png)
This is with dark theme selected.

**Comment by guest4711** [comment]
Works for me on 1179
![screenshot_20170815-005406](https://user-images.githubusercontent.com/26175945/29295539-38fcbf50-8155-11e7-8879-8a26b631946e.png)
