### ISSUE TITLE
[BUG] Latest Nightly Build Crashing

### ISSUE THREAD

**Issue by swarits1ngh** [Deletescape-Media/Lawnchair#4991]
### Describe the bug

I installed the new nightly build released on 11/5/24, and the app kept crashing on open.

### Steps to reproduce

1. Install nightly release of 11/5/24
2. Open the app
3. It crashes

### Expected behavior

The App opens are functions as normal

### Device information

- Device: Moto g 5G 2024
- OS: Motorola MyUX, OEM
- App version: Lawnchair 15-dev branch 11/5/24 Nightly Build

**Comment by DoYouKnowMyNamePlz** [comment]
Did you even attempt to see if this is a duplicate? Because I see about 5 others with this same exact issue 1 being right under yours. You guys are not helping by doing this.

**Comment by SuperDragonXD** [comment]
Duplicate of #4965
