### ISSUE TITLE
[FEATURE] Ability to get previous Nightly Builds

### ISSUE THREAD

**Issue by swarits1ngh** [Deletescape-Media/Lawnchair#4992]
### Describe the feature

The ability to download and use previous nightly builds.

### Why would it be useful to add?

Some people, like myself would like to access older nightly builds for some reasons.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Being able to go back to previous version if the new nightly build is crashing.

**Comment by NekoMimiOfficial** [comment]
You can install older artifacts just fine, I see no reason for this issue, a night build is the latest successfully built artifact

**Comment by SuperDragonXD** [comment]
As stated above, you can install older nightly builds by going to the Actions tab. Closing this issuem
