### ISSUE TITLE
[BUG] Can't take a screenshot of the Homescreen

### ISSUE THREAD

**Issue by ticoeteco23gb** [Deletescape-Media/Lawnchair#4994]
### Describe the bug

I can't take a screenshot of the Homescreen, as the Launcher doesn't appears. It just the wallpaper, and the phone UI, everything else remains transparent.

### Steps to reproduce

1. Go to the homescreen
2. Take a screenshot

### Expected behavior

The Screenshot content should be able to show my Homescreen, with the widgets and the apps icons.

### Screenshots

![Screenshot_20241111-202410](https://github.com/user-attachments/assets/17153e5a-c2fb-4a07-ab83-64c4bef369d7)

### Device information

- Device: Motorola g52
- OS: Android 14
- App version: 14.0.0 Beta 3

### Additional context

Google Play version also has this bug.

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
