### ISSUE TITLE
Awesome App Icon for Lawnchair

### ISSUE THREAD

**Issue by ZerNico** [Deletescape-Media/Lawnchair#5]

**Comment by parthkalsi88** [comment]
Its Already Awesome 😂

**Comment by deletescape** [comment]
@ZerNico don't forget this :joy: :wink:

**Comment by deletescape** [comment]
@ZerNico any update on this?

**Comment by ZerNico** [comment]
@deletescape I tried some stuff. Everything ended up looking awful so far

**Comment by deletescape** [comment]
noice
