### ISSUE TITLE
Carpet Size Bug

### ISSUE THREAD

**Issue by ShadowRedel** [Deletescape-Media/Lawnchair#500]
When you put the icon scale too big the carpets get bugged.
![screenshot_20170812-185245](https://user-images.githubusercontent.com/30420859/29242559-b91ab330-7f8f-11e7-871d-d68a8e4f3b51.png)

**Comment by brody192** [comment]
Why would you ever have them this big??

**Comment by suphon-t** [comment]
Reduce icon columns.
