### ISSUE TITLE
[BUG] v15 Goooler broken

### ISSUE THREAD

**Issue by oniGino** [Deletescape-Media/Lawnchair#5001]
### Describe the bug

latest Goooler build crashing on launch

https://github.com/Goooler/LawnchairRelease/releases/tag/15.0.0-20241114

I'm failing here on latest stable android pixel 8 with

[2024-11-14T13_33_25.991373.txt](https://github.com/user-attachments/files/17758105/2024-11-14T13_33_25.991373.txt)

### Steps to reproduce

start app

### Expected behavior

not crash

### Device information

- Device: [e.g. Google Pixel 8]
- OS: GrapheneOS Latest Stable
- App version: [15.0.0-20241114]

**Comment by SuperDragonXD** [comment]
Unofficial builds are not supported. Alongside that, please see the pinned issue for `15-dev` related crashes.

**Comment by senolfndk** [comment]
Doesn't open

**Comment by oniGino** [comment]
> Unofficial builds are not supported. Alongside that, please see the pinned issue for `15-dev` related crashes.

@Goooler who is on your development team asked me to post this here...

**Comment by oniGino** [comment]
> Doesn't open 

Correct crashes immediately

**Comment by oniGino** [comment]
Still broken, same issue as #5009
