### ISSUE TITLE
[BUG] Lawnchair is completely broken on latest nightly

### ISSUE THREAD

**Issue by colemickens** [Deletescape-Media/Lawnchair#5004]
### Describe the bug

I had to completely revert to the stock Pixel launcher. Lawnchair just flatly does not load anything with the latest nightly.

`Lawnchair.Debug.14-dev.Nightly-CI_1575-6d915c1.apk`

### Steps to reproduce

I have no idea.	

### Expected behavior

Lawnchair doesn't completely fail to load without any info as to what's going on.

### Device information

- Device: Google Pixel 6a
- OS: Android 15
- App version: `Lawnchair.Debug.14-dev.Nightly-CI_1575-6d915c1.apk`

**Comment by 0xAbdiiii** [comment]
Yes, we know. L15 is not launchable yet. It just got merged like last week.

You can close this as it's dupe of #4965

**Comment by colemickens** [comment]
Thank you @s0m3th1ng-r4nd0m. God speed, good luck, I love my Lawnchair!
