### ISSUE TITLE
Dark ui element options for use with light theme

### ISSUE THREAD

**Issue by sln45** [Deletescape-Media/Lawnchair#501]
I think it would be nice to have the option of using dark search bar icons and dark navbar buttons to better see them while using the 'light' theme, especially with blur activated.

**Comment by suphon-t** [comment]
Dark navbar buttons can't be implemented for Nougat or lower.

**Comment by paphonb** [comment]
Dark navbar buttons can't be implemented for Nougat or lower.

**Comment by sln45** [comment]
Didn't stop someone from adding dark navbar buttons to the drawer. The APK targets O anyway, right?

**Comment by suphon-t** [comment]
Alright try to prove me wrong.

**Comment by sln45** [comment]
Prove you wrong about what?

**Comment by sln45** [comment]
Oh... I'm not arguing that it's possible. I have Android O, and I'm saying that the developers are already adding Android O specific features.

**Comment by suphon-t** [comment]
Then why would you ask this? It's already added.

**Comment by sln45** [comment]
What the heck? It's only in the drawer. They're white on the homescreen so I can't see them. White on white.

**Comment by sln45** [comment]
This feature does not exist test

**Comment by sln45** [comment]
*yet
