### ISSUE TITLE
[BUG] App Drawer is not ordered alphabetically, and search is inconsistent.

### ISSUE THREAD

**Issue by Mstrymn** [Deletescape-Media/Lawnchair#5012]
### Describe the bug

Two problems
1) The app drawer is not ordered alphabetically. Youtube is the first app. This is not any kind of recency bias because there are apps I haven't used in months near the top. 

2) Search only seems to find applications that have been recently cashed. It requires me to scroll all the way to the end of the app drawer for Search to find Quick Switch, which should not be the last app. 

### Steps to reproduce

1. Go to 'App Drawer'
2. See error

1. Go to 'App Drawer'
2. Search for an app not immediately seen on the first few rows of apps in the drawer
3. App doesn't come up
4. Scroll to the bottom of the drawer
5. Search for the same app
6. App shows up

### Expected behavior

Apps are sorted alphabetically and search brings up the app you type for.

### Screenshots

https://github.com/user-attachments/assets/55ff97dd-46cc-49fe-82dc-eb1a8f62d52f

### Device information

- Device: Google Pixel 7 Pro
- OS: Stock Pixel Android 15 Rooted
- App version: 14.Dev.(d7e3f32), 14 Beta 3, (Lawnchair.Debug.14-dev.Nightly-CI_1575-6d915c1 crashes on startup.)

**Comment by MrSluffy** [comment]
Disable load inbulk options
