### ISSUE TITLE
[BUG] Changing dock resizes widgets

### ISSUE THREAD

**Issue by issteve** [Deletescape-Media/Lawnchair#5016]
### Describe the bug

With widgets on homescreens (e.g. calendar) changing something on the dock is resizing the widgets to something (smaller).

### Steps to reproduce

1. Place a widget on the homescreen which you resize to something (e.g. more rows).
2. Change in the settings something on the dock.
3. Check widget size.

### Expected behavior

Changing something on the dock should not effect anything above the dock.

### Device information

- Device: Fairphone 5
- OS: stock ROM Android version 14.0
- App version: latest Playstore 14.Dev.(d7e3f32)

**Comment by st0neh** [comment]
Changing dock settings doesn't even do anything for me.  Set it to any number and it just stays at 5.

**Comment by issteve** [comment]
> Changing dock settings doesn't even do anything for me. Set it to any number and it just stays at 5.

As I'm using it currently with 6, this doesn't seem related. You should open a separate bug report for the issue on your side.
