### ISSUE TITLE
[BUG] homescreen frozen after recents page

### ISSUE THREAD

**Issue by Brauhhhh** [Deletescape-Media/Lawnchair#5019]
### Describe the bug

Went into the Recent's page to close out running apps then tried to go back to the homescreen but was frozen. Once again tried to go to the recents page then go back to the homscreen.... Still.

### Steps to reproduce

1. Go to the revenge page
2. Go back to homscreen
3. Now your presented with a frozen recents page ( might not always be a frozen screen if it's only for me )

### Expected behavior

Homescreen just like other launchers like the default stock launcher.

### Screenshots

![Screenshot_20241126_101656_Lawnchair](https://github.com/user-attachments/assets/79800e68-0f58-4d92-b1f2-5941c639a9d6)

### Device information

- Device: [e.g. S23 Ultra]
- OS: [e.g. stock ROM Android version 14.0]
- App version: [e.g. 14 Beta 3]

**Comment by MrSluffy** [comment]
use latest nightly if still exists use quickswitch if still doesn't work reopen this
