### ISSUE TITLE
Google search bar is strange and some apps doesn't have shortcuts

### ISSUE THREAD

**Issue by ArmanKir-yan25** [Deletescape-Media/Lawnchair#502]
![screenshot_20170813-013149](https://user-images.githubusercontent.com/30963247/29244355-3f0ca1e2-7fc7-11e7-82b3-52ce00233bd2.jpeg)
![screenshot_20170813-013312](https://user-images.githubusercontent.com/30963247/29244368-906cfa82-7fc7-11e7-84fa-10699a801e59.jpeg)
![screenshot_20170813-013353](https://user-images.githubusercontent.com/30963247/29244367-906cf1d6-7fc7-11e7-83c5-abba9184ef37.jpeg)
![screenshot_20170813-013347](https://user-images.githubusercontent.com/30963247/29244369-9070b7a8-7fc7-11e7-8399-faab21b4d0f1.jpeg)
![screenshot_20170813-013324](https://user-images.githubusercontent.com/30963247/29244370-9072153a-7fc7-11e7-933d-fcf8942fc16b.jpeg)
![screenshot_20170813-013316](https://user-images.githubusercontent.com/30963247/29244371-907464f2-7fc7-11e7-952d-1f5e9a3c249c.jpeg)

**Comment by ArmanKir-yan25** [comment]
Why?

**Comment by ArmanKir-yan25** [comment]
This is Lenovo K6 Android 7.0 lawnchair 1.1.0.145

**Comment by AxiK101** [comment]
Probably you don't have Android 7.1.1. Thats why shortcuts don't work properly.

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
Search bar will look better if you disable full width widgets from settings

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
Hey grek why youtube had shortcuts, but chrome, seeting, maps doesnt. By the way in nova launcher those 3 are working 🤔

**Comment by KieronQuinn** [comment]
The shortcuts you are seeing working are static shortcuts. They can be and were backported. Dynamic shortcuts (the missing ones) cannot be backported. Nova has its own shortcut system.

**Comment by ArmanKir-yan25** [comment]
Can't you make your own shortcuts system

**Comment by KieronQuinn** [comment]
It would require developers to implement it, which nobody would do. If Sesame ever allow third party launchers (ie. those other than Nova) to use their shortcuts, then I'm sure the Lawnchair devs would be interested. But for now, there's no way to do it
