### ISSUE TITLE
[BUG] Lawnchair 15 refuses to show any available widgets or icon packs

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#5026]
### Describe the bug

I have wanted to set lawnchair 15 as my default launcher, however icon packs and widgets is not working

### Steps to reproduce

1. Go to 'lawnchair 15'
2. Hold and Click on 'settings'
3. Scroll down to 'icon packs'
4. Apply any icons
5. See error

1. Go to 'Lawnchair 15'
2. Hold and click on 'widgets'
3. See error

### Expected behavior

Icon packs should show properly and also widgets should show

### Screenshots

![Screenshot_20241130-212757](https://github.com/user-attachments/assets/86d6077c-d75d-47e6-b779-3da7e8c3dcaf)
![Screenshot_20241130-212749](https://github.com/user-attachments/assets/566a29f7-7638-463c-a32f-092a59a25481)
![Screenshot_20241130-212709](https://github.com/user-attachments/assets/ff9e470a-be70-45e2-8d39-7a6a8220fd62)

### Device information

- Device: [Teclast T40 Pro]
- OS: [Stock ROM Android version 12.0]
- App version: [Lawnchair 15 debug]

### Additional context

I am not using version 15 as default as i only want to use 14 beta for now

**Comment by MrSluffy** [comment]
fixed here 61c3db874e07a6b99fd2512aaab520a15086f7f8 and
6dbfe27f80f7afe6538764abb20d44979c4e2d45
