### ISSUE TITLE
[BUG] Duplicated and disappearing apps in the home screen

### ISSUE THREAD

**Issue by Sandyran** [Deletescape-Media/Lawnchair#5028]
### Describe the bug

When you add apps from the app drawer to the home screen, those apps get duplicated and appear in the top left corner of the home screen. Then, when you try to remove the duplicated app, the other app also disappears.

### Steps to reproduce

1. Go to app drawer.
2. Hold on a any app, so that it can be added to the home screen.
3. Add app to home screen.
4. See error.
5. By then removing the duplicated app, the other app also disappears.
6. See error.

### Expected behavior

Apps should get added to home screen, without any issues.

### Device information

- Device: Samsung Galaxy S24
- OS: Stock Android Rom version 14
- App version: 14.Dev.(d7e3f32)

**Comment by MrSluffy** [comment]
can you reproduce this in latest 15-dev?

**Comment by Sandyran** [comment]
> can you reproduce this in latest 15-dev?

Where do I download it from?

**Comment by MrSluffy** [comment]
https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.15-dev.Nightly-CI_1736-ced2f5a.apk

**Comment by Sandyran** [comment]
> https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.15-dev.Nightly-CI_1736-ced2f5a.apk

I don't know what I did before, but I am not experiencing the bug anymore in the new version. So, for now, I guess I can close this issue.
