### ISSUE TITLE
Please use original assistan icon difference is visible

### ISSUE THREAD

**Issue by ArmanKir-yan25** [Deletescape-Media/Lawnchair#503]
![screenshot_2017-08-13-01-40-43-636](https://user-images.githubusercontent.com/30963247/29244425-b676d062-7fc8-11e7-9333-90cafad988e3.jpeg)

**Comment by ArmanKir-yan25** [comment]
Yellow and green dots are different please change to original

**Comment by ArmanKir-yan25** [comment]
![20170814_221614-collage](https://user-images.githubusercontent.com/30963247/29285386-673c5db4-813f-11e7-9d8a-6586da84a4cb.jpg)

Please fix it use original one

**Comment by ArmanKir-yan25** [comment]
I

**Comment by ArmanKir-yan25** [comment]
Please why you're not updating lawnchair it is 3 days not updating still1.0.182

**Comment by nyancrimew** [comment]
@ArmanKir-yan25 stop with that attitude please, all developers of Lawnchair are doing this for free and because we want to do this, we don't have to and there is nothing forcing us. We also have personal lives, family, school or work and don't you think we can also use some of our time for those things?

**Comment by alamo18** [comment]
Send a godamn pull if you want it fixed so badly lmao

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alamo18** [comment]
Send a godamn pull if you want it fixed so badly lmao  

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Send a godamn pull if you want it fixed so badly lmao
