### ISSUE TITLE
[BUG] Profile tabs overlap icons

### ISSUE THREAD

**Issue by Gros-Jambon-Fr** [Deletescape-Media/Lawnchair#5042]
### Describe the bug

When work profil is enabled, the two tabs at the top of the draw overlap the first row of icons.

![photo_2024-12-04_11-32-53](https://github.com/user-attachments/assets/786aac98-0a19-4b73-9c79-fae85a7a4e14)

### Steps to reproduce

1. Enable work profil
2. See the tabs overlapping the first row of icons

### Expected behavior

There should be more space just at the top of the first row.

### Device information

- Device: Google Pixel 7
- OS: Calyx OS latest stable
- App version: latest Beta 3

**Comment by MrSluffy** [comment]
Please use latest dev build since it's already fixed in latest dev build

![Screenshot_20241204-192538_Lawnchair](https://github.com/user-attachments/assets/3ca0c49f-8db9-4d3f-8719-591c395b99eb)
![Screenshot_20241204-192510_Lawnchair](https://github.com/user-attachments/assets/c4e6ff22-9abf-4a4b-8a79-6cd085d49759)

**Comment by Gros-Jambon-Fr** [comment]
@MrSluffy you mean to test with the nightly build ? i tried the latest and still got the problem. Try to disable the search bar on the drawrer and check if it is still ok for you. 
I think if you disable the search bar, you will have the problem. 
I don't need the search bar in the drawer, that's why i disabled it !

**Comment by Gros-Jambon-Fr** [comment]
sorry, i thought that the nightly build would replace the official version but actually it is installed beside the original.
So i tried with the nightly and the problem looks solved. 
Do you know when it will be available on the stable version ?

**Comment by 0xAbdiiii** [comment]
> sorry, i thought that the nightly build would replace the official version but actually it is installed beside the original.
> So i tried with the nightly and the problem looks solved. 
> Do you know when it will be available on the stable version ?


when the nightly is stable enough to be labeled as beta which not even the devs know when it will be.
