### ISSUE TITLE
[BUG] Option to display app names on two lines does not work

### ISSUE THREAD

**Issue by dontobi** [Deletescape-Media/Lawnchair#5043]
### Describe the bug

I have just updated to the latest dev-15 nightly. I noticed that the function for displaying the app names in two rows does not work.

### Steps to reproduce

1. Update to latest dev-15 nightly 
2. Open App drawer and search for long App names (Example Home Assistant)

### Expected behavior

Long app names should be displayed in two rows.

### Screenshots

![Screenshot_20241204-160031](https://github.com/user-attachments/assets/784ec633-0f1c-4c6c-9b70-6e0d35be1d17)

### Device information

- Device: Google Pixel 8
- OS: Android 15 November Patch
- App version: dev-15 nightly

**Comment by MrSluffy** [comment]
Please make sure there's enough space, adjust app drawer height accordingly 
![Screenshot_20241205-041328_Lawnchair](https://github.com/user-attachments/assets/31d9c9f1-f7db-4842-8e71-e91fcd2a9878)
![Screenshot_20241205-041350_Lawnchair](https://github.com/user-attachments/assets/a7cd616d-8509-4fac-bea3-df109f08c841)
