### ISSUE TITLE
[BUG] (Nightly) PWA Apps Disappear When Folding/Unfolding ZFold 6

### ISSUE THREAD

**Issue by danni-storm** [Deletescape-Media/Lawnchair#5051]
### Describe the bug

When i fold/unfold my ZFold 6 (Android 14, October Security Update) PWA's 'installed' to the homescreen disappear. This is a consistent and repeatable problem. Unfortunately, I moved to Nightly as PWA support on Beta 3 was super buggy and instead of installing it would turn them into simple homescreen web links. Now they 'install' but after I fold or unfold they disappear. Seems similar (?) to #5028 and #5003 but I believe this bug is unique. 

### Steps to reproduce

1. Add PWA (from Cromite, Firefox, Brave, or Brave-Nightly) 
2. Fold or unfold phone
3. PWA is gone

### Expected behavior

1. Add PWA (from Cromite, Firefox, Brave, or Brave-Nightly) 
2. Fold or unfold phone
3. PWA remains on homescreen

### Device information

- Device: Samsung Z Fold 6 (SM-F956U) 
- OS: Android 14 / Security Update October 2024
- App version: 15.Dev.(#1708) 

### Additional context

May be related (?) but the home screen search bar occasionally freaks out and half of it is cut off (ie 100% transparent). 

(Edit) Also forgot to mention this behavior remains constant even when PWAs are placed into a folder. Once folded or unfolded the entire folder is gone. Regular apps are unaffected by this bug.

**Comment by MrSluffy** [comment]
is it possible to send a screen record thanks! since we don't have foldable device to test

**Comment by danni-storm** [comment]
For some reason Samsung doesn't allow screen recordings to continue when folding the phone (you would think they could handle the aspect ratio change). Here are two different screen recordings. The first is the installation and opening of a PWA and the second is after I have folded and unfolded the device.


https://github.com/user-attachments/assets/84fd2bac-8393-442c-a772-915fcb936851


https://github.com/user-attachments/assets/9024af2e-53a6-40c8-ac39-97a84c318891

**Comment by danni-storm** [comment]
For some reason Samsung doesn't allow screen recordings to continue when folding the phone (you would think they could handle the aspect ratio change). Here are two different screen recordings. The first is the installation and opening of a PWA and the second is after I have folded and unfolded the device.

https://github.com/user-attachments/assets/faaa1513-07e1-41bb-b6e6-4108a57716c8


https://github.com/user-attachments/assets/a51d0231-83fa-447f-8fa1-2be098f39c4f

**Comment by MrSluffy** [comment]
closes fixed: c41eb8ac8f3cc5a3b6afd34c093b7e6889a71eff
