### ISSUE TITLE
[BUG] Lawnchair always returns to the default launcher on Funtouch OS 12 Vivo Y21 

### ISSUE THREAD

**Issue by NIGHTZ-hangout** [Deletescape-Media/Lawnchair#5054]
### Describe the bug

Even though I have made the lawnchair the default, when I open the application and exit the application, the other launchers return to the default launcher and this often happens.

https://github.com/user-attachments/assets/b22bfab6-141c-4bd7-9484-49c0ded26612

### Steps to reproduce

1. Go to threads or to any application, but it happens in the threads application when I open and close the application
2. Then you scroll down or press any button in the application. 
3. Then you immediately exit the application
4. And suddenly it goes back to the default launcher 😞

### Expected behavior

I hope this bug gets fixed soon, I really love this launcher ❤️

### Device information

- Device: vivo y21
- OS: Funtouch os 12, android 12
- App version: 14.beta 3 and 14.Dev.(d7e3f32)

**Comment by MrSluffy** [comment]
Can you do logs here?

**Comment by MrSluffy** [comment]
Please use latest nightly if still exists reopen this
