### ISSUE TITLE
[BUG] (nightly 1714) App shortcuts disappear when Lawnchair restarted

### ISSUE THREAD

**Issue by nowster** [Deletescape-Media/Lawnchair#5056]
### Describe the bug

App shortcuts (eg. contacts shortcuts or browser shortcuts) disappear from home screen when Lawnchair is restarted.

### Steps to reproduce

To reproduce: create any app shortcut on the home screen, then select "Restart Lawnchair" from Home Settings three dots menu.

### Expected behavior

App shortcuts should be retained when launcher is restarted.

### Device information

- Device: Google Pixel 7a
- OS: stock Android 15 (AP4A.241205.013)
- App version: Nightly 1714

**Comment by nowster** [comment]
Also, they disappear if the device is rebooted.

**Comment by znbaboy** [comment]
+1

honestly it would be great if they also persisted through backup/restore. I always have to recreate and reorganize them through [Shortcut Maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&hl=en-US) when I need to restore.

**Comment by znbaboy** [comment]
yup looks fixed in latest nightly but the widgets and shortcuts are still not retained in Lawnchair Backups unfortunately...

**Comment by MrSluffy** [comment]
Yes there's already open issue with this
