### ISSUE TITLE
[BUG] (nightly 1714) Edit home screen does nothing

### ISSUE THREAD

**Issue by nowster** [Deletescape-Media/Lawnchair#5058]
### Describe the bug

Selecting _Edit home screen_ from the menu shows a zoomed out view of the current home screen pages but offers no other functionality. Tapping anywhere does the same as if that page was open normally, eg. it opens an app if you tap on its icon.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Open pop-up menu
2. Select Edit Home Screen
3. Try to do anything

### Expected behavior

Edit Home Screen should have some purpose.

### Device information

- Device: Google Pixel 7a
- OS: stock Android 15 (AP4A.241205.013)
- App version: nightly 1714[e.g. Google Pixel 6]

**Comment by MrSluffy** [comment]
that's what it does, to easily arrange icons
