### ISSUE TITLE
[BUG](15dev #1736) After restoring the backup, the icon on the home screen does not appear

### ISSUE THREAD

**Issue by atuy1219** [Deletescape-Media/Lawnchair#5066]
### Describe the bug

As the title suggests, the icon on the home screen does not appear when restoring the backup.

### Steps to reproduce

Make a backup with the PlayStore LawnchAir and restore it with dev15.

### Expected behavior

All icons should be restored, but only dock icons are restored.

### Screenshots

https://github.com/user-attachments/assets/4359ae40-8846-4117-8924-3c75a85abb78

### Device information

- Device: [Google Pixel 6a]
- OS: [stock ROM Android version 15.0 QPR2 beta1]
- App version: [15.dev #1736]

### Additional context

This issue has existed since the first Dev15 release.

**Comment by MrSluffy** [comment]
can you send me your backup? I tried on latest 15-dev build it's working fine

**Comment by atuy1219** [comment]
[Lawnchair Backup Dec 8, 2024 21_02_28.zip](https://github.com/user-attachments/files/18062056/Lawnchair.Backup.Dec.8.2024.21_02_28.zip)
This is the backup. However, there is a possibility that there may not be a problem with the backup.

https://github.com/user-attachments/assets/90cebc23-6bc8-4ae6-a740-b288b2e9d8a1

This video is from the update from version 14 to 15. You can see that the icon has disappeared after the update.

**Comment by bappitybup** [comment]
I have this same issue. the bottom icons appear for me but the icons on the main pages don't. if I open the home screen grid size settings page, it shows the icons on the screen. as if they're still there but have been placed in the wrong position somewhere off-screen.

Note that I made the backup in an older version of lawnchair: version 14.Dev.(d7e3f32)

Pixel 8 Pro, Android 15
[Lawnchair Backup Dec 10, 2024 23_50_37.zip](https://github.com/user-attachments/files/18087474/Lawnchair.Backup.Dec.10.2024.23_50_37.zip)

**Comment by rickymohk** [comment]
I tried to restore a backup created by 14.Dev.(d7e3f32) and a whole page is missing.

**Comment by MrSluffy** [comment]
Found the issue I can restore now
![Screenshot_20241216-145440_Lawnchair](https://github.com/user-attachments/assets/00462217-2fc0-4ac2-8a7e-937f6710670d)
