### ISSUE TITLE
[BUG] Crashes does not produce notifications

### ISSUE THREAD

**Issue by validcube** [Deletescape-Media/Lawnchair#5069]
### Describe the bug

When crashes occurred, Lawnchair crash report (bug report feature) will not produce crash notifications.

Example seen in video shown that self-induced crash doesn't generate a Lawnchair crash report. Aside from the video, this issue to happen with non-self-induced crash too.

### Steps to reproduce

1. Intentionally or unintentionally crash Lawnchair
2. Observe non-existent bug report

### Expected behavior

Lawnchair should produce a notifications, for brevity in development perhaps it can be merge with `NOTIFY_CRASH` flag from L3 as that seems to be the most reliable.

### Screenshots

https://github.com/user-attachments/assets/fc5e558a-c9d4-4842-84c9-3f070d29b824

### Device information

- Device: Samsung M23
- OS: One UI 6.1 (A14)
- App version: Nightly - LawnchairLauncher/lawnchair@742ff94968b782ab95978466643c4fad19045b9c

**Comment by MrSluffy** [comment]
Please make sure you allow notification for lawnchair works fine here : https://streamable.com/prv6f3

**Comment by validcube** [comment]
> Please make sure you allow notification for lawnchair works fine here : [streamable.com/prv6f3](https://streamable.com/prv6f3)

Whoops, will check it next time.
