### ISSUE TITLE
Moved apps to sdcard wont show after reboot

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#507]
Many apps i use i have transferred them to external storage. After phone reboot i loose all these apps from desktops or app bar drawer. Even after phone finish loading all transferred apps, Lawnchair won't restore theme to their previous locations. Other Launchers do keep in memory these apps and that don't happen. Original pixel launcher do have this bug. Here some pics of Sony's launcher after a reboot: icons for transferred apps look different but after loading finish, they revert to normal. Can u make smth similar?
![](http://i.imgur.com/51XwdZ5.png)

![](http://i.imgur.com/FSfaIkS.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
😂😂😂

**Comment by ArmanKir-yan25** [comment]
Stupid

**Comment by AxiK101** [comment]
Watch your language

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dondrejohnson5** [comment]
The apps on my SD card that are in folders are removed after reboot, causing me to re-add them manually. That is bugging me

**Comment by AxiK101** [comment]
only way is to restore from backup after every reboot

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't remove shortcuts when app is installed on SD card](https://trello.com/c/A0qP4Bbf/14-dont-remove-shortcuts-when-app-is-installed-on-sd-card)

**Comment by Hocuri** [comment]
Could someone tell me what the current state of this issue is? When I follow the link from @divadsn it just says that I do not have permission to see something. If nobody else is doing something I could maybe try to do something about this (it really annoys me).

**Comment by Hocuri** [comment]
I think that I've figured out something: There is a method https://github.com/LawnchairLauncher/Lawnchair/blob/affaacdf2328d6f27aebf33fbffa66777e012b03/app/src/main/java/ch/deletescape/lawnchair/util/PackageManagerHelper.java#L38-L44
that should recognize if an app is on the SD card but this seems not to work. I'll submit a pull request to discuss this. 
Update: The pull request is https://github.com/LawnchairLauncher/Lawnchair/pull/1232
