### ISSUE TITLE
[BUG] Apps' icons get bigger once tapped

### ISSUE THREAD

**Issue by guniens** [Deletescape-Media/Lawnchair#5074]
### Describe the bug

Apps' icons get bigger once tapped, both on homescreen and appscreen, currently using You Icons icon pack.
This bug wasn't present on 14-dev, having since the first 15-dev nightly.
A Lawnchair's restart fixes it but the problem happens again as soon as you tap any app's icon.

### Steps to reproduce

1. Try You Icons or possibly any other icon pack, You Icons are rounded icons so the bug is clearly visible
2. Click on an app to launch it
3. Close the app and either go back to homescreen or appscreen
4. App's icon is bigger then the others

### Expected behavior

Apps's icons shoud stay the same size like before and like defined in Lawnchair's settings.

### Device information

- Device: [Google Pixel 8]
- OS: [Stock Android 15 DEC 2024]
- App version: [Latest nightly]

**Comment by guniens** [comment]
Hi @MrSluffy 
Problem is still there, latest nightly.
Please reopen this issue, thanks.

**Comment by MrSluffy** [comment]
Ohhh, seems fix on my end that's weird

**Comment by guniens** [comment]
Still happening on both home screen and app screen

**Comment by MrSluffy** [comment]
Oh you're on Dec sec patch

**Comment by Pauloesfola** [comment]
Continues to happen in version #1811 on Google Pixel 7a

**Comment by Pauloesfola** [comment]
Continues to happen in version #1832 on Google Pixel 7a

**Comment by guniens** [comment]
Yep I can confirm that
