### ISSUE TITLE
[BUG] App drawer's search bar's search icon is white on white in light mode

### ISSUE THREAD

**Issue by guniens** [Deletescape-Media/Lawnchair#5075]
### Describe the bug

App drawer's search bar's search's icon is white on white in light mode, correct in dark mode.
This bug wasn't present on 14-dev, having since the first 15-dev nightly.

### Steps to reproduce

1. Go to app drawer, search bar's search icon is white on white
2. Switch to dark mode
3. Go to app drawer, search bar's search icon is correctly colored

### Expected behavior

App drawer's search bar's search's icon should be grey or something like that on white in light mode.

### Device information

- Device: [Google Pixel 8]
- OS: [Stock Android 15 DEC 2024]
- App version: [Latest nightly]

**Comment by guniens** [comment]
Hi @SuperDragonXD
Fixed in the latest nightly but I think search icon is way too big, out of proportion, was better before but don't know if this' a design choice.

**Comment by SuperDragonXD** [comment]
I am aware of this and plan to push a fix to the search bar height later.

**Comment by guniens** [comment]
Hi @SuperDragonXD 
Just saw you latest commit and tried the latest nightly, icon is still big, is it intentional? 
Thanks in advance!

**Comment by SuperDragonXD** [comment]
The search bar height is now back to normal, but the icons now match the dock QSB (around `56.dp` (px) in width), which was the intended size.

**Comment by guniens** [comment]
Got it!
I still think is a little too big but as is intended size feel free to close this.

**Comment by MrSluffy** [comment]
- closes : d9f030d91bdfe037b99f32f004e5c81bedc26021
