### ISSUE TITLE
Feature request (dynamic with the android o notification system) like nova launcher

### ISSUE THREAD

**Issue by cabban** [Deletescape-Media/Lawnchair#508]
![screenshot_20170809-174703](https://user-images.githubusercontent.com/19514493/29246529-f3d17fb8-7ffd-11e7-86b7-4c4f56c770a6.png)

Would love to see this 
As u see in screenshot 
Dynamic in nova shows who sent, maybe u could do so then it's easier to see who and only tap and hold to content 😀

**Comment by ArmanKir-yan25** [comment]
Are you mad you don't need that because of messenger has round floating

**Comment by cabban** [comment]
@armanKir-yan25
Öh what? Please don't, what do u want?? It's not only messenger all apps has it and that's good too know.

**Comment by Dondrejohnson5** [comment]
That is actually a cool feature to implement. I have no idea what @ArmanKir-yan25 is talking about..
