### ISSUE TITLE
[BUG] Icon traces doesn't disapear on home screen when using home button or gesture

### ISSUE THREAD

**Issue by pedrom34** [Deletescape-Media/Lawnchair#5081]
### Describe the bug

Since latest version of android, icons disappear animation doesn't finish and icons stays on home screen.

### Steps to reproduce

1. Open a folder then an application
2. Wait for a few seconds on the app
3. Click on home button or swipe the home gesture
4. Icons stays on home screen until home button is pressed again.

### Expected behavior

Animation finishes and icon disappear.

### Screenshots

I'm not really clear but here's an image:
![Screenshot_20241212-115927~2](https://github.com/user-attachments/assets/5078985f-3122-46ae-a577-b8eb5860f1b3)

And a video:
https://github.com/user-attachments/assets/d44539f1-0771-4e28-a68a-ebd914ca3bde

### Device information

- Device: Google Pixel 8
- OS: Graphene OS 2024120900
- App version: 14 beta 3 (I tested with latest nightly, same behavior)

**Comment by MrSluffy** [comment]
Any device configuration like disable animation in Dev option etc?

Can you test with latest nightly with logs

**Comment by pedrom34** [comment]
> Any device configuration like disable animation in Dev option etc?

No.

I just tested with nightly, animations are slow but no issue. I then restored my backup and issue is back even on nightly. I'm using smartspacer for feedvand at a glance.

How do I get the logs as there's no crash?

**Comment by pedrom34** [comment]
Is this commit in the latest nightly?
If yes, the issue is still present...

**Comment by MrSluffy** [comment]
please ensure set lawnchair as home and clear cache or data of you update in the top of the previous version to make sure cache been clear on

**Comment by pedrom34** [comment]
I installed latest nightly from github, I restored the data from my current installation, set lawnchair degub as default launcher, then cleared the cache and could reproduce the bug.

**Comment by pedrom34** [comment]
Issue still active on latest nightly. Am I the only one?
