### ISSUE TITLE
[FEATURE] Close all apps button in recent apps overview

### ISSUE THREAD

**Issue by loxoron218** [Deletescape-Media/Lawnchair#5082]
### Describe the feature

I think it would be great if there were an option to add a "Close all apps" button directly on the first page of the recent apps menu, which appears after swiping up.

### Why would it be useful to add?

This would provide an easy and quick way to clear all apps at once without having to swipe each one away individually or scrolling to the end of all apps and close them

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Something like this?
![](https://i.ytimg.com/vi/c1-xClUB06k/maxresdefault.jpg)

**Comment by MrSluffy** [comment]
Please make sure you set lawnchair as recent provider
![Screenshot_20241213-043946_Lawnchair](https://github.com/user-attachments/assets/40ae1a0a-0aac-493d-a1cc-132a7ac6e12e)

**Comment by loxoron218** [comment]
> Please make sure you set lawnchair as recent provider ![Screenshot_20241213-043946_Lawnchair](https://private-user-images.githubusercontent.com/36076410/395321663-40ae1a0a-0aac-493d-a1cc-132a7ac6e12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMzY0ODUsIm5iZiI6MTczNDAzNjE4NSwicGF0aCI6Ii8zNjA3NjQxMC8zOTUzMjE2NjMtNDBhZTFhMGEtMGFhYy00OTNkLWExY2MtMTMyYTdhYzZlMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDIwNDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwY2FkN2NkMjE5YjJhMTNjYWFhZjc1NGU4MmJiNzExZmY0YTI3ZjJlYzZmNjBmZjY3NTIwYWVlODUzZTQyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g8VAIcj-H3I--_TD4gTkw5xq5J03hxZkBJbkV_boSS8)

Is that possible without root? I don't see the option in the settings menu to set it up.

**Comment by MrSluffy** [comment]
Not possible without root unfortunately

closing this
