### ISSUE TITLE
[BUG]  App icon gets stuck when moving from app to lawnchair homescreen

### ISSUE THREAD

**Issue by ice051128** [Deletescape-Media/Lawnchair#5084]
### Describe the bug

App icon becomes stuck when moving from current app to lawnchair homepage.

### Steps to reproduce

1. Use any app
2. Swipe up to move from current app to lawnchair homepage
3. App icon is now stuck at the center of homescreen

### Expected behavior

App should not be stuck to the center of homescreen.

### Screenshots

Watch video slowly to see the bug:
https://youtube.com/shorts/bwmwhXHtDDk?feature=share

### Device information

- Device: Google Pixel 8
- OS: Android 15
- App version: 14.Dev.(d7e3f32)

**Comment by MrSluffy** [comment]
Hi can you try latest nightly 15dev if the issue still persists? Thanks!

**Comment by ice051128** [comment]
> Hi can you try latest nightly 15dev if the issue still persists? Thanks!

Same issue on [Lawnchair.Debug.15-dev.Nightly-CI_1776-e0f63aa.apk]

**Comment by 0xAbdiiii** [comment]
#4465 related?

**Comment by 0xAbdiiii** [comment]
And yes, it happens on dev 15 too since i can't set it as my recents provider right now without it crashing.

**Comment by MrSluffy** [comment]
Please send crash logs if it's crashing

**Comment by 0xAbdiiii** [comment]
@MrSluffy

![Lawnchair.Debug.bug.report.Dec.12.2024.10_03_43.AM.txt](https://github.com/user-attachments/files/18138868/Lawnchair.Debug.bug.report.Dec.12.2024.10_03_43.AM.txt)

![Lawnchair.Debug.bug.report.Dec.12.2024.10_01_36.AM.txt](https://github.com/user-attachments/files/18138869/Lawnchair.Debug.bug.report.Dec.12.2024.10_01_36.AM.txt)

**Comment by imtheabdi** [comment]
commit 6b5e912e10c6407bbe29668af8b7f043a88985e7 made the app opening and closing animation and the whole experience 100 times better for me even in the development version which tends to be laggy and it's not my recents provider either.

**Comment by ice051128** [comment]
Same issue as #5081

**Comment by ice051128** [comment]
Bug still persists with [Lawnchair.Debug.15-dev.Nightly-CI_1848-ce2e59f.apk]
