### ISSUE TITLE
[FEATURE] Add toggle to disable hiding the clock on homescreen

### ISSUE THREAD

**Issue by elisenlebkuch** [Deletescape-Media/Lawnchair#5085]
### Describe the feature

Add a toggle to disabe hiding the clock on the 1st homescreen page.

### Why would it be useful to add?

I don't like the movement in the corner of the screen + currently the feature also hides the clock when you're inside an app.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

I'm on my phone right now so no gimp, I think y'all know what a toggle looks like.

**Comment by MrSluffy** [comment]
done : adfdc67bd6e8b2faa5dde37956ab9fc0b54b582e
