### ISSUE TITLE
[BUG] Google Search bar does not appear correctly

### ISSUE THREAD

**Issue by TolLescnq7** [Deletescape-Media/Lawnchair#5088]
### Describe the bug

When set as the Search bar widget, the Google Search bar does not appear correctly.

### Steps to reproduce

1. Go to Settings
2. Click on Dock
3. Click on Search bar widget
4. Replace Lawnchair with Google Search bar
5.  Go to home screen
6. See the error

### Expected behavior

I expect the search bar to look how it should look.

### Screenshots

![Screenshot_20241215-181834_Lawnchair](https://github.com/user-attachments/assets/b657565b-379a-4a94-8440-990856e36ba0)

### Device information

- Device: [Samsung]
- OS: [One UI 4.1 Android 12]
- App version: [Lawnchair 14.dev.(d7e3f32) Play Store version]

### Additional context

I tried it on the latest 15-dev builds and it's still broken.

**Comment by MrSluffy** [comment]
That's google widget lawnchair only display what it receives from google. Probably that's new google search bar wodget

**Comment by TolLescnq7** [comment]
> That's google widget lawnchair only display what it receives from google. Probably that's new google search bar wodget

Well, would it be possible to change the Dock Search bar to a widget like on Nova Launcher?

**Comment by Son-Vegitto** [comment]
I second this request.
