### ISSUE TITLE
Feature request (more folders layouts)

### ISSUE THREAD

**Issue by cabban** [Deletescape-Media/Lawnchair#509]
More folders layout, not only have round and pixel layout 
Please 
![screenshot_20170809-174418](https://user-images.githubusercontent.com/19514493/29246530-396a4064-7ffe-11e7-867c-be4d80d549b5.png)

**Comment by ArmanKir-yan25** [comment]
You're zombie what you want from this developera🤐

**Comment by cabban** [comment]
@armanKir-yan25
Stfu.. And mind your own business

**Comment by cabban** [comment]
What is a developera 😂
