### ISSUE TITLE
App drawer font and grid customization issue

### ISSUE THREAD

**Issue by silentgurdian** [Deletescape-Media/Lawnchair#510]
Font size and color in drawer wont change on customizing and grid size freezes at times (reducing or increasing row numbers has no effect)

**Comment by intelligentcasanova** [comment]
Could you tell us on which build you are?

**Comment by silentgurdian** [comment]
1.1.0.1146

**Comment by ghost** [comment]
Can confirm on v1.1.0.1176 but it's just the font size not changing, other settings are working fine on mine. 

Kudos to devs.

**Comment by guest4711** [comment]
Same to me on 1179. Only font size affected by this issue.
