### ISSUE TITLE
[BUG] Google feed isn't working on the home screen

### ISSUE THREAD

**Issue by Luigi9020** [Deletescape-Media/Lawnchair#5111]
### Describe the bug

Google feed doesn't work on the home screen, or using Lawnfeed3

### Steps to reproduce

1. I make the normal gesture, pulling to the right and the Google feed does not display

### Expected behavior

Have the Google feed displayed when you perform the gesture

### Device information

- Device: Moto G60
- OS: stock ROM Android version 12.0
- App version: 	Lawnchair (nightly) 15.Dev.(#1832) beta

### Additional context

No error message

**Comment by MrSluffy** [comment]
use [aidl](https://github.com/amirzaidi/AIDLBridge/releases)
