### ISSUE TITLE
[BUG] The app has issues.

### ISSUE THREAD

**Issue by Tearsmort575** [Deletescape-Media/Lawnchair#5117]
### Describe the bug

When I use QuickSwitch, I encounter some difficulties. I am unable to create logs, install the launcher lawnchair, and delete the deleted launcher. I am unsure of what steps to take.

### Steps to reproduce

![Screenshot_20241225-170128](https://github.com/user-attachments/assets/2e66cc22-6fa6-4ccb-a3b1-6ad1c4421960)
![Screenshot_20241225-165939](https://github.com/user-attachments/assets/1d8c97f5-2ff4-4783-a6ad-8eef04f59745)
![Screenshot_20241225-165949](https://github.com/user-attachments/assets/c4a0ab0f-0f31-4c63-95db-cc9fc101abb1)
![Screenshot_20241225-165957](https://github.com/user-attachments/assets/d6d47952-df57-47d5-bf58-23a83ddb3e97)

### Expected behavior

I thought the remote launcher wouldn't be visible, and I would set lawnchair as the default, and that would be it.

### Screenshots

![Screenshot_20241225-170128](https://github.com/user-attachments/assets/32ee7861-9f2f-4eb1-9a25-cc83a77e3240)
![Screenshot_20241225-165939](https://github.com/user-attachments/assets/fe52858e-837a-413a-9b8b-e4f196afb668)
![Screenshot_20241225-165949](https://github.com/user-attachments/assets/0a07bd8c-0485-454c-948c-536ab4337a61)
![Screenshot_20241225-165957](https://github.com/user-attachments/assets/43c13474-72b8-4fbe-be18-c0f5d55f6ec8)
![Screenshot_20241225-170012](https://github.com/user-attachments/assets/fd9a13ae-2ccb-408d-afcd-39e200c1cf7e)

### Device information

- Device: [infinix note 40 pro]
- OS: [XOS android 14.0]
- App version: [The latest version 4.0.3]

### Additional context

I believe the issue lies within the module and the application.

**Comment by 0xAbdiiii** [comment]
check if this helps you.

https://github.com/skittles9823/QuickSwitch/issues/73
