### ISSUE TITLE
Notification badge not showing for folders.

### ISSUE THREAD

**Issue by madvinegar** [Deletescape-Media/Lawnchair#512]
When an app is inside a folder on the home screen and gets a notification, there is no badge showing on the folder. I.e. you need to open the folder in order to see if there is any notification for any of the apps inside the folder.
I don't know if this is how the original pixel launcher of android O works, but, for example, touchwiz shows notification badge on folders if an app or apps inside the folder has/have a notification.

**Comment by intelligentcasanova** [comment]
This should already be working for Lawnchair too.

**Comment by intelligentcasanova** [comment]
Can this issue be closed? @deletescape
