### ISSUE TITLE
[BUG] Lawnchair crashes on startup

### ISSUE THREAD

**Issue by pikuse** [Deletescape-Media/Lawnchair#5120]
### Describe the bug

The app crashes on startup.
I don't know what this crash is caused by, but it seems to be related to private space, and some other thing missing on my rom.

### Steps to reproduce

1. Open Lawnchair
2. Crashes with two crash reports

### Expected behavior

The app starts normally.

### Screenshots

![Screenshot_2024-12-27-02-20-41-17_984e1414ae90666a90f12ff17ec14a7f](https://github.com/user-attachments/assets/2d94f832-aed9-467f-ae60-d5e8447e70cc)

### Device information

- Device: OnePlus Nord 3
- OS: OxygenOS 14.0.0.560
- App version: 15 Nightly (1850)

### Additional context

[Lawnchair bug report 27.12.2024 2.07.16.txt](https://github.com/user-attachments/files/18256300/Lawnchair.bug.report.27.12.2024.2.07.16.txt)
[Lawnchair bug report 27.12.2024 2.07.16x.txt](https://github.com/user-attachments/files/18256301/Lawnchair.bug.report.27.12.2024.2.07.16x.txt)

**Comment by MrSluffy** [comment]
this is fixed in latest nightly
