### ISSUE TITLE
[BUG] Widgets with settings pages appear blank/crash Lawnchair

### ISSUE THREAD

**Issue by pikuse** [Deletescape-Media/Lawnchair#5124]
### Describe the bug

Widgets with settings pages appear either blank, or crash Lawnchair if trying to open them.

### Steps to reproduce

1. Place down a widget
2. It disappears
3. (Optional) Press the widget (but don't hold) and tap "Add"
3.1. Tap the pencil icon
3.2. Lawnchair crashes with "Bad widget id"

### Expected behavior

The widget opens the appropriate settings page and then places down without issue.

### Screenshots

https://github.com/user-attachments/assets/29a18d3e-31eb-4ae3-a91d-da9d560d3cd5

![Screenshot_2024-12-29-03-30-15-75_bf31cd61652f0af2b303d45149eb909c](https://github.com/user-attachments/assets/40aa349a-afcd-40ed-9d77-e3dfe817f816)

### Device information

- Device: OnePlus Nord 3
- OS: OxygenOS 14.0.0.560
- App version: 15 Nightly (1859)

### Additional context

[Lawnchair bug report 29.12.2024 3.22.10.txt](https://github.com/user-attachments/files/18268152/Lawnchair.bug.report.29.12.2024.3.22.10.txt)

This bug has reappeared for me, but I don't know why.

**Comment by charliefrance** [comment]
This is not working in Oneui 6.1, on latest nightly. I also believe this bug persists on Hyperos but I can't verify
