### ISSUE TITLE
[FEATURE] dynamic blur transparency effect for app drawer 

### ISSUE THREAD

**Issue by NIGHTZ-hangout** [Deletescape-Media/Lawnchair#5125]
### Describe the feature

A dynamic blur transparency effect for an app drawer is a visual effect that makes the background of the app drawer appear blurred and transparent. This can create a more immersive and visually appealing user experience.

### Why would it be useful to add?

Some of the benefits of using a dynamic blur transparency effect for an app drawer include:
 • It can make the app drawer appear more integrated with the rest of the device's interface.
 • It can help to reduce visual clutter and make the app drawer appear less intrusive.
 • It can create a more modern and stylish look for the device.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

(https://github.com/user-attachments/assets/5e05b02e-0b76-402b-bc0a-732455aebe2b)

### Additional context

A dynamic blur transparency effect for an app drawer is a visual effect that blurs the background of the app drawer as it opens or closes. The amount of blur can be adjusted to create different levels of transparency. This effect can be used to create a more immersive and visually appealing user experience.

Here are some of the benefits of using a dynamic blur transparency effect for an app drawer:
 • It can make the app drawer feel more integrated with the rest of the app's UI.
 • It can help to create a sense of depth and dimension.
 • It can be used to highlight the app drawer and make it more visually appealing.

**Comment by NIGHTZ-hangout** [comment]
Keep up the spirit, developers.❤️

**Comment by MrSluffy** [comment]
![Screenshot_20241230-035259_Lawnchair](https://github.com/user-attachments/assets/3141f2d8-ecde-42ea-a493-fd75b934510e)
![Screenshot_20241230-035238_Lawnchair](https://github.com/user-attachments/assets/46cfa5ea-e333-453e-b786-c7f4c88da7f3)
