### ISSUE TITLE
Another lawnchair on play store

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#514]
This one is not lawnchair and clearly says so, it even has a link to this github. Wanted to point this out just in case :))
![](http://i.imgur.com/4SQzxN1.png)

https://play.google.com/store/apps/details?id=de.williamherndon.lawnchair

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fonix232** [comment]
It's a pretty old listing, last updated a year ago.

Apparently the dev was nice enough to link to our project 😃 so kudos for that, whoever he/she is.
