### ISSUE TITLE
Google Pill randomly disappears

### ISSUE THREAD

**Issue by gcladores** [Deletescape-Media/Lawnchair#516]
When I go into an app and return to the launcher sometimes the Pill is gone. Or if I go into the settings os Lawnchair and gose back home it's gone. Then randomly returns again.

**Comment by AxiK101** [comment]
Yes this is a pretty old bug indeed

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
Duplicate of #112.
