### ISSUE TITLE
Please add png support/stock icon database.

### ISSUE THREAD

**Issue by silentgurdian** [Deletescape-Media/Lawnchair#517]
Either is fine with me. I just want the system icons from latest google builds for a consistent stock look. So if along with the none option there is one with 3 or 4 of the basic stock icons( contacts, phone, messages, sim toolkit etc.) in the icon packs it would be awesome. I guess png support would be a more generalized version for customizing along the same lines. Either way is fine by me but I would really like to see one or the other. Please!

**Comment by ArmanKir-yan25** [comment]
Needed

**Comment by Dondrejohnson5** [comment]
Me too

**Comment by suphon-t** [comment]
No need to comment without useful informations such as "Needed" and "Me too".
