### ISSUE TITLE
Legitimate or usurper?

### ISSUE THREAD

**Issue by Pedro1999** [Deletescape-Media/Lawnchair#518]
Is it legitimate or is it a usurper that has put your app on Play?

https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair @paphonb @deletescape

**Comment by KieronQuinn** [comment]
![Telegram](https://i.imgur.com/GNeNdxL.png)

It's unauthorised, and because it has the same package name it's going to be an issue for the actual Lawnchair developers

**Comment by hassie-dash** [comment]
I believe that even if the user does take down the app, it still won't be possible since the app package name has been used. 

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by uudruid74** [comment]
I didn't do it, but Apache license ...

**Comment by KieronQuinn** [comment]
The license may allow it but it's common courtesy to at least change to the package name, especially when the original developers are known to be pushing it to the play store themselves

**Comment by uudruid74** [comment]
I agree!  Hopefully someone just made a mistake and he'll take it down when asked.  I was just saying that trying to pursue things through Google or any legal perspective is likely a lost cause.

**Comment by hassie-dash** [comment]
Well if the user decides not to take it down, then it is the right thing to do, to report the app to Google. It's the fact that the app description states "It's still a Work-in-Progress, but the development is moving fast as more feedback slides into __my__  DMs." This is clearly impersonating.  

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KieronQuinn** [comment]
If it gets taken down, the package name does not become available. The only way to get the package name is to have the "developer" who uploaded it to transfer the listing to the correct account and upload a new APK
