### ISSUE TITLE
Day/night weather conditions

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#519]
In greek region the night weather conditions start too early. Can u optimize to sync properly with the time zone plz? Thanks
![](http://i.imgur.com/tJooav0.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
In Armenian region there's no that issue

**Comment by scartozzi** [comment]
In Italy we have the same issue
