### ISSUE TITLE
Dynamic Calendar and Clock Icons

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#52]
Make Calendar and Clock app dynamic (today is June 27, but the icon still says 26)

**Comment by Sparky853** [comment]
Calender app is dynamic for me, Android 6.0.1, Lawnchair v198

**Comment by Dondrejohnson5** [comment]
I discovered this launcher late last night, and even after 12, it didn't change until about 10:30 today. Awfully long time.

**Comment by Dondrejohnson5** [comment]
Plus, I heard how the new Action Launcher is testing the dynamic clock icon

**Comment by OvermindDL1** [comment]
This is a very oddly named issue, seems to have nothing to do with the issue content...  o.O

**Comment by deletescape** [comment]
Theoretically already implemented for Calendar, apparently doesn't change on midnight though, thanks for the report

**Comment by AxiK101** [comment]
Clock is needed. Action launcher do the magic

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
