### ISSUE TITLE
Some graphical glitches 

### ISSUE THREAD

**Issue by zgwerby** [Deletescape-Media/Lawnchair#520]
![](http://i.imgur.com/QGPdLU1.png)

Corner

![](http://i.imgur.com/kRF6VpX.png)

Black rectangle

Some graphical glitches on shortcuts dialogs   

_Sent from my Motorola Moto C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
Duplicate of 78.
Duplicate of 358.
Please close this issue.

**Comment by intelligentcasanova** [comment]
Duplicate of #78.
Duplicate of #358.
Please close this issue.

**Comment by zgwerby** [comment]
@intelligentcasanova ok


_Sent from my Motorola Moto C using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
