### ISSUE TITLE
v1.0.1063 Not staying as default launcher.

### ISSUE THREAD

**Issue by neutralvibes** [Deletescape-Media/Lawnchair#524]
v1.0.1063 seems to keep forcing the re-selection of the default launcher, after unlocking the phone, despite setting it to always be used.

**Comment by neutralvibes** [comment]
This is happening on Android 5.1

**Comment by Zazie-Lavender** [comment]
Can confirm happens on LineageOS 14.1 {Android 7.1.2}

Seems to happen directly after any crash of Lawnchair, which it seems to do at random intervals

**Comment by Zazie-Lavender** [comment]
Confirming this still happens even on latest builds

**Comment by gvlekke** [comment]
Yes for me this is also still happening
