### ISSUE TITLE
Unresponsive top widget

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#525]
I removed the Google search bar (Pixel style > show pixel top bar) and replaced it with Chrome's search bar hoping it would work better. It did solve some of my non-lawnchair-related issues, but at times, it becomes unresponsive, just like the native search bar.

I'm thinking there's a problem with that particular area of the homescreen grid ?
Because other widgets and apps icons always work flawlessly.

Will attach screenrecord if needed, hope this piece of info helps with the search bar/pill bug :)

Lawnchair build 1176

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blackcomb-dev** [comment]
YES. I have the same issue, on a Nexus 6P, DU 11.6. I reported it a while back, complete with a screen record of the issue, but I guess it just got overlooked.

**Comment by blackcomb-dev** [comment]
See issue #339: https://github.com/Deletescape-Media/Lawnchair/issues/339

**Comment by Younes-L** [comment]
@loginnotsecure thanks, didn't know it affects icons too as I don't usually​ put icons in the top row, but it's good information nonetheless :)

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
I figured a way to make the widget (chrome search bar) work 100% of the times : tap the bottom half of the widget, should hopefully work with icons too.
