### ISSUE TITLE
Icons dissapear after restart

### ISSUE THREAD

**Issue by owengraven** [Deletescape-Media/Lawnchair#526]
I have some icons that dissapear after I restart my phone, right now it's xda labs and true skate, but I have no idea what is causing this.

**Comment by AxiK101** [comment]
I have this problem for apps moved on sd card..

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guest4711** [comment]
See #507 and #476 ...
