### ISSUE TITLE
Last entry of list of translators not readable

### ISSUE THREAD

**Issue by guest4711** [Deletescape-Media/Lawnchair#528]
I've just upgraded to 1179. When visiting the scrollable list of translaters I noticed thst the last readable entry "Wilmar Alzate" is not the last one, but I cannot read the following one(s).
I have softkeys enabled on my devices.

**Comment by guest4711** [comment]
![screenshot_20170815-070341](https://user-images.githubusercontent.com/26175945/29302896-5a73f13e-8188-11e7-9955-00ee00d2683f.png)
Example view. Note the last line not readable even if scrolled down to the bottom. 

_Sent from my Samsung GT-I9295 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
This has already been fixed, right? @deletescape

**Comment by guest4711** [comment]
In 1221 all ok. Thanks.
