### ISSUE TITLE
Huge vertical gap with default drawer columns settings

### ISSUE THREAD

**Issue by kostiato** [Deletescape-Media/Lawnchair#530]
Have noticed that in all versions after 1.1.0.1110 the default values for drawer columns settings have been changed for my display (360 dp).
Increasing manually to "6" columns makes it good in portrait screen layout, but almost unusable in horizontal. Whilst the default values are suitable for horizontal screen.
![screenshot_20170815-110019](https://user-images.githubusercontent.com/30745425/29307556-155856bc-81ab-11e7-9672-2f4886ca2186.png)
![screenshot_20170815-110028](https://user-images.githubusercontent.com/30745425/29307570-1e0c3f4e-81ab-11e7-82e0-3e2b78f03d90.png)
![screenshot_20170815-110104](https://user-images.githubusercontent.com/30745425/29307587-2647bdaa-81ab-11e7-9379-b0e328dea79e.png)
![screenshot_20170815-110113](https://user-images.githubusercontent.com/30745425/29307592-2c7bfc72-81ab-11e7-8b34-30e403cea861.png)

**Comment by AxiK101** [comment]
Yes indeed

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
I second this

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
This is indeed an issue.
