### ISSUE TITLE
A part of the shortcuts cuts off.

### ISSUE THREAD

**Issue by nachiketdk** [Deletescape-Media/Lawnchair#535]
![screenshot_20170816-152908](https://user-images.githubusercontent.com/29353816/29358203-ca96ddae-8297-11e7-91b9-321355fa2c0f.png)
![screenshot_20170816-152917](https://user-images.githubusercontent.com/29353816/29358211-d49cd4a2-8297-11e7-860e-045b830af581.png)

**Comment by suphon-t** [comment]
Duplicated issue. Please search before posting.
