### ISSUE TITLE
Day/night mode auto switch (feature request)

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#538]
Like Nova, it whould be nice for Lawnchair to auto change from light to one of the dark themes based on time schedule of the day or usung geolocation (like the weather widget) to identify when night starts in each region.

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dondrejohnson5** [comment]
Ok.. that could be useful

**Comment by suphon-t** [comment]
@Dondrejohnson5 please stop commenting without useful informations like this.
