### ISSUE TITLE
Icon pack loading splash screen (bug)

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#539]
The loading text is no more centered on the screen. Pic below:
![](http://i.imgur.com/FsweuUm.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
this is fixed, plz close

**Comment by nyancrimew** [comment]
@AxiK101 you can close issues you have opened yourself
