### ISSUE TITLE
"Failed to get AppFilter"

### ISSUE THREAD

**Issue by PatriciaGomesDev** [Deletescape-Media/Lawnchair#542]
After I try to Rebuild Icon Database I got this error 
![img_20170817_141418_899](https://user-images.githubusercontent.com/18722810/29414333-401bbbd4-8357-11e7-9e6c-aaaa93ffc41b.jpg)
I have an Umidigi C note with Android 7.0

**Comment by guest4711** [comment]
Perhaps related to #464 ?

**Comment by PatriciaGomesDev** [comment]
Yes, is the same, sorry
