### ISSUE TITLE
Notification badge for for TypeApp (bug)

### ISSUE THREAD

**Issue by ffeingol** [Deletescape-Media/Lawnchair#543]
Hello Guys,

I have enabled notification badges and given Lawnchair permission for notices.  Everything works fine except for TypeApp ( https://play.google.com/store/apps/details?id=com.trtf.blue ).  I get notices, but no dots by the icon.  I've restarted Lawnchair from the debug menu, set the icon's back to default etc.

Let me know what other debugging information I can provide.

Thanks!

**Comment by ghost** [comment]
Same thing happens to WhatsApp. If i have only 1 message in the notification center i get no dot, if more than 1 message then i get the dot. I don't know if it's a Lawnchair thing, this happened to me in the pixel launcher as well.

**Comment by msbdevil** [comment]
I'm having the same problem with Whatsapp can't see the notification dot.

**Comment by callmemulo** [comment]
@Arkanas1 you are not alone with that. also same here.

**Comment by TheShark27** [comment]
Same happens to me. The badge for WhatsApp shows only when the number of unread messages  equals or is more than two.
