### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by paradoxicalrooh** [Deletescape-Media/Lawnchair#544]
Hi buddy I would like to request some changes or features 
First one is Pages in app drawer like Nova, one can set pages for separate apps while having main app drawer scrollable horizontal

Second Dock hight customisable

And third one is slide up indicator in home screen above dock instead of below dock

**Comment by ghost** [comment]
I am for the second request.

As for the third request, the slide up indicator is actually above the dock for me. This could be from the "Transparent Dock" option. Try toggling that to see if it helps.

**Comment by guest4711** [comment]
For 1st request see also #362 and #545 (3. request)
