### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#545]
I have some feature request.

Why make Lawnchair just another copy of Pixel launcher with some more customization when we can make it a better launcher.

1: More features or at least make the swipe down gesture to be able to open an app
2: Universal Search - Search not only own apps but even on play store suggestions, contacts, web search
3: Make it so we can add folders on app drawer

**Comment by ghost** [comment]
4: Ability to hide status bar

**Comment by guest4711** [comment]
See also #362 and #544 for 3. request

**Comment by Dondrejohnson5** [comment]
Please make sure these can be customizable. Some might like these features, others might not

**Comment by Binith215** [comment]
Please add a feature for lawnchair to apply custom icon packs only for home screen like themed icons.
