### ISSUE TITLE
Drawer arrow inside app drawer

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#548]
I have a 50% opacity app drawer and transparent dock, and when open the app drawer I can see the drawer arrow.

![screenshot_20170817-221221](https://user-images.githubusercontent.com/30305404/29441598-6df7ded2-839a-11e7-8ead-4b20aa5c7726.png)

**Comment by LinuxLlama** [comment]
Closing since transparent dock doesn't drop the arrow down under the dock anymore, meaning this issue won't occur.
