### ISSUE TITLE
Change name of "Enable editing homescreen" option

### ISSUE THREAD

**Issue by TMartinPPC** [Deletescape-Media/Lawnchair#550]
Could the name for this option be changed to be a little more descriptive? Maybe change it to "Enable editing individual app icons" or something along those lines?

**Comment by intelligentcasanova** [comment]
This setting involves the editing of the entire home screen, apps, widgets etc. Therefore it would not make sense to change the description.

_Sent from my Motorola XT1524 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment]
This setting involves the editing of the entire home screen, apps, widgets etc. Therefore it would not make sense to change the description.

**Comment by KieronQuinn** [comment]
"Lock desktop" is the name other launchers use, maybe the setting should be inverted and have that as its title with a short description ("Disable editing homescreen") as the subtitle

**Comment by TMartinPPC** [comment]
I don't know exactly what it should be called but "Enable editing homescreen" doesn't explain what it does. It sounds like it's even more than the homescreen. I couldn't find the edit when I long pressed. Had no idea enabling that would let me get to edit again. Luckily I'm running this on my phone and tablet and my this was the only setting that was different between the two.
