### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#555]
Add the ability to choose an accent colour for the app drawer. The automatic colour pick from the wallpaper is useful, but i'd like that colour to stay even if i change my wallpaper. 
I'm sorry if it's a duplicate, could not check if It has been posted already.

**Comment by a220** [comment]
Yeah I'm suprised this isn't a feature. I'd like love a custom color option

**Comment by suphon-t** [comment]
Duplicate of #453. 
There is a button called "search"
