### ISSUE TITLE
Superposition of app drawer and homescreen

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#561]
This glitch happens and can be reproduced consistently, by pressing the home button from another screen than main, and swiping up for app drawer.
Alternatively you can also swipe left or right then swipe up.

Latest build 1186

![](http://i.imgur.com/LUxTV4d.jpg)

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
Wtf

**Comment by guest4711** [comment]
Works for me. Android 7.1.2 on maguro, Dirty Unicorns

**Comment by zfm99** [comment]
Are you sure your drawer isn't transparent?

**Comment by Younes-L** [comment]
@zfm99 my drawer is indeed transparent but that is not the issue. The homescreen should stop being rendered when the drawer is open.

This is just a bug that happens when you open the drawer a little too fast.

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
