### ISSUE TITLE
More docks

### ISSUE THREAD

**Issue by Silviobrittos** [Deletescape-Media/Lawnchair#562]
I wanna suggest to add an option of customization that allow to add more than one dock (at least 2 or 3)

**Comment by ArmanKir-yan25** [comment]
Are you mad

**Comment by Silviobrittos** [comment]
i mean same design, only scrollable

**Comment by fonix232** [comment]
@ArmanKir-yan25 keep a polite tone or you'll be restricted from this repository. This is not your first warning, but it is the last.

**Comment by fon321** [comment]
This would be very useful, thanks in advance!
