### ISSUE TITLE
Clock animated icon not working on Google Clock from Open GApps

### ISSUE THREAD

**Issue by ivancuric** [Deletescape-Media/Lawnchair#566]
The animation worked on a previous stock OxygenOS ROM, both on the OOS clock, and on the Google one installed from the Play Store.

I have Google Clock installed via Open GApps as a system app on a new ROM (VertexOS 3.4, Android 7.1.2), and the animation is not working (same settings in Lawnchair).

The package name is `com.android.deskclock` and its path is `/system/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk`, version 5.1 (4224536)

**Comment by hkaancaliskan** [comment]
Same on CarbonOS 5.1 Android 7.1.2
Same Gapps

**Comment by suphon-t** [comment]
Google clock package is `com.google.android.deskclock`.
