### ISSUE TITLE
Android Oreo 8.0 New launcher tweaks

### ISSUE THREAD

**Issue by ArmanKir-yan25** [Deletescape-Media/Lawnchair#567]
Please update lawnchair with new Android Oreo launcher tweaks and fix some bugs like animation crashing and Google bar disappearing, please add icon shape changer , Change lawnchair app icon to round and disappear it from app drawer and finally the most important correct Google Assistant button icon to original,
I noticed that you are not updating your lawnchair, why?

**Comment by nyancrimew** [comment]
Dude, f*cking stop requesting the same stuff over and over. I already answered you on your other issue where you already requested half of the stuff here. Icon shape changing is supported, but only on O and upwards. All other requests are duplicates.

**Comment by nyancrimew** [comment]
And also: Always open 1 issue per request, it is impossible for us to track progress otherwise

**Comment by ArmanKir-yan25** [comment]
Can't you make icon shape changing avaible for android 7.0

**Comment by ArmanKir-yan25** [comment]
And why you're not changing assistant button icon it is not original change too ordinal

**Comment by nyancrimew** [comment]
@ArmanKir-yan25 are you even reading what I answer... STOP requesting the same stuff over and over. Backporting shape changing to anything pre O is not possible right now, but as soon as we find a way (if there is any) we will do that
