### ISSUE TITLE
Play Store Notification Bubble Previous

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#569]
On official Android 8 (also on action launcher) the bubbles show the notification of installed/updated apps with its individual icons separately (look pics). Lawnchair only shows the notification bar's common icon for store's updates...

![](http://i.imgur.com/gexXAla.png)

![](http://i.imgur.com/J7MX1zx.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment]
This is from Lawnchair:

![](http://i.imgur.com/uVZDZYd.png)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
Hey how your Google widget is like that can you tell me how to do like that

**Comment by AxiK101** [comment]
Its a widget from an alpha build version from google called Search Lite. You can find the apk at apkmirror site

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
Fixed.

**Comment by AxiK101** [comment]
After the fix i get no app shortcut for playstore.🤔
![](http://i.imgur.com/tgkDcuu.jpg)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
