### ISSUE TITLE
Redesign of the "Rounded Apps Searchbar"

### ISSUE THREAD

**Issue by vukkashin** [Deletescape-Media/Lawnchair#570]
I wanted to request a redesign of the rounded apps search bar style. Since I like how it looks like but I think it needs more work. 
I made a concept of how I think it should look like and I'm not sure how hard will it be to make or is it even possible but I hope it is, for the sake of better looks.

Here is the concept image:
http://imgur.com/ZaXpUTP

Instead of apps going under a divider when scrolling, it would look much better if the apps went under the search bar. And also adding a small drop shadow to the search bar so it looks like it's elavated and have an effect that apps are going under it. 

Also I feel like the nav bar semi-transparent overlay is gray instead of black when using the black theme.
So that's just another small this things to fix.
It would be also nice to have an option to didable the nav bar overlay transparency.

**Comment by nyancrimew** [comment]
@paphonb @fonix232 any thoughts on this? Looks pretty cool imo

**Comment by suphon-t** [comment]
This is really nice. But the hardest thing would be to clip the icons under the search bar. I'm thinking about this.

**Comment by fonix232** [comment]
It shouldn't be hard, just don't clip them, rather, make the search bar's
background a dynamic blur element, so stuff gets blurred under.

**Comment by suphon-t** [comment]
Then we have the old problem: performance. Even my SD820 takes around 20ms to blur a 1080p bitmap. So clipping might be a better idea.
