### ISSUE TITLE
can't select original icon of app

### ISSUE THREAD

**Issue by hkaancaliskan** [Deletescape-Media/Lawnchair#572]
I can't select the original icon of app. https://goo.gl/photos/98GpiFxLr4nFW6fV8
Version 1186
Android 7.1.2

**Comment by fonix232** [comment]
The first icon is the original icon you're seeing. It is the official Firefox Nightly icon, see below.

![image](https://user-images.githubusercontent.com/371847/29568115-9c5517fa-874f-11e7-80dc-d923de20b678.png)

**Comment by hkaancaliskan** [comment]
Yes I know and I can't select that. I select but nothing changing.

**Comment by hkaancaliskan** [comment]
https://goo.gl/photos/fwYwdjnPgg5F19UK6
Here's the video.

**Comment by hkaancaliskan** [comment]
Note: I can select from icon pack. I can't select just the original one.

**Comment by intelligentcasanova** [comment]
This has been fixed, right? @paphonb

**Comment by hkaancaliskan** [comment]
Yes, fixed.
