### ISSUE TITLE
App not starting on Oreo

### ISSUE THREAD

**Issue by rdivanji** [Deletescape-Media/Lawnchair#577]
The issue persists even with ALL permissions granted, including the new "Install unknown sources" introduced in Oreo that this app needs for some reason. 

Taken with these steps: I installed, set it as my default launcher, enabled all permissions incl unknown apps, pressed the recents button, started the logcat, pressed the home button, and stopped the log when I noticed a loop occurring.

Log: 
[opening_logcat.txt](https://github.com/Deletescape-Media/Lawnchair/files/1243924/opening_logcat.txt)

**Comment by nyancrimew** [comment]
The currently as stable released build does not work on Oreo, this issue has been fixed in alpha builds already
