### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by noxplotaras** [Deletescape-Media/Lawnchair#578]
- When you long press an app icon it shows shortcuts to some options, but it's not possible to drag them to the home screen like in Pixel Launcher or Google Now Launcher (launcher shortcurts). 

- The option of Chrome "Add to Home Screen" in the three dots menu is not working. I don't know if its a problem related to Chrome or it's a problem related to the launcher.

- The new google app interface with the three icons bottom bar it's not showing if the "show google now page" option is enabled. If i disabled this option, i get the new google app interface. Again, i don't know if its a problem related to the Google App or its a proble related to the Launcher.

**Comment by shuli81** [comment]
@noxplotaras first two issues: I don't experience these. Both work exactly as intended. What version of Android are u on?

3rd issue: this is related to Google app. I don't think the new interface is enabled when using launcher integration.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by noxplotaras** [comment]
I had first two issues with Android 7.1.2 and i have the issues with Android 8.0 too on a Nexus 5x. Adding icons to home screen for new apps is not working and none of the two things mentioned before.

**Comment by suphon-t** [comment]
Can you record a video of the problem?

**Comment by Dondrejohnson5** [comment]
Yeah, the Google Now piece is problematic for me, too
