### ISSUE TITLE
Bugs on notifications dots

### ISSUE THREAD

**Issue by lawnchuser** [Deletescape-Media/Lawnchair#580]
hi The team;

There is a bug on the dots notifications when you erase them by swiping to the right or the left the rectangle containing the infos of the application jumps and returns since the version 1182 where you have accelerated a little the animations...

And today it's with the Gmail notification dots where there is a bug with the latest version (1195) when we erase it by swiping it makes crash the lawnchair.

Samsung Galaxy s8 non rooted 7.0

Sorry for my bad English i'm french ;)

**Comment by lawnchuser** [comment]
And this an answer of XDA member

Yes, I also get this stuttering effect, I reverted back to version just before that update with speeding animation

Sent from my Moto G4 Plus using XDA Labs

**Comment by lawnchuser** [comment]
hello
it's ok now with the (1207)  
great job ;)

for me you can close this issue 
Thank you very much

**Comment by nyancrimew** [comment]
closed it, but you can actually close issues you authored yourself
