### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by iainfm** [Deletescape-Media/Lawnchair#583]
Hi,

Brilliant launcher, thanks very much for releasing this. Could I request a couple of features in a future release, please?

1) Option to have immersive mode (ie auto-hiding soft keys) in the launcher

2) Ability to make the swipe-up chevron thing semi-transparent or invisible

Thanks again for your work :)

Cheers,
Iain

**Comment by iainfm** [comment]
I've implemented immersive mode (after 2 days solid trying to get Android Studio installed and functional). Code change is in Launcher.java:

public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        mHasFocus = hasFocus;
        if (mHasFocus) {
            View decorView = getWindow().getDecorView();
            decorView.setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
        }
    }

I'll try to create a branch with it in and upload it. I'm a gitnoob though :D

**Comment by peteryates** [comment]
Thanks for working on that change (I was looking for it too!). To create a pull request you're best following [this guide](https://guides.github.com/activities/forking/).

**Comment by iainfm** [comment]
Hi Peter,

Thanks very much for this link. I'll take a look at it :)

Cheers,
Iain
