### ISSUE TITLE
Weather is unstable, at times the launcher hangs

### ISSUE THREAD

**Issue by devang98** [Deletescape-Media/Lawnchair#584]
weather is unstable and the launcher hangs at times, it does not do a regular update.

**Comment by zfm99** [comment]
Thanks only time my weather is updating is when I restart or the date changes. Restarting the launcher does nothing

**Comment by edwaine** [comment]
This issue happened on my Android One G1 device. But not on my Pixel & Nexus 5X though.

**Comment by suphon-t** [comment]
Duplicate of #468
