### ISSUE TITLE
Notification arrow pointer ii shortcut's bubble out-centerd (again😂)

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#586]
An old bug made it's return
![](http://i.imgur.com/YQK9bI8.png)

![](http://i.imgur.com/F2l42cg.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment]
This never was a bug before, but it is now, yes.

**Comment by AxiK101** [comment]
Bug or not i had comment it before

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ArmanKir-yan25** [comment]
Hey are you stupid, why you're not changing your language to English to get Google Assistant

**Comment by AxiK101** [comment]
@ArmanKir-yan25 fuck off jerk. Who cares about google assistant

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
@deletescape it was actually a bug and fixed by a0eba56.

**Comment by nyancrimew** [comment]
@ArmanKir-yan25 @AxiK101 please keep the language clean here and NO offtopic discussions in issues please, all 131 watchers get emails for all comments.

If any of you two (or anyone else) thinks they need to insult people on here again I will BAN you from any futher actions on this repository without warning

**Comment by AxiK101** [comment]
Sorry dev, not gonna happen from me. But somebody should block that troll for moking any thread he finds anyway..

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
