### ISSUE TITLE
👻 icons when moving apps

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#588]
Is this normal?
![](http://i.imgur.com/B67lVc8.jpg)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment]
Duplicated icon?

**Comment by AxiK101** [comment]
No, when moving icons this happens. Its like a ghost icon stays at the original position before it moved to new one

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxLlama** [comment]
That happens on most launchers. It's normal

**Comment by AxiK101** [comment]
Dude that doesn't happen to any launcher. And I'm 100% that is a bug on Lawnchair. Moving apps shouldn't show the icon double, when u move it you only get to see the floating icon.and a shadow of where it is pointing. At list on stock aosp launchers is how it works

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxLlama** [comment]
Oh, I thought you meant the icon shadow. Yeah, I see. I also have this problem.

**Comment by ArmanKir-yan25** [comment]
It is big from Pixel launcher and it's in lawnchair too i think no one can fix that

**Comment by ArmanKir-yan25** [comment]
*bug

**Comment by suphon-t** [comment]
Fixed in 3ad7375.
