### ISSUE TITLE
Notifications and excessive RAM usage

### ISSUE THREAD

**Issue by Mackerel71** [Deletescape-Media/Lawnchair#589]
In case this has not been reported, I've experience LawnChair using up to 306 RAM when I have Notifications turned on. Once I turned them off, it went down to around 67.

**Comment by Dondrejohnson5** [comment]
Yup. Extremely problematic for a 1GB phone like mine..

**Comment by Axelzero1** [comment]
@Dondrejohnson5 please stop pointlessly commenting on every issue

**Comment by dimqua** [comment]
I have the same problem too.

**Comment by baruchin** [comment]
Same problem here with a Moto Z Play. With notification dots, 3 hours average RAM is 149 MB, without notification dots, 3 hours average RAM is 55 MB.
