### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ZaheenJ** [Deletescape-Media/Lawnchair#590]
I love Lawnchair but I wish there was an option to keep the Google pixel bar on screen(not a widget but permanently there) like the real pixel launcher and Google now launcher.

**Comment by AxiK101** [comment]
Real pixel launcher keeps pill widget+weather widget __only__ in first desktop page. 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by coyage** [comment]
I would like to +1 on this feature request
