### ISSUE TITLE
Straight lines in notification badges rounded corners (Oneplus 5)

### ISSUE THREAD

**Issue by dadechat** [Deletescape-Media/Lawnchair#591]
![screenshot_20170824-093010](https://user-images.githubusercontent.com/31280775/29654817-0391929e-88af-11e7-9f11-9232b2deb706.png)

**Comment by SovsOgKartofler** [comment]
... and what version of the launcher and Android are you running?

**Comment by dadechat** [comment]
Sorry for the lack of information :
android 7.1.1 (Oxygen OS 4.5.8)
Lawnchair 1.0.1063

**Comment by SovsOgKartofler** [comment]
You could try the latest build here: https://lawnchairmirror.duckdns.org/

**Comment by dadechat** [comment]
Oh I didn't know there were newer versions. Link in the xda-developpers thread points to the 10.1063 version... but the bug is still there on yesterday's version 1.1.0.1199.

**Comment by nyancrimew** [comment]
This is a really old bug (also present on pixel launcher) and afaik it only appears when using a custom DPI, we don't yet have a working fix for this, but we'll hopefully find something soon!

**Comment by dadechat** [comment]
You're right ! I just reset display size to "Normal" (was set to small) and the bug disappears.

**Comment by intelligentcasanova** [comment]
Duplicate of #78. Please close this issue.
