### ISSUE TITLE
Cannot edit auto added icons anymore 

### ISSUE THREAD

**Issue by 5haney** [Deletescape-Media/Lawnchair#592]
From 1191 builds onwards, no longer able to edit home screen icons or text labels added from chrome's "Add to home screen" or similar auto add icons (from Google maps or the weather icon added from a Google weather search).

Nexus 5x - Nougat 7.1.2

**Comment by suphon-t** [comment]
Fixed in affaacd.

**Comment by 5haney** [comment]
The issue has returned again with latest build (currently 1121)

**Comment by 5haney** [comment]
Sorry ignore that last comment, just remembered I'm back on Oreo
