### ISSUE TITLE
[Android 8] cannot add icons to home screen

### ISSUE THREAD

**Issue by 5haney** [Deletescape-Media/Lawnchair#593]
Since android, the option to add icons to home screen has moved from play store to launcher and only works 9n stock pixel launcher or Google now launcher.
In lawnchair, cannot add newly installed apps, chrome Web pages or other auto add icons such as from maps or Google weather search.

**Comment by intelligentcasanova** [comment]
Also see #111.

**Comment by suphon-t** [comment]
Duplicate of #111
