### ISSUE TITLE
Crash on CM12.1

### ISSUE THREAD

**Issue by Haxk20** [Deletescape-Media/Lawnchair#595]
I wrote this issue before but i cannot reopen it and i found the problem it is the gradle 3.0.0
gradle 2.3.0 works perfectly fine on other apps but when i switch them to 3.0.0beta 2 or alpha 8 they crash the system i tried to build lawnchair with 2.3.0 but i failed i hope you can make the project compile with 2.3.0.
Thank you

**Comment by brainvision** [comment]
https://issuetracker.google.com/issues/64434571 here more info about the bug..
