### ISSUE TITLE
Google Pill disappears when opening launcher settings

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#596]

**Comment by robjarsen** [comment]
On Lawnchair version 1.1.0.1207  - [[6ea6636](https://github.com/Deletescape-Media/Lawnchair/commit/6ea66362d1bea7d17415b71194424cf4876d2035)]
Android version 7.1.1 - OxygenOS 4.1.7

**Comment by AxiK101** [comment]
Hate this bug..

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
However, closing the launcher using the Android back button leaves the Google Pill unaffected. Only when I close the settings page or minimize it does the Google Pill disappear.

**Comment by SovsOgKartofler** [comment]
@AxiK101 how does that comment help the devs?! Stop spamming this repo. This is neither Twitter or Reddit!

**Comment by intelligentcasanova** [comment]
Also see #112.

**Comment by vipulvaibhavsingh** [comment]
yup problem is there but you can get it back by locking your device ones and opening again
