### ISSUE TITLE
[Feature Request] Gestures, per app custom icon...

### ISSUE THREAD

**Issue by Vas0sky** [Deletescape-Media/Lawnchair#597]
Hi there. I'll suggest a couple features that I'd love to see implemented.

1. More and customizable gestures: Swipe up and down are already there, but something like double tap+swipe up/down or double tap would be great. Moreover, being able to set an activity for every gesture would be awesome.
2. Swipe up/down on app icon to start a custom activity (start an app). Being able to choose between swipe app or down (or both) should also be considered.
3. Per app icon/custom icon: option to choose an app's icon between the one provided by the icon pack and one that you can choose in the gallery.

Yes, these features are inspired by Nova (and are the reason why I haven't switched to this launcher yet).

**Comment by nyancrimew** [comment]
Icons can be changed per app already selecting icons from other icon packs

Everything here has been requested before, please search for other issues before opening new ones.
