### ISSUE TITLE
Open folder bug

### ISSUE THREAD

**Issue by samshiver** [Deletescape-Media/Lawnchair#604]
Version 1.1.0.1213
![screenshot_20170825-094052](https://user-images.githubusercontent.com/31093306/29704372-d8f0d196-8979-11e7-8963-35ad4ae2e000.png)
That weird circle appears when I open a folder... It doesn't fix with a restart

**Comment by hkaancaliskan** [comment]
Same on CarbonOS 5.1 Android 7.1.2

**Comment by nyancrimew** [comment]
Fixed
