### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Nevaloud** [Deletescape-Media/Lawnchair#607]
Option to make Google feed enabled indicator at top left of search pill transparent.

**Comment by suphon-t** [comment]
Update your Google app.

**Comment by Nevaloud** [comment]
What does that have to do with adding the option to make the indicator that Google feed is enabled transparent

**Comment by suphon-t** [comment]
The background color is taken from the Google app.

**Comment by Nevaloud** [comment]
Thanks for snubbing me...

**Comment by Nevaloud** [comment]
Updating my Google app. Wich is up to date...always. Isn't going to do anything.

**Comment by amirzaidi** [comment]
Are you on Android 6 or older? Extracting from the Google app doesn't work on those versions.

@paphonb and @deletescape consider adding the drawable to the app itself like this:
https://github.com/amirzaidi/Launcher3/commit/d199f131a521ba8725482ff1e0ef799d82685b96

**Comment by suphon-t** [comment]
I'll cherry pick that commit. Thanks.

**Comment by Nevaloud** [comment]
No I'm on Android 7.1.2
