### ISSUE TITLE
Circular icons not working

### ISSUE THREAD

**Issue by ndzaky97** [Deletescape-Media/Lawnchair#611]
I don't know if this has been reported before, but I just using substratum theme and circular icons back to original when I enable the theme. It's happening for every theme I installed.

**Comment by jacksonhvisuals** [comment]
Well, does the substratum theme override the icons? That seems to be what's happening, and I doubt that it can be fixed. Do icon packs still work?

**Comment by ndzaky97** [comment]
Icon pack still work.. When Android (framework) Overlay applied such as primary or accent colors, the ability of adaptive icons not working.

**Comment by fonix232** [comment]
The Substratum theme most likely overrides things related to the  adaptive icons system, which results in what you experience. This is a fault of the Substratum theme, not Lawnchair.
