### ISSUE TITLE
Crashes on long press of bookmarks from Chrome

### ISSUE THREAD

**Issue by michaelmior** [Deletescape-Media/Lawnchair#613]
When I select "Add to Home Screen" from Chrome and then long press on the shortcut on the home screen, Lawnchair crashes. Shortcuts still work if I tap on them.

**Comment by intelligentcasanova** [comment]
The same happens with other shortcuts like Weather from the Google app.

**Comment by suphon-t** [comment]
Fixed in 8d20a15.

**Comment by michaelmior** [comment]
Still seeing the crash after updating.

**Comment by michaelmior** [comment]
Thanks! The latest update fixes things for me.
