### ISSUE TITLE
Square shape of the icon layer when interacting

### ISSUE THREAD

**Issue by OldDreamr** [Deletescape-Media/Lawnchair#616]
- Something very visually uncomfortable, it is possible to see the quad form as an effect when interacting with the icon, I believe this should be hidden, presenting only the touch effect of the icon.

- Wrong layer not hidden when interacting with applications.

![iconeffectwronglayer](https://user-images.githubusercontent.com/31370889/29742465-201ec4f6-8a56-11e7-8adb-247de24e6fca.png)

**Comment by LautaroBel97** [comment]
I've had this happen to me aswell.

Unrelated: OP would you bother telling me your icon pack? It looks sweet.

**Comment by OldDreamr** [comment]
O icon pack: https://play.google.com/store/apps/details?id=com.themezilla.android_o_icon

The best icon pack for me.
