### ISSUE TITLE
Apps suggestions

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#62]
Ability to enable recent apps in drawer

**Comment by AxiK101** [comment]
When this is gonna implemented plz? Its way too old request.

**Comment by divadsn** [comment]
>way too old
>27 June

@AxiK101 get some tea dude.

**Comment by zilexa** [comment]
How can I upvote this feature request? Not to annoy anyone, just to show demand for it.

Bot Recent Apps and/or Frequent Apps section for App Drawer and Desktop would be amazing!

EDIT: just noticed this one is closed and so are the duplicates. Should there not be one at least still open? At least until developers decide not to add it or until it is added?
