### ISSUE TITLE
Shortcut Enhancements Ideas

### ISSUE THREAD

**Issue by xReamed** [Deletescape-Media/Lawnchair#625]
1. Translucent shortcut menu

2. Blur in shortcuts

3. Colored Shortcuts based on icons or wallpaper

**Comment by RikKoedoot** [comment]
I like these ideas.

**Comment by XNJ4** [comment]
Yeah nice ideas!

**Comment by seven58o** [comment]
I've heard blur kicks up the resource using a lot...true?

**Comment by LinuxLlama** [comment]
@seven58o Very true

**Comment by pamish** [comment]
i want more shortcuts...like i could make custom shortcuts
