### ISSUE TITLE
Weird Padding on Long Press Panel

### ISSUE THREAD

**Issue by multiberry** [Deletescape-Media/Lawnchair#629]
Whenever I long press an icon in the middle column, the panel seems to hang over the edge of the screen, as shown here: http://imgur.com/SRGAgV9

Device Info
Lenovo Vibe S1
6.0.1 Marshmallow
Latest Lawnchair Alpha

**Comment by amirzaidi** [comment]
Use your PC to decrease your DPI with ADB.

**Comment by suphon-t** [comment]
Duplicate of #212
