### ISSUE TITLE
[FR] Option for weather app

### ISSUE THREAD

**Issue by ildar** [Deletescape-Media/Lawnchair#630]
When I tap on the weather on top, I get "App not installed". I'd rather like the app of my choice. Thanks!

**Comment by ildar** [comment]
Still miss this.
Should be quite trivial to implement.
BTW as a starter you could simply open URL at OpenWeatherMap. Better then "not installed" message.

**Comment by ildar** [comment]
Emm, anyone?

**Comment by bohrabhijeet** [comment]
@ildar The devs may consider this for upcoming releases. Stay tuned! 😉

**Comment by TheComputerGuy96** [comment]
@abhijeetbohra Can you do that? :joy:

**Comment by divadsn** [comment]
Added on the list for final release!

**Comment by bohrabhijeet** [comment]
@TheComputerGuy96 No, but David can! Haha!
