### ISSUE TITLE
Folders blur only one the first page

### ISSUE THREAD

**Issue by huynhsontung** [Deletescape-Media/Lawnchair#631]

**Comment by JacobDB** [comment]
I'm seeing this as well.

**Comment by meiao** [comment]
Not sure if this what the original poster saw, but I have some screenshots. On screenshot 4 the blurred area is the same as screenshot 2, even though the calendar widget is not in the other screen.
<img src="https://user-images.githubusercontent.com/292463/32249750-7c76ac44-be60-11e7-8d9b-c88fc3bdb1c8.png" width="200px"/>
<img src="https://user-images.githubusercontent.com/292463/32249751-7c7e6092-be60-11e7-8bbe-80663061b5ac.png" width="200px" style="display: inline"/>
<img src="https://user-images.githubusercontent.com/292463/32249752-7c85c5a8-be60-11e7-85ae-f6152a6f2944.png" width="200px"/>
<img src="https://user-images.githubusercontent.com/292463/32249754-7cbfbe70-be60-11e7-8608-ed6ae81041aa.png" width="200px"/>
