### ISSUE TITLE
An ability to have multiple dock pages

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#636]
Exactly, like Nova Launcher does (actually extremely helpful)

**Comment by Gmandese** [comment]
I find it extremely useful, I create folders and put them in the dock to the right, and contact direct-dial shortcuts to the left. Save home screen space for widgets.

**Comment by fon321** [comment]
This would be great!

**Comment by mihawk90** [comment]
This is basically the only feature I am missing now after using Nova for a while :thinking: 

See also #562

**Comment by arafatamim** [comment]
Erm why was this closed?
