### ISSUE TITLE
Open last app when use as default 

### ISSUE THREAD

**Issue by Omerio26** [Deletescape-Media/Lawnchair#637]
I think delete the 'android:excludeFromRecents="true"' from the AndroidManifest.xml will solved the problem....

*Happen in Leeco eui and meizu flyme , both with marshmallow.
 I think it happened because in both of then the home screen is always show in the recents apps, even 
 the stock launcher.

**Comment by amirzaidi** [comment]
Deleting that will make it show up in the recents screen on every phone which is not the behaviour I'd want. If you think that will fix it try compiling a build with that yourself

**Comment by Omerio26** [comment]
It's weird....I install the original pixel launcher v2.1 and there everything works good in leeco and also in Lg G6....you think that line is the only thing that make it happend in the leeco?

**Comment by amirzaidi** [comment]
> the original pixel launcher v2.1 

That's not the original, that's my Launcher3 fork also known as Rootless Pixel Launcher. If it doesn't have the bug someone should perhaps take a look at my XML

**Comment by Younes-L** [comment]
this bug is weird, it happened randomly on Nova, too.
