### ISSUE TITLE
[Android 8] [nexus 5x] severe battery drain when not running

### ISSUE THREAD

**Issue by 5haney** [Deletescape-Media/Lawnchair#640]
Reproduced multiple times.
Install fresh and set lawnchair as launcher.
Change a few settings to suit then switch to another launcher.

Lawnchair battery usage continues to increase through the day and even though not running and force closed.

In this screenshot it is the top app in the battery usage screen showing 22% device usage from only 1 minute of usage.
![screenshot 25 aug 2017 14-11-09](https://user-images.githubusercontent.com/2614406/29913845-3a60cb1c-8e2e-11e7-9554-ebb9798f8184.png)

Nexus 5x
Android 8.0.0
Every alpha build from the past couple of weeks

**Comment by 5haney** [comment]
Forgot to mention:
Notification access and notification dots disabled.
Weather and location permission disabled.
Blur and wallpaper/accent colour disabled.
Any transparency disabled.

**Comment by nyancrimew** [comment]
Please directly upload the picture here (the xda cdn 404s)

As far as we know so far this excessive battery drain is just a reporting issue on the android side, but it is something we will try to address as soon as we find its origin

**Comment by 5haney** [comment]
Updated first post with direct image

**Comment by 5haney** [comment]
And here is another from the same day but a few hours later.
Remember, Lawnchair was NOT default launcher and was force closed throughout this time.
![screenshot_20170825-191526](https://user-images.githubusercontent.com/2614406/29913944-a1796886-8e2e-11e7-85de-4c4ece9fd3c9.png)

**Comment by ghost** [comment]
I've noticed this issue as well. I don't want to say that the app is draining significantly, but if my Nexus 6P heats up even just a little bit with the app running in the background or not at all, then that tells me something is up. I could try pulling a logcat and see what's up.

**Comment by MerrettJosh** [comment]
Installed Lawnchair yesterday after using Nova Launcher for a little bit, can confirm experiencing battery drain in the background also.
![screenshot_20170907-153628](https://user-images.githubusercontent.com/24864537/30168982-ecd102d0-93e2-11e7-8c1c-306bb3db10d4.png)
![screenshot_20170907-153946](https://user-images.githubusercontent.com/24864537/30168985-eeff030e-93e2-11e7-88bd-c95c40ba6160.png)
