### ISSUE TITLE
Old bug (Google icon disappears) that is still there.

### ISSUE THREAD

**Issue by Pedro1999** [Deletescape-Media/Lawnchair#642]
The Google icon (top left) disappears, especially when you exit of the Lawnchair settings.

**Comment by suphon-t** [comment]
You know that this is an old bug and still open a new issue?

**Comment by ghost** [comment]
O.o

**Comment by Pedro1999** [comment]
@paphonb Yes, precisely because it is an old bug that is not fixed.

This is a page to post problems, if you do not want people to expose unsolved problems, close this page.

Have a nice day.

**Comment by nyancrimew** [comment]
@Pedro1999 there is no need to open 50 issues for the same issues as this just generates extra work for the developers, it does not help us in anyway. Please search before opening a new issue.

**Comment by Pedro1999** [comment]
@paphonb Not to annoy or give more work to anyone, it was just to remember that a bug that has been in place since the beginning and has not yet been fixed.

But do not worry about me, I will not open anything else here, so as not to cause discomfort or overwork.

Have a good day sir.

**Comment by fonix232** [comment]
You should not have opened the bug in the first place. We are aware of it,
but the bug itself is not exactly reproducible within fixed test parameters
- i.e. no idea what causes it. Until we figure that out, we can't fix it.
Opening more and more issues for the same shit just makes the logistics
part of development a living hell.
