### ISSUE TITLE
Feature or Bug?

### ISSUE THREAD

**Issue by Mackerel71** [Deletescape-Media/Lawnchair#643]
I noticed that if I have the Enable Weather off, if I long press on the date at the top, it switches over to the weather. Long pressing on the weather, switching it back to the date. 

LG G6
Android 7.0
LawnChair 1.0.1063

Below is my Google+ post with screenshots:
https://plus.google.com/101454067260102240232/posts/33RePGraVXw

**Comment by suphon-t** [comment]
It's a feature.
