### ISSUE TITLE
Weather is not refreshing and recent app suggestions request.

### ISSUE THREAD

**Issue by hrithikb** [Deletescape-Media/Lawnchair#651]
Hello, I'm on Android 7.1.2 (lineage os) , the weather widget is not refreshing when we refresh it by google feed. And also the icon of haze is a bit larger than the original pixel Launcher.

**Comment by hrithikb** [comment]
One feature request is can you add app suggestions in drawer if possible. It looks like something is missing in the drawer.

**Comment by suphon-t** [comment]
Duplicate of #468 and #62
