### ISSUE TITLE
{Android 8.0 } Nexus 6p App doesn't responds after install

### ISSUE THREAD

**Issue by Sumeetgk** [Deletescape-Media/Lawnchair#652]
lawnchair doesn't work on nexus 6p running android O as I try to open the launcher it doesn't show any icons or any app drawer! any way to fix it?

**Comment by 5haney** [comment]
Clearing data and/or Documents folder used to work for me but not anymore.

**Comment by leokvw** [comment]
Me too. Same on Google pixel

**Comment by eailfly** [comment]
Not work for me either, Android 8.0 on Nexus 6p, I tried clear data, dosn't help.

**Comment by iTaysonLab** [comment]
Redmi Note 3 Pro / 8.0. Same too.

Also, when you swipe the screen lockscreen will appear. Maybe an Oreo problem.
P.S: logcat says nothing interesting

**Comment by ghost** [comment]
#694 basically sums this issue up. There is no proper support for Oreo yet it seems, which is ironic considering the Pixel features was backported from Oreo.

**Comment by divadsn** [comment]
As @xenotrumpet have mentioned the issue, there is no full Oreo support yet!

![06c750f2-5230-4df8-a3f0-c9a64998ab33](https://user-images.githubusercontent.com/28547847/30261082-344f81d2-96cb-11e7-9958-affd695e4b64.jpg)
