### ISSUE TITLE
Default home resets whenever I force stop an app

### ISSUE THREAD

**Issue by adityasubathu** [Deletescape-Media/Lawnchair#657]
This issue arose in build number 1237. Whenever I force close an app, I am greeted with an option to select my default launcher, even though I have selected Lawnchair as my default launcher. Even of I select Lawnchair as my default launcher in that prompt, it appears the next time I force close an app.

ROM: Dirty Unicorns 7.1.2
Device: Redmi Note 4 (arm64)

**Comment by suphon-t** [comment]
Should be fixed with the next update. Please report back.

**Comment by adityasubathu** [comment]
It's fixed
