### ISSUE TITLE
Date issue with the Pixel widget

### ISSUE THREAD

**Issue by Mikus92** [Deletescape-Media/Lawnchair#659]
Hi, first off all, thanks and congrats for this awesome work ! 
There is an issue with the complete date under the weather icon. When the name of the month is long (like September) the number of the day not appears correctly on the screen...
Could you please shorten the name of the month or reduce the font size  ?
Thanks a lot ;-)

**Comment by Mikus92** [comment]
Total commander file list (copy)
Total files: 1
/storage/0123-4567/Pictures/Screenshots
Screenshot_2017-09-02-19-25-49.jpg	802647	2017-09-02 19:25:49

**Comment by fonix232** [comment]
I believe the best course of action would be to change the date format from full month name (e.g. September) to short month name (e.g. Sep).

@deletescape any input?

**Comment by Mikus92** [comment]
Correction : this issue finally come from due to the columns extension in home page (5 by default to 7 for my example). The Pixel widget also stretches with the column extension... ;-)
