### ISSUE TITLE
Notification Badges don't show sometimes

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#66]
BUG: Some notification badges don't show on some apps, like Google Play Store when I downloaded a new app.

**Comment by bappa555** [comment]
Notification badges does not show on MIUI 8

**Comment by Ochach** [comment]
Hello dear Lawnchair creator! Thanks a lot for a great job! The first ever side launcher i would like to stay and keep! I have Galaxy S8 Plus. Model SM-G955FD. Firmware version XXUAQF7 (the last official update). I have notification badge issue too. They doesnt appeat on desktop, even they normally appear in apps drawer. Please make a fix

**Comment by deletescape** [comment]
This will be fixed in todays build
