### ISSUE TITLE
[Feature Request] Separate sections for Import and Export

### ISSUE THREAD

**Issue by adityasubathu** [Deletescape-Media/Lawnchair#663]
Separate sections for Import and Export settings. The current implementation is a bit inconvenient. I sometimes export my settings instead of importing them, which overwrites the settings I was trying to import. It would be better if they were separated by, let's say, a line

**Comment by guest4711** [comment]
A warning before overwriting would also be good. And how about a way to administrate the backup files (e.g. by calling the GUI to select/delete/rename the backups)?

**Comment by LinuxLlama** [comment]
This has been added in the latest build.
