### ISSUE TITLE
Feature request :)

### ISSUE THREAD

**Issue by 1chrome** [Deletescape-Media/Lawnchair#664]
Not sure if this is the right place to ask - I've never used GitHub before.

A feature (toggle) to blur the current wallpaper would be nice if possible. Would look nice when using light wallpapers with light icons - makes them more visible.

Thank you for the awesome product, Team Lawnchair!

**Comment by iTaysonLab** [comment]
Options > UI > swipe down > Blur.

**Comment by LinuxLlama** [comment]
There are a lot of apps that can do this.
