### ISSUE TITLE
Search icons

### ISSUE THREAD

**Issue by lologolo** [Deletescape-Media/Lawnchair#665]
Can you add the possibility to search icon by name in layout where all the icons are displayed?
![](https://i.imgur.com/K8SbkMX.png)

**Comment by 1chrome** [comment]
Yes! Would be a great feature to see!

**Comment by 1chrome** [comment]
Yes! Would be a great feature to see!

**Comment by ghost** [comment]
gib

**Comment by burakdede0** [comment]
That would be good.

**Comment by pjtsearch** [comment]
Great idea!

**Comment by m-p-3** [comment]
May I suggest an horizontal scrollbar to quickly switch between icon groups or alphabetical categories? ie: trying to reach the letter R takes a lot of left-swipe to reach it.
