### ISSUE TITLE
Folder in app drawer

### ISSUE THREAD

**Issue by 1szymon4** [Deletescape-Media/Lawnchair#666]
Is it possible to create a folder in the app drawer?

**Comment by LinuxLlama** [comment]
it's not possible to do. Would be a nice feature to have!

**Comment by jabia13** [comment]
I'd like to see us implement the ability to create folders in the app drawer. This would enable better management of the app drawer and greatly improve productivity. For example, office apps and banking apps can be separately categorized in the app drawer without having to clutter the home screen.

This functionality is similar to what is currently available in Samsung's TouchWiz app drawer (home). My ideal setup would have folders created at the top of the app drawer so the most important apps are easily within reach.

Thanks for all your effort so far, they are greatly appreciated. Please let me know if you'd need any further clarifications.

**Comment by YAJATapps** [comment]
https://github.com/gmillz/SlimLauncher/tree/staging?files=1

This is a launcher3 nougat 7.0 launcher3 which support very experimental folders in drawers. not usable as a daily driver but you should look at it to start implemeting this.

**Comment by thatside** [comment]
Upvoting this. Actually I'm not into Android development but I could participate in testing if needed.

**Comment by vndre** [comment]
This would be a really useful feature. I have a lot of apps and it is really useful for me to keep them classified so my drawer doesn't become a mess, please consider it.

**Comment by jackfagner** [comment]
@deletescape I really want this feature. If I were to code it and make a pull request, would you include it?

**Comment by nyancrimew** [comment]
@jackfagner I am always happy to accept pull requests :)

**Comment by skaveesh** [comment]
This is a really useful feature. We would love to see it.  👍 👍 👍 👍

**Comment by ChulanKumara** [comment]
Yes Please.
This feature is much wanted and would love to see it happen. 👍👍👍

**Comment by Phil3819** [comment]
Any news on this feature. I have just started using Lawnchair and need to be able to categorise and order my apps. The ability to sort them alphabetically, recently installed and most used would be good as well. Many thanks for all the work done so far.

**Comment by ghost** [comment]
+1

**Comment by divadsn** [comment]
@Ufeldraku Satan feature? Lol

**Comment by anirudhgupta109** [comment]
@divadsn Well it is 666, makes sense

**Comment by ghost** [comment]
@divadsn The Unholy App Drawer Folder.

**Comment by Trinity015** [comment]
When is this feature going to be implemented 
I really need thiss

**Comment by skittles9823** [comment]
@Trinity015 Why do you say "when"? Was it ever confirmed to be added? If so I don't remember this.

**Comment by guest4711** [comment]
A lovely feature (known from TouchWiz and Nova). Makes live easier for some of us - and helps LawnChair to compete with others (and to be more than a pixel clone).

**Comment by myfrom** [comment]
Basically this is the only thing that keeps me with Nova. If Lawnchair would have that it would be heaven. Also could you think of something like synced folders such as when you drag a folder from app drawer to home screen, they stay in sync. It's currently working that way in Nova

**Comment by divadsn** [comment]
@myfrom We will have frequently used apps in the final version :)

**Comment by kevin71246** [comment]
Upvoting. All the good launchers have a feature like this; whether its App drawer folders or tabs, grouping is necessary to organize apps. Please add!

**Comment by kevin71246** [comment]
Lools like Microsoft Launcher from play store has this feature as well.

**Comment by quezak** [comment]
This would be a really nice feature! Frequently used apps is not the answer here -- I have my frequently used apps on the home screen already. With app drawer folders, I could group all other >100 apps into categories, and even rarely-used apps would still be available at 2 clicks: app drawer folder -> select what you want, no scrolling or searching :)

**Comment by Crescendo-BLYAT** [comment]
2019 and this launcher can't do simple folder...

**Comment by skittles9823** [comment]
@Crescendo-BLYAT Tabs are better though 👀👀

**Comment by Crescendo-BLYAT** [comment]
> @Crescendo-BLYAT Tabs are better though 👀👀

same, whatever for organizing the shortcut inside instead of dumping them in one place.... 
like Nova Launcher.....

**Comment by rodrigoswz** [comment]
> @Crescendo-BLYAT Tabs are better though 👀👀

@skittles9823 I use both!

I use tabs for categories (games, photography, media, etc), just to easily find the apps I need at the moment, but not hidden them in the **main tab** (All apps).
And I use folders on drawer that I use to organize apps that I do not want to be spread around the **main tab**, which I almost never open but I do not want to hide them (icon packs, widget packs, tasker plugins, etc).

But I understand that this is my point of view, I know people use either folders OR tabs for the same purpose. Btw I was going to love this feature in Lawnchair, because I have used this method of organizing my drawer for years.

**Comment by quezak** [comment]
> @Crescendo-BLYAT Tabs are better though

Not in all cases. Tabs are nice if you have 3-4 of them. I probably need 6-10 folders to categorize all my apps. If I were to put them in tabs instead, I'd have to scroll through the tab list to find the tab I want, so then accessing the apps will be much longer and annoying, which kinda defeats the whole purpose of having them categorized. With folders you can access an app with just 2 clicks, no scrolling required.
