### ISSUE TITLE
[BUG] Clearing Telegram/WhatsApp notifications from app shortcut popup don't clear their actual notifications :(

### ISSUE THREAD

**Issue by 1chrome** [Deletescape-Media/Lawnchair#668]

**Comment by Younes-L** [comment]
android version ?

**Comment by Younes-L** [comment]
could be related to #364

**Comment by 1chrome** [comment]
Android version is Nougat 7.1.2

**Comment by divadsn** [comment]
Build version? Stock Android or a modified such as EMUI, MIUI, Grace UX, TouchWiz?

**Comment by Younes-L** [comment]
must be stock since you can only have 7.1.2 on stock Nexus, Pixel, wileyfox , ROM (all stock) and LG V30 which isn't yet available.

**Comment by suphon-t** [comment]
@Younes-L there are tons of 7.1.2 custom ROMs.

**Comment by 1chrome** [comment]
@divadsn I'm on Dirty Unicorns 11.7 (unofficial build) which is on 7.1.2. Running it with EX kernel. I've had this issue on all ROMs I've run including Motorola stock ROM (I use a Moto G4 Plus)

**Comment by Younes-L** [comment]
@paphonb yes, sorry for misunderstood. By stock I meant non OEM skinned AOSP
