### ISSUE TITLE
[Feature Request] Double tap to sleep on home

### ISSUE THREAD

**Issue by burakdede0** [Deletescape-Media/Lawnchair#670]
Sorry if someone asked before me. That feature would be cool. Other famous launchers have this feature, and Lawnchair is better than most of them. Only missing that feature. Thanks.

**Comment by Younes-L** [comment]
this will either require device administrator or root to work properly, and device administrator will in turn require PIN or pattern to unlock. No fingerprint, no smart lock allowed.

**Comment by burakdede0** [comment]
This can be exclusive for root users. No problem

**Comment by fahmi182** [comment]
+1 Please add this...

**Comment by guest4711** [comment]
See #40
