### ISSUE TITLE
[Feature Request] Use top center space for something useful

### ISSUE THREAD

**Issue by TobberH** [Deletescape-Media/Lawnchair#672]
I would love to be able to add either an app icon or maybe a 1x1 widget to the empty space between the Google button and the optional weather widget. 

Otherwise I love the launcher so far, especially the dark theme! 😀

**Comment by divadsn** [comment]
It's actually possible, turn off the pill widget, put something in the first row and turn on the pill widget again, you should still see your Icons there :wink:
