### ISSUE TITLE
Dots not working on my Huawei P8 GRA-L09 (not rooted)

### ISSUE THREAD

**Issue by Rufus85** [Deletescape-Media/Lawnchair#675]
Hi i have a Huawei p8 androi 6.0 EMUI 4.0.3 and i cant see the dots or the badge after the long press. If I reset the phone it works for a few seconds but if I do whatever with the phone and then come back to the desktop the dots and the badges feature stop working. thx in advance

P.D.: notification acces allowed and lawnchair allways on in all the huaweis features for disable apps with screen off.

**Comment by fishears** [comment]
Dots also not working for me on Nexus 5X with Android 8. Was working on ODP4 but stopped working after OPR6  (release)

**Comment by fonix232** [comment]
@fishears completely unrelated. Please try to not derail the topic.

@Rufus85 This seems to be an EMUI related bug. Since AFAIK none of us has Huawei devices, I doubt we can reproduce the issue. Can you please use our issue template and go into detail?
