### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by ildar** [Deletescape-Media/Lawnchair#676]
It seems that the current v. 1.0.1063 has [troubles building in some environment](https://gitlab.com/fdroid/rfp/issues/319) while GIT HEAD is fine.
Could you please make a bugfix minor release? That'll help pushing Lawnchair to F-Droid.
Thanks in advance!

**Comment by jacksonhvisuals** [comment]
Please note that you aren't allowed to push to F-Droid without our permission.

**Comment by ildar** [comment]
Yes, precisely. I'm waiting in another issue.
Take your time to decide.

**Comment by ShadowRedel** [comment]
@ildar you have here the new releases: https://lawnchairmirror.duckdns.org

**Comment by ildar** [comment]
Ahh, nightly! No, I was meaning a Release, i.e. tagged commit in git.

**Comment by ShadowRedel** [comment]
Ahh okay, sorry about that

**Comment by fonix232** [comment]
Duplicate of #240
