### ISSUE TITLE
[Feature request] Ability to change color of pill widget

### ISSUE THREAD

**Issue by Nevaloud** [Deletescape-Media/Lawnchair#677]
Please add ability to change color of Google widget weather/date text .

**Comment by divadsn** [comment]
I think at the moment the best solution would be substratum themes __if you are rooted__, have a look at the various tutorials available on the substratum community on how to create themes and change the colors to your desire by editing the widget values in [res/values/colors.xml](https://github.com/Deletescape-Media/Lawnchair/blob/alpha/app/src/main/res/values/colors.xml#L48-L78).

**Comment by Nevaloud** [comment]
Sounds good. Been wanting to explore subs deeper than just end user

**Comment by divadsn** [comment]
Cool, so I will close the issue for now. If you need any help with substratum, go ahead and join the themers group on Telegram @ThemingHelp or here: https://t.me/ThemingHelp

**Comment by Nevaloud** [comment]
Thanks again
