### ISSUE TITLE
Rename "Transparent Dock" to "Hide Dock", add actual transparency slider to dock

### ISSUE THREAD

**Issue by jacksonhvisuals** [Deletescape-Media/Lawnchair#679]
Currently, it's a bit confusing that "Transparent Dock" is titled as such, when what it really seems to do is "Hide Dock." Renaming this would be nice.

Additionally, an actual transparency slider for the dock background would be nice.

**Comment by suphon-t** [comment]
The "Transparent Dock" option really makes the dock transparent but still there.

**Comment by jacksonhvisuals** [comment]
I misspoke. The problem is that the indicator drops down to below the dock
if the dock is "transparent." If the dock was merely transparent, the
indicator would still be above. I think we should add a toggle that hides
the swipe indicator also.

**Comment by LinuxLlama** [comment]
Closing since we have this implemented.
