### ISSUE TITLE
[FEATURE REQUEST] Disable "search app"  in app drawer

### ISSUE THREAD

**Issue by milouk** [Deletescape-Media/Lawnchair#681]
it would be nice if you could implement the ability to disable the search within the app drawer

**Comment by Younes-L** [comment]
pretty sure this was available before o.o

**Comment by milouk** [comment]
i have no idea...i have been using this launcher for a week and i would really want the option to disable the search bar in the drawer

**Comment by fon321** [comment]
agreed, I never use the Search Bar in the drawer either.

thanks!
