### ISSUE TITLE
(Bug) Reboot Lawnchair cause change language

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#682]
As tge title says, when i reboot Lawnchair it automatically changes the language to english. A sexond reboot reverts to local language and it goes on

**Comment by divadsn** [comment]
**Use the goddamn issue template, otherwise we can't reproduce your issue, thanks.**

https://raw.githubusercontent.com/Deletescape-Media/Lawnchair/alpha/.github/ISSUE_TEMPLATE.md

**Comment by AxiK101** [comment]
I don't know how to use that template. As i said half of Lawnchair stays in English and the rest is using local language. If i reboot Lawnchair some parts revert to local language, if i reboot again they turn to english again. My device is sony Xperia xa ultra, f3211, stock 7.0, no root. No logcat provide, thanks

**Comment by divadsn** [comment]
Which Lawnchair build are you running? Have you tried with the latest one?

You can get the latest available build on Telegram @lawnchairci or here:
https://lawnchairmirror.duckdns.org/latest/lawnchair-latest.apk

**Comment by AxiK101** [comment]
yes i always use the latest, niw i got 1.1.0.1243

**Comment by AxiK101** [comment]
https://drive.google.com/file/d/0B-7jWHTkaOyWU1lrV09CWTNyZmc/view?usp=drivesdk

video presentation

**Comment by AxiK101** [comment]
I did reboots, fresh installs, nothing seems to fix the problem. It's definitely a Lawnchair's bug probably on my device

**Comment by AxiK101** [comment]
I did reboots, fresh installs, nothing seems to fix the problem. It's definitely a Lawnchair's bug probably on my device

**Comment by divadsn** [comment]
Ok, the icons in app drawer seems to be wrong as shown in your video, but the settings looks like they aren't translated to Greece, you can fix them by contributing us some translations on our Crowdin page.

**Comment by AxiK101** [comment]
@divadsn i am the main translator for greek language. As i said, after few Lawnchair reboots, languages seems to switch everytime, it's not the translation the problem (i always update the strings file from crowdin), it must be some kind if bug. Didn't have it for so long, only at latest beta builds

**Comment by AxiK101** [comment]
any solution for this problem devs?😁

**Comment by AxiK101** [comment]
New build but this bug still tortures me😥😥
https://drive.google.com/file/d/0B-7jWHTkaOyWX2cwVWRqb3ZuYlU/view?usp=drivesdk

**Comment by nyancrimew** [comment]
Restarting through the debug options is the same thing as if you would force stop it and start it again, which can both result in weird uncontrollabe behaviours. I don't see a way in which we could (and would want to) do something about this.

**Comment by AxiK101** [comment]
ok obviously it's a bug related to latest builds, in the past that didn't happen. Whatever, i will change my system language to english until i hate it...😜😜

**Comment by AxiK101** [comment]
it's finally fixed. thanks devs!!😂
