### ISSUE TITLE
Suggestion for Pill Widget

### ISSUE THREAD

**Issue by 1chrome** [Deletescape-Media/Lawnchair#684]
When using Dark/Black themes, thr pill colour changes but the translucent area behind the pill widget remains white in colour.

If the hex value for the Dark/Black theme  colour is used, it would blend in and look better :grinning:

![See screenshot](https://ibb.co/dbLvzF)

**Comment by divadsn** [comment]
Fix screenshot please and...

**Provide us more details about your setup as in the issue template provided!**

**Comment by 1chrome** [comment]
@divadsn I'm not reporting a bug, I was suggesting an aesthetic improvement. Do you still require me to follow the issue template?

**Comment by Partixel** [comment]
Definitely is a bug, image here, you'll notice part of the pill is white:
![image](https://user-images.githubusercontent.com/2728862/30174295-779535c6-93f2-11e7-9f3b-2ad648b2989a.png)

Using S8+, latest version of lawnchair

**Comment by divadsn** [comment]
@1chrome it's unclear from your issue description what do you mean, because not everything has to be addressed to us, sometimes it's the fault of the themer who missed something to theme.

Also, it would be easier for us if you would provide us the steps (as wanted by the issue template) that we need to do in order to understand your issue :grin:

**Comment by RikKoedoot** [comment]
this bar is provided by the Google app. and that is not changeable by lawnchair

**Comment by 1chrome** [comment]
@rickkode Ah alright. Thanks for the clarification :)

**Comment by Partixel** [comment]
@rickkode @1chrome 
I'm pretty sure it is changeable by lawnchair as lawnchair already changes the main part of the pill for the dark theme?

**Comment by divadsn** [comment]
See issue #677 for suggestions how to theme the pill widget to your own needs.
