### ISSUE TITLE
No Screen rotation on tablet UI

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#686]
Im not sure if issue has been adressed.

## Description

When I rotate my Samsung Galaxy Tab A 8.0 the launcher stays in portrait mode. I consider this a bug because even the opengapps pixel launcher rotates on a tablet UI

## Expected Behavior

When I rotate the device the UI should rotate to landscape UI

## Actual Behavior

The Launcher stays in portrait mode! It doesn't appeare to support landscape UI?

## Steps to Reproduce

1. Install Launcher
2. Set Launcher to default
3. Rotate Tablet to landscape
4. Launcher does not rotate with tablet

## Environment

* Device: SM-T350
* Android version: 6.0.1
* Launcher version: 1.0.1063
* Rom: Evervolo

**Comment by divadsn** [comment]
Enable screen rotation in Settings -> General.
