### ISSUE TITLE
High RAM consumption

### ISSUE THREAD

**Issue by AndreHM** [Deletescape-Media/Lawnchair#687]
Lawnchair consumes a lot of RAM, going from 100 MB in one day. NOTE:The only extra feature that I leave enabled is the Notification Dot, however in the Rootless Pixel Launcher I leave it and it does not exceed 50MB in RAM consumption.

**Comment by divadsn** [comment]
It's still lower than any other launcher out there, for example Evie takes 380 mb on my phone running Oreo and has far less features than Lawnchair.

Also, please be aware that additional features that aren't in stock Pixel Launcher like custom weather providers or blur always take some additional memory, therefore I will close this issue.

**Comment by AndreHM** [comment]
But how can I consume so much memory if I do not leave any of these resources on?

**Comment by divadsn** [comment]
An app is loaded with all of it's assets into the RAM, including decompiled files and cache for faster launch.

**Comment by fonix232** [comment]
Also, notification dots, mainly because it's a not too optimized backport (and a quite hacky one on <8.0), consume ~100MB extra RAM. Without those, your TEAM usage will be around 50MB too.

**Comment by QQLol-hash** [comment]
@
