### ISSUE TITLE
[Feature Request]  Solid navbar dock & widget in dock

### ISSUE THREAD

**Issue by jaduprey** [Deletescape-Media/Lawnchair#688]
I would like to respectfully request a new feature that I perceive would make this app more delicious.

A) I would like to request the option to change color of navbar dock to solid or any color by using a hex color palette picker.

B) If possible, to insert/add/incorporate a small widget inside the navbar dock. This would resemble many homescream setups in G+ where the navbar icons are seen next to widgets all within the dock area.

I can accommodate bribes, if acceptable, e.g. cool ranch Doritos, IBC Root Beer...

**Comment by jaduprey** [comment]
Wanted to follow up with second part of request: option to manually change color of dock using hex or other color palette picker.

The widget in dock has already been pulled.

Thanks.

**Comment by jaduprey** [comment]
Deletescape,

Does this mean it was incorporated in the LL?

**Comment by divadsn** [comment]
@jaduprey Check pinned issue

**Comment by nyancrimew** [comment]
@jaduprey see #1462
