### ISSUE TITLE
[FEATURE REQUEST] option to re-enable the microphone icon on the large and small search bar

### ISSUE THREAD

**Issue by alexsmithfanning** [Deletescape-Media/Lawnchair#689]
If I recall correctly, at some point this was a thing, wasn't it?

**Comment by divadsn** [comment]
There was no microphone icon on the Pixel/Lawnchair Launcher, you probably have seen that on the old Google Now Launcher, but now it's been replaced by Google Assistant, therefore I will close this issue.
