### ISSUE TITLE
[Features request] Reset custom icon & separate theme effect

### ISSUE THREAD

**Issue by iwantz** [Deletescape-Media/Lawnchair#690]
## Expected Behavior

1.An option to reset Custom icons with a single click.
2.Application of separate theme effects for dock and appdrawer
## Actual Behavior

1.We can only return all the custom icon we choose manually by cleaning the data on the lawnchair,Or by resetting one by one
2.Dock and appdrawer should have the same theme, but maybe some users just want to apply it to the dock or drawer only.
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: geehrc
* Android version:7.1.2
* Launcher version:1.1.0.1127
* Rom: Nitrogen Os

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
1. A custom icon reset feature is being implemented afaik.
2. It would be a nice feature, but I think that it's also up to the themer to theme that :wink:

**Comment by iwantz** [comment]
@divadsn thanks for the response, but I really have not seen any option to reset custom icon, even with the latest version 1.1.0.1245
Maybe I'm wrong, if you do not mind can you show me how to do that 🤔

**Comment by suphon-t** [comment]
It is being implemented, not implemented.

**Comment by iwantz** [comment]
@paphonb aha...sorry, my bad, do not read carefully what david wrote, thank you 🍻
