### ISSUE TITLE
Doesn't work with Unofficial LineageOS 15.0 (Oreo)

### ISSUE THREAD

**Issue by woohooatb** [Deletescape-Media/Lawnchair#692]
## Description
Doesn't work with Unofficial LineageOS 15.0 (Oreo)

## Expected Behavior
It should run. But it doesn't. 

## Actual Behavior
Just shows blank screen with no icons and app drawer cannot be accessed.

## Steps to Reproduce

1. Install LineageOS https://www.androidfilehost.com/?w=files&flid=211867
2. Install Lawnchair
3. It doesn't work

## Environment
* Device: Xiaomi 5s Plus "Natrium"
* Android version: 8.0.0
* Launcher version: Latest Lawnchair build from https://lawnchairmirror.duckdns.org/1.1.0.1243/ 
* Rom: LineageOS 15.0

**Comment by xenotrumpet** [comment]
See #582
