### ISSUE TITLE
Please recompile app with intel x86 libraries....

### ISSUE THREAD

**Issue by JackGitrocks-19** [Deletescape-Media/Lawnchair#693]
Sorry for posting back again about this issue.....:cry:
I'm using the latest version....There's still a dialog on startup of launcher saying "Detected problems with app native libraries--->>libavcodec.so:text relocation, libswresample.so:text relocations..."

Can you please look into this issue and fix it ASAP.....This issue is present in Asus x86 devices
[I'm running LineageOS 14.1 builds in my Asus Zenfone 2(Z00A--->x86)]:relaxed:

**Comment by divadsn** [comment]
Well I can only suggest you compiling the app for x86 devices on your own, there are plenty of tutorials how to build an app from source, so it shouldn't be hard if you have a machine with Linux or macOS.

**Comment by fonix232** [comment]
Lawnchair uses no native elements whatsoever, and such, compiling against x86 targets won't solve the issue. This seems eerily specific to Asus devices (though it might be because only Asus chose to run Android on Intel's chipsets).

**Comment by nyancrimew** [comment]
This is a bug in x86 Android System Libraries which are being used by Lawnchair, there is no possible way to fix this by us.
