### ISSUE TITLE
Lag - Android Oreo Nexus 6P

### ISSUE THREAD

**Issue by Princevader** [Deletescape-Media/Lawnchair#694]
## Description
Lag on my Nexus 6P with official Android Oreo

## Expected Behavior
Smooth like the Pixel Launcher and Google Now launcher

## Actual Behavior
The launcher is lag

## Environment

* Device:Nexus 6P
* Android version:8.0
* Launcher version:v1.0.1063
* Rom: Stock Android

**Comment by divadsn** [comment]
![9c16aa07-f30c-42f0-96f7-6e105934b835](https://user-images.githubusercontent.com/28547847/30244672-1a7a5998-95c3-11e7-8468-7e806b8fe87e.jpg)

**Comment by divadsn** [comment]
Jokes aside, Android O is currently not supported, so you shouldn't expect anything working smooth.

For example, it's even not starting on my Redmi Note 3 running AOSP Oreo.

**Comment by Princevader** [comment]
It's ok. Thanks for the fast response. :)

**Comment by tslio2013** [comment]
I have Nexus 6p and I just installed the new 8.0 and it's sucks!! Too much lag

**Comment by divadsn** [comment]
@tslio2013 read again or GTFO please, people like you are mostly the reason why devs stop working.

**Comment by divadsn** [comment]
Fixed #854
