### ISSUE TITLE
Wallpaper shifts to left on dock

### ISSUE THREAD

**Issue by shriksr** [Deletescape-Media/Lawnchair#696]
## Description

Sometimes wallpaper shifts to left side on dock when blur is enabled on dock.

## Expected Behavior

Wallpaper should not be shifted to left when blur enabled. It should stay in position like home screen wallpaper.

## Actual Behavior

Sometimes wallpaper shifts to left side when blur is enabled.

## Steps to Reproduce

1.https://plus.google.com/+shrikantrapelli/posts/hZ4TutSmFzy
2.
3.
4.

## Environment

* Device: Moto G5 Plus
* Android version: 7.0
* Launcher version: 1.1.0.1243
* Rom: Stock Rom

**Comment by fonix232** [comment]
This is a quite weird behavior, something I haven't noticed before.

Can you try to achieve a way of reproducing it?

**Comment by suphon-t** [comment]
This is a weird issue that happens when there is only one home screen. A workaround is to create a new page and then remove it.

**Comment by shriksr** [comment]
I have two page in homescreen
