### ISSUE TITLE
Can't rearrange left most screen

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#702]
Description
The leftmost "default" screen is locked into place. I can't move it or place other screens next to it.

Expected Behavior
First screen is picked and follows finger, other screen are moved left to the first.

Actual Behavior
Nothing happens when leftmost screen is long pressed, and other screens can't be placed left to the first.

Steps to Reproduce
Long press wallpaper or pinch to overview, long press first screen.

Environment
Device: A0001
Android version: 7.1.2
Launcher version: 1245
Rom: Slim7 0.25 Dev-DM

Notes
If it's the same case with Pixel Launcher, ignore this or take it as feature request : reassign default screen.

**Comment by Younes-L** [comment]
I have never used Pixel launcher before, so if Pixel Launcher works the same way, ignore this or take it as feature request 

The FastHub app is not allowing me to edit this issue in order to add the issue template, might take a few minutes

**Comment by divadsn** [comment]
Yep, it's intended as in stock Pixel Launcher, the leftmost default page is also the one where the pill widget is placed, that's why you can't change it's position. So I will close this issue :)

**Comment by bungabunga** [comment]
hey, @Younes-L, i'd like you to consider reopening this as a feature request. let me explain:

some of us have Google Now purpousely deleted/freezed from our devices. why? Google Now is a piece of legal spyware that knows just every single bit of what you do on your device. it's a trade off between usability and privacy. a bad trade off if you ask some of us. and if you're without Google Now, swipe-left from the home page does nothing and is useless.

you may argue that Lawnchair is intended to use with Google Now as it tries to replicate Pixel Launcher behaviour but please know that Lawnchair is the ONLY DECENT android launcher that is free and open source. and if you ask me it's not only decent but fantastic and it would be a pitty to not be so useful for some of us.

thanks! :)

**Comment by Younes-L** [comment]
@bungabunga hello, thanks for your interest ! 

I have a similar stance toward the Google Now pane/Google feed situation. I don't use it at all, and feel like Lawnchair could see great benefits if freed from these Google limitations.

While I definitely understand why they chose to make it this way, it's kind of poorly executed (there's no reason for the first screen to be immovable – small issue but non negligible imo).

Unfortunately I don't think I can reopen the issue, however I can point you to a similar issue that's currently still opened; it is referenced above your comment.

**Comment by divadsn** [comment]
@Younes-L >Pixel style

**Comment by Younes-L** [comment]
@divadsn  I'm sorry, did I miss something ?
Was such feature added recently ?

**Comment by bungabunga** [comment]
sorry, @Younes-L, I wanted to adress this at @divadsn, but mistakenly adressed you. I posted my arguments here but I don't want to spam opening another issue with the same content. hope my arguments would prevail.

**Comment by Younes-L** [comment]
Well that's embarrassing 😅 apparently I had some things to say on the subject as well 🤣

**Comment by bungabunga** [comment]
@Younes-L of course you do. we share the same arguments, but we're both unable to solve this issue.. :wink:

**Comment by sqozz** [comment]
I may add my +1 here to reopen this as FR since the launcher is actually pretty nice - just this small thing what bothers me. (Arguments are already mentioned above)

**Comment by divadsn** [comment]
Well, as Lawnchair is a Pixel style launcher, we are not gonna to make this a feature, as it's not fitting the design with the Pill widget and left side Google Now pane, even if it is disabled for whatever reason.

**Comment by Younes-L** [comment]
I think I finally understand why... The first screen is frozen for the same reasons the pixel search bar/pill widget is frozen, because it's a regular widget that overwrites whatever was in the first row, instead of occupying an additional row in the desktop grid. Should we move the first screen to second position, another pixel widget would get created on the new first screen and other unexpected behaviours.

**Comment by fghsgh** [comment]
It could also work in such a way that if the widget is disabled, you can move the first page.

**Comment by amirzaidi** [comment]
In Pie the screen reordering feature has been removed entirely by Google, so this issue should not be necessary anymore.

**Comment by fghsgh** [comment]
I though this was not just supposed to be the Pixel launcher but open-source, but a launcher, based on Pixel, with more functionality/options (like reordering the screens or maybe even set another one as the main one).

**Comment by fghsgh** [comment]
Just so you know, the reason why I started looking out for custom launchers is exactly this annoying search bar.
