### ISSUE TITLE
[FEATURE REQUEST] Slide finger instead of tap to open app shorcuts

### ISSUE THREAD

**Issue by EmNN** [Deletescape-Media/Lawnchair#703]
A bit tedious and counter-productive to execute another tap after the app shorcut window is opened. iOS 3D Touch implementation can be adopted such that, after tap and hold on app icon to open app shorcut window, simply swipe finger onto shorcuts while keeping finger in contact with the screen. However, this is only possible when 'Lock desktop' is enabled as swiping across the screen to access app shortcut will only move the app icon instead. Another thing that should be taken note is even when the desktop is locked, swiping on app shorcut window will open the app drawer, provided the app icon isn't in a folder.

**Comment by divadsn** [comment]
If you wanna have iOS features, then buy an iPhone, thanks.

**Comment by suphon-t** [comment]
I will consider this as swiping is useless after locking the desktop anyway.
