### ISSUE TITLE
Graphical bug in long tap options

### ISSUE THREAD

**Issue by ronak-j** [Deletescape-Media/Lawnchair#705]
## Description
![Image of Bug](https://image.ibb.co/mC1cZF/Screenshot_20170911_111109.png)

## Expected Behavior

The rounded rectangle shown above should be perfect.

## Actual Behavior
There is a short white line on top right corner which should not be there.

## Steps to Reproduce
1. Long tap on icon on home screen.
2. See the bug in all it's glory.
(I changed the no. of columns in home screen to 6, icon size to 85% and icon text to 95%) 

## Environment
* Device: mido
* Android version: 7.1.2
* Launcher version: v1.0.1063
* Rom: RR 5.8.4 (11/08 build)

**Comment by divadsn** [comment]
![image](https://user-images.githubusercontent.com/28547847/30262929-4299094a-96d3-11e7-81c1-1731e75c6340.png)

As far as I know this should've been already fixed with the latest builds.
