### ISSUE TITLE
Feature request: small Pixel Google Search Pill widget

### ISSUE THREAD

**Issue by taras-mukin** [Deletescape-Media/Lawnchair#707]
Requesting for ability to keep search widget small (not wide version) and hide date/weather on the right with the ability to place something instead in this place (icons, widgets — like elsewhere on desktop). 

Or just add this small pill as regular widget.

**Comment by ellenswamy** [comment]
You could turn off the top bar, and just download a widget from the play store

**Comment by taras-mukin** [comment]
Any other widget can only mimic looks of pill widget, but not perfectly and without animations, integration with Google Now and everything. It short -- it can't look and work 100% accurate.

**Comment by divadsn** [comment]
Toggles will be added in #959
