### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by LGR0102** [Deletescape-Media/Lawnchair#708]
![screenshot_20170911-003525](https://user-images.githubusercontent.com/31862141/30289519-c5a7deb8-9702-11e7-82cd-3e93e6d24930.png)
![screenshot_20170911-003525](https://user-images.githubusercontent.com/31862141/30289535-d43fa938-9702-11e7-8237-90df2abfaeed.png)

## Description
I'm using lawnchair already for 3 months or more, in all of this months a lot of times the WhatsApp shortcuts keep despairing from nowhere. And from nowhere again, it gets back. Doesn't matter the version I use, it always desapear.

S7 Edge International Version
Android version: 7.1.2
Lawnchair version 1.1.0.1245 (from the telegram group)
LineageOs

**Comment by divadsn** [comment]
Afaik these shortcuts are currently only available on WhatsApp Beta.

**Comment by divadsn** [comment]
https://9to5google.com/2017/07/27/app-shortcuts-now-available-in-latest-whatsapp-beta/

Please note that beta versions are **always** buggy and are mostly unsupported by 3rd parties.
