### ISSUE TITLE
is there any possibility to run this code on SDK 19 or any older release works ?

### ISSUE THREAD

**Issue by samansalamat** [Deletescape-Media/Lawnchair#709]
I've a kitkat device, so i cant run on my device.
I have tried to recode your project for min SDK version 19 or lower, but no possibility.also it cant run on stable version android studio(2.3.3).
please help me on this issue.

best regards,

**Comment by fonix232** [comment]
Too much of Lawnchair's features depend on API21, thus backporting it to devices running Android KitKat or older is not possible.
