### ISSUE TITLE
[request] Most used apps bar under the search bar in app drawer

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#710]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by ghost** [comment]
I think a most used apps bar in the top of the app drawer, just under the search bar will be very useful.
Thank you.

**Comment by fonix232** [comment]
1. Search the damn issue tracker before posting a request. This feature has been requested multiple times, posting it again and again won't bring it forward on the list of tasks to do.

2. Use the issue template.
