### ISSUE TITLE
Stolen and uploaded? Again?

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#712]
I think this app is Lawnchair online
https://play.google.com/store/apps/details?id=o.plus.launcher

**Comment by KieronQuinn** [comment]
Yes, that's definitely Lawnchair.

But it gets worse. The donation link goes to the developer's personal PayPal, the translators list is missing Deletescape, the app icon designer is changed to the developer's name (which I suppose is ok, the icon is different), as well as the summary. Here's a screencast of the app: https://streamable.com/ul7bf

**Comment by AxiK101** [comment]
thats a shame

**Comment by divadsn** [comment]
Yeah, it's a shame that there are people on the Internet who try to make money without doing anything else than stealing code from GitHub, but we already have taken done some of these.

Anyway, I can only advise giving these apps 1-star rating and directly reporting them to Google Play.

**Comment by fonix232** [comment]
I especially like this comment the guy left 😆 

![image](https://user-images.githubusercontent.com/371847/30370035-9f081fc8-9876-11e7-961f-ca28037a0312.png)
