### ISSUE TITLE
[Bug] lag swapping folders' pages with blur enabled

### ISSUE THREAD

**Issue by Loruski** [Deletescape-Media/Lawnchair#713]
## Description

After enabling blur and applying it to folders from the settings, when swiping the pages of the folders the animation is laggy, this doesn't happen when blur isn't active on folders

## Expected Behavior

When swiping pages in folders the animation should be fluid

## Actual Behavior

The swiping animation in folders are laggy

## Steps to Reproduce

1.go to settings
2.to interface
3.enable blur effect
4.apply blur on: folders

## Environment

* Device:P9 Lite VNS-L31
* Android version:7.1.2
* Launcher version:1.0.1063
* Rom: lineageOS unofficial

**Comment by divadsn** [comment]
As from my past knowledge with Huawei devices and custom ROMs, I would assume it's more an issue with the unstable OpenKirin kernel than with Lawnchair.
