### ISSUE TITLE
White boxes of apps while searching for apps

### ISSUE THREAD

**Issue by theandroidenthusiast** [Deletescape-Media/Lawnchair#716]
## Description
When searching for an app this white box behind a few or all apps. Not sure as it disappears quickly. I consider it a bug as it shouldn't exist. I am pretty sure it's launcher related and not icon pack related. Please fix this

## Expected Behavior
No white background behind apps. It only does happen for half a second or so. 

## Actual Behavior

White background appears for half a second or so. 

## Steps to Reproduce

1. Have dark theme on
2. Open app drawer 
3. Search any letter eg F
4. A few apps consisting the letter F will have a white background for half a second 

## Environment

* Device: Galaxy S7 (Exynos)
* Android version: 7.0
* Launcher version: 1.1.0.1245
* Rom: Stock

**Comment by divadsn** [comment]
This happens only when app icons aren't loaded, therefore I don't see an issue here.

Also happens on the stock Pixel Launcher with dark substratum themes.
