### ISSUE TITLE
Noticeable lag when scrolling inside applications

### ISSUE THREAD

**Issue by Aodrulez** [Deletescape-Media/Lawnchair#717]
## Description
There's a noticeable lag in applications that have a scrolling UI like Instagram or 9gag for example. It's kind of interesting though as I don't see how a launcher would affect other app's interface. This is the only issue that's bugging me about Lawnchair. It's a great project & kudos to the time & effort you've put in! Much appreciated.

## Environment

* Device: Moto X Style
* Android version: 7.0 
* Launcher version: Lawnchair v1.0.1063
* Rom: Stock Moto X Style Nougat ROM

**Comment by divadsn** [comment]
I don't see how Lawnchair should have influenced the scrolling of other apps, have you some proofs?

**Comment by ghost** [comment]
Did you try using any other launcher and see if the lag persist? I don't see how a launcher can cause any lags on the apps.

**Comment by Aodrulez** [comment]
I wish I could prove it. But yea, it's definitely noticeable for me. Have tried default Google now launcher, original Pixel Launcher & had no lags. It might be a one-off case. I'll wait for the next release & let you know if it still persists. Thanks!

**Comment by divadsn** [comment]
See #687 about reasons why Lawnchair is consuming more RAM than the stock Pixel Launcher.
