### ISSUE TITLE
Status bar does not invert in app drawer

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#72]
BUG: When opening app drawer, the notification bar background doesn't change

**Comment by deletescape** [comment]
What phone are you using? Perfectly works for me!

**Comment by Dondrejohnson5** [comment]
Samsung Galaxy Grand Prime

**Comment by deletescape** [comment]
With which rom? Can you send me a screenshot of the app drawer?

**Comment by Dondrejohnson5** [comment]
![screenshot_2017-06-27-16-45-37](https://user-images.githubusercontent.com/29732079/27609202-237c0758-5b58-11e7-9afd-0c1a88a84ea7.png)

**Comment by deletescape** [comment]
Realllllly weird, status bar icons should invert the color in the drawer. Also that search text should have a different color.

Are you using a substratum theme?

**Comment by Dondrejohnson5** [comment]
What do you mean by substratum theme?

**Comment by YAJATapps** [comment]
Color invert came in marshmallow.
@deletescape Change the status bar color to grey or black in pre marshmallow

**Comment by deletescape** [comment]
Thanks for the info @YAJATapps forgot about that :joy:
