### ISSUE TITLE
option to choose a name when saving a backup

### ISSUE THREAD

**Issue by Silviobrittos** [Deletescape-Media/Lawnchair#723]
## Description
I like to use some icon packs, and while on other launchers i could save each of my homes with a particular name, in Lawchair by now it's impossible to choose a name for my backups.

By implementing this option will be possible to use differents presets of icon packs!

Of course, to do this the support for made and choose between various backups must be possible too.

**Comment by guest4711** [comment]
Yes, I missed it, too.  I can use the shell or a filemanager to rename the files to have more than one backup but I mostly forget to rename the old files before backing up. So I loose them...

**Comment by AxiK101** [comment]
That's very useful indeed

**Comment by LinuxLlama** [comment]
Added in Lawnchair V2.

**Comment by shubhchan** [comment]
@reC0D3D That's cool
