### ISSUE TITLE
Custom Google search bar widget

### ISSUE THREAD

**Issue by hongyuhuang** [Deletescape-Media/Lawnchair#725]
Can you please add a Google Searchbar that can be put anywhere in the homescreen because it is very limited when you only can put it on the top. Like how they have searchbar on the S8 or LGV30 where it is in the middle of the page. On Nova they have a widget you can use but on Lawnchair their is no Google Searchbar widget. I hppe you understand what I am saying and be able to add this feature.

**Comment by ellenswamy** [comment]
You could turn off the top bar, and just download a widget from the play store
