### ISSUE TITLE
Galaxy Tab 3 10.1 GT-P52xx problems with native libraries

### ISSUE THREAD

**Issue by xRaitor** [Deletescape-Media/Lawnchair#728]
See screenshots below

* Device: samsung gt-p5220
* Android version: 7.1.2
* Launcher version: 1.1.0.1258
* Rom: LinageOS 14.1

![screenshot_20170915-125232](https://user-images.githubusercontent.com/31986952/30478549-2b652980-9a1a-11e7-88ce-e9b6b5f43e86.png)
![screenshot_20170915-125451](https://user-images.githubusercontent.com/31986952/30478554-3271307a-9a1a-11e7-827c-4f1372fe6654.png)

Logcat:
[2017-09-15-13-41-31.txt](https://github.com/Deletescape-Media/Lawnchair/files/1306085/2017-09-15-13-41-31.txt)

**Comment by nyancrimew** [comment]
Read my comment on #693, there is a patch for this which has to be applied by the rom developer ( @MSF-Jarvis you still have the link?) which would allow text relocations

**Comment by msfjarvis** [comment]
https://github.com/halogenOS/android_bionic/commit/11ca6acca048f3e2d5af0474a0195320ed06aba0
