### ISSUE TITLE
Toggle for language changing

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#730]
So that we can choose what language will be used in settings menu and app titles and also the whole ui of Lawnchair.
That won't make us switch the system language to english..

**Comment by AxiK101** [comment]
So what's it gonna be? Whether you remove translations completely so that we have pure English ui or fix the language bug. It's so annoying, half ui in english, half in local language and changing after any action we do... plz do smth

**Comment by divadsn** [comment]
Do you have backport options enabled? If yes, turn them off, as they are **buggy and experimental** if you have read the option in the settings.

**Comment by AxiK101** [comment]
i disabled them, nothing change

**Comment by AxiK101** [comment]
@divadsn okokhere the funny thing. I think i might just found were the bug relays. When using a costume icon pack, language in both apps and settings mains correct (local), whenever i disable the icon pack..problem returns. I made many reboots, refreshing the Lawnchair, disable/enable all experimental settings, nothing, only the icon pack seems to correct the problem. Plz investigate and tell me if i am wrong. Thanks for your patience with me😋

**Comment by AxiK101** [comment]
Bug solution for mixed languages in the UI:
Settings -> Pixel UI -> Change icon shape -> None

Or use a costume icon pack!!
