### ISSUE TITLE
Essential PH-1 - draw behind notification bar

### ISSUE THREAD

**Issue by lounsberry** [Deletescape-Media/Lawnchair#735]
Essentially (pun intended), I'm just looking to see if anybody knows enough about getting the wallpaper to draw behind the notification bar. I _think_ that you have to get Essential themselves to whitelist the app. Not sure, however. I really like this launcher, so if anybody knows how, I'd appreciate it.

**Comment by wprater** [comment]
the developer should ask to be whitelisted. however, Im using the Layout app to apply the whitelist. working pretty well on my PH-1

https://play.google.com/store/apps/details?id=in.tsdo.elw

**Comment by fonix232** [comment]
I hate it when manufacturers hinder base functionality and require developers to get in touch with them to have it fixed. This is the worst thing they can do to Android.

We will get in touch with Essential to have Lawnchair whitelisted once we're on the Play Store.

**Comment by wprater** [comment]
I think it was mentioned in the [AMA](https://www.reddit.com/r/IAmA/comments/7048au/im_andy_rubin_cofounder_of_the_mobile_operating/) that Google requested they go the whitelisting route.

**Comment by wprater** [comment]
Here is what it looks like with full screen layout.  Would be great to slightly adjust the white space above the Pixel widgets.

![image](https://user-images.githubusercontent.com/10452/30847368-41e5993c-a2d6-11e7-9c70-415fe3b370fb.png)
