### ISSUE TITLE
LawnChair crashes when placing shortcut in folder

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#736]
## Description
If "backport shortcuts" is enabled, extra options will appear when long pressing certain apps. As expected, if we long press one of those options, a shortcut for them will be created to be dragged in the desired place. If we do this with the app in a folder, and we place the shortcut in the same folder, LawnChair will crash.

## Expected Behavior
Crashes are never expected, a shortcut should be normally created inside the folder.

## Actual Behavior
LawnChair will crash.

## Steps to Reproduce
Follow those steps to reproduce:

1. Make sure that you have the latest alpha version of LawnChair installed (1.1.0.1243)
2. Open LawnChair settings, press "behaviour" and make sure "Backport shortcuts" is enabled
3. Go to the home screen, open the drawer, scroll down to Gmail, long press it and drag it in an empty space of the screen.
4. Open the drawer, long press any app you want and place it on Gmail to create a folder.
5. Open the folder, long press Gmail, long press "Compose" and drag it next to Gmail.
6. Everything will crash.

## Environment
* Device: Moto G⁴ Play XT1602
* Android version: 6.0.1
* Launcher version: alpha 1.1.0.1243
* Rom: stock
* Build number: MPIS24.241-15.3-21

**Comment by TheShark27** [comment]
Here's an explanatory video:
https://youtu.be/TOAKbTJsREI

**Comment by nyancrimew** [comment]
I am able to reproduce this on 7.1.1 aswell.

**Comment by TheShark27** [comment]
It seems to happens with widgets as well, see #740.
There's something going on with folders.
