### ISSUE TITLE
Little graphical glitch in the app drawer

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#739]
## Description
In the drawer, if an app gets long pressed and dragged, there will be a little graphical glitch: the actual icon that gets dragged will act like normal, but the space where it got taken from won't remain blank, but the icon will reappear there for a fraction of second.

## Expected Behavior
That space should become blank, because the user should think that the app has been actually dragged.

## Actual Behavior
It seems like the icon dupes doing that, and it's kind of weird. Just a little glitch.

## Steps to Reproduce
1. Open the app drawer
2. Long press any app and start dragging it.
3. You will notice the same app briefly flashing in the place it got taken from.

## Environment
* Device: Moto G⁴ Play XT1602
* Android version: 6.0.1
* Launcher version: alpha 1.1.0.1243
* Rom: stock
* Build number: MPIS24.241-15.3-21

**Comment by Younes-L** [comment]
when the drawer is about to make place for the homescreen, the dragged icon reappears, as if the drawer was displayed the way it looks normally

**Comment by Younes-L** [comment]
can confirm it happens on GNL, and lawnchair is based on Launcher3.

**Comment by TheShark27** [comment]
Exactly. Doesn't happen on Oreo Pixel Launcher.

**Comment by divadsn** [comment]
This issue was fixed a long time ago with a newer build afaik, therefore I close this issue.

**Comment by TheShark27** [comment]
Is there a new alpha?

**Comment by nyancrimew** [comment]
This is not fixed yet, the issue described here is our workaround, because the icons started to disappear completely

**Comment by TheShark27** [comment]
Oh ok, well this is obviously better. Thank you

**Comment by divadsn** [comment]
@deletescape but isn't it intended when you pick up an app from the drawer that you are creating a duplicate? I mean the original icon will still be there, since it's in the app drawer.

**Comment by nyancrimew** [comment]
The duplicate should be created once the icon is dropped on the homescreen, we currently create it as soon as the icon is picked up, which looks kinda weird tbh.

**Comment by divadsn** [comment]
On the Pixel Launcher it's also not disappearing, but the app drawer closes so fast that you barely notice it.
