### ISSUE TITLE
Strange widget behaviour with folders

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#740]
## Description
With LawnChair shortcuts, creating widgets is easier. You just have to long press an app, tap "Widgets" and drag it where you want. But strange things will happen if you do that with a shortcut in a folder: the widget can be dragged inside the folder, and it will move apps inside of it to fit. When releasing, the moved app will disappear, leaving a blank space where the widget should be. It can be restored by restarting the launcher.

## Expected Behavior
The folder should close, allowing you to drag the widget inside the home screen.

## Actual Behavior
The widget does strange things, read the description.

## Steps to Reproduce
1. Make sure that you have the latest alpha version of LawnChair installed (1.1.0.1243)
2. Go to the home screen, open the drawer, scroll down to Gmail, long press it and drag it in an empty space of the screen.
3. Open the drawer, long press any app you want and place it on Gmail to create a folder.
4. Open the folder, long press Gmail, tap "Widgets", drag "Label" widget INSIDE the folder. The second app will move on top of Gmail to fit the new widget, which will disappear after releasing the finger.

## Environment
* Device: Moto G⁴ Play XT1602
* Android version: 6.0.1
* Launcher version: alpha 1.1.0.1243
* Rom: stock
* Build number: MPIS24.241-15.3-21

**Comment by divadsn** [comment]
For me it's not possible to recreate your issue, also it's not happening on the Oreo Pixel Launcher.

Edit: When doing it another time, Lawnchair just crashes.

**Comment by TheShark27** [comment]
Maybe that’s a problem with the OS. If you want I can link later a video that includes it.

**Comment by TheShark27** [comment]
Now it crashes when I do that.

**Comment by TheShark27** [comment]
Here's the link for the video of the issue:
https://youtu.be/f8pfmAtUOlw

**Comment by jise** [comment]
Cannot recreate your issue on Nexus 5X 8.1.0 and Xiaomi Mi A1 7.1.2 with Lawnchair version 1.1.0.1730.
