### ISSUE TITLE
Little bug when creating widgets from shortcuts

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#741]
## Description
With LawnChair shortcuts, creating widgets is easier. You just have to long press an app, tap "Widgets" and drag it where you want. Sometimes the widget freezes and you can't drag it, so you have to release the finger and long press again to move it.

## Expected Behavior
You should be able to drag it without any problems.

## Actual Behavior
The widget sometimes freezes.

## Steps to Reproduce
1. Long press Gmail
2. Select "Widgets"
3. Drag any widget where you want.
4. SOMETIMES it will freeze

## Environment
* Device: Moto G⁴ Play XT1602
* Android version: 6.0.1
* Launcher version: alpha 1.1.0.1243
* Rom: stock
* Build number: MPIS24.241-15.3-21

**Comment by divadsn** [comment]
>SOMETIMES

Like on the stock Pixel Launcher too.
