### ISSUE TITLE
Google search suggestion bar covered with keyboard.

### ISSUE THREAD

**Issue by aromiko** [Deletescape-Media/Lawnchair#742]
SCREENSHOT FROM LAWNCHAIR
![screenshot_20170924-001409](https://user-images.githubusercontent.com/25784147/30774986-8967db82-a0bd-11e7-98a0-c51d95392aef.png)

SCREENSHOT FROM PORTED STOCK PIXEL OREO LAUNCHER
![screenshot_20170924-001834](https://user-images.githubusercontent.com/25784147/30775039-fee56b26-a0be-11e7-9e56-5156103669b5.png)

## Description

When searching with the home google icon , the google words/tags suggestion bar just above the keyboard doesn't align right and are overlapping

## Expected Behavior

The suggestion bar should be aligned properly above the keyboard.

## Actual Behavior

The keyboard overlaps the suggestion bar of the google search. I tried this with the ported stock pixel oreo launcher and it works properly. I attached screenshots for reference.

## Steps to Reproduce

1. On the home screen, tap the google icon
2. The search bar will appear and the keyboard as well
3. There you can see that the suggestion bar is covered with the keyboard

## Environment

* Device: Oneplus 3T A3010
* Android version: 7.1.1
* Launcher version: v1.0.1063
* Rom: Stock Oxygen OS 4.1.7

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
Seems more like an issue with your device than an issue with Lawnchair.

Also, I don't get that suggestion bar as well, so seems like you are using beta software, which won't be covered and supported here.

**Comment by divadsn** [comment]
Seems more like an issue with your device than an issue with Lawnchair.

Also, I don't get that suggestion bar as well, so seems like you are using beta software, which won't be covered and supported here.
