### ISSUE TITLE
Mi A1 style search bar

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#743]
Not sure if this is possible to add but having a Mi A1 styled search bar would be a nice feature to add!

![mia1_home](https://user-images.githubusercontent.com/29968331/30776960-fe31d836-a064-11e7-8d54-a6d8feb95ccd.png)

**Comment by TheShark27** [comment]
It would be nice! Android One / Essential Phone search bar.

**Comment by silentgurdian** [comment]
It's the search bar widget for the search lite app google released recently. You can download it on apkmirror.

**Comment by LinuxLlama** [comment]
@silentgurdian That one is different than the one on the Mi A1. The Mi A1 has an animation for a quick Google search when tapped and looks slightly different.
