### ISSUE TITLE
[Feature request] Screens to left and right and custom blur image

### ISSUE THREAD

**Issue by theothertored** [Deletescape-Media/Lawnchair#746]
I'm not using the Google Now page, and Lawnchair is for me a great base for KLWP.
Having that said, I would love to have a way to select my homescreen and be able to access other screens to the left and right.
Another thing is blur. No launcher can blur a live wallpaper, I know it, but a lot of people use an image as a base for their prestets. So, it would be super awesome to have a way to provide an image for Lawnchair to blur. What I mean by this, is you could get the drawer to be blurred  using not the live wallpaper, but your provided image. Ideally, it would be great if the picture could be scrolled n stuff, but that's not a necessity.
Thanks! ^–^

**Comment by theothertored** [comment]
Oh, and also, there would be no need to provide a custom image, if the drawer opening would somehow be registered by KLWP, maybe by vertical scrolling? Idk if that's possible, but hey :D

**Comment by Younes-L** [comment]
check #702
