### ISSUE TITLE
2lines app titles get cropped

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#750]
**BUG** 
In app drawer when enabling the new 2line style for app titles, the second line in some characters is getting cropped. Grid size is set in auto for both columns and rows. Only when changing to manual row number this is fixed BUT then you get a pretty big space between rows. In desktop is ok.

**DEVICE SPECS:** 
Sony Xperia XA Ultra, Stock 7.0
Lawnchair 1.1.0.1265
![](https://i.imgur.com/bQUlNPJ.png)

**Comment by Rawi666** [comment]
What text and icon scalling percentage do you use?

**Comment by AxiK101** [comment]
Thus mostly happens in costume dpi (pic is 340dpi, also tested in others like 390). Icon and text scaling isn't a matter, it happens in all different combinations. Only in stock dpi (360) everything seems ok

**Comment by Rawi666** [comment]
Can you check if this version fixes this issue?
https://www.mediafire.com/file/zbz4y8ihg2ntx3i/app-debug-textscalling.apk
It's latest alpha code + one commit that is in PR state

**Comment by AxiK101** [comment]
v1.1.0.1281 made the problem worst. Icon and title got a bigger gap and in result titles are cut-off also in stock settings (100% scale and 360dpi)
![](https://i.imgur.com/wNs7Agr.png)

**Comment by Rawi666** [comment]
And this happens only if you increase your phone-wide DPI higher than your default (367) ?
EDIT: aaa it hapens also on default :(
Do you have any other system (vendor) themes installed? Because I can see the font is completely different than the default one in launcher.
Is this screenshot sent when using 367 dpi or other?

**Comment by divadsn** [comment]
@Rawi666 if you are not able to fix or want to revert, let me or someone else know.

**Comment by Rawi666** [comment]
The fix was needed anyway as otherwise it was messed up even on emulator with 360dpi and I've also noticed that there were no bottom margins in last row in app drawer on my Huawei P10 (stock dpi, 100% scale).
I think that this issue is something else.

**Comment by Rawi666** [comment]
I'm unable to reproduce it on 6" emulator 1080p (as Xperia XA Ultra) :(
Here is what I see in different conditions when changing phone-wide DPI and in-app scaling.
On max phone dpi and max scaling there is some text clipped but on Xperia you have strange margin between the icon and the label.
![comparison](https://user-images.githubusercontent.com/5843854/30809620-a3b22ba0-a202-11e7-99b2-031acd9dbbfd.jpg)

**Comment by AxiK101** [comment]
@Rawi666 the font is the stock one from xperia or Lawnchair. Not using any third party fonts, not rooted btw

**Comment by AxiK101** [comment]
So is this only happening on 6 inches screen with 1080p res?

**Comment by Rawi666** [comment]
Hard to say. I just cannot reproduce it. It's working fine on my Huawei P10 (default DPI), Nexus 5 (default DPI) and on emulator 6" (same DPI as your xperia). All in 1080p.
What settings do you have in Phone Settings->Display->Font Size and Display Size? Is it default everywhere? If not try to set to default and then change in-app scale.

**Comment by AxiK101** [comment]
@Rawi666 everything is set to default. I reverted back to 1.1.0.1265 as it handles way better this problem on default settings for now

**Comment by Rawi666** [comment]
@AxiK101 one more question. If you set up explicitly 4 columns and 4 or 5 rows in app drawer - does it help in 1.1.0.1265?

**Comment by AxiK101** [comment]
@Rawi666 By default i set 100% icon+label scale and use 4columns + 4rows and its good, no problem. If i set 4columns + 5rows labels are a bit cropped. If i change also scale in icons and/or labels also they messed up. So only default settings work good for me, no costuming is bug-free. All that in default 360dpi

**Comment by Rawi666** [comment]
Could you please test this version. It's the latest alpha with text fix.
http://www.mediafire.com/file/3gic7tbaztkw0en/app-debug-750fix.apk

Please do the following
1. Export your current settings (settings and database)
2. Uninstall your current version
3. Install this debug version
4. Import your previous settings (settings and database)
5. Go to Settings->General and you'll notice 'Icon padding scale' slider (in the Drawer section)

Please let me know if it helps if you decrease the slider and to what value you need to decrease in order to look good on your device.

**Comment by AxiK101** [comment]
@Rawi666 ok, thats the best settings combo i like, icon+label at 100% and padding scale at 80%, at 360dpi. If i increase the number of rows in app drawer then i must decrease the label size or else they get cropped. Not tested though with different icon sizes or with different screen dpis. But, if you add this icon label scale slider in next release update it whould be nice. That way anyone will be able to adjust their settings as they look best in their devices.
![](https://i.imgur.com/IRd59nI.png)
![](https://i.imgur.com/2kx87PX.png)

**Comment by Rawi666** [comment]
@AxiK101 thanks and sorry for the inconvenience!

**Comment by AxiK101** [comment]
@Rawi666 no problem, I'm glad that you managed to solve it😉
