### ISSUE TITLE
Shortcuts aren't working and notification badges also.

### ISSUE THREAD

**Issue by rj-raghavjoshi** [Deletescape-Media/Lawnchair#752]
Shortcuts of the apps like play store, YouTube, play music aren't working when long pressed.

There are some more problems faced by user's for shortcuts. The shortcuts also doesn't fits the screen and it's annoying for Android below Nougat.

I am getting many requests from Google+ community regarding notification badges as in many devices, they aren't working. 

Here are some reports:-
https://plus.google.com/104939338720362439476/posts/dQLQnP5KYBk

https://plus.google.com/106443821819602558813/posts/R3ypRpzyfpg

https://plus.google.com/102226929318025369771/posts/SsJ8TM4hSYZ

https://plus.google.com/+shrikantrapelli/posts/4pE6i4CwLxF

I think you will look on some reports arose by me. Please look into the matter.

**Comment by divadsn** [comment]
Thanks, but without any details and logcat it won't help us at all, so please create seperate issues or use search if these have been already reported.

**Comment by divadsn** [comment]
Also, I can confirm that notification badges are working fine on my Redmi Note 3 running MIUI 8/9 stable/beta (6.0.1) and my Honor 4X running EMUI 4.0 (6.0), so it mostly has to do with wrong battery settings in these UIs.
