### ISSUE TITLE
Can't create shortcut-style widget without a label

### ISSUE THREAD

**Issue by jack980517** [Deletescape-Media/Lawnchair#753]
## Description

My naming of "shortcut-style widget" may be a bit weird. I'm referring to something that appears in the widgets selection, has a size of 1x1, and behaves like a shortcut when created: it has a text label and cannot be resized.
This only happens for Terminal Emulator (jackpal.androidterm) but not anything else that I have tested.
This should be considered a bug of Lawnchair, because it works in the AOSP stock launcher and Nova Launcher.

## Expected Behavior

The shortcut should appear at the location I specified.

## Actual Behavior

After configuring the shortcut, it did not appear, and the location that I specified indeed has nothing added to it, as I can freely move other shortcuts onto it. (I also checked launcher.db to confirm this.) The wait time after configuring the shortcut before the launcher exits out of "edit mode" is also slightly longer than usual.

## Steps to Reproduce

1. Long press at the home screen
2. Choose widgets
3. Find "Term Shortcut" under "Terminal Emulator"
4. Drag it onto a home screen
5. Enter anything (for example, `cd /`) into the arguments text box; or just leave everything blank. Press "OK".
6. No shortcut is created.

## Environment

* Device: OnePlus 3, codename "oneplus3"
* Android version: 7.1.1
* Launcher version: 1.0.1063
* Rom: OxygenOS Open Beta 15

**Comment by Rawi666** [comment]
From what I can see you cannot create Android Terminal shortcut if you don't provide a Label for it.
The same behavior is on my stock Huawei Launcher - you need to provide command and a label to the widget.

**Comment by jack980517** [comment]
Strange. I was sure that I put a label there... But it was as you said. No label, no shortcut created. This wasn't the case on Nova launcher though. Not sure if it could still be considered a bug...

**Comment by Rawi666** [comment]
I think it's app-related thing as on Huawei Launcher I have exactly the same behavior.
I don't have Nova launcher to test.
