### ISSUE TITLE
Option to hide Lawnchair icon from app drawers

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#757]
When using other launchers i whould prefer to hide Lawnchair icon from the app drawer, especially for launchers such as Pixel or Google Now that can't hide icons.
I would appreciate it, thanks

**Comment by divadsn** [comment]
I don't personally see the point, but I think I can add a switch in Debug settings.

**Comment by AxiK101** [comment]
@divadsn thanks dev

**Comment by AxiK101** [comment]
@divadsn when you consider to add that toggle sir?
