### ISSUE TITLE
Change padding size on dock

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#759]
If somebody asks for a feature request on Google+, I'll post them here from now on. This has been forwarded from Luke Stonbraker on Google+: 

Could you add an option to reduce the amount of padding and icon size on the dock?

**Comment by nyancrimew** [comment]
The dock icon size can be adjusted already

**Comment by LinuxLlama** [comment]
@deletescape I knew that. I just copied the full message from Google+.
