### ISSUE TITLE
App freezes when picking up icons from the drawer

### ISSUE THREAD

**Issue by tstackhouse** [Deletescape-Media/Lawnchair#76]
Running the latest travis build from today (198), when I pick up an icon in the drawer the app locks up for up to several seconds before I can see the desktop, and after I place the icon up to a few more seconds pass before the active desktop zooms back in.

I'm running a stock Galaxy S6 with the latest Nougat update (7.0.1 I believe).  I can try to take a screen recording if that helps.

Thanks for making this!

**Comment by deletescape** [comment]
Noticed this issue myself too, should be able to fix it

**Comment by snowboardergrun** [comment]
Here to on a Nexus 6p Android 7.1.2

**Comment by baruchin** [comment]
This behaviour isn't exclusive to the apps drawer, it also happens in homepage.

**Comment by yung40oz84** [comment]
I can confirm this. DU ROM, Pixel XL.

**Comment by Kamin4ri** [comment]
`07-05 23:42:52.888 22388 22397 E System  : Uncaught exception thrown by finalizer
07-05 23:42:52.891 22388 22397 E System  : java.lang.IllegalStateException: The database '/data/user/0/ch.deletescape.lawnchair/databases/google_app_measurement_local.db' is not open.
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteDatabase.throwIfNotOpenLocked(SQLiteDatabase.java:2196)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteDatabase.createSession(SQLiteDatabase.java:367)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteDatabase$1.initialValue(SQLiteDatabase.java:86)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteDatabase$1.initialValue(SQLiteDatabase.java:85)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.ThreadLocal.get(ThreadLocal.java:150)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteDatabase.getThreadSession(SQLiteDatabase.java:361)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteProgram.getSession(SQLiteProgram.java:101)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteQuery.setLastStmt(SQLiteQuery.java:96)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteQuery.close(SQLiteQuery.java:111)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteCursor.close(SQLiteCursor.java:300)
07-05 23:42:52.891 22388 22397 E System  :      at android.database.sqlite.SQLiteCursor.finalize(SQLiteCursor.java:366)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
07-05 23:42:52.891 22388 22397 E System  :      at java.lang.Thread.run(Thread.java:761)`

Maybe this has to do with the lagging? Lawnchair tries to access such database quite a few times. Especially when placing/dragging icons.

**Comment by suphon-t** [comment]
Fixed with 9c391064
