### ISSUE TITLE
DPI settings problem.

### ISSUE THREAD

**Issue by silentgurdian** [Deletescape-Media/Lawnchair#760]
So I reduced my default dpi from 320 and tried out 240,280 & 300. I primarily did this to fix the shortcuts getting cut out. To that extent it worked. Problem is weather in the google widget shrinks disproportionately. Attaching ss below.
![screenshot_2017-09-26-13-00-36](https://user-images.githubusercontent.com/30438401/30848162-ddcc8de4-a2bb-11e7-9736-efe275194986.png)

**Comment by divadsn** [comment]
Use issue template, kthxbye.
