### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#761]
## Description
When system language is set to Dutch the settings of lawnchair are still English

## Expected Behavior
The settings to be dutch

## Actual Behavior
The settings are still english

## Steps to Reproduce

1.set system language to dutch
2.open settings of lc

## Environment

* Device: Moto g4 plus
* Android version: 7.0
* Launcher version:1.1.0.1285
* Rom:stock

**Comment by AxiK101** [comment]
try to disable icon costume settings, set to none, it's probably the localization bug i reported days ago..

**Comment by elsondione** [comment]
I'm also having the same problem. The configuration menu after 1.1.1.1285 did not translate to my native language which is Portuguese, it is only in English, there is a problem with the translation. I have already updated to the latest versions and continue with the same problem.

**Comment by nyancrimew** [comment]
We have tracked down the source of this bug and it should be fixed soon
