### ISSUE TITLE
Problems in the new alpha (Circular icons)

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#763]
## Description
I have set "use Pixel circular icons where possible", but after the update to alpha 1.1.0.1285 normal icons are shown.

## Expected Behavior
Circular icons should show up, as normal. They used to do so in the previous versions.

## Actual Behavior
Normal icons are shown.

## Steps to Reproduce

1. Go in settings, Pixel UI, show Pixel icons. Maybe on other devices they will show up.

## Environment
* Device: Moto G⁴ Play
* Android version: 6.0.1
* Launcher version: alpha 1.1.0.1285
* Rom: stock
* Build number: MPIS24.241-15.3-21

**Comment by Rawi666** [comment]
There isn't such an option 'use Pixel circular icons where possible'.
Go to Pixel UI->Change icon shape and select 'Circle'
![screenshot_20170926-182201](https://user-images.githubusercontent.com/5843854/30871694-fc5c3300-a2e7-11e7-830a-da81de2ff418.png)

**Comment by TheShark27** [comment]
That was the description actually, the title of the option is "Use Pixel Icons". I have enabled it by the way, but they don't show up.

**Comment by TheShark27** [comment]
https://imgur.com/gallery/TF7yE

**Comment by Rawi666** [comment]
aaa it's 6.0. sorry my bad

**Comment by TheShark27** [comment]
Yep, I'm still on Marshmallow. I don't have that option

**Comment by Rawi666** [comment]
Could you check if this app fixes your issue http://www.mediafire.com/file/93s5kn9es4nbarf/app-debug-marshmallowfix.apk ? It's the latest alpha with the fix

**Comment by TheShark27** [comment]
Thank you! Unfortunately I'm unable to install it (at the end of installation it says "app not installed").

**Comment by Rawi666** [comment]
This is a debug version. Export your settings. Uninstall existing version. Install this test version and let me know. Finally you can uninstall test version and install release version and import the settings

**Comment by TheShark27** [comment]
Sorry, how can I export my current layout? Export database?

**Comment by Rawi666** [comment]
yes, export database and settings. and finally inport settings and database

**Comment by TheShark27** [comment]
And once exported, where is their location? When I tap "import" it just say "success!"

**Comment by Rawi666** [comment]
In 'Documents' directory

**Comment by TheShark27** [comment]
Ok, thanks. How can I import them though? Sorry, I'm new to this

**Comment by TheShark27** [comment]
I imagine they are automatically imported directly from the directory, right?

**Comment by Rawi666** [comment]
By clicking import. Yes, they are read from the 'Document/Lawnchair' directory

**Comment by Rawi666** [comment]
Uninstalling the app won't remove Document/Lawnchair directory so no worries

**Comment by TheShark27** [comment]
Thank you, it's fixed! If you want I can send you a screenshot

**Comment by TheShark27** [comment]
https://imgur.com/gallery/09v2O

**Comment by TheShark27** [comment]
Can I close it?

**Comment by Rawi666** [comment]
I think @deletescape will close it when he merges #764 :)

**Comment by TheShark27** [comment]
Ok, thanks for the help :)
