### ISSUE TITLE
Notifications count aren't showing 

### ISSUE THREAD

**Issue by Xmagu** [Deletescape-Media/Lawnchair#765]
The launcher doesn't show count of notifications. 

## Expected Behavior

Please, help me fix. 
Gmail, WhatsApp, Instagram nothing work. 

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by fonix232** [comment]
The issue template is not there for you to ignore. Please use it.
