### ISSUE TITLE
Unread Badges except the dots

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#767]
It whould be nice to support unread badges for missed notifications except for dots, this little guy do the trick: LauncEnr, it's an app from playstore. It should be added as an alternative way of showing missed notifications.
![](https://i.imgur.com/tKTyJh0.jpg)
![](https://i.imgur.com/aURXzYN.jpg)

**Comment by callmemulo** [comment]
what the name of the app again? LauncEnr? can't find it.

**Comment by AxiK101** [comment]
https://play.google.com/store/apps/details?id=com.enrico.launcher3

**Comment by callmemulo** [comment]
awesome. thanks dude.

**Comment by mjeshurun** [comment]
For me, notification dots aren't showing at all. 
Anyone else don't see them?
I gave Lawnchair notification permissions, but they still aren't showing.

**Comment by AxiK101** [comment]
@callmemulo is it enabled from Lawnchair's settings?

**Comment by callmemulo** [comment]
@AxiK101 yep. Settings -> General -> Notification badges and preview. Turn on the notification access for Lawnchair. In case not working, you can try disable and re-enable it again.

@mjeshurun  you can try disable and re-enable it again. for me, most of time it did shown dots. just put in mind that this is in beta stages, so bugs are expected.

**Comment by callmemulo** [comment]
several option also available.
1. Reboot
2. Turn off, pull the battery. Press power button and wait 5-10 seconds.
3. Go to the recovery mode, clear cache & dalvik.
4. Clear Lawnchair cache and data & reboot.

Most of time No.2 work. At least for me. Cheers~

**Comment by hydhyd** [comment]
Didn't want to open another issue since it's somewhat related (though totally dig the idea OP suggested).

Some icons have the "unread" circles, some don't. For instance, GMail works alright; WhatsApp doesn't.

Running 1.1.0.1371 off XDA alpha channel.

Any input? Thanks.

E: Obviously did all the reboot/remove cache & dalvik thing.

**Comment by divadsn** [comment]
@hydhyd update your Lawnchair, you're far too behind, last stable PS release is 1.1.0.15xx

**Comment by hydhyd** [comment]
@divadsn and here I thought XDA app rep stood for latest and greatest (at least, ref Lawnchair). Installed from Google Play, can't test at the moment unfortunately, will continue tomorrow.

Thanks.
