### ISSUE TITLE
S8 blurred dock

### ISSUE THREAD

**Issue by hosseintorkzaban** [Deletescape-Media/Lawnchair#768]
When you enable blur on s8, dock has a line unblurred that shows wallpaper without blur overlay,fix it pls

**Comment by SovsOgKartofler** [comment]
Please provide a screenshot and basic information about your setup (OS version, app version, etc.)

**Comment by hosseintorkzaban** [comment]
Android 7.0.1
Latest alpha version of app
SM-G950F device

On 27 Sep 2017 at 1:10 pm, <Simon Rosted <notifications@github.com>> wrote:

Please provide a screenshot and basic information about your setup (OS
version, app version, etc.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Deletescape-Media/Lawnchair/issues/768#issuecomment-332467309>,
or mute the thread

**Comment by gitter77** [comment]
Restarting the launcher from the debug option  should fix this.It worked for me.

**Comment by hosseintorkzaban** [comment]
Didn't work for me...

**Comment by Zetphren** [comment]
Hi,

can confirm this Problem, also in Beta Channel.
I've written a mail to "support@deletescape.ch" on September the 8th mentioning the problem.
Didnt get an answer though.

I've attached  a new screenshot with a brighter wallpaper to make it more visible. Even though it doesnt seems like much but on the curved screen it looks way more "wrong".

hope this Helps.

so long

Zeto

![2_screenshot_20170908-184119](https://user-images.githubusercontent.com/32359488/30963204-e70e8744-a44c-11e7-9079-1e386ed6b520.png)
![asdfasdf](https://user-images.githubusercontent.com/32359488/30963342-66e10b0e-a44d-11e7-84b9-b99586cd2d86.jpg)

**Comment by TheBITLINK** [comment]
This is happening in my device as well, but the line is much more noticeable (maybe due to the lower resolution?)
![screenshot_20180405-114010](https://user-images.githubusercontent.com/3434300/38376332-533f36da-38c6-11e8-9c4a-6f667bf535e7.png)

**Comment by bohrabhijeet** [comment]
Are you using the stock dpi? Or a custom one?

**Comment by TheBITLINK** [comment]
Custom

**Comment by bohrabhijeet** [comment]
@TheBITLINK Please try the stock dpi and report if the issue persists.

**Comment by hosseintorkzaban** [comment]
Guys, I'm using stock DPI!

**Comment by TheBITLINK** [comment]
Can confirm the issue is still present with the stock DPI
![screenshot_20180405-150902](https://user-images.githubusercontent.com/3434300/38386683-6b02866a-38e3-11e8-81a9-27b8f8d9b1f1.png)
