### ISSUE TITLE
Center wallpaper when only 1 page not actually centering

### ISSUE THREAD

**Issue by ack154** [Deletescape-Media/Lawnchair#770]
## Description

Using the "Center wallpaper when there is only one page" option in the 1.1.0.1285 alpha build - but it does not center my wallpaper. It moves to the left.

Oddly, I think it WAS working yesterday when I first installed the alpha build but today has gone to not centered. I have tried restarting Lawnchair multiple times. Also restarted my phone. I have also tested with multiple wallpapers - have included the one I'm currently using below.

I mention this below as well but I do have the Google Now page turned on - my only guess on this behavior is that it is counting Google Now as a page maybe? And if that's the case, I'd recommend it not  do that. I generally wouldn't count the Google Now page as a homescreen page, it's just a separate thing. So I only have one homescreen page of icons, plus the Google Now page.

## Expected Behavior

The wallpaper should automatically center when turning the option on and only using one home screen.

## Actual Behavior

The wallpaper moves to the left when turned on and centers when turning off.

## Steps to Reproduce

1. Selecting Wallpapers from Lawnchair menu and choosing a photo from my Photos.
2. Turning on Center wallpaper option in General settings of Lawnchair.
3. Wallpaper is not centered.
4. Turned off Center wallpaper option - wallpaper shows centered.

Wallpaper I'm using: https://i.imgur.com/R37LuJw.jpg
Screenshot when option is "on": https://i.imgur.com/wHKRdP2.png
Screenshot when option is "off": https://i.imgur.com/sbXPrNT.png

Like I said, I only have one home screen, but DO have the Google Now page enabled.

## Environment

* Device: Essential PH-1
* Android version: 7.1.1
* Launcher version: 1.1.0.1285
* Rom: Stock, not rooted

**Comment by gedling** [comment]
Same problem on S8+ on 7.0. with Muzei. Even with centered wallpaper on Google now disabled it scrolls to the left. Would be great if there was a fix.
