### ISSUE TITLE
Dynamic calendar icon broken

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#772]
Not sure when this started but I think it stated today. Google calendar icon no longer shows day of the month, just the default 31

**Comment by Rawi666** [comment]
Settings->Pixel UI->Change icon shape->Circle.
AFAIK google calendar icon changes its icon each day only if circular icons are selected.
Previously circular icons were selected by default and that's all.

**Comment by AxiK101** [comment]
@Rawi666 thats not correct. For me the calendar icon shows the daily number of the day even without enabling circular icons. Also the broken part in icon theming for me is the 2 options in icon masks, the "do not change" and also the "none" option do the exact same thing, nothing, more precisely. They revert icons to original none circular style. In past releases if i remember correct the "do not change" option had a different activity, it whould enable circular icons only for apps tha supported it. Now it does nothing.. there is still the language bug when choosing one of these options

**Comment by Rawi666** [comment]
Do not change in previous versions worked in the same way as Circular.
Now it's as follow:
Do not change - use AOSP icons but with original shape
None - use standard icon from your ROM
Circular - pixel icons in circles

Yes, the naming is a bit confusing.

If you are on AOSP based rom then Do not change and none will work the same way. On other devices where ROM manufacturers use different icons then you'll notice different icons.

As for dynamic calendar icons goes - this is strange as on my phone it worked only on circular icons. I may take a look at this. It would be usefull if you provide me any previous version where dynamic calendar icons worked on non circular icons

**Comment by shuli81** [comment]
@rawi666 thanks! chaging to circle fixed it. it used to work properly on do not change. as I said I'm not sure when this changed but I highly doubt it was more than a few versions back. may have even been one of today's updates as I saw there were some changes relating to icon shape.

**Comment by Rawi666** [comment]
It definitely was working previously on 'Do not change' as this setting previously generated Circular icons as well.
Or did you have original shapes and calendar icons was dynamic on original (non-circular) icons?

**Comment by shuli81** [comment]
I  never changed this setting before. always had it on do not change. gave me round icons and dynamic calendar worked. I'm running Pure Nexus.

**Comment by Rawi666** [comment]
ok, so no bug here, only confusion :)
