### ISSUE TITLE
Push notification stop working after a while

### ISSUE THREAD

**Issue by callmemulo** [Deletescape-Media/Lawnchair#773]
## Description
 No incoming messages on messaging app especially WhatsApp, only got the messages if I open the app. Just imagine no incoming messages or notification for a day then you know something is wrong. Until you open the app (Messaging, WhatsApp, etc..), then you realize it is too late already. This doesn't happened when I switched to another launcher. I'm rooted, one thing I did is I push Lawnchair to system\app. Notification access for LC enabled, reboot, clear dalvik cache, clear LC cache and data, I did them all. It work for a while then go silence again for whole day. I need guidance from you guys!

## Steps to Reproduce
I don't have the screenshot since there is nothing to show. 

1.
2.
3.
4.

## Environment

* Device: Lenovo k10e70
* Android version: 6.0.1
* Launcher version: 1.1.0.1285
* Rom: Stock

## Logcat

```

**Comment by callmemulo** [comment]
It work now after hard reset, except for WhatsApp. Notification dot only show up if there are more than **1** incoming message from one contact/group. For example, if there are 1 message each from 5 of my contacts/groups, the dot will not show up. But if one of them send 1 more message then the dot will work as usual. Can someone confirm this? Is this a bug or it just me going crazy?

**Comment by nyancrimew** [comment]
@callmemulo the whatsapp bug is a known bug and we currently have no idea why it is happening

**Comment by callmemulo** [comment]
@deletescape  oic i think this issue should be close for now since its only WhatsApp and i still can see notification icon on status bar. i don't want to move to another launcher just because of dot not working since Lawnchair suits my phone well. thanks for replying and keep up the good work bro.
