### ISSUE TITLE
Some long press app shortcuts are absent, and others does not work properly

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#774]
Some long press app shortcuts, like Google Maps' (Home, Work) aren't backported to Marshmallow. Others, like Compose (Gmail app shortcut) or New conversation (Google Messages app shortcut) does not work properly and link to inbox instead to new email/new message as it should be.

**Comment by TheShark27** [comment]
You're right, it also happens to me in alpha 1.1.0.1300

**Comment by AxiK101** [comment]
These aren't gonna work on lower <7.1 system version.

**Comment by ghost** [comment]
In Nova Launcher, Action Launcher and Evie Launcher the mentioned app shortcuts are present and work properly on Android 6.0.1.

**Comment by LinuxLlama** [comment]
@carloabi Backporting shortcuts is a difficult task especially on lower version of Android and expect them to not work. Sure, other launchers can backport them but they still can't backport all.

**Comment by ghost** [comment]
I'm aware that backporting app shortcuts to lower versions of Android can be very difficult and I know that many shortcuts will never work unless the Android version is 7.1 or higher. In fact, only the shortcuts of some Google apps and a few third party apps installed on my device (like neutriNote or Texpand) work (with Lawnchair, and also with Nova, Action Launcher and Evie Launcher). But all the shortcuts mentioned in my first comment work properly with the mentioned launchers under Marshmallow, so I think that it shouldn't be too difficult backporting them.
