### ISSUE TITLE
Date translation in Polish language

### ISSUE THREAD

**Issue by falafle** [Deletescape-Media/Lawnchair#781]
As you can see on my screenshot below with disabled weather date says "29 września" which makes sense but when I enable weather it changes to "września 29" which is incorrect and doesn't make sense. Also I tested stock pixel launcher and it is fine there.
![bug](https://user-images.githubusercontent.com/8997356/31016830-9852c464-a526-11e7-8d72-57ea4b3d54c2.jpg)

* Device: Moto X Style
* Android version: 7.0
* Launcher version: 1.0.1063
* Rom: stock

**Comment by nyancrimew** [comment]
This has been fixed on Crowdin and will be changed in our builds as soon as new Translations are imported
