### ISSUE TITLE
Add App Suggestions in the drawer

### ISSUE THREAD

**Issue by hugwalk** [Deletescape-Media/Lawnchair#782]
As the title said, the App Suggestions may be convenient for some people like me, It'd be great if this feature will get in this launcher.

**Comment by AxiK101** [comment]
😂😂😂 can't wait for a dev response to that, no offense, i want it too

**Comment by theandroidenthusiast** [comment]
Same here

**Comment by guest4711** [comment]
See #890

**Comment by NoobTW** [comment]
Need this, too.
