### ISSUE TITLE
Reflect option for dock.

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#783]
This has been forwarded over from Google+ from the Lawnchair Community. Original post: https://plus.google.com/110653719783033896347/posts/V7EbgfB5wXJ?fscid=z12uvxsxslq5gt1hc04ci32akoith3iwshc.1506670097561905

"Please Add Dock Icons Reflection effect on next update thanks ☺️"

![screenshot_2017-09-29-12-57-10](https://user-images.githubusercontent.com/29968331/31037986-f65476c8-a528-11e7-9446-d6b795e13cbe.png)

**Comment by RikKoedoot** [comment]
it's a nice option to have, but it's very not material

**Comment by LinuxLlama** [comment]
@rickkode I agree, I was hesitant to post this because it's not that material but I did anyway since a few people seemed to want it.

**Comment by nyancrimew** [comment]
Not sure if this fits into our concept :thinking:

**Comment by fonix232** [comment]
I'm pretty sure it does not fit into any piece of MDL.
