### ISSUE TITLE
Google Bar Custom Widget

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#784]
Ok, now it's official, Google brings customization on search widget, finally. This is the footage from Android authority:
https://youtu.be/JN9UwBwECOk

The question is, can you add it to Lawnchair sooner??

**Comment by LinuxLlama** [comment]
Most likely not. Lawnchair can't control what Google does. The search bar comes from a modified Google APK.

**Comment by AxiK101** [comment]
yes that's logical, but i was wishing you could make a custom widget that copys the original..

**Comment by LinuxLlama** [comment]
@AxiK101 Oh I see. Yeah, it is a nice idea! By the way, it's custom, not costume.

**Comment by AxiK101** [comment]
@Treemindr😂😂😂 you get the point though
