### ISSUE TITLE
[Feature Request] Redesigned Pixel Launcher spotted at Google I/O 2017

### ISSUE THREAD

**Issue by elsondione** [Deletescape-Media/Lawnchair#786]
The big change with this launcher is the new Google Search UI. Rather than a pill-shaped widget sticking out of the side of the display, this new Pixel Launcher has a full-width gray bar that’s sitting between the docked apps and the on-screen navigation buttons. And managed to capture it in a couple of brief videos:

https://www.youtube.com/watch?v=RDeKv5RlCt0

https://www.youtube.com/watch?v=jsRVrsauPf8

https://pbs.twimg.com/media/DLJsZPxXkAAVGn1.jpg:large

https://www.tudoemtecnologia.com/wp-content/uploads/2017/10/PIxel-2-e-XL-2.png

Can you add it to Lawnchair in the future?

**Comment by AxiK101** [comment]
This version probably will come with Pixel 2, or not... we will find out in a couple of days

**Comment by fon321** [comment]
Would love to see this!

**Comment by theandroidenthusiast** [comment]
Well the Pixels have been announced. There are videos which show the Search Pill has been shifted down and a redesigned weather and date combo widget. That's really it. Would it be possible to make the updates to the launcher without actually having hands-on with the device to get the code and apk

**Comment by nyancrimew** [comment]
No Pixel 2 Features will be added before I have a new apk with the redesign

**Comment by AxiK101** [comment]
Forgot of this thread...lol, lets wait for someone to upload the official apk at apkmirror

**Comment by JacobDB** [comment]
Adding screenshots for reference.

![new-launcher-style](https://user-images.githubusercontent.com/1123997/31279366-70f48356-aa6e-11e7-8673-e7576c6e6490.png)

**Comment by JacobDB** [comment]
And a bit more information: https://www.androidcentral.com/everything-new-pixel-2-launcher

**Comment by theandroidenthusiast** [comment]
Read the thread. Developer wants the APK before he is going to update the launcher. Which is reasonable just wait 2-3 weeks

**Comment by JacobDB** [comment]
Yes, I'm aware of that, just posting some more details

**Comment by drew5494** [comment]
+1 new launcher looks cool

**Comment by KieronQuinn** [comment]
https://www.xda-developers.com/get-google-pixel-2-pixel-launcher-bottom-search-bar/

**Comment by theandroidenthusiast** [comment]
Launchers up on XDA. KieronQuinn bet me to it. Looking forward to the update. How long would you think it would take to update the launcher?

**Comment by elsondione** [comment]
https://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-p-4275643-release/pixel-launcher-p-4275643-android-apk-download/

**Comment by chitrarths** [comment]
Pixel 2 launcher apk is now available easily so please add features to lawnchair

**Comment by drew5494** [comment]
Any progress to report?

**Comment by eybarra10** [comment]
https://www.apkmirror.com/apk/paphonb/rootless-pixel-2-launcher-mod/rootless-pixel-2-launcher-mod-p-4275643-modded-1-7-release/rootless-pixel-2-launcher-mod-p-4275643-modded-1-7-android-apk-download/

**Comment by LinuxLlama** [comment]
@drew5494 The app drawer design is being worked on. #972
