### ISSUE TITLE
1.1.0.1322 breaks google calendar icon

### ISSUE THREAD

**Issue by ffeingol** [Deletescape-Media/Lawnchair#787]
I upgraded to the latest Alpha 1.1.0.1322 and it breaks custom icons for the standard Google Calendar.  Instead of the icon from the icon pack you get the default calendar icon.  I tested with numerous icon packs.

Nexus 5X
Android 7.1.2

**Comment by AxiK101** [comment]
yes that is true:
![](https://i.imgur.com/OjytHd7.png)

**Comment by LinuxLlama** [comment]
Yep, I have the issue and others on G+ do too.
