### ISSUE TITLE
Calendar icon not updating

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#788]
This bug was reported by Gabriel Walsh on Google+. Original post: https://plus.google.com/+GabrielWalsh/posts/fyV8SbB9qdi

## Description
When using calendar icon pack that are supposed to change automatically to reflect the current date, the icon never updates automatically from the last date you manually set it.

## Expected Behavior
When selecting a calendar icon from the icon picker, it automatically updates every day.

## Actual Behavior
When selecting a calendar icon from the icon picker, it doesn't automatically update from the last date set.

## Steps to Reproduce
1. Open icon picker for Google Calendar.
2. Select a calendar icon.
3. Wait a day (or set the date manually) and the icon won't update.

## Environment
* Device: Nexus 7 (Second Gen)
* Android version: 6.0.1
* Launcher version: 1.1.0.1318
* Rom: Stock

**Comment by callmemulo** [comment]
@Treemindr this happened on home page or drawer
