### ISSUE TITLE
Hidden Apps Menu

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#789]
This feature request was submitted by Gabriel Walsh on Google+. Original post: https://plus.google.com/+MayurSawantOfficial/posts/NN9YuQHCcB9

There should be some dedicated menu something like the below screenshot to hide / unhide apps from the app drawer. The current implementation is a very tedious task.

![gplus1545446545](https://user-images.githubusercontent.com/29968331/31051593-0d89d538-a621-11e7-966d-16e0bc7d3441.jpg)

**Comment by RikKoedoot** [comment]
I agree

**Comment by fon321** [comment]
Thank you!

**Comment by enricocid** [comment]
If Devs are interested here is my implementation to manage hidden apps in Launcher3 (also used in Paranoid Android).
I would be happy if you use this :)

You can switch to grid layout and customize the hidden item if needed.


https://github.com/enricocid/LaunchEnr/commit/05795174fc02228574b5590477332e31d313b49b

https://github.com/enricocid/LaunchEnr/commit/f3b268d77fa1c9ee934049f389763a1949a6e8f0

**Comment by LinuxLlama** [comment]
This has been added in so I'm closing this issue.
