### ISSUE TITLE
Gray navigation bar icons on the Galaxy S8

### ISSUE THREAD

**Issue by cyberon** [Deletescape-Media/Lawnchair#790]
On the Galaxy S8 the navigation bar buttons are gray and barely visible on some wallpapers, it seems this is a common issue, only fixed on Nova Launcher.
![screenshot_20171001-174023](https://user-images.githubusercontent.com/683597/31056839-4265e5ee-a6d0-11e7-9051-d93d00060536.jpg)
![screenshot_20171001-174249](https://user-images.githubusercontent.com/683597/31056846-5dfac54a-a6d0-11e7-8d9e-7de21c18abeb.jpg)

**Comment by fonix232** [comment]
This is a known issue and we have found no way around it as of now.

**Comment by eggsgent** [comment]
Hi, wound not a setting to make the navigation bar opaque fix this behaviour for the affected users? (is there such a feature request already?)
