### ISSUE TITLE
Issue with Google pill

### ISSUE THREAD

**Issue by rj-raghavjoshi** [Deletescape-Media/Lawnchair#796]
Hello!
There is a problem with the Google pill. Whenever we change a wallpaper, the pill gets hidden back and we have to again and again refresh the Lawnchair whenever we change the wallpaper.

Information on mobile
Android Version- 6.0.1
Phone- Redmi 4A
Lawnchair version- 1.1.0.1324

Here is a report pulled by a guy.

https://plus.google.com/100351328803601045516/posts/JMHRK36hBUH

I wish this will be fixed ASAP.
Thank You

**Comment by fonix232** [comment]
This is a known issue of the Pill implementation we have - for some reason certain changes trigger it to reload and it can't reload successfully all the time.

**Comment by reddvid** [comment]
You can just pinch then the pill will be back
