### ISSUE TITLE
Fast Finder (Sesame Shortcuts)

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#800]
This feature request was submitted by Mayur Sawant on Google+. Original post: https://plus.google.com/+MayurSawantOfficial/posts/JECCUQwPtZD?fscid=z13oen0yazelgbzva230tpggon2feri3y.1507089512837406

Is it possible to integrate "fast finder" with lawnchair like what Nova Launcher team did with Sesame shortcuts? 

Like using some gesture or by double tapping menu/home/back button.

Apps like fast finder and sesame shortcuts are the need of time when the phone storage is gigantic and finding a particular file or anything for that matter is a tedious task.

**Comment by stefanvanruiten** [comment]
I'd love to see fast finder and / or sesame integration in Lawnchair. But please integrate it better then flick launcher did. There it's just a gesture, opening it next to the google search bar making it double. 

It'd be better if it were a search provider in itself or works like sesame in nova.

**Comment by LinuxLlama** [comment]
The Google search bar is already similiar to Sesame so I'm going to close this issue.
