### ISSUE TITLE
Shortcut text color

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#801]
Something I noticed is that Lawnchair's shortcuts are different from the one used on the Pixel Launcher. The shortcut text is grey instead of black. I made a mockup of what it should like to match the Pixel Launcher.

Current:
![screenshot oct 4 2017 6-05-24 pm](https://user-images.githubusercontent.com/29968331/31206850-50826290-a92f-11e7-8bbf-06bbaf8d929f.png)

Mockup:
![screenshot oct 4 2017 6-05-24 pm - copy](https://user-images.githubusercontent.com/29968331/31206861-5be74baa-a92f-11e7-8258-f630a114e80d.png)

**Comment by nyancrimew** [comment]
I didn't even notice this, but tbh I like it more in grey, it fits the overall look of the shortcuts way better imo

**Comment by LinuxLlama** [comment]
@deletescape I do agree, the black doesn't look too great.

**Comment by AxiK101** [comment]
Grey is way better
