### ISSUE TITLE
Previous app on home page

### ISSUE THREAD

**Issue by hetulkatyal** [Deletescape-Media/Lawnchair#803]
## Description

When I hit multitasking it doesn't show the launcher home page as the first but the app I used first

## Expected Behavior

When i press multi tasking it should show the launcher home page as the first page but it shows the app I used and when I unlock the phone or hit home it goes to the app I used before, I'm using an letv le 1s running on EUI 5.8

## Actual Behavior

It should show the launcher home as the main app

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version: 6.0
* Launcher version: v1.0.1063
* Rom: EUI

## Logcat

```
your log here
```

**Comment by nyancrimew** [comment]
The Launcher is usually not supposed to be shown in recents, I know this is different on letv devices, but without owning such a device it is pretty hard to support this.

**Comment by fonix232** [comment]
This is an intended behaviour, detailed in Google's own Android design guidelines. I do not think we should break the current workings just so it works the same way as the letv launcher.

**Comment by hetulkatyal** [comment]
Many launchers like to nova launcher do work like that, not just letv
launcher, maybe you should try looking into it

**Comment by fonix232** [comment]
As I said before, such behaviour goes against Google's own design language.
