### ISSUE TITLE
[Feature Request] Search hidden apps from Search apps bar

### ISSUE THREAD

**Issue by burakdede0** [Deletescape-Media/Lawnchair#807]
## Description
Search apps bar in app drawer searches only visible apps. It would be nice to have search hidden apps from Search apps bar.

**Comment by fon321** [comment]
Great idea, I would like this too!

**Comment by KapilFaujdar** [comment]
+1

**Comment by StefanoCornago** [comment]
+ 1

**Comment by Younes-L** [comment]
This appears to be the same feature request as #304
