### ISSUE TITLE
2x5 dock size

### ISSUE THREAD

**Issue by currall** [Deletescape-Media/Lawnchair#810]
I think that a 2x5 / 3x5 grid size for the dock would be good because I could put more apps in it

**Comment by AxiK101** [comment]
and widgets too, like Google search bar for example 😜

**Comment by RikKoedoot** [comment]
this is a good idea, so you don't have to use klwp for example

**Comment by devgar** [comment]
There's an option to add a second row to dock. "Two row dock" widgets are available in each row.
