### ISSUE TITLE
Unable to place the Month widget on Home screen

### ISSUE THREAD

**Issue by gotroot** [Deletescape-Media/Lawnchair#812]
I want to place the Calendar widget showing the Month on the home screen instead it shows "No more room on this Home screen." although I'm placing it on an empty screen.

Can you please fix that?

**Comment by AxiK101** [comment]
you should try Another Widget, it's an app that mimics new date/calendar/weather widget from pixel²
Search on play store

**Comment by divadsn** [comment]
@gotroot your DPI seems to be too high, the calendar widget requires 4x5 at least as far as I know.
