### ISSUE TITLE
Lawnchair forces reselect of default launcher after any crash event

### ISSUE THREAD

**Issue by Zazie-Lavender** [Deletescape-Media/Lawnchair#816]
Title; This bug occurs even when the user explicitly selects "ALWAYS" use Lawnchair

Device: Nexus 6 (Shamu)
Android Nougat 7.1.2 (LineageOS 14.1)

Expected: On any crash event, Lawnchair remains the default Launcher interface and system ui does not reprompt on launch which launcher to use

Installed launchers: Trebuchet (LineageOS), Google Now Launcher (App package disabled), AutoTools (Not configured to be used by anything for launcher purposes, no task relationships within Tasker are configured)

Confirmed Troubleshooting: Did trial uninstalls of ALL above mentioned packages except Trebuchet, which I merely disabled (for stability reasons) and still saw this issue. 

Currently using latest available build of Lawnchair, this issue still shows up occasionally

**Comment by KieronQuinn** [comment]
Pretty sure this one is caused by Android itself, I've seen other launchers do it too. It's probably a feature, if a launcher is crashing you don't want to be restarting it and it just looping crashing do you?
