### ISSUE TITLE
kengrawin

### ISSUE THREAD

**Issue by kengraWin** [Deletescape-Media/Lawnchair#818]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by kengraWin** [comment]
Good

**Comment by fonix232** [comment]
Please do not use the issue tracker for anything else than issue reports and feature requests. Endorsements, discussions, etc. should all go on our official Telegram channel.

This is your first, last, and final warning. Misuse of the issue tracker will not be tolerated, on the next infraction I will have to restrict your access to the repository.
