### ISSUE TITLE
Crash when attempting to use search

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#820]
## Description
Lawnchair crashes immediately when using app search from app drawer.

## Expected Behavior
Starts listing apps

## Actual Behavior
Crash

## Steps to Reproduce

1. (Or 2) apply [these settings](https://drive.google.com/open?id=0B59oThBMvgEvU1lhd1pVVnRRVDQ)

2. (Or 1) Update from 1324 to 1334

3. Search for apps

4. ???

5. Profit

## Environment

* Device: Oneplus A0001 bacon/find7op

* Android version: 7.1.2

* Launcher version: 1334

* Rom: slim7 

## Logcat

Can't grab useful logcats at the moment, something is flooding them with errors

**Comment by Younes-L** [comment]
new build 5 minutes after I submitted this 😂 phone is charging right now, will test later

**Comment by suphon-t** [comment]
This should be fixed with 580ffcb.

**Comment by Younes-L** [comment]
@paphonb  it does :)
