### ISSUE TITLE
Unable to create folders

### ISSUE THREAD

**Issue by rmehta1987** [Deletescape-Media/Lawnchair#821]
## Description
Unable to create folders in main screen.  I have the latest release 1.1.0.1336, yes I am unable to create new folders and can only use folders that were already created from the original pixel launcher.

## Expected Behavior
When you place an icon on top of another it creates a folder. 

## Actual Behavior
The icons simply change locations

## Steps to Reproduce
Move an icon on top of another icon, the icons will act as magnets and repel each other basically.

## Environment
* Device: Nexus 6p and Pixel XL
* Android version: Oreo
* Launcher version: 1.1.0.1336

**Comment by LinuxLlama** [comment]
Works fine for me. Did you try rebuilding icon database?

**Comment by rmehta1987** [comment]
I have, is there something in the settings I should change to enable folder function ?

**Comment by guest4711** [comment]
It's a little bit tricky for me too. But after some tries I succeed...

**Comment by jerryn70** [comment]
yes there an issue in creating folders. after 5 to 6 times of trying i created a folder. most of the times when we try to create folder the app icon change its location

**Comment by papampi** [comment]
Same problem on tab s3

**Comment by guest4711** [comment]
Same if you try to add another icon to the folder. I'm on .1834 but it has been a problem for a long time...

**Comment by TheSecureTux** [comment]
What would be really helpful and I haven't been able to accomplish is to create folders on the drawer itself, not on the "desktop".  
  
Every time I try to group two pick an app to create a group it immediatelly switches to the desktop to create a shortcut. But that's not where I want it. 

I guess this would be more a  FR than a bugfix?

**Comment by neolovich** [comment]
Same problem here. Maybe it is possible to simplify to "Folder-Creation-Process"? It is a little bit annoying if the icons change in 9 of 10 cases the position instead of building a folder.
Thank you!

**Comment by keithzg** [comment]
I can even get the black circular background around the destination location that implies it's going to create a folder, but nope, when I release my finger it just swaps icon locations instead anyways.

**Comment by SomeMichael** [comment]
I also have have this issue. Thinking about switching to Nova. Just a remark: it seams that the faster you move the app icon onto another icon or folder it is more likley to have success.

**Comment by AyanC1** [comment]
Is this issue resolved for everyone? Still having this issue

**Comment by ghost** [comment]
Hi I'm having this issue, does anyone know of a fix?

**Comment by KTibow** [comment]
1. Check you're on the latest version of Lawnchair
2. If you are, make a new issue, and include a screen recording
