### ISSUE TITLE
Date format in finnish is wrong/not good

### ISSUE THREAD

**Issue by Timbets** [Deletescape-Media/Lawnchair#825]
Date format in finnish is different (bad) from Pixel launcher.
TORSTAINA, LOKAKUUTA 12 
should be
TORSTAI 12. LOKAKUUTA

Pixel launcher screenshot 
![screenshot_20171012-185733](https://user-images.githubusercontent.com/24968370/31507418-43d7c512-af83-11e7-9920-43789d91aaed.png)

Lawnchair screenshot 
![screenshot_20171012-185959](https://user-images.githubusercontent.com/24968370/31507448-64cb1986-af83-11e7-8193-3e559b9cc640.png)

**Comment by Timbets** [comment]
So date names should be
**maanantai, tiistai, keskiviikko, torstai, perjantai, lauantai, sunnuntai**
instead of
**maanantaina, tiistaina, keskiviikkona, torstaina, perjantaina, lauantaina, sunnuntaina**

I think I corrected the date format in crowdin to correct EEEE d. MMMM

**Comment by nyancrimew** [comment]
If you corrected the date format in Crowdin this should be fixed with the next import of translations
