### ISSUE TITLE
Google Translate without Pixel icon

### ISSUE THREAD

**Issue by TheShark27** [Deletescape-Media/Lawnchair#826]
## Description
Even if I've enabled "use Pixel icons" option on my device, the regular Google Translate icon is shown.

## Expected Behavior
The round Translate icon should show up.

## Actual Behavior
The regular Translate icon shows up.

## Steps to Reproduce
Follow this steps:

1. Enable Pixel icons in the settings.

## Environment
*Device: Moto G⁴ Play XT1602
*Android version: Marshmallow 6.0.1
*Launcher version: alpha 1.1.0.1243
*Rom: stock
*Build number: MPIS24.241-15.3-21

**Comment by suphon-t** [comment]
Somehow Google Translate app doesn't have a circle icon. This also happens on official Pixel Launcher too.
