### ISSUE TITLE
Icon lable Colors in the drawer and home screen become same when I press the home button.

### ISSUE THREAD

**Issue by hemangr8** [Deletescape-Media/Lawnchair#828]
## Description

I'm unable to change the icon label colours individually for home screen and drawer.
Whenever I change the icon label colour of the drawer, the home screen aquires the same colour automatically.
Pls fix this bug.
Or send me a solution for it.
## Expected Behavior

The Colors of the icon lable on the home screen and the drawer should be different.
## Actual Behavior

The Colors become the same when restarting the lawnchair.

## Steps to Reproduce

1. Change icon lable Color for drawer
2. Change icon lable color home screen
3. Restart Lawnchair
4. Press home screen button

## Environment

* Device: Redmi Note 4x
* Android version:7.0
* Launcher version:1.1.0.1336
* Rom: MIUI 8.5.8.0 Global Stable

**Comment by LautaroBel97** [comment]
Yes this was happening to me too. Samsung J7 on Android 6.0. Lawnchair version: 1.1.0.1336.
