### ISSUE TITLE
Notification dots 

### ISSUE THREAD

**Issue by SebinChacko** [Deletescape-Media/Lawnchair#829]
Issue with notification dots.. it's not showing for missed calls and SMS in Marshmallow.. fix it plss...

**Comment by jerryn70** [comment]
same issue for me on my moto x play marshmallow.
Iam using the latest version from play store

**Comment by nyancrimew** [comment]
Did you give Lawnchair notification access?

**Comment by jerryn70** [comment]
yes

**Comment by SebinChacko** [comment]
Yes. Still it's not showing pls. Can you try to fix this issue 😊

**Comment by drbeat** [comment]
I noticed that notification dots dont show on 'running' apps e.g. if I listen to music the player has no notification dot.

maybe its the same for sms/call?

**Comment by SebinChacko** [comment]
No..it's like when u are playing music it doesn't show.....buh when you pause it...the dots are shown...

**Comment by suphon-t** [comment]
Then that's the expected behavior.
