### ISSUE TITLE
Import / Export (Setup switcher)

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#83]
Allow backup and restore

**Comment by r4lex** [comment]
I would go even further, automatic backup/restore of the settings is highly desirable, just like most apps currently do when restoring a new phone from the cloud.

**Comment by OvermindDL1** [comment]
Yeah, could link to google drive and sync backup data there for ease of use by both users and the dev.  Perhaps have multiple backups that can be named and chose from?

**Comment by deletescape** [comment]
@OvermindDL1 this is actually exactly what I am planning to do (Kind of like profiles)
