### ISSUE TITLE
Pixel² Launcher finally here😈

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#830]
Here the original apk
https://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-p-4275643-release/pixel-launcher-p-4275643-android-apk-download/

Dear beloved developers, plz take care this precious apk file and do your magic on Lawnchair to get all these goodies mother Google gave as!!!

**Comment by fonix232** [comment]
It's been already posted. Search before opening these tickets ffs. This is not the first time...

**Comment by AxiK101** [comment]
@fonix232only requests are posted. I share an apk here though....

A presentation at a glance
https://drive.google.com/file/d/0B-7jWHTkaOyWRDZqbm1lMktWem8/view?usp=drivesdk
