### ISSUE TITLE
Improve update mechanism

### ISSUE THREAD

**Issue by fmsouza** [Deletescape-Media/Lawnchair#841]
Do we have some good way to know when there's a new update for the launcher? I used to look at the GitHub releases section, but you are not releasing the updates there anymore. The only other way I discovered to find the updates (by luck, while scrolling Google+) is going to ApkMirror whenever I want to check and compare my version with the latest available.

**Comment by guest4711** [comment]
There is a playstore version out already, f-droid version is coming soon. And you can always  have a look at https://lawnchairmirror.duckdns.org/latest/

**Comment by elsondione** [comment]
Playstore version: https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah

**Comment by fmsouza** [comment]
Hmmmm, good to know! Thank you very much, guys! :)
