### ISSUE TITLE
Google Now Pane Not showing up

### ISSUE THREAD

**Issue by ZaheenJ** [Deletescape-Media/Lawnchair#846]
## Description
The Google now pane won't show up on the play store version, after installing lawnfeed and enabling in settings, after rotating screen into landscape. It won't work even after going back to portrait mode.

## Expected Behavior
When you swipe left in any rotation it should open Google now pane.

## Actual Behavior
After rotating into landscape it won't show up, even after rotating back to portrait.

## Steps to Reproduce
Assuming you've already installed lawnfeed, enabled it in settings, and are on the play store version...

1.Swipe left(don't rotate screen, it should be there)
2.Turn to landscape mode
3.Swipe left again(it should not work)
4.Turn back to portrait mode
5.Repeat step 3

## Environment

* Device:Nexus 5x
* Android version:8.0.0
* Launcher version:1.1.0.1356(play store version+lawnfeed)
* Rom:Stock

**Comment by InfernusV** [comment]
It says that you need to install the Lawnfeed Add-on https://storage.codebucket.de/lawnchair/Lawnfeed-1.1.0.1356.apk

**Comment by AxiK101** [comment]
lawnfeed gets many crashes on me and google search pill widget doesn't have that  smooth animation. I'm going back on alpha builds that work like a charm

**Comment by ZaheenJ** [comment]
@InfernusV I did

**Comment by drbeat** [comment]
Yep Lawnfeed also crashes for me sometimes
I am using a G5+ with Android 7.0

edit: seems like it is stable now as it did not crash for a week

**Comment by divadsn** [comment]
Fixed with #959
