### ISSUE TITLE
Can't disable spring effect

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#849]
## Description

There's no toggle in lawnchair settings to disable the spring animation. As feature request I suggest you add a way to disable this effect, as it makes the drawer and all the app icons look blurry for a longer period of time.

## Expected Behavior
Open app drawer, apps icons stop moving when they reach their respective positions and are therefore ready to be looked at.

## Actual Behavior
Apps keep bouncing up and down, which makes them uneasy on the eyes and distracting for the users as we wait for things to settle down.

## Steps to Reproduce

1. Open app drawer with a fast/long enough swipe, or

2. Scroll down, or

3. Scroll up.

## Environment

 

* Device: Oneplus A0001

* Android version: 7.1.2

* Launcher version: 1364

* Rom: Slim7

**Comment by AxiK101** [comment]
is that the begining of pixel² features adding?

**Comment by TheShark27** [comment]
Wait a sec, where can I download this version?

**Comment by Younes-L** [comment]
@TheShark27 t.me/lawnchairci

**Comment by suphon-t** [comment]
b09ca95

**Comment by Younes-L** [comment]
that was fast, thanks !

**Comment by TheShark27** [comment]
Thank you very much for the link!
