### ISSUE TITLE
Is the Google Play release same as the last stable release on Github (1.0.1063)?

### ISSUE THREAD

**Issue by baruchin** [Deletescape-Media/Lawnchair#850]
Couple of queastions about Google Play release.

I use latest stable 1.0.1063 version. What happens if I install the Google Play version over my working github version? Do all my settings will be kept? Do I loose Google Now feed?

If one decides to keep using alpha releases, is Lawnfeed add-on app mandatory, or is it only for Play releases?

**Comment by fonix232** [comment]
The Play Store version uses the package name `ch.deletescape.lawnchair.plah`, whereas the regular Travis builds (so pretty much anything else than the Play Store APK) uses `ch.deletescape.lawnchair`. You can install them side-by-side, and they have their own respective settings.

**Comment by baruchin** [comment]
What about hte second question?

**Comment by fonix232** [comment]
Lawnfeed is only required for Release builds, which are also only Play Store specific as of now.

**Comment by AxiK101** [comment]
yeah but lawnfeed crashes randomly and the g pill widget doesn't get that smooth animation that alpha builds have

**Comment by fonix232** [comment]
@AxiK101 Yes, and it will never be that smooth since it requires proxying through an extra app.

Lawnfeed crashes are being investigated, and you flooding every.fucking.ticket with it does not help the case.
