### ISSUE TITLE
Translucent Google Feed

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#851]
It's a new google feed style enrollment by google these days. For some reason i get it only when i set pixel² launcher as my default launcher, even when i use Lawnchair it shows up but when i set Lawnchair as my default launcher i get the old google style feed. Is there anyway to force it without pixel² launcher installed? Thanks

https://drive.google.com/file/d/0B-7jWHTkaOyWM1hnN2VYalhBTG8/view?usp=drivesdk

**Comment by LinuxLlama** [comment]
I believe it's up to Google change it.

**Comment by nyancrimew** [comment]
We can not affect how Google Now / Google Feed looks, it is entirely provided by google.
