### ISSUE TITLE
Allow tablets to install from the Play Store

### ISSUE THREAD

**Issue by arkon** [Deletescape-Media/Lawnchair#855]
It'd be nice if tablet users could install this from the Play Store.

Is it currently not enabled due to some bugs with layouts (#89, #824)?

**Comment by divadsn** [comment]
No, it is not possible during the alpha stage on the Google Play Store afaik.

**Comment by arkon** [comment]
I don't think that's true, I recently did an alpha release of an app on the Play Store and I could target tablets as well.

**Comment by nyancrimew** [comment]
@arkon 
![image](https://user-images.githubusercontent.com/13785669/31760725-e9382a2e-b4b5-11e7-890b-d1bc11b66ef0.png)

**Comment by arkon** [comment]
@deletescape That doesn't prevent you from making an app available for tablets. You could take a look in the "Device catalogue" section.

**Comment by divadsn** [comment]
@arkon do you still don't believe us?
![image](https://user-images.githubusercontent.com/28547847/31854002-9e0c1112-b692-11e7-90d3-507ee8a0a75b.png)

**Comment by arkon** [comment]
I actually think it's [an issue with permissions](https://stackoverflow.com/a/22982521).

I'm confident that you _can_ offer apps to tablets during the alpha stage because I [had this app](https://github.com/LISTEN-moe/android-app) available as an alpha for a while and I could install it from my Nexus 7.

**Comment by divadsn** [comment]
@arkon as @deletescape have shown, we are unable to provide tablet support as Google Play don't even give a damn duck about checking that on alpha stage for us.

**Comment by arkon** [comment]
I'm sorry if I'm coming off as persistent/annoying. It doesn't really affect me since I can always sideload it, but I just wanted to point out that it's likely not an issue with having it in the alpha stage and that you'll see it in production as well. ¯\\\_(ツ)_/¯
