### ISSUE TITLE
Dock icon bug

### ISSUE THREAD

**Issue by jerryn70** [Deletescape-Media/Lawnchair#857]
There is a bug in dock icons . Bottom of the icons are cut down by the launcher. See screenshot. 
![](https://i.imgur.com/vULmomd.png)

**Comment by guest4711** [comment]
Did you try to adjust the height of the dock (settings -- dock -- height scale)?

**Comment by jerryn70** [comment]
Yes but the problem is still there

**Comment by guest4711** [comment]
Don't see it on 1.1.0.1500 with height>80% . Which version are you using?
