### ISSUE TITLE
Bug persistent icon on the screen

### ISSUE THREAD

**Issue by marcogiannini** [Deletescape-Media/Lawnchair#859]
## Description
When I click on a program icon in a folder, the pressed icon remains fixed on the screen
This is a video of the bug 
https://youtu.be/HCGu2EFZug4

## Environment
* Device: Lenovo K6 (aka Lenovo K33a48)
* Android version: 7.0
* Launcher version: Lawnchair 1.1.0.1371 from Google Play Store 
* Rom: Stock Rom

**Comment by marcogiannini** [comment]
The bug is still present in v 1.1.0.1420

**Comment by divadsn** [comment]
I tried hard, but I wasn't able to reproduce your issue, see:
https://drive.google.com/file/d/0BxuCwRwdyiEnVzhBRDRTZlJpMjA/view?usp=sharing

Did also the same on 3 other phones, running 6.0 and 7.1.

**Comment by marcogiannini** [comment]
How i can help ti debug this bug?
