### ISSUE TITLE
Long press options not fitting properly on screen

### ISSUE THREAD

**Issue by jerryn70** [Deletescape-Media/Lawnchair#860]
When I long press on icons in home screen and app drawer the options bubble goes out side the screen . ![](https://i.imgur.com/1P4KDus.png)
![](https://i.imgur.com/6OCPMEb.jpg)

Device moto x play
Marshmallow 6.0.1

**Comment by divadsn** [comment]
Have you changed DPI settings manually?

**Comment by jerryn70** [comment]
no i didn't changed anything

**Comment by nyancrimew** [comment]
Duplicate of #535
