### ISSUE TITLE
Have labeled dock icons

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#863]
This feature request was submitted by Marco Aurelio Nogueira on Google+. Orginal post: https://plus.google.com/112175035118389145245/posts/LHYAxSicZbb

I´d like to see an option to have labels in dock icons . Thanks in advance for this great launcher!

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Labled dock icons](https://trello.com/c/F96A0Gsr/13-labled-dock-icons)
