### ISSUE TITLE
Searchbar position on a future Pixel2 interface upgrade

### ISSUE THREAD

**Issue by Silviobrittos** [Deletescape-Media/Lawnchair#865]
Hi, guys
First of all, amazing job, thanks!

I imagine that an upgrade for the Pixel2 interface should already be in progress.

I wanna ask to add an option, relative to the new position of the search bar. Please add an option to show the searchbar right above the icons on the dock, not just the (now) conventional position below them.

A lot of phones theses days (and more to come) are borderless. the searchbar below the icons seems to me VERY low in same cases.

Thanks!

**Comment by ghost** [comment]
I 100% support this idea

**Comment by devgar** [comment]
Developers are proposing to add a second row to the dock, then you can add Google search widget where you like it more. Yo can do It today.

And for the pixel2 time/event/weather notification I recommend to use this widget

https://play.google.com/store/apps/details?id=com.tommasoberlose.anotherwidget
