### ISSUE TITLE
Possible fix to add shortcuts on a smaller DPI

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#866]
On the Lawnchair community on Google+, a lot of people have said that shortcuts go off their screen because of a DPI issue. I know that by now we all know this issue. Nova Launcher recently had a workaround by making the middle shortcut appear in the center like this:

![screenshot_20171019-215703](https://user-images.githubusercontent.com/29968331/31825365-e17d6c20-b566-11e7-89c6-ef620224cdaa.png)

This would be a great addition to Lawnchair to fix the shortcut bug.

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix shortcuts on low DPI settings](https://trello.com/c/jV5Wpxjq/12-fix-shortcuts-on-low-dpi-settings)
