### ISSUE TITLE
Feed - Graphical Glitches

### ISSUE THREAD

**Issue by Nathangorr** [Deletescape-Media/Lawnchair#869]
I've been encountering a strange graphical glitch when pressing the home button to exit the feed. Swiping left to get to the home screen functions normally, but pressing the home button generates a brief bouncing effect when pressed. You can find a gif showing this behavior at https://i.imgur.com/Mnicifk.gifv.

Device: Pixel
Android version: 8.0.0
Launcher version: 1.1.0.1420
Lawnfeed version: 1.1.0.1356
Rom: Stock Rom

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lawnfeed update, fix Signing & version number](https://trello.com/c/foXbXKbn/15-lawnfeed-update-fix-signing-version-number)

**Comment by divadsn** [comment]
@paphonb that's what I mean

**Comment by lpen21** [comment]
Happens to me also but only on play store version.  The latest alpha 1490 does not exhibit the glitch

**Comment by drbeat** [comment]
bug still exists

**Comment by divadsn** [comment]
It hasn't been fixed so wait and keep calm.

**Comment by ghost** [comment]
I'll be glad when this is fixed. It is not easy to determine when a possible fix has been released.

**Comment by nyancrimew** [comment]
Apparently this was fixed on googles side in recent updates to the Google app.

Source: Tested myself and feedback from Lawnchair users.


Thanks a lot Google 😉

**Comment by divadsn** [comment]
@deletescape +10000

**Comment by lpen21** [comment]
Go figure, thanks Google!
