### ISSUE TITLE
Transition Between Google Feed and home screen is buggy

### ISSUE THREAD

**Issue by simonerlic** [Deletescape-Media/Lawnchair#870]
## Description

When transitioning from the feed, it glitches and "shakes" for less than a second. Seems to only be when pressing home button in feed.

## Expected Behavior

Normal (smooth) transition to home

## Actual Behavior

See description above
And tweet directed towards lawnchair by @simonerlic

## Steps to Reproduce

1. Swipe left to Google feed
2. Press Home button
3. enjoy.

## Environment

* Device: Essential Phone
* Android version: 7.1.1
* Launcher version:1.1.0.1427
* Rom: Stock

## Logcat

```
your log here
```
There ya go! Hope it helps!

**Comment by helloworld1** [comment]
Same issue on Nexus 6 Android 8.0 with the latest version 1.1.0.1427

**Comment by Nathangorr** [comment]
I reported the same issue at https://github.com/Deletescape-Media/Lawnchair/issues/869. Gif of bug can be found at https://i.imgur.com/Mnicifk.mp4.

**Comment by divadsn** [comment]
Duplicate of #869
