### ISSUE TITLE
Change log shows null

### ISSUE THREAD

**Issue by leibale** [Deletescape-Media/Lawnchair#871]
## Description
For some reason the changelog is null since the last update or two.

## Steps to Reproduce
1. Open the settings
2. Open the about page
3. See that the changelog shows null

## Image
![image](https://user-images.githubusercontent.com/7086055/31948290-2d304130-b8df-11e7-89cd-1bcda7e56b04.png)

**Comment by guest4711** [comment]
Fixed in newer versions, e.g. 1.1.0.1472
