### ISSUE TITLE
Missing old style characteristics

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#877]
It's great that we see new pixel² characteristics adding one by one in lawnchair but it whould be great not to completely remove old style ui, like for example the new pop-up shortcut balloons, it should be an option to choose between the 3 style (2 old ones). If you can please implement every option pixel launcher gives (from oldest to newest)
Thanks

**Comment by nyancrimew** [comment]
We are completely moving on to the 8.1 style in the Launcher3 style, for the Pixel Launcher specific features (like Searchbars, etc.) we will try to allow switching between them.

**Comment by AxiK101** [comment]
Thanks
