### ISSUE TITLE
Adaptive icons are cutting off when moving the icons

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#880]
## Description

The adaptive icons when moved cut off some of the moving parts on the left side of the icons, more noticeable on chrome dev icon and Google maps icon. Some like fasthub don't have this issue.
## Expected Behavior

There shouldn't be any cutoff part of the icon 

## Actual Behavior

It is cut off

## Steps to Reproduce

1.set icons to be adaptive (I used squircle)
2.get some icons ( not all have this issue)
3.shake them around

## Environment

* Device: Moto g4 plus
* Android version: 7.0
* Launcher version: 1.1.0.1477
* Rom:stock

![screenshot_20171026-184417](https://user-images.githubusercontent.com/29402532/32066080-f499df88-ba7e-11e7-8b4b-741c6fae6f6c.png)
![screenshot_20171026-184434](https://user-images.githubusercontent.com/29402532/32066081-f4ceef66-ba7e-11e7-8425-79cfd0cf781c.png)

**Comment by RikKoedoot** [comment]
To be clear, I am moving the icons to the left in the screenshots

**Comment by divadsn** [comment]
@paphonb any thoughts?

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pixel 2 Launcher features](https://trello.com/c/L1y2KR2f/3-pixel-2-launcher-features)

**Comment by AxiK101** [comment]
Same here.. icons get distorted when moving, xa ultra 7.0

https://drive.google.com/file/d/0B-7jWHTkaOyWVGZDWUc2aU9WeTQ/view?usp=drivesdk
