### ISSUE TITLE
Lines when using longpress popup

### ISSUE THREAD

**Issue by RikKoedoot** [Deletescape-Media/Lawnchair#881]
![screenshot_20171026-184355](https://user-images.githubusercontent.com/29402532/32066902-9d459fbc-ba81-11e7-8a23-ba1bec36a846.png)
![screenshot_20171026-184338](https://user-images.githubusercontent.com/29402532/32066903-9d800684-ba81-11e7-8876-a727a121cd0b.png)

## Description

When I longpress any icon on my homescreen there appear lines right and under the popupbox. The screenshot will explain for it self

## Expected Behavior

There should be no lines

## Actual Behavior

There are lines

## Steps to Reproduce

1. Probably just use latest version. I don't know how to reproduce this.

## Environment

* Device: Moto g4 plus
* Android version:7.0
* Launcher version: 1.1.0.1477
* Rom:stock
* Dpi:403

**Comment by divadsn** [comment]
![image](https://user-images.githubusercontent.com/28547847/30262929-4299094a-96d3-11e7-81c1-1731e75c6340.png)

Should be fixed soon tho.

**Comment by divadsn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix shortcuts on low DPI settings](https://trello.com/c/jV5Wpxjq/12-fix-shortcuts-on-low-dpi-settings)
