### ISSUE TITLE
[Feature request] Add option to edit icons with custom picture

### ISSUE THREAD

**Issue by Hilyxx** [Deletescape-Media/Lawnchair#882]
hello

great launcher but some options are missing:
- **Edit icons with custom picture with gallery system app**

- option to change drawer background color
- settings for app folder ( background color, folder preview style, fullscreen app folder...)

Thank you and good job !

version : 1.1.0.1427

**Comment by divadsn** [comment]
Actually maybe a great feature, but also a feature which could potentially break the stability of the launcher, so currently no way :/
