### ISSUE TITLE
The feed integration is kinda poor

### ISSUE THREAD

**Issue by notabene00** [Deletescape-Media/Lawnchair#885]
## Description

I expect last Google feed features to be in it, like the "follow" button and displaying the subject in the title. But got something like Google Now's feed looked like a few weeks ago.

## Expected Behavior

<img src="https://user-images.githubusercontent.com/9576189/32128692-c796a420-bb88-11e7-8923-9a8e6eca4f08.jpg" width="200">

## Actual Behavior

<img src="https://user-images.githubusercontent.com/9576189/32128695-d0864da6-bb88-11e7-9b9b-cdbeefb557bc.jpg" width="200">

## Steps to Reproduce

1. Install launcher's telegram version or get the Lawnfeed if you have Lawnchair installed from GP
2. Just open the Google app

If I return to the stock launcher, Google feed launched from there looks like expected.
And even more, if then I get back to Lawnchair, I have an access to expected look of Google feed if Lawnfeed is not installed.

* Device: Samsung GS7
* Android version: 7.0
* Launcher version: Latest from GP
* Rom: Stock

Sorry for my english, I hope I was pretty clear

**Comment by RikKoedoot** [comment]
This is why google made the new Google now feed on the pixel 2. This is also a problem on like Google now launcher

**Comment by notabene00** [comment]
Google Now Launcher seems to look fine:
<img src="https://user-images.githubusercontent.com/9576189/32166680-aa6b7bc8-bd77-11e7-9683-3c8c28c441cf.jpg" width="200">

**Comment by nyancrimew** [comment]
We can not affect what the Google Feed looks like, the new Google Feed is only visible inside Googles own launchers (or when not using any launcher with Google integration). The only way some Lawnchair users (and hopefully eventually all of them) is if Google decides to show it to you on their server.
