### ISSUE TITLE
Crash or icon disappear when changing icon of appshortcuts when clicing on new icon on icon picker

### ISSUE THREAD

**Issue by YAJATapps** [Deletescape-Media/Lawnchair#886]
## Description
If i try to change icon of a app shortcut most disappears and some app shortcuts like of nova they cause a crash.

## Expected Behavior
It should change icon . No crash or icon disappearing should be there.

## Actual Behavior
Disappears on most crashes on some

## Steps to Reproduce
1.Download latest lawnchair 
2.drag any of nova app shortcut
3.try to change icon and click on new icon in icon picker it crashed
4.try same on play store it's my apps shortcut disappears from desktop

## Environment

Device: lyf wind 1
Android version: 5.1
* Launcher version:1.1.0.1478
* Rom:Stock

**Comment by divadsn** [comment]
I don't understand, could you please make a screen record?

**Comment by divadsn** [comment]
Got fixed, is working now.
