### ISSUE TITLE
Option to select Dock Icon Pack under Settings>Dock

### ISSUE THREAD

**Issue by faezen** [Deletescape-Media/Lawnchair#888]
I like to have a different icon pack for my dock. Can you add icon pack selector under Dock Settings too?

**Comment by clairekardas** [comment]
Tried long pressing on the icon you want to apply a different icon pack on, clicking edit and selecting the icon you prefer? You can do this in the dock too, it's even possible to set a different pack for each app on your homescreen with that.

**Comment by nyancrimew** [comment]
You can change icon packs on a per-icon basis, this is a better solution than having different icon packs for different groups of icons.
