### ISSUE TITLE
Galaxy S8 Oreo 8.0 Animation Bug when Returning to Home from Apps

### ISSUE THREAD

**Issue by derektm** [Deletescape-Media/Lawnchair#894]
## Description
When returning home from any app, the animation is weird and messed up. I have made a video here showing the issue: https://imgur.com/a/oyt2L.

The first 2 times, you can see it is wrong, the last time you can see it is right.

## Expected Behavior
Animation should transition correctly.

## Actual Behavior
Animation is wrong.

## Steps to Reproduce
https://imgur.com/a/oyt2L

Hit the home button from being in any app. Have Galaxy S8 on Oreo 8.0

## Environment
Galaxy S8 Oreo 8.0

* Device: Galaxy S8 Oreo 8.0
* Android version: Oreo 8.0
* Launcher version: Most recent
* Rom: Stock

**Comment by divadsn** [comment]
That's a bug with TouchWiz/Grace UX.

**Comment by derektm** [comment]
@divadsn 

It does not happen with Stock TouchWiz and did not happen on Nougat. It also does not happen with Nova.

**Comment by divadsn** [comment]
But Oreo for S8 is beta software, so we don't support it.
