### ISSUE TITLE
Idea: support third party plugins to show full screen pages, similar to Google Now

### ISSUE THREAD

**Issue by hundeva** [Deletescape-Media/Lawnchair#896]
Example:
- Left side screen: Google Now (like now)
- Center screen: Home screen (like now)
- Right side screen: Calendar screen

What I mean by this is, the mentioned Calendar screen would be:
- a downloadable, third party app, for example from the Play Store
- would take up a whole "page" in the launcher
- would not be a classic widget
- could use any type of `View`, not just the ones accessible via `RemoteViews`
- of course, the calendar is just one example, any type of "full screen pages" could be supported

I'm not sure how the Google Now plugin system works, I guess it could be (at least partly) reused for this. I'm planning to look into the feasibility of this whole stuff, when I will have a little bit of time.

Is this something that you could imagine being part of Lawnchair?

**Comment by divadsn** [comment]
You already can use a widget to scale on the entire page, so I don't see a need for that.
