### ISSUE TITLE
App shortcuts  another widget button glitch

### ISSUE THREAD

**Issue by agoogleuser** [Deletescape-Media/Lawnchair#903]
## Description
When I press an app icon that have both widgets and app shortcuts many times very quickly , sometimes another widgets button appear.

## Expected Behavior
It should appear without the other widgets button appear

## Actual Behavior
I think that's a glitch when the other widgets button appear , but it doesn't show always.

## Steps to Reproduce

1.find an app icon with widgets and app shortcuts like google calendar for examble.
2.hold the icon to reveal app shortcuts.
3.do step.2 many times very quickly untill you see new widget button next to edit button in the app shortcuts menu.

## Environment

* Device:Samsung Galaxy s4 (jfltespr)
* Android version:7.1.2
* Launcher version:1.1.0.1503
* Rom:Optimized LineageOS 14.1 version 8

**Comment by agoogleuser** [comment]
![](https://i.imgur.com/FSuAafG.png)

**Comment by TheShark27** [comment]
Yeah, I can reproduce it.

**Comment by divadsn** [comment]
That's the antenna for VoLTE.

**Comment by agoogleuser** [comment]
Well , it kinda funny glitch , but I hope also these weird lines as seen on my screenshot to be fixed.

**Comment by agoogleuser** [comment]
@divadsni sorry , but i didn't understand what you are meaning

**Comment by divadsn** [comment]
@agoogleuser it's a meme in our community, we are aware of that issue :)

**Comment by suphon-t** [comment]
@divadsn This issue is not about the antenna. There are two widget buttons in the popup.

**Comment by divadsn** [comment]
@paphonb lol, but I also saw the antenna :P
