### ISSUE TITLE
Navigation bar is dark on the widgets menu on Oreo.

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#908]
This is pretty much self explanatory.

![](https://i.imgur.com/dntJCHP.png)

**Comment by chinmaykunkikar** [comment]
@Treemindr can you give more details like if it's on 8.1 or 8.0? Also what theme do you use?
I'm not able to reproduce it. My navbar color stays white.

Edit: Also your widget menu looks different.

**Comment by LinuxLlama** [comment]
@chinmaykunkikar I'm on 8.0, I use a theme called Pixel UI but this happens when it's disabled. Also, this isn't the widget menu from long pressing and then tapping widgets, it's from the app shortcuts menu. (Long press app, then tapping widgets icon)

**Comment by chinmaykunkikar** [comment]
@Treemindr ah thanks! And yes I can reproduce that now and confirm.

**Comment by divadsn** [comment]
Caused by: https://github.com/Deletescape-Media/Lawnchair/pull/867
