### ISSUE TITLE
White lines around notification bubble

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#911]
This bug was submitted by **Adîtyä Mer** on Google Plus. Original post: https://plus.google.com/105968329629993668499/posts/aVNK4x18HVj

## Description
When are you going to fix this issue? I stopped using lawnchair for around like 10 days I came back and it's still there. (This seems to happen on smaller DPIs because I don't see this on my phone. ~reCoded)

## Screenshot
![capture](https://user-images.githubusercontent.com/29968331/32675251-1c968184-c60b-11e7-93fc-f6f0f4a9a366.PNG)

## Expected Behavior
There shouldn't be lines on the notification bubble from the app shortcut.

## Actual Behavior
There are lines on the notification bubble from the app shortcut.

## Steps to Reproduce

1. Enable notification badges
2. Get a notification
3. Long press it

## Environment

* Device: Lenovo k5 note
* Android version: Android 6.0
* Launcher version: 1.1.01507
* Rom: Stock (Unrooted)

**Comment by AxiK101** [comment]
Bug still there, latest ci build![](https://i.imgur.com/MlOvjQF.png)
![](https://i.imgur.com/FmjlG56.jpg)

**Comment by AxiK101** [comment]
![](https://i.imgur.com/GQX5wun.jpg)

**Comment by divadsn** [comment]
We are still humans, so don't get angry when we don't fix an issue immediately, many of us are busy with school or work life.
