### ISSUE TITLE
[Feature request] An option to pin homescreen icons

### ISSUE THREAD

**Issue by Dum4G** [Deletescape-Media/Lawnchair#912]
Hey there! Please add an option to lock the homescreen icons so I can't move them around. Thank you

**Comment by suphon-t** [comment]
Settings -> Behavior -> Lock desktop

**Comment by eggsgent** [comment]
This option is missing in current Lawnchair V2 alpha builds, please bring it back!

**Comment by skittles9823** [comment]
@eggsgent We plan on bringing back or improving all the features from v1. It'll be added eventually, its just a low priority right now.
