### ISSUE TITLE
Bug when spring effect is present (disappearing line)

### ISSUE THREAD

**Issue by theandroidenthusiast** [Deletescape-Media/Lawnchair#913]
## Description
When I slide up to get to the app drawer the line under the search bar of the app drawer disappears for just a second this also occurs when I scroll to the bottom of the app drawer and then scroll up. 

## Expected Behavior
Line remains there as it should. 

## Actual Behavior
Line disappears for a brief amount of time. 

## Steps to Reproduce
1. Open app drawer
2. scroll to bottom
3. scroll up and you will see the line under the seach bar disapper for a second and it will come back

## Environment
* Device: Samsung Galaxy S7 Exynos Duos
* Android version: 7.0
* Launcher version: 1.1.0.1527 
* Rom: Stock Rom

**Comment by LinuxLlama** [comment]
I've noticed this too. IMO the best fix would be having the separator line not bounce like the app icons.

**Comment by divadsn** [comment]
Already known and won't fix until Oreo 8.1 source has been released.
