### ISSUE TITLE
Hidden apps reappear after reboot

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#914]
## Description

Hiding apps on the app drawer doesn't survive reboots, to fix it I need to toggle "show hidden apps" on and off, and possibly hide some apps again.

## Expected Behavior

Nothing changes, hidden apps stay hidden.

## Actual Behavior

Some or all hidden apps reappear on the app drawer.

## Steps to Reproduce

1. Hide some apps

2. Make sure you "show hidden apps" is disabled

3. Reboot device

## Environment

* Device: A0001

* Android version: 7.1.2

* Launcher version: 1527

* Rom: Slim7 beta 0.27 Dev-DM

Not sure how I can grab a logcat of this since it requires a reboot... If needed, help will be appreciated ^^

**Comment by suphon-t** [comment]
Fixed by #921.
