### ISSUE TITLE
App shortcuts window bug

### ISSUE THREAD

**Issue by agoogleuser** [Deletescape-Media/Lawnchair#917]
![](https://i.imgur.com/004hu7p.png)
 This bug happens in folder putted in the middle of the gird 8n home screen , when there are 2x2 in the left one  or 4x4 with the same place

**Comment by agoogleuser** [comment]
I long pressed the jetaudio app and it appears in the wrong place


Also it happens like , I long pressed play store in this screenshot this![](https://i.imgur.com/CtVbpY8.png)

**Comment by divadsn** [comment]
Android Version? What device? Custom DPI?

**Comment by agoogleuser** [comment]
Sorry , 
Android 7.1.2 optimized LineageOS 14.1 version 8
Device : jfltespr
App version 1.1.0.1503
