### ISSUE TITLE
Repository needs a clever tagline

### ISSUE THREAD

**Issue by cascent** [Deletescape-Media/Lawnchair#918]
found this project because someone I follow starred it. as an iOS and Windows user, the concept of wanting to replace the OS shell makes no sense. the git repo description should be clever enough to make me smirk, before I retreat to the comfort of my walled garden

**Comment by nyancrimew** [comment]
The tagline should just be one thing, a tagline. "No Tagline needed" is actually indeed our tagline (as you can also see on our website). If you want to know more about the concept of "replacing the OS shell" or about what the project is in detail I think something like this would rather belong in a README than in the repo description
