### ISSUE TITLE
[Bug] Animated clock icon doesn't work with AOSP DeskClock

### ISSUE THREAD

**Issue by TheComputerGuy96** [Deletescape-Media/Lawnchair#919]
## Description

Note: I know that this issue exists, but it's closed (because it doesn't use the issue template found at your GitHub repository)

Like the title says, AOSP DeskClock (com.android.deskclock) icon doesn't animate (even with all animated clock icon-related options enabled)

Things that I tried:
* Disabling the icon pack I use from Lawnchair's settings
* Restarting Lawnchair (from Lawnchair's settings > Debug)
* Rebuilding the icon database (from the menu listed above)
* ...

## Expected Behavior

AOSP DeskClock icon should animate

## Actual Behavior

AOSP DeskClock icon stays completely the same

## Steps to Reproduce

1. Be on a ROM with AOSP DeskClock (LineageOS, RR, pure (non-Nexus or Pixel) AOSP etc.)
2. Download and install the latest CI version of Lawnchair
3. Go to Lawnchair's settings > Theme
4. Enable "Animated clock icon" and "Animate alternative clock apps" options
5. Go back to Lawnchair's app drawer and notice that AOSP DeskClock icon doesn't animate

![AOSP DeskClock icon doesn't animate](https://i.imgur.com/UfC88gf.png)

## Environment

* Device: Samsung Galaxy Trend Plus
* Android version: 7.1.2
* Launcher version: 1.1.0.1527
* ROM: AOSP 7.1.2

_Sent from my Galaxy Trend Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment]
Which version of the android deskclock do you have ?

https://github.com/Deletescape-Media/Lawnchair/commit/2afb19cba7924a2e0d0a4918a21c18008d165203#commitcomment-24577012
