### ISSUE TITLE
Enhancement/Bug? Padding on "Search Apps" oddly small

### ISSUE THREAD

**Issue by jacksonhvisuals** [Deletescape-Media/Lawnchair#92]
Hi,

I noticed that the padding ounder "Search Apps" is oddly small in Lawnchair compared to Launcher3 or Launcher3-based... launchers. (See photos. The one with a transparent drawer is the OnePlus launcher from the OP5)

https://goo.gl/photos/5TtPJxzi2wdbJD1A7

It would be awesome for this to be fixed!

(And @deletescape, I commend you for your incredible development. You've made so many dreams come true in regards to Launcher3/Pixel Launcher! Thank you so much!)

**Comment by deletescape** [comment]
Should already be fixed (but not yet released)
