### ISSUE TITLE
Missing adaptive icons (?)

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#927]
Can you force enable adaptive for these 3 google apps? We know they already support them but Lawnchair seems to ignore them.
Thanks![](https://i.imgur.com/A48uH1E.png)

**Comment by divadsn** [comment]
Not reproducable, Google Apps are working fine here. But we are looking into another similar issue.

**Comment by AxiK101** [comment]
I use xa ultra 7.0 stock
