### ISSUE TITLE
Custom colors for UI

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#932]
A lot of people on G+ want to be able to choose a custom color for the app drawer, dock, and folders. It would be nice to have each one be able to be colored differently **and have a transparency slider as well**. _This may be a lot to ask for..._

**Comment by tschlunk** [comment]
I would love it if the dock accent color could be customized more.

**Comment by jaduprey** [comment]
Dear Development staff,

Please please please add feature to customize color of dock.

Please please please.

**Comment by divadsn** [comment]
@jaduprey Please please please, give me time and some life ;_;

**Comment by skittles9823** [comment]
@divadsn NoU

**Comment by anirudhgupta109** [comment]
@skittles9823 Nonou

**Comment by divadsn** [comment]
@anirudhgupta109 no one asked you Anirudh

**Comment by anirudhgupta109** [comment]
@divadsn I go...

**Comment by bohrabhijeet** [comment]
@anirudhgupta109 You actually should..

**Comment by jaduprey** [comment]
@divadsn - fair enough. Thanks for the response. Greatly appreciated.

**Comment by jaduprey** [comment]
Same question:

Deletescape,

Does this mean it was incorporated in the LL?
