### ISSUE TITLE
Covers feature (app folder icon)

### ISSUE THREAD

**Issue by ajvsol** [Deletescape-Media/Lawnchair#933]
An alternative to regular app folders whereby you can choose to have an indicator (or none) on an app icon (see app folders at top, covers at bottom):

![](https://camo.githubusercontent.com/f25b1f18685c8833c43e373cd84fed246c2974f2/68747470733a2f2f7777772e616e64726f696463656e7472616c2e636f6d2f73697465732f616e64726f696463656e7472616c2e636f6d2f66696c65732f61727469636c655f696d616765732f323031352f30372f616374696f6e6c61756e636865722d636f7665722e676966)

Then swiping on the app in a certain direction will open the cover to reveal an app folder that looks like this:

![](https://camo.githubusercontent.com/9e583dc5f81f663a79018a3fb08eff346d19bd4a/687474703a2f2f692e696d6775722e636f6d2f41314666657a772e706e67)

**Comment by divadsn** [comment]
One question: Do we look like Action Launcher to kang their ideas? :grimacing:

**Comment by LinuxLlama** [comment]
@divadsn Nova Launcher has this feature too. It's actually quite useful.

**Comment by Starcr0ss** [comment]
@divadsn Is there any way that we could get this feature now?

**Comment by divadsn** [comment]
@Justin00015 we don't think so, it should be respected as it is a Action Launcher exclusive feature.

**Comment by anirudhgupta109** [comment]
Each launcher has it's own specialty, taking other launcher features and adding it is disrespectful af

**Comment by ajvsol** [comment]
This is on at Action, Nova and Apex Launcher so it's hardly an exclusive

**Comment by bohrabhijeet** [comment]
I'll let the devs know about your request. As I don't think they would implement the said feature.

**Comment by divadsn** [comment]
@neomodern Just because two other launchers kanged the idea doesn't mean we have to do the same. But we'll think about an own feature with a similar functionality in the future 🤗

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
This appears to be covered by the current reimplementation tracking issue #2659, as the old Cover Mode behavior still does not seem to be available in any current Lawnchair release.

- #2659

Yes, the feature exist in Lawnchair Legacy version 9.1 alpha 3
