### ISSUE TITLE
Two dock icon "merge"

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#934]
This bug report was submitted by **Gaëtan Brulin** on Google+. Original post: https://plus.google.com/113406248811217771931/posts/H32rJ7AW7Q7

## Description

Sometimes, icons with two lines dock move bottom icons to the top line.

##  Video
https://imgur.com/a/HDzWL

## Expected Behavior

The bottom row icons stay where they are when edited.

## Actual Behavior

The bottom row icons move up and merge with the top row.

## Steps to Reproduce

1. Enable two-row dock.
2. Have icons/widgets on the top and bottom row.
3. Long press an app on the bottom row.
4. Tap edit.
5. Tap anywhere outside of the edit dialog box and the icons will jump up to the top row.

## Environment

* Device: Nexus 5X
* Android version: 8.1 Developer Preview
* Launcher version: 1.1.0.1559
* Rom: Stock

**Comment by RikKoedoot** [comment]
This happened for me too

**Comment by suphon-t** [comment]
Fixed with 6b0b2ff
