### ISSUE TITLE
Weather not showing

### ISSUE THREAD

**Issue by NathanFrederick** [Deletescape-Media/Lawnchair#937]
Open weather map not working it says error when I press and hold down on the date and month that when it says error it would be great if if it gets fixed. phone version 7.1.1

**Comment by divadsn** [comment]
Please check your Location, as this happens only when the location is wrong.

**Comment by NathanFrederick** [comment]
I checked my location I put the city and state and it still says error but if I just put in the city name then it works and gives the wrong temperature it's like way off

**Comment by divadsn** [comment]
Then it works fine, the temperatures are not our fault, it's usual for different weather providers.
