### ISSUE TITLE
Strange spring effect on app search

### ISSUE THREAD

**Issue by burakdede0** [Deletescape-Media/Lawnchair#938]
## Description
Search for more apps part in app search acts different than apps

## Expected Behavior
Search for more apps part should move with apps

## Actual Behavior
Search for more apps part moves different than apps

## Steps to Reproduce

1. Type a letter to app search
2. Move up and down (to see spring effect)
3. See the difference between apps and search for more apps part

## Environment

 - Latest Ci build
 - Android 7.1.2

**Comment by divadsn** [comment]
Confirmed
