### ISSUE TITLE
Voice command "OK Google" not working 

### ISSUE THREAD

**Issue by adityautla** [Deletescape-Media/Lawnchair#94]
"OK Google" voice command is not working on the homepage. 
Kindly resolve this issue. 

Any way, the launcher is great. Kudos mate

**Comment by deletescape** [comment]
I don't see how this would be related to the app itself in any way, but I'll try to find out why

**Comment by OvermindDL1** [comment]
> I don't see how this would be related to the app itself in any way, but I'll try to find out why

Many phones do not have always-on-ok-google-detection due to lack of hardware in them, thus it is the launcher itself that listens to it when the launcher is on the main screen only, only some launchers.

**Comment by ravensousa** [comment]
I can also verify the issue if I use assistant via the Nova method as I've already gotten it both the Nova ok Google and your pill assistant button cause Google to crash and it's only happened since your update

**Comment by ravensousa** [comment]
Also I'm someone who already had native ok Google

**Comment by intelligentcasanova** [comment]
Still an issue? @deletescape

**Comment by ravensousa** [comment]
Not anymore thanks
