### ISSUE TITLE
Piracy Check AGAIN?

### ISSUE THREAD

**Issue by CaKrome** [Deletescape-Media/Lawnchair#940]
## Expected Behavior
It opens a prompt to select icon packs.

## Actual Behavior

It says "This device has a few piracy tools installed. Please uninstall them to continue."

## Steps to Reproduce

1.Install some "piracy tools"
2.Open "Settings"→"Theme"
3.Click "Icon Pack"

## Environment

Device: Xiaomi Redmi Note 4 "mido" 
Android version: 7.1.2
Launcher version: 1.1.0.1583
Rom: LineageOS 14.1

**Comment by LinuxLlama** [comment]
This is normal behavior. The privacy check was never removed.

**Comment by CaKrome** [comment]
Just checked this [unmerged PR](https://github.com/Deletescape-Media/Lawnchair/pull/905), it seems that only icon packs function is restricted if user installed some piracy tools.
Also saw the discussion in [reddit](https://www.reddit.com/r/Android/comments/7azc2i/psa_lawnchair_launcher_now_with_more_censoring/)
I understand why you developers never remove this piracy check for some reasons. But I actually don't want to see the whole world is going to kill piracy, result in everyone has to pay a lot of money to buy things before testing them, in that case, piracy is actually try before buy.
Emmm... OK,  I will fork and make my own one.

**Comment by divadsn** [comment]
Just FYI: You can pirate apps without using those fishy apps :wink:

Or just use the 48h refund period to refund the apps you've tried but don't liked.

**Comment by tejasetty** [comment]
100% Truth- A launcher has no business deciding what I should use it to launch. That's my job. Launchers job is to launch my decision.

**Comment by divadsn** [comment]
You can launch whatever you want, get your facts right before writing spam.

**Comment by suphon-t** [comment]
100% Truth- You replies to a 7 months old issue and Lawnchair doesn’t prevent you from launching your apps.

**Comment by tejasetty** [comment]
@paphonb  Lol....it doesnt matter how old...but have checked just now...still issue preset :-1:

**Comment by divadsn** [comment]
@tvteja are you blind? The mentioned thing wasn't even merged and is now only in use to prevent illegal use of pirated iconpacks and there is a reason behind that.

**Comment by tejasetty** [comment]
@divadsn  is it? then why its asking to remove pirate apps ("_This device has a few piracy tools installed. Please uninstall them to continue_.") its non of your bushiness

**Comment by suphon-t** [comment]
No. Lawnchair doesn’t prevent you from launching apps you want. Your point is invalid.

**Comment by divadsn** [comment]
@tvteja it is our business to prevent you from abusing Lawnchair to use pirated iconpacks.
In many countries such practise would make us as a tool illegal too.

**Comment by tejasetty** [comment]
@paphonb  Read Purpose of thread first, this is the reason i posted here

Expected Behavior
It opens a prompt to select icon packs.

Actual Behavior
It says "This device has a few piracy tools installed. Please uninstall them to continue."

**Comment by bohrabhijeet** [comment]
@paphonb But sir I want my 'launcher' to 'launch' my apps please help I'm blind.

**Comment by divadsn** [comment]
@tvteja selecting iconpacks != launching apps

**Comment by tejasetty** [comment]
@divadsn 100% Truth- A launcher has no business deciding what apps i use. That's my job. Launchers job is to launch my decision.

Is it fine now?

**Comment by divadsn** [comment]
We launch whatever you want, but we won't allow you to use our app to apply illegal iconpacks, get it.

**Comment by tejasetty** [comment]
@divadsn i havent used any pirated icon packs. know facts before post. As a developer like you i use many tools for my development

**Comment by divadsn** [comment]
@tvteja then why does it bother that you get that message? :thinking:

**Comment by tejasetty** [comment]
@divadsn  thats why am asking you why? and what i want to say finally is i dont have any rights to demand you. as a android lover,developer i like Lawnchair so i just trying to resolve issue..(seems not only me, i had read so many post regarding same on xda).hope you people understand

**Comment by divadsn** [comment]
@tvteja because of the fact that iconpacks cannot prevent the use themselves and we respect the work of every iconpack designer.

**Comment by tejasetty** [comment]
@divadsn  not only you i too respect iconpack designer and all app developers also. i know how much hard work will be there behind. but issue is i haven't used any pirated icon pack app and not sure why issue still comming
(Note: not only pirated apps i wont use any pirate apps like lucky patcher etc.. only device got rooted(systemless magisk) and u know rooting is necessary for development)

**Comment by msfjarvis** [comment]
> only device got rooted(systemless magisk) and u know rooting is necessary for development)

I build an app with over a million downloads on an unrooted Google Pixel 2 running stock software, just saying...

**Comment by tejasetty** [comment]
@divadsn and @paphonb you people still want to keep like this then at least change string message as
""This device has a few **piracy icon pack**s installed. Please uninstall them to continue."

**Comment by tejasetty** [comment]
@MSF-Jarvis not everyone ...apps development based on requirement... if you ask mine my task involves development of networking app which required to root for test

**Comment by divadsn** [comment]
@tvteja no, we look after piracy apps, not after iconpacks, get the point.

**Comment by msfjarvis** [comment]
> development of networking app which required to root for test

I intern at [WireGuard](https://wireguard.com) and develop their Android app on that same unrooted phone 🙂

**Comment by tejasetty** [comment]
@MSF-Jarvis  Great and Appreciated,. Not everyone like you. here i cant share my task but what i want to say is rooting is necessary for that

**Comment by suphon-t** [comment]
@tvteja I develop Xposed modules and I understand that root might be required. But I can’t imagine any situation that you’d need piracy tools to develop.

**Comment by tejasetty** [comment]
@paphonb Thanks but please try to get the my point. telling again i haven't used any pirated apps ...only device got rooted.

**Comment by xdevs23** [comment]
If you think your launcher does not match your expectations, please consider using a different launcher or implement the desired functionality yourself. If the developers decide to implement measures against piracy then that's what you get. The point is not what the job of a launcher is. You decide which launcher you use and thus end of discussion.

**Comment by fonix232** [comment]
@tvteja just get over it. Lawnchair will not allow possible piracy (i.e. using icon packs) when there's a chance of the icon pack being pirated, by using a third party tool (like Lucky Patcher), it WILL disable the icon pack feature.

Go and look into the code, the list of apps triggering it are pretty clearly stated. And I don't see how you'd need Lucky Patcher, or Uret patcher - which are pretty much the only packages currently blacklisted. So either remove these apps - because you don't need them for development at all - or stop fucking whining.

**Comment by tejasetty** [comment]
All, thanks for your reply. Let's make end of this discussion ☺️

**Comment by arpitnnd** [comment]
@tvteja You had been trying to 'make a point' all this time and you don't even have one.
Let me simplify things for you:
Lawnchair doesn't stop you from launching anything.
Lawnchair stops you from using an icon pack if you have certain piracy apps installed.
Being a developer you should be capable enough to go through a bit of code & figure of which apps are blacklisted.
Nobody needs piracy tools for development of anything other than those tools themselves.
If you actually aren't using any blacklisted stuff you could have continued this conversation with a very different approach.

I don't even use Lawnchair but, could still figure the first two out from the comments. Why can't you?

@divadsn Maybe, to avoid a commotion like this, just show a pop-up with a list of blacklisted apps on first icon pack selection attempt.

**Comment by bohrabhijeet** [comment]
@arpitnnd Thanks for adding shit to this issue which is irrelevant and not even an issue. All the icon pack developers aren't working for free for days and nights investing numerous hours while making icon packs for users. If you have piracy tools installed, Lawnchair WILL stop you from applying the icon packs even if you use the piracy tools for stuff like blocking ads or making it a system apps. Google the alternate solutions for both of them if that's the case. @deletescape please close this issue as it's completely irrelevant and doesn't belong here at all. Thanks.
