### ISSUE TITLE
[Bug] Other applications cannot create shortcuts at Lawnchair (Android 8.0)

### ISSUE THREAD

**Issue by fython** [Deletescape-Media/Lawnchair#942]
## Description
Other applications cannot create shortcuts in runtime. It happens on Android 8.0.
There is something about App Shortcuts changed since Android 8.0: [Use Pinned Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html#pinned)
We app developers need check if `ShortcutManager.isRequestPinShortcutSupported()` returns `true` before creating shortcuts. But when I set Lawnchair as default launcher, it returns `false` and I cannot create shortcuts.

## Expected Behavior
Successfully add some shortcuts to homescreen in other applications.

## Actual Behavior
No shortcuts added.

## Steps to Reproduce
No screenshots.

1. Open Google Chrome / [PinSettings](https://github.com/fython/PinSettings) (My little app)
2. Try to add shortcuts to homescreen
3. No dialogs pop up. Nothing happen.

## Environment

* Device: OnePlus 3T
* Android version: 8.0.0
* Launcher version: 1.1.0.1583 (The problem may exists a long time)
* Rom: Oxygen OS Open 18 for OnePlus 3T

## Logcat
No logs.

**Comment by divadsn** [comment]
Oh yeah, that is already known bug, I'll look into this today.

**Comment by fython** [comment]
It boreds me a long time. I usually use lite (web) apps from WeChat and Chrome. And I couldn't add them to my launcher.

**Comment by jise** [comment]
This bug is still present in Lawnchair version 1.1.0.1834.
Xiaomi Mi A1 8.0.0.

**Comment by zxspectrun** [comment]
Samsung s8 plus with android 8, I can create firefox shortcuts neither
