### ISSUE TITLE
Crash right after starting Lawnchair Launcher

### ISSUE THREAD

**Issue by prograMAnimus** [Deletescape-Media/Lawnchair#944]
## Description
After the recent update to 1.1.0.1583 Lawnchair keeps crashing everytime it is started and/or set as default home launcher.
No previous version ever gave this behaviour, as it worked correctly right after updating.
I had to revert to the previous version in order to continue using Lawnchair.

## Expected Behavior
Starting Lawnchair as it did the previous version, showing my icons on the home screen and providing the look&feel I'm used to.

## Actual Behavior
Crashing right after starting the launcher with the "... has stopped working" notification.
Restarting and/or waiting for the launcher does yield the same outcome.

## Steps to Reproduce
https://i.imgur.com/H9ZWY69.mp4

1. Download and Install Lawnchair through Google Play
2. Start the Launcher

## Environment

* Device: OnePlus Two (ONE A2003)
* Android version: 7.1.2
* Launcher version: 1.1.0.1583
* Rom: LineageOS 14.1-20171109-NIGHTLY-oneplus2

**Comment by divadsn** [comment]
READ THE CHANGELOG PLEASE.
