### ISSUE TITLE
Explain necessity of permissions on Google Play

### ISSUE THREAD

**Issue by Hocuri** [Deletescape-Media/Lawnchair#945]
You could maybe explain what the app needs the permissions for on the Google Play page. For me, personally, this makes an app more trustable. And it is not immediately obvious what a launcher needs e.g. Internet for (there is probably an easy explanation but I don't know what it is).

**Comment by nyancrimew** [comment]
The internet permission is used to optionally display the current weather to the user.

**Comment by Hocuri** [comment]
Like I said, an easy explanation...
Now, what do you think of my proposal (explaining this on the Google Play page)?

**Comment by fonix232** [comment]
I don't think it is necessary. Looking at the features list, each and every
permission is easily explained. E.g. internet - weather. Location -
weather. And so on.

**Comment by Hocuri** [comment]
> Looking at the features list, each and every permission is easily explained.

I can't find this features list, where is it? There is a features list on the Google Play page but it says nothing about the weather feature.

**Comment by jise** [comment]
Click to https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah&hl=en
At the bottom of the page you see ADDITIONAL INFORMATION, click to View details in Permissions tile, where every permission is explained in detail. If you know your launcher well you can immediately connect every permission with various Lawnchair functions. There is really no problem at all. Try to check another well established launchers, like Nova, etc.

**Comment by divadsn** [comment]
@deletescape, but the phone permissions could be explained tho.

**Comment by Hocuri** [comment]
> If you know your launcher well you can immediately connect every permission with various Lawnchair functions.

I rather thought of users that do not know Lawnchair yet.

An example for an app that explains why the permissions are needed is vlc:
https://play.google.com/store/apps/details?id=org.videolan.vlc
You have to click on "READ MORE" and scroll down a bit:

> It needs "full network access", to open network and internet streams.
> It needs "prevent phone from sleeping" in order to prevent... your phone from sleeping when watching a video.
> ...
