### ISSUE TITLE
Suggestion. Make folders pretty.

### ISSUE THREAD

**Issue by GAZ082** [Deletescape-Media/Lawnchair#947]
Yep. Right now they are just black ugly squares, make them more pretty!

Thanks.

**Comment by divadsn** [comment]
What? Never seen a black square folder.

**Comment by guest4711** [comment]
![I think he means the black background](https://i.imgur.com/9ZKnxPA.jpg)

**Comment by guest4711** [comment]
I think he means the black background...

**Comment by GAZ082** [comment]
Once my continuous force closes stop I'll post some captions myself. Thanks for yours!

**Comment by AxiK101** [comment]
I think they just need the new animation, otherwise folders are good

**Comment by GAZ082** [comment]
Yeah, I believe i was too picky that day. Folders look nice enough.

**Comment by fonix232** [comment]
Especially if you add blur ;)
