### ISSUE TITLE
[Bug] Lawnchair keeps failing

### ISSUE THREAD

**Issue by wovalle** [Deletescape-Media/Lawnchair#948]
I can't use lawnchair because it keeps failing.

## Description
Since the past ~12h (probably because of an update from the play store) I can't use lawnchair because it keeps failing (screenshot attached). I don't know where I should see the logs in order to have a more detailed explanation of what's going on (can't use logcat, not root). Tried force closing it and reinstalling from play store. I already sent feedback through play store.

## Expected Behavior
Lawnchair should work just fine.

## Actual Behavior
It's unusable because it keeps failing after trying to use it.

## Steps to Reproduce
1. Open lawnchair
2. It crashes.

## Environment
* Device: Google Nexus 6P
* Android version: 8.0.0 (November 5 Security patch)
* Launcher version: 1.1.0.1583 (Play Store)
* Rom: Stock

![2017-11-20 15 18 12](https://user-images.githubusercontent.com/7854116/33036867-1998a478-ce06-11e7-9f74-1e199b5c7872.jpg)

**Comment by nyancrimew** [comment]
Read the update changelog on the PlayStore, it tells you what to do.

**Comment by wovalle** [comment]
Thanks @deletescape!

I didn't read the changelog.  Had to uninstall and install Lawnfeed, it works good now. I think this is a great candidate to be in the FAQ or just ask to re-install Lawnfeed if the condition is met (don't know the complexity of this).

Anyway, closing issue.
