### ISSUE TITLE
[Bug] Blank First Page Appears After Icon Database Rebuild

### ISSUE THREAD

**Issue by tschlunk** [Deletescape-Media/Lawnchair#949]
## Description
Sometimes when returning to the home screen from an app or Lawnchair settings, my first page appears blank (dock is unaffected). I realized that actually my first page has been shifted to the right and replaced with a blank first page. This page can be deleted normally and disappears on its own when any icon or widget that got moved to the second page is long-pressed.

## Expected Behavior
My apps should stay on the first and only page.

## Actual Behavior
When the bug is triggered (still figuring out the exact cause - I would upload my settings and database backup but restoring after a new install doesn't cause the bug immediately), a new page is created and my home screen appears blank.

Note: sometimes this bug leads to the bug where overview mode is unable to be entered by long-pressing a blank space. Last time I encountered this bug I ended up in an infinite loop of fixing one bug and causing the other.

## Steps to Reproduce
1. Trigger the bug with some action or toggle (I tried isolating a setting that causes it to no avail).
2. Add icons or widgets to the desktop.
3. Rebuild icon database (or toggle a setting that does so).
4. Return to a blank first desktop page.

[VIDEO DEMONSTRATION](https://t.me/lccommunity/49035)

## Environment
* Device: ONEPLUS A3000
* Android version: 7.1.1
* Launcher version: 1.1.0.1583 (Play Store version) - have experienced bug on previous builds
* Lawnfeed version: 1.1.0.1583
* Rom: Stock OxygenOS 4.5.1 (stable release)

**Comment by LinuxLlama** [comment]
If I simply change a setting in the settings menu, it creates a blank page. I don't need to rebuild icon database.

**Comment by tschlunk** [comment]
What settings did you identify as causing it? Is it all of them? Or is it just a few that could be related to triggering the bug in the first place?

**Comment by LinuxLlama** [comment]
@ChillMasterT It seems that all of them cause this issue.

**Comment by RikKoedoot** [comment]
I have the same issue, this even occurs with setting a new wallpaper.

**Comment by tschlunk** [comment]
@rickkode I observed this too. It's possible setting the wallpaper is what triggers the bug in the first place.

**Comment by ghost** [comment]
Same for me. Sometimes only wake up from sleep mode makes an empty desktop on the first position.

BQ M5 Stock ROM (Android 7.1.2)
Lawnchair version 1.1.0.1742

**Comment by moshpirit** [comment]
Same with 1.1.0.1872 (F-droid) on official ROM Android 7.1.2

**Comment by divadsn** [comment]
@moshpirit k

**Comment by devarni** [comment]
This bug is still there... For some reasons after restarting or changing stuff I see this first blank page.

**Comment by wallaschek** [comment]
Why was this issue closed? Still affected with 1.2.1.2001 on Moto One Vision Stock ROM (Android 9, Build PSAS29.137-17-2)

**Comment by RikKoedoot** [comment]
Because this GitHub only is about lawnchair v2 now, lawnchair v1 is not supported anymore.
