### ISSUE TITLE
Weird left right margin on dock

### ISSUE THREAD

**Issue by ndzaky97** [Deletescape-Media/Lawnchair#95]
I got a big space margin on dock and I think it's probably because I'm using a custom dpi. Please take a look

**Comment by ndzaky97** [comment]
Screenshoot: http://imgur.com/htHLxgL

**Comment by fonix232** [comment]
It seems like an improper padding is applied. Could you please detail your settings (device, original DPI, your custom DPI)?

**Comment by ndzaky97** [comment]
I just find out that restarting launcher fix this issue.
Original 320, custom 290.
