### ISSUE TITLE
Wallpaper Scrolling option 

### ISSUE THREAD

**Issue by TheABvolt** [Deletescape-Media/Lawnchair#951]
## Description

Lawnchair has to the default Android behaviour of scrolling when there are multiple home screen pages.

## Expected Behavior

There should be an option for disabling this, and centring the wallpaper 

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by divadsn** [comment]
Take a look into the behavior settings next time ;)
