### ISSUE TITLE
Weird behaviour since merging #946

### ISSUE THREAD

**Issue by Younes-L** [Deletescape-Media/Lawnchair#957]
For quick access : #946

When an action is pressed, the animation for exiting overview is... Well, there's no animation, it jumps and it doesn't look good imo :/

Plus when I open the widget drawer and hit the back button, [this](https://photos.app.goo.gl/mxXCDyBl3DJvFtwJ3) happens and all the widgets are reloaded for some reason

Without coming out as rude, I'd like to ask about the benefits of this change :)

**Comment by divadsn** [comment]
Indeed, haven't tested out other ways. Ask the PR author.

**Comment by divadsn** [comment]
@enricocid I've reverted your PR, please fix it and ensure it **works as intended** :)

**Comment by divadsn** [comment]
No response from original PR author :/
