### ISSUE TITLE
False Positive Piracy Check

### ISSUE THREAD

**Issue by yodahuang** [Deletescape-Media/Lawnchair#961]
## Description
I got my new phone and install all my apps through Google Play with absolute no piracy apps. However, when I apply icon pack I found myself blocked. I dive into the code and I don't see myself using any of the applications from BLACKLIST.

## Expected Behavior
I apply the icon pack I bought successfully.

## Actual Behavior
I was blocked due to "piracy apps"

## Steps to Reproduce
Null

## Environment
* Device: Essential Phone PH-01
* Android version: 7.1.2
* Launcher version: 1.1.0.1594
* Rom: Stock Rom

**Comment by burakdede0** [comment]
Update to 1.1.0.1617

**Comment by yodahuang** [comment]
According to the release page the latest version is 1.1.0.1594?

**Comment by burakdede0** [comment]
Release page has stable releases only. Download it from t.me/lawnchairci

**Comment by divadsn** [comment]
It's been due to an old app which shouldn't be shipped anymore and it's package name was mostly abused for malware and piracy apps.

**Comment by guest4711** [comment]
It would be nice if the errormessage would tell the culprit...

**Comment by divadsn** [comment]
Got already fixed.
