### ISSUE TITLE
Switch between original Pixel and Pixel 2 styles

### ISSUE THREAD

**Issue by thecyclichedgehog** [Deletescape-Media/Lawnchair#962]
## Description

Make it possible to switch between original Pixel launcher style to Pixel 2's. I mean search bar in Doc area and calendar/weather/alarm widget in top

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by nyancrimew** [comment]
Duplicate of #811

**Comment by guest4711** [comment]
But #811 is not open anymore..  (closed 2017/10)
