### ISSUE TITLE
Flat style popup is gone

### ISSUE THREAD

**Issue by burakdede0** [Deletescape-Media/Lawnchair#963]
It's gone after settings redesign or Pixel 2 style notification changes.

**Comment by Younes-L** [comment]
True 🤔
I wonder since when

**Comment by AxiK101** [comment]
It's a shame

**Comment by LinuxLlama** [comment]
@Younes-L Since the Pixel 2 shortcuts were added.

**Comment by divadsn** [comment]
I guess we'll wait until VoLTE antennas got fixed.
