### ISSUE TITLE
Lawnfeed detected as malware

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#966]
Hi! I'm a huge fan of Lawnchair, and was planning on installing Lawnfeed. Being the paranoiac I am, I uploaded it to Virustotal. Surprisingly, it came up as a PUP and Malware according to 2 out of the 60 scanners. Can someone please put my mind at ease about Lawnfeed? Thank you ☺

**Comment by divadsn** [comment]
Look into the source, we don't supply any Malware.

**Comment by divadsn** [comment]
Also, those 2 are irrelevant AV and they will always be triggered, look at the major ones.

**Comment by ghost** [comment]
Alright, thank you! Sorry for being paranoid XD
