### ISSUE TITLE
Add desktop lock/unlock to the long press menu

### ISSUE THREAD

**Issue by devgar** [Deletescape-Media/Lawnchair#967]
Add a fourth icon to the long press menu (with background, widgets and settings) for fast switching the desktop lock.

It will be great for when a new app wins your heart but you can't add it to you desktop because it's locked.

**Comment by LinuxLlama** [comment]
This would make the menu look cluttered IMO.

**Comment by divadsn** [comment]
Adding additional icons breaks the minimal design and it would be accidentally tapped on/off, so we'll keep the switch.
