### ISSUE TITLE
Status bar colour changes when drawer open

### ISSUE THREAD

**Issue by JonnyTech** [Deletescape-Media/Lawnchair#970]
When I open the drawer, the status bar icons colour changes making them difficult to see - see [attached video](https://github.com/Deletescape-Media/Lawnchair/files/1511031/status.zip) (it's only 50k).

Is it possible to keep the colour the same regardless of the drawer state?

Android 7.1 Lawnchair 1.1.0.1594

**Comment by divadsn** [comment]
Attachment is a zip file?

**Comment by JonnyTech** [comment]
Yes, GitHub prohibits uploading videos, so I zipped it up.

**Comment by divadsn** [comment]
It's possible, look in the behavior and theme settings.

**Comment by JonnyTech** [comment]
Thanks for the pointer, found it: settings >> theme >> apply theme on >> dock & drawer
