### ISSUE TITLE
Notification related crash

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#971]
Found this by complete chance and will probably be difficult to reproduce.
I long pressed YouTube icon to look at a notification then decided to swipe it away to dismiss it. A split second after swiping it away another YouTube notification came in and caused an fc.

**Comment by divadsn** [comment]
Now how we are supposed to recreate it? :P

**Comment by shuli81** [comment]
@divadsn
I would probably write a little app that spams notifications and try to recreate the crash with it
