### ISSUE TITLE
Can't update Lawnfeed

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#974]
Hi team ! 
Since yesterday and the last update of Lawnchair, I've a notification about Lawnfeed update. Bit I can't update Lawnfeed because of a bug (see screenshot attached). 
And the notification loops...
![screenshot_20171201-071902](https://user-images.githubusercontent.com/15948522/33470442-99b274e4-d668-11e7-8f3b-3d65a5285ae4.png)

--Edit--
I find a workaround : uninstall Lawnfeed, try to launch it from Lawnchair by swipping from left to right. It proposes to install Lawnfeed and miracle! It's the new version ! Annnnddd problem gone!

**Comment by divadsn** [comment]
It's due to a wrong and missing package signing, has been fixed with commit 4c2626fa2ff51bc2ae6393bf24a38e61ecbf4976.
