### ISSUE TITLE
Unread badge blacklist (feature request)

### ISSUE THREAD

**Issue by YoshiRulz** [Deletescape-Media/Lawnchair#975]
Currently, the Google search app is getting badged even though it only provides a static weather notification. I propose to let users add apps (e.g. Google search, music players) to a "badging disabled" list. Action Launcher has a similar feature but as a whitelist, disabling badges on all existing and newly installed apps by default.

[Edit: better explaining myself w/ more use cases]

**Comment by divadsn** [comment]
Well, a blacklist isn't the best idea, as sometimes I receive related to my Now feed notifications.
