### ISSUE TITLE
Notification dots

### ISSUE THREAD

**Issue by SebinChacko** [Deletescape-Media/Lawnchair#976]
Issue with notification dots.. it's not showing for missed calls only..it's showing in notification pannel, but not in app.And also.some.of the backported shortcuts don't work for many apps.
Lawnchair PS version 1.1.0.1667
Device. Lenovo Vibe a7010
Version 6.0
![screenshot_2017-11-15-13-10-49-758](https://user-images.githubusercontent.com/32730383/33512954-893d40d8-d75f-11e7-8a31-120b096fe518.jpeg)

**Comment by divadsn** [comment]
And now what? How are we supposed to reproduce it?

Or are you going to send us a Lenovo device? ;)

**Comment by SebinChacko** [comment]
Okaii no.prob ill give u that phone..😂
Jus try to solve this issue. Cuz I like this lawnchair
Idk why it's not showing buh when m using Nova, it's actually showing the dots for calls.

**Comment by SebinChacko** [comment]
Plss solve this. If u can😇
