### ISSUE TITLE
App shortcuts alignment in RTL

### ISSUE THREAD

**Issue by YanovskyOr** [Deletescape-Media/Lawnchair#977]
## Description
Using a right-to-left alignment messes up app shortcuts position.

## Expected Behavior
App shortcuts pop-up opens right above long-pressed icon.

## Actual Behavior
App shortcuts pop-up opens far from the app icon.

## Steps to Reproduce
1. Use RTL (e.g. Hebrew) system language
2. Long press icon.

## Environment
Device: Samsung Galaxy J7 2016
Android version: 6.0.1
Launcher Version: 1.1.0.1655
Rom: Stock Samsung Rom

## Logcat

![screenshot_20171202-143237](https://user-images.githubusercontent.com/21991428/33515721-9e165b56-d76f-11e7-9e9b-cecc50996c36.png)

**Comment by BabiApps** [comment]
Confirm.
Have it too in my Kenzo (NitrogenOS 8.1).
Launcher Version: 1.1.0.1742
