### ISSUE TITLE
Add feature to app drawer

### ISSUE THREAD

**Issue by Joni5664** [Deletescape-Media/Lawnchair#98]
It would be cool of the keyboard could open once app drawer is opened so all you have to do is search for the app by typing and press enter to open it. Hope that makes sense.

**Comment by fonix232** [comment]
It makes sense, however it won't be a default feature, especially since the app drawer is only available by pulling up (which makes the exact point of when to open the keyboard neigh impossible to set). For now, this won't be added.

**Comment by OvermindDL1** [comment]
> It makes sense, however it won't be a default feature, especially since the app drawer is only available by pulling up (which makes the exact point of when to open the keyboard neigh impossible to set). For now, this won't be added.

As a side idea, if a button for opening the app drawer is added then the old google launcher auto-focused the app search bar when pressing and holding the app drawer button for a third second, where tapping it just opened it as normal

**Comment by deletescape** [comment]
@Joni5664 Long pressing on the handle (the arrow thing above the dock) opens the drawer and focuses the search bar, I think this is just what you are searching for

**Comment by paphonbth** [comment]
Long pressing the handle acts like long pressing a blank workspace. Normal click works as expected tho.

**Comment by Joni5664** [comment]
It's like when you swipe down for search and the keyboard automatically opens that's what I was trying to say. I also run  Sony's Xperia Home Launcher and that feature works well.
