### ISSUE TITLE
Lawnchair crashes on start after upgrading to Android 8.1

### ISSUE THREAD

**Issue by Exter-N** [Deletescape-Media/Lawnchair#982]
## Description
I recently upgraded my devices to Android 8.1 "Oreo MR1". After that, Lawnchair began to systematically crash on start. I don't know if the bug appears if the device is already running Oreo MR1 when Lawnchair is first installed.

## Workaround
If I go to my device's settings and manually grant the Storage permission to Lawnchair, it starts functioning normally again.

## Expected Behavior
Lawnchair should have displayed my home screen, as it did before the upgrade.

## Actual Behavior
After entering my PIN code/unlock schema just after the upgrade, I saw a pop-up saying that Lawnchair crashed and a menu asking me to choose between the launchers installed on my devices. Same thing after selecting Lawnchair in the menu, whether it popped up after a crash or by pressing the Home button.

## Steps to Reproduce
1. Upgrade to Android 8.1 "Oreo MR1"
2. Boot the device
3. Unlock the device

## Environment
* Device: Nexus 6P / Pixel C
* Android version: 8.1.0
* Launcher version: 1.1.0.1655
* Rom: Stock Rom

## Logcat
```
12-06 11:22:51.433 18341 20011 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-3
12-06 11:22:51.433 18341 20011 E AndroidRuntime: Process: ch.deletescape.lawnchair, PID: 18341
12-06 11:22:51.433 18341 20011 E AndroidRuntime: java.lang.SecurityException: read wallpaper: Neither user 10291 nor current process has android.permission.READ_EXTERNAL_STORAGE.
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2004)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1950)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:481)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:458)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:412)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:391)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:538)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at ch.deletescape.lawnchair.blur.BlurWallpaperProvider.updateWallpaper(Unknown Source:68)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at ch.deletescape.lawnchair.blur.BlurWallpaperProvider.access$updateWallpaper(Unknown Source:0)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at ch.deletescape.lawnchair.blur.BlurWallpaperProvider$mUpdateRunnable$1.run(Unknown Source:2)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-06 11:22:51.433 18341 20011 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by LinuxLlama** [comment]
Seems like blur is one of the culprits.

**Comment by nyancrimew** [comment]
We currently have a few problems supporting 8.1. Some wallpaper related APIs have been changed, but they are not very well documented (or atleast have not been before the 8.1 source dropped) We'll definetly look into this

**Comment by divadsn** [comment]
It's due to some stupid API changes in Oreo 8.1, you need to give Lawnchair storage permissions in order to access the Wallpaper image. Don't worry, we'll add it surely with another Oreo update asap.

**Comment by LBYPatrick** [comment]
I found a page from Google that might be useful for solving this issue: [Click here](https://developer.android.com/about/versions/oreo/android-8.1.html#wallpaper)

**Comment by LBYPatrick** [comment]
According to [8.1's API Documentation](https://developer.android.com/reference/android/app/WallpaperManager.html), the method **peekWallpaperBitmap()** is now deprecated, or say the entire **Globals** subclass is deprecated (So **getCurrentWallpaperLocked()** is also not available on Oreo 8.1). Instead, it shows that you should use **WallpaperManager.peekDrawable()** or **WallpaperManager.getWallpaperFile(int which)** for achieving the same purpose (These two new methods are actually not static but it's easier to understand). It know this s***ks, but please try it. Thanks. @divadsn

**Comment by JacobDB** [comment]
Any progress on this? Haven't been able to use Lawnchair on my Pixel 2 for a while now ☹️

**Comment by msfjarvis** [comment]
Just grant the storage permissions and Lawnchair works fine as documented in the issue. I've been using it for a while without any problems.
