### ISSUE TITLE
Don't display google now tab preference if no g-apps installed

### ISSUE THREAD

**Issue by guest4711** [Deletescape-Media/Lawnchair#983]
Even after the update to .1673 LawnChair shows in Behavior the option "Show Google Now Page" and clsims the erong version of Lawnfeed is installed.

On my devices -running Android 7.1.2- are neither any g-apps nor Lawnfeed installed...

So the option should either not been shown or the text should read "no g-apps found on this device".

![](https://i.imgur.com/w2Rq1FM.png)![](https://i.imgur.com/9MgRdmw.png)

**Comment by divadsn** [comment]
It's not possible to have it on CI version...
72f51a92f0f0f4130318d018fb80502b2a1563d7

**Comment by guest4711** [comment]
But  the commit you mentioned is part of this version (see changelog in pic#1). So your commit does not really fix the erroneous message... (I can live with it but I saw some discussions where people did not know what to do...)

**Comment by fonix232** [comment]
@guest4711 by the code it is LITERALLY impossible to have that version. As @divadsn said, it is already fixed and something is amiss on your end.

Let's go into detail. That text is only written if:
- The Lawnfeed check is ran
- Lawnfeed is installed
- Lawnfeed version is lower than defined (currently, v1655 is the minimum)

The Lawnfeed check is only ran if the `ENABLE_LAWNFEED` BuildConfig option is true - but on CI builds, it defaults to false, and cannot be true, hence the check is never actually done.

**Comment by guest4711** [comment]
As you may see in the screenshot it is the last version from https://lawnchairmirror.duckdns.org/latest/ and his commit is shown in the about page...

**Comment by guest4711** [comment]
I just backed up settings. And I find boolean name="pref_showGoogleNowTab" value="false" 
After deleting this line and reimporting this option is reset to "true", the newly saved settings show it appended as "true" to the file.

**Comment by divadsn** [comment]
This is intended to be enabled by default on CI builds, so it's not a bug if you don't have Google app installed.

**Comment by divadsn** [comment]
It should be hidden on the latest Play Store version, so it should be also fixed.
