### ISSUE TITLE
Sync folder icon size with icons

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#985]
This feature request was submitted by **Juan Carlos Sanchez** on Google+. Original post: https://plus.google.com/116734235306203234163/posts/HXiZAbhGHFn

Change the size (and shape if is posible) of the folder to be sync with the size of the icons and the option to remove the shadow of the app name, when it's black it looks blurry.

**Comment by LinuxLlama** [comment]
Closing since Lawnchair V2 has this implemented.

**Comment by divadsn** [comment]
@reC0D3D Boi, it's on v1...

**Comment by LinuxLlama** [comment]
It's not that big of a deal since no one else has complained about it, but
I can reopen if you want.
