### ISSUE TITLE
Hex values for color selector.

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#986]
This feature request was submitted by **David Winnert** on Google+. Original post: https://plus.google.com/113975823219825116029/posts/Y9wJeTuCDDR

Add the ability to type HEX values for icon font colors. My fat man fingers don't work so well with tiny child sliders.

**Comment by nyancrimew** [comment]
Note for devs: This would probable require us to move to another (material if possible) color picker library, or if nothing appropriate can be found write our own library based on something like the one we are currently using
