### ISSUE TITLE
Disable new apps being added to the home screen

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#987]
This feature request was submitted by Juan Carlos Sanchez on Google+. Original post: https://plus.google.com/116734235306203234163/posts/HXiZAbhGHFn

It will be nice to have an option to not to put new apps on the desktop.

I personally would like to see this too. ~reCoded

**Comment by jiccyy** [comment]
Please remove the text shadow on desktop, when using dark text colors and light background the text 
 shadow  looks ugly

**Comment by nyancrimew** [comment]
@jiccyy wrong place to request this. open a new issue if there is none for that already.

**Comment by nyancrimew** [comment]
This feature has been completely removed in Android 8 afaik, before that it is possible to disable this in the PlayStore (as I have also personally done). I have already tried to add a toggle for this to Lawnchair, but somehow I have sofar failed to find the exact location of the reciever :wink:
