### ISSUE TITLE
App shortcut icons glitch out sometimes.

### ISSUE THREAD

**Issue by byytelope** [Deletescape-Media/Lawnchair#991]
## Description

When long pressing an app to reveal shortcuts, the shortcut icons sometimes change into the default Android icon thingy. Seems like lawnchair can't find the icons. This started happening after updating to version 1.1.0.1680.

## Expected Behavior

App shortcuts appear with the correct icons.

## Actual Behavior

App shortcuts appear with Mr. Droid as the icon instead of the correct icons.

## Steps to Reproduce

[Screen cap of issue](https://drive.google.com/file/d/1EqLDGba0G7fupLgiO7lucsKvy2J43wb9/view?usp=drivesdk)
1. Press and hold an icon in the home screen or app drawer or in a folder.
2. Press and hold the icon again when the app shortcuts pop up.
3. Repeat until bug appears.

## Environment

* Device: Samsung Galaxy Tab A 8.0
* Android version: 7.1.1
* Launcher version: 1.1.0.1730
* Rom: Stock Samsung Experience 8.5

**Comment by jise** [comment]
Very well documented and understandable description, but I have not met this yet on both my devices and I cannot reproduce this glitch. I thoroughly tested this on Nexus 5X 8.1.0 and Xiaomi Mi A1 7.1.2 with Lawnchair version 1.1.0.1730. Maybe there is another condition that causes this error on your device. Could you please describe your personal Lawnchair setting, especially where you differ from defaults?

**Comment by byytelope** [comment]
[Here are some screenshots of my settings](https://photos.app.goo.gl/0tLQ90yJhsRK7niC2)

**Comment by jise** [comment]
Oh, your settings differ very much from mine. Maybe I'll try yours and retest, but it'll take some time :)

**Comment by byytelope** [comment]
I just realized it only happens when the icon shape is changed. If it is set to anything except "Do not change" or "None", the icons glitch. None of the other settings appear to have any effect on the bug.

**Comment by jise** [comment]
Exactly, great! You saved my time for retesting with your settings...
So now we have know the culprit :+1: .

I was using None, because I prefer various original icons instead of unified look.
As soon as I changed icons shape to Circle, I could immediately reproduce this glitch on Mi A1 with Nougat, but I cannot reproduce the same on Nexus 5X with Oreo. So maybe this glitch is even somewhat connected with back-porting shortcuts feature from Oreo to Nougat.

**Comment by jise** [comment]
Could you please take a look at overlooked issue #980 in return? :angel:

**Comment by byytelope** [comment]
Top row is fine for me. I checked with both widgets and icons.

**Comment by jise** [comment]
Thank you for your time, but your comment should be placed in issue #980, not here.
Did you performed all the steps to reproduce exactly step by step? It is very important. I edited them to be more precise now. And please take a look to the other two connected issues to get whole picture about this bug. BTW issue #980 is icon shape independent :smile:
