### ISSUE TITLE
Can't delete widgets?

### ISSUE THREAD

**Issue by jaybenjaminlee** [Deletescape-Media/Lawnchair#994]

**Comment by divadsn** [comment]
Move widget to the top part of the screen until the widget gets a red tinted color, then release it.

**Comment by jaybenjaminlee** [comment]
But I can't move it ,  my phone is sony xp，and sys is andriod 7.0

**Comment by guest4711** [comment]
Did you enable "Lock Desktop" in settings -- Behavior?

**Comment by jaybenjaminlee** [comment]
Thx  yes
