### ISSUE TITLE
Long tap stops working after enabling "don't keep activities"

### ISSUE THREAD

**Issue by chilikasha** [Deletescape-Media/Lawnchair#995]
## Expected Behavior
Long tap works

## Actual Behavior
Long tap on desktop or any app icon in menu doesn't work. Nothing happens. Same if disable "don't keep activities". Need to go to Lawnchair settings and stop the app to make long tap work again.

## Steps to Reproduce
1. Go to Settings
2. Open developer options
3. Enable "don't keep activities" option

## Environment
* Device: Nexus 5
* Android version: 6.0.1
* Launcher version: 1.1.0.1730
* Rom: stock

**Comment by divadsn** [comment]
This is due to the current restart method, as the previous was creating FC spam in our console.

**Comment by divadsn** [comment]
Although, it's a duplicate
