### ISSUE TITLE
[Feature Request] Pull down action gesture with two fingers

### ISSUE THREAD

**Issue by jise** [Deletescape-Media/Lawnchair#996]
## Description
Please, could you add Pull down action gesture with two fingers to quickly access Quick Settings Menu from anywhere on the screen?

## Expected Behavior
Pull down action gesture with two fingers quickly access Quick Settings Menu.
Get the idea from this video how it works from notification bar: [Google Nexus 5: Quickly Access Quick Settings Menu With 2 Fingers Pull Down](https://www.youtube.com/watch?v=bjwQRWTxgCQ)

## Actual Behavior
Pull down action gesture with two fingers act now the same way as built in Pull down action with one finger gesture.

## Environment
Nexus 5X 8.1.0 and Xiaomi Mi A1 7.1.2 with Lawnchair version 1.1.0.1730.

**Comment by divadsn** [comment]
Gestures are already wanted here.

**Comment by jise** [comment]
I am sorry I searched for 2 fingers pull down gesture prior posting this, but unsuccessfully.
