### ISSUE TITLE
Navigation bar tint is grey instead of black on 8.x

### ISSUE THREAD

**Issue by LinuxLlama** [Deletescape-Media/Lawnchair#998]
## Description

When on Android 8.0 or 8.1 and the theme is set to black, the navigation bar tint in the app drawer is grey, not black. It makes the app drawer look hideous...

## Expected Behavior

The navigation bar tint should be black.

## Actual Behavior

The navigation bar tint is a grey.

## Screenshot
![screenshot_20171209-082545](https://user-images.githubusercontent.com/29968331/33797321-b7da2608-dcba-11e7-8893-06af2afb9bab.png)

## Steps to Reproduce

1. Be on an Oreo ROM. (8.0 or 8.1)
2. Set the theme to black.
3. Swipe up the app drawer.

## Environment

* Device: Moto G4 Plus
* Android version: 8.1.0
* Launcher version: 1.1.0.1739
* Rom: AOSP

**Comment by eggsgent** [comment]
Hi, was this issue fixed? Issue 790 looks similar: https://github.com/LawnchairLauncher/Lawnchair/issues/790
