### ISSUE TITLE
Tapping home button from Google Feed causes a weird jittery animation.

### ISSUE THREAD

**Issue by debopriyobasu-zz** [Deletescape-Media/Lawnchair#999]
The latest version of Lawnfeed 1.1.0.1742 coupled with the latest version of Lawnchair available from Google Play (1.1.0.1730) causes a weird jittery animation when the home button is pressed.
         
## Description
Supportive video to highlight the issue:
https://photos.app.goo.gl/7Cx84YmVGiIqmMcr1

## Expected Behavior
 When the home button is pressed from the Google Feed, then it should not have a jittery animation. It should smoothly transition to the home screen.

#Actual Behaviour
The home screen makes some quick movements from left to right and then comes to a stop.

## Steps to Reproduce
1. Download and install Lawnchair version 1.1.0.1730
2. Download and install Lawnfeed 1.1.0.1742
3. Swipe to the left of the homescreen, i.e., Google Feed.
4. Press back button.

## Environment
Muzei live wallpaper used.
Device: Motorola Moto G5 Plus
Android version: 7.0 
Security Patch: August 2017.
ROM: Stock ROM.

**Comment by divadsn** [comment]
Duplicate, please use the search function

**Comment by debopriyobasu-zz** [comment]
Sure. I wanted to let you know that this is happening on the latest version.
